### ISSUE TITLE
Error on installing the latest PyMuPDF release for window 64x

### ISSUE THREAD

**Issue by cavaya** [pymupdf/PyMuPDF#1000]
Dear Authors, 

I got following error when try to pip install via anaconda: 
whl: 'utf-8' codec can't decode byte 0x9d in position 1112:

**Comment by JorjMcKie** [comment]
Confirmed.
Unfortunately - and only on Windows, an unsupported character found its way into the description.
I am preparing a new patch version.
Linux and Max version are ok.

**Comment by JorjMcKie** [comment]
Version 1.18.12 is uploaded. Should work, hopefully.
