### ISSUE TITLE
Scrub Produce Zero Page PDF

### ISSUE THREAD

**Issue by juviwhale** [pymupdf/PyMuPDF#1009]
## Describe the bug 

For the provided example PDF (with a valid page count) after `.scrub` the PDF object has zero pages 

## To Reproduce

```
pdf_doc = fitz.open('example_pdf_that_has_no_pages_after_sanitize.pdf')
assert pdf_doc.page_count > 0 # Passes

pdf_doc.scrub()

assert pdf_doc.page_count > 0  # Fails!
pdf_doc.save('cleaned.pdf') # Throws -> ValueError: cannot save with zero pages
```

## Expected behavior (optional)

The scrub method would provide a document that would still be able to be saved.

## Your configuration

3.8.2 (default, Jul 17 2020, 15:47:13) 
[Clang 11.0.3 (clang-1103.0.32.62)] 
 darwin 
 
PyMuPDF 1.18.10: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-03-22 05:51:27.
Built for Python 3.8 on darwin (64-bit).

Installed via `pip install PyMuPDF`

[example_pdf_that_has_no_pages_after_sanitize.pdf](https://github.com/pymupdf/PyMuPDF/files/6307429/example_pdf_that_has_no_pages_after_sanitize.pdf)

**Comment by JorjMcKie** [comment]
Interesting case! Investigating ...
It does not happen after the PDF has been converted to a current PDF version.

**Comment by JorjMcKie** [comment]
Found the problem:
This file has an illegal structure: the catalog xref 13 equals the info xref (metadata).
Therefore, erasing the metadata also deletes the catalog.

**Comment by juviwhale** [comment]
Is there a way to detect this before I attempt to use the scrub method?

**Comment by JorjMcKie** [comment]
I have thought about that too:.
Firstly, it is not specific to the scrub method: anytime the PDF's metadata had been modified via `doc.set_metadata` the same effect would have been caused.
Second, the PDF's trailer does show, that the `/Info` and the `/Root` objects are the same - heaven knows how it was possible to achieve this in the first place. But then it is an extremely old PDF version (1.2) ...

The following code could be used to detect this:

```python
info_xref = doc.xref_get_key(-1, "Info")[1]  # will return "13 0 R"
root_xref = doc.xref_get_key(-1, "Root")[1]  # will also return "13 0 R"
```
So this equality can be detected - at least in this case. The option to also scrub metadata could be switched off and nothing bad happens anymore.
The relatively  new methods even offer an alternative way to remove the `/Info` object:
```python
doc.xref_set_key(-1, "Info", "null")
```
So the garbled object at xref 13 will not be touched ... but of cause it then continues to exist and contains those metadata fragments ...
```postscript
>>> print(doc.xref_object(13))
<<
  /CreationDate (D:20190225214342-06'00')  % /Info item
  /Creator (Image Capture Plus)  % /Info item
  /Metadata 12 0 R  % /Root item
  /ModDate (D:20190225215327-06'00')  % /Info item
  /Pages 11 0 R  % /Root item
  /Producer (Adobe Acrobat Pro DC 15 Paper Capture Plug-in)  % /Info item
  /Type /Catalog  % type /Root
>>
>>> 
```
One might even consider removing all keys from object 13 that do not belong to the `/Root` type. But this is a loooong list:
```python
for key in doc.xref_get_keys(-1):
   if key not in valid_root_keys:
        doc.xref_set_key(13, key, "null")
```
On the other hand: how often do you encounter this?

It is probably better to copy the erroneous PDF in a new one and scrub and save this one once we detect this rare condition:
```python
doc = fitz.open("problem.pdf")
if doc.xref_get_key(-1, "Info") == doc.xref_get_key(-1, "Root"):
    new = fitz.open()
    new.insert_pdf(doc)
    new.set_toc(doc.get_toc(False))  # copy old TOC
    # copy more stuff we want to retain
    ...
    new.scrub()
    doc.close()
    doc = new
else:
    doc.scrub()
```

**Comment by JorjMcKie** [comment]
Maybe a good thing to know for you:
I have reworked the `set_metadata` method such that it will no longer cause this type of issue:
1. If removing the metadata, `doc.set_metadata({})`, then the `/Info` in the PDF trailer is simply removed.
2. If replacing the metadata with new content, then now always a new xref is required - the old xref will not be reused as it happens currently. The xref re-use has automatically also removed the PDF catalog, because it was the same object as `/Info`.

If you are interested, I can make a pre-version wheel, which you can test.

**Comment by JorjMcKie** [comment]
There exist pre-version wheels [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/osx) if you want to try the enhancement mentioned above.
