### ISSUE TITLE
saveIncr and freeing up memory

### ISSUE THREAD

**Issue by MerlijnWajer** [pymupdf/PyMuPDF#1016]
## Describe the bug (mandatory)

Images inserted via `page.insert_image` do not seem to be released from memory after `doc.saveIncr()` is called. A workaround is to use `doc.saveIncr(); doc = fitz.open(<same document>)`.

My use case requires me to insert a lot of images that are potentially really large into a PDF, while trying to keep the memory usage down. I figured that inserting some images, and then doing an incremental save of a PDF document would make that work, but I am struggling to keep the memory usage down, with methods that I think should work.

So far, the method that seems to not use more memory over time is doing incremental saves, and then **reopening the document that was just saved for every single image insert**. This seems sub-optimal to me, but would find it acceptable if this ultimately is the accepted solution.

## To Reproduce (mandatory)

I wrote three different programs that mostly do the same, but are subtly different:

1. Naive baseline, inserting all the images, and then calling `doc.save()`
2. Incremental saving, which I think should use less ram than it currently does
3. Incremental saving, re-opening the *document* every time

### Naive baseline

```python
$ cat mass-image-normal.py
import fitz
import sys
from glob import glob

doc = fitz.open()

for idx, img in enumerate(sorted(glob(sys.argv[2]))):
    print(idx)
    img = open(img, 'rb').read()
    page = doc.new_page()
    page.insert_image(page.rect, stream=img)

doc.save(sys.argv[1])
```

```
$ /usr/bin/time -v python mass-image-normal.py /tmp/out.pdf '../../ram-pdf-issues/sim_new-york-times_1910-05-20_59_19109_jp2/sim_new-york-times_1910-05-20_59_19109_000?.jp2'
[...]
	Maximum resident set size (kbytes): 1401188
```

### Incremental saving

```python
$ cat mass-image.py
import fitz
import sys
from glob import glob

doc = fitz.open()

saved_once = False

for idx, img in enumerate(sorted(glob(sys.argv[2]))):
    print(idx)
    img = open(img, 'rb').read()
    page = doc.new_page()
    page.insert_image(page.rect, stream=img)

    if not saved_once:
        doc.save(sys.argv[1])
        doc = fitz.open(sys.argv[1])
        saved_once = True
    else:
        doc.saveIncr()

doc.saveIncr()
```

```
 $ /usr/bin/time -v python mass-image.py /tmp/out.pdf '../../ram-pdf-issues/sim_new-york-times_1910-05-20_59_19109_jp2/sim_new-york-times_1910-05-20_59_19109_000?.jp2'
[...]
	Maximum resident set size (kbytes): 1378576
```

### Incremental saving, re-opening the *document* every time

```python
$ cat mass-image-hack.py
import fitz
import sys
from glob import glob

doc = fitz.open()

saved_once = False

for idx, img in enumerate(sorted(glob(sys.argv[2]))):
    print(idx)
    img = open(img, 'rb').read()
    page = doc.new_page()
    page.insert_image(page.rect, stream=img)

    if not saved_once:
        doc.save(sys.argv[1])
        doc = fitz.open(sys.argv[1])
        saved_once = True
    else:
        doc.saveIncr()
        doc = fitz.open(sys.argv[1])

doc.saveIncr()
```

```
$ /usr/bin/time -v python mass-image-hack.py /tmp/out.pdf '../../ram-pdf-issues/sim_new-york-times_1910-05-20_59_19109_jp2/sim_new-york-times_1910-05-20_59_19109_000?.jp2'
[...]
	Maximum resident set size (kbytes): 1171884
```

As one can see, method (3) uses significantly less memory than the other two methods, with just 10 (large) images.
The difference in memory usage closely resembled the size of all the images in their compressed form.

Sample images can be downloaded here, but really any image should work (as long as they are not the same): https://archive.org/download/sim_new-york-times_1910-05-20_59_19109/sim_new-york-times_1910-05-20_59_19109_jp2.zip

## Expected behavior (optional)

I would expect `saveIncr` (or really `save(incremental=True, ...)` to not keep all insert images in disk.
I understand that potentially the images are kept in memory to be able to de-duplicate them, but I think that behaviour should be something that can be controlled, at least.

## Your configuration (mandatory)

```
>>> sys.version
'3.8.8 (default, Apr 13 2021, 16:35:22) \n[GCC 9.2.0]'
>>> sys.platform
'linux'
>>> fitz.__doc__
'\nPyMuPDF 1.18.12: Python bindings for the MuPDF 1.18.0 library.\nVersion date: 2021-04-10 04:00:00.\nBuilt for Python 3.8 on linux (64-bit).\n'
```

**Comment by MerlijnWajer** [comment]
This is not a high severity bug/problem for me, but figured it was something worth highlighting.

There is no immediate use-case for making PDFs that contain loads of really large images, but due to the automated nature of where my code is used, these cases do occur.

**Comment by JorjMcKie** [comment]
I think there is a basic misconception here as to what incremental saving means:
**_Every change_** appends modifications made so far to the document's file. The start of the file (including any previous incremental updates) remains unchanged. **_Must remain unchanged_** - by PDF specification ... this is also crucial for legal reasons, especially when dealing with signed documents.

> I would expect saveIncr (or really save(incremental=True, ...) to not keep all insert images in disk.

Don't understand. Why not?

> I understand that potentially the images are kept in memory to be able to de-duplicate them, but I think that behaviour should be something that can be controlled, at least.

This is due to MuPDF's internal caching mechanism. As especially images tend to be large, it tries to keep them in memory.
You can force emptying that buffer via `fitz.TOOLS.store_shrink(percent)` after closing the file.
That's about all what is possible.

**Comment by JorjMcKie** [comment]
Additional comment:
If you happen to insert an image with transparency, then the logic leads to internally generating 2 pixmaps: one for the image itself and one for the mask. Both are then _**stored as uncompressed PNGs!**_
To avoid this, split such an image yourself into 2 images, make compressed streams from both of them and use ``stream=stream, mask=mask`` as ``insert_image`` parameters.
Using Pixmap method ``pillowData`` may be helpful here.

**Comment by MerlijnWajer** [comment]
Thank you for the reply, it indeed looks like I didn't quite understand incremental saving. I will look at `store_shrink` and see how it can help me.

Your comment on the masks, I already provide `stream=imagestream, mask=maskstream` in my current application, where the `imagestream` is JPEG2000 and the `maskstream` is either PNG (which then gets turned into cciitt), or JBIG2. Typically the `maskstream` is JBIG2. Would the JBIG2 still be encoded to a `PNG` image?

In general, my hope is that I can create a PDF with lots of images (say 2GB+ worth of images) without requiring to have **all** the images in ram at a given time. My current understanding given your comments is that my "insert image, save document, re-open document" approach could work, combined with the `store_shrink` operations.

**Comment by JorjMcKie** [comment]
If you use `stream=img_stream, mask=mask_stream`, then the insertion mechanism won't touch the format of any of the two. However, if the base stream is DeviceGRAY, then MuPDF (not PyMuPDF) turns the mask into a ccitt.
Only if you have an image with alpha channel and insert without specifying the `mask=` argument, then insertion logic will split up that image internally - however by generating an internal pixmap for the separated alpha channel, which will then be stored as an uncompressed DeviceGRAY PNG - currently.
If your image (with alpha channel) was given as a pixmap, then even both parts - base image and mask - will be stored as uncompressed PNGs. Which is not necessarily a problem if you use a sufficient garbage option.
But in general, taking full control of the formats of both (maybe by also using Pillow for optimized image binaries), will avoid even that intermediate memory bloat.

> My current understanding given your comments is that my "insert image, save document, re-open document" approach could work, combined with the store_shrink operations.

I would think so, yes. Maybe it will even be sufficient to use `store_shrink` alone, without closing the document.

There was a memory leak bug in versions up to 1.18.7, which I meant to heal in v1.18.8. That again was leading to freeing still needed image areas (causing your other issue).
So if you use pre 1.18.8, you will have memory growth because of the memory leak. This effect counteracts what you want to achieve. So please wait for 1.18.13 - I am going to generate it as a pre-version wheel and let you know.

**Comment by JorjMcKie** [comment]
You can pick up Linux wheels from [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux).

**Comment by MerlijnWajer** [comment]
Great, one more general question/clarification (hope this is the right venue for it):

Regardless of the image cache, I think that the following holds: When calling `page.insert_image` a bunch of times, nothing is written to disk, and thus images are kept in memory until some `save()` method is called, right?

**Comment by JorjMcKie** [comment]
> Regardless of the image cache, I think that the following holds: When calling page.insert_image a bunch of times, nothing is written to disk, and thus images are kept in memory until some save() method is called, right?

Correct.
The image cache's significance / advantage comes into play, when no live objects are referencing an image. Normally, this situation would cause the respective memory area being freed. But as long as a copy lives in the cache, any next access to the image will be very fast.
This internal caching mechanism is one of MuPDF's pivotal performance advantages.

**Comment by MerlijnWajer** [comment]
Thanks, I will test the wheel today.

**Comment by MerlijnWajer** [comment]
I tested it for mask generation, but yet for memory usage. Do you think you could commit the code so I can build PyMuPDF locally? I build using a mupdf that has the jbig2 patches.

**Comment by JorjMcKie** [comment]
The current pre-version 1.18.13 code is in my staging [repo](https://github.com/JorjMcKie/py-mupdf).
This repo is used for triggering wheel generation, so it contains all sources you need.
If you want to replicate the full development cyle, I can also send you a zip of that.
I am just hesitant to upload that to the "official" pymupdf repo as this may cause confusion for everyone else ...

**Comment by MerlijnWajer** [comment]
Ah, I see. I was mostly referring to the `master` branch here, but I agree that might not be for testing. Thanks for that link, I can make this work.

**Comment by JorjMcKie** [comment]
I think we can close the issue
