### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [pymupdf/PyMuPDF#1018]
Problem
---------
On aarch64, pip install PyMuPDF builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install PyMuPDF should download the wheels from pypi

@JorjMcKie, Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by JorjMcKie** [comment]
I already have started creating these - for Python 3.9, there should be one [here](https://github.com/pymupdf/PyMuPDF-wheels/blob/linux-extra/PyMuPDF-1.18.10-cp39-cp39-manylinux2014_aarch64.whl)
It would help if you could try that one.
I have no device where I could do this myself. I also did not bother to generate for the most current version, 1.18.12.

**Comment by JorjMcKie** [comment]
What happened? I saw the PR is gone away?
