### ISSUE TITLE
set_metadata doesn't override/replace the previous metadata xref

### ISSUE THREAD

**Issue by MerlijnWajer** [pymupdf/PyMuPDF#1024]
## Describe the bug (mandatory)

Somewhere since 1.18.2, `setMetadata`/`set_metadata` started not updating the existing metadata xref.

This is a sample from PDFs I produce with 1.18.2:

```
11 0 obj
<<
  /CreationDate (D:20210420155812Z)
  /ModDate (D:20210420155812Z)
  /Producer (Internet Archive PDF 1.1.2; including mupdf and pymupdf/skimage)
>>
endobj
```

This is a sample from PDFs that I make with the latest version:

```
11 0 obj
<<
  /Producer (Archive.org hOCR to PDF renderer \(based on Tesseract\) 0.0.1)
  /CreationDate (D:20210420160056)
  /Title <FEFF004E006F0020007400690074006C0065002000700072006F00760069006400650064>
>>
endobj
[...]
25 0 obj
<<
  /Producer (Internet Archive PDF 1.1.2; including mupdf and pymupdf/skimage)
  /CreationDate (D:20210420160120Z)
  /ModDate (D:20210420160120Z)
>>
endobj
```

The `set_metadata` call looks like this:

```
doc_md = from_pdf.metadata if from_pdf is not None else {}
doc_md['producer'] = PRODUCER
if 'url' in extra_metadata:
    doc_md['keywords'] = extra_metadata['url']
if 'title' in extra_metadata:
    doc_md['title'] = extra_metadata['title']
if 'author' in extra_metadata:
    doc_md['author'] = extra_metadata['author']
if 'creator' in extra_metadata:
    doc_md['creator'] = extra_metadata['creator']
if 'subject' in extra_metadata:
    doc_md['subject'] = extra_metadata['subject']
current_time = 'D:' + datetime.utcnow().strftime('%Y%m%d%H%M%SZ')
if from_pdf is not None:
    doc_md['creationDate'] = from_pdf.metadata['creationDate']
else:
    doc_md['creationDate'] = current_time
doc_md['modDate'] = current_time
# Set PDF basic metadata
to_pdf.set_metadata(doc_md)
```

## To Reproduce (mandatory)

```
$ cat metadata.py
import fitz


doc = fitz.open()
doc.new_page()
md = {'producer': 'Test Producer'}
doc.set_metadata(md)

doc.save('/tmp/metadata.pdf')

newdoc = fitz.open('/tmp/metadata.pdf')
md = {'producer': 'Test Producer 2'}
newdoc.set_metadata(md)
newdoc.saveIncr()
```

## Expected behavior (optional)

The earlier metadata xref should be replaced/updated

## Your configuration (mandatory)

```
>>> fitz.version
('1.18.13', '1.18.0', '20210416153943')
```

**Comment by MerlijnWajer** [comment]
Hm... Looks like `saveIncr` has an effect, somehow. Here's a test script for `1.18.2`:

```
doc = fitz.open()
doc.newPage()
#doc.new_page()
md = {'producer': 'Test Producer'}
doc.setMetadata(md)
#doc.set_metadata(md)

doc.save('/tmp/metadata.pdf')

newdoc = fitz.open('/tmp/metadata.pdf')
md = {'producer': 'Test Producer 2'}
newdoc.setMetadata(md)
#newdoc.set_metadata(md)
newdoc.save('/tmp/metadata2.pdf')
#newdoc.saveIncr()
```

Without saveIncr (Ignore the `(none)` in there, that's an old bug that you fixed since this version):

```
$ grep Producer /tmp/metadata2.pdf
<</Author(none)/CreationDate(none)/Creator(none)/Keywords(none)/ModDate(none)/Producer(Test Producer 2)/Subject(none)/Title(none)>>
```

With saveIncr:

```
$ grep Producer /tmp/metadata.pdf
<</Author(none)/CreationDate(none)/Creator(none)/Keywords(none)/ModDate(none)/Producer(Test Producer)/Subject(none)/Title(none)>>
<</Author(none)/CreationDate(none)/Creator(none)/Keywords(none)/ModDate(none)/Producer(Test Producer 2)/Subject(none)/Title(none)>>
```

**Comment by MerlijnWajer** [comment]
Running the above with the latest version, not using saveIncr still results in duplicate metadata info:

```
$ grep Producer /tmp/metadata2.pdf
<</Producer(Test Producer)>>
<</Producer(Test Producer 2)>>
```

**Comment by JorjMcKie** [comment]
This is happening only in the yet unofficial pre-version 1.18.13.
I built it in on purpose, because there obviously exist PDFs where the `/Info` object is contained in the catalog, so that replacing the metadata will delete the catalog ... rendering the PDF unusable.
Because garbage collection is the only way to get rid of updated old data, the final result will be no different from the logic before.
And for incremental saves this is also true: old and new data physically exist.

**Comment by MerlijnWajer** [comment]
Ok, sounds like I can start adding `garbage=2` then. I assume that's not a very intensive step (making the xref table more compact)? Feel free to close. Thanks.

**Comment by JorjMcKie** [comment]
> Ok, sounds like I can start adding garbage=2 then. I assume that's not a very intensive step (making the xref table more compact)?

No wait. Actually you are right: I shouldn't change option requirements if at all avoidable. Who knows what people are relying on.
Garbage option 2 means compact xref table **_plus_** remove unreferenced objects. So this will get rid of empty xref table entries, join any disparate xref table segments, and renumber all objects.

I am testing a changed logic, which assign no new `/Info` xref. It should still circumvent those PDF errors. More complicated, but should work. So you need not expect changes here.

**Comment by JorjMcKie** [comment]
> Ok, sounds like I can start adding garbage=2 then. I assume that's not a very intensive step (making the xref table more compact)?

No wait. Actually you are right: I shouldn't change option requirements if at all avoidable. Who knows what people are relying on.
Garbage option 2 means compact xref table **_plus_** remove unreferenced objects. So this will get rid of empty xref table entries, join any disparate xref table segments, and renumber all objects.

I am testing a changed logic, which assign no new `/Info` xref. It should still circumvent those PDF errors. More complicated, but should work. So you need not expect changes here.

**Comment by JorjMcKie** [comment]
> Ok, sounds like I can start adding garbage=2 then. I assume that's not a very intensive step (making the xref table more compact)?

No wait. Actually you are right: I shouldn't change option requirements if at all avoidable. Who knows what people are relying on.
Garbage option 2 means compact xref table **_plus_** remove unreferenced objects. So this will get rid of empty xref table entries, join any disparate xref table segments, and renumber all objects.

I am testing a changed logic, which assign no new `/Info` xref. It should still circumvent those PDF errors. More complicated, but should work. So you need not expect changes here.

**Comment by JorjMcKie** [comment]
this request will be implemented in the coming version 1.18.13

**Comment by MerlijnWajer** [comment]
Thanks. If it's not too much work, could you push the code that fixes this either to the wheels repository or to master, so that I can test it and build my own version? Sorry to be a bother. :)

**Comment by JorjMcKie** [comment]
Ok, no problem.
I'll go by and make wheels and let you know when done.

**Comment by JorjMcKie** [comment]
The Linux wheels are [done](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux).

**Comment by MerlijnWajer** [comment]
Thanks. I'm still a bit lost on where the updated source file (`fitz.i`) can be found. It's not in the PyMuPDF master, nor in your py-mupdf repository. I need to make a custom PyMuPDF build because I have a patched MuPDF, so I cannot use your wheels for my production purposes since they contain an unpatched MuPDF. Any hint on where to find the files I need to build PyMuPDF myself with the fixes from last week?

**Comment by JorjMcKie** [comment]
I just made a branch: https://github.com/pymupdf/PyMuPDF/tree/pre-1.18.13
which I hope has what what you need ... 😎

**Comment by MerlijnWajer** [comment]
Yes, thanks!
