### ISSUE TITLE
When I converted the PDF to an image, the text was lost

### ISSUE THREAD

**Issue by Blue-Skie** [pymupdf/PyMuPDF#1025]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When I converted the PDF to an image, the text was lost

## To Reproduce (mandatory)
```
import fitz
import os

def pdf_to_img(pdf_path, save_path):
    pdf_doc = fitz.open(pdf_path)
    for page in range(pdf_doc.page_count):
        page_doc = pdf_doc[page]
        zoom_x = 5.0
        zoom_y = 5.0
        matrix = fitz.Matrix(zoom_x, zoom_y)
        pix = page_doc.get_pixmap(matrix=matrix)
        pix.writeImage(os.path.join(save_path, f'{page + 1}.jpg'))
    pdf_doc.close()

pdf_to_img("test.pdf","img")
```

## Expected behavior (optional)
All text should be converted into pictures together with pdf, but all text in the converted picture is lost

## Screenshots (optional)
pdf:
![image](https://user-images.githubusercontent.com/45866651/115507272-7cfe9380-a2ae-11eb-9ee1-aaff8fef7b56.png)
picture:
![image](https://user-images.githubusercontent.com/45866651/115507356-97387180-a2ae-11eb-9cf8-43db9ddb397d.png)

## Your configuration (mandatory)
PyMuPDF: 1.18.12
Python: 3.8.9 on win32(64-bit)

## Additional context (optional)
pdf file:https://drive.google.com/file/d/1UEgHLfC7lVTfEHJmZcLbH1aBg6Wpte1m/view?usp=sharing

**Comment by JorjMcKie** [comment]
None of the fonts used in this file are embedded. So correctly rendering the page with any PDF viewer software depends on whether the selected viewer supports the fonts.
**_None_** (!!!) of the viewers I am using can show **_all_** of the text: Adobe Acrobat, SumatraPDF, MuPDF, Foxit Read, PDF-XChange, evince (Linux). Every single one is missing support for at least one of the fonts ("n/a" means: font file not embedded):
```python
>>> pprint(doc.get_page_fonts(0))
[(4, 'n/a', 'TrueType', 'ArialMT', 'F1', 'WinAnsiEncoding'),
 (9, 'n/a', 'Type0', 'SimSun', 'F2', 'Identity-H'),
 (14, 'n/a', 'Type0', 'SimHei', 'F3', 'Identity-H'),
 (17, 'n/a', 'TrueType', 'SimSun', 'F4', 'WinAnsiEncoding'),
 (22, 'n/a', 'TrueType', 'SimHei', 'F5', 'WinAnsiEncoding'),
 (26, 'n/a', 'TrueType', 'Swiss721BT-RomanExtended', 'F6', 'WinAnsiEncoding')]
>>> 
```
So all you can do is recreate the file with the fonts **_embedded_**.  Or use the font replacement tool to embed some font supported by PyMuPDF. This tool is explained [here.](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/font-replacement)

**Comment by JorjMcKie** [comment]
Here is a version where all the fonts in the file have been replaced with the "Droid Sans Fallback Regular" font. This would not cause your type of problem.
[test-new.pdf](https://github.com/pymupdf/PyMuPDF/files/6350380/test-new.pdf)

**Comment by Blue-Skie** [comment]
Thank you very much! 
I am trying to run repl-font.py and got an error
python repl-font.py test.pdf
![image](https://user-images.githubusercontent.com/45866651/115546000-193c9080-a2d7-11eb-8574-f5da344763ff.png)

**Comment by JorjMcKie** [comment]
Yes, I have had that too and fixed it a minute ago. Please download again .

**Comment by JorjMcKie** [comment]
[test.pdf-fontnames.json.zip](https://github.com/pymupdf/PyMuPDF/files/6350424/test.pdf-fontnames.json.zip)

This is the JSON file I used. You can run repl-font.py directly with it (without first running repl-fontnames.py - where the error occurs).

**Comment by Blue-Skie** [comment]
OK, I will try it. Thanks a lot
