### ISSUE TITLE
are there pymupdf wheel files based on python35 and architecture like aarch64 or mips64

### ISSUE THREAD

**Issue by hellobw2000** [pymupdf/PyMuPDF#1026]
I need pymupdf aarch64 wheels and mips64el wheels based on python35, but I have no enviroment to build them from source code, Is there anyone has built the wheel? please share me. thank you!

**Comment by JorjMcKie** [comment]
Python 3.5 is not supported anymore. This is a zombie Python since October 2020 and also has gone out of PIP-support.

**Comment by JorjMcKie** [comment]
Missing Python 3.5 supports even applies to generating from source code: I am using CPython features not supported before version 3.6.

As for alternative architectures aarch64 etc. for Python 3.6+, I am in development. There exists an aarch64 wheel for Python3.9 already [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux-extra).
