### ISSUE TITLE
Tibetan rendering amiss despite attempts with multiple fonts

### ISSUE THREAD

**Issue by julkamny** [pymupdf/PyMuPDF#1028]
Hello,

First of all thanks for this amazing library, it has helped me achieve things I believed far beyond my ken. I am attempting to output a PDF which contains Tibetan words.  For detailed information about the script used to write this language, please take a look at : https://docs.microsoft.com/en-us/typography/script-development/tibetan#examples-of-tibetan. Your help would be greatly appreciated, I have spent many hours crafting my program, it works well and could have interesting educational benefits, this font issue really bogs me down... 🙏🏿

#### The issue

doc[0].insertTextbox(rect, "རྒྱསྒྲ", fontsize = fontsize, fontname="jomolhari", fontfile = jomolhari_font_path) produces the attached picture, whereas it should produce well, what hopefully you see on your screen : a neatly arranged stack of ར + ག + ཡ (the form of this last consonant changes when it is placed at the bottom of a stack) and a neatly arranged stack of ས + ག + ར. Even གྲ is not properly displayed.

![Capture d’écran 2021-04-21 à 17 38 52](https://user-images.githubusercontent.com/70329091/115582137-eee3d680-a2c8-11eb-9214-006d675ee8b2.png)

#### My attempts

- Multiple fonts, at least half a dozen, NotoSansTibetan, Yagpo, TibetanMachineUnicodeFont. The one that seems to work best is Jomolhari.
- I run into the very same issue with Reportlab. This may hint at a problem on my side ? Or a general problem with Tibetan not tied to MuPDF specifically ?

#### My configuration

- MacBook Air, High Sierra 10.13.6
- PyMuPDF 1.18.12: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-04-10 04:00:00.
Built for Python 3.8 on darwin (64-bit).

**Comment by JorjMcKie** [comment]
This is not a bug - at best a feature you are missing.
let me convert this to an item in topic "Discussions".
