### ISSUE TITLE
Installation fails on Linux

### ISSUE THREAD

**Issue by fladd** [pymupdf/PyMuPDF#1031]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
On Linux (Antix 19.3 64bit), installation with PIP fails due to trying to build a wheel rather than using the pre-built wheels provided on PyPi.

## To Reproduce (mandatory)
`pip3 install PyMuPDF`

## Expected behavior (optional)
I except PIP to install the pre-built manylinux wheel (PyMuPDF-1.18.12-cp37-cp37m-manylinux2010_x86_64.whl)

## Screenshots (optional)
<img width="724" alt="image" src="https://user-images.githubusercontent.com/2971539/115960411-905d6900-a511-11eb-9aa2-ba1b938f71db.png">

<img width="725" alt="image" src="https://user-images.githubusercontent.com/2971539/115960418-9f441b80-a511-11eb-87a4-9c4faf26d964.png">

## Your configuration (mandatory)
 - Antix 19.3, 64 bit
 - Python 3.7.3, 64 bit
 - PyMuPDF installation attempt via pip (`pip3 install PyMuPDF`)

**Comment by DenisSouth** [comment]
https://stackoverflow.com/questions/26053982/

Try to install additional libraries for Python development, I had same problem with other library before

**Comment by JorjMcKie** [comment]
* Have you ever successfully installed any other manylinux2010 package?
* Do you use the most current PIP?
* What is the PIP message if you download the wheel and then execute locally `python3.7 -m pip install PyMuPDF-1.18.12-cp37-cp37m-manylinux2010_x86_64.whl`?

**Comment by fladd** [comment]
>     * Have you ever successfully installed any other manylinux2010 package?
Yes
>     * Do you use the most current PIP?
I did not
>     * What is the PIP message if you download the wheel and then execute locally `python3.7 -m pip install PyMuPDF-1.18.12-cp37-cp37m-manylinux2010_x86_64.whl`?
It complaint about this not being a supported wheel for this platform

Eventually, I simply had to update PIP.

Cheers!

**Comment by JorjMcKie** [comment]
So it worked after upgrading PIP?
Well, if so, that's good. What I don't understand then, how the platform tag **_manylinux2010_** could have worked with the old PIP and other packages 🤔.

**Comment by fladd** [comment]
> 
> 
> So it worked after upgrading PIP?
Yes

> Well, if so, that's good. What I don't understand then, how the platform tag **_manylinux2010_** could have worked with the old PIP and other packages 🤔.
Different venv with apparently updated PIP :-)

**Comment by JorjMcKie** [comment]
> Different venv with apparently updated PIP :-)

Uff, thanks, my world is in order again 😉
