### ISSUE TITLE
Getting incorrect bounding box information

### ISSUE THREAD

**Issue by zweissman** [pymupdf/PyMuPDF#1033]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I am trying to get the bounding boxes of some images and they are coming back as the bbox for the entire page.

## To Reproduce (mandatory)
PDF can be found https://pr-ie-training.s3.amazonaws.com/JP2000243775A.pdf
```
doc = fitz.open("JP2000243775A.pdf")
for page_number in range(doc.page_count):
    for page_image in doc.getPageImageList(page_number, full=True):
        bbox = doc[page_number].getImageBbox(page_image)
        print(f"{page_number} x{page_image[0]}:\t{bbox}")
```
The output is:
```
0 x1320:        Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)
0 x1326:        Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)       WRONG
0 x1322:        Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)       WRONG
1 x9:   Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)
2 x13:  Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)
3 x28:  Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)
4 x44:  Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)
5 x72:  Rect(0.0, -0.01995849609375, 597.8499755859375, 844.0800170898438)
5 x74:  Rect(0.0, -0.01995849609375, 597.8499755859375, 844.0800170898438)       WRONG
5 x68:  Rect(0.0, -0.01995849609375, 597.8499755859375, 844.0800170898438)       WRONG
5 x76:  Rect(0.0, -0.01995849609375, 597.8499755859375, 844.0800170898438)       WRONG
5 x63:  Rect(0.0, -0.01995849609375, 597.8499755859375, 844.0800170898438)       WRONG
5 x77:  Rect(0.0, -0.01995849609375, 597.8499755859375, 844.0800170898438)       WRONG
6 x105: Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)
6 x99:  Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)       WRONG
```
## Expected behavior (optional)
These bboxes look like that of the page, not the image.

The whole reason for wanting the bbox is to see where x1, y1 to try and determine if it is a full page image or it is a cropped already. I want the cropped ones (xref 1326 and 1322 on page 1) and ignore the full page (xref 1320 on page 1). Do something like x1 <= 20 and y1 <= 20, then ignore.

From my minimal knowledge of pdf structure. I can open the pdf in a text editor and search for `1326 0 R` and find its hierarchy:
```
1326 0 obj
<</Subtype/Image/Type/XObject/Width 544/Height 740/Interpolate true/ColorSpace/DeviceGray/BitsPerComponent 1/Filter[/JBIG2Decode]
/DecodeParms[null]/Length 1756>>
stream
 -- stream removed for simplicity --
endstream
endobj

1321 0 obj
<</Im0 1326 0 R>>
endobj

1324 0 obj
<</ProcSet[/PDF/Text/ImageC/ImageB]/XObject 1321 0 R>>
endobj

1315 0 obj
<</Type/XObject/Subtype/Form/BBox[0 0 95.1 129.3]/Resources 1324 0 R/Filter/FlateDecode/Length 36>>
stream
xœ+T°4Õ3T0 BC#K=c0+9Wß3×@Á%_!P s‰%
endstream

1318 0 obj
<</Fg 1291 0 R/P0 1315 0 R/P1 1317 0 R>>
endobj

1294 0 obj
<</ProcSet[/PDF/Text/ImageC/ImageB]/Font 1272 0 R/ExtGState 1285 0 R/XObject 1318 0 R>>
endobj

1262 0 obj
<</Type/Page/Resources 1294 0 R/Parent 1130 0 R/StructParents 0/Contents[1316 0 R]/MediaBox[0 -0.019 594.85 841.98]>>
endobj
```
x1262 looks to be the page and that bbox matches what came back from the page.getImageBbox() call. The PDF is displaying correctly, so somewhere in the pdf should contain the correct bbox. But that is about as far as I can get.

Any thoughts on how to get the actual placement of this image on the page?

PDFs with the same issue:
- https://pr-ie-training.s3.amazonaws.com/JP2000238366A.pdf
- https://pr-ie-training.s3.amazonaws.com/JP2000245818A.pdf

Working PDF example:
- https://pr-ie-training.s3.amazonaws.com/JP2018523541A.pdf 

## Your configuration (mandatory)
 - Operating system: Windows 10 Enterprise v1909
 - Python version: 3.7
 - PyMuPDF version: 1.18.12 installed from pip

**Comment by JorjMcKie** [comment]
The reason for this unpleasant experience is that it is (1) a scanned PDF (so the full pages always consist of an image), and (2) that all images are not directly invoked by the page command source, but are hidden in some so-called Form XObject.
When this is the case, the items of `doc.get_page_images(pno, True)` have the xref of the Form XObject as their last entry. Images invoked by the page itself have a zero there.
This multi-level / recursive invocation of image of course causes multiple coordinate transformations - which obviously are not detected and working as they should in each case.
This is driving me a bit buts at the moment, because the concrete situation can be arbitrarily complex ... or different each time.

For you as a circumvention, I can offer this:
1. make a list `doc.get_page_images(pno, True)` (same as `page.get_images(True)`).
2. make a list `page.get_image_info()`. This is new in v1.18.12. Each item is a dict describing one image, including a bbox, which is **_guaranteed_** to be correct. The only missing information is the image xref (which is inevitably so). But you can try to match between an item here and one in the other list by comparing the width / height / bpc / colorspace.

And maybe you do not need the xref at all.

**Comment by zweissman** [comment]
Thank you, 

page.get_image_info() does look to get the bboxes correctly in this case. PDFs are way more complicated than they need to be and am glad for libraries like this and people like you that understand what is happening under the hood so the rest of us don't need to :)

I believe that I am going to need the xref in order to get / save the images via either

`image = doc.extractImage(xref)`
or
`pixmap = fitz.Pixmap(doc, xref)`

unless you have some other suggestion to get that.

I think that I was able to incorporate the merge code as you had suggested.
```
    def get_page_image_merge(doc, page_number):
        page_image_list = doc.get_page_images(page_number, full=True)
        if len(page_image_list ) == 0:
            return []

        # Sorting by xref
        page_image_list.sort(key=lambda x: (x[0]))
        page_image_dicts = doc[page_number].get_image_info()
        merged = []

        for page_index in range(len(page_image_dicts)):
            found_index_list = get_page_image_match(page_image_dicts[page_index], page_image_list)    
            if len(found_index_list) > 1:
                # Going to try and see if the sorted list of page_image_match are in the same order. If we always find one match, then we can assume we are good.
                index_match = get_page_image_match(page_image_dicts[page_index], page_image_list[page_index:page_index + 1])
                if len(index_match) == 1:
                    # We found a match, so far, so good!
                    found_image_index = page_index
                else:
                    raise Exception(f"Found {len(found_index_list)} matching images on page {page_number} index {page_index} of {doc}. Need special handling to determine what to do.")
            elif len(found_index_list) == 0:
                raise Exception(f"Found 0 matching images on page {page_number} index {page_index} of {doc}. Need special handling to determine what to do.")
            else:
                found_image_index = found_index_list[0]

            page_image_dict = page_image_dicts[page_index]
            
            xref, smask, width, height, bpc, colorspace, alt_colorspace, name, filter, referencer = page_image_list[found_image_index]
            # Adding xref in twice, the underscore makes it show first in the debugger
            page_image_dict['_xref'] = xref
            page_image_dict['xref'] = xref
            page_image_dict['smask'] = smask
            page_image_dict['alt_cs-name'] = alt_colorspace
            page_image_dict['name'] = name
            page_image_dict['filter'] = filter
            page_image_dict['referencer'] = referencer
            
            merged.append(page_image_dict)

        return merged

    def get_page_image_match(page_image_source, page_image_list):
        found_index_list = []

        for page_index, page_image in enumerate(page_image_list):
            width, height, bpc, cs_name = page_image[2:6]
            if (page_image_source['width'] == width and
                page_image_source['height'] == height and
                page_image_source['bpc'] == bpc and
                (page_image_source['cs-name'] == cs_name or (page_image_source['cs-name'] == 'None' and cs_name == '') or (cs_name == "Indexed"))):
#TODO0: figure this Indexed thing out
                if cs_name == "Indexed":
                    print(f"CS NAME {cs_name} -- {page_image_source['cs-name']}")
                found_index_list.append(page_index)

        return found_index_list

```
Outstanding issues:

1. There are three possibilities when looking for a match. You get 1 match, 0 matches, or more than 1 match. 1 Match is great. 0 matches should probably not happen. And more than one match is the issue and I am assuming the reason that this code does not exist already in your codebase. How to handle it when there are more than one match. For now, I am sorting the xrefs in numerical order and so far, they are matching in the same order. But I have to guess that is not always going to be the case. I didn't see anything else to use to match on, so if this doesn't work, I will just have to skip this PDF.

2. In get_page_image_match, when comparing the cs-name from `page_image_list = doc.get_page_images()` to `page_image_source = doc[page_number].get_image_info()`, it looks like there is some processing happening in there that is converting things.

Sometimes, they match fine. Sometimes, the get_image_info()['cs-name'] == 'None' (the string not None the absence of assignment). And sometimes I get `page_image_source['cs-name'] == 'Indexed(1,DeviceRGB)'` and `cs_name == 'Indexed'`
What is that? I tried looking in the PyMuPDF code and didn't see any class called Indexed.

Example PDF https://pr-ie-training.s3.amazonaws.com/KR20070097170A.pdf

**Comment by JorjMcKie** [comment]
Thanks for your understanding.
Actually, there are solutions avoiding those matches altogether:
1. do not use `page.get_image_info()`, but instead a variant of `page.get_text()`, which is based on the same set of MuPDF functions. Meaning the bboxes are always correct, plus you also have the image binary:
```python
images = [b for b in page.get_text("dict")["blocks"] for b["type"] == 1]
```
Every b in that list comprehension is a dictionary, which looks like one of `page.get_image_info()` but has a key `b["image"]` containing the image binary. Still no xref, of course.

2. Convert the PDF to a new (temporary / intermediate) PDF, page ny page, dissolving all Form XObjects and making images being invoked by the (intermediate) page directly. Then use the `page.get_image_bbox()` like usual, which now will work without flawlessly, too. There are other new issues coming up, though:
   - your PDFs are scanned and OCR-ed, which involves using fonts, that MuPDF cannot deal with when doing PDF-to-PDF conversion. So the OCR text layer has to be (temporarily) removed.
   - The conversion also re-numbers all xrefs.
Here is the output of what happens to the first page of your example file:

```
# pprint(page.get_images(True)) of the old page
[(1246, 0, 3404, 4818, 1, 'DeviceGray', '', 'Im1', 'JBIG2Decode', 1261),
 (1248, 0, 544, 740, 1, 'DeviceGray', '', 'Im1', 'JBIG2Decode', 1262),
 (1247, 0, 674, 746, 1, 'DeviceGray', '', 'Im1', 'JBIG2Decode', 1263)]

# pprint(page.get_images(True)) of the new page
[(3, 0, 3404, 4818, 1, 'DeviceGray', '', 'Img3', 'CCITTFaxDecode', 0),
 (4, 0, 544, 740, 1, 'DeviceGray', '', 'Img4', 'CCITTFaxDecode', 0),
 (5, 0, 674, 746, 1, 'DeviceGray', '', 'Img5', 'CCITTFaxDecode', 0)]

# these are the bboxes delivered by page.get_image_bbox()
Rect(0.0, -0.02001953125, 594.8499755859375, 841.97998046875)
Rect(310.3500061035156, 508.91998291015625, 405.45001220703125, 638.219970703125)
Rect(410.70001220703125, 509.6180114746094, 528.4500122070312, 639.968017578125)
```

**Comment by JorjMcKie** [comment]
[clean.zip](https://github.com/pymupdf/PyMuPDF/files/6382745/clean.zip)
This is the script producing the previous output.

**Comment by zweissman** [comment]
Just went through and updated my code and all my test cases are looking good. I went with option 1. All I was looking for were the bounding boxes and the actual image data. This fits the bill perfectly and very clean and fast.

This is just what I was looking for. Thank you very much for your quick responses and for making and maintaining such a great library!

**Comment by JorjMcKie** [comment]
Thank you very much for your nice feedback!
Your inquiry made me look for stabilizing the never-ending issues in this corner. And - heureka! - found a way (embarrasingly easy):

The next version will add a bool parameter `xrefs` to `page.get_image_info()`. When true, each image information of that list will have a new key `xref`. If positive, then a match with one of the page's items in `page.get_images()` was found.
With this backreference, all troubles around Form XObjects are out of the way.

**Comment by zweissman** [comment]
Sounds great. I don't need the xref for what I am doing but having the xref (or some other unique-ish) value would be helpful with debugging.
