### ISSUE TITLE
Pixmap methods only have camelCase

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#1041]
I was doing a pass cleaning up fitz.camelCase to fitz.snake_case.

I noticed the `Pixmap` methods only have camelCase, e.g. `writeImage`, `writePNG`, `get*` and `set*`.

Is intentional or just didn't get to those ones yet?

**Comment by JorjMcKie** [comment]
That's correct - I am just not yet done with it 😒

**Comment by JorjMcKie** [comment]
The nexr version, 1.18.13, will have that changed, finally. It won't always be just a foreseeable insertion of changing upper case to lower case with a prefixed underscore:
I am also trying to find more consistent names across classes: `Pixmap.writeImage` / `Pixmap.writePNG` ==> `Pixmap.save`, `Pixmap.getPNGData`  ==> `Pixmap.tobytes`, `Pixmap.pillowWrite` ==> `Pixmap.pil_save`, `Pixmap.pillowData` ==> `Pixmap.pil_tobytes`, and similar.

There are also leftovers in the `Page` class: `Page.addXYZAnnot()`. That will become `page.add_xyz_annot()`.

**Comment by JorjMcKie** [comment]
Fixed in v1.18.13, which was just published.
