### ISSUE TITLE
'Pixmap' object has no attribute 'getPNGdata'

### ISSUE THREAD

**Issue by iiLaurens** [pymupdf/PyMuPDF#1043]
In version 1.18.13 it seems that getPNG**d**ata() function no longer exists, and is replaced by the function getPNG**D**ata(). Was this intentional? This can break quite a bit of existing code.

**Comment by JorjMcKie** [comment]
oops - sorry, I meant to define it as a deprecated name.
At the moment please use `pixmap.tobytes("png")`, and similarly `pixmap.save(...)` instead of `writePNG`.
Ahh - now I see: I only defined an alias for `getPNGData` (upper case "D").
