### ISSUE TITLE
Scanned 0 degree orientation pdf, page.rotation is giving 270

### ISSUE THREAD

**Issue by sravan-tadiparthi** [pymupdf/PyMuPDF#1045]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Scanned 0 degree orientation pdf, page.rotation is giving 270

## To Reproduce (mandatory)
Take any scanned pdf and parse with pymupdf, check page.rotation value for any page

## Expected behavior (optional)
As page is 0 degree orientation, page.rotation should give value as '0'

## Screenshots (optional)
Attached screenshot of page.rotation & pdf page
![rotation_screenshot](https://user-images.githubusercontent.com/79854145/117647815-0de6d180-b1c0-11eb-9af7-731208b92d9d.PNG)
[Jurong2_Original.pdf](https://github.com/pymupdf/PyMuPDF/files/6451449/Jurong2_Original.pdf)

## Your configuration (mandatory)
 - MS Windows 10
 - Python version 3.6
 - PyMuPDF version - 1.18.6

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
You are wrong: the page rotation **_is 270 degrees_**.

**Comment by JorjMcKie** [comment]
> able to extract text from scanned pdf using pymupdf?

No, not yet. I will include this MuPDF feature in the next PyMuPDF version (1.19,0).
You must use an OCR tool - best take Tesseract, because MuPDF contains an integration for this.

**Comment by JorjMcKie** [comment]
There is a Python package, ocrmypdf, which best runs on Linux ( I am using it in the WSL terminal on Windows).
```
sudo apt update
sudo apt upgrade
sudo apt install ocrmypdf
ocrmypdf Jurong2_Original.pdf ocred.pdf
```
Just tested it. Works fine with this file.
