### ISSUE TITLE
insert_image wrongly caches images when the mask is different, but image stream is the same as previous insert

### ISSUE THREAD

**Issue by MerlijnWajer** [pymupdf/PyMuPDF#1053]
## Describe the bug (mandatory)

`page.insert_image(..., stream=foo, mask=bar)` seems to cache the results even if the mask is different (at a second insert).
This is evident from the example below, where the two pages *should* contain different images, but they actually do not.

The cache being to blame is entirely a guess on my side.

## To Reproduce (mandatory)

```
import fitz

doc = fitz.open()


page = doc.new_page()
bg_contents = open('bgdiubkcdl.jp2', 'rb').read()
fg_contents = open('fgzvps8nir.jp2', 'rb').read()
mask_contents = open('mask8hq8yr37.png', 'rb').read()
page.insert_image(page.rect, stream=bg_contents, mask=None,
        overlay=False)
page.insert_image(page.rect, stream=fg_contents, mask=mask_contents,
        overlay=True)

page = doc.new_page()
bg_contents = open('bgoewrpg8w.jp2', 'rb').read()
fg_contents = open('fgio4gli63.jp2', 'rb').read()
mask_contents = open('maskk7dbuux0.png', 'rb').read()
page.insert_image(page.rect, stream=bg_contents, mask=None,
        overlay=False)
page.insert_image(page.rect, stream=fg_contents, mask=mask_contents,
        overlay=True)

doc.save('/tmp/bug.pdf')
```

Image for the above script are here: https://archive.org/~merlijn/pymupdf-insert-cache/

## Expected behavior (optional)

The pages should have different images.

## Screenshots (optional)

See PDF here:

https://archive.org/~merlijn/pymupdf-insert-cache/bug.pdf

## Your configuration (mandatory)

```
>>> print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.8.9 (default, May 16 2021, 12:11:24)
[GCC 9.2.0]
 linux

PyMuPDF 1.18.13: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-05-05 06:32:22.
Built for Python 3.8 on linux (64-bit).


## Additional context (optional)

Initially found by figuring out why this PDF exhibits the problem: https://archive.org/download/tbl105kRnd/tbl105kRnd.pdf

**Comment by JorjMcKie** [comment]
Yes, indeed I compute the hash solely on the base image and ignore the mask.
Are you telling me it happens that the same base image can occur with different masks?
If yes, I could of compute the hash based on the concatenated streams ...

**Comment by MerlijnWajer** [comment]
Yes, that is indeed what is happening, I believe.

**Comment by JorjMcKie** [comment]
Currently I will always compute different hashes if an image comes via pixmap as well as via file/stream: this will always be treated as different things - and this cannot be changed either if I want to keep the current level of performance.

**Comment by JorjMcKie** [comment]
> Yes, that is indeed what is happening, I believe.

Ok, I will change this then - no real big deal.

**Comment by JorjMcKie** [comment]
The wheel generation with that fix is underway - will be pre-version 1.18.14.
Linux should be ready in 15 minutes or so.

**Comment by JorjMcKie** [comment]
Note that this pre-version 1.18.14 issues deprecation warnings. This will be switched off in the final version. The deprecation messages will be activated for a future version 1.19.0.

**Comment by MerlijnWajer** [comment]
Thanks, I will give it a test run, I'll report back today.

**Comment by MerlijnWajer** [comment]
I can confirm that the problem is resolved in those wheels, thanks!

**Comment by JorjMcKie** [comment]
Thnks for testing this!

**Comment by JorjMcKie** [comment]
fixed by official new version
