### ISSUE TITLE
Can we highlight block of text as single highlight?

### ISSUE THREAD

**Issue by nagamchinna** [pymupdf/PyMuPDF#1054]
I'm trying to highlight multiple lines of text as single highlight by using addHighlightAnnot, but it's highlighting each line separately. 

For Example

Line No 1
Line No 2
Line No 3
I needed to get single rect value, but it's providing rect values for each line.

Is there is any way to get single rect value for all 3 lines.

**Comment by JorjMcKie** [comment]
First of all:
Why do you classify this as a bug? No to speak of the fact, that **_all_** mandatory information for a bug submission are missing ...
So I am taking the liberty to
1. reclassify this as a question
2. move your question to the "Discussions" tab using category "Looking for help". More responses can be found there.
