### ISSUE TITLE
AttributeError: 'Document' object has no attribute '_getXrefLength'

### ISSUE THREAD

**Issue by lx-rookie** [pymupdf/PyMuPDF#1056]
_**Please provide all mandatory information!**_

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

## Additional context (optional)

when I user it in windows:
a = fitz.open(file)
print(a)
I can get 

![image](https://user-images.githubusercontent.com/54061448/118772250-1ae97c00-b8b6-11eb-9d6e-7ac1a2ccf390.png)

but when I run in linux
I get 

![image](https://user-images.githubusercontent.com/54061448/118772306-30f73c80-b8b6-11eb-8728-ba34a9e03527.png)

**Comment by JorjMcKie** [comment]
Cannot reproduce - not clear which code snippts you used. The 2 lines
```python
a = fitz.open(file)
print(a)
```
work the same way everywhere.
```python
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import fitz
In [2]: doc = fitz.open("v110-changes.pdf")
In [3]: print(doc)
Document('v110-changes.pdf')
In [4]:
```
```python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.21.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import fitz
In [2]: doc = fitz.open("v110-changes.pdf")
In [3]: print(doc)
Document('v110-changes.pdf')
In [4]:
```

Also missing are the resp. PyMuPDF versions on both systems.

**Comment by JorjMcKie** [comment]
Please provide the requested information.
Need more help?

**Comment by JorjMcKie** [comment]
Closed for lack of feedeback.
