### ISSUE TITLE
AttributeError: 'Page' object has no attribute '_graft_id'

### ISSUE THREAD

**Issue by jeanmonet** [pymupdf/PyMuPDF#1057]
## Describe the bug (mandatory)

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-6a77c9cc6c89> in <module>
pdf.py in pdftotext_from_mupdf(doc, page_num)
     66     """
     67     with fitz.Document() as tmp:
---> 68         tmp.insert_pdf(doc, page_num, page_num)
     69         return pdftotext.PDF(io.BytesIO(tmp.tobytes()))[0]
     70 

/opt/miniconda3/envs/nlp/lib/python3.9/site-packages/fitz/fitz.py in insert_pdf(self, docsrc, from_page, to_page, start_at, rotate, links, annots, show_progress, final, _gmap)
   4324         if self.is_closed or self.is_encrypted:
   4325             raise ValueError("document closed or encrypted")
-> 4326         if self._graft_id == docsrc._graft_id:
   4327             raise ValueError("source and target cannot be same object")
   4328         sa = start_at

AttributeError: 'Page' object has no attribute '_graft_id'
```

## To Reproduce (mandatory)

Trying to create new PDF (Document object) containing a single page from an existing PDF (Document objet) that is in-memory, and not saved to disk.

I assume the fact that the Document object refers to a PDF created in memory (with PyMuPDF using the same procedure: `insert_pdf`) only and not a PDF loaded from disk triggers this error because the in-memory object does not have the `_graft_id` attribute?

## Expected behavior (optional)

Maybe the check on `_graft_id` attribute should be made with `hasattr(self, "_graft_id", "_absent_left")` or something like that to allow the operation? Or maybe that attribute needs to be set at some point when creating a Document object in-memory? Just food for thought.

## Your configuration (mandatory)
 - Ubuntu 20.04
 - Python 3.9
 - PyMuPDF 1.18.12 (pip installed)

Thanks!

**Comment by JorjMcKie** [comment]
I don't have your failing script, but your assumptions are not valid. Here is a snippet, that

1. reads a PDF to memory
2. creates a PDF document from that memory area
3. creates a new PDF
4. copyies a page from the source PDF into it.
5. no problems

```python
>>> import fitz
>>> inbytes = open("v110-changes.pdf","rb").read()
>>> src = fitz.open("pdf", inbytes)
>>> doc=fitz.open()
>>> doc.insert_pdf(src, from_page=0,to_page=0)
>>> doc.save("page0.pdf")
>>> 
```

**Comment by JorjMcKie** [comment]
What you seem to do is treating a page object as a document.
So it is probably your bug - not one of PyMuPDF.

**Comment by JorjMcKie** [comment]
Any comments? Need more help?

**Comment by jeanmonet** [comment]
Many thanks, and apologies for the mistake. I jumped to conclusion too quickly: indeed I just noticed the object was a `Page` and not a `Document` object as intended, and thought the error was related to working with documents created on the fly. My bad.

**Comment by JorjMcKie** [comment]
No problem at all.
Thanks for using PyMuPDF anyway!

**Comment by Vinaykumar191** [comment]
import fitz

# Open the source PDF file from which you want to copy pages
source_pdf = fitz.open("C:/Users/Vinay/Desktop/9B.pdf")

# Create a new PDF file where you want to copy the pages
output_pdf = fitz.open()

# Specify the page numbers you want to copy (e.g., 0 for the first page, 1 for the second page, etc.)
page_numbers_to_copy = [0, 1, 2]  # Adjust this list as needed

for page_number in page_numbers_to_copy:
    # Get the source page
    source_page = source_pdf[page_number]

    # Append the source page to the output PDF
    output_pdf.insert_pdf(source_page)

# Save the output PDF to a file
output_pdf.save('output.pdf')

# Close both the source and output PDFs
source_pdf.close() .                error:AttributeError: 'Page' object has no attribute '_graft_id'
