### ISSUE TITLE
XML Generation: Include lines / rectangles / curves

### ISSUE THREAD

**Issue by vestronge** [pymupdf/PyMuPDF#1058]
PyMuPDF seems to be amazing and much faster than pdflib tet and pdfminer/pdfminer.six. However, pdfminer provides xml geometry for lines / curves printed on the document. Example

```
<rect linewidth="0" bbox="62.929,462.847,531.901,465.094" />
```

These line coordinates are very much helpful in deducing page layout / table layout.

If would be wonderful if a similar xml element was added to PyMuPDF.

**Comment by vestronge** [comment]
Please refer to https://github.com/euske/pdfminer/blob/master/pdfminer/converter.py#L73 the type of objects I am talking about. 

Thanks

**Comment by JorjMcKie** [comment]
Please have a look at documentation of `Page.get_drawings()`.
The output of that method consists of a list of so-called "paths". These are the drawings like lines, curves and rectangles.
The advantage over an XML format:
* Python objects - no need to interpret via an extra package like lxml
* Ready to be used as input to other PyMuPDF functions for re-creating the graphics on another page.
* And of course again: speed!

The `get_drwings()` method works for all supported document types (XPS, EPUB, SVG, etc), not just PDF.

**Comment by JorjMcKie** [comment]
Question answered? Can we close the issue?

**Comment by vestronge** [comment]
Yes it does. That is fantastic. I will use `get_drawings` in combination with `get_text('xml')`. We'll be using PyMuPDF going forward 🥳
