### ISSUE TITLE
The value of the character coordinates extracted by get_text("words") is wrong

### ISSUE THREAD

**Issue by ye-xue** [pymupdf/PyMuPDF#1066]
## Describe the bug (mandatory)
The value of the character coordinates extracted by get_text("words") is wrong and needs to be transposed to be the correct data.
The conversion is as follows:
x0 = page.rect.x1 - y1
y0 = x1
x1=page.rect.x1 - y1 + y1 - y0
y1=x1 + x1 - x0

## To Reproduce (mandatory)
```
import fitz

doc = fitz.Document("dome.pdf")
page = doc[0]

for x0, y0, x1, y1, value, _, _, _ in page.get_text("words"):
    print(x0, y0, x1, y1)
```

## Expected behavior (optional)
The x0,y0,x1,y1 values are the same as the positions shown on the file

## Screenshots (optional)
![error_img](https://user-images.githubusercontent.com/30040613/120284044-6c4e2e00-c2ee-11eb-87db-52b2b1b67764.png)
![dome_file_img](https://user-images.githubusercontent.com/30040613/120285366-bf74b080-c2ef-11eb-9b6a-b4ac7f76db84.png)

## Your configuration (mandatory)
 - windows 10 21H1 19043.985
 - python3.8.9
 - PyMuPDF 1.18.13 pip install pymupdf

**Comment by JorjMcKie** [comment]
Cannot reproduce without a minimal example file.

**Comment by ye-xue** [comment]
See sample files

[dome.pdf](https://github.com/pymupdf/PyMuPDF/files/6574413/dome.pdf)

**Comment by JorjMcKie** [comment]
There is no error. The following snippet extracts words and then draws their rectangles on the page:
```python
>>> for w in page.get_text("words"):
	rect=fitz.Rect(w[:4])
	page.draw_rect(rect, width=0.3, color=(0,0,1))
>>> doc.save("words.pdf")
>>> 
```
The result is this - everything perfect:
[words.pdf](https://github.com/pymupdf/PyMuPDF/files/6574586/words.pdf)

Your iritation probably is this:
The page is rotated by 90 degrees.
As you can read in the documentation, all methods, which return position information (text extraction, image positions, ...), deliver the coordinates of the **_unrotated_** page.
Also the other way round: To insert something on an unrotated page (text, image, ...), you must provide **_unrotated_** coordinates.
You can compute between those coordinate systems via the page matrices `page.rotation_matrix` and `page.derotation_matrix` if you need these ccordinates. In your post, it looks like you tried to do this yourself ...

**Comment by ye-xue** [comment]
How do I get the coordinates of the rotation?
Can you provide a sample code?

Thank you.

**Comment by JorjMcKie** [comment]
```python
>>> words=page.get_text("words")
>>> word=words[0]
>>> pprint(word)
(164.18531799316406,
 684.3369140625,
 171.1477813720703,
 699.8095092773438,
 '*物号',
 0,
 0,
 0)
>>> rect = fitz.Rect(word[:4])  # word location in unrotated coordinates
>>> # this is the rect in rotated coordinates
>>> rect * page.rotation_matrix
Rect(142.19049072265625, 164.18531799316406, 157.6630859375, 171.1477813720703)
>>> 
```
