### ISSUE TITLE
Garbled out with TextWriter and Type1 font

### ISSUE THREAD

**Issue by vuori** [pymupdf/PyMuPDF#1067]
## Describe the bug (mandatory)
When using `TextWriter` with a classic Type1 font, garbled output is produced.

## To Reproduce (mandatory)
Supply a `Font` produced from a Type1 font with classic 8-bit encoding to a TextWriter and attempt to use it. Note that output is  garbled, while using `insert_text` with a manually inserted font (with `set_simple=True`) works.

The font appears to be identified as a (CID-keyed?) Type0 font and Identity-H mapping is used. This does not work since the argument to `TJ` consists of… something (GIDs?) which are not 8-bit character codes.

Sample code (font files included in attachment):

```py
import pprint
import fitz

OTF_FONT = 'EBGaramond12-Regular.otf'
T1_FONT = 'EBGaramondPS12-Regular.pfa'
TEST_TEXT = "Lorem ipsum dolor sit amet, consectetur adipiscing elit"

def create_pdf():
    document = fitz.Document(width=595, height=842)
    textpage = document.new_page(0)

    xorig = 20
    w = 555
    y = 20

    writer = fitz.TextWriter(textpage.cropbox, color=1.0)

    textpage.insert_font(fontname='EBGaramond-insertfont',
                         fontfile=T1_FONT,
                         set_simple=True)
    # Add test text using various fonts
    for font, desc in ((fitz.Font(fontfile=OTF_FONT), "OTF"),
                       (fitz.Font(fontfile=T1_FONT), "Type1 TextWriter"),
                       ):
        writer.fill_textbox(fitz.Rect(xorig, y, w, y+30),
                            f'[{desc}] ' + TEST_TEXT,
                            font=font,
                            align=fitz.TEXT_ALIGN_JUSTIFY)
        y += 30

    textpage.write_text(writers=[writer])
    textpage.insert_textbox(fitz.Rect(xorig, y, w, y+30),
                            '[Type1 insert_text] ' + TEST_TEXT,
                            fontname='EBGaramond-insertfont')
    y += 30

    textpage.insert_textbox(fitz.Rect(xorig, y, w, y+200),
                            pprint.pformat(textpage.get_fonts()))
    return document

if __name__ == '__main__':
    create_pdf().save('t1_test.pdf', pretty=True)
```

The Type1 font was produced in FontForge by opening the original OpenType version, setting an 8-bit encoding (doesn't matter which one) and generating a Postscript font.

## Expected behavior (optional)
Ideally auto-detect non-CID Type1 fonts as using classic 8-bit encoding, but allowing specifying `set_simple` in the Font constructor would probably be a sufficient workaround.

## Screenshots (optional)
The middle line should say `[Type1 TextWriter] Lorem ipsum dolor sit amet, consectetur adipiscing elit`. At the bottom is the output of `get_fonts()`.

![Screenshot_2021-06-01_19-37-21](https://user-images.githubusercontent.com/7074228/120359845-ab34b180-c2f7-11eb-84a4-f975684dd98f.png)

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 ```
3.7.9 (default, Jan 14 2021, 22:42:22) 
[GCC 9.3.0] 
 linux 
 
PyMuPDF 1.18.13: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-05-05 06:32:22.
Built for Python 3.7 on linux (64-bit).
```
 - PyMuPDF version, installation method (**wheel** or **generated** from source).
`wheel`

## Additional context (optional)
Sample code and fonts:
[t1_test.zip](https://github.com/pymupdf/PyMuPDF/files/6577787/t1_test.zip)

Use case: While there's probably not a whole lot of use for legacy Type1 fonts these days, I'm producing a test PDF to exercise another PDF rasterizer. Being able to output various legacy features is convenient for testing purposes.

**Comment by JorjMcKie** [comment]
The `TextWriter` class only works for Type 0 fonts. I hope I have stated this clearly enough in the docu.
Support of a CMAP is mandatory among other things. All character output is always via its GID - there is no way to do it like with the simple text insertion.

Whatsoever, bottom line is, PyMuPDF cannot do anything about it. And I doubt MuPDF will approve a change request on this, but you may want to try it anyway.

**Comment by vuori** [comment]
Sounds reasonable. Perhaps it would the best to throw on exception on an unsuitable font?

Also, I can't seem to find any mention of the requirement in either the `Font` or `TextWriter` documentation.

**Comment by JorjMcKie** [comment]
> to throw on exception on an unsuitable font?

That's what I am doing already. Font creation will throw MuPDF-initiated exceptions if the `freetype` library cannot handle it. If a "non-writable" font is used in `TextWriter` I will throw an exception, too. This will then be based on MuPDF library feedback.

I have experimented a little with the .pfa font: `Font` and `TextWriter` simply accept it and handle it like they would OTF and TTF fonts. This included unicodes up to 255 at least - didn't try beyond.
But as I said: there is no way to influence how the PDF coding of text output works  - `TJ` operator and 4 hex digits per GID.
