### ISSUE TITLE
whitespace mismatch between output of mutool draw vs fitz

### ISSUE THREAD

**Issue by asishm-wk** [pymupdf/PyMuPDF#1068]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
For this [pdf](https://github.com/asishm-wk/pymupdffile/blob/main/2ThemartComInc_19990826_10-12G_EX-10.10_6700288_EX-10.10_Co-Branding%20Agreement_%20Agency%20Agreement.pdf)

the output of `mutool draw` preserves the whitespaces between the different sections (snip of part of page 1)
![image](https://user-images.githubusercontent.com/81247426/120391605-47ad8280-c2fd-11eb-915c-941c01c01020.png)

whereas when running the same file through fitz ignores all the whitespace
![image](https://user-images.githubusercontent.com/81247426/120391714-6dd32280-c2fd-11eb-8047-9b77c1546fad.png)

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.
```py
import fitz
file = '2ThemartComInc_19990826_10-12G_EX-10.10_6700288_EX-10.10_Co-Branding Agreement_ Agency Agreement.pdf'
doc = fitz.open(file)
print(doc.get_page_text(0))
```

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness (3.6.12
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

3.6.12 (default, Dec 12 2020, 13:53:18)
[GCC 8.3.0]
 linux

PyMuPDF 1.18.13: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-05-05 06:32:22.
Built for Python 3.6 on linux (64-bit).

installed via pip

**Comment by JorjMcKie** [comment]
That is not a bug but a feature 😉. There are situations (like your example) where a few more linebreaks look nice, but mostly that is not the case, so I wrote my own version of simple `get_text("text")` output which aims to reduce linebreaks inflation.
If you like to have some more, use `page.get_text("blocks")` like what follows. This also is an easy way to sort the text to conform to a natural reading sequence.
```python
blocks = page.get_text("blocks")
blocks.sort(key=lambda b: (b[3], b[0])) # sort by ascending y, then x block coordinates
for b in blocks:
    print(b[4])
    print("\n")  # as many times as you like
```

**Comment by JorjMcKie** [comment]
Before you wonder whether those silly linebreaks were sufficient motivation for writing duplicate code:
* All "my" text extraction versions also support a wider range of characters, and return raw unicode escape replacements when needed
* You can always restrict extraction to a subrectangle ("clip") of the full page
* For extractions that also provide position information, you can choose to reduce the wrapping bboxes to the actual glyph - as opposed to always respect the line height of the font.
* Position information always pertains to the **_unrotated_** page: e.g. a bbox is always the same, whether or not the page is rotated. Vice versa: to insert something (text, image, etc.) must always accompanied by unrotated coordinates. Of course there are function that help with any computations ...
* All that is in sync with the text search functions.

"My extractions" are the code behind "text", "words", "blocks", "dict", "json", "rawdict" and "rawjson". So "xml", "html" and "xhtml" are original MuPDF code, which therefore will not react to parameters mentioned above.

**Comment by asishm-wk** [comment]
Thanks for the speedy response (and for the update on the logic!)

That makes sense given most other tools I've tried also remove those linebreaks. Is there a python API equivalent that would offer the same conversion as `mutool`? If not I could figure out a way to build it to have the binary available to call via a subprocess call.

**Comment by JorjMcKie** [comment]
I would **_always_** recommend to use `get_text("blocks")` instead as mentioned above.
1. It is a **_lot faster_** than synchronizing with a subprocess
2. You can sort the output in a satisfactory way for most situations (which mutool draw does not)
3. It is as fast as `get_text("text")`
4. Much easier to code.

If you want you can obviously recreate a complete text string for the full page:
```python
blocks = page.get_text("blocks")
blocks.sort(key=lambda b: (b[3], b[0])) # sort by ascending y, then x block coordinates
text = "\n".join([b[4] for b in blocks])
```
The `text` should be equal to mutool draw output, except it is already sorted.

**Comment by asishm-wk** [comment]
Sounds good! thanks a lot for your help (and for your work on this library)
