### ISSUE TITLE
pip install fails with Python 3.8.5

### ISSUE THREAD

**Issue by geerdink** [pymupdf/PyMuPDF#1070]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Our build pipeline fails, its seems with project failed to upload a manylinux wheel for py38.

## To Reproduce (mandatory)
pip install

## Your configuration (mandatory)
- centos75-python38:3.8.5-2021.02.25
- Python 3.8.5
- mdpdf==0.0.15

## Additional context (optional)

Error log:

Running setup.py install for pymupdf ... error
--
&nbsp; | ERROR: Command errored out with exit status 1:
&nbsp; | command: /pyenv/versions/3.8.5/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-49vzgqb7/pymupdf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-49vzgqb7/pymupdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ky20o69c/install-record.txt --single-version-externally-managed --compile --install-headers /pyenv/versions/3.8.5/include/python3.8/pymupdf
&nbsp; | cwd: /tmp/pip-install-49vzgqb7/pymupdf/
&nbsp; | Complete output (17 lines):
&nbsp; | running install
&nbsp; | running build
&nbsp; | running build_py
&nbsp; | creating build
&nbsp; | creating build/lib.linux-x86_64-3.8
&nbsp; | creating build/lib.linux-x86_64-3.8/fitz
&nbsp; | copying fitz/__init__.py -&gt; build/lib.linux-x86_64-3.8/fitz
&nbsp; | copying fitz/fitz.py -&gt; build/lib.linux-x86_64-3.8/fitz
&nbsp; | copying fitz/utils.py -&gt; build/lib.linux-x86_64-3.8/fitz
&nbsp; | copying fitz/__main__.py -&gt; build/lib.linux-x86_64-3.8/fitz
&nbsp; | running build_ext
&nbsp; | building 'fitz._fitz' extension
&nbsp; | creating build/temp.linux-x86_64-3.8
&nbsp; | creating build/temp.linux-x86_64-3.8/fitz
&nbsp; | gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/include/openssl -I/usr/include/openssl -fPIC -I/usr/include/mupdf -I/usr/local/include/mupdf -Imupdf/thirdparty/freetype/include -I/usr/include/freetype2 -I/pyenv/versions/3.8.5/include/python3.8 -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.8/fitz/fitz_wrap.o
&nbsp; | unable to execute 'gcc': No such file or directory
&nbsp; | error: command 'gcc' failed with exit status 1
&nbsp; | ----------------------------------------
&nbsp; | ERROR: Command errored out with exit status 1: /pyenv/versions/3.8.5/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-49vzgqb7/pymupdf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-49vzgqb7/pymupdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ky20o69c/install-record.txt --single-version-externally-managed --compile --install-headers /pyenv/versions/3.8.5/include/python3.8/pymupdf Check the logs for full command output.

**Comment by JorjMcKie** [comment]
please try again - it took me time b/o bad internet connection

**Comment by geerdink** [comment]
Yes, it works again. Thanks for the quick fix!
