### ISSUE TITLE
Could not find matching package when installing in off line mode

### ISSUE THREAD

**Issue by smoothcriminal78** [pymupdf/PyMuPDF#1075]
I installing PyMuPDF 1.18.4 pretty well when i use pip install PyMuPDF==1.18.4, but if i try to install it from previously downloaded package (pip install PyMuPDF==1.18.4 --no-index --find-links=/path_to_the_folder_with_pymu_whl) it says that no package with right version doesn't found, all other packages installs very well from .whl. I tried to freeze and download and it's the same whl. After installing it on-line, i retried to install it from whl and it's installed without problems. I could only guess that there is some check or something like this which drops this package from installing.

**Comment by smoothcriminal78** [comment]
Actually, I found workaround - renamed PyMuPDF-1.18.14-cp36-cp36m-manylinux2010_x86_64.whl to PyMuPDF-1.18.14-cp36-cp36m-manylinux1_x86_64.whl.

**Comment by JorjMcKie** [comment]
Very weird all that!
There have been changes in wheel generation on Travis CI using cibuildwheel since the times of that patch level, so who knows what the problem was.
Presumably you are using the most recent pip version, don't you? Non-current versions may cause all sorts of problems these days.

**Comment by smoothcriminal78** [comment]
I'm using pip 18.0.1. If you wish to do some kind of investigation i could provide all the enivironment necessary. But i think it's some kind of fusion of factors which causes this behavior. If someone experience this - renaming works fine.

**Comment by JorjMcKie** [comment]
> using pip 18.0.1

very likely the problem!
