### ISSUE TITLE
The width and height of the text curve are inaccurate

### ISSUE THREAD

**Issue by zdw1011781461** [pymupdf/PyMuPDF#1076]
![image](https://user-images.githubusercontent.com/42407561/120738526-8ec88d00-c522-11eb-857b-e1c512f7032a.png)
I have a curve text, width = 15.823 mm,  height = 1.07 mm

doc = fitz.open("./pdf/test.pdf")
page = doc[0]
paths = page.get_drawings() 
for index, path in enumerate(paths):
    outpdf = fitz.open()
    rect = path['rect']
    x, y = rect[0], rect[1]
    out_page = outpdf.new_page(width=rect.width, height=rect.height)
    shape = out_page.new_shape()  # make a drawing canvas for the output page
    **print(index, 'width:', round(rect.width * 25.4 / 72, 3), 'height:', round(rect.width * 25.4 / 72, 3),)**
   **# 2 width: 1.14mm height: 1.14mm**
   for item in path["items"]:  
        if item[0] == "l":  # line         
            shape.draw_line((item[1][0] - x, item[1][1] - y), (item[2][0] - x, item[2][1] - y))
        elif item[0] == "re":  # rectangle  
            shape.draw_rect((item[1][0] - x, item[1][1] - y))
        elif item[0] == "c":  # curve       
            shape.draw_bezier((item[1][0] - x, item[1][1] - y), (item[2][0] - x, item[2][1] - y),
                              (item[3][0] - x, item[3][1] - y), (item[4][0] - x, item[4][1] - y))
        else:
            raise ValueError("unhandled drawing", item)
   shape.finish(
        fill=path['fill'],  # fill color
        color=path["color"],  # line color
        dashes=path["dashes"],  # line dashing
        even_odd=path["even_odd"],  # control color of overlaps
        closePath=path["closePath"],  # whether to connect last and first point
        lineJoin=path["lineJoin"],  # how line joins should look like
        lineCap=max(path["lineCap"]),  # how line ends should look like
        width=path["width"],  # line width
        stroke_opacity=path["opacity"],  # same value for both
        fill_opacity=path["opacity"],  # opacity parameters
        )

    shape.commit()
    outpdf.save("./pdf/demo-%s.pdf" % index)

this's my code, I got this curve width = 1.14mm, height = 1.14mm;
I want get single pdf, to svg

**Comment by JorjMcKie** [comment]
Your code is practically unreadable because all the identation is missing.
To reproduce I also need the test file.
Which version are you using?

**Comment by zdw1011781461** [comment]
PyMuPDF ==1.18.12
python==3.6.2
os==ubuntu16.04
[Uploading test.pdf…]()

**Comment by JorjMcKie** [comment]
I do not understand the problem. Here is a script which reads your input and produces an output with all drawings duplicated.
Looks perfec to me.
[duplicate-draws.zip](https://github.com/pymupdf/PyMuPDF/files/6596763/duplicate-draws.zip)

**Comment by zdw1011781461** [comment]
I hope get a svg not pdf, this my code, thank you fot your help;
[test_draw.zip](https://github.com/pymupdf/PyMuPDF/files/6597050/test_draw.zip)

**Comment by JorjMcKie** [comment]
Why don't you use `page.get_svg_image()`?
```python
>>> for page in doc:
	out=open("page%i.svg" % page.number, "w")
	svg=page.get_svg_image()
	out.write(svg)
	out.close()
```
produces these two good-looking svg files:

[issue-1076.zip](https://github.com/pymupdf/PyMuPDF/files/6597135/issue-1076.zip)

**Comment by zdw1011781461** [comment]
[test_draw1.zip](https://github.com/pymupdf/PyMuPDF/files/6597185/test_draw1.zip)
demo-svg0.svg is normal, demo-svg1,svg and demo-svg2.svg is error

**Comment by JorjMcKie** [comment]
you should upgrade to v1.18.14
Prior versions contain an error calculating `path["rect"]`.

**Comment by JorjMcKie** [comment]
This script produces separate SVG files for each path on page 0:
[split-draws.zip](https://github.com/pymupdf/PyMuPDF/files/6597387/split-draws.zip)

**Comment by zdw1011781461** [comment]
Thank you for helping me solve the problem，I upgraded the version and it worked
