### ISSUE TITLE
page.get_text("blocks") returns content with lots of "question mark in a diamond shape"

### ISSUE THREAD

**Issue by alexgrimmy** [pymupdf/PyMuPDF#1082]
I have a set of order documents that are generated fromt the same source.  Content from some documents are extracted issue free, while others are filled with "question mark in diamond shape" characters.  Was wondering if there are flags / settings that I'm not using correctly.

Code is simple standard:

    blocks = page.get_text("blocks")
    for b in blocks:
        print (b)

The output looks like this:

[27.72, 124.14, 206.86, 364.14, 'A?k;�lmknD�oC�o?kA�@DD=BAA\n']

I'm running:

    Windows 10
    python 3.8.2 64bit
    pymupdf 1.18.14 (wheel)

Thank you!

**Comment by JorjMcKie** [comment]
Neither you nor I did anything wrong here.
The used font (a so-called Type 3 font) is configured to protect itself from being read: you cannot copy/paste from the page using Adobe or another reader.
The only way I see is OCR-ing the page and then extract.

**Comment by alexgrimmy** [comment]
Thank you for the clarification.  Very much appreciated.

**Comment by JorjMcKie** [comment]
There is a little script which uses a separately installed Tesseract to OCR anything that contains those diamond question marks: look [here](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/OCR)

**Comment by alexgrimmy** [comment]
In my case it appears that I may have a slight control over the 3rd party that generated the PDFs.  
In the file that is causing extraction problem, it appears that the file was created using Acrobat Distiller with PScript5.dll.  Per Adobe and Type 3 fonts: "Acrobat and Adobe Reader convert the Type 3 characters to bitmap images and then display them."  So it would make sense that what I see is no longer text but bitmap images.  In the file that did work, the file was also created by Acrobat but did not use PScript5.dll.  
I learned something today.  Thank you again!

**Comment by alexgrimmy** [comment]
Yes sir! Thank you!

    On Monday, June 7, 2021, 11:19:19 AM CDT, Jorj X. McKie ***@***.***> wrote:  
 
 


Close issue?
