### ISSUE TITLE
1.18.14 changed capitalization of deprecated getTextlength to getTextLength (capital L)

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#1085]
In 1.18.12 and 1.18.12:
```
AttributeError: module 'fitz' has no attribute 'get_text_length'
```
But in 1.18.14:
```
AttributeError: module 'fitz' has no attribute 'getTextLength'
```
This is the usual problem we've discussed before: its hard to downstream users to have a minimum supported version while also supporting the latest version.

**Comment by JorjMcKie** [comment]
By no means intentional! On the contrary, I am aware this is an unpleasant change overall, so I want to make it as smooth and gentle as possible
But I don't understand how can your observation can happen:

```python
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import fitz
In [2]: fitz.getTextLength("hello")
Out[2]: 23.23199987411499
In [3]: print(fitz.__doc__)

PyMuPDF 1.18.14: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-06-01 08:11:38.
Built for Python 3.8 on linux (64-bit).

In [4]:
```

**Comment by JorjMcKie** [comment]
As we discussed earlier: Deprecation warning will start being issud in version 1.19.0.
Even that is not set in stone ...

**Comment by cbm755** [comment]
how strange!  I will dig....

**Comment by cbm755** [comment]
I figured it out!

  * In 1.18.13, it is called `fitz.getTextlength` **with a little "l"**  (and `get_text_length` is not present)

  * In 1.18.14, there is a deprecation message for `fitz.getTextLength` **with a capital "L"** (and as expected `get_text_length` is present)

**Comment by JorjMcKie** [comment]
WTF - a typo in the alias definition!

**Comment by JorjMcKie** [comment]
Fixed in new version.
