### ISSUE TITLE
add_rect_annot has slightly different behavior in 1.18.14

### ISSUE THREAD

**Issue by alexgrimmy** [pymupdf/PyMuPDF#1088]
Sorry - I do not know my previous PyMuPDF version, but I recently upgraded to 1.18.14.

In the prior version's behavior, when I add a rectangle annotation there is no fill allowing me to see the text underneath and only the border is visible.  However, in the latest version the fill appears to be opaque and I can no longer see the text underneath.

This is the original code
            page = self.doc.loadPage(0)
            rect = fitz.Rect(a,b,c,d)
            annot = page.add_rect_annot(rect)
            annot.set_border(width=1, dashes=[1,2])
            annot.set_colors(stroke=red)
            annot.update()

I tried the setting with fill=None but still fills the reactangle with white color
            annot.set_colors(stroke=red, fill=None)

I tried setting opacity but this sets _both_ the border and center of the rect box.
            annot.set_opacity(0.5)

Ideally the way it looked before had the border at opacity 1 and center of the rect box at opacity 0.

I tried a few different annotation methods but with no lunch.
Any suggestions?

Environment is:
Windows 10
Python 3.9.5
PyMuPDF 1.18.14 wheel

(Thank you)

**Comment by JorjMcKie** [comment]
There existed an error in some previous version (forgot which one).
This was fixed like so:
To remove or prevent one of the colors stroke or fill, use `stroke=[]` or `fill=[]` respectively.
Specifying `None` means that the color parameter is not touched.

**Comment by JorjMcKie** [comment]
No, sorry, you are right.
Something really awkward happened. Need to check that out.
If this is urgent for you, I can offer this as a circumvention:

**Comment by JorjMcKie** [comment]
Your should be able to achieve your goal via ``annot.update(fill_color=[])``.
I will keep searching the original problem.

**Comment by alexgrimmy** [comment]
Thank you as always!

    On Friday, June 11, 2021, 8:35:08 AM CDT, Jorj X. McKie ***@***.***> wrote:  
 
 


Your should be able to achieve your goal via annot.update(fill_color=[]).
I will keep searching the original problem.

**Comment by alexgrimmy** [comment]
I made the recommded changes but don't believe it yields the same results.My code is as follows
                annot = page.add_rect_annot(rect)                annot.set_border(width=1, dashes=[1,2])                annot.set_colors(stroke=red)                annot.update(fill_color=[])
However when rendered the "fill" is still white and filled in (i.e., cannot see the text underneath)
Thanks,Alex

**Comment by JorjMcKie** [comment]
ok, I will upload a new pre-version wheel in this channel. You have Py 3.9 64bit?

**Comment by alexgrimmy** [comment]
Yes. You are too kind - thank you!

    On Friday, June 11, 2021, 12:42:35 PM CDT, Jorj X. McKie ***@***.***> wrote:  
 
 


ok, I will upload a new pre-version wheel in this channel. You have Py 3.9 64bit?

**Comment by JorjMcKie** [comment]
[PyMuPDF-1.18.15-cp39-cp39-win_amd64.whl.zip](https://github.com/pymupdf/PyMuPDF/files/6640205/PyMuPDF-1.18.15-cp39-cp39-win_amd64.whl.zip)

You must unzip this somewhere and then execute ``py -3.9 -m pip install -U ....whl``.

**Comment by alexgrimmy** [comment]
Magic!  Confirms that everything works again like before with no fill and transparent!
