### ISSUE TITLE
Image Overlay

### ISSUE THREAD

**Issue by vbadwaj** [pymupdf/PyMuPDF#1094]
Hey,

I have been using PyMuPDF for about a week and I'm trying put a given in place of another, I do this by extracting the bbox coordinates, however, when I use the same coordinates for my new image. I get a much smaller version of it.
How can I cover the entire BBOX with my new Image?

I'm trying it in Google Colab.
```
doc=fitz.open(src_pdf_filename)
imglist = doc.getPageImageList(0, True)
for item in imglist:
	print(item[7], page.getImageBbox(item))
```

For now I'm copying the location and pasting it into another place.

```
import fitz
src_pdf_filename = source.pdf
dst_pdf_filename = dest.pdf
img_filename = newimage
img_rect = fitz.Rect(----PASTING IT HERE-------)
document = fitz.open(src_pdf_filename)
page = document[0]
page.insertImage(img_rect, filename=img_filename)
document.save(dst_pdf_filename)
document.close()
```

**Comment by JorjMcKie** [comment]
May be the target document page needs cleaning before you insert something: execute `page.clean_contents()` before you do `page.insert_image()`.
If sloppily created, the target page may have established permanent "geometry" changes - as opposed to encapsulating such things properly.

**Comment by JorjMcKie** [comment]
Refer to [this](https://pymupdf.readthedocs.io/en/latest/faq.html#misplaced-item-insertions-on-pdf-pages) chapter of the docu.

**Comment by vbadwaj** [comment]
Thanks @JorjMcKie I will try doing this.

**Comment by vbadwaj** [comment]
Hey @JorjMcKie, still getting the same problem.

**Comment by vbadwaj** [comment]
Hey @JorjMcKie , still having the problem

**Comment by JorjMcKie** [comment]
Has the target page the same size as the page from which the image is taken?
When inserting an image, the given rectangle is always completely filled with the provided image. So what you describe simply cannot happen.
On the target page, in addition draw the rectangle border `page.draw_rect(rect)` to debug this.

**Comment by vbadwaj** [comment]
I downloaded the new image from the internet.
Can I email you what it looks like after inserting?

**Comment by JorjMcKie** [comment]
>  Can I email you what it looks like after inserting?

Sure.
But have you tried drawing the rectangle border on the target page to confirm it is what you want?

**Comment by vbadwaj** [comment]
I have mailed you my output, I tried drawing a rectanlg border and yes it covers what i want to overlay upon.
