### ISSUE TITLE
Page.page.getImageBbox() turning infinitely

### ISSUE THREAD

**Issue by Scheriaa** [pymupdf/PyMuPDF#1106]
## Describe the bug 
In order to extract the images from a pdf_file, I use the to functions "page.getImageList(full = True)" and paga.getImageBbox. The first one works fine but the second one never returns a result.  
## To Reproduce 
An example of pdf with which I faced this problem can be found here. 

https://www.accenture.com/_acnmedia/PDF-149/Accenture-United-Nations-Global-Compact-Communication-Progress-2020.pdf
The problem is faced with the 3rd page
`import fitz 
document = fitz.Document(pdf_path)
images = document[2].getImageList(full = True)
bbox_image =  page.getImageBbox(images[0])
`

## Configuration 
I am using the version 1.18.5 but I tried other version and the problem persisted  - Python version, bitness

**Comment by JorjMcKie** [comment]
The error does not occur with a newer version:

```python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import fitz
>>> from pprint import pprint
>>> doc=fitz.open("Accenture-United-Nations-Global-Compact-Communication-Progress-2020.pdf")
>>> page = doc[2]
>>> imglist = page.get_images(True)
>>> pprint(imglist)
[(20, 0, 314, 314, 8, 'ICCBased', '', 'Im0', 'DCTDecode', 0),
 (22, 21, 250, 111, 8, 'Indexed', '', 'Im1', 'FlateDecode', 0),
 (24, 0, 205, 100, 8, 'Indexed', '', 'Im2', 'FlateDecode', 0),
 (25, 0, 315, 315, 8, 'ICCBased', '', 'Im3', 'DCTDecode', 0)]
>>> for img in imglist:
	print(page.get_image_bbox(img))

	
Rect(1442.9530029296875, 605.363525390625, 1678.0205078125, 840.4309692382812)
Rect(1443.5443115234375, 841.534912109375, 1630.610595703125, 924.3978271484375)
Rect(1459.94775390625, 443.0, 1613.0521240234375, 517.9663696289062)
Rect(1442.1297607421875, 198.65576171875, 1677.641845703125, 434.1920166015625)
>>> print(fitz.__doc__)

PyMuPDF 1.18.14: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-06-01 08:11:38.
Built for Python 3.8 on win32 (64-bit).

>>> 
```
Your imagelist is created using a temporarily loaded page: `document[2]`.
Which is a waste of resources, because you afterwards reference that same page again.
Did you load it one more time without showing this in your code snippet?
From what I can see, that `page` object could be just anything - potentially leading to Python interpreter breakdowns when things go really wrong.

**Comment by JorjMcKie** [comment]
As an aside:
Since v1.18.11 you can optionally request the return of the so-called "transform" matrix, which embodies all information about what happened to the original image file to make the image fit into the bbox.
This means things like rotation or flipping.

**Comment by syrinecheriaa** [comment]
Thank you for your answer. 

> Did you load it one more time without showing this in your code snippet?
>
Yes, I made a mistaken in the code that I shared : `page = document[2]` is missing. But this is not the problem since in my tests I made sure to assign document[2] to the variable page.
> The error does not occur with a newer version:
>
Unfortunately the version do not resolve the problem for me. 
Here is the output of fitz.__doc__:

PyMuPDF 1.18.14: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-06-01 08:11:38.
Built for Python 3.8 on linux (64-bit).

**Comment by JorjMcKie** [comment]
Woa! Works under Windows but not Linux!
Need to check that out. As a circumvention, please use this more advanced `page` method:
```python
In [9]: for img in page.get_images(True):
   ...:     print(page.get_image_rects(img))
   ...:
[Rect(1442.9530029296875, 605.363525390625, 1678.0205078125, 840.4309692382812)]
[Rect(1443.5443115234375, 841.534912109375, 1630.610595703125, 924.3978271484375)]
[Rect(1459.94775390625, 443.0, 1613.0521240234375, 517.9663696289062)]
[Rect(1442.1297607421875, 198.65570068359375, 1677.641845703125, 434.19195556640625)]
In [10]:
```
`page.get_image_rects` returns the same information **_except_** that it will report all locations that the same image has on a page: there may be multiple.
So what you get is a list of rect objects ... with mostly just one item as above.
Just tested that it does work under Linux.

**Comment by syrinecheriaa** [comment]
Thank you.
I confirm that it works just fine.

**Comment by JorjMcKie** [comment]
Just found out that there is an underlying MuPDF problem: doing `mutool clean -s file.pdf` goes into an infinite loop under Windows and Linux.

**Comment by amirdresler** [comment]
I have the same issue of never returns a result - on version 1.17.0 & 1.17.7.

Upgrade to latest 1.18.5 solved the never return, But i got the following exceptions (on 1.17.0 the same ) in many other cases:

Exception:  Traceback (most recent call last):
  File "..\process_pdf.py", line 82, in pdf_get_image_boxs_scale
    box, scale1 = pdf_get_image_box_scale(filename, page, image)
  File "..\process_pdf.py", line 22, in pdf_get_image_box_scale
    imageBbox = page.getImageBbox(image)
  File "C:\Python3.6\lib\site-packages\fitz\__init__.py", line 161, in deprecated_function
    return fname(*args, **kw)
  File "C:\Python3.6\lib\site-packages\fitz\fitz.py", line 5215, in get_image_bbox
    return self.get_image_rects(item, transform=transform)[0]
IndexError: list index out of range

Will appriciate idea how to detect it in 1.17. so i will not need to upgrade to 1.18 (e.g. skip the image but so i will not stack.)

**Comment by JorjMcKie** [comment]
@amirdresler - this means that the image is not shown on the page, and that condition is not correctly intercepted.

**Comment by amirdresler** [comment]
"condition is not correctly intercepted." - will appreciate any solution that the application will not stack. e.g. can i get the info of "not shown" before calling the function?

**Comment by JorjMcKie** [comment]
> can i get the info of "not shown" before calling the function?

No, the planned result is an infinite rect in that case. For the time being wrap into try/except please

**Comment by amirdresler** [comment]
"wrap into try/except please" -> there is no exception, the function does not return :(

In addition please note that there is one image in the specific page, and it is shown when opening the PDF.

**Comment by JorjMcKie** [comment]
My previous post was not entirely precise:
There is `page.get_image_info(xrefs=True)`. If the xref of an image item in `page.get_images()` does not occur in `page.get_image_info(xrefs=True)`, then the image is not displayed.

**Comment by JorjMcKie** [comment]
> In addition please note that there is one image in the specific page, and it is shown when opening the PDF.

Don't understand. Please let me have that PDF or page. Send to my email if you don't want to have it publicly here.
