### ISSUE TITLE
Try and except clause not wokring properly when a segemntation fault error happens. (Python 3.8)

### ISSUE THREAD

**Issue by abhipn** [pymupdf/PyMuPDF#1111]
I am currently using pymupdf, and I am getting segmentation fault error for few PDF files.

        with open(document_path, "rb") as fp:
            try:
                with fitz.open(stream=fp.read(), filetype="pdf") as document:
                    num_pages = document.pageCount
                    # do stuff
            except:
                continue

If a segmentation fault error happens, try and except clause is not working. This is a huge problem for me because I am not able to catch the error, my program abruptly stops. What can I do?

**Comment by JorjMcKie** [comment]
Python interpreter crashes can never be intercepted - there simply is no way. Forget try/except here.
What must happen is finding and getting rid of the cause of the segfault.
So let me have one example problem file to track this down.
Did you try and do a more conventional processing - i.e. without using `with` clauses? Or at least without **_stacked_** `with` clauses as you do?

**Comment by JorjMcKie** [comment]
There is at least a way to see the last Python instruction used by doing `python -X dev script.py ...`.
That would be helpful.
