### ISSUE TITLE
page.get_images() does not work as expected

### ISSUE THREAD

**Issue by wingbroken** [pymupdf/PyMuPDF#1123]
_**Please provide all mandatory information!**_

I have one PDF file which is converted from word doc via Libreoffice(unfortunately I cannot upload it here due to company policy). When I tried to extract the images by page, the function get_images() always output the same list of images for any page, which is actually the list for full document but not for single page. 

For the same doc above, I used pdfplumber instead, the images can be extracted as displayed.

I tested this function page.get_images() in other normal PDF, and it works well. Any clue what is going on there? is it a bug?

I know it is difficult to tell without a sample doc and detail codes to test. I snapshot my codes in company for the doc, here you will see a list of images were extracted, but no bbox or meta information can be retrieved for any of the item, which is weird.

Hope you have some clue with the limited information here.

Thanks a lot!

![IMG20210706192052](https://user-images.githubusercontent.com/6972745/124611271-dc2e7600-dea3-11eb-9f2f-212b3f4af416.jpg)

**Comment by JorjMcKie** [comment]
This is no bug.
If you look into the documentation: The method only reports the contents of the page's dictionary `/Resources`.
This is not necessarily the list of images **_actually displayed_** on the page.
If you want that, use `page.get_image_info(xrefs=True)`.

**Comment by wingbroken** [comment]
> This is no bug.
> If you look into the documentation: The method only reports the contents of the page's dictionary `/Resources`.
> This is not necessarily the list of images **_actually displayed_** on the page.
> If you want that, use `page.get_image_info(xrefs=True)`.

Thanks Jorj.  Sorry I did read through the document previously on get_images() function but didnot notice it mentioned /Resources content only. But yes, get_page_info() works for me. Thanks again on the reply.
