### ISSUE TITLE
 mupdf: cannot recognize version marker exception in GCP Cloud function 

### ISSUE THREAD

**Issue by maha-01** [pymupdf/PyMuPDF#1124]
_, temp_local_filename = tempfile.mkstemp()
    blob.download_to_filename(temp_local_filename)
    img = fitz.open(temp_local_filename)
    doc = img.convert_to_pdf()
    img.close()
   pdf = fitz.open("pdf", doc)
  pdf.save("sample.pdf", garbage=4, deflate=True)

ERROR:
mupdf: cannot recognize version marker  
img = fitz.open(temp_local_filename)
File "/layers/google.python.pip/pip/lib/python3.8/site-packages/fitz/fitz.py", line 3607, in __init__
    _fitz.new_Document(
RuntimeError: no objects found

Python version :3.8
Pymupdf version :1.18.4

The above script i have executed in gcp cloud function , where i have used tempfile to download a blob then tried to open that and convert to pdf. I m getting an exception as mentioned above.

But the same script i have did in my local machine without using tempfile download. It worked well.

**Comment by JorjMcKie** [comment]
If `fitz.open` fails, then obviously `temp_local_filename` contains no supported document type.
What's the bug?

**Comment by maha-01** [comment]
> If `fitz.open` fails, then obviously `temp_local_filename` contains no supported document type.
> What's the bug?

I am downloading the blob that is a tiff file to a temporary file and trying to use that as we cannot directly open the blob. Obviously the temporary file will contain a tiff document which I wanted to open it for further process. But that is not happening.

**Comment by JorjMcKie** [comment]
Well MuPDF says, it is no valid document. And as TIFF belongs to the supported document types, `temp_local_filename` cannot be a valid TIFF ... **_or_** you have just detected a bug in MuPDF 😉.

**Comment by JorjMcKie** [comment]
Try to detect yourself what is contained in that file: use Pillow for example.

**Comment by maha-01** [comment]
> Try to detect yourself what is contained in that file: use Pillow for example.

I have already tried with pillow trying to open the same tempfile and process it to convert pdf. It worked well.
_, temp_local_filename = tempfile.mkstemp()
 blob.download_to_filename(temp_local_filename)
 img = Image.open(temp_local_filename)
 pages = []
 for page in ImageSequence.Iterator(img):
        pages.append(page.convert("L"))
 img.close()
 pages[0].save("sample.pdf", save_all = True, append_images=pages[1:])

**Comment by JorjMcKie** [comment]
So you are saying, that Pillow accepts the file and MuPDF does not?
If so you have the following options:
1. convert the image to another format using Pillow and process that output further with PyMuPDF
2. submit a bug report to https://bugs.ghostscript.com/enter_bug.cgi

Before using option 2, also try to convert the file using MuPDF cli tool: `mutool convert ...`
You can also send that TIFF to my email and I will look into it.

**Comment by maha-01** [comment]
> So you are saying, that Pillow accepts the file and MuPDF does not?
> If so you have the following options:
> 
> 1. convert the image to another format using Pillow and process that output further with PyMuPDF
> 2. submit a bug report to https://bugs.ghostscript.com/enter_bug.cgi
> 
> Before using option 2, also try to convert the file using MuPDF cli tool: `mutool convert ...`
> You can also send that TIFF to my email and I will look into it.

yes as of my observation Pillow accepts temporaryfile directly where the gcp blob has been downloaded but the same flow I have tried using with Pymupdf it throws an exception .

Pymupdf works well in my local machine, directly passing the tiff file without using tempfile because there is no need of it:
```
img_path = "sample.tiff"
img = fitz.open(img_path)
b = img.convert_to_pdf()  # convert to pdf
img.close()
pdf = fitz.open("pdf", b)  # open as pdf
pdf.save("output.pdf", garbage=4, deflate=True)
```

**Comment by JorjMcKie** [comment]
> directly passing the tiff file without using tempfile because there is no need of it

and 

> Pillow accepts temporaryfile directly

cannot both be true in my mind.
Anyway - I cannot look into your configuration. Try copying the file to somewhere else before processing it with PyMuPDF.
Are sure PyMuPDF is correctly installed on the cloud? Usually not a trivial thing I have heard.

**Comment by maha-01** [comment]
> > directly passing the tiff file without using tempfile because there is no need of it
> 
> and
> 
> > Pillow accepts temporaryfile directly
> 
> cannot both be true in my mind.
> Anyway - I cannot look into your configuration. Try copying the file to somewhere else before processing it with PyMuPDF.
> Are sure PyMuPDF is correctly installed on the cloud? Usually not a trivial thing I have heard.

import tempfile
**_, temp_local_filename = tempfile.mkstemp(suffix = ".tiff")**
blob.download_to_filename(temp_local_filename)
img = fitz.open(temp_local_filename)
doc = img.convert_to_pdf()
img.close()
pdf = fitz.open("pdf", doc)
pdf.save("sample.pdf", garbage=4, deflate=True)

 I have added suffix=".tiff" while creating temporary file and then downloaded the GCP tiff file to that temporary file. It solved my issue.

**Comment by JorjMcKie** [comment]
Good!
