### ISSUE TITLE
doc.get_toc() returns empty on second call

### ISSUE THREAD

**Issue by zweissman** [pymupdf/PyMuPDF#1127]
## Describe the bug (mandatory)
I have a pdf that has a bad page 38 in it https://pr-ie-training.s3.amazonaws.com/IN981MUN2015A.pdf 

When I make a call to doc.get_toc(), it returns 

`[[1, 'abstract', 1], [1, 'description', 2], [1, 'claims', 27], [1, 'drawings', 31], [1, 'wo-search-report', -1]]`

But if you make a second call to doc.get_toc() right after that, you get 

`[]`

## To Reproduce (mandatory)
```
pdf_filename = 'IN981MUN2015A.pdf'
with fitz.open(pdf_filename) as doc:
    print(len(doc.get_toc()))
    print(len(doc.get_toc()))

```

## Expected behavior (optional)
I'd expect that subsequent calls would return the same data, This works fine with a non-damaged pdf and it works fine on the first call, but something gets corrupt after reading it the first time.

## Your configuration (mandatory)
 - Operating system, Windows 10 Enterprise 64 bit
 - Python version, 3.7
 - PyMuPDF version, 1.8.13

## Additional context (optional)
I can try and take a look at this later but I don't have a fork of pymupdf on my computer at the moment.

**Comment by JorjMcKie** [comment]
This is the snippet
```python
>>> import fitz
>>> doc=fitz.open("IN981MUN2015A.pdf")
mupdf: non-page object in page tree
>>> toc1=doc.get_toc()
>>> toc2=doc.get_toc()
mupdf: non-page object in page tree
>>> print(fitz.TOOLS.mupdf_warnings(reset=False))
non-page object in page tree
non-page object in page tree
>>> len(toc1),len(toc2)
(5, 0)
>>>
```
The PDF is clearly damaged - and in a severe way: the page tree is invalid.
Under these conditions you cannot expect an identical behaviour of all functions when executed twice, because repair actions may have changed the document on first time through. Which is the case here, too.
So this is no bug.

**Comment by zweissman** [comment]
Thanks for looking.
