### ISSUE TITLE
TextWriter.fill_textbox returning incorrect lines of overflowing text

### ISSUE THREAD

**Issue by EngineerChris** [pymupdf/PyMuPDF#1146]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When using `TextWriter.fill_textbox`, the result (which should be any lines of text that did not fit in the specified rectangle) will also sometimes return lines of text that did fit in the rectangle.

## To Reproduce (mandatory)
```
>>> import fitz
>>> font = fitz.Font('Arial')
>>> fontsize = 12
>>> line_height = fontsize * font.bbox.height
>>> print(f'Line height = {line_height}')
Line height = 16.488000512123108
>>> rect = fitz.Rect(0, 0, 100, 20)
>>> text_writer = fitz.TextWriter(rect)
>>> text = 'Some text'
>>> text_writer.fill_textbox(rect, text, font=font, fontsize=fontsize)  # should return []
[('Some text', 54.02399969100952)]
```

## Expected behavior (optional)
With the given case, the result of `fill_textbox` should be `[]`

## Your configuration (mandatory)
 - Windows 10, v1909
 - Python version 3.9.1
 - PyMuPDF version 1.18.15, installed via `pip install PyMuPDF`.

**Comment by JorjMcKie** [comment]
Accepted - thx for submitting.
If you need a quick fix apply the following patch to ``utils.py`` in your installation:
```txt
4248c4248
<     return new_lines[i + 1 :]  # return non-written lines
---
>     return new_lines[max_lines:]  # return non-written lines
```

**Comment by EngineerChris** [comment]
I can probably wait on this, though thank you for offering the fix. I'm really wanting the warning to be fixed so I provide warnings when text overflows. For now I'm just trusting that I've gotten it programmed correctly...

A plus would be if there was a separate method for determining the number of lines a string would take, such as `TextWriter.get_number_lines(max_width, text, font, fontsize) -> int` and a method to determine line height `TextWriter.get_line_height(font, fontsize) -> float`. This would reduce the need to rely on a warning from `TextWriter.fill_textbox` or its return value to inform if an overflow occurred.

**Comment by JorjMcKie** [comment]
I understand. I will think about your suggestion, to introduce something like a "simulation run" for `fill_textbox`.
The line height topic has two aspects:
1. You can set it as a parameter, e.g. `lineheight=fontsize * 1.2` or so.
2. You can compute it from font properties `ascender` and `descender`: `(ascender - descender) * fontsize`. The method will do exactly this if the argument is omitted. If the value inside the brackets is equal to 1, the method `fill_textbox` will actively use 1.2, so you should do the same in your prediction.

**Comment by JorjMcKie** [comment]
I am planning to simply use a new parameter - like ``simulate=True`.
In that case the TextWriter would not be filled, and only the formatted line array would be returned. Then you can check its length to confirm it would fit.

**Comment by JorjMcKie** [comment]
New vesion 1.18.16 uploaded to [PyPI](https://pypi.org/project/PyMuPDF/).
