### ISSUE TITLE
test_matrix fails on certain platforms

### ISSUE THREAD

**Issue by swt2c** [pymupdf/PyMuPDF#1147]
The test_matrix test case fails on aarch64, ppc64le, and s390x platforms.

```
_________________________________ test_matrix __________________________________
    def test_matrix():
        assert tuple(fitz.Matrix()) == (0, 0, 0, 0, 0, 0)
        m45p = fitz.Matrix(45)
        m45m = fitz.Matrix(-45)
        m90 = fitz.Matrix(90)
        assert abs(m90 - m45p * m45p) < fitz.EPSILON
        assert abs(fitz.Identity - m45p * m45m) < fitz.EPSILON
        assert abs(m45p - ~m45m) < fitz.EPSILON
        assert fitz.Matrix(2, 3, 1) == fitz.Matrix(1, 3, 2, 1, 0, 0)
        m = fitz.Matrix(2, 3, 1)
        m.invert()
>       assert m * fitz.Matrix(2, 3, 1) == fitz.Matrix(1, 0, 0, 1, 0, 0)
E       assert Matrix(1.0, 1...1.0, 0.0, 0.0) == Matrix(1.0, 0...1.0, 0.0, 0.0)
E         Use -v to get the full diff
tests/test_geometry.py:141: AssertionError
```
On ppc64le, the left side of the failing assert is `Matrix(1.0, 1.4901161193847656e-08, 0.0, 1.0, 0.0, 0.0)` while the right side is ` Matrix(1.0, 0.0, 0.0, 1.0, 0.0, 0.0)` so it seems that there might be a problem with `invert()`.

This is with PyMuPDF 1.18.15 on Fedora.  It fails on Fedora 35 (Rawhide) with Python 3.10.0b4, but I can also reproduce on Fedora 34 with Python 3.9.5.

**Comment by JorjMcKie** [comment]
Okay, accepted. Thanks for submitting.
I will change the assertion to test approximate equality only.

**Comment by JorjMcKie** [comment]
[test_geometry.zip](https://github.com/pymupdf/PyMuPDF/files/6825454/test_geometry.zip)
If you need to replace it now, please use the above new version.
I appreciate you are using this facility.
Interesting, how different the same code behaves on different platfroms ...

**Comment by JorjMcKie** [comment]
I will also update the script in the repo folder rightaway.

**Comment by swt2c** [comment]
Thanks for the quick fix, I just skipped that test for now.

**Comment by JorjMcKie** [comment]
Updated relevant test scripts.
