### ISSUE TITLE
open pdf warning

### ISSUE THREAD

**Issue by zyc130130** [pymupdf/PyMuPDF#1148]
Hi,
  I try to open a pdf and get it's table of contents, but screen outputs some infomation "mupdf: invalid key in dict", what happen?
  By the way, method of "get_toc" it's result is right.

  use code:
      with open(file_name, "rb") as fr:
        file_name = fr.read()
      doc = fitz.open(stream=file_name, filetype="pdf")
      print(doc.get_toc())

screen output:
   mupdf: invalid key in dict
mupdf: invalid key in dict
mupdf: invalid key in dict
mupdf: invalid key in dict
mupdf: invalid key in dict
mupdf: invalid key in dict
mupdf: invalid key in dict
mupdf: invalid key in dict
mupdf: invalid key in dict

The pdf has attached.
[876912f8d1749473cefb41681c51fdbf.pdf](https://github.com/pymupdf/PyMuPDF/files/6829152/876912f8d1749473cefb41681c51fdbf.pdf)

Except your replay.

**Comment by JorjMcKie** [comment]
Very simple answer: the PDF is damaged in various places.
Try to repair it, e.g. via ´mutool clean -gggz file.pdf`, or simply live with the error messages.

**Comment by zyc130130** [comment]
> Very simple answer: the PDF is damaged in various places.
> Try to repair it, e.g. via ´mutool clean -gggz file.pdf`, or simply live with the error messages.

Thanks for your replay.
The pdf is broken, which sounds sad.
Now I try to get table of contents and index which in some pdfs, I used some method like "doc.get_toc", I know there is not bookmark in every pdf, even bookmark is not exactly equivalent to table of contents, so I use image classification technology to process images and locate the table of contents and index location. Do you have any suggestions for this requirement or a better way.
