### ISSUE TITLE
Incorrect search result when using clip

### ISSUE THREAD

**Issue by sagrawal-code** [pymupdf/PyMuPDF#1154]
## Describe the bug (mandatory)
I search for a common word such as "the" using `page.search_for` without any `clip` parameter. All occurrences get returned correctly. However, if I specify a `clip`, the `Rect` returned is wrong.

## To Reproduce (mandatory)
[github_sample.pdf](https://github.com/pymupdf/PyMuPDF/files/6839076/github_sample.pdf)
For this file, the following code, which should return the `the`s present in the line `additional information. The Predecessor Fund was the accounting survivor in` aren't returned. The number of rectangles returned are correct, but their coordinates are incorrect (`[Rect(85.40125274658203, 53.462501525878906, 94.87535095214844, 63.60300064086914), Rect(85.15950012207031, 85.23756408691406, 97.65769958496094, 96.57106018066406)]`).

```python
r1 = page.search_for(
            "the",
            clip=Rect(40.5, 228.31436157226562, 346.5226135253906, 239.5338592529297),
        )
print(r1)
```

## Your configuration (mandatory)
```
3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] 
 linux 
 
PyMuPDF 1.18.12: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-04-10 04:00:00.
Built for Python 3.8 on linux (64-bit).

```

**Comment by JorjMcKie** [comment]
Accepted and found the error.
Any urgency?

**Comment by sagrawal-code** [comment]
Thank you for the quick reply!

Yes, it is urgent. Is there a workaround? One I can think of is to get all occurrences on the page and then subset them in the clip coordinates. Is there a fast way to do this?

**Comment by JorjMcKie** [comment]
1. I can locally generate a Linux version for you and upload the wheel.
2. I can also send you a code snippet containing the lines you need to replace in your local `utils.py`.

Here is a wheel which I hope is installable for you. If not we must switch ot option 2.
[PyMuPDF-1.18.15-cp38-cp38-linux_x86_64.whl.zip](https://github.com/pymupdf/PyMuPDF/files/6840149/PyMuPDF-1.18.15-cp38-cp38-linux_x86_64.whl.zip)

**Comment by sagrawal-code** [comment]
Could you kindly let me know the changes required in `utils.py` as well? Maybe I can somehow make them in my code for now, till this is fixed in a release.

**Comment by JorjMcKie** [comment]
Here it is. Should start around line number 377:
```python
def search_for(*args, **kwargs) -> list:
    """Search for a string on a page.

    Args:
        text: string to be searched for
        clip: restrict search to this rectangle
        quads: (bool) return quads instead of rectangles
        flags: bit switches, default: join hyphened words
    Returns:
        a list of rectangles or quads, each containing one occurrence.
    """
    if len(args) != 2:
        raise ValueError("bad number of positional parameters")
    page, text = args
    quads = kwargs.get("quads", 0)
    clip = kwargs.get("clip")
    if clip != None:
        clip = Rect(clip)
    flags = kwargs.get(
        "flags", TEXT_DEHYPHENATE | TEXT_PRESERVE_WHITESPACE | TEXT_PRESERVE_LIGATURES
    )

    CheckParent(page)
    tp = page.get_textpage(clip=None, flags=flags)  # create TextPage
    rlist = tp.search(text, quads=quads)
    tp = None
    if not rlist or not clip:
        return rlist
    if clip:
        mylist = []
        for r in rlist:
            if Rect(r) in clip:
                mylist.append(r)
    return mylist

```

**Comment by JorjMcKie** [comment]
I haven't yet figured out what maybe going wrong in the underlying C code, but this version does work correctly.

**Comment by sagrawal-code** [comment]
I was able to replicate your logic in my code.

That is, get the occurrences without clipping and check for containment of the returned `Rect` objects within the clip region.

Thank you so much for the outstanding support!

**Comment by JorjMcKie** [comment]
In the meantime I also have located the bug in the C code. So drop me a note if you are interested in a wheel.

**Comment by sagrawal-code** [comment]
> In the meantime I also have located the bug in the C code. So drop me a note if you are interested in a wheel.

No, thank you. My current purpose is solved. I will wait for the fix in the next release.

**Comment by JorjMcKie** [comment]
New vesion 1.18.16 uploaded to [PyPI](https://pypi.org/project/PyMuPDF/).
