### ISSUE TITLE
insertPDF problem on a link splitted into two pages

### ISSUE THREAD

**Issue by lchade** [pymupdf/PyMuPDF#1178]
Hello, we're trying to combine several pdfs to a big one and add page numbers. When we test on a e-book where there's a link splitted on two pages, it occurs a runtime error:

    mupdf: invalid key in dict
    invalid key in dict (0): '<</A<</S/URI/URI(http://TeleGraph/accounts/5436))>>/Rect[360.537 85.2265 432 95.7265]/BS<</W 0>>/Subtype/Link>>'
    Traceback (most recent call last):
      File "C:\LiCh1_Work\Repos\MOF FOI\FOIAssembler\assembler_test.py", line 23, in <module>
        main()
      File "C:\LiCh1_Work\Repos\MOF FOI\FOIAssembler\assembler_test.py", line 19, in main
        result = FOIAssembler.Assemble(fileObjects)
      File "C:\LiCh1_Work\Repos\MOF FOI\FOIAssembler\foi_assembler_module.py", line 96, in Assemble
        result.insertPDF(doc)
      File "C:\Users\LiCh1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fitz\fitz.py", line 4397, in insert_pdf
        self._do_links(docsrc, from_page=from_page, to_page=to_page, start_at=sa)
      File "C:\Users\LiCh1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fitz\utils.py", line 1331, in do_links
        page_dst._addAnnot_FromString(link_tab)
      File "C:\Users\LiCh1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fitz\fitz.py", line 6030, in _addAnnot_FromString
        return _fitz.Page__addAnnot_FromString(self, linklist)
    RuntimeError: invalid key in dict

Since the error message talks about the link, we've tried removing these two pages that has the link, the code ran successfully with the rest of the pdf. And we also tested on the two pages and it occurs the same error. So we think the error comes from the splitted link.

Here is the link snapshot in e-book:
![image](https://user-images.githubusercontent.com/44476697/127376309-5733b8dd-d790-49c4-8fcc-fe8217c20a80.png)

This is the file of two problematic pages for reference:
[01-OReilly_Graph_Databases-problematic.pdf](https://github.com/pymupdf/PyMuPDF/files/6895770/01-OReilly_Graph_Databases-problematic.pdf)

Here is the code snippet to add page number. The error seems to happen at insertPDF() 

    def Assemble(pdfFiles):
        result = fitz.open()
        fileCount = 0
        for doc in pdfFiles:
            fileCount += 1
            for i in range(doc.pageCount):
                pageNumber = i+1
                page = doc.loadPage(i)
                textToAdd = str(fileCount) + "-" + str(pageNumber).zfill(3)
                page.cleanContents()
                
                page.insertTextbox(rect, textToAdd, fontsize = 18,
                              fontname = "Times-Roman",     
                              align = 2)    # 0 = left, 1 = center, 2 = right                   
            result.insertPDF(doc)

## configuration
 - PyMuPDF 1.18.9: Python bindings for the MuPDF 1.18.0 library.
 - Version date: 2021-02-26 13:46:32.
 - Built for Python 3.9 on win32 (64-bit).

Thanks!

**Comment by JorjMcKie** [comment]
The root of the problem is an illegal specification of the link addresses - not the fact, that the link seems to strech across two pages.
In reality, two separate links, one on each page, are present:
```python
>>> doc=fitz.open("01-OReilly_Graph_Databases-problematic.pdf")
>>> page=doc[0]
>>> from pprint import pprint
>>> for link in page.links():
	pprint(link)
	
{'from': Rect(360.5369873046875, 565.7734985351562, 432.0, 576.2734985351562),
 'id': '',
 'kind': 2,
 'uri': 'http://TeleGraph/accounts/5436)',
---------------------------------------^ illegal / unmatched!
 'xref': 49}
>>> print(doc.xref_object(49))
<<
  /Rect [ 360.537 85.2265 432 95.7265 ]
  /Subtype /Link
  /A <<
    /URI (http://TeleGraph/accounts/5436\)) 
% ---------------------------------------^ same thing in original PDF object definition
    /S /URI
  >>
  /M (D:20150430131021+00'00')
  /Border [ 0 0 0 ]
  /Type /Annot
>>
```
If I correct the syntax of the two erroneous link definitions, before ``insert_pdf``, everything works fine:
```python
>>> page = doc[0]
>>> l=page.get_links()[0]
>>> l["uri"]
'http://TeleGraph/accounts/5436)'
>>> l["uri"] = l["uri"][:-1]
>>> pprint(l)
{'from': Rect(360.5369873046875, 565.7734985351562, 432.0, 576.2734985351562),
 'id': '',
 'kind': 2,
 'uri': 'http://TeleGraph/accounts/5436',
 'xref': 49}
>>> page.update_link(l) # update corrected link
>>> page=doc[1]  # same on next page
>>> l=page.get_links()[0]
>>> pprint(l)
{'from': Rect(72.0, 55.04998779296875, 134.26499938964844, 65.54998779296875),
 'id': '',
 'kind': 2,
 'uri': 'http://TeleGraph/accounts/5436)',
 'xref': 59}
>>> l["uri"] = l["uri"][:-1]
>>> page.update_link(l)  # update corrected link
>>> out=fitz.open()  # now open output PDF
>>> out.insert_pdf(doc)  # and insert corrected PDF
>>> # works!

**Comment by JorjMcKie** [comment]
So as shown in previous post, the exception is justified and not a bug.

The question you will have of course:
How can I prevent this from happening / what may be some saveguard?

1. You could do `insert_pdf` without also copying over links and / or annots. May be unfortunate.
2. You could scan all the links on all pages and do some syntax check yourself. This is a never ending story, because you would have to build

**Comment by JorjMcKie** [comment]
All I could do (for the next PyMuPDF version), is ignoring exceptions of this kind and accept that some links / annots cannot be copied.
Background:
`insert_pdf` consists of two internal steps: (1) copying over the pages, (2) inserting links that are present in the source pages.

**Comment by lchade** [comment]
Wow you've given such a quick and all-around answer. Thank you!

**Comment by JorjMcKie** [comment]
As announced in previous post, in the next version I will intercept and ignore links and annotations that could not be copied over.
