### ISSUE TITLE
Is there a way to modify "annotation flag bits" of link?

### ISSUE THREAD

**Issue by Mark-Joy** [pymupdf/PyMuPDF#1187]
**Is your feature request related to a problem? Please describe.**
I would like to modify `Annotation flag bits` of `links`, but as Pymupdf's document reads bellow:

> Annotation Types
> 
> These identifiers also cover links and widgets: the PDF specification technically handles them all in the same way, whereas MuPDF (and PyMuPDF) treats them as three basically different types of objects.

**Describe the solution you'd like**

So is it possible?
Such as: base on `xref` value, turns a `Link` object into an `Annot` object, so that method `set_flags()` can be used?

**Additional context**
When convert from PDF to PDFA, [ghostscript removes hyperlink](https://bugs.ghostscript.com/show_bug.cgi?id=699830#c16)  because the `is_printed` flag is 0. I want to try making it 1 and `is_visible=0`  `is_hidden=1`.

**Comment by JorjMcKie** [comment]
Thanks for the suggestion. Next version will have ``flags`` property and `set_flags()` method for links as well.

Currently, you can achieve this using PyMuPDF low-level code:
```python
def set_flags(link, flags):
    # insert plausibility checks as needed
    doc=link.parent.parent
    doc.xref_set_key(link.xref, "F", str(flags))
```
A similar solution will also be used in the coming version.

Obviously, if you want to use one of the `dict` objects contained in `page.get_links()`  you must use `link["xref"]` as the xref.

**Comment by Mark-Joy** [comment]
Thank you!
I got pdf links fixed by setting `is_printed` flag to 1. Now gs converts pdf to pdf/a without dropping the link. But I did not check if there is any effect when the file is printed.

One more thing, can we have `doc.save(newFileName)` overwrite newFileName file, even if it is already exist?

```
#!/usr/bin/env python3
import os, sys, argparse, fitz
from pathlib import Path

def set_flags(link, flags):
	doc=link.parent.parent
	doc.xref_set_key(link.xref, "F", str(flags))
	return (doc.xref_get_key(link.xref, "F"))[1]

def get_flags(link):
    doc=link.parent.parent
    return (doc.xref_get_key(link.xref, "F"))[1]
    
#
odir="pdfLinkFixed"
ifile=Path(sys.argv[1])
ofile=Path(ifile.parent, odir, ifile.name)
#print(ofile.resolve())

# fitz.PDF_ANNOT_IS_INVISIBLE
# fitz.PDF_ANNOT_IS_HIDDEN
# fitz.PDF_ANNOT_IS_PRINT
# fitz.PDF_ANNOT_IS_NO_VIEW

# Rules for PDF/A Conformance check:
# https://docs.verapdf.org/validation/pdfa-part1/
# except fitz.PDF_ANNOT_IS_PRINT, setting any of the above bits 
# will result in file is not validated as PDF/A
# https://avepdf.com/pdfa-validation

doc = fitz.open(ifile.resolve())
for page in doc:
	lnk = page.firstLink
	while lnk:
		ofl = get_flags(lnk)
		nfl = set_flags(lnk, fitz.PDF_ANNOT_IS_PRINT)
		print(f"uri: {lnk.uri} - xref: {lnk.xref} - oldFlag: {ofl} - newFlag: {nfl}")
		lnk = lnk.next
#
ofile.mkdir(parents=True, exist_ok=True)
doc.save(ofile.resolve(), encryption=fitz.PDF_ENCRYPT_KEEP)
doc.close()

```

**Comment by JorjMcKie** [comment]
>  overwrite newFileName file, even if it is already exist?

This is already the case.

**Comment by Mark-Joy** [comment]
My bad. the error comes from mkdir if the file inside is already exist. I changed it to: 
`os.makedirs(ofile.parent, exist_ok=True)`

**Comment by JorjMcKie** [comment]
New vesion 1.18.16 uploaded to [PyPI](https://pypi.org/project/PyMuPDF/).
