### ISSUE TITLE
AttributeError: 'Document' object has no attribute 'get_toc'

### ISSUE THREAD

**Issue by vinodindia** [pymupdf/PyMuPDF#1209]
Hi,
## issue Description
I'm facing "AttributeError: 'Document' object has no attribute 'get_toc'" error while trying to read the table of contents in following environment,

## To Reproduce (mandatory)
can be reproduced with the following lines of code

import fitz
PDF_file = 'test1.pdf'
doc = fitz.open(PDF_file)
toc = doc.get_toc()

## Expected behavior (optional)
Expecting to get the list of TOC with indent level, title and page number

## Your configuration (mandatory)
 - Operating system, Windows-10 Pro (Version 20H2) 64 bit
 - PyMuPDF 1.18.0: Python bindings for the MuPDF 1.18.0 library.
 - Version date: 2020-10-06 07:15:59.
 - Built for Python 3.6 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
Your version is 16 levels older than the current one! So you must either upgrade or consult documentation for your level.
At that time it was `getToC`.

**Comment by vinodindia** [comment]
oh sorry and thank you @JorjMcKie. is it same for pymupdf 1.17 or can you share me the link of document for PyMuPdf 1.17

**Comment by JorjMcKie** [comment]
v1.17.x should do it - at least roughly.
I just activated v1.18.0 on Read the Docs, so you *should* be able to access it there.

**Comment by vinodindia** [comment]
great. Thanks..!
