### ISSUE TITLE
AttributeError when calling _getXrefStream

### ISSUE THREAD

**Issue by chvolk** [pymupdf/PyMuPDF#1218]
_**Please provide all mandatory information!**_

## Bug description
When calling the document._getXrefStream function, you receive an attribute error about a document not having an attribute called _getXrefStream 

## To Reproduce
Open a pdf with fitz and try to run _getXrefStream 

## Log 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Document' object has no attribute '_getXrefStream'

## Configuration
 - 64 bit Windows
 - 64 bt Python 3.8
 - PyMuPDF latest

**Comment by chvolk** [comment]
Function name has been changed! Closing

**Comment by budgester** [comment]
at the function was changed to ? 

> Function name has been changed! Closing

Is there any clue on what the function name changed to ?

**Comment by JorjMcKie** [comment]
@budgester - `Document.xref_stream()`

**Comment by JorjMcKie** [comment]
There is an own section in the documentation about [deprecated names](https://pymupdf.readthedocs.io/en/latest/znames.html) which elaborates on the reasons for and the results of a major renaming effort.

**Comment by budgester** [comment]
@JorjMcKie thanks, we've been going through that doc and updating our code, but `_getXrefStream` is not referenced anywhere in there, just xrefSteam -> xref_stream.

At least anyone googling should find this thread. Once again many thanks.
