### ISSUE TITLE
Tests not included in pypi sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [pymupdf/PyMuPDF#1227]
Hi, I'm packaging python-pymupdf for Arch Linux. Currently I am using a github generated tarball to be able to run tests (as pypi releases are seemingly not created from tags, the pypi version and tag in this repository may drift apart - see #1226 ).
For downstream distributions and users building from pypi sdist tarballs it would be beneficial to be able to also run tests.

## Describe the bug (mandatory)
There are no tests provided with the sdist tarball on pypi.org.

## To Reproduce (mandatory)
1. Download sdist tarball from pypi.org, extract it and cd into the directory
2. `python setup.py build`
3. `pytest -v`

## Expected behavior (optional)
The sdist tarball contains all necessary files to run tests against the built project.

## Screenshots (optional)
n/a

## Your configuration (mandatory)
 - Arch Linux, x86_64
 - Python 3.9.6, x86_64
 - PyMuPDF >= 1.18.16, installation method (**generated** from source)

## Additional context (optional)
For downstream distribution packaging purposes, many Linux distributions choose to run unit tests (and integration tests where applicable/possible) in their packaging infrastructure, when packaging Python packages. This ensures, that the packages can be built and function within the existing Python ecosystem.

**Comment by JorjMcKie** [comment]
No problem, will include this enhancement in the next version.

**Comment by JorjMcKie** [comment]
new version 1.18.18 now on PyPI

**Comment by dvzrv** [comment]
\o/

... and updated!
