### ISSUE TITLE
Inline images extraction

### ISSUE THREAD

**Issue by maiiabocharova** [pymupdf/PyMuPDF#1230]
There are some small pictures in my PDFs and I am not able to extract them with page.getImageList() (it returns the empty list). Can you please recommend me what I can do to extract those images, maybe another library? I need those images very much)

**Comment by JorjMcKie** [comment]
If this happens, you
1. **_either_** are not looking at images, but at so-called drawings
2. **_or_** are looking at PDF "inline" images.

**_Drawings_** can be extracted via `page.get_drawings()` / `page.get_cdrawings()`. This is a list of dictionaries. Each dict represents a number of interconnected elementary draw commands: lines, curves, rectangles or quads.

Inline images are only contained in the internal page command source (the `/Contents` object(s)) - nowhere else. Method `page.get_text("dict")` (or "rawdict") contains all images on page - inline and others. Each image occurence occurs as many times as it is shown.
