### ISSUE TITLE
Don't want to extract invisible text.

### ISSUE THREAD

**Issue by vijuc895** [pymupdf/PyMuPDF#1232]
I am extracting text from a pdf but I want to extract only visible text and ignore the invisible text. when I reprint the pdf using pdfcairo then that invisible text is gone. but I don't want to use another dependency so is there any parameter that help me to ignore these invisible text.

**Comment by vijuc895** [comment]
Hi @JorjMcKie ,

I want to understand how do you determine the opacity and color for text in _gettexttrace(). Actually I tried this function using above so I get (0,0,0) as color for hidden text and when I am using pdfbox pdf debugger which give us pdf syntax then I don't have any color for hidden text (rg is used to define color in pdf syntax). I am also attaching screenshot for your reference . Here hidden text is `Current Cost`. 
<img width="185" alt="Screenshot 2021-09-15 at 12 08 14 AM" src="https://user-images.githubusercontent.com/43551239/133316203-39f6b591-e873-4e42-be4b-37170a3b9e1e.png">
<img width="459" alt="Screenshot 2021-09-15 at 12 09 00 AM" src="https://user-images.githubusercontent.com/43551239/133316212-c51f5435-e539-435f-97de-7d784817f70b.png">
<img width="625" alt="Screenshot 2021-09-15 at 12 17 41 AM" src="https://user-images.githubusercontent.com/43551239/133316279-20a1eb11-4361-4198-8e8c-9cebc4d4f045.png">

**Comment by JorjMcKie** [comment]
> how do you determine the opacity and color for text in _gettexttrace()

I believe I wrote it:
This method works for all document type, not just PDF. So I do not look into PDF source text as you showed it in your post.
The method is based on a MuPDF "device": whatever it gives me as values for opacity, text color and what not, will be returned by the method. See file `helper_devices.i` in the source. Specifically for color, see these lines
![grafik](https://user-images.githubusercontent.com/8290722/133377440-bae2a8b3-d6ad-47cd-8241-cabb067b6842.png)

So, if the device wouldn't have returned colorspace.n = 3 and color = (0,0,0), then those values would have contained white as color.

**Comment by JorjMcKie** [comment]
Also, the absence of color spec in a text object does not mean it is hidden. This causes "text1" be shown in black:
```
q
BT
1 0 0 1 100 742 Tm
/helv 11 Tf [<7465787431>]TJ
ET
Q
```

**Comment by vijuc895** [comment]
According to you, if the device wouldn't have returned colorspace.n = 3 and color = (0,0,0), then those values must have contained white as color right?? 

Then in _get_texttrace() I should get color as (1,1,1) for Current Cost. Agreed?

**Comment by JorjMcKie** [comment]
Almost: it would have been `(1,)` or even just `1`.

**Comment by vijuc895** [comment]
But in above case of Current Cost I am getting (0,) and it doesn't have colorspace.n = 3 and color = (0,0,0)

**Comment by JorjMcKie** [comment]
Acccording to your trace output it is `1.0 0 0 (0, 0, 0)`.

**Comment by JorjMcKie** [comment]
But the main point is: if you look at the C code you see that colorspace and color **_have_** been provided.
