### ISSUE TITLE
Facing Issue with InsertText()

### ISSUE THREAD

**Issue by vijuc895** [pymupdf/PyMuPDF#1239]
Hello,

I am using insertText() to add own footer on pdf page using the below code,

pagesize = doc.loadPage(0).MediaBox
q = fitz.Point(5, pagesize.y1 - 5)
doc[0].insertText(q, "hello, footer", fontsize=3)

It is unable to write any text with above code, but when I below code it works.

pagesize = doc.loadPage(0).MediaBox
q = fitz.Point(5, 2*pagesize.y1 - 5)
doc[0].insertText(q, "hello, footer", fontsize=3)

The difference is that I am changing the y-coordinate. But why is happening. Any idea??

**Comment by JorjMcKie** [comment]
Probably one of [these](https://pymupdf.readthedocs.io/en/latest/faq.html#misplaced-item-insertions-on-pdf-pages) cases.
Try a `page.clean_contents()` before you insert something.

**Comment by vijuc895** [comment]
Thanks a lot. It worked.
