### ISSUE TITLE
Added header to file on save breaks support of pdf drivers

### ISSUE THREAD

**Issue by rsantina** [pymupdf/PyMuPDF#1242]
## Describe the bug (mandatory)
On Document save we get additional information in the beginning and end of the file which breaks support with plotters

**--c68ad51d5c76fd2d8024f7aa3ccfb535
Content-Disposition: form-data; name="X.pdf"; filename="bea464e9-0b4a-45e0-be73-267fbe0fd5f0.pdf"**
%PDF-1.3

and on the end
%%EOF

**--c68ad51d5c76fd2d8024f7aa3ccfb535--**

## To Reproduce (mandatory)
document = fitz.open(src_pdf_filename)
....
page.insertImage(img_rect, filename=img_filename)
...
document.save(dst_pdf_filename, garbage=4, deflate=True)

## Expected behavior (optional)
ability to not include these additional lines which breaks support for some drivers

## Your configuration (mandatory)
 - Operating system: Win 10 x64
 - Python version: 3.9.6
 - PyMuPDF version: wheel 1.18.17

**Comment by JorjMcKie** [comment]
> ability to not include these additional lines which breaks support for some drivers

I am lost!
A PDF **_must start and end_** with those lines! This is how a file is identified as a PDF.
Did you really mean it like that?

**Comment by rsantina** [comment]
--c68ad51d5c76fd2d8024f7aa3ccfb535
Content-Disposition: form-data; name="X.pdf"; filename="bea464e9-0b4a-45e0-be73-267fbe0fd5f0.pdf"
....
--c68ad51d5c76fd2d8024f7aa3ccfb535--

I mean these lines 

the pdf needs to start with 
%PDF-1.3

**Comment by JorjMcKie** [comment]
to be clear:
I am talking about ``%%PDF-1.3`` and ``%%EOF``. The other stuff, like ``--c68ad51d5c76fd2d8024f7aa3ccfb535--``, comes from somewhere else - not PyMuPDF.

**Comment by rsantina** [comment]
The file is created via document.save function; where could they be generated from ?

**Comment by JorjMcKie** [comment]
> where could they be generated from ?

This has **_never ever happened_** before and would otherwise have broken all the scripts of thousands of other users.
Because you did not provide complete mandatory information for a bug, there is no way to answer this question.
Please provide material to reproduce the error and I will have a look.

**Comment by rsantina** [comment]
verified that the issue is not from pymupdf; another api is interfering. Sorry for the issue and thanks for the prompt reply.

**Comment by JorjMcKie** [comment]
>  Sorry for the issue ...

No need to sorry! Every detected bug is a chance to improve.
