### ISSUE TITLE
extract_font is not working as expected.

### ISSUE THREAD

**Issue by victor-ab** [pymupdf/PyMuPDF#1246]
## Describe the bug
`extract_font` is not working as described in the [docs](https://pymupdf.readthedocs.io/en/latest/functions.html#Document.extract_font).
```python
>>> doc.extract_font(xref)
('ArialNarrow,Bold', 'n/a', 'TrueType', b'')
```

The docs says: 
```
Return details on error:
(“”, “”, “”, b””) – invalid xref or xref is not a (valid) font object.
(basename, “n/a”, “Type1”, b””) – basename is one of the PDF Base 14 Fonts, which cannot be extracted.
```
But no `Arial` nor `ArialNarrow,Bold` is in `fitz.Base14_fontdict`. It also can't be created with `fitz.Font('ArialNarrow,Bold')`

## To Reproduce
`doc.extract_font(xref)`

## Your configuration
```
3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:04:36) [MSC v.1916 64 bit (AMD64)] 
 win32 
 
PyMuPDF 1.18.14: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-06-01 08:11:38.
Built for Python 3.8 on win32 (64-bit).
```

**Comment by JorjMcKie** [comment]
This only is a misleading wording in the docu: there are more fonts than just Base-14 which are not embedded and thus cannot be extracted.

**Comment by JorjMcKie** [comment]
I will reword in the next docu version.
