### ISSUE TITLE
half-width character display bug！

### ISSUE THREAD

**Issue by heyhumor** [pymupdf/PyMuPDF#1247]
## Describe the bug 
Recently, I find a bug with function [ Page.add_freetext_annot() ]. 
When i put text with half-width character, just like '9999ｷ', '9999ｳ' or '9999ﾀ', the number '9999' will display with full-with mode.
But when i double click with this freetext annotation , It's back to normal, confused a lot.

## Code
page.add_freetext_annot(rect=fitz.Rect(353, 687, 365, 750), text='9999ﾀ', align=1, rotate=90,
                                        fontname='HeIt', fontsize=12, fill_color=(1, 0.75, 0.80))
![2021-09-09_083314](https://user-images.githubusercontent.com/52818042/132603251-30b92671-f730-4437-8ff5-e0a35e41be18.png)

**Comment by heyhumor** [comment]
Sorry i add one thing, the character 'ﾀ' above is Janpanese, And this bug is not with fonttype, i tried all fonttype.
I just need the number display normal, please give me some advice , thanks!

**Comment by JorjMcKie** [comment]
This is not a bug:
For FreeText annots, MuPDF supports non-embedded fonts only: Base-14 and CJK. As explained [here](https://pymupdf.readthedocs.io/en/latest/faq.html#changing-annotations-unexpected-behaviour), surprising behaviour can occur if you access / update annotations with a different tool than the one you used for creating them.
As you wrote, you "double clicked" the annot. This will have happened in a PDF viewer different from MuPDF (maybe Adobe Acrobat or something else), so this effect is inevitable.
MuPDF's internal logic for creating the annotation works roughly like this:
* it tries to minimize the fonts used overall
* if encountering Japanese, it will add non-embeddable font "Mincho" to the annot, similar is true for Korean and Chinese
* if no character is unsupported by one of the CJK fonts, it will not include "helv" - even if you specify it
* if your annot text starts with some char unsupported by CJK, "helv" will be used as a start and only be switched to a CJK font when required. After this it will stay with the current font as long as possible, etc.

Look at this snippet to see this work:
```python
import fitz

doc = fitz.open()
page = doc.new_page()
r1 = fitz.Rect(100, 100, 300, 120)
r2 = fitz.Rect(100, 120, 300, 140)
t1 = "9999ﾀ"  # all chars are supported by font "Mincho" (Japanese)
t2 = "x9999ﾀ"  # starts with a char unsupported by Mincho
page.add_freetext_annot(r1, t1, fontname="helv")
page.add_freetext_annot(r2, t2, fontname="helv")
doc.ez_save(__file__.replace(".py", ".pdf"), pretty=True)
```
This will produce the following:
![grafik](https://user-images.githubusercontent.com/8290722/132633574-ed1e3348-b8d0-487e-929f-c55dcbc81829.png)

When looking at the PDF "source" of the annotations, we will see this:
```postscript
>>> a1 = page.first_annot
>>> a2 = a1.next
>>> print(a1._getAP().decode())
0 w
0 0 200 20 re
W
n
BT
0 0 0 rg
0 24.8 Td
0 -14.400001 Td
/Mincho 12 Tf
<0039003900390039ff80> Tj  % ==> all text in Mincho!
ET

>>> print(a2._getAP().decode())
0 w
0 0 200 20 re
W
n
BT
0 0 0 rg
0 24.8 Td
0 -14.400001 Td
/Helv 12 Tf
(x9999) Tj  % ==> start text in Helv
/Mincho 12 Tf
<ff80> Tj  % ==> switch to Mincho when we must
ET

>>> 
```
