### ISSUE TITLE
Can't remove PDF_FIELD_IS_READ_ONLY from widget

### ISSUE THREAD

**Issue by gregersn** [pymupdf/PyMuPDF#1257]
Trying to loop through all widgets in a PDF, and make fields that are previously marked as read only, editable.

I have a hard time making an actual sample, both because I am not sure what should have worked, and because I am fumbling in the dark here.  

But, I read in a PDF with read-only fields, I have tried things like
```
for page in pdf:
        widgets: Iterable[fitz.Widget] = page.widgets()
        for field in widgets:
            if fitz.PDF_FIELD_IS_READ_ONLY & field.field_flags:
                print("Field is readonly")
                field.field_flags = field.field_flags - fitz.PDF_FIELD_IS_READ_ONLY
            field.update()
pdf.save("filename.pdf")
```

When I then reopen the PDF, the fields are still read only.
If I try the opposite, to set all fields read only, that works.

PyMuPDF==1.18.15

**Comment by JorjMcKie** [comment]
Error confirmed! Will be corrected in next version.

**Comment by JorjMcKie** [comment]
new version 1.18.18 now on PyPI
