### ISSUE TITLE
Installing 1.18.18 from PyPI fails with a long error

### ISSUE THREAD

**Issue by mara004** [pymupdf/PyMuPDF#1264]
## Description
Installation fails with a long error. Tail appended:
[pymupdf_install.txt](https://github.com/pymupdf/PyMuPDF/files/7179281/pymupdf_install.txt)

## To Reproduce
`python3 -m pip install -U pymupdf`

## Your configuration
 - KDE Neon 20.04 (64 bit)
 - PyMuPDF 1.18.18
 - Installation from PyPI

**Comment by mara004** [comment]
There apparently is an attempt to build the wheel locally:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymupdf in ./.local/lib/python3.8/site-packages (1.18.17)
Collecting pymupdf
  Using cached PyMuPDF-1.18.18.tar.gz (2.2 MB)
Building wheels for collected packages: pymupdf
  Building wheel for pymupdf (setup.py) ...
```

**Comment by mara004** [comment]
1.18.17 installs correctly, however.

**Comment by JorjMcKie** [comment]
Not a bug!
I am uploading a new version, so there is some time interval until all the wheels have arrived on PyPI as well.
Try again in an hour or so.

**Comment by JorjMcKie** [comment]
wheel now online

**Comment by mara004** [comment]
Ok, sorry for the noise :)

**Comment by mara004** [comment]
I confirm it now installs correctly. I just got the release rss feed notification a bit too early...

**Comment by JorjMcKie** [comment]
I have an extremely slow internet connection, so the time interval between the 1st and the last part uploading to PyPI there can be 1 or 2 hours ... if things have a bad day.

**Comment by mara004** [comment]
Oh, I see... :/
