### ISSUE TITLE
Strange problem when page.cropbox changed

### ISSUE THREAD

**Issue by mlove4u** [pymupdf/PyMuPDF#1268]
OS: macOS 10.15.7
PyMuPDF: 1.18.17
Python: 3.7.4

### My use case:
1. change the value of page.cropbox to trimbox
2. render a image from pdf page.  Rendering area -->page.cropbox(trimbox)

### Problem:
**page.get_pixmap(clip=page.mediabox)** and **page.get_pixmap(clip=page.cropbox)** does not crop the right area as expected.
Please take a look at the attached png file. Sorry for my poor English. Thanks.
Here is my code:
```
import fitz
from PIL import Image


def show_pm(pm, file_name):
    pil = Image.frombuffer('RGB', (pm.width, pm.height), pm.samples)
    pil.save(file_name)
    pil.show()


doc = fitz.open("trimbox.pdf")
page = doc[0]
#mat1 = page.transformation_matrix
#
print("old page.cropbox: ", page.cropbox)
# >> old page.cropbox:  Rect(0.0, 0.0, 400.0, 200.0)
pm = page.get_pixmap()  # clip(default)=page.cropbox
show_pm(pm, "0_page.cropbox.png")
#
pm = page.get_pixmap(clip=page.mediabox)
show_pm(pm, "0_page.mediabox.png")
#
#
doc.xref_set_key(page.xref, "CropBox", '[50 50 350 150]')  # change cropbox
print("new page.cropbox: ", page.cropbox)
# >> new page.cropbox:  Rect(50.0, 50.0, 350.0, 150.0)
#mat2 = page.transformation_matrix
pm = page.get_pixmap(clip=page.mediabox)  # page.mediabox.irect
show_pm(pm, "1_page.mediabox.png")
#
pm = page.get_pixmap(clip=page.cropbox)
show_pm(pm, "1_page.cropbox.png")
#
pm = page.get_pixmap()
show_pm(pm, "1_.png")

```
![pngs](https://user-images.githubusercontent.com/18019314/133719595-17415e91-7ca3-4a4e-b898-7a541a485e9f.png)
[trimbox.pdf](https://github.com/pymupdf/PyMuPDF/files/7182385/trimbox.pdf)

**Comment by JorjMcKie** [comment]
I will have a look.
Meanwhile I will convert htis to a discussion.
