### ISSUE TITLE
Installation from sources: Expose include_dirs and library_dirs using environment variables

### ISSUE THREAD

**Issue by Mark-Joy** [pymupdf/PyMuPDF#1273]
Can we expose `include_dirs` and `library_dirs` using environments variable?

Everytime I install new version of Pymupdf, I have to modify `setup.py` for those above folders. Instead, I propose something like:

```
prefix=os.environ["PREFIX"]
mupdfPath=os.environ["PYMUPDF_MUPDF_SOURCE_PATH"]
```

```
# check the platform
if sys.platform.startswith("linux") or "gnu" in sys.platform:
    module = Extension(
        "fitz._fitz",  # name of the module
        ["fitz/fitz.i"],
        include_dirs=[  # we need the path of the MuPDF headers
            prefix+"/include",
            prefix+"/include/mupdf",
            prefix+"/include/freetype2",
            #mupdfPath+"/include/mupdf",
            #mupdfPath+"/thirdparty/freetype/include",
        ],
        libraries=load_libraries(),
    )
```

It works for me even without above `mupdfPath` variable.

Maybe we can use `prefix`,` prefix1`, `prefix2` if we need more than one `prefix`.

By setting environment variables, we don't have to manually edit `setup.py`.

**Comment by JorjMcKie** [comment]
Interesting idea! Thank you!
Allow me to suggest a variant:
How about storing a JSON filename in `os.environ` like `PYMUPDFDIRS.json`. This would consist of a dictionary with keys "include_dirs" and "library_dirs". Both resp. values would be lists of directories - of arbitrary length.

**Comment by Mark-Joy** [comment]
That's a better idea!! Just set it once and forget everything :)

**Comment by JorjMcKie** [comment]
Ok, fine. I think I will do it then for th next version.

**Comment by JorjMcKie** [comment]
I dared to **_already now_** modify the setup present in this repo. Alongside what we discussed, there are also some other adjustments, see my comments in #972 a few minutes ago.
For the most part I am not able to test this on my machine, so if you want you might try something out yourself ...

**Comment by Mark-Joy** [comment]
Thank you very much for your excellent work!
Sorry for my late reply, I got carried away with something.
`PYMUPDF-DIRS` env variable is not a valid variable name because of its hyphen symbol. I changed it to `PYMUPDF_DIRS` and got it working.
Thanks again for implementing this idea.
