### ISSUE TITLE
showPDFpage with garbled characters

### ISSUE THREAD

**Issue by malizheng** [pymupdf/PyMuPDF#1291]
I want to cut down a PDF, and found that the characters in the generated PDF are all messed up.
`doc = fitz.open()  `
`cur_pdf = fitz.open("1.pdf")`
`for index in range(0,3):`
`    cur_page=cur_pdf[index]`
`    page=doc.new_page(width=cur_page.rect.width, height=cur_page.rect.height)`
`    r1 = fitz.Rect(0, 0, cur_page.rect.width, cur_page.rect.height) `
`    page.showPDFpage(r1, cur_pdf, index, rotate=0) `
`doc.save("2.pdf",garbage=4, clean=1,deflate=True)`
`doc.close()`
![1632730007894](https://user-images.githubusercontent.com/14052596/134869133-74287378-9b55-421c-9d4f-10fb2a4bd15c.jpg)
[2.pdf](https://github.com/pymupdf/PyMuPDF/files/7234468/2.pdf)

[1.pdf](https://github.com/pymupdf/PyMuPDF/files/7234452/1.pdf)

**Comment by JorjMcKie** [comment]
1. You are missing **_mandatory_** information for a bug!
2. Cannot reproduce: evrything looks perfect for me.
3. For "cutting down" a PDF, `show_pdf_page()` is not the best method. Why not use `insert_pdf`? You would e.g. not need to mess around with source page size and such.

**Comment by malizheng** [comment]
Thank you very much for your reply.

##My configuration (mandatory)
 -Macos10.14.6 
 - Python 3.7.4
 - PyMuPDF version==1.18.19, installation method (pip install pymupdf==1.18.19).
 
This problem also occurs when the original file is executed with the following code.
  `cur_pdf.convert_to_pdf()` 

Is this because my macos lacks the corresponding font?

**Comment by JorjMcKie** [comment]
I have no Mac, so cannot tell what may go wrong there. It works fine for Windows & Linux.

`convert_to_pdf` is not failsafe and can indeed go wrong e.g. if Type 3 fonts are present. There also may happen unpleasant layout effects.
If the fonts are all embedded in the PDF, it should be no problem if they are not installed in the OS - after all this is the purpose of embedding them.

Again my question: wayfon't you use `insert_pdf`?

**Comment by malizheng** [comment]
Thank you, I tried to use insert_pdf to cut down.
Earlier, I wanted to try to insert multiple pages in an empty page and cut down the PDF. I need to specify each page to a specified matrix. Insert_pdf does not seem to have a rect option.

**Comment by JorjMcKie** [comment]
> Insert_pdf does not seem to have a rect option.

No it has not. It just copies page by page.
So if you say "cut down", you actually mean to show miniature page images of the source?

**Comment by JorjMcKie** [comment]
Try [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/4-up.py) script if you like. It makes a new PDF from a source file combining every for source pages to one output page.

**Comment by malizheng** [comment]
Thank you very much, it solved my problem. I just used show_pdf_page instead of showPDFpage.

**Comment by JorjMcKie** [comment]
But this is weird: the two are synonyms for the same method!
