### ISSUE TITLE
Unpropagated exception when opening corrupted file

### ISSUE THREAD

**Issue by timurlenk07** [pymupdf/PyMuPDF#1292]
## Describe the bug (mandatory)
When opening a **corrupted file**, PyMuPDF fails to propagate the underlying C exception.

## To Reproduce (mandatory)
```python
import fitz
from pathlib import Path

correct = Path('correct.pdf')
corrupted = Path('corrupted.pdf')
corrupted.write_bytes(correct.read_bytes()[20:])

try:
    doc = fitz.Document(str(corrupted))
except:
    print("This is not a bug")
```

Final output is: `mupdf: cannot recognize version marker`

## Your configuration (mandatory)
 - Ubuntu 20
 - Python 3.8
 - PyMuPDF v1.18.19 (_latest_)

**Comment by JorjMcKie** [comment]
MuPDF does not raise an exception in this case - so why should PyMuPDF do it instead?

**Comment by timurlenk07** [comment]
I would like to handle the opening of corrupted pdf files received over http requests. In its current form of the package, I have no choice but to let the server crash because of an unhandlable scenario.

Do you maybe have some suggestions on my use-case?

**Comment by JorjMcKie** [comment]
MuPDF executes a repair and is able to recover some objects in the case of my test PDF:
```python
>>> len(doc)
0
>>> doc.is_repaired
True
>>> print(doc.xref_object(-1))
<<
  /Size 59
  /Root 2 0 R
  /ID [ <1C44DAC63F07DB41C78E466126F697FC> <56BF67F3C1590EB93302B46E8C129E40> ]
>>
>>> 
```

**Comment by timurlenk07** [comment]
Oh sorry, I did not realize PyMuPDF did return a Document instance and thought the message was an unhandled exception.

**Comment by JorjMcKie** [comment]
You can also check whether ther are any pages at all: ``doc.page_count``.
Also see this:
```python
>>> print(fitz.TOOLS.mupdf_warnings())
cannot recognize version marker
trying to repair broken xref
repairing PDF document
>>> 
```
