### ISSUE TITLE
Support temporary directory in `subset_fonts`

### ISSUE THREAD

**Issue by manycoding** [pymupdf/PyMuPDF#1293]
**Is your feature request related to a problem? Please describe.**
[subset_fonts](https://pymupdf.readthedocs.io/en/latest/document.html#Document.subset_fonts) creates temporary files in the current directory https://github.com/pymupdf/PyMuPDF/blob/master/fitz/utils.py#L4977  which is a problem when the directory is not writable. For example, if used in AWS Lambda, only `tmp` is writable.

**Describe the solution you'd like**
Use system's temp folder https://docs.python.org/3/library/tempfile.html

**Describe alternatives you've considered**
Path to tmp dir parameter

**Comment by JorjMcKie** [comment]
Ok - accepted.
