### ISSUE TITLE
Bookmark actions

### ISSUE THREAD

**Issue by yok0** [pymupdf/PyMuPDF#1300]
I just have a question as I went through the docs back and forward and could not find this option.

I have a big pdf with lots of bookmarks. Unfortunately when bookmark is clicked the pdf changes it's zoom to "Fit Page"
and it must be 100%. The way we do it now is to change initial view to 100% and set bookmark action to "Inherit zoom".
This works perfectly but changing hundreds of bookmarks manually is just ridiculous. 

Does PyMuPDF allows change of these properties ?

![image](https://user-images.githubusercontent.com/6692754/135443977-6ea52b1a-ab6a-4cce-87ff-798b9361ac72.png)

![image](https://user-images.githubusercontent.com/6692754/135444081-bd7e65c1-a875-48c5-b15c-6d981988dd6f.png)

**Comment by JorjMcKie** [comment]
> Does PyMuPDF allows change of these properties?

In principle, yes (ever heard of Radio Erivan?).
The API is explained [here](https://pymupdf.readthedocs.io/en/latest/document.html#Document.set_toc_item).
As per view zoom level, I only support the PDF format ``/XYZ x y z``, where (x, y) is the top-left coordinate on the page and z is the zoom factor: 1 = 100%. Zoom = 0 means "not specified".
Let's see if that is ok for you.
Please do not hesitate to ask if you run into problems.

> I am going to move this to **_Discussions_**.
