### ISSUE TITLE
error get_textbox under linux

### ISSUE THREAD

**Issue by Larbo53** [pymupdf/PyMuPDF#1308]
Good morning,
I have just transferred my program to linux (linux mint 64 bit v20.2) and have the following error (see attached file).
Thank you.

Sincerely

_**Please provide all mandatory information!**_

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `p
[test_fonctions_recup_z_V0.txt](https://github.com/pymupdf/PyMuPDF/files/7273357/test_fonctions_recup_z_V0.txt)
rint(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).
![Lien vers python_pymupdf3102021](https://user-images.githubusercontent.com/87364492/135754557-b432f6ab-f611-4d02-ab99-5767b9f6673f.png)

**Comment by JorjMcKie** [comment]
what is the pymupdf version on Linux?
this is part of the mandatory information

**Comment by Larbo53** [comment]
how to know this information?

**Comment by Larbo53** [comment]
with Synaptic, it's fitz 1.16.11-1

**Comment by JorjMcKie** [comment]
Hm? ``print(fitz.__doc__)`` ... as the bug form tells you.

**Comment by Larbo53** [comment]
I just installed version 1.18.19 and it works.
Thank you.
thank you.
