### ISSUE TITLE
Discard cropped / hidden content ("sanitize") or extract cropped images instead of raw images

### ISSUE THREAD

**Issue by quanvinh** [pymupdf/PyMuPDF#1309]
My PDF has tons of cropped images and AFAIK PyMuPDF only allows me to extract raw (uncropped) ones.

I was wondering if any of the following is possible?

a. Discard hidden / cropped part of all images (similar to "Redact" -> "Sanitize" in Acrobat, without rasterizing) prior to extracting.
b. Obtain cropbox of each images so I can crop the extracted raw images using another library.
c. (Preferrably) Ignore cropped data during extracting (aka extract just the cropped images instead of raw ones).

**Comment by JorjMcKie** [comment]
You need to know which part of the image is covered by other stuff. This would be a sequence of rectangles which have a non-empty intersection with the image bbox on the page.
Then use the image's transformation matrix to compute those intersections in original image coordinates. For all those intersections, empty the resp. rectangle in the image pixmap (i.e. set it to white).
Method `page.get_image_bbox(item, transform=True)` will return that transforation matrix alongside the image bbox.
Then look at [this](https://pymupdf.readthedocs.io/en/latest/app4.html#image-transformation-matrix) for details on transformation matrix.
* Let ``pix`` be the pixmap of the extracted image. Then we define matrix `expand = fitz.Matrix(pix.width, 0, 0, pix.height, 0, 0)`.
* Let ``intersect`` be an intersection area on the page in page coordinates.
* Then ``xrect = (intersect * ~transform * expand).irect`` is an area in the pixmap we need to blank out.
* Depending in the pixmap colorspace (GRAY, RGB, CMYK, with or without alpha), we use the correct pixel value for "white" and execute `pix.set_rect(xrect, white)`. If you have for example an RGB image without alpha, you would use `white = (255, 255, 255)`.

**Comment by JorjMcKie** [comment]
Also note, that there is `Pixmap.copy(sourcepix, irect)`, which lets you make sub-pixmaps of a given source pixmap only containing the ``irect`` part.
