### ISSUE TITLE
mupdf 1.19.0 builds

### ISSUE THREAD

**Issue by MerlijnWajer** [pymupdf/PyMuPDF#1313]
No particular rush, but it would be great to get (test) builds of MuPDF 1.19.0. I was going to ask for a build of the latest RC (to search for potential issues), but I see they just released 1.19.0.

I'm sure this is already in planning, but please let me know if you need any testers. I'd be happy to test.

Thanks!

**Comment by JorjMcKie** [comment]
👍😎
I am already testing it on Windows since a few days.
Thank you very much for your offer - this is more than welcome!
You have a Linux system I remember, Python 3.8.
I should be able to prepare a wheel for you by tomorrow.

**Comment by MerlijnWajer** [comment]
Sounds great, thanks!

**Comment by JorjMcKie** [comment]
Guys, I am trying to compile on Linux.
It formally works - on Github action and also locally. But when I import I am seeing this:
```python
Python 3.8.12 (default, Sep 10 2021, 00:16:05)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.27.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import fitz
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5ebe19763ce1> in <module>
----> 1 import fitz

/usr/local/lib/python3.8/dist-packages/fitz/__init__.py in <module>
      8 # ------------------------------------------------------------------------
      9 import sys
---> 10 from fitz.fitz import *
     11
     12 # define the supported colorspaces for convenience

/usr/local/lib/python3.8/dist-packages/fitz/fitz.py in <module>
     13 # Import the low-level C/C++ module
     14 if __package__ or "." in __name__:
---> 15     from . import _fitz
     16 else:
     17     import _fitz

ImportError: /usr/local/lib/python3.8/dist-packages/fitz/_fitz.cpython-38-x86_64-linux-gnu.so: undefined symbol:
_ZTVN10__cxxabiv117__class_type_infoE
In [2]:
```
Does this ring any bells?
It seems to be a symbol connected to C++ libraries. C++ code is part of MuPDF this time because of integrated support of Tesseract, which is written in C++.
Any idea what I can do?

**Comment by JorjMcKie** [comment]
Seems the reason is that `setup.py` invokes the `gcc` compiler, where it instead should use `c++`.
How do I achieve that?

**Comment by MerlijnWajer** [comment]
I think this might be the solution: https://stackoverflow.com/questions/47890484/undefined-symbol-during-dlopen

**Comment by JorjMcKie** [comment]
Try this one, it's newer anyway: https://github.com/JorjMcKie/py-mupdf/actions/runs/1339456713

**Comment by mjg** [comment]
Since you've been testing: Do you have examples for the new OCR feature? (I'm the Fedora packager for mupdf and need to make sure mupdf has what PyMuPDF needs.)

**Comment by saetlan** [comment]
Hey, thanks for your work and quick updates !
Just hijacking this issue to let you know that I have unexpected behavior between 1.18 and 1.19 with first 2 coordinates being empty when using: 
`page.get_text("words", flags=flag)`
1.18.12
`(213.79994201660156, 21.91998291015625, 220.99993896484375, 21.931982040405273, 'text', 0, 1, 0)`
1.19
`(0.0, 0.0, 220.99993896484375, 21.931982040405273, 'text', 0, 1, 0)`
