### ISSUE TITLE
mupdf: invalid key in dict skipping bad link / annot item 0.

### ISSUE THREAD

**Issue by IbrahimGerbiqi** [pymupdf/PyMuPDF#1314]
I was trying to insert link to the **Rect** it was working well till i came across a weird URL that made a function throw error and it wailed to generate pdf on production.

The problem stands that url hase ")" in it and throws error or warning i don't know how to call it: **mupdf: invalid key in dict
skipping bad link / annot item 0.**

## To Reproduce 
URL that shows error: http://www.akm.gov.al/assets/c)-r.v.n.m.-mbrostar-cae.pdf

![image](https://user-images.githubusercontent.com/34714009/136218546-8f27e1e3-10a4-4ca4-aeef-79018e4e5ef3.png)

What would you recommend to do on this case ?

## Configuration 
 - Operating system: Ubuntu 20.04
 - Python version, 3.8.10 64 bit
 - PyMuPDF version, installation method: 1.18.19, pip

**Comment by JorjMcKie** [comment]
Ah I see. My code assumes that the handed URI is a valid PDF string. Which means that the reserved PDF characters are backslash-escaped. Applies to `), (, \`.
Please try to specify `fitz.get_pdf_str(yourstring)[1:-1]` instead for the time being.
I will adjust the code for the next version.

**Comment by IbrahimGerbiqi** [comment]
@JorjMcKie Thanks again for all explanation and help.
