### ISSUE TITLE
page.get_pixmap can not input params

### ISSUE THREAD

**Issue by hbh112233abc** [pymupdf/PyMuPDF#1359]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
when I use `page.get_pixmap(fitz.Matrix(4,4))`, throw an error: `TypeError: get_pixmap() takes 1 positional argument but 2 were given`
but the function `page.get_pixmap` can input some params like:
```
get_pixmap(matrix=fitz.Identity, colorspace=fitz.csRGB, clip=None, alpha=False, annots=True)
```

## To Reproduce (mandatory)
my code:
```
doc = fitz.Open('demo.pdf')
page = doc.load_page(0)
pixmap = page.get_pixmap(fitz.Matrix(4,4))
pixmap.pil_save('demo_1.jpg')
```

## Your configuration (mandatory)
 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] 
 win32

PyMuPDF 1.19.1: Python bindings for the MuPDF 1.19.0 library.
Version date: 2021-10-23 00:00:10.
Built for Python 3.7 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
This method only has keyword parameters!

**Comment by JorjMcKie** [comment]
I will update the documentation accordingly.

**Comment by hbh112233abc** [comment]
> This method only has keyword parameters!

so, must code : `page.get_pixmap(matrix=fitz.Matrix(4,4))` ??
