### ISSUE TITLE
Functions "extract_image" and "extract_font" missing in 1.19.x Document API docs

### ISSUE THREAD

**Issue by caerulescens** [pymupdf/PyMuPDF#1360]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
* Go [here](https://pymupdf.readthedocs.io/en/latest/document.html).
* CTRL+F for "extract_", and nothing is found.
* Go [here](https://github.com/pymupdf/PyMuPDF/blob/e678b836298fb19c4e5b4bbe5a96c6b76513a97e/fitz/__init__.py#L49), and the functions are missing, although they are still included in the Document API after installation.

## To Reproduce (mandatory)
N/A

## Expected behavior (optional)
* If the function is included in the Document API, then the signature, arguments, and a short description should be documented; the `extract_image` function is very useful, so someone might not know it exists. The same goes for `extract_font`. Otherwise, if it was removed due to adding a new and improved function, then what should be used as a replacement?

## Screenshots (optional)
N/A

## Your configuration (mandatory)
 - Operating system, potentially version and bitness: `debian 10`
 - Python version, bitness: `python 3.9.1`
 - PyMuPDF version, installation method (**wheel** or **generated** from source): `1.19.1` through PyPI.

## Additional context (optional)
N/A

**Comment by caerulescens** [comment]
Ah I see; it has been moved to [here](https://pymupdf.readthedocs.io/en/latest/functions.html#Document.extract_image). Since the function requires a `Document`, do you think it makes sense to include [here](https://pymupdf.readthedocs.io/en/latest/document.html) as well?

**Comment by JorjMcKie** [comment]
Sure, no problem.

**Comment by caerulescens** [comment]
Awesome, thanks.

**Comment by JorjMcKie** [comment]
Done, next version of documentation will reflect your request.
