### ISSUE TITLE
[Question] Differences between PyMuPDF blocks extraction in version 1.17 and 1.18

### ISSUE THREAD

**Issue by Lary15** [pymupdf/PyMuPDF#1361]
I am working on an application that currently uses the 1.17.0 version of the pymupdf lib. However, recently I had a demand that would require to extract text within a rectangle object, a feature present in the 1.18.0 version of pymupdf. So I changed the lib version but encountered some differences in regards to the blocks extraction feature in both versions.

For example, the text described on this screenshot: 
![image](https://user-images.githubusercontent.com/43443548/139743555-806cae26-4412-4be8-963c-e0bc2db3b7b1.png)

On the 1.17.0 PyMuPDF version, is extracted as a block like this:
```python
(119.05406188964844, 189.93833923339844, 726.0125732421875, 207.86404418945312, 'ANO XLVIX EDIÇÃO EXTRA No- 3\nBRASÍLIA - DF, TERÇA-FEIRA, 21 DE JANEIRO DE 2020', 1, 0)
```
And on the 1.18.0 PyMuPDF, like this:
```python
(119.05406188964844, 191.70281982421875, 726.0125732421875, 207.86404418945312, 'ANO XLVIX EDIÇÃO EXTRA No-3 BRASÍLIA - DF, TERÇA-FEIRA, 21 DE JANEIRO DE 2020', 1, 0)
```
The key aspect here is the conservation of linebreaks that occurs on the 1.17.0 version and which is needed for my application.
So, in resume, I wanted to ask if there is a way to mimic this behavior that maintains linebreaks in block extraction with the 1.18.0 version?

### My configuration
 - Operating system: ManjaroLinux, 21.1.4
 - Python version: 3.8.11
 - PyMuPDF installed with pip

**Comment by JorjMcKie** [comment]
I am sure there is.
Which text extraction option do you use? It looks like `get_text("blocks")`.
The hierachy structure blocks->lines->spans is something that MuPDF creates based on whatever heuristics. It has no physical basis in the document itself.
But I am a little amazed to see that there was a change in the versions - if you use the same code. I am not aware of this.
Can you please show me the code snippet you are using? And if possible the document too - just one page.

I am going to convert this to a discussions ...
