### ISSUE TITLE
When content was extracted from content stream using doc.xref_stream(xref).decode("ISO-8859-1"), the output extracted was in uninterpretable format.

### ISSUE THREAD

**Issue by meghanaviyyapu** [pymupdf/PyMuPDF#1365]
![image](https://user-images.githubusercontent.com/36301306/140264903-edc90dc1-b1e8-4147-bbd5-d253bb640a07.png)
Can you please let me know if there is a way to extract text from stream in an interpretable format?

**Comment by meghanaviyyapu** [comment]
[table.pdf](https://github.com/pymupdf/PyMuPDF/files/7472625/table.pdf)
I have considered this PDF as input

**Comment by JorjMcKie** [comment]
This is a typical Discussions item. Let me convert it first.
