### ISSUE TITLE
Some instances of '=', '-' and 'x' are mis-parsed (as '5', '2' and '3') in (attached) PDF, even at char level in rawdict.

### ISSUE THREAD

**Issue by maspotts** [pymupdf/PyMuPDF#1371]
[testfile.pdf](https://github.com/pymupdf/PyMuPDF/files/7476948/testfile.pdf)
<img width="99" alt="Screen Shot maxi 2021-11-04 at 10 16 20 AM" src="https://user-images.githubusercontent.com/4096446/140389041-4ed257b9-03b6-4528-91d4-566b20773fea.png">
<img width="54" alt="Screen Shot maxi 2021-11-04 at 10 16 06 AM" src="https://user-images.githubusercontent.com/4096446/140389043-92f6bb5e-71f5-466b-86b7-5345348cded4.png">
<img width="127" alt="Screen Shot maxi 2021-11-04 at 10 15 36 AM" src="https://user-images.githubusercontent.com/4096446/140389044-4058736d-2534-40fc-95d5-ea19f5c65d71.png">
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
In one particular PDF I'm seeing instances of unexpected mis-parsing at the char level: '=' is parsed as '5', '-' is parsed as '2' and 'x' is parsed as '3'.  I don't know how to debug this because the characters have the value '5', '2' and '3' (respectively) even in 'rawdict' mode, so whatever is causing this (odd character codes?) is invisible to me.  In case it's fixable I'm attaching the PDF in question.

## To Reproduce (mandatory)
Create script test.py:
```
import sys
import fitz
import re

filename = sys.argv[1]
outname = sys.argv[2]
pattern = r'(?:(?<=[=(\s±])|(?<=^))-?\d*\.?\d*(?:e-?\d+)?(?=[,)%\s±-]|$)'
whitespace_pattern = r'\s+'
text_flags = None
blue = (0, 0, 1)
mat = fitz.Matrix(1, 0, 0, 1, 0, -4)

def simplify(x): return '{:,g}'.format(x)

def numbers_from_text(text):
    numbers = []

    for x in re.findall(pattern, text):
        try:
            numbers.append(float(x))
        except ValueError:
            pass

    return numbers

def highlight_numbers(page, bbox, number_string):
    r = fitz.Rect(bbox)
    page.add_highlight_annot(r)
    r.transform(mat)
    page.add_freetext_annot(r, f"{number_string}", fontsize = 5,
                            text_color = blue,
                            align = fitz.TEXT_ALIGN_CENTER)

def process_chunk(page, line, span, word):
    text = ''.join([*map(lambda x: x['c'], word)])
    sys.stderr.write(f"WORD: {text}\n")
    numbers = numbers_from_text(text)

    if numbers:
        number_string = '|'.join([*map(simplify, numbers)])
        sys.stderr.write(f"  ---> {text} ({number_string})\n")
        quad = recover_span_quad2(line['dir'], span, chars = word)
        highlight_numbers(page, quad.rect, number_string)

    return numbers

## This is my copy of fitz.recover_span_quad() with the inappropriate hasattr() check commented out.

def recover_span_quad2(line_dir: tuple, span: dict, chars: list = None) -> fitz.Quad:
    """Calculate the span quad for 'dict' / 'rawdict' text extractions.
    Notes:
        There are two execution paths:
        1. For the full span quad, the result of 'recover_quad' is returned.
        2. For the quad of a sub-list of characters, the char quads are
           computed and joined. This is only supported for the "rawdict"
           extraction option.
    Args:
        line_dir: (tuple) 'line["dir"]' of the owning line.
        span: (dict) the span.
        chars: (list, optional) sub-list of characters to consider.
    Returns:
        Quad covering selected characters.
    """
    if chars == None:  # no sub-selection
        return fitz.recover_quad(line_dir, span)
    ##if not hasattr(span, "chars"):
    ##    raise ValueError("need 'rawdict' option to sub-select chars")

    q0 = fitz.recover_char_quad(line_dir, span, chars[0])  # quad of first char
    if len(chars) > 1:  # get quad of last char
        q1 = fitz.recover_char_quad(line_dir, span, chars[-1])
    else:
        q1 = q0  # last = first

    span_ll = q0.ll  # lower-left of span quad
    span_lr = q1.lr  # lower-right of span quad
    mat0 = fitz.planish_line(span_ll, span_lr)
    # map base line to x-axis such that span_ll goes to (0, 0)
    x_lr = span_lr * mat0

    small = fitz.TOOLS.set_small_glyph_heights()  # small glyph heights?
    h = span["size"] * (1 if small else (span["ascender"] - span["descender"]))

    span_rect = fitz.Rect(0, -h, x_lr.x, 0)  # line rectangle
    span_quad = span_rect.quad  # make it a quad and:
    span_quad *= ~mat0  # rotate back and shift back
    return span_quad

def highlight_page_via_rawdict(doc):
    all_numbers = []
    for page in doc:
        page_dict = page.get_text('rawdict', flags = text_flags)
        blocks = page_dict['blocks']
        text_blocks = filter(lambda x: x['type'] == 0, blocks)
        for block in text_blocks:
            lines = block['lines']
            for line in lines:
                spans = line['spans']
                for span in spans:
                    chars = span['chars']
                    flags = span['flags']
                    bbox = span['bbox']
                    if flags & 2**0:
                        ## Eliminate superscripts.
                        page.add_strikeout_annot(fitz.Rect(bbox))
                    else:
                        ## Split this span on whitespace and extract
                        ## numbers from each chunk.
                        word = []
                        for char in chars:
                            c = char['c']
                            ##sys.stderr.write(f"CHAR: {c}\n")
                            if re.findall(whitespace_pattern, c):
                                if word:
                                    all_numbers += process_chunk(page, line, span, word)
                                    word = []
                            else:
                                word.append(char)
                        if word:
                            all_numbers += process_chunk(page, line, span, word)

    return all_numbers

doc = fitz.open(filename)
numbers = highlight_page_via_rawdict(doc)
print(numbers)
doc.save(outname)
```

2. run: python test.py testfile.pdf testout.pdf
3. open the output file (testout.pdf) in a PDF viewer and observe that all highlighted '=' chars are extracted as '5' (annotated in blue above the highlighted block), and likewise for (most) '-' ('2') and 'x' ('3').

## Expected behavior (optional)
The extracted (and highlighted) chars ('=', '-' and 'x') should be extracted and annotated as '=', '-' and 'x' (respectively).  In particular, the 'x' mis-parse can be seen in column 6 of "Table 1" on page 6, and the '=' and '-' mis-parses can be seen in column 4 of "Table 2" on page 9.

## Screenshots (optional)
Attached 3 screenshots.

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

```
>>> print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.9.5 (default, Jun 24 2021, 15:50:05)
[Clang 12.0.0 (clang-1200.0.32.29)]
 darwin

PyMuPDF 1.19.1: Python bindings for the MuPDF 1.19.0 library.
Version date: 2021-10-23 00:00:01.
Built for Python 3.9 on darwin (64-bit).
```

## Additional context (optional)
This is related to issue https://github.com/pymupdf/PyMuPDF/issues/1364 because the example includes a workaround for that issue (via a copy of `recover_span_quad()`).

I see the same mis-parsing using (eg) `get_text('words')` but am including this `get_text('rawdict')` example since it's the closest I can get to the raw data. 

I have successfully applied this example to other PDFs containing '=', '-' and 'x' without any mis-parsing, so evidently their encoding in this particular PDF is triggering the problem.

**Comment by JorjMcKie** [comment]
> encoding in this particular PDF is triggering the problem.

It is even the problem of exactly one font: "AdvPS586B", here is a list of all fonts used on all pages:
```python
>>> pprint(all_fonts)
{(235, 'cff', 'Type1', 'KLHFMH+AdvOT5ac9723a.BI', 'F9', 'WinAnsiEncoding'),
 (237, 'cff', 'Type1', 'KLHFMG+AdvPSA35E', 'F8', 'WinAnsiEncoding'),
 (241, 'cff', 'Type1', 'KLHFNI+AdvOT8649160c.B+20', 'F10', 'WinAnsiEncoding'),
 (242, 'cff', 'Type1', 'KLHFNJ+AdvPS7DA6', 'F11', 'WinAnsiEncoding'),
 (245, 'cff', 'Type1', 'KLHIAM+AdvPSA35F', 'F12', 'WinAnsiEncoding'),
 (247, 'cff', 'Type1', 'KLHOKF+AdvTT2876772e+25', 'F13', ''),
 (253, 'cff', 'Type1', 'KLOBJG+AdvP4C4E59', 'F14', ''),
 (255, 'cff', 'Type1', 'KLOMGE+AdvTT2876772e+20', 'F15', ''),
 (256, 'cff', 'Type1', 'KLOMIF+AdvTT2876772e+03', 'F16', ''),
 (273, 'cff', 'Type1', 'KLHFJA+AdvOT8649160c.B', 'F1', 'WinAnsiEncoding'),
 (274, 'cff', 'Type1', 'KLHFJB+AdvOTc999d02f', 'F2', 'WinAnsiEncoding'),
 (282, 'cff', 'Type1', 'KLHFJC+AdvOTc999d02f+20', 'F3', 'WinAnsiEncoding'),
 (283, 'cff', 'Type1', 'KLHFKD+AdvPS586B', 'F4', 'WinAnsiEncoding'),
 (287, 'cff', 'Type1', 'KLHFKE+AdvOT05d4dae9.I', 'F5', 'WinAnsiEncoding'),
 (292, 'cff', 'Type1', 'KLHFLE+AdvPSA35D', 'F6', 'WinAnsiEncoding'),
 (293, 'cff', 'Type1', 'KLHFLF+AdvOT05d4dae9.I+20', 'F7', 'WinAnsiEncoding')}
>>> 
```
This font at xref 283 is used throughout the document for the following unicodes:
```python
>>> pprint(allchar_set)
{(51, '3', 3), (46, '.', 1), (50, '2', 2), (59, ';', 5), (53, '5', 4)}
```
Each item here is `(unicode, chr(unicode), glyph-id)`.
It definitely is a problem font: if you e.g. copy/paste this
![grafik](https://user-images.githubusercontent.com/8290722/140492653-24ef9a3c-6a83-46ab-9b8d-55445a15a043.png)
using Adobe Acrobat into Word, you get "interval 0.19–0.73; n 5 2438; I2 5". 
The same garbage.
It also happens with other available PDF-to-Text coverters like Nitro Reader or XPDF.
So it is not a bug and unfortunately you have to live with this.☹️

**Comment by JorjMcKie** [comment]
The one idea I have: simply omit characters if their span has that font.
In the case of this specific PDF, your information loss is zero.

**Comment by maspotts** [comment]
That is brilliant!  Works like a charm: thanks so much for the analysis and suggestion!!!

<img width="111" alt="Screen Shot maxi 2021-11-05 at 7 46 26 AM" src="https://user-images.githubusercontent.com/4096446/140529416-912011ad-3f27-441a-8eb9-14daf089ea86.png">
!!
