### ISSUE TITLE
Using regex expressions in text search

### ISSUE THREAD

**Issue by ChefQ** [pymupdf/PyMuPDF#1376]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.
I am trying to extract the contents under a specific heading("Acknowledgements") from multiple pdfs. 
My approach is to use your text search method to help me find the first occurrence of the word("Acknowledgements")
However, authors make mistakes. They make typos, so I have seen Acknowledgements written in so many different ways e.g:
1. Acknowledgements
2. Acknowledgement
3. Ackowledgements
4. Acknowledgmen
5. Aknowledgements

With a regex expression, I can capture a robust set of strings.
**Describe the solution you'd like**
in https://pymupdf.readthedocs.io/en/latest/page.html#Page.search_for
add an option for regex
**Describe alternatives you've considered**
I see no simpler way. add regex to your search engine.

**Additional context**

**Comment by JorjMcKie** [comment]
Unfortunately this cannot be done: The search function is code in the MuPDF base library, not part of PyMuPDF itself.

But I think there are alternatives that can serve your intention:
1. Make a sorted list of **_"words"_** on the page. These are defined as strings containing no spaces. Each item of the returned list looks like `(x0, y0, x1, y1, "word", bno, lno, wno)`.
2. Match the word strings with your regular expression.

```python
search = re.compile(...)  # matching pattern
words = page.get_text("words", sort=True)
matches = [w for w in words if search.match(w[4])]
```
Delivers a list of words matching the pattern, sorted from top-left to bottom-right, including the words position information.
