### ISSUE TITLE
cannot rotate pages of some PDF

### ISSUE THREAD

**Issue by shin1007** [pymupdf/PyMuPDF#1377]
**Problem description.**
In some pages of PDFs, their rotation matrix and derotation matrix are like
    Matrix(1.0, 0.0, 0.0, 1.0, 0.0, 0.0)
    Matrix(1.0, -0.0, -0.0, 1.0, 0.0, 0.0)
and we cannot rotate these pages properly.

**Solution I'd like**
adding new methods like `set_rotation_matrix` and `set_derotation_matrix`.
which set desirable matrixes and thus we can rotate pages with improper rotation matrix.

**Alternatives I've considered**
names of the methods can be different.

**Comment by JorjMcKie** [comment]
I don't understand:
Page (de-) rotation matrix is computed automatically by inspecting a page's rotation.
Changing / setting page rotation via `page.set_rotation(degree)` will also change those matrices.

**Comment by JorjMcKie** [comment]
Look at this:
```python
>>> for degree in (0, 90, 180, 270):
	page.set_rotation(degree)
	print("de-rot:", page.derotation_matrix)
	print("   rot:", page.rotation_matrix)

	
de-rot: Matrix(1.0, -0.0, -0.0, 1.0, 0.0, 0.0)
   rot: Matrix(1.0, 0.0, 0.0, 1.0, 0.0, 0.0)
de-rot: Matrix(0.0, -1.0, 1.0, 0.0, -0.0, 842.0)
   rot: Matrix(0.0, 1.0, -1.0, 0.0, 842.0, 0.0)
de-rot: Matrix(-1.0, -0.0, -0.0, -1.0, 595.0, 842.0)
   rot: Matrix(-1.0, 0.0, 0.0, -1.0, 595.0, 842.0)
de-rot: Matrix(0.0, 1.0, -1.0, 0.0, 595.0, -0.0)
   rot: Matrix(0.0, -1.0, 1.0, 0.0, 0.0, 595.0)
>>>  
```

**Comment by shin1007** [comment]
I'll check my PDF again. thanks

**Comment by shin1007** [comment]
Thanks to your advice, I've understood it's not related to rotation matrix.
however, I'm still facing a problem with rotation.
I would be pretty happy if you kindly spare some time for solving this problem.

I'm doing a kind of 2-ups and it works for some pdf and does not work for some others.
I need to rotate the page if its paper size is a4 portrait before attaching to a3 paper left / right.
code below sometimes does not rotate as i expect.
it shows just left part of the original page(a4-landscape).

it looks working if i simply overwrite src_pdf.
but still having problem when i try to 2-up again.

are there any solutions you come up with?
TIA

```Python
a3_w, a3_h = fitz.paper_size("a3-l")
rect_a3_left = fitz.Rect(0, 0, a3_w/2, a3_h)
rect_a3_right = fitz.Rect(a3_w/2, 0, a3_w, a3_h)

a4_w, a4_h = fitz.paper_size("a4")
rect_a4_portrait = fitz.Rect(0, 0, a4_w, a4_h)
rect_a4_landscape = fitz.Rect(0, 0, a4_h, a4_w)

page = new_pdf.new_page(-1, width = a3_w, height = a3_h)

if paper_size == 'a4_landscape':
    print(paper_size_of(src_pdf[i]))
    print(src_pdf[i].rotation)
    print(src_pdf[i].rotation_matrix)
    print(src_pdf[i].derotation_matrix)
    if src_pdf[i].rotation == 0:
        src_pdf[i].set_rotation(270)
    else:
        src_pdf[i].set_rotation(src_pdf[i].rotation - 90)
    print(paper_size_of(src_pdf[i]))
    print(src_pdf[i].rotation)
    print(src_pdf[i].rotation_matrix)
    print(src_pdf[i].derotation_matrix)
    page.show_pdf_page(rect_a3_left, src_pdf, i)
```
