### ISSUE TITLE
can not import pymupdf

### ISSUE THREAD

**Issue by Shivam2JDS** [pymupdf/PyMuPDF#1381]
In google colab, after I build PyMuPDF from pip install, it is failing to import pymupdf

code:-
!pip install PyMuPDF
import pymupdf

error:-
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-8e80def7209c> in <module>()
      1 get_ipython().system('pip install PyMuPDF')
      2 
----> 3 import pymupdf

ModuleNotFoundError: No module named 'pymupdf'

**Comment by mailsnathan** [comment]
import fitz 
fitz.open(pdffile)

use this it will work.

**Comment by Shivam2JDS** [comment]
thanks it worked for me
