### ISSUE TITLE
Inconsistent link insertion (inserted as LINK_URI, comes as LINK_LAUNCH

### ISSUE THREAD

**Issue by SirishaGorasa** [pymupdf/PyMuPDF#1384]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When I insert the link using insert_link method and specify the kind as fitz.LINK_URI, and when I refetch the link using getLinks() method it comes as LINK_LAUNCH.

## To Reproduce (mandatory)
Use the attached pdf and json (to pass to insert_link method)
```json
{'uri': 'uni-bonn.de', 'kind': fitz.LINK_URI, 'from': Rect(294.7298889160156, 267.2528076171875, 358.4279479980469, 278.5437316894531)}
```

## Expected behavior (optional)
when fetched using get Links it should be LINK_URI

## Your configuration (mandatory)
 - Windows , 64 bit
 - Python version: 3.9.2

> Name: PyMuPDF
> Version: 1.18.15
> Summary: PyMuPDF is a Python binding for the document renderer and toolkit MuPDF
> Home-page: https://github.com/pymupdf/PyMuPDF
> Author: Jorj McKie
> Author-email: jorj.x.mckie@outlook.de
> License: GNU AFFERO GPL 3.0
> Location: d:\c_drive_clone\lib\site-packages
> Requires:
> Required-by:

File:
[thorsten.pdf](https://github.com/pymupdf/PyMuPDF/files/7511616/thorsten.pdf)

**Comment by JorjMcKie** [comment]
Please also let me have the code you were using to reproduce.

**Comment by SirishaGorasa** [comment]
You can use the JSON provided. Let me just quickly type in here.
``` python
pdf_document=fitz.open("thorsten.pdf")
page=pdf_document.load_page(0)
link_dict={'uri': 'uni-bonn.de', 'kind': fitz.LINK_URI, 'from': Rect(294.7298889160156, 267.2528076171875, 358.4279479980469, 278.5437316894531)}
page.insert_link(link_dict)
pdf_document.save("output.pdf")
doc=fitz.open("output.pdf")
links=list()
for page in doc:
    links.extend(page.get_links())
print(links)
```

**Comment by JorjMcKie** [comment]
Yes, confirmed, just tried it myself.

**Comment by SirishaGorasa** [comment]
Are you able to reproduce the same?

**Comment by JorjMcKie** [comment]
> 
> 
> Are you able to reproduce the same?

Yes, but the situation is **_very_** weird: 
* Adobe Acrobat say it is a **_file_** link, 
* Foxit Reader (correctly) accepts it as a **_URI_**, 
* MS Edge says it is a **_URI_**, 
* Firefox says it is a **_file_**, 
* Nitro 5 Reader says it is a **_URI_**, 
* PDF_XChange Viewer says it is a **_URI_**.
* SumatraPDF (based on MuPDF) says it is a **_file_**
* and of course MuPDF also says it is a **_file_**

The object inserted into the PDF also looks correct: ``/A <</S /URI /URI (...) >>``.
So I need to find out where the ambiguity comes from 😟.

**Comment by SirishaGorasa** [comment]
Looking forward :-[

**Comment by SirishaGorasa** [comment]
I guess it's due to the protocol/scheme inside the url, when I try with `https://google.com` it's fine, but not when I try with `google.com`

**Comment by SirishaGorasa** [comment]
even with website starting with www

**Comment by JorjMcKie** [comment]
> 
> 
> I guess it's due to the protocol/scheme inside the url, because when I try with `https://google.com` it's fine, but not when I try with `google.com`

Exactly! Just found out the same!
So I must update the documentation: the link syntax as such is correct.

**Comment by JorjMcKie** [comment]
The wording in the docu should be to provide a disambiguating link text, starting with `http://´ or `https://` etc.

**Comment by SirishaGorasa** [comment]
So you mean that's the issue.

**Comment by JorjMcKie** [comment]
> So you mean that's the issue.

Yes, there is nothing I can do else: the syntax is otherwise correct, and cannot be made clearer as it is.
I will also issue a warning (or an error?) if the URI text does not start with one of "http://", "mailto:", etc.

**Comment by JorjMcKie** [comment]
One of the problems is that URI text starting with "file:..." is also valid. So, depending on the PDF viewer used, different default assumptions are taken. My list from above demonstrates this ...
