### ISSUE TITLE
In some PDFs in the content stream, there were only symbols instead of text. Can you let me know the reason why symbols are present in the place of text and if there is a way to convert those symbols to text.

### ISSUE THREAD

**Issue by meghanaviyyapu** [pymupdf/PyMuPDF#1395]
In some PDFs in the content stream, there were only symbols instead of text. Can you let me know the reason why symbols are present in the place of text and if there is a way to convert those symbols to text.
[sample-pdf-with-images.pdf](https://github.com/pymupdf/PyMuPDF/files/7525410/sample-pdf-with-images.pdf)

![image](https://user-images.githubusercontent.com/36301306/141423184-f11fc82e-0af5-4c38-98e5-bfe79e013ae1.png)

_Originally posted by @meghanaviyyapu in https://github.com/pymupdf/PyMuPDF/discussions/1394#discussioncomment-1630281_

**Comment by JorjMcKie** [comment]
see discussion  item
