### ISSUE TITLE
moveto, then four lines back to beginning, with no closepath not a rect?

### ISSUE THREAD

**Issue by mlissner** [pymupdf/PyMuPDF#1398]
## Describe the bug (mandatory)

I'm just guessing about what's happening here, but I've got another strange PDF (I think I'm getting towards the end of them):

[testh180.pdf](https://github.com/pymupdf/PyMuPDF/files/7531134/testh180.pdf)

If you extract the XML using `mutool trace` (I'm learning), you get something like this:

```xml
    <fill_path winding="nonzero" colorspace="DeviceGray" color="0" transform="1 0 -0 -1 324.1407 91.7471">
        <moveto x="26.8145" y="17.8763"/>
        <lineto x="0" y="17.8763"/>
        <lineto x="0" y="0"/>
        <lineto x="26.8145" y="0"/>
        <lineto x="26.8145" y="17.8763"/>
    </fill_path>
```

You can see that it's a moveto, four lineto's, and the last lineto takes you back to the beginning. When I look at this from `get_drawings`, it comes up as four lines, not as a rect:

```ipython
In: from pprint import pprint
In: drawings = page.get_drawings()
In: pprint(drawings[2]["items"])
Out: [('l',
  Point(261.0447998046875, 718.1292114257812),
  Point(287.85931396484375, 718.1292114257812)),
 ('l',
  Point(287.85931396484375, 718.1292114257812),
  Point(287.85931396484375, 700.2529296875)),
 ('l',
  Point(287.85931396484375, 700.2529296875),
  Point(261.0447998046875, 700.2529296875)),
 ('l',
  Point(261.0447998046875, 700.2529296875),
  Point(261.0447998046875, 718.1292114257812))]
```

I'd sort of expect that the rectangle detector is already able to figure this kind of thing out, so I'm surprised it's not identifying this as a rectangle already. Maybe there's something else going on.

## To Reproduce (mandatory)
Get drawings for the attached doc or use `mutool trace` to see the lines.

## Expected behavior (optional)
I expected these to be rectangles.

## Your configuration (mandatory)

 - Operating system, potentially version and bitness

Linux, Ubuntu, 64 bit

 - Python version, bitness

3.8, 64 bit

 - PyMuPDF version, installation method (**wheel** or **generated** from source).

1.19.0

**Comment by mlissner** [comment]
Actually, I'm realizing the black rectangles I see are actually part of the image in the PDF and the lines are behind it where I can't see them at all. I think this one is fine-enough for now. We can focus elsewhere.

**Comment by JorjMcKie** [comment]
This one is being detected as a rectangle under v1.19.2!
```python
>>> doc=fitz.open("testh180.pdf")
>>> page=doc[0]
>>> paths=page.get_drawings()
>>> from pprint import pprint
>>> pprint(paths[2])
{'closePath': False,
 'color': None,
 'dashes': '[] 0',
 'even_odd': False,
 'fill': (0.0, 0.0, 0.0),
 'fill_opacity': 1.0,
 'items': [('re',
            Rect(261.0447998046875, 700.2529296875, 287.85931396484375, 718.1292114257812),
            1)],
 'lineCap': [0],
 'lineJoin': 0,
 'rect': Rect(261.0447998046875, 700.2529296875, 287.85931396484375, 718.1292114257812),
 'seqno': 3,
 'stroke_opacity': 1,
 'type': 'f',
 'width': 0}
>>> 
```
