### ISSUE TITLE
AttributeError: 'Document' object has no attribute '_getXrefString'

### ISSUE THREAD

**Issue by songtianhui** [pymupdf/PyMuPDF#1399]
I try to run my code 
```python

def pdf2image1(path, pic_path):
    checkIM = r"/Subtype(?= */Image)"
    pdf = fitz.open(path)
    lenXREF = pdf.xref_length()
    count = 1
    for i in range(1, lenXREF):
        text = pdf._getXrefString(i)
        isImage = re.search(checkIM, text)
        if not isImage:
            continue
        pix = fitz.Pixmap(pdf, i)
        if pix.size < 10000:
            continue
        new_name = f"img_{count}.png"
        pix.writePNG(os.path.join(pic_path, new_name))
        count += 1
        pix = None
```
but get error `AttributeError: 'Document' object has no attribute '_getXrefString`.
My pymupdf version is 1.18.19
How can i fix it or find another method?
Thank you!

**Comment by JorjMcKie** [comment]
This method has been renamed to `doc.xref_object()` a long time ago - please consult the documentation, section "Deprecated Names".

**Comment by JorjMcKie** [comment]
sorry `doc.xref_length`

**Comment by songtianhui** [comment]
Thanks very much!
It works well and I think it is `doc.xref_object` because I want the source of objects
