### ISSUE TITLE
Pixmap_pdfocr_save fails when called with multiple languages

### ISSUE THREAD

**Issue by dannydocrxiv** [pymupdf/PyMuPDF#1400]
I get 
"RuntimeError: OCR initialisation failed"

When I call pix.pdfocr_save(outbytes, language="eng,spa") or pix.pdfocr_save(outbytes, language="eng,heb")
The document I use is in Hebrew

When just using one language like : pix.pdfocr_save(outbytes, language="heb")
it works fine

I attached the PDF I am using
Thx

[מבוא-למנועים.pdf](https://github.com/pymupdf/PyMuPDF/files/7533561/-.pdf)

**Comment by JorjMcKie** [comment]
This error is caused outside (Py-) MuPDF and should have to do with your Tesseract installation.
Verify or disprove using native Tesseract.
On my machine (with no Hebrew available in Tesseract), lanfuage="heb" fails.

**Comment by JorjMcKie** [comment]
Ah - no, I think there is a documentation issue:
You need to specify multiple languages with a `+` separator: `language="eing+heb"`.

**Comment by dannydocrxiv** [comment]
Ok, thanks. works now with multiple languages

**Comment by JorjMcKie** [comment]
Documentation corrected.
