### ISSUE TITLE
Text Redaction in a rotated text, blackens the rest of the textbox after redaction

### ISSUE THREAD

**Issue by ayusonkj** [pymupdf/PyMuPDF#1402]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
after redaction of a rotated textbox, the rest of the textbox is filled with black.

## To Reproduce (mandatory)

```
def remove_text_in_pdf(pdf_file=pdf_file):
    doc = fitz.open(pdf_file)
    to_redact = []
    table_texts = []
    for page in doc:
        page.wrapContents()
        texts = page.get_text('text')
        for text in texts.split():
            areas = page.searchFor(text)
            [page.addRedactAnnot(area) for area in areas]
        page.apply_redactions()
        doc.save(clean_file)
```
        
## Expected behavior (optional)
there are no black areas in the redacted area:

## Screenshots (optional)
original pdf:
![image](https://user-images.githubusercontent.com/89957740/141879351-9189c439-1ebf-4474-b204-b4a61decd565.png)

actual output:
![image](https://user-images.githubusercontent.com/89957740/141879524-3919f7e5-626c-4d72-98b1-4e0b8d60e670.png)

## Your configuration (mandatory)

 - VERSION="20.04.3 LTS (Focal Fossa)"
 --ID=ubuntu
 --VERSION_ID="20.04"
 - Python 3.8.10
 - PyMuPDF                1.18.17
 - Installed via wheel

**Comment by JorjMcKie** [comment]
Sorry, cannot reproduce. Here are data for a similar case that works fine: [redactions.zip](https://github.com/pymupdf/PyMuPDF/files/7544604/redactions.zip)

Your example can obviously not be true: the coontent of the unrotated page is unequal to the rotated one.
And why do you save within the page loop?

**Comment by JorjMcKie** [comment]
Another example: page not rotated, text rotated.
Also everything roses!
[textbox-redactions.zip](https://github.com/pymupdf/PyMuPDF/files/7545263/textbox-redactions.zip)

**Comment by ayusonkj** [comment]
Hi, Jorj

thanks for reaching out, here is the pdf_file that I used as a reference
[pdf_test.zip](https://github.com/pymupdf/PyMuPDF/files/7545337/pdf_test.zip)
.
Apologies for the confusion, a mistake on my part in the indent when I inputted the code earlier.
I tried the approach that you have presented in the redactions.zip, no texts were redacted when I ran it on my side.

**Comment by JorjMcKie** [comment]
Ahhh you were trying to fool me!
Your PDF also contains images which overlap text. So poor MuPDF does its best to modify those image subareas that overlap redaction rectangles. Because images also have a mask, the old MuPDF issue pops up: masked images are not properly modified (to become masked again). This is the result you see.
You have 2 choices only: either remove an overlapping image entirely: `page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_REMOVE)` **_or_** do not touch these images: `PDF_REDACT_IMAGE_NONE`.

**Comment by JorjMcKie** [comment]
this one works as you expect:
```python
import fitz


doc = fitz.open("sample_pdf.pdf")
for page in doc:
    page.wrap_contents()
    texts = page.get_text("text").split()
    for text in texts:
        areas = page.search_for(text)
        for area in areas:
            page.add_redact_annot(area)

    page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)

doc.save("sample_pdf_clean.pdf")
```

**Comment by ayusonkj** [comment]
Hi,
This is amazing! I used the "PDF_REDACT_IMAGE_NONE" and it worked as intended thank you very much!

Cheers!!
