### ISSUE TITLE
Extracted image from pdf is completely black

### ISSUE THREAD

**Issue by YashMistry349** [pymupdf/PyMuPDF#1406]
I am working on image extraction from PDF. The library can detect the image in the PDF page correctly, But while saving it or displaying it I get a completely black image.
For your reference, I am attaching a file that contains the image byte stream which is extracted from pdf. But while saving or displaying it, it's completely black.
![image_screenshot_of_pdf](https://user-images.githubusercontent.com/79560917/141957616-b93fea74-dd83-4788-a552-9407c5717fdd.png)
![test](https://user-images.githubusercontent.com/79560917/141957951-61b54dd6-bcd8-441a-9c15-8a2c1eb21abb.png)
.
[byte_stream.txt](https://github.com/pymupdf/PyMuPDF/files/7544964/byte_stream.txt)

**Comment by JorjMcKie** [comment]
The attachment doesn't help - please provide the document and the code you used for extraction.

**Comment by YashMistry349** [comment]
[Test.pdf](https://github.com/pymupdf/PyMuPDF/files/7545231/Test.pdf)
Code:

**Comment by YashMistry349** [comment]
[Test.pdf](https://github.com/pymupdf/PyMuPDF/files/7545235/Test.pdf)
Code:
`import io
import fitz
from PIL import Image
path = 'Test.pdf'
doc = fitz.open(path, filetype="pdf")

page_count = doc.page_count
if page_count:
    for page_no in range(page_count):
        blocks = doc[page_no].getText('dict')['blocks']
        for ind, block in enumerate(blocks):
            if block['type'] == 1:
                try:
                    image = Image.open(io.BytesIO(block['image']))
                    image.save(open(f"test.{block['ext']}", "wb"))
                except Exception as e:
                    print(e)`

**Comment by JorjMcKie** [comment]
Your way of text extraction is unable to deal with images having an image mask.
Your PDF however has 2 images, each with an image mask:
```python
>>> from pprint import pprint
>>> 
>>> pprint(page.get_images(True))
[(19, 25, 419, 64, 8, 'DeviceRGB', '', 'Img1', 'FlateDecode', 0),
 (20, 26, 419, 64, 8, 'DeviceRGB', '', 'Img10', 'FlateDecode', 0)]
>>> 
```
to extract such images, a special coing must be used: e-g- for the first one (xref 19, mask xref 25):
```python
pix19 = fitz.Pixmap(doc, 19)
mask = fitz.Pixmap(doc, 25)
pix = fitz.Pixmap(pix19, mask)
pix.save("test.png")  # fully recovered image
```
