### ISSUE TITLE
Faster insert_image performance (somehow)

### ISSUE THREAD

**Issue by MerlijnWajer** [pymupdf/PyMuPDF#1408]
**Is your feature request related to a problem? Please describe.**

At archive.org we're using PyMuPDF on a big scale - processing literally millions of pages per day, and as such I've been looking at optimising the software (https://github.com/internetarchive/archive-pdf-tools) to save on power.

As of the last version (1.4.7), the slowest operation is now the `insert_image` performance:

![pdf-timebreakdown](https://user-images.githubusercontent.com/517897/141998117-7534ec1a-b4f1-4af4-ab79-e9a5137c57ee.png)

It is my understanding that pymupdf or mupdf (in the api?) decodes the image before inserting it. This is an entirely reasonable thing to do, but given that in my case the software has just produced the (JPEG2000 and JBIG2) images, I was wondering if it would be possible to *skip* decoding the images when inserting them somehow.

This is the code in question https://github.com/internetarchive/archive-pdf-tools/blob/master/internetarchivepdf/recode.py#L543 - 

```python
 = time()
bg_contents = open(bg_f, 'rb').read()
# Tell PyMuPDF about width/height/alpha since it's faster this way
page.insert_image(page.rect, stream=bg_contents, mask=None,
        overlay=False, width=bg_s[0], height=bg_s[1], alpha=0)

fg_contents = open(fg_f, 'rb').read()
mask_contents = open(mask_f, 'rb').read()

# Tell PyMuPDF about width/height/alpha since it's faster this way
page.insert_image(page.rect, stream=fg_contents, mask=mask_contents,
        overlay=True, width=fg_s[0], height=fg_s[1], alpha=0)

# Remove leftover files
remove(mask_f)
remove(bg_f)
remove(fg_f)
if timing_data is not None:
    timing_data.append(('page_image_insertion', time() - t))
```

Do you have any ideas on how to do this any faster? I know it might be too much too ask. I was thinking I could potentially just create a new (set of) xrefs and set the data/properties manually, and thus somehow skip decoding the image.

The files (`mask_f, bg_f, fg_q`) are already in a `devtmpfs` (i.e in memory), so the problem is very likely not I/O performance.

**Comment by JorjMcKie** [comment]
> Do you have any ideas on how to do this any faster? I know it might be too much too ask. I was thinking I could potentially just create a new (set of) xrefs and set the data/properties manually, and thus somehow skip decoding the image.

Let  me have a look. Interesting problem ...

**Comment by JorjMcKie** [comment]
You already observed, that specifying an xref of an **_existing_** image, will skip all the time critical parts of that method. Only the page's object definition will be updated to point to thr given xref - plus of course the `/Imxxx Do`  instruction in the page's contents.

So an idea might be to look at the configuration of an example page. If I recall correctly, there will be two images: one base image (which has no mask) overlaid by another image which does have a mask.

Then look at the 3 corresponding xref definitions and use them as a template:
Using PyMuPDF's low level facilities it is possible to make the corresponding objects, including all dictionary keys and streams ...
Then specify those xrefs in `insert_image` ...

The question of course is, whether there indeed exists one such template in all cases.

**Comment by MerlijnWajer** [comment]
Thanks for taking a look, I'll report back later this week, looks like that might work indeed.

**Comment by JorjMcKie** [comment]
Can you give me printouts of a page definition ``doc.xref_object(page.xref)`` and the same for the inserted image xrefs?
I could prepare code snippets for making the image object definitions and associated streams.

**Comment by MerlijnWajer** [comment]
```
>>> print(d.xref_object(d[0].xref))
<<
  /Type /Page
  /Parent 2 0 R
  /MediaBox [ 0 0 552.96 645.12 ]
  /Contents [ 77 0 R 10 0 R 80 0 R ]
  /Resources <<
    /ProcSet [ /PDF /Text /ImageB /ImageI /ImageC ]
    /Font <<
      /f-0-0 3 0 R
    >>
    /XObject <<
      /fzImg0 76 0 R
      /fzImg1 78 0 R
    >>
  >>
  /StructParents 0
  /CropBox [ 0 0 553 645.1 ]
  /Rotate 0
  /Tabs /S
>>
```

```
<<
  /Filter /JPXDecode
  /Type /XObject
  /Subtype /Image
  /BitsPerComponent 8
  /Width 1920
  /Height 2240
  /ColorSpace /DeviceRGB
  /Length 78248
>>
```

```
<<
  /Filter /JPXDecode
  /Type /XObject
  /Subtype /Image
  /BitsPerComponent 8
  /Width 1920
  /Height 2240
  /ColorSpace /DeviceRGB
  /SMask 79 0 R
  /Length 18749
>>
```

```
<<
  /Filter /JBIG2Decode
  /Type /XObject
  /Subtype /Image
  /BitsPerComponent 1
  /Width 1920
  /Height 2240
  /ColorSpace /DeviceGray
  /Length 22963
>>
```

**Comment by JorjMcKie** [comment]
Thank you!
Should be easy enough. The only issue is a change for my stream update function: it currently always compresses according to `/FlateDecode`.
If you can provide your images already in the correct compression formats `/JBIG2Decode` and `/JPXDecode`, I could add an argument like `raw` to skip my compression, or I would have to dig out appropriate compression routines.

A simple raw copy of your streams to the PDF objects would be ideal.

**Comment by MerlijnWajer** [comment]
I think you should be able to just use/download this PDF: https://archive.org/download/sim_english-illustrated-magazine_1884-12_2_15/sim_english-illustrated-magazine_1884-12_2_15.pdf

I didn't use the above PDF to give you an idea of the templates, but I think it should be the same otherwise.

**Comment by MerlijnWajer** [comment]
Or, how would you rather have the raw copy of the PDF objects - I can zip/tar them up?

**Comment by JorjMcKie** [comment]
I am actually all set already - except for that one mentioned point (suppressing compression).
So if you are sure, your streams are in the correct compression formats JPX / JBIG2, everything is done, conceptually!
Suppressing compression is a no-brainer.

**Comment by JorjMcKie** [comment]
Okay, then. I'll stop bothering you for a while and come back with a script plus an updated wheel ... 😎

**Comment by JorjMcKie** [comment]
Just an intermediate sign of life:
It does work and it seems to be a lot faster: looks like about 0.000145 seconds (145 microseconds) per image.
How does that compare to your current numbers? Your picture seems to suggest about 500 ms for `insert_image` - is that per method execution or per page or some other measure?
If per page or per image, then my results are really good news, because it would be below 150 resp 300 microseconds.

I used your example PDF and made a new one reusing the respective page images ...

**Comment by JorjMcKie** [comment]
There new v1.19.2 pre-wheel available [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/master/wheelhouse).
This the script I used:
[copy-image.zip](https://github.com/pymupdf/PyMuPDF/files/7554788/copy-image.zip)

**Comment by MerlijnWajer** [comment]
It works, with a minor modification: for the normal path in MuPDF I had to not strip the JBIG2 header, but for the direct insertion, I had to strip the JBIG2 header. (The -p parameter of https://github.com/agl/jbig2enc)

Thanks - I'll do some more testing but this seems promising!

**Comment by MerlijnWajer** [comment]
As far as I can see, it just works, and it's really, really fast. My amortised time measurements measures 0ms (of course Linux hides some i/o latency with it's cache). In any case, this is great and works well for me. I'm planning to use your example script mostly verbatim in my code - I'll add you to the credits, assuming you're OK with AGPL-v3?

**Comment by MerlijnWajer** [comment]
> Just an intermediate sign of life: It does work and it seems to be a lot faster: looks like about 0.000145 seconds (145 microseconds) per image. How does that compare to your current numbers? Your picture seems to suggest about 500 ms for `insert_image` - is that per method execution or per page or some other measure? If per page or per image, then my results are really good news, because it would be below 150 resp 300 microseconds.
> 
> I used your example PDF and made a new one reusing the respective page images ...

Right, yes, my numbers were *per page*.

**Comment by JorjMcKie** [comment]
>  I'll add you to the credits, assuming you're OK with AGPL-v3?

Sure, that's fine.

**Comment by JorjMcKie** [comment]
> 
> 
> As far as I can see, it just works, and it's really, really fast. My amortised time measurements measures 0ms (of course Linux hides some i/o latency with it's cache).

Might also be some rounding thing: after all the new elapsed time is less than 1 thousandth of the previous ... **_microseconds_** not milliseconds.

**Comment by MerlijnWajer** [comment]
> > As far as I can see, it just works, and it's really, really fast. My amortised time measurements measures 0ms (of course Linux hides some i/o latency with it's cache).
> 
> Might also be some rounding thing: after all the new elapsed time is less than 1 thousandth of the previous ... **_microseconds_** not milliseconds.

Yes, I'm sure it is a rounding issue.

I think we can close this issue now or when you (eventually) release the new PyMuPDF? :-)

**Comment by JorjMcKie** [comment]
> I think we can close this issue now or when you (eventually) release the new PyMuPDF? :-)

Ok, I will thanks.
The next version won't be long away either, but the solution isn't really connected to changing PyMuPDF.

**Comment by MerlijnWajer** [comment]
> > I think we can close this issue now or when you (eventually) release the new PyMuPDF? :-)
> 
> Ok, I will thanks. The next version won't be long away either, but the solution isn't really connected to changing PyMuPDF.

Ah, ok, I see. I thought you added you support for raw streams in the build you shared on the issue.

In any case - thanks!

**Comment by JorjMcKie** [comment]
Yes I did that.
But it was an unnecessary restriction all the time anyway. The C code was there ever, only the Python wrapper did not contain the option.

**Comment by MerlijnWajer** [comment]
Just following up with the results...

![image](https://user-images.githubusercontent.com/517897/142744226-c9348d7a-887c-408d-91be-1b0681668514.png)

Thanks for PyMuPDF and all your work!
