### ISSUE TITLE
RuntimeError when inserting text

### ISSUE THREAD

**Issue by pablochud** [pymupdf/PyMuPDF#1411]
## Describe the bug (mandatory)
I can not insert text in the existing blank page. I extract blank page from my pdf document and put it in WeTransfer because the error does not occur for every blank page.

[blank page pdf](https://we.tl/t-Nqxh4jHCR3)

The insertText method returns RuntimeError:
```
pdf_doc = "output_blank_page"
doc = fitz.open(pdf_doc)
for page in doc.pages(): 
    page.insertText(fitz.Point(20, 20), 'COPY') 
```
```
/python3.6/site-packages/fitz/fitz.py", line 2782, in _getPageInfo
    val = _fitz.Document__getPageInfo(self, pno, what)
RuntimeError: cannot retrieve page info
```

## Your configuration (mandatory)
 - Linux, Ubuntu 64 bit
 - Python 3.6
 - PyMuPDF 1.16.6

**Comment by JorjMcKie** [comment]
cannot download the PDF

**Comment by JorjMcKie** [comment]
did you check if there were errors when opening the PDF via ´fitz.open()`?
If there were, then this is no (Py-) MuPDF problem. Repair the file first.

**Comment by JorjMcKie** [comment]
BTW the provided code snippet cannot work anyway: the filename "pdf_doc" contains no recognizable MIME code.

**Comment by JorjMcKie** [comment]
I tried again to access your example PDF:
That web site obviously just wants to sell stuff - no download option anywhere.
It look like you are to tempt me undergoing whatever risks.
Therefore I will close the issue.
Anyone coming across this issue is being warned to access the above link.
