### ISSUE TITLE
page.get_text("words") ignores some of the words on the page.

### ISSUE THREAD

**Issue by Don-Yin** [pymupdf/PyMuPDF#1414]
_**Please provide all mandatory information!**_
Hi McKie, how are you?

## Describe the bug (mandatory)
```page.get_text("words")``` is expected to return a list of tuples containing the information about all words on the current page, with the first four digits indicating the rect. It does not appear to work properly where certain words (and paragraphs) are ignored in a systematic manner. This is what happened when I attempted to draw rectangles around each word on a page using the ```get_text``` returned list:

<img width="1013" alt="Screenshot 2021-11-19 at 13 20 08" src="https://user-images.githubusercontent.com/65135356/142629498-d902f709-e2cf-48fd-b04a-3fa052dd8887.png">

## To Reproduce (mandatory)
1. Here is an example pdf file:
[example.pdf](https://github.com/pymupdf/PyMuPDF/files/7570579/example.pdf)
2. Read doc
```python
doc = fitz.open("example.pdf")
```
3. Define page, and apply page.get_text()
```python
page = doc[3]
all_words_on_page: list[tuple] = page.get_text("words")
```
4. Extract coordinates of rects and draw them
```python
rects_all_words_on_page: list[tuple] = [i[:4] for i in all_words_on_page]
for r in rects_all_words_on_page:
     page.draw_rect(r, color=(0, 0, 0), fill=(0, 0, 0), overlay=False)
```
5. Save doc
```python
doc.save("marked_example.pdf", garbage=1, deflate=True, clean=True)
```

## Expected behavior (optional)
If it works properly, each word should be covered by its own rect. However, as illustrated in the screenshot, this is not the case.

## Your configuration (mandatory)
 - Operating system, potentially version and bitness: MacOs 12.0.1
 - Python version, bitness: 3.9.7
 - PyMuPDF version, installation method (**wheel** or **generated** from source): PyMuPDF==1.18.19 installed with pip

**Comment by JorjMcKie** [comment]
Wrong observation - it does not ignore a single word! See here:
![grafik](https://user-images.githubusercontent.com/8290722/142645076-f700ecd3-837b-418d-8db1-7511dddba00c.png)

**Comment by JorjMcKie** [comment]
Or rather: it is your fault - you put the rectangles in background, ``overlay=False``.
So wherever the page contains an own background, you are hiding your rectangle behind it 😉.

**Comment by Don-Yin** [comment]
My fault. Apologies! I appreciate your response! :)

**Comment by JorjMcKie** [comment]
BTW a very well-prepared issue report!
This does not happen often - thank you!

**Comment by Don-Yin** [comment]
Many thanks. This is the least effort I can make to facilitate a developer's work (and, by the way, fantastic work on PyMuPdf). The shared objective is to increase the efficiency of the community and my response will be that your acuity is also uncommon. Continue!
