### ISSUE TITLE
xref_set_key - don't change key value on a pdf page

### ISSUE THREAD

**Issue by PeterSlezak** [pymupdf/PyMuPDF#1415]
## Describe the bug (mandatory)
I've added two freetext annotations on a blank page a want to set /AP to empty dict using the xref_set_key function but it is changed only for the 2nd annotation.

## To Reproduce (mandatory)
```
import fitz
bg_color = (0.75, 1, 1)

#create blank page
doc = fitz.open()
doc.new_page()
page = doc[0]

#add 1st annot
annot1 = page.add_freetext_annot(fitz.Rect(10,10,40,25),
                                 "text 1",
                                 fontname = 'helv',
                                 fontsize = 10,
                                 rotate=0,
                                 text_color=(0,0,0),
                                 fill_color=bg_color,
                                 align=fitz.TEXT_ALIGN_LEFT)
annot1.set_border(width=0.5)
annot1.update(fontsize=10,
             fontname = 'helv',
             text_color=(0,0,0), 
             fill_color=bg_color, 
             border_color=(0,0,0))

#set Appearnace stream to empty dict
doc.xref_set_key(annot1.xref, "AP", "<<>>")

#add 2nd annot
annot2 = page.add_freetext_annot(fitz.Rect(10,50,40,65),
                                 "text 2",
                                 fontname = 'helv',
                                 fontsize = 10,
                                 rotate=0,
                                 text_color=(0,0,0),
                                 fill_color=bg_color,
                                 align=fitz.TEXT_ALIGN_LEFT)
annot2.set_border(width=0.5)
annot2.update(fontsize=10,
             fontname = 'helv',
             text_color=(0,0,0), 
             fill_color=bg_color, 
             border_color=(0,0,0))
doc.xref_set_key(annot2.xref, "AP", "<<>>")

doc.save("test1.pdf")

#check appearance streams
doc = fitz.open('test1.pdf')
page = doc[0]
for annot in page.annots():
    print(doc.xref_get_key(annot.xref, "AP"))
```

output
('dict', '<</N 9 0 R>>')
('dict', '<<>>')

## Expected behavior (optional)
Set AP to <<>> for both annots

## Your configuration (mandatory)
 - Windows 10 64-bit
 - Python: 3.9.8 64-bit
 - PyMuPDF 1.19.2: Python bindings for the MuPDF 1.19.0 library.
   Version date: 2021-11-20 00:00:01.
   Built for Python 3.9 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
Not a bug, but a consequence of PyMuPDF's extra features for annotations: MuPDF does not (always) become aware of those changes and in this case may re-instate what it thinks should be adequate.

How to circumvent:
* either add instruction `page = doc.reload_page(page)` after each ``annot.update()``, or
* postpone hacking the annot object to immediately before leaving the page (or saving the document)

So this does work:
```python
import fitz

bg_color = (0.75, 1, 1)

# create blank page
doc = fitz.open()
doc.new_page()
page = doc[0]

# add 1st annot
annot1 = page.add_freetext_annot(
    fitz.Rect(10, 10, 40, 25),
    "text 1",
    fontname="helv",
    fontsize=10,
    rotate=0,
    text_color=(0, 0, 0),
    fill_color=bg_color,
    align=fitz.TEXT_ALIGN_LEFT,
)
annot1.set_border(width=0.5)
annot1.update(
    fontsize=10,
    fontname="helv",
    text_color=(0, 0, 0),
    fill_color=bg_color,
    border_color=(0, 0, 0),
)

# add 2nd annot
annot2 = page.add_freetext_annot(
    fitz.Rect(10, 50, 40, 65),
    "text 2",
    fontname="helv",
    fontsize=10,
    rotate=0,
    text_color=(0, 0, 0),
    fill_color=bg_color,
    align=fitz.TEXT_ALIGN_LEFT,
)
annot2.set_border(width=0.5)
annot2.update(
    fontsize=10,
    fontname="helv",
    text_color=(0, 0, 0),
    fill_color=bg_color,
    border_color=(0, 0, 0),
)

# set Appearnace streams to empty dicts
# immediately before leaving the page or saving the doc
doc.xref_set_key(annot1.xref, "AP", "<<>>")
doc.xref_set_key(annot2.xref, "AP", "<<>>")

doc.save("test1.pdf", pretty=True)

# check appearance streams
doc = fitz.open("test1.pdf")
page = doc[0]
for annot in page.annots():
    print("xref", annot.xref, "\n", doc.xref_object(annot.xref))
```

**Comment by PeterSlezak** [comment]
Thank you @JorjMcKie it works like a charm! 
BTW is it possible to remove xref key completely using xref_set_key or some other function? Like for example instead of setting /AP to empty dict to remove /AP completely from the annot xref?

**Comment by JorjMcKie** [comment]
> BTW is it possible to remove xref key completely using xref_set_key or some other function? Like for example instead of setting /AP to empty dict to remove /AP completely from the annot xref?

Not with this method.
Instead of making an empty dict ``<<>>``, you can also use the value ``"null"``, which is PDF's equivalent to None and makes the key being regarded as non-present.
But you seem interested ìn removing all the bytes from ``"/AP"`` to the next `"`>>"``. That is possible too - with some string manipulation logic from your side:
```
annot_src = doc.xref_object(annot.xref)
p0 = annot_src.find("/AP")
p1 = annot_src.find(">>", p0) + 2
new_str = annot_src[:p0] + annot_src[p1:]
doc.update_object(annot.xref, new_str)
```

**Comment by JorjMcKie** [comment]
After doing these hacks, it makes sense to save the doc with garbage>=3 to collect the dangling AP xrefs ...
