### ISSUE TITLE
I cannot install version after 1.18.0 on my jupyter lab, I want to use get_pixmap function

### ISSUE THREAD

**Issue by qqqqqwwwweeerr1gmail** [pymupdf/PyMuPDF#1416]
Building wheels for collected packages: pymupdf
  Building wheel for pymupdf (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-thft9rnx/pymupdf_af79beb98c87448e9a83199ab18c903d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-thft9rnx/pymupdf_af79beb98c87448e9a83199ab18c903d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-37oo33o8
       cwd: /tmp/pip-install-thft9rnx/pymupdf_af79beb98c87448e9a83199ab18c903d/
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/fitz
  copying fitz/__init__.py -> build/lib.linux-x86_64-3.5/fitz
  copying fitz/fitz.py -> build/lib.linux-x86_64-3.5/fitz
  copying fitz/utils.py -> build/lib.linux-x86_64-3.5/fitz
  copying fitz/__main__.py -> build/lib.linux-x86_64-3.5/fitz
  running build_ext
  building 'fitz._fitz' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/fitz
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -m64 -fPIC -fPIC -I/usr/include/mupdf -I/usr/local/include/mupdf -Imupdf/thirdparty/freetype/include -I/usr/local/include/python3.5m -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.5/fitz/fitz_wrap.o
  fitz/fitz_wrap.c:2734:18: fatal error: fitz.h: No such file or directory
   #include <fitz.h>
                    ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pymupdf

**Comment by JorjMcKie** [comment]
PyMuPDF needs Python 3.6 or later.

**Comment by JorjMcKie** [comment]
And after this year, Python 3.7 will be the minimum requirement.
