### ISSUE TITLE
Memory growth when inserting image pages following initial insert_pdf

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#1418]
This is quite possibly a dupe of #1351 but I foolishly did most my testing before checking here, so I'll file it with my MWE.  If that is not helpful, feel free to close as a dupe of #1351.

I have checked on 1.18.17 and 1.19.2.  I have not yet checked on older system.

I have a script that uses `insert_pdf` to put a PDF coverpage into a new document.  Then various png files are inserted, one per page.  The more pngs I add per PDF or the more PDFs total, the larger the memory footprint and it never seems to be garbage collected.  This seems consistent with #1351.

Here's a MWE:
```python
import fitz


def assemble(outname, coverfile, img_list):
    """Assemble a pdf from a coverfile and images."""

    ## MEMORY GROWTH
    doc = fitz.open()
    cover = fitz.open(coverfile)
    doc.insert_pdf(cover)
    # (these don't help)
    #cover.close()
    #cover = None

    ## INSTEAD, then no growth
    #doc = fitz.open(coverfile)

    for img_filename in img_list:
        page = doc.new_page()
        rect = page.bound()
        rect += [10, 10, -10, -10]
        page.insert_image(rect, filename=img_filename)
    doc.save(outname, deflate=True)
    # this explcit close DOES HELP!
    #doc.close()
    #doc = None


def main():
    img_list = ["map.png"]
    for n in range(0, 50):
        print(n)
        assemble(f"out{n}.pdf", "cover.pdf", img_list)


if __name__ == "__main__":
    main()
```
This further uses a "cover.pdf" and "map.png": I'll attach but I don't think it matters much what they are.

Two possible workarounds:
  * explicit `doc.close()` (although notable not `cover.pdf`).
  * `doc = fitz.open(coverfile)`  instead of starting a blank document.

Other comments:
  * In my MWE, I use a single png file in.  If I use `    img_list = ["map.png"]*10` (10 copies of same png), one per page, I get the same memory use.  But 10 different png would give significantly higher memory use.
 
[map.png](https://user-images.githubusercontent.com/818622/142979794-d8037b32-22e0-4fa9-b693-4b48f191d465.png)
[cover.pdf](https://github.com/pymupdf/PyMuPDF/files/7586137/cover.pdf)

**Comment by JorjMcKie** [comment]
This (or these) is a tough one to trace down ...! Like the referred-to #1351.

One preliminary comment though:
It always is a bad idea to open a "constant" file like the cover PDF repeatedly within a loop - especially if the loop is large. It should be opened once and the created document object be passed into the loop.

**Comment by JorjMcKie** [comment]
Preliminary findings for end-of-job memory allocation delta (memory at end - memory at start):
* running your script as-is: 309 MB
* taking cover.pdf out of the loop: 305 MB (4 MB reduction)
* in addition ``doc.close(); doc=None``: 0.4 MB (!!!) ==> ``insert_pdf`` issues disappear

So the general recommendation for ``insert_pdf`` is:
* no avoidable opening of "constant" documents inside a loop - instead pass in such PDFs as **_document objects_**
* if  the loops create a PDF, execute ``doc.close(); doc=None``

With the last configuration, but inserting 5 images (worth of a total of 0.4 MB): 84 MB.

This is an issue, but has nothing to do with ``insert_pdf`` as demonstrated before.
I need to look into ``insert_image`` to see what is going on there.

**Comment by cbm755** [comment]
This is not my real code, `cover.pdf` is not constant in my real application.

Personally, I cannot reproduce it without the `insert_pdf` at the beginning:
1.  Adding this?
```
 ## INSTEAD, then no growth
doc = fitz.open(coverfile)
```
2.  or just putting images into an empty `doc = fitz.open()` doesn't show the growth.

My real application has 2000 iterations, each with (different) cover.pdf and maybe 6 png of 0.5 MiB each for each iteration.  It hits 32GiB after 300 iterations, and then the kernel's OOM daemon kills it.

**Comment by cbm755** [comment]
Your analysis is consistent with what I observered with top:
```
   VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND       
 706068 400516  14016 S   0.0   1.2   0:14.26 ipython 
1021184 715468  14016 S   0.0   2.2   0:16.87 ipython   
1336176   1.0g  14016 S   0.0   3.2   0:19.88 ipython  
1652316   1.3g  14016 S   0.0   4.1   0:22.47 ipython
1968400   1.6g  14016 S   0.0   5.1   0:25.45 ipython
```
(each row is after running the code above once.   memory is growing by 300MiB per run).

But in the case of `doc = fitz.open(coverfile)` or `doc = fitz.open()` I see no such growth.

BTW: my guess here is this is somehow triggered by #1417: something cannot GC what is happening in `insert_image` because something from `insert_pdf` has stale file handles or other resources.

**Comment by JorjMcKie** [comment]
I think I can find a solution. Let me ask you this:
* are your images PNG exclusively?
* always with alpha or always without?

It seems I need to keep MuPDF out of the image insertion business for this type of mass processing. I just developed with someone a solution where the images are being inserted directly (by low-level PyMuPDF code), and their insertion on the page takes place based on xref only.

I am going to assume a few things and make a test with 2000 iterations and watch the maximum memry requirement ...

**Comment by cbm755** [comment]
PNG or JPEG, no alpha channel.

The number of PNG/JPEG being inserted one-per-page is usually 5--10, probably "never" *cough* more than 30: at any rate, being memory-optimal within this loop is not important to me.

The issue for me is the outer iteration (the calls to `assemble` in my MWE).

**Comment by JorjMcKie** [comment]
When using the following script it seems that we stay in the low 2-digit MB memory region: I checked every 100 assemble invocations.
[test2.zip](https://github.com/pymupdf/PyMuPDF/files/7590482/test2.zip)

The approach is:
* convert every image to a JPEG stream before inserting. This seems beneficial both, in terms of final PDF size as well as insertion speed, and also (weird!) memory requirements.
* provide all meta info available width, height, alpha=0

Another script (test3.py) uses PyMuPDF low-level code to do the image insertion into the file, so that the ``insert_image`` method only needs to refer to a pre-inserted xref.
This is a **_lot_** faster and also seems to require even less memory:
[test3.zip](https://github.com/pymupdf/PyMuPDF/files/7590494/test3.zip)

Please let me know your impressions.

**Comment by cbm755** [comment]
test2: I tried removing `doc.close()` and this still shows growth so I guess I don't really see how this is different than my MWE.  See below.

test3: "a lot faster" is certainly interesting!  I assume I can pass FlateDecode for my PNGs instead of transcoding if I want.

- - - - -

Anyway, maybe I should've specified that I'm not really looking for a recipe here: I'm reporting a bug.

  1.  why should it matter if the first page was added with `insert_pdf` or `open`?  And yet it does.
  2. why do I need to explicitly close `doc`?  Its fine, happy to do it.  But it *feels* like a bug.

Or maybe this is just a fundamental misunderstanding on my part: `doc` is like a file handle: it must be explicitly closed (or used in a context manager).  Actually I feel like you explained that to me before *sheepish grin*.

**Comment by JorjMcKie** [comment]
> why should it matter if the first page was added with insert_pdf or open? And yet it does.
> why do I need to explicitly close doc? Its fine, happy to do it. But it feels like a bug.

There is an unresolved memory leak issue in ``insert_pdf``. It looks like it is hidden somewhere inside MuPDF code which I am using for the method. It also seems that I have aggravated the issue in v1.1815 (as reported in #1351) when I changed the code for handling context managers.

So for the time being it is better to use another approach where possible - especially when very many documents must be processed.

Every document consists of two parts: a Python ``Document`` object which wraps an ``fz_document`` inside MuPDF code, which in turn represents a file handle among a lot of other things. ``Document.close()`` (among other things) passes a *destroy* command to MuPDF, which leads to closing the underlying file (and the destruction of all the other stuff).

So if you can achieve your goal by appending image pages to a given front page, then you will save one file handle - and also avoid the memory issues of ``insert_pdf``.

**Comment by JorjMcKie** [comment]
I started the next v1.19.3 with preliminary wheels [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/master/wheelhouse).
It contains the following improvements which are relevant for this issue:
* improved `insert_image()` such that providing filename or stream no longer make a difference and never lead to the internal building of pixmaps
* width, height and alpha are no longer needed and are ignored
* re-instated the handling of the `Document` context manager as it was prior to v1.18.15.

With all that I made tests based on your code snippet. These tests included:
* **_2'000 iterations_**
* (a) with using ``insert_pdf`` for the font page, and (b) extending the front page with image pages
* 6 image pages inserted with images of a total size of 1 MB
* with and without context manager
* Windows and Linux (in Windows WSL)

Results:
* No ``assemble`` iteration ever exceeded a memory requirement of 20 MB - computed as memory at iteration end minus memory at start of the process.
* On Windows, this memory delta was even as low as 7 MB.
* At end of job, the process memory was as low as at its start (+1 MB).
* No file handle exhausting ever occurred.

Comments:
* The test setup remains artificial in that every output PDF is exactly identical: always the same cover page and the same images.
* The memory usage is - like always - somewhat blurred by the fact that MuPDF comes with its own memory cache, which has the standard size of 256 MB in PyMuPDF. This is most intensely used for images and fonts, but also other stuff. This is one of the reasons, why the overall memory usage does almost never drop to the value at start of the process. It however neither is a full explanation.
* When using garbage collection module `gc`, there will be no complaints about lost / unreachable memory ...

Here are the test scripts:
[test.zip](https://github.com/pymupdf/PyMuPDF/files/7604453/test.zip)

`test0.py` is with `insert_pdf()`, `test1.py` extends a cover page with image pages.

**Comment by cbm755** [comment]
Great!   I will test that with some real data and report back...  might be after 1.19.3 is out on pypi.

**Comment by cbm755** [comment]
FYI: Plom's testsuite passes with the cp310 version of those wheels.

**Comment by JorjMcKie** [comment]
New version 1.19.3 is being uploaded to PyPI.
