### ISSUE TITLE
PDF version of corrupted files has changed from 0.0 to 1.7 (1.7 is incorrect)

### ISSUE THREAD

**Issue by Matmaus** [pymupdf/PyMuPDF#1435]
## Describe the bug
File: [pdf-example-with-bug.zip](https://github.com/pymupdf/PyMuPDF/files/7677588/pdf-example-with-bug.zip)

Since version v1.19.0, PyMuPDF set the version to `1.7` if it can not find the version marker (`mupdf: cannot recognize version marker`). It was set to `0.0` in all previous versions. If it is set to `0.0` it can be used as an indicator that something went wrong and the file is corrupted somehow for example. If it is not considered a bug, what are the benefits of having an incorrect version set?

## To Reproduce
```python
import fitz as pymupdf

doc = pymupdf.open('pdf-1.1')  # see section above
doc.metadata['format']
```

## Expected behavior
The version should not be set to incorrect version `1.7`, rather to `0.0`.

## Your configuration
* Linux 4.19.217-1-MANJARO
* gcc (GCC) 11.1.0
* 3.9.7 (default, Oct 10 2021, 15:13:22)
* PyMuPDF 1.19.0 installed via pip (and all above), Python bindings for the MuPDF 1.19.0 library.

## Additional context
I do not want to fix this file, I have more files like this one. I would like to be able to extract the PDF version in the correct form only. The previous solution using `0.0` was better for me since the version is invalid. It is clear that something went wrong and the header is broken at least.

**Comment by JorjMcKie** [comment]
Well, action taken when a PDF file repair is considered necessary are decided inside MuPDF code.
PyMuPDF has no influence here.
Let me also mention that a broken PDF can be easily recoginized by checking a few indicators after open:
* If a `Document` object has not been created, then the matter is clear.
* If `fitz.open` created a document, you can check `doc.is_repaired`. If `False`, error messages should have appeared on `sys.stderr`. In addition, `fitz.TOOLS.mupdf_warnings()` will return detailed messages.

In contrast to this, relying on the PDF version being invalid has never been a reliable indicator.

**Comment by JorjMcKie** [comment]
```python
>>> doc=fitz.open("pdf-1.1")
mupdf: cannot recognize version marker
>>> doc
Document('pdf-1.1')
>>> # the following checks are reliable and provide a cleaner picture
>>> print(fitz.TOOLS.mupdf_warnings())
cannot recognize version marker
trying to repair broken xref
repairing PDF document
>>> doc.is_repaired
True
>>> 
```
The extension, ``".1"`` is not recognizable, so the default assumption "PDF" is chosen.
You may even have objections to this, don't you?

Doing the following, produces a usable PDF. It may still not make sense though, because damages could exist all over the place. A complete health check is not performed (would be a performance hog). Only the version, the xref table and the page tree are investigated.
But if a save is accepted by the library at all, then it **_must_** produce a PDF which passes at least the most basic criteria - and specifically must not have an invalid PDF version marker.

```python
>>> doc.save("test.pdf")
>>> 
```

**Comment by Matmaus** [comment]
Thanks for the quick response and investigation.

What I wanted to point out is that 1) the behaviour has changed, and 2) it changed to worse, I think. But I do not request any changes here anymore since it has changed in MuPDF directly, as you have said. On the other hand, I would like to know if I can go without creating an issue in MuPDF.

Let me describe my trouble a bit better:
- I do not want to repair this file. It is corrupted on purpose. If you run `$ head pdf-1.1` for example you can see the following content:
```
Here should not be anything - it is not correct
But some readers can still read it
----------------------------------
__%PDF-1.1
1 0 obj
        <<
                /Type /Catalog
                /Pages 2 0 R
        >>
endobj
```
- File extension is irrelevant. I did not realize I created `.1`  extension by naming the file `pdf-1.1` before uploading. You can rename it to `example.pdf` for example.
- I do not want to determine whether the file is corrupted or not on the basis of the value of the version, rather I want to know whether the version I get is correct (if it is invalid it indicates that there can be more things broken, but it is not important in this issue).
- I would like to get the correct version or nothing, i.e. `None` or `0.0`, if it can not be found. This is what I could use in version 1.18.9 and below:
```python
doc = pymupdf.open('pdf-1.1')
version = doc.metadata['format'][4:]
if version == '0.0':
    version = None
print(version)  # version is correct (probably) or nothing
``` 
In version 1.19.0 and above I can not do that anymore. Not only that the version will not be invalid (`0.0`) anymore but it will be valid (`1.7`). I think this is what I should do now based on your suggestions:
```python
doc = pymupdf.open('pdf-1.1')
version = doc.metadata['format'][4:]
if 'cannot recognize version marker' in pymupdf.TOOLS.mupdf_warnings():
    version = None
print(version)  # version is correct (probably) or nothing
```
Now it depends on logs instead of an invalid version.

**Comment by JorjMcKie** [comment]
I understand better now. You know from some other context, that it is meant as a PDF, but the file format is definitely broken.
MuPDF will always try to repair the PDF. This is inevitable. It is not peculiar with this intent: Adobe, the MuPDF viewer and many if not most others will open it - albeit with complaints.

And yes: if a valid version marker cannot be found (at the right place!), then you will find an appropriate warning in that log.

BTW: it **_does have a valid version_** - just at an unexpected place. So you could argue that the prior "0.0" return was wrong either.
Submitting a bug to MuPDF makes no sense at all:
* Simply too unimportant to bother
* **_It is no bug!_**
* You have all the means at hand to detect the situation - this is what you figured out already after all.
* You can also read the file as a `bytes` object, `pdfbytes = open("file.xxx", "rb").read()` and check `pdfbytes.startswith(b"%PDF-")` before you pass it to `doc=fitz.open("pdf", pdfbytes)`.

**Comment by Matmaus** [comment]
OK, thank you. I'll go with the solution proposed above.

I just want to clarify one more thing. Yes, it does have a version. I would expect to either return it (`1.1`) or indicate it was not found because it is at an unexpected place or whatever (`None` or `0.0` as in all previous versions). I definitely do not expect to get version `1.7`, which is incorrect. This seems like a default value to me. And this is what I consider to be a bug. But well, getting the most probable version can be a part of the repairing process...

> So you could argue that the prior "0.0" return was wrong either.

Even though returning `0.0` was wrong as well, it was easy to know it is wrong. Now it is not that easy and you have to look into logs for a specific string.
