### ISSUE TITLE
ISSUE with search_For, Page.insert_link()

### ISSUE THREAD

**Issue by prajwalInavolu** [pymupdf/PyMuPDF#1439]
I am getting AttributeError: 'Page' object has no attribute 'search_For' error for methods like 'Search_For','insert_link',update_link().

I am trying to add internals links of page numbers to Table of contents page. if there are not available ,please let me know what else i can use. 

My code need to get Rect of text and add the clickable link in TOC, so that it can navigate to page

**Comment by JorjMcKie** [comment]
Please see the documentation!
The corrct method name is `search_for`.
