### ISSUE TITLE
Memory Leakage in class TextPage since v1.19.3

### ISSUE THREAD

**Issue by mwade625** [pymupdf/PyMuPDF#1474]
I just updated to Version 1.19.3 from 1.18.9 running python 3.9.7 on ubuntu 21.10.  I am still seeing steady memory growth when using this version.  The memory corruption bug when adding annotations seems to be resolved, but I still continuously consume more memory when running large #'s of PDF's.

Are there any known work-arounds for this issue?  I see you reported multiple memory growth patches in this release so I was hoping it was resolved.

**Comment by mwade625** [comment]
To validate the memory leak, I reverted back to version 1.18.14 and I have no memory leak using that version.  Please note above I was using version 1.18.14 previously.

**Comment by JorjMcKie** [comment]
Please be more specific: under **_which circumstances_** do you observe leakages that did not happen earlier?

**Comment by mwade625** [comment]
My apologies, that was not a very helpful issue submission.   

Specifically I am extracting text from many thousands of PDF's.  To do so the code is basically as follows:

`
pdf_doc = Document(file_name)
num_pages = pdf_doc.page_count 
for page_index in range(num_pages):
   page = pdf_doc[page_index]
   page_text = get_text(page, option='rawdict')

   # Here I am just iterating the page_text['blocks'] to create an annotated text class so that I can see the location of every character (graphical coordinates) and other information.
   save_text(doc_text)
`
That code is encapsulated in a class and I instantiate that class in multiple processes extract the text and push it out to database on the back end.  Using any version > 1.18.14 I am getting a memory leak.  With version 1.18.14, it is stable and memory usage does not increase.  I attempted to analyze this a bit using tracemalloc and noticed small but steady allocations in fitz.  It wasn't clear that this was the memory leak, but it made me try the older version again and w/o any other code changes that resolved the issue.

Hopefully this gets you enough information to go on.  Thanks.

**Comment by JorjMcKie** [comment]
I understand.
This is the first time anyone reports memory leakages around text extraction.
The past improvements you were referring to, were around `insert_pdf()` and page pixmap creation, which are parts of the code entirely unrelated to text extraction.
All of them, text extraction code, pixmap creation and `insert_pdf()` in turn have nothing to do with annotations.

So in order to trace down what is happening I wonder if you could let me have code that reproduces the issue.

**Comment by mwade625** [comment]
I will try to put together a simple program that reproduces the issue.  It's possible it is data dependent though, which I can't help with unfortunately.  I was very surprised myself about it.  I have been comparing it to Tika on large scale for robustness and the quality of the text extraction before deciding if it was worth licensing or not.  I will post back with either some simple code or a project on github if that is ok.

**Comment by JorjMcKie** [comment]
Never mind:
Found an error in v1.19.3 (only). You should be ok using v1.19.2.

**Comment by mwade625** [comment]
Thanks for running that down.  I can confrim that with 1.19.2 the memory leak is not there when working with text.  Unfortunately I do a lot of annotations in another part of my app.  Hopefully the next release will resolve this!  Here is my test driver in case it's helpful:

`from typing import List, Union
from os import scandir
from os.path import splitext

from fitz import Document, Page
from fitz.utils import get_text
from itertools import filterfalse
from multiprocessing import Pool


def scantree(path):
    for file in scandir(path):
        if file.is_dir(follow_symlinks=False):
            yield from scantree(file.path)
        else:
            yield file.path


def extract_text_worker(file: Union[List,str]):
    print(f'Processing: {file}')
    doc_text = ''
    pymu_text = ''
    pdf_doc = Document(filename=file)

    num_pages = pdf_doc.page_count
    for page_idx in range(num_pages):
        page:Page = pdf_doc[page_idx]

        page_text = get_text(page, option='rawdict')


if __name__ == "__main__":
    root_path = 'PATH TO DATA WITH TEST FILES'
    files = scantree(path=root_path)

    pdf_files = list(filterfalse(lambda x: splitext(x)[1].lower() != '.pdf', files))

    worker_pool = Pool(processes=10)
    worker_pool.map(extract_text_worker, pdf_files)
    worker_pool.close()
    worker_pool.join()`

**Comment by JorjMcKie** [comment]
Fixed in v1.19.4 currently being uploaded.
