### ISSUE TITLE
There are cases where some PDF words are glued together 

### ISSUE THREAD

**Issue by dannydocrxiv** [pymupdf/PyMuPDF#1489]
There are cases where PDF parser (raw_json blocks) is gluing chars (no space between last one of one word to next) like in below text (page 1) PDT attached
"derived" and "from" are glued for example ..
Can see there is some jump in coordinates? Is there a systematic way to fix it or I need todo coordinate calculations myself?

Factors that enhance monocyte release from bone marrow into blood include chemokines
derived from sites of inflammation,8-11 and recent studies have identified
hyperglycemia and hyperlipidemia as important factors that regulate
monocytosis by acting on bone marrow progenitor cells.
[e33.pdf](https://github.com/pymupdf/PyMuPDF/files/7774257/e33.pdf)

**Comment by JorjMcKie** [comment]
The file makers (often) did not include spaces between words, but directly addressed the character locations.
So it is up to the viewer's heuristics to generate spaces between characters apparently distant enough.
I checked a few, and PDF-XChange and Foxit also did not show spaces, my Firefox PDF plugin in contrast did ok.
There is nothing / not much you can do about this.
You might try the layout preserving text extraction of the command line module `python -m fitz gettext ...` and see where it leads to.

**Comment by JorjMcKie** [comment]
![grafik](https://user-images.githubusercontent.com/8290722/147359929-407e9f6a-973d-4731-af28-77051deae99b.png)

**Comment by JorjMcKie** [comment]
> I need todo coordinate calculations myself?

You can of course always take `page.get_text("rawdict")` and look at the single character bboxes. Exactly this is done by the mentioned layout preserving extraction.

**Comment by dannydocrxiv** [comment]
Yes, that is what I started doing. Calculating average distance from character to character and inject space when I see a large jump compared to average distance between previous characters of the word.  BTW: sometime there is the opposite problem when ALL the characters in a word have space between then like (S P A C E) and to index it you need to shrink the spaces

**Comment by JorjMcKie** [comment]
> when ALL the characters in a word have space between then like (S P A C E) and to index it you need to shrink the spaces

This is perhaps more easily addressible: use text extraction flag bit `fitz.TEXT_INHIBIT_SPACES`.

**Comment by dannydocrxiv** [comment]
Ok, will try. Thanks
