### ISSUE TITLE
Add 'xref' value in page.get_text('dict') result for image block

### ISSUE THREAD

**Issue by SummerXXXX** [pymupdf/PyMuPDF#1491]
**Is your feature request related to a problem? Please describe.**
After extract images from pdf file, I try to get image titles and some other image descriptions (for example: data source).

For now, my solution is analyzing the page structure, especially text blocks before  and after the image block.

First, I extract all images in a page using page.get_image_info()  and get a image xref (I think it's a unique id for each image).

Then, I get the page structure by page.get_text('dict', sort=True) and try to locate image block with xref, (so I can get related text blocks at next step)

But I found the return result of page.get_text('dict', sort=True) doesn't contain xref info for image block:

![Screenshot 2021-12-27 142337](https://user-images.githubusercontent.com/10771754/147441132-17254a8e-1e1a-4e9e-8803-69b7c4a99499.png)

Does that means I can't directly locate a image block with an unique id?

For now, my solution is match the image height and width, so as to check if the image I get in page.get_image_info() and the image block in  page.get_text('dict', sort=True)  is the same one.

**Describe the solution you'd like**
Is this possible to add a 'xref' value in the  page.get_text('dict') return result for image blocks?

**Describe alternatives you've considered**
I debugged the code, I found I can't simply modify the python code, the  page.get_text('dict', sort=True)  return result is generated in deeper level.

Or if there is some other way to get a xref value for an image block?

**Additional context**
my environment:
windows 10
python 3.9
pymupdf 1.19.3

**Comment by JorjMcKie** [comment]
All this is already there!

1. There is a special method `page.get_image_info()` which delivers the metadata of all images on a page. This is the image blocks of `page.get_text("dict")` more or less (just the image binaries are missing). But you can request the MD5 hashes and the PDF xrefs to be included via parameters. The key "digest" uniquely identifies an image via its MD5 hash code. The "xref" key allows to backtrace to `page.get_images()`.
2. Pixmaps also have the attribute `digest", which is what you can check (the method does exactly that) when building `fitz.Pixmap(doc, xref)`.

**Comment by JorjMcKie** [comment]
Please remember that text extraction / text search as such **_has not necessarily anything to do with PDF._**
It works for all MuPDF-supported document types.
Undigging xref numbers and assigning them to extracted images does take time!
In addition, even for PDF documents, not every image you find in text extraction, is an xref-based image!
