### ISSUE TITLE
Segfault on attempt to read the ToC of a certain file

### ISSUE THREAD

**Issue by mara004** [pymupdf/PyMuPDF#1507]
## Describe the bug (mandatory)
When calling `fitz.Document.get_toc(simple=False)` on the attached document, there is a crash (segmentation fault).

`mutool show ./FRC_28_8.2.2__T8.4_Last_remove_obj2.pdf outline` works correctly though, so presumably the bug is on the PyMuPDF side.

## To Reproduce (mandatory)
Same code as in https://github.com/pymupdf/PyMuPDF/issues/1505, only with different file: [FRC_28_8.2.2__T8.4_Last_remove_obj2.pdf.txt](https://github.com/pymupdf/PyMuPDF/files/7798154/FRC_28_8.2.2__T8.4_Last_remove_obj2.pdf.txt)
The document is part of the PDFium test suite (`pdfium/testing/corpus/fx/`). Maybe this file is invalid, but it seems that most other libraries can handle it (qpdf, poppler, pdfium).

## Expected behavior (optional)
No crash should happen.

## Your configuration (mandatory)
 - Linux KDE Neon User (64-bit)
 - Python 3.8.10
 - PyMuPDF 1.19.4, installation method: wheel

## Additional context (optional)
I might report more ToC issues because I'm currently doing ToC parsing tests with all documents in my home directory...

**Comment by mara004** [comment]
Just checked that `get_toc(simple=True)` works correctly - it's only `simple=False` that crashes.

**Comment by JorjMcKie** [comment]
There are pre-version wheels [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/master/wheelhouse), which should fix this.

**Comment by mara004** [comment]
Thanks! With the pre-version, all files pass now :)

**Comment by JorjMcKie** [comment]
Thank you for prompt reaction!
