### ISSUE TITLE
RuntimeError: Too many open files (processing a few thousand PDFs)

### ISSUE THREAD

**Issue by jeanmonet** [pymupdf/PyMuPDF#1509]
Hi, firstly, all the best for 2022! May PyMuPDF continue its rise :)

## Describe the bug
While processing a few thousand PDFs to extract some information, I have encountered the "too many open files" error.
I am not currently able to provide a single snippet of the code to reproduce because the code is quite complex and has multiple locations where PDFs are opened and closed, and **did not yet manage to set up a simplified reproducible example**.

**However**, to be noted:
- Without any change to the code or the environment, the error happened immediately after updating to `1.19.4`.
- Reverting to `1.19.3` (without any other change) allows me to process the same or more PDFs without triggering this error.
- All PDFs are opened using a `with` statement, to ensure the file handler is properly closed.
    - HOWEVER (and this is actually potentially a separate but related issue), even with this setup I have previously encountered the "too many open files" error. I have changed all `with` statements to use `contextlib.closing` as such: `with contextlib.closing(fitz.open(...)): ...`.  Making this change has allowed me to no longer encounter that error (I mean before updating to `1.19.4`).  I wanted to do more testing on this to make a proper bug report but did not have time.  Since the issue that appeared with 1.19.4 is related, I thought I'd mention it.

## To Reproduce
I have not yet a simplified reproductible example, but it involves iterating over 5000 or more PDFs using the `with fitz.open(...): # process PDF 1`. I guess the number of PDFs that will trigger an error will depend on how many open files the system can handle?
I have not yet tried this (will have to do it on a virtual machine to avoid having to reboot the entire machine), but it would go like this:
```python
some_path = pathlib.Path("some/path")   # directory containing 10000+ PDFs, more files than system can keep open simultaneously

def my_gen():
    for pdf in some_path.glob("*.pdf"):
        with fitz.open(pdf) as doc:
            yield doc[0]    # Yield page object for handling outside of generator

for page in my_gen():
    page.get_text()   # or something...
```

## Your configuration
 - Ubuntu 20.04 LTS latest updates installed
 - Python version, 3.9.9
 - PyMuPDF version: pip installed 1.19.4

**Comment by JorjMcKie** [comment]
Hm, weird.
I have just confirmed that `doc.close()` indeed closes the file and that the context manager invokes the close.
I created (almost 10 thousand files and executed this:
```python
import fitz
import os

files = os.listdir()
for i, f in enumerate(files):
    if not f.endswith(".pdf"):
        continue
    with fitz.open(f) as doc:
        page = doc[0]
    if not i % 200:
        print(f"iteration {i}")
print()
print(fitz.__doc__)
print(f"processed {i} files.")
```
Worked without problems under Windows and Linux (Ubuntu WSL):
```
iteration 8400
iteration 8600
iteration 8800
iteration 9000
iteration 9200
iteration 9400


PyMuPDF 1.19.4: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-01-01 00:00:01.
Built for Python 3.8 on linux (64-bit).

processed 9554 files.
```

**Comment by jeanmonet** [comment]
Hmm I will have to try it again to see if I can isolate the behavior, but it will take some work. I can close the issue for now and open open again when I have more info.

**Comment by JorjMcKie** [comment]
Ok, thanks for your efforts!
