### ISSUE TITLE
Inconsistent UTF-8 support in Optional Content features

### ISSUE THREAD

**Issue by Brampie66** [pymupdf/PyMuPDF#1513]
Hi,

I'm trying to port a script that now uses the quick pdf library (which is no longer for sale it seems), I'm using version 1.19.4
I'm working with food packaging layouts and I need to disable certain layers before rendering the pdf to png or jpeg.
I'm unsure which issues are my fault.
Issue 1:
for layer_ui_configs I seem to get an error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 13: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bram\PROJECTS\MuPDF.py", line 18, in <module>
    x = doc.layer_ui_configs()
  File "C:\Python39\lib\site-packages\fitz\fitz.py", line 5048, in layer_ui_configs
    return _fitz.Document_layer_ui_configs(self)
SystemError: <built-in function Document_layer_ui_configs> returned a result with an error set

Issue 2:
When I use the get_ocgs() function to get the "layers" and then set the layers I don't need/want to off with set_layer(-1,on=onLayer,off=offLayer) this does have an effect when I save as PDF but the page.get_pixmap() function seems to ignore this and always renders an image as if all layers are selected/on, I tried saving as PDF, opening that same PDF and still get_pixmap() does renders all layers. When I open the saved PDF with PhantomPDF the active layers are correct, so I guess it's just an issue with get_pixmap, am I doing something wrong ? Is this actually suppose to work ?
If I could get a pixmap of just one layer this would also be a good solution, I could combine them myself (I may need to do this anyway to calculate ink "coverage")

Issue 3:
I had a lot of difficulty getting the artbox to work, the artbox I was getting from the pdf wasn't top-left and right bottom.
I was able to fix this with swapping the y0 and y1, many (but not all) of the pdf files I need to render seem to have this issue.
pix = page.get_pixmap(clip=fitz.Rect([page.trimbox.x0,page.trimbox.y1],[page.trimbox.x1,page.trimbox.y0])) 

Am I doing something wrong ?

**Comment by JorjMcKie** [comment]
Let's separate this into single issues. 

I would like to look into the ArtBox issue first: Can you please let me have an example for where this goes wrong and another one where it works? This phenomenon should actually not exist: either there is an error or not ...

**Comment by Brampie66** [comment]
You would like to have the PDF itself ? I need to ask permission for this, I'm not suppose to share these files.
I can show the output of the functions if this is all you need.

**Comment by JorjMcKie** [comment]
Hm, firstly you can always send stuff to my e-mail to prevent it becoming public here.

Then I need only the page definition source(s) in the PDF to compare them with how the pixmap(s) look like (an image of these I would also need).
The page object definition is accessible via `print(doc.xref_object(page.xref))`.
A pixmap can be made via `page.get_pixmap(clip=page.artbox)` as you know I have noticed.
There may be a minor complication:
* the method takes the page rectangle in absence of the clip parameter. This is basically the CropBox if the page is not rotated, otherwise obviously the rotated version of it.
* if `clip` is given, then the corresponding subarea of the page rectangle is taken
* if an ArtBox is not part of the CropBox (which is possible), some adjustments arre required, see below

If any of the above is contrary to your requirements, you would have to do some (temporary) manipulation(s) like setting another rotation, expanding the CropBox to the MediaBox, etc.

**Comment by Brampie66** [comment]
Hi,

Access is a difficult situation...

I looked in to this a bit more:
From what I can see all pdf files need their y1 and y0 swapped in order to get the right output (for the ones where I can see output without disabling layers).
I have a few exceptions (on 1000 files) but these are special cases where the artbox has a negative value or so.
output of print(doc.xref_object(page.xref)):
  /BleedBox [ 0 0 935.433 453.543 ]
  /Contents 7 0 R
  /CropBox [ 0 0 935.433 453.543 ]
  /MediaBox [ 0 0 935.433 453.543 ]
  /Parent 3 0 R
  /Resources <<
    /ColorSpace <<
      /CS0 8 0 R
      /CS1 9 0 R
      /CS2 10 0 R
    >>
    /ExtGState <<
      /GS0 11 0 R
      /GS1 12 0 R
    >>
    /Font <<
      /T1_0 13 0 R
      /T1_1 14 0 R
      /TT0 15 0 R
    >>
    /ProcSet [ /PDF /Text ]
    /Properties <<
      /MC0 16 0 R
      /MC1 17 0 R
      /MC2 18 0 R
      /MC3 19 0 R
      /MC4 20 0 R
      /MC5 21 0 R
    >>
  >>
  /TrimBox [ 70.8661 70.8661 864.567 382.677 ]
  /Type /Page

.cropbox is Rect(0.0, 0.0, 935.4329833984375, 453.5429992675781)
.trimbox is Rect(70.86609649658203, 382.6769027709961, 864.5670166015625, 70.86599731445312)
trimbox.height is zero in this case, a swapped trimbox
Rect(70.86609649658203, 70.86599731445312, 864.5670166015625, 382.6769027709961)
has a height of 311.81090545654297

For me actually the layer issue is a bigger problem, is what I'm seeing normal or should get_pixmap consider the status done by set_layer

**Comment by JorjMcKie** [comment]
> For me actually the layer issue is a bigger problem, is what I'm seeing normal or should get_pixmap consider the status done by set_layer

I understand, but this is definitely not possible to resolve without having the (a) file at my disposal.

**Comment by Brampie66** [comment]
I guess any multi layer pdf will do ? I can try to find or make a file that has the same issues ?

**Comment by JorjMcKie** [comment]
Probably, but you also reported encoding issues ... the example should include that issue, too.

Otherwise, fine.

**Comment by JorjMcKie** [comment]
I don't know how important (and urgent) it is for you to actually select single layers **_only_** ... and keep others invisible.
Meaning, if you are okay if **_everything_** is visible, then you can simply remove the Optional Content capability completely. A pixmap would then show everything on the page that is available.
Just let me know ...

**Comment by Brampie66** [comment]
Hi,

It is important because those layers are blocking the layers that need to be viewed.
Like when there is a layer with measurements on top of the image that is important.

Bram

**Comment by Brampie66** [comment]
I think I got a more or less working test.
This software allows you to create a pdf with multiple layers, https://www.qoppa.com/pdfstudio/
I created a PDF with 2 bunnies on 2 layers, get_pixmap does behave like it does on my end (showing both bunnies).
The error with doc.layer_ui_configs() actually happens when I use a non ascii name for the layer, Weiß for example
[layers.pdf](https://github.com/pymupdf/PyMuPDF/files/7809891/layers.pdf)
[layers_output.pdf](https://github.com/pymupdf/PyMuPDF/files/7809892/layers_output.pdf)
![layers](https://user-images.githubusercontent.com/21243781/148112130-284c3fbb-cb20-4eac-a3ab-a604f7a84a84.png)
e

import os
import fitz
import sys

pdfPath = f"c:/Users/bram/Downloads/"
doc = fitz.open(os.path.join(pdfPath,"layers.pdf"))
print (doc.layer_ui_configs())

ocgs = doc.get_ocgs()
print(f"ocgs={ocgs}")
layer = doc.get_layer()
print(f"layer={layer}")
onLayer = layer.get("on",[])
offLayer = layer.get("off",[])
for key in ocgs:
    if ocgs[key]["name"].lower().find("wit")>-1:
        print (f"TURNING OFF LAYER {key}-{ocgs[key]['name']}")
        if key in onLayer:
            onLayer.remove(key)
            offLayer.append(key)
doc.set_layer(-1,on=onLayer,off=offLayer)
layer = doc.get_layer()
print(f"layer={layer}")
print (doc.get_ocgs())

doc.save(os.path.join(pdfPath,"layers_output.pdf"))

page = doc.load_page(page_id=0)
print(doc.xref_object(page.xref))
box = page.cropbox

print (box)
print (box.height)

pix = page.get_pixmap(clip=box)
pix.save(os.path.join(pdfPath,"layers.png"))

Thanks in advance

**Comment by JorjMcKie** [comment]
Made a few changes:
1. corrected stupid page rectangle error (hopefully)
2. changed OC layer function to accept non-ASCII

Without any other change, I took your example file and flip-flopped the states of the two annotations, please see attached IDLE log and associated page pixmaps.
Looks as it should to me. Please confirm.

If you want a version for testing, please let me know your config: OS, Python version and bitness.
[exec-log.zip](https://github.com/pymupdf/PyMuPDF/files/7812500/exec-log.zip)

**Comment by Brampie66** [comment]
Hi,

Looks very good, thanks for this.
For testing I use windows/64bit/python 3.9.5, if you can send a version I'll test with all the files I have.

thx
Bram

**Comment by JorjMcKie** [comment]
[PyMuPDF-1.19.5-cp39-cp39-win_amd64.zip](https://github.com/pymupdf/PyMuPDF/files/7814399/PyMuPDF-1.19.5-cp39-cp39-win_amd64.zip)
Good luck!

**Comment by Brampie66** [comment]
Everything looks ok now as far as I can tell.
Thanks a lot :-)

**Comment by JorjMcKie** [comment]
I have changed the issue title to better reflect what really was wrong.
Will be officially fixed in the next version.

**Comment by JorjMcKie** [comment]
Fixed in v1.19.5 currently being uploaded.
