### ISSUE TITLE
Enhance the quality of scanned PDF

### ISSUE THREAD

**Issue by maiiabocharova** [pymupdf/PyMuPDF#1516]
Sorry to disturb, but is there a way in enhance a scanned PDF quality (make dirty greyish background white and make the contrast higher)?

**Comment by JorjMcKie** [comment]
You do not disturb at all, no worries.

> make dirty greyish background white and make the contrast higher

In general no, this is out of PyMuPDF's scope. It actually is an image enhancement topic. You might want to consult Pillow documentation for this.
Also, OCRmyPDF has a feature in that area if I remember correctly. Including improvement of the scanned image orientation.

There are a handful of things in PyMuPDF which may also help, e.g.
1. gamma correction of the pixmap
2. you **_could_** write your own routine and examine the `pix.samples`. Like making it white based on some threshold, e.g. if for an RGB image the pixel is greater than `(200, 200, 200)` replace it by `(255, 255, 255)` or whatever. But it is a shaky thing to do, Pillow and the tools underneath OCRmyPDFs hood are proven and probably less error prone.

**Comment by JorjMcKie** [comment]
Let me transfer this to a **_Discussion._**
