### ISSUE TITLE
Missing wheel for Linux aarch64 

### ISSUE THREAD

**Issue by colinchilds** [pymupdf/PyMuPDF#1528]
**Is your feature request related to a problem? Please describe.**
I'm trying to move my app from an x86_64 AWS EC2 instance type to some of the newer ARM Graviton types. When trying to create a docker image for it, the PyMuPDF wheel is missing so it tries to build from source and fails with the typical `fatal error: fitz.h: No such file or directory`.  From what I can tell, `cibuildwheel` supports it and I couldn't see any reason why it wouldn't be building that arch from your [linux-pypi.yml](https://github.com/JorjMcKie/py-mupdf/blob/master/.github/workflows/linux-pypi.yml) so I assume it's something small in that config I'm missing.

**Describe the solution you'd like**
Please build a `cp37-manylinux_aarch64` wheel for ARM processors.

**Additional context**
You can easily reproduce with the following Dockerfile:
```
FROM python:3.7
RUN python -m pip install --upgrade pymupdf
```

Then try to build it with `docker buildx create --use; docker buildx build --platform=linux/arm64 -t myimage .`

**Comment by JorjMcKie** [comment]
Please see my comment [here](https://github.com/pymupdf/PyMuPDF/discussions/1486).
I am unable to include Tesseract OCR in these generations, because they take so awfully long that the 90 minute restriction restriction of Github is exceeded.
So if I resume building them it will be without this feature. Other than that it should be possible to do them again.

**Comment by colinchilds** [comment]
Ah, thank you. I did not see that other issue. I’m personally fine without that feature. I’d rather have something than nothing! If you could start building it again without Tesseract, I’d really appreciate it.

**Comment by colinchilds** [comment]
Also, if you ever switch to using self hosted runners, you could use an ARM based runner and it will drastically speed up those builds and probably allow you to enable Tesseract again.

**Comment by JorjMcKie** [comment]
I have generated the mentioned pre-version wheels - if you want to give it a try.

**Comment by colinchilds** [comment]
Thank you! I'm looking forward to them being on PyPi as well.

**Comment by JorjMcKie** [comment]
@colinchilds 
> switch to using self hosted runners

That would mean having this running on my local machine, right?
If so I would end up having the resulting wheel sitting on my desk. Then I would have to upload them - which would cost me quite some money given my bad internet connection (which is all based on prepaid mobile tariffs ...).
But maybve I'm on the wrong track.

**Comment by colinchilds** [comment]
No, self hosted would mean spinning up an EC2 instance or something. There are GitHub actions for creating an EC2 instance, running your job, then destroying the instance again. [Here's the documentation](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) for self hosted. [Here's an example](https://github.com/machulav/ec2-github-runner) on-demand GitHub runner. It would cost money for however many resources you use in EC2 though, which would likely be minimal since they are only being used during the time it takes to run the build.

**Comment by JorjMcKie** [comment]
@colinchilds - thank your for the information. Interesting, I'll look into the docu.
