### ISSUE TITLE
Program exit when I try to re-scale the pixmap image

### ISSUE THREAD

**Issue by SummerXXXX** [pymupdf/PyMuPDF#1543]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I want to re-scale a exist pixmap image, for example, the source pixmap image have size 1000 * 800 pixels,  I want to re-size the image to 100 * 100 pixels

I found in Pixmap class,[ __init__](https://pymupdf.readthedocs.io/en/latest/pixmap.html#Pixmap.__init__)(self, source, width, height[, clip]) function may could do that.

But the test program exist:
Process finished with exit code -1073741819 (0xC0000005)

Not sure if I use it wrong.

## To Reproduce (mandatory)
I write a test code:
`import fitz

pix = fitz.Pixmap("test.jpg")
pix1 = fitz.Pixmap(pix, 100, 100)
pix1.save("test2.jpg")`

## Your configuration (mandatory)
 - Win10 x64 professional
 - Python 3.9  64bit
 - PyMuPDF 1.19.3

**Comment by JorjMcKie** [comment]
Pixmap creation consists of constructor overloads. So success is crucially dependent on that different argument patterns select the right constructor.
Something is going wrong here - I need to look into it.
But if you do specify the (by intention) optional ``clip`` parameter as ``None``, things should work, i.e. ``pix1 = fitz.Pixmap(pix0, 100, 100, None)``.

**Comment by JorjMcKie** [comment]
I will change the method in that sense with the coming version:
The clip parameter is mandatory but may be specified as None.
In so far, this is the solution rightaway.

**Comment by SummerXXXX** [comment]
thanks, it works now.
