### ISSUE TITLE
how to extract the  strikethrough text ?

### ISSUE THREAD

**Issue by gousiasultana** [pymupdf/PyMuPDF#1551]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Are there several options for how your request could be met?

**Additional context**

**Comment by JorjMcKie** [comment]
This already possible today!
Iterate through the age'sannotation, selecting type strikethrough. Then take the annotation's rectangle and extract the text within that rectangle. Done.
