### ISSUE TITLE
One page PDF with logo, Generating 108 images

### ISSUE THREAD

**Issue by sunov** [pymupdf/PyMuPDF#1555]
One page PDF with logo, Generating 108 images. Collected nearly 50 pdfs with generating images more than 50. The pdf contains single page, Due to scanner issue or embedded images, Getting 108 image blocks. Checked with new version 1.19.4, Getting same count.

**Comment by sunov** [comment]
@JorjMcKie Please help me, What is the best way to fix the issue

**Comment by JorjMcKie** [comment]
First of all: what is the **bug** of PyMuPDF here?
Second: I cannot help you without any reproducer - meaning code snippet and data.
You obviously should have opened a **_Discussions_** item, shouldn't you?

**Comment by sunov** [comment]
@Sorry, I missed that part. I will opened discussion. Thanks.
