### ISSUE TITLE
Annotation attributes do not display properly until unrelated manual edit in PDF viewer

### ISSUE THREAD

**Issue by matoles** [pymupdf/PyMuPDF#1587]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
In the file output `output.pdf` from the following script, most annotations do not display any fill color despite fill color being set on all annotations. However, if the user opens `output.pdf` in any pdf viewer[1], then manually moves any annotation one pixel in any direction, color displays correctly. 

The bug may require a certain number of pages and annotations per page. The file I am testing with has roughly 40 annotations on each of 5 out of 12 total pages.

[1] Tested on Adobe Acrobat and Foxit PDF Reader

## To Reproduce (mandatory)

```
import fitz


def review_annotations(
    pdf,
):
    with fitz.open(stream=pdf, filetype="pdf") as doc:
        for i, page in enumerate(doc):
            # Unrelated issue where iterating without `list()` causes segfault
            for j, annot in enumerate(list(page.annots())):
                annot.set_colors(
                    {
                        "fill": [1.0, 0.0, 0.0],
                    }
                )
                annot.set_opacity(0.5)
                annot.set_blendmode("dodge")
                annot.update()
            doc.reload_page(page)  # Makes no difference
        print("done")
        return doc.save("output.pdf")


pdf_path = (
    "path_to_file.pdf"
)

with open(pdf_path, "rb") as f:
    review_annotations(f.read())
```

## Expected behavior (optional)
All annotations are colored red when viewed in any PDF viewer

## Screenshots (optional)
[1] Shows portions of several annotations upon opening `output.pdf` in Foxit PDF Viewer. (Cropped for confidentiality)
<img width="337" alt="Screen Shot 2022-02-06 at 5 10 58 AM" src="https://user-images.githubusercontent.com/79861462/152682944-27713294-c3f4-45a3-9246-1cb3c27022e6.png">
[2] Shows the same region after:

1. Select all annotations
2. Tap `left arrow` to slightly move annotations

Note that there are multiple layers of overlapping annotations.
<img width="338" alt="Screen Shot 2022-02-06 at 5 11 10 AM" src="https://user-images.githubusercontent.com/79861462/152682950-89f00313-f635-4e16-b699-cfdee196deb3.png">

## Your configuration (mandatory)
```
print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] 
 darwin 
 
PyMuPDF 1.19.1: Python bindings for the MuPDF 1.19.0 library.
Version date: 2021-10-23 00:00:01.
Built for Python 3.8 on darwin (64-bit).
```
 - PyMuPDF version 1.19.1 installed from pip

**Comment by JorjMcKie** [comment]
I need a reproducer file.

**Comment by JorjMcKie** [comment]
Closed for lack of reproducible data.
