### ISSUE TITLE
Quad with fill color but no edge color is read as 4 lines

### ISSUE THREAD

**Issue by jn-chrn** [pymupdf/PyMuPDF#1591]
## Describe the bug 
When a `Quad` is drawn on a Shape with `color` set to `None` but `fill` set to any color (in `Shape.finish`), and the drawings is read, the result is 4 lines which are the contour of the `Quad`. 

Also, if both `color` and `fill` are set, reading the drawings returns 4 lines and a Quad.

## To Reproduce
The following script creates a Quad and a PDF Document, draws the Quad on the document, then read the drawings and analyses them. In the end, fitz returns that 4 lines are on the PDF Document.

```python
import fitz

quad = fitz.Quad(
    fitz.Point(20.0, 10.0),
    fitz.Point(30.0, 20.0),
    fitz.Point(10.0, 20.0),
    fitz.Point(20.0, 30.0),
)

# Write the PDF
out_pdf = fitz.open()
out_page = out_pdf.new_page(width=50, height=50)
shape = out_page.new_shape()

shape.draw_quad(quad)
shape.finish(color=None, fill=(0, 0, 0))  # No edge but the shape is filled
shape.commit()

# Read the square from the PDF
drawings = out_page.get_drawings()
assert len(drawings) == 1
items = drawings[0]["items"]

# The path consists of 4 line but should not
assert len(items) == 4
print(items)
# Output:
# [
#   ('l', Point(20.0, 10.0), Point(10.0, 20.0)),
#   ('l', Point(10.0, 20.0), Point(20.0, 30.0)),
#   ('l', Point(20.0, 30.0), Point(30.0, 20.0)),
#   ('l', Point(30.0, 20.0), Point(20.0, 10.0))
# ]
```

## Expected behavior (optional)
In the example script above, a Quad drawn should be read as Quad, not as lines. 

Also, if `color` is set to any color, only one Quad should be read in the end, not a Quad and 4 lines.

## Screenshots (optional)
The PDF which is the output of the script above:
![Screenshot from 2022-02-10 10-21-14](https://user-images.githubusercontent.com/98965709/153376684-6f29afb3-5b49-489a-af97-3cef1ed08f05.png)

## Your configuration (mandatory)

Result of the command:
```
3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] 
 linux 
 
PyMuPDF 1.19.5: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-02-01 00:00:01.
Built for Python 3.8 on linux (64-bit).
```

PyMuPDF is installed inside a conda environment with pip.

**Comment by JorjMcKie** [comment]
Thanks for your report anyway ...

**Comment by JorjMcKie** [comment]
If you are interested in the details, have a look at the code in C in [this file](https://github.com/pymupdf/PyMuPDF/blob/master/fitz/helper-devices.i).
MuPDF has a "trace" facility which produces an XML-like output of a page's painting activity, which uses the same data as my code. Try `mutool trace your.pdf > trace.xml`.

**Comment by jn-chrn** [comment]
Thanks for the quick answer, and the insights in the reading and drawing processes! This seems to be a complicated task for sure here.

I will take a look into the "trace", I am quite curious.

**Comment by JorjMcKie** [comment]
I am going to close this then.
