### ISSUE TITLE
Zoom into a pdf within lambda and having issues. 

### ISSUE THREAD

**Issue by meggievh** [pymupdf/PyMuPDF#1597]
Essentially the copy I create is exactly the same as the original copy. I really just want to at least zoom in such that the border margins would go away. 

   file_obj = event["Records"][0]
    bucketname = str(file_obj["s3"]["bucket"]["name"])
    filename = unquote_plus(str(file_obj["s3"]["object"]["key"]))
    
    doc = fitz.open()
    s3 = boto3.resource('s3')
    obj = s3.Object(bucketname, filename)
    fs = obj.get()['Body'].read()
    pdf=fitz.open("pdf", stream=BytesIO(fs))
     # open stream as PDF
    rect = pdf[0].rect
    sizeA4 = fitz.paper_size("A4")
    page = doc.new_page(width = sizeA4[0], height = sizeA4[1])
    page.show_pdf_page(rect, pdf, 0)
  
    new_bytes=doc.write()

    
    
  
    bucketname2='modified'
    s3.Bucket(bucketname2).put_object(Key=filename, Body=new_bytes)

**Comment by JorjMcKie** [comment]
Looks like this is more a question than an issue.
So I will transfer this to the `Discussions` tab.
