### ISSUE TITLE
Test failure (test_drawings1) with 1.19.5

### ISSUE THREAD

**Issue by swt2c** [pymupdf/PyMuPDF#1600]
When upgrading the Fedora package from 1.19.4 to 1.19.5, I observed the following test failure.  Is this a known issue?  This is on Fedora Rawhide with Python 3.10.2.

```
=================================== FAILURES ===================================
________________________________ test_drawings1 ________________________________

    def test_drawings1():
        symbols_text = open(symbols).read()  # expected result
        doc = fitz.open(filename)
        page = doc[0]
        paths = page.get_cdrawings()
        out = io.StringIO()  # pprint output goes here
        pprint(paths, stream=out)
>       assert symbols_text == out.getvalue()
E       assert "[{'closePath...dth': 1.0}]\n" == "[{'closePath...dth': 1.0}]\n"
E         Skipping 2093 identical leading characters in diff, use -v to show
E         + tems': [('qu',
E         +              ((50.0, 255.0), (75.0, 280.0), (75.0, 230.0), (100.0, 255.0)))],
E         - tems': [('l', (75.0, 230.0), (100.0, 255.0)),
E         -             ('l', (100.0, 255.0), (75.0, 280.0)),
E         -             ('l', (75.0, 280.0), (50.0, 255.0))],
E             'lineCap': (0, 0, 0),...
E         
E         ...Full output truncated (615 lines hidden), use '-vv' to show

tests/test_drawings.py:22: AssertionError
=========================== short test summary info ============================
FAILED tests/test_drawings.py::test_drawings1 - assert "[{'closePath...dth': ...
========================= 1 failed, 84 passed in 3.10s =========================
```

**Comment by JorjMcKie** [comment]
OOps - forgot to update some test files.

**Comment by swt2c** [comment]
Thanks!

**Comment by mjg** [comment]
Just came here after I stumbled over that "half patch" without the binaries ... Looks a bit weird in dist-git. The two pdfs (`circular.pdf` and `type3font.pdf`) don't seem to be used in the tests anywhere, so far; in particular they are unrelated to the test suite fix, aren't they?

**Comment by mjg** [comment]
> @mjg - you are right. I accidentally copied over test files intended for the next version of PyMuPDF.

Ah, OK, happens - even with a "git status line" in the terminal ;-)

**Comment by swt2c** [comment]
> Just came here after I stumbled over that "half patch" without the binaries ... Looks a bit weird in dist-git. The two pdfs (circular.pdf and type3font.pdf) don't seem to be used in the tests anywhere, so far; in particular they are unrelated to the test suite fix, aren't they?

Sorry @mjg , I have a habit of hand-editing patches and not documenting my changes.  :-)
