### ISSUE TITLE
page.get_links() not marked `PDF only` but it call `PDF only` function `page.annot_xref()`

### ISSUE THREAD

**Issue by luhuaei** [pymupdf/PyMuPDF#1605]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

```
  File "buffer.py", line 2003, in get_event_link
    for link in page.get_links():
  File "/nix/store/cng1r99by91dghccqb2kz77jh8gws88j-python3-3.9.10-env/lib/python3.9/site-packages/fitz/utils.py", line 964, in get_links
    linkxrefs = [x for x in page.annot_xrefs() if x[1] == PDF_ANNOT_LINK]
TypeError: 'NoneType' object is not iterable
```

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

- use pymupdf open epub document
- call page.get_links()

`test.py`
```
import fitz
import sys

document = fitz.open(sys.argv[1])

for page in document.pages():
    for link in page.get_links():
        print(">>", link)
```

[test epub resource](https://creativecommons.org/use-remix/made-with-cc/) or [click directly download](https://creativecommons.org/wp-content/uploads/2017/04/Made_with_Creative_Commons-ePub2.epub )

```
> python test.py ~/Downloads/Made_with_Creative_Commons-ePub2.epub 
Traceback (most recent call last):
  File "/home/xxxxx/test.py", line 7, in <module>
    for link in page.get_links():
  File "/nix/store/l1kv1mq9mh0s8lgydg9pdi75rf28qlmi-python3-3.9.10-env/lib/python3.9/site-packages/fitz/utils.py", line 964, in get_links
    linkxrefs = [x for x in page.annot_xrefs() if x[1] == PDF_ANNOT_LINK]
TypeError: 'NoneType' object is not iterable
```

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

It normal return page all links, but if it must dependence `PDF only` method, could marked this on document.

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

```
Python 3.9.10 (main, Jan 13 2022, 23:32:03) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import fitz
>>> print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.9.10 (main, Jan 13 2022, 23:32:03) 
[GCC 10.3.0] 
 linux 
 
PyMuPDF 1.19.4: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-01-01 00:00:01.
Built for Python 3.9 on linux (64-bit).

```

**Comment by JorjMcKie** [comment]
If you want to have something now, look here: https://github.com/pymupdf/PyMuPDF-wheels/tree/master/wheelhouse

**Comment by luhuaei** [comment]
> If you want to have something now, look here: https://github.com/pymupdf/PyMuPDF-wheels/tree/master/wheelhouse

Thanks. 

The pre-version wheel working well.

**Comment by JorjMcKie** [comment]
Thanks for the feedback ... and last not least for the well-prepared issue report.
