### ISSUE TITLE
scrub on the pdf document causes deprecation warning

### ISSUE THREAD

**Issue by jaristy** [pymupdf/PyMuPDF#1606]
HI Jorj,

When calling "scrub" on the pdf document, it calls "remove_hidden" in utils.py which in turn calls "page.deleteLink(link)". This fires a warning of "Deprecation: 'deleteLink' removed from class 'Page' after v1.19 - use 'delete_link'." which the user can't do anything about.

## Your configuration (mandatory)
PyMuPDF 1.19.5: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-02-01 00:00:01.
Built for Python 3.9 on darwin (64-bit).

Thanks!

**Comment by JorjMcKie** [comment]
Thanks for the report. Will be changed in next version.

**Comment by JorjMcKie** [comment]
Fixed with new version 1.19.6

**Comment by jaristy** [comment]
Awesome! Thanks for the super fast fix, JorjMcKie! Have a great day!
