### ISSUE TITLE
digital signature certification

### ISSUE THREAD

**Issue by hbh112233abc** [pymupdf/PyMuPDF#1609]
**Is your feature request related to a problem? Please describe.**
We want make some signature with certificate like Adobe.

**Describe the solution you'd like**
1. support use *.crt certificate 
2. support use *.pfx certificate with password
3. support multi sign handle
4. support sign append other signed PDF

**Describe alternatives you've considered**
JAVA IText can sign PDF

**Comment by JorjMcKie** [comment]
Thank you for your interest in PyMuPDF, and for your suggestion.
PDF signing actually already is on my list - somewhere I also documented the issues I am having with an implementation.
