### ISSUE TITLE
Cannot update Content stream with doc.update_stream

### ISSUE THREAD

**Issue by SirishaGorasa** [pymupdf/PyMuPDF#1611]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Update content stream erases everything.

## To Reproduce (mandatory)

- Take content stream of tagged PDF with tagged link i.e. link as marked content sequence in content stream with an MCID(Marked content identifier)
- Create a text file with the decoded content stream.
- Read a similar PDF which is tagged except for the link i.e. link not present in stream.
- update the stream of this PDF with the stream of previous PDF, along with the changes required in internal structure(object definitions).
``` python
import fitz

#Open the text file containing the Content Stream of tagged PDF

file_name=open("text-file.txt",'r')

file_read=file_name.read()

file_name.close()

#Open the untagged pdf of the same tagged version to which the above text file corresponds to

doc=fitz.open("./google_link.pdf")

# taken care of mapping proper xref objects
obj="""<<

  /K [ <<

        /Obj <<

  /A <<

  /S /URI

  /Type /Action

  /URI ([https://www.google.com)]()

  >>

  /BS <<

    /S /S

    /Type /Border

    /W 0

  >>

  /Border [ 0 0 0 ]

  /Rect [ 53.9978 642.966 137.874 653.526 ]

  /StructParent 3

  /Subtype /Link

  /Type /Annot

>>

        /Type /OBJR

      >> 3 ]

  /Pg 3 0 R

  /S /Link

>>"""

xref=doc.get_new_xref()

doc.update_object(xref,obj)

# 12 is the contents xref of PDF file
doc.update_stream(12,file_read,compress=True)

doc.save("updated_google_link.pdf",clean=True)
```
Content stream is completely empty in new file.

## Expected behavior (optional)
Updated content stream in the new PDF.

## Screenshots (optional)
Completely blank PDF.

## Your configuration (mandatory)
 - OS: Windows, 64 bit
 - Python: 3.8.3
- Name: PyMuPDF
- Version: 1.19.5
- Summary: PyMuPDF is a Python binding for the document renderer and toolkit MuPDF
- Home-page: https://github.com/pymupdf/PyMuPDF
- Author: Jorj McKie
- Author-email: jorj.x.mckie@outlook.de
- License: GNU AFFERO GPL 3.0

## Additional context (optional)
Trying to find if we can modify internal structure and corresponding object stream to tag element (link in this context)

**Comment by SirishaGorasa** [comment]
we aren't creating a new xref, we are updating the existing xref containing the object stream with new stream.

**Comment by SirishaGorasa** [comment]
I have tried creating a new xref and updating it with the new stream. Then, I have modified the internal structure to make use of the new stream to look for contents in similar fashion as mentioned below.
```text
 /Contents 45 0 R
```
Then I have saved the document into a new file but I don't the expected content stream after extracting and decoding the content stream.

**Comment by JorjMcKie** [comment]
we put this in `Discussions`.
