### ISSUE TITLE
Search for word does not run

### ISSUE THREAD

**Issue by mameIIas** [pymupdf/PyMuPDF#1617]
I'm trying just a simple example where a couple of words are being replaced, but I can't replace a speficic word because the program doesn't work (the words commented are the ones that broke the code) (I'm trying to find Viviana but I can't). But if I write any other word it does work, that code does run, but if I change text it does not.
What can i do?
```
import fitz

### READ IN PDF
doc = fitz.open("input.pdf")

for page in doc:
    ### SEARCH
    text = "viiana"
    #text = "En"
    #text = "fundamenta"
    text_instances = page.searchFor(text)

    ### HIGHLIGHT
    for inst in text_instances:
        highlight = page.addHighlightAnnot(inst)
        highlight.update()


### OUTPUT


doc.save("output.pdf", garbage=4, deflate=True, clean=True)
```
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/8152889/test.pdf)
Update:
I've changed the words to match the file I'm uploading which has the same problem that the previous one.
And file attached.

Update 2:
fitz                               0.0.1.dev2
Python 3.9

**Comment by mameIIas** [comment]
If tried more and more, and the thing is, if the word I'm searching (text var) is in the pdf, the code does not work.

**Comment by JorjMcKie** [comment]
As I wrote: a reproducing file is required!

**Comment by JorjMcKie** [comment]
Ah, ok - I see the file now.

**Comment by JorjMcKie** [comment]
Doing this:
```python
>>> doc=fitz.open("test.pdf")
>>> page=doc[0]
>>> for r in page.search_for("en"):
	a=page.add_highlight_annot(r)
	a.update()

	
>>> doc.save("y.pdf")
>>>
```
produces this:
![grafik](https://user-images.githubusercontent.com/8290722/155976571-b44f6c96-e1a6-4349-b6a7-cd674f3b77d5.png)

Looks as it should, doesn't it?

**Comment by mameIIas** [comment]
Yes, that's what I'm looking for, but you are using "search_for" which seems deprecated for me ( 'Page' object has no attribute 'search_for') is waiting for "searchFor".
Which version are you using?

**Comment by JorjMcKie** [comment]
No, I must ask you: which version do you use?
You forgot that (mandatory!) info in your bug report.

**Comment by mameIIas** [comment]
I put it at the end of the last update ( fitz 0.0.1.dev2)

**Comment by JorjMcKie** [comment]
Package "fitz" has nothing to do with PyMuPDF!

**Comment by mameIIas** [comment]
Okay, so I delete everything of fitz and install PyMuPDF, thought that they were the same, that fitz was PyMuPDF.
Sorry and thanks for the quick answers!

**Comment by JorjMcKie** [comment]
All that could have been found earlier, if you had used a complete bug report.
You must have seen error messages opening the PDF - which you did not report!

**Comment by mameIIas** [comment]
Then I need to install Mupdf, and then pymupdf right? This is not just a python module. All this came because in everything I've found on the internet seems that fitz is the package of Pymupdf
![image](https://user-images.githubusercontent.com/34312469/155978992-51392003-55bf-4d65-a4f9-b6f9eb1c3c30.png)

**Comment by JorjMcKie** [comment]
You also kept your operating system secret.
If it is Mac, Linux or Windows, then there exist wheels.
If true, you only need to do this:
```python
python -m pip install -U pip
python -m pip install pymupdf
```
No separate MuPDF installation required.

**Comment by mameIIas** [comment]
Unistalled fitz, installed pymu ( PyMuPDF 1.16.7) and upgrade pip and I keep getting the same error:
PD: I'm using anaconda
![image](https://user-images.githubusercontent.com/34312469/155981368-24a9b03d-0baa-4d89-b61f-7fc794e53134.png)

**Comment by JorjMcKie** [comment]
PyMuPDF is not in Anaconda. Use native pip as I wrote.

**Comment by mameIIas** [comment]
Yes, I used pip to install it on anaconda, that version is shown in the anaconda prompt.
