### ISSUE TITLE
Not able to search for a string

### ISSUE THREAD

**Issue by sagrawal-idrc** [pymupdf/PyMuPDF#1621]
## Describe the bug (mandatory)
`page.search_for` is not able to search for a particular string in a particular document (attached below).

[printmgr file.pdf](https://github.com/pymupdf/PyMuPDF/files/8176063/printmgr.file.pdf)

## To Reproduce (mandatory)

```python

doc_path = ""
doc = fitz.open(doc_path)
page = doc[0]

# Following works well
page.search_for("one-")
# Following works well
page.search_for("five")

# Following does not work
page.search_for("five-")
```

## Expected behavior (optional)
`five-` should be picked up from the line `for the one-, five- and 10-year periods ended` in the pdf. `one-` is picked up correctly.

## Your configuration (mandatory)

```
3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] 
 linux 
 
PyMuPDF 1.19.5: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-02-01 00:00:01.
Built for Python 3.8 on linux (64-bit).
```
PyMuPDF installed via pip

**Comment by JorjMcKie** [comment]
Wrong observation:
```python
>>> import fitz
>>> doc=fitz.open()
>>> page=doc.new_page()
>>> page.insert_text((100,100), "for the one-, five- and 10-year periods ended")
1
>>> page.insert_text((100,160), "for the one-, five- and 10-year periods ended")
1
>>> page.insert_text((100,200), "for the one-, five- and 10-year periods ended")
1
>>> doc.save("x.pdf")
>>> doc.close()
>>> doc=fitz.open("x.pdf")
>>> page=doc[0]
>>> page.search_for("five-")
[Rect(162.36997985839844, 88.17500305175781, 183.1489715576172, 103.28900146484375), Rect(162.36997985839844, 148.1750030517578, 183.1489715576172, 163.28900146484375), Rect(162.36997985839844, 188.1750030517578, 183.1489715576172, 203.28900146484375)]
>>> for r in page.search_for("five-"):
	page.draw_rect(r, color=(1,0,0), width=0.3)

	
Point(162.36997985839844, 88.17500305175781)
Point(162.36997985839844, 148.1750030517578)
Point(162.36997985839844, 188.1750030517578)
>>> doc.save("y.pdf")
>>> 
```
Gives this result:
![grafik](https://user-images.githubusercontent.com/8290722/156533584-cfc3c14f-70a0-4f82-82d8-6340ef66c55c.png)

**Comment by sagrawal-idrc** [comment]
Thanks for the quick review! Is it possible to review with the attached pdf too?

**Comment by JorjMcKie** [comment]
Searching has a standard flag setting, which includes hyphenation detection set to on.
Because of the peculiarity of (1) your PDF, and (2) of MuPDF's line detection heuristics, the PDF line containing this word is decomposed in the following MuPDF lines (because of the *justified* text causing those gaps) surrounded green:

![grafik](https://user-images.githubusercontent.com/8290722/156540638-7bb8e73d-49c1-4c6c-853d-55907b0d608e.png)

So because hyphenation detection means taking the word part **_except_** the continuation character "-", you get your irritating result.

Switching off hyphenation detection gives you what you need:
```python
>>> page.search_for("five-",flags=0)
[Rect(143.4812774658203, 489.5978088378906, 160.31117248535156, 499.1236267089844)]
```

**Comment by JorjMcKie** [comment]
BTW if your text would have happened to contain a **_non-breaking_** hyphen, ``chr(0x2011)`` (my first suspicion), your needle value would not have been found either!

**Comment by sagrawal-idrc** [comment]
Thank you very much for the great explanation! I should be able to devise a work-around for my use-case with this.
