### ISSUE TITLE
Getting Duplicate character in Words

### ISSUE THREAD

**Issue by dksfaldu** [pymupdf/PyMuPDF#1624]
I am getting duplicate entry of the words when read pdf using 
```

doc = fitz.open(pdf_file_path)
page = doc[0]
words = page.get_text("words")
```

For Word in PDF : STOCK
I am getting in word : SSSSTTTTOOOOCCCCKKKK
[d91ba75d-1646-456c-9f2f-f5d7e168bd63.pdf](https://github.com/pymupdf/PyMuPDF/files/8192725/d91ba75d-1646-456c-9f2f-f5d7e168bd63.pdf)

PyMuPDF Version : 1.19.4/1.19.5

**Comment by JorjMcKie** [comment]
Your PDF is coded like that.
Sorry.

**Comment by JorjMcKie** [comment]
Obviously the PDF creator tried to simulate BOLD with this.
