### ISSUE TITLE
Wrong text position with get_text

### ISSUE THREAD

**Issue by jrom99** [pymupdf/PyMuPDF#1628]
## Describe the bug (mandatory)
Pymupdf `.get_text("blocks")` indicates the text position below the actual text.

## To Reproduce (mandatory)
`layout-analyser.py` [teste.pdf](https://github.com/pymupdf/PyMuPDF/files/8200075/teste.pdf)
generates the given file with versions 1.19.5 and 1.19.6: [layout-testenew.pdf](https://github.com/pymupdf/PyMuPDF/files/8200074/layout-teste.pdf)
generates the given file with versions 1.19.1 through 1.19.4: [layout-teste.pdf](https://github.com/pymupdf/PyMuPDF/files/8200096/layout-teste.pdf)

## Expected behavior (optional)
Textbox position should be same as actual text.

## Your configuration (mandatory)
- Fedora 35 Workstation (behaviour also observed within WSL in Windows 10)
- pymupdf installed via pip

```
3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)] 
 linux 
 
PyMuPDF 1.19.4: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-01-01 00:00:01.
Built for Python 3.10 on linux (64-bit).
```

## Additional context (optional)
Test file was generated with Figma.

**Comment by JorjMcKie** [comment]
> Pymupdf .get_text("blocks") indicates the text position below the actual text.

what do you mean with this?

**Comment by jrom99** [comment]
The y-coordinates given by `.get_text("blocks")` (both y0 and y1) create a box below the actual text (instead of around it), which can be seen when using [layout-analyser.py](https://raw.githubusercontent.com/pymupdf/PyMuPDF-Utilities/master/text-extraction/layout-analyzer.py).

**Comment by JorjMcKie** [comment]
Issue confirmed!
This actually is an upstream bug (MuPDF) happening with Type 3 fonts. They have identified and fixed this issue. The fix will be rolled out with the next version (due in late autumn of the year).
I have already implemented some intermediate corrections, but obviously still missing cases. The general problem is how to detect that a text is flipped up-down. My circumvention only works if the font and / or the character defined in the font has a valid boundary box (which Type 3 fonts generally / often don't have).

So I am now detecting up-down flips only if the font bbox is valid. Else I am assuming no flip.
In your case, this removes the wrong conclusion that there is an up-down flip ... the effect of which you observed (it was not a vertical displacement).
With this adjustment, the result is fine:

![grafik](https://user-images.githubusercontent.com/8290722/157200382-1f91feb0-ede5-4bde-a2ce-d7a039bb0e09.png)

**Comment by JorjMcKie** [comment]
After some additional corrections of ascender / descender values, your example will look like this (made with `page.get_text("words")`).

![grafik](https://user-images.githubusercontent.com/8290722/157222141-854957d1-2425-4abf-a1a4-1cd25bdeb886.png)

**Comment by jrom99** [comment]
Thank you very much, do you think these corrections will be available in the next version of PyMuPDF?

**Comment by JorjMcKie** [comment]
Sure, but you can also have a pre-release wheel, just drop me a note and I'll let you know, when and where to download.

**Comment by JorjMcKie** [comment]
[Here](https://github.com/pymupdf/PyMuPDF-wheels/tree/master/wheelhouse) are pre-release wheels v1.19.7 for Linux that fix this problem.

**Comment by jrom99** [comment]
Thank you very much!
