### ISSUE TITLE
Grid param like in `fitz gettext` for `page.get_text()`

### ISSUE THREAD

**Issue by NicolasMICAUX** [pymupdf/PyMuPDF#1641]
**Is your feature request related to a problem? Please describe.**
I have an old PDF, where the lines position are pretty loosely recognised.  
I would like that lines which have "a vertical coordinate difference of no more than a value (in points) will be merged into the same output line".

**Describe alternatives you've considered**
In `fitz gettext` command line, there is a setting `grid` that does exactly that : `lines with a vertical coordinate difference of no more than this value (in points) will be merged into the same output line`. But I cannot find an equivalent for `page.get_text`. And I cannot find the code for `fitz gettext` to get inspiration from.

**Describe the solution you'd like**
A setting that does exactly the same than parameter `grid` of `fitz gettext`.

Thanks a lot to developers of this extremely useful and well made library.

**Comment by JorjMcKie** [comment]
Thank you for your appreciation of PyMuPDF - very flattering.

The source code for `-m fitz gettext` is part of `__main__.py` in the package directory.
You can also find it [here](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/text-extraction/fitzcli.py) as a separate script.

The hierarchy structure of the `TextPage` class - which is the input of all variants of `page.get_text()` - is created by the base library MuPDF, not by PyMuPDF.
PyMuPDF only exposes this given structure in various detail, depending on the text extraction variant.
MuPDF's logic behind the `TextPage` hierarchy is very sophisticated: it depends on font characteristics, relative fontsize of text pieces, distance between text spans, text extraction flags, etc.

I do not want to add complexity to all of this - given the fact that all geometric information is available to achieve whatever is desired.

What comes on top is internal consistency - between different parts of text processing. For example the text search function can be used to locate longer parts of text, potentially spanning multiple lines (sic!). This logic is part of the base library - not mine (PyMuPDF).
Anything that dissolves / extends / overrules MuPDF's line identification heuristics would thus have implications for multiple other parts.
A **_very_** significant effort!

So I am sorry to turn down this request.
I recommend you take (parts of) the mentioned script to make something up that meets your requirements.

**Comment by NicolasMICAUX** [comment]
Very clear explanation, thanks a lot.
I was expecting such an answer, no problem at all! Having the logic behind gettext will save me some time anyway.
Thx for the fast and detailed answer.

**Comment by JorjMcKie** [comment]
I thank you for your understanding!
If you run into problems for a solution based on `fitzcli.py` drop a note in the Discussions tab and I or others will try to help.
