### ISSUE TITLE
Insert font invalid！！！

### ISSUE THREAD

**Issue by heyhumor** [pymupdf/PyMuPDF#1644]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I use page.insert_font function, but the "Mincho" font is invalid.

## My code
 ```
doc = fitz.open(root)
for page in doc:
    if os.path.exists('fonts/mincho.ttc'):
        page.insert_font(fontname='Mincho', fontfile='fonts/mincho.ttc', encoding=0)
    annot = page.add_freetext_annot(fitz.Rect(100, 100, 115, 200), "123あいうえお", fontname='Mincho',
                                    fontsize=12, rotate=90, fill_color=(1, 0.75, 0.80), text_color=(0, 0, 0))

doc.ez_save(__file__.replace(".py", ".pdf"), pretty=True)
 ```

## Expected font (Manual)
![Mincho](https://user-images.githubusercontent.com/52818042/158572593-dcd88b51-b578-454b-846c-2813415b7c0d.png)

## Pymupdf Result
the Pymupdf has given me a wrong display status, we have discussed about this at #1248 , that's ok.
This time, I excepted font "Mincho" but "Gothic", like this:
![display](https://user-images.githubusercontent.com/52818042/158572736-424121c9-b383-4486-a98a-6cf2e5b50ebd.png)
![doubleclick](https://user-images.githubusercontent.com/52818042/158572880-9bdb911a-0f0e-4f97-a806-a489ca7db1c5.png)

## My configuration (mandatory)
I use Pdf-Xchange Viewer and font file following. Give me some advice, Thanks!
- Windows 10 64-bit
- Python 3.6.8 64-bit
- PyMuPDF version 1.18.17, pip installed
[msmincho.zip](https://github.com/pymupdf/PyMuPDF/files/8261377/msmincho.zip)

**Comment by JorjMcKie** [comment]
This is a misconception, please read the documentation!
1. Freetext annots only accept these fonts: `Default is “Helv”. Accepted alternatives are “Cour”, “TiRo”, “ZaDb” and “Symb”.` ... lower case allowed. Any CJK characters are automatically accepted / supported by MuPDF's internal logic. This logic cannot be influenced in any way.
2. Inserting some font on the page via `page.insert_font`  has nothing to do with annotations and no effect at all.
