### ISSUE TITLE
unable to install on ipad 

### ISSUE THREAD

**Issue by dummifiedme** [pymupdf/PyMuPDF#1651]
The install fails on ipad using a-shell. I don’t know if its supported on ipad. Nevertheless, I will post the error.

Tried to install via `pip install pymupdf`

![414E5BF2-5314-41D3-956E-665A5B1D914B](https://user-images.githubusercontent.com/68785729/159465607-b0831bb9-8192-413f-b899-63e67f0ee10e.png)
![E2BEF423-40D1-40D5-96B6-2C7E84847234](https://user-images.githubusercontent.com/68785729/159465640-bb14661f-bff1-46a8-be12-b9d532becd11.png)

ipadOS 15.3.1
ipad Air 3
Using a-shell (https://apps.apple.com/in/app/a-shell/id1473805438)

**Comment by JorjMcKie** [comment]
I do not know whether PyMuPDF is generally supported on that platform - you have to find out yourself.
In general, the following statement is true: If MuPDF can be installed as well as a Python >3.6, PyMuPDF can also be installed.
None of the Mac OSX wheels on PyPI is obviously suitable - as determined by `pip`.
In this situation, pip automatically tries to install from sources - which only has a chance to work if **_MuPDF is installed_** and its sources are also available to be detectable by `setup.py`.
Your error message says that MuPDF **_is not installed_**, so the installation is **_bound to fail._**
This is no bug - as explained on the home page and in the installation documentation.
For your platform, you must follow the installation procedure as explained there.
