### ISSUE TITLE
RadioButton changed into CheckBox

### ISSUE THREAD

**Issue by nvictor** [pymupdf/PyMuPDF#1652]
## Describe the bug (mandatory)

We are working with a PDF file (attached) which is freely available [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/697075/cremation-form-1-app-for-cremation-of-body.pdf).

Our goal is to populate the PDF form. We are having an issue with the `RadioButton` widgets. Below is an example using the `RadioButton` named `P3_Sex`.

When this widget is updated according to documentation, it becomes a `CheckBox`. The PDF does not show any update.

## To Reproduce (mandatory)

Code to reproduce the problem

```python
import fitz

print("Before update ----")
doc = fitz.open("form.pdf", filetype="pdf")
for p in doc.pages():
    for w in p.widgets():
        if w.field_name == "P3_Sex":
            print(w.field_type_string, w.button_states(), w.field_value)

print("During Update ----")
doc = fitz.open("form.pdf", filetype="pdf")
for p in doc.pages():
    for w in p.widgets():
        if w.field_name == "P3_Sex":
            print(w.field_type_string, w.button_states(), w.field_value)
        if w.field_name == "P3_Sex" and w.xref == 253:
            w.field_value = True  # Check "Male"
            w.update()
doc.save("out.pdf")

print("After update ----")
doc = fitz.open("out.pdf", filetype="pdf")
for p in doc.pages():
    for w in p.widgets():
        if w.field_name == "P3_Sex":
            print(w.field_type_string, w.button_states(), w.field_value)

```

## Expected behavior (optional)

Didn't expect `RadioButton` to become `CheckBox`. But that's what is happening with the resulting PDF file.

## Screenshots (optional)

```bash
$ python bug.py      
Before update ----
RadioButton {'normal': ['Male', 'Off'], 'down': ['Male', 'Off']} 
RadioButton {'normal': ['Female', 'Off'], 'down': ['Female', 'Off']} 
During Update ----
RadioButton {'normal': ['Male', 'Off'], 'down': ['Male', 'Off']} 
RadioButton {'normal': ['Off', 'Female'], 'down': None} Male
After update ----
CheckBox {'normal': ['Off', 'Male'], 'down': None} Male
RadioButton {'normal': ['Off', 'Female'], 'down': None} Male
```

## Your configuration (mandatory)

Configuration information below:

```python
>>> print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.9.5 (default, May  4 2021, 03:33:11) 
[Clang 12.0.0 (clang-1200.0.32.29)] 
 darwin 
 
PyMuPDF 1.19.6: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-03-03 00:00:01.
Built for Python 3.9 on darwin (64-bit).
```

Thank you! Really appreciate your work.

[form.pdf](https://github.com/pymupdf/PyMuPDF/files/8357884/form.pdf)

**Comment by JorjMcKie** [comment]
The two buttons belong to a radio button group. Handling this situation is not supported by PyMuPDF. It also does (currently) not detect this situation.
Updating a member of a RBG using PyMuPDF can therefore lead to undesired results as is your case.
I realize that I should probably refuse updates for radio buttons altogether. Will include this in the next version.

**Comment by JorjMcKie** [comment]
Just tried something out:
I believe your case can indeed be covered correctly. Pre-version wheels are in the making.
I'll let you know when they are ready for you to test.

**Comment by JorjMcKie** [comment]
Wheels are [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/master/wheelhouse).

**Comment by nvictor** [comment]
Hello, we tested on our end and everything looks okay. This wheel is fine for release if that's planned. Again, thank you so much for the project and working on this issue!

**Comment by JorjMcKie** [comment]
Thank you very much for the feedback!
Yes I am planning to publish soon.

**Comment by JorjMcKie** [comment]
Ah, and it really was a bug on my side, so relabelled the issue again.

**Comment by nvictor** [comment]
@JorjMcKie 

By the way, I wanted to mention this one. It's not a show stopper on our side but the radio buttons appear as checkboxes in the original document. Once set, they turn into radio buttons (i.e., they go from squares to circles). I thought I should mention it just in case you have an idea what is going on.

Thank you

**Comment by JorjMcKie** [comment]
> ... they turn into radio buttons ...

I know. This is inevitably done so by MuPDF. It is ultimately responsible for the appearance. Same sort of thing is true if using e.g. FreeText annotation updates: MuPDF only supports Base-14 fonts (non-bold, non-italic), so any original will look different if coming from another creator.

But every software in this field will do this to some extent. Not all of them support the same variety of border dashing or whatever other details ...

**Comment by nvictor** [comment]
Thanks for explaining 😊

**Comment by jnalviano** [comment]
Hi @JorjMcKie, we were also experiencing this bug on version 1.19.6. We were using the 1.19.7 wheel for a while, but now need to move away from using raw binaries. From what we can see, version 1.19.7 was never released and the fix to this bug never made it into versions 1.20 and 1.21. If possible, would you be able to direct us to the branch/commits for the fix you applied as part of the 1.19.7 wheel so that we can monkey patch? Thanks!

**Comment by JorjMcKie** [comment]
> Hi @JorjMcKie, we were also experiencing this bug on version 1.19.6. We were using the 1.19.7 wheel for a while, but now need to move away from using raw binaries. From what we can see, version 1.19.7 was never released and the fix to this bug never made it into versions 1.20 and 1.21. If possible, would you be able to direct us to the branch/commits for the fix you applied as part of the 1.19.7 wheel so that we can monkey patch? Thanks!

I understand. Let me check what these changes were. Once encountered, we will include them in the next patch v1.21.1.

**Comment by JorjMcKie** [comment]
Sorry for the tardy reply. Finally identified the bug. It will be fixed in next version early 2023.
I imagine you might have urgency by now: if you have a Windows version or Linux 3.10, I can provide a pre-version wheel ...

**Comment by dantard** [comment]
Hello, can you kindly tell me if the bug has been solved already? I'm on version 1.22.1 and still get checkboxes where there are radiobuttons in the original file even when I just save the file without any modifications.
Thanks in advance.

**Comment by JorjMcKie** [comment]
Hi,
That particular thing should actually no longer happen – I confirmed this a moment ago with your file.
What still does not work, is correctly setting / unsetting radio buttons (by changing the field value).
Doing this, requires actually dealing with the button group logic (setting one button on sets off all others automatically).
In addition, setting a radio button ON or OFF also requires modify its parent group.
We are planning to implement this in a future release.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Danilo ***@***.***>
Gesendet: Donnerstag, 20. April 2023 03:51
An: ***@***.***>
Cc: Jorj X. ***@***.***>; ***@***.***>
Betreff: Re: [pymupdf/PyMuPDF] RadioButton changed into CheckBox (Issue #1652)


Hello, can you kindly tell me if the bug has been solved already? I'm on version 1.22.1 and still get checkboxes where there are radiobuttons in the original file even when I just save the file without any modifications.
Thanks in advance.

**Comment by dantard** [comment]
Hi,
I see...what version are you using? Because just before posting I tried the
snippet in y 1.22.1 and the checkbox appeared.
Should I use another one?

Best,
 Danilo

**Comment by JorjMcKie** [comment]
I am using the most current one from PyPI, platform Windows and Linux.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Danilo ***@***.***>
Gesendet: Donnerstag, 20. April 2023 12:12
An: ***@***.***>
Cc: Jorj X. ***@***.***>; ***@***.***>
Betreff: Re: [pymupdf/PyMuPDF] RadioButton changed into CheckBox (Issue #1652)

Hi,
I see...what version are you using? Because just before posting I tried the
snippet in y 1.22.1 and the checkbox appeared.
Should I use another one?

Best,
Danilo
