### ISSUE TITLE
TextWriter fill_textbox align doen't work

### ISSUE THREAD

**Issue by BranDavidSebastian** [pymupdf/PyMuPDF#1683]
_**Please provide all mandatory information!**_
Hi, first, thank you for all the amazing work!

## Describe the bug (mandatory)
TextWriter fill_textbox align doen't work, it will align text center even if align parameter is 0 or 2. (tried fitz constants and have the same result).

#         helps to see the rectangle for debug
        col = fitz.utils.getColor("red")
        self.page.draw_rect(rect, color=col, fill=col, overlay=True)

        tw = fitz.TextWriter(self.page.rect, 1, self.color) # page rect, opacity, color

        # support for many fonts
        font = fitz.Font('helv')
        # used to populate the objet with te text and properties
        tw.fill_textbox(rect,
                        'Test',
                        fontsize=12,
                        font=font,
                        align=0
                        )

        rc = self.page.write_text(rect=rect,writers=tw, overlay=True)

       (self.page is document[0] in this case)

## To Reproduce (mandatory)
1. Create a TextWriter object.
2. Populate it with fill_textbox using align 0 (or 2)
3. Use write_text and save the output

## Expected behavior (optional)
Align text left.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/50082813/164475232-d3af8115-cf5d-4335-8183-acd0caa856f6.png)

## Your configuration (mandatory)
 - Ubuntu 20.04.3 LTS
 - Python 3.7.11
 - PyMuPDF 1.19.6 with pip

## Additional context (optional)
Align right will still align center.

**Comment by JorjMcKie** [comment]
Not a bug, see here the difference between `TextWriter.write_text()` and `Page.write_text()`:
```python
import fitz
doc=fitz.open()
page=doc.new_page()
r=fitz.Rect(100,100,300,200)
tw=fitz.TextWriter(page.rect)
tw.fill_textbox(r,"Test",align=0)
[]
page.draw_rect(r,fill=fitz.pdfcolor["red"])
Point(100.0, 100.0)
tw.write_text(page)
# make another page
page=doc.new_page()
page.draw_rect(r,fill=fitz.pdfcolor["red"])
Point(100.0, 100.0)
page.write_text(rect=r,writers=tw)
doc.ez_save("x.pdf")
```
Result:
[x.pdf](https://github.com/pymupdf/PyMuPDF/files/8537456/x.pdf)
