### ISSUE TITLE
Annot.set_rotation broken in v1.19

### ISSUE THREAD

**Issue by bjhowie** [pymupdf/PyMuPDF#1684]
Hi Jorj. Hope you're well!

I recently upgraded a project from v1.18.19 to v1.19.6 and the annot.set_rotation function no longer appears to operate as intended. See images below:

![image](https://user-images.githubusercontent.com/45848617/164479069-479f998b-057e-4e28-a36a-d0c20aea2940.png)
**Result with v1.18.19 (Expected Behaviour)** 

![image](https://user-images.githubusercontent.com/45848617/164479669-99ab4d92-c58f-4d31-b3a1-6cabbcca2a8c.png)
**Result with v1.19.6 (Unexpected Behaviour** 

I've also noticed that the exported annotations dont quite fill the Rect box and thus they are drawn smaller than expected. Any thoughts on what might cause this? 
![image](https://user-images.githubusercontent.com/45848617/164481697-34f4e22c-bfa9-4651-bf29-86a50d0fc3f5.png)

**System Details**
Running Windows 11 Home
3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] 
 win32 
 
PyMuPDF 1.19.6: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-03-03 00:00:01.
Built for Python 3.8 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
Please let me have a minimal reproducer.
Using the feature with a plain new page works as expected: here is a rect annot rotated by 30°.
![grafik](https://user-images.githubusercontent.com/8290722/164783832-b17d2481-a7f8-4c39-8f87-7c35e3d8488c.png)

**Comment by JorjMcKie** [comment]
Hi @bjhowie - as a reminder: cannot reproduce the issue without your reproducer ...

**Comment by bjhowie** [comment]
Hey Jorj,

Having a bit of trouble distilling the problem down to a simple example. It seems to work fine with just a single annotation, but breaks down with multiple annotations...

Think I've got something, but I just need to simplify it a bit more. I'll send through later today.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bjhowie** [comment]
Ok, I have a json file with annotation positions, rotations and sizes and a script that adds them to a blank PDF and rotates them.

I've included in the attached zip file two PDFs, one generated with v1.18.19 and one with v1.19.6. You'll see there's a difference in the annotation's apperance in each.

Reproducer script is below and also in the zip file. Let me know if you see the same effect.

```
import fitz
import json

inv_scale=(72/25.4)/500

with open("annotdata1.json") as f:
	cols = json.load(f)

doc = fitz.Document()

page  = doc.new_page(width=595*2, height=842)
derotmat = fitz.Matrix(inv_scale,inv_scale) * page.derotationMatrix

for cd in cols:
    intang = int(cd['angle'])

    rect = fitz.Rect(cd['x']-0.5*cd['B'],cd['y']-0.5*cd['D'],cd['x']+0.5*cd['B'],cd['y']+0.5*cd['D'])
    rect.transform(derotmat)
    
    
    print("Expected annot angle:", intang)
    annot = page.add_rect_annot(rect)
    annot.set_rotation(intang)
    annot.update()
    
    doc.xref_set_key(annot.xref, "Rotation", str(intang))

doc.save("fitz_annot_test.pdf")
```


[AnnotTest.zip](https://github.com/pymupdf/PyMuPDF/files/8562306/AnnotTest.zip)

**Comment by JorjMcKie** [comment]
Found the error cause:
There was a major change in version 1.19 of MuPDF. Without diving into technical abyss, bottom line is that the page must be finalized after an `annot.update()` before more annotations can be updated.
![grafik](https://user-images.githubusercontent.com/8290722/166099206-e74286ee-2210-4d6e-b9da-3965906f33b8.png)
This change is also documented.

**Comment by bjhowie** [comment]
Thanks.

So the reference to the page object is lost every time an annotation is updated? That's very awkward. Seems to have fixed the rotation issue though.

Any thoughts on the second issue? The annotations dont fill the Rect box supplied when they're created, so all annotations appear slightly smaller than they should (by approximately half the border thickness).

**Comment by JorjMcKie** [comment]
The update to the page object in v1.19 only becomes complete by leaving and then re-accessing it.
Don't know about the other topic yet.
Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JorjMcKie** [comment]
> So the reference to the page object is lost every time an annotation is updated? That's very awkward.

No, this is not the reason.
In v1.19, MuPDF has changed the logic that completes annot (and field) changes in the page definition. I cannot reach this logic from within PyMuPDF (yet), so the currently only way is to leave the page (which triggers MuPDF page finalization code) and then re-access it.

**Comment by bjhowie** [comment]
Thanks. Yes, sorry i understand. I just meant that the requirement to reload the page effectively means that the reference to the page is lost as i presume the original page object is destroyed upon reload.

Let me know if you're seeing the issue with the annotation sizes too, otherwise i'll look into it further.

**Comment by JorjMcKie** [comment]
> the original page object is destroyed upon reload

Correct. I however do not simply make a new page object from the same page number, but I also rebuild the previous relationships to dependent objects like annotations, fields and links.

As per the annot rect size I currently have too little time to pursue this. So if you could dig out what is different from before v1.19 would be great.

**Comment by bjhowie** [comment]
It looks like it's been an issue since at least v1.17.x, probably much longer. The annotation is offset in from the bounding rectangle by half of the border width, so for most applications it's negligibly small which is probably why it's never been picked up before. I have only picked it up recently as i've started using small annotations with thick borders.

Does MuPDF or PyMuPDF generate the annotation appearance streams?

Understand if you're too busy to look at right now, no rush. I might fork it off as a new issue though, so that it doesnt get lost in the git abyss.

**Comment by bjhowie** [comment]
Are you able to provide any clarity on why that would be the standard MuPDF behavior? Why would it want to create an annotation smaller than the supplied bounding Rect?

I could increase the size of the bounding Rect to force the appearance stream to generate correctly, but the problem then is that the annotation becomes too large as soon as its appearance gets regenerated by a 3rd party editor.

I guess i could manually update the /Rect entry in the annotation's dictionary after afterdating the annotation appearance with the slightly larger bounding Rect...... but seems dirty

**Comment by JorjMcKie** [comment]
I don't know MuPDF's reasoning. The relevant C code is this (file `/mupdf/source/pdf/pdf-appearance.c`):
```C
static void
pdf_write_square_appearance(fz_context *ctx, pdf_annot *annot, fz_buffer *buf, fz_rect *rect, pdf_obj **res)
{
	float x, y, w, h;
	float lw;
	int sc;
	int ic;

	pdf_write_opacity(ctx, annot, buf, res);
	lw = pdf_write_border_appearance(ctx, annot, buf);
	sc = pdf_write_stroke_color_appearance(ctx, annot, buf);
	ic = pdf_write_interior_fill_color_appearance(ctx, annot, buf);

	x = rect->x0 + lw;
	y = rect->y0 + lw;
	w = rect->x1 - x - lw;
	h = rect->y1 - y - lw;

	fz_append_printf(ctx, buf, "%g %g %g %g re\n", x, y, w, h);
	maybe_stroke_and_fill(ctx, buf, sc, ic);
}
```
So they are going away from each border by the linewidth `lw` value.

**Comment by bjhowie** [comment]
FYI the mupdf annotation appearance stream generation code has been updated to rectify this issue in w recent commit.

http://git.ghostscript.com/?p=mupdf.git;h=e9bcb39644fd20812f7f3633880a43dfe00b6ca2
