### ISSUE TITLE
Bug in fill_textbox

### ISSUE THREAD

**Issue by ArturKhuziakhmetov** [pymupdf/PyMuPDF#1686]
## Describe the bug (mandatory)
TextWriter.fiil_textbox() contains bug. If we try to continue in the middle of the line, following text is placed incorrectly. Just try code and suggested patch below.

## Code to reproduce:
import fitz
text = "PyMuPDF: the Python bindings for MuPDF " * 5
font = fitz.Font("helv")
doc = fitz.open()
page = doc.new_page()
tw = fitz.TextWriter(page.rect)
tw.fill_textbox(page.rect, text, font=font)
tw.fill_textbox(page.rect, text, font=font, pos=tw.last_point)
tw.write_text(page)
doc.ez_save("x.pdf")

## Working solution:
--- utils.py.orig    2022-04-24 15:43:52.423032400 +0300
+++ utils.py    2022-04-25 21:10:40.284622900 +0300
@@ -4363,6 +4363,7 @@
                 word_lengths = word_lengths[n:]
                 n = len(words)
                 line0 = None
+                width = rect.width - tolerance
             else:
                 n -= 1

## Configuration:
Windows 10 x64
Python 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)] on win32
PyMuPDF 1.19.6 (installed by: pip install pymupdf)

**Comment by JorjMcKie** [comment]
Excellent! Thanks a lot!
You found a bug and fixed it same time ...
