### ISSUE TITLE
Outline Color for redaction annotation

### ISSUE THREAD

**Issue by MalteHB** [pymupdf/PyMuPDF#1698]
**Is your feature request related to a problem? Please describe.**
The current version of `add_redact_annot()` does not support adding an outline color for the redaction area.

**Describe the solution you'd like**
It would be great to have the ability to specify if you want the outline border, and which color it should be. 

Anyhow - love the library and this feature would creately enhance the value I would get from it!

Thanks.

**Comment by JorjMcKie** [comment]
I understand. The standard color is **red**. Having no outline color at all wouldn't make sense: after all the outline rect is of transient existence and is meant to show which area will be emptied when applying the redactions.
Other than that, there is this intermediate solution available for you:
```python
doc=fitz.open("v110-changes.pdf")
green = fitz.pdfcolor["green"]  # desired color
page = doc[0]
a = page.add_redact_annot((100,100,300,200))  # add some redact annot
apn=a._getAP()  # get PDF command source for annot appearance
apn = apn.replace(b"1 0 0 RG", b"%g %g %g RG" % green)  # replace "red" color spec
a._setAP(apn)  # write back
doc.ez_save("x.pdf")
```
Looks like this:
![grafik](https://user-images.githubusercontent.com/8290722/165922784-268fbc1a-647e-44a0-a576-29a1fb523c42.png)

Remember **_not to update_** the annot after the above hack, because the standard would be re-established.

**Comment by MalteHB** [comment]
Thank you for your answer! 

And I see that when you open the PDF, the does clearly change, however, when you look at the properties of the redaction in e.g., Adobe Acrobat Reader DC, the property "Outline Color" is "No Color". See picture below: 
![image](https://user-images.githubusercontent.com/47593213/166131622-954a5f1e-a034-41a9-ac29-116aab1fb21c.png)

And if you change this property it also clearly changes the appearance of the redaction box:
No outline color: 
![image](https://user-images.githubusercontent.com/47593213/166131642-aada3d72-c145-41de-ab00-d4480dfc7562.png)

Outline color set to red: 
![image](https://user-images.githubusercontent.com/47593213/166131651-baffa076-b691-4feb-b41d-4de397d9381a.png)

**Comment by JorjMcKie** [comment]
That is true, but so what?

Adobe for your displayed window example only looks into the **_object definition(s)_** of the annot (like anyone else would).
And consequently finds not `/C` key (stroke color). It is at every annot creator's discretion to exclusively build the appearance in the contents stream(s) of an annotation in arbitrary ways and don't give a damn about the annot object definition.
That is what MuPDF does.
You could even display an image in that rectangle, and Adobe wouldn't know about it.

If you mix tools (here: MuPDF and Acrobat) to maintain the same annotations you **_will_** get inconsistencies, because all the tools do it a little differently.

**Comment by MalteHB** [comment]
This is not solely a case for Adobe. Also PDFTron and NitroPDF amongst other PDF tools has support for additional attributes to redaction annotations. 

I totally get the point of mixing tools and the inconsistencies within this, somehow fragile, endeavour. I just think that it would be a very cool addition to the PyMuPDF library, if it was able to _actually_ create redactions annotations, that are similar to the ones some of the most recognized PDF tools provide. And I am not a PDF format expert. It would take me many hours to even understand the basics of PDF - I do, however, like your work, as it gives us _mere mortals_ a chance to edit PDF documents with your awesome tool, and I would simply like to see the best of it. 

How much work, do you reckon, there would be in trying to streamline the metadata of a PyMuPDF/fitz redaction to an e.g., Adobe Acrobat Reader redaction?

**Comment by JorjMcKie** [comment]
> How much work, do you reckon, there would be in trying to streamline the metadata of a PyMuPDF/fitz redaction to an e.g., Adobe Acrobat Reader redaction?

First of all, thanks for the compliments! This is very encouraging.

Second however:
I have to say that "streamlining" with other tools is a double-edged sword - at least when it comes to areas, where there is no official standard yet.
This is the case especially for annotations. Not even between Adobe, Nitro, PDF-XChange you will find consistent behavior in this area. They all handle annotation details differently.
While I cannot speak for [Artifex](www.artifex.com), the new owner of PyMuPDF, I would say: there is no longer a central authority for how things should be made in PDF. The specs belong to the ISO standards today - and if you comply with them you are just fine.

For redactions specifically, the behavior of MuPDF is completely logical - and even goes beyond the sheer specification: you can e.g. select how overlapping images should be treated: ignore completely, remove completely or whiten overlapping parts.
There are however missing parts: line art (curves, rectangles, lines) overlapping a redaction annotation is completely ignored yet. If you look at the details what in contrast a complete support by the books would mean, you will quickly see why:
What is the outcome of a filled circle containing / intersecting a redact rectangle? Or a line? This quickly becomes incredibly complex ... for a more than questionable return on the effort.

Apart from the above: you will admit that all of the tools you mention are no completely fair players in this game:
If you save a PDF with them you will see a whole bunch of stuff becoming part of your file:
* XML metadata will suddenly exist with loads of information you did not ask for (references to the company, obvious marketing intent, and, and, and)
* Copyright and other restrictions if you used their freeware versions
* Compression logic introduced, which prevents access by free tools like pdfrw

Among all this, (Py-) MuPDF behaves like an honest player should behave:
* no XML metadata generation
* no metadata bloating
* minimum data required for the properties being asked for
* annotation will contain only what you have been asking for: except for a unique name, no owner, no dates, while offering the full range of still entering these info bits.
