### ISSUE TITLE
mupdf: invalid offset for previous xref section

### ISSUE THREAD

**Issue by gosforth** [pymupdf/PyMuPDF#1703]
I'm getting '`mupdf: invalid offset for previous xref section`' error for some PDFs. My code is:

```
 pdffile = pdf_file
 doc = fitz.open(pdffile)
 page = doc.load_page(0) #number of page
 width, height = fitz.paper_size("a4")
 width = width * 2
 page.set_cropbox(fitz.Rect(0, 0, width, 430))
 zoom_x = 2.0                       # horizontal zoom
 zomm_y = 2.0                      # vertical zoom
 mat = fitz.Matrix(zoom_x, zomm_y)  # zoom factor 2 in each dimension
 pix = page.get_pixmap(matrix = mat)
 output = path+"/img/"+img+".png"
 pix.save(output)
 doc.close()
```

What can be wrong?
I can send you file I have problem with but I need some secure channel - this is confidential.
Regards

**Comment by gosforth** [comment]
That was version 1.19.3 if I remember. After upgrade to last version, 1.19.6 I get error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 28, in <module>
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fitz\fitz.py", line 6653, in set_cropbox
    return self._set_pagebox("CropBox", rect)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fitz\fitz.py", line 6648, in _set_pagebox
    raise ValueError("rect not in mediabox")
ValueError: rect not in mediabox
```

**Comment by julian-smith-artifex-com** [comment]
According to the docs for `set_cropbox()`, the new rect must be completely contained in the Page.mediabox. See: https://pymupdf.readthedocs.io/en/latest/page.html?highlight=set_cropbox#Page.set_cropbox

Does the problem still occur if you constrain the new cropbox to fit the mediabox?

**Comment by JorjMcKie** [comment]
Let us attack your problem as originally announced - and not confuse it with some potential later bug:

> mupdf: invalid offset for previous xref section

We need reproducing data to understand what is going on. High probability: your PDFs are corrupt. Please me an example.

**Comment by gosforth** [comment]
Hi,

thank you very much for your respond and sorry for my delay. 
Yesterday I look at this code again and I see the problem is with the lines:

```
 width, height = fitz.paper_size("a4")
 width = width * 2
 page.set_cropbox(fitz.Rect(0, 0, width, 430))
```
'width' is larger than available area and cast error (logical). That was working in previous versions but not in 1.19.6.
This example [set_cropbox](https://pymupdf.readthedocs.io/en/latest/page.html?highlight=set_cropbox#Page.set_cropbox) is quite weird for me. If I just need to crop part of the page I simply execute code (nothing more... right?) :

```
 pdffile = pdf_file
 doc = fitz.open(pdffile)
 page = doc.load_page(0) #number of page
 page.set_cropbox(fitz.Rect(x, x, x, x))
 zoom_x = 2.0      
 zomm_y = 2.0                
 mat = fitz.Matrix(zoom_x, zomm_y)  # zoom factor 2 in each dimension
 pix = page.get_pixmap(matrix = mat)
 output = path+"/img/"+img+".png"
 pix.save(output)
 doc.close()
```

**Comment by JorjMcKie** [comment]
If all you want is restricting the pixmap to some part of the page ... then why don't you use the `clip` parameter of `get_pixmap()`???
Also consider using `dpi` instead of a zoom matrix if all you want is a higher solution. This is a lot handier.
You would end up with just one statement `pix = page.get_pixmap(dpi=xxx, clip=(x, x, x, x))`.
The method will automatically restrict `clip` to its intersection with the current page.
The relationship between zoom factor and dpi is `zoom = dpi / 72`.

Remains the ominous error message you used for creating the issue: what shall we do with it?

**Comment by gosforth** [comment]
Could you please propose me ready use code? All I need it to crop part of PDF. I need higher resolution because I use this PNG to OCR text.
Thanks for help

**Comment by JorjMcKie** [comment]
I am not sure what you want:
```python
pdffile = pdf_file
doc = fitz.open(pdffile)
page = doc.load_page(0) #number of page
# the following pixmap zoom by a factor of 2 (x and y)
# restricts the image to the page's subrectangle (x, x, x, x)
pix = page.get_pixmap(dpi=144, clip=(x, x, x, x))
output = path+"/img/"+img+".png"
pix.save(output)
doc.close()
```

**Comment by gosforth** [comment]
Thank you very much for your help!
