### ISSUE TITLE
mupdf: too many columns lead to an integer overflow (-1)

### ISSUE THREAD

**Issue by sunov** [pymupdf/PyMuPDF#1708]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
This issue happened in production environment. In production, We got blank image pdf, All pdf contains blank images. While reading the pdf page, The microservice is crashing. It is not coming inside the exception block also. 

## To Reproduce (mandatory)
import fitz
try:
    doc = fitz.Document(r"pdf path")
except Exception as ex:
    print(ex)
for page_num in range(doc.pageCount):
    page = doc.loadPage(page_num)
    try:
        page_dict = page.getText(output='dict')
    except Exception as ex:
        print(ex)
    finally:
        doc.close()

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Operating system = Windows 10
 - Python version = 3.7.3
 - PyMuPDF version = 1.16.7, pip install pymupdf==1.16.7

For example, the output of `[issue_pdf.pdf](https://github.com/pymupdf/PyMuPDF/files/8659454/issue_pdf.pdf)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
closed for lack of reproducing data
