### ISSUE TITLE
cannot identify bold text in page.getText('dict')

### ISSUE THREAD

**Issue by lakshmi1444** [pymupdf/PyMuPDF#1718]
_**Please provide all mandatory information!**_

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
Why do you think this is a bug?
And not a question (to be asked in _Dicussions_?)

Consult the documentation [here](https://pymupdf.readthedocs.io/en/latest/textpage.html#span-dictionary).

**Comment by lakshmi1444** [comment]
sorry, i was unaware how to change label
 I have seen the documentation  Walls & Structure  seems bold but flags is 20. Where can i get detailed documentation of flag
I am identifying  bold based on font type  but i see different font type CIDFont+F4, CIDFont+F1, CIDFont+F2

{'size': 10.357950210571289,
       'flags': 20,
       'font': 'CIDFont+F4',
       'color': 0,
       'ascender': 0.9169921875,
       'descender': -0.21923828125,
       'text': 'Walls & Structure ',
       'origin': (82.08000183105469, 220.67999267578125),
       'bbox': (82.08000183105469,
        211.1818389892578,
        179.60960388183594,
        222.9508514404297)}

**Comment by JorjMcKie** [comment]
As documented: 20 = 0b10100 = 2**4 (bold) + 2**2 (serifed)

**Comment by lakshmi1444** [comment]
Thanks

**Comment by JorjMcKie** [comment]
Please close the issue.
