### ISSUE TITLE
How to get binary text from page.get_text?

### ISSUE THREAD

**Issue by TheDeaX-Lab** [pymupdf/PyMuPDF#1727]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Are there several options for how your request could be met?

**Additional context**

**Comment by JorjMcKie** [comment]
Not understandable: What is "binary text"? Text is text and will be extracted ... as UTF-8.

**Comment by TheDeaX-Lab** [comment]
> 

I have a problem. In my pdf file instead of returning Russian characters to me, it gives \ufffd characters, okay, if I could get this data in at least some form, for example, binary data, with which I will then try to determine which encoding to apply to the text

**Comment by JorjMcKie** [comment]
`0xFFFD` is the standard replacement for unavailable / illegal unicodes returned by the used font.
This has been decided to be so by the PDF creator (for whatever reason).
The only solution is to OCR this page or the respective text lines.
Look for examples in the Utilities repo and please close this issue.

**Comment by TheDeaX-Lab** [comment]
Ok, thanks
