### ISSUE TITLE
Failures in Image Extraction 

### ISSUE THREAD

**Issue by MohieEldinMuhammad** [pymupdf/PyMuPDF#1728]
The image extraction of the library is very powerful, however in some cases the library extract the text from the image not the image itself:

Use Case 1: 
![IMG_20220525_114746](https://user-images.githubusercontent.com/89604782/170240525-a010bc30-4d6b-4ab6-b194-4a38b94be2a2.jpg)
When reading this page and extract all the blocks in it using 
``` 
doc = fitz.open(pdf_path)
page = doc[1]
page_blocks = page.get_text("dict")["blocks"]
#loop through the blocks and when the block type = 1 : get this image from the block **block["image"]**
```
I only got this image:
![IMG_20220525_121551](https://user-images.githubusercontent.com/89604782/170244846-98abd9ec-ad46-40b6-b30b-a612e88c3738.jpg)
The rest of it was extracted as text not image

Use Case 2:
![IMG_20220525_121701](https://user-images.githubusercontent.com/89604782/170244920-75835959-a3e9-48f5-8962-9abf651f19e9.jpg)
 Although the first image extracted perfectly, fitz failed in the second image and extracted the text only again as in the first use case

**Describe the solution you'd like** 
Is there a way to extract these types of images ?

Here are the 2 pdfs 
[taco.pdf](https://github.com/pymupdf/PyMuPDF/files/8770473/taco.pdf)

[mhs.pdf](https://github.com/pymupdf/PyMuPDF/files/8770479/mhs.pdf)

**Comment by JorjMcKie** [comment]
No bug - no room for enhancements:
What you are referring to are no images, but drawings. Thse can of course not be extracted by **_image_** extraction.
Please close the issue and refer to the documentation around `page.get_drawings()`.

**Comment by MohieEldinMuhammad** [comment]
Okay thanks for your help
