### ISSUE TITLE
extract the paragraph text

### ISSUE THREAD

**Issue by jonewei** [pymupdf/PyMuPDF#1735]
How to extract the paragraph text with keywords found by search_for function, that is, the paragraph text with keywords.

**Comment by JorjMcKie** [comment]
This is **_not_** an issue, but a question to be asked in "Discussions".

**Comment by JorjMcKie** [comment]
Your question could meand this: Once found some text via `page.search_for()`, how can I find a larger chunk of text (the haystack), of which this text (the needle) is a part?

E.g. try `page.get_text("blocks")` and see whether the returned search hit(s) are contained in any of the block rectangles.

**Comment by jonewei** [comment]
yes,page.get_text("blocks") only get the text of rect or block,but I want to find a larger chunk of text, such as the&nbsp;paragraph text of which this text (the needle) is a part. Thanks!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pymupdf/PyMuPDF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pymupdf/PyMuPDF] extract the paragraph text (Issue #1735)





 
Your question could meand this: Once found some text via page.search_for(), how can I find a larger chunk of text (the haystack), of which this text (the needle) is a part?
 
E.g. try page.get_text("blocks") and see whether the returned search hit(s) are contained in any of the block rectangles.

**Comment by JorjMcKie** [comment]
Please close this issue.
