### ISSUE TITLE
How to extract Tabular data ?

### ISSUE THREAD

**Issue by Nirav-Khanpara** [pymupdf/PyMuPDF#1740]
Hey,

I want to extract Tabular data from PDFs but I could not find this functionality in PyMuPDF.

Here is the screenshot of the Table:
![Screenshot from 2022-06-02 09-39-09](https://user-images.githubusercontent.com/97885050/171560619-9d7475d6-a0fa-44d7-927f-a8589a5e559c.png)

I am expecting result as below screenshot:
![Screenshot from 2022-06-02 11-16-33](https://user-images.githubusercontent.com/97885050/171561574-e82ff853-442e-4af4-a85f-36855fd052f6.png)

So, is there any way to do this using PyMuPDF ?

For reference, I shared the document on your personal email. [jorj.x.mckie@outlook.de](mailto:jorj.x.mckie@outlook.de)

Can you please do needful?

Thank you.

> Ubuntu 20.04.4 LTS
> Python 3.9.5
> PyMuPDF 1.19.6

**Comment by JorjMcKie** [comment]
Please close the issue.

**Comment by Nirav-Khanpara** [comment]
> This is not and will presumably never be PyMuPDF functionality. Please try to find other packages which may do this.

Thank You for responding.
