### ISSUE TITLE
PyMuPDF Installation issue on MacOS 12.2 

### ISSUE THREAD

**Issue by treeindev** [pymupdf/PyMuPDF#1746]
## Bug Description
The installation process of PyMuPDF in MacOS 12.2 ends up in failure. 

## Steps to Reproduce
Using Python3, run `pip install PyMuPDF`.

## Expected behavior
Installation in MacOS 12.2 should end successfully. 

## My local Configuration
 - Operating system: MacOS 12.2 using Apple M1 Pro.
 - Python version: 3
 - PyMuPDF version: No specified version, just using `pip install PyMuPDF`

The output log looks like this:
```
fitz/fitz_wrap.c:2755:10: fatal error: 'fitz.h' file not found
      #include <fitz.h>
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> PyMuPDF

note: This is an issue with the package mentioned above, not pip.
```

**Comment by JorjMcKie** [comment]
**_This is not a bug._**

M1 is not supported with a wheel, so you must install from sources - which you did not.
There also is a **looong** discussion [thread](https://github.com/pymupdf/PyMuPDF/discussions/875) you should consult.

**Comment by treeindev** [comment]
> **_This is not a bug._**
> 
> M1 is not supported with a wheel, so you must install from sources - which you did not. There also is a **looong** discussion [thread](https://github.com/pymupdf/PyMuPDF/discussions/875) you should consult.

I did not know about that thread, thank you for sharing @JorjMcKie.
Closing this issue.
