### ISSUE TITLE
Regex problem

### ISSUE THREAD

**Issue by Esatyilmaz0** [pymupdf/PyMuPDF#1748]
Hello, I'm converting pdf to text using fitz, but when I search with regex, it doesn't find any results. If I print the text, copy it and assign it to a variable, it can find it. What could cause this problem?

Code: https://dpaste.org/S0hts

**Comment by JorjMcKie** [comment]
There is a plethora of ways why things do not work as you think they should:

* text was not stored in natural reading sequence (stored sequence in the has nothing to do with the appearance),
* unexpected character spacing (i.e. deviating from the visual appearance),
* non-extractable characters, which are then represented as `\uFFFD`,
* simulated bold (doubling eeaacchh pseudo-bold character),
* you may be looking at stuff that is no regular text, but really is part of an image, or text is simulated by drawings, like a capital "D" may be drawn by a "|" followed by a left-open semi-circle,
* etc., and so on

But I don't understand:
You do assign text to a variable `"text"`. I thought this works?

You can play with the text extraction flags, e.g. switch on/off white space representation, dissolving ligatures, or using filler spaces, etc.

**Comment by JorjMcKie** [comment]
Please close this issue: it is a question and should land in "Discussions".
