### ISSUE TITLE
Hash mismatch

### ISSUE THREAD

**Issue by CodeYan01** [pymupdf/PyMuPDF#1749]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Can't install the module as I'm getting hash mismatches.

## To Reproduce (mandatory)
Run `pip install PyMuPDF`
I get this output
```
venv) project@raspberrypi:~/Documents/ABPLS $ pip install PyMuPDF
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyMuPDF
  Using cached PyMuPDF-1.19.6.tar.gz (2.3 MB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    PyMuPDF from https://files.pythonhosted.org/packages/9f/1d/032d24e0c774e67742395fda163a172c60e4d0f9875785d5199eb2956d5e/PyMuPDF-1.19.6.tar.gz#sha256=ef3d13e27f1585d776f6a2597f113aabd28d36b648b983a72850b21c5399ab08:
        Expected sha256 ef3d13e27f1585d776f6a2597f113aabd28d36b648b983a72850b21c5399ab08
             Got        1e1171a35b11d3f7d4447c632589f4b91a77a2f2c804e0a408cf04d27402d804
```

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Raspberry Pi OS Bullseye, 32-bit, 2022-04-04
 - Python 3.9.2
 - 1.19.6, using pip. 

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).
Output (minus the fitz):
```3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] 
 linux
```

## Additional context (optional)
Trying it with lower versions yields a different error, something about fitz.h missing.

**Comment by JorjMcKie** [comment]
Your platform is a corner case. It is not supported with a wheel, so you must install from sources.
You did not read the documentation, so here is a short synopsis:
1. Install MuPDF using your platform compiler. If you do not do this, you will receive those messages about missing `fitz.h`.
2. Install PyMuPDF - again with the appropriate compiler.

If you can switch to 64bit, you will find wheels and there is no more hassle like this.
