### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by shilpeegupta14** [pymupdf/PyMuPDF#1754]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Installation error in Jupyter notebook. 

## To Reproduce (mandatory)
!pip install PyMuPDF

## Expected behavior (optional)
To install the package successfully.

## Screenshots (optional)
<img width="844" alt="Screenshot 2022-06-16 at 10 17 50 AM" src="https://user-images.githubusercontent.com/78029920/173993432-0a7bf6c9-7556-4466-9972-2298966f573e.png">
.

## Your configuration (mandatory)
 - MAC OS X, version 12.4, M1 architecture
 - Python3.9

**Comment by JorjMcKie** [comment]
This is not an issue!
Mac OSX M1 architecture cannot be supported with a wheel, so you must install from sources.
Please refer to the documentation for what that means in detail.

Basically you need to install **MuPDF** first. Then install PyMuPDF from sources.
There also is a long Discussions [thread](https://github.com/pymupdf/PyMuPDF/discussions/875) about that same topic.
