### ISSUE TITLE
how to save as PDF/x-1a, other flavors

### ISSUE THREAD

**Issue by fredzannarbor** [pymupdf/PyMuPDF#1761]
I must be missing something obvious, but how do I tell pymupdf to save file in PDF/x-1a format, or, for that matter, in any arbitrary flavor of PDF?

**Comment by JorjMcKie** [comment]
You haven't missed that: this functionality is not (yet) present.
You may consider formulating an enhancement request.

**Comment by JorjMcKie** [comment]
Duplicate of #1762
