### ISSUE TITLE
save as PDF/x-1a, other flavors of PDF

### ISSUE THREAD

**Issue by fredzannarbor** [pymupdf/PyMuPDF#1762]
**Is your feature request related to a problem? Please describe.**

My immediate problem is that to create books that my printer will accept, I need to provide the file in PDF/x-1a format.

The broader problem is that there are literally dozens of versions and formats that a) can be created by tools like Acrobat and b) can, potentially, be required by consumer applications.

A good list from a 50,000 foot view that is portability & sustainability centric rather than vendor centric is at https://www.loc.gov/preservation/digital/formats/fdd/fdd000030.shtml.

**Describe the solution you'd like**
A parameter to the doc.save that allows me to specify the specific version and format of the file. Ideally, I would like the parameter to accept both string and int lookup values, as my experience has been that lengthy string parameters generate a lot of bug-fighting.
**Describe alternatives you've considered**
Workaround would be to open file in Acrobat and proceed from there with postscript and Distiller.  But this is impractical at scale unless I use Adobe's overly complex scripting language. I want everything in Python.

**Additional context**

<img width="623" alt="Screen Shot 2022-06-17 at 5 27 01 PM" src="https://user-images.githubusercontent.com/1165771/174403482-19d2b48e-dcb3-4c85-9f78-b207eac30f1d.png">
<img width="391" alt="Screen Shot 2022-06-17 at 5 26 10 PM" src="https://user-images.githubusercontent.com/1165771/174403485-c8cf62aa-8857-4058-b89d-d354b8019e0f.png">

**Comment by JorjMcKie** [comment]
Hi Julian,
took the liberty to forward the assignment to you. This probably is a MuPDF topic anyway and ultimately should land there.
