### ISSUE TITLE
Interactive(smartform) form PDF calculation not working in pymupdf

### ISSUE THREAD

**Issue by agsdineshDev** [pymupdf/PyMuPDF#1763]
## What we were trying to do?
We are trying to fill the interactive form values using the pymupdf widget field and generating a new pdf.

## Description of the bug 
We are trying to access the field in smart pdf form and fill in the value using the field.field_value. once the update is done, we expect the total field in the pdf to be updated. but that is not working as expected 

## Sample doc 
[widgettest12.pdf](https://github.com/pymupdf/PyMuPDF/files/8934886/widgettest12.pdf)

## To Reproduce, the sample code below
```
import fitz
doc = fitz.open('widgettest12.pdf')  # new or existing PDF
page = doc[0]
#print (page) 
#page_wid = page.widget()

for field in page.widgets():
    print (field.field_name)
    if (field.field_name == 'num2'):
        field.field_value = '201'
        field.update()

    if (field.field_name == 'num1'):
        field.field_value = '150'
        field.update()
    
    if (field.field_name == 'Text4'):
        field.update()
        #field.script_format
        #field.script_change

#page = doc.reload_page(page)   
doc.save("widgettest_result.pdf")
doc.close()
```

## Screenshots of actual result
![image](https://user-images.githubusercontent.com/63396565/174469209-32433b9d-220d-423f-ae14-c30512aad533.png)

## Expected behaviour 
![image](https://user-images.githubusercontent.com/63396565/174469356-100bdb40-0dc2-4a6a-ae13-1d15556f5b0e.png)

## configuration used
 - Operating system : Windows 10 
 - Python version: 3.10
 - PyMuPDF version:1.20.0

**Comment by JorjMcKie** [comment]
Managed to get this working now. Will be included in the next version.
