### ISSUE TITLE
Convert pdf to svg/text， got garbled text

### ISSUE THREAD

**Issue by chenrulongmaster** [pymupdf/PyMuPDF#1768]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Convert pdf to svg/text， got garbled text

## To Reproduce (mandatory)
page.get_svg_image(text_as_path=False)
reference the attachment pdf
[vaitrocanhan_.pdf](https://github.com/pymupdf/PyMuPDF/files/8953913/vaitrocanhan_.pdf)

## Expected behavior (optional)
Clear text

## Screenshots (optional)
svg file open in browser
![image](https://user-images.githubusercontent.com/38075088/174929268-50873523-4fb4-490d-8afc-90b096c88f9d.png)
svg file open in text editor
![image](https://user-images.githubusercontent.com/38075088/174929347-40b3bc28-b9d3-4d3a-9a4a-e6bf25ce069a.png)

## Your configuration (mandatory)
 - Operating system, windows
 - Python 3.6
 - PyMuPDF 1.18.13

PyMuPDF 1.18.13: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-05-05 06:32:22.
Built for Python 3.6 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
This has nothing to do with SVG. Normal text extraction also produces this output.
It is caused by the fonts used in the file:
```python
pprint(page.get_fonts())
[(3, 'ttf', 'Type0', 'ABCDEE+Times New Roman', 'F3', 'Identity-H'),
 (4, 'ttf', 'Type0', 'ABCDEE+Times New Roman,Bold', 'F4', 'Identity-H'),
 (5, 'n/a', 'Type1', 'Times-Roman', 'F5', 'WinAnsiEncoding'),
 (6, 'n/a', 'Type1', 'Times-Bold', 'F6', 'WinAnsiEncoding')]
```
The first two fonts have no `/ToUnicode` mapping, so back-translation from glyphs to unicodes is not possible.

**Comment by JorjMcKie** [comment]
The only solution is to use `page.get_svg_image(text_as_path=True)` ... or OCR the page.

**Comment by chenrulongmaster** [comment]
> The only solution is to use `page.get_svg_image(text_as_path=True)` ... or OCR the page.

Very appreciated for your reply...
