### ISSUE TITLE
AttributeError: 'Page' object has no attribute 'getText'

### ISSUE THREAD

**Issue by duksosleepy** [pymupdf/PyMuPDF#1772]
I open file with fitz and read page 0 of document, but it raise exception "AttributeError: 'Page' object has no attribute 'getText'". I need some help!!!

**Comment by JorjMcKie** [comment]
You left out literally **all** information mandatory for a bug report.
So you force me to guess:
* you are using v1.20.0
* you did not read the documentation, which tells you that starting with this version, camelCase names have been removed, and snake_cased names **must** be used instead.

**Comment by duksosleepy** [comment]
Oh my bad!Thank you so much

**Comment by tim-oritain** [comment]
> you did not read the documentation, which tells you that starting with this version, camelCase names have been removed.

@JorjMcKie I can't see this documented anywhere in the release notes. Is there some other documentation that I'm not aware of?

**Comment by JorjMcKie** [comment]
>  Is there some other documentation that I'm not aware of?

For example:
* Search for "gettext" in the documentation.
* You will see "Search Reults", which enumerates "Deprecated Names" among other things.
* Clicking on this opens a chapter called like that, which explains the background. This chapter also has a looong list (more than 210 items) of old names mapped to their snake-cased counterparts.

Searching for "deprecated" also will point you to the change log, where such changes are announced in version 1.18.14.
