### ISSUE TITLE
bug deploying fitz in the cloud using a docker container

### ISSUE THREAD

**Issue by GiuseppeMaioIC** [pymupdf/PyMuPDF#1782]
Hi, I am testing pymupdf in the cloud. 

I am trying to select a few pages from a pdf that are of interest to us and save them. 
To do that, I am using the insert_pdf() method.
This works perfectly locally, but when I deploy in the cloud on AWS using a docker container to built fitz, I get the below error. 

It seems like fitz.py in the source code is using a regex method, re.match, but it's only providing the pattern to match '^#page=([0-9]+)$' as an argument without the string on which it should perform the match, hence the error. 

Could you shed some light on this ? May this be due to different local and cloud version of fitz ? I did specify the latest version of pymupdf,pymupdf==1.20.0, in the requirements when building fitz in the cloud and still got the same error... 

Thanks in advance,
Giuseppe

[ERROR] TypeError: match() missing 1 required positional argument: 'string'
Traceback (most recent call last):
  File "/var/task/index.py", line 27, in lambda_handler
    pics_docs_bytes =  esg.get_most_relevant_pages(pdf_bytes)
  File "/var/task/transform_esg_pdfs.py", line 170, in get_most_relevant_pages
    new_doc.insert_pdf(doc, from_page=int(page.number), to_page=int(page.number))
  File "/opt/python/fitz/fitz.py", line 4527, in insert_pdf
    self._do_links(docsrc, from_page = from_page, to_page = to_page,
  File "/opt/python/fitz/utils.py", line 1519, in do_links
    links = page_src.get_links()  # get all its links
  File "/opt/python/fitz/utils.py", line 938, in get_links
    nl = getLinkDict(ln)
  File "/opt/python/fitz/utils.py", line 881, in getLinkDict
    nl = {"kind": ln.dest.kind, "xref": 0}
  File "/opt/python/fitz/fitz.py", line 8185, in dest
    return linkDest(self, uri)
  File "/opt/python/fitz/fitz.py", line 2617, in _init_
    m = re.match('^#page=([0-9]+)$')

**Comment by julian-smith-artifex-com** [comment]
This is fixed in PyMuPDF-1.20.1, released a few hours ago.

[Apologies, it was a bug introduced by me in the 1.20.0 release.]

BTW do you have a simple reproducer? It would be good to have a test that runs this bit of code.

**Comment by GiuseppeMaioIC** [comment]
Thanks, this solved the problem. 
Reproducer below. 

    doc = fitz.open(stream=pdf_bytes)
    page_indices_to_keep = [0,1,2,3]
    doc_pages_to_keep = [page for i, page in enumerate(doc) if i in page_indices_to_keep]
        
        for page in doc_pages_to_keep:
            new_doc = fitz.open()
            new_doc.insert_pdf(doc, from_page=int(page.number), to_page=int(page.number))
            doc_bytes = new_doc.tobytes()

**Comment by julian-smith-artifex-com** [comment]
Thanks for the reproducer, but it's incomplete - do you have the code that defines `pdf_bytes`?

**Comment by GiuseppeMaioIC** [comment]
Hi, that's just the pdf in bytes format !
url = https://assets.new.siemens.com/siemens/assets/api/uuid:4806da09-01c7-40b1-af91-99af4b726653/sustainability2021-en.pdf
r = requests.get(url)
r.content = pdf_bytes
doc = fitz.open(stream=pdf_bytes)
page_indices_to_keep = [0,1,2,3]
doc_pages_to_keep = [page for i, page in enumerate(doc) if i in page_indices_to_keep]
    
    for page in doc_pages_to_keep:
        new_doc = fitz.open()
        new_doc.insert_pdf(doc, from_page=int(page.number), to_page=int(page.number))
        doc_bytes = new_doc.tobytes()
