### ISSUE TITLE
Make Tesseract build optional

### ISSUE THREAD

**Issue by stefan6419846** [pymupdf/PyMuPDF#1788]
**Is your feature request related to a problem? Please describe.**

In https://github.com/pymupdf/PyMuPDF/blob/f79012c2ca4b9e21acc699ca8216039209bbe956/setup.py#L527 Tesseract and its Leptonica dependency will always be built, without any way to actually configure this (without building against a custom/system-wide MuPDF library build). I do not need Tesseract support, so building MuPDF/PyMuPDF with it does not make much sense for me.

**Describe the solution you'd like**

The Tesseract build can be controlled using an environment variable or a build parameter.

**Describe alternatives you've considered**

I am currently patching the corresponding line before actually running `bdist_wheel`, but this does not seem to be a clean solution.

**Comment by julian-smith-artifex-com** [comment]
PyMuPDF's `setup.py` is intended to create a consistent and tested build of PyMuPDF. I think it would be a mistake to be able to modify how it builds MuPDF.

* Allowing the creation of different builds will result in people using non-standard builds of PyMuPDF. These will not have been tested, and could have bugs that do not occur in normal builds, making reproducing and investigating bugs more difficult.
* It will require additional documentation, which runs the risk of confusing people.

It is already possible to control how PyMuPDF's MuPDF is built:

* Clone the mupdf repository or download the source tree, and build it manually using the available options as described in the MuPDF documentation.
* Then build PyMuPDF with PYMUPDF_SETUP_MUPDF_BUILD containing the path of the mupdf directory.

This gives much more control over the MuPDF build than we can ever provide via `setup.py`.

**Comment by stefan6419846** [comment]
Considering that `PYMUPDF_SETUP_MUPDF_BUILD` exists, we already allow non-standard builds in theory (at least as I see it). Before version 1.20, the steps had been decoupled as well, requiring a manual build of MuPDF beforehand (which is what `PYMUPDF_SETUP_MUPDF_BUILD` continues to support).

Nevertheless, I understand your objections against this level of customization. As for now, patching the offending parts is easy enough for me to apply and has not yet led to any issues - by using the `setup.py`-based approach, I avoid having to set the required remaining build parameters myself.
