### ISSUE TITLE
PyMuPDF not catching character `𠮟`

### ISSUE THREAD

**Issue by vinhtq115** [pymupdf/PyMuPDF#1793]
## Describe the bug (mandatory)
For some reason, PyMuPDF won't catch `𠮟` character.

## To Reproduce (mandatory)
Example files:
[Archive.zip](https://github.com/pymupdf/PyMuPDF/files/9027673/Archive.zip)

```
import fitz

# doc = fitz.Document('aozorabunko_43768.pdf')
# page = doc[127]

doc = fitz.Document('aozorabunko_04508.pdf')
page = doc[197]

results = page.get_text('text')

for c in results:
    if c == '𠮟':
        print('Found')
```
When running this script, it doesn't output anything (since PyMuPDF doesn't catch that character). This character is recognized when I open the file in Firefox.

## Your configuration (mandatory)
 - Ubuntu 20.04.4 LTS
 - Python 3.8.13
 - PyMuPDF version 1.20.1 (wheel)

**Comment by JorjMcKie** [comment]
Adobe Acrobat, XPDF-Reader and others don't find it either.
So it has nothing to do with (Py-) MuPDF and is no bug.

Note:
The fact that you can **_see_** that character in a viewer has **_nothing_** to do with whether you can extract it.
