### ISSUE TITLE
partial-ocr.ipynb

### ISSUE THREAD

**Issue by AmressamAI** [pymupdf/PyMuPDF#1799]
PyMuPDF 1.19.1: Python bindings for the MuPDF 1.19.0 library.
Version date: 2021-10-23 00:00:01.
Built for Python 3.6 on linux (64-bit).

```
doc = fitz.open("partial-ocr.pdf")
page = doc[0]
# make the TextPage object. It does all the OCR.
full_tp = page.get_textpage_ocr(flags=0, dpi=300, full=True)

# now look at what we have got
print(page.get_text(textpage=full_tp))
```

mupdf: Tesseract initialisation failed
mupdf: OCR initialisation failed
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?b2bb7f41-72ec-4b0f-a796-4d264ff7a037)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-58d8f14a8f9f> in <module>
      1 # make the TextPage object. It does all the OCR.
----> 2 full_tp = page.get_textpage_ocr(flags=0, dpi=300, full=True)
      3 
      4 # now look at what we have got
      5 print(page.get_text(textpage=full_tp))

~/python-envs/venv_pdf_extraction/lib/python3.6/site-packages/fitz/utils.py in get_textpage_ocr(page, flags, language, dpi, full)
    564         mat = Matrix(zoom, zoom)
    565         pix = page.get_pixmap(matrix=mat)
--> 566         ocr_pdf = Document("pdf", pix.pdfocr_tobytes(compress=False, language=language))
    567         ocr_page = ocr_pdf.load_page(0)
    568         unzoom = page.rect.width / ocr_page.rect.width

~/python-envs/venv_pdf_extraction/lib/python3.6/site-packages/fitz/fitz.py in pdfocr_tobytes(self, compress, language)
   6855 
   6856         bio = BytesIO()
-> 6857         self.pdfocr_save(bio, compress=compress, language=language)
   6858         return bio.getvalue()
   6859 

~/python-envs/venv_pdf_extraction/lib/python3.6/site-packages/fitz/fitz.py in pdfocr_save(self, filename, compress, language)
   6838         self, filename: AnyType, compress: int = 1, language: OptStr = None
...
-> 6840         return _fitz.Pixmap_pdfocr_save(self, filename, compress, language)
   6841 
   6842     def pdfocr_tobytes(self, compress=True, language="eng"):

RuntimeError: OCR initialisation failed

**Comment by JorjMcKie** [comment]
You did not provide a reproducer file.
This makes it impossible to research the problem.

**Comment by JorjMcKie** [comment]
Ah: you also use Python 3.6.
That is not supported. Nedd python 3.7+
