### ISSUE TITLE
The function not found in doc 

### ISSUE THREAD

**Issue by honghh2018** [pymupdf/PyMuPDF#1808]
Hi developer,
    Thanks to develop the great tool
    There are some question about the pdf writed, i follow you workflow

 doc = fitz.open("some.pdf")            # or a new PDF by fitz.open()
    doc.insertPage(n, text="some text")  # insert a new page in front of page n
    doc.save(...)                          # save what we did

but it show me the error doc not the insertPage, 
i install the pymupdf in latest version
no the function i follow you vignette can found in doc. insertPage, other than this, the other function had same issue
how can i solve this issue?
Best,
hanhuihong

**Comment by JorjMcKie** [comment]
@honghh2018 -

As a general rule when you get this type of message:
**Search the documentation for that missing method!** Doing this for `insertPage` would have shown you that it is a deprecated name for `insert_page`.
Do not **_immediately assume_** it is a bug.

After you have invested this research and discovered a reference to old names in the documentation, you could contribute a PR for documentation improvement.

As per your final question: please make a post in the "Discussions" tab - it is an entirely different topic.
