### ISSUE TITLE
Can't extract text from pdf

### ISSUE THREAD

**Issue by hemilparmar** [pymupdf/PyMuPDF#1838]
When i try to parse the pdf i am not able to get the same information from pdf
file  : 
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/9187034/test.pdf)

version is latest

Code : 

with fitz.open(filename) as doc:
    text = ""
    for page in doc:
        text += page.get_text()
        print(text)

**Comment by hemilparmar** [comment]
Please check the above details and provide some solution.
Thank You

**Comment by JorjMcKie** [comment]
The document uses a font that refuses text extraction. None of the ususal software products show other resuts than PyMuPDF.
You must use OCR to access the text.

**Comment by hemilparmar** [comment]
Okay, Thanks
