### ISSUE TITLE
#define FZ_ENABLE_SPOT_RENDERING - overprint simulation

### ISSUE THREAD

**Issue by Brampie66** [pymupdf/PyMuPDF#1870]
Hi,

This is more a question than a bug really.

Is overprint simulation suppose to work without modifications ?
print (fitz.TOOLS.fitz_config) gives me plotter-n:True (which is used for overprint rendering if I understand correctly) but in the mupdf source there is a config.h file with the following line:
/* #define FZ_ENABLE_SPOT_RENDERING */
suggesting it's off by default and needs to be enabled at compile time.

Is it simply suppose to work without any special parameter ? Most pdf viewers have this option "simulate overprint" which you can set on or off.

thx in advance

**Comment by JorjMcKie** [comment]
In PyMuPDF a modified config.h is used, which sets this to on.
So overprint capability is there.

**Comment by Brampie66** [comment]
Hi,

Ok, thanks, is there a way to select a simulation profile ?
With Qoppa I can select a specific CMYK profile (Afga Swop for example) as the simulation profile

thx again

**Comment by JorjMcKie** [comment]
No, there is no provision for that. Neither in MuPDF I believe.
If you want, submit a request to their issue manager https://bugs.ghostscript.com/enter_bug.cgi.

**Comment by Brampie66** [comment]
Hi,

Thanks, I think I could identify the paths that should be removed with get_drawings()
Is is possible to remove (of alter) such a drawing from the page, there is delete_link() etc. but no delete_drawing() ?

thx

**Comment by JorjMcKie** [comment]
No, this is not (and will presumably never be) supported.

**Comment by JorjMcKie** [comment]
With your consent, I would like to close this issue.

**Comment by Brampie66** [comment]
Ok, thanks for your help
