### ISSUE TITLE
fix ValueError: multiple image names found

### ISSUE THREAD

**Issue by PasaOpasen** [pymupdf/PyMuPDF#1885]
Hello again!

How to fix error `ValueError: multiple image names found`? I know it means that there are several images with same name like

```python
page.get_images()
Out[10]: 
[(35, 0, 3308, 4676, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode'),
 (39, 0, 1684, 210, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode'),
 (43, 0, 571, 237, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode'),
 (47, 0, 605, 252, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode'),
 (51, 28, 471, 176, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode'),
 (55, 0, 390, 114, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode')]
```

Saving doc with `garbage=4, clean=True, deflate=True` or `page.clean_contents()` don't help

If it's impossible, can I get information like `image rects` by using not `name` but `xref`?

**Comment by JorjMcKie** [comment]
yes you can use the image xref as parameter: `page.get_image_rects(xref)`.
Your above example can only occur if the images are invoked from within Form XObjects. Confirm by creating the image list like so `page.get_images(True)`. Each item then has the xref of the Form XObject which paints the image. If that entry is 0, the page itself does it.

**Comment by PasaOpasen** [comment]
Understood

Okay, the container label is the last value here (265, 266...)?
```
page.get_images(True)
Out[11]: 
[(35, 0, 3308, 4676, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode', 265),
 (39, 0, 1684, 210, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode', 266),
 (43, 0, 571, 237, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode', 267),
 (47, 0, 605, 252, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode', 268),
 (51, 28, 471, 176, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode', 269),
 (55, 0, 390, 114, 1, 'DeviceGray', '', 'Im1', 'CCITTFaxDecode', 270)]
```
 And the pairs name-container are always unique?

**Comment by JorjMcKie** [comment]
> And the pairs name-container are always unique?

yes, they are.
