### ISSUE TITLE
Not related content become invisible after redaction applied  

### ISSUE THREAD

**Issue by thaidv96** [pymupdf/PyMuPDF#1886]
_**Please provide all mandatory information!**_

## Describe the bug 
I want to use PyMuPDF to hide some sensitive contents from pdf. But after applying redactions on the rectangle contains sensitive information, other parts of the pdf file become invisible.  
![image](https://user-images.githubusercontent.com/36886027/185773321-610b2ab6-0b3c-461b-8914-686292bf21be.png)

## To Reproduce 
The source code for this bug as bellow:
```python3
import fitz
pdf_fn = 'resume.pdf'
sensitive_content = '0394389966'

doc = fitz.open(pdf_fn)
page = doc.load_page(0)
rects = page.search_for(sensitive_content)
for rect in rects:
    page.add_redact_annot(rect, fill=(0,1,0))

page.apply_redactions(images=2)
doc.save("resume-redacted.pdf",garbage=3, deflate=True)
```
You can download the pdf in the example with this url: [resume.pdf](https://drive.google.com/file/d/174dAbLoUOiRdtHf9NzkTVl8lhKH3zCh1/view?usp=sharing)

## Your configuration
 - Operating system: Ubuntu 20.04
 - Python version 3.9.1
 - PyMuPDF version 1.20.2,  installation via pypi

```
3.9.1 (default, Dec 11 2020, 14:32:07) 
[GCC 7.3.0] 
 linux 
 
PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
Version date: 2022-08-13 00:00:01.
Built for Python 3.9 on linux (64-bit).
```

**Comment by JorjMcKie** [comment]
Interesting problem!
The page contains 39 (!!!) full page images. Your way of applying redactions (modify overlapping images) therefore requires that (at least) 39 images must be modified.
And here some error occurs within MuPDF - not PyMuPDF.
I did not understand their purpose. Letting apply-redactions **_remove all_** overlapping images or **_not touching_** any images also produces a wrong results.
So I am afraid I cannot help you here, sorry.
I recommend you submit a bug report to MuPDF [here](https://bugs.ghostscript.com/enter_bug.cgi). If you want to do that please drop me a note on my e-mail and I will send you a ZIP file that you can attach to your report.

**Comment by thaidv96** [comment]
Thank you @JorjMcKie, I've sent you an email to your Outlook.
