### ISSUE TITLE
How to insert registered trademark symbol as superscript into text widget ?

### ISSUE THREAD

**Issue by hoaile-novobi** [pymupdf/PyMuPDF#1887]
I have tried many ways to insert the registered trademark symbol into a form text widget, but the text after rendering is not as superscript.
I hardcode the symbol string as a superscript like this "Jeffery T Walter CFP4®", the string is good but when render in pdf it not show as superscript
I have been stuck on this issue for many days and can not find any solution. I hope you help to determine what the problem is and how to do that. Thanks

Here is my code sample: 

```
for field in page.widgets():
    if (field.field_name == 'name_block'):
        field.field_value = 'Jeffery T Walter CFP4®'
        field.update()
```

![image](https://user-images.githubusercontent.com/104294815/185864822-412bad3f-c8fe-4fd1-a74b-78f16bc1c7d7.png)

**Comment by JorjMcKie** [comment]
This must be supported by MuPDF, before PyMuPDF can make use of it.
So you should submit this feature request to MuPDF. I suppose their issue tracker https://bugs.ghostscript.com/enter_bug.cgi can be used for this.
