### ISSUE TITLE
Get inexplicable text and bbox info when using function page.get_text('words')

### ISSUE THREAD

**Issue by sunyifan2017** [pymupdf/PyMuPDF#1890]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When using page.get_text('words'), I got inexplicable text info especially the bounding box the span.

## To Reproduce (mandatory)
When I use page.get_text('words'), the result as:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/30461425/185890756-3e048a59-c999-41ca-8b77-71c9ccdf57b0.png">
Obviously, the bounding boxes are weird. And I checked the character information under the text bbox, key 'c' of char is '\xa0' or '-'.

## Expected behavior (optional)
The optimal result of text bounding box should be tightly enclosed of text.

## Your configuration (mandatory)
 - My Operating system, Mac M1
 - python 3.9
 - PyMuPDF 1.20
![image](https://user-images.githubusercontent.com/30461425/185892749-4cb40c12-8121-426b-bbd2-8597e69939c4.png)

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
The bug report is incomplete. Please share a reproducing file.

**Comment by JorjMcKie** [comment]
BTW you can influence all `get_text()` behaviors using certain flag bits. In your case (again: no example file provided!) you could set off `fitz.TEXT_PRESERVE_WHITESPACE` which translates white space to spaces.

**Comment by sunyifan2017** [comment]
Sorry about that. @JorjMcKie 

## To Reproduce
```python
import fitz
import cv2 
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# load pdf
pdf_path = './ex.pdf'
doc = fitz.open(pdf_path)
page = doc.load_page(0)
words = words = page.get_text('words')

# get bbox
bboxes = []
for word in words:
    bbox = word[:4]
    bboxes.append(bbox)

# visualize the result
pix = page.get_pixmap(annots=False)
img = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
for bbox in bboxes:
    bbox = [round(item) for item in bbox]
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
    cv2.rectangle(img, (bbox[0], bbox[1]), (bbox[2], bbox[3]), (0,0,255), 2)
plt.figure(figsize=(8, 8))
plt.imshow(img)
plt.show()
```

1. The test pdf can be downloaded here, link: https://pan.baidu.com/s/1ureuse02dIwfQgr32pUE0Q password: lcg0

2. I have tried flag of `fitz.TEXT_PRESERVE_WHITESPACE `, the result does not change.

**Comment by sunyifan2017** [comment]
Sorry about that.

## To Reproduce
```python
import fitz
import cv2 
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# load pdf
pdf_path = './ex.pdf'
doc = fitz.open(pdf_path)
page = doc.load_page(0)
words = page.get_text('words')

# get bbox
bboxes = []
for word in words:
    bbox = word[:4]
    bboxes.append(bbox)

# visualize the result
pix = page.get_pixmap(annots=False)
img = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
for bbox in bboxes:
    bbox = [round(item) for item in bbox]
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
    cv2.rectangle(img, (bbox[0], bbox[1]), (bbox[2], bbox[3]), (0,0,255), 2)
plt.figure(figsize=(8, 8))
plt.imshow(img)
plt.show()
```

1. The test pdf can be downloaded here, link: https://pan.baidu.com/s/1ureuse02dIwfQgr32pUE0Q password: lcg0

2. I have tried flag of `fitz.TEXT_PRESERVE_WHITESPACE `, the result does not change.

**Comment by JorjMcKie** [comment]
I cannot read Chinese, so I don't know what I am looking at on the download page.

**Comment by JorjMcKie** [comment]
> I have tried flag of fitz.TEXT_PRESERVE_WHITESPACE , the result does not change.

How did you use it: `flags=fitz.TEXTFLAGS_TEXT & ^fitz.TEXT_PRESERVE_WHITESPACE`?

**Comment by sunyifan2017** [comment]
Sorry, Here is the test PDF -> [ex.pdf](https://github.com/pymupdf/PyMuPDF/files/9393955/ex.pdf)

I used the flag as follow:

```python
page = doc.load_page(0) 
words = page.get_text('words',flags = fitz.TEXT_PRESERVE_WHITESPACE)
```

**Comment by JorjMcKie** [comment]
The file contains Type 3 fonts, which seem to have issues - but only for non-Chinese text.
This causes my logic that recomputes the character bbox (whenever the font ascender and descender do not add up to 1) to make the wrong decisions.
Please use this instruction to prevent that algorithm from activation before you do extractions: `fitz.TOOLS.unset_quad_corrections(True)`. Then result is correct.
