### ISSUE TITLE
Width value is changed automatically on some PDF pages (overlay=True)

### ISSUE THREAD

**Issue by PWu-gh** [pymupdf/PyMuPDF#1907]
## Describe the bug (mandatory)
Issue : 
When the overlay is True, it doesnt work for width = 1(on some pages, but on others it works fine) 
cf: page1 and page2 (pages are drawn with the same code)
When the overlay is False, it works
My problem, is that I want to have overlay=True since on some documents, some image may go above the drawing

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.
Original file : [origin.pdf](https://github.com/pymupdf/PyMuPDF/files/9471210/origin.pdf)

```python
    
    import fitz  #pymupdf fitz
    pdf = "origin.pdf"
    fpdf = fitz.open(pdf)


    """
        Issue : 
        when the overlay is True, it doesnt work for width = 1 (on some pages, but on others it works fine) cf: p1 and p2
        when the overlay is False, it works
    """

    for npage in range(5):
        page = fpdf[npage]

        # Overlay True
        """
            Top left       =>       overlay True and width = 1
            Problematic:  width changes automatically to approx 10 (on some pages)
        """
        page.draw_rect((10, 10, 200, 200),color=(1,0.5, 0.5), width = 1, overlay=True)


        """
            bottom left    =>       overlay True and width = 2 (different than 1)
            correct : when I change the width for something above 1, it works
        """
        page.draw_rect((10, 300, 200, 500),color=(0.2, 0.8, 0.2), width = 2, overlay=True)


        # overlay False
        """
            top right      =>       overlay False and width = 1
            correct : when I change the width for something above 1, it works
        """
        page.draw_rect((300, 10, 500, 200),color=(0.2, 0.8, 0.2), width = 1, overlay=False)


        """
            bottom right   =>       overlay False and width != 1
            correct : when I keep the overlay to False, it works fine
        """
        page.draw_rect((300, 300, 500, 500),color=(0.2, 0.8, 0.2), width = 5, overlay=False)

    fpdf.save("out_pdf.pdf")

```

## Expected behavior (optional)
What I expect is PyMuPDF (Fitz) drawing shapes in width 1, when overlay is True.
It does the same with other drawings, like draw_line.

## Screenshots (optional)

Here it should be width = 1
![image](https://user-images.githubusercontent.com/56656631/187951012-cd137325-6ebb-4539-89e2-7f67e413b239.png)

Here on an other page, it works
![image](https://user-images.githubusercontent.com/56656631/187951204-27af3f36-3212-4c94-80c7-abffacd13765.png)

## Your configuration (mandatory)
The output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` 

3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] 
 win32 

PyMuPDF 1.19.6: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-03-03 00:00:01.
Built for Python 3.9 on win32 (64-bit).

## Output file
[out_pdf.pdf](https://github.com/pymupdf/PyMuPDF/files/9471215/out_pdf.pdf)

**Comment by JorjMcKie** [comment]
The weird behavior disappears if you execute `page.clean_contents()` rigth after loading the page - before inserting / drawing anything.
This is one of the cases discussed [here](https://pymupdf.readthedocs.io/en/latest/recipes-common-issues-and-their-solutions.html#misplaced-item-insertions-on-pdf-pages) in the documentation.

**Comment by JorjMcKie** [comment]
BTW:
This is a very well-prepared issue - chapeau!

**Comment by PWu-gh** [comment]
Thank you for replying so fast! 
Glad you apreciated the post!
I just tried, it works great 👍
