### ISSUE TITLE
Segmentation fault when applying the redacted annotation for this document

### ISSUE THREAD

**Issue by mirko0x5f** [pymupdf/PyMuPDF#1908]
Thanks for the great work with this library.

## Describe the bug (mandatory)
When trying to apply the redacted annotations to the document attached the C code exits with segmentation fault. This seems very similar to what was happening in #1824. The issue seems to happen in this [call](https://github.com/pymupdf/PyMuPDF/blob/master/fitz/utils.py#L3999).

## To Reproduce (mandatory)
```
import fitz
doc=fitz.open("input.pdf")
page=doc[0]
page.add_redact_annot(fitz.Rect(10,10,50,50))
page.apply_redactions()
```
[input.pdf](https://github.com/pymupdf/PyMuPDF/files/9478426/input.pdf)

## Expected behavior (optional)
That the pdf gets correctly redacted

## Your configuration (mandatory)
 - MacOS Monteray 12.5
 - python 3.9.13
 - PyMuPDF version 1.20.2
 - mupdf: stable 1.20.3 (bottled), HEAD

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).
```
In [5]: print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) 
[Clang 13.0.1 ] 
 darwin 
 
PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
Version date: 2022-08-13 00:00:01.
Built for Python 3.9 on darwin (64-bit).
```

**Comment by JorjMcKie** [comment]
Duplicate of #1868.
Will be resolved in next version.

**Comment by mirko0x5f** [comment]
Thanks for the fast response. Do you know when the next version will be released?

**Comment by mirko0x5f** [comment]
Thank for the fast response. Did not see that issue.

**Comment by JorjMcKie** [comment]
The release schedule is up to Artifex' MuPDF team. Looking back it seems a time frame of October, maybe November this year is probable.

**Comment by mirko0x5f** [comment]
If you have time could you explain to me if it would be possible to install the current main version of MuPDF (which I was reading in the issue you linked works) with the current pyMuPDF code?

**Comment by JorjMcKie** [comment]
MuPDF's mirror on Github must be taken instead of the normal download one.
Unfortunate you are using Mac, otherwise I could have given you a preliminary wheel for Windows or Linux.

**Comment by mirko0x5f** [comment]
Linux would work. I'll just spin up an ec2 instance. Would be super helpful :)

**Comment by JorjMcKie** [comment]
Linux Py 3.10 is the only one I have: 
This wheel is currently 31MB in size. Do you have an e-mail, which I can use?

**Comment by mirko0x5f** [comment]
Sure, thanks again. Email: mirko@super.ai

**Comment by mirko0x5f** [comment]
Hey @JorjMcKie sorry for bothering again, but I did not get the email. Just wondering if there's something wrong on my end

**Comment by JorjMcKie** [comment]
@mirko0x5f no problem, try this one - at your own risk of course.
[PyMuPDF-1.20.4-cp310-cp310-linux_x86_64.zip](https://github.com/pymupdf/PyMuPDF/files/9492038/PyMuPDF-1.20.4-cp310-cp310-linux_x86_64.zip)
In the meantime I was able to reduce the size again. It now is a little small in size, so pls use with care.
