### ISSUE TITLE
getText Function is not able to decode the text from the PDF

### ISSUE THREAD

**Issue by catchmeteja** [pymupdf/PyMuPDF#1912]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
While Calling getText function on the pdf attached, I am seeing that the function is not able to decode the text and I see a bunch of unreadable characters like the following 
���
����
���
���
���
���
�������������������
����
������
�����
������
����������

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.
    doc = fitz.open(pdf_filepath)
    for page_num, page in enumerate(doc):
        page_orientation = 'landscape' if page.rotation == 90 else 'portrait'
        page_text = page.getText()
        page_blocks = page.getText('blocks')
[D014_L00000_D03_C202_V401_F020_VX.pdf](https://github.com/pymupdf/PyMuPDF/files/9537058/D014_L00000_D03_C202_V401_F020_VX.pdf)

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

When the pdf is opened in Adobe reader, the text can be copied from the PDF and also can be pasted into any other editor as a normal text. 

## Your configuration (mandatory)
 - Operating system, potentially version and bitness - 18.04.1-Ubuntu SMP
 - Python version, bitness - Python 3.6.9 
 - PyMuPDF version, installation method (**wheel** or **generated** from source). - 1.17.0, installaed using pip
 - 
3.6.9 (default, Jun 29 2022, 11:45:57)
[GCC 8.4.0]
 linux

PyMuPDF 1.17.0: Python bindings for the MuPDF 1.17.0 library.
Version date: 2020-05-13 20:05:13.
Built for Python 3.6 on linux (64-bit).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
For example the first page:
```python
pprint(doc.get_page_fonts(0))
[(9, 'n/a', 'TrueType', 'Arial', 'F9', 'WinAnsiEncoding'),
 (10, 'ttf', 'TrueType', 'MUSQKV+Tahoma', 'F10', ''),   # <== no encoding
 (11, 'n/a', 'TrueType', 'Arial,Bold', 'F11', 'WinAnsiEncoding')]
```

**Comment by JorjMcKie** [comment]
There is no way to remove a font, because there is text using it.
Tools have different capabilities to interpret / extract text, so you may find one you could use here.
You could of course OCR the file and then use the resulting file - may be an overkill here.

**Comment by catchmeteja** [comment]
> There is no way to remove a font, because there is text using it. Tools have different capabilities to interpret / extract text, so you may find one you could use here. You could of course OCR the file and then use the resulting file - may be an overkill here.

Understood. Thank you for your response.
