### ISSUE TITLE
QImage shows distorted image from pixmap with some specific dpi

### ISSUE THREAD

**Issue by szsdk** [pymupdf/PyMuPDF#1916]
## Describe the bug
QImage shows a distorted image from pixmap with a certain dpi. For example, in the follow script, `dpi=91` does not work but `dpi=90` shows a normal expected result.
![image](https://user-images.githubusercontent.com/6657200/189617791-8ecc32de-9f73-4d57-bebc-43af1f2fbecc.png)

## To Reproduce
```python
import sys
from PyQt5.QtWidgets import QApplication, QLabel
from PyQt5.QtGui import QImage, QPixmap
import fitz

app = QApplication(sys.argv)

#render pdf with PyMuPDF
document = fitz.open("test.pdf")
page = document[0]
pix = page.get_pixmap(dpi=91, alpha = False)
samples = pix.samples

#convert to QImage
image=QImage(samples, pix.width, pix.height, QImage.Format_RGB888);

#show image in QLabel
label=QLabel()
label.setPixmap(QPixmap.fromImage(image))
label.show()
    
sys.exit(app.exec_())
```

## Your configuration
- python version: 3.9.13 (from conda-forge)
- pymupdf: ('1.20.2', '1.20.3', '20220813000001')

**Comment by JorjMcKie** [comment]
This is a PyQt deficiency, and not a PyMuPDF bug!
Specify this
```python
image = QImage(pix.samples_ptr, pix.width, pix.height, pix.stride, QImage.Format_RGB888)
```
This will deliver correct results - and also be 500 times or more faster.
