### ISSUE TITLE
`subset_fonts`: make it possible to silence the stdout

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#1917]
When I run `doc.subset_fonts()` I get the following on stdout/stderr (didn't check which):
```
Built subset of font 'Droid Sans Fallback Regular'.
```
Is it possible to suppress this output?  Perhaps with a `verbose=True` keyword argument?

**Comment by JorjMcKie** [comment]
Ok, accepted. Shouldn't be a problem.

**Comment by JorjMcKie** [comment]
Will be implemented in next version.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.21.0
