### ISSUE TITLE
Error when extracting images from pdf files, the background of the photo is turned black

### ISSUE THREAD

**Issue by nguyenquocduongqnu** [pymupdf/PyMuPDF#1919]
## Describe the bug
The output image is not as expected.

## To Reproduce
I want to get the image from this pdf page [test.pdf](https://github.com/pymupdf/PyMuPDF/files/9554380/test.pdf). The pdf page is described as shown below:
![image](https://user-images.githubusercontent.com/63329565/189810304-2c08d7b7-db85-47af-9f9c-1dace9ab4a21.png)

## Expected behavior
We use the following code:
```
page = pdf_file[page_index]
page_dict = page.get_text("dict")
blocks = page_dict["blocks"]  
img_blocks_all = [b for b in blocks if b["type"] == 1]
all_imgs = [img['image'] for img in img_blocks_all]

# Save images:
for i in range(len(all_imgs)) :
  pix = fitz.Pixmap(all_imgs[i])
  pix.pil_save(f"{i}.jpg", optimize=True, dpi=(150, 150)) 
```

And we get results like the 3 pictures below. Figure 3 gives the result not what we expected. 

Figure 1:
![CB410B3_img_258_1](https://user-images.githubusercontent.com/63329565/189830686-718544ab-ba00-4c02-9a50-bfdec89df36a.jpg)
Figure 2:
![CB410B3_img_258_2](https://user-images.githubusercontent.com/63329565/189830705-d060430d-1b57-4bba-bd77-f09b9adc5d41.jpg)
Figure 3:
![CB410B3_img_258_3](https://user-images.githubusercontent.com/63329565/189830726-cc148e5e-a98b-4a0d-bc22-738846a17a67.jpg)

**How to automatically identify blackened images and convert them back to their original form?**

```
x = imread(BytesIO(img_binary)
cv2.imwrite('file_name.jpg', 255- x)
```
![file_name](https://user-images.githubusercontent.com/63329565/189835921-19d83897-ea0d-40c9-8bd9-1b4539554b06.jpg)

Thank you.

**Comment by JorjMcKie** [comment]
This is not a bug.
If you use `page.get_text()` to extract images, any transparency information (i.e. SMask co-objects) is not contained in it.
You must follow the path `doc.extract_image()`, then see if the image has a mask, make a pixmap and also apply the mask, etc.
This procedure is explained in the [recipe section](https://pymupdf.readthedocs.io/en/latest/recipes-images.html#how-to-extract-images-pdf-documents) of the documentation.
