### ISSUE TITLE
get_text(textpage="blocks") error

### ISSUE THREAD

**Issue by scote89** [pymupdf/PyMuPDF#1921]
## Describe the bug (mandatory)
an error occurs when trying to obtain textblocks as such: `get_text(textpage="blocks")`

## To Reproduce (mandatory)
`doc[50].get_text(textpage="blocks")`

## Expected behavior (optional)
obtain textblocks

## Screenshots (optional)
Here we see that not choosing textpage="blocks" works in comparison.
![image](https://user-images.githubusercontent.com/50223503/189909576-25b2ab88-e8a7-4e98-a4ab-4dfe994c380d.png)

## Your configuration (mandatory)
 - Win, 64x
 - Python version=3.9, bitness= 64x
 - PyMuPDF version= 1.20.2, installation method ( **generated** from source).

## Additional context (optional)
None

**Comment by JorjMcKie** [comment]
There is a misconception WRT the textpage parameter: this must be a `fitz.TextPage` **_not a string!_**

**Comment by scote89** [comment]
Could we have an example of how to call Page.get_text() for blocks?

**Comment by JorjMcKie** [comment]
The valid output option codes are enumerated in the documentation [here](https://pymupdf.readthedocs.io/en/latest/page.html#Page.get_text): “text”, “blocks”, “words”, “html”, “xhtml”, “xml”, “dict”, “json”, “rawdict”, “rawjson”.
So do `blocks = page.get_text("blocks")`- that's it.
