### ISSUE TITLE
page.clean_contents() causes segmentation fault

### ISSUE THREAD

**Issue by f-izzat** [pymupdf/PyMuPDF#1941]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
As per the title, used the code from this [post](https://github.com/pymupdf/PyMuPDF/discussions/1855#discussioncomment-3324039) in order to detect and remove marked-content watermarks from each page of several pdfs. Tried loading the document, extracting/images/annotations and it works fine. However when i call page.clean_contents() the segmentation fault appears

## To Reproduce (mandatory)
Cant really reproduce since the documents are confidential. However this is the code i used, the print statements were used to debug
```
if __name__ == "__main__":
    path = "/path/to/pdf"
    files = sorted([f for f in os.listdir(path) if os.path.isfile(os.path.join(path, f)) and not f.startswith('.')])
    dst = "/destination/folder"
    for ff in files:
        print(f"Load {ff} |", end="")
        doc = fitzopen(f"{path}/{ff}")        
        """ DETECT+REMOVE WATERMARK """
        for idx, page in enumerate(doc.pages()):
            page.clean_contents()
            print(f"Cleaned Page {idx+1}/{doc.page_count}|", end="")

            xref = page.get_contents()[0]  # get xref of resulting /Contents object
            cont = bytearray(page.read_contents())  # read the contents source as a (modifyable) bytearray
            if cont.find(b"/Subtype/Watermark") > 0:  # this will confirm a marked-content watermark is present
                print("| WATERMARK PRESENT ", end="")
                while True:
                    i1 = cont.find(b"/Artifact")  # start of definition
                    if i1 < 0: break  # none more left: done
                    i2 = cont.find(b"EMC", i1)  # end of definition
                    cont[i1-2 : i2+3] = b""  # remove the full definition source "q ... EMC"
                doc.update_stream(xref, cont)  # replace the original source
                print("| STREAM UPDATED ", end="")
                doc.ez_save(f"{dst}/{ff}")  # save to new file
                print("| DOC SAVED ", end="")
        doc.close()
        print("| Done", end="\n")
```
<img width="634" alt="image" src="https://user-images.githubusercontent.com/97789955/193206888-d3b1dfc1-379b-4790-b26f-7636051844e7.png">

It is the file after `1660016063794.pdf` that causes the seg fault. As mentioned before, loading the file and extracting text/images/annotations has no problems.

## Your configuration (mandatory)
 - Mac OS
- 3.7.13 (default, Aug 30 2022, 05:17:35) 
[Clang 12.0.0 (clang-1200.0.32.29)] 
 darwin 
 
- PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
Version date: 2022-08-13 00:00:01.
Built for Python 3.7 on darwin (64-bit).

**Comment by JorjMcKie** [comment]
I am sorry, but we cannot deal with a bug without being able to reproduce it.
Please try to either make up a reproducing file that has no confidentiality issues, or get the authority to still share the file with me - possibly by sending it to my private e-mail address (jorj.x.mckie@outlook.de).

**Comment by f-izzat** [comment]
Hi @JorjMcKie , So everything started to work as usual when i set `page.clean_contents(sanitize=False)`. Im assuming that something computationally heavy is going on in the background? But just to confirm, would setting `sanitize=False` have any effect on the function you [posted](https://github.com/pymupdf/PyMuPDF/discussions/1855#discussioncomment-3324039)?

**Comment by JorjMcKie** [comment]
> Hi @JorjMcKie , So everything started to work as usual when i set `page.clean_contents(sanitize=False)`. Im assuming that something computationally heavy is going on in the background? But just to confirm, would setting `sanitize=False` have any effect on the function you [posted](https://github.com/pymupdf/PyMuPDF/discussions/1855#discussioncomment-3324039)?

Indeed, the `clean_contents()` method is a powerful function:
1. it joins any multiple `/Contents` objects a PDF page may have (often is the case) into only one such object,
2. then syntactically reformats the resulting source code (it in fact **_is_** source!) according to some principles (e.g. every source command is put in its own line of code),
3. then checks whether references to the page's "resources" (e.g. fonts and images) are in 1:1 correspondence to the resources actually present in the page's object definition. As part of that, resource reference names are being changed to conform to a certain scheme (like images are named "Im?", fonts are "F?", etc.).
4. all of the above also is applied to other PDF objects connected to the page, which themselves have this type of command sources ("Form XObjects").

PyMuPDF calls a MuPDF function upon invoking `clean_contents()`. Certain of the above details actions are left out if you use `sanitize=False`. 

You only need the source code cleaning part. I believe you may therefore get what you want specifying "sanitize" with `False`.

Apart from the possibility, that your input files already are well-formed WRT 1 line = 1 command, which is all you need.

**Comment by JorjMcKie** [comment]
So wrapping up:

If you get what you want in the described way, and if you (very unfortunately!) will not be able to share the failing file, then you should close the issue please.

**Comment by f-izzat** [comment]
Thanks @JorjMcKie for the detailed answer, much appreciated! Yes, its very unfortunate that I cant share the file nor have an idea as to how to reduce it in a way that the sensitive information is removed. Or rather, in a way that I wouldnt tamper the document (a lot) so as to lose the actual trace that led to the seg fault. I do plan, however, to find some public dataset and try it again, and will report back should the seg fault issue arise. till then I will close the issue 

Thanks

**Comment by JorjMcKie** [comment]
Thank you. Please do not hesitate to re-open or open a new issue if the situation changes accordingly.
