### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zwitterion** [pymupdf/PyMuPDF#1945]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When saving some PDF's, using the clean=True option, the process crashes with the error:

## To Reproduce (mandatory)
This code will consistently reproduce the error: Segmentation fault (core dumped)

import io
import fitz

pdf = fitz.open("bbc.pdf")
buffer = io.BytesIO()
pdf.save(buffer, clean=True)   # <-- crash here

## Your configuration (mandatory)
 - Linux + Docker image built based of: FROM python:3.9-slim image
-  PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
-  Version date: 2022-08-13 00:00:01.
-  Built for Python 3.9 on linux (64-bit).

[bbc.pdf](https://github.com/pymupdf/PyMuPDF/files/9710107/bbc.pdf)

**Comment by julian-smith-artifex-com** [comment]
Thanks for the report. I get the SEGV with pymupdf-1.20.2.

Interestingly though, current PyMuPDF master with latest MuPDF seems to work ok with no SEGV.

**Comment by JorjMcKie** [comment]
> Thanks for the report. I get the SEGV with pymupdf-1.20.2.
> 
> Interestingly though, current PyMuPDF master with latest MuPDF seems to work ok with no SEGV.

Confirming both observations. The error is being fixed by the next version.

**Comment by zwitterion** [comment]
Thank you!

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.21.0
