### ISSUE TITLE
block_no from get_text("blocks") and get_text("words") do not match, if images are on the page

### ISSUE THREAD

**Issue by Ulipenitz** [pymupdf/PyMuPDF#1947]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
If there are images on a pdf page, get_text("blocks") returns block_no for images.
get_text("words") seems to skip blocks with images, so block_no for words returned from get_text("words") cannot be matched with the according block from get_text("blocks")

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

      with fitz.open(path) as document:
          pages_dict = {}
          for page_no, page in enumerate(document):
              paragraphs = page.get_text("blocks")
              paragraphs_dict = {}
              for block_no, paragraph in enumerate(paragraphs):
                  paragraphs_dict[block_no] = paragraph 
              
              words = page.get_text("words")
      
              pages_dict[page_no] = {
                  "page_number": page_no,
                  "paragraphs": paragraphs_dict,
                  "words": words
              }

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).
I expect to be able to match words with the according block, so that I can get all paragraphs with coodrinates and also the words within the paragraph with coordinates.

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).
windows10 home
python3.7
PyMuPDF-1.20.2-cp37-cp37m-win_amd64.whl

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
>  I expect to be able to match words with the according block, so that I can get all paragraphs with coodrinates and also the words within the paragraph with coordinates.

"words" extraction by default on purpose internally uses a `flags` configuration, which ignores images on a page. The obvious motivation is performance.
This implies that the function, which extracts the words, does not know and cannot know the block numbering if images would have been included.

"blocks" extraction by contrast has default `flags` which include image blocks.

All this is no bug but works as designed and as intended to be exactly like that.

It is your responsibility to use the same `flags` value in both cases. There are convienent bit combinations available - in your case probably best is using `fitz.TEXTFLAGS_WORDS` also for the blocks extraction.

**Comment by JorjMcKie** [comment]
You seem not to be aware of the fact that text extraction (and search) is/are based on data provided by the `TextPage` object.
This object is created first. It exists mainly for the purpose to neutralize / abstract from the different document types supported by MuPDF.
The TextPage object prepares the page data - based on those flags. All the various `get_text()` flavors then exclusively interpret those data, and thus know nothing else about the original document page.

**Comment by Ulipenitz** [comment]
Alright thank you very much for clarification!
