### ISSUE TITLE
Support `py3-none-any.whl` build package

### ISSUE THREAD

**Issue by yannbertrand** [pymupdf/PyMuPDF#1959]
**Is your feature request related to a problem? Please describe.**
I am trying to install PyMuPDF inside [Pyodide](https://pyodide.org/en/stable/usage/loading-packages.html), the later goal is to develop a client side PDF images extractor (can't find how to do it in JS as Mozilla's PDF.js only support JPEG afaik).

It seems like it's not possible as PyMuPDF doesn't provide a `py3-none-any.whl` build distribution.

**Describe the solution you'd like**
I have absolutely no idea if it's possible, but generating a `py3-none-any.whl` build output would be great :)

Didn't find any issues about this but please feel free to close it if that's a duplicate.

**Describe alternatives you've considered**
No idea, open to other ideas!

**Additional context**
Reproduction in a .html file
```
<script src="https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js"></script>
<script>
  async function main() {
    console.log('Loading Pyopdide...');
    let pyodide = await loadPyodide();
    // Pyodide is now ready to use...
    console.log('Loading package "micropip"');
    await pyodide.loadPackage('micropip');
    const micropip = pyodide.pyimport('micropip');
    console.log('Loading package "PyMuPDF"');
    await micropip.install('PyMuPDF'); // -> crashes there

    console.log(
      pyodide.runPython(`
      import sys
      sys.version
    `)
    );
    pyodide.runPython('print(1 + 2)');
  }

  main();
</script>
```

**Comment by JorjMcKie** [comment]
The naming scheme you mentioned is reserved for Python source packages.
PyMuPDF however is a binding to MuPDF, a C-library, so the major part of its functionality is contained in a fairly large (12+ MB) binary module.
So there **_never_** can possibly exist a version with the platform tag you mentioned.

I looked up Pyodide and saw that this is a platform requiring binaries supporting WASM - this is not supported by PyMuPDF yet.

But we can check what the chances for this are.

**Comment by julian-smith-artifex-com** [comment]
Python wheels for Pyodide don't seem to be anywhere near supported yet. Certainly cibuildwheel (which we use to build wheels for Windows, Linux and MacOS on github machines) does not know anything about Pyodide.

If/when that changes we can certainly look into building Pyodide wheels. But i can't see it happening any time soon, so i'll close this issue for now.
