### ISSUE TITLE
search_for is case sensitive

### ISSUE THREAD

**Issue by FeltesPT** [pymupdf/PyMuPDF#1976]
Looking for text using `search_for` is returning different results depending on the Case (lower/upper).
If I search for `guideline` and `Guideline`, returns different results, despite the Documentation saying this method is case insensitive...

## To Reproduce
```
doc = fitz.open(book.pdf.path)
found = False
flags = fitz.TEXT_PRESERVE_LIGATURES | fitz.TEXT_PRESERVE_WHITESPACE
for page in doc:
  text_instances = page.search_for(query, flags=flags)

  if len(text_instances) > 0:
    text = page.get_text("text").split('\n')

    for block in text:
      if query in block:
        references.append({'book':bookToJSON(book), 'page':page.number + 1, 'text': block})
        found = True
        break
      
  if found:
    break

doc.close()
```

## Expected behavior
It should find the first occurrence of the search terms (case insensitive), a quick snapshot and the page where it was found.

## Your configuration
 - Mac OS
 - Django version 4.1.2, 
 - PyMuPDF 1.20.2

**Comment by FeltesPT** [comment]
![Screenshot 2022-10-19 at 17 39 34](https://user-images.githubusercontent.com/5504319/196753298-ce89fcd6-aa0b-461b-824c-7937476d4fcc.png)
![Screenshot 2022-10-19 at 17 40 11](https://user-images.githubusercontent.com/5504319/196753304-b9d2fcbe-f652-419a-a10f-e2daa97403f6.png)

**Comment by JorjMcKie** [comment]
We need an example file to reproduce. Something must be wrong with it or your script.
Just comfirmed with an example that there exists case-insensivity.

**Comment by JorjMcKie** [comment]
your results may also be blurred because of your flags: if white space is on and ligatures are kept, you are taking risks, because you annot be sure if thing like "ff", "fi" etc. always are separate characters or sometimes one single ligature - which cannot be found by searching with characters "ff" - you get the point?

**Comment by FeltesPT** [comment]
Thank you for your reply @JorjMcKie. I was testing the flags when I took the screenshot, but I wasn't using any flags initially and the issue was happening anyway.

There isn't a lot more in the method. But here is a screenshot with the whole thing.

![Screenshot 2022-10-19 at 21 20 04](https://user-images.githubusercontent.com/5504319/196795660-b4d4f291-5dc0-4550-afa8-372d3f69531c.png)

**Comment by FeltesPT** [comment]
I found the problem... Thank @JorjMcKie. It is a problem with my script. Closing the issue.
