### ISSUE TITLE
Error when opening pdf file embedded with embfile_add in for example Acrobat Reader

### ISSUE THREAD

**Issue by PatrikAarnivaara** [pymupdf/PyMuPDF#1977]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When I try to open a pdf embedded with the function embfile_add() the pdf viewer (both Acrobat and Document Viewer) throws an error saying Unable to open document “file:///tmp/evince.5GKDU1/embedMePqm.pdf”. File type plain text document (text/plain) is not supported.

## To Reproduce (mandatory)
import fitz
original = fitz.open("document.pdf", filetype="pdf")
signature = fitz.open("append.pdf", filetype="pdf")
attachment = fitz.open("out.pdf", filetype="pdf")

original.embfile_add("embedMePqmx.pdf", attachment)

original.insert_pdf(signature)

original.save(original, incremental=True, encryption=0)

## Expected behavior (optional)
Pdf attachment should be viewable.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/56720091/196893520-0a35ee30-ddd6-4bdc-86ca-0ae60d54d381.png)

## Your configuration (mandatory)
 - Linux/Ubuntu
3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] 
PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
Version date: 2022-08-13 00:00:01.
Built for Python 3.10 on linux (64-bit).

**Comment by JorjMcKie** [comment]
This is a user error - please see the documentation.
You can only add files with their **_binary content_**. So you should have done something like this:
```python
buffer = pathlib.Path("out.pdf").read_bytes()
doc.embfile_add("some-name", buffer, ...)
```

**Comment by PatrikAarnivaara** [comment]
Ok, I missed that part of the documentation. Thanks for the help.
