### ISSUE TITLE
Getting an issue when insert DAGGER character

### ISSUE THREAD

**Issue by hoaile-novobi** [pymupdf/PyMuPDF#1989]
Hi admin, I am trying use `insert_text` function to add DAGGER character (†) but it looks like it only show a black circle

Here is my code:
`page_0.insert_text((100,100), "HINES SECURITIES, INC.†")`

And the result
![image](https://user-images.githubusercontent.com/104294815/197686530-ed33b3ac-47d0-45a5-87dd-913e5a24a01f.png)

**Comment by hoaile-novobi** [comment]
The issue was fixed when I used TextWriter.

**Comment by JorjMcKie** [comment]
Just to add an explanation for what you were experiencing:

You used the `.insert_text()` method with the default font Helvetica ("helv"). This is one of the (Base-14) built-in fonts which only support characters with a unicode representation <= 255. An arbitrary symbol may or may not be represented by those 255 characters, so a replacement character was shown.

If you use `TextWriter` then (with the same-named default font "helv"), then a non-built-in font will be used that looks exactly equal to Helvetica - but it is something different:
It is a real font file that will be embedded into your PDF (which therefore becomes larger), and it contains many more characters. Check out this:
```python
In [1]: import fitz
In [2]: font=fitz.Font("helv")  # uses the embeddable version!
In [3]: font.glyph_count
Out[3]: 654
```
Another advantage of `TextWriter` output is that it will automatically try to find characters in a "fallback" font, that are missing in your chosen font.

Then there is also this hickup:
If you use the dagger symbol in a Python text, Python will decide the unicode number of the each character in the string. In case of the dagger you will find `ord("†") = 8224`, which is clearly beyond the 256 bytes range of the **_built-in_** Helvetica.
The same is true for the Euro symbol "€" which can be found under unicode 8364 - **_but in this case_** the built-in Helvetica **_has_** that symbol, but under unicode number 128. To print that symbol using the **_built-in_** font, replace every € by chr(128) in your text.
But also the dagger symbol is contained in the built-in Helvetica ... under number 134. So with `text.replace("†", chr(134))` you would have seen it nicely ... 😎.

**Comment by hoaile-novobi** [comment]
How can i know the † is number 134 ?
I got the issue again, but with the other character, it is Polish character like (a, ą, b, c, ć, d, e, ę, f, g, h, i, j, k, l, ł, m, n, ń, o, ó, p, (q), r, s, ś, t, u, (v), w, (x), y, z, ź, ż)
