### ISSUE TITLE
PyMuPDF is not getting installed in the git VM machine now but it was working 4 days before

### ISSUE THREAD

**Issue by utkarshamnesia** [pymupdf/PyMuPDF#1992]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
PyMuPDF is not getting installed in the git VM machine now but it was working 4 days before

## To Reproduce (mandatory)
Installing it in git VM machine and same experience when running in local Docker. (docker buildx build --platform linux/amd64 -t amnesiahub .)

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Mac Os but running in the Linux VM
 - Python version, bitness
 - PyMuPDF 1.20.1, installation method wheel

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).
<img width="1248" alt="Screenshot 2022-10-26 at 10 23 02 PM" src="https://user-images.githubusercontent.com/97506497/198087586-a68e1b6d-2d03-46c6-85b2-25a5884fc384.png">

**Comment by julian-smith-artifex-com** [comment]
Please specify the python version (within the VM/docker).

When it was working, was PyMuPDF installed directly from a wheel (which would be quick), or did it build from sdist (which would take a while)?

Do you know anything that might have changed in the VM - for example has the python version within the VM changed?

**Comment by cbm755** [comment]
> Please specify the python version (within the VM/docker).

Maybe its b/c Python 3.11 is out and we don't have wheels yet?

**Comment by julian-smith-artifex-com** [comment]
PyMuPDF-1.21.0rc1 is available. It has wheels for Python-3.11, so might be worth trying.

See: #2009 for more information.

**Comment by cbm755** [comment]
FWIW, the rc1 worked in my Gitlab CI jobs.

**Comment by julian-smith-artifex-com** [comment]
That's great, thanks for reporting this.
