### ISSUE TITLE
Clarification about threading

### ISSUE THREAD

**Issue by FabriceSalvaire** [pymupdf/PyMuPDF#1994]
As far I understand, from https://mupdf.com/docs/examples/multi-threaded.c. 
We could have a true multithreaded processing with Python by wrapping libmupdf with **CFFI**.

So the issue related in https://pymupdf.readthedocs.io/en/latest/recipes-multiprocessing.html is due to the actual **SWIG wrapper**.
Thus, the Qt example is misleading, it is just a simple and working solution rather than the right one to implement.

Moreover, an example for Qt doesn't make sense nowadays, since Qt 6.3 supports PDF natively in QML.  I would go for the multi-threaded.c solution if I want a faster processing.  It could rather make sense for text extraction.

I think the documentation is actually misleading.

**Comment by JorjMcKie** [comment]
I hope we could clarify this inquiry.
Since there are no further comments, we are going to close this now.

**Comment by OrionSehn** [comment]
Just thinking about how python 3.14 now removes the global interpreter lock. Does this change the restriction on multi-threading here? Should we consider looking into a free-threaded solution like pandas has? 

Thanks for your consideration.

**Comment by OrionSehn** [comment]
I think it would require this:

https://py-free-threading.github.io/porting-extensions/
