### ISSUE TITLE
AttributeError: 'Widget' object has no attribute '_annot' in delete widget

### ISSUE THREAD

**Issue by MallRoy** [pymupdf/PyMuPDF#2013]
## Describe the bug
We are trying to detect the signature widget and delete it. When we perform the operation it throws **AttributeError: 'Widget' object has no attribute '_annot'**
Sample PDF: 
[signed_sample.pdf](https://github.com/pymupdf/PyMuPDF/files/9916829/signed_sample.pdf)

## To Reproduce
```
import fitz

class PdfFunctions:
    def __init__(self, input_path, outputFilePath):
        self.pdfFilePath = input_path
        self.outputFilePath = outputFilePath

    def removesignaturewidget(self):
        doc = fitz.open(self.pdfFilePath)
        for page in doc.pages():     
            for w in page.widgets():
                print(w.xref)
                if (w.field_type == 6):
                    print('exists')
                    page.delete_widget(w)
                    
        doc.save(self.outputFilePath, garbage=3, deflate=True, pretty=True)
        print(self.outputFilePath)
        doc.close()

if __name__ == "__main__":
    filePath = "signed_sample.pdf"
    outputPath = "output.pdf"
    PdfFunction = PdfFunctions(filePath, outputPath)
    PdfFunction.removesignaturewidget()
```

## Expected behavior
The signature widget should be deleted.

## Error Screenshots
![image](https://user-images.githubusercontent.com/54269166/199413002-ffc0bb7f-34c7-4d1a-a759-6db6b1ff26cc.png)

## Your configuration (mandatory)
PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
Version date: 2022-08-13 00:00:01.
Built for Python 3.9 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
You cannot use `page.widgets()` in this context, because deleting a widget changes the iterator.
Do this instead:
```python
for page in doc:
    w = page.first_widget
    while w:
        if w.field_type == 6:
            w = page.delete_widget(w)  # delivers None or next after deleted one
        else:
            w = w.next
```

**Comment by MallRoy** [comment]
I have tried the above solution. It is throwing the same error.

**Comment by JorjMcKie** [comment]
> I have tried the above solution. It is throwing the same error.

Can't be! I tried it out on an example.
Can you share your example file?

**Comment by MallRoy** [comment]
```
import sys
import fitz

class PdfFunctions:
    def __init__(self, input_path, outputFilePath):
        self.pdfFilePath = input_path
        self.outputFilePath = outputFilePath

    def removesignaturewidget(self):
        doc = fitz.open(self.pdfFilePath)
        for page in doc:
                w = page.first_widget
                while w:
                    if w.field_type == 6:
                        w = page.delete_widget(w)  # delivers None or next after deleted one
                    else:
                        w = w.next
            
        doc.save(self.outputFilePath, garbage=3, deflate=True, pretty=True)
        print(self.outputFilePath)
        doc.close()


if __name__ == "__main__":
    filePath = "signed_sample.pdf"
    outputPath = "output.pdf"
    PdfFunction = PdfFunctions(filePath, outputPath)
    PdfFunction.removesignaturewidget()
```

**Comment by JorjMcKie** [comment]
Indeed, there is a bug!
For a hot fix, please change line 1823 in file fitz.py in your Python installation from this:

`annot = getattr(self, "_annot")`

to this:

`annot = getattr(self, "_annot", None)`

A final fix will be included in the new version.
