### ISSUE TITLE
Add Support for PDF Action Type GoToE

### ISSUE THREAD

**Issue by Mano2731995** [pymupdf/PyMuPDF#2033]
Hi, 

One pdf file having multiple pdf attachments. 

I need to map  attachment with pdf hot area(text) 

When click the string(text), attachment should be open. 

I am not able to find out attachment location path

Kindly help on this task. I am using fitz library

**Comment by Mano2731995** [comment]
I need  map to string(hot area text)  and pdf attachments 

When I click the string attachment document should be open

**Comment by Mano2731995** [comment]
Here is the code

import fitz
doc=fitz.open('C:\xxx.pdf') 
PdfAttachments=['abc.pdf']
String=['python']

for(j, k) in zip(String, pdfAttachments) :
  for page in doc:
  Text= page. Search_for(j) 
for i in text:
 Link= page. Insert_link({'kind':2, 'from':fitz.Rect(i.x0, i.y0, i.x1, i.y1), 'uri':k}) 

Doc. Save(op.pdf) 
 

Code running no error but string not linked to attachment document

**Comment by Mano2731995** [comment]
Thanks for your reply jorj

Yes u said right. That is embedded file. 

when I click the string(hot area) embedded file need to open 

Kindly let me know how can i do that?

**Comment by JorjMcKie** [comment]
My suggestion does **not** lead to a text as hot area, but to a button:
`page.add_file_annot()`. Put some button like this:
![grafik](https://user-images.githubusercontent.com/8290722/200531118-43c1575b-a3a5-4d29-a6a2-31821b74b738.png)
The code making this:
```python
import pathlib
pdfbytes=pathlib.Path("v110-changes.pdf").read_bytes()
page.add_file_annot((100,100),pdfbytes,filename="v110-changes.pdf")
'FileAttachment' annotation on page 0 of <new PDF, doc# 1>
doc.save("x.pdf")
```

PDF viewers ususally offer ways to open that file, similar to this one:
![grafik](https://user-images.githubusercontent.com/8290722/200531980-0a00dca4-26ff-4668-936b-2d50066daab8.png)

**Comment by Mano2731995** [comment]
Got it thanks but i need that button should be in near by hot text because that hot area text related to embedd file. 
When click the hot area text embeed file should be open. So button should be nearby text

**Comment by JorjMcKie** [comment]
> Got it thanks but i need that button should be in near by hot text because that hot area text related to embedd file. When click the hot area text embeed file should be open. So button should be nearby text

Only a button will be created! The text you see in the picture is the mouse-over hovering text. With this "solution" you have to manually add (inactive) text to the side of the button.

**Comment by JorjMcKie** [comment]
>  My requirement is click the text and embeed file neee to open. Button option not accepted

Well then "sorry" is all I can say ...

**Comment by Mano2731995** [comment]
Thanks for your support jorj

**Comment by Mano2731995** [comment]
Hi jorj In pymupdf(fitz) cannot able to link the string text and embed file 

Kindly let me know if any other pdf module can able to link

**Comment by JorjMcKie** [comment]
> Hi jorj In pymupdf(fitz) cannot able to link the string text and embed file
> 
> Kindly let me know if any other pdf module can able to link

I am currently not aware of any. Will let you know when I come across one.

**Comment by Mano2731995** [comment]
Hai jorj

One pdf document having 3 Embedded files.I need to save the embedded file in other external folder. 
It's action should need fitz module. 
Could you please tell how can do that?

**Comment by JorjMcKie** [comment]
@Mano2731995 - you can extract the file contents via `Document.embfile_get(item)` where item is the name or the number of the entry.
This is a `bytes` object. Depending on the other attributes of the item, you can choose its filename or any filename you like:
```python
filename = doc.embfile_info(item)["filename"]
out = open(filename, "wb")
out.write(doc.embfile_get(item))
out.close()
```

**Comment by JorjMcKie** [comment]
@Mano2731995 you can also use the fitz module `python -m fitz embed-extract ...`

**Comment by Mano2731995** [comment]
> @Mano2731995 - you can extract the file contents via `Document.embfile_get(item)` where item is the name or the number of the entry.
> This is a `bytes` object. Depending on the other attributes of the item, you can choose its filename or any filename you like:
> ```python
> filename = doc.embfile_info(item)["filename"]
> out = open(filename, "wb")
> out.write(doc.embfile_get(item))
> out.close()
> ```

I got Name error: name'doc' is not defined 

What library need to use?

**Comment by JorjMcKie** [comment]
> I got Name error: name'doc' is not defined
> What library need to use?

Well, of course you must import fitz (PyMuPDF) and then open the PDF, e.g. via `doc = fitz.open("file.pdf")`!

**Comment by Mano2731995** [comment]
> > I got Name error: name'doc' is not defined
> > What library need to use?
> 
> Well, of course you must import fitz (PyMuPDF) and then open the PDF, e.g. via `doc = fitz.open("file.pdf")`!

Import fit
Import item as item

doc = fitz.open('xyz.pdf') 
Filename= doc.embfile_info(item) ['xyz']
Out=open(Filename, 'wb') 
Out. Write(doc.embfile_get(item)) 
Out. Close () 

Value error module item from 'c:\\users.... Not in embeddedfiles array

**Comment by JorjMcKie** [comment]
Well this is a Q&A thing, definitely not any type of issue.
I will convert this to a "Discussion" item, before we bloat the list of real issues.

**Comment by Mano2731995** [comment]
Hi jorj
I'm using Adobe Acrobat Reader DC. I When I trying to click on a  (link) ,  a Security Warning pops up that states "this document is trying to access: \\users\xyz\desktop\Untitled-1.pdf" If you trust this document, choose Allow. If you do not trust this document, choose Block. I chose Allow. The next pop up states: Acrobat Reader... The plug-in required by this "GoToR" action is not available. Information about the missing plug-in may be available on Adobe's Website.

 

There is no mention to the actual plug-in name required. How do I get this problem fixed?

**Comment by JorjMcKie** [comment]
> Hi jorj I'm using Adobe Acrobat Reader DC. I When I trying to click on a (link) ,  a Security Warning pops up that states "this document is trying to access: \users\xyz\desktop\Untitled-1.pdf" If you trust this document, choose Allow. If you do not trust this document, choose Block. I chose Allow. The next pop up states: Acrobat Reader... The plug-in required by this "GoToR" action is not available. Information about the missing plug-in may be available on Adobe's Website.
> 
> There is no mention to the actual plug-in name required. How do I get this problem fixed?

This is not a (Py-) MuPDF problem. Must be your Adobe reader installation. Works on my machine. Please consult their web sites.

Please observe:
The tab `"Issues"` is reserved for issues and should not be used for questions. There is a separate tab `"Discussions"` for this purpose.
In addition, it is confusing for everyone looking at your post, if several different topics are being talked about. Please open a separate Discussions item for separate topics.

**Comment by Mano2731995** [comment]
> > Hi jorj I'm using Adobe Acrobat Reader DC. I When I trying to click on a (link) ,  a Security Warning pops up that states "this document is trying to access: \users\xyz\desktop\Untitled-1.pdf" If you trust this document, choose Allow. If you do not trust this document, choose Block. I chose Allow. The next pop up states: Acrobat Reader... The plug-in required by this "GoToR" action is not available. Information about the missing plug-in may be available on Adobe's Website.
> > 
> > There is no mention to the actual plug-in name required. How do I get this problem fixed?
> 
> This is not a (Py-) MuPDF problem. Must be your Adobe reader installation. Works on my machine. Please consult their web sites.
> 
> Please observe:
> The tab `"Issues"` is reserved for issues and should not be used for questions. There is a separate tab `"Discussions"` for this purpose.
> In addition, it is confusing for everyone looking at your post, if several different topics are being talked about. Please open a separate Discussions item for separate topics.
> 

Ok jorj I will create discussion. Thanks for your excellent support.

**Comment by Mano2731995** [comment]
Hai jorj

Requirement: page.inserlink() should be need to access the embedded files(when we click the link, embedded files need to open) 

My request is Kindly add to Pymupdf library above said requirement

Kindly consider this requirement.

**Comment by JorjMcKie** [comment]
The `GoToE` feature cannot be supported by PyMuPDF alone. For a roundtrip (getting and setting), MuPDF is also required.
There are currently no such plans, we therefore are marking this as "won't fix".
