### ISSUE TITLE
'"devenv.com"' is not recognized as an internal or external command --- when installing

### ISSUE THREAD

**Issue by texbowman** [pymupdf/PyMuPDF#2037]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I use pip to install the package, and it fails. I do not have a clue what is going on.

My platform: Windows 11 Pro 10.0.22621 Build 22621
System Type: x64-based PC
python version: 3.11.0 (I use chocolatey to install python and pip)
pip version: 22.3

`PS C:\Users\wolf_> python3 -m pip install --upgrade --use-pep517 pymupdf
Collecting pymupdf
  Using cached PyMuPDF-1.21.0.tar.gz (57.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pymupdf
  Building wheel for pymupdf (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pymupdf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [79 lines of output]
      PyMuPDF/setup.py: sys.argv: ['setup.py', 'bdist_wheel', '--dist-dir', 'C:\\Users\\wolf_\\AppData\\Local\\Temp\\pip-wheel-3u1uadei\\tmp0tzge0y7']
      PyMuPDF/setup.py: os.getcwd(): C:\Users\wolf_\AppData\Local\Temp\pip-install-chl6z5o5\pymupdf_398d46ce7daf4f43bf24ba74f9aa5682
      PyMuPDF/setup.py: __file__: setup.py
      PyMuPDF/setup.py: $PYTHON_ARCH: None
      PyMuPDF/setup.py: os.environ (47):
      PyMuPDF/setup.py:     ALLUSERSPROFILE: C:\ProgramData
      PyMuPDF/setup.py:     APPDATA: C:\Users\wolf_\AppData\Roaming
      PyMuPDF/setup.py:     CHOCOLATEYINSTALL: C:\ProgramData\chocolatey
      PyMuPDF/setup.py:     CHOCOLATEYLASTPATHUPDATE: 133110965117942506
      PyMuPDF/setup.py:     COMMONPROGRAMFILES: C:\Program Files\Common Files
      PyMuPDF/setup.py:     COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
      PyMuPDF/setup.py:     COMMONPROGRAMW6432: C:\Program Files\Common Files
      PyMuPDF/setup.py:     COMPUTERNAME: OFIDIUS
      PyMuPDF/setup.py:     COMSPEC: C:\WINDOWS\system32\cmd.exe
      PyMuPDF/setup.py:     DRIVERDATA: C:\Windows\System32\Drivers\DriverData
      PyMuPDF/setup.py:     HOMEDRIVE: C:
      PyMuPDF/setup.py:     HOMEPATH: \Users\wolf_
      PyMuPDF/setup.py:     LOCALAPPDATA: C:\Users\wolf_\AppData\Local
      PyMuPDF/setup.py:     LOGONSERVER: \\OFIDIUS
      PyMuPDF/setup.py:     NUMBER_OF_PROCESSORS: 16
      PyMuPDF/setup.py:     NVIDIAWHITELISTED: 0x01
      PyMuPDF/setup.py:     ONEDRIVE: C:\Users\wolf_\OneDrive
      PyMuPDF/setup.py:     OS: Windows_NT
      PyMuPDF/setup.py:     PATH: C:\Users\wolf_\AppData\Local\Temp\pip-build-env-3gsfkqtb\overlay\bin;C:\Users\wolf_\AppData\Local\Temp\pip-build-env-3gsfkqtb\normal\bin;C:\Python311\Scripts\;C:\Python311\;C:\Python310\Scripts\;C:\Python310\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\Programme\SumatraPDF;C:\ProgramData\chocolatey\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Programme\PDFtk-Server\bin\;C:\Programme\swig\;C:\Users\wolf_\AppData\Local\Microsoft\WindowsApps;C:\texlive\2022\bin\win32;C:\msys64\mingw64\bin\;C:\msys64\mingw64\bin\
      PyMuPDF/setup.py:     PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL
      PyMuPDF/setup.py:     PROCESSOR_ARCHITECTURE: AMD64
      PyMuPDF/setup.py:     PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
      PyMuPDF/setup.py:     PROCESSOR_LEVEL: 6
      PyMuPDF/setup.py:     PROCESSOR_REVISION: a502
      PyMuPDF/setup.py:     PROGRAMDATA: C:\ProgramData
      PyMuPDF/setup.py:     PROGRAMFILES: C:\Program Files
      PyMuPDF/setup.py:     PROGRAMFILES(X86): C:\Program Files (x86)
      PyMuPDF/setup.py:     PROGRAMW6432: C:\Program Files
      PyMuPDF/setup.py:     PSMODULEPATH: C:\Users\wolf_\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
      PyMuPDF/setup.py:     PUBLIC: C:\Users\Public
      PyMuPDF/setup.py:     SHIM_MCCOMPAT: 0x810000001
      PyMuPDF/setup.py:     SYSTEMDRIVE: C:
      PyMuPDF/setup.py:     SYSTEMROOT: C:\WINDOWS
      PyMuPDF/setup.py:     TEMP: C:\Users\wolf_\AppData\Local\Temp
      PyMuPDF/setup.py:     TMP: C:\Users\wolf_\AppData\Local\Temp
      PyMuPDF/setup.py:     USERDOMAIN: OFIDIUS
      PyMuPDF/setup.py:     USERDOMAIN_ROAMINGPROFILE: OFIDIUS
      PyMuPDF/setup.py:     USERNAME: wolf_
      PyMuPDF/setup.py:     USERPROFILE: C:\Users\wolf_
      PyMuPDF/setup.py:     WINDIR: C:\WINDOWS
      PyMuPDF/setup.py:     WSLENV: WT_SESSION::WT_PROFILE_ID
      PyMuPDF/setup.py:     WT_PROFILE_ID: {61c54bbd-c2c6-5271-96e7-009a87ff44bf}
      PyMuPDF/setup.py:     WT_SESSION: 231b1f39-d6c9-4b42-9f20-6ddd81268456
      PyMuPDF/setup.py:     PIP_BUILD_TRACKER: C:\Users\wolf_\AppData\Local\Temp\pip-build-tracker-h994spfb
      PyMuPDF/setup.py:     PYTHONNOUSERSITE: 1
      PyMuPDF/setup.py:     PYTHONPATH: C:\Users\wolf_\AppData\Local\Temp\pip-build-env-3gsfkqtb\site
      PyMuPDF/setup.py:     PEP517_BUILD_BACKEND: setuptools.build_meta:__legacy__
      PyMuPDF/setup.py: mupdf_tgz already exists: C:\Users\wolf_\AppData\Local\Temp\pip-install-chl6z5o5\pymupdf_398d46ce7daf4f43bf24ba74f9aa5682\mupdf.tgz
      PyMuPDF/setup.py: Extracting C:\Users\wolf_\AppData\Local\Temp\pip-install-chl6z5o5\pymupdf_398d46ce7daf4f43bf24ba74f9aa5682\mupdf.tgz
      PyMuPDF/setup.py: mupdf_local='mupdf-1.21.0-source/'
      PyMuPDF/setup.py: Building mupdf.
      PyMuPDF/setup.py: Cannot find devenv.com in default locations, using: 'devenv.com'
      PyMuPDF/setup.py: Building MuPDF by running: cd mupdf-1.21.0-source/&&"devenv.com" platform/win32/mupdf.sln /Build "ReleaseTesseract|x64" /Project mupdf
      '"devenv.com"' is not recognized as an internal or external command,
      operable program or batch file.
      Traceback (most recent call last):
        File "C:\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\wolf_\AppData\Local\Temp\pip-build-env-3gsfkqtb\overlay\lib\python3.10\site-packages\setuptools\build_meta.py", line 412, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\wolf_\AppData\Local\Temp\pip-build-env-3gsfkqtb\overlay\lib\python3.10\site-packages\setuptools\build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\wolf_\AppData\Local\Temp\pip-build-env-3gsfkqtb\overlay\lib\python3.10\site-packages\setuptools\build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\wolf_\AppData\Local\Temp\pip-build-env-3gsfkqtb\overlay\lib\python3.10\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 625, in <module>
        File "C:\msys64\mingw64\lib\python3.10\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'cd mupdf-1.21.0-source/&&"devenv.com" platform/win32/mupdf.sln /Build "ReleaseTesseract|x64" /Project mupdf' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymupdf
Failed to build pymupdf
ERROR: Could not build wheels for pymupdf, which is required to install pyproject.toml-based projects`

**Comment by julian-smith-artifex-com** [comment]
It looks like the available Windows wheels are not suitable for your system, presumably because your python is from Chocolatey, which doesn't seem to work with normal Python packaging. So pip is attempting to build PyMuPDF from the sdist (source distribution).

This needs Visual Studio, but it looks like this is not installed on your system (in which case you need to install it), or at least is not installed in a location known to setup.py (in which case you should set environmental variable `PYMUPDF_SETUP_DEVENV` to point to the `devenv.com` binary).

In addition you will need to install SWIG - see https://pymupdf.readthedocs.io/en/latest/installation.html for details.

I hope that makes sense.

**Comment by texbowman** [comment]
I uninstall python from Chocolatey, and reinstall it using conventional binary version. Problem solved! Thank you!.

**Comment by julian-smith-artifex-com** [comment]
This issue is documented in PyMuPDF-1.21.1.
