### ISSUE TITLE
Cannot insert_image into pdf

### ISSUE THREAD

**Issue by chrisjd20** [pymupdf/PyMuPDF#2050]
I'm trying to insert an image with a width of 250 and height of 28 at the x coodinate 200 and y coordinate 400 using:

``` python
            rect = fitz.Rect( (200.0, 400.0), (250.0, 28.0) )
            page.insert_image(
                rect,                  # where to place the image (rect-like)
                filename="../default_images/logo.png",         # image in a file
                mask=None,
                rotate=0,
                xref=0,
                oc=0, 
                keep_proportion=True,
                overlay=True,
            )
```

I also tried making the rec using `rect = fitz.Rect( 200.0, 200.0, 250.0, 28.0 )` but got the same effect. I also tried `rect.normalize()` which prevents the errors but then the wrong values end up in the wrong place and the image ends up in totally unexpected places/sizes. 

Problem is, I keep getting `ValueError: rect must be finite and not empty` or sometimes it works if I shift the rect values but then it ends up in a place and size I have no clue how it got that. What am I doing wrong / misunderstanding or what's broken?

My config:

```
 - Ubuntu 20.04 5.15.0-52-generic
3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] 
 linux 
 
PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
Version date: 2022-08-13 00:00:01.
Built for Python 3.8 on linux (64-bit).
```

**Comment by chrisjd20** [comment]
Ok I dont know why but I was able to get this to work using 

``` python
            rect = page.bound()
            rect += [430, 730, -90, -45]
```

Gave me something I could understand enough to position it.

**Comment by julian-smith-artifex-com** [comment]
Glad you have things working. A couple of thoughts, feel free to ignore:

I think rects need to have the second pair of `(x, y)` values greater than the first pair. So your first example, `rect = fitz.Rect( (200.0, 400.0), (250.0, 28.0) )`, is an empty rect because 28.0 is less than 400.0.

In your second example, you could maybe print out the modified rect with `print(rect)` so you can see the values directly.
