### ISSUE TITLE
Widget field name is concatenated instead of replaced

### ISSUE THREAD

**Issue by mghenderson** [pymupdf/PyMuPDF#2058]
## Describe the bug (mandatory)
When attempting to replace field name for widgets, it concatenates the new value instead of replacing original value.  Is this truly a bug or am I missing something about the save command?

## To Reproduce (mandatory)
```python
import fitz
test_val = 0
doc = fitz.open("input.pdf")
    for page in doc:
        for field in page.widgets():
           new_field_name = f"{page.number:0>2d} {test_val}"
           field.field_name = new_field_name
           field.update()
           test_val += 1
doc.save("output.pdf")
```

## Expected behavior (optional)
Expected field names would be something like "00 01" instead is "record name.00 01"

## Your configuration (mandatory)
Windows 10 (64bit)
Python 3.11.0
PyMuPDF version 1.21.0 installed via pip

**Comment by JorjMcKie** [comment]
This probably is not a bug. The field in your case is a subfield of another one - "record name".
Renaming it **_must not_** destroy this relationship.
The question is what that field's old name looked like.

**Comment by mghenderson** [comment]
Following the example, the original field was named "record name"

**Comment by JorjMcKie** [comment]
Here is an example session which shows that things work in standard situations:
```python
import fitz
doc=fitz.open("widgettest.pdf")
page=doc[0]
w=page.first_widget
w
'Text' widget on page 0 of widgettest.pdf
w.field_name
'Textfield-1'
w.field_name = "changed"
w.field_name
'changed'
w.update()
doc.ez_save("x.pdf")
doc=fitz.open("x.pdf")
page=doc[0]
w=page.first_widget
w
'Text' widget on page 0 of x.pdf
w.field_name
'changed'
```
So the form fields in your PDF are configured in a more complex way, which is not (yet) supported.
A detailed analysis of the file may reveal what actually happens.
But I re-iterate that it is no bug.
