### ISSUE TITLE
trouble with annotation set_rect 

### ISSUE THREAD

**Issue by PCarle** [pymupdf/PyMuPDF#2073]
_**Please provide all mandatory information!**_

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by julian-smith-artifex-com** [comment]
This issue appears to have no information other than the title...?
