### ISSUE TITLE
Small and inversely-ordered bboxes in some PDFs

### ISSUE THREAD

**Issue by joaquimcampos** [pymupdf/PyMuPDF#2082]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
In a lot of PDFs the bounding boxes are very small and their order appears to be inverted.
The numbers for the bboxes seem normal, though.

## To Reproduce (mandatory)
To reproduce, run the following code on the following PDFs:
[sample1.pdf](https://github.com/pymupdf/PyMuPDF/files/10076943/sample1.pdf)
[sample2.pdf](https://github.com/pymupdf/PyMuPDF/files/10076948/sample2.pdf)
[sample3.pdf](https://github.com/pymupdf/PyMuPDF/files/10076950/sample3.pdf)
[sample4.pdf](https://github.com/pymupdf/PyMuPDF/files/10076951/sample4.pdf)
[sample5.pdf](https://github.com/pymupdf/PyMuPDF/files/10076952/sample5.pdf)

```
#!/usr/bin/python3

import os
import click
import fitz
from fitz.utils import getColor


def main(pdf_file, out_dir):
    doc = fitz.Document(pdf_file)
    page = doc.load_page(0)

    out_doc = fitz.Document()
    out_doc.insert_pdf(doc, to_page=0)
    out_page = out_doc[0]
    textpage = page.get_textpage()
    pymu_dict = textpage.extractDICT(sort=True)
    for block in pymu_dict['blocks']:
        out_page.draw_rect(block['bbox'], color=getColor('blue'), width=1.5)

    out_path = os.path.join(out_dir, 'blocks.pdf')
    out_doc.save(out_path)
    print(f'Blocks saved in "{out_path}".')


def validate_pdf_file(ctx, param, path):
    if not os.path.isfile(path):
        raise click.BadParameter(f"Path {path} is not a file.")
    if not path.endswith('.pdf'):
        raise click.BadParameter("File should have a .pdf format.")

    return path


@click.argument('pdf-file',
                callback=validate_pdf_file,
                type=click.Path())
@click.option('--out-dir',
              type=click.Path(exists=True),
              default='.')
@click.command()
def cli(pdf_file, out_dir):
    main(pdf_file, out_dir)


if __name__ == "__main__":
    cli()
```

## Screenshots (optional)
![Screenshot from 2022-11-23 15-36-48](https://user-images.githubusercontent.com/26142730/203591332-4829a635-c194-420e-881e-c4da64c73663.png)
![Screenshot from 2022-11-23 15-36-13](https://user-images.githubusercontent.com/26142730/203591356-b7ade01d-4bf4-4006-bf2c-55f4599ccc3c.png)

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).
```
>>> print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0] 
 linux 
 
PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
Version date: 2022-08-13 00:00:01.
Built for Python 3.11 on linux (64-bit).
```
Installed with ``pip install pymupdf``

## Additional context (optional)
It's possible that it is not an issue with PyMuPDF but with these pdfs...

**Comment by JorjMcKie** [comment]
Have you made sure that this is **_not caused_** by [this](https://pymupdf.readthedocs.io/en/latest/recipes-common-issues-and-their-solutions.html#misplaced-item-insertions-on-pdf-pages) problem?

Presumably you haven't, so best try this:

* after loading a page, immediately execute `page.clean_contents()`.

If the problem persists, please drop me a note.

**Comment by JorjMcKie** [comment]
@joaquimcampos - how are you doing?

**Comment by joaquimcampos** [comment]
Thank you for your suggestion @JorjMcKie. That was indeed the problem! I think you can close this.

**Comment by JorjMcKie** [comment]
Glad you have the solution.
