### ISSUE TITLE
PyMuPDF blocks other threads

### ISSUE THREAD

**Issue by Aran-Fey** [pymupdf/PyMuPDF#2092]
## Describe the bug (mandatory)
While PyMuPDF is doing something, it prevents other threads from running. Presumably, it doesn't release the GIL.

## To Reproduce (mandatory)
Simply use PyMuPDF in a multi-threaded program. Here's an example:

```python
import fitz, itertools, time, threading

def do_stuff_with_fitz():
    pdf_file = fitz.open('foo.pdf')
    
    for page in pdf_file:
        for img in page.get_images():
            xref = img[0]
            image = pdf_file.extract_image(xref)

threading.Thread(target=do_stuff_with_fitz).start()

for n in itertools.count():
    print(n, end='\r', flush=True)
    time.sleep(0.01)
```

You'll observe that the counter will barely increase until the pdf file has been processed.

## Your configuration (mandatory)
 - Windows 10, 64 bit
 - Python 3.10.0, 64 bit
 - PyMuPDF version 1.20.2, installed with pip

**Comment by JorjMcKie** [comment]
This works as designed and is no bug - see documentation: https://pymupdf.readthedocs.io/en/latest/recipes-multiprocessing.html.
