### ISSUE TITLE
Image in pdf changes color after applying redactions

### ISSUE THREAD

**Issue by ot-ksrinivasan** [pymupdf/PyMuPDF#2093]
## Description
Image in a PDF file changes color after applying redactions.

## To Reproduce 
Execute the following python script to reproduce the issue. The script uses this pdf file [image_issue.pdf](https://github.com/pymupdf/PyMuPDF/files/10120494/image_issue.pdf) .
```
import os
import fitz

script_path = os.path.abspath(__file__)
script_folder = os.path.dirname(script_path)
doc = fitz.open(os.path.join(script_folder, 'image_issue.pdf'))

page = doc.load_page(0)

rx=135.123
ry=123.56878
rw=69.8409
rh=9.46397

x0 = rx
y0 = ry
x1 = rx + rw
y1 = ry + rh
    
rect = fitz.Rect(x0, y0, x1, y1)

font = fitz.Font("Helvetica")
fill_color=(0,0,0)
page.add_redact_annot(
    quad=rect,
    #text="null",
    fontname=font.name,
    fontsize=12,
    align=fitz.TEXT_ALIGN_CENTER,
    fill=fill_color,
    text_color=(1,1,1),
)

page.apply_redactions()

doc.save(os.path.join(script_folder, 'image_issue_redacted.pdf'))
```
Note that I am using the default images=2 (blank out overlapping image parts) when calling apply_redactions(). Using images= 0 (ignore) or images=1(remove complete overlapping image) are not desirable for my use case.

## Expected behavior
The color of the image in the pdf file should not change after applying redactions.

## Screenshots
Here's a screenshot of the problem.
![image](https://user-images.githubusercontent.com/95709530/204731301-9b291bcd-a6a1-4e47-aae3-0fc21fba000c.png)

## Your configuration 
 - Operating system Ubuntu 22.04.1 LTS
 - Python version 3.8.14
 - PyMuPDF version 1.20.2

**Comment by JorjMcKie** [comment]
The problem here is that your page is fully covered by two images.
So if your redaction rectangles intersect image bboxes, the respective images will **_always_** be changed if you let the `.apply_redactions()` parameter default to `images=fitz.PDF_REDACT_IMAGE_PIXELS`.
Specify `page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)` and you are fine.

**Comment by ot-ksrinivasan** [comment]
> The problem here is that your page is fully covered by two images. So if your redaction rectangles intersect image bboxes, the respective images will **_always_** be changed if you let the `.apply_redactions()` parameter default to `images=fitz.PDF_REDACT_IMAGE_PIXELS`. Specify `page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)` and you are fine.

@JorjMcKie , Thank you for your response. As I mentioned in the description, 
`Note that I am using the default images=2 (blank out overlapping image parts) when calling apply_redactions(). Using images= 0 (ignore) or images=1(remove complete overlapping image) are not desirable for my use case.`

As I understand, if we set images=0 `page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)` then the image pixels that need to be redacted won't be removed and that is not an effective redaction right? if the box is removed, we will still see the text on the image right?

**Comment by JorjMcKie** [comment]
Got you now.
Situation was blurred by the fact that your redact rectangle was inside a black drawing and hence remained invisible whatsoever.
This is an upstream error (MuPDF): the 2 large images have transparency masks that are incorrectly handled, leading to white background where it has been black before.
I will try to make a reproducer program and submit an issue in MuPDF's bug system ... using example file: ok with you?

**Comment by ot-ksrinivasan** [comment]
> Got you now. Situation was blurred by the fact that your redact rectangle was inside a black drawing and hence remained invisible whatsoever. This is an upstream error (MuPDF): the 2 large images have transparency masks that are incorrectly handled, leading to white background where it has been black before. I will try to make a reproducer program and submit an issue in MuPDF's bug system ... using example file: ok with you?

Sure. You can use my pdf file to file a bug with mupdf.

**Comment by JorjMcKie** [comment]
@ot-ksrinivasan - May I use your example file and submit it to MuPDF's bug system?

**Comment by julian-smith-artifex-com** [comment]
The underlying MuPDF bug has been fixed: https://bugs.ghostscript.com/show_bug.cgi?id=706114
