### ISSUE TITLE
Redaction removing more text than expected

### ISSUE THREAD

**Issue by seb-bau** [pymupdf/PyMuPDF#2108]
## Describe the bug (mandatory)
When applying a redaction on a document, the following word is removed as well.

## To Reproduce (mandatory)
Example PDF file: [test_doc.pdf](https://github.com/pymupdf/PyMuPDF/files/10177152/test_doc.pdf)

Run this script:

```
import fitz
doc = fitz.open("test_doc.pdf")
page = doc[0]
areas = page.search_for("{sig}")
rect = areas[0]
page.add_redact_annot(rect)
page.apply_redactions()
doc.saveIncr()
doc.close()
```
The searched word "{sig}" is removed (as expected).
The word "Vertrag" on the top right is removed as well (unexpected).

## Expected behavior (optional)
Searched string should be removed. No other change should be made.

## Screenshots (optional)
Before script:
![grafik](https://user-images.githubusercontent.com/1752429/206213147-127a1593-e792-46a1-8261-1a3f730bad6d.png)
After script:
![grafik](https://user-images.githubusercontent.com/1752429/206213421-5b051785-4801-447e-894e-2ece2bce233a.png)

## Your configuration (mandatory)
 - OS independant, happening on Windows 11 as well as Debian 11
 - Python Python 3.10.8
 - PyMuPDF 1.21.0, installed via pip

Thank you!

**Comment by JorjMcKie** [comment]
Thank you for the well-prepared report.
I reproduced the error, confirming your observation.
This error occurs in the base library. I determined you have provided a neutral test file, so I am assuming your are ok with forwarding it to MuPDF's issue system.
Once I have an issue number from there, I will post it in this thread.

**Comment by seb-bau** [comment]
Sure, the file can be forwarded.
Thank you for the fast response!

**Comment by JorjMcKie** [comment]
This is the issue on bugzilla: https://bugs.ghostscript.com/show_bug.cgi?id=706147

**Comment by JorjMcKie** [comment]
Just received note from the MuPDF friends confirming that the bug has been resolved, so this should be fixed in coming version.
