### ISSUE TITLE
Some scan pdfs' text is wrong, i think the text is gotten from ocr, so how can l get the original background image?

### ISSUE THREAD

**Issue by njustczr** [pymupdf/PyMuPDF#2130]

**Comment by JorjMcKie** [comment]
This has no description at all.
The title suggests you may have wanted to ask a question in "Discussions".
If so, please open a post there - and with sufficient background please.

**Comment by njustczr** [comment]
> This has no description at all. The title suggests you may have wanted to ask a question in "Discussions". If so, please open a post there - and with sufficient background please.

the pdf is 
![image](https://user-images.githubusercontent.com/30426320/208062995-8b63ef53-8dca-4d93-a4b2-0a448481ced7.png)
but i copy the text is "第丸章 肘足虫"  
the text is gotten by OCR, so if i can get the scan background image
