### ISSUE TITLE
Page.draw_***() does not work correct on pdf which is outcome of (Microsoft) Printing to PDF

### ISSUE THREAD

**Issue by Randallzoeng** [pymupdf/PyMuPDF#2131]
## Page.draw_***() does not work correct on pdf which is  outcome of (Microsoft) Printing to PDF
I was trying to cover the page header in red, when I found this issue.

## To Reproduce (mandatory)
attached ipynb to help reproduce the error.
_FS_indesign_page_01.pdf_ is original file created by Adobe inDesign.
_FS_indesign_ptp_page_01.pdf_ is pdf output after using "Printing to PDF" function 
[🐛debug_hide_page_header.zip](https://github.com/pymupdf/PyMuPDF/files/10243679/debug_hide_page_header.zip)
[FS_indesign_page_01.pdf](https://github.com/pymupdf/PyMuPDF/files/10243687/FS_indesign_page_01.pdf)
[FS_indesign_ptp_page_01.pdf](https://github.com/pymupdf/PyMuPDF/files/10243688/FS_indesign_ptp_page_01.pdf)

when I changed overlay=False, the image locate the right place, but this is awkward since overlay shouldn't change where image is locate, just whether or not shape/image is overlay that rect, right?

## Expected behavior (optional)
I expect returns the same output since all the parameters are the same, see Screenshots. 1st image would be expected, yet for pdf (print to pdf version) it returns 2nd image, the black image is not inserted in the correct place.

## Screenshots (optional)
![download_0](https://user-images.githubusercontent.com/29625093/208050267-2bf1659e-9035-4557-82bb-3d421351b7c9.png)
![download_1](https://user-images.githubusercontent.com/29625093/208050283-282c68df-8956-4e8f-9986-ab1d24271792.png)

![download_original](https://user-images.githubusercontent.com/29625093/208051237-68b97736-0d0b-42b8-8183-99fa8b6ace62.png)

## Your configuration (mandatory)
 - Windows 10 Enterprise
 - Python 3.7.0
 - PyMuPDF==1.20.2

## Additional context (optional)
Some searching I did, 
according to this [link](https://access.trade.gov/help/PDF_Cheat_Sheet_External_DC.pdf)
I guess it may not necessarily be the bug with PyMuPDF, but hope you will find this helpful to help you mitigate the issue.
Important Note: Use the Print to PDF function only once per document. We have noticed that when
the Adobe printer driver is used more than once on the same document, the text in the PDF is no
longer text searchable (i.e., no longer OCR’d). When a PDF file is created from MS Word using
Print to PDF option, do not use PDF file to create another version of the file using Print to PDF.
Always use the original MS Word file to make updates.

I also did some experiment on both file to Page.get_text(). For print to pdf version, it failed to extract page header content ("(Client) Elite ....")

**Comment by JorjMcKie** [comment]
This is no bug: for an explanation and the (simple) solution consult [this](https://pymupdf.readthedocs.io/en/latest/recipes-common-issues-and-their-solutions.html#misplaced-item-insertions-on-pdf-pages) section of the documentation.

**Comment by JorjMcKie** [comment]
I determined that your PDF has the problem as described.
So I am going to close this issues. Please feel free to reopen if other problems occur - or open a "Discussions" items.
