### ISSUE TITLE
Failed to read JPX header when trying to get blocks

### ISSUE THREAD

**Issue by johnidm** [pymupdf/PyMuPDF#2141]
### Describe the bug (mandatory)

When I'm trying to get blocks from some pdfs, the following error occurs: `RuntimeError: Failed to read JPX header`. The same error occurs when I'm trying to get the pixmap with the function `get_pixmap`.

It works if I use `page.gettext()` without `block` or `dict` parameter.

PDFs with this error have the following attributes:
- Producer: GPL Ghostscript 9.23
- PDF Version: 1.5

If I edit the PDF file with any online tool, for example https://www.sejda.com/pdf-editor, the attributes change and the error disappears.

### To Reproduce (mandatory)

PDF file - [test_get_blocks.pdf](https://github.com/pymupdf/PyMuPDF/files/10262924/test_get_blocks.pdf)

```
import fitz

with fitz.open("test_get_blocks.pdf") as doc:
    for page in doc:
        print(page.get_text("blocks"))
```

Traceback

```
Traceback (most recent call last):
  File "/home/johni/Projects/pdf-to-txt/main.py", line 5, in <module>
    print(page.get_text("dict"))
  File "/home/johni/.pyenv/versions/3.9.15/lib/python3.9/site-packages/fitz/utils.py", line 808, in get_text
    tp = page.get_textpage(clip=clip, flags=flags)
  File "/home/johni/.pyenv/versions/3.9.15/lib/python3.9/site-packages/fitz/fitz.py", line 5675, in get_textpage
    textpage = self._get_textpage(clip, flags=flags, matrix=matrix)
  File "/home/johni/.pyenv/versions/3.9.15/lib/python3.9/site-packages/fitz/fitz.py", line 5661, in _get_textpage
    val = _fitz.Page__get_textpage(self, clip, flags, matrix)
RuntimeError: Failed to read JPX header
```

[Notebook to reproduce the error](https://colab.research.google.com/drive/1VL741eghCX31_5EUphhgPmWC3xbdMznV?usp=sharing)

### Your configuration (mandatory)
- Operating system Ubuntu 22.04.1 LTS
- Python version 3.9.15
- PyMuPDF version 1.21.1

**Comment by johnidm** [comment]
@JorjMcKie thanks for you replay.

Of course, feel free to report a bug and use the example file. 

I'm not familiar with how to report a bug in Ghostscript.

**Comment by JorjMcKie** [comment]
This is the corresponding bugzilla bug item: https://bugs.ghostscript.com/show_bug.cgi?id=706245

**Comment by johnidm** [comment]
Thanks for your support @JorjMcKie
