### ISSUE TITLE
wrong coordinates are provided for a text detection in a rotated pdf

### ISSUE THREAD

**Issue by MallRoy** [pymupdf/PyMuPDF#2145]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I am trying to find the coordinates in a PDF [differentdegreepages.pdf](https://github.com/pymupdf/PyMuPDF/files/10284037/differentdegreepages.pdf)  by doing a text search. The PDF which i have used is having different angles. So when i apply the derotation matrix the coordinates are wrongly provided 
[oriented.pdf](https://github.com/pymupdf/PyMuPDF/files/10284040/oriented.pdf).
## To Reproduce (mandatory)
```
import fitz

with fitz.open("differentdegreepages.pdf") as document:
    for page_number, page in enumerate(document):
        words = page.get_text("words", sort=True)
        for word in enumerate(words):
            if "90" in word[1]:
                page = document[page_number]
                rect = fitz.Rect(
                    [word[1][0], word[1][1], word[1][2], word[1][3]])
                rect = rect * page.derotation_matrix
                page.draw_rect(rect, fill=(1, 0, 0))
            if "degree" in word[1]:
                page = document[page_number]
                rect = fitz.Rect(
                    [word[1][0], word[1][1], word[1][2], word[1][3]])
                rect = rect * page.derotation_matrix
                page.draw_rect(rect, fill=(1, 0, 0))
    document.save("oriented.pdf", garbage=3, deflate=True)
    print("completed")
```
For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

## Expected behavior (optional)
The rectangle should be drawn exactly on the words which i have provided.

## Your configuration (mandatory)
 - Operating system, potentially version and bitness: windows 10
 - Python version, bitness : 3.9
 - PyMuPDF version, installation method (**wheel** or **generated** from source). 1.20.2

**Comment by JorjMcKie** [comment]
As stated in the documentation: all coordinates extracted pertain to the **_unrotated_** page and if you insert anything you must again provide unrotated coordinates!
If your script looks something like this, you will see that you have no burden here:
```python
import fitz

doc = fitz.open("differentdegreepages.pdf")
for page in doc:
    page.clean_contents()  # deal with messed up geometry
    for w in page.get_text("words", sort=True):
        page.draw_rect(w[:4], color=(1, 0, 0), width=0.3)
doc.ez_save(__file__.replace(".py", ".pdf"))
```
All words on all pages will be nicely wrapped in red rectangles ... like Christmas presents.

> `page.clean_contents()` is needed because the PDF creator decided to set a trap for us.
