### ISSUE TITLE
Support adding images as pages directly

### ISSUE THREAD

**Issue by nabilanavab** [pymupdf/PyMuPDF#2161]
Hey, I have noticed that the current program does not allow for adding pages directly without first initializing(new_page) and adding an image with a rect(img.rect). Is it possible to modify the program so that pages can be added directly without specifying the image width and height ?
This would be a useful feature for those who need to quickly add multiple images to a PDF file. Thank you for considering this request.
<br/>

```py
import fitz

with fitz.open() as doc:
    for img in imgList:
        with fitz.open(img) as hdIMG:
            rect = hdIMG[0].rect
            pdfbytes = hdIMG.convert_to_pdf()
            imgPDF = fitz.open("pdf", pdfbytes)
            page = doc.new_page(width=rect.width, height=rect.height)
            page.show_pdf_page(rect, imgPDF, 0)
    doc.save(filePath, deflate_images=True)
```
As it stands now, it looks like this [fitz/pymupdf]
<br/>

```py
from PyPDF2 import PdfWriter

writer = PdfWriter()
for img in imgList:
    writer.add_page(img)
```
Can you please do it like this?
<br/>
<h3>Your program is truly impressive, and I am grateful for all the effort you put into it.</h3>

**Comment by JorjMcKie** [comment]
Thank you for for your nice acknowledgement!

As per your request:
You already now can at least do this much simpler thing:
```python
for img in imglist:
    # 1. open image as fitz.Document and convert it to a PDF in memory
    imgpdf = fitz.open(imagefile).convert_to_pdf()
    # 2. append memory PDF as a page
    doc.insert_pdf(fitz.open("pdf", imgpdf))
```
So your request amounts to combining these two lines into a new method `doc.append_image(imagefile)`.

**Comment by JorjMcKie** [comment]
BTW I tried to reproduce your pypdf2 code with this script:
```python
from PyPDF2 import PdfWriter
import time, os

imgList = os.listdir()
t0 = time.perf_counter()
writer = PdfWriter()
for img in imgList:
    if not img.endswith(".jpg"):
        continue
    writer.append(img)  # or .add_page()
t1 = time.perf_counter()
print(f"pypdf2 time {t1-t0}")
```
Doesn't work, exception `PyPDF2.errors.PdfReadError: EOF marker not found`.
Same thing happens when using `.add_page()`.
So something extra has to happend before it works, right?

**Comment by nabilanavab** [comment]
Adding images from a local path does require some additional steps, but it's much easier to do so when loading from a PDF(.add_page() and helps in splitting pdfs). I'd also like to request that this feature be added in images as well as in pdf loading..

**Comment by nabilanavab** [comment]
adding 

```py
doc.append_image(img_path)
```

It will be highly beneficial and exactly what i need. ♥

**Comment by JorjMcKie** [comment]
> I'd also like to request that this feature be added in images as well as in pdf loading.

Not sure what you mean here.

**Comment by nabilanavab** [comment]
Thank you for your response. I was looking for a way to split PDF files, and I found a better solution in your library. Your library is very helpful

![image](https://user-images.githubusercontent.com/53673312/211413422-ee774222-7a9e-4712-b9e2-2f98a79754f4.png)
This is an awesome way
