### ISSUE TITLE
Unable to compile under `llvm`

### ISSUE THREAD

**Issue by Iey4iej3** [pymupdf/PyMuPDF#2164]
## Describe the bug (mandatory)
The linkage of PyMuPDF fails, seemingly because of `llvm`.

## To Reproduce (mandatory)

Under an environment which linker is supplied by `llvm`: install python, then install PyMuPDF via `pip`.

The linkage failed with the following message:

```
mkdir -p build/pymupdf-aarch64-release/resources/fonts/urw/ ; ld -r -b binary -z noexecstack -o build/pymupdf-aarch64-release/resources/fonts/urw/Dingbats.cff.o resources/fonts/urw/Dingbats.cff
ld: error: target emulation unknown: -m or at least one .o file required
```

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
   Termux under Android 12
 - Python version, bitness
   3.11.1 (main, Dec 7 2022, 05:56:18) [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0
 

## Additional context (optional)

Probably related: https://github.com/brummer10/GxPlugins.lv2/issues/9

**Comment by julian-smith-artifex-com** [comment]
This looks like the build of MuPDF is failing.

I suspect building MuPDF on termux is not supported at the moment; will try to find out more in the next few days.

**Comment by Iey4iej3** [comment]
What? This is building `PyMuPDF`, not `MuPDF`. Building `MuPDF` is [supported](https://github.com/termux/termux-packages/blob/master/packages/mupdf/build.sh) and even a package is available out of box.

This particular message indicates that the error is precisely about the difference between the arguments of the `gcc` linker and the `llvm` linker, as explained in https://github.com/brummer10/GxPlugins.lv2/issues/9#issuecomment-431634711

I guess that it is not difficult to set up the configuration system to differentiate the arguments for `gcc` and `llvm` when they are not compatible.

**Comment by julian-smith-artifex-com** [comment]
> What? This is building `PyMuPDF`, not `MuPDF`.

When PyMuPDF builds, it first downloads MuPDF and builds it locally. Then it compiles PyMuPDF (using SWIG etc) and links with the MuPDF it built earlier to create the final `_fitz.so` file.

The output

```
mkdir -p build/pymupdf-aarch64-release/resources/fonts/urw/ ; ld -r -b binary -z noexecstack -o build/pymupdf-aarch64-release/resources/fonts/urw/Dingbats.cff.o resources/fonts/urw/Dingbats.cff
ld: error: target emulation unknown: -m or at least one .o file required
```

is from building MuPDF.


> Building `MuPDF` is [supported](https://github.com/termux/termux-packages/blob/master/packages/mupdf/build.sh) and even a package is available out of box.

That `build.sh` file is not part of standard MuPDF releases so it's not really correct to say that that Termux is "supported" by MuPDF.

> 
> This particular message indicates that the error is precisely about the difference between the arguments of the `gcc` linker and the `llvm` linker, as explained in [brummer10/GxPlugins.lv2#9 (comment)](https://github.com/brummer10/GxPlugins.lv2/issues/9#issuecomment-431634711)
> 
> I guess that it is not difficult to set up the configuration system to differentiate the arguments for `gcc` and `llvm` when they are not compatible.

It's likely that MuPDF's build system could be extended to to work on Termux. This would be a prerequisite for enabling PyMuPDF to build on Termux.

**Comment by julian-smith-artifex-com** [comment]
Closing this now as no response for a while.

**Comment by julian-smith-artifex-com** [comment]
Closing this, as requires MuPDF to support Termux which isn't likely at the moment.
