### ISSUE TITLE
`not a dict (null)` when inserting a pdf in a new/empty one

### ISSUE THREAD

**Issue by yan-hic** [pymupdf/PyMuPDF#2170]
Experienced the error in topic on a few pdfs when trying to merge with other pdfs.
TB:
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\ye\AppData\Local\Programs\Python\Python311\Lib\site-packages\fitz\fitz.py", line 4608, in insert_pdf
    val = _fitz.Document_insert_pdf(self, docsrc, from_page, to_page, start_at, rotate, links, annots, show_progress, final, _gmap)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: not a dict (null)

```

Any param or attributes I can check (can't attach the pdf as confidential) ? I wonder what is type-checked for dict...

**Comment by yan-hic** [comment]
If that helps, here the runtime values as of the call of insert_pdf:
![image](https://user-images.githubusercontent.com/25224265/211885771-731c27e6-f85c-4e72-a5bf-6f54e3229243.png)

**Comment by JorjMcKie** [comment]
Thanks for the information!
This error message does not refer to Python, but to PDF dictionaries. Your input PDF is damaged.
Unfortunately for PDF (i.e., not MuPDF problem), not all damages can be detected on open, although some can - and some even can be successfully repaired.

You could make a new temporary, repaired PDF in memory, and use that one for the inserts.
If this approach leads to an exception, then you know that that guy must be skipped.
Something along this snippet:
```python
src = fitz.open("input.pdf")
try:
    pdfbytes = src.tobytes(garbage=4,deflate=True)  # should force MuPDF to access each PDF object
except:
    # skip this bastard
src.close()
src = fitz.open("pdf", pdfbytes) # open input.pdf again from cleaned memory version
# do what must be done with inout.pdf
```

**Comment by yan-hic** [comment]
Thx Jorj. Unfortunately the `tobytes()` trick didn't help, even with other params I used elsewhere: `garbage=1, linear=True, clean=True, deflate=True`. Note that the issue is not opening the pdf as my snippet is
```
...
with fitz.open('pdf', content) as attachment_pdf:
    merged_pdf.insert_pdf(attachment_pdf)
...
```
... and error is raised when inserting, not the first open - that's the `docsrc` in the screenshot. I can also open the pdf just fine in acrobat and chrome. Seems the issue is really with the insertion.

But as noted, I will skip this one for now. May give a shot with another lib later. Would also report back with a redacted pdf if I can reproduce with it.

**Comment by JorjMcKie** [comment]
You have to restructure your script of course. And as I said: the error may indeed not be detected during open - independent from the tool you use for open.
You must force MuPDF to read it through in its entirety - every object should be accessed, so that the problem has a chance to be detected.
Only after this has happened repopen for normal processing.
```python
with fitz.open("pdf", content) as attachment_pdf:
    content2 = attachment_pdf.tobytes(garbage=4,deflate=True)
with fitz.open("pdf", content2) as attachment_pdf:
    ...
```

**Comment by yan-hic** [comment]
Sorry for the confusion - of course I changed the code but just wanted to reference the original snippet where it didn't raise at opening. I understand that at that time, it didn't consume the content yet. See the snippet I have now and again, for that particular pdf, same error


```
with fitz.open('pdf', content) as attachment_pdf:
    try: # todo: bug - https://github.com/pymupdf/PyMuPDF/issues/2170
        pdfbytes = attachment_pdf.tobytes(garbage=4, deflate=True)
        with fitz.open('pdf', pdfbytes) as attachment_pdf2:
            merged_pdf.insert_pdf(attachment_pdf2)
    except RuntimeError:
        print_log(msg := "Can't insert pdf", severity="ERROR")
        return msg
```
