### ISSUE TITLE
JBIG2Decode required

### ISSUE THREAD

**Issue by wizardforcel** [pymupdf/PyMuPDF#2183]
When saving B&W images, `*.jb2` is much smaller than `*.png`。

I found that PDF also support this format via `JBIG2Decode` , so as for B&W images, it's better to save in this format.

**Comment by JorjMcKie** [comment]
You are not forced to use PNG. For other output formats we have seamlessly integrated calling Pillow into the save options of `Pixmap`.
Simply use `pix.pil_save(<PIL save options>)` and you will be able to use whatever the Pillow package offers you.

**Comment by wizardforcel** [comment]
but i cannot choose to encode into jbig2. It's always deflate

**Comment by JorjMcKie** [comment]
> but i cannot choose to encode into jbig2. It's always deflate

True, but this capability would have to be offered by MuPDF, PyMuPDF can only wrap its features - and potentially those of a selected few of other packagaes, as we do with the most popular one, Pillow.

So if you see this need, you should submit a request to MuPDF. Try the Discord channel [#mupdf](https://discord.gg/FzbefhFrMR).
