### ISSUE TITLE
AttributeError: 'Document' object has no attribute 'pageCount'

### ISSUE THREAD

**Issue by giri-ggr** [pymupdf/PyMuPDF#2186]
AttributeError                            Traceback (most recent call last)
[<ipython-input-49-6d8ea6bc610c>](https://localhost:8080/#) in <module>
      8 #ocr = PaddleOCR(lang="en")  # need to run only once to download and load model into memory
      9 img_path ='/content/sample.pdf'
---> 10 result = ocr.ocr(img_path, cls=True)
     11 for idx in range(len(result)):
     12     res = result[idx]

2 frames
[/usr/local/lib/python3.8/dist-packages/paddleocr/ppocr/utils/utility.py](https://localhost:8080/#) in check_and_read(img_path)
     94         from PIL import Image
     95         imgs = []
---> 96         with fitz.open(img_path) as pdf:
     97             for pg in range(0, pdf.pageCount):
     98                 page = pdf[pg]

AttributeError: 'Document' object has no attribute 'pageCount'
***********
Training Environment.
***********************
1.Google Colab CUDA Version: 11.2 
2.python 3.8
3.paddleclas   2.5.1
4.paddleocr   2.6.1.2
5.paddlepaddle  2.4.1
6.paddlepaddle-gpu  2.1.3.post112

**Comment by JorjMcKie** [comment]
You are using a property that has been deprecated since June 2021 (v1.18.14) and was removed in June 2022 (v1.20.0).
Use `Document.page_count` instead.
