### ISSUE TITLE
I have trouble with bbox position and font size

### ISSUE THREAD

**Issue by DonSudak** [pymupdf/PyMuPDF#2190]
Hi everyone 
I have trouble with bbox position and font size
When im trying to insert text box into pdf page with font size more than 20 there are offset by Y axis

## Your configuration (mandatory)
 - arch linux
 - Python 3.10.9
 -  PyMuPDF 1.21.1 from pip

**Comment by JorjMcKie** [comment]
This a typical "Discussions" post, so let me first transfer it to there.
