### ISSUE TITLE
'SwigPyObject' object has no attribute 'thisown' when deleting annotations

### ISSUE THREAD

**Issue by jack6th** [pymupdf/PyMuPDF#2209]
OS: MinGW32 PyMuPDF v1.21.1 on Windows 7 SP1 32bit

When I try to delete all annotations of a document, the interpreter will abnormally terminate after some successfully page annotation deletions (around 10 it seems). Here is the code

```
import fitz
doc = fitz.open("in.pdf")
for idx, page in enumerate(doc.pages()):
    print(idx)
    for annot in page.annots():
        page.delete_annot(annot)
doc.save("out.pdf")
```
output: (xxxx is the masked path)
```
0
1
2
3
4
5
6
7
8
9
10
Traceback (most recent call last):
  File "xxxxxxxxxxxxxxxxxxxxxx\rm_pdf_annot.py", line 5, in <module>
    for annot in page.annots():
  File "xxxxxxxxxxxxxxxxxxxxxx/python3.10/site-packages/fitz/fitz.py", line 6697, in annots
    annot = self.load_annot(xref)
  File "xxxxxxxxxxxxxxxxxxxxx/python3.10/site-packages/fitz/fitz.py", line 6149, in load_annot
    val.thisown = True
AttributeError: 'SwigPyObject' object has no attribute 'thisown'
swig/python detected a memory leak of type 'Outline *', no destructor found.
swig/python detected a memory leak of type 'Annot *', no destructor found.
swig/python detected a memory leak of type 'Colorspace *', no destructor found.
swig/python detected a memory leak of type 'Colorspace *', no destructor found.
swig/python detected a memory leak of type 'Colorspace *', no destructor found.
```

**Comment by Papafelice** [comment]
Same here: Suse Tumbleweed,  Fitz.version ('1.21.1', '1.21.1', '20221213000001')
```
import fitz
doc = fitz.open("killer.pdf")
page = doc.load_page(0)
for field in page.widgets():
     print(field)
```
yields this:
```
'Text' widget on page 0 of killer.pdf
'Text' widget on page 0 of killer.pdf
'Text' widget on page 0 of killer.pdf
'Text' widget on page 0 of killer.pdf
'Text' widget on page 0 of killer.pdf
'CheckBox' widget on page 0 of killer.pdf
'RadioButton' widget on page 0 of killer.pdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.10/site-packages/fitz/fitz.py", line 6712, in widgets
    widget = self.load_widget(xref)
  File "/usr/lib64/python3.10/site-packages/fitz/fitz.py", line 6059, in load_widget
    val.thisown = True
AttributeError: 'SwigPyObject' object has no attribute 'thisown'
```

**Comment by JorjMcKie** [comment]
Cannot reproduce. You did not provide an example file.

Please note that you are using Python 3.10 on an unsupported platform, see this comment on the Python download website
![grafik](https://user-images.githubusercontent.com/8290722/216562265-020f2924-476a-4619-94b8-add3985cfeb1.png)

I also tried your code snippet on a file with 400 annotations across 10 pages without problem.
So I am afraid, we have to reject this bug report.

**Comment by JorjMcKie** [comment]
If you cannot change your platform situation, try this as a workaround:
```python
for page in doc:
    annot = page.first_annot
    while annot:
        annot = page.delete_annot(annot)
```

**Comment by JorjMcKie** [comment]
@Papafelice this is **not** the same:
1. you are dealing with widgets, not annotations
2. you are not deleting anything

Please submit a report that reflects your situation and is accompanied by required data like platform info and reproducer file.

**Comment by Papafelice** [comment]
You are correct. My guess was that both problems share the same root cause.
It is happening only in certain files. The one that crashes cointains proprietary company data, so I cannot upload.
I will try to create a "clean" file and will then open a new issue.

**Comment by JorjMcKie** [comment]
> You are correct. My guess was that both problems share the same root cause. It is happening only in certain files. The one that crashes cointains proprietary company data, so I cannot upload. I will try to create a "clean" file and will then open a new issue.

If you want, you can also send me the file via my personal e-mail to avoid it being visible publicly ...
