### ISSUE TITLE
Delete text from the page

### ISSUE THREAD

**Issue by ishan-modi** [pymupdf/PyMuPDF#2211]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.

**Describe the solution you'd like**
Wanted a feature with delete functionality similar to delete text from a page object
eg - page.remove_text() removes all characters from the page object

**Describe alternatives you've considered**
obtain xref from page.get_contents()[0]
then obtain page bytes doc.xref_stream(xref)
then iterate through bytes and replace the beginning and ending token of text with b'' (empty byte-string)
later doc.update_stream(xref,changed byte-string)

**Comment by JorjMcKie** [comment]
Are you aware of redaction annotations?
They can be used to do what you want.
```python
page = doc[pagenumber]
page.add_redact_annot(page.rect)  # redaction annotation covering full page
page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)  # do not touch images
```

**Comment by ishan-modi** [comment]
Got it @JorjMcKie, thanks for the quick response
