### ISSUE TITLE
IMG2PDF: image size is changed, that is bad

### ISSUE THREAD

**Issue by jscodecode** [pymupdf/PyMuPDF#2214]
` 
    doc = fitz.open()

   #1. open image as fitz.Document and convert it to a PDF in memory

   imgpdf = fitz.open('1.png').convert_to_pdf()

   #2. append memory PDF as a page

   doc.insert_pdf(fitz.open("pdf", imgpdf))

   doc.save('1.pdf')
`

image size is changed from w:{595 },h:{842}(1.png size) to w:{447},h:{632}(1.pdf size)

How can I solve this problems?

**Comment by JorjMcKie** [comment]
This is a typical "Discussions" post not an issue, therefore I will first transfer it.
