### ISSUE TITLE
blockno is not the same across get_text methods

### ISSUE THREAD

**Issue by darwinharianto** [pymupdf/PyMuPDF#2218]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.
I was trying to connect get_text("words") result with get_text("rawdict"). Looking at the documentations, I thought I can link them using blockno (also known as seqno I believe).  When I tried to link them, I have to add seqno from get_text("words")
 with how many image blocks I get from get_text("rawdict") up to the seqno. 

**Describe the solution you'd like**
Same blockno and seqno on different get_text to link them easier.

**Describe alternatives you've considered**
Are there several options for how your request could be met?

**Additional context**

**Comment by JorjMcKie** [comment]
This is typical "Discussions" item, so I will first reclassify.
