### ISSUE TITLE
page.delete_image | object has no attribute 'is_image'

### ISSUE THREAD

**Issue by alx-xlx** [pymupdf/PyMuPDF#2220]
I am getting the following error while deleting an image using the `xref`
Am I doing something wrong ?

I have attached the image to show that `xref` integer does exists

![](https://i.imgur.com/9vvJRzm.png)

**Comment by JorjMcKie** [comment]
This is duplicate, that will be fixed in next version. In the meantime, please use this hotfix:
```python
doc.is_image = doc.xref_is_image
```
before you execute `doc.delete_image`. There exists a simple typo currently ...
