### ISSUE TITLE
Wrong text extraction, it contains space inside the text

### ISSUE THREAD

**Issue by juhonkang** [pymupdf/PyMuPDF#2225]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Wrong text extraction, it contains space inside the text. However, when I use the Edge browser to extract, it doesn't have an error. 

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).
![image](https://user-images.githubusercontent.com/67153600/217848219-b8fb51f4-d9f1-4a21-8e91-294a2edd5835.png)

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/67153600/217848888-ae2a3b32-6ebe-4934-993c-67634048840c.png)

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
Please provide a reproducer file so the issue can be accepted.

**Comment by JorjMcKie** [comment]
Reminder:
Please complete your issue by providing an example file showing the problem.

**Comment by quangvhhe140489** [comment]
Hi, how it's going?

**Comment by juhonkang** [comment]
https://we.tl/t-B1CT1CG4hB 
pass: nahnah
Plz make it quick, thanks

**Comment by JorjMcKie** [comment]
If you do specify option `TEXT_INHIBIT_SPACES`, the output should be ok:
```python
text =page.get_text(flags=fitz.TEXT_INHIBIT_SPACES, sort=True)
import pathlib
pathlib.Path("inhibited.txt").write_text(text)
```
[inhibited.txt](https://github.com/pymupdf/PyMuPDF/files/10890975/inhibited.txt)

**Comment by JorjMcKie** [comment]
> I also want to do the search_for("keywords") function and get text in a region rect with these pdfs. How can I use this flags=fitz.TEXT_INHIBIT_SPACES

The `Page.search_for()` methods accepts the `flags` parameter like all the `Page.get_text()` methods. In fact, it also has its own set of default flag bits set, like each of the text extration variants. See the documentation [here](https://pymupdf.readthedocs.io/en/latest/vars.html#text-extraction-flags) what these are. To add a flag bit to text search, use `flags = fitz.TEXTFLAGS_SEARCH | fitz.TEXT_INHIBIT_SPACES`.
Similarly, if you want to **_switch off_** preserving ligatures when searching for text, do this: `flags = fitz.TEXTFLAGS_SEARCH  & ~fitz.TEXT_PRESERVE_LIGATURES`.

**Comment by juhonkang** [comment]
Great, and I also have another question in extract text in a rect region. 
How to extract the lines in the rect in pdf? I have found the solution but only to extract words & position them inside the rect.
Note is I want the lines inside the rect, but these lines will only be words inside these rect. 

Another question is if I have words, the position of each word, and how to reconstruct the words and form them into lines? Any algorithms?
