### ISSUE TITLE
open some pdf cost too much time

### ISSUE THREAD

**Issue by buptyyf** [pymupdf/PyMuPDF#2228]
fitz open some pdf cost too much time. And the size of this pdf is only 24MB.

Open this pdf cost 10 seconds on M1 macbook pro.

And cost too much time get_toc(), get_text_blocks() and other api using this pdf. How should I check which pdf fitz parse will be slow?

Test PDF:
[CB_Epx2qj2qxEqN6eV6cj2WzDbV.pdf](https://github.com/pymupdf/PyMuPDF/files/10712949/CB_Epx2qj2qxEqN6eV6cj2WzDbV.pdf)

**Comment by JorjMcKie** [comment]
We are investigating this problem.

In the meantime:
Do you have additional information, like is there a pattern? The example is generated by the `calibre` e-book manager - can you confirm this generally happens in this case?
If there is urgency, I can recommend ways to circumvent the problem.

**Comment by buptyyf** [comment]
> We are investigating this problem.
> 
> In the meantime: Do you have additional information, like is there a pattern? The example is generated by the `calibre` e-book manager - can you confirm this generally happens in this case? If there is urgency, I can recommend ways to circumvent the problem in the meantime.

I have no more information so far. This pdf is upload by other user who also don't have additional info.

**Comment by JorjMcKie** [comment]
@buptyyf - the problem has been fixed. The fix will be published with the next version.
