### ISSUE TITLE
Document.tobytes() maybe not convert it to binary data???

### ISSUE THREAD

**Issue by jscodecode** [pymupdf/PyMuPDF#2235]
This is my code:
doc = fitz.open('test.pdf')
doc = doc.tobytes()
doc = doc.decode(encoding='utf-8')
Threr is an error:
'utf-8' codec can't decode byte 0x9c in position 521: invalid start byte.

I see the interface.
tobytes(garbage=0, clean=False, deflate=False, deflate_images=False, deflate_fonts=False, ascii=False, expand=0, linear=False, pretty=False, no_new_id=False, encryption=PDF_ENCRYPT_NONE, permissions=-1, owner_pw=None, user_pw=None)
ascii (bool) – convert binary data to ASCII.

Document.tobytes() maybe not convert it to binary data???
How can I solve this problems?

**Comment by JorjMcKie** [comment]
See Discussions post with same title.
