### ISSUE TITLE
Some texts can't be parsed completely. And get_pixmap get messy picture.

### ISSUE THREAD

**Issue by buptyyf** [pymupdf/PyMuPDF#2243]
Example PDF:
[区块链黑暗森林自救手册V1.pdf](https://github.com/pymupdf/PyMuPDF/files/10780549/V1.pdf)

I get pixmap from this pdf, then I get a messy picture.
```
import fitz
doc = fitz.open('./testdata/区块链黑暗森林自救手册V1.pdf')
page = doc[31]
pixmap = page.get_pixmap(matrix=fitz.Matrix(2, 2), alpha = False)
pixmap.save('temp-31.jpeg')
```

Another question is text can't parse completely.
```
import fitz
doc = fitz.open('./testdata/区块链黑暗森林自救手册V1.pdf')
page = doc[31]
pageinfo = page.get_text('dict')
# not complete text parse, "这里可能带来的安全问题主要有两点：", "这里" disappear.
# pageinfo[16]['lines']
```
<img width="926" alt="image" src="https://user-images.githubusercontent.com/13342539/220039340-42f6d6b0-0e9c-43e4-ad1c-feaae73c74d7.png">

**Comment by JorjMcKie** [comment]
I am getting the text, look at this near the bottom, distributed over several lines:
```python
print(page.get_text(sort=True))
除了以上这
些，
还有未来
的新增
或更
改而引
入的安全问
题，
我们
经常
说“安全是动
态的、不
是
静态的”，
指的就
是这
点。比
如现在
很多项
目方都
有安全审计
及漂亮的安全审计
报告，
但如
果认真
阅读质
量不错的报告就
会发现，
这些报告会说明
清楚
，什么时
间范围
安全审计
了什么内容，
内容的
唯一标记
是什么（
比如链上开源
验证后
的地址或 GitHub 仓库的 commit 地址，
再或者
目标代码
文件的哈希
值）
。所
以报告是静态的，
如果你发现目标项
目有不
符合
报告里
的描
述内容，
就可以指
出。
NFT 安全
前面提的 DeFi 安全几乎内容都
可以应
用到 NFT 安全上，
但 NFT 又有自己独
特的安全点
，比如：
Metadata 安全

签名安全
Metadata 指
的主要就
是图片
、动
图等内容，
关于
Metadata 的具体标准建
议可以参考
OpenSea 出的：
https://docs.opensea.io/docs/metadata-standards
这里可能
带来
的安全问
题主要有两点
：
一个是图片（或动图）所在的 URI 是不可信的，比如随便的中心化服务，一方面不稳定，
另一方面项目方随便改图片都行，那么 NFT 的数字藏品能力也就没了。一般都会用 IPFS、
Arweave
这些去中心化存储，并且用知名的 URI 网关服务。

另一个问题是可能造成隐私泄露，随便的 URI 是可以采集用户的基本隐私的（如 IP、
User-Agent 等）。
31
```

**Comment by JorjMcKie** [comment]
The incomplete pixmap is another thing, which I cannot explain right now. Probably has to be reported to MuPDF, https://bugs.ghostscript.com/enter_bug.cgi

**Comment by buptyyf** [comment]
> I am getting the text, look at this near the bottom, distributed over several lines:
> 
> ```python
> print(page.get_text(sort=True))
> 除了以上这
> 些，
> 还有未来
> 的新增
> 或更
> 改而引
> 入的安全问
> 题，
> 我们
> 经常
> 说“安全是动
> 态的、不
> 是
> 静态的”，
> 指的就
> 是这
> 点。比
> 如现在
> 很多项
> 目方都
> 有安全审计
> 及漂亮的安全审计
> 报告，
> 但如
> 果认真
> 阅读质
> 量不错的报告就
> 会发现，
> 这些报告会说明
> 清楚
> ，什么时
> 间范围
> 安全审计
> 了什么内容，
> 内容的
> 唯一标记
> 是什么（
> 比如链上开源
> 验证后
> 的地址或 GitHub 仓库的 commit 地址，
> 再或者
> 目标代码
> 文件的哈希
> 值）
> 。所
> 以报告是静态的，
> 如果你发现目标项
> 目有不
> 符合
> 报告里
> 的描
> 述内容，
> 就可以指
> 出。
> NFT 安全
> 前面提的 DeFi 安全几乎内容都
> 可以应
> 用到 NFT 安全上，
> 但 NFT 又有自己独
> 特的安全点
> ，比如：
> Metadata 安全
> 
> 签名安全
> Metadata 指
> 的主要就
> 是图片
> 、动
> 图等内容，
> 关于
> Metadata 的具体标准建
> 议可以参考
> OpenSea 出的：
> https://docs.opensea.io/docs/metadata-standards
> 这里可能
> 带来
> 的安全问
> 题主要有两点
> ：
> 一个是图片（或动图）所在的 URI 是不可信的，比如随便的中心化服务，一方面不稳定，
> 另一方面项目方随便改图片都行，那么 NFT 的数字藏品能力也就没了。一般都会用 IPFS、
> Arweave
> 这些去中心化存储，并且用知名的 URI 网关服务。
> 
> 另一个问题是可能造成隐私泄露，随便的 URI 是可以采集用户的基本隐私的（如 IP、
> User-Agent 等）。
> 31
> ```

Okay, it is maybe another bug. page.get_text(sort=True) can output "这里" as first image. But page.get_text('dict') actual can't parse "这里" as second image.
```
import fitz
doc = fitz.open('./testdata/区块链黑暗森林自救手册V1.pdf')
page = doc[31]
pageinfo = page.get_text('dict')
# not complete text parse, "这里可能带来的安全问题主要有两点：", "这里" disappear.
print(pageinfo[16]['lines'])
```
![image](https://user-images.githubusercontent.com/13342539/221525793-9b2152ca-1f4f-4262-9783-5704f53ffb77.png)
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/13342539/221526483-8cea2ac2-db7d-42f4-bc06-3838344d950a.png">

**Comment by buptyyf** [comment]
> > I am getting the text, look at this near the bottom, distributed over several lines:
> > ```python
> > print(page.get_text(sort=True))
> > 除了以上这
> > 些，
> > 还有未来
> > 的新增
> > 或更
> > 改而引
> > 入的安全问
> > 题，
> > 我们
> > 经常
> > 说“安全是动
> > 态的、不
> > 是
> > 静态的”，
> > 指的就
> > 是这
> > 点。比
> > 如现在
> > 很多项
> > 目方都
> > 有安全审计
> > 及漂亮的安全审计
> > 报告，
> > 但如
> > 果认真
> > 阅读质
> > 量不错的报告就
> > 会发现，
> > 这些报告会说明
> > 清楚
> > ，什么时
> > 间范围
> > 安全审计
> > 了什么内容，
> > 内容的
> > 唯一标记
> > 是什么（
> > 比如链上开源
> > 验证后
> > 的地址或 GitHub 仓库的 commit 地址，
> > 再或者
> > 目标代码
> > 文件的哈希
> > 值）
> > 。所
> > 以报告是静态的，
> > 如果你发现目标项
> > 目有不
> > 符合
> > 报告里
> > 的描
> > 述内容，
> > 就可以指
> > 出。
> > NFT 安全
> > 前面提的 DeFi 安全几乎内容都
> > 可以应
> > 用到 NFT 安全上，
> > 但 NFT 又有自己独
> > 特的安全点
> > ，比如：
> > Metadata 安全
> > 
> > 签名安全
> > Metadata 指
> > 的主要就
> > 是图片
> > 、动
> > 图等内容，
> > 关于
> > Metadata 的具体标准建
> > 议可以参考
> > OpenSea 出的：
> > https://docs.opensea.io/docs/metadata-standards
> > 这里可能
> > 带来
> > 的安全问
> > 题主要有两点
> > ：
> > 一个是图片（或动图）所在的 URI 是不可信的，比如随便的中心化服务，一方面不稳定，
> > 另一方面项目方随便改图片都行，那么 NFT 的数字藏品能力也就没了。一般都会用 IPFS、
> > Arweave
> > 这些去中心化存储，并且用知名的 URI 网关服务。
> > 
> > 另一个问题是可能造成隐私泄露，随便的 URI 是可以采集用户的基本隐私的（如 IP、
> > User-Agent 等）。
> > 31
> > ```
> 
> Okay, it is maybe another bug. page.get_text(sort=True) can output "这里" as first image. But page.get_text('dict') actual can't parse "这里" as second image.
> 
> ```
> import fitz
> doc = fitz.open('./testdata/区块链黑暗森林自救手册V1.pdf')
> page = doc[31]
> pageinfo = page.get_text('dict')
> # not complete text parse, "这里可能带来的安全问题主要有两点：", "这里" disappear.
> print(pageinfo[16]['lines'])
> ```
> 
> ![image](https://user-images.githubusercontent.com/13342539/221525793-9b2152ca-1f4f-4262-9783-5704f53ffb77.png) <img alt="image" width="1069" src="https://user-images.githubusercontent.com/13342539/221526483-8cea2ac2-db7d-42f4-bc06-3838344d950a.png">

Is this a bug? get_text(sort=True) not equals text in get_text('dict')? Some texts disapear.

**Comment by JorjMcKie** [comment]
> Okay, it is maybe another bug. page.get_text(sort=True) can output "这里" as first image. But page.get_text('dict') actual can't parse "这里" as second image.

This is because you did not sort the "dict" extraction. It does support the "sort" argument too.

**Comment by JorjMcKie** [comment]
MuPDF issue number https://bugs.ghostscript.com/show_bug.cgi?id=706451
