### ISSUE TITLE
To detect and get the bounding box of the figures or drawings

### ISSUE THREAD

**Issue by spt3009** [pymupdf/PyMuPDF#2247]
Basically I want to detect and get the bounding box of the figures or drawings which are in pdf using python, [enter image description here](https://i.stack.imgur.com/ap3A0.png) As per the image I just want the bounding box of the figure right below the question, but it also detects the "-" present in the options.

So I tried using the fitz_page.get_drawings() method from importing fitz  and it helps in replicating the images on another pdf file, but doesn't help in differentiating when the first figure ends and the second starts. I just want the x-y coordinates of the bounding box for each figure separately

**Comment by JorjMcKie** [comment]
Every line art figure (called a path in PDF and PyMuPDF) is a dictionary with all the elementary drawings (in key "items") plus common properties, among which you will see "rect", the wrapping rectangle if the items, this is what you are looking for.

**Comment by spt3009** [comment]
The path in paths is for minor figures in a large figure. I want the bounding box for the entire drawing below the question, where as the paths is the representation of minor figures in which the drawing is broken into. The real problem here is that I only want the bounding box for the drawing below the question, but it also identifies the dashes (hyphen) present in the fraction as a figure and hence breaks them into paths, so when I run the loop I get 84 paths for drawings in the page. That’s why it becomes very difficult to differentiate between the drawings and get bounding box for each of them.

**Comment by spt3009** [comment]
This is my input :

and this is my output using “rect” to draw in common properties of paths:




I just don’t want small figures less than a particular size to be there in the output. How can i achieve it ?

**Comment by spt3009** [comment]
like the two small horizontal lines at the end.

**Comment by spt3009** [comment]
this is my input:
![Q](https://user-images.githubusercontent.com/101585441/220874016-042239d6-7292-445a-b073-b0a586e6db23.jpg)

and this is my output:
[drawings-page-0.pdf](https://github.com/pymupdf/PyMuPDF/files/10812306/drawings-page-0.pdf)

I just don’t want small figures less than a particular size to be there in the output like the two small horizontal lines at the  #end.

**Comment by JorjMcKie** [comment]
> I just don’t want small figures less than a particular size to be there in the output like the two small horizontal lines at the end. Is there any way to achieve it ?

No, I am afraid there is not. All you can do is injecting your own code to subselect the paths of interest.
The line art extractor `get_drawings()` has no choice other than extracting drawing commands as they occur in the page appearance source. All it encounters are lines and curves, grouped ("paths") as occurring in that source. PyMuPDF in addition **_does_** recognize lines, which are actually defining rectangles or quads and returns them. But it is unable to recognize other higher level figures (e.g. triangles, circles, ...).
Even more, it certainly cannot guess what the creator's intention **_might_** have been.
The creator of the PDF is to blame for the way he made those drawings. He obviously chose to implement some parts as line art, yet other parts as normal text and intermingle both components for arriving at the visible appearance.

**Comment by JorjMcKie** [comment]
A little bit late, but I have finally located my script which walks over a page's drawings and joins any two intersecting path rectangles , recursively.
The resulting (reduced) set of rectangles is then used to make pixmaps (PNG images) for each of them. As mentioned: if your drawings are luckily created thus, that visually separate figures also have no rectangle intersections, your problem should be solved.
[path2png.zip](https://github.com/pymupdf/PyMuPDF/files/10989647/path2png.zip)
I will also publish this script on our [Utilities](https://github.com/pymupdf/PyMuPDF-Utilities) repository later today.

**Comment by spt3009** [comment]
thank you so much for taking out time for this. The solution has helped me increase the resolution of the image. Actually i have multiple images and in some situations it has a rectangle intersection and it is not diagram or drawing as we can see in the above picture for question no.1. It even identifies the ’square root’ as a diagram which should not be the case and it should identify all the four line graphs in question 4. I understand it is an issue because the way the pdf is generated and i will have to figure a different way out. Thanks again for giving me an approach to think on.

Thank you.

**Comment by JorjMcKie** [comment]
You are very welcome. As I wrote, sorry for the delay in answering this completely.
