### ISSUE TITLE
docs: unclear or broken link in page.rst

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#2250]
in `page.rst`, I saw

```
A coding draft can be found in section "Extractings Drawings" of chapter :ref:`FAQ`.
```

Probably it should be "Extracting Drawings" but I found no match to that either.  Can someone fix up this link?

**Comment by julian-smith-artifex-com** [comment]
Fixed in my tree to say "How to Extract Drawings".
