### ISSUE TITLE
mupdf_display_errors does not apply to Pixmap when loading broken image

### ISSUE THREAD

**Issue by stefan6419846** [pymupdf/PyMuPDF#2251]
## Describe the bug

Loading a partially broken image, which `libjpeg-turbo`(?) reports a warning about, does not respect setting `mupdf_display_errors(False)`, thus spamming the output.

## To Reproduce

```python3
import fitz


fitz.TOOLS.mupdf_display_errors(False)
print(fitz.Pixmap('invalid-sos.jpg'))
print(fitz.TOOLS.mupdf_warnings(reset=True))
```

The broken file is taken from https://github.com/asilvas/node-image-steam/blob/master/test/files/invalid-sos.jpg In my specific case, such images are embedded into a PDF I am extracting the images of, but this simple example raises this error as well.

Output is:

```
Invalid SOS parameters for sequential JPEG
Pixmap(DeviceRGB, IRect(0, 0, 4032, 3024), 0)

```

## Expected behavior

Hiding MuPDF warnings should allow controlling all warnings, not only the direct ones, thus not printing `Invalid SOS parameters for sequential JPEG`.

## Your configuration
 - OpenSUSE Leap 15.3, 64-bit
 - Python 3.7, 64-bit
 - PyMuPDF 1.12.1, generated from source

**Comment by JorjMcKie** [comment]
This message is not issued by (Py-) MuPDF. Therefore it is not being suppressed by the settings you used. We are checking which of the thirdparty libraries issues the message, and whether there ways to suppress it ... or not.

**Comment by JorjMcKie** [comment]
Just confirming that this message is issued by one of the thirdparty packages used by MuPDF, libjpeg.
So MuPDF's own message filtering has no way to intercept it.
In libjpeg, this is a warning. I will forward your inquiry to our experts to see whether suppression is possible.
