### ISSUE TITLE
Words are supposedly outside the page

### ISSUE THREAD

**Issue by andreaswimmer** [pymupdf/PyMuPDF#2253]
## Describe the bug
When extracting text from a PDF, some words are supposedly outside the rect of the page.

## To Reproduce
```
import tempfile

import fitz
import requests

r = requests.get("https://mdpi-res.com/d_attachment/computation/computation-06-00058/article_deploy/computation-06-00058-s001.pdf?version=1542187739", stream=True)
with tempfile.NamedTemporaryFile("wb") as file:
    file.write(r.content)
    file.flush()
    doc = fitz.Document(file.name)
    page = doc[7]
    # can also search for "list" or "parameters"
    tables = page.search_for("Table")
    assert len(tables) == 1
    word = tables[0]
    print(word)
    print(page.rect)
    word_x0, word_y0, word_x1, word_y1 = word
    page_x0, page_y0, page_x1, page_y1 = page.rect
    assert word_x0 >= page_x0
    assert word_y0 >= page_y0
    assert word_x1 <= page_x1
    assert word_y1 <= page_y1  # <- this fails
    print("Success!")
```
Note that the word is clearly inside the page:
![image](https://user-images.githubusercontent.com/53872150/221244144-eb377056-8db1-4e5c-b5c8-4e5f41d6e1c7.png)

## Your configuration (mandatory)
```
>>> print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.8.16 (default, Jan 17 2023, 23:13:24)
[GCC 11.2.0]
 linux

PyMuPDF 1.21.1: Python bindings for the MuPDF 1.21.1 library.
Version date: 2022-12-13 00:00:01.
Built for Python 3.8 on linux (64-bit).
```
Installed via pip on Ubuntu

**Comment by JorjMcKie** [comment]
Please provide the file for reproducing the problem!

**Comment by andreaswimmer** [comment]
[computation-06-00058-s001.pdf](https://github.com/pymupdf/PyMuPDF/files/10834498/computation-06-00058-s001.pdf)

**Comment by tegancp** [comment]
This looks to be just a question of handling page rotation.
If you check `page.rotation` you should see that the page has 90 degree rotation.  The value of `page.rect` uses coordinates _after_ the page is rotated, while the return values for `page.search_for` are in unrotated coordinates.  You can get the rotated coordinates by multiplying by `page.rotation_matrix`.

**Comment by JorjMcKie** [comment]
Please look at @tegancp 's enlightening response. The text is fully extracted:
```python
In [6]: text= page.get_text()
In [7]: print(text)
Table S2. list of the 90 parameters values corresponding to each granuloma shown in Figure S1. The experiment numbers shown refer to the
correspondent parameter sample (out of 1,500 samples) generated by the Latin hypercube sampling scheme.
Parameter Name
... etc.
```
