### ISSUE TITLE
insert_image: document that rotations are counterclockwise

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#2275]
Docs for insert_image:

> rotate (int) – (new in version v1.14.11) rotate the image. Must be an integer multiple of 90 degrees. If you need a rotation by an arbitrary angle, consider converting the image to a PDF ([Document.convert_to_pdf()](https://pymupdf.readthedocs.io/en/latest/document.html#Document.convert_to_pdf)) first and then use [Page.show_pdf_page()](https://pymupdf.readthedocs.io/en/latest/page.html#Page.show_pdf_page) instead.

It would be helpful if this said "rotate the image counter-clockwise."

(I've just spent some time debugging something that mixes `mogrify` (cw), `PIL` (ccw) and `fitz` (ccw); it would be helpful to have these things written down in the docs).

- - - -

Sorry for not sending a PR; but it would be good for someone to double-check that I'm right ;-)

**Comment by JorjMcKie** [comment]
Accepted. As is customary, throughout PDF at least, positive angles rotate counter-clockwise, negative angles are clockwise.

**Comment by julian-smith-artifex-com** [comment]
I have updated the docs in my tree to mention this.
