### ISSUE TITLE
Error installing CentOS 7

### ISSUE THREAD

**Issue by leandrocombr** [pymupdf/PyMuPDF#2277]
sudo python3.12 setup.py install

Error:
clst.cpp:(.text._ZN9tesseract5CLIST4sortEPFiPKvS2_E+0xf3): undefined reference to `operator delete(void*, unsigned long)'
build/release/libmupdf-third.a(sortflts.o):sortflts.cpp:(.text._ZN9tesseract19SORTED_FLOAT_zapperEPNS_10ELIST_LINKE+0xb): more undefined references to `operator delete(void*, unsigned long)' follow
collect2: error: ld returned 1 exit status
make: *** [build/release/mutool] Error 1
Traceback (most recent call last):
  File "/var/www/vhosts/wpp-api425.plataformaathus.com.br/httpdocs/pdff/PyMuPDF/setup.py", line 594, in <module>
    subprocess.run( command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd mupdf-1.21.0-rc1-source/ &&  CFLAGS="-fPIC" make HAVE_X11=no HAVE_GLFW=no HAVE_GLUT=no HAVE_LEPTONICA=yes HAVE_TESSERACT=yes verbose=yes build=release && echo "build/release:" && ls -l build/release' returned non-zero exit status 2.

**Comment by julian-smith-artifex-com** [comment]
We don't currently support python-3.12 because it has not been released yet.

[This particular error looks like it's in MuPDF's `thirdparty/tesseract`, so it might be an issue for tesseract, but this is just speculation at this stage.]
