### ISSUE TITLE
Accent extracted as a separated character

### ISSUE THREAD

**Issue by chamoulox** [pymupdf/PyMuPDF#2279]
Hello,

I'm using PyMuPDF to extract text from native PDF. I'm having some issues with French accents on the joined document.

In my workflow I'm first extracting text as XML, but the issue also appears when extracting text directly.

Every accent in the document is displayed as another character, so my text output is incorrect.

### To Reproduce 
```
import fitz
pdf_file = fitz.open('free_accent.pdf')
page = pdf_file[0]
print(page.get_text())
```
We can see

```
10 aoˆut 2022
Cette somme sera pr´elev´ee
```

From the XML I'm generating, I also have it separated in two characters

```
xml_page = page.get_text("xml").encode('utf-8')
```
give as output (small extract)
```
<font name="NimbusSanL-Bold" size="16.355">
<char quad="152.89699 274.29307 161.99037 274.29307 152.89699 294.83497 161.99037 294.83497" x="152.89699" y="289.81398" color="#000000" c="7"/>
<char quad="161.99037 274.29307 171.08376 274.29307 161.99037 294.83497 171.08376 294.83497" x="161.99037" y="289.81398" color="#000000" c="2"/>
<char quad="171.08376 274.29307 180.17714 274.29307 171.08376 294.83497 180.17714 294.83497" x="171.08376" y="289.81398" color="#000000" c="0"/>
<char quad="180.17714 274.29307 189.27053 274.29307 180.17714 294.83497 189.27053 294.83497" x="180.17714" y="289.81398" color="#000000" c="5"/>
<char quad="189.27053 274.29307 198.3639 274.29307 189.27053 294.83497 198.3639 294.83497" x="189.27053" y="289.81398" color="#000000" c="2"/>
<char quad="198.3639 274.29307 207.45729 274.29307 198.3639 294.83497 207.45729 294.83497" x="198.3639" y="289.81398" color="#000000" c="1"/>
<char quad="207.45729 274.29307 216.55068 274.29307 207.45729 294.83497 216.55068 294.83497" x="207.45729" y="289.81398" color="#000000" c="8"/>
<char quad="221.09737 274.29307 231.09027 274.29307 221.09737 294.83497 231.09027 294.83497" x="221.09737" y="289.81398" color="#000000" c="d"/>
<char quad="231.09027 274.29307 241.08318 274.29307 231.09027 294.83497 241.08318 294.83497" x="231.09027" y="289.81398" color="#000000" c="u"/>
<char quad="245.62769 274.29307 254.72107 274.29307 245.62769 294.83497 254.72107 294.83497" x="245.62769" y="289.81398" color="#bf0000" c="1"/>
<char quad="254.72107 274.29307 263.81446 274.29307 254.72107 294.83497 263.81446 294.83497" x="254.72107" y="289.81398" color="#bf0000" c="0"/>
<char quad="268.36116 274.29307 277.45454 274.29307 268.36116 294.83497 277.45454 294.83497" x="268.36116" y="289.81398" color="#bf0000" c="a"/>
<char quad="277.45454 274.29307 287.44746 274.29307 277.45454 294.83497 287.44746 294.83497" x="277.45454" y="289.81398" color="#bf0000" c="o"/>
<char quad="289.7208 274.29307 295.16703 274.29307 289.7208 294.83497 295.16703 294.83497" x="289.7208" y="289.81398" color="#bf0000" c="ˆ"/>
<char quad="287.44746 274.29307 297.44038 274.29307 287.44746 294.83497 297.44038 294.83497" x="287.44746" y="289.81398" color="#bf0000" c="u"/>
<char quad="297.44038 274.29307 302.8866 274.29307 297.44038 294.83497 302.8866 294.83497" x="297.44038" y="289.81398" color="#bf0000" c="t"/>
<char quad="307.4333 274.29307 316.52668 274.29307 307.4333 294.83497 316.52668 294.83497" x="307.4333" y="289.81398" color="#bf0000" c="2"/>
<char quad="316.52668 274.29307 325.62007 274.29307 316.52668 294.83497 325.62007 294.83497" x="316.52668" y="289.81398" color="#bf0000" c="0"/>
<char quad="325.62007 274.29307 334.71345 274.29307 325.62007 294.83497 334.71345 294.83497" x="325.62007" y="289.81398" color="#bf0000" c="2"/>
<char quad="334.71345 274.29307 343.80683 274.29307 334.71345 294.83497 343.80683 294.83497" x="334.71345" y="289.81398" color="#bf0000" c="2"/>
</font>
```

### Expected behavior
I should expect, for above cases:
```
10 août 2022
Cette somme sera prélevée
```

#### Configuration
 - Ubuntu 20.04
 - Python 3.8.10 
 - PyMuPDF version 1.21.1 installed with pip

## Additional context

I notice that evince PDF reader (native on Ubuntu) manage to get the output right, whereas chrome reader doesn't. (With a simple copy/paste from PDF)

Thanks for your help

[free_accent.pdf](https://github.com/pymupdf/PyMuPDF/files/10929616/free_accent.pdf)

**Comment by JorjMcKie** [comment]
Thanks for communicating differing results between PDF viewers. (Py)MuPDF has certainly no problem with the extended Latin charset or any other character ... **_if_** coded correctly by the creator. The examples suggest that the file is written using two (or rather three) separate characters: e/backspace/accent instead of one é. So this is no bug but a problem of the file itself (or it's creator). If you extract by character (rawdict option) you should be able to see identical / overlapping char boxes here.

**Comment by chamoulox** [comment]
Thank you for the answer. Yes indeed, I have no issue with other documents, only some coming from Free as the one shown. Encoding was also my supposition.

I have indeed an overlap char boxes.

The most surprising part is that evince is then interpreting the content, as it shows correctly the output.
I guess I'll have to do it myself then.

**Comment by JorjMcKie** [comment]
Ok, understod. Right, PyMuPDF does not look at character sequences `e^`, `i´`, stack them and look backward to see if any pair **_might_** occasionally form a ligature character. You either can reach what you want by using `fitz.TEXT_PRESERVE_LIGURATURES`, or develop your own code to super-position an "o" with an "^". Always keping in mind that the PDF creator has been too lazy to do it right from the start.
As it obvious I think, the effort can be quite significant if you want to do it right.

**Comment by chamoulox** [comment]
I tried with the ligature flags, but in the case of this document, it doesn't form a ligature.

I managed to get it done by verifying every word. It do the job.

Thank you for your answers
