### ISSUE TITLE
Font name in Japanese encoding not found

### ISSUE THREAD

**Issue by Zeletochoy** [pymupdf/PyMuPDF#2298]
## Describe the bug (mandatory)

When rendering a PDF with a non-embedded font referred to by its Japanese name in `90ms-RKSJ-H` encoding, the wrong font gets picked and the output image is wrong (see screenshots and repro).

## To Reproduce (mandatory)

```
import fitz

page = fitz.open("SampleA.pdf")[0]
doc = fitz.open("SampleA.pdf")
page = doc[0]
pixmap = page.get_pixmap()
image = pixmap.tobytes(output="png")
with open("output.png", "wb") as f:
    f.write(image)
```
With this file: [SampleA.pdf](https://github.com/pymupdf/PyMuPDF/files/11046347/SampleA.pdf)

## Expected behavior (optional)
The font should be picked up successfully :)

## Screenshots (optional)

Rendered with PyMuPDF:
<img width="123" alt="Screen Shot 2023-03-23 at 11 15 39" src="https://user-images.githubusercontent.com/9062295/227081973-b7c5c9ab-00fe-4fa9-a44e-b88747106500.png">

Rendered by MacOS Preview:
<img width="57" alt="Screen Shot 2023-03-23 at 11 15 48" src="https://user-images.githubusercontent.com/9062295/227081977-963f4218-4d7e-4a4f-9132-e8ef59697cd1.png">

## Your configuration (mandatory)
 - MacOS Monterrey (M1) and Ubuntu 20.04 (x86)
 - Python 3.9
 - PyMuPDF 1.21.1

## Additional context (optional)

The problematic font is defined as `(18, 'n/a', 'Type0', '\x82l\x82r\x83S\x83V\x83b\x83N', 'C2_0', '90ms-RKSJ-H', 0)`.
The encoding is set to `90ms-RKSJ-H` which according to the [PDF spec](https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf) (page 274) is `JIS X 0208 character set with NEC and IBM® extensions`, it seems that it should be handled fine by [MuPDF](https://github.com/ArtifexSoftware/mupdf/blob/9bb8392d0ae742ca30b4be82b6fbadd9248aeddb/source/pdf/cmaps/90ms-RKSJ-H.h#L3) at least.
The name, when decoded in Shift-JIS (python doesn't have JIS X 0208 by default...), gives the correct font name and is found on my system:
```
>>> b'\x82l\x82r\x83S\x83V\x83b\x83N'.decode("sjis")
'ＭＳゴシック'
```
```
$ fc-match "ＭＳゴシック"
msgothic.ttc: "MS Gothic" "Regular"
```

**Comment by JorjMcKie** [comment]
There is no bug. The font is not embedded - see the "n/a" indicator. 
Its name as contained in the PDF definition is
```python
In [7]: print(doc.xref_object(18))
<<
  /BaseFont /#82l#82r#83S#83V#83b#83N
  /DescendantFonts [ 17 0 R ]
  /Encoding /90ms-RKSJ-H
  /Subtype /Type0
  /Type /Font
>>
```
Just like returned from PyMuPDF's API. Nothing "problematic".
Also creating the page's image via Pixmap gives me a fine result:
```python
pix=page.get_pixmap()
pix.save("SampleA-0.png")
```
![grafik](https://user-images.githubusercontent.com/8290722/227155339-962caa3f-c536-4504-aa00-971922a6238a.png)

**Comment by JorjMcKie** [comment]
>  Maybe I misunderstood the underlying issue but it seems like something weird is happening?

Nothing is weird here. Except the PDF creator 😉 - he is the one who decided to switch the font 5 **_(five!!!)_** times within string "00000000000000000NV00000".
As the font in question is not embedded (no fontfile exists to prescribe the visual appearance of each character), it is up to the PDF reader software to do that.
So the text may look different with **_every_** reader you want to use. And in fact my installed handful of readers **_do_** show different appearances.
