### ISSUE TITLE
Too much recursion in tree (parents), makes program terminate 

### ISSUE THREAD

**Issue by Nurskss** [pymupdf/PyMuPDF#2300]
I encounted a strange issue, i have a pdf file that is something wrong with (looks fine) but it raises RunTimeError, too much recursion in tree (parents), When i apply i try/except clause the program just terminates instead. The error happens when i iterate over a documents pages and then try to interact with the page.

When i use page.rect the program terminates no matter what i do to avoid it, but when i use other functions like page.get_pixmap() or page.get_text('blocks'), the same issue happens but it does not end the program. Is this a bug and is there a a way to check recursion depth of three before i do anything with it?

My current solution is to just run page.get_text('blocks) and save it to a variable, and if that works then the page.rect is safe to run, but it seems a bit strange.

**Comment by Nurskss** [comment]
Here is the entire code for the files, it looks a bit f** up some places because i have been trying to debug it for ages:

`import fitz
import io
from PIL import Image
from sewar.full_ref import mse
import json
import numpy as np
import re
from operator import itemgetter
from statistics import mean
from django.db import transaction
from tqdm import tqdm
from collections import Counter
import tracemalloc

#from ..engine.kartverket import GAPI
#from main.models import *
import pdb


class Takst(object):
    def __init__(self, filepath='', doc=''):
        if filepath != 'unactive':
            self.doc = fitz.open(filepath)
        if doc:
            self.doc = doc
        
    @staticmethod
    def compare_images(img1, img2, parameter=2000):
        if img1.size > img2.size:
            img2 = img2.resize(img1.size, Image.Resampling.LANCZOS)
        else:
            img1 = img1.resize(img2.size, Image.Resampling.LANCZOS)

        img1 = np.array(img1)
        img2 = np.array(img2)

        mse_score = mse(img1, img2)
        if mse_score < parameter:
            return True
        else:
            return False

    @staticmethod # Print document scan progress
    def print_progress_bar(iteration, total, prefix = '', suffix = '', decimals = 1, length = 100, fill = '█', printEnd = "\r"):
        percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
        filledLength = int(length * iteration // total)
        bar = fill * filledLength + '-' * (length - filledLength)
        print(f'\r{prefix} |{bar}| {percent}% {suffix}', end = printEnd)
        # Print New Line on Complete
        if iteration == total: 
            print()

    def adjust_pdf(self, rotate=False):
        new_pdf = fitz.Document()
        A4_aspect_ratio = 1.414
        adjusted = False
        rotate = False
        r = 0

        for spage in self.doc.pages():

            # Checks for too much recursion error, if it fails the document is bugged
            try:
                test = spage.get_text('blocks')
            except Exception as e:
                print(e)
                new_pdf.close()
                return 'bugged pdf'
                
        
            bbox = spage.rect
            width = (bbox[2] - bbox[0])
            height = (bbox[3] - bbox[1])
            page_aspect_ratio =  height / width
            
            # Detect Rotation
            #if round(width / height, 3) == A4_aspect_ratio and rotate:
            if rotate:
                adjusted = True
                rotate = True
            
            else:
                # Detect multiple pages on one page:
                if width > height:
                    bbox_list = []
                    
                    # Detect 2x pages
                    if round(page_aspect_ratio, 1) == 0.6 or round(page_aspect_ratio, 1) == 0.7:
                        bbox_list.append(fitz.Rect((bbox[0], bbox[1]), (bbox[2]/2, bbox[3])))
                        bbox_list.append(fitz.Rect((bbox[2]/2, bbox[1]), (bbox[2], bbox[3])))

                    # Detect 4x pages 
                    elif round(page_aspect_ratio, 1) == 0.3 or round(page_aspect_ratio, 1) == 0.4:
                        bbox_list.append(fitz.Rect((bbox[0], bbox[1]), (bbox[2]/4, bbox[3])))
                        bbox_list.append(fitz.Rect((bbox[2]/4, bbox[1]), (bbox[2]/4*2, bbox[3])))
                        bbox_list.append(fitz.Rect((bbox[2]/4*2, bbox[1]), (bbox[2]/4*3, bbox[3])))
                        bbox_list.append(fitz.Rect((bbox[2]/4*3, bbox[1]), (bbox[2], bbox[3])))
            
                    d = fitz.Rect(spage.cropbox_position, spage.cropbox_position)
                    for rx in bbox_list:

                        rx += d  # add the CropBox displacement
                        page = new_pdf.new_page(-1, width = rx.width, height = rx.height)
                        page.show_pdf_page(page.rect, self.doc, spage.number, clip = rx)
                        r += 1

                    adjusted = True
                    continue
            
            try:
                page = new_pdf.new_page(-1, width = width, height = height)
                page.show_pdf_page(page.rect, self.doc, spage.number)
                if rotate:
                    page.set_rotation(90)
            except ValueError as e:
                print(e)
                pass # If value error, the page is empty and will not be included
            r += 1
            rotate = False

        # If changes were made replace the doc with the adjusted pdf
        if adjusted:
            #new_pdf.save("poster.pdf", garbage=3, deflate=True)
            self.doc = new_pdf

    def detect_report(self):
        status = self.adjust_pdf()
        if status:
            print('wrong')
            return None, None, None, None # stopper her 1

        print('dwdwwdwdwd')
        for i in range(2):
            report, pdf_document, info = NorskTakst(doc=self.doc).detect_report()
            if report:
                return 'NorskTakst', report, pdf_document, info # stopper her 1
            
            #report, pdf_document, tg_eval_dict = Standard(doc=self.doc).detect_report()
            #if report:
            #    return 'Standard', pdf_document
            
            #report, pdf_document, tg_eval_dict = BMTF(doc=self.doc).detect_report()
            #if report:
            #    return 'BMTF', pdf_document
            
            #report, pdf_document = Anticimex(doc=self.doc).detect_report()
            #if report:
            #    return 'Anticimex', pdf_document
            
            # Rotates the document and tries again
            if i == 0:
                self.adjust_pdf(rotate=True)
            
        return None, None, None, None

    @staticmethod
    def img_replace(page, xref, filename=None, stream=None, pixmap=None):
        if bool(filename) + bool(stream) + bool(pixmap) != 1:
            raise ValueError("Exactly one of filename/stream/pixmap must be given")
        doc = page.parent  # the owning document
        new_xref = page.insert_image(
            page.rect, filename=filename, stream=stream, pixmap=pixmap
        )
        doc.xref_copy(new_xref, xref)  # copy over new to old
        last_contents_xref = page.get_contents()[-1]
        doc.update_stream(last_contents_xref, b" ")

    @staticmethod
    def detect_text(page, text2):
        for text in page.get_text('blocks'):
            if text[6] == 0:
                if text2 in text[4]:
                    return True
        return False

    @staticmethod
    def merge_pdfs(page, doc, new_doc):
        old_rotation = page.rotation
        bbox = page.rect * page.rotation_matrix
        spage = new_doc.new_page(-1, width=(bbox[2] - bbox[0]), height=(bbox[3] - bbox[1]))
        page.set_rotation(0)
        spage.show_pdf_page(page.rect, doc, page.number)
        spage.set_rotation(old_rotation)
        return new_doc

    @staticmethod
    def image_finder(page, images_dict, doc, aspect_range=0, save=False):
        # Image_dict = {'logo': {'file': dw, 'rect': daw, 'paramter': dwa}}
        found_dict = {}
        widt_range = range(int(page.rect[0]), int(page.rect[2]), 1)
        for image in page.get_images():
            xref = image[0]

            rect_list = page.get_image_rects(xref)
            if rect_list:
                for position in rect_list:
                    
                    # If True image is present, continue check
                    if int(position[0]) in widt_range and int(position[2]) in widt_range:
                        aspect_ratio = (position[2] - position[0]) / (position[3] - position[1])
                        image_image = doc.extract_image(xref)
                        image_bytes = image_image["image"]
                        image = Image.open(io.BytesIO(image_bytes)).convert('RGB')
                        if save:
                            print(xref, position)
                            image.save(f'temp/img{xref}.png')
                        
                        for check in images_dict:
                            rect = images_dict[check]['rect']
                            check_aspect = (rect[2] - rect[0]) / (rect[3] - rect[1])
                            #print(round(check_aspect, aspect_range), round(aspect_ratio, aspect_range))
                            #print(check_aspect, aspect_ratio)
                            if round(check_aspect, aspect_range) == round(aspect_ratio, aspect_range):
                                #print('dwadaw')
                                if Takst.compare_images(images_dict[check]['file'], image, parameter=images_dict[check]['parameter']):
                                    found_dict[position] = check
        return found_dict

    # main function for interacting with the report data3.json files
    #@transaction.atomic
    def extract_statusreports(self, report):
        #pdb.set_trace()
        #gapi = GAPI()
        tracemalloc.start()

        for megler in list(report['salgsoppgave'].keys())[3:]:
            print(megler)
            
            for code in tqdm(report['salgsoppgave'][megler]['success'][30:]):
                
                # need to check that the takstrapport have not already been extracted from the salesreport
                #eiendomsdatalog_instance = EiendomsDataLog.objects.get(eiendom_id__finndata__finn=code)
                #if not eiendomsdatalog_instance.tilstandsrapport:
                if True:

                    # Initializes the takst class and finds report type and data about the report
                    print(code)
                    takst_class = Takst(f'C:/Users/mikae/Desktop/takstrapport/v2/backend/files/salgsoppgave/{code}.pdf')
                    report_type, tg_report, pdf_document, info = takst_class.detect_report()
                    takst_class.doc.close()

                    print('\n', report_type, code)

                    # Terminates iteration if no tilstandsrapport is detected
                    if report_type == None:
                        continue
                    
                    # Gather information from pdf
                    if report_type == 'NorskTakst':
                        print(tg_report)
                        norsk_takst = NorskTakst(filepath=f'C:/Users/mikae/Desktop/takstrapport/v2/backend/files/salgsoppgave/{code}.pdf')
                        try:
                            information = norsk_takst.scrape_information(tg_report)
                        except Exception as e:
                            print('fail', e)
                            pdf_document.close()
                            continue
                    
                    elif report_type == 'Standard':
                        continue

                    elif report_type == 'BMTF':
                        continue

                    elif report_type == 'Anticimex':
                        continue
                    
                    pdf_document.close()
                    print(code, info, report_type, information)

                    continue
                    # Find matrikkel id
                    snr = 0
                    if 'snr' in list(info.keys()):
                        snr = info['snr']
                    
                    matrikkel_id = gapi.findMatrikkelForidents(kommunenummer=info['kommune'], gnr=info['gnr'], bnr=info['bnr'], seksjonsnummer=snr)
                    
                    # If matrikkel_id is not found, just register the extraction of the report, without updating eiendom info
                    if matrikkel_id:
                        # If found the element matrikkel is already registered and we need to move and delete data to avoid duplication
                        try:
                            eiendom_instance = EiendomInfo.objects.get(matrikkel=matrikkel_id)
                            old_eiendom_instance = FinnData.objects.get(finn=code).eiendom
                            
                            # Reassign all the data to the correct eiendom id
                            finndata_instance = FinnData.objects.get(finn=code)
                            finndata_instance.eiendom = eiendom_instance
                            finndata_instance.save()

                            eiendomsdatalog_instance = EiendomsDataLog.objects.get(eiendom=old_eiendom_instance)
                            eiendomsdatalog_instance.eiendom = eiendom_instance
                            eiendomsdatalog_instance.save()

                            salgsoppgave_instance = Salgsoppgave.objects.get(eiendom=old_eiendom_instance)
                            salgsoppgave_instance.eiendom = eiendom_instance
                            salgsoppgave_instance.save()

                            # Delete the old eiendom id
                            old_eiendom_instance.delete()

                            #print(matrikkel_id, 'is present in model, needs to merge the data into the existing one')
                        
                        except EiendomInfo.DoesNotExist:
                            eiendom_instance = FinnData.objects.get(finn=code).eiendom
                            eiendom_instance.matrikkel_id = matrikkel_id
                            eiendom_instance.save()
                            #print(matrikkel_id, 'is not present in the model')
                        
                    
                    print('dwadwadwadawdwadawdawdawdwad')
                    # Save information in database
                    eiendom_instance = FinnData.objects.get(finn=code).eiendom
                    tilstandsrapport_instance = Tilstandsrapport(eiendom=eiendom_instance, filepath=f'tilstandsrapport/{code}.pdf',
                                                                balkong=information['balkong'], parkett=information['parkett'],
                                                                p_rom=information['p_room'], bra=information['BRA'])
                    if 'UTVENDIG' in information:
                        tilstandsrapport_instance.utvendig = information['UTVENDIG']
                    if 'INNVENDIG' in information:
                        tilstandsrapport_instance.innvendig = information['INNVENDIG']
                    if 'VÅTROM' in information:
                        tilstandsrapport_instance.innvendig = information['VÅTROM']
                    if 'KJØKKEN' in information:
                        tilstandsrapport_instance.innvendig = information['KJØKKEN']
                    if 'TEKNISKE INSTALLASJONER' in information:
                        tilstandsrapport_instance.innvendig = information['TEKNISKE INSTALLASJONER']
                    if 'TOMTEFORHOLD' in information:
                        tilstandsrapport_instance.innvendig = information['TOMTEFORHOLD']
                    tilstandsrapport_instance.save()

                    # saves the new pdf document and register it
                    try:
                        pdf_document.save(f'C:/Users/mikae/Desktop/takstrapport/v2/backend/files/tilstandsrapport/{code}.pdf', garbage=3, deflate=True)
                    except FileExistsError:
                        pass
                    pdf_document.close()
        
        raise Exception

#######################################################################################################################################

class NorskTakst(object):
    def __init__(self, doc='', filepath=''):
        if filepath:
            self.doc = fitz.open(filepath)
        else:
            self.doc = doc
        self.headlines = {'Dette trenger du å vite om tilstandsrapporten': (32.003, 89.203, 476.5404, 113.203), 
                        'Beskrivelse av eiendommen': (32.995, 96.403, 304.8524, 120.403), 
                        'Sammendrag av boligens tilstand': (33.987, 96.403, 361.4688, 120.403),
                        'Tilstandsrapport': (32.003, 96.403, 192.2501, 120.403), 
                        'Arealer, byggetegninger og brannceller': (36.595, 85.2014, 451.3152, 112.0139),
                        'Arealer': (14.995, 89.912, 108.1302, 113.912), 
                        'Konklusjon og markedsvurdering': (47.297, 133.634, 349.669, 154.891),
                        'Befarings - og eiendomsopplysninger': (14.995, 85.7684, 437.6351, 112.5809),
                        'Beregninger': (47.297, 133.634, 171.728, 154.891), 
                        'Kilder og vedlegg': (14.995, 89.203, 203.1479, 113.203), 
                        'Tilstandsrapportens avgrensninger': (32.003, 89.203, 369.6982, 113.203)}
        
        # TG IMAGES: width 30, height 12.75, standard, aspect ratio = 2.3529
        self.basepath = 'C:/Users/mikae/Desktop/takstrapport/v2/backend/main/management/engine/media/'
        self.detection_images = {'banner': {'position': (0.0, 72.75, 560.25, 126.75), 'filepath': f'{self.basepath}NorskTakst/banner.jpg'},
                                'top_left_icon': {'position': (0.0, 0.0, 208.5, 202.5), 'filepath': f'{self.basepath}NorskTakst/top_left_icon.jpeg'},
                                'top_right_logo': {'position': (490.5, 36.0, 555.0, 100.5), 'filepath': f'{self.basepath}/NorskTakst/top_right_logo.jpg'},
                                'TG0': {'position': (545.25, 408.0, 575.25, 420.75), 'filepath': f'{self.basepath}/NorskTakst/tg0.jpg'},
                                'TG1': {'position': (247.5, 596.25, 277.5, 609.0), "filepath": f'{self.basepath}/NorskTakst/tg1.jpg'},
                                'TG2': {'position': (247.5, 273.75, 277.5, 286.5), 'filepath': f'{self.basepath}/NorskTakst/tg2.jpg'},
                                'TG22': {'position': (247.5, 273.75, 277.5, 286.5), 'filepath': f'{self.basepath}/NorskTakst/tg22.jpg'},
                                'TG3': {'position': (247.612, 426.75, 277.612, 439.5), 'filepath': f'{self.basepath}/NorskTakst/tg3.jpg'},
                                'TGIU': {'position': (545.25, 615.0, 575.25, 627.75), 'filepath': f'{self.basepath}NorskTakst/tgiu.jpg'}, 
                                }

        self.tg_headlines = {'VÅTROM': ['Overflater vegger og himling', 'Overflater Gulv', 'Sluk, membran og tettesjikt', 
                                        'Sanitærutstyr og innredning', 'Ventilasjon', 'Fukt i tilliggende konstruksjoner'],
                            'UTVENDIG': ['Taktekking', 'Takkonstruksjon/Loft', 'Vinduer', 'Balkonger, terrasser og rom under balkonger']}

    # Detects if a page is Norsk takst and organize it, can input previous page for better organising
    def detect_page(self, page, last_page_data=[]):

        banner_position = self.detection_images['banner']['position']
        banner_aspect_ratio = (banner_position[2] - banner_position[0]) / (banner_position[3] - banner_position[1])
        banner_width = banner_position[2] - banner_position[0]
        banner_image = Image.open(self.detection_images['banner']['filepath'])

        icon_position = self.detection_images['top_left_icon']['position']
        icon_aspect_ratio = (icon_position[2] - icon_position[0]) / (icon_position[3] - icon_position[1])
        icon_width = icon_position[2] - icon_position[0]
        icon_image = Image.open(self.detection_images['top_left_icon']['filepath'])

        logo_position = self.detection_images['top_right_logo']['position']
        logo_aspect_ratio = (logo_position[2] - logo_position[0]) / (logo_position[3] - logo_position[1])
        logo_width = logo_position[2] - logo_position[0]
        logo_image = Image.open(self.detection_images['top_right_logo']['filepath'])

        found_page = False
        address = {'gnr': ''}
        page_summary = {}
        aspect_found = 1
        last_info = ''
        gnr_bnr_snr2 = ''
        #print(page.number)

        # A quick check for text, to speed up progress
        if Takst.detect_text(page, 'Oppdragsnr'):
            image_xrefs = {}
            for image in page.get_images():
                image_xrefs[image[0]] = ''

            widt_range = range(int(page.rect[0]), int(page.rect[2]), 1)
            for xref in list(image_xrefs.keys()):
                
                # Sort the xref values so it starts at the top of the page
                rect_list = sorted(page.get_image_rects(xref), key=itemgetter(1))

                if rect_list:
                    for position in rect_list:
                        
                        # If True image is present, continue check
                        if int(position[0]) in widt_range and int(position[2]) in widt_range:

                            # Loads image_data
                            aspect_ratio = (position[2] - position[0]) / (position[3] - position[1])
                            image_width = position[2] - position[0]
                            image_height = range(int(position[1]), int(position[3]), 1)
                            image_image = self.doc.extract_image(xref)
                            image_bytes = image_image["image"]
                            image = Image.open(io.BytesIO(image_bytes)).convert('RGB')
                            #image.save(f'temp/img{xref}.png')

                            # Compare image to Front page_icon
                            if round(aspect_ratio, 2) == round(icon_aspect_ratio, 2):
                                if Takst.compare_images(image, icon_image):
                                    return ['Front page'], icon_width/image_width, {}
                            
                            # Compare image to banner
                            elif round(aspect_ratio) == round(banner_aspect_ratio):
                                if Takst.compare_images(image, banner_image):
                                    
                                    # If the banner image is found, determine the context of it
                                    for block in page.get_textpage().extractDICT(sort=True)['blocks']:
                                        for line in block['lines']:
                                            for span in line['spans']:
                                            
                                                # This method only active if last_page_data, Experimental might not find gnr all the time
                                                if last_page_data and not page_summary:
                                                    regex = r"^Gnr\s[a-zA-Z0-9]+\s-\sBnr\s[a-zA-Z0-9]+"
                                                    
                                                    # stores all address information, so we can compare data to GAPI
                                                    if re.match(regex, span['text'].strip()) and not address['gnr']:

                                                        # Stores the ids
                                                        gnr_bnr_snr2 = span['text'].strip()
                                                        gnr_bnr_snr = gnr_bnr_snr2.split('-')
                                                        address['gnr'] = re.search(r'\d+', gnr_bnr_snr[0]).group()
                                                        if len(gnr_bnr_snr) > 1:
                                                            address ['bnr'] = re.search(r'\d+', gnr_bnr_snr[1]).group()
                                                        if len(gnr_bnr_snr) > 2:
                                                            address['snr'] = re.search(r'\d+', gnr_bnr_snr[2]).group()

                                                        address['address'] = last_info
                                                        space_number = 0

                                                    elif address['gnr']:
                                                        if gnr_bnr_snr2 == last_info:
                                                            address['kommune'] = span['text'].strip().split(' ')[0]
                                                        space_number += 1
                                                    
                                                    last_info = span['text'].strip()
                                                
                                                    
                                                # This method checks that the headline is within the rect of the image
                                                if int(span['bbox'][1]) in image_height and int(span['bbox'][3]) in image_height:
                                                    
                                                    # If text found matches criteria and contains headline
                                                    if span['color'] == 16777215:
                                                        for headline in self.headlines.keys():
                                                            if headline == span['text'].strip():

                                                                # if True there is empty text before the banner that belongs to previous page banner
                                                                if last_page_data and not page_summary and address['gnr']:
                                                                    # If true the distance between gnr code and banner was correct and no middle text
                                                                    if space_number != 4:
                                                                        page_summary[last_page_data[-1]] = int(position[1] - 10)
                                                                page_summary[headline] = int(position[1])
                            
                            # Compare image to logo, 
                            elif round(aspect_ratio, 2) == round(logo_aspect_ratio, 2) and found_page != True:
                                if Takst.compare_images(image, logo_image):
                                    aspect_found = logo_width/image_width
                                    found_page = True
            
            # Banner items was found
            if page_summary:
                return sorted(page_summary), aspect_found, address
            
            # No banner was found but page was apart of NorskTakst
            elif found_page:
                if last_page_data:
                    if last_page_data[-1] != 'Front page':
                        return [last_page_data[-1]], aspect_found, address
                    else:
                        return ['Unknown'], aspect_found, address
                else:
                    return ['Unknown'], aspect_found, address

        return [], 1, {}
    
    def detect_report(self):
        new_document = fitz.Document()
        headlines_included = {}
        page_summary = []
        headline = ''
        report = {}
        info_list = []
        #Takst.print_progress_bar(0, self.doc.page_count, prefix = 'Progress:', suffix = 'Complete', length = 50)
        #print('dwadw')
        # Goes over each page in document and checks if it's' part of a report
        for page_number in range(len(self.doc)):
            #print('iugiug')
            page = self.doc.load_page(page_number)
            
            #print(page_number)
            page_summary, aspect_found, info = self.detect_page(page, page_summary)
            #print('dd')
            if info:
                info_list.append(info)

            if page_summary:
                if headline and headline != 'Front page' and page_summary[-1] == 'Unknown':
                    page_summary = [headline]
                headline = page_summary[-1]
                report[page.number] = page_summary

                for head in page_summary:
                    headlines_included[head] = ''

                # Inserts the page into the pdf
                new_document = Takst.merge_pdfs(page, self.doc, new_document)       

            #Takst.print_progress_bar(page.number + 1, self.doc.page_count, prefix = 'Progress:', suffix = 'Complete', length = 50)
        
        headlines_included = list(headlines_included.keys())

        if info_list:
            dict_count = Counter(tuple(sorted(d.items())) for d in info_list)
            # Find the dictionary that appears the most number of times
            info = dict(dict_count.most_common(1)[0][0])
        #print('dwadwadwa')
        return report, new_document, info

    def scrape_tg(self, pages):
        floor = ''
        category = ''
        last_headline = ''
        tg_dict_eval = {}

        for page in pages:
            page = self.doc.load_page(page)

            tg_dict = {'tg0': Image.open(f'{self.basepath}/NorskTakst/tg0.jpg'), 'tg1': Image.open(f'{self.basepath}/NorskTakst/tg1.jpg'),
                       'tg2': Image.open(f'{self.basepath}/NorskTakst/tg2.jpg'), 'tgiu': Image.open(f'{self.basepath}/NorskTakst/tgiu.jpg'),
                       'tg22': Image.open(f'{self.basepath}/NorskTakst/tg22.jpg'), 'tg3': Image.open(f'{self.basepath}/NorskTakst/tg3.jpg')}

            
            # Cuts page in two columns, this is to make sure that it follows the right order
            d = fitz.Rect(page.cropbox_position, page.cropbox_position)
            column1 = fitz.Rect((page.rect[0], page.rect[1]), (page.rect[2]*0.5, page.rect[3])) + d
            column2 = fitz.Rect((page.rect[2]*0.5, page.rect[1]), (page.rect[2], page.rect[3])) + d

            # Creates a temporary pdf document to work with the page columns
            temp_pdf = fitz.Document()
            for column in [column1, column2]:
                column_page = temp_pdf.new_page(-1, width = column.width, height = column.height)
                column_page.show_pdf_page(column_page.rect, self.doc, page.number, clip = column)

                # Maps every image on page and identifies the images by xref that is tg symbol
                tg_images = {}
                for image in column_page.get_images():
                    xref = image[0]
                    rect = column_page.get_image_rects(xref)

                    image_image = temp_pdf.extract_image(xref)
                    image_bytes = image_image["image"]
                    image = Image.open(io.BytesIO(image_bytes)).convert('RGB')
                    #image.save(f'temp/img{xref}.jpg')
                    if rect:
                        for tg in tg_dict.keys():
                            if Takst.compare_images(image, tg_dict[tg], parameter=1000):
                                tg_images[xref] = {'image': image, 'rect': rect, 'tg': tg}

                # Iterates over every text element in column
                for text_block in column_page.get_textpage().extractDICT(sort=True)['blocks'][1:]:
                    if text_block['lines'][0]['spans']:
                        font = text_block['lines'][0]['spans'][0]['font']
                        color = text_block['lines'][0]['spans'][0]['color']
                        text = text_block['lines'][0]['spans'][0]['text'].strip()

                        # Found a subject headline
                        if color == 992300 and font == 'Calibri,Bold':
                            text_position = text_block['bbox']

                            # Iterate over all images to find image where height is equal to headline, (Need to also check x cord, so it doesnt match with sibling headline)
                            for image in column_page.get_text('blocks'):
                                if image[6] == 1:
                                    
                                    # If image is on line with text
                                    image_position = (image[0], image[1], image[2], image[3])
                                    diff = image_position[3] - text_position[3]
                                    if diff < 2 and diff > -2:

                                        # Iterate over all xref image rect to find the image that we have found
                                        for xref_image in tg_images.keys():
                                            if image_position in tg_images[xref_image]['rect']:
                                                
                                                # Inserts the rating at the right location, only inserting if category determined
                                                if category and floor == '':
                                                    last_headline = text
                                                    tg_dict_eval[category][last_headline] = {'tg': tg_images[xref_image]['tg'], 'comment': []}
                                                elif category and floor:
                                                    last_headline = text
                                                    tg_dict_eval[category][floor][last_headline] = {'tg': tg_images[xref_image]['tg'], 'comment': []}

                                                
                        # Found a floor headline
                        elif color == 416873 and '>' in text and font == 'Calibri':
                            # If a category have been selected
                            if category:
                                tg_dict_eval[category][text] = {}
                                floor = text
                            last_headline = ''

                        # Found a category headline
                        elif color == 416873 and '>' not in text and font == 'Calibri':
                            category = text
                            tg_dict_eval[category] = {}
                            floor = ''
                            last_headline = ''

                        # This indicates that it's a TG comment
                        elif color == 0:
                            text = ''
                            for line in text_block['lines']:
                                for span in line['spans']:
                                    text += span['text']

                            if last_headline:
                                if category and floor:
                                    tg_dict_eval[category][floor][last_headline]['comment'].append(text)
                                elif category:
                                    tg_dict_eval[category][last_headline]['comment'].append(text)

            temp_pdf.close()                
        # Dict cleanup, if pages that is not TILSTANDSRAPPORT were given this removes all unclassified data
        #tg_dict_eval = {k: v for k, v in tg_dict_eval.items() if v}
        return tg_dict_eval

    def tg_reformat(self, tg_dict_eval):
        information = {}

        tg_dict = {'tg0': 0, 'tg1': 1, 'tg2': 2, 'tg22': 2, 'tg3': 3, 'tgiu': ''}

        allowed_tg = ['INNVENDIG', 'VÅTROM', 'KJØKKEN', 'TEKNISKE INSTALLASJONER', 'UTVENDIG', 'TOMTEFORHOLD']

        # Looking for presence of variables
        def presence_of_variables(dict_section, category, value, information):
            if category == 'INNVENDIG' and value == 'Overflater':
                for comment in dict_section[value]['comment']:
                    if 'parkett' in comment.lower():
                        information['parkett'] = True
            elif category == 'UTVENDIG':
                if 'balkong' in value.lower():
                    information['balkong'] = True
            return information

        for category in tg_dict_eval:
            if category in allowed_tg:
                information[category] = []
                for value in tg_dict_eval[category]:
                    if 'tg' not in tg_dict_eval[category][value].keys():
                        for value2 in tg_dict_eval[category][value]:
                            dict_section = tg_dict_eval[category][value]

                            tg_value = tg_dict[dict_section[value2]['tg']]
                            if tg_value:
                                information[category].append(tg_value)
                                information = presence_of_variables(dict_section, category, value, information)

                    else:
                        dict_section = tg_dict_eval[category]
                        tg_value = tg_dict[dict_section[value]['tg']]
                        if isinstance(tg_value, int):
                            information[category].append(tg_value)
                            information = presence_of_variables(dict_section, category, value, information)
                
                if information[category]:
                    information[category] = mean(information[category])
                else:
                    del information[category]
        
        if 'balkong' not in list(information.keys()):
            information['balkong'] = False
        if 'parkett' not in list(information.keys()):
            information['parkett'] = False

        return information

    def scrape_bra(self, pages):
        for page_number in pages:
            page = self.doc[page_number]
            for text in page.get_text('blocks'):
            
                if text[6] == 0:
                    text = text[4].strip()
                    if 'Areal (BRA):' in text:
                        integers = re.findall(r'\s\d+\s', text)
                        return {'BRA': sum([int(i) for i in integers])}
        return {'BRA': None}

    def scrape_room(self, pages):

        room_text = ''
        room_dict = {}
        p_room = None
        for page_number in pages:
            page = self.doc.load_page(page_number)
            data = False

            for text_block in page.get_textpage().extractDICT(sort=True)['blocks']:
                text_first_column = text_block['lines'][0]['spans'][0]['text'].strip()
                font = text_block['lines'][0]['spans'][0]['font']
                
                # When etasje element is found, the next rows will contain the data
                if 'Etasje' == text_first_column and font == 'Calibri,Bold':
                    data = True

                    bbox_data = text_block['lines'][3]['spans'][0]['bbox']
                    range_data = range(int(bbox_data[0]), int(bbox_data[2]), 1)
                    
                # This means the end of the table have been reached
                elif 'Sum' == text_first_column and font == 'Calibri,Bold':
                    p_room = text_block['lines'][2]['spans'][0]['text'].strip()
                    break

                # Data row is found
                elif data:
                    for line in text_block['lines']:
                        if int(line['bbox'][0]) in range_data: # If the text line starting position is within the designated area
                            for text in line['spans']:  # iterates over all text in the line
                                if not text['text'].isnumeric():  # If the text given is not a number
                                    
                                    # Makes adjustment to text so it is easier to differentiate
                                    text = text['text'].replace(' ', '')
                                    text = re.sub(r'\d+,\d+', '', text)
                                    room_text += text

        room_dict['text'] = room_text
        sleeping_rooms = 0
        rooms = 0

        for key in room_dict:
            for room in room_dict[key].split(','):
                try:
                    float(room)
                except ValueError as e:
                    if 'soverom' in room.lower():
                        sleeping_rooms += 1
                    rooms += 1
        # 'rooms': rooms, 'sleeping_rooms': sleeping_rooms, 
        return {'p_room': p_room}, room_dict

    def scrape_information(self, report):
        
        information = {}
        room_pages = []
        tg_pages = []
        bra_pages = []

        for page in report.keys():
            try:
                test = self.doc.load_page(page)
            except:
                continue
            for headline in report[page]:
                if headline == 'Tilstandsrapport':
                    tg_pages.append(page)
                elif headline == 'Arealer':
                    room_pages.append(page)
                elif headline == 'Front page' or headline == 'Unknown':
                    bra_pages.append(page)

        print(tg_pages, len(self.doc))
        tg_dict_eval = self.scrape_tg(tg_pages)
        #print(tg_dict_eval)
        #with open("tg_eval_dict.json", "w") as outfile:
        #    json.dump(tg_dict_eval, outfile)
        print('bog1')
        tg_info = self.tg_reformat(tg_dict_eval)
        information.update(tg_info)
        print('bog2')
        room_info, room_dict = self.scrape_room(room_pages)
        information.update(room_info)
        print('bog3')
        try:
            bra_info = self.scrape_bra(bra_pages)
            information.update(bra_info)
        except:
            pass

        return information
`

When i run the script i just call the takst.extract_statusreports() and provide it with a json document containing filenames

**Comment by Nurskss** [comment]
Its mainly the adjust_pdf function that encounters the errors when it iterates over the pages and use page.rect, but sometimes the error happens at other page iterations. it seems quite random, 

Do you need any more info or logs or anything?

**Comment by JorjMcKie** [comment]
Analyzed the situation:
* there is indeed a recursion problem in the file
* but: PyMuPDF does not correctly catch the exception, so the script ends without comment.

So this is indeed a bug. Developed a solution which will properly raise a Python exception.
When this happens in your daily life - even after being fixed - it is probably still no fun. So you may want to implement a circumvention, which you also can use today:

```python
import fitz
doc=fitz.open("265968270.pdf")
def myrect(page):
    cb = page.cropbox
    w, h = cb.width, cb.height
    if page.rotation not in (0, 180):
        w, h = h, w
    return fitz.Rect(0, 0, w, h)

for page in doc:
    print(page.number, myrect(page))
```

**Comment by JorjMcKie** [comment]
BTW I am thinking about **_not_** to raise an exception, but let the warning occur and return the mentioned fallback.

**Comment by JorjMcKie** [comment]
Ok, here is the solution after the fix:
```python
In [1]: import fitz
In [2]: doc = fitz.open("265968270.pdf")
In [3]: for page in doc:
   ...:     print(page.number, page.rect)
   ...:
too much recursion in tree (parents)
0 Rect(0.0, 0.0, 841.89, 595.276)
too much recursion in tree (parents)
1 Rect(0.0, 0.0, 841.89, 595.276)
too much recursion in tree (parents)
2 Rect(0.0, 0.0, 841.89, 595.276)
too much recursion in tree (parents)
3 Rect(0.0, 0.0, 841.89, 595.276)
too much recursion in tree (parents)
4 Rect(0.0, 0.0, 841.89, 595.276)
too much recursion in tree (parents)
5 Rect(0.0, 0.0, 841.89, 595.276)
too much recursion in tree (parents)
6 Rect(0.0, 0.0, 841.89, 595.276)
too much recursion in tree (parents)
7 Rect(0.0, 0.0, 841.89, 595.276)
too much recursion in tree (parents)
8 Rect(0.0, 0.0, 841.89, 595.276)
9 Rect(0.0, 0.0, 841.8900146484375, 595.2755737304688)
10 Rect(0.0, 0.0, 841.8900146484375, 595.2755737304688)
11 Rect(0.0, 0.0, 841.8900146484375, 595.2755737304688)
12 Rect(0.0, 0.0, 841.8900146484375, 595.2755737304688)
13 Rect(0.0, 0.0, 841.8900146484375, 595.2755737304688)
...
```

**Comment by Nurskss** [comment]
Thanks so much for the help!

**Comment by JorjMcKie** [comment]
You must have introduced another problem. What is `self` here. And `self.myrect()`?

**Comment by Nurskss** [comment]
The self is just the class that initializes the pdf document, but i noticed when i ran page.seach_for() it rises an error correctly so i just made a try-except clause at the start for every pdf document and it manages to detect all of the bugged documents correctly
