### ISSUE TITLE
Error loading _fitz: Operation not permitted

### ISSUE THREAD

**Issue by bryankaplan** [pymupdf/PyMuPDF#2342]
## Describe the bug (mandatory)

Working in a virtual environment on Alpine Linux, when I `import fitz` I get the following error:

```
ImportError: Error loading shared library [REDACTED PATH]/venv/lib/python3.10/site-packages/fitz/_fitz.cpython-310-x86_64-linux-gnu.so: Operation not permitted
```

`ls -l` reports that I am the owner and group-member for that library, and it has 0755 permissions.

## To Reproduce (mandatory)

0. Use Alpine Linux.
1. Set up a venv and activate it.
2. pip install PyMuPDF
3. in `ipython` or a python script, `import fitz`.

## Expected behavior (optional)

Import succeeds without error.

## Your configuration (mandatory)

* Alpine Linux 3.17.2
* Python 3.10.10
* PyMuPDF 1.21.1, installed via pip

**Comment by bryankaplan** [comment]
Hmm, I tried it under Arch Linux and got:
```
ImportError: [REDACTED PATH]/venv/lib/python3.10/site-packages/fitz/_fitz.cpython-310-x86_64-linux-gnu.so: failed to map segment from shared object
```
I don't know if that's related.

**Comment by julian-smith-artifex-com** [comment]
Is your venv in a no-exec filesystem? I think this could cause what you're seeing.

Could try installing and importing a different Python package that uses compiled code, such as `numpy`?

BTW PyMuPDF-1.22.0 was released four days ago on 2023-04-14 (Friday). I don't think anything has changed that might effect what you're seeing, but it might be worth trying this later release with:

    `python -m pip install --upgrade PyMuPDF`

**Comment by bryankaplan** [comment]
@julian-smith-artifex-com **Thank you.** When I read your thought that my fs is no-exec, I thought for certain that's wrong. Twenty minutes of experimentation later, long story short, you're right. Thank you so much. I learned something valuable here.
