### ISSUE TITLE
Turn off print statements in utils.py

### ISSUE THREAD

**Issue by Ulipenitz** [pymupdf/PyMuPDF#2345]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.

When I run the insert_pdf() method on a pdf, I sometimes get hundreds of print statements like these: 
print("cannot create /Annot for kind: " + str(l["kind"]))

**Describe the solution you'd like**

I want to be able to turn them off, so that my terminal is not overloaded.

**Describe alternatives you've considered**
Are there several options for how your request could be met?

Maybe logging could be used instead of print statements

**Additional context**

**Comment by JorjMcKie** [comment]
You can exclude annotations and / or links from being copied alongside their pages:

```python
doc.insert_pdf(src, from_page=f, to_page=t, annots=False, links=False)
```
Then copying these objects will be suppressed and no messages will be issued. The default is copying these object types.
For me, a message informing about failing to do desired actions is worth reporting.
I can look whether it s possible to re-route the warnings to the MuPDF container, so they can be viewed via `fitz.TOOLS.mupdf_warnings()` as desired.

**Comment by JorjMcKie** [comment]
Again thinking about it:
These messages actually make no sense in any case, because they in essence simply say, that something went wrong without being able to mention the actual cause, not to speak of ways to fix it. So I will simply omit the messages I think.

**Comment by backnotprop** [comment]
How do we debug this? agree with @JorjMcKie

**Comment by backnotprop** [comment]
I cant suppress the logging with or without the `annots=False,` param.
