### ISSUE TITLE
How can i get the source code of the swig file(such as fitz.i ) ?

### ISSUE THREAD

**Issue by JoyChenNo1** [pymupdf/PyMuPDF#2352]

**Comment by JorjMcKie** [comment]
Look here: https://github.com/pymupdf/PyMuPDF/tree/master/fitz

**Comment by JoyChenNo1** [comment]
> Look here: https://github.com/pymupdf/PyMuPDF/tree/master/fitz

I want to directly use some functions like xref_get_keys in my C++ source code(use mupdf), but I just found the swig file in the fitz.i.How can I get those C implement function?
