### ISSUE TITLE
text extracted is not good

### ISSUE THREAD

**Issue by urup32** [pymupdf/PyMuPDF#2360]
_**Please provide all mandatory information!**_
text extracted is not readable.

## Describe the bug (mandatory)
Extracting text from some pdfs generated by external organitzation show text unreadable. Anyway with looking with  any visor (okular, pdfreader) text is good, and is text not image.
## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.
With attached file:

import fitz
doc=fitz.open("test.pdf")
for page in doc:
    print(page.get_text("text",sort=True)

Result is 
'\r\x10\x11\x12\x11\x13\x14\x15\x16\x11�\x17\x18\n\x19\x18\x15\x1a\t�\t\x14\x19�\x17\x18\x10\n\r\x1b\x1c\x12\x14�\x1c\x18\x1b\x12\x15\x14\n\x1d\x1b\x17\t�\t\x11\x10\n�\x01\x02\x03\x04\x05\x06\x07�\t\x02\x06\n\x0b\x0c\x07\x05�\r\x07\x06\x0c\x0e\x0f\x01\x02\x0e\x01\n\x17\x07\x06\x01\x03�\r\n\x06\x0e\x1e\x0e\x1f\x02\n\x1c �\r\x0c\x01\x1e\n!\x0e\x0f\x0e\n\x02\x06\x01"#$%&\'())*\n\x1c �\x17\x01\x1e\x04\x0f\n\x02\x06\x01"#&&*+,+*%-\n\x18.\n\x0c\x1e\x0e\x1e\x0e\x01�/\x0e\x03\x1e\x07\x05"#()((\n\x13\n\x1e0\x07�!\n�\n\x0f\x0e\x03\x0e\x1f\x02"#)%#123456#()(&#7("&%\n\x19\n\x0c8\x0e\x1e\x0e\x01\x03��\x01\x02\x03\x04\x05\x06\x07!\x01\x03\n\x11\x18\x11\x12�;�\r\n\x0c\x1e\n<\x1e\x0e\x01\x02\n\x03�=\x0f\x01!>9:\n?@ABC\nDEFGH35#E1IJFEKEL31M#NEJ#3LFEOE131IN#ILMJPQEL3N6\n\x11\x18\x11\x12�;�\t\x11\x18C\n\x11\x18\x11\x12�;��\x04\n\x02\x06\x07\x03\x11\x0f<\x05\x0e\x07!\x07\x039:\n=\x0f\x01!>�?@RBC\n\x11\x18\x11\x12�;�\x13\x01\x02!\x01\t\x028\n\x0c\x03\x0e\x01\x02\n\x03DEFGH35#E1IJFEKEL31M#NEJ#13FMN6\n=\x0f\x01!>�?STBC\n9:\n\x19\x18\r\x18�;�\r\x0c\n\x03\x06\x07\x1e\x0e\x01\x02\n\x03C\n)))&#U55M56#V3#WI5NMJ3#NMHELEF313#JM#IN#FEFGH35#1I#W5INF3LEPJ#M#JM#FEIJI#W5INF3LEMJIN#IJ\n3HF36\n\t\x1c\x19\x19�;�\r\x0c\n\x03\x06\x07\x1e\x0e\x01\x02\n\x03C\n\x18\x02\x06\x0e!\x07!\n\x03�\x13\x0e\x02\x07\x02\x1e\x0e\n\x0c\x07\x03�;9:\n�\x01\x02\x03\x04\x05\x06\x07\x03�<\x01\x0c�\x1c\t\x13C\n\x11\x18\x11\x12�;�\r\n\x0c\x1e\n<\x1e\x0e\x01\x02\n\x03�=\x0f\x01!>�?@AB\nXUDUYUZ9X\n[V\\]U\n^_`[V\\]U\nabc9XDU^\naYdXU^9#\\\n[D\\\nabc9XDU^\naVD\nd\\^D9^\nZUZ_[a`VU XUeUXUY[a\nd+&7%*$%)\n)\naYdX6\\#[D\\"\n)h))\nXUcUX6")h))\n76i)ih*)\n,(&$$i+7*)\n%\nUbcVU\\Z9\n^#c9X\n[_UYD\\\n\\fUY\\#UY\ndUYUX\\V\nXUDXa`_[a\ngY"\n(76*%7h((\nXUDUY[agY\n"(6$$&hi7\n]\\V9X\\[ag\nY")h))\naYdX6\\\n[D\\6"#)h))\naYdX6\\\n[D\\6XUcUX\n[6)h))\nXUDXa`_[a\n9Y"#)h))\nXUDUY[a9Y\n"#)h))\n]\\V9X\\[a9\nY"#)h))\nV3#EJKM5Q3LEPJ#M4FIJE13#3#F53OlN#1IH#cGJFM#YIGF5M#fG1ELE3H#mJEL3QIJFI#WGI1I#GFEHEn35NI#IJ#IH#Q35LM#1IH#W5MLI1EQEIJFM#oG1ELE3H#LM55INWMJ1EIJFIh#NEJ#pGI#WGI13#LMQGJEL35NI#3#FI5LI5MN#KGI53#1I#HMN\nL3NMN#WI5QEFE1MN#WM5#IH#M51IJ3QEIJFM#oG5q1ELM6##ZELr3#EJKM5Q3LEPJh#LG3J1M#NI#5IKEI53#3#13FMN#WI5NMJ3HINh#INFj#NMQIFE13#3H#XIkH3QIJFM#dIJI53H#1I#c5MFILLEPJ#1I#Z3FMN#s#H3#VIs#95kjJEL3#&\'()7,h#1I#%\n1I#1ELEIQ45Ih#1I#c5MFILLEPJ#1I#Z3FMN#s#d353JFq3#1I#ZI5ILrMN#ZEkEF3HIN6#UH#WI5NMJ3H#pGI#3LLI13#3#INF3#EJKM5Q3LEPJ#INFj#NMQIFE1M#3H#LGQWHEQEIJFM#1IH#1I4I5#1I#NIL5IFM6#UH#F53F3QEIJFM#1I#INF3\nEJKM5Q3LEPJ#1I4I5j#5I3HEn35NI#5INWIF3J1M#H3N#LM55INWMJ1EIJFIN#QI1E13N#1I#NIkG5E131#pGI#k353JFELIJ#NG#EJFIk5E131h#1ENWMJE4EHE131#s#LMJKE1IJLE3HE1316\ncjkEJ3#7#1I\n%\')i\'(&#7("&+\n#i\n'

For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).
It must return  text correctly

## Screenshots (optional)
$pdffonts test.pdf
 name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
[none]                               Type 3            Custom           yes no  no     151  0

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).
OS Ubuntu 22.04.2
Python 3.10.6
PyMuPDF 1.22.0
For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).
3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] 
 linux 
 
PyMuPDF 1.22.0: Python bindings for the MuPDF 1.22.0 library.
Version date: 2023-04-14 00:00:01.
Built for Python 3.10 on linux (64-bit).
## Additional context (optional)
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/11261422/test.pdf)

**Comment by JorjMcKie** [comment]
This is no bug, but a problem of the file itself.
Confirmed this by using a number of alternative tools, and none worked.
All you can do is OCR the page.
