### ISSUE TITLE
PyMuPDF 1.22.1 version is producing Type Error while extracting drawings from PDFs

### ISSUE THREAD

**Issue by SirishaGorasa** [pymupdf/PyMuPDF#2365]
Hello,

**I am trying to extract drawings using 'page.get_drawings()' and also using 'page.get_cdrawings()' from a PDF.**

I am getting the below error while using page.get_drawings()
![image](https://user-images.githubusercontent.com/47634813/233572420-d0972bba-7a0e-4a98-92e9-37a421371378.png)

And the below error with page.get_cdrawings()
![image](https://user-images.githubusercontent.com/47634813/233572451-c4b5e6b3-cc37-4f36-92cc-9d385712f47b.png)
**Both of them indicate a Type Error. May I know why is this happening ??**

**Comment by JorjMcKie** [comment]
You probably get this error when trying to **_draw_** - not when **_extracting_** drawings.
This is due to a change pertaining to compatibility of joins of a "fill" and a "stroke" path. As opposed to the previous behaviour, value irrelevant to either "fill" or "stroke" are now set to `None`, like `fill_opacity` will be `None` in a stroke path.

**Comment by SirishaGorasa** [comment]
Thanks @JorjMcKie, I fixed it now by adding an existence check. But unfortunately, I now see overlap/bold borders for rectangles which I have created using the output of get_cdrawings(). E.g.: seems like a rectangle drawn again over it.

**Comment by JorjMcKie** [comment]
Found the problem:
All fill-stroke paths are generated automatically by PyMuPDF by joining a **_fill_** followed by a **_stroke_** under certain conditions.
In the most recent version, I forgot to remove the old defalt values `None` for fill color and fill opacity. So fill-strokes had `None` for these two key/values.
This has been fixed and should be published with the next version.

**Comment by SirishaGorasa** [comment]
Thanks for resolving the issue. May I know if this is fixed in the version 1.22.3??

**Comment by JorjMcKie** [comment]
> Thanks for resolving the issue. May I know if this is fixed in the version 1.22.3??

No, not yet, sorry.

**Comment by SirishaGorasa** [comment]
Okay, fine. May I know when can we expect this issue being resolved?

**Comment by JorjMcKie** [comment]
> Okay, fine😊. May I know when can we expect a version with this issue resolved?

The new version is in the making. Currently there is no date fixed.

**Comment by SirishaGorasa** [comment]
Sure. Thanks a lot for quick response.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.22.5.

**Comment by AbdirayimovS** [comment]
> Thanks @JorjMcKie, I fixed it now by adding an existence check. But unfortunately, I now see overlap/bold borders for rectangles which I have created using the output of get_cdrawings(). E.g.: seems like a rectangle drawn again over it.
> 
> Is this somehow related to the original comparability issue?

Can you kindly share your code with the existence check of the parameters. I am getting same error.
