### ISSUE TITLE
page.get_text() can't extract the text on the edge

### ISSUE THREAD

**Issue by CHIJUI0128** [pymupdf/PyMuPDF#2379]
Hello!
I have a confusion
When I want to create a text (fontsize =1) at the bottom of a new page of pdf and output it into a new pdf
However, when I use page.get_text(), I can't find the word.
Thank you
~ Have a good weekend~

```
import fitz
doc = fitz.open()  # new or existing PDF
page = doc.new_page()  # new or existing page via doc[n]
p = fitz.Point(0, page.rect.height)  # start point of 1st line

text = "Some text."

rc = page.insert_text(p,  # bottom-left of 1st char
                     text,  # the text (honors '\n')
                     fontsize = 1,  # the default font size
                     )

doc.save('.\text.pdf')
```
```
import fitz
fname = r'.\text.pdf'
doc = fitz.open(fname)  
page = doc[0]
words=page.get_text()
print(words)  
```

**Comment by CHIJUI0128** [comment]
This pdf document has very, very tiny text in the lower left corner.
[text.pdf](https://github.com/pymupdf/PyMuPDF/files/11351818/text.pdf)

**Comment by JorjMcKie** [comment]
Cannot reproduce: tried on Linux Py3.10, pymupdf 1.22.1, Windows Py3.7 through Py3.11, pymupdf 1.19.6 and the current version 1.22.2 and several others. All worked fine.
You don't mention your environment - please do so.

**Comment by JorjMcKie** [comment]
Please complete information requested in previous post - otherwise we will need to close this issue as resolved / answered within the next few days.

**Comment by CHIJUI0128** [comment]
ok i will try it myself
Thank you!!
