### ISSUE TITLE
marked content support

### ISSUE THREAD

**Issue by cole-dda** [pymupdf/PyMuPDF#2387]
**Is your feature request related to a problem? Please describe.**
pdf use  BDC ... EMC,  BMC ... EMC ,  /OC ... BDC ... EMC 
describe page logic tree, but by page api, can't get it.

**Describe the solution you'd like**
mcs = page.get_marked_contents()

mcs=[{name:'span',items:[seqno1,seqno2],children:[{name:'span'}]}]

**Comment by JorjMcKie** [comment]
You can access a page's appearance stream. This is a `bytes` object `cont = page.read_contents()`.
Then do an analysis of that string to find the respective commands.
To ease this analysis, you can first solidify and syntactically clean that source via `page.clean_contents()` and **then** invoke the first method. The effect will be a more reliable layout, like all appearance commands are ensured to occur in their own line, within which they are the last item. So you could split the bytes object by lines and locate the ones starting with `b"/OC"` or ending with `b"EMC"`, etc.

Another question is, what you have achieved once you have located those items: things enclosed in pairs of BMC/EMC or the like also are in that same syntax, the interpretation of which is up to you.
There is no support in (Py-) MuPDF to analyze this - and presumably will not be any time soon.
