### ISSUE TITLE
The rectangles, texts, and images drawn based on the given coordinates are not in the correct positions. They consistently appear near the bottom left corner of the page.

### ISSUE THREAD

**Issue by Jasoneng2017** [pymupdf/PyMuPDF#2392]
I have a standard A4-sized PDF file with several annotated texts on the pages, which are used for searching and replacing during the process. By iterating through these texts, I am able to accurately obtain the coordinates of the text on the respective pages. I then use these coordinates to draw a colored-filled rectangle on top of the text. However, no matter how I adjust the parameters, the drawn rectangle always appears in the bottom left corner of the page. The relative positions of the annotated texts remain intact, but they cannot appear at the specified coordinates. When using the library's built-in text highlighting function, it correctly displays the annotations, but any rectangles, texts, or images I draw myself consistently appear in the bottom left corner of the page and are very small in size.

The version of the library I'm using is the latest version, [1.22.2.]

Here is the pdf file 
[A4.pdf](https://github.com/pymupdf/PyMuPDF/files/11423450/A4.pdf)

And this is the processed PDF file.
[output.pdf](https://github.com/pymupdf/PyMuPDF/files/11423456/output.pdf)

Here is my code

```
import tkinter as tk
from tkinter import filedialog

import fitz


def fill_rectangles(pdf_path, search_strings, output_path):
    doc = fitz.open(pdf_path)
    for page_num in range(doc.page_count):
        page = doc.load_page(page_num)

        for search_string in search_strings:
            text_instances = page.search_for(search_string)
            for rect in text_instances:
                x0, y0, x1, y1 = rect
                rect_color = (1, 0, 0)
                page.draw_rect(fitz.Rect(x0, y0, x1, y1),
                               color=rect_color, fill=rect_color, width=2)

    doc.save(output_path)
    doc.close()


root = tk.Tk()
root.withdraw()

pdf_path = filedialog.askopenfilename()
output_path = "output.pdf"
search_strings = ['#SH#', '#JH#', '#PZ#', '#SJ#',
                  '#HQR#', '#HQDATE#', '#HQZY#']
fill_rectangles(pdf_path, search_strings, output_path)
```

**Comment by JorjMcKie** [comment]
This is not a bug an effect discribed in the documentation [here](https://pymupdf.readthedocs.io/en/latest/recipes-common-issues-and-their-solutions.html) under headline "Misplaced Item Insertions on PDF Pages".
If you insert the line `page.wrap_contents()` like in the following, the problem is gone:
```python
import tkinter as tk
from tkinter import filedialog

import fitz


def fill_rectangles(pdf_path, search_strings, output_path):
    doc = fitz.open(pdf_path)
    for page_num in range(doc.page_count):
        page = doc.load_page(page_num)
        page.wrap_contents()  # <=== INSERTED
        for search_string in search_strings:
            text_instances = page.search_for(search_string)
            for rect in text_instances:
                x0, y0, x1, y1 = rect
                rect_color = (1, 0, 0)
                page.draw_rect(
                    fitz.Rect(x0, y0, x1, y1),
                    color=rect_color,
                    fill=rect_color,
                    width=2,
                )

    doc.save(output_path)
    doc.close()


root = tk.Tk()
root.withdraw()

pdf_path = filedialog.askopenfilename()
output_path = "output.pdf"
search_strings = ["#SH#", "#JH#", "#PZ#", "#SJ#", "#HQR#", "#HQDATE#", "#HQZY#"]
fill_rectangles(pdf_path, search_strings, output_path)
```

**Comment by Jasoneng2017** [comment]
Thank you very much, add this code solves the problem perfectly.
