### ISSUE TITLE
Gaps within text of same line not filled with spaces

### ISSUE THREAD

**Issue by liwenjie0728** [pymupdf/PyMuPDF#2400]
[双开论文2.pdf](https://github.com/pymupdf/PyMuPDF/files/11447802/2.pdf)
get_text()
this function gets right datas in version 1.21.1,but in latest version gets error data.It processes data that is not in a row into a row.
![image](https://github.com/pymupdf/PyMuPDF/assets/15979538/1df99067-9ff2-45a0-8369-ce6be4c4c7d6)

**Comment by JorjMcKie** [comment]
Please add details:
I don't understand the problem? All data are extracted.

**Comment by liwenjie0728** [comment]
but it recognizes 'Residual learning for effective joint' and 'demosaicing-denoising' into one line.In version 1.21.1,these two blocks are not recognized into one line.

**Comment by JorjMcKie** [comment]
> but it recognizes 'Residual learning for effective joint' and 'demosaicing-denoising' into one line.In version 1.21.1,these two blocks are not recognized into one line.

Ah, ok, now it became clear: the distance between the words "Morel." and "Residual" is an empty gap, which should be filled with a suitable number of spaces by MuPDF ... and **_this_** is what does not happen.
We are currently analyzing the situation.

**Comment by JorjMcKie** [comment]
This bug is already under investigation.

**Comment by liwenjie0728** [comment]
ok,thank you.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.22.5.
