### ISSUE TITLE
Blacklining an image in PDF won't remove underlying content in version 1.22.X

### ISSUE THREAD

**Issue by bbustamante** [pymupdf/PyMuPDF#2404]
### Discussed in https://github.com/pymupdf/PyMuPDF/discussions/2399

<div type='discussions-op-text'>

<sup>Originally posted by **bbustamante** May 10, 2023</sup>
Hello,
I have just updated my PyMuPDF version from 1.21.1 to 1.22.2. When I blackline a text from an image even wen I edit the result PDF to get de blankline from the file manualy, the text behind it was desaparead (that's, for me, the correct working system). But right now, when I do it the text is still there. This just happend when the text is an image inside de PDF (second line of the example), not wen is a real text (first line of the example).

I include three (plus one) images with the process and the PDF I use:

1) Te original PDF with two lines. First one is real text while the second one is an image.
![image](https://github.com/pymupdf/PyMuPDF/assets/2870196/d291214b-476c-4ec5-9c1a-8477353c6a78)

2) The result PDF after blackileing it with PyMuPDF.
![image](https://github.com/pymupdf/PyMuPDF/assets/2870196/2a441c11-36bf-4af3-ae13-c43494d89822)

3) The result PDF manually edited to remove the blacklines.
![image](https://github.com/pymupdf/PyMuPDF/assets/2870196/3553329c-d760-46e5-ac91-e094b77fb426)

4) The PDF file I use for the example.
[PyMuPDF example.pdf](https://github.com/pymupdf/PyMuPDF/files/11443267/PyMuPDF.example.pdf)

5) The result of the example made with PyMuPDF 1.21.1 after editing manually for removing blacklines.
![image](https://github.com/pymupdf/PyMuPDF/assets/2870196/c73b17f7-d579-442f-bb39-40e474b94dcb)

Any idea of what is happening? How could I resolve it?
Thanks.</div>

I have try all the PyMuPDF 1.22.X versions and in all of them happen the same. I have see that between PyMuPDF 1.21.1 and PyMuPDF 1.22.0 the MuPDF version has changed, don't know if this could be affecting to this issue.

Here is an example code of what I'm doing:

[test.zip](https://github.com/pymupdf/PyMuPDF/files/11453515/test.zip)

**Comment by JorjMcKie** [comment]
This is a bug and already under investigation.

**Comment by JorjMcKie** [comment]
Please also refer to discussion #2399.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.22.5.
