### ISSUE TITLE
pymupdf extract page blocks are different between two same pdf files.

### ISSUE THREAD

**Issue by buptyyf** [pymupdf/PyMuPDF#2410]
PyMuPDF version : 1.21.0

## Describe the bug (mandatory)
Example pdf files:

[whole.pdf](https://github.com/pymupdf/PyMuPDF/files/11505257/CB_22xBAdBADGPK6gU6gWA8K54U.pdf)

[some.pdf](https://github.com/pymupdf/PyMuPDF/files/11505243/CB_22xBAdBADGPK6gU6gWA8K54U.2.pdf)

some.pdf is some part pages of whole.pdf (page 11-14).

But I extract page_text by pymupdf get different results.

```
import fitz
doc1 = fitz.open('some.pdf')
print(doc1[0].get_text('dict'))
doc2 = fitz.open('whole.pdf')
print(doc2[11].get_text(dict))
```

In theory, doc1[0].get_text('dict') should be the same with doc2[11].get_text(dict). But actually, doc2[0].get_text('dict') get 15 blocks, and  doc2[11].get_text(dict) get 6 blocks. Maybe doc2 is reasonable result.

I want to know why extract these pdfs different results. How should I handle it?

Thank you in advance.

**Comment by JorjMcKie** [comment]
This is not a bug: the subset PDF has been created by some other tool, **_not by PyMuPDF_**.
You should submit a bug report to that other tool provider. Maybe the document metadata may give you a clue, who they are.
