### ISSUE TITLE
Ability to set pair of values to comboboxes (face and export values)

### ISSUE THREAD

**Issue by australgisinc** [pymupdf/PyMuPDF#2411]
While creating or populating a PDF combobox, there are two values: the facing value (visible to the user) and the export value (the value exported).
If somebody uses Adobe API Javascript it would be something like this : f.setItems( ["Ohio", "OH"], ["Oregon", "OR"], ["Arizona", "AZ"] ), being 'Ohio' the face value and 'OH' the export value.

**Comment by JorjMcKie** [comment]
Thank you, noted.
Pleased to see you followed my recommendation 😊.

**Comment by JorjMcKie** [comment]
> While creating or populating a PDF combobox, there are two values: the facing value (visible to the user) and the export value (the value exported). If somebody uses Adobe API Javascript it would be something like this : f.setItems( ["Ohio", "OH"], ["Oregon", "OR"], ["Arizona", "AZ"] ), being 'Ohio' the face value and 'OH' the export value.

In the meantime we determined that string value pairs in fact **_are supported_** already!
Your problem occurs only if the pair of strings is a Python `list` - it works if it is a tuple.
Please confirm.
For a future version we will implement a fix to stabilize the behaviour such that arbitrary Python sequence types are accepted.

**Comment by JorjMcKie** [comment]
Therefore, your example should work if you use tuples like this:

`widget.choice_values = (("Ohio", "OH"), ("Oregon", "OR"), ("Arizona", "AZ"))`

**Comment by australgisinc** [comment]
Hi Jorj,

Thanks for your quick response. 
You are right, I tested with tuples, it works perfectly. The only thing that must be mentioned in  the documentation, as well as the tuple form is that it works inversely, I mean, in a tuple ('OHIO','OH') 'OHIO' appear as the export value. so it must be like ('OH','OHIO') instead.

**Comment by JorjMcKie** [comment]
@australgisinc Thank you for feedback!
As I mentioned, in a coming version the "tuple" restriction will be removed and any sequence type (e.g. lists) will be accepted.
You are right, for time being we should adapt the documentation.
Thanks for that other hint, let me look up the PDF spec.

**Comment by JorjMcKie** [comment]
As for the `("OHIO", "OH")`<-> `("OH", "OHIO")` thing: there is no code in PyMuPDF that checks which one is what. So we only need to document that `("OH", "OHIO")` is the correct way of specifying this.

**Comment by australgisinc** [comment]
Hi Jorj, 
There is one more thing I want to comment to you. The content of the tuple must by quoted (string), I mean, if the content of the tuple is an integer must be quoted, otherwise it not going to work : ( 1, 'Beaconsfield') must be ('1', 'Beacoonsfield').

**Comment by JorjMcKie** [comment]
> Hi Jorj, There is one more thing I want to comment to you. The content of the tuple must by quoted (string), I mean, if the content of the tuple is an integer must be quoted, otherwise it not going to work : ( 1, 'Beaconsfield') must be ('1', 'Beacoonsfield').

Correct, only pairs of Python **_strings_** are allowed - I am including a respective check in the coming change.
