### ISSUE TITLE
fitz.open() is not recognizing the dynamic input file

### ISSUE THREAD

**Issue by ArSenic04** [pymupdf/PyMuPDF#2414]
**Is your feature request related to a problem? Please describe.**
fitz.open() is not recognizing the dynamic input file

**Describe the solution you'd like**
So please solve this issue of fitz library of module PyMuPDF 

**Describe alternatives you've considered**
Are there several options for how your request could be met?

**Additional context**

**Comment by JorjMcKie** [comment]
Sorry, this is not understandable. Please provide a reproducer.

**Comment by JorjMcKie** [comment]
Please provide details and clarifications, otherwise we are not able to deal with your post and will have to close it.

**Comment by JorjMcKie** [comment]
Closing this for lack of details.
Please reopen when needed.
