### ISSUE TITLE
Cannot find reference 'open' 

### ISSUE THREAD

**Issue by johnbumgarner** [pymupdf/PyMuPDF#2416]
I'm trying to use `PyMuPDF` in `PyCharm 2023.1.2`.  My environment is virtual and using Python 3.9.  Each time I try to use:

> doc = fitz.open("sample.pdf")

I receive this error:  

![Screen Shot 2023-05-23 at 7 30 00 AM](https://github.com/pymupdf/PyMuPDF/assets/50935186/247a0a96-5520-4a8a-bc3b-bf8d45192e1c)

I have tried to bypass this error by trying different versions of `Python`, which include `3.8`, `3.9` and `3.10`.  I have also tried downgrading `PyMuPDF` from 1.22.3 to various lower versions, but the error never goes away.  

I have these packages installed:

![Screen Shot 2023-05-23 at 7 35 17 AM](https://github.com/pymupdf/PyMuPDF/assets/50935186/dee9ceb7-8d7a-472b-bdaf-458130741969)

Here is the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)`

> 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 17:02:14) 
[Clang 6.0 (clang-600.0.57)] 
 darwin 
 
> PyMuPDF`` 1.22.3: Python bindings for the MuPDF 1.22.0 library.
Version date: 2023-05-10 00:00:01.
Built for Python 3.9 on darwin (64-bit).

My operating system is `macOS Catalina 10.15.7`.

**Comment by JorjMcKie** [comment]
> Thanks for quick response. If I install `PyMuPDF` locally with `Brew` everything seems to work correctly. If I use this same environment in PyCharm the `Fitz` package only has these items:
> 
> Any idea why the other modules in `Fitz` aren't installing correctly?

Looks good - pymupdf needs no other things. Every installation should look exactly like this, only the suffix of the `.so` module may be different.

Unfortunately, there also exists a **package named "fitz"** on PyPI (in alpha state, no longer maintained, etc.). I hope you haven't installed this 🤢.
That package and pymupdf cannot live in the same environment.

**Comment by johnbumgarner** [comment]
I decided to installed `pymupdf` locally using brew.  Brew installed `mupdf` with `fitz`

> sudo grep -r -l fitz /usr    
/usr/local/include/mupdf/fitz.h
/usr/local/include/mupdf/pdf/cmap.h
/usr/local/include/mupdf/pdf/form.h
/usr/local/include/mupdf/pdf/document.h
/usr/local/include/mupdf/pdf/resource.h
truncated...

**Comment by JorjMcKie** [comment]
Thank you for reporting back!

**Comment by johnbumgarner** [comment]
Thanks for the help.  This most be an issue within PyCharm, because `pymupdf` installs correctly on my local system and in a Google Colab notebook.

**Comment by haaza23** [comment]
Hello! I'm having the same issue using PyCharm. Have you found a solution?
