### ISSUE TITLE
bug: page.apply_redactions() will cause the linewidth changed

### ISSUE THREAD

**Issue by windvan** [pymupdf/PyMuPDF#2426]
latest version:
the previous line width is 0.0 through page.get_drawings()
after called page.apply_redactions(), call page.get_drawings() again, the line width is changed

**Comment by JorjMcKie** [comment]
Sorry, this issue cannot be accepted as a bug report as is: you have omitted all information mandatory.

**Comment by JorjMcKie** [comment]
Closed due to missing information.
