### ISSUE TITLE
Inconsistency between matrix rotation direction in documentation and implementation

### ISSUE THREAD

**Issue by VeryLazyBoy** [pymupdf/PyMuPDF#2427]
## Describe the bug (mandatory)
Given positive degree `30`, fitz.Matrix(1, 1).prerotate(30) results in the original pdf rotated **clockwise** instead of counter-clockwise as described in the documentation

<img width="772" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/18899212/73f0ab96-5ca4-4308-b8e0-7a437fccce08">

## To Reproduce (mandatory)
```python
# any pdf
doc = fitz.Document('hello_world.pdf')
# positive degree 30
pix = doc.load_page(0).get_pixmap(matrix=fitz.Matrix(1,1).prerotate(30))

new_doc = fitz.Document()
new_page = new_doc.new_page(width=pix.width, height=pix.height)
new_page.insert_image(fitz.Rect(0, 0, pix.width, pix.height), pixmap=pix)
new_doc.save('output.pdf')
```

input pdf:
<img width="484" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/18899212/34c55323-8aec-4a2f-bba0-b10a487af2fd">

output pdf(rotated clockwise instead of counter-clockwise):
<img width="611" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/18899212/bc497c77-ea35-41c7-9da7-20f6b8921ed6">

## Your configuration (mandatory)
output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` 

```
3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0]
 linux

PyMuPDF 1.22.3: Python bindings for the MuPDF 1.22.0 library.
Version date: 2023-05-10 00:00:01.
Built for Python 3.8 on linux (64-bit).
```

**Comment by JorjMcKie** [comment]
Thank you.
Documentation will be corrected.

**Comment by jamie-lemon** [comment]
Now fixed in the latest docs!

**Comment by VeryLazyBoy** [comment]
@jamie-lemon It seems the wording are the same as before?

<img width="745" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/18899212/6238e0e2-94e5-451b-90b2-dd556f1feeae">

I noticed that the example given at the end changed, but shouldn't it be `Matrix(-30)` instead of `Matrix(30)`?

<img width="721" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/18899212/ece88f01-3acf-440d-a490-5efbb80355ff">

**Comment by JorjMcKie** [comment]
Picture and wording are correct as shown: positive angles mean anti-clockwise rotation.

**Comment by VeryLazyBoy** [comment]
I have tested the latest version 1.22.5 and it appears that the behavior remains the same as before. Specifically, positive angles rotate the page clockwise, which contradicts the wording in the documentation.

**Comment by JorjMcKie** [comment]
> I have tested the latest version 1.22.5 and it appears that the behavior remains the same as before. Specifically, positive angles rotate the page **clockwise**, which contradicts the wording in the documentation.

Your example (and our old one in previous docu version) is misleading - so we replaced it with new pictures: what you see now is the red rotation point and the correspondingly rotated text - whith the rotation angle 30° shown as it actually has been used.

**So how to explain this apparent inconsistency?**
The image geometry in PDF has its origin (0,0) in the top-left point, and the positive y-axis **_points downwards!_** The y-value 0 is at the top, and the value y = image.height is at the bottom.
In this geometry, positive angle rotations WRT to (0,0) - as always - are rotations in direction to growing y-values ... giving the picture you are showing.

**Comment by VeryLazyBoy** [comment]
Thanks for you clarification.

Perhaps the context of the coordinate system should be considered when deciding on the appropriate wording for the documentation. The current wording, *Modify the matrix to perform a counter-clockwise rotation for positive deg degrees, else clockwise* , is accurate in a standard coordinate system where up means the positive y-axis. However, when working with PDF files that use a non-standard coordinate system where down means the positive y-axis, positive deg degrees is defined clockwise and thus result in a clockwise rotation.

Since the Matrix is used exclusively for working with PDF files(*it seems?*), it can be confusing to use terms that are specific to a standard coordinate system. 

Regards with the new image example in the documentation,  again, the rotation seems correct in standard coordinate. It may be helpful to provide image examples that reflect the non-standard coordinate system commonly used in PDF files.

**Comment by JorjMcKie** [comment]
> Since the Matrix is used exclusively for working with PDF files(it seems?), ...

No, this is an unjustified assumption. Geometry objects like matrices, rectangles, points or quads are independent from documents or document types and consequently live without connection to whatever pages or the like.
Apart from that, even in PDF spec, images have a top-down orientated y-axis. Only PDF pages in that spec are oriented from bottom to top.
This is the reason for me to take an **_image_** as an example.
It should be sufficient to accept that a rotation direction depends on the underlying coordinate system.
The rest of consequences follows from that.
But you are right in asking for examples that help prevent wrong conclusions. We'll see what can be done here.
