### ISSUE TITLE
Incorrectly reducing ref count of Py_None

### ISSUE THREAD

**Issue by JorjMcKie** [pymupdf/PyMuPDF#2430]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Starting with version 1.22.0, creating the dictionary `Font.flags` will erroneously decrement the reference count of the "immortal" Python object `Py_None`. After (many) creations, that reference count will eventually reach zero, crashing the interpreter.

## To Reproduce (mandatory)
Create a `Font` object and build `Font.flags` repeatedly.

## Your configuration (mandatory)
 - All operating systems and Python versions
 - PyMuPDF version 1.22.0 and later

**Comment by JorjMcKie** [comment]
Problem fixed and should be rolled out in one of the next versions.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.22.5.
