### ISSUE TITLE
Inserted non-website links are not visible on pdf.js based viewers

### ISSUE THREAD

**Issue by krystianMoras** [pymupdf/PyMuPDF#2434]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Link insertion only works when you use uri that starts with "http://" or "https://". However "file://" or any other uri e.g. "obsidian://" fails. I think that somewhere these links are disambiguated which should not be a case. 

## To Reproduce (mandatory)
To create a link for a website
```py
def create_link(rect, uri):
    return {
        "kind": 2,
        "from": rect,
        "uri": uri
    }

import fitz
doc = fitz.open()
doc.insert_page(0)
link = create_link(fitz.Rect(0,0,500,500), "http://google.com")
doc[0].insert_link(link)
doc.save("empty_doc.pdf")
```
To create a link for a file
```py
doc = fitz.open()
doc.insert_page(0)
link = create_link(fitz.Rect(0,0,500,500), "file://C:/Users/kryst/Documents/empty_doc.pdf")
doc[0].insert_link(link)
doc.save("empty_doc.pdf")
```
( I tried every number of slashes after "file:" just in case )

## Expected behavior (optional)
Whatever value is passed to "uri" should create a link. There should be the same behaviour for any kind of uri

## Screeenshots
website uri:
![obraz](https://github.com/pymupdf/PyMuPDF/assets/72855171/4bf6cb3f-5d20-4b1a-9e23-ef465f397bd2)

any other uri:

on microsoft edge link is there:
![obraz](https://github.com/pymupdf/PyMuPDF/assets/72855171/2071c049-90fe-4336-a28e-8ca5c9a56811)

on any pdf.js based viewer it does not exist:
![obraz](https://github.com/pymupdf/PyMuPDF/assets/72855171/fe029f2a-c00b-4d29-bf4e-3977ffbafd44)

example with annotation inserted with javascript in pdf.js:
![obraz](https://github.com/pymupdf/PyMuPDF/assets/72855171/9e730c48-7d70-4a8a-805f-3b7fe75e1980)

## Your configuration (mandatory)
 - Windows 11
 - Python 3.11
 - PyMupdf 1.22.3, wheel

**Comment by JorjMcKie** [comment]
This is no bug.
The URI string is inserted as is in any case. Whether or not this leads to a recognizable file identification is up to the viewer you arer using.
Inserting a file path specific for Windows works for all viewers installed on my Windows machine: Adobe, XChange, Foxit, MuPDF, etc., but using evince on my WSL Linux won't recognize a Windows-format filename of course.
