### ISSUE TITLE
PyMuPDF==1.21.1 and PY3.10.2 returning empty page blocks for few scanned documents

### ISSUE THREAD

**Issue by sunov** [pymupdf/PyMuPDF#2441]
### Discussed in https://github.com/pymupdf/PyMuPDF/discussions/2432

<div type='discussions-op-text'>

<sup>Originally posted by **sunov** May 31, 2023</sup>
PyMuPDF==1.21.1 and PY3.10.2 returning empty page blocks for few scanned documents and not returning any error. With PY3.7.3 and PyMuPDF==1.19.4, The page blocks are identifying and images are extracting from the pdf. This issue is happening in our prod environment, Due to security concerns not able to share the pdfs. Can anyone help?</div>

**Comment by JorjMcKie** [comment]
I am afraid without at least one example document page, it is impossible to help. Couldn't you pick an unproblematic page and make a single page document from it?
Or you could send an example to my private e-mail.
