### ISSUE TITLE
page.apply_redactions() changes the line width of drawings on the page

### ISSUE THREAD

**Issue by windvan** [pymupdf/PyMuPDF#2446]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
when call page.apply_redactions() after the redact_annot is added, previous lines on the output pdf file is changed.
the previous line-width is 0.0(page.get_drawings()), after redact_annot is added and page.apply_redactions() is called,the line-width
on the output file is 1.0((page.get_drawings())

## To Reproduce (mandatory)
`import fitz`
`doc=fitz.open("test.pdf")`
`page=doc[0]`
`drawings=page.get_drawings()`
`for drawing in drawings:`
`    print(drawing)`
`print('#############################')`
`page.add_redact_annot([10,10,20,20])`
`page.apply_redactions()`
`drawings = page.get_drawings()`
`for drawing in drawings:`
`    print(drawing)`

## Expected behavior (optional)
the drawings  in the pdf stay unchanged after redactions are applied

## Screenshots (optional)
![1](https://github.com/pymupdf/PyMuPDF/assets/128346285/038cc125-8bcb-47da-b04a-f17f9f6b2251)
![2](https://github.com/pymupdf/PyMuPDF/assets/128346285/bd1a7729-61a6-4cc2-b46d-f3fd1f6b3c2b)

## Your configuration (mandatory)
 - OS==Windows10,22H2
 - Python version==3.11.0
 - PyMuPDF version==1.22.3, pip install

**Comment by JorjMcKie** [comment]
Please provide a reproducer file, thank you.

**Comment by windvan** [comment]
________________________________
发件人: Jorj X. McKie ***@***.***>
发送时间: 2023年6月2日 13:36
收件人: pymupdf/PyMuPDF ***@***.***>
抄送: windvan ***@***.***>; Author ***@***.***>
主题: Re: [pymupdf/PyMuPDF] page.apply_redactions() changes the line width of drawings on the page (Issue #2446)


Please provide a reproducer file, thank you.

―

**Comment by JorjMcKie** [comment]
Thanks for the file. Finally it is possible to see what happens!

As part of applying redactions, the appearance stream of the page must obviously be recreated (`/Contents` object - a special type of source code) to reflect that the redacted parts of the page are no longer there.
As part of that process, the commands in that stream are **_cleaned and sanitized_**. This includes standardization of that source code's syntax, and also **_removal of commands_** that are not recommended as per the PDF specification.

Your PDF includes multiple commands `0 w` which set the stroke line width to 0. Doing this is **_not recommended_** by the PDF standard, therefore these commands are removed as part of applying redactions.

As a consequence, the default line width 1 is used when PDF viewers display the redacted page.

This effect is inevitable for pages not adhering to PDF recommendations and not a bug.
