### ISSUE TITLE
Annotation rectangle different from the one used to set it

### ISSUE THREAD

**Issue by jn-chrn** [pymupdf/PyMuPDF#2451]
## Describe the bug (mandatory)
When adding an annotation to a page using `page.add_circle_annot`, a rectangle can be given to set its size. However, when retrieving the size of the annotation, the rectangle has a different size, namely a bit larger.

## To Reproduce (mandatory)

```python
import fitz

doc: fitz.Document = fitz.open()
doc.insert_page(0, width=50, height=50)

page: fitz.Page = list(doc.pages())[0]

rectangle = fitz.Rect(10, 10, 20, 20)
page.add_circle_annot(rect=rectangle)

(single_annot,) = page.annots()
assert single_annot.rect == rectangle  # (9.5, 9.5, 20.5, 20.5) != (10, 10, 20, 20)
``` 

## Expected behavior (optional)
The rectangle that is read from the PDF should have the same size as the rectangle that is used to set the annotation.

## Your configuration (mandatory)

* Operating system, potentially version and bitness

3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] 
 linux 

* Python version, bitness

PyMuPDF 1.21.1: Python bindings for the MuPDF 1.21.1 library.
Version date: 2022-12-13 00:00:01.
Built for Python 3.10 on linux (64-bit).

* PyMuPDF version, installation method (wheel or generated from source).
    *  PyMuPDF version 1.21.1 and 1.22.3, both installed using pip (so wheel).

**Comment by JorjMcKie** [comment]
Probably no bug:
You did not provide a reproducer file. But chances are that you should first wrap the page's contents by graphics stacking commands: `page.wrap_contents()`, before you insert the annot.

**Comment by JorjMcKie** [comment]
Otherwise, your statement

*The rectangle that is read from the PDF should have the same size as the rectangle that is used to set the annotation.*

is wrong.
This
```python
rectangle = fitz.Rect(10, 10, 20, 20)
annot=page.add_circle_annot(rect=rectangle)
print(annot.rect)
```
prints this: `Rect(9.5, 9.5, 20.5, 20.5)`, which is correct, given the default line width is 1.

You can enforce things like this:
```python
rectangle = fitz.Rect(10, 10, 20, 20)
annot = page.add_circle_annot(rect=rectangle)
annot.set_border(width=0)
annot.update()
print(annot.rect)
```
which prints the original `rectangle`.
