### ISSUE TITLE
Doc.insert_pdf looses some pdf elements

### ISSUE THREAD

**Issue by PasaOpasen** [pymupdf/PyMuPDF#2460]
For one document I have an issue: it has some pdf element, but after doc.insert_pdf  it is loosed. I tried versions 1.21 / 1.22

Before:
![изображение](https://github.com/pymupdf/PyMuPDF/assets/45700689/4d8a6f9c-0c7c-4d58-be3a-7c9f6bb7359b)

After:
![изображение](https://github.com/pymupdf/PyMuPDF/assets/45700689/7a120829-8869-4348-a03b-94a608d05147)

Minimal code:
```python
from PIL import Image
import fitz


def show_page(p: fitz.Page):
    pix = p.get_pixmap()
    local_mode = 'RGB'
    Image.frombytes(local_mode, (pix.width, pix.height), pix.samples).show()

pdf_path="missing-stamp.pdf"
with fitz.open(pdf_path) as doc:
    page = doc[2]
    show_page(page)   # a stamp exists

    out_doc = fitz.open()
    out_doc.insert_pdf(doc, from_page=2, to_page=2)
    show_page(out_doc[0])   # no stamp

```

It's private document, so I sent it to jorj.x.mckie@outlook.de

**Comment by JorjMcKie** [comment]
Thanks for letting me have a reproducing file - it's in safe hands 👌.
This is no stamp annotation, but a signature image.
Widgets / fields cannot be copied via this function - see documentation.

**Comment by PasaOpasen** [comment]
@JorjMcKie so how to perform page extraction logic for this pages?

**Comment by JorjMcKie** [comment]
> @JorjMcKie so how to perform page extraction logic for this pages?

The only way is making a pixmap / image of the page and use this instead.

**Comment by PasaOpasen** [comment]
@JorjMcKie how I can I know that a page contains such elements?

**Comment by JorjMcKie** [comment]
> @JorjMcKie how I can I know that a page contains such elements?

check for the existence of widgets: `page.widgets()` is an iterator over them.
