### ISSUE TITLE
Error at  "get_drawing(extended=True )"

### ISSUE THREAD

**Issue by Dong-gri-dong** [pymupdf/PyMuPDF#2462]
Hi, 

when using the **get_drawing(extended=True)** function

**Segmentation fault (core dumped)** error occurs

There is no error when extended=False.

The file below is an example of an error file.
[sample.pdf](https://github.com/pymupdf/PyMuPDF/files/11702703/sample.pdf)

PyMyPDF version: 1.22.3(1.22.0, 1.22.1 1.22.2 same)

**Comment by JorjMcKie** [comment]
Accepted - thanks for submitting this!

**Comment by JorjMcKie** [comment]
This is being fixed in the coming version 1.22.4.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.22.5.
