### ISSUE TITLE
RuntimeError: color pixmap must not have an alpha channel

### ISSUE THREAD

**Issue by little-polka-dot** [pymupdf/PyMuPDF#2483]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I implemented it according to the document example code and then i got an error. why?
https://pymupdf.readthedocs.io/en/latest/recipes-images.html

## To Reproduce (mandatory)
i = document[0].get_images()[0]
pix1 = fitz.Pixmap(document.extract_image(i[0])["image"])
print(pix1.colorspace)  # Colorspace(CS_RGB) - DeviceRGB
mask = fitz.Pixmap(document.extract_image(i[1])["image"])
print(mask.colorspace)  # Colorspace(CS_GRAY) - DeviceGray
fitz.Pixmap(pix1, mask)

## Your configuration (mandatory)
3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] 
 win32 
 
PyMuPDF 1.22.3: Python bindings for the MuPDF 1.22.0 library.
Version date: 2023-05-10 00:00:01.
Built for Python 3.7 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
This is not a bug. As explained in the documentation, it may happen that the base image has an alpha channel although a separate mask for transparency exists.
Please check change your script like this:
```python 
if pix1.alpha:  # check if alpha channel there
    pix1 = fitz.Pixmap(pix1, 0)  # remove alpha channel
pix = fitz.Pixmap(pix1, mask)
```

**Comment by little-polka-dot** [comment]
It works, thanks😊
