### ISSUE TITLE
Issue with Quad.ul/Quad.ur/Quad.ll/Quad.lr

### ISSUE THREAD

**Issue by little-polka-dot** [pymupdf/PyMuPDF#2510]
## Describe the bug (mandatory)
1. Create a rectangle:
```python
doc = fitz.Document()
page = fitz.utils.new_page(doc, width=600, height=800)
shape = page.new_shape()
shape.draw_line((250, 250), (350, 250))
shape.draw_line((350, 250), (350, 350))
shape.draw_line((350, 350), (250, 350))
shape.draw_line((250, 350), (250, 250))
shape.finish(fill=(1, 0, 0), width=2, color=(0, 0, 1))
shape.commit()
doc.save('output.pdf')
``` 
2. Get drawings from PDF:
```python
d = fitz.Document('output.pdf')
for i in d[0].get_drawings():
    print(i)
``` 
And then i got an Quad with ul=Point(250.0, 250.0), ur=Point(250.0, 350.0), ll=Point(350.0, 250.0), lr=Point(350.0, 350.0).
But according to my understanding, Point(250.0, 350.0) is actually quad.ll.
Is this a bug?

## To Reproduce (mandatory)
[output.pdf](https://github.com/pymupdf/PyMuPDF/files/11934524/output.pdf)

## Your configuration (mandatory)
3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] 
 win32 
 
PyMuPDF 1.22.5: Python bindings for the MuPDF 1.22.2 library.
Version date: 2023-06-21 00:00:01.
Built for Python 3.7 on win32 (64-bit).

**Comment by little-polka-dot** [comment]
Are ul and lr necessarily correct?

**Comment by JorjMcKie** [comment]
> Are ul and lr necessarily correct?

They are correct, if you use `.draw_quad()` instead of drawing the 4 single lines. Or of course, if you draw the lines in the correct sequence: `ul -> ll -> lr -> ur -> ul`.
This draw method internally draws the 4 lines in anti-clockwise mode, starting from and ending at `ul`.
Try it out **_without_** fill color and you should see the correct result:
```python
quad = fitz.Quad((250, 250), (350, 250), (250, 350), (350, 350))
shape = page.new_shape()
shape.draw_quad(quad)
shape.finish(color=(0, 0, 1))
shape.commit()
```
Correctly yields:
```python
[{'closePath': True,
  'color': (0.0, 0.0, 1.0),
  'dashes': '[] 0',
  'even_odd': None,
  'fill': None,
  'fill_opacity': None,
  'items': [('qu',
             Quad(Point(250.0, 250.0), Point(350.0, 250.0), Point(250.0, 350.0), Point(350.0, 350.0)))],
  'layer': '',
  'lineCap': (0, 0, 0),
  'lineJoin': 0.0,
  'rect': Rect(250.0, 250.0, 350.0, 350.0),
  'seqno': 0,
  'stroke_opacity': 1.0,
  'type': 's',
  'width': 1.0}]
```

Just noticed however, that for a combination of fill and stroke, the mechanism doesn't - which is a different issue.
