### ISSUE TITLE
pdf / form fields / radio button output

### ISSUE THREAD

**Issue by wave-DmP** [pymupdf/PyMuPDF#253]
Hi, I'm having issues pulling the output of radio button form fields grouped inside the same annot:
annot.widget_value: 
    - output is a bool object which does not work for any 2+ option radio buttons
    - seems to be pulling the value of the last option in a group
annot.widget_choices: returns a None

Is there something I may be missing?

UPDATE: after some more tinkering I've discovered the following, which seems to be the root of the problem - when iterating over a group of radio buttons, the annot.widget_name corresponds to the group name, hence when writing the values to a key dict, it is always the last value that overwrites all previous ones under the same annot.widget_name.

**Comment by JorjMcKie** [comment]
Hi,
this situation may not be supported yet. I cannot tell based on the description.
Please send me the PDF if possible to let me have a look into it.
