### ISSUE TITLE
use convert_to_pdf report an error

### ISSUE THREAD

**Issue by zZzClarezZz** [pymupdf/PyMuPDF#2531]
Hi,
when i convert the source PDF to a new PDF, i got an error.How should I handle this or verify the colorspaces of the PDF.

convert  code:
```
hFile = fitz.open("source.pdf")
srcbytes = hFile.convert_to_pdf()
```

errorMsg: RuntimeError: only Gray, RGB, and CMYK colorspaces supported

sourcePDF: [source.pdf](https://github.com/pymupdf/PyMuPDF/files/12013428/source.pdf)

PyMuPDF version: 1.19.1
python version: python 3.8 64bit
Computer version: windows 10 64bit

**Comment by JorjMcKie** [comment]
PDF-to-PDF conversion may be impossible for a number of reasons. In your case it was unsupported colorspaces, other unsupported cases include certain fonts, etc. etc.
The most practical way probably is wrapping the conversion in a try-except clause. You don't want to analyze the PDF yourself - let MuPDF do it.
