### ISSUE TITLE
get_texttrace returned a incorrect character bbox

### ISSUE THREAD

**Issue by little-polka-dot** [pymupdf/PyMuPDF#2533]
## Describe the bug (mandatory)
get_texttrace returned a incorrect character bbox

## To Reproduce (mandatory)
[盐城高新区投资集团有限公司2023年度第四期超短期融资券募集说明书.pdf](https://github.com/pymupdf/PyMuPDF/files/12013804/2023.pdf)

```python
d = fitz.Document('temp/盐城高新区投资集团有限公司2023年度第四期超短期融资券募集说明书.pdf')
page = d[250]
for span in page.get_texttrace():
    for char in span['chars']:
        if chr(char[0]) == '民':
            print(char)
``` 
The above code will print this message:
```python
(27665, 8775, (114.0, 634.72998046875), (114.0, 633.2604370117188, 124.44999694824219, 643.71044921875)
``` 
Origin y (634.72998046875) is too close to bbox y0 (633.2604370117188), and this is obviously not right.

Screenshot of the incorrect character bbox (red).
![test](https://github.com/pymupdf/PyMuPDF/assets/44431347/9dfe557e-5e17-4a8c-a568-e4f061024a40)

![1689124136230(1)](https://github.com/pymupdf/PyMuPDF/assets/44431347/5ba7f13b-c64c-42e6-afb4-f72bb990a2d3)

Screenshot code:
```python
page.get_pixmap(matrix=fitz.Matrix(2, 2), alpha=False, clip=fitz.Rect(114.0, 633.2604370117188, 124.44999694824219, 643.71044921875)).save(f'test.png')
``` 

## Your configuration (mandatory)
print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] 
 win32 
 
PyMuPDF 1.22.5: Python bindings for the MuPDF 1.22.2 library.
Version date: 2023-06-21 00:00:01.
Built for Python 3.7 on win32 (64-bit).

**Comment by little-polka-dot** [comment]
Hello? Is this a bug or just a special case?

**Comment by JorjMcKie** [comment]
It is a bug! I am working on this already.

**Comment by little-polka-dot** [comment]
😀Haha, thank you for answer.
Looking forward to your good news.

**Comment by JorjMcKie** [comment]
Your PDF nevertheless **_IS_** a special case in the way it is made - which is the reason why this bug was revealed.
Thank you!

**Comment by JorjMcKie** [comment]
Just implemented a fix. Should roll out in one of the next versions.

**Comment by little-polka-dot** [comment]
Haha, nice😀

**Comment by JorjMcKie** [comment]
We do no longer support Python 3.7 because this has been retired end of June.
So you need to upgrade. I recommend doing this **_now_**. We will not generate wheels for Python 3.7 for the next version.

**Comment by little-polka-dot** [comment]
I see
