### ISSUE TITLE
fritz.utils.scrub AttributeError Annot object has no attribute fileUpd inside 

### ISSUE THREAD

**Issue by markonose** [pymupdf/PyMuPDF#2542]
## Describe the bug
in utils.py in scrub we have the following line:
`annot.fileUpd(buffer=b" ")  # set file content to empty`
https://github.com/pymupdf/PyMuPDF/blob/main/fitz/utils.py#L4227

which triggers ```AttributeError: 'Annot' object has no attribute 'fileUpd'```

## To Reproduce
call
```fitz.open(stream=file_bytes, filetype="pdf").scrub(clean_pages=False)```
on a pdf document that has file attachments with the type ```PDF_ANNOT_FILE_ATTACHMENT```

## Describe the bug
fileUpd appears to be an alias, which does not get generated if the version of PyMuPDF is not 1.19.*

```
if VersionBind.startswith("1.19"):  # don't generate aliases after v1.19.*
    restore_aliases()
 ```
 
if calling ```restore_aliases()``` beforehand, the scrub function does not fail, but emits ```Deprecation: 'fileUpd' removed from class 'Annot' after v1.19 - use 'update_file'.```

## Additional context (optional)
None of the other aliases get referenced anywhere else in the code, except the deprecated aliases for utils.Shape are defined on the class itself. And aliases ```addWidget```, ```cleanContents```, ```PaperSize ``` get referenced in comments.

I can create the PR for the fix, it seems that just replacing the ```fileUpd``` call with ```update_file``` should do the trick.

**Comment by JorjMcKie** [comment]
Thank you for submitting this!
