### ISSUE TITLE
Segmentation fault at caling get_cdrawings(extended=True)

### ISSUE THREAD

**Issue by pulsar314** [pymupdf/PyMuPDF#2556]
## Description
If a document contains sequences like
```
q
100 100 m
W n
```
invocation of `page.get_cdrawings(extended=True)` results in a segfault.

In this case `dev_pathdict` is being cleared due to the empty commands list, but `jm_lineart_clip_path` and `jm_lineart_clip_stroke_path` are trying to get a value from the dict.

## Configuration
 - Linux MINT
 - Python 3.8
 - PyMuPDF 1.22.5, installed via pip

**Comment by pulsar314** [comment]
Unfortunately, I cannot provide you with the original PDF, but there is a reproduction of the failing sequence
[segfault.pdf](https://github.com/pymupdf/PyMuPDF/files/12182681/segfault.pdf)

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.4.
