### ISSUE TITLE
Documentation bug: File 4-up.py from documentation missing

### ISSUE THREAD

**Issue by sdbbs** [pymupdf/PyMuPDF#2560]
## Describe the bug (mandatory)

When I look at https://pymupdf.readthedocs.io/en/latest/page.html , I see:

> create “n-up” versions of existing PDF files, combining several input pages into one output page (see example [4-up.py](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples/4-up.py)),

... but if I click on https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples/4-up.py , I get 404 - page not found

## To Reproduce (mandatory)

1. Go to https://pymupdf.readthedocs.io/en/latest/page.html 
2. Click on the [4-up.py](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples/4-up.py)
3. Get 404 

## Your configuration (mandatory)

Firefox 115, Windows 10

**Comment by JorjMcKie** [comment]
Fixed.
