### ISSUE TITLE
Add mathematical characters to become question marks

### ISSUE THREAD

**Issue by chaodreaming** [pymupdf/PyMuPDF#2568]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I use page.add_ Redact_ Annot ([x1, y1, x2, y2], text, fontname='help ', fontsize=8) Adding mathematical characters results in a question mark in the PDF
## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.
`import fitz
pdf_path="new.pdf"

doc = fitz.open(pdf_path)
page = doc.load_page(0)
page.add_redact_annot([100,100,200,200], "𝐹 ∈ 𝑅𝐶×𝐻×𝑊 as input", fontname='times-roman', fontsize=8)
    # china-s
page.apply_redactions()
doc.save("保存文件路径.pdf")`
For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).
The character I want to write should appear in the document instead of a question mark
## Screenshots (optional)
![image](https://github.com/pymupdf/PyMuPDF/assets/49591435/89b0842a-3511-427b-9a48-1616a1cfb549)

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).
3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)] 
 win32 
 
PyMuPDF 1.22.5: Python bindings for the MuPDF 1.22.2 library.
Version date: 2023-06-21 00:00:01.
Built for Python 3.8 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
The font you chose, Times-Roman, does not have these mathematical symbols.

**Comment by chaodreaming** [comment]
How to solve this problem, such as which font supports it

**Comment by chaodreaming** [comment]
I browsed relevant discussions in the community and found that page. insert_ Textbox can set other fonts, so why page.add_ Redact_ Annot does not choose to support it

**Comment by JorjMcKie** [comment]
> I browsed relevant discussions in the community and found that page. insert_ Textbox can set other fonts, so why page.add_ Redact_ Annot does not choose to support it

Your own example shows, that you need **_two different fonts_** to generate the desired content for the emptied rectangle.
And this is only one of several complications that may happen when filing space emptied by a redaction.

You still have all options available to achieve your goals.

**Comment by chaodreaming** [comment]
I'm not quite sure what you mean. All I need is the math font to solve the problem. I'll use page. insert_ The use of math font in textbox can solve the problem, but math font is applied in add_ Redact_ Annot is an error reported

**Comment by JorjMcKie** [comment]
Well, it has been decided some time ago to not invest in the effort to support arbitrary fonts out of the box. Supported are the Base-14 and the CJK fonts.
**_Plus any font for which there already exists text on that page._** That's it.
Requirements beyond this can still be satisfied by using normal text output features.

**Comment by chaodreaming** [comment]
Is it Machine translation? I can't understand it. I just want to know how to solve the problem that math is a question mark

**Comment by JorjMcKie** [comment]
```python

font=fitz.Font("math")
text="mathematical text"
tw = fitz.TextWriter(page.rect)
tw.fill_text(rect, text, font=font)
tw.write_text(page)
```

Where `rect` is the rectangle previously emptied via redaction.

**Comment by chaodreaming** [comment]
Although the extracted results are significantly different from the ones written back in, the formula is no longer a question mark. Thank you very much for your help
