### ISSUE TITLE
Using multiple fonts in a form fields

### ISSUE THREAD

**Issue by jtbai** [pymupdf/PyMuPDF#2573]
I'm trying to bold a few keywords in a text field (widget), and I have to either bold the whole text or no words at all.

I'd like to add to be able to some rich text elements to text fields, or even a markdown version of the text would be good (so I can bold and italicize some words).

As additional context, I'm using this to refill a game cards template and I would like to bold keywords so the players have an easy understanding of the main card points.

**Comment by JorjMcKie** [comment]
I am going to close this request for the time being.
This would have to be implemented by MuPDF anyway, before we could think of supporting it.
And there are no plans in this direction at the moment.
