### ISSUE TITLE
top and bottom image stripe lost in extractDICT()

### ISSUE THREAD

**Issue by banxian** [pymupdf/PyMuPDF#2580]
## Describe the bug (mandatory)
when parse certain scanned pdf, top and last row of image stripe lost in page dict.

## To Reproduce (mandatory)
```
import fitz
import sys

with fitz.open(sys.argv[1]) as doc:
    for page in doc.pages():
        pagewidth = page.rect.width / 72 * 600
        print("pagewidth", pagewidth)
        d = page.get_text("dict")
        blocks = d["blocks"]
        imageblocks = [b for b in blocks if b["type"] == 1]
```
use attached isoiec9899{ed1.0}en.img.1.pdf as argument

## Expected behavior (optional)
my input file have 139 stripe in page1, I expect all 139 image stripe parsed but only 137 instance found in imageblocks. im0/im138 which on top/bottom doesn't present in dict.

## Your configuration (mandatory)
 - Widows 10, LTSC 2017
 - Python 3.7.4, x64
 - PyMuPDF 1.22.5, pip pre-built package.

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

## Additional context (optional)
page.get_images() returned 139 object.

[isoiec9899{ed1.0}en.img.1.pdf](https://github.com/pymupdf/PyMuPDF/files/12248297/isoiec9899.ed1.0.en.img.1.pdf)

**Comment by JorjMcKie** [comment]
Not a bug, works as designed:
Images not fully contained in the given clip (in this case the full page, MediaBox) are no included. The top rectangle has a negative top coordinate `(0.0, -0.280029296875, 608.6400146484375, 5.719970703125)` so is above MediaBox, and bottom rectangle `(0.0, 845.239990234375, 608.6400146484375, 851.239990234375)` goes beyond the MediaBox bottom 851.0.
BTW text extraction also follows these conditions.

To include all image rectangles either do `page.get_image_info()` which deliberately does not use these confinements, or specify a clip explicitely larger than the MediaBox like this `blks = page.get_text("dict",clip=page.rect+(0, -5, 0, 5))["blocks"]` which increases the extraction area at top and bottom by 5 points and also includes your missed rectangles.
