### ISSUE TITLE
provide attribute `__version__`

### ISSUE THREAD

**Issue by workflowsguy** [pymupdf/PyMuPDF#2592]
**Is your feature request related to a problem? Please describe.**

A lot of Python packages like `pandas`, `numpy`, `pikepdf`provide their version through a `__version__` attribute. This makes it possible for a script to query the version of the module it imports.

It would be great if PyMuPdf would also implement this.

**Comment by JorjMcKie** [comment]
There already exists `fitz.version`.
![grafik](https://github.com/pymupdf/PyMuPDF/assets/8290722/19d2db18-ddbf-4c53-8957-4d40d05a3219)
And you can get the details:
![grafik](https://github.com/pymupdf/PyMuPDF/assets/8290722/7988f9bf-32e3-47df-acf5-206b26c747c8)

**Comment by workflowsguy** [comment]
Thank you, but it would still be useful to have this information also in a `__version__` attribute.

Consider the use case where information about the loaded modules and their versions has to be collected for diagnostic purposes.

This could be done by iterating over all modules similar to this:

```
for module_name in sys.modules.copy():
	if '.' not in module_name:
		try:
			print(f'Module: {module_name}\nVersion: {sys.modules[module_name].__version__}')
		except:
			print(f'Module: {module_name}\nVersion: not defined')
```

However, for all modules that do not follow this convention, extra code has to be written that gets that information individually.
