### ISSUE TITLE
how page.search_for to ignored text within '\n'?

### ISSUE THREAD

**Issue by a-jiang** [pymupdf/PyMuPDF#2595]
![image](https://github.com/pymupdf/PyMuPDF/assets/9330004/093939d1-f0e7-4531-93a0-3396db3f1a9d)

**Comment by JorjMcKie** [comment]
This cannot be done, we are sorry.
This is because the search would have to return two separate rectangles - one for each fragment.
This only works for words interrupted by hyphenation.
