### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by officialplayer** [pymupdf/PyMuPDF#2601]
error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [286 lines of output]
      Reading version file C:\Users\svhan\AppData\Local\Temp\pip-install-yacqvphs\traits_0a72c67407c14ec794be70afe378f904\traits\version.py       
      Package version from version file: ('6.3.2', '6df2ff9bd1d21c74e688aff6f67a19fbbefdd53b')
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\traits
      copying traits\api.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\base_trait_handler.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\constants.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\ctrait.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\editor_factories.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\has_traits.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\interface_checker.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\traits.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\traits_listener.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_base.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_converters.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_dict_object.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_errors.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_factory.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_handler.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_handlers.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_list_object.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_notifiers.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_numeric.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_set_object.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_type.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\trait_types.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\version.py -> build\lib.win-amd64-cpython-311\traits
      copying traits\__init__.py -> build\lib.win-amd64-cpython-311\traits
      creating build\lib.win-amd64-cpython-311\traits\adaptation
      copying traits\adaptation\adaptation_error.py -> build\lib.win-amd64-cpython-311\traits\adaptation
      copying traits\adaptation\adaptation_manager.py -> build\lib.win-amd64-cpython-311\traits\adaptation
      copying traits\adaptation\adaptation_offer.py -> build\lib.win-amd64-cpython-311\traits\adaptation
      copying traits\adaptation\adapter.py -> build\lib.win-amd64-cpython-311\traits\adaptation
      copying traits\adaptation\api.py -> build\lib.win-amd64-cpython-311\traits\adaptation
      copying traits\adaptation\__init__.py -> build\lib.win-amd64-cpython-311\traits\adaptation
      creating build\lib.win-amd64-cpython-311\traits\etsconfig
      copying traits\etsconfig\api.py -> build\lib.win-amd64-cpython-311\traits\etsconfig
      copying traits\etsconfig\etsconfig.py -> build\lib.win-amd64-cpython-311\traits\etsconfig
      copying traits\etsconfig\__init__.py -> build\lib.win-amd64-cpython-311\traits\etsconfig
      creating build\lib.win-amd64-cpython-311\traits\examples
      copying traits\examples\_etsdemo_info.py -> build\lib.win-amd64-cpython-311\traits\examples
      copying traits\examples\__init__.py -> build\lib.win-amd64-cpython-311\traits\examples
      creating build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\api.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\events.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\exceptions.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\exception_handling.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\expression.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\i_observable.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\observe.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\parsing.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_anytrait_filter.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_dict_change_event.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_dict_item_observer.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_filtered_trait_observer.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_generated_parser.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_has_traits_helpers.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_i_notifier.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_i_observer.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_list_change_event.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_list_item_observer.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_metadata_filter.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_named_trait_observer.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_observe.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_observer_change_notifier.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_observer_graph.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_set_change_event.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_set_item_observer.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_testing.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_trait_added_observer.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_trait_change_event.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\_trait_event_notifier.py -> build\lib.win-amd64-cpython-311\traits\observation
      copying traits\observation\__init__.py -> build\lib.win-amd64-cpython-311\traits\observation
      creating build\lib.win-amd64-cpython-311\traits\testing
      copying traits\testing\api.py -> build\lib.win-amd64-cpython-311\traits\testing
      copying traits\testing\doctest_tools.py -> build\lib.win-amd64-cpython-311\traits\testing
      copying traits\testing\nose_tools.py -> build\lib.win-amd64-cpython-311\traits\testing
      copying traits\testing\optional_dependencies.py -> build\lib.win-amd64-cpython-311\traits\testing
      copying traits\testing\unittest_tools.py -> build\lib.win-amd64-cpython-311\traits\testing
      copying traits\testing\__init__.py -> build\lib.win-amd64-cpython-311\traits\testing
      creating build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\check_observe_timing.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\check_timing.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_abc.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_any.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_anytrait_static_notifiers.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_array.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_array_or_none.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_automatic_adaptation.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_bool.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_callable.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_class_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_clone.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_configure_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_constant.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_constants.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_container_events.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_copyable_trait_names.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_copy_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_ctraits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_cythonized_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_date.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_datetime.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_delegate.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_deprecated_handlers.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_dict.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_directory.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_dynamic_notifiers.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_dynamic_trait_definition.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_editor_factories.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_enum.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_event_order.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_expression.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_extended_notifiers.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_extended_trait_change.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_file.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_float.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_float_range.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_get_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_has_required_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_has_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_historical_unpickling.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_instance.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_integer.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_integer_range.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_interfaces.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_interface_checker.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_int_range_long.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_keyword_args.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_list.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_listeners.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_list_events.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_long_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_map.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_new_notifiers.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_none.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_observe.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_pickle_validated_dict.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_prefix_list.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_prefix_map.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_property_delete.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_property_notifications.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_python_properties.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_range.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_readonly.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_regression.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_rich_compare.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_special_event_handlers.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_static_notifiers.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_string.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_str_handler.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_sync_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_target.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_time.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_traits_listener.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_base.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_change_event_tracer.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_converters.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_cycle.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_default_initializer.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_dict_list_set_event.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_dict_object.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_exceptions.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_get_set.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_list_dict.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_list_object.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_prefix_list.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_set_object.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_trait_types.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_tuple.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_type.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_ui_notifiers.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_undefined.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_unicode_traits.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_union.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_uuid.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_validated_tuple.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_version.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_view_elements.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\test_weak_ref.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\tuple_test_mixin.py -> build\lib.win-amd64-cpython-311\traits\tests
      copying traits\tests\__init__.py -> build\lib.win-amd64-cpython-311\traits\tests
      creating build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\api.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\async_trait_wait.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\camel_case.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\clean_strings.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\deprecated.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\event_tracer.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\home_directory.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\import_symbol.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\resource.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\toposort.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\trait_documenter.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\weakiddict.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\_traitsui_helpers.py -> build\lib.win-amd64-cpython-311\traits\util
      copying traits\util\__init__.py -> build\lib.win-amd64-cpython-311\traits\util
      creating build\lib.win-amd64-cpython-311\traits\adaptation\tests
      copying traits\adaptation\tests\abc_examples.py -> build\lib.win-amd64-cpython-311\traits\adaptation\tests
      copying traits\adaptation\tests\benchmark.py -> build\lib.win-amd64-cpython-311\traits\adaptation\tests
      copying traits\adaptation\tests\interface_examples.py -> build\lib.win-amd64-cpython-311\traits\adaptation\tests
      copying traits\adaptation\tests\lazy_examples.py -> build\lib.win-amd64-cpython-311\traits\adaptation\tests
      copying traits\adaptation\tests\test_adaptation_manager.py -> build\lib.win-amd64-cpython-311\traits\adaptation\tests
      copying traits\adaptation\tests\test_adaptation_offer.py -> build\lib.win-amd64-cpython-311\traits\adaptation\tests
      copying traits\adaptation\tests\test_adapter.py -> build\lib.win-amd64-cpython-311\traits\adaptation\tests
      copying traits\adaptation\tests\test_global_adaptation_manager.py -> build\lib.win-amd64-cpython-311\traits\adaptation\tests
      copying traits\adaptation\tests\__init__.py -> build\lib.win-amd64-cpython-311\traits\adaptation\tests
      creating build\lib.win-amd64-cpython-311\traits\etsconfig\tests
      copying traits\etsconfig\tests\test_etsconfig.py -> build\lib.win-amd64-cpython-311\traits\etsconfig\tests
      copying traits\etsconfig\tests\__init__.py -> build\lib.win-amd64-cpython-311\traits\etsconfig\tests
      creating build\lib.win-amd64-cpython-311\traits\examples\tests
      copying traits\examples\tests\test_etsdemo_info.py -> build\lib.win-amd64-cpython-311\traits\examples\tests
      copying traits\examples\tests\__init__.py -> build\lib.win-amd64-cpython-311\traits\examples\tests
      creating build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_dict_change_event.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_dict_item_observer.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_exception_handling.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_expression.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_filtered_trait_observer.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_generated_parser.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_has_traits_helpers.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_list_change_event.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_list_item_observer.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_metadata_filter.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_named_trait_observer.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_observe.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_observer_change_notifier.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_observer_graph.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_parsing.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_set_change_event.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_set_item_observer.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_trait_added_observer.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_trait_change_event.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\test_trait_event_notifier.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      copying traits\observation\tests\__init__.py -> build\lib.win-amd64-cpython-311\traits\observation\tests
      creating build\lib.win-amd64-cpython-311\traits\testing\tests
      copying traits\testing\tests\test_nose_tools.py -> build\lib.win-amd64-cpython-311\traits\testing\tests
      copying traits\testing\tests\test_optional_dependencies.py -> build\lib.win-amd64-cpython-311\traits\testing\tests
      copying traits\testing\tests\test_unittest_tools.py -> build\lib.win-amd64-cpython-311\traits\testing\tests
      copying traits\testing\tests\__init__.py -> build\lib.win-amd64-cpython-311\traits\testing\tests
      creating build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_async_trait_wait.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_camel_case.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_clean_strings.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_deprecated.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_import_symbol.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_message_records.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_record_containers.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_record_events.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_resource.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_traitsui_helpers.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_trait_documenter.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\test_weakidddict.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      copying traits\util\tests\__init__.py -> build\lib.win-amd64-cpython-311\traits\util\tests
      creating build\lib.win-amd64-cpython-311\traits\examples\introduction
      copying traits\examples\introduction\0_introduction.py -> build\lib.win-amd64-cpython-311\traits\examples\introduction
      copying traits\examples\introduction\1_validation.py -> build\lib.win-amd64-cpython-311\traits\examples\introduction
      copying traits\examples\introduction\2_initialization.py -> build\lib.win-amd64-cpython-311\traits\examples\introduction
      copying traits\examples\introduction\3_observation.py -> build\lib.win-amd64-cpython-311\traits\examples\introduction
      copying traits\examples\introduction\4_properties.py -> build\lib.win-amd64-cpython-311\traits\examples\introduction
      copying traits\examples\introduction\5_documentation.py -> build\lib.win-amd64-cpython-311\traits\examples\introduction
      copying traits\examples\introduction\6_visualization.py -> build\lib.win-amd64-cpython-311\traits\examples\introduction
      copying traits\examples\introduction\default.css -> build\lib.win-amd64-cpython-311\traits\examples\introduction
      copying traits\examples\introduction\index.rst -> build\lib.win-amd64-cpython-311\traits\examples\introduction
      creating build\lib.win-amd64-cpython-311\traits\examples\introduction\images
      copying traits\examples\introduction\images\LICENSE.txt -> build\lib.win-amd64-cpython-311\traits\examples\introduction\images
      copying traits\examples\introduction\images\sample_0001.png -> build\lib.win-amd64-cpython-311\traits\examples\introduction\images
      copying traits\examples\introduction\images\sample_0002.png -> build\lib.win-amd64-cpython-311\traits\examples\introduction\images
      creating build\lib.win-amd64-cpython-311\traits\tests\test-data
      creating build\lib.win-amd64-cpython-311\traits\tests\test-data\historical-pickles
      copying traits\tests\test-data\historical-pickles\README -> build\lib.win-amd64-cpython-311\traits\tests\test-data\historical-pickles       
      copying traits\tests\test-data\historical-pickles\hipt-t5.2.0-p0-float-ctrait.pkl -> build\lib.win-amd64-cpython-311\traits\tests\test-data\historical-pickles
      copying traits\tests\test-data\historical-pickles\hipt-t5.2.0-p1-float-ctrait.pkl -> build\lib.win-amd64-cpython-311\traits\tests\test-data\historical-pickles
      copying traits\tests\test-data\historical-pickles\hipt-t5.2.0-p2-float-ctrait.pkl -> build\lib.win-amd64-cpython-311\traits\tests\test-data\historical-pickles
      copying traits\tests\test-data\historical-pickles\hipt-t5.2.0-p3-float-ctrait.pkl -> build\lib.win-amd64-cpython-311\traits\tests\test-data\historical-pickles
      copying traits\tests\test-data\historical-pickles\hipt-t5.2.0-p4-float-ctrait.pkl -> build\lib.win-amd64-cpython-311\traits\tests\test-data\historical-pickles
      copying traits\tests\test-data\historical-pickles\hipt-t5.2.0-p5-float-ctrait.pkl -> build\lib.win-amd64-cpython-311\traits\tests\test-data\historical-pickles
      copying traits\tests\test-data\historical-pickles\generate_pickles.py -> build\lib.win-amd64-cpython-311\traits\tests\test-data\historical-pickles
      running build_ext
      building 'traits.ctraits' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

**Comment by officialplayer** [comment]
how to solve this i want to install it

**Comment by julian-smith-artifex-com** [comment]
This doesn't look to have anything to do with PyMuPDF.
