### ISSUE TITLE
Cannot rotate insterted pages

### ISSUE THREAD

**Issue by paternal** [pymupdf/PyMuPDF#261]
Hello,
I want to combine single *rotated* pages (from a source PDF) to a blank page of a new PDF (kind of [4-nup](https://pymupdf.readthedocs.io/en/latest/faq/#how-to-combine-single-pages), with rotations). Reading the documentation about [Matrix](https://pymupdf.readthedocs.io/en/latest/matrix/), I tried:

~~~py
destpage.showPDFpage(rect * fitz.Matrix(180), src, number)
~~~

But it does not give the intended result. Is it possible to rotate pages while insersting them using `showPDFpage`?

# MWE

The source looks like this ([source.pdf](https://github.com/pymupdf/PyMuPDF/files/2944923/source.pdf) one A6 page, with text, svg, and bitmap): 
![source](https://user-images.githubusercontent.com/6587757/54016541-9ce0a500-4183-11e9-89cb-071b590707ab.png)

I run this script:

~~~py
import fitz
src = fitz.open("source.pdf")
dest = fitz.open()                      # empty output PDF

width, height = fitz.PaperSize("a4")   # A4 portrait output page format
r = fitz.Rect(0, 0, width, height)

# define the 4 rectangles per page
r1 = r * 0.5                           # top left rect
r2 = r1 + (r1.width, 0, r1.width, 0)   # top right
r3 = r1 + (0, r1.height, 0, r1.height) # bottom left
r4 = fitz.Rect(r1.br, r.br)            # bottom right

# now copy input pages to output
sourcepage = src[0]
destpage = dest.newPage(-1, width = width, height = height)

# Rotate 20 degrees
destpage.showPDFpage(r1 * fitz.Matrix(20), src, sourcepage.number)
# Rotate 20 degrees
destpage.showPDFpage(r2 * fitz.Matrix(fitz.Identity).preRotate(20), src, sourcepage.number)
# Upside down, plus some random shift to move it back on the visible page
destpage.showPDFpage(r3 * fitz.Matrix(-1, 0, 0, -1, r1.x1, 1.5*r.y1), src, sourcepage.number)
# Upside down, plus some random shift to move it back on the visible page
destpage.showPDFpage(r4 * fitz.Matrix(1,1).preRotate(180).preTranslate(-1.5*r.x1, -1.5*r4.y1), src, sourcepage.number)

dest.save("dest.pdf")
~~~

And I would like to get this (some pages rotated by 20°, some pages rotated by 180°):
![expected](https://user-images.githubusercontent.com/6587757/54016752-3d36c980-4184-11e9-8e61-cb1134b82e03.png)

Instead, I get this ([dest.pdf](https://github.com/pymupdf/PyMuPDF/files/2944946/dest.pdf): some (random?) translations, but no rotation):
![dest](https://user-images.githubusercontent.com/6587757/54016779-53dd2080-4184-11e9-8cb4-ef4a3b7f9248.png)

Thanks for your work,
Louis

**Comment by JorjMcKie** [comment]
Hi,
thanks for your interest!

1. PDF page rotation angles (by definition) must be multiples of 90 (see the Adobe manual). Page rotation is nothing more than a simple single parameter inside the page's object definition, e.g. `/Rotate 270`.
2. The rect parameter of `showPDFpage `always if assumed to be a true rectangle (90° angles, edges parallel to x and y axis). Whatever matrix you apply to this parameter: it will be a such a true rectangle - potentially not fully contained in the target page. The source PDF page rectangle (either the full page or the `clip` part) will be scaled to fit. Whether side proportions are maintained is parameter-controlled.
3. Unfortunately, by construction of `showPDFpage`, the `/Rotate` parameter cannot be included and is always ignored: the **original** source page orientation is shown.
4. The only thing you can currently do is creating a pixmap of a source page using an arbitrary matrix, get the binary stream of it (`pix.getImageData()`) and then use page method `insertImage`.

I will use your inquiry to check whether a future enhancement might lift these restrictions in `showPDFpage`.

**Comment by paternal** [comment]
Thanks for your answer. Actually, I only need a 180° rotation (the 20° rotation was only as an example), without the pixmap (to keep text searchable, among other things). I am using [PyPDF2](https://github.com/mstamy2/PyPDF2), but I was interested in switching to PyMuPDF because:
- it is waaaaay faster;
- it crops pages before merging them (see mstamy2/PyPDF3#11).

I will stick to PyPDF2…
Thanks,
-- Louis

**Comment by JorjMcKie** [comment]
Hm, sorry to hear that ;-)

Keep an eye on PyMuPDF ... as I said: I may come out with this feature added in the next versions ...

Anyway, let's keep this issue open, so you will be notified, when I refer to it once this happens.

**Comment by JorjMcKie** [comment]
Hi,
just uploading a new v1.14.10, which should include what you require. The wheels for Windows and Linux should be in PyPI in a minute.

You would use the method like this:

```python
page.showPDFpage(rect, src, pno, rotate=180, ...)
```

The rotate parameter can be any (integer) multiple of 90.

**Comment by paternal** [comment]
Awesome! I will test this at home (I am at work, with limited control over my computer). Thanks!

**Comment by paternal** [comment]
It works. Thank you very much.

**Comment by JorjMcKie** [comment]
Good!!!
Thanks for using PyMuPDF then ...
