### ISSUE TITLE
annotation with chinese

### ISSUE THREAD

**Issue by danny1023** [pymupdf/PyMuPDF#2616]
When I want to create a Chinese free text annotation with "Arial" font, it can't display correctly on pdf.
But if I implement the font on `insert_text` or `insert_textbox`, it works.

here it the codes:
```
import fitz
text = "肿瘤诊断"
doc = fitz.open("demo.pdf")
page = doc.load_page(0)
page.draw_rect((90, 50, 90+100, 100), color=(1, 1, 1), fill=(0, 0, 0), width=0) 
ff = page.insert_font(fontname="F0", fontfile="Arial Unicode.ttf", fontbuffer=None,
                      set_simple=False)
page.insert_text((90, 100), text, fontname="F0", fontsize=12, color=(0, 0, 1), fill=None,
                 render_mode=0, border_width=1, rotate=0, morph=None, overlay=True)

r1 = fitz.Rect(200, 50, 200+100, 100)
annot = page.add_freetext_annot(
    r1,
    text,
    fontsize=12,
    fontname="china-s",
    rotate=0,
    text_color=black,
    fill_color=stdcolor[0],
    align=fitz.TEXT_ALIGN_LEFT
)
annot.set_border(width=1, dashes=[])
annot.update(text_color=black, fill_color=stdcolor[0])

r1 = fitz.Rect(400, 50, 400+100, 100)
page.insert_textbox(r1, text, fontname="F0", fontsize=12, color=(0, 0, 1), fill=black,
                 render_mode=0, border_width=1, rotate=0, morph=None, overlay=True)
doc.save("test.pdf", garbage=4, deflate=True)
```

And here is the pdf output:
<img width="476" alt="a873117b9f07b5bc3a06c79bd8c22566" src="https://github.com/pymupdf/PyMuPDF/assets/22441771/bf80cfdf-9c55-48c8-9b13-8b724367d9ab">

If there has a way to fix this problem?

**Comment by danny1023** [comment]
BTW, when I double click the annotation, the words in it is correct.
And if I adjust the annotation box, it can also display correctly.

**Comment by JorjMcKie** [comment]
PyMuPDF does not support arbitrary fonts in annotations - please see the documentation.
Supported are the Base-14 fonts and some sets of CJK (Chinese, Korean, Japanese) fonts. The base library dynamically select the right font when it inspects the desired text for the annotation.
In your case, this is font Mincho.

I looked it up: the Mincho font has no glyphs defined for characters 肿 and 诊. The other two characters of your text are ok.
Therefore you see spaces where those two characters occur. When editing the annotation with a PDF viewer that supports rich text for annotations, it will replace the Mincho font with a supporting one.
This explains the behavior you mentioned.

That said, if you want to add non-annotation text, there exists no such restriction: whatever font you specify, the text will be shown as supported by the font.

So I am sory to say, that there is no solution for your special case.

**Comment by danny1023** [comment]
Thanks for the reply!
