### ISSUE TITLE
fitz Page.get_image_rects not return image location infos

### ISSUE THREAD

**Issue by weikenxq** [pymupdf/PyMuPDF#2618]
Example code:
```
import fitz
pdf_filename = "test.pdf"
pages = fitz.Document(pdf_filename)
print("fitz_version", fitz.version)
page = pages[0]
images = page.get_images(full=True)
print("images", images)
image_rects = page.get_image_rects(images[0], transform=True)
print("image_rects", image_rects)
```

Output:
fitz_version ('1.22.5', '1.22.2', '20230621000001')
images [(28, 29, 529, 238, 8, 'DeviceRGB', '', 'Image9', 'FlateDecode', 22)]
image_rects []

Attachment:
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/12425472/test.pdf)

Snapshot of pdf:
![image](https://github.com/pymupdf/PyMuPDF/assets/42831401/0484d545-85a6-4f78-bc65-bd25d85066e1)

**Comment by JorjMcKie** [comment]
This is no bug.
The page simply does not display the image. It is displayed as part of a `/Artifact <</Subtype/Watermark/Type/Pagination>>` command.
