### ISSUE TITLE
Extracting jpx-based image mask as jpx image

### ISSUE THREAD

**Issue by HinTak** [pymupdf/PyMuPDF#2643]
**Is your feature request related to a problem? Please describe.**

Some scan-generated pdf consists of color images plus image masks. It is the image mask would is the interesting part containing a high-res 1-bit image of the text.

**Describe the solution you'd like**

**Describe alternatives you've considered**

Doing `mutool show -b -e -o out.jpx in.pdf objnum` is close enough except it is headerless - this gives a headerless jpx data. Without `-e`, it gives headerless pbm. Some way of recreating and pretending the jpx header?

**Additional context**

**Comment by JorjMcKie** [comment]
This is not achievable by PyMuPDF. Please direct the request to MuPDF. Best start by discussing this in MuPDF's Dicord channel https://discord.com/channels/770681584617652264/770685907279282196.

**Comment by HinTak** [comment]
I beg to differ. `mutool show ` with or without -b basically separate the header info with the jpx payload. So it is a matter of recombining the header with the payload, and it is more suitable to do it at a scripting level, than adding such option on the c side.

I assume it is possible to do the equivalent of "mutool show " with or without -b and the -e option in pymupdf. It is just a matter of re-arranging/combine these options.

**Comment by JorjMcKie** [comment]
PyMuPDF is a binding for the MuPDF library. It relies on its capabilities in every aspect when it comes to document handling and dealing with images.
So PyMuPDF can present capabilities on the Python level - if there is a corresponding basis in MuPDF.

So WRT JPX headers: they either are made available in some way by MuPDF - then there is a chance to also have it in PyMuPDF.
Or there is no way at all.

But with PyMuPDF you can **_access every PDF object_** in any way you like already today:
Read the source of any xref or the PDF trailer, or the catalog, extract the binary stream (raw or decompressed), etc., etc.
These capabilities are very much equivalent to everything available via `mutool show`.

**Comment by HinTak** [comment]
@JorjMcKie FWIW, actually, this is possible with pymupdf - most of the needed information was in: https://github.com/pymupdf/PyMuPDF/issues/685 - for jbig2 mask, the header is 13 bytes. Jbig2dec doesn't seem to care about footers.
