### ISSUE TITLE
Incorrect drawing of elements using shape and svg

### ISSUE THREAD

**Issue by vkovenko** [pymupdf/PyMuPDF#2648]
Greetings. I tried to redraw SVG on page using shape (https://pymupdf.readthedocs.io/en/latest/shape.html#Shape.finish). 
The pdf object looks the following way:
<img width="175" alt="Знімок екрана 2023-09-07 о 23 44 50" src="https://github.com/pymupdf/PyMuPDF/assets/117199553/a74b4e08-b339-4a3a-bb45-6560ca00c76c">
That's how it looked like after redrawing everything using the code from documentation (https://pymupdf.readthedocs.io/en/latest/recipes-drawing-and-graphics.html#how-to-extract-drawings).
<img width="82" alt="Знімок екрана 2023-09-07 о 23 57 44" src="https://github.com/pymupdf/PyMuPDF/assets/117199553/fd88e117-494b-4319-8ec4-5efc07a39fbd">
It seems that something is wrong with evenodd parameter (that's my theory). How can I change the code in documentation to get exactly same result in terms of SVG graphics as it can be seen on first image?

**Comment by JorjMcKie** [comment]
Please provide the data for reproducing the situation.

**Comment by vkovenko** [comment]
Sure, I will anonymize all the sensitive information and send you a file.

**Comment by JorjMcKie** [comment]
Thanks for the file.
I have to manage your expectations - I hope you have read the documentation thoroughly:
There is no guarantee (and there never will be one) to faithfully reproduce whatever extracted vector graphics with the `Shape` classes draw methods.
Of course: if there indeed are errors in the extracted data themselves, they need to be fixed. But it also remains true, that today's draw capabilities do not cover 100% of all the myriads of possible situations.

**Comment by vkovenko** [comment]
Got it, thank you.
I went trough all documentation, just thought that I've probably missed something and that's why the output was not aligned with what I expected to see.

**Comment by JorjMcKie** [comment]
> Got it, thank you. I went trough all documentation, just thought that I've probably missed something and that's why the output was not aligned with what I expected to see.

Ok, understood, thank you. Please do come back if you suspect a wrong output of `page.get_drawings()`.
