### ISSUE TITLE
ModuleNotFoundError: No module named 'frontend'

### ISSUE THREAD

**Issue by DennisWYH** [pymupdf/PyMuPDF#266]
Hi, I'm having a problem with Fitz library. I have installed Fitz with `pip install fitz` in my virtualenv 'smartocr'. It's successfully installed. However, when I try to call it in my flask web application
`Traceback (most recent call last):
  File "hello.py", line 15, in <module>
    from utils.convert_pdf import convert_pdf
  File "/Users/marve/Documents/codingProjects/fi-report-recog/utils/convert_pdf.py", line 1, in <module>
    from utils.pdf_to_excel import convert_pdf_to_pics,image_to_string,parse_hocr,hocr_to_excel,add_resolution
  File "/Users/marve/Documents/codingProjects/fi-report-recog/utils/pdf_to_excel.py", line 11, in <module>
    import fitz
  File "//anaconda/envs/smartocr/lib/python3.6/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'`

![image](https://user-images.githubusercontent.com/17793533/54347865-cf5a3880-4682-11e9-9109-a3a81f3ffe95.png)

it returned the above error. What I don't understand here is that, under the same directory of __init__.py file, the frontend.py file exists, however the error message says it can't be found. I have been working on it for days, please if anyone can help, thank you in advance.

**Comment by JorjMcKie** [comment]
In order to install, issue ``pip install pymupdf`` not ``fitz``.
``fitz`` must be name the name of a completely different package which has nothing to do with me.

**Comment by DennisWYH** [comment]
Thank you for your advice. After another day 's working. I realize indeed this Fitz library is not necessary for my project. Because this part of the code is written by my colleague(So I'm not familiar with the logic), and she must be confused to add the library "fitz" to our requirement list, therefore causing trouble while using pymupdf library due to the same naming. I comment here just in case anyone runs into the same unlucky issue as I did...Btw, while browsing through the whole issue log...I'm very curious if you really stay in swimming pool and harvest coconut for the most of the day (you mentioned that in another conversion). My friend is betting with me that you are joking or something.

**Comment by JorjMcKie** [comment]
Well, not **every** day and not **all** day long. However, I do have a swimming pool, which we are using almost daily, and we do have 2 coconut palm trees, and just recently harvested about 20 nuts, made nice drinks and cake from them. Not to mention our lemon and orange trees, lechosa (Papaya) trees, Maracuja (parchita) and about 10 other species of palm trees.
Seriously.
So you win the bet!
