### ISSUE TITLE
Page/Document.add_image which takes an image dictionary as from doc.extract_image(xref) 

### ISSUE THREAD

**Issue by HinTak** [pymupdf/PyMuPDF#2660]
**Is your feature request related to a problem? Please describe.**
This is sort of a follow-up to
https://github.com/pymupdf/PyMuPDF/issues/2643
In some pdf's made from scans (luradocument...), the interesting part of the document is the image mask which contains the scanned text, not the images. So it would be nice to just extract those and put into a smaller and "text-only" pdf.

**Describe the solution you'd like**
It looks like upstream's pdf_add_image() can take /preserve information from a fz_image which contains the original compression info+stream. This seems to become the image dictionary, which contains the raw stream plus compression info. Pixmap can consume it (or equivalent from reading xref) but that doesn't seems to be available to *add_image()?

**Describe alternatives you've considered**
The Alternative is basically #2643 - extract the image and reassemble the pdf.

**Additional context**

**Comment by JorjMcKie** [comment]
Today, images can only be inserted by using the `Page` method. This has no specific reason other than practical considerations.

No major problem to make a `Document.insert_image()` method giving it the same/similar parameters.
In particular, the image could be given as a filename, Pixmap or `bytes` object, the latter of which might be `img["image"]` of a previously extracted `img = doc.extract_image(xref)`.
As before, the method would return the new xref generated as part of the insertion.

The inserted image at this point in time will not be used by anything else in the PDF of course. If this remains like so, it will be deleted again on the next save with a garbage collection option >0.

**Comment by JorjMcKie** [comment]
Under the hood, `page.insert_iamge()` is using that C-function of course.
Fact is, that a Pixmap does not longer contain **_all_** information of the image from which it has been created.
When inserting a Pixmap as image, this will happen via in internal conversion to PNG - causing the standard compression for PNG in PDF being used. Exception is a GRAY Pixmap with black and white only: then a CCITTFaxDecode compression will result.
Therefore, `insert_image()` accepts original images from file or memory too. In the ideal case, the original compression will be maintained.

**Comment by JorjMcKie** [comment]
Implementing image insertion on the document level only makes sense if the image will actually be used by some page. Otherwise it will be removed by way of the next garbage collection.

So either inserting the image in the traditional way (into some page) is the way to go, or inserting it in a "temporary" (i.e. immediately to be deleted) page achieves the same goal.
