### ISSUE TITLE
Dynamic acroform not rendering

### ISSUE THREAD

**Issue by MallRoy** [pymupdf/PyMuPDF#2668]
## Describe the bug (mandatory)
I have provided a sample file, where user can select the value mentioned in the dropdown, which will trigger JS actions for appending contents into the pdf. [sample.pdf](https://github.com/pymupdf/PyMuPDF/files/12593788/level.pdf)

## To Reproduce (mandatory)
import fitz
doc = fitz.open('level.pdf')  # new or existing PDF
page = doc[0]

for field in page.widgets():
    print (field.field_name)
    if (field.field_name == 'Dropdown18'):
        field.field_value = '4'
        field.update()

doc.save("newlevel.pdf")
doc.close()
## Expected behavior (optional)
New pdf should be created with a box and the number of pages in the pdf should be changed.

## Your configuration (mandatory)
 - Operating system: windows 10
 - Python version: 3.9
 - PyMuPDF version: 1.22.5

## Additional context (optional)
The dynamic acroform works as expected in adobe pdf viewer.

**Comment by JorjMcKie** [comment]
Executing JavaScripts is not supported by PyMuPDF itself.
Apart from the fact, that this JS is support by Adobe, but not by e.g. Foxit, Nitro or PDFXchange viewers.

**Comment by JorjMcKie** [comment]
When inter-field validations are entered in one of the relevant JS script actions are stored in the field, then PyMuPDF will dynamically create the appropriate entry in `AcroForm` - but again, won't execute any of that itself.
