### ISSUE TITLE
Reading Annotation Rotations

### ISSUE THREAD

**Issue by bjhowie** [pymupdf/PyMuPDF#267]
Hi,

Is there a simple way to access the rotation of an annotation? The 'Rect' function appears to just return a rectangle oriented to the global X/Y axes which envelopes the annotation.

Apologies if this is covered in the docs and i'm missing something.

**Comment by JorjMcKie** [comment]
The annot rect is as defined in Adobe's manual, table 8.15, pp. 606 ``(Required) The annotation rectangle, defining the location of the annotation on the page in default user space units.`` It has no rotation as an own property.
But there is property ``annot.flags``, an integer that can be checked and set. A combination of sub-properties coded as bit switches. One of those is ``ANNOT_XF_NoRotate 16 – If set, do not rotate the annotation’s appearance to match the rotation of the page. The upper-left corner of the annotation rectangle remains in a fixed location on the page, regardless of the page rotation.``

**Comment by bjhowie** [comment]
Thanks for your response Jorj.

I'm just trying to figure out if i rotate an annotation in a PDF by say 45 degrees, how i can then read that rotation relative to the page rotation back with pymupdf. A custom annotation dictionary entry perhaps? 

Apologies as i'm not very familiar with the PDF standard.

**Comment by JorjMcKie** [comment]
No, what I am saying is: **you cannot rotate annotations at all** as per the PDF standard (for all I know).
This is independent from PyMuPDF.
All you can do is what mentioned previously.
Also works: if you have a FreeText annotation, you can have the text appear in multiples of 90 degress.

**Comment by bjhowie** [comment]
Ah i see what you mean. I think you're correct.
The annotations i'm reading are created in a commercial PDF mark-up software that allows annotation rotations somehow.

Might just put this one in the too hard basket for now. Thanks.

**Comment by JorjMcKie** [comment]
You can show the object definition of an annotation like this: ``doc._getXrefString(annot.xref)``. E.g.
```
'<</Type/Annot/Subtype/PolyLine/F 4/Vertices[100 742 200 642]/BS<</W 1>>/C[0 0 1]/Rect[95 637 205 747]/AP<</N 7 0 R>>/IC[1 1 0]/LE[/Diamond/Circle]>>'
```

I am pretty sure you wont find any rotation parameter there ... otherwise, please do send the PDF by all means if possible!
Every (almost) annotation object also has one or more associated objects which control the appearance. Represented by the ``AP<<...>>`` parameter above. The ``/N`` sub-parameter points to the "normal" appearance object, in this case it has the xref 7. Looking there ``doc._getXrefString(7)`` returns
```
'<</Type/XObject/Subtype/Form/BBox[95 637 205 747]/Matrix[1 0 0 1 0 0]/Length 390/Resources 8 0 R>>'
```
Maybe your example shows something here with a ``/Matrix`` parameter which does **not** equal ``[1 0 0 1 0 0]`` (which is the do-nothing matrix).

**Comment by bjhowie** [comment]
Ah that's solved it!

The annotations that have non-zero rotations have an extra 'Rotation' parameter. I've copied the XrefString below. I'll send through an example PDF when i can as the page content on the one i'm using is sensitive and i'm using Foxit at the moment which cant rotate annotations.

`<</P 4144 0 R/BS<</S/S/W 2/Type/Border>>/RD[1 1 1 1]/C[1 0 0]/T(XXX)/Rect[1150.24 1482.3 1188.52 1535.43]/F 4/Subj(column)/Type/Annot/Subtype/Square/IC[1 0 0]/CreationDate(D:20180913150801+10'00')/M(D:20180913150801+10'00')/Rotation 303/AP<</N 20864 0 R>>/NM(NMARNVKEALAGUEMV)>>`

Any recommendations on the best way to parse this into a python dictionary?

**Comment by JorjMcKie** [comment]
Hm, I'm afraid not really at the moment. Maybe best use the ``re`` module or simply locate string ``/Rotate`` skip any blanks and then use the following bytes until no longer being digits.

The number 303 is the rotation angle? or another object number?

**Comment by JorjMcKie** [comment]
The ``/Rotation`` parameter there is definitely not official: the above mentioned book does not contain it for any annot type.
So your PDF maker has "illegally" inserted it (PDF does not defend itself against any such abuse). And the interpretation of the parameter is then done inside the "command source", which is part of the appearance object with xref 20864. You can read out this command source (something in ``bytes`` format, therefore the ``decode()`` function) like this: ``doc._getXrefStream(20864).decode()``. PDF creator software is generally free to do whatever they want in there - even showing completely different things than announced in the annot definition (e.g. show a circle even if defined to be a rectangle).

**Comment by bjhowie** [comment]
The 303 appears to be an anti-clockwise rotation of the annotation.
I've attached a PDF with a few rotated annotations if you're interested.

[rotated_annotation_test.pdf](https://github.com/pymupdf/PyMuPDF/files/3037893/rotated_annotation_test.pdf)

**Comment by JorjMcKie** [comment]
thanks a lot - sure I am interested!

**Comment by JorjMcKie** [comment]
thanks a lot - sure I am interested!

**Comment by bjhowie** [comment]
Discovered an interesting phenomenon when trying to extract node coordinates from a rotated rectangle annotation. To get the correct coordinates i need to rotate by 90 degrees and flip horizontally.
Any idea why that may be the case? 

Code is below. Note the two 'fudge' matrices i've had to include

```
def get_rect_annot_coords(annot,scale=1):
    doc=annot.parent.parent
    
    #Find appearance xref
    xrstr=doc._getXrefString(annot.xref)
    ri=xrstr.find("AP<<")
    ps=xrstr[ri+4:]
    ri=ps.find(">>")
    ps1=ps[:ri].split(" ")
    APref=int(ps1[1])
    
    #Find appearance matrix
    apstr=doc._getXrefString(APref)
    ri=apstr.find("/Matrix[")
    ps=apstr[ri+8:]
    ri=ps.find("]")
    ps2=ps[:ri].split(" ")
    APM=list(map(float,ps2))
    APMat=fitz.Matrix(APM[0],APM[1],APM[2],APM[3],APM[4],APM[5])
    
    #Find appearance BBox
    ri=apstr.find("/BBox[")
    ps=apstr[ri+6:]
    ri=ps.find("]")
    ps2=ps[:ri].split(" ")
    BB=list(map(float,ps2))

    fudgemat1 = fitz.Matrix(90)
    fudgemat2 = fitz.Matrix(-1,1)    
    rectq=fitz.Rect(BB[0],BB[1],BB[2],BB[3]).quad
    tfq=rectq.transform(APMat).transform(fudgemat1).transform(fudgemat2)
    coords=[(tfq.ul.x,tfq.ul.y),(tfq.ur.x,tfq.ur.y),(tfq.lr.x,tfq.lr.y),(tfq.ll.x,tfq.ll.y)]
    coords=list(map(lambda a: (scale*(annot.rect.x0+a[0]),scale*(annot.rect.y0+a[1])),coords))
    return(coords)
```

**Comment by JorjMcKie** [comment]
Uff - sophisticated code!
Maybe I should really think about a routine that interprets PDF dictionaries to Python ones ...

1. be aware that a PDF keyword like ``/Matrix`` may be followed by 0 or more (white) spaces before its parameter starts: ``/Matrix[`` or ``/Matrix   [``, etc. So in the general case, you need an extra round to find the left bracket. Just generally, arbitrary white spaces (including line breaks and stuff) or allowed everywhere.

2. Makers of the appearance object have the choice to either specify BBox in the desired way, or to put that logic into its contents stream. So BBox may or may not reflect the full truth.

3. It also may be that the page itself contains some geometry changing tricks (which would then be buried in transformation matrices).

4. The rectangle coordinates you are extracting above are **NOT** the coordinates of the corresponding PyMuPDF rectangle. MuPDF regards the page's **top-left** as point (0, 0), whereas in PDF (0, 0) is **bottom-left**. To cope with this pesky difference, I have created a page method that calculates a transformation matrix for this: ``page._getTransformation()``. You can use this and its inverse matrix to transform between PDF and MuPDF coordinates.

**Comment by bjhowie** [comment]
Thanks very much Jorj. You've been a great help!

**Comment by JorjMcKie** [comment]
A pleasure to help.

However, Iam afraid I won't be able to implement anything similar to this rotation feature in PyMuPDF. While it certainly would technically be possible, the MuPDF base library supports annotations to a great extent since their version 1.14.0. And presumably they are on a path to increase this. So, whatever I do in the annotations topic, is endangered to be overhauled by their next version ...

What I could do nevertheless, is developing a routine which converts PDF dictionaries to Python dictionaries, something like this:
Assuming you have a PDF xref 3 looking like this
```
3 0 obj
<</Contents 31 0 R/Type/Page/MediaBox[0 0 595.32 841.92]/Rotate 0
/Parent 12 0 R/Resources<</ExtGState<</R7 26 0 R>>
/Font<</R8 27 0 R/R10 21 0 R/R14 15 0 R/R12 24 0 R/R23 7 0 R>>
/ProcSet[/PDF/Text]>>>>
endobj
```
a method call ``doc.getObjectDict(3)`` would deliver 
```python
{
    "/Contents": [
        "xref",
        31
    ],
    "/Type": "/Page",
    "/MediaBox": [
        0,
        0,
        595.32,
        841.92
    ],
    "/Rotate": 0,
    "/Parent": [
        "xref",
        12
    ],
    "/Resources": {
        "/ExtGState": {
            "/R7": [
                "xref",
                7
            ]
        },
        "/Font": {
            "/R8": [
                "xref",
                27
            ],
            "/R10": [
                "xref",
                21
            ],
            "/R14": [
                "xref",
                15
            ],
            "/R12": [
                "xref",
                24
            ],
            "/R23": [
                "xref",
                7
            ]
        },
        "/ProcSet": [
            "/PDF",
            "/Text"
        ]
    }
}
```

... or - as this is doable on a pure Python level - **you** want to contribute this ;-) ?

**Comment by JorjMcKie** [comment]
Coming back to your question:
The newest v1.14.14 now offers a way to read the source code of an object in a pre-formatted way - very close to what you hoped to find as a Python dictionary. Example:

```python
>>> import fitz
>>> doc = fitz.open("rotated_annotation_test.pdf")
>>> page=doc[0]
>>> annot=page.firstAnnot
>>> # the old output:
>>> print(doc._getXrefString(annot.xref))
<</Subj(Rectangle)/Type/Annot/P 5 0 R/F 4/C[1 0 0]/CreationDate(D:20190401133029+11'00')/T(benjamin.howie)/Subtype/Square/M(D:20190401133045+11'00')/AP<</N 8 0 R>>/RD[.5 .5 .5 .5]/Rect[142.0509 394.0163 427.0811 648.0077]/NM(XSVVLMFDHWQHJSBG)/Rotation 30>>
>>> # the new available format:
>>> print(doc._getXrefString(annot.xref, compressed=False))
<<
  /Subj (Rectangle)
  /Type /Annot
  /P 5 0 R
  /F 4
  /C [ 1 0 0 ]
  /CreationDate (D:20190401133029+11'00')
  /T (benjamin.howie)
  /Subtype /Square
  /M (D:20190401133045+11'00')
  /AP <<
    /N 8 0 R
  >>
  /RD [ .5 .5 .5 .5 ]
  /Rect [ 142.0509 394.0163 427.0811 648.0077 ]
  /NM (XSVVLMFDHWQHJSBG)
  /Rotation 30
>>
>>> # and similar for the /AP object "8 0 R":
>>> print(doc._getXrefString(8, compressed=False))
<<
  /Type /XObject
  /Subtype /Form
  /FormType 1
  /BBox [ 164.7183 443.5641 404.4137 598.4598 ]
  /Resources <<
    /ProcSet [ /PDF ]
  >>
  /Matrix [ .8660253 -.5000002 .5000002 .8660253 -364.4324 -181.9309 ]
  /Length 54
>>
>>> 
```

As you can see, **every item** starts on a new line with an indentation indicating its level. And the item values are also in an easily parseable format. A /Rect or /BBox for example, can be extracted and turned into fitz.Rect objects in 1 or 2 Python lines with this - using no loops, just split(), replace() and join() functions.

The new version is not yet on PyPI. But Windows wheel can be found in the ``/releases`` folder of this repo, and OSX and Linux wheel are in the ``pymupdf/PyMuPDF-Wheels`` repo in there respective branches.
