### ISSUE TITLE
Some MuPDF errors are wrapped as RuntimeError and not fitz.FileDataError

### ISSUE THREAD

**Issue by dmoklaf** [pymupdf/PyMuPDF#2674]
## Describe the bug (mandatory)
Some PDFs during a crawl triggered MuPDF errors raised in Python as RuntimeError with this message:
"cannot find page xxx in page tree" which originates from MuPDF's C source code

## To Reproduce (mandatory)
Any faulty PDF file will do (e.g., a truncated/corrupted file).

## Expected behavior (optional)
The MuPDF error should be wrapped in Python into a fitz.FileDataError like other errors.

This will allow easy catching in try...except blocks by the user of your API.

## Your configuration (mandatory)
```
MacBook Pro 16'', 2023
MacOS 13.5.2
Mamba 1.5.1
Conda 23.7.4
Python 3.11.5
PyMuPDF 1.23.3 installed through mamba
```

Output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` :
```
3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:33:12) [Clang 15.0.7 ] 
 darwin 
 
PyMuPDF 1.23.3: Python bindings for the MuPDF 1.23.2 library.
Version date: 2023-08-31 00:00:01.
Built for Python 3.11 on darwin (64-bit).
```

**Comment by JorjMcKie** [comment]
This has to be classified as an enhancement request - it is not a bug.

At the same time I am afraid we have to turn down the request:
While an error detected by the base library can be intercepted and converted to a Python exception, there is no reason or error code associated with it. Depending on the concrete situation, multiple things may have gone wrong when MuPDF catches a problem.

So apart from the message text itself, there exist no data to map the reason to one of the zillions of Python exceptions - and we certainly will never try to interpret the message strings for that type of translation.

The only alternative would be to **always** raise `FileDataError` wherever we today have `RuntimeError`...

**Comment by dmoklaf** [comment]
An enhancement makes sense, sorry for the confusion, I thought incorrectly the RuntimeError behavior was not in the documentation.

Indeed  the C library could raise errors which may be mapped to other Python error types, e.g., FileNotFoundError.

Simplifying all errors by mapping them to FileDataError is thus not perfect.

But it is at least simple to understand by the API user.

Otherwise with RuntimeError, the situation is only worse, because there are 2 different error types which may be raised (FileDataError and RuntimeError) without a clear logic as to which is triggered when. Both can be triggered by file corruptions for example, depending on where the corruption occurs.

Thus this proposal is not for a perfect solution, but at least one that is simple for the API user.

If not implemented it is fine, because the workaround is simple for the API user.

**Comment by JorjMcKie** [comment]
Thanks for your feedback and your understanding!

FileDataError can only happen at file open (Document creation) time. This is a point when PyMuPDF has full control over the situation.
Any later exception is either again under PyMuPDF control (then situation-specific exceptions are raised like ValueError for incorrect parameters), or it comes from MuPDF, in which case a lot of different things may have occurred.
