### ISSUE TITLE
Windows 10 ImportError: DLL load failed while importing _fitz: 找不到指定的模块。

### ISSUE THREAD

**Issue by yuchangfu** [pymupdf/PyMuPDF#2678]
system:Windows 10 64
python:Python 3.10.11 amd64
pypdf:1.23.3

after use pip install PyMuPdf,get error

Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yuc\AppData\Local\Programs\Python\Python310\lib\site-packages\fitz\__init__.py", line 22, in <module>
    from fitz.fitz import *
  File "C:\Users\yuc\AppData\Local\Programs\Python\Python310\lib\site-packages\fitz\fitz.py", line 14, in <module>
    from . import _fitz
ImportError: DLL load failed while importing _fitz: 找不到指定的模块。

**Comment by julian-smith-artifex-com** [comment]
Thanks for reporting this.

[According to Google, ` 找不到指定的模块。` translates to `Can't find the specified module.`]

I've just checked and things work fine for me on Windows, so i'm not sure what's going wrong for you here.

1. Are you in a Python venv when installing/using fitz?
2. Could you post the exact command you used to install PyMuPDF? It would also be useful if you posted the complete output from this command when installing into a new venv.
3. Please post the output of: `pip show pymupdf`.
4. Please post the output of: `pip show pymupdfb`.

**Comment by yuchangfu** [comment]
1. I am not't use venv
2. use command 'pip install pymupdf --no-cache-dir',and install success.
`
C:\Users\yuc>pip install pymupdf --no-cache-dir
Defaulting to user installation because normal site-packages is not writeable
Collecting pymupdf
  Obtaining dependency information for pymupdf from https://files.pythonhosted.org/packages/de/ff/0c16387c329023ab76d860329202a6c1b9c59291adfa4869f0fe16659646/PyMuPDF-1.23.3-cp310-none-win_amd64.whl.metadata
  Downloading PyMuPDF-1.23.3-cp310-none-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: PyMuPDFb==1.23.3 in c:\users\yuc\appdata\roaming\python\python310\site-packages (from pymupdf) (1.23.3)
Downloading PyMuPDF-1.23.3-cp310-none-win_amd64.whl (3.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 23.4 kB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.23.3
`
After install I test it,get this
`
C:\Users\yuc>python
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yuc\AppData\Roaming\Python\Python310\site-packages\fitz\__init__.py", line 22, in <module>
    from fitz.fitz import *
  File "C:\Users\yuc\AppData\Roaming\Python\Python310\site-packages\fitz\fitz.py", line 14, in <module>
    from . import _fitz
ImportError: DLL load failed while importing _fitz: 找不到指定的模块。
>>>
`

3.pip show pymupdf
`
C:\Users\yuc>pip show pymupdf
Name: PyMuPDF
Version: 1.23.3
Summary: A high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.
Home-page:
Author: Artifex
Author-email: support@artifex.com
License: GNU AFFERO GPL 3.0
Location: c:\users\yuc\appdata\roaming\python\python310\site-packages
Requires: PyMuPDFb
Required-by:

`
4.pip show pymupdfb
`C:\Users\yuc>pip show pymupdfb
Name: PyMuPDFb
Version: 1.23.3
Summary: MuPDF shared libraries for PyMuPDF.
Home-page:
Author: Artifex
Author-email: support@artifex.com
License: GNU AFFERO GPL 3.0
Location: c:\users\yuc\appdata\roaming\python\python310\site-packages
Requires:
Required-by: PyMuPDF
`

Thank you

**Comment by julian-smith-artifex-com** [comment]
Thanks for the comprehensive answers to my questions.

1. You say "I changed Python version to 3.10.7" - could you explain exactly how you did this? (I have only ever used venv's, so this might be quite important.)
2. Please post the output of: `dir c:\users\yuc\appdata\roaming\python\python310\site-packages\fitz`
3. Please post the output of: `dir c:\users\yuc\appdata\roaming\python\python310\site-packages\fitz_new`

Finally i wonder whether you could try installing into a venv, by running these commands:
```
py -m venv pylocal
pylocal\Scripts\activate
python -m pip install --upgrade pip
pip install pymupdf
```
[Hopefully we'll be able to get your non-venv approach to work, but knowing whether a venv works will be useful information.]

**Comment by yuchangfu** [comment]
Problem solved.
The resion is my system missing MSVCP140.dll.If you have problem like this.the following is for reference:
1.use dll-diagnostics to check DLL dependencies

- pip install dll-diagnostics
- dlldiag deps mupdfcpp64.dll
Get the following tips：

> C:\Users\yuc\AppData\Roaming\Python\Python310\site-packages\fitz>dlldiag deps mupdfcpp64.dll
> DLL Diagnostic Tools version 0.0.18
> Copyright (c) 2019-2021 Adam Rehn
> 
> Parsing module header and identifying direct dependencies... done.
> 
> Parsed module details:
> Module:          C:\Users\yuc\AppData\Roaming\Python\Python310\site-packages\fitz\mupdfcpp64.dll
> Type:            Dynamic-Link Library
> Architecture:    x64
> 
> Attempting to load the module's direct dependencies:
> 
> api-ms-win-crt-convert-l1-1-0.dll        Loaded successfully
> api-ms-win-crt-environment-l1-1-0.dll    Loaded successfully
> api-ms-win-crt-filesystem-l1-1-0.dll     Loaded successfully
> api-ms-win-crt-heap-l1-1-0.dll           Loaded successfully
> api-ms-win-crt-math-l1-1-0.dll           Loaded successfully
> api-ms-win-crt-runtime-l1-1-0.dll        Loaded successfully
> api-ms-win-crt-stdio-l1-1-0.dll          Loaded successfully
> api-ms-win-crt-string-l1-1-0.dll         Loaded successfully
> api-ms-win-crt-time-l1-1-0.dll           Loaded successfully
> api-ms-win-crt-utility-l1-1-0.dll        Loaded successfully
> KERNEL32.dll                             Loaded successfully
> **MSVCP140.dll                             Error 126: 找不到指定的模块。**
> VCRUNTIME140.dll                         Loaded successfully
> VCRUNTIME140_1.dll                       Loaded successfully

- search  MSVCP140.dll in msdn.com,install it（https://www.microsoft.com/zh-cn/download/details.aspx?id=53840）


Why test dependencies of mupdfcpp64.dll ,because it's the only one DLL file in fitz

> C:\Users\yuc>cd "C:\Users\yuc\AppData\Roaming\Python\Python310\site-packages\fitz
> 
> C:\Users\yuc\AppData\Roaming\Python\Python310\site-packages\fitz>dir
>  驱动器 C 中的卷没有标签。
>  卷的序列号是 0E51-A8A2
> 
>  C:\Users\yuc\AppData\Roaming\Python\Python310\site-packages\fitz 的目录
> 
> 2023/09/21  09:20    <DIR>          .
> 2023/09/22  09:10    <DIR>          ..
> 2023/09/21  08:23           377,637 fitz.py
> **2023/09/21  08:11        23,288,832 mupdfcpp64.dll**
> 2023/09/21  08:23            75,219 table.py
> 2023/09/21  08:23           187,581 utils.py
> 2023/09/21  08:23           716,288 _fitz.cp310-win_amd64.pyd
> 2023/09/21  08:23            22,932 __init__.py
> 2023/09/21  08:23            40,875 __main__.py
> 2023/09/21  08:23    <DIR>          __pycache__

**Comment by julian-smith-artifex-com** [comment]
Great, i'm glad you were able to fix the problem.

And many thanks for the detailed explanation, it's really appreciated. I haven't come across dll-diagnostics before, it looks very useful.

**Comment by sam-armstrong0** [comment]
I can confirm I had the exact same issue on a windows 10 VM that was previously working. I didn't experience this problem on another laptop.

Replaced the missing MSVCP140.dll in C:\Windows\System32 folder and everything now works again.
Thanks for the fix.

**Comment by julian-smith-artifex-com** [comment]
Good to know.

I've just added a note about this issue to `docs/installation.rst`. This will be visible in the official docs after the next release.

**Comment by lzmsomuch** [comment]
system: Windows 10 64
python: Python 3.10.11 amd64
pymupdf: 1.24.14

error occurred when import pymupdf:
```
import error: dll load failed while importing _extra: 找不到指定的模块。
```
I also resolved my problem following this:
https://github.com/pymupdf/PyMuPDF/issues/2678#issuecomment-1730662415

only one different:
- search MSVCP140.dll in msdn.com,install it（[https://www.microsoft.com/zh-cn/download/details.aspx?id=53840）](https://www.microsoft.com/zh-cn/download/details.aspx?id=53840%EF%BC%89)

the link is 404

I got [https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist] instead

**Comment by sdbbs** [comment]
I hate it so much when things that used to be working, stop working: I'll spend my whole damn life just fixing dependencies problems.

Anyways, I'm on MINGW64 / Windows 10, and I have pymupdf from pacman:

```
$ pacman -Ss pymupdf
clangarm64/mingw-w64-clang-aarch64-python-pymupdf 1.24.4-3
    Python bindings for MuPDF's rendering library (mingw-w64)
mingw64/mingw-w64-x86_64-python-pymupdf 1.24.4-3 [installed]
    Python bindings for MuPDF's rendering library (mingw-w64)
ucrt64/mingw-w64-ucrt-x86_64-python-pymupdf 1.24.4-3
    Python bindings for MuPDF's rendering library (mingw-w64)
clang64/mingw-w64-clang-x86_64-python-pymupdf 1.24.4-3
    Python bindings for MuPDF's rendering library (mingw-w64)
```

Unfortunately, I couldn't have installed dll-diagnostics because of some stupid `maturin` dependency, whatever it is:

```
$ python3 -m pip install dll-diagnostics
warning: externally-managed-environment
...
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      ðŸ’¥ maturin failed
        Caused by: Failed to find a python interpreter
        Caused by: Failed to get information from the python interpreter at C:/msys64/mingw64/bin/python3.exe
        Caused by: A python 3 interpreter on windows does not define abiflags in its sysconfig à² _à²
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', 'D:/msys64/tmp/pip-modern-metadata-
nozuvvuv', '--interpreter', 'C:/msys64/mingw64/bin/python3.exe']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory C:/msys64/tmp/pip-modern-metadata-nozuvvuv --interpreter D:/msys64/ming
w64/bin/python3.exe`
      [end of output]
...
```

It turns out I do not really have a .dll either, I have .pyd instead:

```
$ pacman -Ql mingw-w64-x86_64-python-pymupdf
mingw-w64-x86_64-python-pymupdf /mingw64/
mingw-w64-x86_64-python-pymupdf /mingw64/bin/
mingw-w64-x86_64-python-pymupdf /mingw64/bin/pymupdf.exe
mingw-w64-x86_64-python-pymupdf /mingw64/lib/
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__init__.py
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__main__.py
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/__init__.cpython-312.opt-1.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/__init__.cpython-312.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/__main__.cpython-312.opt-1.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/__main__.cpython-312.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/fitz_old.cpython-312.opt-1.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/fitz_old.cpython-312.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/table.cpython-312.opt-1.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/table.cpython-312.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/utils.cpython-312.opt-1.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/__pycache__/utils.cpython-312.pyc
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/_fitz_old.cp312-mingw_x86_64_msvcrt_gnu.pyd
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/fitz_old.py
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/table.py
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/fitz_old/utils.py
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/PyMuPDF-1.24.4.dist-info/
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/PyMuPDF-1.24.4.dist-info/COPYING
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/PyMuPDF-1.24.4.dist-info/entry_points.txt
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/PyMuPDF-1.24.4.dist-info/METADATA
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/PyMuPDF-1.24.4.dist-info/README.md
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/PyMuPDF-1.24.4.dist-info/RECORD
mingw-w64-x86_64-python-pymupdf /mingw64/lib/python3.12/site-packages/PyMuPDF-1.24.4.dist-info/WHEEL
mingw-w64-x86_64-python-pymupdf /mingw64/share/
mingw-w64-x86_64-python-pymupdf /mingw64/share/licenses/
mingw-w64-x86_64-python-pymupdf /mingw64/share/licenses/python-pymupdf/
mingw-w64-x86_64-python-pymupdf /mingw64/share/licenses/python-pymupdf/COPYING
```

So, ultimately, instead of using `dll-diagnostics` to inspect a .dll, I used https://github.com/lucasg/Dependencies to inspect the .pyd file, and I got:

> We could not find libgumbo-2.dll file on the disk anymore, please fix this problem and refresh the window via F5

What the hell is libgumbo-2 and why the hell is it a dependency now ... the crappy thing, however, I already have gumbo package in MINGW64:

```
$ pacman -Ss gumbo | grep installed
mingw64/mingw-w64-x86_64-gumbo-parser 0.13.0-1 [installed]
```

... however it has no libgumbo-2.dll - only libgumbo-3.dll:

```
$ pacman -Ql mingw-w64-x86_64-gumbo-parser | grep dll
mingw-w64-x86_64-gumbo-parser /mingw64/bin/libgumbo-3.dll
mingw-w64-x86_64-gumbo-parser /mingw64/lib/libgumbo.dll.a
```

... so I tried cheating with a symlink:

```
$ (cd /mingw64/bin/; ln -s libgumbo-3.dll libgumbo-2.dll)
```

... and apparently it worked:

```
$ python3 -c 'import fitz_old as fitz'
$
```

Goddamn it, I hate life and I hate computers and I hope soon an asteroid crashed on the Earth and destroys all people and computers and everything
