### ISSUE TITLE
Windows sdist build failure - non-quoting of path and using UNIX which command

### ISSUE THREAD

**Issue by jamesg-nz** [pymupdf/PyMuPDF#2683]
Doing source build for PyMuPDF 1.23.3 on Python 3.12rc3 as no wheel is available yet.

Python is installed at: `C:\Program Files\Python312`

The build failed in two places due to the space in that path.

Here inside _setup.py_ `{sys.executable}` needs double quotes around it in the format string:

https://github.com/pymupdf/PyMuPDF/blob/1c2f1da3eb2541f1c8dbd50acb3a916939c99d3e/setup.py#L840

Here inside _pipcl.py_ the Python include path parameter to MSVC needs double quotes around the whole thing:

https://github.com/pymupdf/PyMuPDF/blob/1c2f1da3eb2541f1c8dbd50acb3a916939c99d3e/pipcl.py#L1758

Then in the _MuPDF_ source that was inside the sdist (_mupdf-1.23.2-source_) I downloaded from PyPI it tries to use `which` on Windows inside _swig.py_ - it'd be unusual for Windows users to have this installed:

https://github.com/ArtifexSoftware/mupdf/blob/4ae522a299df7e18f155ae319c7756298d69c490/scripts/wrap/swig.py#L77C1-L77C1

So I commented that line out (just seems to be for build logs to show where swig is installed I guess).

**After making those three changes I got a successful build of a wheel that I then installed.**

**Comment by julian-smith-artifex-com** [comment]
Many thanks for this.

 I've applied your suggested fixes to my tree, so things will be fixed in the next release.

(The error from the use of `which` is already fixed in 1.23.3.)

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.4.
