### ISSUE TITLE
PyMuPDF 1.23.3: Cannot make CHECKBOX read-only by adding flags PDF_FIELD_IS_READ_ONLY

### ISSUE THREAD

**Issue by hsvlz** [pymupdf/PyMuPDF#2695]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

I cannot make a checkbox read-only by adding flags widget.field_flags |= fitz.PDF_FIELD_IS_READ_ONLY.

This issue has already been mentioned in [this ticket](https://github.com/pymupdf/PyMuPDF/issues/2278). Despite using newer version 1.23.3, I still cannot make checkboxes readonly in my document. Maybe something specific to this document?

## To Reproduce (mandatory)
```
doc = fitz.open(name)
for page in doc:
    widgets = page.widgets()
    for widget in widgets :
        widget.field_flags |= fitz.PDF_FIELD_IS_READ_ONLY
        widget.update()
```

## Expected behavior (optional)
I want to make the checkbox read-only by adding flags fitz.PDF_FIELD_IS_READ_ONLY

## Screenshots (optional)
file: [sample.pdf](https://drive.google.com/file/d/1Xav33FZlq6_7JiLOZJtrrL5uxMBEi7hC/view?usp=drive_link)

## Your configuration (mandatory)
 - Python version, bitness 3.11.2
  - PyMuPDF version, installation method 1.23.3

**Comment by JorjMcKie** [comment]
Cannot reproduce - it does work for me:
```python
import fitz

doc = fitz.open("sample_pdf.pdf")
page = doc[0]

for widget in page.widgets():
    widget.field_flags |= fitz.PDF_FIELD_IS_READ_ONLY
    widget.update()

doc.save("output.pdf")
```
The output's fields cannot be changed.
My list utility also shows ReadOnly, for example:
```
thisown = True
border_color = [0.06269840896129608, 0.37649503350257874, 0.3724980056285858]
border_style = 'Solid'
border_width = 1.0
border_dashes = None
choice_values = None
rb_parent = None
field_name = 'Check Box 10'
field_label = ''
field_value = 'Off'
field_flags = 1 (ReadOnly)
field_display = 0
field_type = 2
field_type_string = 'CheckBox'
fill_color = []
button_caption = None
is_signed = None
text_color = [0.0, 0.0, 0.0]
text_font = 'Helv'
text_fontsize = 0.0
text_maxlen = 0
text_format = 0
script = None
script_stroke = None
script_format = None
script_change = None
script_calc = None
script_blur = None
script_focus = None
rect = Rect(430.1570129394531, 251.35406494140625, 441.4960021972656, 262.6929931640625)
xref = 42
parent = <class 'weakref.ProxyType'>
```

**Comment by hsvlz** [comment]
this is the output file I get: [output.pdf](https://drive.google.com/file/d/1DkqTpOV4jHYdtMrWZlQpHyaajgL738_e/view?usp=sharing)

when I use this output file in my code again as the input, all non checkbox fields have the proper `widget.field_flags=1` while checkboxes still have `widget.field_flags=0`.

I have tried this locally (a mac) and when running from a server environment, and I am afraid the result is the same. I can see that all other fields are properly readonly - except these checkboxes.

**Comment by JorjMcKie** [comment]
Something is very wrong. Here is the relevant PDF source of your output file, showing all checkbox definitions:
![grafik](https://github.com/pymupdf/PyMuPDF/assets/8290722/448941df-ed3b-4236-8c24-19a6ceaf708b)

All button fields have `/Ff 1` (field flag 1 = ReadOnly). The top item is marked - whoever / whatever may have done that.
Otherwise everything is just fine and none of my PDF viewer allows changing anything - including the checkboxes.

I tried my script above under Windows and Linux (have no Mac) and it works both ways.

**Comment by hsvlz** [comment]
Ha, I think I have found the issue: [read-only-checkbox-is-clickable-on-mac-computer](https://community.adobe.com/t5/acrobat-sdk-discussions/read-only-checkbox-is-clickable-on-mac-computer/m-p/8014612)

I can confirm the fields are readonly when using 3rd party viewer. And my bad, I misread `widget.field_flags` values of output file.

Thanks for your help. Closing the issue as not a fitz bug.
