### ISSUE TITLE
[FEATURE REQUEST] find_tables limit itertation

### ISSUE THREAD

**Issue by danny007in** [pymupdf/PyMuPDF#2704]
Loop limit in find_tables method for performance

Before
```py
tabs = page.find_tables(clip=clip) # iterates till end, but only need tabs[0]
  if tabs.tables:
  tab = tabs[0] 
```

After
```py
tabs = page.find_tables(clip=clip, maxCheck=1) # iterates till maxCheck ,
  if tabs.tables:
  tab = tabs[0]
```

**Comment by JorjMcKie** [comment]
This won't work. The main problem of all table processing is **_finding_** content that **_may_** be table(s). For this, **_everything_** inside the current `clip` must be investigated. This is where all the significant effort goes into. The result of that analysis is an overall list of all cells within the clip - for whatever individual table.
Subsequent identification / separation of individual tables and providing them as Python objects is a peanuts effort in comparison.

**Comment by JorjMcKie** [comment]
Thanks for understanding!
