### ISSUE TITLE
Form Field not being parsed

### ISSUE THREAD

**Issue by harsha-usethread** [pymupdf/PyMuPDF#2715]
I am noticing that I am unable to get the Form field text. I am redacting the exact numbers for privacy reasons, and instead using random numbers. Here is what the PDF looks like:

<img width="435" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/122410316/9f90fec4-5949-4f99-b122-350127a8be59">

Here is what the output ends up looking like:
<img width="435" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/122410316/472ccb3a-6f52-41a0-95fd-f480b26a4924">

I am using Langchain, so the problem could be with that library, but here is the code that Langchain uses to ingest the PDF file:
```
def lazy_parse(self, blob: Blob) -> Iterator[Document]:
        """Lazily parse the blob."""
        import fitz

        with blob.as_bytes_io() as file_path:
            doc = fitz.open(file_path)  # open document

            yield from [
                Document(
                    page_content=page.get_text(**self.text_kwargs),
                    metadata=dict(
                        {
                            "source": blob.source,
                            "file_path": blob.source,
                            "page": page.number,
                            "total_pages": len(doc),
                        },
                        **{
                            k: doc.metadata[k]
                            for k in doc.metadata
                            if type(doc.metadata[k]) in [str, int]
                        },
                    ),
                )
                for page in doc
            ]
```

Happy to add any additional points if that makes it easier to understand.

**Comment by JorjMcKie** [comment]
I am going to close this for now.
Please re-open or submit another issue once you can provide a reproducing file.
