### ISSUE TITLE
Segmentation Fault Convert to PDF

### ISSUE THREAD

**Issue by johnbowethejoker** [pymupdf/PyMuPDF#272]
Hi, let me preface this saying I'm an extremely inexperienced noob so I'm unfamiliar with a lot of concepts and general etiquette on here especially  

I have a script that runs fine on a windows machine. The script captures an image using opencv, then converts it to a PDF and then appends it to the end of an existing PDF. However now I'm trying to run it off a RPi, and I'm getting the following error:

Backend terminated (returncode: -11)
Fatal Python Error: Segmentation Fault

Current thread 0x76f9e640 (most recent call first):
File"/usr/local/lib/python3.5/dist-packages/fitz/fitz.py", line 1955 in convertToPDF

My first question is what is a segmentation fault, and my 2nd being why particularly would a script handle all the libraries fine on one type of system and not another as long as the libraries are the same? That isn't to say I don't believe such a thing is possible, more that I don't understand the mechanisms at play.

**Comment by JorjMcKie** [comment]
As per the general part of the question, see here: [Wikipedia](https://en.wikipedia.org/wiki/Segmentation_fault).
To the specific part:
PyMuPDF is a binding (= Python API) to the excellent libary MuPDF, which is written in C. On every platform, where PyMuPDF shall be used, the MuPDF binary components must be generated first, before the PyMuPDF can be successfully generated.

This total process is executed and "bottled" into Python wheels for platforms Windows, Linux and Mac OSX. They all should (in theory) run equally well.

For other platforms (what is RPi?? Rasperry Pi?) the installing person is responsible for doing the same installation steps in the same sequence as has been done generating those wheels. Rasperry Pi is not blessed with a wheel, so I guess this process must be done there (or for it). All the required steps are explained in the installation chapter of the documentation. They roughly are:
* download MuPDF
* copy over C source modifications by PyMuPDF into the MuPDF source. One of these mods pertains to preventing a MuPDF error, popping up in convertToPDF, BTW
* generate MuPDF in / for the target platform
* generate PyMuPDF

**Comment by JorjMcKie** [comment]
Hm, forgot to ask the the obvious:
What has been done to generate MuPDF & PyMuPDF for Raspberry Pi?
What are version numbers and bitnesses of all the contributing pieces (OS, Python, PyMuDF)?

**Comment by johnbowethejoker** [comment]
I used the mupdf tar file to generate MuPDF and used pip for PyMuPDF

OS is Raspbian version 9

Python is 3.5.3

PyMuPDF is 1.14.12

I re-installed MuPDF from source and it seems to still have the issue.

Think I should delete everything and start from the beginning?

**Comment by johnbowethejoker** [comment]
Worth noting I'm also forcing myself to learn linux with this little misadventure so I'm out of my depth in that department as well.

For what it's worth, pymupdf works fabulously on my other (Windows) system

**Comment by JorjMcKie** [comment]
Did you closely follow the MuPDF installation steps, as explained in the docu? Specifically these:

> The repo's fitz folder contains a few files whose names start with an underscore "_". These files contain configuration data and hotfixes. Each one must be copy-renamed to its correct target location of the MuPDF source that you have downloaded, before you generate MuPDF. Currently, these files are:
> 
>    * fitz configuration file _mupdf_config.h copy-replace to: mupdf/include/fitz/config.h. It contains configuration data like e.g. which fonts to support.
>    * fitz error module _error.c, copy-replace to: mupdf/source/fitz/error.c. It redirects MuPDF warnings and errors so they can be intercepted by PyMuPDF.
>    * PDF device module _pdf-device.c copy-replace to: mupdf/source/pdf/pdf-device.c. It fixes a bug which caused method Document.convertToPDF() to bring down the interpeter.
>    * Now **MuPDF** can be generated.

Only after all this has happened, PyMuPDF generation must take place.

**Comment by johnbowethejoker** [comment]
Yes, those steps which i admittedly skipped before iirc, I did this time. I'm gonna clear out and then re generate mupdf properly just to be sure.

Is it alright to use pip for pymupdf if i'm generating mupdf manually?

**Comment by JorjMcKie** [comment]
Yes that should work ... however this also depends on the platform, from which you are issuing the pip command though:
If it is a wheel-supported one, then the matching wheel will automatically be downloaded and installed - which is not what you want in your case.

Just download the source from the PyPI site and use its setup.py (after due modification with your installed MuPDF's libary locations ...)

**Comment by johnbowethejoker** [comment]
Unfortunately it's doing much the same. Could it be a permission error? Any idea how to run a python script as super user?

**Comment by johnbowethejoker** [comment]
Scratch that, I just tried to run it in a su shell and got the same thing. I'll hammer away at it and see if i get anywhere regardless.

**Comment by JorjMcKie** [comment]
I do not believe it is a permission problem.
But in Windows, you just have to start a batch windows as admin, and in Linux you probably have to prefix the command with sudo.

It sounds like a memory issue. E.g. a mixture of bitnessess (both, x32 and x64 components mixed up) somewhere: MuPDF, Python, and the runtime platform must all be in synch.

If you can run the script in your normal Linux, then the problem must be Raspberry. I would assume, that this platform RPi is x32!

**Comment by JorjMcKie** [comment]
I just made sure, my Linux is running fine with convertToPDF from a bif JPEG picture - all fine.

**Comment by johnbowethejoker** [comment]
Ah. So how do I go about syncing everything up?

**Comment by JorjMcKie** [comment]
Assuming RPi has a 32bit architecture (which I don't know), then all parts which contribute any binary must be compiled for 32bits:

* Generate MuPDF (with all the above mentioned mods) for 32bit
* Take a 32bit Python and generate PyMuPDF under it (using the setup.py)
* transfer the resulting PyMuPDF stuff to your RPi Python (however that works). This should be a folder named ``fitz``, containing the usual `__init__.py`, then `fitz.py`, `_fitz.<...>.so`, `utils.py`. And also your application script of course.

**Comment by johnbowethejoker** [comment]
Did some research, the RPi 3 B which is the one i'm using supports 64 bit however Raspbian (The OS) only supports 32 bit because they want to support legacy platforms.

I will attempt your recommendations, and I imagine that'll clear it up. If it helps, Raspbian is just Debian retooled. I however have no experience on linux systems to begin with so I would hardly call myself an expert. But, that's never stopped me before.

**Comment by johnbowethejoker** [comment]
Unfortunately I could not get them to work properly, so I replaced pymupdf with img2pdf which uses pillow. I can only assume it's some quirk of raspian causing the issue.

**Comment by JorjMcKie** [comment]
Sorry that it didn't work.
Going to close this issue then.
