### ISSUE TITLE
When will a Python 3.12 wheel be available?

### ISSUE THREAD

**Issue by 17Reset** [pymupdf/PyMuPDF#2723]
Hi, Python 312 has been released and the following problem occurs when installing this library using Python 312:
Collecting pymupdf
  Downloading PyMuPDF-1.23.4.tar.gz (60.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.5/60.5 MB 13.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: ### Starting.
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: __name__: 'setup'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: platform.platform(): 'Windows-11-10.0.22621-SP0'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: platform.python_version(): '3.12.0'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: sys.executable: 'D:\\App\\Python\\python.exe'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: CPU bits: 64 sys.maxsize=9223372036854775807
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: __file__: 'D:\\Tmp\\pip-install-dr453vlh\\pymupdf_01181739ab1e49e28731b8eda2fe68ac\\setup.py'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: os.getcwd(): 'D:\\Tmp\\pip-install-dr453vlh\\pymupdf_01181739ab1e49e28731b8eda2fe68ac'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: sys.argv (3):
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     0: 'D:\\App\\Python\\Lib\\site-packages\\pip\\_vendor\\pyproject_hooks\\_in_process\\_in_process.py'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     1: 'prepare_metadata_for_build_wheel'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     2: 'D:\\Tmp\\tmp6b_3ef_i'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: os.environ (47):
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     ALLUSERSPROFILE: 'C:\\ProgramData'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     APPDATA: 'C:\\Users\\xLAB\\AppData\\Roaming'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     CLION: 'D:\\App\\JetBrains\\CLion\\bin;'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     COMMONPROGRAMFILES(X86): 'C:\\Program Files (x86)\\Common Files'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     COMMONPROGRAMW6432: 'C:\\Program Files\\Common Files'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     COMPUTERNAME: 'XLAB'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     COMSPEC: 'C:\\Windows\\system32\\cmd.exe'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     DRIVERDATA: 'C:\\Windows\\System32\\Drivers\\DriverData'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     HOMEDRIVE: 'C:'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     HOMEPATH: '\\Users\\xLAB'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     LOCALAPPDATA: 'C:\\Users\\xLAB\\AppData\\Local'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     LOGONSERVER: '\\\\XLAB'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     NUMBER_OF_PROCESSORS: '4'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     OS: 'Windows_NT'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PATH: 'D:\\Tmp\\pip-build-env-i328il0q\\overlay\\Scripts;D:\\Tmp\\pip-build-env-i328il0q\\normal\\Scripts;D:\\App\\Python\\Scripts\\;D:\\App\\Python\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;D:\\App\\Git\\cmd;C:\\Users\\xLAB\\AppData\\Local\\Microsoft\\WindowsApps;D:\\App\\PyCharm\\bin;D:\\App\\JetBrains\\CLion\\bin;D:\\App\\JetBrains\\CLion\\bin\\mingw\\bin;C:\\Users\\xLAB\\AppData\\Local\\JetBrains\\Toolbox\\scripts;D:\\App\\JetBrains;D:\\App\\msys64\\ucrt64\\bin'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PEP517_BACKEND_PATH: 'D:\\Tmp\\pip-install-dr453vlh\\pymupdf_01181739ab1e49e28731b8eda2fe68ac'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PEP517_BUILD_BACKEND: 'setup'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PIP_BUILD_TRACKER: 'D:\\Tmp\\pip-build-tracker-0v5oiusd'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PROCESSOR_ARCHITECTURE: 'AMD64'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 167 Stepping 1, GenuineIntel'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PROCESSOR_LEVEL: '6'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PROCESSOR_REVISION: 'a701'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PROGRAMDATA: 'C:\\ProgramData'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PROGRAMFILES: 'C:\\Program Files'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PROGRAMFILES(X86): 'C:\\Program Files (x86)'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PROGRAMW6432: 'C:\\Program Files'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PROMPT: '$P$G'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PSMODULEPATH: '%ProgramFiles%\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PUBLIC: 'C:\\Users\\Public'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PYCHARM: 'D:\\App\\PyCharm\\bin;'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PYTHONNOUSERSITE: '1'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     PYTHONPATH: 'D:\\Tmp\\pip-build-env-i328il0q\\site'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     SYSTEMDRIVE: 'C:'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     SYSTEMROOT: 'C:\\Windows'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     TEMP: 'D:\\Tmp'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     TMP: 'D:\\Tmp'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     USERDOMAIN: 'XLAB'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     USERDOMAIN_ROAMINGPROFILE: 'XLAB'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     USERNAME: 'xLAB'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     USERPROFILE: 'C:\\Users\\xLAB'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     WINDIR: 'C:\\Windows'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     WSLENV: 'WT_SESSION::WT_PROFILE_ID'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     WT_PROFILE_ID: '{0caa0dad-35be-5f56-a8ff-afceeeaa6101}'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     WT_SESSION: 'e72cb6b4-1b5a-465c-b8c2-07ca6c004463'
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py:     __COMPAT_LAYER: 'DetectorsAppHealth'
      pipcl.py: build_wheel():  wheel_directory='D:\\Tmp\\pip-modern-metadata-a4rqww8s' config_settings=None metadata_directory=None
      pipcl.py: _call_fn_build(): calling self.fn_build=<function build at 0x000001685204BA60>
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: skeleton=None
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: PYMUPDF_SETUP_MUPDF_BUILD=None
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: mupdf_tgz already exists: D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac\mupdf.tgz
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: Extracting D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac\mupdf.tgz
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: Copying D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac/fitz/_config.h to D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac\mupdf-1.23.2-source/include/mupdf/fitz/config.h.
      pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py: D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac\mupdf-1.23.2-source/include/mupdf/fitz/config.h: os.stat_result(st_mode=33206, st_ino=1688849860319456, st_dev=13445203884946845423, st_nlink=1, st_uid=0, st_gid=0, st_size=5686, st_atime=1696650054, st_mtime=1695760732, st_ctime=1696650050) mtime=2023-09-26-20:38:52
      Traceback (most recent call last):
        File "D:\App\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\App\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\App\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac\pipcl.py", line 582, in build_wheel
          items = self._call_fn_build(config_settings)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac\pipcl.py", line 731, in _call_fn_build
          ret = self.fn_build()
                ^^^^^^^^^^^^^^^
        File "D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py", line 672, in build
          mupdf_build_dir = build_mupdf_windows( mupdf_local, env_extra, build_type)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac\setup.py", line 802, in build_mupdf_windows
          vs = pipcl.wdev.WindowsVS()
               ^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Tmp\pip-install-dr453vlh\pymupdf_01181739ab1e49e28731b8eda2fe68ac\wdev.py", line 74, in __init__
          assert directories, f'No match found for: {pattern}'
      AssertionError: No match found for: C:\Program Files*\Microsoft Visual Studio\2*\*
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by JorjMcKie** [comment]
You mean **_when_** we will publish a wheel for Python 3.12?
This will happen during the week to come: we will also roll out a new version.

**Comment by JorjMcKie** [comment]
You have no Visual Studio installed. Because there is no wheel yet for Python 3.12, the pip of your Python tries an an installation from sources, which hence fails.

**Comment by MrDwarf7** [comment]
Are there any work-arounds for this in the current state? Also facing a similar issue until a wheel is released

**Comment by JorjMcKie** [comment]
If you cannot wait, I suggest you install Visual Studio Community 2019 and then simply repeat PyMuPDF installation.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.5.

**Comment by MinuteMaid20** [comment]
I post it for the first time.
PyMuPDF , on mac OS 12 /Python3.12　it's running very well.
So  I'll port it on Windows11(MinGW64),but very struggling.(due to _missing MSVC_  ,it's MinGW64/MSYS2  not Windows native!)
I took look into setup.py and found some snippet for installing to MSYS2  and UNIX.

Could I fixed it  and do well? Or is there missing anything?

568:   msys2 = platform.system().startswith('MSYS_NT-')

605,620 :    if windows:
        mupdf_build_dir = build_mupdf_windows(
                mupdf_local,
                build_type,
                overwrite_config,
                g_py_limited_api,
                PYMUPDF_SETUP_MUPDF_REFCHECK_IF,
                PYMUPDF_SETUP_MUPDF_TRACE_IF,
                )
    else:
        if 'p' not in PYMUPDF_SETUP_FLAVOUR and 'b' not in PYMUPDF_SETUP_FLAVOUR:
            # We only need MuPDF headers, so no point building MuPDF.
            log(f'Not building MuPDF because not Windows and {PYMUPDF_SETUP_FLAVOUR=}.')
            mupdf_build_dir = None
        else:
                mupdf_build_dir = build_mupdf_unix(
