### ISSUE TITLE
Support for .cbr files

### ISSUE THREAD

**Issue by Cyberjuice** [pymupdf/PyMuPDF#2726]
Would it be possible to add support for ".cbr" files?
As far as I know, the only difference to ".cbz" files that are already supported is that instead of the "zip" format being used for compression, it is "rar".

**Comment by JorjMcKie** [comment]
I have submitted your enhancement request to MuPDF's issue system [here](https://bugs.ghostscript.com/show_bug.cgi?id=707249) for your reference.

**Comment by JorjMcKie** [comment]
I learned from the MuPDF colleagues that this had already been considered once some time ago.
But because of the unclear and unpleasant license situation around the RAR compression algorithm the idea has been dropped again.

**Comment by Cyberjuice** [comment]
Thank you for that.
I learned something.
