### ISSUE TITLE
how to read a file stream instead of file location

### ISSUE THREAD

**Issue by manish59** [pymupdf/PyMuPDF#276]
Im trying to read the filestream instead of file location in fitz how can i do that

**Comment by JorjMcKie** [comment]
What do you mean: open a document given as a memory area?

```python
doc = fitz.open("xxx", bytesobject)
```
where "xxx" is one of the supported document type extensions ("pdf", "xps", "epub", any of the images like "png", "jpg", "svg", ...)

**Comment by JorjMcKie** [comment]
answered your question?
