### ISSUE TITLE
Unexpected table cell contents when opening multiple PDFs

### ISSUE THREAD

**Issue by ArrichM** [pymupdf/PyMuPDF#2760]
_**Please provide all mandatory information!**_

First of all, thank you very much for implementing the find_tables feature, it works great and is incredibly useful for a lot of us I think!

## Describe the bug (mandatory)
When opening more than one PDF document at a time, the contents returned by <Table>.extract() is unexpected.

## To Reproduce (mandatory)

```
import fitz

doc = fitz.open("national-capitals.pdf")

tables = []
for page in doc:  # iterate over the pages
    tabs = page.find_tables()  # locate tables on page
    if len(tabs.tables) == []:  # no tables found?
        break  # stop
    tab = tabs[0]  # assume fragment to be 1st table
    tables.append(tab)  # append this DataFrame

# Everything as expected until here

doc_2 = fitz.open("input1.pdf")
tables_2 = []
for page in doc_2:  # iterate over the pages
    tabs = page.find_tables()  # locate tables on page
    if len(tabs.tables) == []:  # no tables found?
        break  # stop
    tab = tabs[0]  # assume fragment to be 1st table
    tables_2.append(tab)  # append this DataFrame

# This returns text from the input1.pdf, not national-capitals.pdf as intended
df = pd.concat([tab.to_pandas() for tab in tables])
```

## Expected behavior (optional)
I expect the df from the code above to contain the contents of the tables held by the national-capitals.pdf document.

## Your configuration (mandatory)
3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23) 
[Clang 13.0.0 (clang-1300.0.29.30)] 
 darwin 
 
PyMuPDF 1.23.5: Python bindings for the MuPDF 1.23.4 library.
Version date: 2023-10-11 00:00:01.
Built for Python 3.9 on darwin (64-bit).

## Additional context (optional)
I think this is due to the namespace management in the table functions.

**Comment by JorjMcKie** [comment]
You can correct your code like this:
```python
tables = []
for page in doc:  # iterate over the pages
    if page.number > 2:
        break
    tabs = page.find_tables()  # locate tables on page
    if len(tabs.tables) == []:  # no tables found?
        break  # stop
    tab = tabs[0]  # assume fragment to be 1st table

    # "tables" should contain DataFrames, not objects from different pages,
    # which do no longer exist.
    tables.append(tab.to_pandas())  # append this DataFrame


# Everything as expected until here
tables_2 = []
for page in doc_2:  # iterate over the pages
    tabs = page.find_tables()  # locate tables on page
    if len(tabs.tables) == []:  # no tables found?
        break  # stop
    tab = tabs[0]  # assume fragment to be 1st table
    tables_2.append(tab)  # append this DataFrame

# This returns text from the input1.pdf, not national-capitals.pdf as intended
df = pd.concat([tab for tab in tables])  # now "tables" contains DataFrames already
```

We will add logic that prevents wrong usage as you provoked it.
Thanks for submitting this!

**Comment by JorjMcKie** [comment]
The background of your problem is that tables contain references to the table finder object and the page.
So storing a table somewhere else e.g. in an array, beyond the lifetime of the owning table finder and page objects **_must_** **_necessarily_** lead to errors.

The only problem you have been facing is that no exception has been raised as would have been appropriate.

If you want to keep table content after its parent table finder and page are dead, this can only be done in a format without dependencies from original page and table finders - most suitable pandas DataFrame as shown in my snippet.

**Comment by JorjMcKie** [comment]
Closing this for now as there are no changes planned in this respect in the foreseeable future.
