### ISSUE TITLE
After applying redactions with Page.add_redact_annot() some text disappears outside the redaction areas (in this example)

### ISSUE THREAD

**Issue by ffalcon31415** [pymupdf/PyMuPDF#2762]
## Describe the bug (mandatory)
For a simple example document, using `Page.add_redact_annot()` on words found with `Page.get_text("words")` appears to correctly mark the redactions. But, when the same redactions are applied, other text disappears outside of the redactions.

## To Reproduce 
Minimal code snippet:
```python
    import fitz
    def minimal(input_pdf_path: Path, output_pdf_path: Path, apply_redactions: bool = False):
        doc = fitz.open(input_pdf_path)
        for page in doc:
            words = page.get_text("words", delimiters=".,;:")
            for word in words:
                if "(" in word[4] and ")" in word[4]:
                    page.add_redact_annot(
                        word[:4],
                        fill=(0, 0, 0),
                        text="D.O.B.",
                        text_color=(1, 1, 1),
                        fontsize=12,
                        align=fitz.TEXT_ALIGN_CENTER,
                    )
            if apply_redactions:
                page.apply_redactions()
        doc.save(output_pdf_path)
        doc.close()

    minimal("source.pdf","unapplied.pdf", apply_redactions = False)
    minimal("source.pdf","applied.pdf", apply_redactions = True)
```
[source.pdf](https://github.com/pymupdf/PyMuPDF/files/13140626/source.pdf)

## Expected behavior (optional)
Only the text inside the marked redaction areas should be gone

## Screenshots (optional)

source.pdf looks like this:
![ClipboardImage](https://github.com/pymupdf/PyMuPDF/assets/77492177/f3d2e5d6-e078-45c4-a283-11f9298ee425)

unapplied.pdf looks like this (shows the intended redactions as expected):
![ClipboardImage (0001)](https://github.com/pymupdf/PyMuPDF/assets/77492177/03336e95-27b8-42d0-a1cb-e092bbee44fa)

applied.pdf looks like this (note some text outside the redaction areas, in lines above the redactions, is gone):
![ClipboardImage (0002)](https://github.com/pymupdf/PyMuPDF/assets/77492177/9473d9f5-98e3-4bc0-9e57-175550b5775d)

Same artifacts occur on lines below the redactions, though my example here doesn't show that.
## Your configuration (mandatory)
 - Microsoft Windows 10 Enterprise 10.0.19044 x64 
 - Python 3.11.3 (main, May  7 2023, 18:40:36) [MSC v.1929 64 bit (AMD64)]
 - pymupdf==1.23.5, pip install version (wheel)

## Additional context (optional)
Easily possible this is user error rather than a bug. 

Note the source.pdf file is provided to me from outside.

I am able to get close to the desired result by changing the parameters as follows, but it doesn't look quite right and seems hacky.

                page.add_redact_annot(
                    (word[0], word[1] + 3, word[2], word[3] - 2),
                    fill=(0, 0, 0),
                    text="D.O.B.",
                    text_color=(1, 1, 1),
                    fontsize=8,
                    align=fitz.TEXT_ALIGN_CENTER,
                )

This change yields:
![ClipboardImage (0003)](https://github.com/pymupdf/PyMuPDF/assets/77492177/ac8a4355-77ea-469d-803b-94f9bf461e43)

I am loving this library and I truly appreciate the work done on it. It makes my life so much easier.

**Comment by JorjMcKie** [comment]
Both of these observations are (probably) no bugs.
1. Misplaced insertions go back to "unprotected" geometry changes in the page's `/Contents`. Please consult the documentation [here](https://pymupdf.readthedocs.io/en/latest/recipes-common-issues-and-their-solutions.html#misplaced-item-insertions-on-pdf-pages) for how to address this.
2. Unexpected removals above or below the redaction rectangles go back to a too large redaction rectangle height. Whenever the text lines in a page have a closer distance than what their "natural" height is, this effect happens Natural height refers to font properties "ascender" and "descender". For example Helvetica has a natural lineheight of 1.374 * fontsize - which is a lot. Your effect will occurs for text lines having a distance less than 13,74 points for fontsize 10. You can heal this by a smaller redaction rectangle height. For example set `fitz.TOOLS.set_small_glyph_heights(True)` globally, but for sure before you search. This will yield smaller rects. If still not sufficient, there is no way but adding own code that shrinks the rect height ...

**Comment by ffalcon31415** [comment]
Very interesting. set_small_glyph_heights works for my use case. Thanks!

**Comment by JorjMcKie** [comment]
Glad you found a way!
Close the issue?

**Comment by Muhammadraafat1** [comment]
@JorjMcKie 
Hi, I apply set_small_glyph_heights and it works well, but the fontsize became small even I determined it by 20 and it's not effected 
![image](https://github.com/pymupdf/PyMuPDF/assets/140750834/729d3b0a-ab1c-4449-b98b-ea3f2b0c15cf)
