### ISSUE TITLE
Cannot insert text with floating point fontsize/non-zero render mode

### ISSUE THREAD

**Issue by smithct2** [pymupdf/PyMuPDF#2771]
Hello,

I recently upgraded from PyMuPDF version 1.22.3 to version 1.23.5 and I can no longer insert text into pages using a floating point fontsize with a render_mode besides zero. All documentation suggests that floats should still be supported, and this approach worked in version 1.22.3 without issue. The issue goes away if I either use a render_mode of 0 or an integer fontsize.

## Describe the bug (mandatory)
PyMuPDF raises the following error when trying to call page.insert_text() with a floating point fontsize and a non-zero render_mode.

![image](https://github.com/pymupdf/PyMuPDF/assets/46684044/8ac77069-ddfa-48f3-ac99-029809d7efb8)

## To Reproduce (mandatory)
Please use attached script and sample PDF. I believe the same error will be raised for any input PDF though.
[sample.pdf](https://github.com/pymupdf/PyMuPDF/files/13181452/sample.pdf)

[script.py.txt](https://github.com/pymupdf/PyMuPDF/files/13181454/script.py.txt)

## Expected behavior (optional)
Text is inserted without error.

## Your configuration (mandatory)
 - Ubuntu 22.04
 - Python 3.10.6
 - PyMuPDF versions 1.22.3 and 1.23.5, both installed with pip

**Comment by JorjMcKie** [comment]
That line shoulkd read:
![grafik](https://github.com/pymupdf/PyMuPDF/assets/8290722/6a9f76d2-ff89-4302-923e-81b4d702597d)
As well as line 3918. Both in `utils.py`

**Comment by JorjMcKie** [comment]
If brackets are omitted, the formatting replacement character "%" binds stronger than the multiplication. If then the fontsize is an integer no error is detected, but the string is replicated a respective number of times.
