### ISSUE TITLE
wrong encoding for "\Č" character when sort=True

### ISSUE THREAD

**Issue by vorel99** [pymupdf/PyMuPDF#2774]
## Describe the bug
I have PDF and trying to read the text, but special characters are incorrectly formatted, when `sort=True` is set.
text in my pdf: `something \Č etc.`

```
page.get_text()
```
returns `something \\Č etc.`

but when sort True is set, the text is formatted differently.
```
page.get_text(sort=True)
```
returns `something \\\\u010c etc.`

The problem is similar to #2730 but with different character.

**Comment by JorjMcKie** [comment]
This is a duplicate of #2553 which will be fixed in next release.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.6.
