### ISSUE TITLE
Is insertImage(keep_proportion=True) broken?

### ISSUE THREAD

**Issue by killthekitten** [pymupdf/PyMuPDF#278]
How exactly the `keep_proportion` flag is supposed to work?

I'd expect it would use the image's real width and height combined with one of the sides of the rect, instead it squishes the image based on the rect's width and height:
https://gist.github.com/killthekitten/ca3bbc29cecc3cd9bba20b81afc605c5

Seems, the problem is in [this piece](https://github.com/pymupdf/PyMuPDF/blob/672a44ca088c31706c52b9bb01504fe75fd2b3d6/fitz/utils.py#L177), especially `fw = fh` and `max(fw, fh)`:

```python
fw = r.width
fh = r.height
if keep_proportion:
    fw = fh = min(fw, fh)
    my = r.height - max(fw, fh)
    mx = r.width - max(fw, fh)
else:
    my = mx = 0
```

Whereas for [showPDFPage](https://github.com/pymupdf/PyMuPDF/blob/672a44ca088c31706c52b9bb01504fe75fd2b3d6/fitz/utils.py#L61) it looks legit:

```python
fw = tr.width / sr1.width  # scale the width
fh = tr.height / sr1.height  # scale the height
if keep:
    fw = fh = min(fw, fh)  # take min if keeping aspect ratio
```

**Comment by JorjMcKie** [comment]
`keep_proportion` for images was not a feature ever before, so this is the first try to offer it - and that failed, unfortunately.

I had the illusion, that this might work without reading out image properties at that early point in the process. And that's not true.

What I will do now is correcting this, but I am afraid it will have an adverse effect on performance ...

**Comment by killthekitten** [comment]
Yea, I see what you wanted to do, which is totally awesome 👍 

`HummusJS` takes the idea even further, it even allows you to provide only one dimension:

```js
pageModifier
  .startContext()
  .getContext()
  .drawImage(420, 280, imageStream, {
    transformation: { width: 150, proportional: true }
  });
```

I just wanted to confirm it's a bug and hoped that `MuPDF` might handle grabbing the dimensions from the stream while working with the image. 

Otherwise, for our use case it's ok to keep it outside of `PyMuPDF` scope – there's no real reason to bring in `PIL` dependency to the lib. I could just as well read out the image and calculate the rect before calling `insertImage`.

**Comment by JorjMcKie** [comment]
I solved this problem yesterday. As you said: bringing in other packages is an absolute no-go.

Uisng MuPDF, I wrote a little C routine to determine the image dimensions and then re-use intermediate results as much as possible.

All this is necessary only when the aspect ratio (proportion) must be kept.
That approach brought me back to previous performance ranges.

And yes: the quotient width/height of the image would be sufficient to know ... in theory.

Already today you can "solve" the issue by providing a display rectangle with the correct widht:height ratio.

**Comment by killthekitten** [comment]
Thanks! 👍

**Comment by killthekitten** [comment]
It was super-easy to achieve using just `Pixmap` without any dependencies 👍 

One last thing that is not clear – the dimensions get corrupted when using `keep_proportion=False` and the bottomright corner of the image rect happen to be outside of the page rect. 

Seems like it gets squished to fit the page.

**Comment by JorjMcKie** [comment]
The specified target rectangle is **always automatically intersected** with the page rectangle - and thus modified, if parts of it are outside the page.
That should be the explanation for your symptom ...

**Comment by JorjMcKie** [comment]
Hi, just uploaded v1.14.13 to PyPI (contrary to my earlier reluctance ...). This should fix the issue.

**Comment by killthekitten** [comment]
Fixes the original issue but has a regression for (transparent?) pixmaps. This code gives me another segfault https://gist.github.com/killthekitten/f600f96aedc04be2540f3e23f35d0870.

**Comment by JorjMcKie** [comment]
Made a bunch of comments on your Gist.
As it looks right now, insertImage is broken for exclusively if using pixmaps on Linux.
Everything else works - Windows or Linux.

**Comment by JorjMcKie** [comment]
Recompiled the stuff ... and voilà everything works now.
If you need a working Linux version look at the ``linux`` branch of https://github.com/pymupdf/PyMuPDF-wheels to pick your version.
I think I won't publish v1.14.14 anytime soon on a general basis.

**Comment by killthekitten** [comment]
I got the error on Mac, actually, so osx version should also be recompiled.

Thanks for looking into it! The code successfully runs in production already.

P.S.: responding to the gist comments, the snippet has nothing to do with our real code and using Pixmap was a temporary solution prior to 1.14.13 – that's how I got to catch the error.

**Comment by JorjMcKie** [comment]
Ok, I will have the OSX version generated too. You can have a look there yourself in that repo – branch OSX

Jorj

________________________________
Von: Nikolay Shebanov <notifications@github.com>
Gesendet: Tuesday, April 9, 2019 5:15:12 PM
An: pymupdf/PyMuPDF
Cc: Jorj X. McKie; Comment
Betreff: Re: [pymupdf/PyMuPDF] Is insertImage(keep_proportion=True) broken? (#278)


I got the error on Mac, actually, so osx version should also be recompiled.

Thanks for looking into it! The code successfully runs in production already.

P.S.: responding to the gist comments, the snippet has nothing to do with our real code and using Pixmap was a temporary solution prior to 1.14.13 – that's how I got to catch the error.

**Comment by JorjMcKie** [comment]
please find the OSX wheels in https://github.com/pymupdf/PyMuPDF-wheels branch ``osx``.

**Comment by killthekitten** [comment]
Great, thanks for all the help!
