### ISSUE TITLE
Problem with get_toc in pymupdf 1.23.6

### ISSUE THREAD

**Issue by blenzi** [pymupdf/PyMuPDF#2788]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
`get_toc` returns wrong information in pymupdf 1.23.6

## To Reproduce (mandatory)

```
pdf = fitz.open("outputs/dossiers/91dc9eb5-a34e-4241-89b7-28188421b534/PJ49_EDD_compDREAL_avril2023.pdf.pdf")
pdf.get_toc(simple=False)[-1]
[2, 'Page 1', 0, {'kind': 4, 'xref': 712, 'name': 'nameddest=_PAGE1', 'zoom': 0.0}]
```

The file can be found [here](https://osmose.numerique.gouv.fr/front/publicLink/publicDownload.jsp?id=9879d883-1c17-4723-b47a-a22e592cf25136c41299-7ca5-4e6e-91ce-0ac66af1cb81).

## Expected behavior (optional)
In v1.22 this gives: `[2, 'Page 1', 284, {'kind': 4, 'xref': 712, 'name': 'page=284&zoom=100,-4,-4.1102297', 'zoom': 0.0}]` which looks correct.

**Comment by julian-smith-artifex-com** [comment]
The change mentioned above give the following toc for the specified PDF:
```
[
[1, 'PJ49_EDD_annexe5_plan_general.pdf', 1, {'kind': 1, 'xref': 711, 'page': 0, 'to': Point(0.0, 1.0), 'zoom': 0.0, 'collapse': False}],
[2, 'Page 1', 0, {'kind': 4, 'xref': 712, 'page': 283, 'to': (-4.0, 846.0), 'zoom': 0.0, 'nameddest': '_PAGE1'}],
]
```
So the dict now contains the destination page number and (x, y). And for completeness it also contains the original nameddest string `_PAGE1`.

[However the source page number `0` is not 1-based as it should be according to the docs, and we should probably change `(-4.0, 846.0)` to `Point(-4.0, 846.0)`.]

**Comment by julian-smith-artifex-com** [comment]
The current tree now gives the following toc for the specified PDF:
```
[1, 'PJ49_EDD_annexe5_plan_general.pdf', 1, {'kind': 1, 'xref': 711, 'page': 0, 'to': Point(0.0, 1.0), 'zoom': 0.0, 'collapse': False}]
[2, 'Page 1', 284, {'kind': 4, 'xref': 712, 'page': 283, 'to': Point(-4.0, 846.0), 'zoom': 0.0, 'nameddest': '_PAGE1'}]
```
\- which looks ok to me.

**Comment by julian-smith-artifex-com** [comment]
Note that this fix will be in the rebased implementation only.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.7.

**Comment by archeradvanture** [comment]
Hi i am encountering similar issue.
the pymupdf version is already 1.23.7 

```shell 
$ conda list |grep pymupdf           
pymupdf                   1.23.7                   pypi_0    pypi
pymupdfb                  1.23.7                   pypi_0    pypi

```

```python
 doc = fitz.open(pdf_path)
    toc_list = doc.get_toc(simple=False)
    toc = toc_list[9]
    print(toc)
```

output 

```
[3, 'Privileges and authorities required', 15, {'kind': 4, 'xref': 2866, 'name': 'nameddest=_OPENTOPIC_TOC_PROCESSING_d135e3328', 'color': (0.0, 0.0, 0.0), 'zoom': 0.0}]
```

i have two questions.

1.There is no `to` attribute in toc 
2.How am i supposed to use the namedest attribute ? 
In 1.21.0. the name attribute was like ` 'name':'page=15&zoom=nan,nan,629.2'` which i can leverage to find the link destination (coordination) in another page.

**Comment by JorjMcKie** [comment]
@archeradvanture what was your import statement? fitz_new (=rebased)?
Your result does not look like this.

**Comment by archeradvanture** [comment]
> @archeradvanture what was your import statement? fitz_new (=rebased)? Your result does not look like this.

nothing special , just the normal way 

```
import fitz
```

**Comment by archeradvanture** [comment]
if i change the import statement to 

``` python
import fitz_new as fitz
```

then the result would be like 
```
[3, 'Privileges and authorities required', 15, {'kind': 4, 'xref': 2866, 'page': 14, 'to': Point(0.0, 162.79999), 'zoom': 0.0, 'nameddest': '_OPENTOPIC_TOC_PROCESSING_d135e3328', 'color': (0.0, 0.0, 0.0)}]
```
This seems match the official docs. 

But I still wonder why there is a need to import packages like above and what i can do with the `nameddest` attribute ?

**Comment by JorjMcKie** [comment]
The import statement refers to a new PyMuPDF version that has a different internal architecture. We are in the process of migrating to it and have started implementing some new features exclusively in the new version - like PDF names resolution.

This is the reason why resolving named destinations is available in the new ("rebased") version only.
In one of the new PyMuPDF releases we will switch over to rebased such that the old import statement will automatically activate that new version.

Otherwise, it is up to you what you **_want_** to do with the destination name. It is a PDF feature that offers to use symbolic names for destination targets. You are not obliged to take notice: as you can see, our resolution contains all information as you would also see for a GOTO destination.

**Comment by archeradvanture** [comment]
Thank you very much for the patience and clear explanation !
