### ISSUE TITLE
How to fill pdf so that all the fields appear filled in Chrome?

### ISSUE THREAD

**Issue by paritoshranjan** [pymupdf/PyMuPDF#2789]
If I fill the pdf form using pymupdf and then open the pdf in Chrome then Chrome gives following warning:

"This document contains open fields to fill out. Completing them within the web browser is not supported. In order to complete them, please download and save the document."

Even after selecting "OK" to this warning, the fields of the pdf in Chrome appear empty.

The pdf fields appear filled in Acrobat Reader and in Firefox.

Can this be fixed?

I am using following code:

    doc = fitz.open("form.pdf");

    for page in doc:
        widgets = page.widgets()
        for widget in widgets:
            widget.field_value = "the value string"
            widget.update()
            doc.save(filename, incremental=False)
        doc.save(filename)

**Comment by JorjMcKie** [comment]
PDF support is not a direct feature of internet browsers themselves - instead they use some PDF plugin of their (individual) choice. The same browser on different OS platforms may even have a different plugin per platform.
So all depends on the PDF plugin that your Chrome version uses on your machine.
There is nothing that PyMuPDF can do about I am afraid.

**Comment by jamie-lemon** [comment]
Possibly Chrome is looking at a cached (unfilled) version of your PDF if it has the same filename. Try a different filename or clearing your cache maybe.
