### ISSUE TITLE
The positional information extracted through the Page.get_text('words', flags=fitz.TEXT_INHIBIT_SPACES) method has a deviation.

### ISSUE THREAD

**Issue by 1339503169** [pymupdf/PyMuPDF#2796]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
The positional information extracted through the Page.get_text('words', flags=fitz.TEXT_INHIBIT_SPACES) method has a deviation.

## To Reproduce (mandatory)
[words_test.pdf](https://github.com/pymupdf/PyMuPDF/files/13315186/words_test.pdf)
![image](https://github.com/pymupdf/PyMuPDF/assets/22074904/394068d7-c85e-4e48-b062-6962404b278b)
![image](https://github.com/pymupdf/PyMuPDF/assets/22074904/2cd99b6e-b8b2-4636-bcaa-42a8f189686b)

pymupdf version is 1.23.5

The code belows can reproduces the bug

`   document = fitz.open('data/word_test.pdf')
    page = document.load_page(0)
    words = page.get_text('words', flags=fitz.TEXT_INHIBIT_SPACES)
    for word in words:
        rect =fitz.Rect(word[0], word[1], word[2], word[3])
        color = (0, 1, 0)
        page.draw_rect(rect, color)
    document.save('word_test_new.pdf')
`

The text boxes extracted through the Page.get_text('words', flags=fitz.TEXT_INHIBIT_SPACES) contain some abnormal blocks that seem much larger than I anticipated. Is there room for optimization that I might be missing?

**Comment by JorjMcKie** [comment]
This file has an illegal font specification in that it uses "Identity-H" encoding for a non-embedded font (SimSun).
This seems to cause confusion wRT character sizes (causing the extremely high bboxes).
All this is outside control of PyMuPDF and has to be looked at by the MuPDF experts.
Do you want to submit a bug there? https://bugs.ghostscript.com/enter_bug.cgi

**Comment by 1339503169** [comment]
otherway i try to convert pdf to image, it seems like the transferred image does not look consistent with the original pdf , this is the image i transfered from this pdf ,  is there some setting i dont set? 
![image](https://github.com/pymupdf/PyMuPDF/assets/22074904/cf83ebb3-a342-480d-8f4e-8531d2b1ca65)

**Comment by JorjMcKie** [comment]
I see no difference.

**Comment by JorjMcKie** [comment]
Closed b/o of waiting for response for an extended period of time.
