### ISSUE TITLE
Document.select does not reflect sequence

### ISSUE THREAD

**Issue by srunow** [pymupdf/PyMuPDF#2800]
Loading a pdf with four pages and having a set like `[0, 1, 2, 1, 2, 1, 2, 3]` passed to `Document.select` as sequence leads to a corrupted pdf. Corrupted means, that the saved pdf has the correct number of pages but after the first four pages the next pages cannot be loaded (tried with different pdf readers). In addition, using `Document.load_page` with e.g index 5 after calling `Document.select` returns the page object at index 1 (which is per se the correct page, but the wrong object).

I expect that the document will be reordered from `[0, 1, 2, 3]` to given sequence and pages (1 and 2 in the example) were added (or removed) as stated in the docs as "Page numbers can occur multiple times and in any order: the resulting document will reflect the sequence exactly as specified." here https://pymupdf.readthedocs.io/en/latest/document.html#Document.select

But in this issue https://github.com/pymupdf/PyMuPDF/issues/880 was stated, that Document.select only removes but not add any pages.

Please clarify what behaviour should be expected by `Document.select`

**Comment by JorjMcKie** [comment]
It works as designed:
* there are no new pages created - if a page number is contained mutiple times in that list, it is the same page object - only the reference to the page is duplicated. Check this by looking at `page.xref`.
* accordingly, if you make changeds to one of those pages, its twin will show that change too.
* Most viewers understnd this correctly, among them are PDF XChange, Foxit, evince, SumatraPDF, MuPDF. Adobe has some issues - I didn't find out why.

**Comment by srunow** [comment]
Thank you for clarifying this. In my opinion it's not clearly stated in the docs that `Document.select`only affects page references and do not fullcopy page objects when duplicates of a page is in the sequence. After you've listed the expected behaviour, someone can reduct this from `Document.copy` mentioned in the notes of `Document.select`.

Is there any chance that `Document.select` gets an additional flag with which it calls `fullcopy_page` instead of `copy_page` internally?

Nevertheless, you guys delivered a really good work with that lib.

**Comment by JorjMcKie** [comment]
> Is there any chance that Document.select gets an additional flag with which it calls fullcopy_page instead of copy_page internally?

No, I am afraid there is no business case to ever do that.

**Comment by srunow** [comment]
I'm sure it is, I wouldn't ask otherwise. But as for you the documentation seems to be clear enough as well, I don't mind to keep my questions and suggestion for myself in the future.

Thanks again for answering my initial question.
