### ISSUE TITLE
custom stamp anotation

### ISSUE THREAD

**Issue by santi2491** [pymupdf/PyMuPDF#2802]
Can I add a custom stamp to the stamps that currently exist in Stamp Annotation Icons

**Comment by JorjMcKie** [comment]
Yes - to a limited extent - please see the documentation [here](https://pymupdf.readthedocs.io/en/latest/annot.html#Annot.set_name).

**Comment by santi2491** [comment]
Can you give me more information? I tried the documentation but the notation is not stamp type

**Comment by santi2491** [comment]
> Yes - to a limited extent - please see the documentation [here](https://pymupdf.readthedocs.io/en/latest/annot.html#Annot.set_name).

Can you tell me how? I am trying to modify the text of a stamp with the set_name function but it does not work

**Comment by JorjMcKie** [comment]
No idea why it doesn't seem to work anymore. As a last resort you could do this:
```python
a = page.add_stamp_annot(rect)
code = a._getAP().replace(b"Approved", b"my-stamp")
a._setAP(code)
```
