### ISSUE TITLE
table cell not extracted correctly

### ISSUE THREAD

**Issue by clockfly** [pymupdf/PyMuPDF#2814]
# Input

![in1](https://github.com/pymupdf/PyMuPDF/assets/2595532/f0264aaf-1e89-4d96-bcd0-12a798e1341a)
# Output 
![out1](https://github.com/pymupdf/PyMuPDF/assets/2595532/05e28a98-7801-450d-acb3-3bcb3d897e26)

# How to reproduce 
[xx2.pdf](https://github.com/pymupdf/PyMuPDF/files/13393150/xx2.pdf)

# Expectation

Cell is not wrongly splitted into multiple cells.

**Comment by clockfly** [comment]
After using get_drawings, I can see some "hard-to-find" transparent line separators. Can we optimize the code so that when extracting table border we also take into account of the color of drawing color?

So that a table border that is not visible IS NOT a real table border.

<img width="1563" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/2595532/a970d022-18f3-49fb-b792-11d6cc7179e9">

**Comment by JorjMcKie** [comment]
Aha! Thanks for doing this investigation! Saved me a lot of investigative effort!
You are quit right: that is the reason. In table detection, one is normally happy for every tiny hint that helps - and thus gladly also accepts white lines.

But I do understand the situation. Let me think about this possible enhancement.
Maybe the best would be to add a parameter that lets exclude white lines or fully transparent objects.

**Comment by JorjMcKie** [comment]
Within all the vector graphics, there 25 rectangles with no border and filled with white.
Probably ignoring these would already solve the problem.

To come up with a decent API, we could do one of the following:
* add a parameter with colors to ignore
* add a parameter for colors to consider

Any opinion?

**Comment by clockfly** [comment]
@JorjMcKie], thanks,

Is it possible detect the background color and ignore the border that has the same color? 

For example, sometimes we have a dark pdf background, and we want to use light color border to extract the tables.

**Comment by JorjMcKie** [comment]
This is not safely detectable, because the background may be an image, which would then have to be analyzed. Similar is true for a background formed by a vector graphic.
So it cannot be done fully automatically.

But of course:
If you think you know where to look on your page, take a small rectangle, make an RGB Pixmap using this rectangle as the clip. Then confirm that `Pixmap.is_unicolor` and use one of its pixels as the color to ignore.

**Comment by JorjMcKie** [comment]
In your case, the page looks white, but in reality it has no background color at all. If you would make a Pixmap with transparency, you would see that:
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/38040279-eb69-4067-b095-b0a409990767)

**Comment by JorjMcKie** [comment]
This issue has been resolved by 1.23.14.
