### ISSUE TITLE
Segfault reproducible with `PyMuPDF>=1.22`

### ISSUE THREAD

**Issue by tovrstra** [pymupdf/PyMuPDF#2815]
## Describe the bug

A Segfault is produced with the example script below. The input PDF file (also attached as [fig.pdf](https://github.com/pymupdf/PyMuPDF/files/13399286/fig.pdf)) was generated with [matplotlib](https://matplotlib.org/) 3.8.2 using the following code:

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot([0, 1, 2, 3], [4, 2, 3, 1])
fig.savefig("fig.pdf")
```

This is just a simple example plot. The details in the figure don't matter, and the problem can be reproduced with other PDFs generated with matplotlib too. However, running the script below with a PDF generated differently, e.g. with Inkscape, does not reproduce the problem.

The following script uses `fig.pdf` as input and causes the segfault.

```python
import fitz
fig = fitz.open("fig.pdf")
w = fig[0].rect.width
h = fig[0].rect.height
doc = fitz.open()
page = doc.new_page(width=w*2, height=h)
page.show_pdf_page(fitz.Rect(0, 0, w, h), fig, 0)
page.show_pdf_page(fitz.Rect(w, 0, 2*w, h), fig, 0)
doc.scrub()
doc.save("result.pdf")
```

The file `result.pdf` is generated, and the segfault apparently only happens afterwards when Python is closing.

The problem can also be reproduced when placing two different figures, i.e. it is not specifically due to using the *same* `fig` in two subsequent `show_pdf_page` calls.
Note that the problem goes away when commenting out one of the `show_pdf_page` lines or the `scrub` line. (The script above is a minimal example derived from a more complicated script.)

## To Reproduce

Run the example script above.

## Expected behavior

The script ends without segfault.

## Screenshots (optional)

Not relevant.

## Your configuration (mandatory)

 - **Operating system, potentially version and bitness:** Fedora Linux 39 (Workstation Edition), 12th Gen Intel® Core™ i7-1260P × 16
 - **`uname -a`:** `Linux molmod47 6.5.11-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 8 22:37:57 UTC 2023 x86_64 GNU/Linux`
 - **Python version, bitness:** Python 3.12.0 (main, Oct 2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)] on linux (python3-3.12.0-1.fc39.x86_64.rpm)
 - PyMuPDF version, installation method (**wheel** or **generated** from source): `PyMuPDF-1.23.6-cp312-none-manylinux2014_x86_64.whl` installed with pip.

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

```
>>> print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)] 
 linux 
 
PyMuPDF 1.23.6: Python bindings for the MuPDF 1.23.5 library.
Version date: 2023-11-06 00:00:01.
Built for Python 3.12 on linux (64-bit).
```

## Additional context (optional)

The segfault occurs with all PyMuPDF versions 1.22.0 and newer.

**Comment by JorjMcKie** [comment]
Thank for the diligent preparation of the report!
I have reproduced the problem. It is a duplicate of #2742 in that it does similar things as that problem and it does not occur when you use the new rebased implementation of PyMuPDF.
Please see comments thread there.
Therefore, using `import fitz_new as fitz` is a good workaround for this situation until we shift to making `fitz_new` the default for `fitz` soon.

**Comment by tovrstra** [comment]
Thanks for the quick reply and the fix! I can confirm that it also works for the more complex example.

**Comment by JorjMcKie** [comment]
Glad that this works for you!
As I mentioned, we are in the process of migrating PyMuPDF to the implementation based on `fitz_new`.
This process consists of three steps:

* In the current step 1 we are making the new implementation available via import statement `import fitz_new ...`.

* Step 2 will then change the default to `import fitz` again, keeping the "classic" implementation still available via `import fitz_old ...` as a fallback. This step will be taken very soon.

* The final step will then remove the classic implementation altogether.
