### ISSUE TITLE
Trying to insert multiple links for same hot area

### ISSUE THREAD

**Issue by ashish9308** [pymupdf/PyMuPDF#283]
Hello i'm trying to add 5 linkes in a keyword using insertLink method while I'm trying to to do so I'm able to see only 1 link.
Please tell me the steps to add multiple link in a single keyword.

**Comment by JorjMcKie** [comment]
Don'tunderstand what you are trying to do.

**Comment by ashish9308** [comment]
> Don'tunderstand what you are trying to do.

Hi Thanks for your reply Attaching the screenshot of Sample PDF.  Suppose we need to add two links (http://www.google.com and http://www.abc.com ) in a single page at Same position around the keyword (Challenging) Then How we can implement this?
Currently I'm doing like this you can see in coding but only last link getting inserted that is (http://www.abc.com) Please tell me the steps to add multiple links : 

text_instances = page.searchFor(row.Keyword,hit_max = 1)
            for i in text_instances:
                 var_weblink = page.insertLink({'kind': 2, 'from': fitz.Rect(i.x0, i.y0, i.x1, i.y1), 'uri': 'http://www.google.com'}) 
                 var_weblink = page.insertLink({'kind': 2, 'from': fitz.Rect(i.x0, i.y0, i.x1, i.y1), 'uri': 'http://www.abc.com'}) 


Need to implement this in priority so please tell me the solution

**Comment by JorjMcKie** [comment]
This does work!
But you cannot **see** it!

The "hot area" is the rectangle around the searched word "challenging". The same rectangle is used for **two different link targets**. Of course, your PDF viewer can only show one of them, but they both exist.
You can see this when looking into the PDF "source" by using a suitable text editor.

**Comment by JorjMcKie** [comment]
BTW you can code the link insertion like this: ``var_weblink = page.insertLink({'kind': 2, 'from': i, 'uri': 'http://www.google.com'})``, because ``i`` already **is** a ``fitz.Rect``.

**Comment by ashish9308** [comment]
> BTW you can code the link insertion like this: `var_weblink = page.insertLink({'kind': 2, 'from': i, 'uri': 'http://www.google.com'})`, because `i` already **is** a `fitz.Rect`.

After Doing the changes which you suggested again I executed my python code , I inserted two links but while clicking on that link through PDF , I can see only one link is opening in the browser not Two.

**Comment by JorjMcKie** [comment]
I had hoped I made it clear:
Your approach **cannot** work! If you insert one or 100 links for the same rectangle: **only one link target** is ever shown - by every PDF reader I know.

**Comment by ashish9308** [comment]
> Of course only one link is shown. I had hoped I made it clear:
> Your approach **cannot** work! If you insert one or 100 links for the same rectangle: **only one link target** is ever shown - by every PDF reader I know.

Let me clarify more on this please refer the screenshot example. If 2 links are there then why it is showing only the last link (Please refer screenshot) . As you can see it is adding only one **Open a weblink** action but ideally it should be 2  **Open a weblink** one with http://www.google.com and another with http://www.abc.com so manually if you add one more link then you can see one more action will be added and then if you click on keyword it will open two links for you. Please let me know how I can achieve this?
Please let me know if you need more clarification on this.

![Capture](https://user-images.githubusercontent.com/17781215/56033603-8b6e5800-5d42-11e9-8c3a-09123afa7374.PNG)

**Comment by JorjMcKie** [comment]
* I did understand what you want to do.
* Both links do exist. Verify this by looking at ``page.getLinks()``
* **Showing** these links is the task of your PDF viewer (Adobe Acrobat or whatever). If your viewer only shows one link, then you have to accept that. Your idea simply is not going to work. Think about something else.

**Comment by JorjMcKie** [comment]
Maybe I should add that coding several action steps into one link is not possible with PyMuPDF.

**Comment by ashish9308** [comment]
> Maybe I should add that coding several action steps into one link is not possible with PyMuPDF.

Is there any alternative way to implement this or can you please suggest or do some alternative coding for this scenario.
I'm using PymuPDF for one of my project and all the functionality is working fine only in this step I stuck If you can suggest something to me that will be very helpful.

**Comment by JorjMcKie** [comment]
I am afraid not - not at the moment at least.
If you only have 2 links word, you want to consider dividing the hot area rectangle in two parts and take the left for one link and the right for the other ... as ugly as this may sound.

**Comment by JorjMcKie** [comment]
I have have taken your requirement on my list of longterm feature extensions.
Thanks fpr bringing this up - although it took a while for me to understand the true background of your request ... your initial remarks have put me on a completely wrong track.

Some words about the complexity involved:
1. MuPDF (the C base library I am relying on) does not support it
2. Support of this feature would be PDF exclusively, whereas MuPDF also supports links of other document types as well
3. **Insertion** of chained action links is one thing, **updating** and **deleting** such links would have to be supported in a consistent manner as well
4. All of this must be kept compatible with the existing **_Link class_** API of PyMuPDF

**Comment by ashish9308** [comment]
Thanks for all your support **JorjMcKie** happy to hear that now you understood this operation.
Can you please let me know how much time it will take to add this feature, if it can be done in 2-3 days then it will be very helpful for me because for my project this is the last operation where I stuck. Please let me know if you can enhance this fetature in latest Pymupdf or do some coding for me in current library so that I can use.
Thanks for your continuous help on this.

**Comment by JorjMcKie** [comment]
As I pointed out in my previous post, a quality solution is quite complex for a number of reasons (I named some of them).
So there is now way in the near future to find a solution for you - sorry.
