### ISSUE TITLE
feature : introduce raw bytes of character

### ISSUE THREAD

**Issue by ivanstepanovftw** [pymupdf/PyMuPDF#2835]
I am requesting to add `span["chars"][N]["b"]` that represent raw bytes.
I need to get raw `bytes` that are inside span. `span["chars"][N]["c"]` is of type `str`, not `bytes`.

```py
doc = fitz.fitz.Document("pdfs/arabic.pdf")

for page in doc:
    blocks = fitz.utils.get_text(
        page=page,
        option="rawdict",
        flags=fitz.TEXT_PRESERVE_LIGATURES | fitz.TEXT_INHIBIT_SPACES
    )["blocks"]
    for block in blocks:
        for line in block["lines"]:
            for span in line["spans"]:
                for char in span["chars"]:
                    c = char["c"]  # leave str for compatibility
                    b = char["b"]
                    assert isinstance(b, bytes)
```

Reasoning: not all bytes can be represented as str, that is a unicode string.

PDF to verify: [arabic.1.pdf](https://github.com/pymupdf/PyMuPDF/files/13438694/arabic.1.pdf)

Relevant: https://github.com/pymupdf/PyMuPDF/issues/365 https://github.com/pymupdf/PyMuPDF/discussions/2834 https://github.com/UD3-Lab/mintEMU/issues/18

**Comment by JorjMcKie** [comment]
When there exists no valid Unicode and no reason exists to return the Invalid Unicode `0xFFFD`, Python's raw unicode escape function is used which does return backslash-escaped strings. That's all we can offer. There is no way for PyMuPDF to directly access the bytes that MuPDF has encountered when parsing the text.

There is [method](https://pymupdf.readthedocs.io/en/latest/functions.html#Page.get_texttrace) `page.get_texttrace()` which more directly interacts with MuPDF and returns a list of dictionaries. For each glyph encountered, the unicode and the glyph numbers are returned, currently.
We might add an option to this method such that instead the names of the unicode and the glyph are returned. In your example case this would be information like this (although not in XML format of course):
```xml
    <span font="NSIEBX+OmegaSerifArabicOne" wmode="0" bidi="0" trm="11.9552 0 0 11.9552">
        <g unicode="�" glyph="qaffin" x="199.92053" y="741.08" adv=".554"/>
        <g unicode="�" glyph="wawiso" x="188.76033" y="741.08" adv=".43"/>
        <g unicode="�" glyph="hehini" x="176.52053" y="741.08" adv=".526"/>
        <g unicode="�" glyph="wawfin" x="171.48067" y="741.08" adv=".425"/>
        <g unicode="�" glyph="alifiso" x="162.00063" y="741.08" adv=".295"/>
        <g unicode="�" glyph="hahini" x="154.56038" y="741.08" adv=".621"/>
        <g unicode="�" glyph="dalfin" x="149.64043" y="741.08" adv=".412"/>
        <g unicode="�" glyph="yehiso" x="141.84043" y="741.08" adv=".649"/>
        <g unicode="�" glyph="alifiso" x="132.36035" y="741.08" adv=".295"/>
        <g unicode="�" glyph="lamini" x="129.60019" y="741.08" adv=".235"/>
        <g unicode="�" glyph="thalfin" x="124.68026" y="741.08" adv=".412"/>
        <g unicode="�" glyph="alifiso" x="121.20057" y="741.08" adv=".295"/>
        <g unicode="�" glyph="tehiso" x="111.36035" y="741.08" adv=".827"/>
    </span>
    <span font="YQFCOP+SFTT1200" wmode="0" bidi="0" trm="11.9552 0 0 11.9552">
        <g unicode="\" glyph="backslash" x="140.16034" y="670.4004" adv=".514"/>
        <g unicode="b" glyph="b" x="146.27489" y="670.4004" adv=".514"/>
        <g unicode="o" glyph="o" x="152.38945" y="670.4004" adv=".514"/>
        <g unicode="d" glyph="d" x="158.504" y="670.4004" adv=".514"/>
        <g unicode="y" glyph="y" x="164.61855" y="670.4004" adv=".514"/>
        <g unicode="d" glyph="d" x="170.73311" y="670.4004" adv=".514"/>
        <g unicode="i" glyph="i" x="176.84766" y="670.4004" adv=".514"/>
        <g unicode="r" glyph="r" x="182.9622" y="670.4004" adv=".514"/>
    </span>
```
If none of these options comes close to what you require, I am afraid we have to turn down your request on behalf of PyMuPDF.
You may want to talk to the MuPDF people about this in this [Discord](https://discord.gg/stKJn3xt) channel.

**Comment by ivanstepanovftw** [comment]
Seems like it works, need to double check 
![image](https://github.com/pymupdf/PyMuPDF/assets/8203898/83e3a472-df7e-43f6-b37f-ace77925c0f0)
```py

for page in doc:
    texttrace = page.get_texttrace()
    fig, ax = plt.subplots()
    ax.imshow(pixmap_to_image(fitz.utils.get_pixmap(
        page=page,
    )))

    for text in texttrace:
        for char in text["chars"]:
            print(char[0], char[1])
            ax.add_patch(plt.Rectangle((char[3][0], char[3][1]), char[3][2]-char[3][0], char[3][3]-char[3][1],
                                       fill=False, color="red"))
            ax.text(char[2][0], char[2][1], char[1], fontsize=16, color="red")
    plt.show()
"""
1633 3
65533 36
65533 45
65533 54
65533 21
65533 37
65533 44
65533 41
65533 21
65533 37
65533 17
65533 13
65533 47
65533 14
65533 21
65533 37
65533 17
65533 13
65533 6
65533 54
65533 21
65533 25
65533 46
1617 1
... (NOT SORTED)
"""
```
(I do not know what `char[0]` is)

**Comment by ivanstepanovftw** [comment]
I think it is solved: use `page.get_texttrace` instead of `page.get_text`/`fitz.utils.get_text` with `option="rawdict"` to get raw ~byte~ glyph.

**Comment by JorjMcKie** [comment]
The first integer is the unicode number, the second one is the glyph number.
There is a way to let MuPDF determine the glyph name based on font data (i.e. if the font contains that info at all).
So my question was whether it would make sense to offer a parameter like `page.get_texttrace(names=True)`.

**Comment by ivanstepanovftw** [comment]
Yes, any extra info will help, as I do not understand yet how to get glyph by it's id from an extracted font. I do not see relevant numbers to what I see in FontForge.

**Comment by JorjMcKie** [comment]
Yes, that suggested change would return strings "tehiso", "alifiso" instead of glyph numbers and "backslash" as the character instead of the unicode.
