### ISSUE TITLE
Incorrect span grouping when using doc.getText

### ISSUE THREAD

**Issue by pmariglia** [pymupdf/PyMuPDF#284]
[OddText.pdf](https://github.com/pymupdf/PyMuPDF/files/3080266/OddText.pdf)

The text in the attached PDF has a weird representation when I attempt to extract it with fitz. There are whitespace characters in seemingly random places and the lines/spans are incorrect as a result.

I was wondering if this is a problem with fitz, or the PDF itself.

If it is the PDF - is there anything that can be done to allow this to be processed properly?

Thanks.

**Comment by JorjMcKie** [comment]
ok, I will look at it.
In the meantime please tell me your technical details (OS, platform, bitness, PyMuPDF version, etc.)

Have you look at the output of muPDF's command line utility ``muconvert`` (or ``mutool convert`` choosing html output? This should provide a first glimpse at the issue's extent.

**Comment by pmariglia** [comment]
OS/Platform/Bitness: Linux 64-bit (Ubuntu Desktop 16.04)
PyMuPDF version: 1.14.13

I am not familiar with `mutool convert`, but looking at the docs page [here](https://mupdf.com/docs/manual-mutool-convert.html) it doesn't seem to have an HTML output.

I did look at the output of [mutool trace](https://mupdf.com/docs/manual-mutool-trace.html) which I am more familiar with. The output of mutool trace is missing whitespace characters - which may be related.

**Comment by JorjMcKie** [comment]
well, I did it.
The output looks failry screwed up - here is a snippet:

![grafik](https://user-images.githubusercontent.com/8290722/56159547-f8782c80-5f92-11e9-9c38-5bef1904bd01.png)

Hard to tell what is going on there. Looks like the creator used some special font program (for whatever reason) that let the page look allright as PDF, but everyone else has a problem.

Depending on what you actually need the text output for, there are a few more options available instead of using the dictionary output of `getText`:
* You could try `getTextWords`. This delivers a list of "words" together with their respective rectangle.
* Then sort this list by those rectangles and glue the words together again that follow each other on the same line (i.e. y-coordinate).

When I do that, the output again looks weird at first:

```python
>>> words = doc[0].getTextWords()
>>> for i in range(10):
	print(words[i])

(x0, y0, x1, y1, "word", ...)
(458.94439697265625, 81.37550354003906, 477.1954040527344, 93.09021759033203, 'DEL', 0, 0, 0)
(483.9671325683594, 81.37550354003906, 496.4271545410156, 93.09021759033203, 'XE', 0, 0, 1)
(499.1078186035156, 81.37550354003906, 505.33782958984375, 93.09021759033203, 'P', 0, 0, 2)
(511.99749755859375, 81.37550354003906, 525.6343383789062, 93.09021759033203, 'OP', 0, 0, 3)
(531.8456420898438, 81.37550354003906, 550.8812866210938, 93.09021759033203, 'RTY', 0, 0, 4)
(477.00860595703125, 81.37550354003906, 483.7523193359375, 93.09021759033203, 'U', 0, 1, 0)
(505.2257385253906, 81.37550354003906, 511.9694519042969, 93.09021759033203, 'R', 0, 2, 0)
(525.55029296875, 81.37550354003906, 531.7802734375, 93.09021759033203, 'E', 0, 3, 0)
(102.92066192626953, 114.45761108398438, 109.79428100585938, 129.05789184570312, 'T', 1, 0, 0)
(117.78163146972656, 114.45761108398438, 128.28892517089844, 129.05789184570312, 'IS', 1, 0, 1)
>>> 
```
So, instead of getting a decent "DELUXE PROPERTY", you get "DEL XE P OP RTY U R E" as the first 8 "words" in the first line (which is located at height 81.375). But if you sort these 8 pieces by ascending x0 coordinate, you get "DEL U XE P R OP E RTY". If you then glue together adjacent words where ending coordinate x1 is equal or greater start coordinate x0 of the next word, you should be successful and get something readable.
For example, "U" starts at 477.009, and "DEL" ends at 477.195. So you would build "DELU", etc.

**Comment by pmariglia** [comment]
Thanks, that will be helpful!

I have no idea what the original creator used to generate this PDF, but I agree it is quite odd.

So outside of a custom word/span generation it could not be resolved directly using fitz/mupdf?

What I find interesting is that when this file is opened in a PDF viewer (Ubuntu's default document viewer Evince) the text is searchable. For example using cntrl+f and typing `deluxe property` will result in the text being found, despite the text not being identifiable by fitz.

Would you have any idea what is going on here?

**Comment by JorjMcKie** [comment]
The following little script comes already close to the original text:

```python
from operator import itemgetter
from itertools import groupby
import fitz

doc = fitz.open("OddText.pdf")
page = doc[0]  # we want text from this page

rect = page.rect

"""
Get all words on page in a list of lists. Each word is represented by:
[x0, y0, x1, y1, word, bno, lno, wno]
The first 4 entries are the word's rectangle coordinates, the last 3 are just
technical info (block number, line number, word number).
"""
words = page.getTextWords()

# the following sub-list could help detecting left and right column
# of the original page
mywords = [w for w in words if fitz.Rect(w[:4]) in rect]
mywords.sort(key=itemgetter(1, 0))  # sort by y0, x0 of the word rect
group = groupby(mywords, key=itemgetter(1))

for y0, gwords in group:  # for each line do this:
    text = ""
    x1_old = 0
    for w in gwords:
        r = fitz.Rect(w[:4])
        if r.x0 > x1_old + 2:  # allow small error (like 2)
            text += " " + w[4]
        else:
            text += w[4]
        x1_old = r.x1

    print(text)
```

**Comment by JorjMcKie** [comment]
Well, some PDF readers can swallow the toad, others cannot, I suppose.

BTW you could do the above with the "raw" of dictionary output just as well.
This method is just more convenient for the purpose - no hazzle climbing your way down through the dict structure ...

**Comment by pmariglia** [comment]
That script will work! Thanks for your help.

Will close.

**Comment by JorjMcKie** [comment]
Actually, there is no white space problem at all. It's just that the text is physically stored in a different way as you would expect it being readable. E.g. the first line is stored as
``[(D)-4(E)-5(L)-725(XE)-287(P)-713(O)-15(P)-665(R)-19(T)-19(Y)7909(U)-2299
(R)-1454(E)]``

Text in ``(brackets)`` is the text to be shown. The numbers in between modify the position relative to the previous text piece. So the line does not start with ``(DE)``, but the "E" is placed 4 units the **left** (-4) of its canonical position. You can see quite nicely where the weird look comes from.

**Comment by JorjMcKie** [comment]
Thanks to your inquiry, I will cover similarly odd cases with a little helper function - probably just in the documentation.
The following function will go through a page's list of words and recover them. In your example PDF it worked.

```python
def recover(words, rect):
    """ Word recovery.

    Notes:
        Method 'getTextWords()' does not try to recover words, if their letters
        do not appear in correct lexical order. This function steps in here
        and creates a new list of recovered words.
    Args:
        words: list of words as created by 'getTextWords()'
        rect: rectangle to consider (usually the full page)
    Returns:
        List of recovered words. Same format as 'getTextWords', but left out
        block, line and word number - a list of items of the following format:
        [x0, y0, x1, y1, "word"]
    """
    # build my sublist of words contained in given rectangle
    mywords = [w for w in words if fitz.Rect(w[:4]) in rect]

    # sort the words by lower line, then by word start coordinate
    mywords.sort(key=itemgetter(3, 0))  # sort by y1, x0 of word rectangle

    # build word groups on same line
    grouped_lines = groupby(mywords, key=itemgetter(3))

    words_out = []  # we will return this

    # iterate through the grouped lines
    # for each line coordinate ("_"), the list of words is given
    for _, words_in_line in grouped_lines:
        for i, w in enumerate(words_in_line):
            if i == 0:  # store first word
                x0, y0, x1, y1, word = w[:5]
                continue

            r = fitz.Rect(w[:4])  # word rect

            # Compute word distance threshold as 20% of width of 1 letter.
            # So we should be safe joining text pieces into one word if they
            # have a distance shorter than that.
            threshold = r.width / len(w[4]) / 5
            if r.x0 <= x1 + threshold:  # join with previous word
                word += w[4]  # add string
                x1 = r.x1  # new end-of-word coordinate
                y0 = max(y0, r.y0)  # extend word rect upper bound
                continue

            # now have a new word, output previous one
            words_out.append([x0, y0, x1, y1, word])

            # store the new word
            x0, y0, x1, y1, word = w[:5]

        # output word waiting for completion
        words_out.append([x0, y0, x1, y1, word])

    return words_out

```
