### ISSUE TITLE
Different view behaviour from GOTO and GOTOR links

### ISSUE THREAD

**Issue by sam-armstrong0** [pymupdf/PyMuPDF#2842]
## Describe the bug 
When inserting a link of kind `fitz.LINK_GOTO` the `"to"` item takes a `fitz.Point(x,y)` as the left and top components of the destination view. These are specified from a coordinate system from the top left corner of the page (as with everything else fitz).

The link kind `fitz.LINK_GOTOR` for external links take the same `"to"` item in the dictionary, but it seems the coordinate system is specified from the bottom left corner.

## To Reproduce
```python
import fitz

pdf1 = "path_to_your_pdf_with_atleast_2_pages"
pdf2 = "path_to_another_pdf_with_atleast_2_pages"

# Define the clickable area for the 2 links
rect1 = fitz.Rect(50, 300, 150, 400) # Internal
rect2 = fitz.Rect(200, 300, 300, 400) # External

# Aim to view the top left corner 100 points in
to = fitz.Point(100, 100)
zoom = 4.00 # 400%

# Make internal link to page 2
int_link_dict = {
    "kind": fitz.LINK_GOTO,
    "from": rect1,
    "page": 1, #page2
    "to": to,           # This is as expected. 100 points in from top left corner
    "zoom": zoom
}

# Make external link to page 2
ext_link_dict = {
    "kind": fitz.LINK_GOTOR,
    "from": rect2,
    "file": pdf2,
    "page": 1, #page2
    "to": to,           # This ends up being 100 points in from the BOTTOM left corner of page 2
    "zoom": zoom
}

doc = fitz.open(pdf1)
page = doc[0]

# Create the internal link with a green rect
annot = page.add_rect_annot(int_link_dict["from"])
annot.set_colors(fill=(0,1,0))

annot.update()
page.insert_link(int_link_dict)

# Create the external link with a red rect
annot = page.add_rect_annot(ext_link_dict["from"])
annot.set_colors(fill=(1,0,0))
annot.update()
page.insert_link(ext_link_dict)

doc.saveIncr()
doc.close()
```

## Expected behavior
I believe the destination view should act the same when given the same `"to"` and `"zoom"` items for both type of links. Should the GOTOR link also use the coordinates starting at the top left?

## My configuration
 - Win10 64bit
 - Python 3.11.1 64bit
 - PyMuPDF 1.23.6, installation method pip.
 - PyMuPDF 1.23.6: Python bindings for the MuPDF 1.23.5 library.
 - Version date: 2023-11-06 00:00:01.
 - Built for Python 3.11 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
Your observation is correct, and this works as designed and intended:

For knowing the coordinates of the top-left (100,100) location one needs the page height (and maybe even the page rotation).
Target PDFs referenced by GOTOR however **_deliberately_** are never opened in order to find these things out. And such a behavior wouldn't make sense either, because specifying a GOTOR link must be possible even when the referenced file is unavailable.

This means, that your specification is accepted as is.

**Comment by sam-armstrong0** [comment]
That makes sense. Like you said, to get the same page view for GOTOR links, I will have to open the destination doc and check the page height in my code.

Thanks for the quick feedback and all the team's hard effort on this project!
