### ISSUE TITLE
Highlight multiple lines

### ISSUE THREAD

**Issue by arthur-b-renaud** [pymupdf/PyMuPDF#285]
Hi ! Thank you for the good job at mupdf !!

I tried to mess around with the API, but I'm not able to hightlight multiple lines of text, using : 
page.addHighlightAnnot(rl) # Feeding rl a list of Quads

Does the current implementation support this ? 

Many thanks in advance,
Arthur

**Comment by JorjMcKie** [comment]
Hi,

thanks for your interest.
No, I'm afraid not. It always is along one straight line (which need not be horizontal).
You must use separate annots for separate highlighted areas.

**Comment by JorjMcKie** [comment]
Exactly!
Why don't you write something on the Wiki pages of the repo?
Or even better, or both:
Submit a PR for the documentation, [this](https://pymupdf.readthedocs.io/en/latest/faq/#how-to-add-and-modify-annotations) chapter. the "source" code of the docu can be found [here](https://github.com/pymupdf/PyMuPDF-Optional-Material/blob/master/docs/faq.rst).

**Comment by arthur-b-renaud** [comment]
Sure ! Let us finish and test it thoroughly and we will add a new "recipe" in the Wiki ! 

Best,
Arthur

**Comment by pluieciel** [comment]
Hi @JorjMcKie and arthur-b-renaud,

Thanks a lot for your work and detailed instruction!

Just for confirmation, after the for-loop, the highlight boxes are still seperated, right?
I just tried and cannot get a one-block multi-line highlight box, which is my need.
If that is the case, I should wait for the next version.

Thanks again!
Best,
P

**Comment by JorjMcKie** [comment]
@pluieciel - this version now supports what you can ever get from text marker annotations in a PDF!
Following snippet finds and highlights a string spread across 2 lines with **one** annot. The annot rectangle is also drawn for demo purposes:

```python
>>> import fitz
>>> doc=fitz.open("v110-changes.pdf")
>>> p=doc[0]
>>> t="this solely depends on how the image"
>>> ql = p.searchFor(t)
>>> a = p.addHighlightAnnot(ql)
>>> p.drawRect(a.rect)
Point(86.4762191772461, 247.7672119140625)
>>> soc.saveIncr()
>>> 
```
![grafik](https://user-images.githubusercontent.com/8290722/62859856-6f68cc00-bccc-11e9-99e9-951fc4eeb9e9.png)

This is the best what PDF (**not** MuPDF or PyMuPDF) can do.

**Comment by boan-anbo** [comment]
> @pluieciel - this version now supports what you can ever get from text marker annotations in a PDF!
> Following snippet finds and highlights a string spread across 2 lines with **one** annot. The annot rectangle is also drawn for demo purposes:
> 
> ```python
> >>> import fitz
> >>> doc=fitz.open("v110-changes.pdf")
> >>> p=doc[0]
> >>> t="this solely depends on how the image"
> >>> ql = p.searchFor(t)
> >>> a = p.addHighlightAnnot(ql)
> >>> p.drawRect(a.rect)
> Point(86.4762191772461, 247.7672119140625)
> >>> soc.saveIncr()
> >>> 
> ```
> 
> ![grafik](https://user-images.githubusercontent.com/8290722/62859856-6f68cc00-bccc-11e9-99e9-951fc4eeb9e9.png)
> 
> This is the best what PDF (**not** MuPDF or PyMuPDF) can do.

Thanks for the tips! Is there a way to remove the black borderline?

**Comment by MartinThoma** [comment]
@JorjMcKie I would like to highlight all text I have [to solve this problem](https://stackoverflow.com/q/63494812/562769). Can you tell me how to do that?

**Comment by JorjMcKie** [comment]
I have posted this answer on StackOverflow:

> With PyMuPDF you can easily remove all text as is required for @ypnos' suggestion.
> As an alternative, with PyMuPDF you can also check whether text is hidden in a PDF. In PDF's relevant "mini-language" this is triggered by the command 3 Tr ("text render mode", e.g. see page 402 of https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf). So if all text is under the influence of this command, then none of it will be rendered - allowing the conclusion "this is an OCR'ed page".

To implement removal of all text, use something like this snippet
```python
page.cleanContetns()  # performs syntax cleaning of page appearance commands
xref = page.getContents()[0]  # xref of the cleaned command source (bytes object)
cont = doc.xrefStream(xref)  # read it
ba_cont = bytearray(cont)  # a modifyable version
pos = 0
changed = False  # switch indicates changes
while pos < len(cont) - 1:
    pos = ba_cont.find(b"BT\n", pos)  # begin text object
    if pos < 0: break  # not (more) found
    pos2 = ba_cont.find(b"ET\n", pos)  # end text object
    if pos2 <= pos: break  # major error in PDF page definition!
    ba_cont[pos:pos2+2] = b""  # remove text object
    changed = True
if changed:  # we have indeed removed some text
    doc.updateStream(xref, ba_cont)  # write back command stream w/o text
```

**Comment by JorjMcKie** [comment]
In a similar way as in previous post, you can search for the command ``b"3 Tr\n"`` in ``cont`` between any pair of  ``b"BT\n"`` and ``b"ET\n"``.

**Comment by JorjMcKie** [comment]
Yet another check may simply look for when in the command stream is the page covering image displayed:
The command for displaying the image is ``b"/imgname Do\n"``, where imgname is the image reference name, which ``item[7]`` in an entry of ``page.getImageList()``.
If after this command no more text objects occur in ``cont``, it is reasonable to assume, that the text cannot be seen.

**Comment by JorjMcKie** [comment]
@MartinThoma - could you please let me know whether any of this was helpful and what you ended up doing?

The StackOverflow user **_mkl_** mentioned several different aproaches for inserting invisible text in an OCR.
These are
1. the ``"3 Tr"`` approach which was covered by one of my previous posts
2. the "image covers all" approach, which I also mentioned before
3. the Tesseract approach, which uses an artifical font, which only draws empty glyphs - no idea how to detect this (other than detecting that all text is encoded with that font (which has a special name, "GlyphLessFont")
4. the "full transparency" approach, which uses an opacity value of 0 (which means 100% transparency) for all text. This can be detected in the ``cont``, although with some additional effort.

In order to not get lost in all this exorbitant creativity, the safest, simplest methods seems to be this idea of comparing two versions of pixmaps of each page one before and one after removed all text.

**Comment by MartinThoma** [comment]
@JorjMcKie Thank you very much for your help! I went with the "remove text" solution: https://github.com/MartinThoma/algorithms/blob/master/PDF/check_type.py - seems to work :-)

**Comment by MartinThoma** [comment]
@JorjMcKie Would it be fine for you if I edited your answer and added the code?
