### ISSUE TITLE
Issue while installing PyMuPDF through pip

### ISSUE THREAD

**Issue by riyazmuthyalapati** [pymupdf/PyMuPDF#2851]
assert os.path.isfile( devenv), f'Does not exist: {devenv}'
      AssertionError: Does not exist: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\devenv.com
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

## Your configuration (mandatory)
 - Operating system : Windows
 - Python version - 3.12.0
 - PyMuPDF version, installation method : pip install 

It was working fine for my older python version 3.8.12. I recently installed latest python version( due to some security concerns in the 3.8 version

**Comment by riyazmuthyalapati** [comment]
The exact command you used to install PyMuPDF. - pip install PyMuPDF
The full output from the install command. - 

PS C:\Users\email@address\OneDrive - Company name\GPS\QnA\privateGPT-main_1> pip install PyMuPDF==1.23.1
Collecting PyMuPDF==1.23.1
  Using cached PyMuPDF-1.23.1.tar.gz (60.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: ### Starting.
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: __name__: 'setup'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: platform.platform(): 'Windows-10-10.0.19045-SP0'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: platform.python_version(): '3.12.0'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: sys.executable: 'C:\\Users\\email@address\\AppData\\Local\\Programs\\Python\\Python312\\python.exe'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: CPU bits: 64 sys.maxsize=9223372036854775807
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: __file__: 'C:\\Users\\email@address\\AppData\\Local\\Temp\\pip-install-zj4e408s\\pymupdf_db5c1e70502f43898d8e0132cd443833\\setup.py'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: os.getcwd(): 'C:\\Users\\email@address\\AppData\\Local\\Temp\\pip-install-zj4e408s\\pymupdf_db5c1e70502f43898d8e0132cd443833'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: sys.argv (3):
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     0: 'C:\\Users\\email@address\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pip\\_vendor\\pyproject_hooks\\_in_process\\_in_process.py'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     1: 'prepare_metadata_for_build_wheel'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     2: 'C:\\Users\\RIYAZM~1.COM\\AppData\\Local\\Temp\\tmpri5gagm2'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: os.environ (61):
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     ALLUSERSPROFILE: 'C:\\ProgramData'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     APPDATA: 'C:\\Users\\email@address\\AppData\\Roaming'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     CHASSIS: 'Notebook'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_12932_LGJWLASUTQFUBXVY'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     COLORTERM: 'truecolor'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     COMMONPROGRAMFILES(X86): 'C:\\Program Files (x86)\\Common Files'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     COMMONPROGRAMW6432: 'C:\\Program Files\\Common Files'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     COMPUTERNAME: 'AZURE-8U5OIG2MP'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     COMSPEC: 'C:\\Windows\\system32\\cmd.exe'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     DRIVERDATA: 'C:\\Windows\\System32\\Drivers\\DriverData'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     FPS_BROWSER_USER_PROFILE_STRING: 'Default'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     HOMEDRIVE: 'C:'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     HOMEPATH: '\\Users\\email@address'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     IGCCSVC_DB: 'AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA2pmHx3TkrUOLVPIe7JHx6gQAAAACAAAAAAAQZgAAAAEAACAAAAAU6+7Jo3AY7Fn6xbBC3MDg1qx6ljYrsXfOkSf6gEs/oAAAAAAOgAAAAAIAACAAAAAD0QXNbmhtZkjU6PqFb8efN94fv9g2YPOu9SafxMZNi2AAAAALUrNcP/vs3KEmUvgl0FvhoDd9fG9PKTCC0DOmOSpNgKwAOFXH88i0r0NvUQEs7a8YKh31npTPLqjyogZZSd8B4ey/w+v8EOcATAD9M+vMC54Z1l8zJ/DX49XGb3H4PmRAAAAAPmghaVO4Lr+iCrYN9Z/ELT0gu2zvQ9+jwsAsyQintKL6Icb9vcpRlL7tJZel5ZSnlg5WAmTEjAw3skBHcBMhjw=='
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     LANG: 'en_US.UTF-8'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     LOCALAPPDATA: 'C:\\Users\\email@address\\AppData\\Local'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     LOGONSERVER: '\\\\AZURE-8U5OIG2MP'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     MODEL: '5570'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     NEXTHINK: 'C:\\Program Files\\Nexthink\\Collector'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     NUMBER_OF_PROCESSORS: '20'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     ONEDRIVE: 'C:\\Users\\email@address\\OneDrive - Company name'   
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     ONEDRIVECOMMERCIAL: 'C:\\Users\\email@address\\OneDrive - Company name'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     OS: 'Windows_NT'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PATH: 'C:\\Users\\email@address\\AppData\\Local\\Temp\\pip-build-env-95_n_pc3\\overlay\\Scripts;C:\\Users\\email@address\\AppData\\Local\\Temp\\pip-build-env-95_n_pc3\\normal\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Users\\email@address\\.cargo\\bin;C:\\Users\\email@address\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\;C:\\Users\\email@address\\AppData\\Local\\Programs\\Python\\Python312\\;C:\\Users\\email@address\\OneDrive - Company name\\GPS\\Servicenow\\Scripts\\;C:\\Users\\email@address\\OneDrive - Company name\\GPS\\Servicenow\\;C:\\Users\\email@address\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\email@address\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PEP517_BACKEND_PATH: 'C:\\Users\\email@address\\AppData\\Local\\Temp\\pip-install-zj4e408s\\pymupdf_db5c1e70502f43898d8e0132cd443833'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PEP517_BUILD_BACKEND: 'setup'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PIP_BUILD_TRACKER: 'C:\\Users\\email@address\\AppData\\Local\\Temp\\pip-build-tracker-io6cr8ar'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PROCESSOR_ARCHITECTURE: 'AMD64'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 154 Stepping 3, GenuineIntel'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PROCESSOR_LEVEL: '6'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PROCESSOR_REVISION: '9a03'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PROGRAMDATA: 'C:\\ProgramData'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PROGRAMFILES: 'C:\\Program Files'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PROGRAMFILES(X86): 'C:\\Program Files (x86)'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PROGRAMW6432: 'C:\\Program Files'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PSMODULEPATH: 'C:\\Users\\email@address\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PUBLIC: 'C:\\Users\\Public'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PYTHONNOUSERSITE: '1'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     PYTHONPATH: 'C:\\Users\\email@address\\AppData\\Local\\Temp\\pip-build-env-95_n_pc3\\site'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     SERIAL: '4DKXSQ3'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     SESSIONNAME: 'Console'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     SYSTEMDRIVE: 'C:'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     SYSTEMROOT: 'C:\\Windows'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     TEMP: 'C:\\Users\\RIYAZM~1.COM\\AppData\\Local\\Temp'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     TERM_PROGRAM: 'vscode'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     TERM_PROGRAM_VERSION: '1.84.2'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     TMP: 'C:\\Users\\RIYAZM~1.COM\\AppData\\Local\\Temp'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     TYPE: 'Precision'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     USERDNSDOMAIN: 'AP.LILLY.COM'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     USERDOMAIN: 'AP'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     USERDOMAIN_ROAMINGPROFILE: 'AP'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     USERNAME: 'L045139'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     USERPROFILE: 'C:\\Users\\email@address'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     VSCODE_INJECTION: '1'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     VSCODE_NONCE: '4fc64e4c-a4ce-4f2b-a373-7075c7dc5078'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     WINDIR: 'C:\\Windows'
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py:     ZES_ENABLE_SYSMAN: '1'
      pipcl.py: build_wheel():  wheel_directory='C:\\Users\\email@address\\AppData\\Local\\Temp\\pip-modern-metadata-2gvdh25t' config_settings=None metadata_directory=None
      pipcl.py: _call_fn_build(): calling self.fn_build=<function build at 0x0000026A2BCBB7E0>
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: skeleton=None
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: PYMUPDF_SETUP_MUPDF_BUILD=None
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: mupdf_tgz already exists: C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833\mupdf.tgz
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: Extracting C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833\mupdf.tgz
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: Copying C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833/fitz/_config.h to C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833\mupdf-1.23.0-source/include/mupdf/fitz/config.h.
      pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py: C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833\mupdf-1.23.0-source/include/mupdf/fitz/config.h: os.stat_result(st_mode=33206, st_ino=2251799814477292, st_dev=2461237825758205503, st_nlink=1, st_uid=0, st_gid=0, st_size=5686, st_atime=1701322495, st_mtime=1692873956, st_ctime=1701322490) mtime=2023-08-24-10:45:56     
      Traceback (most recent call last):
        File "C:\Users\email@address\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\email@address\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\email@address\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833\pipcl.py", line 
579, in build_wheel
          items = self._call_fn_build(config_settings)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833\pipcl.py", line 
731, in _call_fn_build
          ret = self.fn_build()
                ^^^^^^^^^^^^^^^
        File "C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py", line 
687, in build
          mupdf_build_dir = build_mupdf_windows( mupdf_local, env_extra, build_type)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833\setup.py", line 
816, in build_mupdf_windows
          vs = pipcl.wdev.WindowsVS()
               ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\email@address\AppData\Local\Temp\pip-install-zj4e408s\pymupdf_db5c1e70502f43898d8e0132cd443833\wdev.py", line 8          assert os.path.isfile( devenv), f'Does not exist: {devenv}'
      AssertionError: Does not exist: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\devenv.com
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.






----------------------------
also, devenv.com is not available in this path(C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\devenv.com). I checked it..

**Comment by julian-smith-artifex-com** [comment]
I'm closing this as "won't fix", because we only fix bugs that in the most recent release (currently PyMuPDF-1.23.7, released a few hours ago).
