### ISSUE TITLE
Can getToC work more accurately for page numbers?

### ISSUE THREAD

**Issue by yinkaisheng** [pymupdf/PyMuPDF#286]
Currently the page numbers returned by getToC always are int.
But it is not accurate because a bookmark may actually point to a middle position of a page.
Is it possible to return float page numbers for more accuracy? Such as 4.0, 5.51.

**Comment by JorjMcKie** [comment]
If you read the resp. part of the documentation, you will find an option that can be passed to getToC.
If you specify ``doc.getToC(False) you will get an additional item for each TOC entry which contains a link destination. Use this to determine your required info.

**Comment by yinkaisheng** [comment]
Thanks a lot.
doc.getToC(False) works for me.

**Comment by JorjMcKie** [comment]
Pleased to hear this.
Have fun with PyMuPDF!

**Comment by JorjMcKie** [comment]
BTW:
When the page number in getToC is <1, then this destination should contain a pointer to some place outside the current document (another file or a web address).
