### ISSUE TITLE
find_tables function is not working as expected.

### ISSUE THREAD

**Issue by sachinanand** [pymupdf/PyMuPDF#2865]
find_tables function is treating paragraph text as table text. In the attached file, on page 2 there is no table however, the find_table method extracts 1 table with following content

[['Hyperthyroidism is'], ["attributed in large part to Grave's disease. While PTD is single most common endocrine"]]

[table_overlap.pdf](https://github.com/pymupdf/PyMuPDF/files/13544251/table_overlap.pdf)

To reproduce the bug:

```
doc = fitz.open(document_path, filetype="pdf")
 for count, page in enumerate(doc):
     extracted_tables = plumber_page.find_tables().tables
     for table in extracted_tables:
                print("extracted words", table.extract())
```

I am Windows 10 with Python 3.8.10

**Comment by JorjMcKie** [comment]
There is no way to prevent these types of false positives.
The same recognition also happens with other packages, btw.

The problem in table recognition is to find enough criteria to **_recognize_** - as opposed to exclude criteria which may (or may not) betray the presence of a table.

In your case, there are two invisible, unsolicited white rectangles under the visible text. I have marked them in the following image:
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/2bf6c6d1-9958-46bc-bf88-d6ee326855a3)

**Comment by JorjMcKie** [comment]
Please also compare to #2814.

**Comment by sachinanand** [comment]
Ok. Thanks for investigating this @JorjMcKie . I understand that this can never be 100% accurate.
