### ISSUE TITLE
What is the best way to make a transparent text background(ignore background color)?

### ISSUE THREAD

**Issue by yinkaisheng** [pymupdf/PyMuPDF#287]
I'm using page.getPixmap to render pdf. 
I draw a custom background before I draw the pixmap.
I also draw a selection text background before I draw the pixmap.
But some pdfs may have a background color under some texts.
It covers my custom background and selection. 
Does I need to use getText('dict') and draw all the texts respectively by myself?

The following picture shows that the center texts have a white background and it covers my gray background.
The page svg has a white path:
```xml
<path transform="matrix(1,0,0,-1,65.16,577.2)" d="M 0 0 L 378 0 L 378 510 L 0 510 Z " fill="#ffffff"/>
```

![image](https://user-images.githubusercontent.com/5846696/56625234-f0914a00-666e-11e9-8b60-2e7eafc3ef00.png)

**Comment by JorjMcKie** [comment]
How did you create the pixmap?
There is an option "alpha" which can be used to make a transparent pixmap (alpha=True).
But if the pixmapped page has intransparent parts, that won't help.
Other than that I know no easy way to get over this hurdle ...

**Comment by yinkaisheng** [comment]
I'm sure I got the pixmap with alpha=True(default is True).
Only a part of the pdf is not transparent, other parts are all transparent.
Now I know It's not easy to do that.
Thank You.
