### ISSUE TITLE
Error in Skeleton for Named Link Destinations

### ISSUE THREAD

**Issue by JorjMcKie** [pymupdf/PyMuPDF#2886]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Named link destinations do not work after update/insert.

## To Reproduce (mandatory)
Obvious: even when specifying a correct, existing name in the PDF and preparing a correct link dictionary, the link is not working.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
All configurations

**Comment by julian-smith-artifex-com** [comment]
Fixed in PyMuPDF-1.23.8.
