### ISSUE TITLE
There doesn't seem to be any way to get ActualText values 

### ISSUE THREAD

**Issue by stevesimmons** [pymupdf/PyMuPDF#2889]
## Describe the bug (mandatory)

I have an externally generated PDF where words like "so**rt**" and "o**ffi**ce" have ligature-like groups of letters wrapped in `ActualText`. 

Here is the "rt" in "sort" in the source PDF:

```
/Span<</ActualText (rt) >> BDC
8.0101776 0 Td <92> Tj
EMC
```

PyMyPDF's `page.get_text()` extracts them as the unicode replacement character �.  The original characters appear to be not recoverable, even with the "xml" or "rawdict" extraction options.

## To Reproduce (mandatory)

Try `page.get_text()` to extract text including the `/ActualText` span above. Get back "�".

## Expected behavior (optional)

It would be great to have an option like TEXT_PRESERVE_ACTUALTEXT that returns the ActualText value "rt" (in the above example) rather than the replacement <92>.

## Your configuration (mandatory)
 - Operating system: Linux, Ubuntu
 - Python version: 3.11.4
 - PyMuPDF version: 1.23.2, wheel

**Comment by JorjMcKie** [comment]
see #2876

**Comment by JorjMcKie** [comment]
This issue has been resolved with version 1.23.14.
