### ISSUE TITLE
Copy partial pages to new PDF file

### ISSUE THREAD

**Issue by bschollnick** [pymupdf/PyMuPDF#289]
I've been asked to segment some PDF files, but the segments are scattered across multiple pages, so each page may have 1 or more segments in it...

eg. Chapter 2 may start in the middle of a page

Now, I've been forced to identify these breaks by the header (getPageText("html"), since some of the headers are also in the normal body text, and the font size is the only dependable indicator...

So, I have access to the HTML and the images in the PDF file...

I was thinking that I could "chunk" this better, but forcing page breaks between the segments, and even maybe making the segments into separate files... (I do this split to separate files right now, but I still have the end of the previous segment)

But I don't see any way to take a segment of the HTML and copy it to a separate file via pyMuPDF?  

eg...

text text text of chapter 2 
text text text of chapter 2 
text text text of chapter 2 
text text text of chapter 2 
text text text of chapter 2 (Page 2)

Chapter 3  (Page 2)

text text text of chapter 3 (Page 2)
text text text of chapter 3
text text text of chapter 3
text text text of chapter 3

page = doc.loadPage(2)
html_page = page.getPageText("HTML")
html_page = html_page.split("Chapter 3")[1]  # only return html for chapter 3

Can convert_toPDF work with the HTML code that Fitz gives us?

If not, is there any way to manipulate fitz to allow us to split a page at an arbitrary place?
(eg. Insert Page break at the Chapter 3 header? Reflowing would *NOT* necessarily be necessary..  Nice, but white space is something that should be acceptable..)

That probably would be the easier and better way to do this, since it would allow just copying the document by pages....

**Comment by JorjMcKie** [comment]
Hm, a looong question, and I don't know, where exactly to start my answer. Maybe, from ground up:
1. Yes, you can use ``doc.convertToPDF`` for every document type (except PDF) supported. This includes HTML, EPUB, XPS, ... and all supported image files,
2. Yes you can take arbitrary parts of a given PDF page and show them on arbitrary places of another PDF page.

Taking the bottom part of your inquiry: if you are able to locate a part of a given PDF page, then specify a rectangle that encloses this area and include it on another PDF page.
**Locating** interesting parts could be done by using text search for example:
* Search for the words "stuff-starts-here" and "stuff-ends-here". Assume r1 is the rectangle where you find the first text, and r2 the one of the second.
* Take top-left point of the first, and bottom-right point of the last search items' rectangles and form a new rectangle ``rect = fitz.Rect(r1.tl, r2.br)``.
* Then, for the page of the target PDF ``target_page``, do this: ``target_page.showPDFpage(target_rect, src, n, clip=rect)``, where target_rect is the rectangle, where the selected part of the source document page (``src[n]``) should appear.

And of course, you can make the target PDF make such, that it has the size of the source (clip) rectangle if that's an interesting aspect. Or, you can also show several input rectangles collectively on the same out output page, of course. All this is fully flexible.

Needless to mention, that your source PDF ``scr`` could have been the result of an input HTML - if that is a question at all.
How god (Py-) MuPDF actually is at that specific job of HTML-to-PDF conversion is another question and remains to be tested in a concrete scenario ...

All this make any sense to you?

**Comment by bschollnick** [comment]
Okay, I started with trying direct HTML manipulation....  I'm attaching the code, and PDF file that I am using..

Exporting the HTML, and then using the "convert any document to PDF" workflow doesn't seem to work for HTML?

https://pymupdf.readthedocs.io/en/latest/faq/#how-to-convert-any-document-to-pdf

[test_output.pdf](https://github.com/pymupdf/PyMuPDF/files/3116698/test_output.pdf)
[applicoinc.com-What Happened to CurrentC When Platform Innovation Fails.pdf](https://github.com/pymupdf/PyMuPDF/files/3116699/applicoinc.com-What.Happened.to.CurrentC.When.Platform.Innovation.Fails.pdf)

`
import fitz
from io import BytesIO

test_file = r"/Volumes/Support/Support/Dropbox/pdfs/applicoinc.com-What Happened to CurrentC When Platform Innovation Fails.pdf"

doc = fitz.open(test_file)
page = doc.loadPage(0)
html_text = page.getText("html")

#with open("test_page1_out.pdf", "w") as output_file:
new = fitz.open()

with open("temp.html", "w") as output:
    output.writelines(html_text)

doc = fitz.open("temp.html")

b = doc.convertToPDF()                      # convert to pdf
pdf = fitz.open("pdf", b)                   # open as pdf

# save the conversion result
pdf.save("test_output" + ".pdf", garbage=4, deflate=True)
`

The code above is causing a unrecognizable PDF...?  I'm not sure if it's something I'm missing or just not being able to handle the html..?

--------------

Now going with the rectangle idea, I did see that in the docs, but I'm unclear on how to identify from the HTML the coordinates for the rectangles?  Am I missing something here?  

Looking closer at the docs, I could (in theory) use:

You can find out, exactly where on a page a certain text string appears:

>>> areas = page.searchFor("mupdf", hit_max = 16)

Except for false positives.  For example, let's say I use the keyword chapter.

>>> areas = page.searchFor("chapter", hit_max = 5)

I'm looking for "Chapter", as a header (eg font size 12.xx), where there are "chapter" in the body text as well (Font size 6, I believe).  I don't see a way to distinguish between the two via searchFor.  (That's why I had to go down to HTML, so that I could make a regex that also checked for Font sizes)

**Comment by JorjMcKie** [comment]
ok, let's forget the HTML path for the moment.
I have also ... let's say ... mixed experience with that file type in MuPDF.

Why not try the following:
Make a list of words on the page via ``page.getTextWords()``. Every item in the returned list contains one word on the page. The term _word_ in this context means a string of non-space contiguous bytes. It looks like

```python
worditem = [x0, y0, x1, y1, "word", ...]
```
where "word" is the actual text of the word and the first 4 floats are the bbox of the word's location. If you set ``wordrect = fitz.Rect(worditem[:4])``, then wordrect.height is (at least) an **indicator** of the fontsize: should be a value between fontsize * 1.25 and fontsize * 1.4.

If you need the exact value of the fontsize, you can use ``page.getText("dict")`` and figure this value out from there.

**Comment by bschollnick** [comment]
Ah.  

I see, somehow I missed the fact that getTextWords returns the 4 coords..  

So, I could simply use the Y coords to estimate the fonts size, and I could also use the Ymax and Ymin as a border for the segmenting of the file...

I'll test that out and let you know how that works...  

Once again, thanks for the library, and for the fast turn around.  I know my questions can be quite challenging at times....

**Comment by JorjMcKie** [comment]
That was quick!
Challenging? By no means! On the contrary: you have a way to exactly describe what you want ...

Please be aware the the sequence of those word items are not necessarily in any "natural" reading order. Shouldn't be an issue for your current use case though ...
Other, you can sort that list obviously ...

In the last 2 weeks or so, I came across nasty PDFs, where the creator was inventive enough to spread single letters of words across the page's text definitions. So, every viewer displays the PDF as a harmless animal, but (almost all) text extractions produce garbled words.
If that should ever be your problem, remember to look at #288 for a solution ...
The script shown there also contains a search function based on `getTextWords()` output ...

Didn't you - sometime earlier - have a problem with unreadable old PDFs?

**Comment by bschollnick** [comment]
> Didn't you - sometime earlier - have a problem with unreadable old PDFs?
> 

Yep.  

We haven’t been able to find a PDF that we can clear for review…  Since we’re working in HIPAA regulated space…  

> That was quick!
> Challenging? By no means!
> 

I was trying to refer to my earlier issues..  
> On the contrary: you have a way to exactly describe what you want ...
> 
But thank you…

> Please be aware the the sequence of those word items are not necessarily in any "natural" reading order. Shouldn't be an issue for your current use case though ...
> Other, you can sort that list obviously ...
> 
> In the last 2 weeks or so, I came across nasty PDFs, where the creator was inventive enough to spread single letters of words across the page's text definitions. So, every viewer displays the PDF as a harmless animal, but (almost all) text extractions produce garbled words.
> If that should ever be your problem, remember to look at #288 <https://github.com/pymupdf/PyMuPDF/issues/288> for a solution ...
> The script shown there also contains a search function based on getTextWords() output ...
> 
I’ll keep that in mind…  

And again, Thanks…
	
	- Benjamin

**Comment by bschollnick** [comment]
If possible, as a feature request…

* getTextWords gives us every word that is on the page, which at least in this case, is a lot of spam that I have to filter through

A getTextWord(word_to_scan_for) where it would return only items related to what I am searching for would be nice…
(Please keep in mind, scanning for an entire string would be better in my case, because of the potential for false positives).

	- Benjamin

**Comment by bschollnick** [comment]
Maybe never mind?  I missed SearchPageFor and SearchPage…!  I’m testing those right now…

	- Benjamin

**Comment by JorjMcKie** [comment]
Let me challenge this request a bit:

1. The full list ``page.getTextWords()`` can be sub-selected by everyone for the interesting stuff. Doing it by oneself would also be more flexible b/o potentially using regular expressions, upper/lower case selections, etc.
2. As I mentioned previously, there is the potential of garbled words in mal-created PDFs in the first stage. So point 1 would only make sense **after** a cleaned-up list of words has been created. This in turn has a negative effect on the overall performance. Which I wouldn't like to have: after all this whole method only exists for having a top performance option to get position info (otherwise, the dictionary text extraction has the same and more information).
3. Returning other than single strings with no interspersed white space is just outside the scope of the method.
4. There also exists method ``page.getTextBlocks()``. Very similar, but returnes text **blocks**. Same list structure, but the 5th item is a concatenation of lines belonging to the same block. The height of the bbox accompanying this would have to be divided by the number of occurrences of string ``\n`` + 1, in order to get this fontsize approximation. Obviously, arbitrary strings could be looked up  here - not just white-space-free ones.
5. And finally again ``page.getText("dict")``. It also delivers blocks (the same as in previous), but subdivided in single lines (with their own bbox). Each line consists of spans, which finally contain the text. Usually just one span exists. More are only created if the font or any of its attributes change with the same line. A span contains all the text of a line, for which the same font attributes apply. So you could look up your string in the spans, check the (**exact**) fontsize (or even **fontname**), and use the containing line's bbox as the required coordinate.

**Comment by bschollnick** [comment]
Okay,

Never mind, somehow I missed SearchPageFor and SearchPage… 

It’s been one of those weeks..

	- Benjamin

**Comment by JorjMcKie** [comment]
No problem - everything's fine ;-)

**Comment by bschollnick** [comment]
Looks good.  Closing this ticket, but I've run into a very *odd* error...  See new ticket.
