### ISSUE TITLE
Words ending with "ting" are wrongly extracted.

### ISSUE THREAD

**Issue by asher-stern-aquant** [pymupdf/PyMuPDF#2893]
## Describe the bug (mandatory)
In some documents, a word ending with "ting" is extracted as if it ended with "'ng" instead of "ting".

## To Reproduce (mandatory)
[Interesting.pdf](https://github.com/pymupdf/PyMuPDF/files/13672234/Interesting.pdf)

Use the attached document.
(Note: the document was created by creating a new MS-Word document, writing the word "interesting", and saving as PDF).

Run this code:
```python
filename = '/Users/astern/Temporary/Interesting.pdf'
with fitz.open(filename) as doc:
    for page in doc:
        page_dict = page.get_text('dict', sort=True)
        for block in page_dict['blocks']:
            block_text = ' '.join([' '.join([span.get('text', '') for span in line['spans']]) for line in block['lines']])
            print(block_text)
```

The printed text is:
```
Interes'ng
```

## Your configuration (mandatory)
 - Operating system: `macOS Sonoma 14.1.2`
 - Python version: `3.10.13`
 - PyMuPDF version `1.23.7`

`print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)`
```
3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ] 
 darwin 
 
PyMuPDF 1.23.7: Python bindings for the MuPDF 1.23.7 library.
Version date: 2023-11-30 00:00:01.
Built for Python 3.10 on darwin (64-bit).
```

**Comment by JorjMcKie** [comment]
The issue number on MuPDF's system is [this](https://bugs.ghostscript.com/show_bug.cgi?id=707403).

**Comment by JorjMcKie** [comment]
Our MuPDF team has reviewed the corresponding bug and determined that the file is broken. While the visible text appears to be ok, the information required to extract it is incorrect and cannot be repaired.
