### ISSUE TITLE
Create a document from stream without loading all the file stream to memory

### ISSUE THREAD

**Issue by Eliav-B** [pymupdf/PyMuPDF#2894]
I have a pdf service based on this library. I want to recieve a large pdf file as stream, and to pass this stream to a document creation. I do it with 2 documents, and then merge them to output stream using the insert_pdf() function. 
This is how i create the documents from stream: 
`fitz.open(stream=file_stream.read())`. My stream is a stream i get from flask request file. 
The problem is that it still loads the full file in the memory, and it crashes. 

Is it possible to do this pdf merging as a streamed process? If so, what is the right way? If not - can we request for it?

**Comment by JorjMcKie** [comment]
This is not and cannot ever be supported by PyMuPDF. You may want to ask MuPDF (the base library) experts in [this](https://discord.gg/CyjPq8br) Discord channel.
If there is a way, then it must be enabled by MuPDF.
