### ISSUE TITLE
find_tables  Parsing error occurred.

### ISSUE THREAD

**Issue by sonlia** [pymupdf/PyMuPDF#2897]
![image](https://github.com/pymupdf/PyMuPDF/assets/1559999/ccd3e4c2-7056-48eb-ab3e-8b947fcc9dcd)

find_table encounters parsing issues when the table is irregular and contains a large number of blank areas in between, resulting in the failure to parse the content below.

**Comment by JorjMcKie** [comment]
You did not supply important mandatory information.
Please re-enter with reproducible material like example file, code snippet, your platform and the PyMuPDF version.
