### ISSUE TITLE
insert_link() can't insert a link to the last page in a pdf document

### ISSUE THREAD

**Issue by jackb007** [pymupdf/PyMuPDF#2903]
### Description of the bug

When an attempt is made to pass a link to the insert_link method pointing to the last page in a document, an error message is returned and the program exits. This problem is caused by an off-by-one error. The fitz.Document numbering of fitz.Page objects is 0-based, while the numbering used by pdf readers is 1-based. The problem is solved by changing the following lines in the getLinkText function in the utils.py file:

1. The two occurences of the line
if lnk["page"] >= 0:
should be changed to
if lnk["page"] >= 1:

2. The line
pno = lnk["page"]
should be changed to
pno = lnk["page"] - 1

The fix was tested and is working correctly.

### How to reproduce the bug

How to reproduce the bug:
Attempt to pass a valid link to the insert_link() method pointing to the last page in a pdf document. The method will return an error message and the program will terminate.

### PyMuPDF version

1.23.7

### Operating system

Windows

### Python version

3.9

**Comment by julian-smith-artifex-com** [comment]
The "page" entry in a link dictionary is defined to be zero-based - see https://pymupdf.readthedocs.io/en/latest/page.html#description-of-get-links-entries.

So you need to pass in zero-based page numbers in `lnk["page"]`.
