### ISSUE TITLE
bbox return 'bbox': (2147483520.0, 2147483520.0, -2147483648.0, -2147483648.0)

### ISSUE THREAD

**Issue by myhloli** [pymupdf/PyMuPDF#2906]
### Description of the bug

api : page.get_text("dict") return not expected results

### How to reproduce the bug

[mcj.7.3.304.pdf](https://github.com/pymupdf/PyMuPDF/files/13702796/mcj.7.3.304.pdf)
page_id : 0 (page_id start from 0）
```
doc: fitz.Document
for page in doc:
    text_block = page.get_text("dict")
    print(text_block)
```
there is my code demo

```
{'width': 432.0, 'height': 648.0, 'blocks': [{'number': 1, 'type': 0, 'bbox': (2147483520.0, 2147483520.0, -2147483648.0, -2147483648.0), 'lines': [{'spans': [{'size': 6.0, 'flags': 4, 'font': 'Geneva', 'color': 22...
```
it return bbox value must be wrong

### PyMuPDF version

1.23.7

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
PyMuPDF by default is trying to detect some character positioning errors and potentially re-computes coordinates.
~This seems to go wrong in this case - we are analyzing the situation.~
I found the reason: The font "Geneva" contains ridiculous geometry information (ascender = descender = 3.8). We should have intercepted this and assumed reasonable, synthetic fallback values ascender = 0.8, descender = -0.2.

For now, please switch off the corrective actions by the following statement - before you extract text:
```python
fitz.TOOLS.unset_quad_corrections(True)
```
This will lead to correct coordinates in `page.get_text("dict")`.

**Comment by JorjMcKie** [comment]
The issue has been reviewed by our MuPDF team.
The result is that the font in question, "Geneva", contains errors that cannot be repaired:
For correctly extracting text, glyph boundary boxes must computed. The font does not contain the required information to do this.
