### ISSUE TITLE
Rebased version: KeyError in resolve_names when merging pdfs 

### ISSUE THREAD

**Issue by cormier** [pymupdf/PyMuPDF#2919]
### Description of the bug

KeyError when extracting page numbers in `resolve_names` for PDFs that contains actions that refers to non-existent pages

### How to reproduce the bug

```python
import fitz_new as fitz

def merge_pdf(content: bytes, coverpage: bytes):
   with fitz.Document(stream=coverpage, filetype="pdf") as coverpage_pdf, fitz.Document(
	   stream=content, filetype="pdf"
   ) as content_pdf:
	   coverpage_pdf.insert_pdf(content_pdf)
	   doc = coverpage_pdf.write()
	   return doc 

def reproduce():
	with open(f"content.pdf", "rb") as content_pdf, open(f"content.pdf", "rb") as coverpage_pdf:
		content = content_pdf.read()
		coverpage = coverpage_pdf.read()
		merge_pdf(content, coverpage)

reproduce()
```

Using: 
[content.pdf](https://github.com/pymupdf/PyMuPDF/files/13731405/content.pdf)

The following will work for the non-rebased version

### PyMuPDF version

1.23.8

### Operating system

Linux

### Python version

3.8

**Comment by julian-smith-artifex-com** [comment]
This is fixed in release candidate 1.23.9rc1; see: #2960
