### ISSUE TITLE
render quality is not as good as SumatraPDF for some pdf files.

### ISSUE THREAD

**Issue by yinkaisheng** [pymupdf/PyMuPDF#292]
I have some pdf files that PyMuPDF can render them but the quality is not as good as SamatraPDF(which is also based on MuPDF).

"Mastering Machine Learning with R(2nd).pdf" is one of the pdf files. 
[Mastering Machine Learning with R(2nd).zip](https://github.com/pymupdf/PyMuPDF/files/3123649/Mastering.Machine.Learning.with.R.2nd.zip)

I also tested some other PDF readers, below are the results for page 3.

1 The best: SumatraPDF 3.1.2
![image](https://user-images.githubusercontent.com/5846696/56846604-d3c17480-6903-11e9-873e-9198a34af9f0.png)

2 Firefox 66
the font seems a litter taller than SumatraPDF 
![image](https://user-images.githubusercontent.com/5846696/56846762-9eb62180-6905-11e9-8961-340444188de7.png)

3 PyMuPDF 1.14.13 
like Firefox, but the letter 'd' is a litter wider that 'e'
![image](https://user-images.githubusercontent.com/5846696/56846764-a83f8980-6905-11e9-903b-8d8b0714c93e.png)

4 PDF-XChangeViewer 2.5.322.8
A mess! It can't show the headline.
![image](https://user-images.githubusercontent.com/5846696/56846768-af669780-6905-11e9-92f8-f9e4d0ac3cec.png)

5 Chrome 71
Worst. Unreadable!
![image](https://user-images.githubusercontent.com/5846696/56846779-c4dbc180-6905-11e9-941d-707903117a4e.png)

For other PDF files, all of the above readers have the same render quality from my sight.

**Comment by JorjMcKie** [comment]
The difference to SumatraPDF (except for the background color, which I don't know where it comes from - neither SumatraPDF on my PC nor PyMuPDF have them) is the choice of the **_font_**.

You should take into account that, while SumatraPDF is indeed based on MuPDF, this basis is 5 years old (MuPDF v1.6!). The **current MuPDF's** own viewer (v1.14.0) displays the page exactly like PyMuPDF, 
which is to be expected and which cannot even be influenced. For some reason, current MuPDF also decides to use a non-serifed font for the display, while 5 years back it was some serifed Roman-like font.

So wrapping up: this PDF **does** impose challenges to viewers. And challenges obviously go back to the embedded fonts. There always is some degree of freedom of choice for the viewers in how they decide to render something.

The PDF also **contains errors** in their embedded fonts: confirm this with opening it using Adobe Acrobat ...

So, you really cannot blame any viewer if it doesn't recover from these errors in the best of all possible ways ... ;-)

**Comment by yinkaisheng** [comment]
OK.
Btw, the background color comes from [SumatraPDF-settings.txt](https://www.sumatrapdfreader.org/settings3.2.html)

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #c7edcc
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]
