### ISSUE TITLE
Read and Convert the attach pdf wrong!

### ISSUE THREAD

**Issue by exocrdotcom** [pymupdf/PyMuPDF#2927]
### Description of the bug

I use fitz to convert the pdf to image ,but it get wrong image, the text in the image is not in the right position.
[1.pdf](https://github.com/pymupdf/PyMuPDF/files/13739861/1.pdf)
wrong image 
![1_1](https://github.com/pymupdf/PyMuPDF/assets/71757657/9c581e94-4f40-4b28-a339-6bcb8e9c184a)

### How to reproduce the bug

def pymupdf_convert_pdf_to_image(pdfFile, save2Path, dpi=200, width=0, height=0, ext='jpg', quality=95):
    """
    pdfFile: pdf文件路径
    savePath: 解开的图形存储的路径
    dpi: resolution in dpi (default: 200)
    width: width (in pixels) (maximum width if dpi is specified)
    height: height (in pixels) (maximum height if dpi is specified)
    ext: 'jpg' or 'png'
    quality: jpg compress rate
    """
    resolution = 72
    res_specified = False

    if ext not in ['jpg', 'png']:
        raise Exception("input image format error!")

    try:
        doc = fitz.open(pdfFile)
    except Exception as e:
        print(e)
        return

    if dpi > 0:
        resolution = dpi
        res_specified = True

    q_name, pdf_name = os.path.split(pdfFile)
    h_name = os.path.splitext(pdf_name)[0]
    # 创建时间戳存储文件
    if doc.page_count > 1:
        save_path = os.path.join(save2Path, h_name)
    else:
        save_path = save2Path
    if not os.path.exists(save_path):
        os.makedirs(save_path)

    index = 1
    for pg in range(doc.page_count):
        #if pg >= 10: break
        page = doc[pg]
        #根据page的box，预先计算一下输出的图像的大小，如果超过了设定的最大宽度或者高度，则需要进行重新调整scale
        fbound = page.mediabox          #page的大小
        scale = resolution/72.0         # 此处若是不做设置，默认dpi=72
        ctm = fitz.Matrix(scale, scale)
        fbound = fbound.transform(ctm)  #计算缩放后的大小（float）
        ibound = fbound.round()         #整型大小

        w, h = width, height
        # If a resolution is specified, check to see whether w/h are exceeded; if not, unset them.
        if res_specified:
            if w > 0 and ibound.width <= w:  w = 0
            if h > 0 and ibound.height <= h: h = 0
        # Now w or h will be 0 unless they need to be enforced.
        if w > 0 or h > 0:
            fbound = page.mediabox
            scalex = w/fbound.width
            scaley = h/fbound.height
            if w < 1: scalex = scaley
            if h < 1: scaley = scalex
            scale = min(scalex, scaley)
            ctm = fitz.Matrix(scale, scale)

        pm = page.get_pixmap(matrix=ctm, dpi=None, alpha=False)
        dpi = round(scale*72)
        pm.set_dpi(dpi,dpi)

        #out_pdf_name = os.path.join(save_path, "PDF{:0>3d}_{:0>4d}.{}}".format(pid, index, ext))
        out_image_name = os.path.join(save_path, "{}_{:0>4d}.{}".format(h_name, index, ext))
        print("    >>>>>>：", out_image_name)
        pm.pil_save(out_image_name, quality=quality)

        index = index + 1

### PyMuPDF version

1.23.8

### Operating system

Windows

### Python version

3.8

**Comment by JorjMcKie** [comment]
I don't see the problem: what is wrong?

Apart from that, your reproducer script is incorrectly formatted and cannot be copied like that.

**Comment by exocrdotcom** [comment]
I use pymupdf（fitz） to convert pdf to image.
The pdf in the attach file（"1.pdf"）， and the result image(attach file "1_0001.jpg" )
The fitz version is 1.23.3, and the code is pdf2imagev2.py
But I use the smartPDF to view the pdf file ,it is correct("1_002.png").
You can compare the pymupdf output "1_0001.jpg" and smartpdf viewer ""1_002.png"

Thank you!
 
From: Jorj X. McKie
Date: 2023-12-23 16:15
To: pymupdf/PyMuPDF
CC: exocrdotcom; Author
Subject: Re: [pymupdf/PyMuPDF] Read and Convert the attach pdf wrong! (Issue #2927)
I don't see the problem: what is wrong?
Apart from that, your reproducer script is incorrectly formatted and cannot be copied like that.

**Comment by JorjMcKie** [comment]
Sorry, but the only thing attached is "1.pdf". Not the script. The shown image is not named like "1_0001.png" or "1_002.png", so I don't know what you are trying to tell me with it.
Please visually mark somehow what you are complaining about in the image.

**Comment by exocrdotcom** [comment]
I zip the all files, please check.



朱军民

北京易道博识科技有限公司
北京市海淀区农大南路1号硅谷亮城2号楼A座7层
手机：+86 139-1039-2121
***@***.***
网址：http://www.exocr.com
国内统一咨询电话：400-9669-910
 
From: Jorj X. McKie
Date: 2023-12-25 16:42
To: pymupdf/PyMuPDF
CC: exocrdotcom; Author
Subject: Re: [pymupdf/PyMuPDF] Read and Convert the attach pdf wrong! (Issue #2927)
Sorry, but the only thing attached is "1.pdf". Not the script. The shown image is not named like "1_0001.png" or "1_002.png", so I don't know what you are trying to tell me with it.
Please visually mark somehow what you are complaining about in the image.

**Comment by JorjMcKie** [comment]
There is no ZIP file anywhere!

**Comment by exocrdotcom** [comment]
How can I sent to you？ I really attach the attach.rar.
Please use another email address?



朱军民

北京易道博识科技有限公司
北京市海淀区农大南路1号硅谷亮城2号楼A座7层
手机：+86 139-1039-2121
***@***.***
网址：http://www.exocr.com
国内统一咨询电话：400-9669-910
 
From: Jorj X. McKie
Date: 2023-12-25 16:50
To: pymupdf/PyMuPDF
CC: exocrdotcom; Author
Subject: Re: [pymupdf/PyMuPDF] Read and Convert the attach pdf wrong! (Issue #2927)
There is no ZIP file anywhere!
―

**Comment by JorjMcKie** [comment]
Yes, you can use my e-mail address jorj.x.mckie@outlook.de.

**Comment by exocrdotcom** [comment]
I put the rar file on this website:

link: https://pan.baidu.com/s/1X0Vg6B2Ee9JjSsUnsvfcxQ 
code: 6fiw



朱军民

北京易道博识科技有限公司
北京市海淀区农大南路1号硅谷亮城2号楼A座7层
手机：+86 139-1039-2121
***@***.***
网址：http://www.exocr.com
国内统一咨询电话：400-9669-910
 
From: Jorj X. McKie
Date: 2023-12-25 16:50
To: pymupdf/PyMuPDF
CC: exocrdotcom; Author
Subject: Re: [pymupdf/PyMuPDF] Read and Convert the attach pdf wrong! (Issue #2927)
There is no ZIP file anywhere!

**Comment by JorjMcKie** [comment]
cannot read Chinese, so don't know what to do when staring at the web page

**Comment by exocrdotcom** [comment]
I have sent it to the ***@***.***>, please check.



朱军民

北京易道博识科技有限公司
北京市海淀区农大南路1号硅谷亮城2号楼A座7层
手机：+86 139-1039-2121
***@***.***
网址：http://www.exocr.com
国内统一咨询电话：400-9669-910
 
From: Jorj X. McKie
Date: 2023-12-25 17:18
To: pymupdf/PyMuPDF
CC: exocrdotcom; Author
Subject: Re: [pymupdf/PyMuPDF] Read and Convert the attach pdf wrong! (Issue #2927)
cannot read Chinese, so don't know what to do when staring at the web page

**Comment by JorjMcKie** [comment]
Thanks for the files - I **_finally_** received them.
My analysis is this:
1. **_None_** of all my PDF viewers can display the page correctly. I am using Adobe Acrobat, MuPDF, SumatraPDF, Foxit Reader, Nitro 5 PDF Reader, PDF XChange Viewer. All on Windows. Under Linux, `evince` also cannot display the file.
2. The file contains an illegal font KaiTi: not embedded, but using identity encoding - which is against the specs.
3. As a consequence, PyMuPDF (MuPDF) cannot render the page image correctly. We use the third party library "FreeType" to decypher fonts. This library issues almost 1000 error messages when called by the Pixmap Generation like this:

```python
pix=page.get_pixmap()
print(fitz.TOOLS.mupdf_warnings())
non-embedded font using identity encoding: KaiTi
non-embedded font using identity encoding: SimSun
FT_Get_Advance(KaiTi,7536): invalid glyph index
FT_Load_Glyph(KaiTi,7536,FT_LOAD_NO_HINTING): invalid argument
FT_Get_Advance(KaiTi,7536): invalid glyph index
FT_Load_Glyph(KaiTi,7536,FT_LOAD_IGNORE_TRANSFORM): invalid argument
FT_Load_Glyph(KaiTi,7536,FT_LOAD_IGNORE_TRANSFORM | FT_LOAD_NO_HINTING): invalid argument
cannot render glyph
FT_Get_Advance(KaiTi,3230): invalid glyph index
FT_Load_Glyph(KaiTi,3230,FT_LOAD_NO_HINTING): invalid argument
FT_Get_Advance(KaiTi,3230): invalid glyph index
FT_Load_Glyph(KaiTi,3230,FT_LOAD_IGNORE_TRANSFORM): invalid argument
FT_Load_Glyph(KaiTi,3230,FT_LOAD_IGNORE_TRANSFORM | FT_LOAD_NO_HINTING): invalid argument
cannot render glyph
FT_Get_Advance(KaiTi,13644): invalid glyph index
... and it goes on like that for 900 more lines
```

Therefore we are unable to render that page.
