### ISSUE TITLE
link do not contain `to` or `dest` attribution, cannot get the jump position.

### ISSUE THREAD

**Issue by xsank** [pymupdf/PyMuPDF#2928]
### Description of the bug

The `link` got from `Page`

1.  do not contain `to` or `dest` attribution
2. `from` `rect` is not correct

### How to reproduce the bug

code:
```python
import fitz
doc=fitz.open("test.pdf")
for page in doc:
    for link in page.get_links():
        print(page.get_textbox(link['from']))
        print(link)
```
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/13742011/test.pdf)

result
```shell
r∗
dr
{'kind': 4, 'xref': 4, 'from': Rect(357.7130126953125, 98.07000732421875, 359.70599365234375, 114.010009765625), 'name': 'nameddest=Hfootnote.1', 'id': ''}
r1 
r A
{'kind': 4, 'xref': 5, 'from': Rect(140.60699462890625, 624.885009765625, 146.58399963378906, 637.406005859375), 'name': 'nameddest=Hfootnote.2', 'id': ''}
 in
e2 
 an
{'kind': 4, 'xref': 6, 'from': Rect(229.4770050048828, 636.8400268554688, 235.45399475097656, 649.3610229492188), 'name': 'nameddest=Hfootnote.3', 'id': ''}
....
```

### PyMuPDF version

1.23.7

### Operating system

MacOS

### Python version

3.11

**Comment by JorjMcKie** [comment]
Following comments:

1. Named destinations can only be handled correctly by the "rebased" implementation of PyMuPDF. I.e. you must (currently) still use `import fitz_new as fitz`.
2. Please use the current version 1.23.8, which also contains important changes to handling named links.
3. The links you are referring to are correctly extracted, specifically the "from" rectangle is correct. Extracting the text underneath the link "from" rectangle is generally unreliable and proves nothing. Instead **draw** the link rectangle and you will see that the cursor reacts precisely to the drawing: 
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/735fef12-62e8-42ac-9739-5968c1dcfe81)

4. For xref 4 for instance, **_there is no "to" point_**: did you not click on it? The page is not moved to the "*" at the bottom.

So wrapping up, there is no identifiable error WRT to 1.23.8.

**Comment by xsank** [comment]
@JorjMcKie thank you for replay. let me try the version of `1.23.8`.

**Comment by xsank** [comment]
The `1.23.8` version does works, thanks again~
