### ISSUE TITLE
When I do multiple document.embfile_add for XML files, Adobe Acrobat can not open a few of them

### ISSUE THREAD

**Issue by australgisinc** [pymupdf/PyMuPDF#2929]
### Description of the bug

I am using the following script to add multiple XML files:

```python
import fitz
import os
import pathlib
path = r"C:\temp"
namedoc = "document.pdf"
pathnamedoc = os.path.join(path,namedoc)
print(pathnamedoc)

doc = fitz.open(pathnamedoc) # open main document
count = doc.embfile_count()
print("number of embedded file:", count)     # shows number of embedded files
namedata = "data.xml"
pathnamedata = os.path.join(path,namedata)
print(pathnamedata)

embedded_doc = fitz.open(pathnamedata) # open document you want to embed
embedded_data = pathlib.Path(pathnamedata).read_bytes() # get the document byte data as a buffer
doc.embfile_add("data.xml", embedded_data)
doc.saveIncr()
```

Everything worked fine until I added 5 XMLs to a PDF document. Then suddenly a few files attached to the PDF are unable to be read. 

Note: I tried to attach the exact same files manually (using drag and drop from Acrobat Pro) and they worked fine, so I believe my XMLs are well built.
 

### How to reproduce the bug

1. Run Python code properly (no errors)
2. Five (5) XMLs files are visible in the PDF attachment section. Just like we wish to happen.
3. When I try to open them, some of them do not open (two actually).
4. NO error is showed, they just not open, they can't be read in Adobe. 
5. When I try to delete them from the PDF manually, 3 of them are deleted except of those 2 corrupted. 

### PyMuPDF version

1.23.8

### Operating system

Windows

### Python version

3.9

**Comment by JorjMcKie** [comment]
You did not provide all mandatory data to reproduce the problem.
It could be multiple causes - among them that Acrobat accepts XML only when having a chance to confirm they don't contain security issues.
So pleas either complete this issue description or try to embed those files with a different extension or in zipped format or the like.

**Comment by JorjMcKie** [comment]
This issue will be close in 3 more days if you do not provide the missing information.

**Comment by JorjMcKie** [comment]
Closed because of missing required feedback.

**Comment by australgisinc** [comment]
> Hi @australgisinc, have you solved the issue somehow? I'm having same problem - some of the attachments cannot be open in Adobe Reader (they can be saved though), the issue is not dependent on names or contents of the attachments and seems to behave randomly. Works in other PDF viewers.

Hi @BohdanMaslowski, No, I didn't. I didn't solve this issue because we had a major project architecture change then the PDF development approach ended.

**Comment by blazzup** [comment]
I can confirm that this is still happening: multiple attachments, some of them can be opened and some not. It does not seem to follow any pattern when attaching different files. Happens with Acrobat Reader, PDF-XChange has no problem opening any of the attachments. Saving the attachments works in both cases.
