### ISSUE TITLE
Unable to insert more than <random #> pages into 1 file reliably?

### ISSUE THREAD

**Issue by bschollnick** [pymupdf/PyMuPDF#293]
I'm running into a strange issue, with inserting pages into a new document...

This code works fine with smaller documents, and with larger (eg over 250 pages), it may or may not die with a Permissions Error (Unable to open file) on a .save call.

But, run it a few times, and it'll work perfectly fine ~50% of the time.

I'm not sure if this is an issue with Fitz, or an Silly Programmer error.  Probably the later.

I'll apologize regarding the code, ahead of time.  

Earlier in the code, it has been scanning each page of a PDF looking for Font Size 14 headers, each page may multiple headers.

docMap = Dictionary of Page Numbers

The page blocks is a dictionary of information about each page block that is defined on the page (1 or more).

One obvious issue maybe, I'm cropping the page, and then saving, under the presumption that the revised crop has to be saved the PDF file...  That's the proper work flow for cropping, right?

`
print()
print()
currentTitleBlock = ""        
for pageNumber in sorted(docMap.keys()):
    
    print("Writing Page ",pageNumber)

    sorted_page_blocks = sorted(docMap[pageNumber].keys())
    num_blocks = len(sorted_page_blocks)
    nextBlock = None
    
    for blockNumber in range(0, num_blocks):
        block = sorted_page_blocks[blockNumber]
            
        # each block is the Y offset of the block on the page
        data = docMap[pageNumber][block]
        print("\tProcessing - ", data["Title"])

        if blockNumber < num_blocks-1:
            nextBlock = docMap[pageNumber][sorted_page_blocks[blockNumber+1]]
            endHeight = nextBlock["Y"]
            print(currentBlockTitle, nextBlock)
        else:
            nextBlock = None
            endHeight = data["PageHeight"]

        PageMask = data["PageMask"]
        if currentTitleBlock != data["Title"]:
            new_doc = fitz.open()
        currentTitleBlock = data["Title"]
        #print("Inserting")
        
        if currentTitleBlock not in [None, "None"]:
            new_doc.insertPDF(doc,
                          from_page=pageNumber,
                          to_page=pageNumber,
                          links=True)
                          
            page = new_doc.loadPage(-1)
            if data["Type"] == "Beginning":
                page.setCropBox([0,data["Y"],data["PageWidth"],endHeight])
            elif data["Type"] == "Ending":
                page.setCropBox([0,0,data["PageWidth"],data["Y"]])
            new_doc.save(data["FileName"])
`

**Comment by JorjMcKie** [comment]
I am sure I don't totally understand the code ...
But a `save` is handed down to MuPDF directly and a permission error typically occurs if (1) the file would land on a prohibited (e.g. read-only) device, or (2) if the filename is that of a currently open file.
I would guess (or bet), it's case (2) here ... Who / what is guarantying that `data["FileName"]` is referring to a file that is **not** still open?
In general you don't need to save a document that you still want to work with afterwards. So, if you in fact are done with a file, why not close it after a save? That would cause an exception if any reference occurs to it (or its children, i.e. pages) after that.
If it is true what I am suspecting, you may want to check `os.path.exists(path)` before you save (which MuPDF doesn't do) to prevent overwriting stuff and thereby tracing down any intermitting Heisenbug.

**Comment by bschollnick** [comment]
Sorry.  Got it working reliably, the most note worthy change was changing it from saving (not iterating saving, but saving) after each page.  I'm assuming that the library wasn't allows able to clean up before the next save request came in.  

Either way, it's working fine, and the other issues I had were code issues that were from my side of the code...
