### ISSUE TITLE
Radiobutton widget field_value is not setting 

### ISSUE THREAD

**Issue by vissnxk** [pymupdf/PyMuPDF#2931]
### Description of the bug

Radio button group is not getting set.

### How to reproduce the bug

I have 2 radio buttons on pdf form:
SpeedType : SpeedActual as radiobutton, SpeedEstimated as radiobutton
ReportTo: Yes as radiobutton, No as radiobutton

values as not getting select / set.

{widget.field_name} - {widget.field_type} {widget.field_type_string } - {widget.button_states()} - {widget.on_state()}')
SpeedType - 5 RadioButton - {'normal': ['SpeedActual'], 'down': ['Off', 'SpeedActual']} - SpeedActual
SpeedType - 5 RadioButton - {'normal': ['SpeedEstimated'], 'down': ['Off', 'SpeedEstimated']} - SpeedEstimated

ReportedTo - 5 RadioButton - {'normal': ['Yes'], 'down': ['Off', 'Yes']} - Yes
ReportedTo - 5 RadioButton - {'normal': ['No'], 'down': ['No', 'Off']} - No

I tried to set widget.field_value = True || widget.field_value = 'Yes' || widget.field_value = widget.on_state() 
but NOTHING is worked.

import fitz  # PyMuPDF

def fill_pdf_form(input_pdf_path, output_pdf_path, form_data):
    pdf_document = fitz.open(input_pdf_path)    

    for i in range(pdf_document.page_count):
        page = pdf_document[i]

        for widget in page.widgets():
            print(f'{widget.field_name} - {widget.field_type} {widget.field_type_string } - {widget.button_states()} - {widget.on_state()}')
            
            for field_name, field_value in form_data.items():            
                if widget.field_name == field_name:
                    if widget.field_type == 5 and widget.on_state() == field_value:
                        # widget._checker()
                        print('RADIO BUTTON MATCH', f'{widget.field_name} - {widget.field_type} {widget.field_type_string } - {widget.button_states()} - {widget.on_state()}')
                        widget.field_value = True
                        widget.field_label = 'HELLLLLOOOOOOO'
                        widget.update()
                       
                        
    
    pdf_document.save(output_pdf_path)
    pdf_document.close()

# Example usage
form_data = {
    
    'SpeedType': 'SpeedEstimated',
    'ReportedTo': 'No'
}
pdf_input_path = f"C:\\Local Data\\input.pdf"
pdf_output_path = f"C:\\Local Data\\output.pdf"

fill_pdf_form(pdf_input_path, pdf_output_path, form_data)

<img width="315" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/148460604/490bdb4b-5a58-47c2-9b32-f3393ee84d4f">
<img width="394" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/148460604/676ea0f1-ae41-44b2-849f-bb58f2ef352d">

### PyMuPDF version

1.23.8

### Operating system

Windows

### Python version

3.12

**Comment by JorjMcKie** [comment]
You did not provide all mandatory data to reproduce your problem.
Please provide a reproducing file and other data - otherwise we are not able to help solving this.

**Comment by JorjMcKie** [comment]
Closing this for lack of information to reproduce the issue.
