### ISSUE TITLE
Input Fields Don't Show Up in Adobe Acrobat

### ISSUE THREAD

**Issue by Ephraim-Bryski** [pymupdf/PyMuPDF#2932]
[base.pdf](https://github.com/pymupdf/PyMuPDF/files/13746395/base.pdf)
### Description of the bug

Input fields updated with fitz show up in browsers (e.g. Edge and Chrome), but not Adobe Acrobat or other non-browser applications.

### How to reproduce the bug

I'm attempting to fill in a form with input fields using fitz.

```python
base_pdf_name = "base.pdf"

with fitz.open(base_pdf_name) as doc:

    assert len(doc)==1 # it's a one page document
    page = doc[0]
    widgets = page.widgets()

    for idx, widget in enumerate(widgets):  
        widget.field_value = str(idx) # i just want to see the field number for now
        widget.update()
        
    page=doc.reload_page(page)
    doc.need_appearances = True
    doc.save('filled.pdf')
```

The new pdf has its fields filled in Edge or Chrome, but doesn't show up in Adobe Acrobat (or Bluebeam Revu).

(I attached the actual pdf I'm using just in case this bug only occurs for certain types of input fields).

### PyMuPDF version

1.23.8

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
Cannot reproduce:
The script works as expected. All my PDF viewers show `filld.pdf` with the updated fields:
* Adobe Acrobat
* browsers
* Foxit reader
* Nitro PDF 5
* evince (Linux)
* PDF XChange

Checkboxes are not changed by your script of course. But setting those to `True` instead of some string value then also works.
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/49a7a174-0bb1-4b80-a206-163ab048bac0)

**Comment by Ephraim-Bryski** [comment]
After seeing your screenshot, I installed the latest Adobe Acrobat version, and it does appear there. It turns out I was using the older Adobe Acrobat 2020 (20.005.30539), which it doesn't appear on on. It also doesn't appear on Bluebeam 20.2.90. (Other functionality like annotations do work on both however).

![adobe](https://github.com/pymupdf/PyMuPDF/assets/38594736/27a1a5ee-4773-49c6-a4ed-4da8906f27af)
![bluebeam](https://github.com/pymupdf/PyMuPDF/assets/38594736/dfec2d13-c2f9-4977-86e0-27a04520528a)
