### ISSUE TITLE
Unable to convert the text with custom fonts into images：get_pixmap

### ISSUE THREAD

**Issue by oldoldstone** [pymupdf/PyMuPDF#2937]
### Description of the bug

In some cases, page.get_pixmap() cannot convert text from pages with custom fonts into images.

### How to reproduce the bug

```
import fitz

doc = fitz.open("test.pdf")
page = doc[0]
pixmap = page.get_pixmap()
pixmap.save("test.png")
doc.close()
```
This is the original image from the PDF.  "Hello  World" inserted using the page.insert_text()  function with a custom font, obtained using the fonttools subsetter from a TTC font. However, if the font is subset of TTF font , it is all ok.
![1](https://github.com/pymupdf/PyMuPDF/assets/10879798/41b0c3fb-9706-4da3-8a50-e8f367635bdf)
This is the image extracted using the pixmap.
![test](https://github.com/pymupdf/PyMuPDF/assets/10879798/e66e6680-0515-41ef-8c18-91d5d2f15134)

[test.pdf](https://github.com/pymupdf/PyMuPDF/files/13754029/test.pdf)

### PyMuPDF version

1.23.7

### Operating system

Linux

### Python version

3.11

**Comment by JorjMcKie** [comment]
Thanks for submitting this. The font contains errors:
```python
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
import fitz
doc=fitz.open("test.pdf")
page=doc[0]
page.get_text()
'1\nH e l l o  W\no r l d\nTest Pages\n'
pix=page.get_pixmap()
pix.save("test.png")
print(fitz.TOOLS.mupdf_warnings())
FT_Load_Glyph(SourceHanSansSC-Bold,2,FT_LOAD_NO_HINTING): invalid argument
FT_Load_Glyph(SourceHanSansSC-Bold,5,FT_LOAD_NO_HINTING): invalid argument
FT_Load_Glyph(SourceHanSansSC-Bold,6,FT_LOAD_NO_HINTING): invalid argument
FT_Load_Glyph(SourceHanSansSC-Bold,7,FT_LOAD_NO_HINTING): invalid argument
FT_Load_Glyph(SourceHanSansSC-Bold,3,FT_LOAD_NO_HINTING): invalid argument
FT_Load_Glyph(SourceHanSansSC-Bold,8,FT_LOAD_NO_HINTING): invalid argument
FT_Load_Glyph(SourceHanSansSC-Bold,4,FT_LOAD_NO_HINTING): invalid argument
```
Some PDF viewers render the text (MuPDF, SumatraPDF, Foxit), others don't.

We cannot accept this as an issue.
