### ISSUE TITLE
Content ordering is getting destroyed in some PDFs.

### ISSUE THREAD

**Issue by hafiz031** [pymupdf/PyMuPDF#2944]
### Description of the bug

Open the PDF attached with the issue with the following code and print it. The printed text doesn't maintain the ordering of the contents.

### How to reproduce the bug

Open the attached file with the following program:

```
import fitz 

def extract_data(pdf_path):
    doc = fitz.open(pdf_path)
    data = ""
    for page in doc:
        data += page.get_text()

    return data

if __name__ == "__main__":
    data = extract_data("Get_Started_With_Smallpdf.pdf")
    print(data)
```

The output will be like:
```
Welcome to Smallpdf
Digital Documents—All In One Place
Access Files Anytime, Anywhere 
Enhance Documents in One Click 
Collaborate With Others 
With the new Smallpdf experience, you can 
freely upload, organize, and share digital 
documents. When you enable the ‘Storage’ 
option, we’ll also store all processed files here. 
You can access files stored on Smallpdf from 
your computer, phone, or tablet. We’ll also 
sync files from the Smallpdf Mobile App to our 
online portal
When you right-click on a file, we’ll present 
you with an array of options to convert, 
compress, or modify it. 
Forget mundane administrative tasks. With 
Smallpdf, you can request e-signatures, send 
large files, or even enable the Smallpdf G Suite 
App for your entire organization. 
Ready to take document management to the next level?
```
Which is not the not in the actual order.

The file: [Get_Started_With_Smallpdf.pdf](https://github.com/pymupdf/PyMuPDF/files/13770949/Get_Started_With_Smallpdf.pdf)

### PyMuPDF version

1.23.7

### Operating system

Linux

### Python version

3.11

**Comment by JorjMcKie** [comment]
If you do not request sorting the text, the return is always as physically stored in the page.
This has a number of good reasons (not explained here).
To request a page-wide sorting sequence top-left to bottom-right, do `text = page.get_text(sort=True)`.
