### ISSUE TITLE
'Page' object has no attribute 'insert_htmlbox'

### ISSUE THREAD

**Issue by conql** [pymupdf/PyMuPDF#2949]
### Description of the bug

I have updated to PyMuPDF 1.23.8. But I still can't use 'insert_htmlbox'.

![image](https://github.com/pymupdf/PyMuPDF/assets/49243542/1a4e9688-a155-4141-8b22-5427da8c55a6)

### How to reproduce the bug

python -m pip install PyMuPDF --upgrade

### PyMuPDF version

1.23.8

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
This new method has only been implemented in the new "rebased" implementation of PyMuPDF.
For a short timeframe (3 more weeks or so), please use `import fitz_new as fitz` to access it.

In first half of January we plan to switch activation defaults, so the usual import statement will point to rebased.

**Comment by JorjMcKie** [comment]
Please let me know what you think about this new feature ... also feel to ask questions or voice any suggestion.

**Comment by conql** [comment]
> Please let me know what you think about this new feature ... also feel to ask questions or voice any suggestion.

I think this is a very neat feature! Before this, insert_text was barely usable for me. Mixing Chinese and English text requires Chinese fonts, which can cause large and ugly spacing for ASCII characters. Now, with typesetting offloaded to HTML, it's much more convenient.

I was trying to use this feature to insert invisible texts into scanned PDFs to make them searchable. For my use case, however, this method is too slow, taking hundreds of times longer than the original. And most importantly, it seems to not support the alpha channel?
