### ISSUE TITLE
apply_redactions() moving text

### ISSUE THREAD

**Issue by indigoviolet** [pymupdf/PyMuPDF#2957]
### Description of the bug

[test.pdf](https://github.com/pymupdf/PyMuPDF/files/13808740/test.pdf)

I have seen #2210 and #2108, but those have been closed in previous versions.

### How to reproduce the bug

```python
doc = fitz.open("test.pdf")
page = doc[0]
page.wrap_contents()
for rect in page.search_for("Dwight Crow"):
    page.add_redact_annot(rect, fill=(1, 0, 0), fontname="courier")

page.apply_redactions()
```
Before:
![image](https://github.com/pymupdf/PyMuPDF/assets/114010/473f59fd-d902-4364-bcfa-0e88f774396f)

After: notice that the red redaction box is positioned correctly but the text around it has moved.

![image](https://github.com/pymupdf/PyMuPDF/assets/114010/988003a9-ace6-4c73-9e96-5bf762797688)

### PyMuPDF version

1.23.7

### Operating system

MacOS

### Python version

3.11

**Comment by JorjMcKie** [comment]
Thanks for the report. I will check it out.

**Comment by JorjMcKie** [comment]
Submitted issue report to https://bugs.ghostscript.com/show_bug.cgi?id=707448.

**Comment by indigoviolet** [comment]
Hello, Is there any sense of what to expect on this issue? It is currently a blocker for one of our efforts.

I did link to it via support@ as well but never heard back - should I be going through some other flow?

**Comment by JorjMcKie** [comment]
> Hello, Is there any sense of what to expect on this issue? It is currently a blocker for one of our efforts.
> 
> I did link to it via support@ as well but never heard back - should I be going through some other flow?

I have increased the priority in MuPDF's issue system.
It is always a good idea to underpin your interest as a user there, too.

When you speak of "us": are you a commercial customer? Please do review your license situation. As a commercial customer, your requests will be handled in a top priority channel.

**Comment by indigoviolet** [comment]
@JorjMcKie: yes, we (=my company, additive.ai) have a PyMuPDF commercial license with Artifex. I have emailed support@artifex.com twice now with no response, so perhaps I'm unaware of the right channel to use.

I will create an account on the MuPDF tracker as well.

**Comment by JorjMcKie** [comment]
@indigoviolet - alright, thank you for this important information!

**Comment by JorjMcKie** [comment]
@indigoviolet The MuPDF team has developed a fix, which I have already tested. I can confirm that it works for your test file.
The team is now discussing the rollout schedule for this hotfix.
In the meantime: if you have another example, I am more than willing to test this too for increased confidence.
In case of any data protection concerns, please feel free to use my private e-mail jorj.x.mckie@outlook.de.
