### ISSUE TITLE
draw_rect radius problem

### ISSUE THREAD

**Issue by Andreasox** [pymupdf/PyMuPDF#2963]
### Description of the bug

The code snippet do not produce any rounded corners, have tested with many different radius and width values without any effect. Ignore the text 111, it is added later without any problem.

### How to reproduce the bug

    color_gold = 0, 0.35, 1, 0.1
   rect = (276.5, 159.5, 318.5, 143.5)
    shape.draw_rect(rect,radius=0.12)
    shape.finish(width=0, fill=(color_gold))

<img width="73" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/6737097/afe0d5b8-8f80-4ff4-ae94-9463b09b65a1">

### PyMuPDF version

1.23.8

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
Your rectangle specification is wrong: you specified an empty rectangle.

**Comment by JorjMcKie** [comment]
Apart from that, the code tried its best to still fulfil your request and drew this: 
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/cd8d73a0-bde8-43da-9683-ee582e0a9ea2)

**Comment by Andreasox** [comment]
Aah, that's why I was quite certain it had worked earlier. Coming from GIS with other coordinate principles and issues.

**Comment by JorjMcKie** [comment]
> Aah, that's why I was quite certain it had worked earlier. Coming from GIS with other coordinate principles and issues.

OKAY! I see now.
It is source for frequent misunderstandings. But I very much agree with MuPDF's coordinate system (top-left = (0,0)).
First of all, MuPDF supports a dozen other document types beyond PDF (which mostly do the same).
Secondly, even PDF is not consequent - it e.g. addresses image coordinates also top-left to bottom-right.
