### ISSUE TITLE
lineheight is not documented for insert_textbox

### ISSUE THREAD

**Issue by Andreasox** [pymupdf/PyMuPDF#2965]
### Description of the bug

e.g. in https://pymupdf.readthedocs.io/en/latest/shape.html#Shape.insert_textbox
And the name lineheight is confusing in my understanding as it changes the line spacing.

### How to reproduce the bug

see above

### PyMuPDF version

1.23.8

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
> And the name lineheight is confusing in my understanding as it changes the line spacing.

A  matter of personal taste I think. Line spacing isn't more correct.
The "natural" line height of a font (my own unofficial term) is the value `lh = font.ascender - font.descender`. If using the default of `lineheight` (1.0), a value of `lh * fontsize` is used. Outputting text that way, leads to zero inter-line overlaps.
Many PDF creators save space on the page by using a smaller value, like `lh * fontsize * 0.8`. Searching for or extracting text in such a situation delivers bboxes that overlap text in neighboring lines. One can prevent this by setting a global variable `fitz.TOOLS.set_small_glyph_heights(True)`before extractions and searches.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.9.
