### ISSUE TITLE
insert_htmlbox - cannot access it

### ISSUE THREAD

**Issue by Andreasox** [pymupdf/PyMuPDF#2966]
### Description of the bug

I cannot get my code to find the function insert_htmlbox for the page.
Should it not be available for the shape class as well?

### How to reproduce the bug

page.insert_htmlbox(rect, "Fare zone", css="* {color:white;font-family:GothamNarrow-Medium;font-weight:bold;font-size:7px;}")
AttributeError: 'Page' object has no attribute 'insert_htmlbox'

The code structure is from the really helpful multi-page table code: https://github.com/pymupdf/PyMuPDF/discussions/2405
doc = fitz.open("pdf", fp)
for page in doc:
    page.wrap_contents()  # ensure all "cm" commands are properly wrapped
    x, y, x1, y0 = coords[page.number]  # read coordinates of the page
    x = sorted(list(x)) + [x1]  # list of cell left-right borders
    y = [y0] + sorted(list(y))  # list of cell top-bottom borders
    shape = page.new_shape()  # make a canvas to draw upon

etc ... - page.insert_font do work:
    page.insert_font(fontname='GothamNarrow-Bold',fontfile='<file path>')

### PyMuPDF version

1.23.8

### Operating system

MacOS

### Python version

3.9

**Comment by Andreasox** [comment]
I have included the suggested import without any success:
from fitz_new.utils import insert_htmlbox

**Comment by JorjMcKie** [comment]
The correct import statement is `import fitz_new as fitz`. No other change in your script required!

Then `page.insert_htmlbox(...)`.

**Comment by Andreasox** [comment]
Thanks, works.
Just curious as very recent user of this excellent library, why is this needed?
Will it change back to only "import fitz" in a later version?

**Comment by JorjMcKie** [comment]
> Thanks, works. Just curious as very recent user of this excellent library, why is this needed? Will it change back to only "import fitz" in a later version?

Yes, exactly: we will switch to "rebased" during the course of January.
Because the rebased version is indeed a major rework, we decided to offer both, classic and rebased, in parallel for a while.

Soon we will have `fitz` to represent the current `fitz_new`. The classic version will remain available under the fallback import statement `fitz_old` for while, before it will be abandoned.
