### ISSUE TITLE
Page divided in random blocks

### ISSUE THREAD

**Issue by lasseedfast** [pymupdf/PyMuPDF#2976]
### Description of the bug

When reading a PDF most pages are read correctly but for some of them the blocks seem to be random. I cannot share the text but the blocks are the same with it redacted: [example.pdf](https://github.com/pymupdf/PyMuPDF/files/13833783/example.pdf)  
If someone will have a look at this I can send the original file.
When I mark the text in macOS Preview the text is marked in the correct order, but it can of course still be that the problem lies in the PDF file.

### How to reproduce the bug

```
import fitz
doc = fitz.open(pdf_path)
page.get_text("blocks")
```

### PyMuPDF version

1.23.8

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
This is normal and can happen. It is no bug.
You can extract via `get_text("blocks", sort=True)`. That may help in a number of cases.
But generally, the PDF creator is free to physically store text in any sequence - even down to single characters.
In very bad cases you may even be forced to sort by single characters and re-compose text based on this.
In PDF, spaces may, but need not be stored at all - in which case you additionally have to generate the missing ones based on some clever algorithm.
