### ISSUE TITLE
Drawing with dashed line stops further drawings.

### ISSUE THREAD

**Issue by xxao** [pymupdf/PyMuPDF#299]
If the "dashes" is defined for Shape.finish() no further drawing operations are possible. Looks like the PDF itself is broken after that. No exception raised.

**Comment by JorjMcKie** [comment]
please provide me a minimal example to recreate the situation

**Comment by xxao** [comment]
My expectation is to see 3 lines, the middle one should be dashed, however, only the top line is visible. I've tried several ways of setting the dashes but none was working. (The Adobe PDF Reference seems to be inaccessible.)

[test.pdf](https://github.com/pymupdf/PyMuPDF/files/3182520/test.pdf)

`
import fitz

doc = fitz.open()
page = doc.page = doc.newPage(width=200, height=200)
shape = page.newShape()

shape.drawLine((50,50), (150,50))
shape.finish(dashes=None)

shape.drawLine((50,100), (150,100))
shape.finish(dashes="[3]")

shape.drawLine((50,150), (150,150))
shape.finish(dashes=None)

shape.commit()

doc.save("test.pdf")
doc.close()
`

**Comment by xxao** [comment]
Interestingly, in the browser I see now 3 lines (still none dashed). In Adobe Acrobat Reader DC version 2018.011.20055 I see just the first line.

**Comment by JorjMcKie** [comment]
I repeated the above. The PDF is **not** broken.

The display highly depends on the PDF viewer used:
* everything fine with SumatraPDF, MuPDF
* Adobe, Nitro PDF, XPDF-Viewer behave differently, but none as expected.
* browsers behave according to the PDF viewer plugin they are using

The solution: specify the dashes parameter including the so-called **_dash phase_**, eg. dashes="[3] 0". Obviously only the more intelligent viewers assume 0 if this is omitted.
Admitttedly, the Adobe docu does **_not_** state, that dash phase is optional ...

**Comment by xxao** [comment]
Perfect! It works now. Thank you very much!
