### ISSUE TITLE
extract text dictionary from pdf

### ISSUE THREAD

**Issue by hellohr11** [pymupdf/PyMuPDF#2998]
### Description of the bug

In the attached pdf, I was trying to extract text from page 34  
If I use page.get_text(), I have no problem, it shows there is no text on the page  
If I use page.get_text('dict'), the program got stuck and takes forever.  

pdf file:
[PRINTED (1).pdf](https://github.com/pymupdf/PyMuPDF/files/13864522/PRINTED.1.pdf)
 

### How to reproduce the bug

no problem for installing

### PyMuPDF version

1.23.7 or earlier

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
You mean page 33 0-based?
Believe it or not: that page has an appearance source of over 12 MB length, over **_109 thousand inline images (!!!!!!!)_** plus 123 external (xref-based) images.

If you now go by and simply do `page.get_text("dict")` with the default `flags` value, then you do not only extract text, but also all images ... **_including the image binaries_**, inline and xref-based.

The page indeed has no text. Your extraction will therefore only consist of image blocks - a list of 110K items.
If works at all - probably your Python storage will overrun - you will have to wait long enough ...

Why don't you use `flags=TEXTFLAGS_TEXT` to make sure to only extract text and no images?

**Comment by JorjMcKie** [comment]
Is this example file usable in a public context or are there data protection concern?
thank you!

**Comment by hellohr11** [comment]
Hi Jorj,

You can use it. But could you please only show the pages you are interested in or maybe remove the address on the pdf page?

Ran
________________________________
