### ISSUE TITLE
How to draw a shape without outlines

### ISSUE THREAD

**Issue by xxao** [pymupdf/PyMuPDF#300]
How the shapes should be drawn just with fill but no outline?
Even if the line width is set to 0, there is still tiny outline visible. If the same image is generated using pycairo, the outline is gone as expected.

[pycairo.pdf](https://github.com/pymupdf/PyMuPDF/files/3183372/pycairo.pdf)
[mupdf.pdf](https://github.com/pymupdf/PyMuPDF/files/3183373/mupdf.pdf)

`import fitz

doc = fitz.open()
page = doc.page = doc.newPage(width=200, height=200)
shape = page.newShape()

shape.drawCircle((100,100), 50)
shape.finish(width=0, color=None, fill=(.9,.9,.9))

shape.commit()

doc.save("mupdf.pdf")
doc.close()`

**Comment by JorjMcKie** [comment]
Thanks for spotting this - on my list for the next release.

**Comment by JorjMcKie** [comment]
This is an easy one. If you need it now, I can send you a corrective version of ``utils.py`` ...

**Comment by xxao** [comment]
Thanks, it would be nice!
Just to let you know, this is what I am working on: https://github.com/xxao/pero

**Comment by JorjMcKie** [comment]
[utils.zip](https://github.com/pymupdf/PyMuPDF/files/3201924/utils.zip)

**Comment by JorjMcKie** [comment]
Here you are.

**Comment by JorjMcKie** [comment]
Pero is an interesting project!
Now I see, why those many draw-related issues are popping up from your corner!
Gives me an itch to now also look into your other issue #301 related to line cap, etc. ...

**Comment by xxao** [comment]
:) thanks. Now it works as expected.

**Comment by JorjMcKie** [comment]
BTW this utils.py version should also fix #298.

**Comment by xxao** [comment]
I know :)

**Comment by xxao** [comment]
Nice! Is seems to work, although, I am using just the shape.finish() method so no check if other methods are correct. Just one comment about the names - they implies it is just about round vs. not round, which is not the case. I understand that you probably should be compatible with previous versions, so you must keep the original name for roundCap. Not easy :) Maybe some documentation would be enough.

**Comment by JorjMcKie** [comment]
Thanks for testing this and giving good feedback!

The other uses of draw methods occur as ``Page`` methods only and always use the ``Shape`` class for this. So those should be ok too.

As per the names: indeed not easy. Either I rename the parameter and keep a synonym for some time with a deprecation warning, or I do a lot of explanation in the documentation to come ...

**Comment by JorjMcKie** [comment]
Urged by another user, I just officially published v1.14.15.
It fixes the issues you brought up.
Please note that I also followed your recommendation and named the new draw parameters ``lineJoin`` and ``lineCap``.
