### ISSUE TITLE
Remove the Ink stamp from pdf

### ISSUE THREAD

**Issue by kumarlova** [pymupdf/PyMuPDF#3004]
### Description of the bug

I am trying to remove stamp from pdf ,but i am fail to remove .
[1300006763.pdf](https://github.com/pymupdf/PyMuPDF/files/13884265/1300006763.pdf)

### How to reproduce the bug

I am trying to remove stamp from pdf ,but i am fail to remove .
[1300006763.pdf](https://github.com/pymupdf/PyMuPDF/files/13884265/1300006763.pdf)

### PyMuPDF version

Built from source

### Operating system

Windows

### Python version

3.12

**Comment by JorjMcKie** [comment]
What did you try?

**Comment by kumarlova** [comment]
import fitz  # PyMuPDF

def remove_ink_stamps(input_path, output_path):
    # Open the existing PDF
    pdf_document = fitz.open(input_path)

    # Iterate through pages
    for page_number in range(pdf_document.page_count):
        page = pdf_document[page_number]
        annotations = page.annots()

        # Filter out ink stamp annotations
        annotations = [annot for annot in annotations if annot.info["title"] == "Ink" and annot.info["subject"] == "Stamp"]

        # Remove ink stamp annotations
        for annot in annotations:
            page.delete_annot(annot)

    # Save the modified PDF
    pdf_document.save(output_path)
    pdf_document.close()

# Example usage
input_pdf_path = "1300006763.pdf"  # Replace with the path to your input PDF
output_pdf_path = "output.pdf"  # Replace with the desired output PDF path

remove_ink_stamps(input_pdf_path, output_pdf_path)
i have tried this code

**Comment by JorjMcKie** [comment]
Stamp annotations are not identifiable in the way you did it. You are looking at annotation properties that are free for arbitrary use - they don't tell you the annotation type!
Why don't you use the `annot.type`?
