### ISSUE TITLE
Page.get_text throws Attribute Error for 'parent'

### ISSUE THREAD

**Issue by jimforem** [pymupdf/PyMuPDF#3027]
### Description of the bug

First off, I am so grateful for you and your amazing code, it has been an incredible advancement. But as far as the bug; similar to Issue #2969, I am getting an attribute error when attempting to use Page.get_text property with a textpage provided as an input. It appears to be caused by the "parent" property being moved under "this" instead of a direct property of the textpage. In 1.23.8, "parent" was a direct property of TextPage, but in 1.23.9 it got moved under the "this" property.

Variable organization using 1.23.9
![image](https://github.com/pymupdf/PyMuPDF/assets/120132706/c5ad488b-81b5-493f-b4de-683c4ba467b8)

Variable organization using 1.23.8
![image](https://github.com/pymupdf/PyMuPDF/assets/120132706/0a9b97a9-00a4-4925-9571-305181f09274)

### How to reproduce the bug

Code:
```
import fitz
doc = fitz.open("TextPage Example Doc.pdf")
page = doc[0]
textpage = page.get_textpage()
fitz.utils.get_text(page=page,option="dict",textpage=textpage)["blocks"]
```

Error Message:
```
  File "TextPage Bug.py", line 5, in <module>
    fitz.utils.get_text(page=page,option="dict",textpage=textpage)["blocks"]
  File "fitz\utils.py", line 803, in get_text
    elif getattr(tp, "parent") != page:
AttributeError: 'TextPage' object has no attribute 'parent'
```

### PyMuPDF version

1.23.9rc2

### Operating system

Windows

### Python version

3.10

**Comment by julian-smith-artifex-com** [comment]
Thanks for reporting this.

It's fixed in new release PyMuPDF-1.23.12.

[One minor thing - please use triple-backticks to enclose code when writing Github issues, otherwise they end up with no line-breaks. I fixed up your initial post, you'll be able to see if you click on `.../Edit`.]
