### ISSUE TITLE
Change color of addHighlightAnnot

### ISSUE THREAD

**Issue by Jensxy** [pymupdf/PyMuPDF#303]
Hello,

I would like to change the color of the highlighted annotations (addHighlightAnnot). Is that somehow possible?

I could use drawRect instead of addHighlightAnnot but this does not work in this case because of the format of the PDF. Either I see the filled rectangle if I use overlap=True or I do not see any rectangle if I use overlap = False. 

If I use addHighlightAnnot everything works fine, but I need a different color, i.e. green.

**Comment by cabal-chan** [comment]
@Jensxy did you figure out how to resolve this? I'd like to know as well.
