### ISSUE TITLE
how to implement a Device

### ISSUE THREAD

**Issue by cole-dda** [pymupdf/PyMuPDF#304]
I want to use a custom device,such as:
class MyDevice:
  def __init__(self):pass
 def fillText(self,...):pass
 def fillPath(self,...):pass

how to?

**Comment by JorjMcKie** [comment]
Not understandable like that.
Where is a connection to PyMuPDF?

**Comment by cole-dda** [comment]
sush as : 
page = doc[0]
device = MyDevice()   #
page.run(device)

**Comment by JorjMcKie** [comment]
have a look at [this](https://github.com/pymupdf/PyMuPDF/blob/master/demo/demo-lowlevel.py)
