### ISSUE TITLE
Insert text with different Chinese fontnames but result in the same 

### ISSUE THREAD

**Issue by Supercarry-khr** [pymupdf/PyMuPDF#3047]
### Description of the bug

I use different Chinese fontnames(including china-s, china-ss...) when inserting the same words into a page.
But the final results are the same.

### How to reproduce the bug

My code is quite simple:

import fitz
print(fitz.__version__)
doc = fitz.open()
page = doc.new_page()
page.insert_textbox(fitz.Rect(0,0,100,100),'飒飒大苏打实打实的方式',fontname = 'china-s',fontsize = 10)
doc.ez_save('fontsize_s.pdf')

doc = fitz.open()
page = doc.new_page()
page.insert_textbox(fitz.Rect(0,0,100,100),'飒飒大苏打实打实的方式',fontname = 'china-ss',fontsize = 10)
doc.ez_save('fontsize_ss.pdf')

But fontsize_s.pdf and fontsize_ss.pdf are the same.

### PyMuPDF version

1.23.8

### Operating system

Linux

### Python version

3.10

**Comment by Supercarry-khr** [comment]
[fontsize_s.pdf](https://github.com/pymupdf/PyMuPDF/files/13944631/fontsize_s.pdf)
[fontsize_ss.pdf](https://github.com/pymupdf/PyMuPDF/files/13944632/fontsize_ss.pdf)
[fontsize_ts.pdf](https://github.com/pymupdf/PyMuPDF/files/13944633/fontsize_ts.pdf)
I later use the same method trying china-ts, but the result is still the same as china-s & china-ss.

**Comment by Supercarry-khr** [comment]
I upgraded my pymupdf just now. (version:1.23.14)
And I did the same tests.
This problem still remains.

**Comment by JorjMcKie** [comment]
That is no bug or issue. These fonts are not embedded and therefore rendered at the discretion of your browser.
Which means that how they look like depends on how your Chrome, Edge, evince or whatever you use wants to show them and is outside PyMuPDF's control.

Use your own font files if you want to have a different text appearance.
