### ISSUE TITLE
Text of original column get seperated into two columns

### ISSUE THREAD

**Issue by linkstatic12** [pymupdf/PyMuPDF#3065]
### Description of the bug

I am running a PDF through this function with the text strategy and when the output dataframe is displayed I see that the original single column in the PDF gets converted into two columns. Also for every page if I do the strategy "text" it detects a table even if there is no table on that page.

### How to reproduce the bug

use any financial report PDF.
doc = fitz.open("test.pdf")
page =doc[14]
and use the find_tables on the page variable, then convert the answer to dataframe and display it.

### PyMuPDF version

1.23.16

### Operating system

Windows

### Python version

3.10

**Comment by linkstatic12** [comment]
doc = fitz.open("F:\\testCom\\786\\PVCL_Annual_June04.pdf")
page = doc[14]
tabs = page.find_tables(horizontal_strategy="text", vertical_strategy="text")  # detect the tables

for i,tab in enumerate(tabs):  # iterate over all tables
    for cell in tab.header.cells:
        page.draw_rect(cell,color=fitz.pdfcolor["red"],width=0.3)
    page.draw_rect(tab.bbox,color=fitz.pdfcolor["green"])
    print(f"Table {i} column names: {tab.header.names}, external: {tab.header.external}")
    
show_image(page, f"Table & Header BBoxes")

[PVCL_Annual_June04.pdf](https://github.com/pymupdf/PyMuPDF/files/13987504/PVCL_Annual_June04.pdf)

**Comment by JorjMcKie** [comment]
Preliminary comments:

You may not have seen detection strategy "lines_strict". This option ignores rectangles with no border, i.e. having a fill color only.
We have seen numerous cases where text inside table cells has a background color. This will regularly confuse the table detection algorithm and deliver messy / nonsense columns.
