### ISSUE TITLE
some pdf's textblocks are wrongly splited

### ISSUE THREAD

**Issue by drunkpig** [pymupdf/PyMuPDF#3073]
### Description of the bug

![image](https://github.com/pymupdf/PyMuPDF/assets/60862764/b714bc90-6ce9-43d8-ae74-e844df6bb227)
![image](https://github.com/pymupdf/PyMuPDF/assets/60862764/68722085-2ec1-4aa3-95ae-34c250c92686)

some pdf text blocks are wrongly splited .

### How to reproduce the bug

```python
import fitz
import os
from pathlib import Path
from loguru import logger

def draw_text_bbox_on_pdf(pdf_path):
    new_pdf = f"{Path(pdf_path).parent}/{Path(pdf_path).stem}.block.pdf"

    doc = fitz.open(pdf_path)
    if os.path.exists(new_pdf):
        os.remove(new_pdf)

    for page in doc:
        char_dict = page.get_text("dict", flags=fitz.TEXTFLAGS_TEXT)['blocks']
        char_dict.sort(key=lambda x: x['bbox'][1])
    
        for blk in char_dict:
            b = blk['bbox']
            shape = page.new_shape()
            shape.draw_rect(b)
            shape.finish(color=fitz.pdfcolor['red'])
            shape.commit()
            # for line in blk['lines']:
            #     b = line['bbox']
            #     shape = page.new_shape()
            #     shape.draw_rect(b)
            #     shape.finish(color=fitz.pdfcolor['red'])
            #     shape.commit()

        shape.commit()


    doc.save(new_pdf)
    logger.info(f"save ok {new_pdf}")
    return new_pdf


pdf_path = "bad-layout.pdf"
draw_text_bbox_on_pdf(pdf_path)
```

### PyMuPDF version

1.23.8 or earlier

### Operating system

Linux

### Python version

3.10
[bad-layout.pdf](https://github.com/pymupdf/PyMuPDF/files/14006941/bad-layout.pdf)

**Comment by drunkpig** [comment]
![image](https://github.com/pymupdf/PyMuPDF/assets/60862764/d57c4cfa-461b-4f20-8340-e7e0f5bcd3e6)

line blocks are totaly right.

**Comment by drunkpig** [comment]
when I select text on the page, it looks like this:
![image](https://github.com/pymupdf/PyMuPDF/assets/60862764/037e6632-bc8a-4323-ba7a-775e735fe5b9)

**Comment by JorjMcKie** [comment]
This is not a bug. It just may happen.
The sub division in blocks and lines depends on how the PDF has been created. MuPDF's internal algorithm does some initial clean-up but does not try to make sense out of the overall layout.
This is far beyond its scope.
If you need to precisely follow the layout (mainly 2 columns per page it looks like here) you need to develop according code - down to single spans or even characters, depending on the making of the file.

**Comment by drunkpig** [comment]
@JorjMcKie I want to enhance this feature,  where should I start?
