### ISSUE TITLE
Improper placement of inserted objects on PDF pages

### ISSUE THREAD

**Issue by thaotonto** [pymupdf/PyMuPDF#308]
Page.insertImage and Page.showPDFpage inserted a image or pdf into pdf page but the image or pdf is not inserted at the right location (inside rect). Image or pdf is auto resized and displayed at the bottom left of the page

**Comment by JorjMcKie** [comment]
Very probably your PDF contains improper changes of the page geometry.
This occurs when eg. the page orientation is reversed (point (0,0) is no longer the PDF standard bottom-left) and that command range is not encapsulated in the string pair ``q`` / ``Q``.

Try to repair that by cleaning the file as a whole (using the cli ``mutool`` utility) or in you script on a per page level using ``page._cleanContents()`` before inserting something.
In rare occasions this action may lead to other problems, however. If so, please tell me and I will show you a way out. It basically works by prefixing and appending thos two commands to the page's `/Contents` object.

**Comment by thaotonto** [comment]
wow after added page. _cleanContents() it worked. Thanks you very much !!!

**Comment by JorjMcKie** [comment]
glad to hear that!
Have fun with the package.

**Comment by JorjMcKie** [comment]
This or a similar issue is popping up once in a while.
And the solution is not rocket science. So I am wondering what can be done to point to it more visibly ...

**Comment by thaotonto** [comment]
It would be great if there are some note about this problem in the document. I spent quite a while to read the doc but still couldn't figure it out and have to go up here asked for help.

**Comment by JorjMcKie** [comment]
Ok thanks.
You are right - it should be in the doc. It actually is, but I am afraid just not prominently enough.

**Comment by JorjMcKie** [comment]
Just published a new docu version which hopefully better addresses your [issue](https://pymupdf.readthedocs.io/en/latest/faq/#misplaced-item-insertions-on-pdf-pages).

**Comment by thaotonto** [comment]
thank you for the information. Can i ask you one more thing: is there any function that insert the image but can still move the image around like annotation object ?

**Comment by JorjMcKie** [comment]
Interesting question! No, not yet. One reason is the PDF concept itself:

Annotations are designed to be "temporary dust" on the surface of a page image. Therefore their position and other characteristics remain accessible for inspection, change or deletion. This is also reflected by the fact, that there is a separate permission category for annotations: you might be authorized to add or change them, but not the document itself.

Technically, changing locations of **images** is very probably never ever possible. Deleting and then re-inserting one might be achievable.

Looks a little better for things inserted via ``showPDFpage`` because those are stored with more explicit location info.

**Comment by thaotonto** [comment]
thank you for the answer. But i noticed that there are some tool that let user insert image on top of pdf's page but can still move it around freely like [PDF-XChange Editor](https://www.tracker-software.com/product/pdf-xchange-editor). I would hope to find a python library that can do the same as this tool.

**Comment by JorjMcKie** [comment]
This may be an approach to change an image location ... doable even today:

* Find out the image's reference name. ``Document.getPageImageList(pno)`` items each describe one image on a page. Example

```python
>>> doc.getPageImageList(0)
[[316, 0, 261, 115, 8, 'DeviceRGB', '', 'Im1', 'DCTDecode']]
```

* Read (all of the) ``/Contents`` object(s) and search for ``b" /Im1 Do "`` (remember that multiple spaces are treated as one and may be interchanged with line breaks). Delete this string where found. Rewrite the contents object(s). Now the image will no longer be shown on that page (but physically it is still there).

* Extract the image stored under xref=316 and insert it at a new location.

This procedure generates a few left over orphans of information, which should be cleaned up on save using the garbage option.

**Comment by JorjMcKie** [comment]
> thank you for the answer. But i noticed that there are some tool that let user insert image on top of pdf's page but can still move it around freely like [PDF-XChange Editor](https://www.tracker-software.com/product/pdf-xchange-editor). I would hope to find a python library that can do the same as this tool.


Does this work for arbitrary PDF images, ie. those not inserted by that tool?
Does this work after you have left the tool session and started over with again opening the PDF from before?

**Comment by thaotonto** [comment]
This only work for image inserted as stamp. And even you reopen PDF with other PDF viewer tool you can still move the image around.

**Comment by JorjMcKie** [comment]
A "stamp"? Sounds like a stamp annotation.
That would be another sort of thing of course - as I wrote before.
In order to support PDF annotation stamps with arbitrary images might be something interesting to do.

**Comment by thaotonto** [comment]
sorry for bother but i got these value after used `_getXrefStream` for content xref after insert image to pdf page but i can't understand what they are. Can you explain it to me
![image](https://user-images.githubusercontent.com/25856583/60038568-eb885f80-96de-11e9-9d10-e0375c3f5529.png)

**Comment by JorjMcKie** [comment]
A page can have zero to many `/Contents` object. These are (bytes) strings which (if multiple exist) will be concatenated and must be interpreted by any PDF viewer software.
They are written in a special mini-language explained in appendix A ("Operator Summary", p. 985) of the Adobe PDF manual.
In the above, "q", "Q", "Do", "cm" are commands, the other tokens are parameters for these commands. The specialty of this language is that parameters **_prefex_** their respective command, eg. the commands
* "cm" means "Concatenate matrix to current transformation matrix", and the six float values **before** that are the matrix values,
* "Do" means "Invoke named XObject", and "fzImg0" is the name of that objct.

The complete string has been generated by your `page.insertImage(...)` method.
