### ISSUE TITLE
doc.close() not closing the document

### ISSUE THREAD

**Issue by JojoMueller** [pymupdf/PyMuPDF#3081]
### Description of the bug

Hi,

doc.close() does not really close a pdf file. My python script does some checks using PyMuPDF, closes the file, compresses it by calling an external program and finally saves the original and copies the compressed file onto the original one. This yields an os error, indicating that the original file is in use by the current python process. Importing fitz_old as fitz instead of fitz works fine.

Thank you in advance for your effort fixing the problem and enhancing this excellent program. 

### How to reproduce the bug

- Open a PDF file using PyMuPDF: doc = fitz.open(pdf_path)
- Try to close the document: doc.close()
- Try to copy a file onto the one pointed to by pdf_path: os.rename(any_file, pdf_path) 

### PyMuPDF version

1.23.17

### Operating system

Windows

### Python version

3.10

**Comment by julian-smith-artifex-com** [comment]
With rebased, the file is kept open after `.close()` if a `fitz.Page` instance is still alive.

So for example:
```
document = fitz.open(path)
page = document[0]
document.close()
# We still have a file handle open for `path`.
page = None
# No file handle open for `path`.
```
Arguably this new behaviour is ok, but we're looking at whether we could replicate the behaviour of `fitz_old` where `page` would become some sort of zombie object after `document.close()`.

**Comment by JojoMueller** [comment]
Thanks for your help. After setting page to None the file is effectively closed.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.18. (There is now no need to set page to None.)

**Comment by JorjMcKie** [comment]
> Hello,
> 
> Last week, I installed PyMuPDF==1.25.3 and am currently using Python 3.12.9 on Windows 11. After calling doc.close(), the file does not appear to be properly closed, as attempting to execute os.remove(file_path) results in the following exception: `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process.`

Cannot confirm - tried it out on Windows and everything works as expected.

**Comment by pachomur** [comment]
I created an issue for this case: https://github.com/pymupdf/PyMuPDF/issues/4319
