### ISSUE TITLE
Block numbers from page.get_text("dict") and page.get_text("words") mismatch.

### ISSUE THREAD

**Issue by rashboldb** [pymupdf/PyMuPDF#3089]
### Description of the bug

I wan't to get some attributes of PDF which I can found using `page.get_text("dict")`.
Later on in the code I try to enrich the info I get from `page.get_text("words")` with the info from the func below. But when I do so based on the block# seems like they mismatch. Is this a desired behaviour?

### How to reproduce the bug

 ```python
def _extract_line_attributes(self, blocks_dict):
        """
        Extracts line attributes from the given blocks dictionary.

        Args:
            blocks_dict (dict): A dictionary containing blocks information.

        Returns:
            dict: A dictionary containing block numbers as keys and line numbers as subkeys.
                Each line's attributes include font size and angle.
        """
        blocks = blocks_dict["blocks"]
        text_blocks = filter(lambda b: b["type"] == 0, blocks)
        attr = {}
        for block_num, block in enumerate(text_blocks):
            attr[block_num] = {}

            for line_num, line in enumerate(block["lines"]):
                attr[block_num][line_num] = {}
                # angle
                a_cos = line["dir"][0]
                a_sin = line["dir"][1]
                r_angle = math.atan2(a_sin, a_cos)
                # NOT relative to page rotation, in degrees
                line_angle = r_angle * (180 / math.pi)
                font_sizes = []
                for span in line["spans"]:
                    # font size, float
                    print(f"text: {span['text']} in block: {block_num}")
                    font_sizes.append(span["size"])

                max_font_size = max(font_sizes)
                attr[block_num][line_num]["font_size"] = max_font_size
                attr[block_num][line_num]["angle"] = line_angle

        return attr
```

Note: I've also tried to use block["number"] instead of enumeration in order to try to get the correct block#, that does't work as well.

### PyMuPDF version

1.23.14

### Operating system

MacOS

### Python version

3.10

**Comment by JorjMcKie** [comment]
The reason for this phenomenon is that the default extraction flags differ by extraction variant:
"dict" by default also extract image blocks, "word" only looks at text blocks and ignore images (for performance reasons!).

If you need the maximum possible number of blocks (or identical block counts across different variants), then please make sure to use the identical extraction flag integer.
IAW use `flags=fitz.TEXTFLAGS_DICT` or `flags=fitz.TEXTFLAGS_TEXT` in both cases.
