### ISSUE TITLE
Interpreting naive datetime as local warning

### ISSUE THREAD

**Issue by as4456** [pymupdf/PyMuPDF#310]
Hi,
I have recently installed fitz using the pre-loaded binaries (PyMuPDF-1.14.15-py27-x64.zip) in Windows.
I am using Canopy as editor and using python 2.7 (64 bit).
Now whenever I try to run some functions from fitz, it shows warnings in python kernel
"Interpreting naive datetime as local warning".

Looks like importing fitz somehow enables warnings in kernel and I get these warnings for each line I type in kernel for using any other packages too.

I dont want to temporarily suppress warnings. Could you tell me what is causing this.
My ipykernel version is 4.7.0-1

thanks

**Comment by as4456** [comment]
I have resolved this issue. you can close this.

**Comment by JorjMcKie** [comment]
Ok ... but nothing to be learned from this for the rest of the world?
