### ISSUE TITLE
Wrong internal property accessed in get_xml_metadata

### ISSUE THREAD

**Issue by gsiegman** [pymupdf/PyMuPDF#3100]
### Description of the bug

In the Document method get_xml_metadata on line 4274 of __init__.py the following code is accessing the wrong property internal.

`if xml and xml.internal:`

It should be:

`if xml and xml.m_internal:`

### How to reproduce the bug

1) Open a document

2) Run the method Document.get_xml_metadata

### PyMuPDF version

1.23.19

### Operating system

MacOS

### Python version

3.11

**Comment by julian-smith-artifex-com** [comment]
Thanks for this, you are quite right. It's fixed in my tree.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.20.
