### ISSUE TITLE
Problems with annotations: Use addHighlightAnnot()

### ISSUE THREAD

**Issue by Chegarra** [pymupdf/PyMuPDF#311]
Hi!

First of all I would like to thank all the work invested for the realization of this fantastic library, it is very useful.

This is my code:

```
instances = doc[p].searchFor(value)
for inst in instances:                    
  annot = doc[p].addHighlightAnnot(inst)
  annot.parent = doc[p]
  annot.setColors({"stroke":(0, 0, 1), "fill":(0.75, 0.8, 0.95)})
  print(annot.__dict__)
  annot.update()
```

I try to change the color to the annotations, but using th **addHighlightAnnot()** method strange things appear:

- The annotation that returns has a **parent = None** (when trying to change color it tells me that it is an orphan).

**Result Annot:**
```{parent': None, 'this': <Swig Object of type 'fz_annot_s *' at 0x7f926c3f9870>}```

**Traceback**
```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-5196e350f28e> in <module>()
----> 1 outbase64 = resaltarResultados(fileBase64, result)

<ipython-input-4-cb07b71420bd> in resaltarResultados(pdfBase64, diccionario)
     10                     annot = doc[p].addHighlightAnnot(inst)
     11                     #annot.parent = doc[p]
---> 12                     annot.setColors({"stroke":(0, 0, 1), "fill":(0.75, 0.8, 0.95)})
     13                     print(annot.__dict__)
     14                     # annot.update()

/usr/local/lib/python3.5/dist-packages/fitz/fitz.py in setColors(self, colors)
   3999         Changes the 'stroke' and 'fill' colors of an annotation. If provided, values must be lists of up to 4 floats.
   4000         """
-> 4001         CheckParent(self)
   4002 
   4003         return _fitz.Annot_setColors(self, colors)

/usr/local/lib/python3.5/dist-packages/fitz/fitz.py in CheckParent(o)
   1644 def CheckParent(o):
   1645     if not hasattr(o, "parent") or o.parent is None:
-> 1646         raise ValueError("orphaned object: parent is None")
   1647 
   1648 def CheckColor(c):

ValueError: orphaned object: parent is None
```

- If you manually insert the page as parent ```annot.parent = doc[p]``` when making the update(), the Python kernel complains with ```Violation of segment (` core 'generated)```.

- If I do a ```annot.setColors({"stroke":(0, 0, 1), "fill":(0.75, 0.8, 0.95)})``` on the annotation, it warns me that ```warning: annot type has not fill color``` (I do not do the update because what happened above happens to me).

**_VERSION LIBRARY: PyMuPDF 1.14.16
VERSIÓN PYTHON: 3.5.2_**

_PD: Translation from Spanish to English by a translator._

**Comment by JorjMcKie** [comment]
Muchas gracias para tu *feedback* tan amable :-)

But everything behaves as designed and as it should: please see [this](https://pymupdf.readthedocs.io/en/latest/app4/#ensuring-consistency-of-important-objects-in-pymupdf) section of the documentation.

There is a hierarchy between some objects of PyMuPDF, eg.: doc -> page -> annotation.
In this example, if `doc` or `page` seize to exist, ``annotation`` will become an orphan and must not be used for **any purpose**. Actually, it should be deleted, but I don't know how to do that.

If you do ``doc[n]``, then the page will be created and **immediately be deleted again**. So, an annotation created via ``doc[n].addHighightAnnot`` "nació huérfano".

Simply create a ``Page`` object via ``page=doc[n]`` and work with it. Drop it when you are with it.
BTW this also has a positive performance impact: in your code you unnecessarily create and delete the same page object multiple times ...

**Comment by Chegarra** [comment]
Thanks for your time to help me with my problem.
Now it goes perfectly.
