### ISSUE TITLE
Calling doc.subset_fonts() throws exception if no fonts exist.

### ISSUE THREAD

**Issue by cmyers009** [pymupdf/PyMuPDF#3111]
### Description of the bug

Calling doc.subset_fonts() throws exception if it is ran on an image PDF with no fonts.

### How to reproduce the bug

FontTools version 4.25.0

Traceback (most recent call last):

  File "C:\Users\{user}\Desktop\scripts\flatten_size_metrics\pdf_transformer.py", line 434, in extract_image_from_pdf
    source_pdf_bytes = PdfTransformer.reset_rotation_and_flatten(source_pdf_bytes,computer_generated_pages)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{user}\Desktop\scripts\flatten_size_metrics\pdf_transformer.py", line 426, in reset_rotation_and_flatten
    new_doc.subset_fonts()
  File "C:\Users\{user}\anaconda3\Lib\site-packages\fitz\utils.py", line 5631, in subset_fonts
    width_table, def_width = get_old_widths(font_xref)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{user}\anaconda3\Lib\site-packages\fitz\utils.py", line 5350, in get_old_widths
    df_xref = int(df[1][1:-1].replace("0 R", ""))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '<</BaseFont/CIDFont+F1/CIDSystemInfo<</Ordering 14 /Registry 15 /Supplement 0>>/CIDToGIDMap/Identity/FontDescriptor<</Ascent 891/CapHeight 662/Descent -216/Flags 6/FontBBox 16 /FontFile2 17 /FontName

Code:

doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        # Create a new PDF to store JPEG images
        new_doc = fitz.open()

        for index, page in enumerate(doc):
            
            if(computer_generated_pages[index]):
                new_doc.insert_pdf(doc, from_page=index, to_page=index)
            else:
                # Analyze the color space of page elements
                is_grayscale = True
                for img in page.get_images(full=True):
                    xref = img[0]
                    base_image = doc.extract_image(xref)
                    
                    if base_image["colorspace"] != 1:
                        is_grayscale = False
                        break

                # Check and adjust the page rotation
                rotation = page.rotation
                if rotation != 0:
                    mat = fitz.Matrix(1, 0).prerotate(-rotation)
                    rotation_matrix = fitz.Matrix().prerotate(-rotation)
                    mat = mat * rotation_matrix

                # Render the page to an image with lower resolution to save space
                mat = fitz.Matrix(150 / 72, 150 / 72)  # Lower DPI
                pix = page.get_pixmap(matrix=mat, colorspace="GRAY" if is_grayscale else "RGB")
                png_bytes = pix.tobytes("png")
                img = Image.open(io.BytesIO(png_bytes))

                page_dim = page.bound()
                with io.BytesIO() as jpeg_bytes:
                    img.save(jpeg_bytes, format="JPEG", quality=quality)
                    jpeg_bytes.seek(0)
                    
                    # Create a PDF page and insert the JPEG image
                    img_rect = fitz.Rect(0, 0, page_dim[2], page_dim[3])
                    new_page = new_doc.new_page(width=page_dim[2], height=page_dim[3])

                    # Insert the JPEG image onto the new page
                    xref = new_page.insert_image(img_rect, stream=jpeg_bytes)

        # Perform operations to reduce file size
        with io.BytesIO() as output_bytes:
            new_doc.subset_fonts()
            new_doc.ez_save(output_bytes)#save(output_bytes, garbage=4, deflate=True, clean=True, incremental=False)
            return output_bytes.getvalue()

### PyMuPDF version

1.23.16

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
Please provide an example file showing this behavior.
We cannot follow up the problem in this way.

**Comment by JorjMcKie** [comment]
As an intermediate information: method `Document.subset_fonts()` shows no problem in any situation I tried (PDFs with image-only pages, empty / non-text pages).

So we are still waiting for an example from you. Please note that we will need close this issue on the 3rd of February if we don't hear from you.

**Comment by JorjMcKie** [comment]
Closed for lack of information / reproducibility.
