### ISSUE TITLE
convert to PDF/A

### ISSUE THREAD

**Issue by hbh112233abc** [pymupdf/PyMuPDF#3124]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

`document.save` function add param `flag`,it's value can be `fitz.PDF_A_1A` or `fitz.PDF_A_1B`

```python
doc = fitz.open(pdf_filepath)
doc.set_metadata(metadata)
doc.save(save_path,flag=fitz.PDF_A_1A)
```

before save,maybe check the pdf is PDF/A format first

**Describe alternatives you've considered**
1. save function add param `flag` for output format flag

**Additional context**
No

**Comment by JorjMcKie** [comment]
Thanks for your post.
This request cannot be handled by PyMuPDF bur must be implemented by our base library, MuPDF.
It has been requested multiple times and the MuPDF team has had good reasons to not implement it. We recommend to join the chat room for MuPDF in this [Discord](https://discord.gg/jzyRrnu7) channel.
