### ISSUE TITLE
Initialising Archive with a pathlib.Path fails.

### ISSUE THREAD

**Issue by GPRicci** [pymupdf/PyMuPDF#3126]
Creating an instance of an `Archive` with a `pathlib.Path` fails with a ValueError "bad archive content".
Debugging the code, I suspect the following lines are responsible:

https://github.com/pymupdf/PyMuPDF/blob/4d604d6d2ddeacd88c321648412e4cc3b0401fde/src/__init__.py#L1749-L1752

Since a `Path` object has an attribute `name` (and given that's checked first), the `content` variable receives the final path component.
Therefore, when the code checks if `content` is either a directory or file (lines 1754 and 1762), it will only be true if the final path element is either a subdirectory or file in the directory where the `__init__.py` file resides.

I tried inverting the conditions of the if and elif statements on the cited snippet, i.e check if `content` is an instance of `Path` before checking it has the attribute `name`, and it worked. However, given my limited knowledge of the library, I'm not sure if this would break in other scenarios.

**Comment by julian-smith-artifex-com** [comment]
Thanks for the report.

I agree that we are incorrectly using the leafname, which means that we will usually not find the intended file or directory. We'll have an internal discussion about how best to make things work, and hopefully release a fix maybe early next week.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.23.
