### ISSUE TITLE
Identifying paragraphs in PDF files

### ISSUE THREAD

**Issue by CaiSamuelsFSA** [pymupdf/PyMuPDF#3132]
### Description of the bug

I am trying to extract paragraphs of text from PDF files, and as far as I'm aware, blocks seem to be the only way to identify paragraphs in PyMuPDF. The problem is that blocks often cut off paragraphs and separate them into multiple blocks.

### How to reproduce the bug

Paragraphs are being cut off when extracting text in blocks.

### PyMuPDF version

1.23.21

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
This is no issue but a Discussions item - transferring ...
