### ISSUE TITLE
Table extraction - vertical text not handled correctly

### ISSUE THREAD

**Issue by kyliemsauter** [pymupdf/PyMuPDF#3148]
### Description of the bug

Vertical text in table columns isn't handled correctly anymore, it used to work before the recent switch to use the "word extractor" methods. 

### How to reproduce the bug

Call extract() on any table that has vertical text
Example file: the two cells that have vertical text "Text" and "Numbers" are returned in reverse order as "txeT" and "srebmuN"
[table_examples_vertical_text.pdf](https://github.com/pymupdf/PyMuPDF/files/14247770/table_examples_vertical_text.pdf)

### PyMuPDF version

1.23.21

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
The fix includes support for all rotations by multiples of 90°.

> You may be aware that line breaks in a cell are preserved. This makes **some** sense as a last resort to identify additional table rows, and in cases with complex cell content ... but only for rotation 0 (horizontal) text. In other cases (rotations by 90°, 180°, 270°) I am replacing line breaks by spaces.

**Comment by kyliemsauter** [comment]
great thank you!!!

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.24.
