### ISSUE TITLE
fitz find_tables with strategy="lines" worse than pdfplumber on this doc

### ISSUE THREAD

**Issue by indigoviolet** [pymupdf/PyMuPDF#3156]
### Description of the bug

IIUC, PyMuPDF's table detection is based originally on pdfplumber; but I noticed an example where it performed worse. I care about this because we'd prefer to standardize on PyMuPDF for all PDF manipulation.

[test_redacted.pdf](https://github.com/pymupdf/PyMuPDF/files/14273999/test_redacted.pdf)

### How to reproduce the bug

```python
import pdfplumber

pdfplumber.__version__
pdf_path = "/Users/venky/Downloads/test_redacted.pdf"

page = pdfplumber.open(pdf_path).pages[0]
tab = page.find_table(
    table_settings={"vertical_strategy": "lines", "horizontal_strategy": "lines"}
)
display(page.to_image().draw_rect(tab.bbox))
```
'0.10.2'

![image](https://github.com/pymupdf/PyMuPDF/assets/114010/ac06cb3e-4497-411c-a75f-3e87e87f5fbd)

----

```python
import fitz

fitz.VersionBind
pdf_path = "/Users/venky/Downloads/test_redacted.pdf"

page = fitz.open(pdf_path)[0]
tab = page.find_tables(vertical_strategy="lines", horizontal_strategy="lines")
page.draw_rect(tab[0].bbox, color=fitz.pdfcolor["red"])
display(pixmap_to_pil(page.get_pixmap()))
```
'1.23.21'

![image](https://github.com/pymupdf/PyMuPDF/assets/114010/d1e482ba-9b32-4c7b-9ec2-88f3ba0d6800)

### PyMuPDF version

1.23.21

### Operating system

MacOS

### Python version

3.11

**Comment by JorjMcKie** [comment]
It is true, that table detections of both packages have the same root. There do exist however differences as per today - and this will increase over time.
1. PyMuPDF detection also works on all of the supported document types (if the type is relevant here at all, like XPS, EPUB, MOBI).
2. We decompose all vector graphics into lines, such that detection is based on (orthogonal) lines exclusively.
3. PyMuPDF's vector graphics extraction is more sophisticated. We will internally add "virtual" graphics where appropriate, such that tables like the following are correctly detected
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/ad7607a5-f6f9-42cf-9fd7-aace14889f8a) which will not work in pdfplumber.
4. We also allow to add virtual vector graphic lines to help (or even **_enable_**) detection. These virtual graphics are additional, and do not disable / replace the overall strategy.
5. The detection strategy `"lines_strict"` **_excludes_** rectangles with fill color but without border. Many tables have cell content that is either visibly highlighted or even has invisible white background. This confuses the `"lines"` detection strategy in cases like the following - leading to all sorts of nonsense cells. In contrast to pdfplumber, this strategy does not exclude bordered rectangles.
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/00ca8ba4-f3fa-44eb-ba60-d12b0aa433a9). If you use `strategy="lines_strict"`, the table will be identified.
6. We support an additional `clip` parameter, which restricts the parts of the page taken into consideration for detection. No need to modify the page's CropBox.

**Comment by indigoviolet** [comment]
Ok, thank you. Agree that `lines_strict` works, mostly I was reporting to make sure you weren't surprised by the `lines` strategy behaving differently. I appreciate the detailed explanation.

**Comment by JorjMcKie** [comment]
Thanks for your feedback and your understanding!
