### ISSUE TITLE
Vscode Type Checking cannot access member "get_pixmap" for type "Page". Member "get_pixmap" is unknown - Pylance

### ISSUE THREAD

**Issue by fredericomattos** [pymupdf/PyMuPDF#3157]
Info 1:
![image](https://github.com/pymupdf/PyMuPDF/assets/58320500/97d87637-4d31-4960-b95e-595ef5bc70d2)
Info 2:
![image](https://github.com/pymupdf/PyMuPDF/assets/58320500/c403bd22-9af5-4fac-8572-e55a7946dd53)
Info 3:
![image](https://github.com/pymupdf/PyMuPDF/assets/58320500/c42f14fb-4b28-4fd9-9f60-f259f00c18a6)

Using Vscode with Type Checking even set to "basic", still receive an alert about not finding the `Page` base for use to `.get_pixmap` function

**Comment by JorjMcKie** [comment]
This is a duplicate of #2883.

**Comment by julian-smith-artifex-com** [comment]
Closing this because, as @JorjMcKie points out above, it is a duplicate of #2883.
