### ISSUE TITLE
Can't we create PDFs with unordered lists having bullets of different shapes?

### ISSUE THREAD

**Issue by SirishaGorasa** [pymupdf/PyMuPDF#3169]
I have tried creating an unordered list using the Unicode \u2022 for the list bullet, but the output pdf had a square bullet as the list label. I have changed the Unicode from 2022 to 25CB which should yield me a hollow round bullet but still the solid square bullet is seen on the page with list.

**Comment by julian-smith-artifex-com** [comment]
Please post the code that you're using to create your PDF. Also specify what PyMuPDF version you are using, and the OS you are running on.

**Comment by JorjMcKie** [comment]
@SirishaGorasa  Let me offer a bet:
You **_must_** be using `page.insert_text()` with no special font that e.g. supports Unicodes beyond 255!

**Comment by SirishaGorasa** [comment]
I am providing the code below.
```
import fitz
def create_pdf_with_unordered_list(filename,items):
    doc=fitz.open()
    page=doc.new_page()
    y=700
    bullet_point="\u25CB"
    font_size=12
    font="Helvetica"
    for item in items:
        page.insert_text((50,y),bullet_point,fontname=font,fontsize=font_size)
        page.insert_text((70,y),item,fontname=font,fontsize=font_size)
        y-=20
    doc.save(filename)
    doc.close()
def main():
    items=["Item 1","Item 2","Item 3"]
    create_pdf_with_unordered_list("unordered_list.pdf",items)
if __name__=="__main__":
    main()
```
The output is as follows:
![image](https://github.com/pymupdf/PyMuPDF/assets/47634813/d08ee61e-31fd-4207-9671-38481a1d7d49)
The bullet I want to create list with is `Hollow Round bullet`, but the list had got created with square bullet. No matter which unicode I specify, the result is the same.

I am using PyMuPDF of version `1.23.3` and running on `Windows 10`

**Comment by JorjMcKie** [comment]
Hi @SirishaGorasa I have **_won my bet_** 😎:
You are using the Base14 built-in font Helvetica. A so-called simple font that only supports characters with Unicode values up to 255. Clearly, 0x25BC "&#9675;" is not among them.
You must use a richer font - or a specialized font. Here are 3 alternatives:

1. Use a special font for the symbol like here font "symbol2" from [pymupdf-fonts](https://pypi.org/project/pymupdf-fonts/). In this case, you should use `doc.subset_fonts()` as shown.
```python
def create_pdf_with_unordered_list(filename, items):
    fontname = "F0"
    font = fitz.Font("symbol2")  # this font from pymupdf-fonts has that symbol
    doc = fitz.open()
    page = doc.new_page()
    y = 700
    bullet_point = chr(0x25CB)
    font_size = 12
    page.insert_font(fontname=fontname, fontbuffer=font.buffer)
    for item in items:
        page.insert_text(
            (50, y),
            bullet_point,
            fontname=fontname,
            fontsize=font_size,
        )
        page.insert_text((70, y), item, fontsize=font_size)
        y -= 20
    doc.subset_fonts()
    doc.save(filename)
    doc.close()
```
Result:
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/abd95bfa-04b3-4fe1-866d-9ae9e5f60092)

2. If you are okay with what the Base14 built-in font ZapfDingbats has to offer, do this:
```python
def create_pdf_with_unordered_list(filename, items):
    doc = fitz.open()
    page = doc.new_page()
    y = 700
    bullet_point = chr(0o155)  # this looks quite similar
    font_size = 12
    for item in items:
        page.insert_text(
            (50, y),
            bullet_point,
            fontname="zadb",  # Base14 ZapfDingbats font
            fontsize=font_size,
        )
        page.insert_text((70, y), item, fontsize=font_size)
        y -= 20
    doc.subset_fonts()
    doc.save(filename)
    doc.close()
```
Result: 
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/9ad11daa-ae64-493a-bca5-17197e21c972)

3. Leave all the pesky stuff around proper font selection to PyMuPDF and use the new method `page.insert_htmlbox()`. It does require some basic HTML knowledge like:
   * line break is `<br>`,
   * non-breaking space is `&nbsp;`
   * Unicode characters can be represented by their number via `&#9675;` (0x25cb = 9675)
   * basic font-family names, like Helvetica = "sans-serif"
```python
def create_pdf_with_unordered_list(filename, items):
    text = ""
    for item in reversed(items):  # append one line per item in list
        text += f"&#9675;&nbsp;&nbsp;  {item}<br>"
    doc = fitz.open()
    page = doc.new_page()
    y1 = 700  # lower y
    y0 = y1 - 20 * len(items)  # upper y
    x0 = 72  # left border
    x1 = 300  # right border
    rect = fitz.Rect(x0, y0, x1, y1)
    page.insert_htmlbox(rect, text, css="* {font-family: sans-serif;}")
    doc.subset_fonts()
    doc.save(filename)
    doc.close()
```
Result:
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/e4849577-3383-4db5-92d0-b27d76692462)
