### ISSUE TITLE
Modify the color of non-text in PDF

### ISSUE THREAD

**Issue by CHIJUI0128** [pymupdf/PyMuPDF#3174]
Dear @JorjMcKie:
Thank you for your hard work! This is a very useful kit. I have successfully merged the contents of two pdfs into a new pdf.

Next, I want to modify the color of the non-text (for example, the first PDF content becomes red dots, and the second PDF content becomes green dots), and then merge the first PDF and  the second PDF into one PDF page.
So that the new PDF contains red and green dots. Now we can clearly see which dots it comes from by color.

BTW, I saw that most of the previous questions were about changing the color of text, but there is no text in my pdf

Below are two pdf files and what I wrote about the merge program.
[change_nontext_color.zip](https://github.com/pymupdf/PyMuPDF/files/14317955/change_nontext_color.zip)

Thanks

**Comment by JorjMcKie** [comment]
Sorry, there is no way and no plan to implement this request in the foreseeable future.

This task is **_a lot_** more complex to do than it seems.
What you can try is hack your way through by changing the appearance source of the page using low-level functions of PyMuPDF. You are on your own and at your own risk when doing this.
1. Read the `/Contents` object(s) of the page.
2. Locate color specifications as defined in the PDF specification, e.g. "PDF 3200-1:2008", page 651 (Operator Summary), and make your changes.
3. Right back the changed appearance source.
