### ISSUE TITLE
Custom font use error

### ISSUE THREAD

**Issue by QwertyCodePL** [pymupdf/PyMuPDF#3176]
### Description of the bug

When i want to add monserrat-regular.ttf as custom font 

```
font_path = r"data/montserrat_reg.ttf"
font = fitz.Font(fontfile=font_path)
...
page.insert_text(insertion_point, new_text, fontname=font.name, fontsize=15)
```
Error: `ValueError: bad fontname chars {' '}`
when i use any other default font (like helvetica) it works

### How to reproduce the bug

use

```
font_path = r"path/to/font"
font = fitz.Font(fontfile=font_path)
...
page.insert_text(insertion_point, new_text, fontname=font.name)
```

### PyMuPDF version

1.23.22

### Operating system

Windows

### Python version

3.12

**Comment by JorjMcKie** [comment]
This is a user error:
1. Insert the font on the page via `page.insert_font(fontname="F0", fontfile="...")`
2. Insert text via `insert_text(point, text, fontname="F0")

The fontname is the **_reference name_** of the font. Not the filename and neither the internal font name.

**Comment by QwertyCodePL** [comment]
@JorjMcKie When i do:
```
    font_path = r"data/mont.ttf"
    
    
    # For every page in doc
    for page in doc:
        page.insert_font(fontname="F0", fontfile=font_path)
...
page.insert_text(insertion_point, new_text, fontname='F0', fontsize=15)
```

I get an error: `Exception: need font file or buffer` 

i have correct ttf file and correct path

**Comment by QwertyCodePL** [comment]
i changed name and still i get the same error
```
page.insert_font(fontname="mont", fontfile=font_path)
...
page.insert_text(insertion_point, new_text, fontname='mont', fontsize=15)
```

**Comment by JorjMcKie** [comment]
Here is how it works: 
[test.zip](https://github.com/pymupdf/PyMuPDF/files/14322947/test.zip)

**Comment by QwertyCodePL** [comment]
thanks so much
