### ISSUE TITLE
fitz.Pixmap(None, pix) Unrecognised args for constructing Pixmap

### ISSUE THREAD

**Issue by luhuaei** [pymupdf/PyMuPDF#3177]
### Description of the bug

```
    pixalpha = fitz.Pixmap(None, pixmap)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fitz/__init__.py", line 9723, in __init__
    raise Exception( text)
Exception: Unrecognised args for constructing Pixmap:
    <class 'NoneType'>: None
    <class 'fitz.Pixmap'>: Pixmap(DeviceRGB, (0, 0, 1920, 2485), 1)
```

### How to reproduce the bug
read the [document](https://pymupdf.readthedocs.io/en/latest/pixmap.html#id4)
```
>>> import fitz
>>> pix = fitz.Pixmap("screenshot.png")
>>> pix
Pixmap(DeviceRGB, (0, 0, 3840, 2400), 1)
>>> alpha = fitz.Pixmap(None, pix)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/fitz/__init__.py", line 9723, in __init__
    raise Exception( text)
Exception: Unrecognised args for constructing Pixmap:
    <class 'NoneType'>: None
    <class 'fitz.Pixmap'>: Pixmap(DeviceRGB, (0, 0, 3840, 2400), 1)

>>> fitz.version 
('1.23.22', '1.23.10', '20240212000001')
>>> 
```

### PyMuPDF version

1.23.22

### Operating system

Linux

### Python version

3.11

**Comment by julian-smith-artifex-com** [comment]
Thanks for reporting this. I have a fix in my tree, so hopefully it'll be in the next release in a few days time.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.23.

**Comment by luhuaei** [comment]
Thanks!

**Comment by jack-gits** [comment]
when I extract the images from PDF, it still raise errors as following.

`doc = fitz.open(file)
        docs=[]
        b_unit = tqdm.tqdm(total=doc.page_count, desc="PDFOCRReader context page index: 0")
        for i, page in enumerate(doc):

            # 更新描述
            b_unit.set_description("PDFOCRReader context page index: {}".format(i))
            # 立即显示进度条更新结果
            b_unit.refresh()
            # TODO: 依据文本与图片顺序调整处理方式
            text = page.get_text("")
            resp = text + "\n"

            img_list = page.get_images()
            for img in img_list:
                try:
                    pix = fitz.Pixmap(doc, img[0])
                    
                except Exception as e:

                    # otherwise, just skip the file and report the error
                    print(
                        f"Failed to load file {file} with error: {e}. Skipping...",
                        flush=True,
                    )`
