### ISSUE TITLE
Table Detection: Incorrect Separation of Vector Graphics Clusters

### ISSUE THREAD

**Issue by JorjMcKie** [pymupdf/PyMuPDF#3179]
### Discussed in https://github.com/pymupdf/PyMuPDF/discussions/3170

<div type='discussions-op-text'>

<sup>Originally posted by **bjmvercelli** February 16, 2024</sup>
Hello folks.

I've been trying to extract tables from a PDF file but i'm having this issue when there are multiple tables in the same page. In the following image you can see that it is grouping all tables as a single one...

![image](https://github.com/pymupdf/PyMuPDF/assets/61213222/f6db4bc8-19d8-49ad-ae01-7b1b84362ab4)

You can replicate it in my [Collab](https://colab.research.google.com/drive/19Ji4Ie-HEpyFx9fAfZqc0TeB6VBAjnAN?usp=sharing)

And you can find the (public) PDF here: [edital_convocacao_matricula_res__medica_2024.pdf](https://github.com/pymupdf/PyMuPDF/files/14310991/edital_convocacao_matricula_res__medica_2024.pdf)
</div>

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.24.
