### ISSUE TITLE
Font object has no attribute bbox

### ISSUE THREAD

**Issue by mtallonb** [pymupdf/PyMuPDF#3188]
https://github.com/pymupdf/PyMuPDF/blob/3a214b0c144d86fd1329b26030f6b9f2a6b27020/src/utils.py#L3089

**Comment by julian-smith-artifex-com** [comment]
Please fill in the details about your PyMuPDF version, Python version and OS when reporting bugs.

**Comment by mtallonb** [comment]
Closing it because It was fixed on latest version. The bug is on v 1.23.9
