### ISSUE TITLE
Remove text not working in 1.23.25 version vs 1.20.2

### ISSUE THREAD

**Issue by bilykigor** [pymupdf/PyMuPDF#3196]
### Description of the bug

Text removal from pdf with PyMuPDF

works good in python3.8 and PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library

<img width="938" alt="Screen Shot 2024-02-21 at 11 12 42 PM" src="https://github.com/pymupdf/PyMuPDF/assets/7822623/5224ac67-5a9f-41ed-ac71-920a6acfae2e">

but if used python3.12 and PyMuPDF 1.23.25 - not all text is removed

<img width="954" alt="Screen Shot 2024-02-21 at 11 09 57 PM" src="https://github.com/pymupdf/PyMuPDF/assets/7822623/17e40152-e1c8-4700-a644-700e1b414332">

### How to reproduce the bug

`import fitz
pdf_doc = fitz.open('data/file.pdf')
page = pdf_doc.load_page(0)
for block in page.get_text("words"):
    rect = fitz.Rect(block[:4])
    page.add_redact_annot(rect)
page.apply_redactions()

pdf_doc.save('data/file_1.pdf')
pdf_doc.close()`

### PyMuPDF version

1.23.25

### Operating system

MacOS

### Python version

3.12

**Comment by julian-smith-artifex-com** [comment]
Could you add the input file, `data/file.pdf`, to this issue page?

**Comment by bilykigor** [comment]
Unfortunately not, it is under NDA. Maybe I can share some metadata?

**Comment by bilykigor** [comment]
The bug starts from PyMuPDF-1.23.9.

**Comment by JorjMcKie** [comment]
@bilykigor  yes - use it with confidence

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.0.
