### ISSUE TITLE
Some problems when using insert_pdf()

### ISSUE THREAD

**Issue by zZzClarezZz** [pymupdf/PyMuPDF#3198]
### Description of the bug

Hi!

After upgraded pymupdf to 1.23.25,
I tried to add a form pdf using insert_pdf(), but the form's contents were missing in the newly obtained pdf.
In the old version, I was able to copy the form contents to the new pdf : 1.19.1

Is there any way I can implement the addition of form content on 1.23.25.

### How to reproduce the bug

This is the form file I used: [test.pdf](https://github.com/pymupdf/PyMuPDF/files/14372057/test.pdf)

'''
import fitz
sourceFile = fitz.open("test.pdf")
newFile = fitz.open()
newFile.insert_pdf(docsrc=sourceFile, start_at=0)
newFile.save("result.pdf")
'''

These are the results I received:
[1.19.1.pdf](https://github.com/pymupdf/PyMuPDF/files/14372107/1.19.1.pdf)
[1.23.25.pdf](https://github.com/pymupdf/PyMuPDF/files/14372112/1.23.25.pdf)

It looks like the form's properties are missing. Does this need some configuration?

Thanks!

### PyMuPDF version

1.23.25

### Operating system

Windows

### Python version

3.10

**Comment by JorjMcKie** [comment]
Whether a PDF is a PDF with form fields is determined independent from pages, IAW a document property.
Method `Document.insert_pdf()` is a copy on page level, and therefore does not copy over that property.
No can-do.
