### ISSUE TITLE
Build error with version 1.14.17

### ISSUE THREAD

**Issue by guoyunhe** [pymupdf/PyMuPDF#320]
Hi, I am maintaining the openSUSE RPM package of PyMuPDF. Last week I try to update the package from 1.14.16 to 1.14.17, but get the following error:

```
[   71s] gcc -pthread -shared -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g build/temp.linux-i686-2.7/fitz/fitz_wrap.o -L/usr/lib -lmupdf -ljbig2dec -lopenjp2 -ljpeg -lfreetype -lharfbuzz -lmupdf-third -lpython2.7 -o build/lib.linux-i686-2.7/fitz/_fitz.so
[   75s] Traceback (most recent call last):
[   75s]   File "setup.py", line 95, in <module>
[   75s]     py_modules=["fitz.fitz", "fitz.utils"],
[   75s]   File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
[   75s]     dist.run_commands()
[   75s]   File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
[   75s]     self.run_command(cmd)
[   75s]   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
[   75s]     cmd_obj.run()
[   75s]   File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
[   75s]     self.run_command(cmd_name)
[   75s]   File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
[   75s]     self.distribution.run_command(command)
[   75s]   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
[   75s]     cmd_obj.run()
[   75s]   File "setup.py", line 11, in run
[   75s]     return super().run()
[   75s] TypeError: super() takes at least 1 argument (0 given)
```

I have the following patch to the source:
```diff
diff -rub PyMuPDF-1.14.10.orig/setup.py PyMuPDF-1.14.10/setup.py
--- PyMuPDF-1.14.10.orig/setup.py       2019-03-10 19:00:25.000000000 +0200
+++ PyMuPDF-1.14.10/setup.py    2019-03-11 11:50:03.288295091 +0200
@@ -15,7 +15,7 @@
         libraries=[
             "mupdf",
             #'crypto', #openssl is required by mupdf on archlinux
-            #'jbig2dec', 'openjp2', 'jpeg', 'freetype',
+            'jbig2dec', 'openjp2', 'jpeg', 'freetype', 'harfbuzz',
             "mupdf-third",
         ],  # the libraries to link with
     )
```
Package is here https://build.opensuse.org/package/show/home:guoyunhe:branches:devel:languages:python/python-PyMuPDF

I cannot find a solution for this. Hope you can guide me! Thanks!

**Comment by JorjMcKie** [comment]
Hi, you are hitting a change in how the pymupdf source is provided, please also refer #312, which lead to this change.
Where did you get the source code from?
If it was Github, then you need to adjust your installation / generation procedure somewhat. In the repo I do no longer provide sources ``fitz.py`` and ``fitz_wrap.c``, which both are generated by SWIG. When using the repo as your installation basis, you also need to have SWIG installed.
If you cannot / do not want to do that, please take the PyPI source, which has the old content ``__init__.py``, ``fitz.py``, ``fitz_wrap.c``, ``utils.py``.
Hope that addresses your issue ...

**Comment by guoyunhe** [comment]
Hi @JorjMcKie thanks for your explanation!

I get the source code from GitHub releases (tar.gz). I did successfully built 1.14.16. I have added swig as build dependency. But I don't know how to get these file generated. Isn't it included in setup.py?

**Comment by JorjMcKie** [comment]
> 
> I get the source code from GitHub releases (tar.gz). I did successfully built 1.14.16. I have added swig as build dependency. But I don't know how to get these file generated. Isn't it included in setup.py?

By request of that issue #312 the SWIG generated files are no longer there, unfortunately. The argument for this being, that (refers to ``fitz.py`` and ``fitz_wrap.c``) building diff files for generates are misleading / worthless.

As I wrote: To get the files you need, you can either fall back to PyPI, or install SWIG and generate them with it. The command line should look something like so: ``$ swig -python fitz.i``.
But actually, the ``setup.py`` provided in the Github repo should do that automatically. Maybe @josch (author of #312) can help here.

**Comment by josch** [comment]
Hi @guoyunhe and hello to you SuSE people form Debian land! :)

To make PyMuPDF build without going through any special invocations other than running setup.py we patched PyMuPDF a bit. You can see our patches here:

https://salsa.debian.org/python-team/modules/pymupdf/tree/master/debian/patches

As you can see we carry a similar patch for the libraries to link against as you do (see patch named `libs`). The patch that should be interesting for you is called `swig` and it modifies `setup.py` such that it will invoke swig in the correct way such that everything gets built automatically.

**Comment by JorjMcKie** [comment]
@josch - THANKS!

**Comment by josch** [comment]
The changes of that patch should also be in git already as part of https://github.com/pymupdf/PyMuPDF/pull/314

**Comment by guoyunhe** [comment]
Thanks @josch  and  @JorjMcKie , I will try!

**Comment by guoyunhe** [comment]
I tried with debian patches but it still fails for same reason...

**Comment by guoyunhe** [comment]
OK, I found it https://stackoverflow.com/a/38964291/4699409

I am building the package for both Python 2 and Python 3. While this `super()` is Python 3 only usage. For Python 2, it must be `super(Object, self)`.

**Comment by josch** [comment]
Python 2 has five months left to live: https://pythonclock.org/

So yes, I didn't bother with adjusting my patch for it. ;)

**Comment by JorjMcKie** [comment]
@josch - bets are still accepted as to whether we'll see a zombie Python 2 still walking around in 2020 ...

**Comment by guoyunhe** [comment]
At least in openSUSE, here isn't any package depending on the python2 version... But Python 2 is still supported. I guess it will finally get abandoned in openSUSE Leap 16.0. I tried to make a patch but it doesn't work as I expected...

**Comment by guoyunhe** [comment]
I disabled Python 2 package building. Now it works.

Maybe we should add some description in README that this library only works with Python 3.x.
