### ISSUE TITLE
PDF can not be displayed after linearization

### ISSUE THREAD

**Issue by vicent4no** [pymupdf/PyMuPDF#3200]
### Description of the bug

Hello everyone

After linearizing this [pdf_original.pdf](https://github.com/pymupdf/PyMuPDF/files/14377935/bad_linearization_original.pdf), 

I can not open it neither via Ubuntu's `Document Viewer` 

![image](https://github.com/pymupdf/PyMuPDF/assets/85420914/d5005bd2-2bdf-4a6d-9292-7fc04e9d71f8)

or Mozilla's PDFJS viewer 

![image](https://github.com/pymupdf/PyMuPDF/assets/85420914/b8e89906-69dd-4726-b218-6ec379cdc6a6)

Thanks for your time by the way.

### How to reproduce the bug

Here's sample code to reproduce the issue 

**REPRODUCTION**

(sample file is in description)

```

from pathlib import Path
import fitz  # type: ignore

file_path = Path(__file__).with_name("pdf_original.pdf")
destination_path = Path(__file__).with_name("pdf_linearized.pdf")
with fitz.open(file_path) as pdf:
    pdf.save(linear=True, filename=destination_path)
```

assuming that `pdf_original.pdf` is in the same level as `__main__.py`

**EXPECTED**:

Be able to open the PDF's linearised version and navigate through it

**NOTE**: 

* No other libraries are installed in environment other than mypy.
* No warnings are displayed by `fitz.TOOLS.mupdf_warnings()` after opening or saving the file

### PyMuPDF version

1.23.25

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
Not yet sure how to best address this. But maybe something is wrong with the provided examples file:
When first saving it using options with implied repair mechanisms, a subsequent saving with linearization leads to a correct file that can be displayed by the usual PDF viewers.

**Comment by vicent4no** [comment]
I am sorry for the delay, actually, by just running `Document.save(linear=True, garbage=2)` solves the issue for web viewers based on PDFJs which is enough for me. Thank you for your timely response

**Comment by JorjMcKie** [comment]
Thank you for your information and cooperation!
