### ISSUE TITLE
Extracting tables which is continued/split across multiple pages

### ISSUE THREAD

**Issue by rahulgoel11** [pymupdf/PyMuPDF#3208]
Hello,

How do we extract tables which is continued across multiple pages, without main table headers being passed to another page?

For Eg :
Below table is split across multiple page

<img width="556" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/54889350/4612b949-a3ed-4682-b88b-18683c759818">

Can we have some solution for this scenario's, because Table extraction is currently at page level (find_tables operate only on page object)?

**Comment by JorjMcKie** [comment]
This situation has no general solution and must be solved by your own code.

First of all, this only works on the basis of pandas Dataframes or the Python lists `table.extract()`. Then, equality of column counts must be assured.
Then, header repetition must be confirmed or excluded.
Potentially in addition, table cell data type must be checked for compatibility.
Etc.

We currently have no plans to address this functionality. The utilities repository has an example script for joining pandas Dataframes. You should be able to adapt it for your specific needs.
