### ISSUE TITLE
Empty vertices in ink annotation

### ISSUE THREAD

**Issue by jesuslop** [pymupdf/PyMuPDF#3209]
### Description of the bug

The Annot.vertices of an ink annotation is empty. Annotation is visible in mupdf and other readers. Getting annotation xref and printing xref_object(xref) show that the vertices are in the dictionary. Inspecting the qpdf JSON dump comfirm vertex data presence. But printing annot.vertices gives the empty list (while annot.info is OK). Some relation to #525

### How to reproduce the bug

 
```
import fitz

pdf = fitz.Document(filetype="pdf")
page = pdf.new_page()
page.add_ink_annot([[(300,300), (400, 380), (350, 350)]])
for a in page.annots():
    print(a.vertices)
pdf.save("borrame.pdf")  # Check the output PDF that the annotation is correctly drawn
```

output is `[]` instead of list of vertices

### PyMuPDF version

1.23.25

### Operating system

Windows

### Python version

3.10

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.23.26.

**Comment by jesuslop** [comment]
Fixed, thanks. Swift!

**Comment by julian-smith-artifex-com** [comment]
Thanks for confirming it works for you, and also for the simpler reproducer.
