### ISSUE TITLE
The function insert_textbox() is not valid

### ISSUE THREAD

**Issue by pierre110** [pymupdf/PyMuPDF#3218]
### Description of the bug

insert_textbox() is invalid in some PDF files

### How to reproduce the bug

`pdf_document = fitz.open('11.pdf')
c = (0, 0, 1)
for page_num in range(pdf_document.page_count):
    r1 = fitz.Rect(90, 20, 800, 800)  # rectangle (left, top, right, bottom) in pixels
    page = pdf_document[page_num]
    shape = page.new_shape()
    shape.draw_rect(r1)
    rc = shape.insert_textbox(r1, 'test', color=c, fontsize=17,
                              fontname="china-ss")
    shape.commit()

pdf_document.save('xx.pdf')
pdf_document.close()`

[11.pdf](https://github.com/pymupdf/PyMuPDF/files/14467911/11.pdf)

### PyMuPDF version

1.23.25

### Operating system

Windows

### Python version

3.10

**Comment by JorjMcKie** [comment]
Please use the bug report form to submit a bug. This is needed for dealing with the problem.
In this case the following is missing specifically:
* clearly describe the error
* clearly describe what should have happened

**Comment by pierre110** [comment]
> Please use the bug report form to submit a bug. This is needed for dealing with the problem. In this case the following is missing specifically:
> 
> * clearly describe the error
> * clearly describe what should have happened

thanks for your reply.. 
I want to add text to the top left of the page.
I'm using “insert_textbox()” on 11.pdf adds text but it does not take effect. 
Can you verify“11.PDF” for me?

**Comment by JorjMcKie** [comment]
what is the value of the return code `rc`?

**Comment by pierre110** [comment]
> what is the value of the return code `rc`?

hello, the value is 240.52 .

**Comment by JorjMcKie** [comment]
This modified script works. You forgot the `.finish()`method.
```python
import fitz

pdf_document = fitz.open("11.pdf")
c = (0, 0, 1)
r1 = fitz.Rect(90, 20, 800, 800)  # rectangle (left, top, right, bottom) in pixels
page = pdf_document[0]
shape = page.new_shape()
shape.draw_rect(r1)
shape.finish(fill=(1, 1, 0))
rc = shape.insert_textbox(r1, "test", color=c, fontsize=17, fontname="china-ss")
shape.commit()

pdf_document.save("xx.pdf")
pdf_document.close()
```

**Comment by pierre110** [comment]
> This modified script works. You forgot the `.finish()`method.
> 
> ```python
> import fitz
> 
> pdf_document = fitz.open("11.pdf")
> c = (0, 0, 1)
> r1 = fitz.Rect(90, 20, 800, 800)  # rectangle (left, top, right, bottom) in pixels
> page = pdf_document[0]
> shape = page.new_shape()
> shape.draw_rect(r1)
> shape.finish(fill=(1, 1, 0))
> rc = shape.insert_textbox(r1, "test", color=c, fontsize=17, fontname="china-ss")
> shape.commit()
> 
> pdf_document.save("xx.pdf")
> pdf_document.close()
> ```

hello, You should get the wrong idea. the .finish(fill=(1, 1, 0)) method just fills in the background color and I need my test text information to be added to the PDF.

**Comment by JorjMcKie** [comment]
Look again: your text is there!
Drawing a rectangle is your idea, not mine.

**Comment by pierre110** [comment]
> Look again: your text is there! Drawing a rectangle is your idea, not mine.

Yeah, sorry！ Oddly enough, after I opened and hidden key information in other software, the regenerated PDF file was ready to use. The insert () method adds text information, but invalidates the original unmodified file
