### ISSUE TITLE
SVG converted to PDF and lost clip-path

### ISSUE THREAD

**Issue by more-strive** [pymupdf/PyMuPDF#3238]
### Description of the bug

`
pymupdf==1.23.7
`
```
filepath="./yft-design.svg"
svg_pdf = fitz.open(filepath)
pdf_bytes = svg_pdf.convert_to_pdf()
svg_pdf.close()
src = fitz.open("pdf", pdf_bytes)
filename = f'{int(time.time())}.pdf'
src.save(os.path.join(current_path, filename))
```
![1709864467](https://github.com/pymupdf/PyMuPDF/assets/113762408/f79103e3-4553-4678-9b2e-03f834a3bab3)

### How to reproduce the bug

converting SVG to PDF lost clip-path

[1709864467.pdf](https://github.com/pymupdf/PyMuPDF/files/14532423/1709864467.pdf)

### PyMuPDF version

1.23.8 or earlier

### Operating system

Windows

### Python version

3.10

**Comment by more-strive** [comment]
This is an SVG file
[Uploading yft-design-svg.zip…]()

**Comment by JorjMcKie** [comment]
The SVG conversion to PDF is not complete as mentioned in the documentation [here](https://pymupdf.readthedocs.io/en/latest/pixmap.html#supported-input-image-formats):
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/e5ea2766-183b-41f8-87c6-61f0a760ae9f)
