### ISSUE TITLE
get_links() does not return links to attached PDF's

### ISSUE THREAD

**Issue by Robustin** [pymupdf/PyMuPDF#3239]
### Description of the bug

I'm trying to programmatically extract, modify, and insert links to page views for PDFs that are attached to the PDF containing the links.  However, when I use the page.get_links() method (or iterate through page.links() or page.annots()) in a document full of links to page views in attached PDF's - nothing is returned. 

### How to reproduce the bug

1. Open your 'Main' PDF in Adobe Acrobat Pro
2. Go to Tools->Edit PDF->Attach File
3. Select an 'Attached PDF' to attach to the Main PDF
4. Highlight text in the Main PDF, right click, select 'Create Link' (or use Tools->Edit PDF->Link->Add Document Link and then click and drag to create the link)
5. In the "Create Link" popup, select "Go to a page view" under "Link Actions", then hit "Next"
6. Click on the paperclip (attachment) icon, double click on the Attached PDF, then click "Set Link" on the desired page of the Attached PDF
7. Save and close the Main PDF
8. Run the following Script to confirm that no link(s) are found:

```
import fitz  # PyMuPDF
doc = fitz.open('test.pdf')
for page_num in range(len(doc)):
    page = doc[page_num]
    links = page.get_links()
    print("Page "+str(page_num)+" contains "+str(len(links))+" links")
```

### PyMuPDF version

1.23.26

### Operating system

Windows

### Python version

3.10

**Comment by JorjMcKie** [comment]
Links of type (kind) `GoToE` (which is this case) are not supported.
