### ISSUE TITLE
ValueError raised when running "page.find_tables()" function in ThreadPoolExecutor.

### ISSUE THREAD

**Issue by igni-c** [pymupdf/PyMuPDF#3241]
## DESCRIPTION
Hello,
Thank you for all the work you've been putting into this project.
Last day I tried to run table extraction in python's thread pool executor with max_workers > 1, but pymupdf raised ValueError: not a textpage of this page. I don't now whether it is a bug or just by design.

## ERROR MESSAGE
![image](https://github.com/pymupdf/PyMuPDF/assets/13314864/8d9b01cf-9c76-4689-a539-68356c4d5ec0)

## TEST FILE
[77a7f504e1041635.pdf](https://github.com/pymupdf/PyMuPDF/files/14536488/77a7f504e1041635.pdf)

## CODE TO REPRODUCE

`import time

import fitz
from concurrent.futures import ThreadPoolExecutor

pdf = fitz.open('77a7f504e1041635.pdf')

def extract_table(page_id):
    start = time.time()
    page = pdf[page_id]
    table_finder = page.find_tables(
        vertical_strategy='lines',
        horizontal_strategy='lines', )
    print(page_id, table_finder.tables, f'time: {time.time() - start}')

futures = []
with ThreadPoolExecutor(max_workers=10) as executor:
    list(executor.map(extract_table, [i for i in range(len(pdf))]))`

### PyMuPDF version

1.23.26

### Operating system

MacOS

### Python version

3.8

**Comment by JorjMcKie** [comment]
PyMuPDF cannot be used with Python threading!
Only using multiprocessing module is supported.

**Comment by neilbhutada** [comment]
It seems that only .find_tables() has this issue when run concurrently. This code on the other hand does not;
for page in doc:
        blocks = page.get_text("dict")["blocks"]
        # prev_table_page, tables = await add_tables(prev_table_page, page.number, page, tables)
        for i in range(len(blocks)):
            if "lines" in blocks[i]:
                contents, current_term = add_text_contents(contents, blocks[i]["lines"], current_term, re.sub("\.pdf","",paths_split[-1]) )
            else:
                image_bytes = blocks[i]["image"]
                image = Image.open(io.BytesIO(image_bytes))
                image_name = str(uuid.uuid4())
                image_path = f"images/{image_name}.{blocks[i]['ext']}"
                image.save(image_path, format="JPEG")
                images[current_term] = {'path':image_path}
