### ISSUE TITLE
Python 3.12 and Alpìne 3.19 error: No matching distribution found for pymupdfb==1.23.22

### ISSUE THREAD

**Issue by andrea-mucci** [pymupdf/PyMuPDF#3247]
### Description of the bug

I want to install PyMuPDF of Alpine 3.19 and Python 3.12.
During the Docker build i get the following error:

```

453.6 ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
453.6 ERROR: Could not find a version that satisfies the requirement pymupdfb==1.23.22 (from versions: none)
453.6 ERROR: No matching distribution found for pymupdfb==1.23.22

```

### How to reproduce the bug

The docker file is:

```
FROM python:3.12-alpine3.19 as base
LABEL authors="andrea@clariteia.com"

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

RUN apk update && \
    apk add libpq

FROM base as builder
ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

RUN apk update && \
    apk add build-base gcc linux-headers g++ cmake make mupdf-dev freetype-dev

WORKDIR /app

RUN pip install poetry==1.8.2

COPY pyproject.toml poetry.lock ./

RUN poetry export -f requirements.txt > requirements.txt
RUN python -m pip install -r requirements.txt
RUN poetry install --without dev --no-root
RUN python -m spacy download en_core_web_lg

```

The PyMuPDF version in the rewquirement file is: 

```
pymupdf = "^1.23.26"

```

### PyMuPDF version

1.23.26

### Operating system

Linux

### Python version

3.12

**Comment by julian-smith-artifex-com** [comment]
What is `^` for in your specifier `pymupdf = "^1.23.26"`?

PyMuPDF specifies a second package, PyMuPDFb, as a prerequisite, and it looks like it is not available in your setup for some reason. PyMuPDFb is on pypi.org and `pip install PyMuPD==1.23.26` will find and install it automatically.

Hope that helps.

**Comment by andrea-mucci** [comment]
The ^ mean that find and update minor versions, this is not the problem

i have moved the image from Alpine to python-bulleye and everything work fine, so i supopose that have some kind of problems related with Alpine Image, that during the installation process does not detect the os version or architecture type or something else

**Comment by julian-smith-artifex-com** [comment]
Ok, thanks for the update. In that case i'll close this issue.
