### ISSUE TITLE
Text alignment is broken for redact annotations Ver. PyMuPDF==1.23.26

### ISSUE THREAD

**Issue by LeonardoReyes** [pymupdf/PyMuPDF#3249]
### Description of the bug

The alignment parameter is not parsed correctly for redact annotations, causing the alignment to default to 0, hence only aligning left. 

### How to reproduce the bug

This is the code snippet I was running:

```
page.add_redact_annot(
        hits[0],
        starter,
        fill=(0.98, 0.98, 0.98),
        fontsize=font_size,
        fontname="helvetica-bold",
        text_color=(0, 0.29, 0.678),
        align=1,
    )
page.apply_redactions()
```

I have tracked down the function deep in the class and made a hard code patch for my case, but I did not have time to find where the dictionary is wrongly parsed in the class. I think the wrong key is assigned, instead of mapping to `align` it is mapping to `ascender`. 

This causes an issue with the `center_rect` function in `utils.py` line 4264, where the function cannot find the right key and assigns 0 as default, when executing this command `align = redact.get("align", 0)`

My patch was simply replacing `align = redact.get("align", 0)` with `align =1`, so it will centre the text as expected, but it does not fix the intended functionality.

### PyMuPDF version

1.23.26

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
We nee the PDF page to deal with this problem.
Thanks.

**Comment by LeonardoReyes** [comment]
Hi, 

The PDF has only one page, a PDF export from Canva. As it has a design I cannot share.

Thx,

**Comment by JorjMcKie** [comment]
Ah, too bad.
Then we cannot deal with the issue.

**Comment by JorjMcKie** [comment]
Sorry, we need to close this issue.

**Comment by JorjMcKie** [comment]
Please feel free to reopen or submit a new issue once you have an example you can share.
