### ISSUE TITLE
How to make combobox clickable on whole area/text, not only on dropdown button?

### ISSUE THREAD

**Issue by stefaneidelloth** [pymupdf/PyMuPDF#3255]
I created some combo box:

```
   combo_box = fitz.Widget()  # create a new widget
    combo_box.field_type = fitz.PDF_WIDGET_TYPE_COMBOBOX
    combo_box.field_name = "myComboBox"
    combo_box.field_value = items[0]
    combo_box.choice_values = items   
   
```

Unfortunately, the combo box only expands when I click on the dropdown button when showing it in Acroboat Reader.

=> How to adapt the code, so that he whole combobox reacts on mous clicks?

Is there some flag I can set or use the `script_focus` JavaScript handler to expand the combo box on mous click?

![image](https://github.com/pymupdf/PyMuPDF/assets/12675339/21796d97-fbf7-4a9e-8b1c-1999351f3601)

**Comment by fhg-isi** [comment]
That's fine. Even if there is no solution, it could already be helpful for others to know that someone tried and failed. It seems the Adobe JavaScript API does not provide a way to programmatically expand a combo box. And there does not seem to be a flag to influence the expansion behavior. Furthermore, the behavior of the combo box is different in different viewers.

**Comment by stefaneidelloth** [comment]
That's fine. Even if there is no solution, it could already be helpful for others to know that someone tried and failed. It seems the Adobe JavaScript API does not provide a way to programmatically expand a combo box. And there does not seem to be a flag to influence the expansion behavior. Furthermore, the behavior of the combo box is different in different viewers.

**Comment by JorjMcKie** [comment]
Thanks for sharing the insight and your understanding.
Closing this post now.
