### ISSUE TITLE
How to detect signature in a form pdf?

### ISSUE THREAD

**Issue by manish59** [pymupdf/PyMuPDF#326]
[FDA-1572_508_R6_FINAL.pdf](https://github.com/pymupdf/PyMuPDF/files/3408678/FDA-1572_508_R6_FINAL.pdf)
[FDA-1572_508_R6_FINAL (2).pdf](https://github.com/pymupdf/PyMuPDF/files/3408679/FDA-1572_508_R6_FINAL.2.pdf)

I have a form pdf which has signature embedded and I want to detect wether the pdf is signed or not?

**Comment by JorjMcKie** [comment]
This is currently (up to version 1.14.18) not supported unfortunately.
I need to straighten out that version anyway b/o some screw ups. So I may insert a ``Document`` method which inquires this state. The key PDF object property is called ``/SigFlags`` in the ``AcroForm`` object. This is an integer with 2 significant bit positions (see p. 674 of the manual):
* bit 0 _**"If set, the document contains at least one signature field."**_
* bit 1 _**"If set, the document contains signatures that may be invalidated if the file is saved (written) in a way that alters its previous contents, as opposed to an incremental update."**_

So what I will probably do in version 1.14.19 is defining a document method ``isSigned`` which returns this integer `/Sigflags`. Or maybe I call it ``getSigFlags``. If not positive, the PDF has no signature fields. A value of 3 would mean ``True`` in the sense of your question.

Support for signature widgets themselves will have to wait until version 1.15.x I am afraid.

**Comment by JorjMcKie** [comment]
just uploaded v1.14.19 to PyPI.
As announced, there is a new method ``doc.getSigFlags()``, which returns
* -1 for no (Form) PDF / no signature fields
* 1 if there is at least one signature field
* 3 if signatures would be invalidated upon a non-incremental save / write. I.e. this value should indicate the status "signed".

**Comment by manish59** [comment]
You are an amazing person buddy. Thanks a lot

**Comment by JorjMcKie** [comment]
thanks a lot, very flattering.
But it wasn't difficult, just a 10-liner in C. Your examples were a big help to focus right on spot!
