### ISSUE TITLE
insert_pdf does not copy widgets

### ISSUE THREAD

**Issue by Kochanac** [pymupdf/PyMuPDF#3272]
### Description of the bug

I was trying to merge two PDFs with fillable forms, and when I do insert_pdf it does not copy widgets, so on the second page forms disappear.

### How to reproduce the bug

1. Make a fillable form
2. `python -m fitz join cioms-continuation.pdf -output tmp.pdf` or in code:
```python
doc = fitz.open(CIOMS_PDF_PATH)
continuation = fitz.open("./cioms-continuation2.pdf")
doc.insert_pdf(sec_page)
doc.save('out.pdf') # this way on the first page fillable forms remain
```
4. With `fitz join` all fillable forms disappear, with insert_pdf only the second one

### PyMuPDF version

1.23.26

### Operating system

Linux

### Python version

3.11

**Comment by Kochanac** [comment]
the workaround is to manually copy the widgets

**Comment by Kochanac** [comment]
my pdf:

[cioms-continuation2.pdf](https://github.com/pymupdf/PyMuPDF/files/14628771/cioms-continuation2.pdf)

**Comment by JorjMcKie** [comment]
This is not bug but works as designed!

**Comment by ReedGraff** [comment]
@JorjMcKie, how can we emulate copying them? This is how I currently am doing so:
[test1.pdf](https://github.com/user-attachments/files/15523395/test1.pdf)
[test2.pdf](https://github.com/user-attachments/files/15523396/test2.pdf)

`python
import fitz
docA = fitz.open("test1.pdf")
docB = fitz.open("test2.pdf")

allWidgets = []
for page in docA.pages():
    allWidgets.extend(page.widgets())

widgetsToAdd = []
for page in docB.pages():
    widgetsToAdd.extend(page.widgets())

docA.insert_pdf(docB)
print("allWidgets", allWidgets)
print("widgetsToAdd", widgetsToAdd)

for page in docA.pages(docA.page_count-1, docA.page_count):
    for widget in widgetsToAdd:
        print(widget.field_name)
        if widget.field_type != 6:
            if widget.field_name in [x.field_name for x in allWidgets]:
                print("field name already exists")
                widget.field_name = "_" + widget.field_name # duplicate fields
                page.add_widget(widget)
            else:
                page.add_widget(widget)

print("\n\n")
for page in docA.pages():
    for widget in page.widgets():
        print(
            widget.field_name
        )

docA.save('output01.pdf')
`
This copies the widgets and applies them on the following pdf. 
However, this doesn't work with signature fields, as y'all can't seem to make them. In my application I need to merge forms and subsequently fill them. Merging fillable forms like this is possible in other libraries like pypdf & pdfrw.

**Comment by JorjMcKie** [comment]
Try the relatively new method [bake](https://pymupdf.readthedocs.io/en/latest/document.html#Document.bake).
