### ISSUE TITLE
Page.get_image_info() method returns flipped images

### ISSUE THREAD

**Issue by Irajan** [pymupdf/PyMuPDF#3273]
### Description of the bug

I tried to extract images from the pdf document that contains image and tried to run OCR on the extracted image in order to get the image data. I tried using `Page.get_image_info()` method but the OCR result is not giving me the result as expected. 

### How to reproduce the bug

I tried debugging by printing the detected image with the following code and found that the detected images are flipped unexpectedly. Need help to find out if there's something wrong in my implementation or there's a bug in the image detection.

```python
import fitz
from PIL import Image
import io

doc = fitz.open("sample.pdf")

for page_index , page in enumerate(doc):

  image_blocks = page.get_image_info(xrefs=True)
  count = 0

  for image in image_blocks:
      if not image["xref"]:
        continue

      base_image_info = doc.extract_image(image["xref"])
      image_bytes = base_image_info["image"]

      image = Image.open(io.BytesIO(image_bytes))
      image.save(f"./images/image__{page_index + 1}__{count}.png")
      count = count + 1
```

Sample pdf file is 
[sample.pdf](https://github.com/pymupdf/PyMuPDF/files/14632561/sample.pdf)

Extracted images
image__1__0
![image__1__0](https://github.com/pymupdf/PyMuPDF/assets/38995844/aa5739c0-ccb6-4385-ae7b-c8b9cb40bbec)

image__1__1
![image__1__1](https://github.com/pymupdf/PyMuPDF/assets/38995844/58d2645a-01a6-4403-b08f-1920064cf8a2)

### PyMuPDF version

1.23.26

### Operating system

Linux

### Python version

3.11

**Comment by JorjMcKie** [comment]
The PDF creator has rotated the images flipped top-bottom.
This is not a PyMuPDF problem.
You could find out what happened during image insertion to the PDF page by looking at the transformation matrix used. For example image at xref 7:
```python
import fitz
doc=fitz.open("sample.pdf")
page=doc[0]
from pprint import pprint
pprint(page.get_images())
[(7, 0, 1318, 1018, 8, 'DeviceGray', '', 'R183', 'FlateDecode'),
 (8, 0, 1318, 1018, 8, 'DeviceGray', '', 'R182', 'FlateDecode'),
 (9, 0, 1318, 1018, 8, 'DeviceGray', '', 'R181', 'FlateDecode'),
 (10, 0, 1318, 1018, 8, 'DeviceGray', '', 'R180', 'FlateDecode'),
 (11, 0, 1318, 1018, 8, 'DeviceGray', '', 'R179', 'FlateDecode'),
 (12, 0, 1318, 1018, 8, 'DeviceGray', '', 'R178', 'FlateDecode'),
 (13, 0, 1318, 1018, 8, 'DeviceGray', '', 'R177', 'FlateDecode'),
 (14, 0, 1318, 1018, 8, 'DeviceGray', '', 'R176', 'FlateDecode'),
 (15, 0, 1318, 1018, 8, 'DeviceGray', '', 'R175', 'FlateDecode'),
 (24, 0, 155, 73, 8, 'DeviceGray', '', 'R8', 'DCTDecode')]
img7=doc.extract_image(7)
img7.keys()
dict_keys(['ext', 'smask', 'width', 'height', 'colorspace', 'bpc', 'xres', 'yres', 'cs-name', 'image'])
page.get_image_rects(7,transform=True)
[(Rect(1431.9599609375, 334.1400146484375, 2043.8399658203125, 1126.1400146484375), Matrix(0.0, -792.0, -611.8800048828125, -0.0, 2043.8399658203125, 1126.1400146484375))]
```
As you can see, the transformation matrix has negative values for `matrix.b` and `matrix.c` and hence does a top-bottom flip.

**Comment by JorjMcKie** [comment]
The transformation matrix is also part of `page.get_image_info()`.

**Comment by JorjMcKie** [comment]
The image's **original is flipped!** The PDF creator has "un-flipped" it to properly display on the page.

**Comment by Irajan** [comment]
Is't there any way to undo the "un-flipped" action by pdf-creator. This would help me restore the original content of the document

**Comment by JorjMcKie** [comment]
> Is't there any way to undo the "un-flipped" action by pdf-creator. This would help me restore the original content of the document

What you actually mean is to **_do the same thing as the creator_**: un-flip the image, right?
Take the image and use e.g. Pillow for unflipping using `Image.Transpose.FLIP_TOP_BOTTOM`.

**Comment by Irajan** [comment]
I've tried this as well but the problem I ran into was there is combined case for flip as well as image flip.
For example :
 If I have the transformation matrix of page as 
`(-612.0, -0.0, -0.0, 792.0, 899.3999633789062, 203.4000244140625)`
and the transformation matrix for image as
`(0.0, -792.0, -611.8800048828125, -0.0, 2043.8399658203125, 1126.1400146484375)`

This shows the case page is not flipped and image is flipped 

But for the transformation matrix 
`(-612.0, -0.0, -0.0, -792.0, 899.3999633789062, 203.4000244140625)` for page
and same as above for the image

this shows that the page and image both are flipped and the above un flipping technique doesn't work 
any suggestion on this ??

**Comment by JorjMcKie** [comment]
let's convert this to a discussion first ...
