### ISSUE TITLE
NameError: name 'Py_RETURN_NONE' is not defined

### ISSUE THREAD

**Issue by josch** [pymupdf/PyMuPDF#328]
Since the 1.14.19 release I'm getting `NameError: name 'Py_RETURN_NONE' is not defined` when I do `insertText`. The full error can be seen on Travis CI where I regularly test some code that relies on PyMuPDF:

https://travis-ci.org/josch/plakativ/builds/561540882

**Comment by JorjMcKie** [comment]
damn - type correction underway - let you know when done ...

**Comment by JorjMcKie** [comment]
hotfix uploaded, also to PyPI (except MacOSX-wheels for which Travis generation currently is having issues).
Thanks for spotting this!

**Comment by JorjMcKie** [comment]
PyPI download section also contains Mac OSX wheels again now.
