### ISSUE TITLE
PDF file after text replacement doesn't show bullet point correctly

### ISSUE THREAD

**Issue by santanuOUP** [pymupdf/PyMuPDF#3282]
### Description of the bug

Below are the steps I performed:
1. Read a pdf written in Dutch
2. Translate all the texts to English
3. Replace texts in original pdf with translated text

During the reading and translation bullet point is showing as expected. But after replacement when I open the PDF it's showing as '?'. 

Here is the code:

`with fitz.open(file_path) as doc:  
        for page in doc:
            page_blocks = page.get_text("dict")["blocks"]                     
            for block in page_blocks:
                if "lines" in block.keys():
                    spans = block['lines']                           
                    for span in spans:
                        span_info = span['spans']                                    
                        for text_info in span_info:
                            if text_info['text'].strip():
                                new_text = invoke_translator(text_info['text'])
                                if new_text:
                                    rect = text_info['bbox']
                                    page.add_redact_annot(rect, new_text)

            page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)`

Output after pdf read: [pdf-read.txt](https://github.com/pymupdf/PyMuPDF/files/14653311/pdf-read.txt)
Original pdf: 
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/14653327/test.pdf)

Final PDF: 
[translated (10).pdf](https://github.com/pymupdf/PyMuPDF/files/14653336/translated.10.pdf)

### How to reproduce the bug

NA

### PyMuPDF version

1.23.25

### Operating system

Windows

### Python version

3.8

**Comment by santanuOUP** [comment]
```
`with fitz.open(file_path) as doc:  
        for page in doc:
            page_blocks = page.get_text("dict")["blocks"]                      
            for block in page_blocks:
                if "lines" in block.keys():
                    spans = block['lines']                           
                    for span in spans:
                        span_info = span['spans']                                    
                        for text_info in span_info:
                            if text_info['text'].strip():
                                new_text = invoke_translator(text_info['text'])
                                if new_text:
                                    rect = text_info['bbox']
                                    page.add_redact_annot(rect, new_text)

            page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)
```
`

**Comment by JorjMcKie** [comment]
If I understand your code correctly, you insert the new text via the redaction annotation itself.
**_I am assuming this is true_** for the following.

Replacement text in annotations uses Base14 fonts. These fonts only show text correctly that uses no character code beyond 255, i.e. they are "simple" fonts.
The bullets in your original PDF are however characters above that limit: 0x2022 = 8226 = &#8226;.
So the logical output is a question mark for these bullets.

**Comment by santanuOUP** [comment]
@JorjMcKie Thanks for your reply.
How to display those bullet points as it shows in original pdf? Is there any provision in PyMuPDF?

Thanks.

**Comment by JorjMcKie** [comment]
> @JorjMcKie Thanks for your reply. How to display those bullet points as it shows in original pdf? Is there any provision in PyMuPDF?
> 
> Thanks.

If you insist on the comfort of specifying a replacement text directly in the redaction definition, then you must pay by effort somewhere else.
You have some alternatives:
1. insert a suitable font (have character &#8226;). Insert some text with this font somewhere outside any redaction rectangle. E.g. a space at position (0,0). The use the chosen font name from method `page.insert_font()` in the redaction definition.
2. Do **not** specify replacement text in the redact annotation. Wait until after `page.apply_reactions()`. Then use [page.insert_htmlbox](https://pymupdf.readthedocs.io/en/latest/page.html#Page.insert_htmlbox) with your desired text.

**Comment by JorjMcKie** [comment]
As an ultimate resort you can also use a similar bullet that is in `range(256)`: chr(0xb7) = "&#xb7;". This makes it possible to stick with Helvetica and friends.
