### ISSUE TITLE
test_3081 is playing file handle roulette

### ISSUE THREAD

**Issue by mjg** [pymupdf/PyMuPDF#3285]
The following assert can (and does) fail non-deterministically:

https://github.com/pymupdf/PyMuPDF/blob/f039ad400807bb22befb408abb71b7d0cb485086/tests/test_general.py#L865

The reason is that the test relies on a few assumptions:
- file handles are reused immediately after being released
- file handles are numbered sequentially
- the process is the only one requesting file handles

Only if all of these are satisfied `fd2` will equal `fd1+1`, because the explicit open in line 833 gets the same handle as `fd1` (having been closed) and holds it at the time when `fd2` gets set, and the next available one is (hopefully) `fd2+1`.

I'm afraid none of these assumptions is justified. Why shouldn't the explicit open get, say `fd1+1` so that `fd1` is available at the time `fd2` get's set? What is the assert trying to test? Everything in the test description is tested by the exceptions already.

**Comment by mjg** [comment]
This is what lead me to my analysis:
```
       print(f'{fd1=} {fd2=} {fd3=} {fd4=}')
        print(f'{document=}')
>       assert fd2 == fd1 + 1
E       assert 17 == (15 + 1)

tests/test_general.py:865: AssertionError
----------------------------- Captured stdout call -----------------------------
Received expected exception: document closed
Received expected exception: page is None
fd1=15 fd2=17 fd3=15 fd4=15
document=closed Document('/builddir/build/BUILD/PyMuPDF/tests/test_3081-2.pdf')
=========================== short test summary info ============================
FAILED tests/test_general.py::test_3081 - assert 17 == (15 + 1)
================ 1 failed, 219 passed, 14 deselected in 19.48s =================
```
I called it non-deterministic because of the pattern where it appeared [in copr](https://copr.fedorainfracloud.org/coprs/mjg/mupdf-git-release/build/7187969/) testing 

I agree that my analysis and your quotes from the man page are in disagreement ...

As for the check: You check that fd1 got closed (basically) by checking that you could reuse that handle. This assumes that there aren't other problems like duplicate handles, unless you check that the handle really gives different content now.

In copr, we sometimes see "spurious" failing tests which hint at concurrency or timing issues. Typically you don't see them locally or in other CI, but I don't think it's an infra problem.

And I don't think those tests need to make all these assumptions about file handles. But I can ignore them easily, of course.

**Comment by julian-smith-artifex-com** [comment]
Thanks for your comments. I'm intrigued that you see these failures, but i can't think of any mechanism that would effect file descriptor numbers other than a kernel bug or perhaps some sort of monitoring system that was running hidden code, e.g. on an injected thread, within processes. [The only alternative i can think of is that PyMuPDF behaves differently in this respect on Fedora, compared to the systems we regularly test on - Windows, other Linux, MacOS and OpenBSD.]

By the way, i've just checked, and POSIX does indeed mandate that `open()` returns the lowest available file descriptor - see: https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_14 ("File Descriptor Allocation").

> This assumes that there aren't other problems like duplicate handles, unless you check that the handle really gives different content now.

There are always ways for a buggy programme to break things in ways that do not fail tests; i still think the file-descriptor tests are useful.

Thanks for stating that you're happy to ignore these tests. I'll close this issue shortly. Please feel free to re-open it if you find more information.
