### ISSUE TITLE
v1.24 breaks XPS-table example

### ISSUE THREAD

**Issue by martin-dreyer-teck** [pymupdf/PyMuPDF#3295]
### Description of the bug

With v1.23.26 running page.find_tables() with the provided example file XPS-table.pdf returns one table.
With v1.24, doing the same returns ZERO tables.

### How to reproduce the bug

```pip install PyMuPDF==1.24```

```
import fitz

doc = fitz.open("XPS-table.pdf")
page = doc[0]
tabs = page.find_tables()
print(f"len={len(tabs.tables)}")
```
output: len=0

### PyMuPDF version

1.24.0

### Operating system

Linux

### Python version

3.10

**Comment by julian-smith-artifex-com** [comment]
Could you provide the file XPS-table.pdf?

**Comment by JorjMcKie** [comment]
This is not a table-related problem. When taking a closer look it turns out that **_no text is extracted_** from the page.
Based on this, of course no table can ever be identified.

**Comment by JorjMcKie** [comment]
Closed b/o extended time without response.

**Comment by martin-dreyer-teck** [comment]
@JorjMcKie apologies, I missed the messages on this hence the late response. FYI the file XPS-table.pdf is in the pymupdf repo and presented in examples of how to do table extraction.

https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/table-analysis
