### ISSUE TITLE
pdf to image

### ISSUE THREAD

**Issue by wangcn99** [pymupdf/PyMuPDF#330]
When i want convert my pdf to image i can only get the first page but the other pages is empty

**Comment by JorjMcKie** [comment]
plus OS, Python version, PyMuPDF version and script

**Comment by wangcn99** [comment]
win10  python3.7 pymupdf1.14.19.1 

here are my script：
    def pdf_cut(self):
        doc = fitz.open(self.pdf_path)
        count = 0
        for pg in range(doc.pageCount):
            page = doc[pg]
            count = count + 1
            rotate = int(0)
            zoom_x = 4
            zoom_y = 4
            trans = fitz.Matrix(zoom_x, zoom_y).preRotate(rotate)
            pm = page.getPixmap(matrix=trans, alpha=False)
            print(pm)
            # cv2.imshow(pm)
            pm.writePNG(self.target_path+'%s.png' % pg)

**Comment by wangcn99** [comment]
![图片](https://user-images.githubusercontent.com/42457954/61988221-00933e00-b051-11e9-9f4b-7a78d49cd734.png)
i can only get the first page but the others the os say they don‘t support such format

**Comment by JorjMcKie** [comment]
Impossible to recreate your situation, so send me the PDF please, too.

**Comment by JorjMcKie** [comment]
why don't you try this simple snippet:

```python
for page in doc:
    pm = page.getPixmap(alpha=False)
    pm.writePNG("p-%i.png" % page.number)
```
If this works, then you know your original script has some error not related to PyMuPDF.
If it **doesn't** work, then the PDF has some problem. Either send it and I am willing to check it out, or try another PDF to confirm.

**Comment by wangcn99** [comment]
i find the problem  ：
not pymupdf‘s problem 
is another jars problem thank  you for your help
