### ISSUE TITLE
page.get_text("blocks") not working with PyMuPDF version 1.24.0

### ISSUE THREAD

**Issue by 3051360** [pymupdf/PyMuPDF#3300]
### Description of the bug

page.get_text("blocks") has stopped working with the latest PyMuPDF version.

### How to reproduce the bug

Below is a simple code snippet:

```
input_file = "my_pdf.pdf"
doc = fitz.open(input_file)

for page_no, page in enumerate(doc):
    print(page.get_text("blocks"))

```

With **PyMuPDF version 1.22.2** the code prints:

`[(0.0, 0.0, 273.6000061035156, 728.1599731445312, '<image: ICCBased(RGB,GIMP built-in sRGB), width: 1140, height: 3034, bpc: 8>', 0, 1)]`

With  **PyMuPDF version 1.24.0** the code is not able to get anything.

### PyMuPDF version

1.24.0

### Operating system

MacOS

### Python version

3.12

**Comment by JorjMcKie** [comment]
We cannot accept a bug report without a reproducing file.

**Comment by JorjMcKie** [comment]
Please consult the documentation on [text extraction flags](https://pymupdf.readthedocs.io/en/latest/vars.html#text-extraction-flags).

**Comment by 3051360** [comment]
Thank you for your response. I see that we now have to necessarily use this flag for documents containing images.

Earlier, with version 1.22.2 the flag was not required explicitly,

![Screenshot 2024-03-24 at 5 13 29 PM](https://github.com/pymupdf/PyMuPDF/assets/131248521/e9cc9cf5-83bc-44b8-af4b-c5210139c7ce)


With version 1.24.0, the same code block does extract the image information by default,

![image](https://github.com/pymupdf/PyMuPDF/assets/131248521/f6d361ab-eeb7-4bf6-8557-1f3f1426df55)


But it does when the flag is supplied,

![image](https://github.com/pymupdf/PyMuPDF/assets/131248521/15df5c78-5536-439c-afda-287c2e6c4193)
