### ISSUE TITLE
Docs update for v1.24

### ISSUE THREAD

**Issue by stevesimmons** [pymupdf/PyMuPDF#3305]
### Description of the bug

Hi guys,

Thank you very much for the v1.24 release, especially for the support for ActualText replacements. 

I did notice that the new flag `TEXT_CID_FOR_UNKNOWN_UNICODE` that turns on this feature isn't mentioned in the docs yet (<https://pymupdf.readthedocs.io/en/latest/vars.html>, for PyMuPDFversion 1.23.26). 

On one hand, many users will now use it by default because it is now included in page.get_text()'s preset flags `TEXTFLAGS_TEXT`, `TEXTFLAGS_DICT`, etc. 

However if a user calls page.get_text() with their own combination of flags, they probably won't realise they should include `TEXT_CID_FOR_UNKNOWN_UNICODE` to avoid getting � replacement text.

### How to reproduce the bug

<https://pymupdf.readthedocs.io/en/latest/vars.html>

### PyMuPDF version

1.24.0

### Operating system

Linux

### Python version

3.11

**Comment by JorjMcKie** [comment]
Resolved in newest version of the documentation.
