### ISSUE TITLE
Text containing capital 'ET' not appearing as annotation

### ISSUE THREAD

**Issue by milicanikolic** [pymupdf/PyMuPDF#3306]
### Description of the bug

When freetext_annotation text contains capital ET, the annotation is not displayed (works with lowercase).

### Non-working example
`
import fitz

doc = fitz.open()
page = doc.new_page()
width = page.rect.width
height = page.rect.height

footer_rect = fitz.Rect(0, 0, width, 50)
footer_rect.y0 = height - footer_rect.height
footer_rect.y1 = height

page.add_freetext_annot(footer_rect, "11:30AM ET", fontsize=10, fontname="Times-Roman", text_color=(0, 0, 1), align=0)
doc.save("ET_test_example.pdf")
`

### Working example
`
import fitz

doc = fitz.open()
page = doc.new_page()
width = page.rect.width
height = page.rect.height

footer_rect = fitz.Rect(0, 0, width, 50)
footer_rect.y0 = height - footer_rect.height
footer_rect.y1 = height

page.add_freetext_annot(footer_rect, "11:30AM et", fontsize=10, fontname="Times-Roman", text_color=(0, 0, 1), align=0)
doc.save("et_lowercase_test_example.pdf")
`

[ET_test_example.pdf](https://github.com/pymupdf/PyMuPDF/files/14747623/ET_test_example.pdf)
[et_lowercase_test_example.pdf](https://github.com/pymupdf/PyMuPDF/files/14747625/et_lowercase_test_example.pdf)

### PyMuPDF version

1.24.0

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
A stupid typo - will be fixed in next version.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.1.
