### ISSUE TITLE
insert_text not same with texts of saved pdf

### ISSUE THREAD

**Issue by HonorJay** [pymupdf/PyMuPDF#3310]
### Description of the bug

```python 
import fitz 
font=fitz.Font("cjk")
pdf_path="/example.pdf"
doc = fitz.open(pdf_path)
page = doc.load_page(0)
page.insert_font(font_name="F0", fontbuffer=font.buffer)
writer = page.new_shape()
font_size= 10
coordinates = (150, 150)
writer.insert_text(coordinates, "test text", fontsize=font_size, fontnamr="F0", render_mode=3)
writer.commit()
doc.save("/result.pdf")
```

this code is pseudo code to explain my code. whatever. i tried to insert text with English and Korean characters. so i used cjk font and it's buffer. it was great till i tried doc.get_page_text(0) every character was good. but i downloaded the result.pdf file and opened it by adobe Acrobat pro, boom. characters got broken. i copied all text from result.pdf file and pasted it on notepad.  it exactly difference with doc.get_page_text(0). so i don't know why is it different. is there any problem? what's wrong with it. 

### How to reproduce the bug

well.

### PyMuPDF version

1.23.8 or earlier

### Operating system

Linux

### Python version

3.8

**Comment by JorjMcKie** [comment]
We cannot accept a bug report without data to reproduce the problem.
Please provide working code or a PDF example.
I have just verified that correct coding using that CJK font does work and yield a PDF usable by the usual PDF viewers.

**Comment by JorjMcKie** [comment]
Closed for lack of reproducibility.
Please feel free to reopen once you can demonstrate an error.
