### ISSUE TITLE
Setting RadioButton values to 'Off' doesn't set them to off after the file is saved

### ISSUE THREAD

**Issue by ag-gaphp** [pymupdf/PyMuPDF#3314]
Moving my reply from #2333 because this seems like a regression according to #711.

I have 2 in a document, and I can change almost any other property of the radio buttons without issue and see those changes reflected after a `doc.save(path, garbage=1)`. The only change I am unable to affect is the value of the radios.

System info:
* PyMuPDF v1.23.26, v1.24.0
* Python v3.12.2
* Windows 10 Pro
* Using a venv in VSCodium

I have 2 radio buttons in a group, the only 2 on the page. Here is their info according to PyMuPDF:

```python
>>> fdoc = fitz.open(doc_path)
>>> page = fdoc.load_page(0)
>>> btn1 = page.load_widget(66)
>>> btn2 = page.load_widget(69)
>>> btn1.button_states()
{'normal': ['Off', '1'], 'down': None}
>>> btn2.button_states()
{'normal': ['Off', '2'], 'down': None}
>>> print(btn1.field_value, ", ", btn2.field_value)
Off, 2
```

This is how they read when I first export from LibreOffice Draw. Then I do the following:

```python
>>> btn2.field_value = 'Off'
>>> btn2.update()
>>> btn2.field_value
'Off'
```

It appears to be off. However, when I save the file and open in any PDF viewer, `btn2` is _always_ selected. This is whether I set both values to `Off`, `False`, `True`, anything. No matter the combination I've tried to turn both of them off, or at least check `btn1` instead of `btn2`, it never actually changes in the saved PDF even though PyMuPDF is reporting that the value has changed just before saving.

Attaching the PDF in question as it has been exported from LibreOffice, before I run my PyMuPDF script on it:
[ROI - General.pdf](https://github.com/pymupdf/PyMuPDF/files/14774965/ROI.-.General.pdf)

PDF viewers I've tested with: Firefox, Chrome, Edge, LaTeX/PDF viewer extenson in VSCodium, Adobe Acrobat Pro, Okular

_Originally posted by @ag-gaphp in https://github.com/pymupdf/PyMuPDF/discussions/2333#discussioncomment-8929529_

**Comment by ag-gaphp** [comment]
I have also confirmed similar behavior in PyMuPDF v1.24.0

The only difference now is that both of my RadioButtons are checked, even after I set them both to 'Off'.

**Comment by JorjMcKie** [comment]
This works: the two buttons are being toggled 2 times and then show the correct values.
```python
import fitz

doc = fitz.open("ROI-General.pdf")
page = doc[0]
btn1 = page.load_widget(66)
btn2 = page.load_widget(69)
print(f"btn1={btn1.field_value}, btn2={btn2.field_value} - {doc.name=}")

btn1.field_value = False
btn1.update()

btn2.field_value = True
btn2.update()

doc.save("x.pdf")
doc = fitz.open("x.pdf")
page = doc[0]
btn1 = page.load_widget(66)
btn2 = page.load_widget(69)
print(f"btn1={btn1.field_value}, btn2={btn2.field_value} - {doc.name=}")
btn1.field_value = True
btn1.update()

btn2.field_value = False
btn2.update()
doc.save("y.pdf")
doc = fitz.open("y.pdf")
page = doc[0]
btn1 = page.load_widget(66)
btn2 = page.load_widget(69)
print(f"btn1={btn1.field_value}, btn2={btn2.field_value} - {doc.name=}")
```
Original:
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/09f74de3-24cf-43a7-9858-27b8dc94c006)
x.pdf: 
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/18d4c3bb-5b4e-486a-b9ab-db1f57cb25f4)
y.pdf: 
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/e6600123-b6c5-4ea3-a72c-dcfb0ad86ae6)

**Comment by ag-gaphp** [comment]
Sorry for having the two spots of discussion, I replied in https://github.com/pymupdf/PyMuPDF/discussions/2333#discussioncomment-8931423

**Comment by ag-gaphp** [comment]
False alarm, my bad. I may have been working with a corrupted file at some point, but the takeaway is to specifically use `True`/`False` for a Radio/Checkbox when you want to turn it on/off and the backend should handle everything else appropriately.
