### ISSUE TITLE
Special character bbox report

### ISSUE THREAD

**Issue by june6423** [pymupdf/PyMuPDF#3319]
### Description of the bug

![char_bbox](https://github.com/pymupdf/PyMuPDF/assets/31475080/5f81411b-c5a8-40ab-90e0-deb39c16b1d7)

I used page.get_textpage().extractRAWDICT()['blocks'] to extract every character bbox and made visualization.

Most bboxes are correct, but some special characters and spacebar bboxes are incorrect and I want to report them.

If you look at Table 1, you can see that the bboxes of ± and blank right before it are strange. The coordinates of y2 are too high.

### How to reproduce the bug

Here's my pdf and code
[d0ra06930b.pdf](https://github.com/pymupdf/PyMuPDF/files/14785496/d0ra06930b.pdf)

```
import fitz
from PIL import Image, ImageDraw


def rescale(rect, w1, h1, w2, h2):
    return [rect[0] / w1 * w2, rect[1] / h1 * h2, rect[2] / w1 * w2, rect[3] / h1 * h2]


if __name__ == "__main__":
    src_pdf = './d0nj06267g.pdf'
    doc = fitz.open(src_pdf)
    page = doc[31]

    matrix = fitz.Matrix(3, 3)
    image = page.get_pixmap(matrix=matrix)
    image = Image.frombytes("RGB", [image.width, image.height], image.samples)
    W,H = image.width, image.height

    draw = ImageDraw.Draw(image)
    page_raw_text = page.get_textpage().extractRAWDICT()['blocks']

    for text in page_raw_text:
        for line in text['lines']:
            for word in line['spans']:
                for char in word['chars']:
                    cur_bbox = list(char['bbox'][0:4])
                    rescaled_bbox = rescale(cur_bbox,page.rect.width, page.rect.height, W, H)
                    draw.rectangle(rescaled_bbox, outline='green', width=1)
    image.save("./char_bbox.png")
```

### PyMuPDF version

1.24.0

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
This must be the wrong file, it does not contain the shown page.

**Comment by JorjMcKie** [comment]
Otherwise, your observation is not necessarily exhibiting a problem. It often occurs that a PDF creator treats special characters in a special way, such that they e.g. look correctly positioned but otherwise have a character boundary box that does not fit in the line of surrounding characters.
PyMuPDF (MuPDF) generates spaces where it seems necessary (controlled by its extraction flag bits). So accordingly, a generated space may inherit awkward bbox dimensions from the character for which it was generated.

**Comment by june6423** [comment]
I'm sorry for delayed reply.
Here's the right pdf.
[d0nj06267g.pdf](https://github.com/pymupdf/PyMuPDF/files/14817989/d0nj06267g.pdf)

If this is a font issue, I wonder I can force all fonts on the page (e.g. helvitica) to solve the issue.

**Comment by JorjMcKie** [comment]
Thanks for the file. Looking at it confirmed my previous comment, so there is no issue.
You cannot do anything about this. The characters "&#177;" and the spaces preceding them have been taken from a separate font having character bounding boxes that are not compatible with those of other characters visually on the same line - no idea why the PDF creator decided this so.
In addition, that special font has no back-translation information for the "&#177;" character, so you simply have no chance at all to get to know was is written there - except using OCR of course.
