### ISSUE TITLE
`not a dict (array)` error when attaching a document

### ISSUE THREAD

**Issue by angea** [pymupdf/PyMuPDF#332]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Attaching a file and saving the doc returns a `not a dict (array)` error.

## To Reproduce (mandatory)
From a fresh pip install, running the `embedded-import.py` [example](https://github.com/pymupdf/PyMuPDF/blob/master/examples/embedded-import.py) gives:
```
File "python2.7/site-packages/fitz/fitz.py", line 2410, in save
    return _fitz.Document_save(self, filename, garbage, clean, deflate, incremental, ascii, expand, linear, pretty, decrypt)
RuntimeError: not a dict (array)
````

## Your configuration (mandatory)
- Python 2.7.16 on Linux or Windows
- PyMuPDF 1.14.19: Python bindings for the MuPDF 1.14.0 library,
built on 2019-07-21 03:55:10

**Comment by JorjMcKie** [comment]
Error confirmed, thank you for reporting this.
Spotted the error and will upload a hot fix within 24 hours.

Just as an aside: line 37 should read
```python
doc.embeddedFileAdd(name, content, impfn, desc)
```
Ie. sequence of parameters "name" and "content" was reversed in v1.14.13.

**Comment by JorjMcKie** [comment]
You should now be able to download the hotfix as a new wheel version from PyPI, which should be named like `PyMuPDF-1.14.19.2-...`.

**Comment by angea** [comment]
The fix works fine and that's awesome (tested working on linux and windows).
Thanks a lot!

**Comment by JorjMcKie** [comment]
good!
thx for the feedback!
you may want to look at https://github.com/pymupdf/PyMuPDF-Utilities where you find similar scripts ``all-my-pics-?.py`` which allow you to either embed (your case), insert, or attach all files of a folder into one PDF for demo purposes ...

**Comment by angea** [comment]
Hey - thanks for these. Interesting examples indeed -  PyMuPDF can do a lot more than I thought!

**Comment by angea** [comment]
FYI I wrote a short article based on this small research.
https://pagedout.institute/download/PagedOut_001_beta1.pdf#page=16

Thanks again!

**Comment by JorjMcKie** [comment]
Thanks for referencing PyMuPDF in that way!
