### ISSUE TITLE
fitz.mupdf.FzErrorFormat: code=7: unknown image file format

### ISSUE THREAD

**Issue by izerui** [pymupdf/PyMuPDF#3321]
### Description of the bug

 When opening the binary content of a network image with fitz.Pixmap, you may encounter the following error:

https://file.yj2025.com/77cefac1-b5a2-48b8-a880-1da6fbefa46e.jpg

But another image will open

https://cdn.pixabay.com/photo/2023/11/09/19/36/zoo-8378189_1280.jpg

### How to reproduce the bug

 url = 'https://file.yj2025.com/77cefac1-b5a2-48b8-a880-1da6fbefa46e.jpg'
 response = httpx.get(url)
 img_pixmap = fitz.Pixmap(response.content)

### PyMuPDF version

1.23.26

### Operating system

MacOS

### Python version

3.10

**Comment by julian-smith-artifex-com** [comment]
It looks like the first image is in fact a Web/P image (despite the .jpg suffix), while the second is a jpeg. PyMuPDF does not support Web/P images - see https://pymupdf.readthedocs.io/en/latest/pixmap.html#supported-input-image-formats.

**Comment by JorjMcKie** [comment]
Confirming: 

> It looks like the first image is in fact a Web/P image (despite the .jpg suffix), while the second is a jpeg. PyMuPDF does not support Web/P images - see https://pymupdf.readthedocs.io/en/latest/pixmap.html#supported-input-image-formats.

This image is WebP format with a wrong filename extension.

**Comment by izerui** [comment]
Yes the image has the wrong suffix so fitz can't recognize it, now there is a layer of conversion in between:
 
```
img = Image.open(io.BytesIO(url_datas[mark.image_url])).convert("RGB")
          # img = img.resize((int(rect.width), int(rect.height)))
          img_stream = io.BytesIO()
          img.save(img_stream, format='JPEG')
          img_pixmap = fitz.Pixmap(img_stream)
          page.insert_image(rect, pixmap=img_pixmap, keep_proportion=False, alpha=0, xref=0,
                            rotate=rotations[index])
```

at last:

```
target_doc = fitz.open()
for item_doc in item_docs:
    target_doc.insert_pdf(docsrc=item_doc)
    if is_item_doc_close:
        item_doc.close()
return target_doc
```


But ran into another problem, if the page many times insert_image, and multiple documents to be merged by insert_pdf, will lead to the final document volume is very large, there is any way to reduce the volume of the generated pdf? Any way to reduce the size of the resulting pdf? Thank you very much!

**Comment by JorjMcKie** [comment]
What are the `Document.save()` parameters you are using?
You **_should_** take the max compression options `doc.save(..., garbage=4, deflate=True)`.

**Comment by izerui** [comment]
```
doc.save(filepath, garbage=3, deflate=True)
```

This is the way I'm using it. Do I need to change the parameters?   Thank you very much.

**Comment by izerui** [comment]
I have inserted the same images on each page, resulting in an xref for each page, so how can I avoid duplicates by referencing them?

**Comment by izerui** [comment]
> What are the `Document.save()` parameters you are using? You **_should_** take the max compression options `doc.save(..., garbage=4, deflate=True)`.

Yes, the change to 4 has reduced the size from 60MB to 9MB.

@JorjMcKie   You're right. Thank you very much. @_@!!!

**Comment by JorjMcKie** [comment]
Are you ok with closing the issue?
