### ISSUE TITLE
Older versions of PyMuPDF no longer available on PyPi

### ISSUE THREAD

**Issue by keithrozario** [pymupdf/PyMuPDF#333]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I installed 1.14.17 and used it during my testing phase, and today the build failed because the older version is no longer available on PyPi.

## To Reproduce (mandatory)
When `pip install PyMuPDF==1.14.17`

Could not find a version that satisfies the requirement PyMuPDF==1.14.17 (from versions: 1.11.2, 1.12.5, 1.13.20, 1.14.19.post2, 1.14.19.2) No matching distribution found for PyMuPDF==1.14.17

## Expected behavior (optional)
Should be installable

## Your configuration (mandatory)
Python 3.6
Pip

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient.

**Comment by wilomgfx** [comment]
Pypi says [latest release is 1.14.19](https://pypi.org/project/PyMuPDF/1.14.19/) but when we pip install it fails saying `(from versions: 1.11.2, 1.12.5, 1.13.20, 1.14.19.post2, 1.14.19.2) No matching distribution found for PyMuPDF==1.14.19`

**Comment by JorjMcKie** [comment]
Sorry for having deleted the older 1.14.x versions. They have been only marginally different - so I decided to do some cleanup ... not expecting someone would be instisting of a specific one of them.

@wilomgfx - you didn't mention any details of your configuration, so I am forced to guess. Just tried PyPI installations for Windows 10 and Linux (Ubuntu). Both worked and installed v1.14.19, automatically using wheels starting ``PyMuPDF-1.14.19.2-...``

**Comment by wilomgfx** [comment]
> Sorry for having deleted the older 1.14.x versions. They have been only marginally different - so I decided to do some cleanup ... not expecting someone would be instisting of a specific one of them.
> 
> @wilomgfx - you didn't mention any details of your configuration, so I am forced to guess. Just tried PyPI installations for Windows 10 and Linux (Ubuntu). Both worked and installed v1.14.19, automatically using wheels starting `PyMuPDF-1.14.19.2-...`

Some good old ubuntu 16.04 with python 3.5 under docker, nothing crazy.
Was able to install with `PyMuPDF=1.14.19.2`

**Comment by JorjMcKie** [comment]
Good! I promise to never again delete intermediate versions ...

**Comment by wilomgfx** [comment]
> Good! I promise to never again delete intermediate versions ...

Yeah that's pretty bad practice :P

**Comment by keithrozario** [comment]
Dude, @jbarlow83 -- I've used many PDF python packages, and yours is definitely one of the best, which is why I use it :)

It's just that when you delete the older version, my build failed, because the `requirements.txt` pointed to the older version.

Thanks for the work and the help, and again, it's an amazing package.

**Comment by jbarlow83** [comment]
@keithrozario I write pikepdf, not PyMuPDF (although I have made a few contributions to PyMuPDF). You can thank @JorjMcKie, and indirectly Artifex Software for making PyMuPDF possible.

**Comment by keithrozario** [comment]
Thanks @JorjMcKie

**Comment by JorjMcKie** [comment]
@keithrozario - thank you for the rewarding compliment.
Thanks to @jbarlow83 we are providing Linux and Mac OSX wheels these days ...
