### ISSUE TITLE
Get the transformation applied to an image

### ISSUE THREAD

**Issue by julamb** [pymupdf/PyMuPDF#335]
Hi. Thanks for a great library with loads of documentation and examples!

I'm trying to follow this example to extract images from a pdf: https://github.com/pymupdf/PyMuPDF/wiki/How-to-Extract-Images-from-a-PDF

My issue is, in some PDFs that are scans of a document, the images seems to be rotated (the export is rotated 90° compared to what I see in the .pdf). I've researched the subject a little and it looks like I could apply the inverse rotation if I could access the transformation matrix (ctm) of every image, but could not find a way to get it from either the xref or the pixmap object. Any hints?

Thanks a lot!
Julien

**Comment by JorjMcKie** [comment]
You must mean ``Page._getTransformation()``.
This method delivers the matrix applied to the **page** so that its geometry appears as presented in PyMuPDF.
If you want, send me examples with few pages where your problem persists.

**Comment by julamb** [comment]
Thanks for the quick reply! I've taken a look at the transformation matrix for my page but it doesn't seem to include any rotation. Isn't there a transformation matrix associated to the image element too? Not really familiar with how pdf layouts work.

I've sent you a document by email (unfortunately I could not find a reproduction case that).

**Comment by JorjMcKie** [comment]
I haven't yet received the document.
Unfortunately, there is more than one way how things can get rotated.

My own page method ``insertImage`` rotates by a command in the page's /Contents objects for example. To undo this kind would require writing a de-compiler of the used PDF mini-language. Which you probably do not want to do.

Then, the scanned-in image itself may contain instructions of this sort in its EXIF meta-information. There are Python packages to check this. I used ``piexif`` and PIL to do this (another context outside PyMuPDF):
```python
# read orientation value if present (img is a PIL Image)
if "exif" in img.info:
    exif_dict = piexif.load(img.info["exif"])
    orientation = exif_dict["0th"].get(piexif.ImageIFD.Orientation, 1)
else:
    orientation = 1
```

And of course you might use some heuristics: check whether the image aspect ratio width/height > 1 and the page rectangle width/height < 1?

You could print all / some PDF object definitions and include them here:

```python
xref_count = doc._getXrefLength()
for xref in range(1, xref_count):
    print("===> object:", xref)
    print(doc._getXrefString(xref))
```

This would allow to check if there is a way to detect this via PDF object inspection.

**Comment by JorjMcKie** [comment]
You could also try a different method for image extraction than in the example script.
If you have a PDF where every page is completely covered by a scanned-in image:
```python
for pno in range(len(doc)):
    img_list = doc.getPageImageList(pno) # list of all images on page pno: should only have 1 item!
    xref = img_list[0][0]  # the PDF object number of the page image
    img = doc.extractImage(xref)  # extract the image without using Pixmaps
    img_file = open("img-%i.%s" % (xref, img["ext"], "wb")
    img_file.write(img["image"])
    img_file.close()
```
This is faster, but more importantly saves the image in its **original format**, and we can hope this is **not rotated**.

**Comment by JorjMcKie** [comment]
@julamb - any reaction on your side?
