### ISSUE TITLE
LINK_NAMED is not working with annotations created by fitz

### ISSUE THREAD

**Issue by sky-code** [pymupdf/PyMuPDF#3350]
### Description of the bug

I am trying to create a named link like in this example https://github.com/pymupdf/PyMuPDF/blob/main/tests/test_named_links.py#L15 that point to newly created annotation, but link does not work.

### How to reproduce the bug

Here is a script and pdf file
```
import fitz


doc = fitz.open(
    "./two_page.pdf"
)

pages = list(doc.pages())

annot_target = pages[1].add_rect_annot(fitz.Rect(100, 100, 200, 200))
annot_target.set_colors(fill=(1, 1, 0), stroke=[])

pages[0].insert_text(
    fitz.Point(100, 100), "link", color=(98 / 255, 102 / 255, 240 / 255)
)
new_link = {
    "kind": fitz.LINK_NAMED,
    "from": fitz.Rect(100 - 10, 100 - 10, 200, 200),
    "name": annot_target.info["id"],
}
pages[0].insert_link(new_link)
doc.save(
    "./two_page_annotated.pdf"
)

```
[two_page.pdf](https://github.com/pymupdf/PyMuPDF/files/14891810/two_page.pdf)

I am expecting that link will navigate to annotation but it doesn't.

### PyMuPDF version

1.24.0

### Operating system

MacOS

### Python version

3.12

**Comment by JorjMcKie** [comment]
You can only let links point to named destinations that **_already are defined_** within the PDF.

Your PDF has no names array - therefore your script cannot work.

You can check which names are defined in a PDF via `doc.resolve_names()` which delivers a dictionary.

**Comment by sky-code** [comment]
@JorjMcKie thanks for the answer, I see you're saying

> already are defined

but want to be sure, is there any API available to create named destinations for objects created by fitz?

**Comment by JorjMcKie** [comment]
If the name exists in the PDF, then named links can be successfully created - yes.
