### ISSUE TITLE
Broken pages in saved pdf document, second example.

### ISSUE THREAD

**Issue by wz93672** [pymupdf/PyMuPDF#3367]
### Description of the bug

I have second example with isolated blank pages which breaks pdf file on save. My guess is, there is something wrong with source files, but I have tried a few different tools/libraries on them without problems. It happens with garbage=4 and garbage=3 option. Option clean=True helps, but then missing characters bug appears.
For output file Acrobat Reader gives error nr 14 “Expected a dict object”.

[in.pdf](https://github.com/pymupdf/PyMuPDF/files/14923032/in.pdf)
[out_garbage-3.pdf](https://github.com/pymupdf/PyMuPDF/files/14923030/out_garbage-3.pdf)

### How to reproduce the bug

```python
with fitz.open('in.pdf') as doc:
    doc.save('out_garbage-3.pdf', garbage=3)
``` 

### PyMuPDF version

1.24.1

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
I don't know how you made the blank pages. But common to them all is that they have no `/Contents` objects.
This irritates Adobe (only) - other viewers are tolerant as they should be. If you do this, the save works with top compression and without having to clean the file:
```python
In [21]: doc=fitz.open("in.pdf")
In [22]: for page in doc:  # check whether there are page pages without a contents object
    ...:     print(page.get_contents())
    ...:
[]
[]
[]
[]
[10]
In [23]: for page in doc:  # the empty pages are truly naked!
    ...:     if not page.get_contents():  # give them an empty content at least!
    ...:         fitz.TOOLS._insert_contents(page, b"")
    ...:
In [24]: for page in doc:  # check what happens
    ...:     print(page.get_contents())
    ...:
[149]
[150]
[151]
[152]
[10]
In [25]: doc.ez_save("x.pdf")
```
The reuslting file is 87 KB size and processed by Acrobat w/o problem.

**Comment by JorjMcKie** [comment]
The problem occurring with clean_contents()  has already been reported to MuPDF.
