### ISSUE TITLE
When calling subset_fonts from multiple threads, an error occurs : No such file or directory: '/tmp/newfont.ttf'

### ISSUE THREAD

**Issue by izerui** [pymupdf/PyMuPDF#3369]
### Description of the bug

```
future = pool.submit(...)
```

```
chn_fontname = 'chn'
font_buffer = read_bytes_from_file(
    os.path.join(os.path.abspath(os.path.dirname(__file__)), 'fonts', 'FangZhengHeiTiJianTi-1.ttf'))

font = Font(fontname=chn_fontname,
            fontbuffer=font_buffer,
            language='zh-Hans')

page.insert_font(fontname=chn_fontname,
                         fontbuffer=font.buffer)
# cause error
doc.subset_fonts()
```

### How to reproduce the bug

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fitz/utils.py", line 5491, in build_subset
    os.remove(newfont_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/newfont.ttf'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fitz/utils.py", line 5486, in build_subset
    os.remove(oldfont_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/oldfont.ttf'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fitz/utils.py", line 5481, in build_subset
    os.remove(uncfile_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/uncfile.txt'
../usr/local/lib/python3.10/site-packages/fitz/__init__.py:100:exception_info: exception_info:
Traceback (most recent call last):

### PyMuPDF version

1.24.1

### Operating system

MacOS

### Python version

3.10

**Comment by JorjMcKie** [comment]
PyMuPDF does not support threading!
Use Python module `multiprocessing` instead. Otherwise, please see my comments in Discussion item #3368.

**Comment by izerui** [comment]
Yes, I've found that all in-memory operations based on pymupdf can be multithreaded, but when it comes to using system fonts or calling system files for io operations, multithreading can be problematic. Looking forward to your replacement for fontTools... thanks a lot...
