### ISSUE TITLE
Every object is inserted upside down with "Microsoft: Print To PDF" property

### ISSUE THREAD

**Issue by Samuraiwarm** [pymupdf/PyMuPDF#337]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
On inserting anything (text, textbox, image, etc.) in the existing page (not new page), everything that is inserted is upside down (mirrored up and down)

## To Reproduce (mandatory)
Files:
[pdf_using_microsoft_pdf_printer.pdf](https://github.com/pymupdf/PyMuPDF/files/3452049/pdf_using_microsoft_pdf_printer.pdf)
sample_image.jpg
![sample_image](https://user-images.githubusercontent.com/24846011/62216174-76413600-b3d2-11e9-8255-14b18d5b7a53.jpg)
```python
import fitz
doc = fitz.open('pdf_using_microsoft_pdf_printer.pdf')

page = doc[0]
A4 = fitz.PaperSize("A4")

signature_image = fitz.Pixmap("sample_image.jpg")
page.insertImage(fitz.Rect(10,10,400,400),pixmap=signature_image,overlay=True)

doc.save("output1.pdf")

```

## Expected behavior (optional)
Image should be upright, not reversed

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/24846011/62216293-aab4f200-b3d2-11e9-9322-6e19aa17d48c.png)

![image](https://user-images.githubusercontent.com/24846011/62216565-29aa2a80-b3d3-11e9-8bcd-387447078084.png)

## Your configuration (mandatory)
 - Ubuntu 18.04.2 LTS
 - Python 3.6.8
```
>>> fitz.version
('1.14.19', '1.14.0', '20190729135612')
```
- Installed by `pip3 install PyMuPDF

```
>>> print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] 
 linux 
 PyMuPDF 1.14.19: Python bindings for the MuPDF 1.14.0 library,
built on 2019-07-29 13:56:12
```

## Additional context (optional)
Works perfectly fine if I add an image in the new page, not existing page.

**Comment by piyapan039285** [comment]
+1 I have this problem too.

**Comment by JorjMcKie** [comment]
I think I know what it is.
The PDF page is defining its own "geometry", but in an **_unclean_** way. Look at [this](https://pymupdf.readthedocs.io/en/latest/faq/#misplaced-item-insertions-on-pdf-pages) section of the documentation for technical and a number of solutions.
You can probably heal your issue by simply executing method ``page._cleanContents()`` **before your first** item insertion.

**Comment by JorjMcKie** [comment]
Just confirming: the above suggestion solves the issue ...

**Comment by JorjMcKie** [comment]
@piyapan039285 / @Samuraiwarm - your issues solved?

**Comment by Samuraiwarm** [comment]
It works now! I've been trying various possible formats I could think of:
from LibreOffice, Microsoft (Word, PowerPoint, Excel) - both also works.
Thank you!

**Comment by JorjMcKie** [comment]
Good - I am glad to hear this!
One might wonder, why this is not done automatically by PyMuPDF. The reasoning is detailed out in the documentation. The biggest objections are performance implications (``Page._cleanContents()`` indeed does a lot of things ...) and a negative impact if you want to do incremental updates.

I will be publishing a little utility function in the next version: it checks whether there exists a wrapping ``q ... Q`` around the ``/Contents`` objects. This will at least give some preventive indication for doing a contents cleaning - although the false alarms will still prevail. Inevitable however - as long as you do not write your own full-blown contents syntax checker.

**Comment by AlexRederstein** [comment]
> I think I know what it is. The PDF page is defining its own "geometry", but in an **_unclean_** way. Look at [this](https://pymupdf.readthedocs.io/en/latest/faq/#misplaced-item-insertions-on-pdf-pages) section of the documentation for technical background and a number of solutions. You can probably heal your issue by simply executing method `page._cleanContents()` **before your first** item insertion.

you are my super hero now
