### ISSUE TITLE
Tesseract Initialization Error with `get_textpage_ocr`

### ISSUE THREAD

**Issue by tevfikcagridural** [pymupdf/PyMuPDF#3374]
### Description of the bug

Hello,

First, thank you for your hard works. It's a great library.

The function `get_textpage_ocr` returns `fitz.mupdf.FzErrorLibrary: code=3: OCR initialisation failed` error. Even though, it looks like a tesseract error I was able to extract image with `get_page_images` and then get the text with `pytesseract.image_to_string(img, lang='tur')`

### How to reproduce the bug

The following function returns the error at the `page.get_textpage_ocr(language='tur')` step
```python
def txt_extract_builtin(file):
    doc = fitz.open(file)
    text = ''
    for page in doc:
        tp = page.get_textpage_ocr(language=' tur')
        page_text = page.get_text(textpage=tp)            
        text += page_text
```

But  this function runs without a problem and extracts all of the texts from all the pages
```python
def txt_extract_pytesseract(file):    
    doc = fitz.open(file)
    image_bytes_list = []
    for i in range(len(doc)):
        for img in doc.get_page_images(i):
            xref = img[0]
            pix = fitz.Pixmap(doc, xref)
            image_bytes_list.append(pix.tobytes())
    
    text = ''    
    for img in image_bytes_list:
        img = Image.open(BytesIO(img))
        config = "/usr/local/share/tessdata"
        text += pytesseract.image_to_string(img, lang='tur', config=config)
```

I did set `os.environ["TESSDATA_PREFIX"] = "/usr/local/share/tessdata"` or `/usr/local/Cellar/tesseract/5.3.4_1/share/tessdata` before importing fitz. Referring to [the discussion post #2439](https://github.com/pymupdf/PyMuPDF/discussions/2439)

<details>
  <summary>py file contents</summary>
  
  ```python
# The tesseract environment variable must be set before importing flitz. Resource: https://github.com/pymupdf/PyMuPDF/discussions/2439
import os
os.environ["TESSDATA_PREFIX"] = "/usr/local/share/tessdata"

from PIL import Image
import fitz
import pytesseract
from io import BytesIO
        
def txt_extract_pytesseract(file):    
    doc = fitz.open(file)
    image_bytes_list = []
    for i in range(len(doc)):
        for img in doc.get_page_images(i):
            xref = img[0]
            pix = fitz.Pixmap(doc, xref)
            image_bytes_list.append(pix.tobytes())
    
    text = ''    
    for img in image_bytes_list:
        img = Image.open(BytesIO(img))
        config = "/usr/local/share/tessdata"
        text += pytesseract.image_to_string(img, lang='tur', config=config)
            
    return text


def txt_extract_builtin(file):
    doc = fitz.open(file)
    text = ''
    for page in doc:
        tp = page.get_textpage_ocr(language=' tur')
        page_text = page.get_text(textpage=tp)            
        text += page_text
        
    return text

if __name__ == '__main__':
    file = '20240405-22.pdf'
    # txt = txt_extract_ocr(file) # Raising error
    # txt = txt_extract_tesseract(file) # Working
  ```
</details>

Sample pdf:
[20240405-22.pdf](https://github.com/pymupdf/PyMuPDF/files/14949825/20240405-22.pdf)

# Configuration
MacOS: Sonoma 14.4.1
Python: 3.11.5
pytesseract: 0.3.13 (installed via pip)
tesseract: 5.3.4 (installed via homebrew)
PyMuPDF: 1.24.1 (installed via pip)

### PyMuPDF version

1.24.1

### Operating system

MacOS

### Python version

3.11

**Comment by julian-smith-artifex-com** [comment]
In your code it says `language=' tur'`. Could the leading space be causing the problem?

**Comment by JorjMcKie** [comment]
Please check
1. correct language specification
2. your tesseract has Turkish support `--list-lang`

You don't special support for Turkish probably. Tried your script w/o language parameter and it worked.

**Comment by tevfikcagridural** [comment]
> In your code it says `language=' tur'`. Could the leading space be causing the problem?
 It is the leading space 🤦 . Thank you
