### ISSUE TITLE
Impossible to install with pip3 if specifying version 1.14.19

### ISSUE THREAD

**Issue by sfavre-dp** [pymupdf/PyMuPDF#339]
Pymupdf package won't install when doing `pip3 install pymupdf==1.14.19`, It says the package does not exist.
The problem can be fixed by doing `pip3 install pymupdf==1.14.19.2` but this breaks a check we have in our code that looks for availability of python packages using pypi web site, as 1.14.19.2 is registered in pypi as 1.14.19.

 - Operating system : Ubuntu 18.04 fully updated
 - Python version : 3.6.8

**Comment by JorjMcKie** [comment]
Duplicate of #342

**Comment by JorjMcKie** [comment]
please switch to new version 1.14.20 just uploaded
