### ISSUE TITLE
Does pymupdf cut the pdf by the page of file? Or it separate the pdf file by it own rules?

### ISSUE THREAD

**Issue by HuXinjing** [pymupdf/PyMuPDF#3395]
I use pymupdf to handle my pdf file, but I find _fitz.open()_ give me more pages than the file does. So in what kind of situation the program will divide the original page? And I feel confused, if the program do not divide the file by it orignal order of pages,  will _page.get_pixmap(matrix=mat, alpha=False, clip=clip)_ work correctly?

example here 
[FOMC19900207meeting.pdf](https://github.com/pymupdf/PyMuPDF/files/15014256/FOMC19900207meeting.pdf)
This file has 58 pages, but I got 84 from _len(fitz.open(input))_

**Comment by JorjMcKie** [comment]
I don't understand what you are talking about:
```python
import fitz
doc=fitz.open("FOMC19900207meeting.pdf")
doc.page_count
58
len(doc)
58
```
The same number is given by every PDF viewer.

**Comment by HuXinjing** [comment]
> I don't understand what you are talking about:
> 
> ```python
> import fitz
> doc=fitz.open("FOMC19900207meeting.pdf")
> doc.page_count
> 58
> len(doc)
> 58
> ```
> 
> The same number is given by every PDF viewer.

Sorry, it's my misstake. I miswrited filename.
