### ISSUE TITLE
get_pixmap cannot get full image

### ISSUE THREAD

**Issue by tangent2018** [pymupdf/PyMuPDF#3399]
### Description of the bug

Hello, Jorj

I want to convert pdf to jpg, first page can be converted but the second cannot.

### How to reproduce the bug

```code
pdf_path = Path(r'sample.pdf')
doc = fitz.open(str(pdf_path))
for i, page in enumerate(doc):
    trans = fitz.Matrix(2, 2).prerotate(0)
    pm = page.get_pixmap(matrix=trans, alpha=False)
    jpg_path = f'{pdf_path.stem}_{i}.jpg'
    pm.save(jpg_path)
```
[sample.pdf](https://github.com/pymupdf/PyMuPDF/files/15022853/sample.pdf)
![result_0](https://github.com/pymupdf/PyMuPDF/assets/36388333/d736eb2d-3add-4acf-b67b-a3dd16661161)
![result_1](https://github.com/pymupdf/PyMuPDF/assets/36388333/a21d64c1-9df0-4d03-9f37-56aed5ebf75c)

### PyMuPDF version

1.23.x or earlier

### Operating system

Windows

### Python version

3.8

**Comment by JorjMcKie** [comment]
You must have received a lot of error messages when making the pixmap of page 2: "MuPDF error: syntax error: unknown colorspace: R9".
The color space is not supported, respectively its definition is syntactically wrong.
