### ISSUE TITLE
Question / Comment:Problems about using gettext()and getPagetext()!

### ISSUE THREAD

**Issue by xp449** [pymupdf/PyMuPDF#340]
Dear sir:
Thanks you a lot to offer me this amazing projects to help me handle some .PDF files. But now I have got some problems in using the gettext() or getPagetext() methods.
when I use showPDFpage() methods to splits the 1 page in 1 PDF document, for example the demo you offered in here [posterize.py]. I split 1 page into 4 pages ,bu when I use gettext() or getPagetext try to get the text in each pages , the return of the strings are always the the total text of the page before split , plz help me to handle this problems cause I want to split also the text into 4 part same as the 4 pages. 
thanks a lot!

**Comment by JorjMcKie** [comment]
Thanks for the compliments ...
Unfotunately there is no way to avoid this. Apart from text, also any images of the shown PDF page are included in all relevant methods of the displaying page.
You have to create code yourself to down select stuff. Use ``Page.getTextWords`` or ``Page.getText("dict")`` to exclude elements not inside the clipped area of the shown page part.
You may want to look at [textboxextraction](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/textboxtract.py) for a way to do that.

**Comment by xp449** [comment]
Thanks a lot,I have followed your suggestion to solved my problems and get what I want immediately.Thank you! But could you plz tell me why this happens? Why I couldn't get the text I want in certain pages.

**Comment by JorjMcKie** [comment]
``page.showPDFpage()`` import the full PDF definition of the referenced page into the target PDF - not just a page image.
So you _**enrich**_ the target PDF page with everything that the shown PDF page contains: text, images, any new fonts, etc., etc.
If this is not what you want, you can always create a pixmap image of the source page (or parts of it via the pixmap ``clip`` parameter) and display it in the target page via ``page.insertImage()``. This will then be a rasterized image of the source page, whereas ``showPDFpage`` inserts a vector image.

So you do have a number of alternatives ...

**Comment by JorjMcKie** [comment]
close this issue?

**Comment by xp449** [comment]
OK. merci beaucoup!

**Comment by JorjMcKie** [comment]
Aucune cause!
