### ISSUE TITLE
Cannot add Widgets containing inter-field-calculation JavaScript

### ISSUE THREAD

**Issue by JorjMcKie** [pymupdf/PyMuPDF#3402]
### Description of the bug

When adding a widget containing an `AA/C` JavaScript entry (inter field calculation), an exception like this occurs: `fitz.mupdf.FzErrorArgument: code=4: not an array (null)`.

### How to reproduce the bug

Executing this script produces the exception: 
[interfield-calculation.zip](https://github.com/pymupdf/PyMuPDF/files/15047877/interfield-calculation.zip)

### PyMuPDF version

1.24.2

### Operating system

All

### Python version

All

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.3.
