### ISSUE TITLE
find_tables doesn't recognize any table in scanned document

### ISSUE THREAD

**Issue by RodrigoTomeES** [pymupdf/PyMuPDF#3403]
### Description of the bug

Hi,

We are trying to get the tables of this scanned document as [this](https://github.com/pymupdf/PyMuPDF/files/15052782/RE2.pdf) but find_tables doesnt recognize any one. We tried to use also `page.find_tables(horizontal_strategy="text", vertical_strategy="text")` as mention [here](https://medium.com/@pymupdf/yes-pymupdf-can-be-used-to-extract-tables-from-scanned-images-731c7557b59e).

### How to reproduce the bug
```python
import fitz  # import package PyMuPDF
import os

# Open some document, for example a PDF (could also be EPUB, XPS, etc.)
doc = fitz.open("RE2.pdf")

for page in doc:
  # Look for tables on this page and display the table count
  tabs = page.find_tables()

  for table in tabs.tables:
    print(table.to_pandas())
  print(f"{len(tabs.tables)} table(s) on {page}")

# We will see a message like "1 table(s) on page 0 of input.pdf"
```

### PyMuPDF version

1.24.2

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
As answered in Discord: no such can-do!
