### ISSUE TITLE
page.find_tables() is taking high CPU.

### ISSUE THREAD

**Issue by AniketModi** [pymupdf/PyMuPDF#3404]
### Description of the bug

When we do the processing of each page of the pdf one by one and use find_tables(), cpu is going very high. Also, while doing the processing of multiple pages at once, it is going very high. So, concurrent is also not possible.

### How to reproduce the bug

Load the attach the pdf and process each page one by one and use the page.find_tables()
[annual-report-2022-2023.pdf](https://github.com/pymupdf/PyMuPDF/files/15053266/annual-report-2022-2023.pdf)

### PyMuPDF version

1.24.2

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
Sorry, but this is a very complex document and thus requires a lot of resources to process. It is not apparent that a guaranteed service is not being provided.
So it is not a defect.
I tried other table processing packages, and they either do not recognize tables at all, or if they do, consume even higher CPU power.
I also have seen that you have adequately opened a Discussions item.
