### ISSUE TITLE
MuPDF error: syntax error: unknown keyword: '4.48823e'

### ISSUE THREAD

**Issue by Supercarry-khr** [pymupdf/PyMuPDF#3409]
Hi, I wonder what causes this error: MuPDF error: syntax error: unknown keyword: '4.48823e'
Thanks!

**Comment by JorjMcKie** [comment]
Please do provide more information!

**Comment by julian-smith-artifex-com** [comment]
Is this #3381 ?

**Comment by JorjMcKie** [comment]
Closed for lack of reaction in due time.
