### ISSUE TITLE
missing attribute set_dpi()

### ISSUE THREAD

**Issue by tobiasfarmerenemy** [pymupdf/PyMuPDF#3414]
### Description of the bug

I want to create a pixmap from an annot and adapt the resolution with the "dpi" argument as stated in the docs.
However, this is creating an 

Attribute Error: 'FzPixmap' object has no attribute 'set_dpi'

is this a bug?

### How to reproduce the bug

annot.get_pixmap(dpi=10)

### PyMuPDF version

1.24.2

### Operating system

Windows

### Python version

3.11

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.3.
