### ISSUE TITLE
stamp annotation from pixmap/file

### ISSUE THREAD

**Issue by tobiasfarmerenemy** [pymupdf/PyMuPDF#3415]
**Describe the solution you'd like**
I woulk like to add stamp annotations like the method Page.add_stamp_annot() does.
However I would like to use different stamps than the standard ones in the library. 

Ideally this could be performed using a pixmap object or an imported file (jpg/png)

I'd be very happy if there's a possibility to implement that feature

**Comment by JorjMcKie** [comment]
We do not plan to do this in PyMuPDF.
Only in case MuPDF would decide to extend annotation handling in this way, PyMuPDF can even **_consider_** to adjust its support accordingly.
Please voice your requirement in MuPDF's public [Discord](https://discord.gg/A33YqpgX) channel. If you are a commercial customer, please do not forget to add your customer number.
