### ISSUE TITLE
Re-introduced bug, text align add_redact_annot

### ISSUE THREAD

**Issue by cajmorgan** [pymupdf/PyMuPDF#3418]
### Description of the bug

https://github.com/pymupdf/PyMuPDF/issues/1286

Hello, the same bug is introduced, I downgraded to 1.23.5 and there it works as expected

### How to reproduce the bug

https://github.com/pymupdf/PyMuPDF/issues/1286

### PyMuPDF version

1.24.2

### Operating system

MacOS

### Python version

3.10

**Comment by JorjMcKie** [comment]
A typo has been corected.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.4.
