### ISSUE TITLE
PyMuPDF failed to extract bw images

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [pymupdf/PyMuPDF#3423]
### Description of the bug

Pdfimages can extract three images from test.pdf. One of the three images is a pbm image.

But the program extractimg.py can only find two images, with the pbm image missing. Is this a bug in page.get_images()?

$ ./extractimg.py test.pdf
[+] Found a total of 2 images in page 0
Image mode: RGB
jpx
Image mode: RGB
jpx

[test.pdf](https://github.com/pymupdf/PyMuPDF/files/15149484/test.pdf)

extractimg.py:

```
#!/usr/bin/env python3

import sys
import fitz
pdf_file = fitz.open(sys.argv[1])

from PIL import Image
import io

for page_index in range(len(pdf_file)): 
	# get the page itself 
	page = pdf_file[page_index] 
	# help(page)
	image_list = page.get_images() 
	
	# printing number of images found in this page 
	if image_list: 
		print( 
			f"[+] Found a total of {len(image_list)} images in page {page_index}") 
	else: 
		print("[!] No images found on page", page_index) 

	for image_index, img in enumerate(page.get_images(), start=1): 
	
		# get the XREF of the image 
		xref = img[0] 
	
		# extract the image bytes 
		base_image = pdf_file.extract_image(xref) 
		image_bytes = base_image["image"] 

		image = Image.open(io.BytesIO(image_bytes))
		if image.mode in ("1", "L"):
			print("Image is likely black and white")
		else:
			print("Image mode:", image.mode)
	
		# get the image extension 
		image_ext = base_image["ext"] 
		# print(image_bytes, image_ext)
		print(image_ext)
```

### How to reproduce the bug

See above.

### PyMuPDF version

1.24.1

### Operating system

MacOS

### Python version

3.11

**Comment by prRZ5F4LXZ** [comment]
Let's put the question in another way. How to extract the third image as pdfimags does in PyMuPDF?

**Comment by JorjMcKie** [comment]
You can extract all images via `doc.extract_image(xref)`. This is a dictionary from which you can save the binary using e.g. pathlib:
```python
img = doc.extract_image(xref)
pathlib.Path(f"img{xref}.{img['ext']}").write_bytes(img["image"])
```
Sometimes the file extension img["ext"] may not suitable for a mask image. In that case extract via `pix = fitz.Pixmap(doc, xref)`.
The do `pix.save("img.png")`. This should mostly work.

**Comment by prRZ5F4LXZ** [comment]
```
import sys
import fitz
doc = fitz.open(sys.argv[1])

import pathlib

for page_index in range(len(doc)): 
	for xref, smask, width, height, *_ in doc.get_page_images(page_index):
		if smask:
			pix = fitz.Pixmap(doc, smask)
			pix.save("img.png")
			# img = doc.extract_image(smask)
			# pathlib.Path(f"img{xref}.{img['ext']}").write_bytes(img["image"])
```

I tried both methods. The one based on pathlib save a jb2 file. But I can not view this file.

pix.save does save a png file. But it is a 8-bit grayscale. However, pdfimages only generate pbm which is 1 bit per pixel. Why is there such a discrepancy? How to directly generate a pbm file?

$ file img.png 
img.png: PNG image data, 3021 x 4118, 8-bit grayscale, non-interlaced

**Comment by JorjMcKie** [comment]
You can do this:
```python
pix23 = fitz.Pixmap(doc, 23)  # a pixmap wwith colorspace None because it is a mask
# convert to a monochrome pixmap:
pix = fitz.Pixmap(fitz.csGRAY, pix23.w, pix23.h, pix23.samples, 0)
pix.save("monochrome.pgm")  # save as portable graymap
```

**Comment by prRZ5F4LXZ** [comment]
Why does it have to be pgm? Can it be pbm just as pdfimages does?

**Comment by JorjMcKie** [comment]
> Why does it have to be pgm? Can it be pbm just as pdfimages does?

You can name it the way you like. PBM is simply the wrong extension, that's all.

**Comment by prRZ5F4LXZ** [comment]
No. I use your method to save the file as pbm. The file size is 12MB. But pdfimage only save a pbm file of 1.5MB. So they are not the same. In the file generated by pdfimage, it is 1 pixel 1 bit. In the file generated by your code, it is 1 pixel 8 bits.

**Comment by prRZ5F4LXZ** [comment]
I printed pix.w, pix.h and len(pix.samples). They are 3021 4118 12440478.

3021*4118=12440478

Therefore, the problem is with `pix = fitz.Pixmap(doc, smask)`. It saves a bit as a byte. Is there a way to let fitz.Pixmap to save a bit as a bit instead of as a byte?

**Comment by JorjMcKie** [comment]
No there is not. Use a different library like PIL for this.
