### ISSUE TITLE
Question / Comment: How to get \n, \t, \r of pdf and convert pdf to text file in same format as pdf does ?

### ISSUE THREAD

**Issue by fuserabin** [pymupdf/PyMuPDF#343]

**Comment by JorjMcKie** [comment]
Don't fully understand.
Have you read the documentation about the various text extraction methods: ``getText``, ``getTextWords``, ``getTextBlocks``? Specifically ``getText("dict")`` contains everything you need for what I deduct from your question.
After that, you should also look at chapter [text](https://pymupdf.readthedocs.io/en/latest/faq/#text) of the manual.

**Comment by fuserabin** [comment]
Yaa, you are right, the main problem that I am facing is, whenever I am trying to convert pdf to text but it's not generating the same format as pdf does, so What can I do for that ?

**Comment by JorjMcKie** [comment]
Well, you have to be painstakingly dilligent to achieve this! Sorry, but (apart from text **_color_**), you find **all** information in the dictionaries ``page.getText("dict")`` or ``page.getText("rawdict")`` - down to single letters if you want: position, font fontsize, writing direction, ...
You can also output a page in HTML format if that helps you. But even then (this is unmodified original MuPDF code basically) you will notice more or less subtle differences.

**Comment by JorjMcKie** [comment]
If the right font is not you problem (which I am assuming because you speak of **_text_** output), then relative text positions, line breaks and such are your problem.
Look at the chapter reference above to find an example for extraction text contained in some rectangle more or less faithfully.

**Comment by fuserabin** [comment]
Yes but it would be great if there is any way that I could get information about \n, \r, \t with text extraction, thank you !

**Comment by JorjMcKie** [comment]
The various flavors of ``getText*()`` is all there is.
But you can influence the way how MuPDF interprets the text. To do this, you must pay a price of a little higher complexity and can no longer you the shortcut which these methods incarnate:

Look at [this](https://pymupdf.readthedocs.io/en/latest/coop_low/) chapter. You can play with the indicators ``fitz.TEXT_PRESERVE_LIGATURES, fitz.TEXT_PRESERVE_WHITESPACE, fitz.TEXT_PRESERVE_IMAGES`` to influence this behaviour.
