### ISSUE TITLE
Redact/Replace

### ISSUE THREAD

**Issue by Singrig** [pymupdf/PyMuPDF#344]
Hi ,
Pymupdf is really a great package to work with PDF's and other type of formats..

I have a quick question, I need to redact the sensitivity information from PDF, Is there any function related to redact or can we replace the words in PDF while highlighting?

**Comment by JorjMcKie** [comment]
The new MuPDF version 1.16.0 also supports Redact annotations.
I haven't decided yet, whether / when to include support for this also in PyMuPDF.
Currently I am still in v1.16.0 development.
Quite a big update to the current v1.14.x unfortunately.

**Comment by JorjMcKie** [comment]
What do you mean by "sensitivity"? Encryption?
PyMuPDF v1.16.0 will definitely fully support password-based encryption / decryption and permission levels.

**Comment by Singrig** [comment]
Sorry I'm confused Mupdf as redacting the specific words in PDF ? Can you please share some link?

Let's consider a eg, if PDF has Customer name either I need to redact that customer name or I need to replace with some junk letters

**Comment by JorjMcKie** [comment]
No, we are talking about different things. Redact annotations are part of the most recent PDF specification.
What you want is not supported at all by MuPDF - sorry.
I have written an anonymizer going in that direction some time ago. This is significant effort going far beyond what this repository has to offer.

**Comment by Singrig** [comment]
Sorry for bothering you, can't we delete/replace those specific words using pymupdf?

**Comment by JorjMcKie** [comment]
No, this already goes fairly deep into how text is coded in a PDF. In the absolutely most simple cases you might even treat the PDF as a text file and use some editor.

Of course you can always cover sensitive things with - say - a black rectangle. But that is cosmetics only: the information is still there.
A text like "Mr. Anonymous" might be coded in a plethora of ways in unfortunate circumstances: hexadecimal, each single letter being separated from each other and not in natural reading sequence, the text may be split across several lines, ... and what not.

**Comment by Singrig** [comment]
Can you please share some code or some links that can help to achieve as u suggested like making it into not in natural reading seq or split across line...

**Comment by JorjMcKie** [comment]
Read chapter [text](https://pymupdf.readthedocs.io/en/latest/faq/#text), specifically about textbox text extraction to see how a natural reading order can be re-established.
And of course you should look at the original PDF spec manual to see examples for how complex a simingly simple text may be coded. For example, the PDF manual for this repo on page 9 looks like:

![grafik](https://user-images.githubusercontent.com/8290722/62717812-94aac100-b9d2-11e9-964f-44132d708ff5.png)

and the highlighted text is coded like this in the PDF file:
```
BT\n/F38 9.9626 Tf 72 462.176 Td [(PyMuPDF)]TJ/F52 9.9626 Tf 45.81 0 Td [(is)-270(a)-270(Python)-270(binding)-270(for)]TJ
```

I cannot share the code I developed in the above mentioned case, because that was paid work and I thus do not own the copyright.

**Comment by Singrig** [comment]
Thanks this will help me... Let me check what I can do... The difficulty would be I'm very new to this Field

**Comment by Singrig** [comment]
Hi

**Comment by JorjMcKie** [comment]
you are not using the current version - please switch to 1.14.20

**Comment by JorjMcKie** [comment]
@Singrig - the new v1.16.11 supports redaction annotations.

**Comment by Singrig** [comment]
Thanks McKie,hope the more details I can find in PyMupdf docs

**Comment by JorjMcKie** [comment]
@Singrig - sure you will. The new documentation is already uploaded. I am about to also populate PyPI with the installation material.

**Comment by Singrig** [comment]
Cool that will help a lot
