### ISSUE TITLE
get_pixmap function removes the table and leaves just the content behind

### ISSUE THREAD

**Issue by anirudhagarwal1** [pymupdf/PyMuPDF#3448]
### Description of the bug

I have a single page pdf file which has a table inside it. When I load the pdf and try to call the get_pixmap function, it just keeps the content and removes the table around it. 

`pix = page.get_pixmap(alpha=False, dpi=150)
        image = Image.open(io.BytesIO(pix.tobytes()))
        image.save("temp.jpeg", format='jpeg')`

Unfortunately, I won't be able to share to share this particular pdf on an open platform, would you be able to suggest how can I further debug it? 

Sharing the part of screenshot of this pdf and the converted image. 
PDF - 
<img width="1084" alt="Screenshot 2024-05-08 at 1 41 06 AM" src="https://github.com/pymupdf/PyMuPDF/assets/85726789/f5768b9c-eddf-415f-b360-1b2f971fdc00">

Image from it - 
<img width="881" alt="Screenshot 2024-05-08 at 1 42 34 AM" src="https://github.com/pymupdf/PyMuPDF/assets/85726789/284cc8b5-baeb-4fbf-ad88-4d4b5b826f0c">

### How to reproduce the bug

Seems to be breaking only in this particular kind of PDF. Seems to be working fine elsewhere. 

### PyMuPDF version

1.24.1

### Operating system

MacOS

### Python version

3.10

**Comment by JorjMcKie** [comment]
Providing the example file (not just the pictures) is mandatory for submitting a bug.

**Comment by anirudhagarwal1** [comment]
Since this document contains some sensitive information, I would not able to share it on a public forum. I tried to replicate this issue with multiple other PDFs and wasn't able to. 

Would you consider if I could mail it to you privately?

**Comment by JorjMcKie** [comment]
> Since this document contains some sensitive information, I would not able to share it on a public forum. I tried to replicate this issue with multiple other PDFs and wasn't able to.
> 
> Would you consider if I could mail it to you privately?

Yes, certainly! Please do use this way.

**Comment by mjun0812** [comment]
I have the same issue.
When processing a PDF of this paper, the title and table borders were removed.
https://arxiv.org/abs/2310.19909
This problem does not occur when using v1.23.26.

**Comment by JorjMcKie** [comment]
> I have the same issue. When processing a PDF of this paper, the title and table borders were removed. https://arxiv.org/abs/2310.19909 This problem does not occur when using v1.23.26.

Please provide the link to an example PDF / page - I need it to report the bug!

**Comment by mjun0812** [comment]
@JorjMcKie 
Sorry, I should have been more explicit. The following URL is the link to the PDF.
https://arxiv.org/pdf/2310.19909
Page 1, 4, 7, and 8 borders disappear.

**Comment by JorjMcKie** [comment]
Problem file: 
[notext.pdf](https://github.com/user-attachments/files/15955231/notext.pdf)

**Comment by JorjMcKie** [comment]
> @JorjMcKie Sorry, I should have been more explicit. The following URL is the link to the PDF. https://arxiv.org/pdf/2310.19909 Page 1, 4, 7, and 8 borders disappear.

This specific file seems to be no issue (anymore in recent version). The test file above still is a problem.

**Comment by julian-smith-artifex-com** [comment]
Fixed in PyMuPDF-1.24.11.
