### ISSUE TITLE
Question / Comment:

### ISSUE THREAD

**Issue by peterkmurphy** [pymupdf/PyMuPDF#345]
Dear PyMuPDF developers and contributors,

My goal in using PyMuPDF is to use it to read selected PDF pages, and turning them into PNG images. There are two types of images I want to generate - thumbnails (where quality is not so important), and high resolution (300 DPI) images. I find the tool quicker to use than ghostscript, so I am using it already for thumbnail generation. 

However. there is one particular PDF that causes problems, 20DixStRedcliffe.pdf (attached), which is why I have held off in using PyMuPDF for high resolution images. When rendered, text appears wrapped in black rectangles, and the black rectangles overlap each other. That makes it messy. So I am still using ghostscript for generating high resolution images, even though being a lot slower than PyMuPDF. If there is something I can do to make the rectangles go away, I would be delighted.

To replicate the problem, please run extract20dix.py (attached in zip form). Apart from having fitz installed, the only requirement for execution is to have gs installed as well. Running it using Python 3 on Ubuntu 16.04, I find it takes 5.8 seconds to generate 300 DPI images of all 6 pages of 20DixStRedcliffe.pdf using PyMuPDF; the processing time for gs is 12.6s. You can see why I would like to use PyMuPDF for generating higher resolution images. But there's a problem...

Alas, the images from PyMuPDF have those black rectangles:
![20DixStRedcliffe pdfpymupdfpage-0](https://user-images.githubusercontent.com/1015989/62751348-b9706880-baa6-11e9-8caf-83942e31379a.png)

And the images from gs do not.
![20DixStRedcliffe pdfpage-0](https://user-images.githubusercontent.com/1015989/62751423-f9375000-baa6-11e9-9efe-9485e8667be1.png)
  
I am submitted this as a question rather than a bug, because I don't know if it is the fault of the PDF generator, PDFsharp (1.2.1269-g), which produced the PDF in the first place. If I see the PDF in Xreader 1.6.2 (Ubuntu's default PDF viewer), I see those rectangles. However, if I open up the PDF in Firefox's internal PDF viewer (which is based on their [PDF.js](https://mozilla.github.io/pdf.js/) library), then those rectangles don't appear.

Attachments:

[20DixStRedcliffe.pdf](https://github.com/pymupdf/PyMuPDF/files/3484419/20DixStRedcliffe.pdf)

[extract20dix.py.zip](https://github.com/pymupdf/PyMuPDF/files/3484555/extract20dix.py.zip)

**Comment by JorjMcKie** [comment]
uff, that was a tough one ...
The rectangles are borders of PDF annotations - apparently all of them being of type ``/Square``. The PDF command for **_drawing_** those rectangles looks like ``b'1 w\n66 279 14 181 re\ns'`` in **every** case. It means:
"**draw** (the final 's') **a rectangle** ('re') **at location** (those numbers ...) **with border width 1 pixel** ('1 w')".

So a faithful PDF viewer has no choice other than doing this, right?

In the low-level toolbox of PyMuPDF there are ways to directly modify such items. I tried two alternatives (note: those commands are ``bytes`` objects):
1. replace width 1 by width 0.00001 (b"1 w" --> b"0.00001 w"). This produced a nicer image with borders only faintly visible.
2. replace the "draw" command ``s`` with a "no-op" command ``n``.

Alternative 2 seemed the best - no rectangle borders visible anymore. This is the code snippet doing the job:

```python
>>> doc = fitz.open("20DixStRedcliffe.pdf")
>>> for page in doc:  # iterate through the pages
        a = page.firstAnnot  # get first annotation
        while a:  # iterate through annotations
            ap = a._getAP()  # read the annot's commands
            ap = ap.replace(b"\ns", b"\nn")  # replace 'draw' with 'no-op'
            a._setAP(ap)  # rewrite command
            a = a.next  # get next annot until 'None' received
        # now generate and write pixmap (no alpha for better speed)
        pix = page.getPixmap(alpha=False, matrix=fitz.Matrix(300/72, 300/72))
        pix.writeImage("pn-%i.png" % page.number)
>>>
```

Note:
* This does not permanently change the PDF. However, if you want you can save it in that modified form.
* I haven't measured the performance impact of this modification - hopefully it is sufficiently low.

**Comment by JorjMcKie** [comment]
Couldn't rest without knowing the performance impact and measured the above snippet under Windows and Linux.
To my surprise, in both cases the runtime was **smaller** (2% - 3%) **with** the modification!
Apparently it takes longer to render borders than modifying the command as I did ...

**Comment by peterkmurphy** [comment]
@JorjMcKie: firstly, I have to commend you for your research and your diligence. I thought the PDF was malformed in some way; I didn't expect that the PDF was formatted correctly, but in a counter-intuitive way. (Perhaps it is PDFSharp that creates those silly annotations?) Anyway, what you have done is awesome.

More to the point, your solution is perhaps a way forward to using PyMuPDF for high resolution images. I need to do a little more research on this, but if the annotations only occur with PDFSharp produced PDFs, then I can replace GhostScript with PyMuPDF for this task. I will let you know.

Thank you so much.

**Comment by JorjMcKie** [comment]
thanks for the compliments ;-)

Those rectangles are indeed created by the program that converts the CAD files to PDF (which may be PDFSharp - I don't know).
The annotations created, consist of text (which is indeed needed) appearing in a so-called ``/Square`` type annotation (vulgo rectangle). Why choosing this type (and not e.g. ``/FreeText``) remains their secret. And why bothering to then also draw the rectangle **_border_** and not just the text, is hard to understand, too.

Of course you would be walking on thin ice if you **always** would treat rectangle annotations in this way ...

Just as a comment: There is a way to suppress **all** annotations when rendering a PDF page (look in the recipes or the docu). And you can also create a pixmap for each annotation individually ...

**Comment by JorjMcKie** [comment]
You could base any decision as to whether or not use my above snippet on what you find as ``producer`` / ``creator`` in the ``doc.metadata``: if PDFSharp occurs there, do it, otherwise don't. Or whatever.

**Comment by peterkmurphy** [comment]
@JorjMcKie: I'm going to have to give this matter some thought. One other issue that arose is the size of the output PNG files (after rectangular annotations were removed). I adapted and ran the script across 10 PDFs, and compared the size of the output PNGs for PyMuPDF against those generated by gs (in each case, 300 DPI resolution). Output PNGs from PyMuPDF were on average 3.2 times the size of those from gs (with ranges from 1.6 times to 4.6 times).

But this is my issue, not yours. The output quality of PyMuPDF seems to be better than that on gs. However, the speed saving in image generation may be outweighed by the speed increase in downloading the generated image by users. One particular A0 size architectural drawing - 14044 x 9344 pixel in size in PDF form - comes to 14.3MB via PyMuPDF, but 6.5MB via gs.

Thank you again.

**Comment by JorjMcKie** [comment]
This sounds very awkward. I can’t believe the resolutions are really the same. Could look into them with some tool like irfanview?
I know that MuPDF doesn’t use the highest possible PNG compression, but never that big a difference ...

Von meinem iPhone gesendet

**Comment by peterkmurphy** [comment]
I used Gimp (not irfanview, as it is not present on Linux). The output from gs results in more "blobby" lines and letters than PyMuPDF.

**Comment by JorjMcKie** [comment]
could you please tell me the command line you use for gs png creation?
I will see myself where that difference comes from.
If you see quality differences to PyMuPDF, then there should be some resolution difference.

Interestingly, Ghostscript and MuPDF are products of the same company Artifex.

**Comment by peterkmurphy** [comment]
This is the code I used to call gs from Python.

    import subprocess;

    def crPicFromPDF(filename, outputfile, pageno, resolution, device='png16m', encoder_options=75):
        ''' Calls ghostscript directly to generate images from a PDF. '''
        commandArgs = ['gs', '-dQUIET', '-sDEVICE={}'.format(device), '-o', \
            outputfile, '-r{}'.format(resolution)]
        if device == 'jpeg':
            commandArgs.append('-dJPEGQ={}'.format(encoder_options))
        commandArgs.extend(['-dFirstPage={}'.format(pageno), \
            '-dLastPage={}'.format(pageno), filename])
        subprocess.call(commandArgs)

Where _filename_ is the input PDF, _outputfile_ is the output PNG (or JPG), _pageno_ is the page number, and _resolution_ is the resolution in DPI.

**Comment by JorjMcKie** [comment]
Hi,
thanks for the information – I belatedly saw that you already had included your script for the image generation.
In the meantime I found the reason for the filesize differences: Ghostscript uses a so-called ICC colorspace for generating the PNGs, which allows for a better compression ratio. But – as you have noticed – at the price of considerably lower image quality.

PyMuPDF does not (yet) support ICC colorspaces.
What you may want to do however, is outputting PyMuPDF pixmaps as JPEG images, using the PIL / Pillow package as follows –it is very easy easy to interface with it from PyMuPDF.
This yielded smaller overall image sizes for your example PDF, and an again improved processing speed.
I also found out, that the pesky rectangle borders can be removed alltogether more easily. Obviously, the annotations just consist of those rectangles, and Ghostscript does not bother to render them at all.

All those means lead to an even shorter PyMuPDF (+ PIL) execution time and overall image filesizes of 7.3 MB versus 5 MB (gs).
The runtimes on my machine were PyMuPDF 5 second, Ghostscript 20 seconds for your example file.

Jorj

PS:
The next PyMuPDF version 1.16.0 will have a pixmap argument, which allows to render pages without its annotations.

**Comment by JorjMcKie** [comment]
Internet is back - here is the modified script
[extract20dix.zip](https://github.com/pymupdf/PyMuPDF/files/3512561/extract20dix.zip)

**Comment by peterkmurphy** [comment]
Thanks for all your research (and sorry for my tardiness in replies). I will try out your fixes when I have time to get around to it. The project has moved onto a different phase, but I will try these things out and see if they work. Thanks again.

**Comment by JorjMcKie** [comment]
Always welcome. Enjoy using PyMuPDF.
Closing this for now, but please don't hesitate to re-open it or submit other inquiries.
