### ISSUE TITLE
Unable to align or format text in Form Field Widgets

### ISSUE THREAD

**Issue by sumitjain236** [pymupdf/PyMuPDF#3455]
### Description of the bug

Currently, there seems to be no direct method to align the text within Form Field Widgets in PyMuPDF (fitz). Additionally, there is no built-in property or method to apply bold or italic formatting to the text value within these widgets.

### How to reproduce the bug

Attempt to align text within a Form Field Widget using PyMuPDF (fitz).
Attempt to apply bold or italic formatting to the text value within a Form Field Widget using PyMuPDF (fitz).

### PyMuPDF version

1.24.3

### Operating system

MacOS

### Python version

3.10

**Comment by JorjMcKie** [comment]
Please consult the documentation:
There is no way to achieve using other than the "Regular" versions of the Base-14 fonts: Times-Roman, Helvetica and Courier, no bold, no italic.

PDF does not provide parameters to influence the alignment of text field content. So this is not possible to do.
