### ISSUE TITLE
pix = page.get_pixmap(matrix=matrix, clip=rect) recommend to modify function get_pixmap 

### ISSUE THREAD

**Issue by Smonkey123** [pymupdf/PyMuPDF#3468]
**Is your feature request related to a problem? Please describe.**
When I used pix = page.get_pixmap(matrix=matrix, clip=rect), I found:
This function always performs the image cutting (clip) first, and then performs the matrix transformation, which may be in reverse order, should you perform the image transformation before performing the cutting?

**Describe the solution you'd like**

**Describe alternatives you've considered**
Are there several options for how your request could be met?

**Additional context**

**Comment by JorjMcKie** [comment]
The design has been chosen with due consideration: in this way only necessary data will submitted to any desired transformations, reducing memory requirements.

You can always create sub-pixmaps from a pixmap, so you can first transform and then extract a subset from the result.
