### ISSUE TITLE
Embedded full-text search index

### ISSUE THREAD

**Issue by ZupoLlask** [pymupdf/PyMuPDF#3476]
Dear Community,

As I haven't found information on this, can you let me know if `PyMuPDF` supports full-text search index embedding?
- https://blog.adobe.com/en/publish/2014/07/29/speed-up-pdf-search-with-an-embedded-index

This is super useful to speed-up searches in large PDF documents.

Thank you!

**Comment by ZupoLlask** [comment]
Thanks for the quick feedback!

Just to make it clear: you also don't support this on your commercial offering, right?

**Comment by JorjMcKie** [comment]
Consider this:
That Adobe solution obviously modifies the PDF permanently by storing keyword search results somewhere inside it for later retrieval.

**_Upon_** later retrieval you again need an application that knows
1. how to **_sense_** that extended search information is present in the PDF at all,
2. where to find it and
3. how to interpret these data and use them in answering user inquiries.

If I am not missing something basic here, this sounds to be a specific solution around that specific application.
At least in the official PDF specification there is no such thing as an "Embedded Index".

What I mean is: open such a PDF in a non-Adobe PDF viewer and I would be amazed if it can use such an embedded index. Only at that point things may become interesting.

**Comment by ZupoLlask** [comment]
Dear Jorj,

I totally agree with your reasoning.

Any application that makes use of such index, either reverse engineered proprietary data structure and its features to make use of them, or is also embedding a different proprietary search index under `/PieceInfo` that will also be only usable by some specific application.

Thanks for your time and for your clarification.
