### ISSUE TITLE
Question: is PyMuPDF rect compatible with reportlab rect?

### ISSUE THREAD

**Issue by armenic** [pymupdf/PyMuPDF#348]
Dear developers,

I was trying to use coordinates obtained from PyMuPDF in reportlab but it seems they are not compatible or I am missing something. I am using `rect` [72, 74, 103, 85] to place free text annotation and you can see that reportlab places it at the bottom meanwhile `fitz` on top. My system and environment info can be found in #347 
Thank you so much for your help to demystify this.

[word1.pdf](https://github.com/pymupdf/PyMuPDF/files/3522421/word1.pdf)
[word1_fitz.pdf](https://github.com/pymupdf/PyMuPDF/files/3522422/word1_fitz.pdf)
[word1_reportlab.pdf](https://github.com/pymupdf/PyMuPDF/files/3522423/word1_reportlab.pdf)

The code that generates `word1_fitz.pdf`:
```python
import fitz

doc = fitz.open("word1.pdf")
color1 = [0.941, 0.976, 0.91]
# text color
black = (0, 0, 0)
border = {"width": 1}

# work with first page only
page = doc[0]

# get list of text locations, restricting to the first occurrence
anno = page.addFreetextAnnot(fitz.Rect(72, 74, 103, 85), "DM.USBUJ", fontsize=7, fontname="ti")

anno.setFlags(0)
anno.setBorder(border)
anno.update(fill_color=color1)
doc.save("word1_fitz.pdf")
```

The code that generates `word1_reportlab.pdf`:

```python
from reportlab.pdfgen import canvas

c = canvas.Canvas("word1_reportlab.pdf")
c.drawString(100, 750, "")
  
body_style = '(0 0 0 rg /Arial,Bold 9 Tf)'
rect = [72, 74, 103, 85]
color = '[0.941 0.976 0.91]'
anno = "DM.USBUJ"

c.freeTextAnnotation(anno, DA=body_style, Rect=rect, C=color)  
c.save()
```

**Comment by armenic** [comment]
I think I found an answer to my own question :)
`fitz` is using top-left corner as a start of coordinate system, meanwhile `reportlab` is using bottom-left corner. `reportlab` used to have `bottomup` argument in `Canvas` fo flip the coordinate system but apparently they deprecated it. The workaround is to convert `fitz` rect y values by the height of the page:

```python
heigth <- fitz_page.MediaBoxSize.y
y0orig = 0
y0 = height - y0orig
y1orig = 100
y1 = height - y1orig
```

**Comment by JorjMcKie** [comment]
Currently without internet trying an answer while being “blind”. From a short look at RL documentation I concluded they are following the standard PDF coordinates: origin point on a page is bottom left. So rectangles (which normally are defined 2 diagonally opposite points) are defined by their bottom left and their top right point coordinates. MuPDF uses the top left page corner as (0, 0), and consequently our rectangles are given by top-left / bottom-right points. MuPDF provides a way to calculate between these two systems: the page transformation matrix, available via ctm = page._getTransformation(), translates PDF coordinates into MuPDF coordinates. For example, a rectangle r, given in PDF (or RL) coordinates, can be had in (Py-) MuPDF coordinates via “r * ctm”. Conversely, an object in PyMuPDF coordinates can be translated to PDF by multiplying it with ~ctm (the inverse matrix).
Hope that helps 

Von meinem iPhone gesendet
