### ISSUE TITLE
Marked content sequences in text trace dictionary

### ISSUE THREAD

**Issue by EluuuArcanum** [pymupdf/PyMuPDF#3489]
Have you considered adding information on the marked content sequences?

This could be one extra key (for example mcid) of the text trace [dictionary](https://pymupdf.readthedocs.io/en/latest/functions.html#Page.get_texttrace).

Would that possible to add it also to the TextPage rawdict for every span?

It would be a really useful information for tagged PDF files created by ABBYY FineReader. This way one could reconstruct the document sructure ABBYY adds to these PDF files. This contains information about paragraphs, lines and table cells as well.

**Comment by JorjMcKie** [comment]
To provide this information is must be extractable by the base library MuPDF - which is currently not the case.
So, please direct an enhancement request to the MuPDF team. I suggest to join their public [Discord](https://discord.gg/44ZWYCDj) channel to directly discuss with them.

**Comment by EluuuArcanum** [comment]
I received the answer from the mupdf team. They say that the structure data is available in the new version of mupdf. The device now has a begin_structure and end_structure properties.

**Comment by JorjMcKie** [comment]
> I received the answer from the mupdf team. They say that the structure data is available in the new version of mupdf. The device now has a begin_structure and end_structure properties.

That was quick! Thanks for letting me know.
I looked at the device after a long pause again and can confirm that this info is now available there.
However, whether we can implement this any time soon is a completely other question ...

**Comment by alireza-hariri** [comment]
It worth mentioning here that this issue is already solved and the "seqno" is the equivalent key for mcid in `page.get_texttrace` method also the `page.get_bboxlog` is a new handy method to find bbox based on mcid
