### ISSUE TITLE
pixmap.invert_irect(pixmap.irect) take 7 seconds

### ISSUE THREAD

**Issue by manateelazycat** [pymupdf/PyMuPDF#3498]
### Description of the bug

I am the author of eaf-pdf-viewer (https://github.com/emacs-eaf/eaf-pdf-viewer). One of the features of this PDF reader is to support dark mode.

Recently, I don’t know whether it is pymupdf or the upgrade of the underlying library that causes pixmap.invert_irect(pixmap.irect) to be very slow. It takes 6 to 7 seconds to execute it once. 

The problematic code is at:  https://github.com/emacs-eaf/eaf-pdf-viewer/blob/0b79e9000551200b6a0d2206de14b87d9ed3c9c9/eaf_pdf_page.py#L198

### How to reproduce the bug

1. Start emacs with ```dark theme```
2. Install [EAF](https://github.com/emacs-eaf/emacs-application-framework)
3. Open any pdf file
4. pixmap.invert_irect(pixmap.irect) block EAF

### PyMuPDF version

1.24.4

### Operating system

Linux

### Python version
3.12

![截图 2024-05-17 23-51-02](https://github.com/pymupdf/PyMuPDF/assets/237487/a712ad02-fd02-424d-adbb-ccc52c7ec5af)

**Comment by JorjMcKie** [comment]
Can we have a PDF page please and the code which produces a pixmap from it?
To accept a bug, we can only deal with reproducible data requiring no extra installations.

**Comment by JorjMcKie** [comment]
Closing this for lack of response for more than a week.
