### ISSUE TITLE
cygwin x64 pip3 install pymupdf error

### ISSUE THREAD

**Issue by daivermastermaster** [pymupdf/PyMuPDF#3502]
### Description of the bug

cant install pymupdf in cygwin

### How to reproduce the bug

1. Windows 10 x64
2. cygwin x86_64
3. pip3 install pymupdf
4. error : "subprocess.CalledProcessError: Command 'py -0p' returned non-zero exit status 127"
there is no py launcher in cygwin as in linux os

full log in attach
[cygwin_pymupdf_log.txt](https://github.com/pymupdf/PyMuPDF/files/15368100/cygwin_pymupdf_log.txt)

### PyMuPDF version

1.24.4

### Operating system

Windows

### Python version

3.9

**Comment by julian-smith-artifex-com** [comment]
Cygwin is not (currently) supported.

A first step would be to add support for Cygwin to MuPDF. You might like to contact the MuPDF people about this, see https://mupdf.com/.

**Comment by daivermastermaster** [comment]
Thank you.
