### ISSUE TITLE
Question / Comment: How can I read a file from buffer?

### ISSUE THREAD

**Issue by sueyeontwigfarm** [pymupdf/PyMuPDF#351]
![Screen Shot 2019-08-26 at 5 11 35 PM](https://user-images.githubusercontent.com/52396871/63675826-a094e080-c824-11e9-9f0e-889728909bc1.png)

I was trying to read a file from buffer with 

fitz.open(ifile)
fitz.open(None, file_obj, "pdf")
etc.

but none of these worked and I got an error message as in the image above.
Is there another way?

**Comment by JorjMcKie** [comment]
**PyMuPDF cannot read from the internet.**
If you have a **file** (on your computer! - not on the internet), the following will always work:

```python
>>> # from a file
>>> doc = fitz.open("some.pdf")
>>> doc = fitz.open("some.file", None, "pdf") # copes with wrong extension
>>> doc = fitz.open("some.file", filetype="pdf") # copes with wrong extension
```
When I am talking of a **_stream_** this means a ``bytes`` or a ``io.BytesIO`` object **not an nternet stream!**
If you have some object like that (``mem_area``) you can do

```python
>>> # from memory
>>> doc = fitz.open("pdf", mem_area)
>>> doc = fitz.open(None, mem_area, "pdf")
>>> doc = fitz.open(stream=mem_area, filetype="pdf")
```

**Comment by JorjMcKie** [comment]
Did this answer your question?

**Comment by JorjMcKie** [comment]
Closed for lack of reaction.
Please come back with more questions any time.
