### ISSUE TITLE
Text Color Change for different fonts

### ISSUE THREAD

**Issue by meghanaviyyapu** [pymupdf/PyMuPDF#3517]
Tried to change change the font color of the first line of text using page.insert_text and applying redactions. While inserting text used the font (TimesNewRomanPS-BoldMT) extracted using span["font"].
After this process, was getting an error "font at xref 5 is not supported"
Could you let me know how it can be resolved?
[Uploading FireEmergencyGuide_untagged 1.pdf…]()

**Comment by JorjMcKie** [comment]
This is a duplicate of the quoted discussion.
Therefore, there is no need for this post - making it an issue will not change anything.
