### ISSUE TITLE
get_toc(simple=False) AttributeError: 'Outline' object has no attribute 'rect'

### ISSUE THREAD

**Issue by binghuis** [pymupdf/PyMuPDF#3519]
### Description of the bug

When I use the get_toc(simple=False) method, the program throws an AttributeError: 'Outline' object has no attribute 'rect' error. I noticed a try-catch block in the source code, but this error is still being raised.

<img width="1263" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/20395726/074d22ed-f3a1-4e99-8e2e-212d38288424">

<img width="854" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/20395726/f0cb82b5-992b-4b0a-baba-c13e1e87b803">

### How to reproduce the bug

use get_toc(simple=False) 

### PyMuPDF version

1.24.4

### Operating system

MacOS

### Python version

3.12

**Comment by binghuis** [comment]
PR: https://github.com/pymupdf/PyMuPDF/pull/3520

**Comment by julian-smith-artifex-com** [comment]
I think this is now addressed, so closing.

**Comment by julian-smith-artifex-com** [comment]
Reopening as fix is not released yet.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.6.
