### ISSUE TITLE
custom metadata keys

### ISSUE THREAD

**Issue by vorel99** [pymupdf/PyMuPDF#3528]
Hi,
It would be nice to have option to add custom metadata keys to Document as following:

```python
import fitz

doc = fitz.open(input path)
doc.set_metadata({
    "url": custom_url,
    "category": "article"
})
```

Right now, there are just following keys avalilable:  /Creator, /Producer, /CreationDate, /ModDate, /Title, /Author, /Subject, /Trapped and /Keywords respectively.
https://pymupdf.readthedocs.io/en/latest/document.html#Document.metadata

**Comment by JorjMcKie** [comment]
Already implemented!
Please consult the documentation: https://pymupdf.readthedocs.io/en/latest/recipes-low-level-interfaces.html#how-to-extend-pdf-metadata
