### ISSUE TITLE
Add dotted gridline detection to table recognition

### ISSUE THREAD

**Issue by JorjMcKie** [pymupdf/PyMuPDF#3539]
### Discussed in https://github.com/pymupdf/PyMuPDF/discussions/3535

<div type='discussions-op-text'>

<sup>Originally posted by **aborruso** May 31, 2024</sup>
Hi,
first of all thank you for this great tool.

I have seen that via python I can use `find_tables`. Is there a way to do something similar via cli and extract a table from a PDF?

Thank you</div>

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.6.

**Comment by aborruso** [comment]
Thank you very much @JorjMcKie and @julian-smith-artifex-com
