### ISSUE TITLE
mupdf error when higher than 1.24.1

### ISSUE THREAD

**Issue by YYTB** [pymupdf/PyMuPDF#3549]
### Description of the bug

when i use pymupdf higher than 1.24.1，my code blow get lots of mupdf error like `MuPDF error: format error: Index bounds` `MuPDF error: format error: Reserved charstring byte`, and finally crashed. since it's not a python exception, it's hard for me to track which part of my code cause these errors. when i use 1.24.1, dont have these errors.
```python
    def add_annotations(self, font_file_path, annot_page, box_width, box_height,
                        tempdir=_TEMP_DIR, font_size=10.0, to_edge=5,
                        dpi=200):
        filename = self.doc.name
        page_count = self.doc.page_count
        if annot_page == "all":
            annot_page = [i for i in range(page_count)]
        else:
            annot_page = [annot_page]
        fontfile = font_file_path if font_file_path else None
        fontname = "user_font" if font_file_path else _DEFAULT_FONT
        for i in annot_page:
            page = self.doc[i]
            page_w = page.rect.width
            page_h = page.rect.height
            # https://pymupdf.readthedocs.io/en/latest/functions.html#paper_size
            logger.debug(f"page_h {page_h}, page_w {page_w}")
            rect = fitz.Rect((page_w - box_width) / 2, to_edge, (page_w - box_width) / 2 + box_width, box_height + to_edge)
            shape = page.new_shape()  # create Shape
            shape.draw_rect(fitz.Rect(rect.top_left - 2, rect.bottom_right + 2), radius=0.05)
            shape.finish(width=1, color=self.annot_border_color, fill=self.annot_bg_color, fill_opacity=0.75)
            shape.commit()
            page.insert_textbox(
                rect, self.file_description, fontname=fontname, fontfile=fontfile, fontsize=font_size,
                color=self.annot_color
            )
        self.doc.subset_fonts()
        self.doc.set_toc(self.orin_toc)
```
when i delete `self.doc.subset_fonts()`, error stays, but the program wont crash.

### How to reproduce the bug

don't know

### PyMuPDF version

1.24.5

### Operating system

Windows

### Python version

3.8

**Comment by JorjMcKie** [comment]
We cannot accept bug reports that are not reproducible. Please provide all mandatory information - like a reproducing PDF!

Obviously, the PDF contains errors that were undetected by previous MuPDF versions. If you read the change log of new versions, you will see that `subset_fonts()` is going to be replaced by new, more efficient and complete code. This change is still experimental for some time.
If this doesn't work for your case, use option `fallback=True)` and - **_again_** - please provide the problem file!

**Comment by YYTB** [comment]
Thanks, after I ran some test ,   found that `subset_fonts()` was the only reason cause of these errors in some specific fonts, after adding `fallback=True` the error disappeared. just dont know why when i using the same fonts in 1.24.1 would not report these error. anyway, thanks again.

**Comment by YYTB** [comment]
> Thanks, after I ran some test , found that `subset_fonts()` was the only reason cause of these errors in some specific fonts, after adding `fallback=True` the error disappeared. just dont know why when i using the same fonts in 1.24.1 would not report these error. anyway, thanks again.

by the way , i use this font [Source Han Serif 思源宋体](https://source.typekit.com/source-han-serif/cn/)
