### ISSUE TITLE
Text extraction missing colour data

### ISSUE THREAD

**Issue by Rocketknight1** [pymupdf/PyMuPDF#356]
## Describe the bug (mandatory)
Hi! I'm working on a project involving structured text extraction from webpages. I've been saving pages as PDF and using PDF extraction to locate words and their co-ordinates. However, I've been noticing some oddities involving font colour. I've attached an example PDF from a random website (generated by Chrome/Puppeteer), where I ran some JS to colour different elements on the page different colours before creating the PDF. The different colours are clearly visible in the PDF, and if I load the document with PyMuPDF and then use `pixmap` to save a render, the colours are correct in the render. However, if I try to extract text information, the colours seem to be lost.

Example of failing PDF: [colour_test.pdf](https://github.com/pymupdf/PyMuPDF/files/3591137/colour_test.pdf)

## To Reproduce (mandatory)
Here's a minimum snippet to reproduce with the attached PDF above:
```
import fitz
doc = fitz.open('colour_test.pdf')
page = doc.loadPage(0)
text = page.getText('dict')
print(text['blocks'][2])
```

## Expected behavior (optional)
The above code prints the text span containing the headline, but fails to identify the colour (it just has a value of 0):
```
{'type': 0, 'bbox': (298.125, 289.1205139160156, 896.9669799804688, 357.07049560546875), 'lines': [{'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (298.125, 289.1205139160156, 896.9669799804688, 323.32049560546875), 'spans': [{'size': 28.5, 'flags': 4, 'font': 'Lato-Regular', 'color': 0, 'text': 'Chips, jerky and rehab for injured Bronco hockey', 'bbox': (298.125, 289.1205139160156, 896.9669799804688, 323.32049560546875)}]}, {'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (298.125, 322.8705139160156, 375.6105041503906, 357.07049560546875), 'spans': [{'size': 28.5, 'flags': 4, 'font': 'Lato-Regular', 'color': 0, 'text': 'player', 'bbox': (298.125, 322.8705139160156, 375.6105041503906, 357.07049560546875)}]}]}
```

## Your configuration (mandatory)
```
3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] 
 linux 
 
PyMuPDF 1.16.1: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-09-03 19:21:33.
Built for Python 3.7 on linux (64-bit).
```

**Comment by Rocketknight1** [comment]
I'm not sure, but this may be related to certain webpages greying out the page to display a popup box - the grey overlay appears as an element in the PDF too, and maybe that distorts colour recognition somehow.

**Comment by JorjMcKie** [comment]
Hi, I have checked out your example. I believe you are right with that gray overlaying. I see the same thing happening.
When using other text extraction variants (html), the same thing happens. This variant directly uses the MuPDF base library (in contrast to "dict" and "rawdict", which are my own making), so I am afraid there is nothing I can do ... except posting this as an issue upstream to them.
For this being successful however, we would need a much simpler / more direct example, which can be submitted to them.

**Comment by Rocketknight1** [comment]
I'll see if I can find a very simple page where it recurs. In the meantime, is there any way I can recover the colour information? Maybe by altering the PDF to remove the overlay image/box?

**Comment by JorjMcKie** [comment]
I have tried a few things, e.g. removed all images and all links, but the gray overlay wouldn't go away.
Looking further.

**Comment by Rocketknight1** [comment]
I'll keep looking too - if I can find out the conditions that cause it, it should make it a lot easier to submit a clean bug report to MuPDF.

**Comment by JorjMcKie** [comment]
After several more experiments I am giving up. Probably some of the myriads of GS operators (graphics state) do the graying out - hopeless to fiddle with.

If you can find a simple example - great. You can then send it to them, but you need to demonstrate that one of their own utilities is failing to recognize the color. E.g. using ``mutool draw -o test.html test.pdf``. From their point of view, PyMuPDF is of course irrelevant.
You can also use me as a relay station if you want ... and I'll submit to https://bugs.ghostscript.com/enter_bug.cgi.

**Comment by JorjMcKie** [comment]
closing this for now ...

**Comment by Rocketknight1** [comment]
Attempting to reproduce in HTML with simple overlays isn't working - the colour seems to be extracted correctly, so I don't know if the overlay is the problem now. If I can't localize the problem, is it worth submitting the complex example to them?
