### ISSUE TITLE
How to add watermarks to PDF file?

### ISSUE THREAD

**Issue by jackczhang** [pymupdf/PyMuPDF#357]
How to add watermarks to PDF file? Could you give a sample? TKS

**Comment by JorjMcKie** [comment]
You need an image or a PDF page or a SVG image to serve as the watermark.
In PyMuPDF, watermark support means overlaying PDF pages with such objects - I do not support watermark **annotations**.
This snippet:
1. creates a transparent image file from some PDF page
2. inserts the created image on every page of some PDF that you want to mark.

```python
>>> import fitz
>>> doc=fitz.open("PyMuPDF.pdf")  # take 1st page of this as watermark image
>>> page=doc[0]
>>> pix=page.getPixmap(alpha=True)  # make sure the image is transparent!
>>> pix.writeImage("watermark.png")  # create image
>>> doc.close()  # no longer needed
>>> pix=None  # no longer needed
>>> doc=fitz.open("123dok.pdf")  # watermark this file
>>> image_file = "watermark.png"  # with this image
>>> for page in doc:  # iterate through all pages of the file
	page.insertImage(page.rect, filename=image_file,
                         keep_proportion=False,  # stretch picture to cover full page
                                  )
>>> doc.save("watermarked.pdf")  # thewatermakred PDF
>>> 
```
That should do it. Be aware the non-transparent parts of the image file will make stuff invisible.

**Comment by JorjMcKie** [comment]
The following is very similar, but directly overlays PDF pages with a given page from another PDF:
```python
>>> src=fitz.open("pymupdf.pdf")
>>> doc=fitz.open("123dok.pdf")
>>> for page in doc:
	page.showPDFpage(page.rect,  # cover the full page
                         src,  # the PDF from which to take the image
                         0,  # choose page number in 'src'
                         keep_proportion=False,  # like before: stretch
                 )
>>> doc.save("overlayed.pdf")
>>> 
```
This method looks a little easier. Just choose the one that fits your situation. Other filetypes supported by MuPDF can be converted to PDF (on the fly, temporarily, using the ``convertToPDF()`` method) and then used in exactly the same way as shown here.

**Comment by JorjMcKie** [comment]
answered your question?

**Comment by JorjMcKie** [comment]
Assuming "yes" for the moment. Please feel free to come back with more questions anytime.
