### ISSUE TITLE
MuPDF error: argument error: not a dict (string)

### ISSUE THREAD

**Issue by NexPlex** [pymupdf/PyMuPDF#3584]
### Description of the bug

 PyMuPDFb==1.23.3.  works fine 
when we upgrade to  PyMuPDFb==1.24.5 these lines of code started throwing an error.
   
    doc = fitz.open(stream=input_pdf_path, filetype="pdf")
    page = doc[page_number - 1]
           
    MuPDF error: argument error: not a dict (string)

this error repeats about 15 times. but the code save successfully.
    
     
   I saw a post that suggested we clean the file like this, but it did not change the results.
   
       doc = fitz.open(stream=input_pdf_path, filetype="pdf")
    print('clean')
    pdfbytes = doc.tobytes(garbage=3)
    doc.close()
    doc = fitz.open("pdf", pdfbytes)
  print('page')
    page = doc[page_number - 1]

### How to reproduce the bug

No errors with  PyMuPDFb==1.23.3. 

### PyMuPDF version

1.24.5

### Operating system

Linux

### Python version

3.9

**Comment by JorjMcKie** [comment]
A bug report cannot be accepted without a reproducing file.

**Comment by NexPlex** [comment]
Sorry my bad. See attached. thank  you for the quick reply.
[003668df-7ea8-4f40-b672-7162f2d1e209-ca-polst-2017-en.pdf](https://github.com/user-attachments/files/15845765/003668df-7ea8-4f40-b672-7162f2d1e209-ca-polst-2017-en.pdf)

**Comment by JorjMcKie** [comment]
The PDF **_does_** contain many errors. It has 39 form fields which all have a wrong entry `/AP`.
AP - albeit optional - if present should be correct. As per the specs it **_must_** be a PDF dictionary, but it is a string in all cases. Who knows why.
If an AP is missing or unusable, the appearance will be generated from the object definition of the field.

If you are molested by the messages you can request to not show them - use `pymupdf.TOOLS.mupdf_display_errors(False)`.
