### ISSUE TITLE
Question / Comment: RAWDICT documentation

### ISSUE THREAD

**Issue by matter-funds** [pymupdf/PyMuPDF#360]
Hi,

Is there any documentation anywhere about what RAWDICT is supposed to contain and how blocks/lines/spans are formed?

I'm also particularly interested in what the color field represents. I see it's usually a number, but I'm not sure how to interpret it:

e.g. I see `'color': 0`, in the below; how should I interpret that?

```
>>> rd['blocks'][-1]['lines'][1]['spans']
[{'size': 6.0, 'flags': 4, 'font': 'TimesNewRomanPSMT', 'color': 0, 'chars': [{'origin': (532.2755737304688, 859.394287109375), 'bbox': (532.2755737304688, 854.047607421875, 535.2755737304688, 860.692138671875), 'c': '2'}, {'origin': (535.2755737304688, 859.394287109375), 'bbox': (535.2755737304688, 854.047607421875, 538.2755737304688, 860.692138671875), 'c': '9'}]}]
```

**Comment by matter-funds** [comment]
Actually, I eventually found this:
https://pymupdf.readthedocs.io/en/latest/textpage/#dictionary-structure-of-extractdict-and-extractrawdict

Thanks!

**Comment by JorjMcKie** [comment]
ah, ok.

**Comment by matter-funds** [comment]
I guess a (minor) suggestion would be to maybe link to https://pymupdf.readthedocs.io/en/latest/textpage/#dictionary-structure-of-extractdict-and-extractrawdict
from https://pymupdf.readthedocs.io/en/latest/app2/#rawdict

if that's a page you can modify.
