### ISSUE TITLE
Output issue for text extraction function

### ISSUE THREAD

**Issue by heyan0114** [pymupdf/PyMuPDF#361]
## Describe the bug
I've been using PyMuPDF for parsing pdfs with text layer for a while and I've noticed an issue regarding the getText() function: under certain sinario, when characters like `fi` or `fl` got connected together, the extraction result becomes character `ﬁ` (encoded as `&#xfb01;`) or `ﬂ` (encoded as `&#xfb02;`)

Since these kind of cases happened quite frequently amont pdfs, I was wondering if there is a way to fix this?

## To Reproduce
Sample code to get the individual words within a pdf page:
```
pdf_doc = fitz.open(pdf_path)
pdf_page = pdf_doc.loadPage(i)
page_words = pdf_page.getTextWords()
```
Sample code to get the xhtml for a pdf page:
```
pdf_doc = fitz.open(pdf_path)
pdf_page = pdf_doc.loadPage(i)
dl = pdf_page.getDisplayList()
tp = dl.getTextPage()
page_xhtml = tp.extractXHTML()
```

The sample pdf document has been uploaded here: [google drive link].(https://drive.google.com/file/d/1qx-6-liDDOgs4Is3iJAukN8oJyQBa59M/view?usp=sharing)

## Configuration
```
PyMuPDF 1.16.0: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-08-25 01:01:00.
Built for Python 3.5 on linux (64-bit).
```

**Comment by JorjMcKie** [comment]
All text extraction variants are high level methods which use so-called ``TextPage`` and ``DisplayList`` objects under the hood. You have indicated some yourself.
There are three bit indicators which can be set when creating a textpage for a display list- see [here](https://pymupdf.readthedocs.io/en/latest/displaylist/#DisplayList.getTextPage) and [here](https://pymupdf.readthedocs.io/en/latest/vars/#textpreserve).

What you want, is already implemented and you (currently) just need to fall back to the underlying methods if you want to use another setting of the bit flags.
Therefore I am reclassifying this issue as a **question**.

I should probably offer a way to set these flags using the highlevel methods and offer a tabular overview on what happens under which setting.

**Comment by heyan0114** [comment]
Thanks, this helps a lot! I actually missed that piece of parameter setting documentation on the website.
