### ISSUE TITLE
Why does PyMuPDF print checkmarks instead of 'X' for checkboxes.

### ISSUE THREAD

**Issue by ahussain3** [pymupdf/PyMuPDF#3618]
For the same PDF document, I noticed that when I fill in a checkbox using Apple Preview, or Adobe Acrobat, selected checkboxes are shown as [X]. Whereas, when I check a checkbox using PyMuPDF, the checkbox shows as [✓].

## Apple Preview
![Screenshot 2024-06-25 at 3 57 25 PM](https://github.com/pymupdf/PyMuPDF/assets/3147141/df4a6acf-c9d7-4452-8bae-ec705a9085e1)

## Adobe Acrobat
![Screenshot 2024-06-25 at 3 57 37 PM](https://github.com/pymupdf/PyMuPDF/assets/3147141/d1241a93-7804-4be9-bfcd-8629493d0612)

## PyMuPDF
```
if widget.field_type == PDF_WIDGET_TYPE_CHECKBOX:
    widget.field_value = True
```
![Screenshot 2024-06-25 at 3 57 57 PM](https://github.com/pymupdf/PyMuPDF/assets/3147141/eb6994d7-aff5-4738-8ffb-debf032227f3)

Is this configurable? I have tried setting `widget.text_font` and `widget.text_fontsize`, but with no success.

My main concern is that the screen readers / scanners that read the printed form will misread the checkboxes if they are selected in this non-standardized way.

**Comment by JorjMcKie** [comment]
No, this behavior is based on MuPDF's appearance stream creation and cannot be changed.
