### ISSUE TITLE
Text change in fitz 1.16.2

### ISSUE THREAD

**Issue by sshustov** [pymupdf/PyMuPDF#363]
_**Please provide all mandatory information!**_

For some reason in version 1.16.2 text generated differently. I assume some changes between 1.16.1 and 1.16.12 affected getText(), getTextWords() and getText('rawDict'). For example '(24.74% of' turned into '(24.74%of'

## To Reproduce (mandatory)
Try same file with version 1.16.1 and 1.16.2. 
doc = fitz.Document('file_path')
print(doc[0].getText())
print(len(doc[0].getTextWords()))

## Expected behavior
Both versions should have same text and words

## Your configuration (mandatory)
 - Ubuntu 16.40
 - Python version 2.7 (3.6 will probably have same issue, can test if needed)
 - PyMuPDF version 1.16.1 vs 1.16.2

## PDF document
Attached file
[Table 1 - Edited.pdf](https://github.com/pymupdf/PyMuPDF/files/3611922/Table.1.-.Edited.pdf)

**Comment by JorjMcKie** [comment]
There is a new bit indicator called ``TEXT_INHIBIT_SPACES``, so there are now the following:

**TEXT_PRESERVE_LIGATURES**
1 – If this option is activated ligatures are passed through to the application in their original form. If
this option is deactivated ligatures are expanded into their constituent parts, e.g. the ligature f is
expanded into three eparate characters f, f and i.
**TEXT_PRESERVE_WHITESPACE**
2 – If this option is activated whitespace is passed through to the application in its original form.
If this option is deactivated any type of horizontal whitespace (including horizontal tabs) will be
replaced with space characters of variable width.
**TEXT_PRESERVE_IMAGES**
4 – If this option is set, then images will be stored in the structured text structure. The default is to
ignore all images.
**TEXT_INHIBIT_SPACES**
8 – If this option is set, we will not try to add missing space characters where there are large gaps
between characters.

All of them are set via an integer called "flags", which is available in **_all_** extraction methods. The defaults for the methods are documented here:
![grafik](https://user-images.githubusercontent.com/8290722/64897940-49c83d00-d653-11e9-9c58-6a6eb9a0845c.png)

So I took the liberty to set ``TEXT_INHIBIT_SPACES`` in v1.16.2 on by default - in contrast to earlier versions, which ignored this flag completely.
I did this in the hope it would make more sense. So,

```
>>> print(page.getText(flags=1+2+8))  # delivers:
GLOBAL PREMIUM:
$5,241USD
CANADIAN MASTER PREMIUM:
$4,237USD
•
billed by Canadian Broker and remitted
COMMISSION:
$1,048USD (24.74%of Canadian Premium)
(20% of Global Premium)
PASSPORT ISSUANCE FEE:
$250USD
•
billed by Canadian Broker and remitted
PASSPORT PREMIUM: 
Central  Collection-$1,004USD +applicable taxes 
•
billed by Canadian Broker and remitted to North 
America
•
DO NOT SEND THIS PREMIUM TO CANADA -Please 
wait for billing instructions)
OTHER TERMS:
As per November 2, 2018 indication 
IMPORTANT CONDITIONS  
OF BINDER:
See below.

>>> print(page.getText(flags=1+2))  # delivers:
GLOBAL PREMIUM:
$5,241 USD
CANADIAN MASTER PREMIUM:
$4,237 USD
•
billed by Canadian Broker and remitted
COMMISSION:
$1,048 USD (24.74% of Canadian Premium)
(20% of Global Premium)
PASSPORT ISSUANCE FEE:
$250 USD
•
billed by Canadian Broker and remitted
PASSPORT PREMIUM: 
Central  Collection - $1,004 USD +applicable taxes 
•
billed by Canadian Broker and remitted to North 
America
•
DO NOT SEND THIS PREMIUM TO CANADA -Please 
wait for billing instructions)
OTHER TERMS:
As per November 2, 2018 indication 
IMPORTANT CONDITIONS  
OF BINDER:
See below.

>>> 
```
Note the **extra spaces** inserted before ``USD`` etc. in the second output, i.e. no longer "inhibited", resulting in output as before.
If you think this is inaequate, I am open to revert the default ...

**Comment by JorjMcKie** [comment]
I must confess however, that in your case I would not have classified those gaps as being **_"large"_** ...

**Comment by sshustov** [comment]
Thanks for explanation, I didn't find details about this in latest changelog.
In my opinion, it is better to keep 'TEXT_INHIBIT_SPACES' set to false, otherwise it makes new fitz output slightly different, which may confuse person,who is updating version from 1.14 to 1.16.2, but I am fine with both options. I will close issue
