### ISSUE TITLE
bboxes of glyphs are all the same in a font

### ISSUE THREAD

**Issue by khaled-hammoud** [pymupdf/PyMuPDF#3641]
### Description of the bug

Hi, I want to get the bounding boxes for each glyph in a given font but as NOT expected, `glyph_bbox()` returns the same coordinates for any glyph.
According to documentation, it returns the rectangle coordinates relative to fontsize 1, okay one should scale it for given font size but this returned value still the same regardless what a glyph was fed to.
Did I understand something wrong or what happens exactly here?

### How to reproduce the bug

From documentation:
<img width="279" alt="glyph" src="https://github.com/pymupdf/PyMuPDF/assets/33861815/655f2ca6-211f-4f79-bab1-e2d960ced0c6">

My script:
```
import fitz

font_file = "Arial.ttf"

my_font = fitz.Font(fontname = "arial", fontfile = font_file)

#Printing out bboxes for A to Z in Arial font
for i in range(65, 91):
    print(f'{chr(i)}, bbox: {my_font.glyph_bbox(i)}')

#fitz output:
'''
A, bbox: Rect(-0.66455078125, -0.32470703125, 2.0283203125, 1.037109375)
B, bbox: Rect(-0.66455078125, -0.32470703125, 2.0283203125, 1.037109375)
C, bbox: Rect(-0.66455078125, -0.32470703125, 2.0283203125, 1.037109375)
...
X, bbox: Rect(-0.66455078125, -0.32470703125, 2.0283203125, 1.037109375)
Y, bbox: Rect(-0.66455078125, -0.32470703125, 2.0283203125, 1.037109375)
Z, bbox: Rect(-0.66455078125, -0.32470703125, 2.0283203125, 1.037109375)
'''

#from ttx command by fonttols
'''
<TTGlyph name="A" xMin="-3" yMin="0" xMax="1369" yMax="1466">
<TTGlyph name="B" xMin="150" yMin="0" xMax="1257" yMax="1466">
<TTGlyph name="C" xMin="102" yMin="-25" xMax="1398" yMax="1491">
...
<TTGlyph name="X" xMin="9" yMin="0" xMax="1353" yMax="1466">
<TTGlyph name="Y" xMin="6" yMin="0" xMax="1350" yMax="1466">
<TTGlyph name="Z" xMin="41" yMin="0" xMax="1200" yMax="1466">
'''
```

The fontfile used is here "[Arial.tff](https://github.com/matomo-org/travis-scripts/blob/master/fonts/Arial.ttf)"

I inspected it with other online services, not all its glyphs have the same bbox

### PyMuPDF version

1.24.1

### Operating system

Windows

### Python version

3.9

**Comment by JorjMcKie** [comment]
This is no bug. See a quote here:

> In a proportional font, the glyph bounding boxes are indeed equal for all glyphs, regardless of their visual width. This might seem counterintuitive, but it’s a design choice that simplifies text layout and rendering. Explanation:

> - **Consistent Metrics:** Proportional fonts maintain consistent metrics (such as ascent, descent, and line spacing) across all characters. This ensures that text aligns neatly and uniformly, even when different glyphs have varying visual widths. Imagine reading a paragraph where each line had different line heights—it would be visually jarring!

> - **Predictable Spacing:** By using uniform bounding boxes, proportional fonts achieve predictable spacing between characters. This consistency makes it easier to calculate text width, align text in columns, and handle kerning (adjusting spacing between specific pairs of characters).

> - **Efficient Rendering:** When rendering text, the system can allocate space for each glyph based on the bounding box dimensions. This simplifies the layout process and improves performance. If each glyph had a unique bounding box, it would complicate text layout algorithms significantly.

> - **Legibility:** Uniform bounding boxes contribute to legibility. Readers expect consistent spacing, and proportional fonts strike a balance between readability and aesthetics. The visual variation comes from the actual glyph shapes, not their bounding boxes.

> In summary, while proportional fonts visually vary in width, their bounding boxes remain uniform to ensure consistent layout, spacing, and legibility.

**Comment by khaled-hammoud** [comment]
Indeed, it seems for me counterintuitive, I thought that would great if I can get bbox of a glyph using this function but as you quoted, it doesn't work.
So I think in order to get bbox of a glyph, I should a character using `insert_text() ` into temporally pdf then getting its data with `get_text('rawdict')`, do you think that would satisfies what I want (like getting its visual width, height etc)?

**Comment by JorjMcKie** [comment]
There are more methods available with the `Font` object see [here](https://pymupdf.readthedocs.io/en/latest/font.html#Font.char_lengths). This gives you a list of widths - 1 width per character in the passed-in string.
Or work with the values of `Font.ascender`/`Font.descender` and the font size as here
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/9b2609a9-bbae-42cb-a8d0-5941807564b4)

Which you find in the doc [here](https://pymupdf.readthedocs.io/en/latest/textpage.html#span-dictionary).

**Comment by JorjMcKie** [comment]
See here:
```python
import pymupdf
c = "A"
fontsize = 10
font = pymupdf.Font("helv")
asc, dsc = font.ascender,font.descender
w = font.text_length(c,fontsize=fontsize)
x0=0
x1=w
y1 = -dsc * fontsize
y0 = -asc * fontsize
bbox = pymupdf.Rect(x0, y0, x1, y1)
bbox
Rect(0.0, -10.750000476837158, 6.669999957084656, 2.9899999499320984)
```

**Comment by khaled-hammoud** [comment]
Thank you for your help!
