### ISSUE TITLE
page.get_text("text", sort = True)  extract text at wrong position

### ISSUE THREAD

**Issue by meet1704** [pymupdf/PyMuPDF#3651]
### Description of the bug

page.get_text("text", sort = True)  extract text at wrong position.  The PDF is redacted with masks, and it appears proper after insertion of text. But when the PDF is tried to read again, the text position is changed and is not a proper place.

### How to reproduce the bug

This is the Original PDF which is redacted and updated with masked data
![image](https://github.com/pymupdf/PyMuPDF/assets/7633841/9027fb27-9d66-4b94-a70f-029076b384a8)

This is the output of get_text, with sort = True, but the text `abcdrfer**` is clearly at wrong place. i have tried page.clean_contents as well
![image](https://github.com/pymupdf/PyMuPDF/assets/7633841/3516b93f-247d-4de0-b1a8-f97be0a0cad3)

### PyMuPDF version

1.24.7

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
As documented, the `sort` parameter in plain text extraction causes it to return the sorted text content of the "blocks" extraction variant.
It does not go down to single words - which would be required to meet your expectations.
So you have to do this with your own code. Here is an example script: 
[recovered-lines.zip](https://github.com/user-attachments/files/16082610/recovered-lines.zip)
