### ISSUE TITLE
When applying redactions, characters from the line below are also erased

### ISSUE THREAD

**Issue by danielcoelhocgu** [pymupdf/PyMuPDF#3655]
### Description of the bug

I am aware that Page.apply_redactions(), when used with a rectangle from Page.search_for(), may erase characters from other lines if the supplied rectangle touches characters from these lines. I am also using the method `set_small_glyph_heights(True)` as suggested on issue #2762 and in the docs.

However, when I try to erase the word "Território" from the attached file ([redact_test.pdf](https://github.com/user-attachments/files/16089322/redact_test.pdf)), the library erases characters from the line below (x characters in red denote the original annotation area).

![image](https://github.com/pymupdf/PyMuPDF/assets/110624029/21a55d4a-9517-487e-983f-0c281aec0e8d)

Docs state that "a character is removed if its bbox has a non-empty overlap with a redaction rectangle".
So I tried to inspect all characters of the page and see which ones overlap with the rectangles of the redaction annotations.

The results showed only characters of the word "Território", but the final file still lost other characters as showed in the image above.

Could this be a bug with the mupdf library itself?

### How to reproduce the bug

Here is my test code:

```python
import os

import pymupdf

pymupdf.TOOLS.set_small_glyph_heights(True)

this_dir = os.path.dirname(os.path.realpath(__file__))
file_path = os.path.join(this_dir, 'redact_test.pdf')
output_path = os.path.join(this_dir, 'redact_test_result.pdf')

# Open file
doc = pymupdf.open(file_path, filetype='pdf')

# Get page and raw dict
page = list(doc.pages())[0]
page_dict = page.get_text('rawdict')

# Search for word 'Territórios'
rect_list = page.search_for('Territórios')
for rct in rect_list:
    print('Redact rect: {0}'.format(rct))

    # Before adding redact, check which chars do intersect with this rect
    i_line = 1
    prev_line = None
    for block in page_dict['blocks']:
        for line in block['lines']:
            if prev_line and line['bbox'][1] > prev_line['bbox'][1]:
                i_line += 1

            intersected_chars = ''
            for span in line['spans']:
                for char in span['chars']:
                    if pymupdf.Rect(*char['bbox']).intersects(rct):
                        intersected_chars += char['c']
            if intersected_chars:
                print('Line {0}: {1}'.format(i_line, intersected_chars))
            prev_line = line

    # Add redact annotation
    page.add_redact_annot(rct, text='XXXXXXX', text_color=(1, 0, 0))

# Apply redactions
page.apply_redactions(images=0, graphics=0)

# Save document
doc.save(output_path, garbage=2, deflate=True)
```

### PyMuPDF version

1.24.7

### Operating system

Linux

### Python version

3.8

**Comment by JorjMcKie** [comment]
This is not a bug.
The font in use, Minion, has extremely large ascender / descender values. While you can restrict the bbox height of extracted text to more a less the visible characters, the inter-line distance even with this precaution may still be too small to avoid overlap with the line above or below.
MuPDF's redaction algorithm does not care about `set_small_glyph_heights` and will remove all characters that intersect with any part of its boundary box - even if the visible character portions seems not to intersect.
Here, we must remember that redactions primary motivation is one of legal relevance: Any risk of disclosure of sensitive information **_must_** be avoided by all means.
