### ISSUE TITLE
Consider namespacing fitz

### ISSUE THREAD

**Issue by kojiromike** [pymupdf/PyMuPDF#3658]
**Is your feature request related to a problem? Please describe.**

Due to name confusion, developers sometimes install https://github.com/kastman/fitz when they really want pymupdf. I find out when secvulns on the other fitz hit my scans.

**Describe the solution you'd like**

I propose that pymupdf incrementally work toward leverage namespace packaging so that they can continue to use the name `fitz`, but without colliding with any other package with the same name.

Instead of installing to `site-packages/fitz`, eventually install to `site-packages/pymupdf/fitz`.
Instead of `import fitz`, `from pymupdf import fitz`.

This could be done incrementally, giving folks time to plan and without causing immediate pain.

**Describe alternatives you've considered**

Unless kastman wants to hand over the package name to pymupdf, there aren't any completely "free" alternatives. I suspect namespacing is less distateful than renaming the fitz package in pymupdf to something else entirely.

**Additional context**

I'm sure there's a history here I'm not aware of. Forgive me if this has been brought up many times before. But I thought it wouldn't hurt to ask, since this is a real issue impacting us, and I'm sure you're going to get issues mentioning the other fitz from now until the end of time anyway.

**Comment by JorjMcKie** [comment]
All of these suggestions are already implemented!
You can do any of the following with the exact same effect:
* `import pymupdf`
* `import pymupdf as fitz`
* `import fitz`

**Comment by kojiromike** [comment]
@JorjMcKie You're quite right. I need to point devs to 

https://pymupdf.readthedocs.io/en/latest/tutorial.html#note-on-the-name-fitz

in the docs and I think that's the best I can expect here.

Thanks for the reply!

**Comment by JorjMcKie** [comment]
There also is this entertaining [blog article](https://artifex.com/blog/pymupdf-1.24.3-and-farewell-to-fitz) which you can point to 😉.

**Comment by kojiromike** [comment]
ref #3431
