### ISSUE TITLE
Unable to locate documentation on replacement for openErrMsg & openErrCode?

### ISSUE THREAD

**Issue by bschollnick** [pymupdf/PyMuPDF#366]
This may not be a bug, possibly a feature enhancement request?  

In v1.14.xx document.openErrMsg & document.OpenErrCode existed, and I use those when opening a PDF to detect if the document is damaged...

I found in the v1.16 release notes, that those variables have been removed, but I can't find any references to what has replaced that functionality?

Can you please point me in the right direction?  How can I detect a non-valid or damaged PDF in v1.16?

>>> import fitz
>>> test = fitz.open("CCITT_4.tif.pdf")
mupdf: cannot recognize xref format

But I don't see any exceptions, or obvious variables that indicate this is a damaged PDF?

Any assistance or suggestions are welcome.  

The PyMuPDF library has been a fantastic tool in the past and seriously been a fantastic aide in resolving PDF issues in the past.

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (wheel or source generated).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient.

**Comment by bschollnick** [comment]
According to the documentation, 

> Tools
> This class is a collection of utility methods and attributes, mainly around memory management. To simplify and speed up its use, it is automatically instantiated under the name TOOLS when PyMuPDF is imported.
> Tools.mupdf_warnings() | return the accumulated MuPDF warnings

But, I do not see mupdf_warnings() in TOOLS / Tools.  
```

>>> dir(fitz.TOOLS)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__weakref__', '_concat_matrix', '_hor_matrix', '_include_point_in_rect', '_insert_contents', '_intersect_rect', '_invert_matrix', '_le_annot_parms', '_le_butt', '_le_circle', '_le_closedarrow', '_le_diamond', '_le_openarrow', '_le_rclosedarrow', '_le_ropenarrow', '_le_slash', '_le_square', '_oval_string', '_transform_point', '_transform_rect', '_union_rect', 'fitz_config', 'fitz_stderr', 'fitz_stderr_reset', 'fitz_stdout', 'fitz_stdout_reset', 'gen_id', 'glyph_cache_empty', 'image_profile', 'measure_string', 'mupdf_version', 'store_maxsize', 'store_shrink', 'store_size', 'this', 'thisown']
```

Still digging around to see how I can work around this.

Being able to identify a damaged or unreadable PDF is a vital task for some of my code.

**Comment by JorjMcKie** [comment]
Which version and OS are you using?
Doing ``print(fitz.__doc__)`` should output something like this:

```
PyMuPDF 1.16.2: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-09-12 17:43:20.
Built for Python 3.6 on linux (64-bit).
```

and

```python
In [4]: dir(fitz.TOOLS)
Out[4]:
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__swig_destroy__',
 '__weakref__',
 '_angle_between',
 '_concat_matrix',
 '_fill_widget',
 '_hor_matrix',
 '_include_point_in_rect',
 '_insert_contents',
 '_intersect_rect',
 '_invert_matrix',
 '_le_annot_parms',
 '_le_butt',
 '_le_circle',
 '_le_closedarrow',
 '_le_diamond',
 '_le_openarrow',
 '_le_rclosedarrow',
 '_le_ropenarrow',
 '_le_slash',
 '_le_square',
 '_oval_string',
 '_parse_da',
 '_save_widget',
 '_transform_point',
 '_transform_rect',
 '_union_rect',
 '_update_da',
 'fitz_config',
 'gen_id',
 'glyph_cache_empty',
 'image_profile',
 'measure_string',
 'mupdf_version',
 'mupdf_warnings',    # <=====
 'reset_mupdf_warnings',
 'store_maxsize',
 'store_shrink',
 'store_size',
 'this',
 'thisown']
```

**Comment by JorjMcKie** [comment]
Previously, there hasn't been eception either, if MuPDF could recover errors.

Excample session for a damaged PDF (also contained in the current documentation!):

```python
>>> import fitz
>>> doc = fitz.open("damaged-file.pdf") # leads to a sys.stderr message:
mupdf: cannot find startxref
>>> print(fitz.TOOLS.mupdf_warnings()) # check if there is more info:
trying to repair broken xref
repairing PDF document
object missing 'endobj' token
>>> doc.can_save_incrementally() # this is to be expected:
False
>>> # the document has nevertheless been created:
>>> doc
fitz.Document('damaged-file.pdf')
>>> # we now know that any save must occur to a new file
```
You can use method ``doc.can_save_incrementally()`` as the programmatical error indicator ... or check whether ``fitz.TOOLS.mupdf_warnings()`` is an empty string.

**Comment by bschollnick** [comment]
One sec...

Looks like I didn't update PyMuPDF to the *latest* version...
I just upgraded, and...

>>> import fitz
>>> print(fitz.__doc__)

PyMuPDF 1.16.2: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-09-12 17:43:20.
Built for Python 3.7 on win32 (64-bit).

And it's now  fitz.TOOLS.mupdf_warnings() is there..  

Sorry, missed the fact that I was still running an outdated version in that virtual environment...

**Comment by JorjMcKie** [comment]
NP :-)
