### ISSUE TITLE
Can't find a word in pdf using search_for

### ISSUE THREAD

**Issue by Mkznd** [pymupdf/PyMuPDF#3660]
### Description of the bug

Trying to search_for and highlight a sentence using the following:
```
    for page in doc:
        text = "scientific"
        found = page.search_for(text)
        for i in found:
            annot = page.add_highlight_annot(i)
            annot.set_colors(stroke=(0, 1, 0))
            annot.update()
```
Every word and sentence (even multiline has been successful so far, but the word "scientific" in the following pdf just can't be found. Specifically the problem seems to be with the letter f. It should be found and highlighted on page 2 in the first sentence.

The link to the pdf: https://www.jmlr.org/papers/volume12/pedregosa11a/pedregosa11a.pdf
Location: Page 2, sentence 1

### How to reproduce the bug

1. Download the pdf
2. Use the snippet provided to find and highlight the word "scientific"

### PyMuPDF version

1.24.5

### Operating system

Windows

### Python version

3.12

**Comment by JorjMcKie** [comment]
This is not a bug!
The document uses ligatures which implies that the characters "fi" in "scientific" are encoded as &#xfb01;` = chr(0xFB01)`.
And because you do (of course) not specify your search string with a ligature, you will never find that string. You can request dissolving ligatures into their components by switching off the respective extraction flag bit, `TEXT_PRESERVE_LIGATURES`. E.g. here is a successful search:
```python
import pymupdf

doc = pymupdf.open("pedregosa11a.pdf")
for page in doc:
    text = "scientific"
    for rect in page.search_for(text, flags=0):
        print(f"found {text=} on {page.number=} at {rect=}")
```
Delivers this:
```text
found text='scientific' on page.number=1 at rect=Rect(89.99981689453125, 473.2886047363281, 129.39369201660156, 487.8413391113281)
found text='scientific' on page.number=2 at rect=Rect(272.2843322753906, 267.1345520019531, 311.6781005859375, 281.6872863769531)
found text='scientific' on page.number=2 at rect=Rect(330.7842712402344, 445.86572265625, 370.17803955078125, 460.41845703125)
found text='scientific' on page.number=4 at rect=Rect(263.64349365234375, 333.8790588378906, 303.0372619628906, 348.4317932128906)
found text='scientific' on page.number=5 at rect=Rect(268.08343505859375, 177.12220764160156, 308.0711975097656, 190.4422149658203)
```

**Comment by Mkznd** [comment]
Thank you for your response!

**Comment by Mkznd** [comment]
@JorjMcKie Could you point where I can learn more about flags?

**Comment by JorjMcKie** [comment]
Sure: https://pymupdf.readthedocs.io/en/latest/app1.html#text-extraction-flags-defaults

Maybe it would make sense to change the default for searching.
On the other hand: there are other drawbacks that still are waiting for implementation - like accented characters ("È" will be found if "è" is searched for, etc.).
Also, the Latin character set is fairly trivial WRT to ligatures compared to scripts like Devanagari which has many dozens of ligatures ... 😒
