### ISSUE TITLE
After translating and replacing the translation to the original position, the original position has a white color block. 

### ISSUE THREAD

**Issue by K8S666** [pymupdf/PyMuPDF#3679]
### Description of the bug

After translating and replacing the translation to the original position, the original position has a white color block. I have actually cleared the original. And the white color block only appears on some pages of some documents. Does this have anything to do with the vector graphics in the document?
[input11.pdf](https://github.com/user-attachments/files/16188713/input11.pdf)

### How to reproduce the bug

**Error effect image**
![tset](https://github.com/user-attachments/assets/ca35c582-378d-4ae2-8227-7d0c27b017dc)

**Part of the code**
def extract_text_with_details(pdf_path):
    document = fitz.open(pdf_path)
    text_details = []
    for page_num in range(len(document)):
        page = document[page_num]
        blocks = page.get_text("dict")["blocks"]
        for block in blocks:
            if block['type'] == 0:  # 文字块
                for line in block["lines"]:
                    for span in line["spans"]:
                        if span["text"].strip():  
                            text_detail = {
                                "text": span["text"],
                                "font": span["font"].replace(" ", ""),  
                                "size": span["size"],
                                "color": span["color"],
                                "bbox": span["bbox"],
                                "origin": (span["bbox"][0], span["bbox"][1]),
                                "page": page_num  
                            }
                            text_details.append(text_detail)
                            print(f"Detected font: {span['font']}")  
    return text_details

def replace_text_in_pdf(pdf_path, output_path, text_details):
    document = fitz.open(pdf_path)

    for page_num in range(len(document)):
        page = document[page_num]

        for item in page.get_drawings():
            if 'paths' in item:
                for path in item["paths"]:
                    if 'items' in path and path['items']:
                        page.delete_shape(path["items"][0])

        for detail in text_details:
            if detail["page"] == page_num:
                text_width = detail["bbox"][2] - detail["bbox"][0]
                text_height = detail["bbox"][3] - detail["bbox"][1]
                text_insert_x = detail["origin"][0]
                text_insert_y = detail["origin"][1] - text_height / 2 + detail["size"] / 2

                color = detail["color"]
                if isinstance(color, int):
                    r = (color >> 16) & 255
                    g = (color >> 8) & 255
                    b = color & 255
                    color = (r / 255, g / 255, b / 255)
                elif isinstance(color, tuple) and len(color) in [1, 3, 4]:
                    color = tuple(max(0, min(c, 1)) for c in color)
                else:
                    color = (0, 0, 0)

                if not is_font_supported(detail["font"]):
                    detail["font"] = "SimSun"  

                font_path = f"font/{detail['font']}.ttf"  
                if not os.path.exists(font_path):
                    font_path = "font/Noto-Sans-SC-Bold-2.ttf" 

                page.add_redact_annot(detail["bbox"])
                page.apply_redactions()

                print(f"Inserting text at ({text_insert_x}, {text_insert_y}) on page {page_num}: {detail['text']} with size {detail['size']} and color {color}")

                try:
                    result = page.insert_text(
                        (text_insert_x, text_insert_y),
                        detail["text"],
                        fontname=detail["font"].replace(" ", ""),  
                        fontfile=font_path,
                        fontsize=detail["size"],
                        color=color,
                        overlay=True
                    )
                    print(f"Insert result: {result}")
                except Exception as e:
                    print(f"Failed to insert text: {detail['text']}\nError: {e}")

    document.save(output_path)

### PyMuPDF version

1.24.7

### Operating system

Windows

### Python version

3.10

**Comment by K8S666** [comment]
Supplement: Through debugging, the problem seems to lie in text removal. Whenever text removal is called, colored blocks are left on certain specific pages. There doesn't seem to be any special formatting in the observed area. Could it be due to the font?

**Comment by JorjMcKie** [comment]
This is no bug.
Method `apply_readctions()` will by default remove vector graphics that completely are inside some redaction rectangle.
If you don't want that, use the appropriate parameter `graphics=pymupdf.PDF_REDACT_LINE_ART_NONE`.

**Comment by K8S666** [comment]
Thank you, it has been resolved. Sorry to disturb

**Comment by JorjMcKie** [comment]
No problem - it was a valid question!
