### ISSUE TITLE
How to correctly install from sources

### ISSUE THREAD

**Issue by MalikRumi** [pymupdf/PyMuPDF#368]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
You docs say that the PyMuPDF version must == MuPDF version.
The PyMuPDF version I have is 1.16.2. But there is no such version on the MuPDF site, or on their github. The last / highest version they have is 1.16.1

## To Reproduce (mandatory)
All you have to do is look at their site https://github.com/ArtifexSoftware/mupdf/blob/master/CHANGES

## Your configuration (mandatory)
Ubuntu 18.04 & Python 3.7.2
 - PyMuPDF version, installation method (wheel or source generated).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient. 

Yea, well, fitz.__doc__ gives me None. I finally found your instructions for Ubuntu, and am trying to follow that when I noticed the version mismatch. I suppose I will have to install a version I can get a match to...

**Comment by JorjMcKie** [comment]
Which part of the documentation are you quoting? The [introduction](https://pymupdf.readthedocs.io/en/latest/intro/) says this:

>The major and minor versions of PyMuPDF and MuPDF will always be the same. Only the third qualifier (patch level) may be different from that of MuPDF.

You forgot to mention how you installed PyMuPDF. Just reconfirmed that installing v1.16.2 from PyPI works well.

**Comment by MalikRumi** [comment]
I got it working. At least, this time the docstring prints out.

I was looking here:

https://github.com/pymupdf/PyMuPDF/wiki/Ubuntu-Installation-Experience

And not here

https://pymupdf.readthedocs.io/en/latest/intro/

As your reply suggests.

I would recommend making the Ubuntu instructions more visible and
accessible, perhaps by putting them, or a link to them, on the introduction
page.


However, my working install is in the wrong place:

/home/malikarumi/Projects/hattie/mupdf-1.16.1-source/PyMuPDF/fitz

Because I naively assumed python setup.py would install it in site-packages.

So as I see it, I have these choices:

   1.

   Leave things alone and make the best of it
   2.

   Rip this out and start over now that I have the Ubuntu instructions and
   understand what went wrong
   3.

   Just move the existing / working fitz folder to site packages.


I don’t know if # 3 will work or not. What do you think?

*“None of you has faith until he loves for his brother or his neighbor what
he loves for himself.”*

**Comment by JorjMcKie** [comment]
That Wiki page has been written by another user and later been edited by me and after that by yet some other user ... so has a tendency to age over time.
It should be taken as what its title says, namely a user experience which will not necessarily stay correct bit by bit forever.

In this repository's folder ``installation/ubuntu``, there also is a bash to do the installation ... This may help you, too.

You are generating PyMuPDF **from source** (and not, as you certainly could, installing it from PyPI wheels) for some reasons - among them presumably the installation experience itself.

Given this, I wouldn't get my hands dirty with fiddling around manually moving folders as the final step, but start over and execute a clean installation procedure (your option 2.).
You are also very welcome to update the instructions in the Wiki with what you have experienced!
Or submit a PR if ``ubuntu_pymupdf.sh`` needs adjustments.

> The Pastafari, the adepts of the FSM are the only believers who concede that their god is a monster ...

**Comment by MalikRumi** [comment]
Got a problem:
(hattie-nHCNXwaX) malikarumi@Tetuoan2:~/Projects/hattie$ pip uninstall
PyMuPDF
ERROR: Cannot uninstall 'PyMuPDF'. It is a distutils installed project and
thus we cannot accurately determine which files belong to it which would
lead to only a partial uninstall.

You might want to warn people against using setup.py:
https://stackoverflow.com/questions/1550226/python-setup-py-uninstall

I have to do this manually, and there are many warnings about the hazards
therein.
Other than the clearly named folders, where should I be looking for MuPDF
and PyMuPDF files to delete?


*“None of you has faith until he loves for his brother or his neighbor what
he loves for himself.”*

**Comment by MalikRumi** [comment]
Ok, I seem to have survived. But I still have a number of questions /
issues:

1. What is 'resp.' referring to in this line?
        Here is the resp. code snippet:
There are other places where I see 'resp.'. I just want to know what it
means, what is its significance?

2. You might want to correct this part of the tutorial:
>>> page1text = page1.getText("text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'page1' is not defined

3. I did not see this page before: https://github.com/pymupdf/PyMuPDF
What is the difference between
    pip install PyMuPDF
    and
    pip install manylinux1_x86_64.whl
    ?

Just to clarify the history, the first time I installed PyMuPDF, I just did
'pip install'. When that only worked at the command line, and not inside my
Sublime Text 3 editor, I went back and compiled from source. This third
time I used the 'manylinux' wheel, but there does not appear to be any
difference between this and the original. It works fine from the command
line, but a script in ST3 still gets the same
        "AttributeError: module 'fitz' has no attribute 'open'"
error and print(fitz.__doc__) prints None.

Is this expected behavior?

The fitz folder in site-packages does *not* have all the C helpers that the
compiled from source version had. Somehow, apparently, they are being
accessed from the command line but nowhere else. I don't pretend to get
that. Perhaps there is some additional setting I can add to ST3 so my
scripts work?

I have more, but this is getting a little long. Thanks.



*“None of you has faith until he loves for his brother or his neighbor what
he loves for himself.”*

**Comment by MalikRumi** [comment]
I have 2 urgent problems and 2 other questions:

1. I need to preserve ALL uppercase words in the original documents. For
reasons I don't understand, some are, but most aren't.

2. My original documents *already* use the separator "\n-----\n" to set
footnotes apart from the main text. Again, for reasons I don't understand,
this separator is *completely ignored* and does not show up in my extracted
text *at all*. I must have this. Without it, the footnote and main text
just run together and no longer make sense.

3. It would be *nice* if I could also preserve text that was italicized in
the original.

4. Would it be possible to search (and maybe replace?) by font? It looks
like fonts are only used for writing pdfs...
https://pymupdf.readthedocs.io/en/latest/page/#Page.insertFont



*“None of you has faith until he loves for his brother or his neighbor what
he loves for himself.”*

**Comment by JorjMcKie** [comment]
Concerning your last post: please make a new issue from it (a question). To then answer it, I would need some minimal material for recreating the situation, like a PDF page and the script you were using.

**Comment by JorjMcKie** [comment]
> 3. I did not see this page before: https://github.com/pymupdf/PyMuPDF
What is the difference between
    pip install PyMuPDF
    and
    pip install manylinux1_x86_64.whl
    ?

I am confused: what do you mean, you never saw the home page of PyMuPDF?

Otherwise ``pip install pymupdf`` will automatically determine the installation procedure to use:
* if there is a wheel which supports your combination of OS and Python, then this will be used. For most Linux systems, a wheel with the ``manilinux1`` tag will work ... which is the reason why wheels with this platform tag have been created by some clever people.
* if there is no compatible wheel, ``pip`` will use the source distribution present on PyPI and try an installation with the included ``setup.py``.
* if you have a wheel file **locally** on your computer, e.g. ``PyMuPDF-1.16.3-cp36-cp36m-manylinux1_x86_64.whl``, you can also directly use it with pip ``pip install <wheelfile>``.
* there are more ways to have pip look at yet other places to download installation material from. Please consult their documentation.

I would **always** install Python packages in a terminal / console window and **never** try to do that from within an editor. Only heaven (if you believe in something like that) knows in which environment or folder things are happening. A message like `` "AttributeError: module 'fitz' has no attribute 'open'"`` generally indicates that you are trying to import fitz inside the packages directory (where ``__init__.py`` lives). This cannot work.

**Comment by JorjMcKie** [comment]
> 1. What is 'resp.' referring to in this line?
        Here is the resp. code snippet:
There are other places where I see 'resp.'. I just want to know what it
means, what is its significance?

> 2. You might want to correct this part of the tutorial:
>> page1text = page1.getText("text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'page1' is not defined

Where is this from?

**Comment by JorjMcKie** [comment]
"resp." is the abbreviation for "respectively" ...

**Comment by JorjMcKie** [comment]
> 3. It would be *nice* if I could also preserve text that was italicized in
the original.

If you read the documentation you will find that there are variants of text extraction (``Page.getText()``) which return fontname, font color and font flags (whether serifed, monospced, italics, ...): [RTFD](https://pymupdf.readthedocs.io/en/latest/textpage/).

**Comment by JorjMcKie** [comment]
> 3. It would be *nice* if I could also preserve text that was italicized in
the original.

Here is an example of a super simple demo text extractor / font analyzer script to show what is possible with PyMuPDF.
This is how the example PDF page looks like: 
![grafik](https://user-images.githubusercontent.com/8290722/66007759-9e581e80-e481-11e9-9a3b-231bcb70f647.png)

This is the script analyzing the text and its font properties:

```python
import fitz

def flag_decompose(flags):
    """Decompose font flags in human readable text."""
    l = []
    if flags & 2 ** 0:
        l.append("superscript")
    if flags & 2 ** 1:
        l.append("italic")
    if flags & 2 ** 2:
        l.append("serifed")
    else:
        l.append("sans")
    if flags & 2 ** 3:
        l.append("monospaced")
    if flags & 2 ** 4:
        l.append("bold")
    return ", ".join(l)


doc = fitz.open("the.pdf")
page = doc[0]
blocks = page.getText("dict")["blocks"]
for b in blocks:
    for l in b["lines"]:
        for s in l["spans"]:
            print("")
            fprop = "Font: '%s' (%s), size %g, color #%06x" % (
                s["font"],
                flag_decompose(s["flags"]),
                s["size"],
                s["color"],
            )
            print("text:", s["text"])
            print(fprop)
```

And this is the script's output:
```
text: Courier Normal
Font: 'Courier' (sans, monospaced), size 11, color #ff0000

text: Courier Bold
Font: 'Courier-Bold' (sans, monospaced, bold), size 11, color #00ff00

text: Courier Italic
Font: 'Courier-Oblique' (italic, sans, monospaced), size 11, color #0000ff

text: Courier Bold Italic
Font: 'Courier-BoldOblique' (italic, sans, monospaced, bold), size 11, color #000000

text: Times Normal
Font: 'Times-Roman' (serifed), size 11, color #ff0000

text: Times Italic
Font: 'Times-Italic' (italic, serifed), size 11, color #00ff00

text: Times Bold
Font: 'Times-Bold' (serifed, bold), size 11, color #0000ff

text: Time Bold Italic
Font: 'Times-BoldItalic' (italic, serifed, bold), size 11, color #000000

text: Helvetica Normal
Font: 'Helvetica' (sans), size 11, color #ff0000

text: Helvetica Bold
Font: 'Helvetica-Bold' (sans, bold), size 11, color #00ff00

text: Helvetica Italic
Font: 'Helvetica-Oblique' (italic, sans), size 11, color #0000ff

text: Helvetica Bold Italic
Font: 'Helvetica-BoldOblique' (italic, sans, bold), size 11, color #000000

```

**Comment by MalikRumi** [comment]
jorj wrote:

>I would *always* install Python packages in a terminal / console window
and *never* try to do that from within an editor. Only heaven (if you
believe in something like that) knows in which environment >or folder
things are happening.

I did not mean that I *installed* with Sublime Text. I meant that for
whatever reason, PyMuPDF does not *work* in Sublime Text. Since this is my
editor and I make and run my scripts from here,

this is a major inconvenience. I will post an issue about this.

>A message like "AttributeError: module 'fitz' has no attribute 'open'" generally
indicates that you are trying to import fitz inside the packages directory
(where __init__.py lives). >This cannot work.

? I don't understand this. Are you referring to the site-packages directory
that comes with a virtualenv? Isn't that where pip puts *all* Python
packages? Isn't that the whole point? I'll post an issue about this, too.

And I have been reading the docs. That's where I've been for the last two
days. I like what you have done, and I want to use it. But it does not
answer all my questions.


*“None of you has faith until he loves for his brother or his neighbor what
he loves for himself.”*

**Comment by JorjMcKie** [comment]
Assuming the original issue is answered.
