### ISSUE TITLE
Encoding issue with get_textbox() only

### ISSUE THREAD

**Issue by conjuncts** [pymupdf/PyMuPDF#3686]
### Description of the bug

Hello, 

I stumbled across a pdf for which `get_text("text")` and `get_text("words")` both work with no issue, while `get_textbox()` produces a encoding-garbled output. 

### How to reproduce the bug

The file can be downloaded here:
PMID 10491136. 
https://pubmed.ncbi.nlm.nih.gov/10491136/
https://febs.onlinelibrary.wiley.com/doi/epdf/10.1046/j.1432-1327.1999.00685.x
It is a free full text (open access) article so you should be able to download it with no subscription required. 

These are the steps to reproduce: 
```
import pymupdf
doc = pymupdf.open(f"{root}/10491136.pdf")
pg = doc[6]
pg.get_textbox([0,0,100,200])
```

Output: 
> `'������������\n������������\n�������������\n���������������\n�������������\n��������������\n���������������'`

I looked through the characters, and they seem to be all turned into "\ufff" characters with loss of data.

However, `pg.get_text("text")` works just fine: 

> '886 E. Antoine et al. (Eur. J. Biochem. 264)\nq FEBS 1999\nADH activity and the Fe content is 0.5 mol per subunit. Iron\nsignatures are also found ' ...

(the entire string is encoded with no issue.)

And `pg.get_text("words")` also works just fine: 
`' '.join(x for _,_,_,_,x,_,_,_ in pg.get_text("words"))`

> '886 E. Antoine et al. (Eur. J. Biochem. 264) q FEBS 1999 ADH activity and the Fe content is 0.5 mol per subunit. Iron signatures are also found in its amino acid sequence. The histidine residues are involved in the iron dependence of this class of dehydrogenases' ...

(the entire string is encoded with no issue.)

Expected: `get_textbox()` encodes the same content as `get_text()`

If desired, I can also provide more example pdfs.

### PyMuPDF version

1.24.7

### Operating system

Windows

### Python version

3.10

**Comment by conjuncts** [comment]
Also garbled for me: 
`pg.get_textpage([0,0,100,200]).extractText()`
pg.get_textpage([0,0,100,200]).extractWORDS()`

But this works:
```pg = doc[6]
pg.get_text('text', clip=[0,0,100,200])```
> '886 E. Antoine\nADH activity a\nsignatures are\nhistidine residu\nl\nf d h d\nFig. 3. Amino-te\nGrey boxes indica\n'

**Comment by JorjMcKie** [comment]
This not a bug. There are the following differences between `get_text(clip=clip)` and `get_textbox(clip)`:
* different text extraction flags (flags=0). `TEXTFLAGS_TEXT` are used in standard `get_text()`.
* different character inclusion criteria: **_intersecting_** characters will be included (only **_contained_** characters in standard `get_text()`).

So if the more generous character inclusion works for you, you can define a `TextPage` with desired extraction flags to enforce the same character extraction properties - like this:
```python
tp = page.get_textpage(flags=pymupdf.TEXTFLAGS_TEXT)
text = page.get_textbox(clip, textpage=tp)
```

**Comment by JorjMcKie** [comment]
As a further comment:
The flag bit combination of `TEXTFLAGS_TEXT` includes the option to use the glyph number as the Unicode number if the font has no back-translation information (and MuPDF will thus return &#xfffd;).
In some cases - as in your example - (but not always) this leads to a satisfying extraction result.
You may want to keep this in mind as an option when running into similar problems.

**Comment by conjuncts** [comment]
I see - thanks!
