### ISSUE TITLE
mupdf: cmsCreateTransform failed

### ISSUE THREAD

**Issue by eyeds** [pymupdf/PyMuPDF#369]
## Describe the bug (mandatory)
(1) Getting an error "mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed" on particular pdf which terminates python thread.

(2) When this happens the calling threads gets SIGABRT and since I'm using ThreadPool I have to handle signal manually which is not that good.

## To Reproduce (mandatory)
```import concurrent.futures
import os
import fitz

imgdir = 'images'  # found images are stored here
zoom = 150.0 / 72.0


def chunks(l, n):
    for i in range(0, len(l), n):
        yield l[i:i + n]


def process_doc(path, first, last):
    doc = fitz.open(path)
    print('From page {} to {}'.format(first, last))
    mat = fitz.Matrix(zoom, zoom)
    for i in range(first, last + 1):
        print('Page {}'.format(i))
        p = doc[i]
        d = fitz.Rect(p.CropBoxPosition, p.CropBoxPosition)
        r1 = fitz.Rect(0, 0, p.rect.height, p.rect.width * 0.25) + d
        pix = p.getPixmap(colorspace=fitz.csGRAY, matrix=mat, alpha=False, clip=r1)
        imgname = os.path.join(imgdir, 't-{}.png'.format(p.number))
        pix.writePNG(imgname)
        pix = None


def process_file(path):
    if not os.path.exists(imgdir):
        os.mkdir(imgdir)
    doc = fitz.open(path)
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
        # process in 5-page batches
        image_list = list(chunks(range(0, doc.pageCount - 1), 5))
        doc.close()
        for il in image_list:
            executor.submit(process_doc, path, il[0], il[-1])
    return


if __name__ == '__main__':
    process_file('fail.pdf')
```

PDF file: [fail.pdf](https://github.com/pymupdf/PyMuPDF/files/3675309/fail.pdf)

```
From page 0 to 4
Page 0
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed
From page 5 to 9
Page 5
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed
Page 1
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),DeviceGray) failed
Fatal Python error: ceval: tstate mix-up

Current thread 0x000070000cbb4000 (most recent call first):
  File "/Users/.../venv/lib/python3.7/site-packages/fitz/fitz.py", line 4823 in getPixmap
  File "/Users/.../venv/lib/python3.7/site-packages/fitz/utils.py", line 566 in getPixmap
  File "/Users/.../utils/pdf/fitz_mupdf_demo.py", line 24 in process_doc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57 in run
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 80 in _worker
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865 in run
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 885 in _bootstrap
...
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
## Expected behavior (optional)
(1) It is mupdf issue itself? What is special with this pdf? Converted thousands of others and this is the first one failed.
(2) Throw exception instead of SIGABRT if possible.

## Your configuration (mandatory)
```print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] 
 darwin 
 
PyMuPDF 1.16.2: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-09-12 17:43:20.
Built for Python 3.7 on darwin (64-bit).

mudraw -v
mudraw version 1.15.0
Installed from brew
```
Obviously py and mu versions are not matching since I didn't build mu muself (1.15.0 is the latest on brew).

Thank you for amazing library!

**Comment by JorjMcKie** [comment]
A complex situation:
* you are right: there should be an exception and not an interpreter crash
* **you script works if I let it run with v1.14.21**
* ``concurrent.futures`` seems to use Python threading. This is not supported by MuPDF, and hence not by PyMuPDF. Use ``multiprocessing`` if you want speed imrpovements.
* a script which **sequentially reads** the pages (i.e. not using threading) does not fail with v.1.16.x
* MuPDF 1.16.x and also PyMuPDF v1.16.x produce garbage images with this PDF. This does not happen when using v1.14.x - for both, mutool and PyMuPDF
* also MuPDFs own PDF viewer v1.16 shows garbage!

I will try to re-generate PyMuPDF with ICC support taken out completely. If this also fails or produces garbage, we have a case of an upstream bug in MuPDF.

**Comment by JorjMcKie** [comment]
> Obviously py and mu versions are not matching since I didn't build mu muself (1.15.0 is the latest on brew).

This is a matter of course: if you install a wheel, the MuPDF binaries used at  generation time are baked into it and may differ from what else is present on your machine.

**Comment by JorjMcKie** [comment]
Aha!
When taking out ICC support from PyMuPDF, the problem disappears!
Your script works as it did with version 1.14.21 - but note my remark wrt to using ``concurrent.futures``.

I will now go ahead and publish a new version (1.16.3) which should fix your issue. Take me the better part of today. If you are in a hurry, install ``pymupdf==1.14.21`` in the meantime.

**Comment by eyeds** [comment]
Jorj,
Thank you so much for swift reply!

> * you are right: there should be an exception and not an interpreter crash
> * **you script works if I let it run with v1.14.21**

Confirm, tested.

> * `concurrent.futures` seems to use Python threading. This is not supported by MuPDF, and hence not by PyMuPDF. Use `multiprocessing` if you want speed imrpovements.

Unfortunately I can't because I launch it from celery task and can only start threads. I can move to subtasks but it is a bit complex now. For every new thread I reopen file with fitz.open, can it cause problems?
> * a script which **sequentially reads** the pages (i.e. not using threading) does not fail with v.1.16.x

Confirm, error is there but does not kill the interpreter.
> * MuPDF 1.16.x and also PyMuPDF v1.16.x produce garbage images with this PDF. This does not happen when using v1.14.x - for both, mutool and PyMuPDF
MuPDF 1.15.0 + PyMuPDF 1.14.21 also worked fine.
> * also MuPDFs own PDF viewer v1.16 shows garbage!
> 
> I will try to re-generate PyMuPDF with ICC support taken out completely. If this also fails or produces garbage, we have a case of an upstream bug in MuPDF.

So ICC removed doesn't produce garbage anymore? Did I get correctly?

> I will now go ahead and publish a new version (1.16.3) which should fix your issue. Take me the better part of today. If you are in a hurry, install `pymupdf==1.14.21` in the meantime.

I made a workaround catching SIGABRT but I'll move to 1.14.12, thanks.

**Comment by JorjMcKie** [comment]
> So ICC removed doesn't produce garbage anymore? Did I get correctly?

Correct. I am generating new wheels for this modification currently. I tested your script on Windows with 1.16.3 and it works!
So later during today you should be seeing that new version on PyPI (if I am not suffering internet issues which prevent me from uploading it).
If you are in a real hurry, I yould send you your MacOS wheel also via e-mail ...

**Comment by eyeds** [comment]
Thanks! It is ok, I can wait for release.

**Comment by JorjMcKie** [comment]
> For every new thread I reopen file with fitz.open, can it cause problems?

Actually it shouldn't. As I wrote, your script works ...
PyMuPDF is ignoring threads, so remains in one process. Every ``fitzopen()`` just creates a new document object, which does not share resources with other copies.
Of course the process as a whole is put on wait whenever a subtask has to wait for something. So the best performance given your limitations is therefore one that does not in turn create new subtasks, meaning you can process your files just in sequential manner and still be faster than before, because no additional subtasking overhead ...

**Comment by eyeds** [comment]
>PyMuPDF is ignoring threads, so remains in one process. Every fitzopen() just creates a new document object, which does not share resources with other copies.

Perfect.
> Of course the process as a whole is put on wait whenever a subtask has to wait for something. So the best performance given your limitations is therefore one that does not in turn create new subtasks, meaning you can process your files just in sequential manner and still be faster than before, because no additional subtasking overhead ...

Sorry, didn't specify my task correctly -- it is not to process the whole doc fast, but to find a particular page fast (seconds really count), so I make it parallel on page batches basis in batches of 5.

**Comment by JorjMcKie** [comment]
new version on PyPI already at your disposal

**Comment by eyeds** [comment]
Tested and it works, thank you!

**Comment by JorjMcKie** [comment]
Glad to hear that. Thanks you for the confirmation!

**Comment by JorjMcKie** [comment]
@eyeds - I found a way to programmatically disable ICC for cases like yours. The next PyMuPDF version **will support ICC**, so in order for you to prevent exceptions like we have been discussing here, issue this statement as / when needed:

```python
fitz.TOOLS.set_icc(False)  # and enable it again via argument True
```
