### ISSUE TITLE
Circular Import Issue

### ISSUE THREAD

**Issue by enicotra65** [pymupdf/PyMuPDF#3692]
### Description of the bug

I had just uninstalled and reinstalled PymuPDF with pip, I updated pip, I updated PyMuPDF, and I keep getting this circular import error:

ImportError: cannot import name '_extra' from partially initialized module 'pymupdf' 

From within the library, I never changed it, I haven't touched the library at all, and 2 weeks later this is what happens when I try to run my application which uses PyMuPDF. 

### How to reproduce the bug

Running a script that imports Fitz (example script):

import fitz  # PyMuPDF

def test_pymupdf():
    try:
        # Open a sample PDF file
        pdf_path = "sample.pdf"  # Replace with the path to your test PDF file
        document = fitz.open(pdf_path)

        # Print the number of pages
        num_pages = document.page_count
        print(f"Number of pages: {num_pages}")

        # Extract text from the first page
        first_page = document.load_page(0)
        text = first_page.get_text()
        print(f"Text from the first page:\n{text}")

        # Save the first page as an image
        pix = first_page.get_pixmap()
        image_path = "first_page.png"
        pix.save(image_path)
        print(f"First page saved as image: {image_path}")

        # Close the document
        document.close()
        print("Test completed successfully.")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    test_pymupdf()

### PyMuPDF version

1.24.7

### Operating system

Windows

### Python version

3.12

**Comment by enicotra65** [comment]
My bad it was an issue on my end, I'm pretty sure something got corrupted you can forget this was here sorrrryy

**Comment by julian-smith-artifex-com** [comment]
No problem, thanks for letting us know.

**Comment by sehmaschine** [comment]
@enicotra65 Do you have any idea what you did in order to solve this? I'm running into the same issue (with AWS lambda) and I tried everything for 2 days now (without success).

**Comment by enicotra65** [comment]
What was the problem?

**Comment by sehmaschine** [comment]
@enicotra65 Exactly what you described (the import error on `_extra`). I think it has something to do with the serverless version (because it works with v3 but throws an error with v4). So we downgraded to v3 for the moment.

**Comment by enicotra65** [comment]
Yeah im pretty sure thats what i did i tried another version of it and it
worked it was a while ago
