### ISSUE TITLE
page.search_for(text) splits a line break into two completely different objects

### ISSUE THREAD

**Issue by eliyotz** [pymupdf/PyMuPDF#3694]
### Description of the bug

I use PyMuPDF for document reduction. Sometimes I want to reduct only one instance of a certain text on the page, then I use an index
```
areas = page.search_for(text)
area = areas[index]
```
The problem is that if there is a line break in the middle of the phrase I was looking for, or certain designs that split the text, it turns it into two different instances and confuses my index
Is there no way to detect whether multiple objects belong to the same single expression?

### How to reproduce the bug

```
    def RedactSelectedInstance(self, text, instance_index, page_number=-1):

        if not self.pdf_document:
            return
        if page_number == -1:
            page = self.pdf_document[self.current_page_number]
        else:
            page = self.pdf_document[page_number - 1]
        areas = page.search_for(text)
        if areas and 0 <= instance_index <= len(areas):
            area = areas[instance_index]
            page.add_redact_annot(area, text="█" * len(text), fill=(0, 0, 0))
            page.apply_redactions()
```

### PyMuPDF version

1.24.7

### Operating system

Windows

### Python version

3.10

**Comment by JorjMcKie** [comment]
I think you asked the same question on StackOverflow where I have answered it.
