### ISSUE TITLE
Bounding boxes are much taller than visible text sometimes

### ISSUE THREAD

**Issue by miikatoi** [pymupdf/PyMuPDF#3718]
### Description of the bug

I have encountered some cases where the bounding boxes of spans (and characters) extracted with PyMuPDF are much taller than the visible height of the text, but only for non-english characters in specific files.

### How to reproduce the bug

This seems to always happen when using pdf-files converted from docx-format with [libreoffice-docker](https://github.com/libreofficedocker/libreoffice-unoserver). Below is an example of [sample files](https://www.duxburysystems.com/documentation/dbt12.7/Content/samples/word/samples.htm) converted into pdf in two languages.

Example files:
[english-en.pdf](https://github.com/user-attachments/files/16357419/english-en.pdf)
[korean-ko.pdf](https://github.com/user-attachments/files/16357420/korean-ko.pdf)

Code to reproduce:
```python
import fitz
from PIL import Image

file_path = "korean-ko.pdf"
# file_path = "english-en.pdf"

doc = fitz.open(file_path)
page = doc.load_page(0)
blocks = page.get_text("rawdict", sort=True)["blocks"]

for b in blocks:
    if b["type"] == 0:
        for line in b["lines"]:
            for span in line["spans"]:
                page.draw_rect(span['bbox'], width=1, color=(1,0,0))

pix = page.get_pixmap()
img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

display(img)
```

Resulting Images:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/7ccc0629-e129-49d3-b18d-cba40a276644">

The suggested solution in https://github.com/pymupdf/PyMuPDF/issues/739 removes the biggest problems, which is sufficient for my use case, but it still does not perfectly align so I am reporting it here.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/4aed2025-a0ab-409b-81ad-4c105fbb496f">

### PyMuPDF version

1.24.8

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
This is no bug: the font chosen by that converter simply is like that.
```python
doc=pymupdf.open("korean-ko.pdf")
pprint(doc.get_page_fonts(0))
[(84, 'pfa', 'Type1', 'BAAAAA+NotoSansCJKhk-Bold', 'F1', ''),
 (79, 'ttf', 'TrueType', 'CAAAAA+TimesNewRomanPS-BoldMT', 'F2', ''),
 (94, 'ttf', 'TrueType', 'DAAAAA+TimesNewRomanPSMT', 'F3', ''),
 (89, 'pfa', 'Type1', 'EAAAAA+NotoSansCJKhk-Regular', 'F4', '')]

# extract font at xref 84 for example:
ff = doc.extract_font(84)

# make pymupdf Font object from it
font84 = pymupdf.Font(fontbuffer=ff[-1])
font84
Font('NotoSansCJKhk-Bold Regular')

# look at font properties ascender, descender
font84.ascender
1.8070000410079956
font84.descender
-1.0460000038146973
# so for any given fontsize "fs", the line height is ...
fs = 10
lineheight = (font84.ascender - font84.descender) * fs
lineheight
28.53000044822693
# Almost 3 times font size! This results in your enormous inter-line overlaps.
```
