### ISSUE TITLE
Cannot be installed on python 3.8-rc1

### ISSUE THREAD

**Issue by hauworkarea** [pymupdf/PyMuPDF#372]
Hello!

## Describe the bug (mandatory)
I try to install pymupdf via pip on python 3.8-rc1 but I get an error (in the attachment). On the same machine with python 3.6 and 3.7 there are no problems.
What's wrong?

## Your configuration (mandatory)
 - MacOS 10.14.6
 - Python version, 3.8-rc1
 - PyMuPDF version, 1.16.3 wheel.

> (tools.3.8-rc1) [8:35:51] user:tools git:(master*) $ pip install -U pymupdf
Collecting pymupdf
  Using cached https://files.pythonhosted.org/packages/c9/10/be4910656cd54b781331bc7abd4742a53f3937c5baf769832ccd48bc68d9/PyMuPDF-1.16.3.tar.gz
Installing collected packages: pymupdf
  Running setup.py install for pymupdf ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/user/PycharmProjects/env/tools.3.8-rc1/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/89/z_dcckks17b07n6rdbx4xp240000gp/T/pip-install-a0wkwx4o/pymupdf/setup.py'"'"'; __file__='"'"'/private/var/folders/89/z_dcckks17b07n6rdbx4xp240000gp/T/pip-install-a0wkwx4o/pymupdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/89/z_dcckks17b07n6rdbx4xp240000gp/T/pip-record-lzd5tyqi/install-record.txt --single-version-externally-managed --compile --install-headers /Users/user/PycharmProjects/env/tools.3.8-rc1/include/site/python3.8/pymupdf
         cwd: /private/var/folders/89/z_dcckks17b07n6rdbx4xp240000gp/T/pip-install-a0wkwx4o/pymupdf/
    Complete output (283 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.8
    creating build/lib.macosx-10.14-x86_64-3.8/fitz
    copying fitz/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/fitz
    copying fitz/fitz.py -> build/lib.macosx-10.14-x86_64-3.8/fitz
    copying fitz/utils.py -> build/lib.macosx-10.14-x86_64-3.8/fitz
    running build_ext
    building 'fitz._fitz' extension
    creating build/temp.macosx-10.14-x86_64-3.8
    creating build/temp.macosx-10.14-x86_64-3.8/fitz
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/include/mupdf -I/usr/local/include -I/Users/user/PycharmProjects/env/tools.3.8-rc1/include -I/Users/user/.pyenv/versions/3.8-dev/include/python3.8 -c fitz/fitz_wrap.c -o build/temp.macosx-10.14-x86_64-3.8/fitz/fitz_wrap.o
    fitz/fitz_wrap.c:3503:54: warning: incompatible pointer types passing 'char **' to parameter of type 'unsigned char **' [-Wincompatible-pointer-types]
            size_t len = fz_buffer_storage(gctx, buffer, &c);
                                                         ^~
    /usr/local/include/mupdf/fitz/buffer.h:18:75: note: passing argument to parameter 'datap' here
    size_t fz_buffer_storage(fz_context *ctx, fz_buffer *buf, unsigned char **datap);
                                                                              ^
    fitz/fitz_wrap.c:3519:53: warning: incompatible pointer types passing 'char **' to parameter of type 'unsigned char **' [-Wincompatible-pointer-types]
            size_t len = fz_buffer_storage(ctx, buffer, &c);
                                                        ^~
    /usr/local/include/mupdf/fitz/buffer.h:18:75: note: passing argument to parameter 'datap' here
    size_t fz_buffer_storage(fz_context *ctx, fz_buffer *buf, unsigned char **datap);
                                                                              ^
    fitz/fitz_wrap.c:3536:53: warning: incompatible pointer types passing 'char **' to parameter of type 'unsigned char **' [-Wincompatible-pointer-types]
            size_t len = fz_buffer_storage(ctx, buffer, &c);
                                                        ^~
    /usr/local/include/mupdf/fitz/buffer.h:18:75: note: passing argument to parameter 'datap' here
    size_t fz_buffer_storage(fz_context *ctx, fz_buffer *buf, unsigned char **datap);
                                                                              ^
    fitz/fitz_wrap.c:3540:51: warning: incompatible pointer types passing 'char **' to parameter of type 'unsigned char **' [-Wincompatible-pointer-types]
            size_t nlen = fz_buffer_storage(ctx, res, &b64);
                                                      ^~~~
    /usr/local/include/mupdf/fitz/buffer.h:18:75: note: passing argument to parameter 'datap' here
    size_t fz_buffer_storage(fz_context *ctx, fz_buffer *buf, unsigned char **datap);
                                                                              ^
    fitz/fitz_wrap.c:3709:58: warning: passing 'char *' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
            if (c) res = fz_new_buffer_from_copied_data(ctx, c, len);
                                                             ^
    /usr/local/include/mupdf/fitz/buffer.h:28:81: note: passing argument to parameter 'data' here
    fz_buffer *fz_new_buffer_from_copied_data(fz_context *ctx, const unsigned char *data, size_t size);
                                                                                    ^
    fitz/fitz_wrap.c:4210:19: warning: unsequenced modification and access to 's' [-Wunsequenced]
                    *s++ = 255 - *s;
                      ^           ~
    fitz/fitz_wrap.c:4211:30: warning: expression result unused [-Wunused-value]
                if (dest->alpha) *s++;
                                 ^~~~
    fitz/fitz_wrap.c:4237:11: warning: assigning to 'unsigned char *' from 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
            c = PyBytes_AS_STRING(imagedata);
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fitz/fitz_wrap.c:4242:11: warning: assigning to 'unsigned char *' from 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
            c = PyByteArray_AS_STRING(imagedata);
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fitz/fitz_wrap.c:4362:50: warning: incompatible pointer types passing 'char **' to parameter of type 'unsigned char **' [-Wincompatible-pointer-types]
            size_t len = fz_buffer_storage(ctx, buf, &da);
                                                     ^~~
    /usr/local/include/mupdf/fitz/buffer.h:18:75: note: passing argument to parameter 'datap' here
    size_t fz_buffer_storage(fz_context *ctx, fz_buffer *buf, unsigned char **datap);
                                                                              ^
    fitz/fitz_wrap.c:4576:42: warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        PyObject *val = PyUnicode_DecodeUTF8(s, (Py_ssize_t) len, "replace");
                                             ^
    /Users/user/.pyenv/versions/3.8-dev/include/python3.8/unicodeobject.h:463:17: note: passing argument to parameter 'string' here
        const char *string,         /* UTF-8 encoded string */
                    ^
    fitz/fitz_wrap.c:4591:51: warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        PyObject *val = PyUnicode_DecodeUnicodeEscape(s, (Py_ssize_t) len, "replace");
                                                      ^
    /Users/user/.pyenv/versions/3.8-dev/include/python3.8/unicodeobject.h:600:17: note: passing argument to parameter 'string' here
        const char *string,         /* Unicode-Escape encoded string */
                    ^
    fitz/fitz_wrap.c:4605:40: warning: passing 'const unsigned char [2]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        return PyUnicode_FromStringAndSize(data, 2);
                                           ^~~~
    /Users/user/.pyenv/versions/3.8-dev/include/python3.8/unicodeobject.h:131:17: note: passing argument to parameter 'u' here
        const char *u,             /* UTF-8 encoded string */
                    ^
    fitz/fitz_wrap.c:4754:27: error: no member named 'color' in 'struct fz_stext_char_s'
            style.color = ch->color;
                          ~~  ^
    fitz/fitz_wrap.c:4894:73: error: passing 'fz_color_params' (aka 'struct fz_color_params_s') to parameter of incompatible type 'const fz_color_params *' (aka 'const struct fz_color_params_s *'); take the address with &
                buf = freebuf = fz_new_buffer_from_image_as_png(ctx, image, color_params);
                                                                            ^~~~~~~~~~~~
                                                                            &
    /usr/local/include/mupdf/fitz/write-pixmap.h:78:101: note: passing argument to parameter 'color_params' here
    fz_buffer *fz_new_buffer_from_image_as_png(fz_context *ctx, fz_image *image, const fz_color_params *color_params);
                                                                                                        ^
    fitz/fitz_wrap.c:5302:17: warning: implicit declaration of function 'pdf_signature_is_signed' is invalid in C99 [-Wimplicit-function-declaration]
                if (pdf_signature_is_signed(ctx, pdf, annot->obj))
                    ^
    fitz/fitz_wrap.c:5662:64: warning: passing 'char [3]' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                               fz_new_buffer_from_copied_data(ctx, "  ", 1),
                                                                   ^~~~
    /usr/local/include/mupdf/fitz/buffer.h:28:81: note: passing argument to parameter 'data' here
    fz_buffer *fz_new_buffer_from_copied_data(fz_context *ctx, const unsigned char *data, size_t size);
                                                                                    ^
    fitz/fitz_wrap.c:6097:22: warning: unused variable 'contents' [-Wunused-variable]
        pdf_obj *xobj1, *contents = NULL, *resources = NULL, *o, *spageref;
                         ^
    fitz/fitz_wrap.c:6551:51: warning: incompatible pointer types passing 'char **' to parameter of type 'unsigned char **' [-Wincompatible-pointer-types]
            size_t len = fz_buffer_storage(gctx, res, &c);
                                                      ^~
    /usr/local/include/mupdf/fitz/buffer.h:18:75: note: passing argument to parameter 'datap' here
    size_t fz_buffer_storage(fz_context *ctx, fz_buffer *buf, unsigned char **datap);
                                                                              ^
    fitz/fitz_wrap.c:6807:24: error: member reference type 'fz_error_context *' (aka 'struct fz_error_context_s *') is a pointer; did you mean to use '->'?
                gctx->error.errcode = 0;       // reset any error code
                ~~~~~~~~~~~^
                           ->
    fitz/fitz_wrap.c:6808:24: error: member reference type 'fz_error_context *' (aka 'struct fz_error_context_s *') is a pointer; did you mean to use '->'?
                gctx->error.message[0] = 0;    // reset any error message
                ~~~~~~~~~~~^
                           ->
    fitz/fitz_wrap.c:6827:49: warning: passing 'char *' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                        data = fz_open_memory(gctx, c, len);
                                                    ^
    /usr/local/include/mupdf/fitz/stream.h:25:65: note: passing argument to parameter 'data' here
    fz_stream *fz_open_memory(fz_context *ctx, const unsigned char *data, size_t len);
                                                                    ^
    fitz/fitz_wrap.c:7050:24: warning: unused variable 'name_len' [-Wunused-variable]
                Py_ssize_t name_len = 0;
                           ^
    fitz/fitz_wrap.c:7052:19: warning: unused variable 'sname' [-Wunused-variable]
                char *sname = NULL;
                      ^
    fitz/fitz_wrap.c:7191:54: warning: incompatible pointer types passing 'char **' to parameter of type 'unsigned char **' [-Wincompatible-pointer-types]
                    size = fz_buffer_storage(gctx, data, &buffdata);
                                                         ^~~~~~~~~
    /usr/local/include/mupdf/fitz/buffer.h:18:75: note: passing argument to parameter 'datap' here
    size_t fz_buffer_storage(fz_context *ctx, fz_buffer *buf, unsigned char **datap);
                                                                              ^
    fitz/fitz_wrap.c:7183:17: warning: unused variable 'entry' [-Wunused-variable]
                int entry = 0;
                    ^
    fitz/fitz_wrap.c:7434:57: warning: incompatible pointer types passing 'char **' to parameter of type 'unsigned char **' [-Wincompatible-pointer-types]
                            fz_buffer_storage(gctx, buffer, &hex);
                                                            ^~~~
    /usr/local/include/mupdf/fitz/buffer.h:18:75: note: passing argument to parameter 'datap' here
    size_t fz_buffer_storage(fz_context *ctx, fz_buffer *buf, unsigned char **datap);
                                                                              ^
    fitz/fitz_wrap.c:7478:38: error: use of undeclared identifier 'pdf_default_write_options'; did you mean 'pdf_parse_write_options'?
                pdf_write_options opts = pdf_default_write_options;
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
                                         pdf_parse_write_options
    /usr/local/include/mupdf/pdf/document.h:295:20: note: 'pdf_parse_write_options' declared here
    pdf_write_options *pdf_parse_write_options(fz_context *ctx, pdf_write_options *opts, const char *args);
                       ^
    fitz/fitz_wrap.c:7478:31: error: initializing 'pdf_write_options' (aka 'struct pdf_write_options_s') with an expression of incompatible type 'pdf_write_options *(fz_context *, pdf_write_options *, const char *)' (aka 'struct pdf_write_options_s *(struct fz_context_s *, struct pdf_write_options_s *, const char *)')
                pdf_write_options opts = pdf_default_write_options;
                                  ^      ~~~~~~~~~~~~~~~~~~~~~~~~~
    fitz/fitz_wrap.c:7517:38: error: use of undeclared identifier 'pdf_default_write_options'; did you mean 'pdf_parse_write_options'?
                pdf_write_options opts = pdf_default_write_options;
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
                                         pdf_parse_write_options
    /usr/local/include/mupdf/pdf/document.h:295:20: note: 'pdf_parse_write_options' declared here
    pdf_write_options *pdf_parse_write_options(fz_context *ctx, pdf_write_options *opts, const char *args);
                       ^
    fitz/fitz_wrap.c:7517:31: error: initializing 'pdf_write_options' (aka 'struct pdf_write_options_s') with an expression of incompatible type 'pdf_write_options *(fz_context *, pdf_write_options *, const char *)' (aka 'struct pdf_write_options_s *(struct fz_context_s *, struct pdf_write_options_s *, const char *)')
                pdf_write_options opts = pdf_default_write_options;
                                  ^      ~~~~~~~~~~~~~~~~~~~~~~~~~
    fitz/fitz_wrap.c:7646:21: warning: unused variable 'count' [-Wunused-variable]
                    int count = fz_count_pages(gctx, self);
                        ^
    fitz/fitz_wrap.c:7694:26: warning: assigning to 'const char *' from 'const unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                        data = fz_lookup_cjk_font(gctx, ordering, &size, &index);
                             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fitz/fitz_wrap.c:7695:64: warning: passing 'const char *' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                        font = fz_new_font_from_memory(gctx, NULL, data, size, index, 0);
                                                                   ^~~~
    /usr/local/include/mupdf/fitz/font.h:178:90: note: passing argument to parameter 'data' here
    fz_font *fz_new_font_from_memory(fz_context *ctx, const char *name, const unsigned char *data, int len, int index, int use_glyph_bbox);
                                                                                             ^
    fitz/fitz_wrap.c:7698:22: warning: assigning to 'const char *' from 'const unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                    data = fz_lookup_base14_font(gctx, bfname, &size);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fitz/fitz_wrap.c:7701:66: warning: passing 'const char *' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                        font = fz_new_font_from_memory(gctx, bfname, data, size, 0, 0);
                                                                     ^~~~
    /usr/local/include/mupdf/fitz/font.h:178:90: note: passing argument to parameter 'data' here
    fz_font *fz_new_font_from_memory(fz_context *ctx, const char *name, const unsigned char *data, int len, int index, int use_glyph_bbox);
                                                                                             ^
    fitz/fitz_wrap.c:7686:36: warning: unused variable 'fb_font' [-Wunused-variable]
                fz_font *font = NULL, *fb_font= NULL;
                                       ^
    fitz/fitz_wrap.c:7683:17: warning: unused variable 'lang' [-Wunused-variable]
                int lang = 0;
                    ^
    fitz/fitz_wrap.c:7682:17: warning: unused variable 'cwlen' [-Wunused-variable]
                int cwlen = 0;
                    ^
    fitz/fitz_wrap.c:7800:24: warning: unused variable 'len' [-Wunused-variable]
                Py_ssize_t len = 0;
                           ^
    fitz/fitz_wrap.c:7933:71: error: passing 'fz_color_params' (aka 'struct fz_color_params_s') to parameter of incompatible type 'const fz_color_params *' (aka 'const struct fz_color_params_s *'); take the address with &
                                         fz_device_rgb(gctx), NULL, NULL, color_params, 1);
                                                                          ^~~~~~~~~~~~
                                                                          &
    /usr/local/include/mupdf/fitz/pixmap.h:77:165: note: passing argument to parameter 'color_params' here
    fz_pixmap *fz_convert_pixmap(fz_context *ctx, fz_pixmap *pix, fz_colorspace *cs_des, fz_colorspace *prf, fz_default_colorspaces *default_cs, const fz_color_params *color_params, int keep_alpha);
                                                                                                                                                                        ^
    fitz/fitz_wrap.c:8351:69: warning: passing 'char [3]' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                                   fz_new_buffer_from_copied_data(gctx, "  ", 1), NULL, 0);
                                                                        ^~~~
    /usr/local/include/mupdf/fitz/buffer.h:28:81: note: passing argument to parameter 'data' here
    fz_buffer *fz_new_buffer_from_copied_data(fz_context *ctx, const unsigned char *data, size_t size);
                                                                                    ^
    fitz/fitz_wrap.c:8331:22: warning: unused variable 'page2' [-Wunused-variable]
                pdf_obj *page2 = NULL;
                         ^
    fitz/fitz_wrap.c:8387:26: warning: unused variable 'page2' [-Wunused-variable]
                    pdf_obj *page2 = pdf_lookup_page_loc(gctx, pdf, nb, &parent2, &i2);
                             ^
    fitz/fitz_wrap.c:8476:29: warning: unused variable 'seps' [-Wunused-variable]
                fz_separations *seps = NULL;
                                ^
    fitz/fitz_wrap.c:8509:31: warning: unused variable 'pdf' [-Wunused-variable]
                    pdf_document *pdf = page->doc;
                                  ^
    fitz/fitz_wrap.c:8652:19: warning: unused variable 'data' [-Wunused-variable]
                char *data = NULL, *uf = ufilename, *d = desc;
                      ^
    fitz/fitz_wrap.c:8655:20: warning: unused variable 'len' [-Wunused-variable]
                size_t len = 0;
                       ^
    fitz/fitz_wrap.c:9144:77: error: passing 'fz_color_params' (aka 'struct fz_color_params_s') to parameter of incompatible type 'const fz_color_params *' (aka 'const struct fz_color_params_s *'); take the address with &
                            pm = fz_convert_pixmap(gctx, pix, NULL, NULL, NULL, color_params, 1);
                                                                                ^~~~~~~~~~~~
                                                                                &
    /usr/local/include/mupdf/fitz/pixmap.h:77:165: note: passing argument to parameter 'color_params' here
    fz_pixmap *fz_convert_pixmap(fz_context *ctx, fz_pixmap *pix, fz_colorspace *cs_des, fz_colorspace *prf, fz_default_colorspaces *default_cs, const fz_color_params *color_params, int keep_alpha);
                                                                                                                                                                        ^
    fitz/fitz_wrap.c:9160:80: error: passing 'fz_color_params' (aka 'struct fz_color_params_s') to parameter of incompatible type 'const fz_color_params *' (aka 'const struct fz_color_params_s *'); take the address with &
                            pm = fz_convert_pixmap(gctx, pixmap, NULL, NULL, NULL, color_params, 1);
                                                                                   ^~~~~~~~~~~~
                                                                                   &
    /usr/local/include/mupdf/fitz/pixmap.h:77:165: note: passing argument to parameter 'color_params' here
    fz_pixmap *fz_convert_pixmap(fz_context *ctx, fz_pixmap *pix, fz_colorspace *cs_des, fz_colorspace *prf, fz_default_colorspaces *default_cs, const fz_color_params *color_params, int keep_alpha);
                                                                                                                                                                        ^
    fitz/fitz_wrap.c:9391:68: error: passing 'fz_color_params' (aka 'struct fz_color_params_s') to parameter of incompatible type 'const fz_color_params *' (aka 'const struct fz_color_params_s *'); take the address with &
                    pm = fz_convert_pixmap(gctx, spix, cs, NULL, NULL, color_params, 1);
                                                                       ^~~~~~~~~~~~
                                                                       &
    /usr/local/include/mupdf/fitz/pixmap.h:77:165: note: passing argument to parameter 'color_params' here
    fz_pixmap *fz_convert_pixmap(fz_context *ctx, fz_pixmap *pix, fz_colorspace *cs_des, fz_colorspace *prf, fz_default_colorspaces *default_cs, const fz_color_params *color_params, int keep_alpha);
                                                                                                                                                                        ^
    fitz/fitz_wrap.c:9467:32: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
                    if (stride * h != size) THROWMSG("bad samples length");
                        ~~~~~~~~~~ ^  ~~~~
    fitz/fitz_wrap.c:10227:19: warning: unused variable 'data' [-Wunused-variable]
                char *data = NULL;              // for new file content
                      ^
    fitz/fitz_wrap.c:10230:21: warning: unused variable 'size' [-Wunused-variable]
                int64_t size = 0;
                        ^
    fitz/fitz_wrap.c:10759:70: error: too many arguments to function call, expected 3, have 4
                            fz_print_stext_page_as_html(gctx, out, self, 0);
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~                  ^
    /usr/local/include/mupdf/fitz/structured-text.h:114:1: note: 'fz_print_stext_page_as_html' declared here
    void fz_print_stext_page_as_html(fz_context *ctx, fz_output *out, fz_stext_page *page);
    ^
    fitz/fitz_wrap.c:10762:69: error: too many arguments to function call, expected 3, have 4
                            fz_print_stext_page_as_xml(gctx, out, self, 0);
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~                  ^
    /usr/local/include/mupdf/fitz/structured-text.h:122:1: note: 'fz_print_stext_page_as_xml' declared here
    void fz_print_stext_page_as_xml(fz_context *ctx, fz_output *out, fz_stext_page *page);
    ^
    fitz/fitz_wrap.c:10765:71: error: too many arguments to function call, expected 3, have 4
                            fz_print_stext_page_as_xhtml(gctx, out, self, 0);
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                  ^
    /usr/local/include/mupdf/fitz/structured-text.h:118:1: note: 'fz_print_stext_page_as_xhtml' declared here
    void fz_print_stext_page_as_xhtml(fz_context *ctx, fz_output *out, fz_stext_page *page);
    ^
    fitz/fitz_wrap.c:20599:3: warning: implicit declaration of function 'fz_set_warning_callback' is invalid in C99 [-Wimplicit-function-declaration]
      fz_set_warning_callback(gctx, JM_mupdf_warning, &user);
      ^
    fitz/fitz_wrap.c:20600:3: warning: implicit declaration of function 'fz_set_error_callback' is invalid in C99 [-Wimplicit-function-declaration]
      fz_set_error_callback(gctx, JM_mupdf_error, &user);
      ^
    44 warnings and 15 errors generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/user/PycharmProjects/env/tools.3.8-rc1/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/89/z_dcckks17b07n6rdbx4xp240000gp/T/pip-install-a0wkwx4o/pymupdf/setup.py'"'"'; __file__='"'"'/private/var/folders/89/z_dcckks17b07n6rdbx4xp240000gp/T/pip-install-a0wkwx4o/pymupdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/89/z_dcckks17b07n6rdbx4xp240000gp/T/pip-record-lzd5tyqi/install-record.txt --single-version-externally-managed --compile --install-headers /Users/user/PycharmProjects/env/tools.3.8-rc1/include/site/python3.8/pymupdf Check the logs for full command output.

**Comment by JorjMcKie** [comment]
There do not yet exist wheels for Python 3.8 on PyPI. PIP will therefore automatically try to install from sources.
This would certainly work if the following two conditions were satisfied:
1. You have installed the development version of Python 3.8 (which seems to be the case)
2. You have installed MuPDF (which is **not** the case)

So you either need to wait until my wheel generator web site Travis supports Python 3.8, or you install MuPDF on your machine and else follow the instructions for installing PyMuPDF on OSX.

Sorry about that!
