### ISSUE TITLE
 IndexError: list index out of range When reading table

### ISSUE THREAD

**Issue by TranThuyy** [pymupdf/PyMuPDF#3724]
### Description of the bug

 IndexError: list index out of range When reading table
 
<img width="580" alt="Untitled" src="https://github.com/user-attachments/assets/0f3b1df6-874b-41f0-9a1c-ea372886d09b">

### How to reproduce the bug

tabs = page.find_tables()

### PyMuPDF version

1.23.x or earlier

### Operating system

Linux

### Python version

3.11

**Comment by JorjMcKie** [comment]
Sorry, we need the example page and a code snippet for accepting this as a bug report.

**Comment by JorjMcKie** [comment]
Closed for lack of reaction over an extended time period.
