### ISSUE TITLE
PDF file to image, data conversion error

### ISSUE THREAD

**Issue by Agoin-max** [pymupdf/PyMuPDF#3729]
### Description of the bug

PDF file to image, data conversion error

```
import fitz
import tempfile
from pathlib import Path
from PIL import Image

def pdf2png_with_pymupdf(pdf_data: Union[bytes, str], matrix: int = 2):
    images: List[Image.Image] = []
    path = tempfile.mkdtemp()
    path_ = Path(path)

    try:
        if isinstance(pdf_data, bytes):
            pdf_path = str(path_.joinpath("mypdf.pdf"))
            with open(pdf_path, "wb") as fs:
                fs.write(pdf_data)
        else:
            pdf_path = pdf_data

        doc = fitz.open(pdf_path)
        for page_index in range(len(doc)):
            page = doc.load_page(page_index)
            pix = page.get_pixmap(matrix=fitz.Matrix(matrix, matrix))  # type: ignore
            img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)  # type: ignore
            images.append(img)
        doc.close()
    finally:
        delete_temp_directory(path)
    return images
```
       
       
[354195 COMPLETE 2.pdf](https://github.com/user-attachments/files/16386317/354195.COMPLETE.2.pdf)

### How to reproduce the bug

Where data errors occur : First page of pdf file 
origin data image: 
![20240726-115954](https://github.com/user-attachments/assets/9b15b99f-ff5a-4d27-99d5-26802fbff8ef)

After converting to image:
![20240726-120142](https://github.com/user-attachments/assets/80d3500f-294f-47f6-827d-38806cbdb3c9)

### PyMuPDF version

1.24.6

### Operating system

Windows

### Python version

3.9

**Comment by JorjMcKie** [comment]
This file contains errors than prevent successful page rendering. MuPDF message:
 `warning: non-embedded font using identity encoding: CourierStd-Bold (mapping via TrueType-UCS2)`.
Other tools also have that problem.

**Comment by Agoin-max** [comment]
ok. Thanks

**Comment by ssaliabbey64-byte** [comment]
import fitz  # PyMuPDF
from pathlib import Path

# Paths
annotated_pdf_path = Path("/mnt/data/St_Andrews_Nansomba_Electrical_Annotated.pdf")
singleline_pdf_path = Path("/mnt/data/St_Andrews_Singleline_Diagram.pdf")
preview_annotated_png = Path("/mnt/data/St_Andrews_Annotated_Preview.png")
preview_singleline_png = Path("/mnt/data/St_Andrews_Singleline_Preview.png")

# Function to convert first page of PDF to PNG preview
def pdf_to_png(pdf_path, png_path, zoom=2):
    doc = fitz.open(str(pdf_path))
    page = doc[0]
    mat = fitz.Matrix(zoom, zoom)
    pix = page.get_pixmap(matrix=mat)
    pix.save(str(png_path))
    doc.close()

# Generate previews
pdf_to_png(annotated_pdf_path, preview_annotated_png)
pdf_to_png(singleline_pdf_path, preview_singleline_png)

(str(preview_annotated_png), str(preview_singleline_png))
