### ISSUE TITLE
How do I get PyMuPDF to work in Sublime Text 3?

### ISSUE THREAD

**Issue by MalikRumi** [pymupdf/PyMuPDF#373]
_**Please provide all mandatory information!**_

## To Reproduce (mandatory)

This test came from your docs:

import fitz
print(fitz.__doc__)
pdf_document = '/home/malikarumi/Projects/hattie/finer_points.pdf'
doc = fitz.Document(pdf_document)
print("number of pages: %i" % doc.pageCount)
print(doc.metadata)

When I run it from Sublime, it gives me this result:

None  # <--- This is the print function
Traceback (most recent call last):
  File "/home/malikarumi/Projects/hattie/utilities/preprocess/data_profiling/plainpdf/fitz.py", line 1, in <module>
    import fitz
  File "/home/malikarumi/Projects/hattie/utilities/preprocess/data_profiling/plainpdf/fitz.py", line 4, in <module>
    doc = fitz.Document(pdf_document)
AttributeError: module 'fitz' has no attribute 'Document'  # <-- I am not in site-packages
[Finished in 0.1s with exit code 1]
[shell_cmd: python -u "/home/malikarumi/Projects/hattie/utilities/preprocess/data_profiling/plainpdf/fitz.py"]
[dir: /home/malikarumi/Projects/hattie/utilities/preprocess/data_profiling/plainpdf]
[path: /home/malikarumi/.local/share/virtualenvs/hattie-nHCNXwaX/bin:/snap/heroku/curent/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/bin]

But in the terminal - and the same virtualenv, which is from pipenv, if that matters, I get:

>>> import fitz
>>> print(fitz.__doc__)

PyMuPDF 1.16.2: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-09-12 17:43:20.
Built for Python 3.7 on linux (64-bit).

All of my other python dependencies and modules in site-packages work as expected in Sublime.
Would putting the C helpers in site-packages help?
Currently mupdf is here: /usr/local/include/mupdf

## Your configuration (mandatory)
Ubuntu 18.04 & Python 3.7.2
pip install PyMuPDF-1.16.2-cp37-cp37m-manylinux1_x86_64.whl

**Comment by JorjMcKie** [comment]
Folder ``/home/malikarumi/Projects/hattie/utilities/preprocess/data_profiling/plainpdf/`` does not look like a subfolder of your Python's ``dist-packages`` or ``site-packages``.
But it contains a file ``fitz.py`` - named like one of the 4 files of every PyMuPDF installation.
This cannot work.

**Comment by JorjMcKie** [comment]
I assume you found the problem.
Please re-open if issues persist.
