### ISSUE TITLE
Unable to read the table correctly

### ISSUE THREAD

**Issue by qqlww1987** [pymupdf/PyMuPDF#3734]
### Description of the bug

[合并PDF_1.pdf](https://github.com/user-attachments/files/16402069/PDF_1.pdf)
use  findtable  the result like this 
![image](https://github.com/user-attachments/assets/ad7a6672-78ee-43b4-b285-02186a1adcb4)

### How to reproduce the bug

Unable to read the table correctly

### PyMuPDF version

1.24.7

### Operating system

Windows

### Python version

3.10

**Comment by JorjMcKie** [comment]
The supplied page has an extremely reduced CropBox, including the table header only.
When setting for instance CropBox = MediaBox the table will be recognized - however **_except_** the header lines, which is built in a way that the table module cannot decipher - like many other table recognizing tools as well.
So unfortunately this cannot be resolved and incomplete recognition of the table header must accepted.

**Comment by qqlww1987** [comment]
thanks, this sounds sad
