### ISSUE TITLE
Position of previous character overlaps next character

### ISSUE THREAD

**Issue by minhnbdemetio** [pymupdf/PyMuPDF#3736]
### Description of the bug

Hi, thank you for the awesome library.

I'm having some trouble with the position of characters extracted from [this PDF](https://github.com/user-attachments/files/16407281/4.pdf).
The position of the previous character is overlapping the next character. For example, in the line `YEO DO GON` on the second page, the bbox of the letter Y is 
```
Rect(14.330100059509277, 136.32901000976562, 30.990901947021484, 149.32901000976562)
```
the letter E right next to it has the bbox of
```
Rect(22.16546630859375, 136.32901000976562, 36.275665283203125, 149.32901000976562)
```
According to this information the letter Y ends at position 30.990901947021484, which is after the starting position of the letter E at 22.16546630859375. It's supposed to be before or equal to the starting position of the letter E.

### How to reproduce the bug

I'm getting character information from `get_text` method then go through blocks, lines, spans and finally chars:
```
page.get_text("rawdict", flags=1 + 2 + 8)
``` 

### PyMuPDF version

1.23.x or earlier

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
Yes, there is some overlap. This happens all the time and is no bug.
The position information is extracted correctly.

**Comment by minhnbdemetio** [comment]
Yeah I don't think it's a bug neither. But why do they overlap? Is it because of the font characteristics?

I'm using the character position information to calculate the `letter-spacing` property, if I use the information above it will be negative and it should not be.

Please give me an explanation for this.

**Comment by JorjMcKie** [comment]
Who knows ... may be not even the PDF creator ... who did this.
