### ISSUE TITLE
How to handle the case were we get bullet points in PDF to extract? 

### ISSUE THREAD

**Issue by rafayaar** [pymupdf/PyMuPDF#3739]
`  blocks = page.get_text("dict" , flags=11, sort=True)["blocks"]`

I am using above method to get text. But it converts bullet points to letter 'l(lowercase L)' every time. 
Not sure how to handle this

**Comment by JorjMcKie** [comment]
There is no way unfortunately. Your bullet points obviously are written in their own font. To cause a bullet to be written, the PDF creating app uses 'L'. There is no way of knowing the actual appearance (like a filled circular shape).

**Comment by JorjMcKie** [comment]
Maybe you have access to that font's documentation. It should show which unicode values point to which font glyphs.
Text extraction uses the opposite direction: given a glyph, what is the originating unicode? Often (not always) there is a special kind of table enabling this (the CMAP, available as PDF key To Unicode).

**Comment by JorjMcKie** [comment]
Yes, the built-in font ZapfDingbats has a bullet point for octal 154 = decimal 111 = "l".
![image](https://github.com/user-attachments/assets/2a7b6c89-cd87-4019-b676-bb9370c6dfa2)
