### ISSUE TITLE
page.insert_htmlbox() and  page.clean_contents() not working properly.

### ISSUE THREAD

**Issue by elipongr** [pymupdf/PyMuPDF#3741]
### Description of the bug

We use PyMyPDF for putting stamps onto our PDF. 

We run into 2 issues.

When we just do on some PDF
`page.insert_htmlbox` (or any other insert) with `page.clean_contents(false)` or no clean the text is not visible, it is inserted but on a lower layer, but adding a border with the draw function works completly fine. See example:
Before:
![image](https://github.com/user-attachments/assets/392fbf2d-3f36-4c82-8f81-384144b50aa6)
After(in the red rectangle there should be text):
![image](https://github.com/user-attachments/assets/b5435836-1f92-4425-b667-01dd5412a256)

Now adding `page.clean_contents(true)` before the insert solves the issue, but causes other PDF's when trying to stamp them to completely get destroyed. See example:
Before:
![image](https://github.com/user-attachments/assets/2acd3c53-4ec9-4628-ac8d-71a2c669506f)
After(stamp added on bottom left):
![image](https://github.com/user-attachments/assets/81734a84-2cd9-4a98-b7be-afbb295a5bd5)

### How to reproduce the bug

[sanitize_false_text_missing.pdf](https://github.com/user-attachments/files/16414923/sanitize_false_text_missing.pdf)
[sanitize_true_destroyed.pdf](https://github.com/user-attachments/files/16414925/sanitize_true_destroyed.pdf)

### PyMuPDF version

1.24.2

### Operating system

Linux

### Python version

3.12

**Comment by JorjMcKie** [comment]
A bug fixed in the meantime. Please upgrade PyMuPDF.

**Comment by elipongr** [comment]
We have another issue:

We use it with `page.clean_contents(true)`, as you know making it false causes the issue above. The result is that the whole PDF content is deleted.

[White_pdf_IN.pdf](https://github.com/user-attachments/files/17128617/White_pdf_IN.pdf)
[White_pdf_OUT.pdf](https://github.com/user-attachments/files/17128618/White_pdf_OUT.pdf)
