### ISSUE TITLE
No aarch64 wheel for pymupdfb 1.24.9

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#3744]
### Description of the bug

https://pypi.org/project/PyMuPDFb/1.24.9/#files there is no wheel for aarch64.

There is one for 1.24.8:
```
PyMuPDFb-1.24.8-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl (15.7 MB)
```

(Apologies if this is just "we know, not ready yet": I'll downgrade my deps in the meantime).

### How to reproduce the bug

Compare:

https://pypi.org/project/PyMuPDFb/1.24.8/#files

https://pypi.org/project/PyMuPDFb/1.24.9/#files

### PyMuPDF version

1.24.9

### Operating system

Linux

### Python version

3.11

**Comment by julian-smith-artifex-com** [comment]
Apologies, it looks like the upload of aarch64 wheels failed halfway through.

I've uploaded again, and i think the files are now present. Could you try again and let us know whether it's working for you now?

**Comment by julian-smith-artifex-com** [comment]
Closing this as no response in 3 weeks, and problem is believed to be fixed.
