### ISSUE TITLE
Add option to don't convert glyph icon to text when use get_svg_image(matrix=fitz.Identity, text_as_path=False)

### ISSUE THREAD

**Issue by markleedu** [pymupdf/PyMuPDF#3745]
Hi, because some icon font can not found on some system, so please add a option to don't convert the glyph icon as text,
example: 
<img width="612" alt="Screen Shot 2024-07-31 at 13 41 51" src="https://github.com/user-attachments/assets/2711838f-0bd6-4a20-83f4-ca555ded6e94">
the check box icon is not found when convert svg to pdf on my app and many app,, because it had convert to:
`<text xml:space="preserve" transform="matrix(1 0 -0 1 0 792)" font-size="12" font-family="Symbol"><tspan y="-144.5" x="135.02">&#xf095;</tspan></text>`
So please add a option to convert glyph icon to path when text_as_path=False

**Comment by JorjMcKie** [comment]
This cannot be done:
We only have the alternatives "every text is path" and "every text is text". If a check box is not written as one of the known Unicodes

![image](https://github.com/user-attachments/assets/10979dce-20fa-43de-aa42-a9617dfb095d)

but as e.g. a vector graphic like a little rectangle, then it cannot be / won't be converted to a Unicode character.
