### ISSUE TITLE
How To Get Rid Of Ligatures?

### ISSUE THREAD

**Issue by MalikRumi** [pymupdf/PyMuPDF#375]
ligatures

    >>> pdf = fitz.open('559bv.pdf')
    >>> with open('559.html', 'a', encoding='utf-8') as f:
    ...     number_of_pages = pdf.pageCount
    ...     for page_number in range(number_of_pages):
    ...         page = pdf.loadPage(page_number)
    ...         page_content = page.getText("html", TEXT_PRESERVE_LIGATURES=0)
    ...         f.write(page_content)
    ... 
    Traceback (most recent call last):
      File "<stdin>", line 5, in <module>
    TypeError: getText() got an unexpected keyword argument 'TEXT_PRESERVE_LIGATURES'
    >>> import fitz
    >>> pdf = fitz.open('559bv.pdf')
    >>> with open('559.html', 'a', encoding='utf-8') as f:
    ...     number_of_pages = pdf.pageCount
    ...     for page_number in range(number_of_pages):
    ...         page = pdf.loadPage(page_number)
    ...         page_content = page.getText("html", PRESERVE_LIGATURES=0)
    ...         f.write(page_content)
    ... 
    Traceback (most recent call last):
      File "<stdin>", line 5, in <module>
    TypeError: getText() got an unexpected keyword argument 'PRESERVE_LIGATURES'

    # https://pymupdf.readthedocs.io/en/latest/app2/#text-extraction-flags

    >>> print(page.getText("html", flags=fitz.TEXT_PRESERVE_LIGATURES))
    This is the default. How do you turn it *OFF*?!

**Comment by JorjMcKie** [comment]
The call pattern is ``Page.getText(opt, flags=None)``.
The flags parameter is a combination of up to four bits named ``TEXT_PRESERVE_LIGATURES``, ``TEXT_PRESERVE_WHITESPACE``, ``TEXT_PRESERVE_IMAGES`` and ``TEXT_INHIBIT_SPACES``.
Of course, each of those names must be prefixed with ``fitz.`` when used.

**Comment by JorjMcKie** [comment]
> print(page.getText("html", flags=fitz.TEXT_PRESERVE_LIGATURES))
This is the default. How do you turn it *OFF*?!

set ``flags = 0 | <a wanted option> | <a wanted option> ...``

**Comment by arderyp** [comment]
what id you don't want to disable all flags? This doesn't make much sense to me.

**Comment by JorjMcKie** [comment]
> what id you don't want to disable all flags? This doesn't make much sense to me.

Not sure who you were addressing with this comment ... but

It may make sense to dissolve ligatures into their components: For instance, some fonts have a separate glyph for "&#xfb01;" and extracting the text with ligatures preserved will deliver **_one_** unicode 0xFB01, instead of two separate ones "f" and "i".
Having ligatures active or not will therefore an impact on text searching and matching.

**Comment by arderyp** [comment]
I understand that but.  But it sounds like the recommendation above is to set flags to 0. Unless I'm misunderstanding, that would disable all flags, of which the ligature preservation flag is only one.  So disabling all flags instead of targeting the ligatures constant specifically seems like it would have unforeseen consequences.

Am I misunderstanding?

**Comment by JorjMcKie** [comment]
> I understand that but. But it sounds like the recommendation above is to set flags to 0. Unless I'm misunderstanding, that would disable all flags, of which the ligature preservation flag is only one. So disabling all flags instead of targeting the ligatures constant specifically seems like it would have unforeseen consequences.
> 
> Am I misunderstanding?

No you are quite right. Unconsidered bit flag setting was certainly not the intended recommendation!

**Comment by arderyp** [comment]
I appreciate the responses.

In any case, no amount of messing with the `flags` value actually fixed the "fi" ligature to a two-character "f" "i".

Maybe the PDF format is wonky.  You can CTRL+F for (without the quotes) "/fles/" here, there is only one entry:

https://www.supremecourt.gov/opinions/18pdf/588us1r61_g31i.pdf

You can see it displays in the browser (and my local PDF viewer) as ".../files/..." but the ligature makes it ".../fles/..."

**Comment by JorjMcKie** [comment]
Looked at that again and tried a handful of other text extractors: they all (including Adobe) extract as "fles" instead of the visible "files".
Also extracted via PyMuPDF character-wise ("rawdict"). The characters appears as "f", "l", "e", "s", not as "&#xfb01;", "l", "e", "s".
So this is not a ligature at all.

**Comment by arderyp** [comment]
So bizarre. If it's not a ligature, I wonder how it is actually displaying as "fi", which is mapped to "f".

**Comment by JorjMcKie** [comment]
> So bizarre. If it's not a ligature, I wonder how it is actually displaying as "fi", which is mapped to "f".
> 
> Thanks for looking into it, btw.

A font can do anything it wants to let the glyph of a Unicode point look like whatever. In this case, the font also contains errors in its backward mapping glyph numbers to Unicode. The page appearance source invokes the glyph numbered 0xAE (=174, `chr(174) =` &#174;). The glyph program stored under that number generates an appearance looking like the ligature "fi", but the back-translation table to Unicode delivers a standard "f" - **_not_** the ligature "&#xfb01;".

**Comment by arderyp** [comment]
I know virtually nothing about fonts, so I very much appreciate you taking the time to look into this and provide such a thoughtful and helpful explanation!

I'm guessing g, based on your info, that's it's safe to conclude that there is no "fix" for my predicament here.  This is just a mistake made by the upstream data supplier and it is what it is.

For what it's worth, it wouldn't be nearly the first time 😅
