### ISSUE TITLE
unexpectedly big rect.height and rect.get_area after version update

### ISSUE THREAD

**Issue by pranctco** [pymupdf/PyMuPDF#3756]
### Description of the bug

After pymupdf version upgrade from 1.23.4 to latest (1.24.9) I found unexpectedly big rect.height and rect.get_area values.

Is there any code fix or configuration to get more or less the same rect.height and rect.get_area values as before upgrade?

## Step 1

Create new venv-11.

Install requirements:

```
python -m pip install pymupdf==1.23.4
python -m pip install pydantic==2.8.2
```

Download attached zip file with 'version_upgrade_height_area_issues.py' script and 'test-doc-2.pdf' file and unzip them to the same folder.

* [version_upgrade_height_area_issues.zip](https://github.com/user-attachments/files/16523213/version_upgrade_height_area_issues.zip)

Run script (from the folder with 2 previously downloaded files):

```
# venv-11
#
python version_upgrade_height_area_issues.py debug-log-1-23-4.txt
```

As a result 'debug-log-1-23-4.txt' file will be created (is also attached).

## Step 2

Create new venv-22

Install requirements:

```
python -m pip install pymupdf==1.24.9
python -m pip install pydantic==2.8.2
```

Run the same script with the same code (from the folder with 2 previously unzipped files):

```
# venv-22
#
python version_upgrade_height_area_issues.py debug-log-1-24-9.txt
```

As a result 'debug-log-1-24-9.txt' file will be created (is also attached).

## Step 3

Compare content of 'debug-log-1-23-4.txt' and 'debug-log-1-24-9.txt' files.

Example with "unexpectedly big rect.height" ("* eq_debug_info() / height <-- False" from 'debug-log-1-24-9.txt' file):

```
word_39 == 'ī'
* eq_debug_info() / height <-- False
  * diff_ratio == 0.1006236117715751
  * (11.160003662109375, 10.13970947265625)
```

unexpectedly big rect.get_area ("* eq_debug_info() / orig intersection <-- False" from 'debug-log-1-24-9.txt' file):

```
word_18 == 'Text'
* eq_debug_info() / height <-- True
  * diff_ratio == 0.0
  * (11.160003662109375, 11.160003662109375)
* eq_debug_info() / orig intersection <-- False
  * diff_ratio == 0.05353058108380629
  * (238.9835702427663, 226.8406580062583)
```

## Step 4

Is there any code fix or configuration to get more or less the same rect.height and rect.get_area values as before upgrade?

### PyMuPDF version

1.24.9

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
Without trying to follow all of your complex code, I did a simple compare based on the following snippet:
```python
import fitz

doc = fitz.open("test-doc-2.pdf")
page = doc[0]
alltext = page.get_text("rawjson")
out = open(f"{fitz.version[0]}.json", "w")
out.write(alltext)
out.close()
```
This script extracts all text down to each character using the "rawdict" / "rawjson" variant.
Running the script for each version delivers **_identical files_** - i.e. identical character / span / line / block rectangles across both versions.
As all of your comparisons are based on this variant, I would argue that your observations are caused by something else.
[compare.zip](https://github.com/user-attachments/files/16531439/compare.zip)

**Comment by pranctco** [comment]
> Running the script for each version delivers identical files - i.e. identical character / span / line / block rectangles across both versions.

Yes, that is true for your script, not mine.

I will try to add more details about my case:

1. I have "original-pdf" file
1. I'm using pymupdf to get all the text, and rectangles coordinates from "original-pdf" file
1. With that information I create new "rendered-pdf" file
1. I'm collecting information about text, and rectangles coordinates from "original-pdf" file
1. Doing the same (as in previous step) for "rendered-pdf" file
1. Now I'm comparing gathered information ("original-pdf" file info VS "rendered-pdf" file info)

For "**pymupdf==1.23.4**" everything works as expected:
* Difference in [Rect.get_area](https://pymupdf.readthedocs.io/en/latest/rect.html#Rect.get_area) is less than my threshold (== 0.05) value
    * 0 occurrences of "eq_debug_info() / orig intersection <-- False" string in "debug-log-1-23-4.txt" file
* Difference in [Rect.height](https://pymupdf.readthedocs.io/en/latest/rect.html#Rect.height) is less than my threshold (also == 0.05) value
    * 0 occurrences of "eq_debug_info() / height <-- False" string in "debug-log-1-23-4.txt" file

Unfortunately, "**pymupdf==1.24.9**" is not working the same way as my previous version:
* 39 occurrences of "eq_debug_info() / orig intersection <-- False" string in "debug-log-1-24-9.txt" file
    * previously it was 0 occurrences
* 3 occurrences of "eq_debug_info() / height <-- False" string in "debug-log-1-24-9.txt" file
    * previously it was 0 occurrences

**Comment by JorjMcKie** [comment]
Well that is a different problem info than originally reported or implied:
* there is no difference in text extraction positions between PyMuPDF versions!

How do you create the "rendered file" then. It seems you are trying to say that the current version creates a different rendered file.
I dont see code that creates that file.

**Comment by JorjMcKie** [comment]
Closed because of an extended time period without response.

**Comment by pranctco** [comment]
> How do you create the "rendered file" then. It seems you are trying to say that the current version creates a different rendered file.

I have modified my script a bit.

Download attached zip (ver22) file with 'version_upgrade_height_area_issues_ver22.py' script and 'test-doc-2.pdf' file and unzip them to the same folder.

* [version_upgrade_height_area_issues_ver22.zip](https://github.com/user-attachments/files/16599029/version_upgrade_height_area_issues_ver22.zip)

**Run new script** (from the folder with 2 previously downloaded files):

```
# venv-11
#
python version_upgrade_height_area_issues_ver22.py rendered-1-23-4.pdf
```

As a result 'rendered-1-23-4.pdf' file will be created (is also attached).

**Run the same new script** with the same code (from the folder with 2 previously unzipped files):

```
# venv-22
#
python version_upgrade_height_area_issues_ver22.py rendered-1-24-9.pdf
```

As a result 'rendered-1-24-9.pdf' file will be created (is also attached).

**Comment by pranctco** [comment]
As you can see the same code executed under different PyMuPDF versions will generate 2 different files.

Differences are in:
* fonts rendering ([Rect.get_area](https://pymupdf.readthedocs.io/en/latest/rect.html#Rect.get_area), [Rect.height](https://pymupdf.readthedocs.io/en/latest/rect.html#Rect.height))
* file size

**Comment by JorjMcKie** [comment]
> As you can see the same code executed under different PyMuPDF versions will generate 2 different files.
> 
> Differences are in:
> 
> * fonts rendering ([Rect.get_area](https://pymupdf.readthedocs.io/en/latest/rect.html#Rect.get_area), [Rect.height](https://pymupdf.readthedocs.io/en/latest/rect.html#Rect.height))
> * file size

You did not debug sufficiently: There are more differences.
The 1.24 file **_always_** uses the built-in fonts Helvetica and Times-Roman (font names "Nimbus..."), whereas the 1.23 version re-uses fonts from the original PDF. Which - from looking somewhat in the depth of your logic - means that the original PDF's fonts are never correctly recognized under v1.24.
So differences in position information (and also file sizes) are inevitable.

I did not check why your logic no longer detects original fonts under 1.24. But this is the root of your problem.

There is one obvious error though: `fitz.Font(fontname=name,...)` only works if name is one of either the built-in fonts ("helv", "tiro", ...) or one of the name codes in pymupdf-fonts (if installed).
Otherwise it will raise an exception.
Specifying both parameters, fontname **_and_** fontbuffer makes no sense at all. Even more, in your case specifying fontbuffer is the **_only_** thing that makes sense.
