### ISSUE TITLE
No Slicing?

### ISSUE THREAD

**Issue by MalikRumi** [pymupdf/PyMuPDF#376]
Slicing
How do you do more than one page at a time? Only with 'for page in range'?
No slicing, like doc[45:56]?

**Comment by JorjMcKie** [comment]
Accessing pages via the slicing syntax is not supported.

**Comment by JorjMcKie** [comment]
I have thought about this a few times and never saw a suitable way to do this.

* what meaning could an expression like ``doc[n:m]`` have?
    - a new document with pages ``doc[n]`` thru ``doc[m-1]``?
    - or just syntax sugar for constructs like ``for page in doc[n:m:k]``?

 * what about something like ``doc1[n:m] = doc2``?

**Comment by JorjMcKie** [comment]
After giving some thought one more time, I decided to not invest this effort.
After all there are efficient ways in Python to implement this by yourself, e.g.

```python

from itertools import islice
...
for page islice(doc, start, stop, step):
    # do something with the page
```

**Comment by JorjMcKie** [comment]
In response to your request, and after some deeper analysis of the previously mentioned solution ``itertools.islice``, I have changed my mind again:

The next version of PyMuPDF will have a new ``Document`` method ``Document.range`` looking very similar: ``for page in doc.range(start, stop, step)``.

This is a generator iterator with properties exceeding those of ``islice``:
* full support of Python's built-in ``range()``
* parameters may be positive or negative allowing forward and backward iteration
* if not provided, ``step`` will automatically be correctly chosen to match the values of ``start`` and ``stop``.

Usage examples:
* ``"for page in doc.range()"`` is the same as ``"for page in doc"``.
* ``"for page in doc.range(4, 9, 2)"`` delivers pages 4, 6, 8.
* ``"doc.range(-2)"`` delivers the last two pages.
* ``"for page in doc.range(-1, -1)"`` is the same as ``"for page in reversed(doc)"``.
* ``"for page in doc.range(-1, -2)"`` delivers pages in reversed sequence starting and ending with the last document page.
