### ISSUE TITLE
get_page_images docs and behaviour do not align regarding values returned

### ISSUE THREAD

**Issue by Laubeee** [pymupdf/PyMuPDF#3760]
### Description of the bug

the [get_page_images docs](https://pymupdf.readthedocs.io/en/latest/document.html#Document.get_page_images) state that each image has 10 values, but only 9 are present in 1.24.9

```
>>> page.get_images()
[(6, 0, 7014, 4959, 1, 'DeviceGray', '', 'Im0', 'CCITTFaxDecode'), (23, 0, 7013, 4959, 1, '', '', 'Im0', 'CCITTFaxDecode')]
```

### How to reproduce the bug

load a PDF with images, run `pdf[0].get_page_images()`

### PyMuPDF version

1.24.9

### Operating system

Windows

### Python version

3.8

**Comment by JorjMcKie** [comment]
You can have 10 items if you specify `True` as additional parameter. This is also mentioned in the documentation, https://pymupdf.readthedocs.io/en/latest/document.html#Document.get_page_images
