### ISSUE TITLE
Hyphens

### ISSUE THREAD

**Issue by MalikRumi** [pymupdf/PyMuPDF#377]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.

**Describe the solution you'd like**
When converting a pdf to html, a way to make the css setting 'white-space:normal;' instead of the automatic 'white-space:pre;'. Or some other way to make it break only on whitespace and not hyphenate words? The C code? I found this on github, but I know almost nothing about C (or is this C++?):
    https://github.com/ArtifexSoftware/mupdf/blob/0b61eeb8d94b747711a81010d492fcc9f51fcb94/source/html/html-parse.c
    https://github.com/ArtifexSoftware/mupdf/blob/13d1c2ad494216d3e7ff8545985cd8ee7afdab03/source/pdf/pdf-font.c
    https://github.com/ArtifexSoftware/mupdf/blob/3af1bd68abfcb2c8d88c090e5269650f6f09e422/scripts/texglyphlist.txt
    https://github.com/muennich/mupdf/blob/master/source/pdf/pdf-font.c

**Describe alternatives you've considered**
Are there several options for how your request could be met?
I actually have a workaround. I was just hoping this could be done up front. 

**Additional context**
This is a sample of the html code that is being generated:
p style="position:absolute;white-space:pre;margin:0;padding:0;top:401pt;left:169pt" span style="font-family:CenturyExpanded,serif;font-size:8.960847pt;color:#221f1f"

**Comment by JorjMcKie** [comment]
see #378
