### ISSUE TITLE
pymupdf4llm is failing to recognize text when using multithreading

### ISSUE THREAD

**Issue by subho-das** [pymupdf/PyMuPDF#3771]
### Description of the bug

Python version : 3.12

Problem desciption:
The below two code fragment processes the same PDF file in a multithreaded fashion (with ThreadPoolExecutor(max_workers=10) as pool:)

Code 1 : using only pymupdf 

```
def extract_text_using_pymupdf(self,pdf_doc:pymupdf.Document):
        """
        Process a PDF, extracting text only from text-containing pages.
        
        :param pdf_file_path: Path to the PDF file.
        :return: Dictionary with page number as key and extracted text as value.
        """
        extracted_text = {}
        
        for page_num in range(len(pdf_doc)):
            page = pdf_doc[page_num]
            
            # Check if the page contains text
            if self.is_text_page(page):
                text = page.get_text("text")
                extracted_text[page_num + 1] = text  # Store with 1-based page number
            else:
                logger.warning(f"Page {page_num + 1} is a non-text page and will be skipped.")
        
        return extracted_text`
```
**The above code works and filter the not text pages**

Code 2: Using pymupdf4llm

```
def extract_text_using_pymupdf4llm(self,pdf_doc:pymupdf.Document):
        """
        Process a PDF, extracting text only from text-containing pages.

        :param pdf_file_path: Path to the PDF file.
        :return: Dictionary with page number as key and extracted text as value.
        """
        extracted_text = {}
        try:
            text_from_pdf=pymupdf4llm.to_markdown(pdf_doc, write_images=True, page_chunks=True)
        except ValueError as e:
            logger.error(f"An error occurred: {e}", exc_info=True)
            raise
        for i,page in enumerate(text_from_pdf):
            text=page.get("text",'')
            extracted_text[i + 1] = text  # Store with 1-based page number

        return extracted_text`
```
**The code fragment 2 does not work and fail  with below error **

Error:
```
/lib/python3.12/site-packages/pymupdf/utils.py", line 547, in get_textbox
    raise ValueError("not a textpage of this page")
ValueError: not a textpage of this page
```

Reference : [pymupdf does not support multithrading](https://github.com/pymupdf/PyMuPDF/issues/3241)

I understand pymupdf4llm is another wrapper on top of the pymupdf library. Also it processes the entire pdf as a pymupdf.Document not individual pages (as per the API doc)

Can you please recommend how I can use the pymupdf4llm?

FYI the same pymupdf4llm code works when I do not use multithreading. 

### How to reproduce the bug

1. Use any pdf which contain both image, text and tables
2. Use the above code to process the pdfs in a single threaded and then multithreaded way
3. pymupdf4llm throws the error in the description

### PyMuPDF version

1.24.9

### Operating system

MacOS

### Python version

3.12

**Comment by JorjMcKie** [comment]
This is not a bug!
The documentation clearly states that PyMuPDF (and thus of course neither PyMuPDF4LLM) cannot be used in a multithreading environment.
