### ISSUE TITLE
Excessive html/css generated by html option

### ISSUE THREAD

**Issue by MalikRumi** [pymupdf/PyMuPDF#378]
**Is your feature request related to a problem? Please describe.**
The code replaces newlines with p tags. This means that every 'line' is now also its own paragraph, each with nearly identical code:

`p style="position:absolute;white-space:normal;margin:0;padding:0;top:208pt;left:160pt" span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" certiorari 
 span span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span  span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" to span span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span  span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" the span  span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span  span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" united  span  span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span  span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" states span span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" court  span  span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span  span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" of  span  span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span  span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" appeals span  pan style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span  span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" for  span  span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span p
p style="position:absolute;white-space:normal;margin:0;padding:0;top:219pt;left:261pt"  span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" the span  span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" sixth  span  span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span  span style="font-family:CenturyExpandedSC,serif;font-size:10.952146pt;color:#221f1f" circuit  span  span style="font-family:Times,serif;font-size:10.952146pt;color:#221f1f"  span  p`

**Describe the solution you'd like**
I can do the regular text wrangling, it's just that if I could get better control of this up front, it would save me a lot of work later. 

**Describe alternatives you've considered**
Are there several options for how your request could be met?

**Additional context**

**Comment by JorjMcKie** [comment]
The syntax is generated by the underlying library MuPDF and I have no influence on how this is done.
Please submit a feature request to them if you think it is worthwhile: https://bugs.ghostscript.com/enter_bug.cgi
