### ISSUE TITLE
`find_tables()` is not detecting the only table on the page

### ISSUE THREAD

**Issue by vedantkingh** [pymupdf/PyMuPDF#3805]
### Description of the bug

Code:
```
def extract_report_from_pages( pages):
  doc = pymupdf.open(pdf_file_path)
  page = doc[pages[0]]
  tables = page.find_tables( strategy="lines_strict")
  for i,tab in enumerate(tables):
    print(tab.to_pandas())
  Return tables
 ```
 Output:
```
  for the year ended March 31, 2024 CIN : L93030DL2010PLC198141          Col1
0                                                                (INR crores)
1  Particulars Note For the year ended For the ye...                     None
```

find_tables() is not working very well, can anyone help me, please? In this case, it is failing terribly. I also simply tried feeding the page image to the Google Gemini API and asking it to give me a json response for the table, but it is not accurate enough, and accuracy is paramount in my case.

![Screenshot 2024-08-25 134803](https://github.com/user-attachments/assets/d388bbbe-3df1-4a55-9291-03616b37b9a9)

Note: The image I sent below is not low quality at all, it is super clear and high quality, me screenshotting it and sending it might have compressed it.

[Here is the entire PDF file](https://www.bseindia.com/xml-data/corpfiling/AttachHis/629bfe24-4e55-4b14-957e-8c8bc5828ff0.pdf)

Although I am sending only the page which contained the table, in this case, page number 170 of the PDF file.

Also, the method I seek should be generalized for all cases, such as the images attached below, and not be particularly made for a single corner case.

![Screenshot 2024-08-25 135608](https://github.com/user-attachments/assets/416cd91f-4e7e-4301-ab48-6c09a26573a6) 
![Screenshot 2024-08-25 135644](https://github.com/user-attachments/assets/eb726774-fa24-4372-be53-708d39d9940b)
![Screenshot 2024-08-25 135724](https://github.com/user-attachments/assets/94f15ef0-0cca-4631-a546-24dd0e60e98c)

Thank you for your help.

### How to reproduce the bug

```
def extract_report_from_pages( pages):
  doc = pymupdf.open(pdf_file_path)
  page = doc[170]
  tables = page.find_tables( strategy="lines_strict")
  for i,tab in enumerate(tables):
    print(tab.to_pandas())
  Return tables
 ```

Use this function on the pdf I just attached.

### PyMuPDF version

1.24.9

### Operating system

Windows

### Python version

3.12

**Comment by JorjMcKie** [comment]
Thank you for submitting this. However, as stated in the documentation, identifying tables is a topic for which there exists no silver bullet - anywhere in the market.

While we always are seeking ways to improve what we have, we also now that a perfect solution will not be reached whatsoever.

So your request "general for all cases" **_cannot_** be fulfilled. You will continue to depend on your wits to find a solution in difficult cases.

**Comment by vedantkingh** [comment]
Thank you @JorjMcKie for your reply and clarification, however, when I said "general for all cases" I did not mean just anything, The structure of the table would be the same, but the headers might be different so it should not be extremely specialized.
And I agree that no perfect solution exists in my case. 
Could you please guide me in some direction how I can improve it? maybe using pymupdf for most tasks and some other library for table scanning?
