### ISSUE TITLE
TextPage.extractDICT|extractRAWDICT failed to exec after upgrading from 1.16.2 to 1.16.3

### ISSUE THREAD

**Issue by imckl** [pymupdf/PyMuPDF#381]
## Describe the bug (mandatory)
TextPage.extractDICT|RAWDICT failed to executed in version 1.16.3.
The file also tested in 1.16.2, and it works as normal.
It seems that the bug is produced in version 1.16.3

## To Reproduce (mandatory)
```Python
import fitz

path = r'D:\Desktop\sample2.pdf'
doc = fitz.Document(path)
page0 = doc.loadPage(0)
dl = page0.getDisplayList()
tp = dl.getTextPage()
tp.extractDICT()
```
which output:
```
Process finished with exit code -1073741819 (0xC0000005)
```
Test file: https://github.com/imckl/tmp_pymupdf/raw/master/sample2.pdf

## Expected behavior (optional)
Extract as normal.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/20377660/66542847-4480e400-eb66-11e9-9404-530923ae6977.png)

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
Windows 10 LTSC  2016, Version 1607
 - Python version, bitness
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
 - PyMuPDF version, installation method (**wheel** or **generated** from source).
('1.16.3', '1.16.0', '20191001090106'), installed via pipenv

**Comment by JorjMcKie** [comment]
Thanks for reporting this.
Cause: the PDF contains fonts with non-ASCII names, and I forgot to catch this case in v1.16.3.
I have created a patch and will publish it probably today (VE time).

**Comment by JorjMcKie** [comment]
Please close this issue once you can confirm it is fixed by the new version (or drop me a note).

**Comment by imckl** [comment]
#### This issue
Tested on 1.16.4, up to 14k pdf files without problem, i'm sure 1.16.4 fix this bug, thanks!
#### Another issue
- Desc
there still one file aborts python with same output, it's a really rare case (only this file among 14k pdf files) and I assume this is another bug/issue.
I've tested in 1.16.2/1.16.4.
- Code:
```Python
    import fitz
    print(fitz.version)
    doc = fitz.Document(r'D:\Desktop\abortion\sampe-201901112142.pdf')
    for page in doc:
        dl: fitz.DisplayList = page.getDisplayList()
        text_page: fitz.TextPage = dl.getTextPage(fitz.TEXT_PRESERVE_LIGATURES | fitz.TEXT_INHIBIT_SPACES)
        text_page.extractText()
        text_page.extractRAWDICT()
```
- Output:
('1.16.4', '1.16.0', '20191010100000')
Process finished with exit code -1073741819 (0xC0000005)
- Attachment:
https://github.com/imckl/tmp_pymupdf/raw/master/sampe-201901112142.pdf
- Screenshot:
![image](https://user-images.githubusercontent.com/20377660/66655840-6914b300-ec6f-11e9-96e4-c50c6adae62b.png)
- Remark:
I will create new issue for this if necessary :)

**Comment by JorjMcKie** [comment]
Good that one issue was resolved.

The other problem indeed is a new issue - would you mind opening one?
What I found out so far:
* Problem is **not** related to DICT or RAWDICT extraction methods. Instead, the creation of the page's DisplayList already brings down the interpreter.
* The PDF does have structural problems, here are some messages from the ``mutool`` utility, when extracting text with it:

```
mutool draw -o sample3.txt sample3.pdf 1
warning: non-embedded font using identity encoding: ╦╬╠Õ
warning: ... repeated 17 times...
warning: non-embedded font using identity encoding: Arial
page sample3.pdf 1
```

Certainly the crash shouldn't happen nonetheless.
I am also amazed, why PyMuPDF brings down the interpreter by using ``page.getText("text")``, whereas the (presumably) same code in MuPDF ends normally with just those warnings ...

Investigating this ...

**Comment by imckl** [comment]
Thanks for your positive action!

It's an edge case though, bring down the interpreter is not very nice to the automatic procedure :S
BTW, it displays slightly different between Chrome Browser and Adobe Acrobat Reader DC, I assume it's the font issue (Chinese character doesn't display in Chrome but Adobe):
- Chrome:
![image](https://user-images.githubusercontent.com/20377660/66690337-04367880-ecc2-11e9-882a-6f4cbd8d9b6a.png)
- Adobe:
![image](https://user-images.githubusercontent.com/20377660/66690343-0993c300-ecc2-11e9-8359-cec0f5dd20a1.png)

I'll open new issue for that, with more detailed test info & structural template :)

**Comment by JorjMcKie** [comment]
Concerning that new problem:
I am using a handful of different PDF viewers, and practically none looks equal to any of the others ... Even my Adobe version shows a different picture than yours (and complains a lot on opening the file).

I have been looking for ways to intercept the crash. My current findings point into the direction of MuPDF's warnings:
All fonts are **_not embedded_** in the PDF, but use encoding ``Identity-H``, which is illegal.
I have successfully tested a version which checks this condition and - if detected - reacts with an exception, when trying to extract text from or render the page.
If you are interested in this version, then please dropt me a note, so I can upload it.

**Comment by JorjMcKie** [comment]
Forget my previous post: I found the true cause!

I did not correctly build unicode strings for fontnames containing illegal characters as is the case in your sample PDF. The crash occurred when I tried to store the above mentioned warning messages in my `mupdf_warnings` buffer. The amazing aspect was, that the same code compiled for Python 2.7 worked ...

I will publish another hot fix to PyPI tomorrow.

**Comment by JorjMcKie** [comment]
New version 1.16.5 uploaded to PyPI.

**Comment by JorjMcKie** [comment]
Hi @imckl - to foster your appreciation of PyMuPDF, I am sending you a **_demo_** script, which is able to replace fonts in a PDF.
I converted your problem sample PDF to one which uses "legal" fonts. Looks better than the original ... ;-)
[replace-fonts.zip](https://github.com/pymupdf/PyMuPDF/files/3724607/replace-fonts.zip)
Maybe you need it some day.

**Comment by imckl** [comment]
Thanks McKie.
Sry I didn't reply&recreate new issue in time cuz I'm busy for a couple days.
I'll keep using pymupdf and give any useful feedback once I have found and have time :)

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________
