### ISSUE TITLE
Add text alignment information to text extraction API

### ISSUE THREAD

**Issue by LamichhaneBibek** [pymupdf/PyMuPDF#3818]
**Is your feature request related to a problem? Please describe.**
Currently, the text extraction API in pymupdf does not provide information about the text alignment within a PDF. This information can be useful for preserving the original layout and formatting of the content when creating new PDFs from the extracted data or when working with the extracted text in other applications.

**Describe the solution you'd like**
I propose adding text alignment information to the text extraction API, using the existing TEXT_ALIGN_* constants defined in the source code. This could be achieved by adding an align field to the span objects returned by get_text("dict").

**Comment by JorjMcKie** [comment]
This is a no-can-do, sorry.
This information is not stored in the PDF, so it consequently cannot be extracted.
