### ISSUE TITLE
class improves namedDest handling

### ISSUE THREAD

**Issue by zhu1205** [pymupdf/PyMuPDF#3820]
**Is your feature request related to a problem? Please describe.**
I have a pdf which contains bookmarks.
Each bookmark has a nameddest.
After call document.get_toc() I get a list of bookmarks, but there's no page in each bookmark under dest, so I step into linkDest class to find the reason.

class linkDest:
    def __init__(self, obj, rlink, document=None):
        ...
                        if document and m:
                            named = m.group(1)
                            self.named = document.resolve_names().get(named)
                            if self.named is None:
                                # document.resolve_names() does not contain an
                                # entry for `named` so use an empty dict.
                                self.named = dict()
                            self.named['nameddest'] = named
                        else:
                            self.named = uri_to_dict(self.uri[1:])
                    ...

I found the problem at line "self.named = document.resolve_names().get(named)" for the named is a escaped str,
![named](https://github.com/user-attachments/assets/b466a26b-0201-4675-82d8-1b0e2c6cd081)

 while each key in dict returned by document.resolve_names() is a unescaped str, 
![esolve_name](https://github.com/user-attachments/assets/6068f306-0689-430e-9f45-1502e269e30a)

so self.named will always be None.    

**Describe the solution you'd like**
To solve this issue, named should be unescaped before "self.named = document.resolve_names().get(named)"

from pymupdf.mupdf import ll_fz_decode_uri_component

named = ll_fz_decode_uri_component(named)
self.named = document.resolve_names().get(named)

**Describe alternatives you've considered**
Are there several options for how your request could be met?

**Additional context**
The pdf:
[21.0_TREATMENT OF ADOLESCENTS AND CHILDREN WITH CH.pdf](https://github.com/user-attachments/files/16797699/21.0_TREATMENT.OF.ADOLESCENTS.AND.CHILDREN.WITH.CH.pdf)

**Comment by JorjMcKie** [comment]
We have developed a fix for this problem. It will be rolled out with one of the next PyMuPDF versions.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.10.
