### ISSUE TITLE
Extract Model Tree Info

### ISSUE THREAD

**Issue by Celtics33** [pymupdf/PyMuPDF#3822]
Is there a way with Pymudf to extract model tree info or verify that it exists? I have done some research and have not found anything in the documentation.

**Comment by JorjMcKie** [comment]
No, this is currently not supported in any way.
You can however freely access the PDF catalog via its xref number and further inspect its content using low-level API call.

**Comment by Celtics33** [comment]
Anywhere in the documentation to get started? I am not sure where to look to find the model tree's xref position.

**Comment by JorjMcKie** [comment]
I don't know either where to find a thing called "model tree".
You could start by looking at the PDF's catalog:
```python
cat_xref = doc.pdf_catalog()  # xref of catalog

# print the catalog object
print(doc.xref_object(cat_xref))

# produces something like this
<<
  /Type /Catalog
  /Pages 2 0 R
  /StructTreeRoot 44 0 R
  /MarkInfo <<
    /Marked true
  >>
  /Metadata 841 0 R
  /ViewerPreferences 842 0 R
>>

# other object identified by xref can be shown also. E.g. "44 0 R"
print(doc.xref_object(44))
<<
  /Type /StructTreeRoot
  /RoleMap 45 0 R
  /ParentTree 46 0 R
  /K [ 48 0 R ]
  /ParentTreeNextKey 5
>>
```
This may help finding what you are looking for.

**Comment by Celtics33** [comment]
Excellent thank you, it did help a lot! Is there a way to extract color information, or its hiding somewhere in xref?

**Comment by JorjMcKie** [comment]
> Excellent thank you, it did help a lot! Is there a way to extract color information, or its hiding somewhere in xref?

Glad to hear that. If you want, attach the PDF and I'll have a look.

**Comment by Celtics33** [comment]
This is what I am looking to see if pymupdf or another python library supports this (this is a java based library) : 
[https://stackoverflow.com/questions/10456486/does-pdfbox-support-spot-colors-and-separations](url)
