### ISSUE TITLE
page.searchFor gives separate Rects for inline match

### ISSUE THREAD

**Issue by wave-DmP** [pymupdf/PyMuPDF#383]
When using page.searchFor, the output results in separate rectangles, even for one-liner hits it detects separate lines.

It would be good if the output would group single hit rectangles, then it would be possible to detect one-liner lists of rectangles and combine them, or have that as an option based on a pixel threshold (for example: if both top and bottom coordinates from one token to the other vary by +-2 pixels in the same direction), i.e. list of lists output, or dict:list

Unfortunately unable to share the file.

## configuration
 - Windows 10
 - Python 3.6.7
 - PyMuPDF 1.16.5

Example of split rects that are part of the same match:
Rect(330.2518005371094, **242.53500366210938,** 354.29315185546875, **256.0002136230469**), 
Rect(356.8882141113281, **242.53500366210938**, 391.5311584472656, **256.0002136230469**), 
Rect(393.981201171875, **242.53500366210938**, 414.8934326171875, **256.0002136230469**)

**Comment by JorjMcKie** [comment]
Questions:
* Is this a new phenomenon in this version or did it happen earlier, too?
* Does this always happen (which I do not believe), or what are any specifics when that happens?

Your example rectangles have the same y-coordinates, so are on the **same line**, which means they are **valid** separate hits of the same search string, or are they not?

However, if your intention is an **_enhancement_** request like:

"Whenever a hit is located an more than one line, group the respective rects/quads in some way."

... then we should re-classify the issue to some non-bug category.

More than one rect for one search string should only happen, if both of the following conditions are true:
* The search string contains at least one space, and the max number of separate rects for a search string is ``len(search.split()) - 1``.
* (at least) two consecutive rects in the returned list do **not** contain the full search string - a condition that can be checked via extracting the text from the rectangle.

The only other explanation I can think of, is a peculiarity of MuPDF's lookup mechanism:
The decision for logically subdividing a text block in separate lines and spans is **not** (only) based on the relative height (y-coordinate) of the text fragments, but also on some other, rather technical criteria.

**Comment by JorjMcKie** [comment]
Given you cannot share an example PDF, could you submit an image of the respective page part with the rectangles marked?

**Comment by JorjMcKie** [comment]
I tried several things to recreate the observation you made - without any luck. As far as I can see, the function works as designed.
So please find a way to provide me with data which exhibit the malfunction.

**Comment by JorjMcKie** [comment]
Closing this issue for now - please do re-open it once you have data allowing an investigation.
