### ISSUE TITLE
Missing Wheel Support for Python 3.8

### ISSUE THREAD

**Issue by bschollnick** [pymupdf/PyMuPDF#384]
I am forcibly upgrading to Catalina to try to resolve an issue with my computer...  So I am running MOSX Catalina v10.15...

Using Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
[Clang 6.0 (clang-600.0.57)] on darwin.

And I am still seeing the same issue as with https://github.com/pymupdf/PyMuPDF/issues/372

I do not see any instructions for MuPDF for installing under MOSX, presumably the Linux instructions might work...  

There have been some dependency issues, but everything else has installed fine...

**Comment by JorjMcKie** [comment]
Unfortunately, I do not own a Mac myself. All I can offer is the YAML file used to trigger PyMuPDF wheel generation on Travis CI:
[.travis.yml.zip](https://github.com/pymupdf/PyMuPDF/files/3747239/default.travis.yml.zip)

And the log file of one of the last builds - may be it helps:
https://travis-ci.org/JorjMcKie/py-mupdf/jobs/597547122

**Comment by bschollnick** [comment]
Am i missing something?  I’m not seeing an error?


------------------------------------------------------------------

**Comment by JorjMcKie** [comment]
Hm? I guess I don't understand.
I am using Travis CI to build the non-Windows wheels. The problem currently is that their service is not yet upgraded to the current Python 3.8.
So I was just hoping you might get some clue from seeing what happens, when they generate PyMuPDF on their system ...

**Comment by JorjMcKie** [comment]
I have looked at the https://github.com/joerick/cibuildwheel/ repo, which is actually the critical part for Python 3.8 support.
They are underway and it seems a matter of days until they come up with supporting the new Python.

**Comment by bschollnick** [comment]
That would be great.  Looking forward to have that resolved....

**Comment by FloWi** [comment]
Hi @JorjMcKie!

Just stumbled upon this issue. Found out that cibuildwheel now supports python 3.8. :) Would you mind triggering a build for 3.8?

**Comment by FloWi** [comment]
Hi @JorjMcKie!

Just stumbled upon this issue. Found out that cibuildwheel now supports python 3.8. :) Would you mind triggering a build for 3.8?

**Comment by JorjMcKie** [comment]
No, I don't mind 😊 - I've seen it too today. ``cibuildwheel`` is not yet on PyPI, so I need to adjust the yaml to pull from GitHub

**Comment by JorjMcKie** [comment]
Señores - there now exist Python 3.8 wheels [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux) and [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/osx) for Linux and OSX.

I will upload them to PyPI the other day, but I thought you might be interested before this.

**Comment by JorjMcKie** [comment]
Interesting to know, that the wheel generating package ``cibuildwheel`` no longer supports Python 3.4 ... which I think is more than adequate.

**Comment by JorjMcKie** [comment]
Upload to PyPI happened just now.

**Comment by bschollnick** [comment]
Thank you!
