### ISSUE TITLE
Documentation Request: Page on docs explaining PDF errors and warnings

### ISSUE THREAD

**Issue by cmyers009** [pymupdf/PyMuPDF#3866]
**Is your feature request related to a problem? Please describe.**

Some PDF errors are critical to the PDF and can cause issues with the PDF if ignored.
Some PDF errors are not that big of a deal.

It is not immediately clear for some of the PDF errors what the potential impacts of the PDF error is on the PDF.  There is also no documentation for the 'severity' of the error.

**Describe the solution you'd like**
I would like a page on the docs explaining the mupdf errors with the following:
1. A description of why the error occurred (For example, 'This error occurs on pdfs that have X constructed incorrectly')
2. The potential impacts of the error (For example, 'It is not recommended to do X pdf operation if this error occurs because it can cause Y')
3. A 'severity' score - (1-10 or low, medium, high, critical)

**Comment by JorjMcKie** [comment]
This is a request that should be addressed to MuPDF. Please resubmit to either MuPDF's issues system https://bugs.ghostscript.com/enter_bug.cgi or talk to the people on MuPDF's [Discord](https://discord.gg/qAT6kGFc) channel.
