### ISSUE TITLE
getimagebox() return negative coordinations 

### ISSUE THREAD

**Issue by apache135** [pymupdf/PyMuPDF#387]
Use page.bound() return rect object [0,0,512,789]

However when I try to get images box, it returns rect which contains negative values, [4352,-6664, 4789,-6427]  which out of the page range. Via pdf plumber,found that the coordinations was values referred just now multiply 0.1 .

**Comment by JorjMcKie** [comment]
Please send me the PDF in question - just the page in question if possible, to save internet download times. If PDF is large, please extract the page into a new PDF via a code snippet like this one:

```python
src = fitz.open("input.pdf")
doc = fitz.open()  # output PDF
doc.insertPDF(src, from_page=n, to_page=n)
doc.save("output.pdf")
```

**Comment by apache135** [comment]
Sorry for the working network restrictions. I can’t upload anything about it. If possible, could you offer some tips which I can check?

**Comment by JorjMcKie** [comment]
You mean you cannot share even a part of the PDF? Too bad.

I presume the bbox of that image is correct in output of method ``page.getText("dict")``? You could apply "heuristic" methods (i.e. human judgement 😉) and compare the width/height values from there with the ones found in ``page.getImageList`` to determine which xref the bbox belongs to ...

Again a few words on how ``page.getImageBbox`` works:

> I am parsing the page's ``/Contents`` source for strings like ``a b c d e f cm``. The last ``cm`` is a function ("concatenate matrix") and the ``a`` through ``f`` are the matrix coordinates.
Parsing forward, I am multiplying all such matrices until I find the command ``/Im0 Do``, where ``Im0`` is the name of the image in question (``item[7]`` if ``item in page.getImageList()``).
From the resulting matrix I then calculate the image's bbox.

This approach works for many / most situations, but not always: there are just too many ways, how I can be tricked out - to many to name them all here (I am probably not even aware of all ways how my algorithm can fail).
But if the page geometry is set in certain special ways, I do not detect this and my matrix calculation returns wrong values.
So it would be great to have more examples to learn from and improve the algorithm ... 😟

**Comment by apache135** [comment]
yes i got the right coordinations about the image. However there are 3 images which are in same size . I will try to find another way to get the right coordinations.  So sorry I can’t share the file to help this issue.

**Comment by JorjMcKie** [comment]
One more idea:
To match the image cross references in ``page.getImageList()`` with the (correct) bboxes contained in ``page.getText("dict")`` you can also use this "brute-force" approach:

```python
image_blocks = [b for b in page.getText("dict")["blocks"] if b["type"] == 1]  # image blocks
images = page.getImageList()  # list of images
>>> for item in images:
	img = doc.extractImage(item[0])
	bbox = ()
	for b in image_blocks:
		if img["image"] == b["image"]:  # compare the image binary streams
			bbox = b["bbox"]
			break
	print("image '%s' at xref %i has bbox %s" % (item[7], item[0], str(bbox)))
```

**Comment by JorjMcKie** [comment]
The more I think about the approach in my last post, the better I like it.
What I am seriously considering now is to make a utility function which ...
1. Starts with an image block (which is a dictionary) of ``page.getText("dict")`` or ``page.getText("rawdict")`` as parameter
2. Searches for a matching entry in ``page.getImageList()``
3. If found, extends the dictionary with new key/value pairs from the found entry like xref, smask, etc.

This way we have the best of both attack lines:
* the bbox is always calculated correctly by MuPDF's C code
* there is no more need to duplicate that code via Python and, at best, deliver inferior results
* the image block dictionary is extended by all the PDF-specific information (xref, smask, reference name, etc.)
* we will always talk about images which actually are **displayed** by the page - as opposed to ``page.getImageList()``, which may contain "dead entries": those are typically difficult to explain to someone new to PDF.

**Comment by apache135** [comment]
I am confused. Page.getimagebox() seems to be derived from page.gettext().
Does Page.gettext(‘dict’) return all images info which don’t contain dead entries?

**Comment by JorjMcKie** [comment]
No, ``page.getImageBbox`` only uses ``page.getImageList``. This is the reason why "dead" entries may happen. It also only works for PDF documents.

In contrast to this, ``page.getText`` is a text extraction method, which nevertheless is able to extract images on the page as well (for some of its output options). It works for all supported document types, not just PDFs. For this reason, it cannot return PDF specific information (like xref).
Because the underlying logic (provided by MuPDF base library) parses and interprets the page commands, all information is guarantied to be valid and update to date - no dead entries.
The returne information basically is a list of items called "blocks" of two types: text blocks and image blocks.
Image blocks are very similar to what ``doc.extractImage`` returns for a given image xref in the PDF case.

My suggestion from previous post is, to provide a utility function, which connects these two separate sets of information for a PDF page.
The goal is to provide a **complete** image dictionary for an image on a PDF page, with BBOX, XREF, SMASK and everything else.

**Comment by apache135** [comment]
thanks for the detailed explanation and such a great lib which offered me a solution for my issue. I will close this ticket .
