### ISSUE TITLE
Error when trying to use pyMuPDF on FreeBSD

### ISSUE THREAD

**Issue by rainerduffner** [pymupdf/PyMuPDF#388]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I have built mupdf-1.16.0,1 on FreeBSD, using the port and poudriere.
It's built on FreeBSD 11.3-RELEASE-p3 amd64

When I build pyMuPDF and try to use it:

`

(mu) (python-test <mu>) 0 # python
Python 2.7.16 (default, Oct 23 2019, 15:53:49)
[GCC 4.2.1 Compatible FreeBSD Clang 8.0.0 (tags/RELEASE_800/final 356365)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/mu/lib/python2.7/site-packages/fitz/__init__.py", line 3, in <module>
    from fitz.fitz import *
  File "/root/mu/lib/python2.7/site-packages/fitz/fitz.py", line 18, in <module>
    from . import _fitz
ImportError: /usr/local/lib/libmupdf.so.1.16.0: Undefined symbol "FT_Get_Advance"

`

## To Reproduce (mandatory)
see above

## Expected behavior (optional)
What does that error mean? How can fix it?

## Your configuration (mandatory)
```
mupdf-1.16.0,1
Name           : mupdf
Version        : 1.16.0,1
Installed on   : Mon Oct 28 10:30:12 2019 CET
Origin         : graphics/mupdf
Architecture   : FreeBSD:11:amd64
Prefix         : /usr/local
Categories     : graphics
Licenses       : AGPLv3
Maintainer     : uzsolt@uzsolt.hu
WWW            : https://www.mupdf.com/
Comment        : Lightweight PDF viewer and toolkit
Options        :
	DOCS           : on
	JS             : off
	SCROLL         : on
Shared Libs required:
	libjbig2dec.so.0
	libGL.so.1
	libXext.so.6
	libglut.so.3
	libharfbuzz.so.0
	libjpeg.so.8
	libopenjp2.so.7
	libfreetype.so.6
	libX11.so.6
Shared Libs provided:
	libmupdf.so.1.16.0
	libmupdf-third.so.1.16.0
Annotations    :
	FreeBSD_version: 1103000
	cpe            : cpe:2.3:a:artifex:mupdf:1.16.0:::::freebsd11:x64
	repo_type      : binary
	repository     : EveryWare
Flat size      : 46.5MiB
Description    :
MuPDF is a lightweight PDF viewer and toolkit written in portable C.

The renderer in MuPDF is tailored for high quality anti-aliased graphics. It
renders text with metrics and spacing accurate to within fractions of a
pixel for the highest fidelity in reproducing the look of a printed page on
screen.

MuPDF has a small footprint. A binary that includes the standard Roman fonts
is only one megabyte. A build with full CJK support (including an Asian
font) is approximately five megabytes.

MuPDF has support for all non-interactive PDF 1.7 features, and the toolkit
provides a simple API for accessing the internal structures of the PDF
document. Example code for navigating interactive links and bookmarks,
encrypting PDF files, extracting fonts, images, and searchable text, and
rendering pages to image files is provided.

WWW: https://www.mupdf.com/
```

**Comment by JorjMcKie** [comment]
This error indicates that PyMuPDF has not been built correctly. It probably goes back to wrong / incomplete references of the libraries of your MuPDF installation (did you check those are usable, e.g. by testing the ``mutool`` cli utility?).

Unfortunately, there exist variations per platform as to which libs must be included. Please look at the comments indicating some differences for especially the correct thirdparty library references.

Your undefined symbol ``FT_Get_Advance`` is one of the freetype library (needed for font handling), so I am assuming that you are not correctly referencing at least this thirdparty component ...

**Comment by rduffner** [comment]
I checked and the mu tools do work. If it couldn't find the freetype libraries while building, wouldn't it complain?

I asked the author of the mupdf port and he says his port works.

**Comment by rduffner** [comment]
(mu) (bsd-test <mu>) 0 # ldd lib/python2.7/site-packages/fitz/_fitz.so
lib/python2.7/site-packages/fitz/_fitz.so:
	libthr.so.3 => /lib/libthr.so.3 (0x801257000)
	libmupdf.so.1.16.0 => /usr/local/lib/libmupdf.so.1.16.0 (0x801600000)
	libmupdf-third.so.1.16.0 => /usr/local/lib/libmupdf-third.so.1.16.0 (0x8044c5000)
	libpython2.7.so.1 => /usr/local/lib/libpython2.7.so.1 (0x804797000)
	libc.so.7 => /lib/libc.so.7 (0x800825000)
	libjpeg.so.8 => /usr/local/lib/libjpeg.so.8 (0x804b8e000)
	libopenjp2.so.7 => /usr/local/lib/libopenjp2.so.7 (0x804e23000)
	libjbig2dec.so.0 => /usr/local/lib/libjbig2dec.so.0 (0x80507d000)
	libm.so.5 => /lib/libm.so.5 (0x80529a000)
	libdl.so.1 => /usr/lib/libdl.so.1 (0x8054ca000)
	libintl.so.8 => /usr/local/lib/libintl.so.8 (0x8056cb000)
	libutil.so.9 => /lib/libutil.so.9 (0x8058d6000)

**Comment by rainerduffner** [comment]
Hi,

the wording in setup.py is a bit confusing. At least for somebody who does not do that regularly.

The libraries have indeed got to be adjusted, like this:

`        libraries=["mupdf", "mupdf-third", "freetype", "harfbuzz"],
`

likely more, as mupdf is linked to more libraries.

But it was enough to make the "import fitz" step work at least.

I'll update the ticket later, maybe with a more complete list.

**Comment by JorjMcKie** [comment]
Did you say, it is working now for you?
Would be great.

I agree, this is an unfortunate aspect of MuPDF (not PyMuPDF!): the items to name in those brackets are different by platform, and also sometimes change across MuPDF releases.

It would be great if you could come up with a list that works sometime and submit a PR to update the setup.py ...

**Comment by rainerduffner** [comment]
I was at least able to import it in the python console.

First I only added libfreetype and then it complained about some harfbuzz function, which made me realize I need to potentially add all those libraries by hand.

The customer who is using the module in his application is now checking it. He'll report back any additional libraries that will need to be added.

With hindsight, I could probably also have looked at the spec file for recent Fedora releases, which seem to contain it as package.

**Comment by cges30901** [comment]
Here is patch Fedora use to build PyMuPDF:
https://src.fedoraproject.org/rpms/python-PyMuPDF/blob/master/f/fix-library-linking.patch.
Similar patch is required when I build for openSUSE, Arch and Ubuntu.

**Comment by rainerduffner** [comment]
Yes, I realized I could have looked at the srpm from Fedora. But only after I found it out myself.

**Comment by JorjMcKie** [comment]
@rainerduffner - how are you doing? Is your issue resolved?

**Comment by rainerduffner** [comment]
Yes.
Customer says everything works.
Maybe some more comments in setup.py so even a noob understands what to do.

Thanks.

**Comment by JorjMcKie** [comment]
excellent - please provide me with some version of your setup.py, so I can integrate your comments into the repo version
