### ISSUE TITLE
find_tables increase process time 30% after version 1.23.8

### ISSUE THREAD

**Issue by lqglqy** [pymupdf/PyMuPDF#3885]
### Description of the bug

find_tables process time increases on the pdf file too many pages are observed.

### How to reproduce the bug

slow_find_tables.py
`import fitz as pymupdf
import time

pdf_file = "slow_p50.pdf"

start_time = time.time()

pdf_document = pymupdf.open(pdf_file)
for page in pdf_document:
    page.get_text()
    tabs = page.find_tables()
    for t in tabs.tables:
        table = t.extract()
        print(table)
        print("===")

print("Time taken: ", time.time() - start_time)`

`pip3 install pymupdf==1.23.8

 python3 slow_find_table.py 

**Time taken:  1.2648093700408936**
`

` pip3 uninstall pymupdf

pip3 install pymupdf==1.24.10

python3 slow_find_table.py 

**Time taken:  0.8415310382843018**
`

[slow_p50.pdf](https://github.com/user-attachments/files/17128776/slow_p50.pdf)

### PyMuPDF version

1.24.10

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
This is not a bug. We are constantly improving the table finder and trying different strategies in efforts to find tables. This of course takes more time.
Well invested time, as you will agree.
None of your 50 pages contains a table BTW. So what you are testing here is the time it takes to determine that there is no table whatsoever.

**Comment by lqglqy** [comment]
> This is not a bug. We are constantly improving the table finder and trying different strategies in efforts to find tables. This of course takes more time. Well invested time, as you will agree. None of your 50 pages contains a table BTW. So what you are testing here is the time it takes to determine that there is no table whatsoever.

Thank you for your time.

I need to locate the tables in an unidentified PDF, even if they contain none. 
Do you have another way to do a faster search?

**Comment by JorjMcKie** [comment]
Sorry, I am not aware of anything faster.
