### ISSUE TITLE
How can I extract sound from a pdf file

### ISSUE THREAD

**Issue by dplcz** [pymupdf/PyMuPDF#3888]
[Big_Password_Removed.pdf](https://github.com/user-attachments/files/17133860/Big_Password_Removed.pdf)
I have a pdf file with sound button. I want to extract them in pymupdf.

**Comment by JorjMcKie** [comment]
Have a look here please: https://pymupdf.readthedocs.io/en/latest/annot.html#Annot.get_sound

**Comment by dplcz** [comment]
> Have a look here please: https://pymupdf.readthedocs.io/en/latest/annot.html#Annot.get_sound
I tried get_sound function, but it made an error:TypeError: bad annot type.

**Comment by JorjMcKie** [comment]
I saw it now. It is not a sound annotation, which is the only type from which we currently support extraction of the sound file.
It is a `Screen` annotation which we do not support yet at all.
