### ISSUE TITLE
Memory Leak In getPixmap

### ISSUE THREAD

**Issue by cherryjo18** [pymupdf/PyMuPDF#389]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
getPixmap cause memory leak when pdf file has many images

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

import fitz
import tracemalloc

tracemalloc.start(1000)
t1 = tracemalloc.take_snapshot()
for i in range(100) : 
	doc = fitz.open("c:\\temp\\bbb.pdf")
	page = doc.loadPage(0)
	mat = fitz.Matrix(3, 3)
	pix = page.getPixmap(matrix = mat)
	del pix
	del page
	doc.close()
t2 = tracemalloc.take_snapshot()

stats = t2.compare_to(t1, 'lineno')

for stat in stats :
	print(stat)

bbb.pdf has many bitmap object

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

OS : 
windows 10 / 64 bit

python :
C:\Python37>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

PyMuPDF  
 1.16.5

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
 win32

PyMuPDF 1.16.5: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-10-13 22:50:03.
Built for Python 3.7 on win32 (32-bit).

## Additional context (optional)
tracemalloc result 
C:\Python37\lib\site-packages\fitz\fitz.py:4766: size=210 MiB (+210 MiB), count=3203 (+3203), average=67.2 KiB
C:\Python37\lib\site-packages\fitz\fitz.py:3502: size=22.3 MiB (+22.3 MiB), count=3201 (+3201), average=7306 B

**Comment by JorjMcKie** [comment]
I believe this is **not** the case.
The base library MuPDF in contrast **deliberately keeps things in memory** - up to some provided limit, and - for images - even after the document has been closed.
A realistic scenario for measuring memory occupation therefore must not only close the document, but also forcedly free this MuPDF buffer **before** measuring memory deltas.
PyMuPDF has tools to do exactly this. Here is a script to convince you. It reads a cli-provided document ``niter`` times and creates pixmaps for each page of it.
A sample output for 100 page scientific magazine with several hundred images produced this output (``niter = 10``). The Adobe manual with is 180 images on 1310 pages looks similar.

```
File 'sdw_2015_06.pdf'
Memory deltas (MB) for Page.getPixmap
0 stop delta 5.8
1 stop delta 0.9
2 stop delta 0.5
3 stop delta -0.1
4 stop delta 0.4
5 stop delta -0.7
6 stop delta 0.6
7 stop delta -0.3
8 stop delta 0.6
9 stop delta 0.1
================================================================================
Total pages processed: 1000
Duration: 34 sec
```
[memory-pix.zip](https://github.com/pymupdf/PyMuPDF/files/3784136/memory-pix.zip)

**Comment by cherryjo18** [comment]
thank for your help.  
TOOLS.store_shrink(100) works well
PyMuPDF is BEST!!

**Comment by JorjMcKie** [comment]
Thanks for the feedback!

**Comment by bc291** [comment]
@JorjMcKie 
Hi! Quick question. Is a `get_pixmap` leak a thing again? After some investigation, I can reach up to ~ 350 MB with sample [Adobe manual](https://helpx.adobe.com/content/dam/help/en/pdf/photoshop_reference.pdf?clickref=1011lwATThWn&mv=affiliate&mv2=pz&as_camptype=&as_channel=affiliate&as_source=partnerize&as_campaign=prodesigntools).

Output from your `memory-pix.zip`(`getPixmap` switched to `get_pixmap`) as follows :

```bash
3.11.2 (main, Feb  9 2023, 20:14:21) [GCC 10.2.1 20210110]

PyMuPDF 1.21.0: Python bindings for the MuPDF 1.21.0 library.
Version date: 2022-11-08 00:00:01.
Built for Python 3.11 on linux (64-bit).

File 'adobe.pdf'
Memory deltas (MB) for Page.getPixmap
0 stop delta 268.8
1 stop delta 36.9
2 stop delta -13.2
3 stop delta 13.1
4 stop delta 0.3
5 stop delta 0.0
6 stop delta 0.5
7 stop delta -20.0
8 stop delta 6.4
9 stop delta 12.6
================================================================================
Total pages processed: 10170
Duration: 30 sec
```

**Comment by JorjMcKie** [comment]
> Is a get_pixmap leak a thing again?

It actually never has leaked!
I believe I mentioned in my response to the previous inquiry: The base library MuPDF tries to keep especially images in its internal cache, in order to avoid having to load these typically large object multiple times.
So your amount of occupied memory does not look problematic in an way. Deleting a created Pixmap object in Python will not necessarily remove the corresponding image in MuPDF's internal cache.
If you - for no apparent reason - wish to empty that cache, you can use the above mentioned method.

**Comment by moran-trullion** [comment]
how someone need to guess he should run this TOOLS.store_shrink(100)  crap.
if the document is closed release the memory.
to say it's the deseried behavior, crazy. cost me 5 days of my life
