### ISSUE TITLE
While extracting sound from a pdf file , I got an TypeError

### ISSUE THREAD

**Issue by dplcz** [pymupdf/PyMuPDF#3890]
### Description of the bug

I have a pdf file with sound button. I want to extract them in pymupdf. But I got an TypeError: bad annot type.

### How to reproduce the bug

I tried following code.
```
import sys
import pathlib
import fitz

doc = fitz.open("Big_Password_Removed.pdf")  # open PDF
page = doc[0]  # load desired page (0-based)
annot = page.first_annot  # access the desired annot (first one in example)
temp = annot.get_sound()
pass
```

### PyMuPDF version

1.24.9

### Operating system

Windows

### Python version

3.9

**Comment by dplcz** [comment]
[Big_Password_Removed.pdf](https://github.com/user-attachments/files/17134474/Big_Password_Removed.pdf)
This is my pdf file.

**Comment by JorjMcKie** [comment]
We do not support Screen annotations at all currently.
