### ISSUE TITLE
Can not remove the text by  page.add_redact_annot(span["bbox"])

### ISSUE THREAD

**Issue by ytcpub** [pymupdf/PyMuPDF#3895]
### Description of the bug

when I want to remove the text by 'RESEARCH' in the title in first page, it take no effect, I do not want remove the image, only remove the 'RESEARH' text
[81d0fe05b5bd35793742a647dd12e.pdf](https://github.com/user-attachments/files/17146376/81d0fe05b5bd35793742a647dd12e.pdf)

### How to reproduce the bug

doc = fitz.open('..pdf')
page = doc[0]
blocks = page.get_text("dict")["blocks"]
txt_blocks = [blk for blk in blocks if blk['type'] == 0]

for block in txt_blocks:
    for line in block.get("lines", []):
        for span in line['spans']:
          page.add_redact_annot(span["bbox"])
 page.apply_redactions(images=0, graphics=1, text=0)
 doc.ez_save(output_file)

### PyMuPDF version

1.24.9

### Operating system

Linux

### Python version

3.12

**Comment by JorjMcKie** [comment]
You are wrong: the word "RESEARCH" is gone! To prove this, try to extract it again.

**Comment by ytcpub** [comment]
import fitz
    input_pdf = f'81d0fe05b5bd35793742a647dd12e.pdf'
    doc = fitz.open(input_pdf)
    page = doc[0]
    blocks = page.get_text("dict")["blocks"]
    txt_blocks = [blk for blk in blocks if blk['type'] == 0]
    for block in txt_blocks:
        for line in block.get("lines", []):
            for span in line['spans']:
                page.add_redact_annot(span["bbox"])
    page.apply_redactions(images=0, graphics=1, text=0)
    doc.ez_save('/tmp/test.pdf')
I see in windows 10， the “RESEARCH” is not gone
![1727400221217](https://github.com/user-attachments/assets/d9b55abb-9e8b-4f9b-a288-6aa224a0d599)
[test.pdf](https://github.com/user-attachments/files/17157756/test.pdf)

**Comment by JorjMcKie** [comment]
Can you still extract the text "Research"? No, you cannot: there is no such text anymore.
Is that text still visible? Yes, it is. **_But not as text!_**
The fault is your choice of options for `apply_redactions()`. Your intention obviously is not to influence images and vector graphics.
So this is the result.
If you let these options default, then the image part with the text is punched out.

**Comment by ytcpub** [comment]
> Can you still extract the text "Research"? No, you cannot: there is no such text anymore. Is that text still visible? Yes, it is. **_But not as text!_** The fault is your choice of options for `apply_redactions()`. Your intention obviously is not to influence images and vector graphics. So this is the result. If you let these options default, then the image part with the text is punched out.

got， thanks very much~
