### ISSUE TITLE
Linearizing PDF does not speed up web viewing

### ISSUE THREAD

**Issue by blenzi** [pymupdf/PyMuPDF#3900]
### Description of the bug

Hi,

I am trying to save a linearised version of a PDF to speed up its web viewing. With [Adobe API](https://github.com/adobe/pdfservices-python-sdk-samples/blob/main/src/linearizepdf/linearize_pdf.py) it does it on a Firefox / pdfjs viewer but with PyMuPDF it doesn't seem to help.

Original PDF: https://minio.lab.sspcloud.fr/blenzi/public/org64M.pdf
Linearized with pymupdf 1.24.10: https://minio.lab.sspcloud.fr/blenzi/public/linear.pdf
Linearized with Adobe API: https://minio.lab.sspcloud.fr/blenzi/public/LinearizePDF.pdf

Any ideas?

Thanks in advance

### How to reproduce the bug

```
import fitz

doc = fitz.open("org64M.pdf")
with fitz.open() as doc2:
    doc2.insert_pdf(doc)
    doc2.save("linear.pdf", linear=True)

with fitz.open("linear.pdf") as doc2, fitz.open("LinearizePDF.pdf") as doc3:
    print(doc.is_fast_webaccess, doc2.is_fast_webaccess, doc3.is_fast_webaccess)

# Output: 0 1 1
```

### PyMuPDF version

1.24.10

### Operating system

Linux

### Python version

3.12

**Comment by JorjMcKie** [comment]
The linearized version is created by MuPDF code. PyMuPDF cannot do anything here. So I suggest you submit bug in their issue system, https://bugs.ghostscript.com/enter_bug.cgi. You probably should also discuss with the MuPDF team on [this](https://discord.gg/mFSSpaEp) Discord channel.

Other than that, I suggest to also use some garbage collection option when saving the PDF like `garbage=3`. Creating the linearized format drastically changes a PDF's internal structure, leaving behind now-unused object. I would also make sure to compress eligible objects with `deflate=True`.

**Comment by dedesite** [comment]
For the record, I tried the 2 linearized pdf with a Pdf Web Player that handle linearization (PSPDFKit) with Firefox Dev tools activated and a bandwith limit set to 4G/LTE and had no problem streaming them.
It seems that they both took the same time to first display and had no problem streaming the files.
