### ISSUE TITLE
page.get_images() returns CCITTFaxDecode image with inverted black/white colors

### ISSUE THREAD

**Issue by davidress-ILW** [pymupdf/PyMuPDF#3912]
### Description of the bug

* Explain the steps required to reproduce the bug.
When trying to extract the image on page 283 (0 based) of the [document  ](https://www.militarynewbie.com/wp-content/uploads/2013/11/TM-43-0001-28-Army-Ammunition-Data-Sheets1.pdf)the image that is returned has the black/white colors inverted, producing a "dark mode" image.  When examined in the document, the images are reversed/normal. Some debugging revealed that the smask is 0 and the colorspace is None for the image. I have also tried converting the PixMap to a Pillow Image for doing the inversion, but that fails also.

* Include required code snippets, example files, etc.
The example code is taken from both the PyMuPDF documentation and Pillow examples.

```
import fitz
from PIL import Image, ImageChops

doc = fitz.open( "/files/TM 43-0001-28-Army-Ammunition-Data-Sheets.pdf")
use_PIL = False
page = doc[283]
image_list = page.get_images()
for image_index, img in enumerate(image_list, start=1):  # loop through all images on the page
    xref = img[0] # get the xref
    pix = fitz.Pixmap(doc, xref) # create a Pixmap
    if use_PIL:
        pil_image = Image.frombytes("1", [pix.width, pix.height], pix.samples)
        pil_image = ImageChops.invert(pil_image)
        pil_image.save(f"image_{image_index}.png")
    else:
        if pix.n - pix.alpha > 3: # CMYK: convert to RGB first
            pix = fitz.Pixmap(fitz.csRGB, pix)
        pix.save(f"image_{image_index}.png")  # save the image as png
```
* Describe what you expected to happen (if not obvious).
I expected the image to not be black/white color reversed.

* Include any other information that could be relevant, for example information about the Python environment.
Python 3.10.0
PyMuPDF version = 1.24.10
Pillow version = 10.3.0

### How to reproduce the bug

* Give the exact build/install commands that were run.
Conda installation

### PyMuPDF version

1.24.10

### Operating system

Windows

### Python version

3.10

**Comment by JorjMcKie** [comment]
This will do the job:
```python
import pymupdf

doc = pymupdf.open("test.pdf")
page = doc[283]
for img in page.get_images():
    xref = img[0]
    pix = pymupdf.Pixmap(doc, xref)
    if not pix.colorspace.n:  # a stencil-only pixmap
        png = pix.tobytes()  # convert it to a PNG
        pix = pymupdf.Pixmap(png)  # re-open from a memory PNG
        pix.invert_irect()  # invert the b&w pixmap
    pix.save(f"{xref}.png")
``

**Comment by davidress-ILW** [comment]
@JorjMcKie Thank you, that does indeed work. 

Also, thank you for reminding me to start using "import pymupdf" instead of "import fitz" - I just upgraded all my project source scripts accordingly.
