### ISSUE TITLE
Ability to print MuPDF errors to `logging` instead of `stdout`

### ISSUE THREAD

**Issue by jamesbraza** [pymupdf/PyMuPDF#3914]
**Is your feature request related to a problem? Please describe.**

`PyMuPDF==1.24.10` will occasionally print [`MuPDF error`](https://github.com/pymupdf/PyMuPDF/blob/1.24.10/src/__init__.py#L16658-L16659)s to [`stdout`](https://github.com/pymupdf/PyMuPDF/blob/1.24.10/src/__init__.py#L102-L107).

The issue with `print` is:
- Random `stdout` prints mess with CLI utilities like `rich.Progress` bars
- Misses the opportunity for the benefits of Python logging (process global message formatting and/or filtering)

**Describe the solution you'd like**

Either:

- PyMuPDF to expose a way for callers to "install" a `logging.Logger` instead of `print`
    - And `message` to support a "level" argument (e.g. error level, debug level, etc)
- PyMuPDF to move to Python `logging`

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by julian-smith-artifex-com** [comment]
Latest PyMuPDF in git has new function `pymupdf.use_python_logging()` that allows PyMuPDF messages to be sent to Python's `logging` module. See: https://github.com/pymupdf/PyMuPDF/blob/main/src/__init__.py#L109

The function docstring describes how to use it, but we'll also add it to the main documentation soon.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.12. See: https://pymupdf.readthedocs.io/en/latest/app3.html#diagnostics

**Comment by jamesbraza** [comment]
Okay thank you @julian-smith-artifex-com , I went from:

```python
# Work around https://github.com/pymupdf/PyMuPDF/issues/3914
pymupdf_logger = logging.getLogger(pymupdf.__name__)

def message(text="") -> None:
    # https://github.com/pymupdf/PyMuPDF/blob/1.24.10/src/__init__.py#L102-L107,
    # but with logging instead of print
    # Warning was chosen since most `message` usages are errors or warnings
    pymupdf_logger.warning(text)

pymupdf.message = message
```

To this:

```python
pymupdf.set_messages(pylogging=True)
```

**Comment by julian-smith-artifex-com** [comment]
Great, i'm glad it's working for you.
