### ISSUE TITLE
Slicing doesn't work

### ISSUE THREAD

**Issue by keshavdata** [pymupdf/PyMuPDF#392]
On the tutorial page https://pymupdf.readthedocs.io/en/latest/tutorial/ the usage of slicing is mentioned :
```
for page in doc.pages(start, stop, step):
   # do something with 'page'
```

a simple example:

```
for pa in asr.pages(0,6,1):
    type(pa)
```

this doesn't work, but returns an error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Document' object has no attribute 'pages'
```

**Comment by JorjMcKie** [comment]
you did not provide mandatory information: ``print(fitz.__doc__)``

**Comment by keshavdata** [comment]
PyMuPDF 1.16.3: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-10-01 09:01:06.
Built for Python 3.7 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
this feature has been introduced in v1.16.4
