### ISSUE TITLE
RuntimeError: code=7: cannot find entry OEBPS

### ISSUE THREAD

**Issue by mrx23dot** [pymupdf/PyMuPDF#3921]
### Description of the bug

Epubs opens without problem in SumatraPdf, but fails with lib, lib should tolerate minor inconsistencies.
```

import pymupdf

def readDoc(fn):
  text = []
  print('reading',fn)
  with pymupdf.open(fn) as doc:
    for page in doc:
      for line in page.get_text().splitlines():
        text.append(line.rstrip())
  return text

readDoc('dummy.epub')
```
in
[dummy.zip](https://github.com/user-attachments/files/17269442/dummy.zip)

gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in readDoc
  File "C:\py38_64\lib\site-packages\pymupdf\__init__.py", line 2699, in __getitem__
    if i not in self:
  File "C:\py38_64\lib\site-packages\pymupdf\__init__.py", line 2632, in __contains__
    if loc < self.page_count:
  File "C:\py38_64\lib\site-packages\pymupdf\__init__.py", line 5009, in page_count
    return self.page_count2(self)
  File "C:\py38_64\lib\site-packages\pymupdf\extra.py", line 132, in page_count_fz
    return _extra.page_count_fz(document)
RuntimeError: code=7: cannot find entry OEBPS/welcome.html
```

### How to reproduce the bug

see above

### PyMuPDF version

1.24.11

### Operating system

Windows

### Python version

3.8

**Comment by JorjMcKie** [comment]
This is a design decision taken in the base library MuPDF. PyMuPDF has no way to work around this - which is not to say that we even share your assessment of a **_"minor"_** inconsistency.

Please submit an "enhancement" (?) request to MuPDF's issue system here https://bugs.ghostscript.com/enter_bug.cgi.
Or discuss with the MuPDF experts on this [Discord](https://discord.gg/mFSSpaEp) channel.
