### ISSUE TITLE
Bad loca value error when using subset_fonts with a specific document

### ISSUE THREAD

**Issue by shunkica** [pymupdf/PyMuPDF#3922]
### Description of the bug

Whenever I use the `subset_fonts() `function on a specific document I get this output: `MuPDF error: format error: Bad loca value`

However, I can not see any apparent problems in the document which is subsequently created, so this error puzzles me.

Using `subset_fonts` with `fallback=True` does not produce this error.

Unfortunately I can not share the document in question because it is confidential.

### How to reproduce the bug

```
def merge_pdfs(output_path, input_file_paths):
    pdf_output = fitz.open()

    for input_file_path in input_file_paths:
        pdf = fitz.open(input_file_path)
        pdf_output.insert_pdf(pdf)
        pdf.close()

    # pdf_output.subset_fonts(fallback=True)
    pdf_output.subset_fonts()
    pdf_output.ez_save(output_path)
    pdf_output.close()
```

### PyMuPDF version

1.24.11

### Operating system

Linux

### Python version

3.12

**Comment by JorjMcKie** [comment]
This is a problem in some font, detected by the `subset_fonts()` function in the base library. This function is a lot more diligent than the former `fontTools`-based method.
More font categories are supported as well as internal font format errors are detected which were simply ignored before.
So just also ignore these messages.

**Comment by shunkica** [comment]
Is there any way I can pinpoint the exact problem in the original pdf?

**Comment by JorjMcKie** [comment]
No, MuPDF does not provide specific information.
