### ISSUE TITLE
Question: Best Approach to image flattening a PDF

### ISSUE THREAD

**Issue by juviwhale** [pymupdf/PyMuPDF#393]
I would like to *image flatten* pdfs (i.e. convert PDF pages to images). What is the best way to do this with PyMuPDF? 

Would you recommend an alteration of your [Make one PDF of all your Pictures](https://pymupdf.readthedocs.io/en/latest/faq/#how-to-make-one-pdf-of-all-your-pictures-or-files) recipe where instead each of the inserted images is generated via `page.getPixmap()` of each page?

Or is there a better approach / MuPDF API you would recommend?

**Comment by JorjMcKie** [comment]
If you want to make images from document pages (PDF or all the other document types), then ``page.getPixmap`` is the best approach. As I know you know, there is a plethora of ways to control the output quality (resolution, colorspace, etc.).

The other catch word you mentioned was rather the other way round: how to combine **existing** files (images or general files) into one PDF for whatever motives Here we have several alternatives - from embedding or attaching files to converting images to PDFs and joining the results, and what not.

When looking closer at your inquiry:
If you just want to "convert" an existing PDF into one looking exactly equal but consisting of a sequence of images made from the original pages, then two separate steps would be apppropriate:
1. convert a (any) document to a series of page images
2. combine the separate images into one PDF

**Comment by JorjMcKie** [comment]
So the whole code snippet might be:

```python
src = fitz.open(input.pdf)
out = fitz.open()
mat = fitz.Matrix(2,2)  # double resolution
for page in src:
    rect = page.rect
    pix = page.getPixmap(matrix = mat)
    png = pix.getImageData("png")
    outpage = out.newPage(width=rect.width, height=rect.height)
    outpage.insertImage(rect, stream=png)
out.close("flattended.pdf", garbage=4, deflate=True)
```

**Comment by juviwhale** [comment]
Great. Thanks!

**Comment by arunksoman** [comment]
For newer version of PyMUPDF (I tried on 1.21.0) the above snippet is not working due to some breaking changes in API. The below snippet is working for me:

```python
import fitz

src = fitz.Document("input.pdf")
out = fitz.Document()
mat = fitz.Matrix(2, 2)  # double resolution
for i, page in enumerate(src):
    rect = page.rect
    pix = page.get_pixmap(matrix=mat)
    # pix.pil_tobytes()
    png = pix.tobytes("png")
    out._newPage(width=rect.width, height=rect.height)
    out_page = out.load_page(i)
    out_page.insert_image(rect, stream=png)
out. Save("flattend.pdf", garbage=4, deflate=True)
```
