### ISSUE TITLE
sys:1: DeprecationWarning: builtin type swigvarlink has no __module__ attribute

### ISSUE THREAD

**Issue by samiashi** [pymupdf/PyMuPDF#3931]
### Description of the bug

Upgrading from `pymupdf==1.24.10` to `pymupdf==1.24.11` shows a deprecation warning when running pytest
Likely related to https://github.com/swig/swig/issues/2881

```
<frozen importlib._bootstrap>:241
<frozen importlib._bootstrap>:241
  <frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute

<frozen importlib._bootstrap>:241
<frozen importlib._bootstrap>:241
  <frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute

<frozen importlib._bootstrap>:241
  <frozen importlib._bootstrap>:241: DeprecationWarning: builtin type swigvarlink has no __module__ attribute

sys:1: DeprecationWarning: builtin type swigvarlink has no __module__ attribute
```

### PyMuPDF version

1.24.11

### Operating system

MacOS

### Python version

3.11.10

**Comment by julian-smith-artifex-com** [comment]
Thanks for the report. It's actually a known issue with pytest and Py_LIMITED_API (which we started to use with PyMuPDF_1.24.11).

For more information, please see: https://github.com/swig/swig/issues/2881#issuecomment-2332652634.

I'll close this now as there's nothing we can do in PyMuPDF to avoid these warnings.

**Comment by samiashi** [comment]
Thanks for the update @julian-smith-artifex-com!

**Comment by wentao-belfry** [comment]
I see this is closed: https://github.com/swig/swig/issues/2881#issuecomment-2332652634. Wonder if this ticket can be reopened to fix the deprecation warning? It is not breaking anything but a little annoying in the log.

**Comment by julian-smith-artifex-com** [comment]
The version of SWIG on pypi.org is 4.3.1, which does not contain the fix. As explained earlier, until this is updated PyMuPDF builds will continue to show the warning and there is little we can do about it, so i don't think it makes sense to reopen this issue.

I have verified that the warnings do not appear when PyMuPDF is built with the latest swig in git (which calls itself version 4.4.0) so it will eventually be fixed, depending on the swig and PyMuPDF release schedules.

**Comment by andres-ito-traversal** [comment]
@julian-smith-artifex-com how do you know what version of SWIG is on pypi.org? WHere do you find that sort of the information

**Comment by julian-smith-artifex-com** [comment]
> [@julian-smith-artifex-com](https://github.com/julian-smith-artifex-com) how do you know what version of SWIG is on pypi.org? WHere do you find that sort of the information

`pip install swig` shows the name of the sdist/wheel it uses. This name contains the version, for example:
```
 % pip install swig
Collecting swig
  Using cached swig-4.4.0-py3-none-macosx_10_9_universal2.whl.metadata (3.5 kB)
Using cached swig-4.4.0-py3-none-macosx_10_9_universal2.whl (2.6 MB)
Installing collected packages: swig
Successfully installed swig-4.4.0
%
```
The version is also on the pypi swig page, https://pypi.org/project/swig/.

**Comment by andres-ito-traversal** [comment]
Right, but when I do this in my `pyproject.toml`

```
[build-system]
requires = ["setuptools>=42", "wheel", "numpy==1.26.4", "swig==4.4.0"]
build-backend = "setuptools.build_meta"

...
[project]
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
	"pymupdf==1.26.6",
	"swig==4.4.0",
]
```

I still experience this SwigVar issue.

i wonder if this is because `pymupdf==1.26.6` uses swig version `4.3.1`. Is there a way to figure this out?

**Comment by julian-smith-artifex-com** [comment]
There seems to be an unrelated problem with the latest swig-4.4.0 on macos (https://github.com/swig/swig/issues/3279)  so on macos pymupdf is built with swig-4.3.1. Hence the warnings from pytest with pymupdf are still there.

On non-macos platforms, we build pymupdf with swig-4.4.0 and for me this does not show the warnings with pytest.

**Comment by andres-ito-traversal** [comment]
Got it, this makes sense. Im on a mac. Thanks @julian-smith-artifex-com for being so responsive!
