### ISSUE TITLE
PyMuPDF Segfaults when using TOOLS.mupdf_warnings()

### ISSUE THREAD

**Issue by bschollnick** [pymupdf/PyMuPDF#394]
I can not identify if this issue is a PyMuPDF related issue, or a Python 3 related issue, but PyMuPDF appears to be causing a segment Fault after attempting to check for MuPDF.warnings. (It appears to work fine, until it outputs the raw_errmsg data.

        raw_errmsg = fitz.TOOLS.mupdf_warnings()

See sample code.

## Describe the bug (mandatory)
This code verifies the structure of the PDF file, by opening the PDF file, and then examining Fitz.TOOLS.mupdf_warnings(), and passing back a tipple containing (error status (boolean), a modified err msg, and the raw err msg from mupdf_warnings).

This issue may have been occurring for a while, since in a multitasking environment (gunicorn) it appears to be running for a while, until it segfaults.  But since gunicorn is multithreaded, it is catching the error and preventing it from dying.

## To Reproduce (mandatory)
See sample code, example:

(quickbbs) benjamin@Nerv frontend % python test_pdf.py /Volumes/Support/Support/Dropbox/pdfs/sites.google.com-Ghostbuster\ proton\ pack.pdf 
Before check
Before
After
Really after
0 True
after check
Before check
Before
After
zsh: segmentation fault  python3 test_pdf.py 

## Your configuration (mandatory)
 - Mac OS Mojave (10.15.1)
[Clang 6.0 (clang-600.0.57)] 
 darwin 
 
PyMuPDF 1.16.6: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-11-01 18:55:25.
Built for Python 3.8 on darwin (64-bit).
[HomeMade Modern EP46 Concrete Fire Pit.pdf](https://github.com/pymupdf/PyMuPDF/files/3817155/HomeMade.Modern.EP46.Concrete.Fire.Pit.pdf)

[test_pdf.py.zip](https://github.com/pymupdf/PyMuPDF/files/3817158/test_pdf.py.zip)

**Comment by JorjMcKie** [comment]
Thanks for submitting this - it is a PyMuPDF bug.
I forgot to increase the Python reference count for the underlying list, so it was a question of time until the function would try to address a non-existing object.
The most simple quickfix for you:
Call ``fitz.TOOLS.reset_mupdf_warnings()`` after each ``fitz.TOOLS.mupdf_warnings()``.

Let me ask you this: Should that be the correct handling anyway, or should I continue to append messages endlessly?

**Comment by JorjMcKie** [comment]
The error can be reproduced simply by repeatedly calling ``fitz.TOOLS.mupdf_warnings()`` e.g. in IDLE.

**Comment by bschollnick** [comment]
Well, at bare minimum reviewing Fitz.TOOLS.mupdf_warnings() shouldn't cause a segfault.    So that code shouldn't be dependent on the reset for preventing the segfault.  

Now regarding the clearing of the warnings, I can argue both ways regarding the clearing of the warnings.

It does have a reasonable precedent to clear a stack after you've viewed it.  

But...

Is there any code in PyMuPDF that views that stack?  (eg does your code destroy that stack before the programmer can get to it..)

**Comment by JorjMcKie** [comment]
> Is there any code in PyMuPDF that views that stack? (eg does your code destroy that stack before the programmer can get to it..)

No - these two functions are the only ones accessing it. If the user / script never looks, then nothing happens except appending new lines to the internal Python list for every warning.

But from your hesitant reaction I conclude that I should better leave things functionality-wise as they are and better just increase the reference count properly.
This also already works in my testing ...

**Comment by JorjMcKie** [comment]
> Well, at bare minimum reviewing Fitz.TOOLS.mupdf_warnings() shouldn't cause a segfault. So that code shouldn't be dependent on the reset for preventing the segfault.

Of course. What I was thinking of is resetting the store every time autmatically when the function ``mupdf_warnings()`` has been called.

**Comment by bschollnick** [comment]
That's really up to what design you want to follow.  As I mentioned, I can see arguments for both sides.  
I just get a few opinions from some coworkers...

General attitude is, that if we're checking for an error, we shouldn't be checking for the same error again.  So auto-clearing of the errors, is probably the advised route...  Just please make sure it's documented as such...

**Comment by JorjMcKie** [comment]
Thanks for this feedback and opinion collection.
I think I will offer a keyword argument like ``mupdf_wanings(reset=True)``. If someone still wants to maintain a full message collection, would have to specify ``reset=False``.

**Comment by bschollnick** [comment]
That seems like a fair way to deal with it.

**Comment by JorjMcKie** [comment]
PyPI upload v1.16.7 fixing this.
