### ISSUE TITLE
The text results of parsing PDF files are all garbled (Chinese PDF)

### ISSUE THREAD

**Issue by Number18-tong** [pymupdf/PyMuPDF#3945]
### Description of the bug

Thanks for your great work, I have been using the fitz  to parse pdf for a while, it truly has excellent ability to parse PDFs.
but I found when parse some Chinese pdfs. the results are all garbled. Is there an solution for this issue?
![企业微信截图_17289751034875](https://github.com/user-attachments/assets/12f58ef8-5eba-42fb-b428-2ee7bd910024)

### How to reproduce the bug

[1015.pdf](https://github.com/user-attachments/files/17373987/1015.pdf)

def extract_text_and_coordinates(pdf_path):
    """
    Extract all text and corresponding coordinates from a PDF file.

    Parameters:
    - pdf_path: path to the PDF file

    Returns:
    - List of tuples containing text and corresponding coordinates (x0, y0, x1, y1).
    """
    doc = fitz.open(pdf_path)
    # text_with_coordinates = []
    allrestext = ""
    for page_number in range(len(doc)):
        pagelist = []
        page = doc.load_page(page_number)
        # blocks = page.get_text("dict")["blocks"]
        blocks = page.get_text("blocks")
        for i, b in enumerate(blocks):
            if b[6]:
                continue
            try:
                # text = page.get_text("blocks", clip=[b[0], b[1], b[2], b[3]])
                oritext = unicodedata.normalize('NFKD', b[4]).encode('utf-8', 'replace').decode('utf-8')
                # oritext = b[4].replace("\ue5cc", "")
                textlist = oritext.split("\n")
                text = ""
                for x in textlist:
                    if x == "":
                        continue
                    if text != "":
                        text += " " + x.strip()
                    else:
                        text += x.strip()
                if text == "":
                    continue
                pagelist.append([[b[0], b[1], b[2], b[3]], text])
                # print([[b[0], b[1], b[2], b[3]], b[4]])
            except:
                print(b)
        # pagelist = sorted(pagelist, key=lambda x: (x[0][1], x[0][0]))
        pagetext = ""
        for block in pagelist:
            if pagetext != "":
                pagetext += "\n" + block[1]
            else:
                pagetext += block[1]
        pagetext += "\n"
        if allrestext != "":
            allrestext += "\n" + pagetext
        else:
            allrestext += pagetext
    return allrestext, len(doc)

### PyMuPDF version

1.24.9

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
One or more fonts of this PDF contain non-standard encoding. No tool can extract the text.
Try to cut and past using some PDF viewer: it will always result in garbish.

**Comment by Number18-tong** [comment]
I get it now, thanks a lot



---Original---
From: "Jorj X. ***@***.***&gt;
Date: Tue, Oct 15, 2024 16:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pymupdf/PyMuPDF] The text results of parsing PDF files are allgarbled (Chinese PDF) (Issue #3945)




 
One or more fonts of this PDF contain non-standard encoding. No tool can extract the text.
 Try to cut and past using some PDF viewer: it will always result in garbish.
