### ISSUE TITLE
A PDF that cannot be processed

### ISSUE THREAD

**Issue by 1339503169** [pymupdf/PyMuPDF#3962]
### Description of the bug

https://helpx.adobe.com/cn/acrobat/using/component-files-pdf-portfolio.html

![image](https://github.com/user-attachments/assets/7ffcc634-644a-4a3e-a8cb-ae272906f8f7)
![71e24f86-b9d5-45ba-982b-7c3bd914ff94](https://github.com/user-attachments/assets/f06a9a91-9654-433a-a9a4-5a84ba5b0c55)

[文件：合并发票pdf.pdf]

I encountered this problem when processing PDF format files. PDF package refers to a compressed file that integrates multiple PDFs into one PDF. The specific details can be found in the link I posted. Pymupdf seems to be unable to correctly parse this file and can only obtain cover information. Using Adobe Reader, you can see that it contains many files. Is there any good solution for this situation

### How to reproduce the bug

import pymupdf

doc = pymupdf.open(file_path)
page = doc.load_page(0)
text  =page.get_text()

### PyMuPDF version

1.24.11

### Operating system

Windows

### Python version

3.9

**Comment by 1339503169** [comment]
[合并发票pdf2.pdf](https://github.com/user-attachments/files/17452915/pdf2.pdf)

I previously uploaded the problem file, but for some unknown reason, it was not uploaded successfully. Here is the problem file you need

**Comment by 1339503169** [comment]
https://helpx.adobe.com/acrobat/using/component-files-pdf-portfolio.html

This is an explanatory document about PDF Portfolio in English

**Comment by JorjMcKie** [comment]
Thanks for providing the file.
This is no bug: PyMuPDF (MuPDF) does not support PDF portfolios and there are no plans to do so either.
You may want to discuss with the MuPDF team in [this](https://discord.gg/AwtN7GFv) Discord channel.
