### ISSUE TITLE
addHighlightAnnot function produces ellipses instead of rectangles

### ISSUE THREAD

**Issue by wangzehao1003** [pymupdf/PyMuPDF#3963]
### Description of the bug

Why highlight annotation are not  simple rectangles, but with rounded corners and both sides are curved. It looks not perfect and that interaction area have deeper colors.
![bug](https://github.com/user-attachments/assets/10391611-072a-4ea7-9b24-56c81fd10781)

### How to reproduce the bug

```python
highlight_rect = fitz.Rect(x0, y0, x1, y1)
highlight = page.add_highlight_annot(highlight_rect)

### PyMuPDF version

1.24.10

### Operating system

Windows

### Python version

3.9

**Comment by JorjMcKie** [comment]
You did not provide any reproducible data.
So, any reaction from my side inevitably contains some degree of guesswork.

That said: this is no bug!
* Highlight annotations **_do not deliver rectangles_** but have have curved left and right edges.
* Highlight annotations by default are created using blend mode "Multiply". This means the following:
![image](https://github.com/user-attachments/assets/473e3e1a-408f-44b6-80a1-743e42758adf)

As you see, the effect you are complaining about is a result of your color choice. It will not occur when you stay with the default color.
So choose a different color or experiment with different blend modes. Refer to [this](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples/test-blendmode) folder to get an impression.

**Comment by wangzehao1003** [comment]
Thanks for your reply. Is there any method that can make the highlight areas look like simple rectangles, like figure-2 I post below. Now I got figure-1 which is not satisfied.
![badcase](https://github.com/user-attachments/assets/e67b14fc-3f5a-433c-a862-233ca99c0207)
![goodcase](https://github.com/user-attachments/assets/46af414f-9a89-44ad-8086-de9aaf51512e)

**Comment by JorjMcKie** [comment]
You can do that - but not with highlight annotations! They are what they are.
Simply use `page.add_rect_annot()`. Then update the annotation by setting blending mode to "Multiply" - to achieve the behavior of highlighting.

If you want to add permanent rectangles (annotations can be removed), then use `page`.draw_rect(..., overlay=False)`. This will put the color **_behind_** other page content.

**Comment by wangzehao1003** [comment]
Now I got it by using `page.add_rect_annot()`  with "Multiply" mode.  Thanks a million.
