### ISSUE TITLE
When I rotate a page to 270 degrees and want to access it later from appending, any page rotated 270 is adding +1 to the index

### ISSUE THREAD

**Issue by Begimkins** [pymupdf/PyMuPDF#3965]
### Discussed in https://github.com/pymupdf/PyMuPDF/discussions/3964

<div type='discussions-op-text'>

<sup>Originally posted by **Begimkins** October 18, 2024</sup>
I have a Contents Appendix and whenever I rotate pages, export them and try to access those pages that are 270 degree rotation, the link is giving me the next page. 

For example:
Page 15 - rotated 270 
Page 16 - rotation 90 

If I press Page 15 from my Contents list, the link goes to page 16. 
if both page 15 and page 16 are rotated 270, it goes to page 17.

How do I fix that?</div>

**Comment by JorjMcKie** [comment]
I am going to close this issue, because for the time being it is correctly classified as a Discussions item.
Going to comment in the discussions post.

**Comment by Begimkins** [comment]
> I am going to close this issue, because for the time being it is correctly classified as a Discussions item. Going to comment in the discussions post.

Ok, thank you!
