### ISSUE TITLE
Will you plan to support the EPS

### ISSUE THREAD

**Issue by Pjumpod** [pymupdf/PyMuPDF#3968]
**Describe the solution you'd like**
I would like to have the pure python library can open the EPS file and export pages as picture.
also the function to read/write the metadata of EPS file.

**Additional information**
It should be very good if we can manage the EPS file with pure python, no GS, no Inkscape, no postscript.

**Comment by JorjMcKie** [comment]
No there are no plans to do this in any foreseeable future, sorry.
