### ISSUE TITLE
Customize Minimum Column Number in find_tables

### ISSUE THREAD

**Issue by lmX2015** [pymupdf/PyMuPDF#3987]
**Is your feature request related to a problem? Please describe.**

I recently had examples of tables with one column only in forms / FAQ types of document (see below for an example of such documents).

This still makes sense to have this data treated table as the cells help to properly split the text.

However it seems that this snippet is removing such tables, despite the cells being properly recognized.

``` python
    # PyMuPDF modification:
    # Remove tables without text or having only 1 column
    for i in range(len(tables) - 1, -1, -1):
        r = EMPTY_RECT()
        x1_vals = set()
        x0_vals = set()
        for c in tables[i]:
            r |= c
            x1_vals.add(c[2])
            x0_vals.add(c[0])
        if (
            len(x1_vals) < 2
            or len(x0_vals) < 2
            or white_spaces.issuperset(
                page.get_textbox(
                    r,
                    textpage=TEXTPAGE,
                )
            )
        ):
            del tables[I]
```

**Describe the solution you'd like**

Is it possible to make the minimum column / row an attribute of the TableFinder Settings?

**Describe alternatives you've considered**
Are there several options for how your request could be met?

I can make a PR for that if you are ok with the idea.

**Additional context**

Basic example
[Question.pdf](https://github.com/user-attachments/files/17496642/Question.pdf)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by JorjMcKie** [comment]
We have discussed this In our design team and unanimously determined that in any reasonable understanding of what is a table, the minimum numbers for columns and rows should both be two.

This especially coincides with a new, advanced table module under development which is much less dependent on vector graphic elements than the current one, but on the other hand needs reliable criteria for identifying text positions on the page as being table cell candidates.

In view of this I am sorry to refuse introducing flexibility in this respect.
