### ISSUE TITLE
Dropped wheel support for PyMuPDF v1.16.7 on Python 3.4

### ISSUE THREAD

**Issue by vanderGoes** [pymupdf/PyMuPDF#399]
When I run `pip install PyMuPDF`, I get this error:

`Command "/mnt/anaconda2/envs/py34/bin/python -u -c "import setuptools, tokenize;__file__='/mnt/tmp/pip-build-36kmrvut/PyMuPDF/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i5ppx1fl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /mnt/tmp/pip-build-36kmrvut/PyMuPDF/`

Similar to https://github.com/pymupdf/PyMuPDF/issues/262

Version 1.16.6 works fine. Did the latest release got a bug?

Environment: Jupyter with Python 3 on AWS EMR 5.24.0

**Comment by JorjMcKie** [comment]
Wheels for OSX and Linux platforms are built on Travis CI by ``cibuildwheel``, which in its current version supports Python 2.7 and Python 3.5 through 3.8 - **but apparently no longer Python 3.4!**
So you only have these options left:
1. stay with PyMuPDF 1.16.6
2. install later versions from source

... and of course upgrade your Python, which you probably should anyway some time this year 😉

**Comment by vanderGoes** [comment]
Thank you for your quick reply.

I'm working in Python 3.6.2. I've to check why the error indicates Python 3.4.
