### ISSUE TITLE
Extraction skipping every alternate line and also not extracting headers

### ISSUE THREAD

**Issue by chelsud123** [pymupdf/PyMuPDF#4017]
### Description of the bug

In the attached PDF, I am trying to extract the last table. PyMuPDF is extracting it, but skipping every alternate line and is also not extracting the column headers. The following items are attached:
1. Problem_document.pdf : The PDF from which the table has been extracted
2. Table_error.png : The erroneous extraction
[Problem_document.pdf](https://github.com/user-attachments/files/17619433/Problem_document.pdf)
![Table_error](https://github.com/user-attachments/assets/e266f898-67f2-4852-bdd9-b01957698162)

### How to reproduce the bug
```
import pymupdf
from IPython.display import display, Image

doc = pymupdf.open('Problem_document.pdf')
page = doc[idx]
tabs = page.find_tables(add_lines=None)
print(f"{len(tabs.tables)} found on page {idx}")
if tabs.tables:
   for idt in range(0, len(tabs.tables)):
       df_test = pd.DataFrame(tabs[idt].extract())
       display(df_test)
```
### PyMuPDF version

1.24.13

### Operating system

Windows

### Python version

3.9

**Comment by JorjMcKie** [comment]
Sorry for the delay.
We have checked out various settings and came to the result that the tables situation on this page as a whole and also the making of each single table cannot be (correctly) detected by the table finder.
You will have to develop own code which for instance adds information via the `add_lines` parameter to help the table finder.
