### ISSUE TITLE
PyMuPDF hangs when iterating over zero page PDF pages backwards

### ISSUE THREAD

**Issue by C-Saunders** [pymupdf/PyMuPDF#4018]
### Description of the bug

PyMuPDF is able to open this PDF, but hangs if I try to iterate over the pages backwards.

### How to reproduce the bug

[zero_pages.pdf](https://github.com/user-attachments/files/17619742/zero_pages.pdf)

```py
import pymupdf

pdf = pymupdf.open("...zero_pages.pdf")

# this raises ValueError: bad start page number
for page in pdf.pages():
    print(page.number)

# this hangs forever
for page in pdf.pages(-1, -1):
    print(page.number)
```

I've tried this on Mac and Linux, and with PyMuPDF versions 1.24.9 and 1.24.13

### PyMuPDF version

1.24.13

### Operating system

MacOS

### Python version

3.11

**Comment by julian-smith-artifex-com** [comment]
Fixed in PyMuPDF-1.24.14.
