### ISSUE TITLE
Parsing failure on old English PDFs

### ISSUE THREAD

**Issue by marko-polo-cheno** [pymupdf/PyMuPDF#4022]
### Description of the bug

<img width="328" alt="image" src="https://github.com/user-attachments/assets/34645f60-a204-4a24-ba8c-673391327781">

PyMuPDF in its most default configuration cannot parse this [PDF from Statistics Canada](https://www150.statcan.gc.ca/n1/en/pub/75-001-x/01101/5981-eng.pdf) using the `.get_text()` function.

The words `Average market income` parse into something unreadable!

### How to reproduce the bug

Download the PDF from the link above, and:
```
with pymupdf.open(pdf_path) as pdf:
    pymupdf_text = ""
    num_pages = 5
    for page_num, page in enumerate(pdf):
        pymupdf_text += page.get_text() + "\n"
text_output = pymupdf_text
```

### PyMuPDF version

1.24.13

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
This is not a bug or "parsing failure", but goes back to missing back-translation information from the font glyphs to their originating Unicodes.
There is no way to access the text other than using OCR. For an example that uses partial OCR in case of unreadable characters see [here](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/OCR/tesseract2.py).

**Comment by benjminus** [comment]
> This is not a bug or "parsing failure", but goes back to missing back-translation information from the font glyphs to their originating Unicodes. There is no way to access the text other than using OCR. For an example that uses partial OCR in case of unreadable characters see [here](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/OCR/tesseract2.py).

hi, @JorjMcKie , I'm many thank you for building this project, and I'm learning pymupdf. And now I got the same problem with Page.get_text, it result me some invalid chars. I have learn "fz_font" 3 days for this problem to resolve it. Is it seems unable to resolve ? I'm not understand `missing back-translation information` indicate what?
many thanks again for your reply..

**Comment by JorjMcKie** [comment]
1. The visual, readable text on a PDF page may not be text at all - in the technical sense! It could be
   - just pixels inside an image
   - vector graphics "simulating" text, for example the letter "D" can be simulated by a vertical line "|" and a left-open semicircle. Or "A" = `"/"`, `"-"`, `"\"` = `/-\`. I hope you see the argument.
   - both types of "text" cannot be extracted, you must use OCR.
2. If text is indeed text in a technical sense, then still what you see are **_not_** directly the letters but graphical representations of them, so-called glyphs (which are implemented as small vector graphics). The font contains small graphic programs which produce the visual appearance of each glyph. Writing text using a font goes roughly down to telling the font: "use glyph number 4711 and draw at this position with this scaling factor".
   - There is no need for the font to know which Unicode number (e.g. 65 for character "A") it is currently reproducing when executing glyph program 4711. A font **_may_** contain a backtranslation table (which **_may_** contain value 65 for key 4711 ... or not), but there is no such obligation.
   - Many fonts have no `/ToUnicode` table (or equivalent information) at all, and yet others do but it may be incomplete.
   - Successful text extraction only works if this type of information is **_present and complete_**. In all other cases, we must use OCR.

**Comment by benjminus** [comment]
completely understand, thanks again!!!
