### ISSUE TITLE
page.getImageBbox Exception

### ISSUE THREAD

**Issue by mzw2018** [pymupdf/PyMuPDF#405]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
when running function page.getImageBbox(), I get a Exception which is 'str() takes at most 1 argument (2 given)'

## Expected behavior (optional)
In fact, I modifies ”fitz/utils.py” , and the problem has been solved.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/42856096/69028713-c853a900-0a0d-11ea-8f21-99dcdcc01639.png)

## Your configuration (mandatory)
 - Operating system: win10
 - Python version: python2.7
 - PyMuPDF version: 1.16.7

**Comment by JorjMcKie** [comment]
Confirmed. Thanks for submitting this.
Will be fixed in next version.
The correct formulation should be ``imgnm = ("/" + imgname).encode()`` which works in Py2 and Py3.

**Comment by mzw2018** [comment]
Thanks for your quick response.

**Comment by mzw2018** [comment]
Thanks for your quick response.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jorj X. McKie"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 下午4:05
收件人: "pymupdf/PyMuPDF"<PyMuPDF@noreply.github.com&gt;; 
抄送: "毛志伟"<982503758@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pymupdf/PyMuPDF] page.getImageBbox Exception (#405)




Confirmed. Thanks for submitting this.
 Will be fixed in next version.
 The correct formulation should be imgnm = ("/" + imgname).encode() which works in Py2 and Py3.

**Comment by JorjMcKie** [comment]
solved by v1.16.8
