### ISSUE TITLE
Question / Comment: Is it possible to use REGEX with searchFor

### ISSUE THREAD

**Issue by Quentin-Piot** [pymupdf/PyMuPDF#406]
Hello,

I'm still a beginner in python and I wanted to know if there is a way to use REGEX for the searchFor() method because I need it for a project ?
Thanks by advance.

**Comment by JorjMcKie** [comment]
Sorry, no that will not work, only strings are accepted.
Depending on your exact requirements. you may want to look at the text extraction method's ``Page.getText(opt)`` variants. For opt = "dict", "blocks", "words" you will get results with position information down to text spans, blocks or single words ...

**Comment by Quentin-Piot** [comment]
Thank your for your fast answer, I'll look at it. Very nice framework tho !
