### ISSUE TITLE
[A World of Propensities by Karl Popper (1997).pdf](https://github.com/user-attachments/files/17758342/A.World.of.Propensities.by.Karl.Popper.1997.pdf)

### ISSUE THREAD

**Issue by brucenielson** [pymupdf/PyMuPDF#4060]
I got the 'repeating word' error to replicate in Google Colab. The previous bug report got closed due to not being able to replicate. But you should now be able to easily replicate it. See:

https://colab.research.google.com/drive/1d3BCUI5PyV928PcJwmnx_RkvWGHGJGC9?usp=sharing

Just to be sure, here is the document again that I'm using. [A World of Propensities by Karl Popper (1997).pdf](https://github.com/user-attachments/files/17790911/A.World.of.Propensities.by.Karl.Popper.1997.pdf)

Drop that into the Colab and run the simple code and you can see from the results already saved that it creates the repeating "It" word in the section I previously reported. We should now be able to replicate this bug in Colab.

_Originally posted by @brucenielson in https://github.com/pymupdf/PyMuPDF/issues/4042#issuecomment-2477485378_

**Comment by brucenielson** [comment]
Example of bug in Colab:


print(md)
###### A WORLD OF PROPENSITIES Karl R. Popper

The two lectures presented here belong to Popper's late work, most
of which is still unpublished. The first introduces a new view of
causality, based on Popper's interpretation of quantum theory yet
freed of all difficulty. It is a new and encouraging view of the universe.
a view that easily merges with the commonsense view that our will is
free. The second lecture gives a glimpse of human knowledge as it
evolves from animal knowledge.

_/tom the PREFACE_
_I am of course not certain whether the two lectures which I_
_here submit to the patient perusal or the possible refusal of_
_my readers are, as I hope, the best I have produced so far,_
_nor is this question, I admit, of any importance. But I wish to_
_convey to my readers that I have worked hard to make them_
_the best, since I myself have, in writing them, been able to_
_learn things of great importance to myself._

**ISBN 1 85506 000 0**
**£5 99 U**


### KARLR.
# POPPER
## A WORLD Of PROPENSITIES


-----

Published in 1995 by

Thoemmes Press
11 Great George Street
Bristol BSl 5RR
England

© 1990 by Karl R. Popper

**_First published in 1990_**
5
**_Reprinted 199_**

ISBN 1 85506 000 0

All rights reserved. No part of this publication may
be reproduced, stored in a retrieval system, or
transmitted in any way or by any means, electronic,
mechanical, photocopying, recording or otherwise,
without the written permission of the copyright
holder, application for which should be addressed
to the publisher.

**Printed in England by Hobbs the Printers Ltd., Southampton SO40 3YS**


###### Dedicated to the memory of my dear wife, Hennie


-----

##### Preface

**I am of course not certain whether the two lectures which**
**I here submit to the patient perusal or the possible refusal of**
**my readers are, as I hope, the best I have produced so far;**
**nor is this question, I admit, of any importance. But I wish**
**to convey to my readers that I have worked hard to make**
**them the best, since I myself have, in writing them, been**
**able to learn things of great importance to myself.**

**I am grateful to have been able to do this in my 87th and**
**88th year, despite the drawbacks of failing memory.**

**A shorter version of the first lecture was given on August**
**24th, 1988 before the World Congress of Philosophy at**
**Brighton, under the chairmanship of Professor Richard**
**Hare. A shorter version of the second lecture was given on**
**June 9th, 1989 before the Alumni of the School at the**
**London School of Economics, under the chairmanship of its**
**Director, Dr I.G. Patel.**

**I never should have been able to write either of these**
**lectures without the help of my Assistant, Melitta Mew.**


-----

###### Contents

Preface ...................................... vu

A World of Propensities:
Two New Views of Causality .................... 1

Towards an Evolutionary
Theory of Knowledge . . . . . . . . . . . . . . . . . . . . . . . . . . 2 7


-----

#### A World of Propensities: Two New Views of Causality


-----

Ladies and Gentlemen,

I shall begin with some personal memories and a personal
confession of faith, and only then turn to the topic of my
lecture.

It
was 54 years ago, in Prague in August 1934, that I first
...
I came to Prague with the corrected page proofs of my book,
It
_Logik der Forschung._ was published three months later in
Vienna, and in English 25 years later as The Logic of Scientific
_Discovery._ ...
Tarski and Godel arrived, independently at almost the same
It
time. was first published by Tarski in 1930, whereupon
It
Godel, of course, accepted Tarski's priority. is a theory of

**Comment by brucenielson** [comment]
I created this ticket out of the previous one so I thought it would put it in the right queue. But it looks like maybe it didn't. This is already known to be a problem with PyMUPDF4LLM, not PyMu.

**Comment by JorjMcKie** [comment]
I have also worked on this in the meantime. Really a weird phenomenon.
You are right: it is a problem happening in PyMuPDF4LLM - there is no issue in PyMuPDF - my transfer of the problem to here was wrong.

So I am going to close the bug here again, and open a new issue on the4llm repo.

**Comment by brucenielson** [comment]
Give me the link to that issue and I'll track it there.

**Comment by brucenielson** [comment]
Can we please delete out the pdf from the issue once you have it downloaded to work with?
