### ISSUE TITLE
Annot.setOpacity trouble 

### ISSUE THREAD

**Issue by PCarle** [pymupdf/PyMuPDF#407]
New version of PyMuPdf (1.16.1) seems to have a trouble on the code below (inspired from pymupdf doc for Collection of recipes part Annotations) the generated pdf is correct, the generated image is wrong: annotation with opacity != 1. is missing in image.
<pre>
from __future__ import print_function
import sys
print("Python", sys.version, "on", sys.platform, "\n")
import fitz
print(fitz.__doc__, "\n")

import os
print (os.getcwd())

def print_descr(rect, annot):
    """Print a short description to the right of an annot rect."""
    annot.parent.insertText(rect.br + (10, 0),
                    "'%s' annotation" % annot.type[1], color = red)

red    = (1, 0, 0)
blue   = (0, 0, 1)
gold   = (1, 1, 0)
colors = {"stroke": blue, "fill": gold}
colors2 = {"fill": blue, "stroke": gold}
border = {"width": 0.3, "dashes": [2]}
displ = fitz.Rect(0, 50, 0, 50)
r = fitz.Rect(50, 100, 220, 135)

doc = fitz.open()
page1 = doc.newPage()

annot = page1.addPolygonAnnot([r.bl, r.tr, r.br, r.tl])
annot.setOpacity(0.5)
annot.setBorder(border)
annot.setColors(colors2)
annot.update()
print_descr(annot.rect, annot)
print("added 'Polygon'")

pix=page1.getPixmap(alpha=True,annots=True)

doc.save("test-annots.pdf")
pix.writePNG("test-annots.png")
pix.writeImage("test-annots.psd","psd")

doc.close()
</pre>

produce in png file :
![image](https://user-images.githubusercontent.com/16350743/69352184-c2afca80-0c7c-11ea-9f8b-6a3c6b6ff9d2.png)
if i comment line a:
<pre>
     annot.setOpacity(0.5)
</pre>
the script produce 
![image](https://user-images.githubusercontent.com/16350743/69352297-fc80d100-0c7c-11ea-8ba4-d43e945a72a3.png)
I do a second test if i save document, reopen it and extract page pixmap, annotation is correct in the regenerated png(with opacity=0.5).

**Comment by JorjMcKie** [comment]
cannot reproduce your issue on my v1.16.8, Win 10, Python 3.7 64bit. Your script delivers these PNG (left is alpha=0, right is alpha=1):
![grafik](https://user-images.githubusercontent.com/8290722/69361093-1eb92580-0c62-11ea-81b3-22b72c07bb4e.png)

**Comment by JorjMcKie** [comment]
Ahh, now I see what you are pointing to:
You need to reload the page before making pixmaps, so that links, annots, widget are refreshed, e.g. like this:

```python 
pno = page1.number
page1 = None
page1 = doc[pno]
```
The everything works.
I remember that i did not include a programmatic page refresh after each annotation, link or widget update.
I guess I should mention this behaviour more prominently in the doc, and maybe also add a little method to more easily do this ... ``page.refresh()`` or something.

**Comment by PCarle** [comment]
I truy on window 7 

with:
print("Python", sys.version, "on", sys.platform, "\n")
<pre>
PyMuPDF 1.16.8: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-11-18 18:12:19.
Built for Python 3.7 on win32 (64-bit).
 </pre>

and the scrpit  (bellow) don't works for Me
<pre> 
from __future__ import print_function
import sys
print("Python", sys.version, "on", sys.platform, "\n")
import fitz
print(fitz.__doc__, "\n")

import os
print (os.getcwd())


def print_descr(rect, annot):
    """Print a short description to the right of an annot rect."""
    annot.parent.insertText(rect.br + (10, 0),
                    "'%s' annotation" % annot.type[1], color = red)

red    = (1, 0, 0)
blue   = (0, 0, 1)
gold   = (1, 1, 0)
colors = {"stroke": blue, "fill": gold}
colors2 = {"fill": blue, "stroke": gold}
border = {"width": 0.3, "dashes": [2]}
displ = fitz.Rect(0, 50, 0, 50)
r = fitz.Rect(50, 100, 220, 135)

doc = fitz.open()
page1 = doc.newPage()

annot = page1.addPolygonAnnot([r.bl, r.tr, r.br, r.tl])
annot.setOpacity(0.5)
annot.setBorder(border)
annot.setColors(colors2)
annot.update()
print_descr(annot.rect, annot)
print("added 'Polygon'")

page=None
page=doc[0]
pix=page1.getPixmap(annots=True)

doc.save("test-annots.pdf")
pix.writePNG("test-annots.png")


doc.close()
</pre>
the .png is like this :
![image](https://user-images.githubusercontent.com/16350743/69425848-00b7f780-0d2c-11ea-9feb-6634afc6e1a3.png)


my results files:
[test-annots.pdf](https://github.com/pymupdf/PyMuPDF/files/3879477/test-annots.pdf)
![test-annots](https://user-images.githubusercontent.com/16350743/69425916-234a1080-0d2c-11ea-87da-4b81cbbb0ad1.png)

**Comment by JorjMcKie** [comment]
I have been digging a bit more.
You were right: it only happens with **newly created annotations with an opacity set smaller than 1.**

I have already implemented this "refresh" method, and it will work as described. It's advantage over the dirty fix described above is that it requires no page reloading.
But there remains a corner where I am still struggling:

* after ``page.refresh()``, the pixmap of the **page** correctly shows the opaque annotation
* but the pixmap of the annot still shows nothing 😒

**Comment by JorjMcKie** [comment]
I believe you made an error:
you're resetting ``page`` instead of ``page1``

**Comment by JorjMcKie** [comment]
Okay, found a solution. I will publish this with the next version. I presume thesume there is no particular hurry?
Otherwise please drop me a note.

**Comment by PCarle** [comment]
No problem i use the "PyMuPDF==1.13.20" version ... and annotations accepts setOpacity  and page give correct pixmap in this version

**Comment by JorjMcKie** [comment]
Just uploaded v1.16.9 which fixes this.
