### ISSUE TITLE
Washed colors when exporting CMYK images

### ISSUE THREAD

**Issue by DawidIzydor** [pymupdf/PyMuPDF#4070]
### Description of the bug

I have a PDF that contains some images in RGP format and some in CMYK format. RGB images are getting exported fine, however, CMYK when exported directly have inverted colors and after inverting them again look washed.

Below a screenshot of what I mean by that (the image is also mirrored but I can live with that). Mask is applied correctly, just the colors look off

![obraz](https://github.com/user-attachments/assets/38832f72-6eb6-4aa3-88c0-79ec60360219)
![obraz](https://github.com/user-attachments/assets/b360357d-a4bf-427e-89d3-d34dd35f13e1)

Below is the script I'm using:
```python
    # Extract and save the images
    for i, img in enumerate(image_list):
        xref = img[0]
        smask = img[1]
        base_image = pdf_document.extract_image(xref)

        pix1 = fitz.Pixmap(base_image["image"])
        if pix1.colorspace.n == 4:
            print(f"Changing colorspace CMYK to RGB")
            pix1 = fitz.Pixmap(fitz.csRGB, pix1)
            pix1.invert_irect()
            
        try:
            mask = fitz.Pixmap(pdf_document.extract_image(smask)["image"])
            pix = fitz.Pixmap(pix1, mask)  # Combine image with mask
            print(f"Mask found and applied for image {i + 1}")
        except:
            pix = pix1  # Use the base image without mask
            print(f"Mask not found for image {i + 1}, saving without mask")

        
        # Prepend the page number to the image filename
        
        image_filename = os.path.join(output_folder, f"{page_number + 1}_image_{i + 1}.png")
        
        pix.save(image_filename)
```

### How to reproduce the bug

Extract a CMYK image from a Paizo's PDF

### PyMuPDF version

1.24.9

### Operating system

Windows

### Python version

3.10

**Comment by JorjMcKie** [comment]
Please provide the PDF page original.

**Comment by JorjMcKie** [comment]
Please be aware that we cannot deal with this issue without an example file / page and we will close it as "won't fix" on the 28th of November.

**Comment by JorjMcKie** [comment]
Closed for lack of reproducible data.
Please feel free to open again with a reproducing file.
