### ISSUE TITLE
the document.is_pdf is True but get_text() method freezes

### ISSUE THREAD

**Issue by Changeyuy** [pymupdf/PyMuPDF#4075]
### Description of the bug

When I use the page.get_text() method, the python process freezes  and the document.is_pdf is True. 

### How to reproduce the bug

the original PDF file of 50MB cannot be uploaded to GitHub. Is there any way to upload this PDF attachment?

### PyMuPDF version

1.24.14

### Operating system

Linux

### Python version

3.12

**Comment by JorjMcKie** [comment]
You can send the file via e-mail to me if you like.
Did you look at details like which pages are causing the problem? Long response times may appear like loops, so include print statements after every successful page, etc.

**Comment by Changeyuy** [comment]
This is a PDF file that is corrupted on Windows but can be partially opened on Mac. It is only one page。Thank you very much for your reply  I will send to your email soon

**Comment by Changeyuy** [comment]
> I have sent a mail. hope you have received it

**Comment by JorjMcKie** [comment]
Thanks for the file. I tried to open with a range of viewers:
* evince (Linux): cannot open (loops forever)
* Adobe Acrobat (Windows): opens after 5 minutes messaging some errors thereafter
* Foxit Reader (Windows): opens after a long time
* PDF XChange viewer: cannot open
* Nitro PDF: cannot open
* MuPDF / SumatraPDF: cannot open
* Firefox (Linux): opens after a long time
* MS Edge: cannot open (apparently loops)

**Comment by Changeyuy** [comment]
Thanks your reply. I just would like to know if there is any way to avoid the process from hanging when dealing with this kind of file by pymupdf？

**Comment by JorjMcKie** [comment]
The problem with this file is its **_absolutely crazy_** amount of optional content information:

* 786'432 Optional Content Groups
* making the catalog object very, very, **_very!!!_** large, because all the OCG objects are enumerated there 4 times
* this makes at least 3 million object references in the PDF catalog alone
* the total number of objects in the file is around 2.4 million

I tried the following script successfully. It simply (temporarily) deletes all optional content information, which makes everything visible unconditionally:
```python
import pymupdf

doc = pymupdf.open("lock.pdf")
cat = doc.pdf_catalog()  # access the PDF catalog xref
# disable all optional content info
doc.xref_set_key(cat, "OCProperties", "null")

# NOW load the page (not earlier!)
page = doc[0]

# this now works
print(page.get_text())
```

This script counts the number of Optional Content Groups:
```python
import pymupdf

doc = pymupdf.open("lock.pdf")
oc = 0
xreflen = doc.xref_length()
for xref in range(1, xreflen):
    otype = doc.xref_get_key(xref, "Type")
    if otype[1] == "/OCG":
        oc += 1
print(f"OCG count {oc}, total xrefs: {xreflen}")
```
Honestly, I am hesitating to accept this as a bug because the file is made in a way that cannot be called reasonable any longer.
Under these circumstances, there even is no way to say that the a program freezes (loops) because it might as well be, that it just takes very long to digest all that nonsense.

**Comment by Changeyuy** [comment]
> optional content information
Thank you very much for taking so much time to deal with this issue. I also thought it was a crazy file.I had been working on multiple processes for almost a day but didn't extract the contents, so I raised the issue. By the way, I would like to ask what optional content information means

**Comment by JorjMcKie** [comment]
The complete background information can of course be found in the official PDF spec manual(s). But in short, this is the meaning:
* PDF creators have the option to define **_conditions_**, under which certain parts of the pages are shown.
* These "conditions" are implemented as so-called Optional Content Groups. These or certain PDF object types (`/Type /OCG`) which can carry a state: either "ON" or "OFF".
* Text, images, vector graphics and other objects appearing on a page (`/Type /Page`) can be enriched with the cross reference number ("xref") of an OCG. For instance, if an image definition in the PDF also carries the xref of an OCG, then the display of that image will only happen if this OCG has a status of ON.
* PDF viewers (and also PyMuPDF/MuPDF) react to these OCG states and do not show (or extract) text having an OCG that is OFF.
* Advanced viewers have menu options, where OCGs (also called "layers") can be switched ON/OFF.
* This feature is often used with CAD/CAM documents to suppress or include technical details etc. Other uses include different visibility versions depending on whether the page is printed or displayed.

In your example of a 1-page PDF I just cannot imagine, how a meaningful use of almost 800 thousand layers / OCGs could potentially look like.

**Comment by Changeyuy** [comment]
Thank you very much for explaining the problem with me An excellent journey to discuss issues with you

**Comment by JorjMcKie** [comment]
As I demonstrated above, there are ways to show (or make plausible) that this is a crazy PDF. But I fail to see how this can be turned into a general criterion to decide not to try working with it.

For the time being, I am therefore going to close this issue with the "won't fix" flag.
Please do not hesitate to re-open it whenever you have new insights.
