### ISSUE TITLE
'Rect' object has no attribute 'contains'

### ISSUE THREAD

**Issue by boan-anbo** [pymupdf/PyMuPDF#408]
Hi there.

I was trying to detect rect area of highlight passages and switch to hand cursor when hovering over them. I did:
1. get the current page's 'annots'.
2. get the rect object of the first annotation with 'i = list(annots)[0].rect'
3. when I called 'i.contains(cursor_position)', it says 'Rect' object has no attribute 'contains'. I tested other attributes such as .getArea(), it works fine.

What am I doing wrong?

Thanks in advance.

**Comment by boan-anbo** [comment]
Nevermind, I figured it out! The class is .__contains__(), not .contains(), as stated in https://pymupdf.readthedocs.io/en/latest/rect/#Rect.contains 
Thx anyways.

**Comment by JorjMcKie** [comment]
Thanks for raising this - I need to correct the documentation.
