### ISSUE TITLE
Create uniformly spaced character cells in a text widget based on "text_maxlen"

### ISSUE THREAD

**Issue by k3vob** [pymupdf/PyMuPDF#4080]
In PDF forms/widgets, it is possible to create a text box which is split into some number of cells, each containing one character. This is used when a PDF has an array of boxes which require one character in each box.

Here is an example of adding such a text form field on [pdffiller.com](https://www.pdffiller.com):

![CleanShot 2024-11-22 at 12 56 38@2x](https://github.com/user-attachments/assets/bd4d543b-3a22-44ae-bab4-01f93da17306)

I would like the option to create a text widget with `widget.text_maxlen` number of cells, all equally spaced to the width of the widget `rect`.

Is this possible in any way currently? Or else, could this functionality be added please?

**Comment by JorjMcKie** [comment]
This cannot be achieved currently. There also are no plans to do this. Can you attach a simple example here, so I can take a look?

**Comment by k3vob** [comment]
Here is an example: [sample.pdf](https://github.com/user-attachments/files/17897432/sample.pdf).

Also, it seems like this is only supported on some PDF editors. On MacOS's default Preview app, the letters aren't spaced out correctly, but with Chrome's native PDF editor, the letter are correctly spaced.

Preview:
![preview](https://github.com/user-attachments/assets/4860bdae-b7db-43fa-9177-f264545c7649)

Chrome:
![chrome](https://github.com/user-attachments/assets/fac70ef6-3e6e-420a-bb29-238241ec83e4)

**Comment by JorjMcKie** [comment]
Thanks for the example.
Actually, the whole should be supported already: all you have to do is setting the field flags accordingly, namely:
![image](https://github.com/user-attachments/assets/ed7980a0-2f6e-45ad-a023-e5e500fc6d10)

**Comment by k3vob** [comment]
This worked perfectly, thank you!
