### ISSUE TITLE
pymupdf.Rect.round()

### ISSUE THREAD

**Issue by tenghian** [pymupdf/PyMuPDF#4082]
### Description of the bug

round
533.9301147460938 -> 533
534.147216796875 -> 535

![2024-11-23_15-13-23](https://github.com/user-attachments/assets/ce459974-cc5d-43f7-8a46-057b1b6f4858)

pymupdf 1.24.14
python 3.13
Windows 10

### How to reproduce the bug

`print(pymupdf.Rect((42.58039855957031, 533.9301147460938, 127.0392837524414, 542.086181640625)).round())
IRect(42, 533, 128, 543)

print(pymupdf.Rect((42.58039855957031, 523.4177856445312, 182.61207580566406, 534.147216796875)).round())
IRect(42, 523, 183, 535)
`

### PyMuPDF version

1.24.14

### Operating system

Windows

### Python version

3.13

**Comment by JorjMcKie** [comment]
This works as intended and is no bug! Please see [here](https://pymupdf.readthedocs.io/en/latest/rect.html#Rect.round).

**Comment by tenghian** [comment]
print(round(533.9301147460938))
print(round(534.147216796875))
correct value is:
534
534

**Comment by JorjMcKie** [comment]
> print(round(533.9301147460938)) print(round(534.147216796875)) correct value is: 534 534

Why don't you read the documentation that I provided under the link?
Rectangle method `.round()` **_does not do arithmetic rounding for a purpose!_**
* The top coordinate y0 is taken to be the largest integer <= original value. Therefore ` 533.9301147460938 ==> 533`. More or less equal to `math.floor` result.
* The bottom y1 is the smallest integer >= original value. Therefore `542.086181640625 ==> 543`. Roughly equal to `math.ceil`.
