### ISSUE TITLE
Memory leak on page.get_text('rawdict') for version 1.24.13

### ISSUE THREAD

**Issue by HuJianE** [pymupdf/PyMuPDF#4089]
### Description of the bug

I was Using a Linux and getting a suspect memory leak for that api in multithread env, but for apple Mac silicon it seems to be fine
System Info:
  PRETTY_NAME="Ubuntu 22.04.3 LTS"
  NAME="Ubuntu"
  VERSION_ID="22.04"
  VERSION="22.04.3 LTS (Jammy Jellyfish)"
  VERSION_CODENAME=jammy
  ID=ubuntu
  ID_LIKE=debian
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  UBUNTU_CODENAME=jammy
  Python 3.9.x
`
# coding: utf-8
# Created by hujian on 2024/1/26 14:08
#
import gc
import time
from concurrent.futures import ThreadPoolExecutor
import sys
import os
import fitz

executor = ThreadPoolExecutor(max_workers=30)
all_futures = []
files = ['/root/hujian/memray_files/response_1732171853904.pdf',
         '/root/hujian/memray_files/response_1732171673563.pdf',
         '/root/hujian/memray_files/response_1732171501004.pdf',
         '/root/hujian/memray_files/response_1732170627303.pdf',
         '/root/hujian/memray_files/response_1732171393720.pdf']
# for i in range(200):
#     future = executor.submit(process_file, '/root/hujian/memray_files/response_1732171673563.pdf')
#     # future = executor.submit(process_file, '/Users/hujian/Downloads/upload_pdf/response_1732171673563.pdf')
#     all_futures.append(future)
def get_merge_raw_dict_by_page_from_pdf_obj(temp_file_path):
    """
    @param if_include_shape:
    @param uuid:
    @param temp_file_path:
    """
    pdf_obj = None
    raw_dict_by_page = {}
    with fitz.open(temp_file_path) as pdf_obj:
        # pdf_obj = fitz.open(temp_file_path)
        for pid, one_page in enumerate(pdf_obj, start=1):
            # logger.info(f"{uuid}:running into get_text('rawdict') for page == {pid}")
            one_page_start_time = time.time()
            raw_dict_by_page[pid] = one_page.get_text('rawdict')
            one_page_end_time = time.time()
            rotation = one_page.rotation
            directions = {
                0: (1.0, 0.0),  # 如果页面没有旋转
                90: (0.0, -1.0),  # 如果页面向右旋转了90度
                180: (-1.0, 0.0),  # 如果页面向右旋转了180度
                270: (0.0, 1.0),  # 如果页面向右旋转了270度
            }
            horizontal_dir = directions[rotation]
            one_page_cost_time = one_page_end_time - one_page_start_time

            remove_pic_idx = []
            # add text object
            for block_idx, one_block in enumerate(raw_dict_by_page[pid]['blocks']):
                line_text_list = []
                one_block['uuid'] = f'{pid}_{block_idx}'
                if one_block['type'] != 0 :
                    remove_pic_idx.append(block_idx)
                    continue
                if one_block['type'] == 0: # 也记录方向不对的block，准备删除
                    for line_idx, one_line in enumerate(one_block['lines']):
                        # if one_line['dir'] not in [(1.0,0.0),(0.0,1.0)]:
                        if one_line['dir'] not in [horizontal_dir,(1.0,0.0)]:
                            remove_pic_idx.append(block_idx)
                            continue
                for line_idx, one_line in enumerate(one_block['lines']):
                    span_text_list = []
                    for span_idx, one_span in enumerate(one_line['spans']):
                        one_span_txt = ''.join(one_char['c'] for one_char in one_span['chars'])
                        span_text_list.append(one_span_txt)
                        one_span['text'] = one_span_txt
                        one_span['uuid'] = f'{pid}_{block_idx}_{line_idx}_{span_idx}'
                    one_line_text = ''.join(span_text_list)
                    line_text_list.append(one_line_text)
                    one_line['text'] = one_line_text
                    one_line['uuid'] = f'{pid}_{block_idx}_{line_idx}'
                one_block_text = '\n'.join(line_text_list)
                one_block['text'] = one_block_text
            raw_dict_by_page[pid]['blocks'] = [one_block for idx, one_block in enumerate(raw_dict_by_page[pid]['blocks']) if idx not in remove_pic_idx]

    return raw_dict_by_page

for file in files:
    for i in range(50):
        future = executor.submit(get_merge_raw_dict_by_page_from_pdf_obj,file)
        all_futures.append(future)
for future in all_futures:
    future.result()

gc.collect()
executor.shutdown(wait=True)
time.sleep(120)

`
For files, my test file is a scan PDF or called one picture one page PDF, and this could be easily found.
This is tested OK in single thread, but when in multi-thread, the memory is going up steady.
![20241127-172129](https://github.com/user-attachments/assets/92270a25-5156-4926-96a7-94b97ff9deb0)

### How to reproduce the bug

# coding: utf-8
# Created by hujian on 2024/1/26 14:08
#
import gc
import time
from concurrent.futures import ThreadPoolExecutor
import sys
import os
import fitz

executor = ThreadPoolExecutor(max_workers=30)
all_futures = []
files = ['/root/hujian/memray_files/response_1732171853904.pdf',
         '/root/hujian/memray_files/response_1732171673563.pdf',
         '/root/hujian/memray_files/response_1732171501004.pdf',
         '/root/hujian/memray_files/response_1732170627303.pdf',
         '/root/hujian/memray_files/response_1732171393720.pdf']
# for i in range(200):
#     future = executor.submit(process_file, '/root/hujian/memray_files/response_1732171673563.pdf')
#     # future = executor.submit(process_file, '/Users/hujian/Downloads/upload_pdf/response_1732171673563.pdf')
#     all_futures.append(future)
def get_merge_raw_dict_by_page_from_pdf_obj(temp_file_path):
    """
    @param if_include_shape:
    @param uuid:
    @param temp_file_path:
    """
    pdf_obj = None
    raw_dict_by_page = {}
    with fitz.open(temp_file_path) as pdf_obj:
        # pdf_obj = fitz.open(temp_file_path)
        for pid, one_page in enumerate(pdf_obj, start=1):
            # logger.info(f"{uuid}:running into get_text('rawdict') for page == {pid}")
            one_page_start_time = time.time()
            raw_dict_by_page[pid] = one_page.get_text('rawdict')
            one_page_end_time = time.time()
            rotation = one_page.rotation
            directions = {
                0: (1.0, 0.0),  # 如果页面没有旋转
                90: (0.0, -1.0),  # 如果页面向右旋转了90度
                180: (-1.0, 0.0),  # 如果页面向右旋转了180度
                270: (0.0, 1.0),  # 如果页面向右旋转了270度
            }
            horizontal_dir = directions[rotation]
            one_page_cost_time = one_page_end_time - one_page_start_time

            remove_pic_idx = []
            # add text object
            for block_idx, one_block in enumerate(raw_dict_by_page[pid]['blocks']):
                line_text_list = []
                one_block['uuid'] = f'{pid}_{block_idx}'
                if one_block['type'] != 0 :
                    remove_pic_idx.append(block_idx)
                    continue
                if one_block['type'] == 0: # 也记录方向不对的block，准备删除
                    for line_idx, one_line in enumerate(one_block['lines']):
                        # if one_line['dir'] not in [(1.0,0.0),(0.0,1.0)]:
                        if one_line['dir'] not in [horizontal_dir,(1.0,0.0)]:
                            remove_pic_idx.append(block_idx)
                            continue
                for line_idx, one_line in enumerate(one_block['lines']):
                    span_text_list = []
                    for span_idx, one_span in enumerate(one_line['spans']):
                        one_span_txt = ''.join(one_char['c'] for one_char in one_span['chars'])
                        span_text_list.append(one_span_txt)
                        one_span['text'] = one_span_txt
                        one_span['uuid'] = f'{pid}_{block_idx}_{line_idx}_{span_idx}'
                    one_line_text = ''.join(span_text_list)
                    line_text_list.append(one_line_text)
                    one_line['text'] = one_line_text
                    one_line['uuid'] = f'{pid}_{block_idx}_{line_idx}'
                one_block_text = '\n'.join(line_text_list)
                one_block['text'] = one_block_text
            raw_dict_by_page[pid]['blocks'] = [one_block for idx, one_block in enumerate(raw_dict_by_page[pid]['blocks']) if idx not in remove_pic_idx]

    return raw_dict_by_page

for file in files:
    for i in range(50):
        future = executor.submit(get_merge_raw_dict_by_page_from_pdf_obj,file)
        all_futures.append(future)
for future in all_futures:
    future.result()

gc.collect()
executor.shutdown(wait=True)
time.sleep(120)
`
`

### PyMuPDF version

1.24.13

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
Do not use PyMuPDF in a multithread environment as it does not support Python threading - see documentation.
Please feel free to open a new issue when observing this in a single-threaded setup.
