### ISSUE TITLE
Question: best practice inserting general utf-8 text

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#409]
Suppose I have some utf-8 text which is user-supplied (like their name) which I want to paste  into a pdf file.

I'm currently thinking something like this:
```python
txt = "我爱你"
txt = "çèéêëìí"
txt = "ทดสอบภาษาไทย"
fontname = None
try:
    tmp = txt.encode("Latin-1")
    fontname = "Helvetica"
except UnicodeEncodeError:
    pass
try:
    tmp = txt.encode("gb2312")
    fontname = "china-ss"
except UnicodeEncodeError:
    pass
if not fontname:
    raise ValueError("Don't know how to write name {} into PDF".format(txt))
....
page.insertTextbox(rect, txt, fontname=fontname,
            fontfile=None, ...)
```

~~But of course there are things other than Chinese and latin-1!~~  [updated code with something a bit more reasonable: a cascading set of attempts to encode].

Is there any best practice here?  Let's suppose I want only PDF Base 14 and built-in CJK for now.

**Comment by JorjMcKie** [comment]
I would use another package with the ability to guess the language. I have seen (but not tested) [guess-language](https://pypi.org/project/guess_language-spirit/), [polyglot](https://polyglot.readthedocs.io/en/latest/), [langdetect](https://pypi.org/project/langdetect/), [langid](https://pypi.org/project/langid/).
Polyglot and langdetect look quite good.
I am sure there are more packages out there.

These packages mostly also return the probability of the guess and the ISO language code (which I will be using in PyMuPDF sooner or later).
You would probably also want to include options like mono, serifed, italic, bold for font fine selection.

> As you can see e.g. in #398, PyMuPDF still has a gap to adequately support "all" languages. While there is no problem to accept any font given as a file, that issue is bringing up the inability to combine certain successive unicode characters (2 or even 3 in some cases) into **_one_** glyph for a language like Nepali. Instead, the generated text in the PDF appears with 2, resp. 3 separate glyphs. The basic reason for this is that PyMuPDF knows nothing about natural languages and thus doesn't tell MuPDF. My plan is to heal this some time and offer a language parameter ...

**Comment by JorjMcKie** [comment]
Anything else I can help you with?

**Comment by cbm755** [comment]
Thanks for the tip, I'll look into those languages detection packages
