### ISSUE TITLE
problem with mupdf.pdf_save_document 

### ISSUE THREAD

**Issue by msedaghatpour** [pymupdf/PyMuPDF#4097]
### Description of the bug

Having an issue that i cant find an answer to anywhere. So maybe its a bug? 
Originally we thought it may be a problem with Jupyter Notebook but also ran it in VS code with (I think) a new environment and in terminal. I am working with 3 long PDFs and same error occurs for all three. 

This particular iteration of the error is with Python 3.11.3 and PyMuPDF== 1.24.14

I have also run the script with python3.9 and PyMuPDF==1.21.1 and get the same error at the same line (it just doesn't say "code=8"). 
PDF is fine when I open it in Preview or Adobe & works with my other scripts where I also use PyMuPDF. 
The strange part is that the exact same code runs fine for my collaborator. She was using PyMuPDF==1.21.1. 

[NOUVELLE FLORE DU LIBAN ET DE LA SYRIE 1.pdf](https://github.com/user-attachments/files/17962976/NOUVELLE.FLORE.DU.LIBAN.ET.DE.LA.SYRIE.1.pdf)

Here is the full error:
```
---
FzErrorSyntax                             Traceback (most recent call last)
<ipython-input-45-6a1dbdbb7482> in ?()
      1 # %%
      2 print("Processing vol1")
----> 3 process_volume("vol1", vol1_index_df, vol1_char_df, vol1_doc, vol1_genera)
      4 print("\n\n\nProcessing vol2")
      5 process_volume("vol2", vol2_index_df, vol2_char_df, vol2_doc, vol2_genera)
      6 print("\n\n\nProcessing vol3")

<ipython-input-44-1d520c871696> in ?(volume, volume_index_df, volume_char_df, volume_doc, volume_genera)
    201                 annot_rect = page.add_rect_annot(r_box)
    202                 annot_rect.update()
    203 
    204     marked_epithet_fname = f"{output_dir}/local/main_text/{volume}_binom_sections_new_page_cont_v4.pdf"
--> 205     volume_doc.save(marked_epithet_fname)
    206 
    207     volume_word_df.to_pickle(f"{input_dir}/desc_box_df/{volume}_desc_df_v2.pkl")

~/opt/anaconda3/envs/EvoGen/lib/python3.11/site-packages/pymupdf/init.py in ?(self, filename, garbage, clean, deflate, deflate_images, deflate_fonts, incremental, ascii, expand, linear, no_new_id, appearance, pretty, encryption, permissions, owner_pw, user_pw, preserve_metadata, use_objstms, compression_effort)
   5655         if no_new_id == 0:
   5656             JM_ensure_identity(pdf)
   5657         if isinstance(filename, str):
   5658             #log( 'calling mupdf.pdf_save_document()')
-> 5659             mupdf.pdf_save_document(pdf, filename, opts)
...
  51728 def pdf_save_document(doc, filename, opts):
  51729     r""" Class-aware wrapper for ::pdf_save_document()."""
51730     return _mupdf.pdf_save_document(doc, filename, opts)

FzErrorSyntax: code=8: invalid key in dict
```

### How to reproduce the bug

Here is the complete script: https://github.com/shidedh/ExtractFloraOrganizedV0/blob/p0_draft/main_text/entry_bbox_page_cont.py 

### PyMuPDF version

1.24.14

### Operating system

MacOS

### Python version

3.11

**Comment by JorjMcKie** [comment]
The problem has nothing to do with your code _[although I would question why you are doing things as you do them ... but forget that at the moment]_.

The point is that your file indeed contains errors. Did you ever try to simply open and then save it separate from your program? I am getting this:
```python
import pymupdf
doc=pymupdf.open("NOUVELLE.FLORE.DU.LIBAN.ET.DE.LA.SYRIE.1.pdf")
doc.save("x.pdf")
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    doc.save("x.pdf")
...
pymupdf.mupdf.FzErrorSyntax: code=8: invalid key in dict
```
MuPDF's command line tool does and reports the same thing:
```bash
mutool clean NOUVELLE.FLORE.DU.LIBAN.ET.DE.LA.SYRIE.1.pdf
warning: dropping unclosed output
syntax error: invalid key in dict
```

But independent from that frightening message, an output PDF is still created.
There is no telling whether this creates error-free PDF output, but it does look ok at a first glance.

**Comment by msedaghatpour** [comment]
I had opened the files separately but not saved them. I made a copy of the first PDF and the code ran with correct outputs. Although it doesn't make sense to me why PDFs 2 and 3 also ran correctly, I made no changes to those. Earlier I had tried running the code with PDF 2 first and 3 first and those gave the same error as PDF 1. At any rate, thanks for the simple fix!

**Comment by JorjMcKie** [comment]
I cannot say anything about the origin of these files. Fact is that at least the attached PDF contains errors ... more than the one named in the error message.
Who / what created them ... who knows.

This does not necessarily mean that such a PDF is completely unusable. Because PDF files contain (almost) no built-in consistency check - in contrast to file formats with a rigorous internal structure like databases - errors may exist unnoticed for ages until using a certain feature that exhibits them.
In your case that means that the PDF can be opened by PDF viewers without apparent problems, but saving it causes an access to erroneous regions.
