### ISSUE TITLE
Extracting Heading and the content of the pdf

### ISSUE THREAD

**Issue by ArjunSikhwal** [pymupdf/PyMuPDF#410]
Hi,
I'm trying to extract the heading and the content of it in a pdf document. Main issue is I can't seem to find any consistency of fonts in document, what i thought could've been used for separating the heading from content.
Thank you

**Comment by JorjMcKie** [comment]
PDF knows nothing about such things as "header", "footer" or similar. This has nothing to do with (Py-) MuPDF.

You must find out yourself the first (or last) text (-line) on a PDF (or any document) page.

Do this either by text position info or (if known ... !)  maybe also by fontname.
All information required for such investigation can be gotten from PyMuPDF functions, the most applicable being one of the various outputs of ``Page.getText()``.

**Comment by ArjunSikhwal** [comment]
Okay got it.
Thanks a lot

**Comment by sheshank1436** [comment]
Hi arjun  i am trying to get the same, were you able to get the output. if yes please help me

**Comment by motua16** [comment]
Hi , was anyone able to accurately do this ?

**Comment by adicode-1729** [comment]
You can turn the page into a Textpage which will allow you to extract all sorts of details alongside the texts. I personally used TextPage.extractRAWDICT(), and it had a lot of data within the "span" parameter, including the box from which it has been captured, flags that represent bold/italic/other text metadata, fonts, font size, and more. 

[This](https://pymupdf.readthedocs.io/en/latest/textpage.html) documentation might be able to help.
