### ISSUE TITLE
question about checkboxes

### ISSUE THREAD

**Issue by jonathanbouchet** [pymupdf/PyMuPDF#4100]
Hi,
I have some issues to have checkboxes _checked_ and I'm not sure if it comes from the pdf file I'm using.
I'm using the _MEDICARE PART B (MEDICAL INSURANCE)_ pdf file (attached) which has only 1 checkbox

<img width="1009" alt="Screen Shot 2024-12-01 at 6 13 48 PM" src="https://github.com/user-attachments/assets/c52b5a86-7f16-4334-a0f7-2e2b8f3bad3c">

and my code is below:

```py
import pymupdf
doc = pymupdf.open("./CMS-40B_keep.pdf")

# check widgets
for page in doc: 
    widgets = page.widgets()
    for widget in widgets:
        if widget.field_type == 2:
            print(f"""widget: {widget}, name:{widget.field_name}, 
                choice_values: {widget.choice_values}, label: {widget.field_label}, 
                type: {widget.field_type}, button_states: {widget.button_states()}""")
```

The checkbox is found:
```
widget: Widget:(field_type=CheckBox script=None), name:YES, 
                choice_values: None, label: YES, 
                type: 2, button_states: {'normal': ['On'], 'down': ['Off', 'On']}
```

I then try to modify it using :

```py
# modify checkbox
for page in doc: 
    widgets = page.widgets()
    for widget in widgets:
        if widget.field_type == 2:
            widget.field_value = "Yes" # True
            widget.update()

doc.save("new_replacement.CMS-40B_keep.pdf")
```

However the pdf is not changed, so I'm not sure what I'm doing wrong.
I tried both `True` and `Yes`.
Thanks for any help.

Jonathan

## env

1. macOS 10.15.7
2. Python 3.11.10
3. PyMuPDF  1.24.14
[CMS-40B_keep.pdf](https://github.com/user-attachments/files/17971690/CMS-40B_keep.pdf)

**Comment by sarahkittyy** [comment]
use widget.field_value = widget.on_state()

**Comment by jonathanbouchet** [comment]
thanks for the suggestion @sarahkittyy 
However, `widget.on_state()` will just return `Yes`, please see below for the output of this specific widget:

```py
widget: Widget:(field_type=CheckBox script=None), name:YES, 
                choice_values: None, label: YES, 
                type: 2, button_states: {'normal': ['Off', 'Yes'], 'down': None}, rect: Rect(333.4800109863281, 111.719970703125, 342.6000061035156, 120.84002685546875)
, on_state: Yes
```

So setting the value by hand with either `Yes` or `True`, or using the `on_state()` method has the same effect.

**Comment by jonathanbouchet** [comment]
quick update on my initial issue.

The code above works perfectly fine. it turns out that the `checkbox` is not displayed as `checked` with MacOS Preview.
However, it does show as `checked` when using Acrobat Reader (I'm using 2024.004.20272)

See result below, left is Preview, right is Acrobat

<img width="1772" alt="Screen Shot 2024-12-05 at 2 29 50 PM" src="https://github.com/user-attachments/assets/b1cee375-47c8-4056-ad4b-bf6dcce44556">
