### ISSUE TITLE
page.get_images() is not working properly

### ISSUE THREAD

**Issue by NabeelParve** [pymupdf/PyMuPDF#4103]
### Description of the bug

I tried to extract images using `page.get_images() ` 
for the following Image
![image](https://github.com/user-attachments/assets/208d27e6-c05f-4820-b7fa-682fc9587440)
I get multiple small images like below
![image](https://github.com/user-attachments/assets/851236ac-6f94-4971-b926-fcef12aea4fe)
![image](https://github.com/user-attachments/assets/aee89b7b-302b-44ff-bd3e-174ac3b487b0)
![image](https://github.com/user-attachments/assets/755b731e-76b6-40de-8102-cc50f3b5986f)

My code looks like this:
```
image_list = page.get_images(full=True)
for img_index, img in enumerate(image_list):
        xref = img[0]
        base_image = page.parent.extract_image(xref)
        image_bytes = base_image["image"]
        bbox = page.get_image_bbox(img)
        with open('myfile.png', "wb") as img_file:
            img_file.write(image_bytes)
```

### How to reproduce the bug

```
image_list = page.get_images(full=True)
for img_index, img in enumerate(image_list):
        xref = img[0]
        base_image = page.parent.extract_image(xref)
        image_bytes = base_image["image"]
        bbox = page.get_image_bbox(img)
        with open('myfile.png', "wb") as img_file:
            img_file.write(image_bytes)
```

### PyMuPDF version

1.24.2

### Operating system

Windows

### Python version

3.10

**Comment by NabeelParve** [comment]
Hello @JorjMcKie ,

Here are the reproducing code and file
```
import fitz  # PyMuPDF
import os

def extract_images_from_pdf(pdf_path, output_folder):
    pdf_document = fitz.open(pdf_path)

    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    for page_number in range(pdf_document.page_count):
        page = pdf_document.load_page(page_number)

        image_list = page.get_images(full=True)
        
        for img_index, image in enumerate(image_list):
            xref = image[0]
            base_image = pdf_document.extract_image(xref)
            image_bytes = base_image["image"]

            image_filename = f"page_{page_number + 1}_image_{img_index + 1}.png"

            image_path = os.path.join(output_folder, image_filename)

            with open(image_path, "wb") as image_file:
                image_file.write(image_bytes)

            print(f"Image saved: {image_path}")

    print("Image extraction completed.")

pdf_path = "document.pdf"
output_folder = "extracted_images"
extract_images_from_pdf(pdf_path, output_folder)
```
[document.pdf](https://github.com/user-attachments/files/17988018/document.pdf)




I understand that the images are overlapping, but I'm still only able to see three overlapping images. Is there any other method to view all the images properly?

Thank you!

**Comment by JorjMcKie** [comment]
The other stuff on the page are no images but vector graphics - so they of course are not shown in `get_images()`.
Vector graphics cannot (easily) be extracted - at least not in a way you seem to need. All you can do here is rendering the page (i.e. make a `Pixmap`) around this area which you then save as an image.
Method `page.cluster_drawings()` returns a list of rectangles which each surround vector graphics that seem to belong together. For each such rectangle do `pix = page.get_pixmap(clip=rect)`.
