### ISSUE TITLE
Seg Fault with page.firstWidget

### ISSUE THREAD

**Issue by mpalazz** [pymupdf/PyMuPDF#411]
## Bug
I iterate through widgets on a regular basis.  I often use the firstWidget attribute to start a loop with each page.  I updated to 1.16.8 recently and all my code started failing on `page.firstwidget`.   I've tried this on many different forms, and it seems to universally fail on versions > 1.16.5. 

## To Reproduce
[random form link for testing](https://www.cms.gov/Medicare/CMS-Forms/CMS-Forms/downloads/cms1490s-english.pdf)
~~~~
mudoc = fitz.open('cms1490s-english.pdf')
page = mudoc[0]
f = page.firstWidget
~~~~
## Output:
`Segmentation fault: 11`

## Configuration
 - Reproduced on MacOS and Windows 10
 - Python version 3.7.5
 - PyMuPDF >=1.16.6, installed with `pip install pymupdf`

## Additional
Perhaps fixing issue #390 (“Incomplete deletion of annotations”)  in 1.16.6 created this bug?  
Thanks for the help!  Love the software, btw.

**Comment by JorjMcKie** [comment]
Thanks for submitting this!
I located and fixed the error. Some background:
In some recent version I extended the ``Widget`` class with some properties, among them ``button_caption``. The base library's (MuPDF) PDF object text retrieval function I used for this occasionally does not return a proper C char* type (instead pinted into the wild).
This disappeared after switching to a more cautious alternative ...

I presume there is some urgency for you here?
If yes, I can publish a fixed version by tomorrow ...

**Comment by JorjMcKie** [comment]
BTW you are aware of the new iterator ``page.wigdets()``? It saves you accessing ``firstWidget`` yourself, and also allows subselecting the desired widget types.

**Comment by mpalazz** [comment]
There is no emergency - 1.16.5 is working fine for now.  Thanks for your fast response!

I am aware of the new iterator and use it - I just wanted this bug to be clear.

**Comment by JorjMcKie** [comment]
Just uploaded v1.16.9 which fixes this.
