### ISSUE TITLE
int too large to convert to float

### ISSUE THREAD

**Issue by xiaolibuzai-ovo** [pymupdf/PyMuPDF#4113]
### Description of the bug

Traceback (most recent call last):
  File "/Users/mingzhili/py/pymupdf_demo/pingce.py", line 66, in <module>
    redaction(filename)
  File "/Users/mingzhili/py/pymupdf_demo/pingce.py", line 31, in redaction
    page.insert_htmlbox(bbox, html)
  File "/Users/mingzhili/py/pymupdf_demo/venv/lib/python3.9/site-packages/pymupdf/utils.py", line 2107, in insert_htmlbox
    fit = story.fit_scale(temp_rect, scale_min=1, scale_max=scale_max)
  File "/Users/mingzhili/py/pymupdf_demo/venv/lib/python3.9/site-packages/pymupdf/__init__.py", line 12510, in fit_scale
    return self.fit(fn, scale_min, scale_max, delta, verbose)
  File "/Users/mingzhili/py/pymupdf_demo/venv/lib/python3.9/site-packages/pymupdf/__init__.py", line 12466, in fit
    if update(parameter):
  File "/Users/mingzhili/py/pymupdf_demo/venv/lib/python3.9/site-packages/pymupdf/__init__.py", line 12407, in update
    rect = fn(parameter)
  File "/Users/mingzhili/py/pymupdf_demo/venv/lib/python3.9/site-packages/pymupdf/__init__.py", line 12509, in fn
    return Rect(x0, y0, x0 + scale*width, y0 + scale*height)
OverflowError: int too large to convert to float

### How to reproduce the bug

pdf: [Defining and Evaluating Decision and Composite Risk in Language Models Applied to Natural Language Inference.pdf](https://github.com/user-attachments/files/18006579/Defining.and.Evaluating.Decision.and.Composite.Risk.in.Language.Models.Applied.to.Natural.Language.Inference.pdf)

```python
    docs = pymupdf.open('filename')  
    for page in docs:
        blocks=page.get_text("dict",flags=pymupdf.TEXTFLAGS_TEXT)["blocks"]
        spans=[s for b in blocks for l in b['lines'] for s in l['spans']]
        for span in spans:
            bbox = span['bbox']
            text = span["text"]
            if "CMMI10" in span['font']:
                continue
            color = "%02x%02x%02x" % pymupdf.sRGB_to_rgb(span["color"])
            page.add_redact_annot(span["bbox"])
            page.apply_redactions(images=0, graphics=0, text=0)
            html = f'<span style="color: #{color};font-size:{span["size"]}px; overflow-wrap: break-word;">{text}</span>'
            print(bbox)
            page.insert_htmlbox(bbox, html)
    docs.ez_save("redaction/"+filename,garbage=4)
```

### PyMuPDF version

1.24.14

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
This is not a bug.
You are trying to use `page.insert_htmlbox()` more than 20 thousand times in this code.
With the current version, this will lead to a memory overflow because required fonts will be dynamically allocated each time this method is executed.
We may improve this at a later time.

Currently, you need to restrict the number of executed `insert_htmlbox`  - maybe do it for 1 page, then save, then do it for another page etc.

**Comment by JorjMcKie** [comment]
Another comment:
Independent from insert_htmlbox, your code has an extremely bad performance: you add a redaction annot and immediatley apply it. This happens 1321 times on page 0 alone!!!
1. Instead, add all required redactions.
2. Then apply them all at once.
3. Then iterate over the spans again and insert the new text.

Still very bad performance but at least sort of doable. Here is code that does that:
```python
import pymupdf
import pathlib

pdfbytes = pathlib.Path("test.pdf").read_bytes()
doc = pymupdf.open("pdf", pdfbytes)
page_count = doc.page_count
for i in range(page_count):
    page = doc[i]
    count = 0
    blocks = page.get_text("dict", flags=pymupdf.TEXTFLAGS_TEXT)["blocks"]
    spans = [s for b in blocks for l in b["lines"] for s in l["spans"]]
    for span in spans:
        bbox = span["bbox"]
        text = span["text"]
        if "CMMI10" in span["font"]:
            continue
        count += 1
        page.add_redact_annot(span["bbox"])
    page.apply_redactions(images=0, graphics=0, text=0)
    print(f"executed {count} redactions on {page.number=}")
    for span in spans:
        bbox = span["bbox"]
        text = span["text"]
        if "CMMI10" in span["font"]:
            continue
        color = "%02x%02x%02x" % pymupdf.sRGB_to_rgb(span["color"])
        html = f'<span style="color: #{color};font-size:{span["size"]}px; overflow-wrap: break-word;">{text}</span>'
        page.insert_htmlbox(bbox, html)
    print(f"inserted htmlboxes on {page.number=} {count}")
    pdfbytes = doc.write(garbage=4, deflate=True)
    doc.close()
    doc = pymupdf.open("pdf", pdfbytes)
    print()

doc.subset_fonts()
doc.ez_save("redacted.pdf")
```
