### ISSUE TITLE
Feature Request: Allow controlling whether TOC entries should be collapsed

### ISSUE THREAD

**Issue by PeterSlezak** [pymupdf/PyMuPDF#412]
Hi,
Is it possible to specify in setTOC() method whether the created outline item will be open/closed if it has a descendants? Outline item dictionary must have a Count entry if item has any descendants but I haven't found an option in setTOC() method to set the value. Is it possible to specify that by pymupdf? I assume that it's set to 0 by default as all nested outlines are closed. 
Thanks in advance for the response!

**Comment by JorjMcKie** [comment]
Your observation is correct: some long time ago I made this switch to collapse all TOC entries below level 1. This happened out of my own needs.

Let me keep this as the default and include an option to **not** do that - something like ``collapse=True/False`` or even ``collapse=n`` where n means "collapse level n and below".

BTW this is controlled in PDF by setting the ``/Count`` parameter in an outline entry to a negative value.

Thanks for submitting this!

**Comment by JorjMcKie** [comment]
A more difficult (although certainly possible) solution would be to control this on each individual entry.
Something like an additional bool which causes collapsing entries below it.

**Comment by JorjMcKie** [comment]
Was easy to implement:
Here is what the documentation for the next version will contain:

```
setToC(toc, collapse=1)
...
• collapse (int) – controls the hierarchy level below which outline entries should
be initially displayed collapsed. The default 1 will only display level 1, higher
levels must be expanded in the PDF viewer. To suppress collapsing alltogehter
specify either a large enough integer or collapse=0, resp. collapse=None.
```

**Comment by PeterSlezak** [comment]
Thank you, that's perfect!  Really appreciate your quick response

**Comment by JorjMcKie** [comment]
Just uploaded v1.16.9 which fixes this.
