### ISSUE TITLE
getting page count = 0 for a pdf with 13 pages.

### ISSUE THREAD

**Issue by zhanglifan1022nice** [pymupdf/PyMuPDF#4120]
### Description of the bug

[1951807.pdf](https://github.com/user-attachments/files/18033989/1951807.pdf)

This pdf file seems normal when open it with desktop application containing 13 pages.
But when it open by pymupdf,

pdf = fitz.open("./bug_pdf/1951807.pdf")
print(pdf.page_count)
print(len(pdf))
-------------------
0
0
Process finished with exit code 0

Any idea why this is happened? Thanks!

### How to reproduce the bug

pdf = fitz.open("./bug_pdf/1951807.pdf")
print(pdf.page_count)
print(len(pdf))

### PyMuPDF version

1.24.9

### Operating system

MacOS

### Python version

3.10

**Comment by JorjMcKie** [comment]
This is not a bug, because the PDF is severely damaged. Most PDF viewers cannot read the file at all.
MuPDF's repair mechanisms do not yield a usable file.

**Comment by zhanglifan1022nice** [comment]
![image](https://github.com/user-attachments/assets/d23a7aea-d28c-48b8-8aa3-047e5d117195)
it seems wps can read the file. I wonder what is the different..
