### ISSUE TITLE
Unicode Normalization with word extraction?

### ISSUE THREAD

**Issue by mpalazz** [pymupdf/PyMuPDF#413]
**Is your feature request related to a problem? Please describe.**
When using `page.getText('words')`, I often get strings like this:
`'Secondary\xa0School\xa0Contact\xa0Name\xa0'`
which I can fix by using this (python native): 
`unicodedata.normalize('NFKC',  'Secondary\xa0School\xa0Contact\xa0Name\xa0')`
output: 
`'Secondary School Contact Name '`
Issue:
I only have a rect for the full, original output after I normalize. 
**Describe the solution you'd like**
Is there any way you could normalize the text before generating the rect coordinates?  Perhaps with a flag option? 
Thanks!

**Comment by JorjMcKie** [comment]
Hm, I am afraid this is not possible.
The "blocks" and "words" options for ``getText`` have been created for high performance, Specifically, the "words" option looks for strings **which do not contain spaces** and treats those fragments as *words*. If a PDF has been created with ``xa0`` bytes in between its text, then this is simply not a space and thus will deliver a completely different list of *words*.
The only alternative would be to treat this special byte ``0xA0`` exactly like a space (for this function only!), which seems to be a fairly radical approach ...
On the other hand, ``0xA0`` can be viewed as a "non-breaking" version of space, so there **_is_** some justification for it ... **IF** it is not a different meaning in some other character set encoding (e.g. Symbol, where this is the code for the Euro character).

So in summary:
If I would treat code point 160 just like 32 (space),
* you would never get the return 'Secondary School Contact Name ', but instead 4 separate words, each with its rectangle
* depending on the encoding used (checking of which will never be part of these functions), there may be produced wrong results, as mentioned above
* the code point 160 (0xA0) is interpreted as nonbreaking space only in WinAnsiEncoding, whereas in MacRomanEncoding, code point 202 takes on the role of nonbreaking space and 160 is "Psmall".

>  Is there any way you could normalize the text before generating the rect coordinates? Perhaps with a flag option?

Short answer: no.
Longer answer:
The code behind the ``getText`` functions works for all MuPDF supported document types - not just PDF. While options "xml", "(x)html", "text" are MuPDF-provided, the other options are ("blocks", "words", "(raw)dict" are PyMuPDF's own code, but written in C using the same basic logic. There is no way to determine the encoding of the text which is being extracted - the extraction process is unicode charatcer by unicode character.
As mentioned above, a correct interpretation of those unicode characters depends on the encoding used (and some other things).

What you could do:
Extract the text using option "rawdict". This delivers a dictionary with unicode character granularity. Each character has its rectangle. So you can go by and recreate your words by concatenating characters (and joining their accompanying rectangles) by treating normal and nonbreaking spaces equally as word breaking codes. The code snippet would look something like this:

```pythpn
wordlist = []
blocks = page.getText("rawdict")["blocks"]
for line in blocks["lines"]:
    for span in line["spans"]:
        text = ""  # will contain word text
        x0, y0 = span["bbox][:3]  # we use this as start for first word in span
        rect = fitz.Rect(x0, y0, x0, y0)  # start word rect  with this empty one
        for char in span["chars"]:
            if char["c"] not in (" ", chr(160)):  # not one of the space characters
                text += char["c"]  # append it to the word
                rect |= char["bbox"]  # join with word rectangle
            else:  # output what we have as a word and start new one
                if len(text) > 0:  # guard against multi spaces in sequence
                    wordlist.append(list(rect) + [text])
                text = ""
                x0, y0 = char["bbox"][2:]  # end of space char is start of new word
                rect = fitz.Rect(x0, y0, x0, y0)
# now work with the wordlist
```

The above of course carries no guaranty to work - please use your own judgement.
Some finetuning / safeguarding is definitely required: take into account that more than one (nonbreaking) space may occur in a  row ..., etc.

**Comment by JorjMcKie** [comment]
Here is the previous snippet as a function with some corrections:

```python
def wlist(page):
    wordlist = []
    blocks = page.getText("rawdict")["blocks"]
    for block in blocks:
        for line in block["lines"]:
            for span in line["spans"]:
                text = ""  # will contain word text
                x0, y0 = span["bbox"][:2]  # we use this as start for first word in span
                rect = fitz.Rect(x0, y0, x0, y0)  # start word rect  with this empty one
                for char in span["chars"]:
                    if char["c"] not in (
                        " ",
                        chr(160),
                    ):  # not one of the space characters
                        text += char["c"]  # append it to the word
                        rect |= char["bbox"]  # join with word rectangle
                    else:  # output what we have as a word and start new one
                        if len(text) > 0:  # guard against multi spaces in sequence
                            wordlist.append(list(rect) + [text])
                        text = ""
                        x0, y0 = char["bbox"][
                            2:
                        ]  # end of space char is start of new word
                        rect = fitz.Rect(x0, y0, x0, y0)
                if len(text) > 0:  # output unfinished word
                    wordlist.append(list(rect) + [text])
    return wordlist
```

**Comment by JorjMcKie** [comment]
This function should deliver a list **_almost_** equal to ``getText("words")`` with the following difference:

> ``getText("words")``  ignores all font information when composing text into words. In contrast to that, the **_function_** will start a new word for every new span. "Spans" are the pieces of a line with the same font characteristics, which include font name, size, color, bold, serifed, .... So for example, whenever a conventional "word" contains letters in different colors (or boldness, etc.) it will be split into multiple words by the function.

**Comment by mpalazz** [comment]
Much appreciated.  Thanks for all of this.  I will use your function!

**Comment by mani2106** [comment]
If the problem is only related to Unicode space characters, you can try setting flags like below
```python
page.getText('words', flags=fitz.TEXT_PRESERVE_LIGATURES | fitz.TEXT_INHIBIT_SPACES)
```
this helped me get the individual words which are combined by Non-breaking space`(\xa0)` or any other Unicode space character, although other characters may still need to handled separately.
