### ISSUE TITLE
Text In Text Form Widget Not Being Redacted by Redact Annotations

### ISSUE THREAD

**Issue by lyon-tonic** [pymupdf/PyMuPDF#4140]
### Description of the bug

I'm using redact annotations to remove specific text in PDFs.  This generally works quite well, but I've noticed that it fails with text within form text widgets.

Is this a known issue, and are there any workarounds?

### How to reproduce the bug

This is a sample I created, which has some text in form fields.
[sample.pdf](https://github.com/user-attachments/files/18102094/sample.pdf)

```
import fitz 

def redact_pdf(input_file, output_file, page_number, rect):
    pdf_document = fitz.open(input_file)
    
    page = pdf_document[page_number - 1]
    
    redaction_rect = fitz.Rect(*rect)
    
    page.add_redact_annot(redaction_rect) 
    page.apply_redactions()
    
    pdf_document.save(output_file)
    pdf_document.close()

input_pdf = "sample.pdf"
output_pdf = "redacted.pdf"

page_to_redact = 1
redact_rectangle = (0, 0, 400, 300) 

redact_pdf(input_pdf, output_pdf, page_to_redact, redact_rectangle)

print(f"Redacted PDF saved to {output_pdf}")
```

This script adds a redaction over the top left corner of the page, and the resulting redaction removes the regular text and leaves the form text untouched.

[redacted.pdf](https://github.com/user-attachments/files/18102120/redacted.pdf)

### PyMuPDF version

1.25.0

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
This is no bug and works as designed. Form fields do not count as being redactable.
One reason is that they cannot be **_partly_** deleted, there is an all-or-nothing regime here.
Form fields can but be deleted via `page.delete_widget()`.

**Comment by JorjMcKie** [comment]
There is a way out of this - I should of thought of earlier:
You can convert ("bake-in") annotations and widgets to **_permanent_** page content throughout the PDF.
Then these are just normal text, vector graphics etc. and will behave as you seem to want it.
For this to happen, execute `doc.bake()`. Then do your adding and applying redactions.

But be aware, that after `bake()` the complete document will no longer be a Form PDF and will have no annotations - just normal content. IAW you cannot restrict baking to single pages only.
