### ISSUE TITLE
misalignment between column headers and cell values

### ISSUE THREAD

**Issue by mehtdip** [pymupdf/PyMuPDF#4146]
### Description of the bug

Please refer to the attached pdf (converted to text to eb able to attach)  and converted markdown file.
1. The financial year in  column headers is not completely identified which will create inaccurate result when used further.
2. The cell values are mis-aligned 
Please note that when converting to all formats whether csv, html etc have the same issue.

[pdftomd.txt](https://github.com/user-attachments/files/18122201/pdftomd.txt)
[tsla-20230930-gen1.pdf](https://github.com/user-attachments/files/18122133/tsla-20230930-gen1.pdf)
[tesla1.md](https://github.com/user-attachments/files/18122135/tesla1.md)

### How to reproduce the bug

1. download attached text file  and rename it to .py file.
2. download attached pdf file
3. change path in the .py file for the downloaded pdf file
4. execute the pyhon program after importing all libraries needed.

### PyMuPDF version

1.25.0

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
This is unfortunately inevitable with the table finder. If you look at your example, the "$" sign occurs in some rows only. This confuses the table finder algorithm, so there is no way to cope with this, sorry.
