### ISSUE TITLE
Enhance `page.get_text("raw_dict")` by including the PS name of each glyph.

### ISSUE THREAD

**Issue by elmstedt** [pymupdf/PyMuPDF#4150]
## Problem

The result from `page.get_text("rawdict")` is missing some information which would be incredibly handy to have. Specifically, it would be beneficial to have the result include the PS name for each glyph as well as an outline accurate bounding box.

This is beneficial for finding suitable unicode replacements for glyphs where the embedded font is lacking them—especially many math fonts. For instance, when compiling a MWE TeX file,

```tex
\documentclass{article}
\begin{document}
  $\sum$
\end{document}
```

The `dict` for the generated character is,
```py
'chars': [
  {
    'bbox': (
      148.71200561523438,
      119.6019058227539,
      159.22254943847656,
      156.78231811523438
    ),
    'c': 'P',
    'origin': (148.71200561523438, 127.29302978515625)
  }
]
```

Changing this to include the PS name like this,

```py
'chars': [
  {
    'bbox': (
      148.71200561523438,
      119.6019058227539,
      159.22254943847656,
      156.78231811523438
    ),
    'c': 'P',
    'name': 'summationtext'
    'origin': (148.71200561523438, 127.29302978515625)
  }
]
```
Would make it easy to use the [Adobe Glyph List (AGL)](https://github.com/adobe-type-tools/agl-aglfn/blob/master/glyphlist.txt) (or another PS name/Unicode map) to find a suitable replacement glyph. In this case,
```text
summation;2211
```

So we would replace the `P` with `∑`, making the extracted text more meaningful.

## Desired Solution
Add an additional entry to the `dict` returned by `page.get_text()` to include the PS name of the glyph taken from the embedded font when it is available.

## Alternatives

My current process for augmenting the `page.get_text("rawdict")` with PS names is to,

1. Extract the content streams from the target pdf using **qpdf**.
2. Parsing the root JSON object of the PDF to locate the embedded font objects.
3. Parse the embedded font object to extract character code and PS name pairs from the `/Encoding` field.
   a. Sometime also needing to process the `ToUnicode` entry to fix mapping issues.
4. Merge the additional data into the original output.

I have also experimented with,

### `page.get_texttrace()`
The output of which includes the glyph index for the glyph in the embedded font which looks like it might solve some of the CMap issues with some fonts, but it still requires additional external tools to acquire the PS name.

### `mutool trace`
This command line utility produces an XML output like this,
```xml
<document filename="mwe.pdf">
<page number="1" mediabox="0 0 595.276 841.89">
<set_default_colorspaces gray="DeviceGray" rgb="DeviceRGB" cmyk="DeviceCMYK" oi="None"/>
<fill_text colorspace="DeviceGray" color="0" ri="1" bp="1" op="0" opm="0" transform="1 0 0 -1 0 841.89">
    <span font="LBWBDW+CMEX10" wmode="0" bidi="0" trm="9.9626 0 0 9.9626">
        <g unicode="�" glyph="summationtext" x="148.712" y="714.597" adv="1.056"/>
    </span>
    <span font="SDXKYB+CMR10" wmode="0" bidi="0" trm="9.9626 0 0 9.9626">
        <g unicode="1" glyph="one" x="303.133" y="139.255" adv=".5"/>
    </span>
</fill_text>
</page>
</document>
```
which includes the glyph PS name, but mangles some of the glyphs themselves for fonts which do not include a proper unicode mapping (e.g. the Computer Modern fonts used in the vast majority of academic and scientific writing). This can be combined easily enough with some additional careful work, but it is still another external tool.

**Comment by JorjMcKie** [comment]
This request cannot be implemented by PyMuPDF:
PyMuPDF's standard text extraction is footed on MuPDF's structured text page. So please direct your request to MuPDF - the recommended way is using [this](https://discord.gg/edryCudN) Discord channel.

**Comment by JorjMcKie** [comment]
As an additional context: There exists no glyph named "summationtext" in the official lists from e.g. Adobe.

**Comment by elmstedt** [comment]
> As an additional context: There exists no glyph named "summationtext" in the official lists from e.g. Adobe.

Yes, I'm aware of that. 

For the CM fonts it is necessary to truncate the `text` and `display` suffixes.

This is a problem I have already solved for myself with post-processing, I was just making a suggestion to make **PyMuPDF** useful.
