### ISSUE TITLE
is it possible to add an overlay arguments on annotation.

### ISSUE THREAD

**Issue by PCarle** [pymupdf/PyMuPDF#416]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Are there several options for how your request could be met?

**Additional context**

**Comment by PCarle** [comment]
usage exemple:
# -*- coding: utf-8 -*-
from __future__ import print_function
import sys
print("Python", sys.version, "on", sys.platform, "\n")
import fitz
print(fitz.__doc__, "\n")

import os
print (os.getcwd())
from matplotlib.pyplot import imshow
import numpy as np
from PIL import Image


def print_descr(rect, annot):
    """Print a short description to the right of an annot rect."""
    annot.parent.insertText(rect.br + (10, 0),
                    "'%s' annotation" % annot.type[1], color = red)
    
red    = (1, 0, 0)
blue   = (0, 0, 1)
gold   = (1, 1, 0)
colors = {"stroke": blue, "fill": gold}
colors2 = {"fill": blue, "stroke": gold}
border = {"width": 1.3}
displ = fitz.Rect(0, 50, 0, 50)
r = fitz.Rect(50, 100, 220, 135)
t1 = u"têxt üsès Lätiñ charß,\nEUR: €, mu: µ, super scripts: ²³!"

doc = fitz.open()
page = doc.newPage()

annot = page.addPolygonAnnot([r.bl, r.br, r.tr,r.tl])
annot.setOpacity(0.5)
annot.setBorder(border)
#### 
###annot.setOverlay(False)

annot.setLineEnds(fitz.PDF_ANNOT_LE_SQUARE , fitz.PDF_ANNOT_LE_NONE)
annot.setColors(stroke=blue,fill=blue)
annot.update()
print_descr(annot.rect, annot)
print("added 'Polygon'")
page.insertText(r.bl + (10, -10),"Test de transparence")
r+=displ
annot = page.addTextAnnot(r.tl, t1,icon="Tag")

annot.update()
print_descr(annot.rect, annot)

pix=page.getPixmap(matrix=fitz.Matrix(fitz.Identity).preScale(3,3),alpha=True,colorspace="RGBA")


from PIL import Image, ImageTk
mode = "RGBA"
img = Image.frombytes(mode, [pix.width, pix.height], pix.samples)


from matplotlib import pyplot as plt
import matplotlib as mpl
mpl.rc("savefig", dpi=300)
plt.figure(figsize = (20,20))
fig, ax = plt.subplots(figsize=(18, 20))
ax.imshow(np.asarray(img))
plt.show()

**Comment by JorjMcKie** [comment]
@PCarle - interesting example!
Not sure what your intention was by immediately closing the issue. Just to make sure, a few comments from my side.
Annotations are a construct of the PDF standard - not one of MuPDF. So we are confined by what that standard offers. There is no way to put annotations in the background, although a number of bit flags may be set, some of which influence an annot's visibility:

1. Invisible
2. Hidden (PDF 1.2)
3. Print (PDF 1.2)
4. NoZoom (PDF 1.3)
5. NoRotate (PDF 1.3) 
6. NoView (PDF 1.3) 
7. ReadOnly (PDF 1.3)
8. Locked (PDF 1.4)
9. ToggleNoView (PDF 1.5)
10. LockedContents (PDF 1.7)

Detail descriptions on pages 608, 609 of the Adobe manual.
And of course, **_opacity_** also effects visibility.
Another idea might be to insert an annotation on a page of a temporaray PDF, create a pixmap of it and then insert that image with the desired overlay attribute on the target page.
Of course that image would no longer be an **_annotation_** on that target page, but it would look like one.

**Comment by PCarle** [comment]
The researched behaviour is something like  addHighlightAnnot on page but with list of points!
the overlay arguments is False in case of highlight annotation !

**Comment by PCarle** [comment]
something like addPloygonHighlightAnnot

**Comment by JorjMcKie** [comment]
The only thing coming near to what you apparently are looking for is using a polygon annotation, fill it with some color and then setting the opacity attribute with some value < 1.

**Comment by PCarle** [comment]
I do that but the rendering is not like the highlighting, the black (for the text) is diluted by the color of the polygon, in my test, the use of the annotation "highlighting" is the only way to change this behaviour.

**Comment by JorjMcKie** [comment]
I understand. Well, then I’m afraid that’s the best thing achievable. Or you do not use annotations, but use permanent  changes via page draw
Commands. They support overlays.
Von meinem iPhone gesendet

Am 18.03.2020 um 13:04 schrieb PCarle <notifications@github.com>:

﻿

I do that but the rendering is not like the highlighting, the black (for the text) is diluted by the color of the polygon, in my test, the use of the annotation "highlighting" is the only way to change this behaviour.

**Comment by JorjMcKie** [comment]
Being back home, I looked into this more closely again.
Your request is **not** about overlaying or not. As I wrote once: there is no such thing for annotations. The difference between 'Highlight' annotation rendering and opaqueness really is the so-called ``Blending Mode`` (PDF parameter `/BM`). For 'Highlight' annots only, this parameter is set to `/Multiply` by the MuPDF base library, which according to the PDF manual

> "Multiplies the backdrop and source color values. The result color is always at least as dark as either of the two constituent colors. Multiplying any color with black produces black; multiplying with white leaves the original color unchanged. Painting successive overlapping objects with a color other than black or white produces progressively darker colors." (Page 520)

This is why text covered with a highlight annotation is still (at least) as dark as before (probably darker) - and specifically not lightened up by an opaque object.

Let me ask, why you are so eager to have this behavior for arbitray shapes? After all you can create Highlights for **arbitrary rectangles** - you are not bound to highlighting just text for example ...

So far, dealing with this parameter is not part of PyMuPDF, and the effort would probably be fairly significant. This is partly due to finding a decent way to making it a new parameter for annotations, ensuring consistent behavior across annot updates. And then of course it wouldn't make sense to just introduce the `/Multiply` blending mode, but also the full dozen of alternatives. And all that would need to be documented, too of course.

**Comment by PCarle** [comment]
I use pyMupdf to create semantic annotations on a pdf I need to select text and to visualize it, the shape of the text selection is a polygon and not a rectangle like this example:
![exemple selection](https://user-images.githubusercontent.com/16350743/77166040-c846e100-6ab3-11ea-9cba-79d10b6e8d03.jpg)
transforming the polygon into a rectangle list (to make it a highlight annotation) is not immediate.

So I can't decide for you but it will be a nice feature for me 

Patrice

**Comment by JorjMcKie** [comment]
Ok, I see your point.
Let me check what implementing this may really mean and come back to you ...

**Comment by JorjMcKie** [comment]
While you are waiting ... what do you think about this little script?
Suppose you have a PDF page and want to highlight lines between these red points:
![grafik](https://user-images.githubusercontent.com/8290722/77187608-23280a80-6aab-11ea-9da8-71e1fe456a30.png)
Then this can be done by:
```python
import fitz


def get_rect_list(page, pointa, pointb):
    blocks = page.getText("dict")["blocks"]
    rectangles = []
    lines = []
    for b in blocks:
        if b["type"] != 0:  # not a text block
            continue
        for line in b["lines"]:
            bbox = fitz.Rect(line["bbox"])
            if bbox.y0 < pointa.y or bbox.y1 > pointb.y:
                continue
            lines.append(line)
    lines.sort(key=lambda line: line["bbox"][1])
    line0 = lines[0]  # first line
    bbox = fitz.Rect(line0["bbox"])
    if bbox.y0 - pointa.y < 0.1 * bbox.height:  # restrict rect if near top of selection
        bbox &= fitz.Rect(pointa.x, bbox.y0, bbox.br)
    rectangles.append(bbox)
    # ------------
    # add some caveats if less than 2 lines ...
    # ------------
    linex = lines[-1]  # last line
    bbox = fitz.Rect(linex["bbox"])
    if pointb.y - bbox.y1 < 0.1 * bbox.height:  # restrict rect if near bottom of selection
        bbox &= fitz.Rect(bbox.tl, pointb.x, bbox.y1)
    rectangles.append(bbox)
    for line in lines[1:-1]:
        rectangles.append(fitz.Rect(line["bbox"]))
    return rectangles


doc = fitz.open("v110-changes.pdf")
page = doc[0]
rl = page.searchFor("For e.g. colorspace RGB")
pointa = rl[0].tl
rl = page.searchFor("which therefore needs to be checked.")
pointb = rl[0].bl
rectangles = get_rect_list(page, pointa, pointb)
page.addHighlightAnnot(rectangles)
doc.save(...)

```
, and looks like this:
![grafik](https://user-images.githubusercontent.com/8290722/77187762-5bc7e400-6aab-11ea-9218-c62077c266f1.png)

**Comment by JorjMcKie** [comment]
FYI @PCarle - for the next version I have decided to

1. Add the feature as described in previous post to the text marker annotations. I am convinced this will address your requirements - as far as I know them. So the above effect would be achieved by ``page.addHighlightAnnot(start=pointa, stop=pointb)``. An optional ``clip`` parameter can be used to restrict the page area to consider (use with e.g. multi-column layouts).
2. Add the capability to specify a PDF "blend mode" for _**all**_ annotation types. It will be available as method ``Annot.setBlendMode("Multiply")`` and become visible via ``Annot.update()`` as usual. So one can now freely combine opacity and blend mode for all annotations. Apart from "Multiply" all other values are possible too, as described in the PDF spec.

**Comment by PCarle** [comment]
It sound's  as greats features ! thank's a lot 

Patrice

**Comment by JorjMcKie** [comment]
The new v1.16.14 is on PyPI and delivers the announced things.
Hope it helps.
No doubt you will find new issues - given your intense use of annotations 😉!

**Comment by PCarle** [comment]
Thank you for your help and your reactivity ...

As I am confined (I am French is located in the Parisian suburbs) 
I am forced to test all the implemented functionalities of my software
...

Patrice

Le 2020-03-25 20:09, Jorj X. McKie a écrit :

> The new v1.16.14 is on PyPI and delivers the announced things.
> Hope it helps.
> No doubt you will find new issues - given your intense use of annotations 😉! 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1] https://github.com/pymupdf/PyMuPDF/issues/416#issuecomment-604030868
[2]

**Comment by JorjMcKie** [comment]
> I am forced to test all the implemented functionalities of my software

... and I am absolutely in favor of this approach! You have uncovered a number of errors and inconsistencies this way and I am grateful for this.
During my business career at a world leading consultant company, a disciplined, well-thought testing methodology (the V model) was crucial to success and predictable quality.
So please do continue like that!
