### ISSUE TITLE
find_tables not identifying tables

### ISSUE THREAD

**Issue by mehtdip** [pymupdf/PyMuPDF#4169]
### Description of the bug

find_table method does not identify most of the tables in my attached pdf file.
[spgi-annual-report-2023.pdf](https://github.com/user-attachments/files/18209627/spgi-annual-report-2023.pdf)

### How to reproduce the bug

doc = pymupdf.open(path to the pdf file)

# Look for tables on this page and display the table count
for page in doc:
    tabs = page.find_tables()
    print(len(tabs.tables))

above code prints one table for  page 1 and zero tables for page 2 &3 .
Table identified on page 1 is also partial.

### PyMuPDF version

1.25.0

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
Sorry, there can nothing be done in the table finder module itself to improve this. Like just any table module on the market, `find_tables()` has its strengths and weaknesses.
The only way currently is to add more information in your script, like virtual lines via parameter `add_lines`. In your case, vertical virtual lines would seem appropriate.
This will help the table finder to identify tables and cells.
