### ISSUE TITLE
Bug in `doc.subset_fonts(fallback=True)`: Unable to obtain correct subset font for Source Han Serif

### ISSUE THREAD

**Issue by timelic** [pymupdf/PyMuPDF#4173]
### Description of the bug

While developing [PDFMathTranslate](https://github.com/Byaidu/PDFMathTranslate) using the PyMuPDF library, I encountered an issue where correct subset font files cannot be generated.

After investigating the code, I found that this is due to a bug in the `build_subset` method within `/src/utils.py`.

### How to reproduce the bug

Here's my reproduction code:

```
import fontTools.subset as fts
oldfont_path = "./SourceHanSerifCN-Medium.ttf"
newfont_path = "./test.ttf"
args = [
    oldfont_path,
    "--retain-gids",
    f"--output-file={newfont_path}",
    "--layout-features='*'", 
    "--passthrough-tables",
    "--ignore-missing-glyphs",
    "--ignore-missing-unicodes",
    "--symbol-cmap",
    "--gids=10-120", // change this to test the size of output file
]
fts.main(args)
```

I discovered that the output file size is always 1.2K regardless of the input.

After modifying the code:

```
"--layout-features=*", 
```

The modification successfully generated the correct output file (252K).

Test files:

[SourceHanSerifCN-Medium.ttf.zip](https://github.com/user-attachments/files/18218662/SourceHanSerifCN-Medium.ttf.zip)

### PyMuPDF version

1.25.1

### Operating system

Linux

### Python version

3.11

**Comment by JorjMcKie** [comment]
I cannot reproduce your problem - my subset font varies satisfactorily.
Als, your prosed change to replace `layout-features='*'` by `layout-features=*` is in contradiction to the [documentation](https://fonttools.readthedocs.io/en/latest/subset/index.html#glyph-set-expansion) 
![image](https://github.com/user-attachments/assets/8dd603e2-a71c-424b-aba9-1b97f5381b01)

**Comment by timelic** [comment]
I thoroughly checked and found that this bug seems to originate from the font I modified, rather than PyMuPDF.  I will close this issue. 

Thank you very much for your detailed feedback and suggestions.
