### ISSUE TITLE
MuPDF error: syntax error: cannot find ExtGState resource 'GS0'

### ISSUE THREAD

**Issue by esraa-abdelmaksoud** [pymupdf/PyMuPDF#4175]
### Description of the bug

I've been using `PyMuPDF==1.20.2` for a while and upgraded to `PyMuPDF 1.25.1` today. After running the same old code using the same old files, I saw the error below being printed but not raised. It doesn't stop the process.
```
MuPDF error: syntax error: cannot find ExtGState resource 'GS0'
```
I decided to keep downgrading gradually until ```PyMuPDF==1.23.26```. This was when the error disappeared.

### How to reproduce the bug

To reproduce the problem, please read the pages of any PDF file, and then use get_pixmap.
```
page = doc.load_page(p)
pix = page.get_pixmap(dpi=100)
image_bytes = pix.tobytes()
```

### PyMuPDF version

1.25.1

### Operating system

Linux

### Python version

3.9

**Comment by JorjMcKie** [comment]
When reporting a bug, submitting a reproducing file is  mandatory.

**Comment by esraa-abdelmaksoud** [comment]
Unfortunately, all files I have contain sensitive medical information with identifiers. That's why I haven't added any files to the issue.

**Comment by JorjMcKie** [comment]
Well, then there is not much we can do, can we.
There is no doubt that the message is correct, though. All you can do is suppressing its display via `pymupdf.TOOLS.mupdf_display_errors(False)`.

**Comment by robinwatts** [comment]
First you claim that "all files show the problem", then you claim that "all files contain sensitive medical information". One of those statements is clearly false.

**Comment by esraa-abdelmaksoud** [comment]
@robinwatts Maybe I should've said "all files I have show the problem". At the same time, all the files I have are medical PDF files.

**Comment by esraa-abdelmaksoud** [comment]
@JorjMcKie Thanks! I'll use that.
