### ISSUE TITLE
After write text with textwriter, some original font cannot be displayed.

### ISSUE THREAD

**Issue by nissansz** [pymupdf/PyMuPDF#4176]
### Description of the bug

![image](https://github.com/user-attachments/assets/e8518c05-02cf-4ec8-b379-8aaf429bf7c5)

### How to reproduce the bug

After write text with textwriter, some original font cannot be displayed.

### PyMuPDF version

1.24.14

### Operating system

Windows

### Python version

3.9

**Comment by JorjMcKie** [comment]
All data required to reproduce the problem are missing.

**Comment by nissansz** [comment]
[7.pdf](https://github.com/user-attachments/files/18237678/7.pdf)
Try this pdf, write some Chinese text and save

**Comment by JorjMcKie** [comment]
... and what did you do to run into the problem???

**Comment by nissansz** [comment]
page.insert_text((rect.x0, rect.y0- int(fontsize /4)), text_red, fontsize=fontsize_fit, fontname="F0", color=color_red,
                             morph=(fitz.Point(rect.x0, rect.y0- int(fontsize /4)), transform_matrix))



    out.subset_fonts()  # 
    new_file = path.replace('.PDF','').replace('.pdf','')+'_'+str(dpi)+'_textlines.pdf'
    out.ez_save(new_file, garbage=3, deflate=True)
    out.close()

**Comment by JorjMcKie** [comment]
This seems to go on forever: what is the font "F0"! It doesn't appear in the page's font list.
Before we go on with this:
There is no guarantee that an embedded font can be reused for text insertion. This is not a PyMuPDF problem but depends on the way how the font subset was created.

**Comment by nissansz** [comment]
Original pdf is printed with Chrome directly.
