### ISSUE TITLE
Extract two  lines  Tag Number from Process Instrumentation Drawing (PID) 

### ISSUE THREAD

**Issue by samer1977** [pymupdf/PyMuPDF#4177]
Hi,

Im not sure if your tool can do this but is there a way to parse instrument tags from PID drawing in PDF format. For example:

![image](https://github.com/user-attachments/assets/ced67fec-c1a5-458d-8afa-82e0dadd0eb2)

I would like to be able to extract the following Tags:

HS 33381A
HS 33171B

Thanks

**Comment by JorjMcKie** [comment]
We do not (intend to) extract "tags" in this way. All we can do is extracting text and images and vector graphics.
There is no way for us to make sense out of these objects **_semantically_**. This remains your responsibility - potentially you might find AI-based tools which specifically understand CAD/CAM output.
