### ISSUE TITLE
Spans bbox have 0 instead of real values

### ISSUE THREAD

**Issue by sshustov** [pymupdf/PyMuPDF#418]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
For some reason I noticed several documents that have wrong bbox value

## To Reproduce (mandatory)
You can use getText('dict') on attached document. I also attached the screenshot (you will find that 1 'bbox' value is correct, but another one is not

## Expected behavior (optional)
Both bbox should have some numbers, not 0

## Screenshots (optional)
[example.pdf](https://github.com/pymupdf/PyMuPDF/files/3985397/example.pdf)
![example_from_debug](https://user-images.githubusercontent.com/55201297/71204735-d562f280-226e-11ea-8d8e-0d836b0ccce8.png)

## Your configuration (mandatory)
 - ubuntu 16.04 x64
 - Python version 2.7
 - PyMuPDF version,1.14.21

**Comment by JorjMcKie** [comment]
cannot reproduce your problem - see attached logfile:

[logfile.zip](https://github.com/pymupdf/PyMuPDF/files/3985571/logfile.zip)

**Comment by sshustov** [comment]
I see, can you please check line bbox. Try this:
```import fitz
doc = fitz.open('/home/sshustov/Downloads/example.pdf')
page = doc[0]
blocks = page.getText('dict')['blocks']
for block in blocks:
  ...:    print(block['bbox'])
  ...:    for line in block['lines']:
  ...:        print(line['bbox'])```

**Comment by JorjMcKie** [comment]
You are right, there is an error in this version.
It works correctly in version 1.16.x. Just tested with 1.16.9 (current in PyPI).
Please upgrade.
