### ISSUE TITLE
get_image_info() returns image data, get_text("dict") does not.

### ISSUE THREAD

**Issue by pdc1** [pymupdf/PyMuPDF#4183]
### Description of the bug

Based on the documentation, I assumed that `get_image_info()` would be equivalent to `get_text("dict")` without the image content:

> This includes information for exactly those images that are shown on the page, including “inline images”. Similar to get_text(), but no image binary content is loaded, which drastically reduces memory usage.

The TextPage documentation states

> An image block is generated for **all and every image occurrence** on the page. Hence there may be duplicates, if an image is shown at different locations.

However, I have a PDF where `get_image_info()` returns info about an image, but `get_text("dict")` does not return any images at all (i.e. the "blocks" key is an empty array).

Am I misunderstanding how this works? I was hoping to extract images in a way that would be compatible with PDF as well as EPUB.

### How to reproduce the bug

From the Astro City graphic novel PDF:
```py
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymupdf
>>> doc = pymupdf.open('Astro City Metrobook Volume 1 - Kurt Busiek.pdf')
>>> page = doc.load_page(11)
>>> page.get_text('dict')
{'width': 477.0, 'height': 733.5, 'blocks': []}
>>> page.get_image_info(xrefs=True)
[{'number': 0, 'bbox': (-9.1199951171875, -8.94000244140625, 486.0, 742.5), 'transform': (495.1199951171875, 0.0, -0.0, 751.4400024414062, -9.1199951171875, -8.94000244140625), 'width': 2063, 'height': 3131, 'colorspace': 3, 'cs-name': 'ICCBased(RGB,sRGB IEC61966-2.1)', 'xres': 96, 'yres': 96, 'bpc': 8, 'size': 7496511, 'digest': b'O\xb3\xd7j\xd8*\xb2nl\xa4I\x83F\xe3D\xba', 'xref': 4203}]
>>> page.get_images()
[(4203, 4204, 2063, 3131, 8, 'ICCBased', '', 'Im0', 'DCTDecode')]
```
I notice the image has an smask, might this be why it is not reported by `get_text()`? Regardless, this was very unexpected given the `get_text()` documentation, which states "An image block is generated for **all and every image occurrence** on the page" (emphasis from the documentation).

### PyMuPDF version

1.24.14

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
There is a different default WRT which images are considered:
* `.get_image_info()` indeed reports all images - even if they are not fully contained in the visible page part.
* `.get_text("dict")` and friends use the visible page area as default. This may therefore lead to reporting less images. You can enforce an equivalent behavior by specifying `clip=None`.

SMasks are no images in this sense and are therefore not separately extracted. They are completely ignored in both these methods (which is somewhat unfortunate, admittedly), because of which the original image cannot be safely reconstructed from this output. If this is desired, you need to resort to `doc.extract_image()`.

**Comment by pdc1** [comment]
Thanks for the clarification, but as a graphic novel, I can assure you the image is visible. Also, not a clipping issue:
```py
>>> page.get_text("dict", clip=None)
{'width': 477.0, 'height': 733.5, 'blocks': []}
```

Any other thoughts?

**Comment by JorjMcKie** [comment]
Did you not notice this: `'bbox': (-9.1199951171875, -8.94000244140625, 486.0, 742.5)`?
The image is partly outside the visible area - therefore the negative x0/y0 values.

**Comment by JorjMcKie** [comment]
Maybe I forgot some detail. You haven't attached the PDF, so I need to guess a bit: try `clip=pymupdf.ININITE_RECT()`.

**Comment by pdc1** [comment]
OHHHH! Now I see what you mean! I saw the negative bbox but didn't make the connection! My apologies. And yes, the infinite clip works and I get the image data. Thanks!!
