### ISSUE TITLE
document permissions: sometimes dict, sometimes int

### ISSUE THREAD

**Issue by massimosala** [pymupdf/PyMuPDF#419]
I open the same PDF file:
PyMuPDF 1.14.13
fitz.version (14.13', '1.14.0', '20190407064320')
doc.permissions = {'print': True, 'edit': True, 'note': True, 'copy': True}

PyMuPDF 1.14.19
 fitz.version ('1.14.19', '1.14.0', '20190729135612')
doc.permissions = {'print': True, 'edit': True, 'note': True, 'copy': True}

PyMuPDF 1.16.6
fitz.version ('1.16.6', '1.16.0', '20191101185525')
**doc.permissions = -4**

I dont' understand: is this a bug or a change of the *permissions* type ?

I cannot see any clue in the change log:
https://documentation.help/PyMuPDF/changes.html

**Comment by JorjMcKie** [comment]
This has changed with versions 1.16 or later, see here in the change log:

```
16.10 Changes in Version 1.16.0
 ...
• Changed Document.permissions to now contain an integer of bool indicators – was a dictionary before.
```

**Comment by massimosala** [comment]
Hi Jorj. Many thanks four your fast answers.

Can you please ponit me to the docs: how to decode the integer bits?

**Comment by JorjMcKie** [comment]
look here: https://pymupdf.readthedocs.io/en/latest/document/#Document.permissions

Quote: "Contains the permissions to access the document. This is an integer containing bool values in respective bit positions. For example, if _**doc.permissions & fitz.PDF_PERM_MODIFY > 0**_, you may change the document. See Document Permissions for details."

**Comment by massimosala** [comment]
I read it, but it is the first time I see a bit-mapped value and it is negative:
doc.permissions = **-4**

Can you please check and let me know?

**Comment by JorjMcKie** [comment]
This is fine!
I am initializing the permissions field with -1 to make sure everything is allowed (all bits on) for a start.
The integer value as such is irrelevant.

**Comment by massimosala** [comment]
Ehm
1) value is -4, not -1
2) if the value is irrilevant, how can I decode the permissions setted by the author?

The previous method where you decode the fields and permission was a dict is simpler.

**Comment by JorjMcKie** [comment]
Only the single bit values are relevant - there combined integer value is not.
-1 simply means that checks for any of the permission bits is > 0 (successful). This is just the default vaue taken if the programmer does not specify the field. It's not the only value which would do that job. The field is in so far **not an integer** and should not be tested as such.

> The previous method where you decode the bits and permission was a dict is simpler.

Hmmm - obviously a matter of personal taste. What's more important: this is kept compliant with the base library MuPDF and with the PDF definition standard. If you would look at the single bit position definitions: they are more now (8 not 4) and quite sophisticated.

**Comment by massimosala** [comment]
Pardon, perhaps I didn't explain well.

Note: I know -1 is often equivalent to MAX_INT, so all the bits are set.

I read a PDF file.
permissions = -4 = minus 4 (not -1)

Please show me how you decode this value, becase I don't know.

**Comment by JorjMcKie** [comment]
```python
access_ok = bool(doc.permissions & fitz.PDF_PERM_ACCESSIBILITY)
annotate_ok = bool(doc.permissions & fitz.PDF_PERM_ANNOTATE)
... etc. for all the PDF_PERM_* values
```

**Comment by yahiachames** [comment]
hello jorj can i ask how to modify the permessions of a doc ?

**Comment by JorjMcKie** [comment]
Consult [this](https://pymupdf.readthedocs.io/en/latest/vars.html#document-permissions) section of the documentation:
```python
perm = fitz.PDF_PERM_ACCESSIBILITY  # the obsolete, always present permission
# then 'OR' the other desired values in it, like
perm |= fitz.PDF_PERM_PRINT  # permits printing ...
# finally save the document specifying using the permissions value 'perm'
```

**Comment by yahiachames** [comment]
helo again , first of all i want to thank you for this library that i feel really comfortable with ,my task is to make the pdf unchangable its just read only so i thought i should change the permission i did what u ve told me still can make some changes in acrobat so if u had an idea tell me pls ,
thanks in advance

**Comment by JorjMcKie** [comment]
So what did you specify as permission?

**Comment by JorjMcKie** [comment]
Ah, forgot to tell you, that you must also protect the document with an owner-password and some encryption like this:
```python
doc.save("read-only.pdf", permissions=perm, owner_pw="owner", encryption=fitz.PDF_ENCRYPT_AES_256)
```
Will render the following document properties:
![grafik](https://user-images.githubusercontent.com/8290722/111024989-f2299f80-83b7-11eb-8670-69ac6fd55e7b.png)

**Comment by yahiachames** [comment]
hello sorry for the late response last days was like hell 
i ve specified only the printing permission  and i ve encrypted like u said u really sir has thought of anything about pdf lol
one question are u familiar with pdf of type /a archive or something ?

**Comment by yahiachames** [comment]
![image](https://user-images.githubusercontent.com/47031747/111145799-f658e700-8588-11eb-8dea-fd7c0f0fb086.png)

**Comment by yahiachames** [comment]
it also annotation it gives me empry once i tried to extract an arabic text from annotation 
i think its a font problem any advice how to solve it 
![image](https://user-images.githubusercontent.com/47031747/111147890-446eea00-858b-11eb-8d2e-1ea9ef3864f5.png)

**Comment by JorjMcKie** [comment]
> pdf of type /a archive or something

This is a standard (= set of rules) defined for PDFs so they qualify for being an adequate format for archiving, i.e. long-term preservation. This is defined in ISO 19005. For start readings you want to look [here](https://helpx.adobe.com/acrobat/using/pdf-conversion-settings.html#about_pdf_x_pdf_e_and_pdf_a_standards).
PyMuPDF does not yet support creating compliant PDFs.

**Comment by JorjMcKie** [comment]
> extract an arabic text from annotation

For annotations (only 'FreeText' are relevant anyway), only Latin, Greek, Cyrillic, Chinese, Japanese and Korean characters are supported, with the fonts Helvetica, Times-Roman, Courier, Symbol, ZapfDingbats and the CJK language fonts (Chinese, Japanese and Korean). All of them inly with their normal font weight (no bold, no italics).

**Comment by yahiachames** [comment]
so i can't install an arabic font and use it on annotation

**Comment by yahiachames** [comment]
> > pdf of type /a archive or something
> 
> This is a standard (= set of rules) defined for PDFs so they qualify for being an adequate format for archiving, i.e. long-term preservation. This is defined in ISO 19005. For start readings you want to look [here](https://helpx.adobe.com/acrobat/using/pdf-conversion-settings.html#about_pdf_x_pdf_e_and_pdf_a_standards).
> PyMuPDF does not yet support creating compliant PDFs.

lol u don't have no idea how much u ve had helped me here i found what i should write on google

**Comment by JorjMcKie** [comment]
> so i can't install an arabic font and use it on annotation

Correct - unfortunately. Hope this will change some time in my base library MuPDF.

**Comment by yahiachames** [comment]
don't worry u ve arleady helped me a lot i ve used arabic font and i ve writed a new pdf in arabic the problem was only with annotation so its okey thank you sir for your time and kindness hope u all the best
