### ISSUE TITLE
embeddedFileCount: integer or function?

### ISSUE THREAD

**Issue by massimosala** [pymupdf/PyMuPDF#420]
I open the same PDF file:
fitz.version ('1.14.13', '1.14.0', '20190407064320')
type(doc.embeddedFileCount) = <type 'int'>

fitz.version ('1.14.19', '1.14.0', '20190729135612')
type(doc.embeddedFileCount) = <type 'instancemethod'>

fitz.version ('1.16.6', '1.16.0', '20191101185525')
type(doc.embeddedFileCount) = <type 'instancemethod'>

Note: where embeddedFileCount is a method, I try
*doc.embeddedFileCount()*
and it returns an integer.

Is this a bug or a change of the *permissions* type ?

I cannot see any clue in the change log:
https://documentation.help/PyMuPDF/changes.html

**Comment by JorjMcKie** [comment]
Another quote from the documentation:

```
16.15 Changes in Version 1.14.16
• Changed Document methods around PDF /EmbeddedFiles to no longer use MuPDF’s “portfolio” functions.
That support will be dropped in MuPDF v1.15 – therefore another solution was required.
• Changed Document.embeddedFileCount() to be a function (was an attribute).
• Added new method Document.embeddedFileNames() which returns a list of names of embedded files.
• Changed Document.deletePage() and Document.deletePageRange() to internally no longer
use Document.select(), but instead use functions to perform the deletion directly. As it has turned out,
the Document.select() method yields invalid outline trees (tables of content) for very complex PDFs and
sophisticated use of annotations.
```

**Comment by massimosala** [comment]
https://github.com/pymupdf/PyMuPDF/tree/master/examples

Please update:
- embedded-export.py
- embedded-list.py

Also: it isn't clear about
*info["file"]*
vs
*info["filename"]*

Many thanks, Massimo

**Comment by JorjMcKie** [comment]
Yes, there are a few example scripts which need updates.
... for which I actually have no time to do. They are examples after all and not part of the core package.

The idea is to give programmer something to start with ...

If you are looking for a ready PyMuPDF utility dealing with embedded files, then use ``python -m fitz ...`` in the command line.

So how about you preparing a PR once you encounter mismatches? This would be great and conform to the spirit of open source ... 😉

The documentation should always be current of course, so no discrepancies should exist in this part.
