### ISSUE TITLE
Is it possible to extract correct text(special symbols like average variable,sigma,etc.)?

### ISSUE THREAD

**Issue by scz526600266** [pymupdf/PyMuPDF#423]
Is it possible to extract correct text(special symbols like average variable,sigma,or some kind of brackets or divsion symbols,etc.) of mathmatical formula or text mixed with special symbols?When I use getText("dict|html,etc") or extractBlock etc,some special symbols just turn into question mark(?).
Use getPixmap capture the entire image could work sometime.However,text mixed with special symbols it would be tedious to do that.
![speical_symbol_can't_show](https://user-images.githubusercontent.com/4705133/71362502-3709c080-25d1-11ea-9c7e-36de1071ba2b.JPG)

**Comment by JorjMcKie** [comment]
Of course, image rendering via pixmaps is always possible. So talking about text extraction only:

All that can be done is extracting the unicode codes of the text - to interpret the meaning of those codes is up to the consuming application (your script). To help in this process, the accompanying font can be used in method ``page.getText("dict")``. That's all.

It is exactly the reverse process compared to when you insert text in a PDF: you provide of unicode characters and a font - the combination of both data controls the appearance. For example, inserting an "S" using the **_Symbol_** font will cause a capital Sigma to appear.

Being a mathematician myself, I am aware that this may be less than satisfactory. But there is no way to get more information out the file than has been put into it upon creation.

If you see this question mark surrounding by a rhombus, then the underlying C library MuPDF was not able to identify the respective character as a valid unicode code [so strictly speaking, the process is not truly the inverted process of text insertion].

**Comment by scz526600266** [comment]
Thank you very much for replying.
> Of course, image rendering via pixmaps is always possible. So talking about text extraction only:
> 
> All that can be done is extracting the unicode codes of the text - to interpret the meaning of those codes is up to the consuming application (your script). To help in this process, the accompanying font can be used in method `page.getText("dict")`. That's all.
> 
I don't quite understand how to use accompanying font in page.getText. How to set specific fontname(for symbols) when using getText() or other extract text functions.
`
doc=fitz.open("some.pdf")
text=doc[n].getText("dict")` 
works fine for some natural language text but missing symbols(like the picture show above,and omega for current testing),some symbols are not showing pretty well or correctly.Currently Tex converted PDF files are hard to extract satisfactory text.I think I need to write some python code solve that problem.
> It is exactly the reverse process compared to when you insert text in a PDF: you provide of unicode characters and a font - the combination of both data controls the appearance. For example, inserting an "S" using the **_Symbol_** font will cause a capital Sigma to appear.
>
I tried to write the code,but it didn't work,just add an empty page.What's wrong with my code?
`import fitz
doc2=fitz.open()
doc2.insertPage(pno=-1,text=u"S",fontname="Symbol",height = 842,color= (0, 0, 0))
doc2.save("A4.pdf")`

As a pymupdf user,I am already very satisfied if I could insert such symbols using fontname="Symbol" parameter(still trying how).For question mark symbol problem ,it seems getPixmap is the only way currently.Hope to find a better way(such as ORC method) in the future !
Thank you again for replying!

**Comment by JorjMcKie** [comment]
I modified some little scripts in this zip:

[text-handling.zip](https://github.com/pymupdf/PyMuPDF/files/3998159/text-handling.zip)

This should explain what I meant - although only the simple case of **_embedded fonts_** is covered. Specifically as per the "Symbol" font: your extracted text contains an "S", but from the fontname you can derive the true meaning as capital sigma.

**Comment by JorjMcKie** [comment]
> Hope to find a better way(such as ORC method) in the future !

I have been working with one or two OCR apps (e.g. ABBYY). So I don't think you will ever get what you want:
Suppose a very clever OCR reader detects a Sigma symbol - what should it do with it? After all you requested it to output **_text_** - not an image. ABBYY offers to leave parts of the interpreted page uninterpreted and include it as an image in its output (which may be e.g. MS Word) ... not much of a help or is it?
Same unsatisfyctory results with LibreOffice and MS Word: try one of them with this admittedly super simple included example PDF: complete crap!

**Comment by scz526600266** [comment]
> I modified some little scripts in this zip:
> 
> [text-handling.zip](https://github.com/pymupdf/PyMuPDF/files/3998159/text-handling.zip)
> 
> This should explain what I meant - although only the simple case of **_embedded fonts_** is covered. Specifically as per the "Symbol" font: your extracted text contains an "S", but from the fontname you can derive the true meaning as capital sigma.

**Comment by scz526600266** [comment]
> I modified some little scripts in this zip:
> 
> [text-handling.zip](https://github.com/pymupdf/PyMuPDF/files/3998159/text-handling.zip)
> 
> This should explain what I meant - although only the simple case of **_embedded fonts_** is covered. Specifically as per the "Symbol" font: your extracted text contains an "S", but from the fontname you can derive the true meaning as capital sigma.

>
`("Fontname 'symb'%SSSSS", "symb")`
So I can insert symbols like %  or numbers."SSSSS" can be any non-symbol and non-number characters in order to be an end flag, when I need to extract them I can use some judge statements get the symbols,is that understanding right?But I tried some symbols(keyboard symbols(*,^,$,~,etc) will still be treated as blank space.Some Ancient Greek symbols and some math symbols predefined in my input method software like ʃ,Γ,Δ,∑,Ε... are not supported as well.
`("Fontname 'symb'%%%*\*%{}><?/][%SSSSS", "symb")` will show
![symbol](https://user-images.githubusercontent.com/4705133/71421459-e9b34f00-26b5-11ea-82ed-6dd9919b4ed6.JPG)
`    ("Fontname 'symb'%%%*\∝θʃΓ∑Δ*%{}><?/][%SSSSS", "symb")`will show many blank spaces in symbols line.
![特殊符号](https://user-images.githubusercontent.com/4705133/71421597-df458500-26b6-11ea-9e5c-a7d313b632ea.JPG)
Is that possible to insert that kind of symbol using pymupdf?Or can but use tex format and converted tool generate PDF,which is not I intend to do in the first place.But it seems that only tex format can support such large set of symbols.

**Comment by JorjMcKie** [comment]
Well, as I said: my example only uses the Base14 embedded fonts. They all (except the embedded CJK fonts = China, Japan, Korea) are only defined for character codes < 256. What any of these codes will look like with a certain font once inserted in a PDF can be looked up in the Adobe manual pp. 995.

You must use a more advanced font if you need more choices. There are also special mathematical fonts out there, e.g. thse coming with Mathematica.
Also pls. note that not all viewers are clever enough to display all fonts as expected, and - in contrast to what they should: the Base14 fonts + CJK must actually be supported by every viewer.
What I'm saying is this: if you see an unexpected blank, be sure to try an alternative viewer as well.

PyMuPDF should support complex fonts as well. I have tested seveal China and Hindi fonts (mostly pre-installed on my Win 10 machine) and they worked.

The only issue I am still having (should not be of concern in your case), the correct translation of multi-unicodes into one glyph (= what you see in the PDF). This only works once I am telling my base library, which (natural) language to use ...

**Comment by scz526600266** [comment]
> Well, as I said: my example only uses the Base14 embedded fonts. They all (except the embedded CJK fonts = China, Japan, Korea) are only defined for character codes < 256. What any of these codes will look like with a certain font once inserted in a PDF can be looked up in the Adobe manual pp. 995.
> 
> You must use a more advanced font if you need more choices. There are also special mathematical fonts out there, e.g. thse coming with Mathematica.
> Also pls. note that not all viewers are clever enough to display all fonts as expected, and - in contrast to what they should: the Base14 fonts + CJK must actually be supported by every viewer.
> What I'm saying is this: if you see an unexpected blank, be sure to try an alternative viewer as well.
> 
> PyMuPDF should support complex fonts as well. I have tested seveal China and Hindi fonts (mostly pre-installed on my Win 10 machine) and they worked.
> 
> The only issue I am still having (should not be of concern in your case), the correct translation of multi-unicodes into one glyph (= what you see in the PDF). This only works once I am telling my base library, which (natural) language to use ...
If I want to use a more advanced font.What should I do?Shall I change `("Fontname 'china-s': 我很喜欢德国！德国是个好地方！", "china-s"),` "china-s" into my new font name:"Microsoft YaHei" e.g.?

**Comment by JorjMcKie** [comment]
[chinese-tb-yahei.zip](https://github.com/pymupdf/PyMuPDF/files/4003146/chinese-tb-yahei.zip)

This example uses a fontfile stored on the computer (Windows example). A text with mixed English and Chinese characters is fit in a given rectangle.
That rectangle is rotated afterwards and surrounded with a border ...

**Comment by scz526600266** [comment]
> [chinese-tb-yahei.zip](https://github.com/pymupdf/PyMuPDF/files/4003146/chinese-tb-yahei.zip)
> 
> This example uses a fontfile stored on the computer (Windows example). A text with mixed English and Chinese characters is fit in a given rectangle.
> That rectangle is rotated afterwards and surrounded with a border ...

I got it!`.ffile="my font path" page.insertFont(fontname="f0", fontfile=ffile)` is the key point.Thank your very much!
