### ISSUE TITLE
Package not installing under ActiveState Python 2.7.13 32bit

### ISSUE THREAD

**Issue by ignaciordc** [pymupdf/PyMuPDF#424]
Package not installing under ActiveState Python 2.7.13 32bit

Typing "pip install PyMuPDF" under Python 2.7.13 I get the following error:

 Building wheel for PyMuPDF (setup.py) 
ERROR:
...
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I./mupdf/include -I./mupdf/include/mupdf -IC:\Python32\include -IC:\Python32\PC /Tc./fitz/fitz_wrap.c /Fobuild\temp.win32-2.7\Release\./fitz/fitz_wrap.obj
  fitz_wrap.c
  **c:\python32\include\pyport.h(190) : fatal error C1189: #error :  "Python needs a typedef for Py_ssize_t in pyport.h."**

**Comment by JorjMcKie** [comment]
I am no longer uploading wheels for 32bit Python versions.
So your pip tries to generate the package from sources. Which in turn won't work without **_MuPDF_** being installed.

Please use a 64bit Python.
I am also recommending to upgrade to Python version 3.

However, if you have absolutely no way to do any of this I am willing to send you a 32bit wheel.

**Comment by ignaciordc** [comment]
Jorj,

thanks a lot for your answer.
Yep, it makes sense. So, I'll go to the roots and begin fiddling with the
MuPDF c sources.
I did install it with 64 bit without problems, and was surprised to see the
32bit breaking.
However, we still have packages that are tied to the 32bit interpreter...
;-(

i would appreciate if you can email me the 32 wheel, while I work on the
muPDF sources.

Thanks a lot,
   Ignacio

**Comment by ignaciordc** [comment]
Oh, I forgot:
Compiled with MS VC9 (2008)...
Thanks,
    Ignacio

**Comment by JorjMcKie** [comment]
Por favor, descargalo de aquí: https://github.com/pymupdf/PyMuPDF/releases/tag/1.16.10

**Comment by ignaciordc** [comment]
Thanks a lot!

One last question: is it correct to think that the extensions PyMuPDF
incorporates assumes pages with one single colorspace for its objects?
    I wanted to use CMYK+SPOT or device-N with 7 colors...

Ignacio

**Comment by JorjMcKie** [comment]
Not sure if I fully understand.
PyMuPDF only supports 3 colorspaces, gray, rgb and cmyk i.e. 1, 3 or 4 bytes per pixel). Each with or without transparency.
It makes no assumption like you are indicating.

The versions I am currently publishing also contain no ICC support (although this would be possible in MuPDF). The main reason for this is that in rare occasions (of ill structured PDFs), the sublibrary will bring down the Python interpreter - and I have yet not found a way to prevent this.
This support gap only has minor consequences, see #397.
