### ISSUE TITLE
PolygonAnnotation in 1.16.10 version 

### ISSUE THREAD

**Issue by PCarle** [pymupdf/PyMuPDF#426]
with the new version (1.16.10) polyAnnots are placed in strange places!

```python 
import fitz
print(fitz.__doc__)

red = (1, 0, 0)
blue = (0, 0, 1)
displ = (0, 50, 0, 50)
r = fitz.Rect(50, 100, 220, 135)

doc = fitz.open()
page = doc.newPage()

for i in range(7):
    page.insertText(r.br + (10, 0), "texte_"+ str(i), color=red)
    r += displ

words = page.getTextWords()
for (x0,y0,x1,y1,w,blocknum ,line,wordnum) in words:
    annot = page.addPolygonAnnot([[x0,y0],[x1,y0],[x1,y1],[x0,y1],[x0,y0]])
    annot2=page.addRectAnnot(fitz.Rect(x0,y0,x1,y1))
    #annot.setOpacity(0.3)
    annot.setBorder(width=1.3)
    dgreen=fitz.utils.getColor('DARKGREEN')
    annot.setColors(stroke=dgreen, fill=dgreen)
    annot.update()
    
page = doc.reload_page(page)  # refresh the page before taking pictures
pix=page.getPixmap(matrix=fitz.Matrix(fitz.Identity).preScale(3,3),alpha=True,colorspace="RGBA")

from PIL import Image, ImageTk
mode = "RGBA"
img = Image.frombytes(mode, [pix.width, pix.height], pix.samples)

from matplotlib import pyplot as plt
import matplotlib as mpl
mpl.rc("savefig", dpi=300)
plt.figure(figsize = (20,20))
fig, ax = plt.subplots(figsize=(18, 20))
ax.imshow(np.asarray(img))
```

results:
![polyannotsPyMupdf1_16_10png](https://user-images.githubusercontent.com/16350743/71820960-180b3400-3091-11ea-9690-93885a692955.png)

p.s setOpacity have a strange behavior also !

**Comment by JorjMcKie** [comment]
Found the misplacement error.
What is the opacity problem?

**Comment by PCarle** [comment]
if i uncomment setOpacity! polygons are invisibles !

**Comment by JorjMcKie** [comment]
Ok, thanks. This has been addressed, too.
The output of your script now looks like this as it should:
![grafik](https://user-images.githubusercontent.com/8290722/72715715-5c91d780-3b47-11ea-86e2-7a9003a76bf6.png)
Uncommenting ``setOpacity``:
![grafik](https://user-images.githubusercontent.com/8290722/72715803-86e39500-3b47-11ea-9e0b-4ee3098cc1ed.png)

**Comment by JorjMcKie** [comment]
If you tell me which wheel you would require, I can send you a preview version so you can confirm that the is solved.

**Comment by JorjMcKie** [comment]
Official release v1.16.11 is out.

**Comment by PCarle** [comment]
using 1.16.13 version i have a strange behaviour with Annotation.setOpacity
```python 
# -*- coding: utf-8 -*-
import sys
print("Python", sys.version, "on", sys.platform, "\n")
import fitz
print(fitz.__doc__, "\n")

import os
print (os.getcwd())
from matplotlib.pyplot import imshow
import numpy as np
from PIL import Image

def print_descr(rect, annot):
    """Print a short description to the right of an annot rect."""
    annot.parent.insertText(rect.br + (10, 0),
                    "'%s' annotation" % annot.type[1], color = red)
    
red    = (1, 0, 0)
blue   = (0, 0, 1)
gold   = (1, 1, 0)

border = {"width": 1.3}
displ = fitz.Rect(0, 50, 0, 50)
r = fitz.Rect(50, 100, 220, 135)

doc = fitz.open()
page = doc.newPage()

annot = page.addPolygonAnnot([r.bl, r.br, r.tr,r.tl])
annot.setOpacity(0.5)
annot.setBorder(border)
annot.setColors(stroke=blue,fill=blue)
annot.update()
print_descr(annot.rect, annot)
print("added 'Polygon'")
page.insertText(r.bl + (10, -10),"Test de transparence")


pix=page.getPixmap(matrix=fitz.Matrix(fitz.Identity).preScale(3,3),alpha=True,colorspace="RGBA")

from PIL import Image, ImageTk
mode = "RGBA"
img = Image.frombytes(mode, [pix.width, pix.height], pix.samples)

from matplotlib import pyplot as plt
import matplotlib as mpl
mpl.rc("savefig", dpi=300)
plt.figure(figsize = (20,20))
fig, ax = plt.subplots(figsize=(18, 20))
ax.imshow(np.asarray(img))
#ax.imshow(plt.imread(imgdata))
plt.show()
```
Results
![testopacity](https://user-images.githubusercontent.com/16350743/77329512-5c1be580-6d1e-11ea-8c0e-5cdb45207eab.png)

if i comment annot.setOpacity() the result is :
![testopacity_noOpacity](https://user-images.githubusercontent.com/16350743/77329677-99807300-6d1e-11ea-81f7-40356a93329f.png)

Patrice

**Comment by JorjMcKie** [comment]
Before taking pixmaps of a page (or its annotations) after annotations have been added or changed on it, the page **_must be reloaded_**, i.e. the statement ``page = doc.reload_page(page)`` must be executed after all annotation changes and before ``pix = page.getPixmap(...)``, or ``pix = annot.getPixmap(...)`` respectively.
Only this forces MuPDF to finalize every appearance detail.

BTW PyMuPDF haas no colorspace named "RGBA", just "RGB". The alpha attribute is included by a separare argument. It didn't harm in this case because an invalid specification is silently replaced by ``fitz.csRGB`` ...
