### ISSUE TITLE
Extra symbols appearing in text output

### ISSUE THREAD

**Issue by juviwhale** [pymupdf/PyMuPDF#431]
## Description

Text extracted from a PDF contains symbols that do not *appear* in the rendered PDF and that are not returned by other PDF text extractors, specifically pdftotext.

## To Reproduce

Get text from attached example PDF
```python
file_name = 'cs_fcm_auth_ref_en.pdf'
doc = fitz.open(file_name)
page = doc[0]
text = page.getText('text')
```

The text produced is:
```
EUROPEAN COMMISSION 
DIRECTORATE-GENERAL HEALTH AND FOOD SAFETY 
 
Safety of the Food Chain 
Unit E2 Food Processing Technologies and Novel Foods 
SANTE E2/JB (2019) 
 
CCoonnttaacctt  ppooiinnttss  ffoorr  tthhee  ccoom
mppeetteenntt  aauutthhoorriittiieess  ooff  tthhee  M
Meem
mbbeerr  SSttaatteess  
ffoorr  FFoooodd  CCoonnttaacctt  M
Maatteerriiaallss  
 
Last updated: September 2019 
 
 
 
The data contained in this document includes the names and addresses of the national competent 
authorities designated to be responsible in its territory for food contact materials including those 
designated to receive applications for authorising substances to be used in food contact materials or 
processes for recycling materials for food contact, which may include individuals. This information is 
published by the European Commission on its website. A privacy statement can be found at the end of this 
document. 
```

*Note:*
1) The extra characters e.g. `CCoonnttaacctt` and `aauutthhoorriittiieess`
2) The lack to the text `confidential` that appeared at the top of the PDF

Now this may just be a strangely produced PDF and that is the true text, however when get the text with the [pdftotext](https://www.xpdfreader.com/pdftotext-man.html) utility the text results better match the expected text.

e.g. 
```
pdftotext cs_fcm_auth_ref_en.pdf
```

Produces
```
confidential

EUROPEAN COMMISSION
DIRECTORATE-GENERAL HEALTH AND FOOD SAFETY

Safety of the Food Chain
Unit E2 Food Processing Technologies and Novel Foods

SANTE E2/JB (2019)

Contact points for the competent authorities of the Member States
for Food Contact Materials
Last updated: September 2019

The data contained in this document includes the names and addresses of the national competent
authorities designated to be responsible in its territory for food contact materials including those
designated to receive applications for authorising substances to be used in food contact materials or
processes for recycling materials for food contact, which may include individuals. This information is
published by the European Commission on its website. A privacy statement can be found at the end of this
document.

confidential
```

## Configuration
PyMuPDF 1.16.10: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-12-21 07:31:32.
Built for Python 3.7 on darwin (64-bit).

## Additional context

[Example file source](https://ec.europa.eu/food/sites/food/files/safety/docs/cs_fcm_auth_ref_en.pdf)

[cs_fcm_auth_ref_en.pdf](https://github.com/pymupdf/PyMuPDF/files/4100591/cs_fcm_auth_ref_en.pdf)

**Comment by JorjMcKie** [comment]
Oha, this is a hard one:
When looking at the PDF internals I found that those repeated characters are indeed coded multiple times. It is not a question of using the text rendering operator ``Tr`` for simulating bold text, as I expecting at first.
No: in the lines starting with "Contact points ..." every single character really occurs twice with slightly different coordinates and also in two different colors: one is black, the other some gray.
Also my various PDF viewers react differently when copy / pasting that text:

* **Adobe Acrobat:** cannot read the document at all (version 2019.021.20061)
* **Foxit:** "Contact points"
* **SumatraPDF:** "Co on nt ta ac ct t p po oi in nt ts s"
* **MS Edge browser:** "C Co on nt ta ac ct t  p po oi in nt ts "
* **Mozilla Firefox browser:** "Coonnttaaccttppooiinntts"
* **Nitro reader 5:** "C
C
o
o
n
n
t
t
a
a
c
c
t
t


p
p
o
o
i
i
n
n
t
t
s
"
* **PDF-Xchange Viewer:** "CCoonnttaacctt  ppooiinntts"

So I am afraid there is nothing I can do by modifying PyMuPDF. The only solution is to write a script with in-built tolerance against minimal text position variances. For example by using ``page.getText("rawdict")``.
All text extractors producing a more satisfactory output therefore do include some application logic which does this type of thing.

For example the "rawdict" output of the first character "C" of "Contact points" looks like this:

```json
    {
        "size": 18.0,
        "flags": 16,
        "font": "KFOLLJ+Calibri-Bold",
        "color": 12632256,
        "chars": [
            {
                "origin": [46.439998626708984, 198.239990234375],
                "bbox": [46.439998626708984, 184.739990234375,
                         55.967342376708984, 202.739990234375],
                "c": "C"
            }
        ],
        "bbox": [46.439998626708984, 184.739990234375,
                 55.967342376708984, 202.739990234375]
    },
    {
        "size": 18.0,
        "flags": 16,
        "font": "KFOLLJ+Calibri-Bold",
        "color": 0,
        "chars": [
            {
                "origin": [45.71999740600586, 197.52001953125],
                "bbox": [45.71999740600586, 184.02001953125,
                         55.24734115600586, 202.02001953125],
                "c": "C"
            }
        ],
        "bbox": [45.71999740600586, 184.02001953125,
                 55.24734115600586, 202.02001953125]
    },
```

Notice the minimal differences of the "origin" (bottom left character coordinate) values (and also the different colors).
Some application logic is needed to treat those two, _almost_ overlapping "C" characters to be identical and ignore one of them ...

**Comment by JorjMcKie** [comment]
Couldn't rest until giving you a start at least. Here is a script which outputs the text corectly ...
[doubles.zip](https://github.com/pymupdf/PyMuPDF/files/4103557/doubles.zip)

**Comment by juviwhale** [comment]
Great thank you very much for the script, I am adding it to my workflow.

Regarding the other difference: the missing `confidential` text at the top and bottom of the page.

*I apologize as I gave you a different PDF than my text above was generated from. The referenced PDF to test is 
[cs_fcm_auth_ref_en-2.pdf](https://github.com/pymupdf/PyMuPDF/files/4105380/cs_fcm_auth_ref_en-2.pdf)
(the document is not confidential anymore as it originally stated) however on this version of the same PDF you will notice two `'confidential'` text strings in the rendered PDF one at the top and one at bottom.*
![Screen Shot 2020-01-23 at 12 53 12 PM](https://user-images.githubusercontent.com/6657003/73023696-ee684180-3de0-11ea-8998-671854004c5d.png)


These two words have a few unexpected results:

1) The text is contained in the `page.getText("text")` result however are both returned at the end of the resulting string instead of one at the beginning and one at the end.

```
EUROPEAN COMMISSION 
DIRECTORATE-GENERAL HEALTH AND FOOD SAFETY 
 
Safety of the Food Chain 
Unit E2 Food Processing Technologies and Novel Foods 
SANTE E2/JB (2019) 
 
CCoonnttaacctt  ppooiinnttss  ffoorr  tthhee  ccoom
mppeetteenntt  aauutthhoorriittiieess  ooff  tthhee  M
Meem
mbbeerr  SSttaatteess  
ffoorr  FFoooodd  CCoonnttaacctt  M
Maatteerriiaallss  
 
Last updated: September 2019 
 
 
 
The data contained in this document includes the names and addresses of the national competent 
authorities designated to be responsible in its territory for food contact materials including those 
designated to receive applications for authorising substances to be used in food contact materials or 
processes for recycling materials for food contact, which may include individuals. This information is 
published by the European Commission on its website. A privacy statement can be found at the end of this 
document. 
 
conﬁdential
conﬁdential
```

Looking at the word extraction with `page.getText("words")` you can see that while both are at the end of the resulting list their locations are accurate.

```
[
...
... <TRUNCATED>
...
 (35.99993896484375,
  390.12005615234375,
  89.18924713134766,
  402.12005615234375,
  'document.',
  8,
  12,
  0),
 (277.4280090332031,
  18.600011825561523,
  317.8919982910156,
  29.592012405395508,
  'conﬁdential',
  10,
  0,
  0),
 (277.4280090332031,
  820.52001953125,
  317.8919982910156,
  831.5120239257812,
  'conﬁdential',
  11,
  0,
  0)
]
```

Looking at the documentation you have provided, I see this may be the expected behavior as you write. 

> Return a string of the page’s complete text. The text is UTF-8 unicode and in the same sequence as specified at the time of document creation.

however maintaining (as best as possible) the original physical layout of the text is very important to my use case. **Maybe this here is a feature request and really what I am asking for is an option on the TextPage to attempt to maintain the text layout. I can make a different feature request ticket perhaps? See more below** 

2) That other difference is that those `conﬁdential` text strings are not what they originally appeared to me. The forth character is not `f` but rather `s[3] => 'ﬁ'`. Why such a character was used is unclear to me (maybe some OCR process) and this again could be labeled as just a strangely formatted PDF  and not solvable however the *pdftotext` out appears to return the expected character somehow.

e.g.
```bash
pdftotext cs_fcm_auth_ref_en.pdf
```

Produces:

```
confidential

EUROPEAN COMMISSION
DIRECTORATE-GENERAL HEALTH AND FOOD SAFETY

Safety of the Food Chain
Unit E2 Food Processing Technologies and Novel Foods

SANTE E2/JB (2019)

Contact points for the competent authorities of the Member States
for Food Contact Materials
Last updated: September 2019

The data contained in this document includes the names and addresses of the national competent
authorities designated to be responsible in its territory for food contact materials including those
designated to receive applications for authorising substances to be used in food contact materials or
processes for recycling materials for food contact, which may include individuals. This information is
published by the European Commission on its website. A privacy statement can be found at the end of this
document.

confidential
```

**i.e.**

```
pdftotext_output_str = 'confidential'
# len(pdftotext_output_str) => 12
pymupdfoutput__str = 'conﬁdential'
# len(pymupdfoutput__str) => 11
```

I honestly have no clue how pdftotext is able to correctly produce the text string. **Am I missing something? If not is this something that the TextPage could handle better?**


### Feature Request Thoughts On Additions to TextPage

The particular issues raised by this one example PDF are probably just a few of the very many that could arise and each would most likely need its own scripted resolution, that being said I could see great value in a consolidation of many of these 'fixes' into a single place such that they can be used by others. It appears that this may have been what happened in pdftotext and 'fixes' were added overtime such that the results the utility well-matched the users' expectations. 

Using the options on the [manpage for pdftotext](https://www.xpdfreader.com/pdftotext-man.html) ([and the non-public options in the source code](https://xpdfreader-dl.s3.amazonaws.com/xpdf-4.02.tar.gz) specifically those in TextOutputDev.cc) as a ref, I feel there are many processing options the would be very useful to be utilized in the TextPage. Where some layout analysis could be reflected in the `extractTEXT()` and `extractWORDS()` but also be included at attributes in the extractDICT(). Maybe this sort of feature is `out-of-scope` for your project but it would be highly valuable to how my company needs to use the module.

**Comment by juviwhale** [comment]
Update on 2) of the last comment. It appears that the `pdftotext` utility utilizes a defined Unicode Map (src attached to comment) to handle the char mentioned. The determination of when this mapping is used appears to be complex and depends on various factors. 

```
static struct {
  Unicode u;
  const char *name;
} nameToUnicodeTab[] = {
...
  {0xfb00, "ff"},
  {0xfb03, "ffi"},
  {0xfb04, "ffl"},
  {0xfb01, "fi"},
  {0x246e, "fifteencircle"},
  {0x2482, "fifteenparen"},
...
};
```

Seeing this mapping makes me wonder which is best result, to return characters that may better match the users' exceptions or to return the `true` set of unicode characters. I initially would personally say the latter as `{0x263a, "smileface"},` is a mapping that I would not want for a pipeline that can handle unicode characters. However that said, there are real world cases (like the issue above) where the mapping resolves an existing inconsistency in the PDF data/expectations from rendering.

[UnicodeRemapping.h.zip](https://github.com/pymupdf/PyMuPDF/files/4105812/UnicodeRemapping.h.zip)

**Comment by JorjMcKie** [comment]
First of all, my script also processes the two "confidential" string correctly:

```
conﬁdential


EUROPEAN COMMISSION
DIRECTORATE-GENERAL HEALTH AND FOOD SAFETY

Safety of the Food Chain
Unit E2 Food Processing Technologies and Novel Foods

SANTE E2/JB (2019)

Contact points for the competent authorities of the Member States
for Food Contact Materials

Last updated: September 2019



The data contained in this document includes the names and addresses of the national competent
authorities designated to be responsible in its territory for food contact materials including those
designated to receive applications for authorising substances to be used in food contact materials or
processes for recycling materials for food contact, which may include individuals. This information is
published by the European Commission on its website. A privacy statement can be found at the end of this
document.


conﬁdential
```

The plain ``getText("text")`` method contains no provision to re-arrange text according to any particular reading order. It extract the text in the same sequence as it is coded in the PDF.
Obviously, the **confidential** markers have been added **after** other parts of the PDF had been finished.
This is a common practice: adding headers / footers to a PDF after it is actually ready. The accompanying position data of those pieces take care of correct appearance when shown by a viewer.

Another aspect is: what is a **_"natural"_** reading order? You and I are accustomed to: "from top-left to bottom-right". But ask an Arabian or Chinese guy ...

So. PyMuPDF provides all the information without any such bias.

Yet another aspect: if you have a complex PDF page, say one with two text columns plus an intermingled table: try pdftotext on this!

There are just systematic limits for text extractions ...

Of course I could publish the script of today as a sample solution ... to the bunch of other solutions already there.
Although I think you are right, and it is time to overhaul this bunch and give it some intelligible overall approach.
I would be greatful for your input on how to attack this.

**Comment by JorjMcKie** [comment]
As per the unicode encodings:
MuPDF handles those automatically. PyMuPDF ``getText()`` option "rawdict" returns the unicode of each character as an integer.

If it comes to the **interpretation** of this code, you obviously need to know the **font** under which the character had been encoded. I.e. you need to know it was the "Symbol" font to interpret 0xe5 correctly as the mathematical summation symbol and not as charatcer 'å'.

**Comment by juviwhale** [comment]
Re: 
> my script also processes the two "confidential" string correctly:

That is awesome! I hadn't realized that nor retried that same doc with the script. Thanks again for making that.

> Another aspect is: what is a "natural" reading order? You and I are accustomed to: "from top-left to bottom-right". But ask an Arabian or Chinese guy ...


Also, I agree with you it not being possible to assume a natural reading order which and any attempts to do so could almost be ethnocentric. I am not familiar enough with the PDF spec to know if the needed attributes are available to produce a text string that closely resembles the rendered PDF based on reading order. 

> Yet another aspect: if you have a complex PDF page, say one with two text columns plus an intermingled table: try pdftotext on this!

I was curious about this so I played around with some of the example docs that google docs provides. There were many issues but I was actually surprised at the robustness of the text layout.

```
pdftotext -layout -f 1 -l 1 compressed.tracemonkey-pldi-09.pdf
```
![Screen Shot 2020-01-23 at 3 58 04 PM](https://user-images.githubusercontent.com/6657003/73034411-aace0180-3df9-11ea-96a6-8fc2e85b2ae3.png)


```
pdftotext -layout -f 1 -l 1 Brochure.pdf 
```
![Screen Shot 2020-01-23 at 3 59 04 PM](https://user-images.githubusercontent.com/6657003/73034419-af92b580-3df9-11ea-80e1-d9a57f828249.png)

```
 pdftotext -layout -f 1 -l 1 Petresume.pdf
```

![Screen Shot 2020-01-23 at 4 00 08 PM](https://user-images.githubusercontent.com/6657003/73034428-b6b9c380-3df9-11ea-8b96-fbf86bc58a31.png)

I feel those results are impressive **however** I don't want to give the impression that I regard the pursuit as trivial in anyway nor by providing the examples am I saying anything like *'hey PDFTOIMAGE does this, won't you", the project has had almost 25 years to produce those results.  I honestly now wonder if such textual layout features should even be in the scope of PyMuPDF project. Such functional could easily warrant its very own project dedicated to the pursuit. 

> Although I think you are right, and it is time to overhaul this bunch and give it some intelligible overall approach.
I would be greatful for your input on how to attack this.


I will try to think of some possible useful input to provide. Currently I am only able to muster a list of 'issues' I have had with particular PDFs rather than a input on a particular approach.

Of the items in that list of 'issues', one that I will mention because it has come up a lot is in dealing with the text and dict output of a pdf page with 'hidden' text. Specifically, 'hidden' text being defined here as either 
- invisible text (happens with the horrible auto-OCR some scanners add)
- clipped text (behind some overlapping opaque element)

Having these 'hidden' text elements included in the text and dict output has lead to some strange user experiences in our project.

**Comment by JorjMcKie** [comment]
Thanks you very much for this input indeed!
It makes a big difference to have that type feature request (also like in your other request request related to redact annotations) as opposed to presuming user interests by just looking at areas where issues are being found or questions are being focused on ...

**Comment by JorjMcKie** [comment]
Ahh ... forgot to send you an improved / corrected version of that script:
[doubles.zip](https://github.com/pymupdf/PyMuPDF/files/4107640/doubles.zip)

**Comment by juviwhale** [comment]
I had forgot to add the referenced exampled PDF in my comment above. Adding here for future reference if needed.
- [compressed.tracemonkey-pldi-09.pdf](https://github.com/pymupdf/PyMuPDF/files/4129416/compressed.tracemonkey-pldi-09.pdf)
- [Brochure.pdf](https://github.com/pymupdf/PyMuPDF/files/4129420/Brochure.pdf)
- [Petresume.pdf](https://github.com/pymupdf/PyMuPDF/files/4129412/Petresume.pdf)

**Comment by JorjMcKie** [comment]
Can we close this issue?
Time permitting, I will eventually add functionality to approximate the ``pdftotext`` functionality.
