### ISSUE TITLE
How to shrink an output PDF that got inserted a a PNG file

### ISSUE THREAD

**Issue by axlgit** [pymupdf/PyMuPDF#432]
Having the input PDF file sise of 91kb and the PNG image sizse 7kb when I do .insertImage and then save the PDF file output size is 1105kb.

The insertion works perfectly and the trasparency of the PNG file is just good but the size is too big.
I have to stick to PNG because of the transparent background.
The PNG dimensions are 1099x236+0+0

The same happens with BMP (with transparent background) but in that case the image file size is indeed more than 1Mb big and hence is somehow expected.

Examples will follow

**Comment by JorjMcKie** [comment]
Do you have a handy example for me? I would like to try a few things ...

**Comment by axlgit** [comment]
Hi,

the input PDF would be theis

http://www.pdf995.com/samples/pdf.pdf

the PNG to insert is the one I attached

```
**23/01/2020  08:40            15.367 arrow.png
23/01/2020  08:42           433.994 pdf.pdf
23/01/2020  09:08         1.703.889 pdfout.pdf**
```

The code I use

```
import PyPDF2
import fitz

input_file = "pdf.pdf"
output_file = "pdfout.pdf"
inserted_file = "arrow.png"

input_pdf = PyPDF2.PdfFileReader(input_file,"rb")
p = input_pdf.getPage(0)

w_page = p.mediaBox.getWidth()
h_page = p.mediaBox.getHeight()

image_rectangle = fitz.Rect(round(w_page*0.50),round(h_page*0.90),round(w_page*0.9),round(h_page*0.95))

file_handle = fitz.open(input_file)
first_page = file_handle[0]

first_page.insertImage(image_rectangle, filename=inserted_file)
file_handle.save(output_file)

```

PyPDF2 is there to compute the height and the width of the PDF page.


![arrow](https://user-images.githubusercontent.com/57374262/72966997-80138700-3dc0-11ea-9884-181e89e83a53.png)

**Comment by axlgit** [comment]
I have attached the arrow as a zip just in case.

[arrow.zip](https://github.com/pymupdf/PyMuPDF/files/4101940/arrow.zip)

**Comment by JorjMcKie** [comment]
If you use the following script, the output filesize is 442 KB, compared to the input 424 KB.
You also need no other package to determine page or image dimensions, by the way.

```python
import fitz


doc = fitz.open("pdf.pdf")
page = doc[0]

img_rectangle = fitz.Rect(
    page.rect.width * 0.5,
    page.rect.height * 0.9,
    page.rect.width * 0.9,
    page.rect.height * 0.95,
)

page.insertImage(img_rectangle, filename="arrow.png")
doc.save("new-pdf.pdf", deflate=True)
```

**Comment by JorjMcKie** [comment]
The pivotal parameter is ``deflate`` in the document ``save`` method.

**Comment by axlgit** [comment]
Thanks ! I looked for an option like deflate but in the wrong place (in .InsertImage).

I will close this one, but I have another question: I would like to save the new PDF as an entire image wrapped as PDF doc.

Is there any oneliner for it or I have to save the doc as image, import it and then save as PDF?
This is a totally different question hence let me know if I have to move it somewhere else than this thread.

Alex

**Comment by JorjMcKie** [comment]
You mean something like converting a PDF to an equal looking other PDF, but each original page is an image in the new PDF?
If I understood you right, here is something like that:

```python
for page in in_pdf:
    pix = page.getPixmap(matrix=fitz.Matrix(2, 2))  # double resolution for better image quality
    out_page = out_pdf.newPage(width=page.width, height=page.height)
    out_page.insertImage(page.rect, stream=pix.getImageData("png"))

out_pdf.save("output.pdf", deflate=True)
```

Instead of the "png" parameter you can also use "ppm" - a much simpler image format, to improve performance.
PPM images are widely unknown under Windows. This is adequate in our case as we do not need transparency.

**Comment by axlgit** [comment]
Thanks, I'm trying to test your piece of code. I guess I need to create new PDF doc called out_pdf but when doing help(fitz) or help(fitz.open) I don't seem how to initialize a new PDFdoc/stream.

Other methods like moving pages suppose such a stream is already open for writing: maybe from an existing PDF file?

So: how do I initialize out_pdf?

Sorry for such questions, I use Python but I might not be a super expert :-)

**Comment by axlgit** [comment]
out_pdf= fitz.open()

:-)

**Comment by JorjMcKie** [comment]
I should have been more explicit:
in_pdf = fitz.open("something-there.pdf")
out_pdf = fitz.open()

**Comment by axlgit** [comment]
Minor correction for those who will read this.

for page in in_pdf:
    pix = page.getPixmap(matrix=fitz.Matrix(2, 2))  # double resolution for better image quality
    out_page = out_pdf.newPage(width=page. **rect.** width, height=page. **rect.** height)
    out_page.insertImage(page.rect, stream=pix.getImageData("png"))

out_pdf.save("output.pdf", deflate=True)

Great! Thank you Jori!

**Comment by axlgit** [comment]
How to remove the "bug" label?

**Comment by JorjMcKie** [comment]
done
