### ISSUE TITLE
Inserted image flipped horizontally

### ISSUE THREAD

**Issue by axlgit** [pymupdf/PyMuPDF#433]
In a series of PDFs the code here below puts the inserted image in the expected position in many of them but in some the image is mirrored related to the horizontal ax of the page.

```
import fitz

in1_pdf="in1.pdf"
out1_pdf="out1.pdf"
in2_pdf="in2.pdf"
out2_pdf="out2.pdf"

image="arrow.png"
doc1=fitz.open(in1_pdf)
doc2=fitz.open(in2_pdf)
tlx_perc=0.5
tly_perc=0.9
brx_perc=0.85
bry_perc=0.95

for in_page in doc1:
    img_rectangle = fitz.Rect(
            in_page.rect.width * tlx_perc,
            in_page.rect.height * tly_perc,
            in_page.rect.width * brx_perc,
            in_page.rect.height * bry_perc,
            )
    
    in_page.insertImage(img_rectangle, filename=image)

for in_page in doc2:
    img_rectangle = fitz.Rect(
            in_page.rect.width * tlx_perc,
            in_page.rect.height * tly_perc,
            in_page.rect.width * brx_perc,
            in_page.rect.height * bry_perc,
            )
    
    in_page.insertImage(img_rectangle, filename=image)

doc1.save(out1_pdf, deflate=True)
doc2.save(out2_pdf, deflate=True)
```

out1.pdf is the expected result, out2.pdf is the output with the image flipped horizontally.

![ok_imm](https://user-images.githubusercontent.com/57374262/73023958-dae2c800-3e2c-11ea-8584-457a2582baa9.jpg)

^^^^^ out1.pdf ^^^^^

![ko_imm](https://user-images.githubusercontent.com/57374262/73023959-dae2c800-3e2c-11ea-9484-d8204fbadbc5.jpg)

^^^^^ out2.pdf ^^^^^

What can I check in terms of properties of PDF source to find maybe a difference that may explain the different output?

TIA,

Alex

**Comment by JorjMcKie** [comment]
This problem is explained in the documentation - including how to resolve it: https://pymupdf.readthedocs.io/en/latest/faq/#misplaced-item-insertions-on-pdf-pages.

You should take the time to read the docs - at least the tutorial and the recipes chapter.

**Comment by axlgit** [comment]
Thanks, when you are in a hurry may be obliged to leran by trial and error.
Many thanks for your time in replying, I will definitely go through the docs.

Alex

**Comment by JorjMcKie** [comment]
I understand ... and I didn't mean to cut you off.
Please do continue asking stuff - PyMuPDF definitely has become a fairly large package.
I am probably beyond the point where I can imagine which aspects may be stumbling stones for new users.
Just ask and I will either provide a verbose answer or point you to a place where this is covered in the docs.
Let me also invite you to improve the documentation. For example there may be gaps for providing gentle starts to newcomers ... or maybe basic stuff about PDFs, or whatever.

**Comment by padschino** [comment]
@JorjMcKie The Link you provided is dead in the meantime:
https://pymupdf.readthedocs.io/en/latest/faq/#misplaced-item-insertions-on-pdf-pages

I couldn't find the point to this issure in the current FAQs.

**Comment by JorjMcKie** [comment]
> @JorjMcKie The Link you provided is dead in the meantime: https://pymupdf.readthedocs.io/en/latest/faq/#misplaced-item-insertions-on-pdf-pages
> 
> I couldn't find the point to this issue in the current FAQs.

This is because we have changed PyMuPDF such that this issue should no longer occur.
We therefore removed the description referring to a non-problem.

Unfortunately, there exists a corner case where this issue can still pop up, but a solution has been identified already.

**Comment by padschino** [comment]
Thanks for that super quick reply.
Actually my problem is slightly different, but I thought that could help me anyway.

In my case I want to inset an image from one pdf into another pdf.

```
img_dicts = page.get_image_info(xrefs=True)
for img_dict in img_dicts:
     print(img_dict)
```

But when looking at the img_dict in the original pdf the transform matrix tells me that the image is flipped already:
'bbox': (0.0, 0.3199462890625, 595.2000122070312, 842.0),
'transform': (595.2000122070312, 0.0, -0.0, -841.6800537109375, 0.0, 842.0)

So when inserting this image into another pdf it is consequently also flipped.

**Comment by JorjMcKie** [comment]
Yes, that sounds different indeed.
In PyMuPDF there currently is no way to flip images or pixmaps, respectively doing other transformations directly.
Only rotations by 90° multiples can be selected when inserting.
So you must use PIL or another image package for this case.

**Comment by padschino** [comment]
Alright, thank you for the confirmation.
I just wanted to make sure, that I am not missing a simpley way to solve this :)

**Comment by dimas-adi-kris** [comment]
I'm still facing this issue. But with insert_htmlbox

Python : 3.10
PyMuPDF : 1.23.26

Possible cause : first image is rendered with py3o library which convert odt into pdf. second image is rendered using wkhtmltopdf. Both are rendered, merged with PyPDF2, saved, read again by PyMuPDF to insert htmlbox. 

![image](https://github.com/pymupdf/PyMuPDF/assets/62425346/808c8cd2-9cea-40a2-ad87-9fe01e136424)

![image](https://github.com/pymupdf/PyMuPDF/assets/62425346/dc4fec5f-6e04-4170-90ab-50eb86695ea6)
*I've cleaned up some text detail in the image due to my company's privacy. But trust me, I'm not manipulating the issue. I just erase some sensitive text

```

        doc = fitz.open(input_pdf)
        for page in doc:
                
            html = '''
            <style>
            .content {
                color: red;
                background-color: blue;
            }
            </style>
            <p class="content">''' + text + '''</p>
            '''
            page.insert_htmlbox((position[0], position[1], position[0] + 250, position[1]+100), html, css="* {font-family:}")
        doc.save(output_pdf, incremental=True, encryption=PDF_ENCRYPT_KEEP)
```

**Comment by JorjMcKie** [comment]
> Alright, thank you for the confirmation. I just wanted to make sure, that I am not missing a simpler way to solve this :)
> 
> Could it be a solution to insert the image into the new pdf and then manipulate the bbox and transform attribues?

No, this won't work either ... 😒
