### ISSUE TITLE
PDF redaction 

### ISSUE THREAD

**Issue by juviwhale** [pymupdf/PyMuPDF#434]
Is PDF redaction on the roadmap? To be more clear, I am defining PDF redaction as content identification + removal of information from a PDF document in the area specified in a reliable and secure way.

MuPDF 1.16 added `Add Redact annotation type and function to apply redactions.` however it is not clear to me what the specifics of that functionality are.

## Describe the solution you'd like

My needs in redacting  of a PDF are in the content removal portion:
- Given a specific rect of a PDF
- Find all elements that are fully or partially within that rect
- Remove the elements from PDF that are entirely within the rect
- Modify the elements from PDF that are partially within the rect while maintaining the layout of the parts of the elements not within (e.g. mask images, remove only some of text elements while maintaining the layout flow.)
- Adding a redaction annotation (would be nice to support the OverlayText)

## Are there several options for how your request could be met?

I have seen multiple approaches to the API of 'resolving' where the redactions annotations are to be placed.

The two main approaches to resolving redactions in various utilities are:
- String match based (sometime with regular expression)
- and Box area based (resolved both text and images)

Both are non-trivial of course. My personal needs are for the box area approach.

## Describe alternatives you've considered

The best *opensource* project I have seen so far for these needs is [pdfsweep by iText](https://itextpdf.com/en/products/itext-7/pdfsweep). While it is open source it not free to use. Additionally is has numerous issues with various image compressions. 

## Additional context

**Could be a duplicate of #344**

- [Adobe PDF Addendum](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/pdf_reference_addendum_redaction.pdf)

**Comment by JorjMcKie** [comment]
Thanks a lot for this input.
I haven't given this new MuPDF more than an only superficial reading, but will now look deeper into it over the next weeks.

**Comment by JorjMcKie** [comment]
First results of reviewing MuPDF code:
* Redaction annotations can be inserted, modified and deleted like any other annot type.
* OverlayText is **not** supported. It seems that only a red outline indicates the respective area.
* The redacted area is either the annotation's rectangle or a specified quadrilateral within that rectangle.
* The PDF page can be **_redacted_** which removes content covered by one of the existing redaction annotations. All redaction annots will be removed by this function. The content removal extends to text. It remains to be seen what exactly happens in case of a character on the borderline of a redact area. As far as I can see, images are not covered.

More to follow ...

**Comment by juviwhale** [comment]
That sounds very promising!

**Comment by JorjMcKie** [comment]
@juviwhale - Have been working for you 😉 and implemented redaction annotations.

## Functionality
1. Add a redaction annotation: ``Page.addRedactAnnot(quad)``. This will mark an area given by ``quad`` as a candidate for removal. "Quad" may be a rectangle or a quadrilateral, however de-facto always the annot rectangle will be regarded (a MuPDF restriction). In the following example I marked a text block:
![img-redact](https://user-images.githubusercontent.com/8290722/75024307-8e140080-546f-11ea-92e4-727001a1ae4b.jpg)

2. Remove redacted areas: ``Page.apply_redactions(mark=False)``. This will **_physically_** remove all text covered by any redaction. You can choose to either leave those areas empty or be covered by black rectangles (``mark=True``). The method also removes all redaction annots from the page.

## Current Restrictions
Only text is removed if it appears in the page's ``/Contents`` object(s). No images, no text contained in embedded PDF pages (via ``showPDFpage``).
**_Please comment_** on this - I am still investigating whether I can go beyond MuPDF functionality here. If e.g. image removal is possible at all, it will cause the image to be no longer **_displayed_** by the page and not physically removed, because there might be references to it elsewhere.
Some detail would be whether an image must be completely or only partly covered by the redaction area ...

Any other annotations on the page are unaffected (which is intentionally so, and not a restriction).

**Comment by JorjMcKie** [comment]
@juviwhale - for various reasons I decided to publish v1.16.11 quickly ... with the above functionality.

Depending on your feedback I am ready to investigate further how to include images and other /XObjects in the redaction process, which would go into a next versions.

**Comment by juviwhale** [comment]
This is great news, that you so much for the quick changes!

 I will give it a try and update with any feedback I have. Also great to hear that redactions on images and other objects are coming because that is strong need as I would need to redact both digital and scanned PDFs.

**Comment by JorjMcKie** [comment]
I have already been experimenting with images and xobjects a little. I have a script which already does this. It can remove such objects from the page **_physically_**, although it does not **_delete_** them from the PDF (directly). However, if an image was referenced only by this page, it will also go off the PDF if garbage collection is used on save.

I must pickup an earlier comment of mine:
Images (and xobjects) can only be removed from a page as a whole. If a redaction covers just part of it, then there is only the option to remove the image alltogether or let it survive completely.
This has obvious consequences for full-page scans ...

Adobe PDF is making very clear that just **_overlaying_** unwanted objects would be against the intentions of a redaction.

**Comment by juviwhale** [comment]
I had some time this morning to try redacting various documents. Here is my initial feedback:

1. The text inclusion decisions (lower left bbox corner) has worked so far in all of my tests. I was trying to find an example PDF were it would not work but was unable to find one. (I recall a few PDFs that were apparently converted from word documents and had titles with huge line heights that overlapped subtitles,  I can't seem to find/test these but will keep looking for them.)

2. I like the visual non-applied redaction annotations. Nice touch with the cross out :)

3. I have requests in terms of the color of the applied redactions. The users of my project have the use case of needing to use different colors for different applied redactions. This color coding allows them to retain the reason type to why the redaction was applied. Can an arbitrary color be set instead of just black and clear/white?

4. I have further requests in terms of the applied redactions but I understand if you may consider them out of scope. Ideally, it would be nice to have more of the options that Adobe Acrobat provided in applied redactions, specificly the text overlay. Now I understand this is a complex feature however I will add a screenshot of the Acrobat options here so you have a chance to see what they offer if you haven't seen them.

<img width="562" alt="Screenshot 2020-01-24 15 25 49" src="https://user-images.githubusercontent.com/6657003/75376017-27824e80-5884-11ea-80a7-9eba3ac78121.png">


5. I furher have requests in terms of 'sanitizing' PDFs as part of the redaction process. This request may be out of scope as well and may deserve its own feature reqeust ticket. 

<img width="532" alt="Screenshot 2020-01-24 15 27 06" src="https://user-images.githubusercontent.com/6657003/75376001-1c2f2300-5884-11ea-80db-a774c3a6bfc7.png">

Questions regarding the XObjects:

1. My familarity with the details of Xobjects is limited, is there a way to 'decompress' them in mupdf such that they are duplicated for each use and not shared?
2. Ideally on images if would be best to redraw the image elment with portions 'puched out' or merged with an opaque box overlay. Could this be possible?

**Comment by JorjMcKie** [comment]
> My familarity with the details of Xobjects is limited, is there a way to 'decompress' them in mupdf such that they are duplicated for each use and not shared?

The logic to **_not_** repeatedly store the same data for an /XObject is my own making, so I guess I could find a way to switch off that logic. Inserting xobjects in PyMuPDF only happens with method ``Page.showPDFpage()`` if I am not forgetting something here.
Could you please add a separate feature request for this - it makes things better trackable ...

**Comment by juviwhale** [comment]
Sure thing. I will make that feature request ticket.

**Comment by JorjMcKie** [comment]
> Ideally on images if would be best to redraw the image elment with portions 'puched out' or merged with an opaque box overlay. Could this be possible?

While doable, as I wrote earlier, Adobe PDF specification excludes this type of thing. In order to conform
to that spec, the store image itself would have to modified and then stored again in the PDF.
Which in turn would have unforseeable consequences: after all that same image might be used on other pages as well.
One could only delete an image completely - even if only parts of it are covered by a redaction.
Of course one might just give a damn on the specs and write a colored rectangle over redacted parts ... maybe even only in cases of partly coverage.

**Comment by JorjMcKie** [comment]
> I furher have requests in terms of 'sanitizing' PDFs as part of the redaction process. This request may be out of scope as well and may deserve its own feature reqeust ticket.

Most of this looks doable, and even might be achievable using existing functionality.
Can I asked you once more to add a separate feature request?

**Comment by JorjMcKie** [comment]
**Your point 3. and 4.**
I will give this further thought. It may be possible to add overlay text in the sense, that this text should be inserted in the rectangle emptied by the "apply redaction" process.
So in effect this is turning redactions into a text edit / replacement function. This would mean that the new text will become a **permamnent** part of the PDF.

An implementation would have to take care of some pesky details:
* what if the new text doesn't fit in the redact rectangle? Decrease font until it fits? Cut off from new text tail? ...
* can restrict this feature to PDF built-in fonts (Base 14)?
* can we agree on excluding text rotations?
* ...

**Comment by juviwhale** [comment]
> While doable, as I wrote earlier, Adobe PDF specification excludes this type of thing. In order to conform
to that spec, the store image itself would have to modified and then stored again in the PDF.
Which in turn would have unforseeable consequences: after all that same image might be used on other pages as well.

Not sure this would be the case for most people but that would actually be a `feature` for me. We are mainly redacting sensitive data so if it gets redacted in all references that is a good thing for me.

**Comment by juviwhale** [comment]
> An implementation would have to take care of some pesky details:
> * what if the new text doesn't fit in the redact rectangle? Decrease font until it fits? Cut off from  new text tail? ...
> * can restrict this feature to PDF built-in fonts (Base 14)?
> * can we agree on excluding text rotations?

I agree this could be a **can of worms** feature. I can offer my opinion, if you would like, for the default of some of these.

**Comment by JorjMcKie** [comment]
> I agree this could be a can of worms feature. I can offer my opinion, if you would like, for the default of some of these.

Please do so! You are the primary requester, so this is a chance of "stage setting" ...

**Comment by juviwhale** [comment]
ok great. 

> what if the new text doesn't fit in the redact rectangle? Decrease font until it fits? Cut off from new text tail? ...

From my iOS UX days I may have a bias to decreasing the font until it either fits OR a min font size is reached at which point it would be truncated with ellipsis. (truncated from the right - a western language bias here I admit)

*In the edge case where there is very very little space and 1, or maybe even 0, full characters can be shown then I the overlay should be omitted entirely.*

> can restrict this feature to PDF built-in fonts (Base 14)?

I think using the build-in fonts would be best as it limits complexity and I don't see the need for custom fonts.

> can we agree on excluding text rotations?

I agree. 

#### Other Possible Details

- Acrobat has an option for repeating overlay text, while probably not difficult I have no need for this feature.

- Setting the color of the text would be an important feature

- I could see the overlay text alignment being a valuable feature for some users perhaps, however I would only want the text to be vertically and horizontally centered. 

- Should the overlay text font match the font of content that was redacted? It could be, but that sounds super fancy and I don't think is needed. If a consistent font is used for the overlay text then I feel that font should excel and being legible at small sizes. I personally fell that a sans serif font is more appropriate, I think Helvetica would be best.

![Screen Shot 2020-02-26 at 2 26 02 PM](https://user-images.githubusercontent.com/6657003/75393975-0598c400-58a4-11ea-97fb-6882f6e8ee37.png)
![Screen Shot 2020-02-26 at 2 25 55 PM](https://user-images.githubusercontent.com/6657003/75393983-0893b480-58a4-11ea-818f-41d24a16de10.png)

**Comment by juviwhale** [comment]
Note: If you allowed selection of any of the PDF built-in fonts (Base 14) that would be great, in my last comment I meant more if the font had to be hard-coded.

**Comment by JorjMcKie** [comment]
I have a ready-to-use method ``insertTextbox`` in the ``Page`` and ``Shape`` classes. I would probably use this one internally.
It supports text colors and is also prepared to accept even any font.
It does support horizontal, but not vertical centering. Vertical centering is currently **not possible**.
This is a rough sketch of what would have to be done:

1. Allow entering overlay text and font data together with inserting the redact annotation.
2. Add methods for modifying a redact annot with this information.
3. Before invoking MuPDF's ``apply redactions`` for a page, scan through redactions and store away all the previous info (because it afterwards will have been deleted by MuPDF).
4. Work through the saved redact infos and do ``insertTextbox`` methods for them.

**Comment by JorjMcKie** [comment]
Just published v1.16.12 which enhances redactions as we have been discussing them here.
As ever before: please let me know if things do not work as expected.
Closing this for now.
