### ISSUE TITLE
How to move the page all content or move one text block to a new position?

### ISSUE THREAD

**Issue by a22349** [pymupdf/PyMuPDF#435]
1. how to move a text block to a new position in a page ? 
2. how to move all content in a page to a new condition ,with relative position not changed . 
3. page.setCropBox just enlarge all the crop contents to the full size of page , can't use it to move the crop area to a left top corner .

**Comment by JorjMcKie** [comment]
There is no direct way to do that.
But you **can** create a new page and insert stuff from the old page to desired positions.
Best would probably be however to use ``showPDFpage`` for this: you create a new page and then position any desired rectangular portions of the source page on it - according to the following scheme:

```python
# rect0 is a rectangle on the source page which you wish to show
# rect1 is the rectangle where rect0 should be shown
# doc is the document object , page is the source page
# we insert the new page after the source page
new_page = doc.newPage(page.number + 1, width=page.rect.width, height=page.rect.height)
new_page.showPDFpage(rect1,  # showthe source rectangle here
        doc,
        page.number, 
        clip=rect0  # sourcerectangle
    )
# repeat these 2 statements for all desired areas of the source page
# when done, delete the source page
doc.deletePage(page.number)
```

**Comment by a22349** [comment]
i'd like to only move one of the block in page now but not whole page ,  directly delete a text block or move it should be great . this will implement the most commercial software of "edit page" function . is there quick way to implement this in code level ?

**Comment by JorjMcKie** [comment]
As I mentioned in your other issue, PyMuPDF does not support direct editing of text contained in a page. But you can take any piece of text (orother item on the page) which you identify via a rectangle and put it on some place of your new page via the method show above:

```python
src = fitz.open("source.pdf")
doc = fitz.open("source.pdf")  # same file, but must be different document
page = src[n]  # some page you want to take rectangles from
new_page = doc.newPage(page.number + 1,  # make new page, put after source page
    width=..., height=...,  # choose as desired
    )
# src_rect contains text (or anything else) you want to show
# new_rect is the place where to show it on new_page
new_page.showPDFpage(new_rect, src, page.number, clip=src_rect)
# repeat the above statement for every pair of rectangles (src_rect, new_rect) you want.
# when done, delete src_page if appropriate
doc.deletePage(n)
```
The important trick here is that you have two documents which refer to the same file. They will be handled independent from each other by fitz - but you should do ``doc.save(...)`` to a new file after your changes (no incremental save), otherwise the ``src`` document will (probably) become invalid and exceptions will be raised when trying to access ``src`` objects.

**Comment by himmetozcan** [comment]
I wonder, now that it is 2025, if there is any update about this text shift feature on the lastest version of pymupdf?

**Comment by JorjMcKie** [comment]
> I wonder, now that it is 2025, if there is any update about this text shift feature on the lastest version of pymupdf?

There are no plans to do this beyond the support already implemented. Using `Page.show_pdf_page`as indicated should bring you close to what you want.
