### ISSUE TITLE
How to change pdf file mediabox size ? 

### ISSUE THREAD

**Issue by a22349** [pymupdf/PyMuPDF#436]
is there way to change the page size ? i just want to enlarge the page and  add more blank space for this page . can pymupdf have way to do this ?

**Comment by JorjMcKie** [comment]
Hm, not yet. At least not directly.
You can use the same approach as I explained inyour other issue, i.e. create a new page with desired mediabox dimension, then insert the old page via ``showPDFpage``, then delete the old page.

I could add a new method which modifies the mediabox directly, too, without problem. You can also do this yourself with some little tricks which I will show further down.
There is however a potential issue when doing this: depending on how the page content is structured, the page may look unexpected after this. For example, if you change page size say, from ISO A4 to ISO A3, you cannot be sure where the old page content will be shown on the new page's area (top or bottom, left or right).

This is the trick you can use to update the mediabox yourself:

```python
page = doc[n]  # the desired page
xref = page.xref  # the page's object number
s = doc.xrefObject(xref)  # get the definition string
print(s)  # just to show how this looks like
<<
  /Contents 31 0 R
  /Type /Page
  /MediaBox [ 0 0 595.32 841.92 ]
  /Rotate 0
  /Parent 12 0 R
  /Resources <<
    /ExtGState <<
      /R7 26 0 R
    >>
    /Font <<
      /R8 27 0 R
      /R10 21 0 R
      /R14 15 0 R
      /R12 24 0 R
      /R23 7 0 R
    >>
    /ProcSet [ /PDF /Text ]
  >>
>>
s = s.replace("841.92", "1684")  # double the page height
doc.updateObject(xref, s)  # write back the changed page definition
doc.save("test.pdf")  # save PDF to new file
```
You may end up with the following result:
Before
![grafik](https://user-images.githubusercontent.com/8290722/73418885-7a1c2980-431d-11ea-8e75-be65ad0d598f.png)
After:
![grafik](https://user-images.githubusercontent.com/8290722/73418907-95873480-431d-11ea-902f-99c441c54786.png)

**Comment by JorjMcKie** [comment]
So what I am suggesting is the following code snippet:
```python
src = fitz.open("input.pdf")  # the PDF you want to modify
doc = fitz.open(src.name)  # the same file, but as a different document object!
pno = n  # the number of the page you want to enlarge
rect = doc[pno].rect  # the page rectangle
rect_new = rect + (0, 0, 0, rect.height)  # new rect has twice the height
new_page = doc.newPage(pno + 1, width=rect_new.width,
        height=rect_new.height)  # the larger page behind the current one
new_page.showPDFpage(rect_new, src, pno, clip=rect)
doc.deletePage(pno)  # delete old small page
doc.save(...)
```
Method ``showPDFpage`` can show pages from the same PDF file, but the source PDF must be a different PyMuPDF **object** as shown.

**Comment by a22349** [comment]
Great thanks , and the showPDFPage will compress pdf as image correct , then the text blocks will loss i guess . so i think the first way should be better for me now . and if you can add some function later to change the mediabox and trimbox and artbox and bleedbox like setCropBox that should be convinient too .
