### ISSUE TITLE
Extract image and text from the PDF and combine

### ISSUE THREAD

**Issue by nandagopal1992** [pymupdf/PyMuPDF#437]
Hi  , I have been working on a project in which I need to combine text extracted from the pdf using fitz library and OCR result of the images in the same image.  In order to combine the results , I would require the position of the image block. But I am unable to understand the positional information from the page.getPageImageList(). According to the documentation , they only return width and height of the image block. Is there a way we can get one of the coordinate of the image block?

**Comment by JorjMcKie** [comment]
Yes! Please look up the documentation for method ``Page.getImageBbox()``.

**Comment by nandagopal1992** [comment]
Thanks for the quick reply @JorjMcKie , but I am facing the below error
![image](https://user-images.githubusercontent.com/26832613/74024725-739a4b80-49c8-11ea-8957-475d55f5204c.png)
I got the list of all images in the page using pg.getImageList() and am passing the third image. 

On debugging the code, I doubt if the value set to stream_xref is correct. The item[-1] for me is 'DCTDecode'

**Comment by JorjMcKie** [comment]
Did you use ``getPageImageList(pno, full=True)``?
Only then the items contain the required information for ``getImageBbox()``.

**Comment by nandagopal1992** [comment]
Thanks @JorjMcKie  . It worked :)
