### ISSUE TITLE
Controlling the resolution of the image exported?

### ISSUE THREAD

**Issue by james-roden** [pymupdf/PyMuPDF#438]
Hello,

In the documents it says "Method Page.getPixmap() offers lots of variations for controlling the image: **resolution**..." But I can't see a parameter for this? 
The image I am exporting from a PDF comes out really low quality in comparison to the original PDF.

Thanks, James

**Comment by JorjMcKie** [comment]
You need to use the matrix parameter for resolution changes, rotations, mirroring, and more.
Please look [here](https://pymupdf.readthedocs.io/en/latest/faq/#how-to-increase-image-resolution).

**Comment by james-roden** [comment]
Works like a charm. Thank you so much.

Excellent library btw.

**Comment by allefeld** [comment]
This should be made explicit in the documentation of `Page.getPixmap`, it is not at all clear.

**Comment by JorjMcKie** [comment]
@allefeld - I understand. I am adding a more verbose explanation. Should be online in an hour or so.

**Comment by allefeld** [comment]
@JorjMcKie great, thanks!
