### ISSUE TITLE
How to get image's location on page ?

### ISSUE THREAD

**Issue by a22349** [pymupdf/PyMuPDF#440]
use the page.getImageList just can know the width and height ,but not know the coordinates  
use page.getText("blocks") can't get the image block neither  if the page has image .
is there some api can get the image location ?

**Comment by JorjMcKie** [comment]
Yes! Please consult [this](https://pymupdf.readthedocs.io/en/latest/page/#Page.getImageBbox) method.

Use the following statements:

```python
img_list = doc.getPageImageList(pno, full=True)  # important: use 'full' parameter
# for the required image item in this list, then do this:
rect = page.getImageBbox(item)  # where page = doc[pno]

**Comment by JorjMcKie** [comment]
Closed for lack of reaction.

**Comment by SuryaViswanath11** [comment]
Hey @JorjMcKie I am currently having a similar use case where I want to identify if a particular table has an image with it, however with the use of the `getPageImageList()` I will be able to get the coordinates. Is there a way I can check if there is an image next to text line so that I will be able to add that data into my excel

**Comment by JorjMcKie** [comment]
@SuryaViswanath11 - loop through the image list `doc.get_page_images()` (the new name of getPageImageList()) and store each image rectangle therein in a list (caution: not all images in the page list need actually be shown on the page - in that case the returned bbox is infinite).
Then check for each text line of interest, whether its bbox is close (enough) to one of the images in the stored list.

**Comment by rizwan29** [comment]
@JorjMcKie `get_image_bbox` method returns the `Rect` object which is a bounding box of the image but not the relative position of the image in the page. Is there a method which can help to extract image's location in the page?

**Comment by uttam-scai** [comment]
@rizwan29 were you able to get the position of the image with respect to the pdf page? 
@JorjMcKie I am struggling to use the bbox output values in opencv (cv2.rectangle). It doesn't draw the box at the same location of the image.

**Comment by JorjMcKie** [comment]
@uttam-scai - have you confirmed that the bbox coordinates from PyMuPDF are correct?
You can do this by drawing that rectangle and inspecting it in a temp PDF:
```python
page.draw_rect(bbox)
doc.save("temp.pdf")
```
It it works, then CV2 has a problem.
I am not using that package, so I cannot say what may be going wrong there.
What is CV2's page coordinate system: where is point (0, 0) - top-left or bottom-left?

**Comment by uttam-scai** [comment]
@JorjMcKie thank you very much for quick response. I have confirmed by using page.draw_rect command that it draws correctly. However it's failing in case of CV2. The reason of failure is the **scale**  
in case of CV2:  

- CV2's page coordinate system: top left is considered as (0,0), which is same as PyMuPDF as well. 
To draw the rectangle in cv2 and PyMuPDF, I use the following command - 
- `image = cv2.rectangle(img, (1, 1), (100, 100), color, thickness)`
- `page.draw_rect((1, 1, 100, 100))`
[temp.pdf](https://github.com/pymupdf/PyMuPDF/files/10258451/temp.pdf)
![image](https://user-images.githubusercontent.com/54339614/208405135-617956b4-d96d-4da5-baaa-0ea108ecc366.jpg)

However the pymupdf is covering more space than cv2. Is there any scale value that I can play around? 
Please see the attached image and pdf that I received from the output. 

Thank you.

**Comment by JorjMcKie** [comment]
As I mentioned: I have no knowledge of OpenCV. So don't know what they might mean with "scale".
Have you confirmed, that CV addresses from top-left to bottom-right?

**Comment by JorjMcKie** [comment]
Are you even sure that Figure 1 is an image at all?
Might as well be a drawing (PDF vector image instructions).

**Comment by uttam-scai** [comment]
I understand. Thank you. 
In the example above I am not trying to create rectangle around Figure 1. I simply wanted to show that CV2 addresses the coordinate from TOP-LEFT. I am simply trying to create a rectangle from (1,1) to (100,100). and since both are starting from top left (blue rectangle) then both have to have same coordinate system for the page.. right? 

I apologize for asking cv2 question here. Thank you for your help !!!

**Comment by JorjMcKie** [comment]
>  In the example above I am not trying to create rectangle around Figure 1. I simply wanted to show that CV2 addresses the coordinate from TOP-LEFT. I am simply trying to create a rectangle from (1,1) to (100,100). and since both are starting from top left (blue rectangle) then both have to have same coordinate system for the page.. right?

Correct, now I understand.
