### ISSUE TITLE
Question / Comment: attachments return to MuPDF

### ISSUE THREAD

**Issue by ousia** [pymupdf/PyMuPDF#442]
@JorjMcKie,

I thought you might be interested: attachments come back to MuPDF as per https://git.ghostscript.com/?p=user/tor/mupdf.git;a=commit;h=cc32a0c5cc2c4d6c46ef23309bda77e2e6f18b5f.

I hope it helps.

**Comment by JorjMcKie** [comment]
@ousia - thanks for the hint.
Looking into it revealed, that it only is concerned with **_FileAttachment annotation_** support for the mupdf-gl utility and not re-introduction of EmbeddedFiles ...
Embedded file support seems to remain lost for MuPDF for the foreseeable future.
**PyMuPDF** however continues to support EmbeddedFiles. You may have noticed that fitz as a **_module_** also supports this feature in the command line.

**Comment by ousia** [comment]
@JorjMcKie, you are right.

And this is also an issue, because MuPDF won’t be able to read the documents that include that method.
