### ISSUE TITLE
Please put documentation into this repo

### ISSUE THREAD

**Issue by htgoebel** [pymupdf/PyMuPDF#443]
The (sphinx based) documentation is kept in a separate repo (https://github.com/pymupdf/PyMuPDF-Optional-Material/tree/master/docs), while this repo`s ``doc`` contains the PDF and html.zip version of the documentation.

Users would expect to find source and docuemtnation at one place, as most other projects do. Also user would expect to find the *source* here, without any build artifacts.

I suggest 
1) moving the *source* of the docs into this very repo. 
2. moving the PDF and html.zip version of the docu into some other repo -if any, since readthedocs can provide these file, too.

This would also simplify the release-process, since one does not need to build and upload the PDF and html.zip manual. Additionally this would reduce the size of data to be downloaded when cloning.

Thanks.

**Comment by JorjMcKie** [comment]
Closing this with v1.16.11.
