### ISSUE TITLE
Please clarify documentation

### ISSUE THREAD

**Issue by htgoebel** [pymupdf/PyMuPDF#444]
## Describe the bug (mandatory)
The [documentation](https://pymupdf.readthedocs.io/en/latest/installation/#option-2-install-from-binaries) does not state whether muPdf or any other resources (fonts, etc.) need to be installed in addition to the wheels to use muPDF.

If the wheels are self-contained, this is an impotant information, esp. snce this would be a major benefit of muPDF over e.g. ghostscript.

## Expected behavior (optional)
If muPDF or any other resources (e.g.) need to be installed in addition to the wheel, the documentation should state this. If neither muPDF or any other resources are required, the documentation shouled *explicitly* state this.

**Comment by JorjMcKie** [comment]
The wheels are self-contained.
I will add a comment which confirms that their installation is sufficient to make PyMuPDF usable.

**Comment by JorjMcKie** [comment]
Closing this with current v1.16.11.
