### ISSUE TITLE
Remove outdated gh-pages documentation

### ISSUE THREAD

**Issue by htgoebel** [pymupdf/PyMuPDF#445]
When searching the source of the docs, I stepped of terh [`gh-pages` branch](https://github.com/pymupdf/PyMuPDF/tree/gh-pages), which contains 7 year old documentation.

I suggest to either simply delete this branch or remove all files there, leaving just a page pointing to readthedocs.

**Comment by JorjMcKie** [comment]
The documentation sources can be found [here](https://github.com/pymupdf/PyMuPDF-Optional-Material). This repo is also the source for doc generation.
I removed that branch, thanks for the hint.
