### ISSUE TITLE
CI / How the releases get build automatically?

### ISSUE THREAD

**Issue by htgoebel** [pymupdf/PyMuPDF#446]
I'm missing any CI file in this repo (travis, appvayor, etc.) Thus I wonder, how one could automate the build-process for e.g. reproducible builds.

What about adding CI tooling?

**Comment by htgoebel** [comment]
Addentum: This could also be used to automatically build the wheels for different platforms.

**Comment by JorjMcKie** [comment]
I do use Travis for exactly this purpose - but in another [fork](https://github.com/JorjMcKie/py-mupdf) of this repo.
