### ISSUE TITLE
Question / Comment:

### ISSUE THREAD

**Issue by saket404** [pymupdf/PyMuPDF#448]
Hello,

 I had an inquiry regarding a feature. Is it possible to extract highlighted text with the color from PDF?

**Comment by JorjMcKie** [comment]
Which color do you mean?
* ``Page.getText("dict")`` or ``Page.getText("rawdict")`` extract text (in Python *dict* format) alongside with the used font including text color.

* I assume you mean text highlighted with an annotation and want to know the color used for highlighting? Then just use ``Annot.colors`` to find out the highlighting color. But using the annotations rectangle, you can also extract the text which was highlighted by subselecting the respective text portions from previous method and then look at the text color.

**Comment by saket404** [comment]
Thank you for you reply,

 I got it working and have been extracting annotations rectangles. I checked the documentation here [Extract all doc text](https://pymupdf.readthedocs.io/en/latest/faq/#how-to-extract-all-document-text) but the link of the script is not valid.

**Comment by JorjMcKie** [comment]
> I checked the documentation here Extract text from rectangle but the link of the script is not valid. I am trying to extract text for the highlighted part.

Yes, sorry, I changed the location of those scripts and did not update the references everywhere. You find it [here](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/textboxtract.py) now.

**Comment by saket404** [comment]
Thank you for the instant reply!

**Comment by JorjMcKie** [comment]
You are welcome!
