### ISSUE TITLE
How to migrate font from one pdf to  another ? 

### ISSUE THREAD

**Issue by a22349** [pymupdf/PyMuPDF#450]
hi , 
want to use same font in one pdf to insert text  to new pdf .

i use getText("dict", flags=11)["blocks"] to get the font and text info from one pdf page and print it  like : 

     Font: '*Courier-Bold-9564' (serifed, proportional, bold), size 24, color #332e30

and  i try to insert to a new pdf new page using 
      new_pdf_page . inserttextbox( font = "*Courier-Bold-9564" ..,"hello world") 
it prompt me  exception like : 
     "_fitz.Page__insertFont(self, fontname, bfname, fontfile, fontbuffer, set_simple, idx, wmode, serif, 
      encoding, ordering)
     RuntimeError: need one of fontfile, fontbuffer
    "

when i try to call "insertFont" i dont know where to get the "fontbuffer"

i tried "getFontList" to get the xref of the font and then call Document._getXrefStream(xref) but return is "None" . 

how could it be done ? 

thanks .

**Comment by JorjMcKie** [comment]
This only works if the font is not a built-in font.
In the source PDF do ``src.extractFont(xref)``.
```
Returns
a tuple (basename, ext, subtype, buffer), where ext is a 3-byte suggested file exten-
sion(str), basenameisthefont’sname(str), subtypeisthefont’stype(e.g. “Type1”)
and buffer is a bytes object containing the font file’s content (or b”“). For possi-
ble extension values and their meaning see Font File Extensions. Return details on
error:
• (“”, “”, “”, b”“) – invalid xref or xref is not a (valid) font object.
• (basename, “n/a”, “Type1”, b”“) – basename is one of the PDF Base 14 Fonts,
which cannot be extracted.
```

**Comment by JorjMcKie** [comment]
If the entry of ``doc.getPageFontList(pno)`` looks something like this:
``(27, 'ttf', 'TrueType', 'FNUUTH+Calibri-Bold', 'R8', '')`` (the fontname starts with a 6 characters string ending with "+", then only a subset of **Calibri-Bold** is present in the buffer (last item in tuple of *extractFont* and re-using that font somewhere else will show a "?" for character codes which are not present.

**Comment by JorjMcKie** [comment]
Answered your question?

**Comment by JorjMcKie** [comment]
Assuming this is answered.

**Comment by suparnaj3** [comment]
I was also trying to migrate a font from one pdf to another. 

buffer = src.extractFont(xref)
font = fitz.Font(name, fontbuffer=buffer[-1])

font.glyph_count returns 4237, but font.valid_codepoints() returns empty result.

As glyphs are not there, it is getting written to pdf as given below:


![Screenshot from 2021-08-15 23-35-32](https://user-images.githubusercontent.com/30137308/129488094-3cfc2953-ea5a-484c-ba9a-36edfacbe4b4.png)

The font is ('BOPWZB+Arial-BoldMT', 'ttf', 'Type0').

@JorjMcKie , Could you please suggest a solution for this issue?

**Comment by JorjMcKie** [comment]
Can you please check the response to `font.is_writable`?
MuPDF in general only supports a subset of fonts  - those having `Identity` encoding and therefore a CMAP.
But the font you named is a standard font which you do not need to migrate at all, but simply directly use Helvetica Bold - code "hebo".

**Comment by JorjMcKie** [comment]
Independent from the above:
If you re-use a subset font as you did, there also is the risk, that it does not contain all the glyphs you need in your own text.

**Comment by suparnaj3** [comment]
The font is writable.

And I am trying to move the same text to another new pdf. In that case, glyphs should be there, am I correct?

**Comment by JorjMcKie** [comment]
I have tried another example. It seems the check behind `Font.is_writable` is insufficient so gives false-positive answers.
MuPDF text output is only supported with fonts having an ``Identity-H`` or ``Identity-W`` encoding. So something like your check for `valid_codepoints` being not empty should be included.
When you `pprint(page.get_fonts())` you will see the encoding as the last entry in each list item. If there is no ``Identity-*`` then it won't work.

**Comment by suparnaj3** [comment]
page.get_fonts() is returning:

(23, 'ttf', 'Type0', 'BOPWZB+Arial-BoldMT', 'C2_6', 'Identity-H'),
 (31, 'ttf', 'Type0', 'TANYIG+Arial,Bold', 'C2_5', 'Identity-H'),
 (39, 'ttf', 'Type0', 'ENQAVF+Arial-BoldMT', 'C2_8', 'Identity-H'),
 (47, 'ttf', 'Type0', 'ZCXTOP+ArialMT', 'C2_7', 'Identity-H'),
 (55, 'ttf', 'Type0', 'LNXNZM+ArialMT', 'C2_2', 'Identity-H'),
 (58, 'ttf', 'Type0', 'MNKFXU+ArialMT', 'C2_1', 'Identity-H'),
 (61, 'ttf', 'Type0', 'TANYIG+Arial', 'C2_4', 'Identity-H'),
 (69, 'ttf', 'Type0', 'AHMMTY+ArialMT', 'C2_3', 'Identity-H'),
 (72, 'ttf', 'Type0', 'LLQWTW+Arial-BoldMT', 'C2_9', 'Identity-H'),
 (75, 'ttf', 'Type0', 'LLQWTW+ArialMT', 'C2_25', 'Identity-H'),
 (83, 'ttf', 'Type0', 'LEJENW+Arial', 'C2_26', 'Identity-H'),
 (86, 'ttf', 'Type0', 'IFTOND+Arial-BoldMT', 'C2_0', 'Identity-H'),
 (89, 'n/a', 'Type1', 'Helvetica-Bold', 'FXF2', ''),
 (90, 'n/a', 'Type1', 'Helvetica', 'FXF1', 'WinAnsiEncoding'),
 (91, 'ttf', 'Type0', 'RDJFQK+ArialMT', 'C2_21', 'Identity-H'),
 (94, 'ttf', 'Type0', 'BOPWZB+ArialMT', 'C2_22', 'Identity-H'),
 (97, 'ttf', 'Type0', 'YKSJPW+ArialMT', 'C2_23', 'Identity-H'),
 (100, 'ttf', 'Type0', 'XCXERJ+ArialMT', 'C2_24', 'Identity-H'),
 (103, 'ttf', 'Type0', 'DTIATR+ArialMT', 'C2_20', 'Identity-H'),
 (1, 'n/a', 'Type1', 'Courier', 'Xi0', 'WinAnsiEncoding'),
 (2, 'n/a', 'Type1', 'Helvetica', 'Xi1', 'WinAnsiEncoding'),
 (106, 'ttf', 'Type0', 'YHZYER+ArialMT', 'C2_18', 'Identity-H'),
 (109, 'ttf', 'TrueType', 'KYHHLJ+IDMSTaxFont', 'TT1', ''),
 (113, 'ttf', 'Type0', 'RSXZYF+Arial-BoldMT', 'C2_19', 'Identity-H'),
 (115, 'ttf', 'TrueType', 'KYHHLJ+IDMSTaxFont', 'TT0', ''),
 (116, 'ttf', 'Type0', 'VDPHNY+Arial-BoldMT', 'C2_14', 'Identity-H'),
 (119, 'ttf', 'Type0', 'LTHAOM+ArialMT', 'C2_15', 'Identity-H'),
 (121, 'ttf', 'Type0', 'FIJNVO+ArialMT', 'C2_16', 'Identity-H'),
 (124, 'ttf', 'Type0', 'XXHZJU+Arial', 'C2_17', 'Identity-H'),
 (126, 'ttf', 'Type0', 'GLZSEH+ArialMT', 'C2_10', 'Identity-H'),
 (128, 'ttf', 'Type0', 'QWOYMI+ArialMT', 'C2_11', 'Identity-H'),
 (131, 'ttf', 'Type0', 'DJSDIR+ArialMT', 'C2_12', 'Identity-H'),
 (133, 'ttf', 'Type0', 'ZQNHYP+ArialMT', 'C2_13', 'Identity-H')]

It's Identity-H only.

**Comment by JorjMcKie** [comment]
Hm, I don't know what is going wrong really.
It definitely is outside PyMuPDF: because if you use `mutool extract file.pdf` (which will extract fonts and images), you will also get unusable fontfiles.
As a counter-example try this demo pdf: 
[text-oc.pdf](https://github.com/pymupdf/PyMuPDF/files/6992664/text-oc.pdf)
It does work as described.
So the missing check within `font.is_writable` really is whether `font.valid_codepoints()` is not an empty sequence.

**Comment by suparnaj3** [comment]
Yes, you are correct. I tried using mutool, it is also giving unusable fontfiles.

I decided to keep a fallback font.

Thanks for the support.
