### ISSUE TITLE
Can I change the format of Free text annotation to "Bold"?

### ISSUE THREAD

**Issue by kurokawaikki** [pymupdf/PyMuPDF#452]
Recently, I am trying to add lots of free text annotation with pyMuPDF to an existing PDF.
However, I cannot find a way to add the bold text with desired font (TimesNewRoman-Bold).
I tried this  page.addFreetextAnnot(rect, text, fontsize=24, fontname="TimesNewRoman-Bold", text_color=(1, 0, 0), fill_color=(0, 0, 0, 100), rotate=page.rotation).
But I can only get the normal style of text not the bold one.
What is the solution?
Thank you very much for your great efforts!
Keep on the great works!

**Comment by JorjMcKie** [comment]
Thank your for your nice feedback!

Unfortunetaly I have to say, that the used C base library, MuPDF, has removed this support with version 1.16.0 ☹. So their regrettably their currently is no way to achieve this.

**Comment by kurokawaikki** [comment]
Thank you for your reply.
I have another thought. Can I add a button that can run Javascript?
I mean... Can I use PyMuPDF to add a button widget that contain a specific Javascript? After exporting as PDF file, I can click on that button and run the Javascript that I predefined in PyMuPDF.
Thank you very much for your great help!

**Comment by JorjMcKie** [comment]
I understand, let me check this. Looks definitely more promising.
Could you please add another issue with this as feature request?
I will then close this one as "won't fix".
