### ISSUE TITLE
Feature Request: Add Acrobat like PDF Sanitization 

### ISSUE THREAD

**Issue by juviwhale** [pymupdf/PyMuPDF#453]
Related to PDF redaction it would be beneficial if PDFs could be sanitized via your package. 

### Background:

PDFs often contain a large about of hidden data that is often sensitive. Users pass along documents not realizing this data is contained in the PDF. 

### Solution/Feature Desired

It would be very beneficial if there was functionality that allows a page or entire PDF document to be sanitized. *Sanitized* here is best described as Adobe Acrobat Describes it. 

<img width="532" alt="Screenshot 2020-01-24 15 27 06" src="https://user-images.githubusercontent.com/6657003/75385844-6bca1a80-5895-11ea-8855-68da02945d06.png">

Removal of:

- Metadata
- Embedded content and attached files
- Scripts
- Hidden layers
- Embedded search indexes
- Stored form data
- Review and comment data
- Comments hidden within the body of the PDF file
- Hidden data from the previous document saves
- Obscured text and images
- Unreferenced data
- Links, actions, and javascripts
- Overlapping objects

That is a large list of sub-features and I understand some would be far less straightforward than others. Implementation of any would be very beneficial. 

### Alternatives

Adobe Acrobat is the only product I have seen that has this functionality. There are few commercial or non-commercial product that allows this do be done programmatically.  

The only one I have tried is [Origapy](https://www.decalage.info/fr/python/origapy) and I was not impressed with its performance nor scope of sanitization. 

There are some options for 'flattening' a PDF to achieve this, [for example](https://github.com/Kerbalnut/Sanitize-PDF), but 'flattening' in this cases just means replacing the PDF content with a rendered image aka an `image only pdf`.  

##### Other found that I have yet to try

- [aling93/pdf-sanitizer](https://github.com/aling93/pdf-sanitizer) : Bachelor Thesis project intended to sanitize PDF files containing malware javascript
- [gianniLeslie/PdfSanitizer](https://github.com/gianniLeslie/PdfSanitizer)

### Additional context**

- [NSA Documentation on the need for PDF sanitation](http://www.itsecure.hu/library/file/Biztonsági%20útmutatók/Alkalmazások/Hidden%20Data%20and%20Metadata%20in%20Adobe%20PDF%20Files.pdf)
- [Paper-Efficient Techniques for Document Sanitization](https://www.researchgate.net/publication/221613463_Efficient_Techniques_for_Document_Sanitization)

**Comment by JorjMcKie** [comment]
Thank you for submitting this. As you wrote: some subfeatures are fairly low-hanging fruits while others require more effort. As a first reaction, please see these first assessments:

- **Metadata:** document level metadata (standard and XML based) can already be removed. XML metadata can also occur on arbitrary objects: this requires new code.
- **Embedded content and attached files:** I assume this means removing all ``/EmbeddedFiles`` entries and ``FileAttachment`` annotations. This can be done with existing functionality.
- **Scripts:** *Don't know what that means (other than JavaScript).*
- **Hidden layers:** Not sure what that means. We could include removal of **hidden annotations**
- **Embedded search indexes:** Don't know what that means.
- **Stored form data:** We can loop through all form fields on all pages and reset values to defaults.
- **Review and comment data:** Remove ``PopUp`` annotations response chain. This features exists in parts: if an annotation is removed, then any related ``PopUP`` and ``IRT`` ("in response to") annotation is deleted, too. This part of the code would have to be approachable separately.
- **Comments hidden within the body of the PDF file:** Don't know what means.
- **Hidden data from the previous document saves:** Don't know other than our garbage collection.
- **Obscured text and images:** Don't know what that means - redacted parts?
- **Unreferenced data:** This should be covered by garbage collection.
- **Links, actions, and javascripts:** Code must be developped.
- **Overlapping objects:** This needs more detail and can be very tricky.
    * Text may be covered by an image, but the image may be transparent - then what?
    * Or two images my overlap, or overlap incompletely
    * Or text is overlapped by an image, which in turn is overlapped by some other text.

**Comment by JorjMcKie** [comment]
> There are some options for 'flattening' a PDF to achieve this, for example, but 'flattening' in this cases just means replacing the PDF content with a rendered image aka an image only pdf.

I understand. I am sure you are aware, that this type of "flattening" is a 5-liner in PyMuPDF.

**Comment by JorjMcKie** [comment]
Jotted down a first cut version. Would you care trying it out and provide feedback?
[pdf-sanitizer.zip](https://github.com/pymupdf/PyMuPDF/files/4271996/pdf-sanitizer.zip)

**Comment by JorjMcKie** [comment]
An version with minor fixes 
[pdf-sanitizer.zip](https://github.com/pymupdf/PyMuPDF/files/4272415/pdf-sanitizer.zip)

Status assessment:

* ~Metadata~ **_Done_**
* ~Embedded content and attached files~ **_Done_**
* Scripts **_(not clear what to do here beyond javascript removal)_**
* Hidden layers **_(need more research on OCGs)_**
* Embedded search indexes **_(not clear what to do here)_**
* Stored form data **_(coming with next version)_**
* Review and comment data **_(coming with next version)_**
* ~Comments hidden within the body of the PDF file~ **_Done_**
* ~Hidden data from the previous document saves~ **_Done_**
* Obscured text and images **_(not clear what to do here beyond redactions)_**
* ~Unreferenced data~ **_Done_**
* ~Links, actions, and javascripts~ **_Done_**
* overlapping objects **_(probably too complex to ever do it)_**

**Comment by juviwhale** [comment]
Great, I will try out the script. Are you thinking the sanitization functionality will be best implemented as a script like this or are you thinking of adding this as methods on the doc/page objects?


> Scripts (not clear what to do here beyond javascript removal)

I think the *scripts* being referenced here are just javascripts

> Embedded search indexes (not clear what to do here)

I think it would be best to purge the search indexes entirely if possible


> Obscured text and images (not clear what to do here beyond redactions)

For me it would be best to remove all of the obscured text and images if possible. Like ideally what I am aiming for is a digital version of what the 'image flattened' PDF provides, that being I know what I am getting/giving and there is not any hidden gotchas.

Aside: I am curious, how are the auto OCR characters generally added to a PDF? Are those added at a lower 'z-index' than the scanned image or are the characters added with a 'clear' text color?

**Comment by JorjMcKie** [comment]
> I think it would be best to purge the search indexes entirely if possible

I should have written: what **are** search indices?

> are you thinking of adding this as methods on the doc/page objects?

I am undecided yet. A separate script always tends to be dangling around and appears disconnected from the main stuff. After all, this feature is not intended to become an example.
So probably a document method would be best.
What is your take?

> how are the auto OCR characters generally added to a PDF? 

I have seen this:
The page ``/Contents`` looks like filled with normal text, and towards its very end an image display command appears, i.e.:

```postscript
q
BT  % Begin Text command
/F_0 9.5 Tf  % OCR-ed text follows from here ...
.89695 0 0 1 139.35 730.65 Tm
<0f10114324> Tj
2.0638 0 0 1 158.5 730.65 Tm
<01> Tj
1.0175 0 0 1 163.35 730.65 Tm
<2f0321> Tj
1.9148 0 0 1 177.85 730.65 Tm
<01> Tj
1.0583 0 0 1 182.35 730.65 Tm
<1d190b> Tj
2.0425 0 0 1 196.85 730.65 Tm
<01> Tj
1.0271 0 0 1 201.65 730.65 Tm
<080309> Tj
1.851 0 0 1 213 730.65 Tm
<01> Tj
1.0542 0 0 1 217.35 730.65 Tm
<27052f070b> Tj
...
1.157 0 0 1 431 64.85 Tm
<083504210709> Tj
2.1276 0 0 1 457.14 64.85 Tm
<01> Tj
1.2279 0 0 1 462.14 64.85 Tm
<0706> Tj
1.9148 0 0 1 470.5 64.85 Tm
<01> Tj
1.1469 0 0 1 475 64.85 Tm
[<2705040436210C>14<1704192F0E>] TJ  % ... up to here
ET  % ==> end of text command
Q
q
/Artifact <</Type/Page>> BDC   % artifact definition wraps image display
657.15 0 0 774 0 0 cm   % ==> image coverage matrix (full page)
/BG Do  % image display command
EMC
Q
```
If you do ``page.getText("blocks")`` (or "dict" as well), the image will **_not_** be extracted - just the OCR-ed text! This is due to the ``/Artifact`` encapsulation.
But ``doc.getPageImageList(pno, full=True)`` delivers ``[(19, 0, 2738, 3225, 8, 'DeviceRGB', '', 'BG', 'JPXDecode', 0)]``, and ``page.getImageBbox()`` accordingly delivers a rectangle containing ``page.rect``.
And because the image display command is the last command of all, the image will cover all of the OCR-ed text.
Don't know how special this case is, but it can surely be handled by e.g. redacting the text (**only**) of the whole page. Which would leave over  the image only.
Or just delete everything before the image from the string, or everything between and inluding any string pair ``BT ... ET``, etc.

**Comment by JorjMcKie** [comment]
Here is another way, how OCR-ed text can be coded to make it invisible, but still be searchable and copy-pastable. This was done with the OCR feature of PDF-Xchange:

```postscript
q
420 0 0 595 0 0 cm  % image matrix (full page cover)
/Im0 Do  % display command
Q
BT  % Begin Text
94.446 Tz
3 Tr  % ==> Text render command: 3 makes following text invisible!
55.8 544.837 Td
/F0 11 Tf
<003900510050> Tj
100.474 Tz
23.76 0 Td
<004A004F00480074004700D50050> Tj
101.788 Tz
38.76 0 Td
<00240058005700520055> Tj
89.254 Tz
29.64 0 Td
<004800550056006E00D5004C0048005100480051> Tj
86.66 Tz
48.84 0 Td
<00440058008900480055004700480050> Tj
88.775 Tz
-141 -12.481 Td
<0044004F0056> Tj
79.188 Tz
15.48 0 Td
<002B0048005C005100480061003700440056000900D5004800D500140014001D00BE00810047001400480055> Tj
88.334 Tz
-15.48 -25.562 Td
<003600570055004400890048> Tj
90.595 Tz
32.04 0 Td
<004700480055> Tj
90.652 Tz
17.28 0 Td
<0039004800550047005100500050005100740056> Tj
49.14 Tz
61.92 0 Td
<0010> Tj
87.833 Tz
7.2 0 Td
<0025004400510047> Tj
82.407 Tz
25.56 0 Td
<0016001600140044> Tj
97.455 Tz
-144 -12.481 Td
<0027004C0048> Tj
92.459 Tz
18.96 0 Td
<002C005100560048004F> Tj
89.84 Tz
24.48 0 Td
<004700480055> Tj
90.874 Tz
17.28 0 Td
<00370044005700480051> Tj
53.283 Tz
30.96 0 Td
<000D> Tj
88.301 Tz
7.56 0 Td
<0025004400510047> Tj
79.954 Tz
25.68 0 Td
<0018001600190019> Tj
ET  % End Text
```

**Comment by JorjMcKie** [comment]
Here is a version which suppresses text hidden in the way of the previous post.
Maybe you can try it and see if we are approaching the goal ...
[pdf-sanitizer.zip](https://github.com/pymupdf/PyMuPDF/files/4280997/pdf-sanitizer.zip)

**Comment by juviwhale** [comment]
> what are search indices?

I have never used an embedded search index and it appears the Adobe is moving away from using them. I am not sure how the data is stored in the PDF but here is how they are created, [Create and manage an index in a PDF](https://helpx.adobe.com/acrobat/using/creating-pdf-indexes.html)

> I am undecided yet. A separate script always tends to be dangling around and appears disconnected from the main stuff. After all, this feature is not intended to become an example.
So probably a document method would be best.
What is your take?

I fear that a script may be missed by users who could benefit from the functionality. It would make sense to me to have some connection of the sanitation functionality with the application of redaction annotations or as a param on the save method which already has a robust set of save options. 

Thanks for the examples on the  OCR-ed text. These PDFs have been a thorn in my side as they rarely have decent OCR text and are hard to determine text detection quality in a programatic way. Too bad scanners don't do good job of describing what they 'did'.

Another question I have had on the subject: from my reading of the PDF spec, transparent text (i.e. alpha=0) is not supported, is this correct?  Of course there is nothing stoping white text on a white background. 

Hidden text has been a frustrating topic for me, I have had to deal with numerous user reported 'issues' where the PDF content didn't well represent what was 'seen' by the user. The sanitation process wouldn't solve all of these cases but maybe could reduce the number.

**Comment by JorjMcKie** [comment]
> I am not sure how the data is stored in the PDF but here is how they are created

Thanks for the pointer. To create this you obviously have to buy a commercial Acrobat version ...
But you are right, Adobe recommends to no longer use them. So I will put this to the end of the priority list.

> Another question I have had on the subject: from my reading of the PDF spec, transparent text (i.e. alpha=0) is not supported, is this correct? Of course there is nothing stoping white text on a white background.

This is exactly my state of knowledge.

> I fear that a script may be missed by users who could benefit from the functionality. It would make sense to me to have some connection of the sanitation functionality with the application of redaction annotations or as a param on the save method which already has a robust set of save options.

Thanks for that feedback. I think I will follow this recommendation.

BTW: have you tried the hidden text removal which is contained in the latest script version?

**Comment by juviwhale** [comment]
I haven't tired the latest script yet. I am away but will be sure to try it out when I return on Monday.

**Comment by JorjMcKie** [comment]
New version 1.16.14 is on PyPI, which introduces method ``Document.scrub(...)``.
It has a lot of options, which in the end motivated me to create a new method instead of overloading ((save()``.

**Comment by JorjMcKie** [comment]
I am aware that this is not yet your 100% solution, but I hope it addresses most of it.
