### ISSUE TITLE
Perform ROI on selected PDF pages

### ISSUE THREAD

**Issue by mshoa** [pymupdf/PyMuPDF#455]
**Is your feature request related to a problem? Please describe.**
Can we use the GUI for ROI (Region of interest) from a page

**Describe the solution you'd like**
Can we do this region of interest selection inside a WX GUI?
import cv2
ROI=cv.namedWindow('ROIs', cv.WINDOW_GUI_NORMAL)

img = cv2.imread(filename)

cv2.selectROIs()

while(1):
    fromCenter = False
    ROIs = cv2.selectROIs('ROIs', img, fromCenter)

    ROI_1 = img[ROIs[0][1]:ROIs[0][1]+ROIs[0][3], ROIs[0][0]:ROIs[0][0]+ROIs[0][2]]
    ROI_2 = img[ROIs[1][1]:ROIs[1][1]+ROIs[1][3], ROIs[1][0]:ROIs[1][0]+ROIs[1][2]]
    ROI_3 = img[ROIs[2][1]:ROIs[2][1]+ROIs[2][3], ROIs[2][0]:ROIs[2][0]+ROIs[2][2]]

    cv2.imshow('1', ROI_1)
    cv2.imshow('2', ROI_2)
    cv2.imshow('3', ROI_3)

    
#    cv2.destroyAllWindows()
cv2.waitKey(0)
cv2.destroyAllWindows()

**Describe alternatives you've considered**
This opens a GUI when run, can it be captured by WX GUI frame?

**Additional context**
btw good library

**Comment by JorjMcKie** [comment]
Thank you for the feedback.
I am not using opencv myself. I wrote a few scripts using various GUIs which access PyMuPDF, however. Several of them using wxPython.
But there is no connection nor dependency between PyMuPDF and any GUI.
My goal also is to keep PyMuPDF free from any dependency outside the  Python base library.
So your approach may or may not work. In any case I'm afraid it is outside the scope of PyMuPDF.

**Comment by JorjMcKie** [comment]
Assuming this is answered.

**Comment by kurokawaikki** [comment]
I used PyQT5 to display PDF file which read by PyMUPDF. It is totally possible to use the GUI to select ROI for further use.
PyMUPDF is a perfect library to manipulate PDF. But, you should write the code to implement it with your GUI. 
In my case, I use the pixmap from page and convert it to QImage. Use the position on the image to link back to PDF and do some further process.
There are some case out there which you can check with.

**Comment by JorjMcKie** [comment]
> Use the position on the image to link back to PDF and do some further process.

Just to underpin your description, @kurokawaikki: in fact one can use PyMuPDF to locate areas of interest on a ``fitz.Page`` via e.g. text extraction methods (``page.getText(code)``) or image bbox calculation (``page.getImageBbox(item)``), and then translate this to coordinates of the page's pixmap.
