### ISSUE TITLE
why i need to import fitz to use PyMuPDF?

### ISSUE THREAD

**Issue by andreabisello** [pymupdf/PyMuPDF#457]
hi
thanks for this awesome library.
only a comment :

to use the library i need to import fitz,
in order to use for example method open.

but fitz is another libraries,

and if i pip install fitz instead of PyMuPDF i'm importing something else,
then i'm not able to remove fitz from requirements.txt,
i need to manually remove fitz and install PyMuPDF

why does the module is not called pymuypdf ? 

thanks.

**Comment by JorjMcKie** [comment]
It is because the creator of this repository, @rk700 years ago has decided it so.
It has had good reasons, which you undoubtedly have read in the first pages of the documentation:
The makers of the base library used, MuPDF have called their main library component (the document-independent one) ``fitz``.

**Comment by JorjMcKie** [comment]
Also note, that that other library has been created later than this one - we exist since 2015 or so.
There are several famous examples for libraries with a deviating top-level name, e.g. ``PIL`` for Pillow.

**Comment by andreabisello** [comment]
understand, thanks

**Comment by informatik01** [comment]
## For the historical reference
- With the new versions of PyMuPDF we can import this module as `pymupdf` (see ["Note on the Name fitz"](https://pymupdf.readthedocs.io/en/latest/tutorial.html#note-on-the-name-fitz))
- The history behind the previous naming: [PyMuPDF 1.24.3 and Farewell to “Fitz”](https://artifex.com/blog/pymupdf-1.24.3-and-farewell-to-fitz)
