### ISSUE TITLE
The image extracted has size greater than the pdf page size

### ISSUE THREAD

**Issue by nandagopal1992** [pymupdf/PyMuPDF#458]
Hi , I used the recommended way to extract images from a pdf document. The page was having a resolution of 596 * 841. I extracted the image whose bounding box was Rect(67.0, 12.09, 458.5, 90.09). The resolution of the image extracted is 1352 * 270 . How is this possible ? Can we scale this down to original size before saving?

**Comment by JorjMcKie** [comment]
> The resolution of the image extracted is 1352 * 270 . How is this possible ? Can we scale this down to original size before saving?

This is even normal!
Storing an image in its original size often does make sense, if you think of zooming the display: If the embedded image quality has enough "reserve", then it remains nice even when zooming into it at 200%.
But you are right: this type of thing may be a big waste of space, unnecessarily increasing the PDF file size.
There are a few ways to prevent this:
1. Use the ``thumbnail`` method of ``PIL.Image``, which allows you to scale down to the desired sizes.
2. PyMuPDF offers similar features for pixmaps:

    - ``Pixmap.shrink()`` reduces in-place by dividing width and height by a power of 2 (2, 4, etc.), which decreases the size to 1/4, 1/16, etc. of the original.

    - Copy to a new pixmap by providing the desired new width and height values: ``pix2 = fitz.Pixmap(pix1, w, h, clip)``. This function even allows you to copy just the ``clip`` (rectangle) part of pix1.

After doing one of these things, store the image in the PDF.

**Comment by JorjMcKie** [comment]
Do you feel this answers your question?

**Comment by nandagopal1992** [comment]
Yes , thanks 👍
