### ISSUE TITLE
Question: Update RadioButtons / CheckBoxes 

### ISSUE THREAD

**Issue by lvapeab** [pymupdf/PyMuPDF#460]
Hi,
I want to set the value of a RadioButton or mutually exclusive checkboxes, as those from this pdf: https://www.lacba.org/docs/default-source/member-benefits/epl-2504-0615-admiral-epl-only-proposal-form.pdf

In the case of this example, I tried to update two checkboxes that share name. But these changes are not reflected in the pdf. I can give more details if required. I suspect this is related to the way these values are stored in the pdf. According to the PDF reference 1.7 (p. 689):

```
The Kids entry in the radio button field’s field dictionary (see Table 8.69 on page 675) holds an array of widget annotations representing the individual buttons in the set. The parent field’s V entry holds a name object corresponding to the appearance state of whichever  child field is currently in the on state; the default value for this entry is Off.
```

Is there a way to do this? I updated text fields and "simple" checkboxes without issues.

Thanks!

**Comment by JorjMcKie** [comment]
Hm, unfortunately I am not yet supporting such hierarchies of of button.
I am willing to take this on my list of enhancements, but cannot make promises as to which version may contain it ...

**Comment by lvapeab** [comment]
Got it. Thanks for the answer.
