### ISSUE TITLE
Signature Check for a pdf

### ISSUE THREAD

**Issue by manish59** [pymupdf/PyMuPDF#461]
I'm trying to check a pdf for a signautre and the value i got is 0. but in the documentation we have only -1,1 and 3. I have attached the pdf can you look in to that why it is behaving like that.
[coyle-yvonne-20161107-296-1080-1572.pdf](https://github.com/pymupdf/PyMuPDF/files/4301159/coyle-yvonne-20161107-296-1080-1572.pdf)

**Comment by JorjMcKie** [comment]
A documentation issue only:
* -1: some type of error
* 0: no signature fields present
* 1: signature field(s) present, but no signed one
* 3: at least one signed signature fields exists

**Comment by JorjMcKie** [comment]
Fixed with v1.16.12.
