### ISSUE TITLE
Complex line elements not handled

### ISSUE THREAD

**Issue by wwwslinger** [pymupdf/PyMuPDF#462]
**Is your feature request related to a problem? Please describe.**
Some PDF pages have complex line drawings in them that are not images.  PyMuPDF is not rendering these as HTML or extracting them as images, but they do appear when converting a page to an image.

**Describe the solution you'd like**
It would be great to convert complex lines into an SVG object for display in HTML or to export as an image.

**Describe alternatives you've considered**
Currently I need to detect a threshold level of line elements and convert the full page to an image instead of HTML or extracting an image.  This gets tricky when there are tables, which also have many "lines" elements.  It also means an extra step for every page to extract to JSON, count the "lines" elements, and then proceed with HTML (under threshold) or a full page image (over threshold).

**Additional context**
See the attached "missed_lines_example.pdf" for an example page that does not render the drawing.
[missed_lines_example.pdf](https://github.com/pymupdf/PyMuPDF/files/4301510/missed_lines_example.pdf)

**Comment by JorjMcKie** [comment]
While SVG image creation with MuPDF does have its weaknesses, it seems to work well in your case!

```python
doc = fitz.open(filename)
page = doc[0]
svg = page.getSVGimage()
outsvg = open("page.svg", "w")
outsvg.write(svg)
outsvg.close()
```

Produces a nice SVG version of the page - at least at first sight.

**Comment by JorjMcKie** [comment]
If you are willing to undergo the effort interpreting the SVG source, then you might as well consider directly interpreting the PDF page's ``/Content`` object - should be similar complexity:

```python
page._cleanContents()
clist = page._getContents()  # fetch list of xrefs of contents objects.
# has just one element b/o contents cleaning
xref = clist[0]
cont = doc.xrefStream(xref).decode()  # read contents as a string
```
The syntax has some similarities to SVG and PostScript and is described in the PDF manual "Appendix A Operator Summary", page 985.

**Comment by wwwslinger** [comment]
Also noticed that lines in tables or elsewhere do not appear in the HTML output, either, so seems to be a general lack of implementation to handle lines.  In the "missed_lines_example.pdf" file, you can see the top line and the bottom small boxes are missing when output is HTML.  Also see the table in the attached "missed_table_lines.pdf".  The table structure comes out nicely in HTML, but no cell or table borders show.  
[missed_table_lines.pdf](https://github.com/pymupdf/PyMuPDF/files/4302193/missed_table_lines.pdf)

**Comment by wwwslinger** [comment]
@JorjMcKie Interesting approach.  I'll take a look and see what I can come up with.  Thanks!

**Comment by wwwslinger** [comment]
Just saw this: https://github.com/pymupdf/PyMuPDF/issues/178 . It is the same issue, so perhaps this is still not an attractive cost/benefit ratio.

**Comment by wwwslinger** [comment]
A solution that seems to work thus far is to follow your exploration from #178 -- run the the page through the `remove_text` function in [anonymize.py](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/anonymize.py) then get the SVG and add it to the main div element in the HTML output.  So far, this captures all the header lines, the boxes at the bottom, table lines, and any drawings.  
For pages that already have images, I also have to remove the symbol and image tags.  Can use a simple regex:
```
import re
TAG_RE = re.compile(r"<.?symbol[^>]*>|<.?use[^>]*>|<.?image[^>]*>")
def remove_tags(text):
    return TAG_RE.sub('', text)

svg = remove_tags(page.getSVGimage())
```

**Comment by JorjMcKie** [comment]
If using the ``remove_text`` function, one might easily also remove references to images and so-called ``/XObjects``. Both are displayed on the page by the same command in PDF ``/Contents`` syntax: ``/name Do``, where ``name`` is the image or xobject reference name.
After having a formatted ``/Contents`` source thanks to ``page._cleanContents()``, one can rely on the fact that any ``/name Do`` will look exactly like this and live on its own line ... easy to remove by checking ``startswith("/")`` and ``endswith("Do")``.

**Comment by wwwslinger** [comment]
Wonderful, thanks!

**Comment by JorjMcKie** [comment]
Okay to close this?
