### ISSUE TITLE
NameError: name 'unicode' is not defined (line 2760 in 'fitz.py')

### ISSUE THREAD

**Issue by jaredRSEC** [pymupdf/PyMuPDF#466]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
line 2760 in 'fitz.py': (in 'save' function)
elif type(filename) == unicode:
NameError: name 'unicode' is not defined

## To Reproduce (mandatory)
doc = fitz.open()
doc.newPage()
doc.save('save_test.pdf')

## Expected behavior (optional)
Should save the file without error.

## Your configuration (mandatory)
Windows 10 64-bit
Python 3.7.2 64-bit
PyMuPDF 1.16.13

## Additional context (optional)
Fixed by adding `from past.builtins import unicode` to top of 'fitz.py'.

**Comment by JorjMcKie** [comment]
Sorry, cannot reproduce this error.
Your snippet works fine with me for all Python versions .
Also, the referenced line should never be executed in Python 3 ... but I will consider to make sure that it ever will only be used for Python 2.

**Comment by JorjMcKie** [comment]
The next version will have the following change in behavior:
 If filename is not ``str`` then a Python 2 check is made and then type``unicode`` is checked. If that fails, ``str(filename)`` is used and a potential exception accepted at that point.

This avoids more imports and still supports filenames provided as ``pathlib.Path``.

**Comment by JorjMcKie** [comment]
New version 1.16.14 is on PyPI.

**Comment by cbm755** [comment]
On 1.16.11, I could hit something like using pathlib.
```py
from pathlib import Path
p = Path('hello.pdf')
```
then
```py
doc = fitz.open() 
doc.newPage()                                                                                  
doc.save(p)

       ~/.local/lib/python3.7/site-packages/fitz/fitz.py in save(self, filename, garbage, clean, deflate, incremental, ascii, expand, linear, pretty, encryption, permissions, owner_pw, user_pw)
   2673         if type(filename) == str:
   2674             pass
-> 2675         elif type(filename) == unicode:
   2676             filename = filename.encode('utf8')
   2677         else:

NameError: name 'unicode' is not defined

```

```py
>>> fitz.version                                                                                   
('1.16.11', '1.16.0', '20200221154027')
```

But upgrading to 1.16.14 fixed it for me.

**Comment by JorjMcKie** [comment]
@cbm755 - thank your for the feedback!
