### ISSUE TITLE
Question / Comment: Pix generation parameters?

### ISSUE THREAD

**Issue by mpalazz** [pymupdf/PyMuPDF#467]
I am currently working with generating low dpi images of pdfs.  I was wondering if there are underlying parameters that control how the image is generated?  I'm specifically interested in preserving black line segments. At low res, they are generated fuzzier and gray.   Thanks again for this awesome module - I use it every day.

**Comment by JorjMcKie** [comment]
Thanks for finding PyMuPDF useful!

I am not sure I understand:
Did you mean images generated from a PDF page - like with ``page.getPixmap()``?
You can control its quality via ``page.getPixmap(matrix=mat)`` with a matrix ``mat=fitz.Matrix=(f,f)``. Set the zoom factor f to a value > 1 until the resulting image is good enough.

Of course the effect is limited to non-raster page content: if the page itself contains images, then these will appear blurred if magnified beyond their inherent resolution ...

**Comment by mpalazz** [comment]
Yes! I am generating low dpi images from pdfs using getPixmap and the scale matrix.  I'm curious if there are any parameters that control the underlying module that translates the vector graphic into an image.  Often times, in other applications, parameters like compression method and anti-aliasing can be toggled.  Thanks again!

**Comment by JorjMcKie** [comment]
I am afraid that plus gamma correction is about all there is for the moment. As yet I have not enabled changing the anti-aliasing value (but letting it default to the maximum).
I would be interested though to see if you can achieve approvements by using a different configuration with the mutool command line module - it allows changing the anti-aliasing value ...

**Comment by mpalazz** [comment]
I'll attempt it.  Would this be something you could eventually add as a feature?  Happy to put in a feature request.  Thanks!

**Comment by mpalazz** [comment]
[Here is the function in mupdf.](https://github.com/ArtifexSoftware/mupdf/blob/7d9c33bb50f555b97f7d3e52324c25820e3f414d/source/fitz/draw-rasterize.c#L151)

**Comment by JorjMcKie** [comment]
> Would this be something you could eventually add as a feature? Happy to put in a feature request.

Thanks for the hint.
Yeah, let me check and understand ... also how to integrate with the programming API of PyMuPDF ...

**Comment by JorjMcKie** [comment]
@mpalazz - following your request I am implementing this feature in the next version, 1.16.14.
The anti-aliasing values in MuPDF are present in the global context and not implemented / modified on a per pixmap or per rendering action.
So I decided to also implement them as global functions in PyMuPDF, which establish a new global value (for the current session). This works like so:

```python
>>> import fitz
>>> fitz.TOOLS.anti_aliasing_values()
{'graphics': 8, 'text': 8, 'graphics_min_line_width': 0.0}
>>> fitz.TOOLS.set_aa_level(4)
>>> fitz.TOOLS.anti_aliasing_values()
{'graphics': 4, 'text': 4, 'graphics_min_line_width': 0.0}
>>> # now generate your pixmap etc., do not forget to also use gamma correction:
>>> pix.gammaWith(factor)  # factor > 1.0
>>> # change the AA values again anytime
>>> # don't know yet the effect of the min. line width setting.
```

**Comment by mpalazz** [comment]
Thanks for the fast response time!

**Comment by JorjMcKie** [comment]
New version 1.16.14 is on PyPI.

**Comment by mpalazz** [comment]
I updated to 1.16.14 and got a seg fault without changing any of my code.  It originates around Document.._deleteObject(xref).  I will have more on that soon with a reproducible example.   Thanks again.

**Comment by JorjMcKie** [comment]
>  I will have more on that soon with a reproducible example

Oha, please do so!

**Comment by JorjMcKie** [comment]
There is a general problem with that version 1.16.14.
If you tell me your configuration I can send you a wheel for repeating the tests and avoid hunting the wrong deer ...

**Comment by mpalazz** [comment]
I don't understand - can you restate that?  How does this wheel differ from 1.16.14? 
I run conda envs with python 3.7 and 3.8 on macos 10.14.6.

**Comment by JorjMcKie** [comment]
Please download the new version 1.16.15 from PyPI.
It fixes a stupid mistake of mine which I suspect also has hit you.
If this is unexptedly is not the case: could you shae your script and a suitable PDF?
Good luck!

**Comment by mpalazz** [comment]
My current code still crashes.  I will work on getting you a script with a
pdf.

**Comment by mpalazz** [comment]
I uploaded a new script with a new issue that clearly shows the issue.  Thanks for all your help.

**Comment by JorjMcKie** [comment]
OK, got it - thatnks for the script and the example PDF.
I will look into it.
