### ISSUE TITLE
Is there a way to increase hit_max parameter for Page.searchFor?

### ISSUE THREAD

**Issue by hieu-lam** [pymupdf/PyMuPDF#470]
I'm wondering if it is possible to return more man 16 hits when using `Page.searchFor` method. I just want to make sure I don't miss any items on the page. 

I'm aware that there is an alternative using  `Page.getTextWords()`, but that gives the Rect() object for a single word - and that is simply not what I want. Sometimes (or most of the time) I also want to highlight the whole **phrase** instead. (Of course, that can be done by comparing the whole phrase with a combination of consecutive words iteratively from the start until we reach the end of the page. If there is a match, highlight each word. ) But how about increasing `hit_max `to 32, or 64?

**Comment by JorjMcKie** [comment]
MuPDF pre-allocates an array of length ``hit_max + 1``. There is no way to extend this "dynamically". If you want to be on the safe side, choose a large enough value. How about 100? This will result in the allocation of 101 * 8 floats. Once the method returns its list to you, those floats have already been de-allocated.

**Comment by hieu-lam** [comment]
Thank you so much for your answer. Seems like it's the best way from now.
