### ISSUE TITLE
Question / Comment:

### ISSUE THREAD

**Issue by psg719** [pymupdf/PyMuPDF#471]
Hello, I'm a new Python learner, please excuse me if this is a dumb question.
I'm trying to fill out a pdf form. How do I determine the point coordinates of a specific place on the pdf so I can insert the text appropriately in the correct place?

Please see my code for inserting text so far:

`def Example(text,p):
    page = doc[1] # new or existing page via doc[n]
    p = fitz.Point(68, 770)  # start point of 1st line (latitude,longitude)
    text = "aa" #37 character limit
    rc = page.insertText(p,  # bottom-left of 1st char
                     text,  # the text (honors '\n')
                     fontname = "helv",  # the default font
                     fontsize = 9,  # the default font size
                     rotate = 90,  # also available: 90, 180, 270
                     )
`

**Comment by JorjMcKie** [comment]
If you fill out a **Form** PDF, then you are filling out form fields ("widgets"). This entails putting values in ``widget.field_value``, for which you need no position knowledge: the position is where the field lives on the page.
If you just write text to a page, like in your example (hard to read btw.), then it is up to you where you want to put the text. Method `insertText()`` starts writing with the first character's bottom-left point at the coordinate given as first argument.
If you want to fill a certain rectangular area with some text, you can also use ``insertTextbox()``. Again it is you who must know how to find / determine the rectangle position.

I guess you should provide an example where you have problems finding an insertion point ...

**Comment by psg719** [comment]
Thanks for prompt reply, it is technically not a fillable pdf. Just regular pdf with blank spaces that I would like to fill at specific points. My question is, how do I determine exactly what those points are without doing trial and error.

`def HomeMeds(text,p):
    page = doc[1]
    p = fitz.Point(68, 770)  
    text = "aa" 
    rc = page.insertText(p,text, fontname = "helv", fontsize = 9,rotate = 90)`

**Comment by JorjMcKie** [comment]
Do you know anything about those locations at all? Is there some text that could be used for orientation, or anything else?

**Comment by psg719** [comment]
Yes, for example I want to fill out my text in the text box under the "Name" field.

**Comment by JorjMcKie** [comment]
Ah ok. In this case you can search for "name":
```python
rect_list = page.searchFor("name")  # this is a list of rectangles
rect = rect_list[0]  # is the first rectangle surrounding a string of "name" (upper or lower case!)
page.insertText(rect.br + (5, 0), "your text" ...)  # puts text 5 pixels to the right of that string
page.insertText(text.bl + (0, line_height), "your text", ...)  # puts text below that string ...
# calculate line_height as fontsize * 1.2
# etc.
```

**Comment by JorjMcKie** [comment]
Did this answer your question?

**Comment by psg719** [comment]
Yes this was exactly the answer I needed. I finally made it work for my setup! Thank you very much again.
