### ISSUE TITLE
Question: How do I search for multiple strings using page.SearchFor()? 

### ISSUE THREAD

**Issue by graceen95** [pymupdf/PyMuPDF#475]
Hi! It's so fantastic I found PyMuPDF

Is there a way to search for multiple strings using page.SearchFor? This is what I did and the error message I get is: TypeError: in method 'TextPage_search', argument 2 of type 'char const *'. I don't get this error message if my search_terms is a single string.
```

import fitz
pdf_document = fitz.open("output.pdf")


search_terms = ['dog', 'cat', 'fish']

for i in range(len(pdf_document)):

     page = pdf_document[i]

     text_instances = page.searchFor(search_terms)

     for inst in text_instances:
        print(inst, type(inst))
        highlight = page.addHighlightAnnot(inst)

pdf_document.save("highlightedoutput.pdf", garbage=4, deflate=True, clean=True)
```

**Comment by JorjMcKie** [comment]
No, sorry, you cannot do that. Neither regex expressions are possible.
But your above example's result can be achieved by doing separate searches, then join their results ...

```python
for page in doc:
    results=[]
    for item in search_items:
        results.extend(page.searchFor(item))
    for rect in results:
        ...
```
    

You may also want to have a look at the several variants of ``page.getText(opt)``, where opt is one of "blocks", "words",, "dict".

**Comment by JorjMcKie** [comment]
@graceen95 - did this answer your question?

**Comment by JorjMcKie** [comment]
Closing this for now.

**Comment by MarceloPiemonteRibeiro** [comment]
@JorjMcKie I have a similar issue as @greysnam but I am using a different piece of code (below). Is it still impossible to search for several items at once? If not, do you know how I could proceed in the example below?

```
import fitz     
# opening the pdf file  
my_pdf = fitz.open("AR_Finland_2021.pdf")      
# input text to be highlighted  
my_text = ['blood', 'first aid', 'volunteers', 'staff']    
# iterating through pages for highlighting the input phrase  
for n_page in my_pdf:  
    matchWords = n_page.search_for(my_text)      
    for word in matchWords:  
        my_highlight = n_page.add_highlight_annot(word)  
        my_highlight.update()     
# saving the pdf file as highlighted.pdf  
my_pdf.save("highlighted_text.pdf")  
```

**Comment by JorjMcKie** [comment]
>  Is it still impossible to search for several items at once?

Yes it is. At least for the `page.search_for()` method.
There are several ways to circumvent this restriction:
```python
# option 1
rect_list = page.search_for(needle1) + page.search_for(needle2) + ...
# option 2 - usable in case of needles without white space
words = [fitz.Rect(w[:4]) for w in page.get_text("words") if w[4] in my_text]
# option 3: records rectangles of text pieces containing a needle word
rects = []
for b in page.get_text("dict")["blocks"]:
    for l in b["lines"]:
        for s in l["spans"]:
            if set(s["text"].split()).intersection(set(my_text)) != set():
                rects.append(fitz.Rect(s["bbox"]))
```
