### ISSUE TITLE
Trouble with 1.1.16.14

### ISSUE THREAD

**Issue by PCarle** [pymupdf/PyMuPDF#476]
my python 3.5 crash on any examples, (all are tested with 1.16.13 version )

**Comment by JorjMcKie** [comment]
what the hell.
Something with the last binary generation went really wrong!
I think I will have to revoke the complete release - my Windows doesn't work either!

**Comment by JorjMcKie** [comment]
Found the problem - my fault. I will send you a new wheel for your installation on this channel. Would be nice if you could try it out.

The error concerns a certain C function used incorrectly. Its effect is not omnipresent and mainly pertains to annotations, so, there is probably no need to completely rewind that release ...

**Comment by JorjMcKie** [comment]
What is your OS? Linux?

**Comment by mpalazz** [comment]
@JorjMcKie my seg fault arises when I delete widgets.  Just fyi.

**Comment by PCarle** [comment]
i'am under window7 
code example:
'''python
### StampAnnot&Unicode
# -*- coding: utf-8 -*-
import sys
print("Python", sys.version, "on", sys.platform, "\n")
import fitz
print(fitz.__doc__, "\n")

import chardet

import os
print (os.getcwd())
from matplotlib.pyplot import imshow
import numpy as np
from PIL import Image

def print_descr(rect, annot):
    """Print a short description to the right of an annot rect."""
    annot.parent.insertText(rect.br + (10, 0),
                    "'%s' annotation, name \"%s\", content \"%s\"" % (annot.type[1],
                                                             annot.info['name'].encode('latin-1').decode("utf-8"),
                                                             annot.info['content'].encode('latin-1').decode("utf-8")), color = red)

doc = fitz.open()
page = doc.newPage()

annot = page.addStampAnnot(fitz.Rect(10,10,200,60))
annot.setColors(stroke=fitz.utils.getColor('red4'))
annot.setOpacity(0.5)
annot.setName("le chat Botté")
annot.setInfo(content="le chat Botté")
annot.update()

print_descr(annot.rect, annot)
print("name ["+annot.info['name']+\
      "] re-encoded ["+\
      annot.info['name'].encode('latin-1').decode("utf-8")+\
      "]")
print("content ["+annot.info['content']+\
      "] re-encoded ["+\
      annot.info['content'].encode('latin-1').decode("utf-8")+\
      "]")
page = doc.reload_page(page)
pix=page.getPixmap(matrix=fitz.Matrix(fitz.Identity).preScale(3,3),alpha=True,colorspace="RGB")

from PIL import Image, ImageTk
mode = "RGBA"
img = Image.frombytes(mode, [pix.width, pix.height], pix.samples)

from matplotlib import pyplot as plt
import matplotlib as mpl
mpl.rc("savefig", dpi=300)
plt.figure(figsize = (20,20))
fig, ax = plt.subplots(figsize=(18, 20))
ax.imshow(np.asarray(img))
#ax.imshow(plt.imread(imgdata))
plt.show()
'''
crash 1.16.14 
Patrice

**Comment by JorjMcKie** [comment]
I fixed the error and will soon upload a new version 1.16.15.

Some more background for this bug:
In trying to fix the wrong encoding you observed in the info dictionary of annotations, I used a different C function whithout checking whether it raises an exception ... 🙄

**Comment by JorjMcKie** [comment]
There is a new version 1.16.15 on PyPI now. I hope it addresses this issue!

**Comment by PCarle** [comment]
Euh... it still crash each time! 
```python 
### StampAnnot&Unicode
# -*- coding: utf-8 -*-
import platform 
print("OS",platform.system(),platform.release())
import sys
print("Python", sys.version, "on", sys.platform, "\n")
import fitz
print(fitz.__doc__, "\n")

import chardet

import os
print (os.getcwd())
from matplotlib.pyplot import imshow
import numpy as np
from PIL import Image

def print_descr(rect, annot):
    """Print a short description to the right of an annot rect."""
    annot.parent.insertText(rect.br + (10, 0),
                    "'%s' annotation,\nname \"%s\" re-encoded \"%s\",\
                            \ncontent \"%s\" re-encoded \"%s\"" % 
                            (annot.type[1],
                             annot.info['name'],
                             annot.info['name'].encode('latin-1').decode("utf-8"),
                             annot.info['content'],
                             annot.info['content'].encode('latin-1').decode("utf-8")), 
                            color = fitz.utils.getColor('red'))

doc = fitz.open()
page = doc.newPage()

annot = page.addStampAnnot(fitz.Rect(10,10,200,60))
annot.setColors(stroke=fitz.utils.getColor('red4'))
annot.setOpacity(0.5)
annot.setName("le chat Botté")
annot.setInfo(content="le chat Botté")
annot.update()

print_descr(annot.rect, annot)
print("name ["+annot.info['name']+\
      "] re-encoded ["+\
      annot.info['name'].encode('latin-1').decode("utf-8")+\
      "]")
print("content ["+annot.info['content']+\
      "] re-encoded ["+\
      annot.info['content'].encode('latin-1').decode("utf-8")+\
      "]")
page = doc.reload_page(page)
pix=page.getPixmap(matrix=fitz.Matrix(fitz.Identity).preScale(3,3),alpha=True,colorspace="RGB")

from PIL import Image, ImageTk
mode = "RGBA"
img = Image.frombytes(mode, [pix.width, pix.height], pix.samples)

from matplotlib import pyplot as plt
import matplotlib as mpl
mpl.rc("savefig", dpi=300)
plt.figure(figsize = (20,20))
fig, ax = plt.subplots(figsize=(18, 20))
ax.imshow(np.asarray(img))
#ax.imshow(plt.imread(imgdata))
plt.show()
```
produce:
```
OS Windows 7
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32 


PyMuPDF 1.16.15: Python bindings for the MuPDF 1.16.0 library.
Version date: 2020-03-26 15:15:15.
Built for Python 3.7 on win32 (64-bit).
 

C:\Python37\Scripts
```
and crash

**Comment by JorjMcKie** [comment]
There still is an error in setInfo. Please use the dictioary instead of direct parameters to circumvent it for the moment.

**Comment by JorjMcKie** [comment]
There is a new version out on PyPI.
Hope this time I have grasped all the open ends ...
