### ISSUE TITLE
Doc Bug or code bug ?

### ISSUE THREAD

**Issue by PCarle** [pymupdf/PyMuPDF#477]
in documentation on annot.setName :
"If you set ..... fitz.getTextLength(text, fontname="tiro", fontsize=20) / annot.rect.width <= 0.85."

but in fitz code is fitz.getTextLength don't exist, the implemented function is fitz.getTextlength ("l" from length is not capitalized)

**Comment by JorjMcKie** [comment]
ok, thank you.
I will change the docu.

**Comment by PCarle** [comment]
So i test the condition, i may be do something wrong : (i use tyhe 1.16.13 version some troubles with 1.16.15) 

```python
### StampAnnot
# -*- coding: utf-8 -*-
import platform 
print("OS",platform.system(),platform.release())
import sys
print("Python", sys.version, "on", sys.platform, "\n")
import fitz
print(fitz.__doc__, "\n")
print (fitz.getTextlength)
import os
print (os.getcwd())
from matplotlib.pyplot import imshow
import numpy as np
from PIL import Image

def print_descr(rect, annot):
    """Print a short description to the right of an annot rect."""
    annot.parent.insertText(rect.br + (10, 0),
                    "'%s' annotation" % annot.type[1], color = fitz.utils.getColor('red'))

doc = fitz.open()
page = doc.newPage()
rect=fitz.Rect(10,10,400,120)
text="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
annot = page.addStampAnnot(rect)
newtext=''
for i in text:
    #print(newtext,"legnth",fitz.getTextlength(newtext, fontname="tiro", fontsize=20))
    #print(i," lenth ",fitz.getTextlength(i,fontname="tiro", fontsize=20))
    if ((fitz.getTextlength(newtext, fontname="tiro", fontsize=20)+
        fitz.getTextlength(i,fontname="tiro", fontsize=20))/
        annot.rect.width) <= 0.85:
        newtext+=i
    else:
        break
print("\n\nChange text:"
    "\n\ttext length :",fitz.getTextlength(newtext, fontname="tiro", fontsize=20),
    "\n\tannot width: ",annot.rect.width,
    "\n\tcorrect? ",
    (fitz.getTextlength(newtext, fontname="tiro", fontsize=20)/annot.rect.width)<=0.85)
annot.setColors(stroke=fitz.utils.getColor('red'))
annot.setOpacity(0.5)

annot.setName(newtext)
annot.update()


print_descr(annot.rect, annot)

page = doc.reload_page(page)
pix=page.getPixmap(matrix=fitz.Matrix(fitz.Identity).preScale(3,3),alpha=True,colorspace="RGB")

from PIL import Image, ImageTk
mode = "RGBA"
img = Image.frombytes(mode, [pix.width, pix.height], pix.samples)

from matplotlib import pyplot as plt
import matplotlib as mpl
mpl.rc("savefig", dpi=300)
plt.figure(figsize = (20,20))
fig, ax = plt.subplots(figsize=(18, 20))
ax.imshow(np.asarray(img))

plt.show()
```
Results:
OS Windows 7
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32 


PyMuPDF 1.16.13: Python bindings for the MuPDF 1.16.0 library.
Version date: 2020-03-15 05:29:04.
Built for Python 3.7 on win32 (64-bit).
 

<function getTextlength at 0x0000000005263318>
C:\Python37\Scripts


Change text:
	text length : 317.7599792480469 
	annot width:  390.0 
	correct?  True

<Figure size 1440x1440 with 0 Axes>
<img src=https://user-images.githubusercontent.com/16350743/77771531-170df100-7047-11ea-9dfe-dee79d5fe778.png)>

**Comment by JorjMcKie** [comment]
The formula I provided is overly complicated I am afraid, and also does not deliver the maximum possible length in all cases.
And then the **_fontname_** must be Times-Bold, _**tibo**_.
I have been finally successful with this script:

```python
import fitz
from PIL import Image

doc = fitz.open()
page = doc.newPage()
annot = page.addStampAnnot((100, 100, 500, 200))
text = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
q = fitz.getTextlength(text, fontname="tibo", fontsize=20)
while q > 190:
    text = text[:-1]  # cut off last char
    q = fitz.getTextlength(text, fontname="tibo", fontsize=20)
annot.setName(text)
annot.update()
page = doc.reload_page(page)

pix = annot.getPixmap()
img = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
img.show()
```
this was shown:
![grafik](https://user-images.githubusercontent.com/8290722/77783593-84ae2300-702f-11ea-9ad5-c04fd8f09212.png)

**Comment by JorjMcKie** [comment]
There is a new version 1.16.16 on PyPI. The docu is updated as well.
Hope this clarifies the point. Otherwise please suggest a better formulation.
Thanks.

**Comment by JorjMcKie** [comment]
I assume this is answered.
