### ISSUE TITLE
1.16.16 Seg Fault on Widget iteration

### ISSUE THREAD

**Issue by mpalazz** [pymupdf/PyMuPDF#478]
## Seg Fault on Widget iteration
Since 1.16.13, there has been a clear breakage in widget iteration.  The code below gives an example of this behavior. 

## To Reproduce:
The following code finishes with version 1.16.13 and breaks in  1.16.14-16:
```
import requests
import fitz
stream_url = "http://arkansas-dar.org/wordpress/wp-content/uploads/2014/06/DEV-1003-Donation-Form.pdf"
res = requests.get(stream_url)
mudoc = fitz.open(stream=res.content, filetype='pdf')
for f in mudoc[0].widgets():
    print(f.field_type_string)
```

## Configuration:
 - macOS 10.14.6
 - Python 3.7+
 - Pymupdf versions 1.16.13-1.16.16 installed from PyPI

**Comment by JorjMcKie** [comment]
Thanks for submitting this ...
I have found and corrected the error. Testing on Windows and Linux shows, that the error is gone.
Currently wating for the Mac Wheel generation to finish. I don't have a Mac, but as soon as those wheels are created, you can download and install the wheel relevant for you. I will show you how to do this as soon as this is available (matter of 10 minutes or so).

**Comment by mpalazz** [comment]
great - ready when you are.

**Comment by JorjMcKie** [comment]
Ah, here we are already. Please download your [wheel](https://github.com/pymupdf/PyMuPDF-wheels/blob/osx/PyMuPDF-1.16.16-cp37-cp37m-macosx_10_9_x86_64.whl).
Then execute in a terminal:
```text
python -m pip install -U PyMuPDF-1.16.16-cp37-cp37m-macosx_10_9_x86_64.whl
```
You should be fine if all works out 😎

**Comment by JorjMcKie** [comment]
The error happens in a corner case I think. So I hope I do not have to make a new release for this.
Of course, the fix will be contained in the next official version.

**Comment by mpalazz** [comment]
I can confirm that this bug is Fixed.  Thanks again.

**Comment by JorjMcKie** [comment]
Excellent!
Thanks for the feedback and sorry for the inconveniences ...
