### ISSUE TITLE
The order of block elements is incorrect in the documentation

### ISSUE THREAD

**Issue by tsiq-maxime** [pymupdf/PyMuPDF#481]
I will bypass the mandatory format of a bug report as it is not exactly a bug, just a documentation error.

The documentation for the method `extractBlocks` [here](https://pymupdf.readthedocs.io/en/latest/app2/) reads:

#########################################################
BLOCKS
Function TextPage.extractBLOCKS() (or Page.getText(“blocks”)) extracts a page’s text blocks as a list of items like:

(x0, y0, x1, y1, "lines in block", block_type, block_no)
Where the first 4 items are the float coordinates of the block’s bbox. The lines within each block are concatenated by a new-line character.

This is a high-speed method with enough information to re-arrange the page’s text in natural reading order where required.

Example output:

>>> print(page.getText("blocks"))
[(50.0, 88.17500305175781, 166.1709747314453, 103.28900146484375,
'Some text on first page.', 0, 0)]

########################################################

This is incorrect as the real order of a block is 
`(x0, y0, x1, y1, "lines in block", block_type, block_no)`

This is the behaviour I observe and you can find the proof in the source code here: https://github.com/pymupdf/PyMuPDF/blob/05b3baf76dd00c00200caa425d6e012ab2673bf3/fitz/fitz.i#L7041

**Comment by JorjMcKie** [comment]
should have been addressed in version 1.16.17 uploaded today,
