### ISSUE TITLE
Add fill for Text Annotation 

### ISSUE THREAD

**Issue by PCarle** [pymupdf/PyMuPDF#485]
If annot is a text annotation  The fill argument of annot.setColor  (icon represented) will change the icon color ! (stroke argument change the background !)

**Comment by JorjMcKie** [comment]
No, if you try to set the fill color, you will reveice a warning, that this will not work.
This annot type **only** supports a stroke color - by definition of PDF spec.
And I don't want to rewrite MuPDF's code in that annotation's again ...
