### ISSUE TITLE
Question / Comment: how to access image bbox by its xref

### ISSUE THREAD

**Issue by yufc2002** [pymupdf/PyMuPDF#487]
I want to extract images and their coordinates from PDF files, but  I found that there are some cases it misses some images if I use  `Document.getPageImageList()` or  `Page.getImageList()`.

So, I tried to loop the objects through the xref,  like:
```
lenXREF = doc._getXrefLength() 
checkXO = r"/Type(?= */XObject)"           
checkIM = r"/Subtype(?= */Image)"  
for i in range(1, lenXREF):
    text = doc._getXrefString(i)    
    isXObject = re.search(checkXO, text)   
    isImage = re.search(checkIM, text) 
    if not isXObject or not isImage: 
        continue
    pix = fitz.Pixmap(doc, i) 
```
but how can I know where these images are in the pdf render images, in which page and their bbox? Thank you.

**Comment by JorjMcKie** [comment]
Have you tried ``page.getImageBbox(item)``?
This requires one of the items of ``doc.getPageImageList(page.number, full=True)``. The ``True`` is important here.

Just as an aside: It may still happen, that the image is not displayed by the page, although listed in the resources. Or, vice versa, a visible image on the page, but not in the list. Quite some circumstances can lead to these things:
* there may be a central ``/Resources`` object (which I need to check first ...), listing all images of all pages. I have seen this with PDFs created from scanned pages.
* pages containing so-called "inline" images. Typically small things like special bullet point formats, etc.
* watermark images

So you should always wrap ``getImageBbox`` in a try-except clause.

**Comment by yufc2002** [comment]
Thank you for your reply.

Yes, I have tried `page.getImageBbox(item)`. But problem is the `item` is the one of results from `doc.getPageImageList(page.number, full=True)` as you said, so when `doc.getPageImageList(page.number, full=True)` can't find all images in one specific page in the first place, I can't get all images and their bboxs.

My solution would be locate all images by their xrefs.
 
1. In my understanding, if I want to access an image's bbox by `page.getImageBbox(item)`, I would need a list contains image descriptions like [xref, smask, width, height, bpc, colorspace, alt. colorspace, symbolic name, filter, form_xref]. However, what I can access is only a part of them, when I invoked `doc.extractImage(xref)`. The first question is how can I access all  image descriptions ,especially the symbolic name , when I know the image xref ?

2. Is there any way else I can all images and their bbox ? 

Thank you.

**Comment by JorjMcKie** [comment]
if you see images on a page, which do **_not_** appear in ``getPageImageList``, then the situation is trickier. It may be that:

1. it is **_not_** an image at all, but a drawing produced directly using PDF drawing commands. Typically Gantt charts or mathematical functions are like that. A problem of this sort was discussed in #464 
2. it may be an "embedded image". This option is usually used for small images. These are not yet supported by PyMuPDF.
3. it may be a watermark image. Look in #468 to see how to confirm this.

``page.getText(option)`` (option being "dict" or "rawdict"), returns images displayed by the page. But with no connection to any xref. This is because this method is available for all document types - not just PDFs.

If all fails an confidentiallity permitting, you can also send me the PDf so I can have a look at it.

**Comment by yufc2002** [comment]
Thank you for your precious advice.

The images did not appear in `getPageImageList` turned out to be images in annotation.  That is very unusual. For now, I didn't find function to extract this kind of images In the document.

What I can access are xref numbers of both image and annotation objects, `annot.rect`  is the bbox I need, and `fitz.Pixmap(doc, image_xref)` is the image file I need. 

Question is how can I match them, if I have several image xref and several annotation xref ? 

I guess the best chance is to parse the objects, however I have no idea how to do that. Could you help with that?  If needed, please take below as an example.

1. The annotation object from `doc._getXrefString(annot.xref) `
```
<<
  /Rect [ 117.64232 375.50437 254.64232 506.74845 ]
  /Subtype /GoldGrid:AddSeal
  /F 4
  /Type /Annot
  /AP <<
    /N 3947 0 R
  >>
  /Info 3945 0 R
  /ChildList [ ]
  /TextUpDown 1
>>
```
2. the image object from `doc._getXrefString(image_xref) `
```
<<
  /Subtype /Image
  /Type /XObject
  /BBox [ 0 0 182 175 ]
  /BitsPerComponent 8
  /ColorSpace /DeviceRGB
  /Mask [ 200 255 200 255 200 255 ]
  /Width 182
  /Height 175
  /DecodeParms <<
    /Columns 182
    /Colors 3
    /Rows 175
  >>
  /Filter /FlateDecode
  /Length 5437
>>
```

Thank you for your time.

**Comment by JorjMcKie** [comment]
> The images did not appear in getPageImageList turned out to be images in annotation. That is very unusual. For now, I didn't find function to extract this kind of images In the document.

... and indeed, there is no such function.
Somewhere, somehow, the annotation must still reference the image, though. The typical place where an annotation's appearance is set up is the ``/AP`` object (of which you unfortunately can have more than one btw.) In your example, the "normal" appearance object `/AP/N` = 3947 would be the place to look via ``doc.xrefObject(3947)``.
``/AP`` objects in PDF terminology are **_Form XObjects_**, which have streams. These streams contain commands to construct the annot appearance (same mini language that you find in page ``/Contents`` objects).
So, probably in the object and / or stream part of 3947 we should find the reference to the image.
The annotation's appearance stream (the one of ``/AP/N``) can be extracted via ``annot._getAP()`` which is a Python ``bytes`` object, so ``decode("utf8")`` to get a string.

More notes:
* You are aware that annotations have there own ``getPixmap`` method?
* functionally equivalent to ``fitz.Pixmap(doc, xref)`` (which is a pixmap obviously) is ``doc.extractImage(xref)`` which extracts the ``native`` image format of xref - if at all possible. This is usually much faster, delivers smaller and **native** output: you will get a JPEG it the image is a JPEG.

**Comment by JorjMcKie** [comment]
How are you doing with your issue?
Any more input needed?
