### ISSUE TITLE
Widget field_name parameter is not writeable

### ISSUE THREAD

**Issue by mskrc2** [pymupdf/PyMuPDF#488]
I have a form template page that I am inserting multiple times within a larger PDF. Each individual form page has different field values, but because each form template has the same field names they conflict with each other (i.e. only the first form values show, the rest are blank).

I'd like a way to overwrite a Widget.field_name parameter so that the first form page has field_name[0], second is field_name[1], etc.

One possible option is to access the PDF bytes data and regex for the different field names and edit them there, but it would be nice if the field_names field was able to edited through the Widget class.

**Comment by JorjMcKie** [comment]
ok - let me see what I can do.

**Comment by mskrc2** [comment]
Thanks. I did find a workaround for my particular use case, which was just creating a new widget with all the parameters of a previously existing widget, except for a new field_name, then adding it to the page and using the Document._deleteObject() function to delete the old widget by its xref. But if it were possible to just overwrite a field_name I think it would be beneficial rather than go through that.

**Comment by JorjMcKie** [comment]
Ok, got you.
Pleased to see btw. that you are an avid user of PyMuPDF ...

**Comment by JorjMcKie** [comment]
Your feature will be included in the next version.
Required a minor change only.

**Comment by mskrc2** [comment]
Great to hear! Thank you for your hard work on this incredible package.

**Comment by JorjMcKie** [comment]
Thanks for the feedback!
The new version is out.
