### ISSUE TITLE
Print Text position,color,font

### ISSUE THREAD

**Issue by manish59** [pymupdf/PyMuPDF#489]
How to print each characters position, font, font color, page number ?

I think for font color how can we print r g b values for that character. I tried using a library called poppler.pdf which is based on libpoppler but its not working every time.

**Comment by JorjMcKie** [comment]
``page.getText("rawdict")`` should deliver what you want. It returns a (usually large) dictionary which is described [here](https://pymupdf.readthedocs.io/en/latest/textpage/).

Note of caution: it also returns any images on the page, which have a different sub-dictionary structure of course.
So select only the text bloks.

**Comment by manish59** [comment]
but the problem is, its not printing everything i wanted, it only prints text position, character, font and font color and font size.

**Comment by manish59** [comment]
{'width': 612.0, 'height': 792.0, 'blocks': [{'type': 0, 'bbox': (186.24000549316406, 116.42399597167969, 425.5921630859375, 127.1520004272461), 'lines': [{'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (186.240005
49316406, 116.42399597167969, 425.5921630859375, 127.1520004272461), 'spans': [{'size': 12.0, 'flags': 20, 'font': 'TimesNewRoman,Bold', 'color': 0, 'chars': [{'origin': (186.24000549316406, 124.55999755859
375), 'bbox': (186.24000549316406, 116.42399597167969, 192.2519989013672, 127.1520004272461), 'c': '2'}, {'origin': (192.24700927734375, 124.55999755859375), 'bbox': (192.24700927734375, 116.42399597167969,
 195.25900268554688, 127.1520004272461), 'c': '.'}, {'origin': (195.25401306152344, 124.55999755859375), 'bbox': (195.25401306152344, 116.42399597167969, 201.26600646972656, 127.1520004272461), 'c': '3'}, {
'origin': (201.26101684570312, 124.55999755859375), 'bbox': (201.26101684570312, 116.42399597167969, 204.27301025390625, 127.1520004272461), 'c': '.'}, {'origin': (204.2680206298828, 124.55999755859375), 'b
box': (204.2680206298828, 116.42399597167969, 210.9520263671875, 127.1520004272461), 'c': 'S'}, {'origin': (210.947021484375, 124.55999755859375), 'bbox': (210.947021484375, 116.42399597167969, 213.95901489
257812, 127.1520004272461), 'c': '.'}, {'origin': (213.9540252685547, 124.55999755859375), 'bbox': (213.9540252685547, 116.42399597167969, 219.9660186767578, 127.1520004272461), 'c': '4'}, {'origin': (219.9
600067138672, 124.55999755859375), 'bbox': (219.9600067138672, 116.42399597167969, 231.97201538085938, 127.1520004272461), 'c': '—'}, {'origin': (231.9600067138672, 124.55999755859375), 'bbox': (231.9600067
138672, 116.42399597167969, 240.63600158691406, 127.1520004272461), 'c': 'C'}, {'origin': (240.60800170898438, 124.55999755859375), 'bbox': (240.60800170898438, 116.42399597167969, 249.95599365234375, 127.1
520004272461), 'c': 'O'}, {'origin': (249.92800903320312, 124.55999755859375), 'bbox': (249.92800903320312, 116.42399597167969, 258.60400390625, 127.1520004272461), 'c': 'N'}, {'origin': (258.5760192871094,
 124.55999755859375), 'bbox': (258.5760192871094, 116.42399597167969, 266.5920104980469, 127.1520004272461), 'c': 'T'}, {'origin': (266.56402587890625, 124.55999755859375), 'bbox': (266.56402587890625, 116.
42399597167969, 275.2400207519531, 127.1520004272461), 'c': 'R'}, {'origin': (275.2120361328125, 124.55999755859375), 'bbox': (275.2120361328125, 116.42399597167969, 284.5600280761719, 127.1520004272461), '
c': 'O'}, {'origin': (284.53204345703125, 124.55999755859375), 'bbox': (284.53204345703125, 116.42399597167969, 292.54803466796875, 127.1520004272461), 'c': 'L'}, {'origin': (292.5200500488281, 124.55999755
859375), 'bbox': (292.5200500488281, 116.42399597167969, 295.53204345703125, 127.1520004272461), 'c': ' '}, {'origin': (295.5040588378906, 124.55999755859375), 'bbox': (295.5040588378906, 116.42399597167969
, 304.85205078125, 127.1520004272461), 'c': 'O'}, {'origin': (304.8240661621094, 124.55999755859375), 'bbox': (304.8240661621094, 116.42399597167969, 312.1680603027344, 127.1520004272461), 'c': 'F'}, {'orig
in': (312.14007568359375, 124.55999755859375), 'bbox': (312.14007568359375, 116.42399597167969, 315.1520690917969, 127.1520004272461), 'c': ' '}, {'origin': (315.12408447265625, 124.55999755859375), 'bbox':
 (315.12408447265625, 116.42399597167969, 323.8000793457031, 127.1520004272461), 'c': 'D'}, {'origin': (323.8800048828125, 124.55999755859375), 'bbox': (323.8800048828125, 116.42399597167969, 332.5559997558
594, 127.1520004272461), 'c': 'R'}, {'origin': (332.5460205078125, 124.55999755859375), 'bbox': (332.5460205078125, 116.42399597167969, 341.2220153808594, 127.1520004272461), 'c': 'U'}, {'origin': (341.2120
361328125, 124.55999755859375), 'bbox': (341.2120361328125, 116.42399597167969, 350.5600280761719, 127.1520004272461), 'c': 'G'}, {'origin': (350.550048828125, 124.55999755859375), 'bbox': (350.550048828125
, 116.42399597167969, 353.5620422363281, 127.1520004272461), 'c': ' '}, {'origin': (353.55206298828125, 124.55999755859375), 'bbox': (353.55206298828125, 116.42399597167969, 360.2360534667969, 127.152000427
2461), 'c': 'S'}, {'origin': (360.22607421875, 124.55999755859375), 'bbox': (360.22607421875, 116.42399597167969, 368.9020690917969, 127.1520004272461), 'c': 'U'}, {'origin': (368.89208984375, 124.559997558
59375), 'bbox': (368.89208984375, 116.42399597167969, 376.9080810546875, 127.1520004272461), 'c': 'B'}, {'origin': (376.8981018066406, 124.55999755859375), 'bbox': (376.8981018066406, 116.42399597167969, 38
3.58209228515625, 127.1520004272461), 'c': 'S'}, {'origin': (383.5721130371094, 124.55999755859375), 'bbox': (383.5721130371094, 116.42399597167969, 391.5881042480469, 127.1520004272461), 'c': 'T'}, {'origi
n': (391.578125, 124.55999755859375), 'bbox': (391.578125, 116.42399597167969, 400.2541198730469, 127.1520004272461), 'c': 'A'}, {'origin': (400.244140625, 124.55999755859375), 'bbox': (400.244140625, 116.4
2399597167969, 408.9201354980469, 127.1520004272461), 'c': 'N'}, {'origin': (408.91015625, 124.55999755859375), 'bbox': (408.91015625, 116.42399597167969, 417.5861511230469, 127.1520004272461), 'c': 'C'}, {
'origin': (417.576171875, 124.55999755859375), 'bbox': (417.576171875, 116.42399597167969, 425.5921630859375, 127.1520004272461), 'c': 'E'}], 'bbox': (186.24000549316406, 116.42399597167969, 425.59216308593
75, 127.1520004272461)}]}]}, {'type': 0, 'bbox': (221.39999389648438, 238.8809051513672, 390.7293701171875, 251.4326629638672), 'lines': [{'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (221.39999389648438, 238.880
9051513672, 390.7293701171875, 251.4326629638672), 'spans': [{'size': 14.039999961853027, 'flags': 20, 'font': 'TimesNewRoman,Bold', 'color': 0, 'chars': [{'origin': (221.39999389648438, 248.4000244140625),
 'bbox': (221.39999389648438, 238.8809051513672, 231.55091857910156, 251.4326629638672), 'c': 'R'}, {'origin': (231.5208740234375, 248.4000244140625), 'bbox': (231.5208740234375, 238.8809051513672, 240.8995
9716796875, 251.4326629638672), 'c': 'E'}, {'origin': (240.8695526123047, 248.4000244140625), 'bbox': (240.8695526123047, 238.8809051513672, 254.13735961914062, 251.4326629638672), 'c': 'M'}, {'origin': (25
4.10731506347656, 248.4000244140625), 'bbox': (254.10731506347656, 238.8809051513672, 264.25823974609375, 251.4326629638672), 'c': 'D'}, {'origin': (264.22821044921875, 248.4000244140625), 'bbox': (264.2282
1044921875, 238.8809051513672, 273.60693359375, 251.4326629638672), 'c': 'E'}, {'origin': (273.576904296875, 248.4000244140625), 'bbox': (273.576904296875, 238.8809051513672, 281.3971862792969, 251.43266296
38672), 'c': 'S'}, {'origin': (281.3671569824219, 248.4000244140625), 'bbox': (281.3671569824219, 238.8809051513672, 286.8427429199219, 251.4326629638672), 'c': 'I'}, {'origin': (286.8127136230469, 248.4000
244140625), 'bbox': (286.8127136230469, 238.8809051513672, 296.963623046875, 251.4326629638672), 'c': 'V'}, {'origin': (296.93359375, 248.4000244140625), 'bbox': (296.93359375, 238.8809051513672, 302.409179
6875, 251.4326629638672), 'c': 'I'}, {'origin': (302.379150390625, 248.4000244140625), 'bbox': (302.379150390625, 238.8809051513672, 312.5300598144531, 251.4326629638672), 'c': 'R'}, {'origin': (312.5000305
175781, 248.4000244140625), 'bbox': (312.5000305175781, 238.8809051513672, 316.0240783691406, 251.4326629638672), 'c': ' '}, {'origin': (315.9940185546875, 248.4000244140625), 'bbox': (315.9940185546875, 23
8.8809051513672, 320.6833801269531, 251.4326629638672), 'c': '('}, {'origin': (320.6533508300781, 248.4000244140625), 'bbox': (320.6533508300781, 238.8809051513672, 331.59051513671875, 251.4326629638672), '
c': 'G'}, {'origin': (331.56048583984375, 248.4000244140625), 'bbox': (331.56048583984375, 238.8809051513672, 339.3807678222656, 251.4326629638672), 'c': 'S'}, {'origin': (339.3599853515625, 248.40002441406
25), 'bbox': (339.3599853515625, 238.8809051513672, 344.0493469238281, 251.4326629638672), 'c': '-'}, {'origin': (343.9200134277344, 248.4000244140625), 'bbox': (343.9200134277344, 238.8809051513672, 350.95
404052734375, 251.4326629638672), 'c': '5'}, {'origin': (350.94000244140625, 248.4000244140625), 'bbox': (350.94000244140625, 238.8809051513672, 357.9740295410156, 251.4326629638672), 'c': '7'}, {'origin':
(357.9599914550781, 248.4000244140625), 'bbox': (357.9599914550781, 238.8809051513672, 364.9940185546875, 251.4326629638672), 'c': '3'}, {'origin': (364.97998046875, 248.4000244140625), 'bbox': (364.9799804
6875, 238.8809051513672, 372.0140075683594, 251.4326629638672), 'c': '4'}, {'origin': (371.9999694824219, 248.4000244140625), 'bbox': (371.9999694824219, 238.8809051513672, 386.05401611328125, 251.432662963
8672), 'c': '™'}, {'origin': (386.0400085449219, 248.4000244140625), 'bbox': (386.0400085449219, 238.8809051513672, 390.7293701171875, 251.4326629638672), 'c': ')'}], 'bbox': (221.39999389648438, 238.880905
1513672, 390.7293701171875, 251.4326629638672)}]}]}, {'type': 0, 'bbox': (261.1199951171875, 399.44219970703125, 350.9766845703125, 412.232666015625), 'lines': [{'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (261.
1199951171875, 399.44219970703125, 350.9766845703125, 412.232666015625), 'spans': [{'size': 14.039999961853027, 'flags': 4, 'font': 'TimesNewRoman', 'color': 0, 'chars': [{'origin': (261.1199951171875, 409.
20001220703125), 'bbox': (261.1199951171875, 399.44219970703125, 271.2709045410156, 412.232666015625), 'c': 'G'}, {'origin': (271.2408752441406, 409.20001220703125), 'bbox': (271.2408752441406, 399.44219970
703125, 275.1580505371094, 412.232666015625), 'c': 'i'}, {'origin': (275.12799072265625, 409.20001220703125), 'bbox': (275.12799072265625, 399.44219970703125, 279.045166015625, 412.232666015625), 'c': 'l'},
 {'origin': (279.0151062011719, 409.20001220703125), 'bbox': (279.0151062011719, 399.44219970703125, 285.2629089355469, 412.232666015625), 'c': 'e'}, {'origin': (285.2328796386719, 409.20001220703125), 'bbo
x': (285.2328796386719, 399.44219970703125, 291.4806823730469, 412.232666015625), 'c': 'a'}, {'origin': (291.4506530761719, 409.20001220703125), 'bbox': (291.4506530761719, 399.44219970703125, 298.484680175
78125, 412.232666015625), 'c': 'd'}, {'origin': (298.45465087890625, 409.20001220703125), 'bbox': (298.45465087890625, 399.44219970703125, 301.97869873046875, 412.232666015625), 'c': ' '}, {'origin': (301.9
486389160156, 409.20001220703125), 'bbox': (301.9486389160156, 399.44219970703125, 309.7689208984375, 412.232666015625), 'c': 'S'}, {'origin': (309.7388916015625, 409.20001220703125), 'bbox': (309.738891601
5625, 399.44219970703125, 315.9866943359375, 412.232666015625), 'c': 'c'}, {'origin': (315.9566650390625, 409.20001220703125), 'bbox': (315.9566650390625, 399.44219970703125, 319.87384033203125, 412.2326660
15625), 'c': 'i'}, {'origin': (319.8437805175781, 409.20001220703125), 'bbox': (319.8437805175781, 399.44219970703125, 326.0915832519531, 412.232666015625), 'c': 'e'}, {'origin': (326.0615539550781, 409.200
01220703125), 'bbox': (326.0615539550781, 399.44219970703125, 333.0955810546875, 412.232666015625), 'c': 'n'}, {'origin': (333.0655517578125, 409.20001220703125), 'bbox': (333.0655517578125, 399.44219970703
125, 339.3133544921875, 412.232666015625), 'c': 'c'}, {'origin': (339.2833251953125, 409.20001220703125), 'bbox': (339.2833251953125, 399.44219970703125, 345.5311279296875, 412.232666015625), 'c': 'e'}, {'o
rigin': (345.5010986328125, 409.20001220703125), 'bbox': (345.5010986328125, 399.44219970703125, 350.9766845703125, 412.232666015625), 'c': 's'}], 'bbox': (261.1199951171875, 399.44219970703125, 350.9766845
703125, 412.232666015625)}]}]}, {'type': 0, 'bbox': (271.32000732421875, 447.7440185546875, 340.68609619140625, 458.4720153808594), 'lines': [{'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (271.32000732421875, 447
.7440185546875, 340.68609619140625, 458.4720153808594), 'spans': [{'size': 12.0, 'flags': 20, 'font': 'TimesNewRoman,Bold', 'color': 0, 'chars': [{'origin': (271.32000732421875, 455.8800048828125), 'bbox':
(271.32000732421875, 447.7440185546875, 277.3320007324219, 458.4720153808594), 'c': '1'}, {'origin': (277.32000732421875, 455.8800048828125), 'bbox': (277.32000732421875, 447.7440185546875, 283.332000732421
9, 458.4720153808594), 'c': '2'}, {'origin': (283.3320007324219, 455.8800048828125), 'bbox': (283.3320007324219, 447.7440185546875, 286.32000732421875, 458.4720153808594), 'c': ' '}, {'origin': (286.3200073
2421875, 455.8800048828125), 'bbox': (286.32000732421875, 447.7440185546875, 294.9960021972656, 458.4720153808594), 'c': 'A'}, {'origin': (294.98602294921875, 455.8800048828125), 'bbox': (294.98602294921875
, 447.7440185546875, 301.6700134277344, 458.4720153808594), 'c': 'p'}, {'origin': (301.6600341796875, 455.8800048828125), 'bbox': (301.6600341796875, 447.7440185546875, 307.0000305175781, 458.4720153808594)
, 'c': 'r'}, {'origin': (306.9900207519531, 455.8800048828125), 'bbox': (306.9900207519531, 447.7440185546875, 310.3380126953125, 458.4720153808594), 'c': 'i'}, {'origin': (310.3280334472656, 455.8800048828
125), 'bbox': (310.3280334472656, 447.7440185546875, 313.676025390625, 458.4720153808594), 'c': 'l'}, {'origin': (313.6660461425781, 455.8800048828125), 'bbox': (313.6660461425781, 447.7440185546875, 316.67
803955078125, 458.4720153808594), 'c': ' '}, {'origin': (316.6680603027344, 455.8800048828125), 'bbox': (316.6680603027344, 447.7440185546875, 322.6800537109375, 458.4720153808594), 'c': '2'}, {'origin': (3
22.6700744628906, 455.8800048828125), 'bbox': (322.6700744628906, 447.7440185546875, 328.68206787109375, 458.4720153808594), 'c': '0'}, {'origin': (328.6720886230469, 455.8800048828125), 'bbox': (328.672088
6230469, 447.7440185546875, 334.68408203125, 458.4720153808594), 'c': '2'}, {'origin': (334.6741027832031, 455.8800048828125), 'bbox': (334.6741027832031, 447.7440185546875, 340.68609619140625, 458.47201538
08594), 'c': '0'}], 'bbox': (271.32000732421875, 447.7440185546875, 340.68609619140625, 458.4720153808594)}]}]}, {'type': 0, 'bbox': (153.1199951171875, 560.6640014648438, 458.90081787109375, 571.3919677734
375), 'lines': [{'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (153.1199951171875, 560.6640014648438, 458.90081787109375, 571.3919677734375), 'spans': [{'size': 12.0, 'flags': 20, 'font': 'TimesNewRoman,Bold', 'co
lor': 0, 'chars': [{'origin': (153.1199951171875, 568.7999877929688), 'bbox': (153.1199951171875, 560.6640014648438, 161.79598999023438, 571.3919677734375), 'c': 'C'}, {'origin': (161.77899169921875, 568.79
99877929688), 'bbox': (161.77899169921875, 560.6640014648438, 171.12698364257812, 571.3919677734375), 'c': 'O'}, {'origin': (171.1099853515625, 568.7999877929688), 'bbox': (171.1099853515625, 560.6640014648
438, 179.78598022460938, 571.3919677734375), 'c': 'N'}, {'origin': (179.76898193359375, 568.7999877929688), 'bbox': (179.76898193359375, 560.6640014648438, 187.11297607421875, 571.3919677734375), 'c': 'F'},
 {'origin': (187.09597778320312, 568.7999877929688), 'bbox': (187.09597778320312, 560.6640014648438, 191.77597045898438, 571.3919677734375), 'c': 'I'}, {'origin': (191.75897216796875, 568.7999877929688), 'b
box': (191.75897216796875, 560.6640014648438, 200.43496704101562, 571.3919677734375), 'c': 'D'}, {'origin': (200.41796875, 568.7999877929688), 'bbox': (200.41796875, 560.6640014648438, 208.43397521972656, 5
71.3919677734375), 'c': 'E'}, {'origin': (208.41696166992188, 568.7999877929688), 'bbox': (208.41696166992188, 560.6640014648438, 217.09295654296875, 571.3919677734375), 'c': 'N'}, {'origin': (217.075958251
95312, 568.7999877929688), 'bbox': (217.07595825195312, 560.6640014648438, 225.0919647216797, 571.3919677734375), 'c': 'T'}, {'origin': (225.074951171875, 568.7999877929688), 'bbox': (225.074951171875, 560.
6640014648438, 229.75494384765625, 571.3919677734375), 'c': 'I'}, {'origin': (229.73794555664062, 568.7999877929688), 'bbox': (229.73794555664062, 560.6640014648438, 238.4139404296875, 571.3919677734375), '
c': 'A'}, {'origin': (238.39694213867188, 568.7999877929688), 'bbox': (238.39694213867188, 560.6640014648438, 246.41294860839844, 571.3919677734375), 'c': 'L'}, {'origin': (246.39593505859375, 568.799987792
9688), 'bbox': (246.39593505859375, 560.6640014648438, 249.40792846679688, 571.3919677734375), 'c': ' '}, {'origin': (249.39093017578125, 568.7999877929688), 'bbox': (249.39093017578125, 560.6640014648438,
258.0669250488281, 571.3919677734375), 'c': 'A'}, {'origin': (258.0499267578125, 568.7999877929688), 'bbox': (258.0499267578125, 560.6640014648438, 266.7259216308594, 571.3919677734375), 'c': 'N'}, {'origin
': (266.70892333984375, 568.7999877929688), 'bbox': (266.70892333984375, 560.6640014648438, 275.3849182128906, 571.3919677734375), 'c': 'D'}, {'origin': (275.367919921875, 568.7999877929688), 'bbox': (275.3
67919921875, 560.6640014648438, 278.3799133300781, 571.3919677734375), 'c': ' '}, {'origin': (278.3629150390625, 568.7999877929688), 'bbox': (278.3629150390625, 560.6640014648438, 285.7069091796875, 571.391
9677734375), 'c': 'P'}, {'origin': (285.6899108886719, 568.7999877929688), 'bbox': (285.6899108886719, 560.6640014648438, 294.36590576171875, 571.3919677734375), 'c': 'R'}, {'origin': (294.3489074707031, 56
8.7999877929688), 'bbox': (294.3489074707031, 560.6640014648438, 303.6968994140625, 571.3919677734375), 'c': 'O'}, {'origin': (303.8399963378906, 568.7999877929688), 'bbox': (303.8399963378906, 560.66400146
48438, 311.1839904785156, 571.3919677734375), 'c': 'P'}, {'origin': (311.17498779296875, 568.7999877929688), 'bbox': (311.17498779296875, 560.6640014648438, 319.8509826660156, 571.3919677734375), 'c': 'R'},
 {'origin': (319.84197998046875, 568.7999877929688), 'bbox': (319.84197998046875, 560.6640014648438, 324.52197265625, 571.3919677734375), 'c': 'I'}, {'origin': (324.5129699707031, 568.7999877929688), 'bbox'
: (324.5129699707031, 560.6640014648438, 332.5289611816406, 571.3919677734375), 'c': 'E'}, {'origin': (332.51995849609375, 568.7999877929688), 'bbox': (332.51995849609375, 560.6640014648438, 340.53594970703
125, 571.3919677734375), 'c': 'T'}, {'origin': (340.5269470214844, 568.7999877929688), 'bbox': (340.5269470214844, 560.6640014648438, 349.20294189453125, 571.3919677734375), 'c': 'A'}, {'origin': (349.19393
92089844, 568.7999877929688), 'bbox': (349.1939392089844, 560.6640014648438, 357.86993408203125, 571.3919677734375), 'c': 'R'}, {'origin': (357.8609313964844, 568.7999877929688), 'bbox': (357.8609313964844,
 560.6640014648438, 366.53692626953125, 571.3919677734375), 'c': 'Y'}, {'origin': (366.5279235839844, 568.7999877929688), 'bbox': (366.5279235839844, 560.6640014648438, 369.5399169921875, 571.3919677734375)
, 'c': ' '}, {'origin': (369.5309143066406, 568.7999877929688), 'bbox': (369.5309143066406, 560.6640014648438, 374.2109069824219, 571.3919677734375), 'c': 'I'}, {'origin': (374.201904296875, 568.79998779296
88), 'bbox': (374.201904296875, 560.6640014648438, 382.8778991699219, 571.3919677734375), 'c': 'N'}, {'origin': (382.868896484375, 568.7999877929688), 'bbox': (382.868896484375, 560.6640014648438, 390.21289
0625, 571.3919677734375), 'c': 'F'}, {'origin': (390.2038879394531, 568.7999877929688), 'bbox': (390.2038879394531, 560.6640014648438, 399.5518798828125, 571.3919677734375), 'c': 'O'}, {'origin': (399.54287
71972656, 568.7999877929688), 'bbox': (399.5428771972656, 560.6640014648438, 408.2188720703125, 571.3919677734375), 'c': 'R'}, {'origin': (408.2098693847656, 568.7999877929688), 'bbox': (408.2098693847656,
560.6640014648438, 419.54986572265625, 571.3919677734375), 'c': 'M'}, {'origin': (419.5408630371094, 568.7999877929688), 'bbox': (419.5408630371094, 560.6640014648438, 428.21685791015625, 571.3919677734375)
, 'c': 'A'}, {'origin': (428.2078552246094, 568.7999877929688), 'bbox': (428.2078552246094, 560.6640014648438, 436.2238464355469, 571.3919677734375), 'c': 'T'}, {'origin': (436.21484375, 568.7999877929688),
 'bbox': (436.21484375, 560.6640014648438, 440.89483642578125, 571.3919677734375), 'c': 'I'}, {'origin': (440.8858337402344, 568.7999877929688), 'bbox': (440.8858337402344, 560.6640014648438, 450.2338256835
9375, 571.3919677734375), 'c': 'O'}, {'origin': (450.2248229980469, 568.7999877929688), 'bbox': (450.2248229980469, 560.6640014648438, 458.90081787109375, 571.3919677734375), 'c': 'N'}], 'bbox': (153.119995
1171875, 560.6640014648438, 458.90081787109375, 571.3919677734375)}]}]}]}

Here is the output

**Comment by manish59** [comment]
its exactly missing font color

**Comment by JorjMcKie** [comment]
But you have `` '..., 'color': 0,.. ``, so what is missing?
BTW: a font itself has no color, only the text itself has one. In this case it is 0 = black.

**Comment by JorjMcKie** [comment]
The color in dictionaries ``getText("dict")`` and ``getText("rawdict")`` is coded on the ``span`` level. In fact, creation of a new span hapens if any of the following properties changes between two adjacent characters: font, fontsize, color, flags. So all characters within a span have those same properties.

**Comment by JorjMcKie** [comment]
Are your questions answered?
