### ISSUE TITLE
Question / Comment: how to create the type Action

### ISSUE THREAD

**Issue by GianpaoloPedrazza** [pymupdf/PyMuPDF#490]
Hi,
I read the documentation but I have not found anything related how to create PDF Action. Is this supported or not? If not, will this be implemented?

**Comment by JorjMcKie** [comment]
Having internet connection issues, so answering via e-mail.

There is no direct support for PDF actions yet. Actions are implicitely created where necessary (annotations, links, widgets). For widgets I recently added the option to create JavaScript actions.

There are no plans to extend this at the moment.

**Comment by GianpaoloPedrazza** [comment]
Thank you for the quickly answer. Any chances to execute some javascript code as open action or to run an embedded file? I do not plan anything malicious with that, I just want to check if some other application would recognize the pdf as potentially dangerous.

**Comment by JorjMcKie** [comment]
This sounds more like a one time thing then.
Using PyMuPDF, there are certainly ways to add respective objects to a PDF by using its low-level features.
This would work along these lines:
1. define the "source" of a JavaScript action and insert this as an object to the PDF
2. manipulate the string of the PDF's root object (the catalog) to include an invocation of the action via the "OpenAction" entry

A JavaScript action's source in PDF object terminology looks like this

```text
<<
/S JavaScript
/JS(... the JavaScript source ...)
>>
```
Add this string to the PDF via

```python
xref = doc._getNewXref()
doc._updateObject(xref, string)
```
Then get the current source of the catalog, insert or replace line with the OpenAction.

```python
doc=fitz.open("PyMuPDF.pdf")
root_xref=doc._getPDFroot()
print(doc.xrefObject(root_xref))
<<
  /Type /Catalog
  /Pages 2449 0 R
  /Names 2706 0 R
  /PageMode /UseOutlines
  /PageLabels <<
    /Nums [ 0 <<
          /S /D
        >> 2 <<
          /S /r
        >> 4 <<
          /S /D
        >> ]
  >>
  /OpenAction 1 0 R  % replace "1" with the xref of the action object
  /Outlines 2709 0 R
>>
```
The do a ``doc._updateObject(root_xref, string)`` with modified catalog string.

**Comment by JorjMcKie** [comment]
Did this help you? Require anything else?

**Comment by GianpaoloPedrazza** [comment]
It helped me a lot, thank you very much.
