### ISSUE TITLE
Question: How to get graphic elements(not chars line or big images, but lines or rects in tables etc) in a PDF page?

### ISSUE THREAD

**Issue by gladuo** [pymupdf/PyMuPDF#491]
Question: How to get graphic elements(not chars line or big images, but lines or rects in tables etc) in a PDF page? I find many methods to add graphic elements like lines, rects etc. But I haven't found a method to do such things, please tell me I miss something important.

**Comment by gladuo** [comment]
Example like https://arxiv.org/pdf/1804.02767.pdf, 
![image](https://user-images.githubusercontent.com/5893628/79335866-5304e980-7f55-11ea-9a8a-5b68b726cd21.png)，how to get the rect of the orange line

**Comment by JorjMcKie** [comment]
Having problems with my internet connection – so mailing this.

This is possible but difficult and requires you to interpret the commands in PDF‘s mini-language. Look in chapter “Appendix A Operator Summary” (page 985). Here is a simple (!) example for how this works:

5 5 m  % goto point (5,5)
145 5 l  % draw line to (145,5)
70 126.244 l  % from there, draw line to (70, 126…)
h  % close subpath
0 0 1 rg f  % set blue RGB color and fill path, etc.
75 5 m
37.5 65.6218 l
107.5 65.6218 l
h
1 1 0 rg f
40 5 m
21.25 35.3109 l
56.25 35.3109 l
h
1 1 0 rg f
22.5 5 m
13.125 20.1554 l

Every single little graphical element (line markers like circle, rhombus, etc.) is built with these atomic instructions. And there is no guarantee that e.g. the four sides of a rhombus are defined in one contiguous set of instructions: they might be totally scattered across the command text.

**Comment by gladuo** [comment]
@JorjMcKie Thank you for your quick response.
I understand your examples that every graphical element is just painted on the canvas, what I need at least is some methods to sure "there is something graphical there" then I made a screenshot to extract the image. What should I start to do that, is it too hard?

**Comment by JorjMcKie** [comment]
Well it definitely is hard as I wrote.
Extract the command buffer for your example and judge for yourself. If you ask me: I would not do it, but would instead to find other ways to access the original data which resulted in those graphics.

Here is how to extract the commands (they reside in some ``/Contents`` object). I show here only the simple case, where the graphics reside in some of the page's `/Contents`. Things may be much more complicated than that.

```python
xref_list = page.getContents()  # delivers a list of xrefs of page command buffers
# assuming we only have one xref:
xref = xref_list[0]
cont = doc.xrefStream(xref).decode()  # get it as a string
# it probably is large, so best output it to a text file for easier study
contout = open("contents.txt", "w")
contout.write(cont)
contout.close()
```

**Comment by JorjMcKie** [comment]
I presume your question has been addressed.
