### ISSUE TITLE
Question / Comment: Getting png images without colors

### ISSUE THREAD

**Issue by moka1309** [pymupdf/PyMuPDF#493]
Hi, 
I am extracting images from pdf in png format. But as a result I am getting colorless like no RGB colors on those images. I tried my code with other pdf where I am getting proper images with colors.
Code I am using:
```
import fitz
import csv


def extract_images(file_name):
    doc = fitz.open(file_name)
    csv_file_name = file_name[:-4] + "-images-with-coordinates.csv"
    with open(csv_file_name, 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["Image name", " Block_Coordinates"])
        for page in doc:
            image_blocks = [b for b in page.getText("dict")["blocks"] if b["type"] == 1]
            images = page.getImageList()
            for item in images:
                xref = item[0]  # xref number
                pix = fitz.Pixmap(doc, xref)  # make pixmap from image
                img = doc.extractImage(xref)
                bbox = ()
                save_image_name = "page-%s-%s.png" % (page.number, xref)
                path = f"./images2/{save_image_name}"
                if pix.n - pix.alpha < 4:  # can be saved as PNG
                    pix.writePNG(path)
                else:  # CMYK: must convert first
                    pix0 = fitz.Pixmap(fitz.csRGB, pix)
                    pix0.writePNG(path)
                    pix0 = None  # free Pixmap resources
                pix = None
                for b in image_blocks:
                    if img["image"] == b["image"]:
                        bbox = b["bbox"]
                        break
                writer.writerow([save_image_name, bbox])
    return


if __name__ == '__main__':
    filename = "./test.pdf"
    extract_images(filename)
```
`
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/4501339/PP-BOS-USA-0614.BOSULIF.Core.Visual.Aid.November.2019.Update_Post-MLR.pdf)

**Comment by JorjMcKie** [comment]
If this works for some PDF and not for others, I need an example

**Comment by moka1309** [comment]
For pdf I attached in question I am getting images as in this file [images.zip](https://github.com/pymupdf/PyMuPDF/files/4502691/images.zip).
For this [english-short-stories-free.pdf](https://github.com/pymupdf/PyMuPDF/files/4502692/english-short-stories-free.pdf) pdf I am getting images which I placed in this [images2.zip](https://github.com/pymupdf/PyMuPDF/files/4502701/images2.zip) file.
In images2 also I am getting some images as colorless.

**Comment by JorjMcKie** [comment]
I have looked at it. Indeed: the example xref 227 on page 27 of  english-short-stories-free.pdf is extracted (almost) in gray levels. Interestingly, this is **independent** from whether you create a PNG via `Pixmap(doc, 227)` or **directly** do a `doc.extractImage(227)`.
In the latter case it turns out that this image is a JPEG.

Because of the direct, unmodified binary data extraction method used by `doc.extractImage(227)`, it is clear that the color for the image must come from an external source. And indeed: the page definition contains a /Colorspace object which in turn contains binary data which obviously somehow set the colors.

So at the moment it looks like, that I cannot support this constellation ... 🤔, but I will check if there are improvement options for the pixmap path.

**Comment by JorjMcKie** [comment]
Ha, found the problem!
I have been taking an inappropriate path when doing Pixmap(doc, xref). Just corrected this and it works for the example.
Will be fixed with the next version.
Thanks for bringing this up!

**Comment by moka1309** [comment]
Hey, thanks for checking that. But, is there a way to get those images into RGB images in this version.

**Comment by JorjMcKie** [comment]
No, there is not unfortunately.
But I could send you a pre-version wheel if you tell me your configuration: OS, Python version. If Windows, then also the bitness.

**Comment by moka1309** [comment]
Okay, thanks!
Here are my configs:
OS:: Ubuntu 18.04 64 bit
Python:: 3.6 64bit

**Comment by JorjMcKie** [comment]
Great. Wheel generation is already finished, you can download your version from here: https://github.com/pymupdf/PyMuPDF-wheels/tree/linux.
Please let me know if it works.

**Comment by moka1309** [comment]
Perfect! Now its working fine. Thanks a lot! :100: :+1:

**Comment by JorjMcKie** [comment]
Thanks for the feedback! 😊

**Comment by JorjMcKie** [comment]
The new version is officially out now.
