### ISSUE TITLE
Question / Cannot add text box using Page.addFreetextAnnot()

### ISSUE THREAD

**Issue by yongqixxll** [pymupdf/PyMuPDF#494]
Hi, 

It seems if the PDF version lower than PDF-1.6 (e.g. PDF-1.5), the method Page.addFreetextAnnot() will not work. (the code still can run but nothing added). 

Is it expected? Is there a way to add Free text in PDF-1.5?

**Comment by JorjMcKie** [comment]
This script creates a range of annotations on a page in a (new) PDF-1.4 file:
[new-annots.zip](https://github.com/pymupdf/PyMuPDF/files/4532900/new-annots.zip)
So I assume something else is going wrong.

**Comment by yongqixxll** [comment]
Hello,

Thanks for the prompt reply. Unfortunately I am unable to share the document. I think we can close it for now. Thanks again.

**Comment by JorjMcKie** [comment]
Ok. Please do not hesitate to re-open the issue when you have data that you can share.
