### ISSUE TITLE
Question / Comment: Compare two pdf's text using otherthan block wise concept?

### ISSUE THREAD

**Issue by moka1309** [pymupdf/PyMuPDF#495]
Hi again,
I am comparing two pdfs with same content but have changed text in some blocks. That changes are belongs to entire block or some words. I entire block is changed I marking entire block or if some words changed then only those in first pdf. For this I approached block-wise concept. But here problem is what if post/second pdf blocks coordinates missing with pre/first pdf. I also approached natural reading concept(top-bottom, left-right). Here I am facing a problem like below example

```
ALT increased 4.5%   (first pdf line)
------------------------------------------------------------------------------
ALT increased 4.5%   (second pdf line)


Grade 0.7% 0.4% 2.6% 1.1%
------------------------------------------------------------------------------
0.7% 0.4% 2.6% 1.1%


≥3
------------------------------------------------------------------------------
Grade


AST increased 2.6%
------------------------------------------------------------------------------
≥3
```

Here also there is a change in coordinates in second time so Grade is coming in third line.

Is there any different approach or can I get proper solution using these two methods.

**Comment by JorjMcKie** [comment]
The different text extraction variants (except the "naive" getText("text")):
1. "blocks": as you have been using it
2. "words": a list of words, each with its bbox. A *word* here means contiguous non-space characters.
3. "dict": spans of text (characters having the same font properties, size, color, etc.) also with bbox, organized in lines, which belog to the same block.
4. "rawdict": same as dict, but going down to each single character.

I am not sure I understod you completely. But you could for example also take the lists of words of the two PDFs and then use a module like *difflib* to compare these two lists. First sort the two lists by their position. Then include the position info in the comparison (or not) as required.

**Comment by moka1309** [comment]
Hi I thanks for response. My approach is almost same as your example. But issue is what if positions are mismatched in duplicate pdf I mean for example in duplicate pdf text starts after 2, 3 lines. 
```
TEXT 1                                    TEXT 2
--------------------------------------- ---------------------------------------
This is example text. Line number 1.                   

                                         This is example text. Line number 3.
```

**Comment by JorjMcKie** [comment]
Well, I would say, it is up to you if you want to ignore this and still regard them equal or not.

Once you have sorted the text by position you can then decide if the position coordinates should be part of the comparison or or if equality of text itself should be all that counts.

**Comment by moka1309** [comment]
Yeah for simple and straight text like above example I am not bothering. I have [file1](https://github.com/pymupdf/PyMuPDF/files/4541797/DAURISMO.Patient.Brochure_Post-MLR.copy.pdf), [file2](https://github.com/pymupdf/PyMuPDF/files/4541798/DAURISMO.Patient.Brochure_RC.copy_modified.pdf) files, reading and markings are becoming difficult. Can you help me with this type of complexity. How can I approach for comparing.

**Comment by JorjMcKie** [comment]
What type ofresult do you have to produce? Obviously it is not a simple statement like "equal or "not equal"?
What type of report should be the output?
Your second file e.g. explanatory annotations, which are not present on file 1.
Then there are text differences and also position deviations - not to talk about layout changes overall.

As far as only text is concerned you can produce a list of lines, sorted first by vertical then by horizontal coordinate. Take the `getText("dict")` as a starting point for this.
Then you can run two comparisons with these two sorted lists of lines:
1. compare the texts only and report any differences.
2. compare the line bboxes. There may be bbox differences (i.e. layout changes) for lines with equal text, which may be worth reporting.

For the non-text content, you can determine bboxes of `images` and report any deviations.
And of course it could be interesting whether two pages differ with regard to number and position of any annotations.

**Comment by moka1309** [comment]
@JorjMcKie thanks for detailed info. As per my question I am marking pdf 1 block if that entire block text is changed in pdf 2. If only some words changed I am marking that words only. As you mentioned here 

> Then you can run two comparisons with these two sorted lists of lines:
> 
>     1. Using difflib, compare the texts only and report any differences.
>     2. compare the line bboxes. There may be bbox differences (i.e. layout changes) for lines with equal text, which may be worth reporting.
In point 2 if that layout changed in pdf 2 but if text is same, I need to compare those lines.
But getting problems like this when we get bbox differences.
```
ALT increased 4.5%   (first pdf line)
------------------------------------------------------------------------------
ALT increased 4.5%   (second pdf line)

here from both pdfs lines are same

Grade 0.7% 0.4% 2.6% 1.1%
------------------------------------------------------------------------------
0.7% 0.4% 2.6% 1.1%

Here in pdf 2 Grade bbox changed so it went to next line. but when we read pdf both are same. How can I handle this situation. I cant mark Grade in pdf 1 because it is appearing normally when we read 2nd pdf.

≥3
------------------------------------------------------------------------------
Grade


AST increased 2.6%
------------------------------------------------------------------------------
≥3

```

**Comment by JorjMcKie** [comment]
The "blocks" output of `getText` is probably to coarse for your purpose:
What belongs to the same "line" when collecting the data for a block is subject to a number of criteria which not always mean really a new line according to normal understanding: just a few pixels up or down may lead to a new line, or entries in two different columns of a table.
Also there may be differences introduced by the way how the PDF was created: Text may have been appended at a later time. It can still appear at **_any_** position of the page, but will be contained in `getText("text")` and `getText("blocks")` at the very end and in its own block.

What you probably will have to do is taking the "dict" or "words" output and then "re-synthesize" each single line after sorting its components by position - starting from "spans" in the "dict" case.

 This will also offer the chance to ignore position differences which are too subtle (compared to the font size).

Let me emphasize again: `getText("text")` and `getText("blocks")` are both "naive" extraction methods in the sense that they assume a straightforward making of the PDF. They are not made to detect the trickier situations - they are made to be **_fast_**.

I have seen cases where each single word had to be re-synthesized from its letters. **_Every_** extraction method sort of reported the anagram `J`, `r`, `M`, `K`, `e`, `o`, `j`, `c`,  `i` what should have been `Jorj McKie`. Only going down to each single character (using "rawdict"), sorting and merging revealed readable stuff.
This is by the way more or less what each PDF viewer is doing when it produces the visible page.

**Comment by moka1309** [comment]
Hi @JorjMcKie sorry for late reply.
At these bbox 
(54.56669998168945, 620.5899047851562, 150.9648895263672, 636.786865234375) 
when I used "dict", I got
`[M81.0 – `

when I used "blocks" I got
```
[M81.0 – Age-related osteoporosis  
without current pathological fracture]
```
In dict I even didn't get entire line also.
 
I am using [this](https://github.com/pymupdf/PyMuPDF/files/4557090/Amgen.Assist.Prolia.Summary.of.Benefits.SOB._BL.pdf) pdf

**Comment by JorjMcKie** [comment]
> In dict I even didn't get entire line also.

Oh, you did! If you read the doc about the "dict" structure you'll see that a line consists of spans. Doing

```python
>>> blocks = [b for b in page.getText("dict")["blocks"] if b["type"]==0] # text blocks only
>>> for b in blocks:
	for line in b["lines"]:
		for span in line["spans"]:
			print(span["text"])
```

delivers all info - only on a more detailed level ... as I suggested to use for your type of analysis. You just ignored one of the line spans:
```text
...
Verified for Diagnosis
[M81.0 – 
Age-related osteoporosis  
without current pathological fracture]
Policy Level: 
...
```

**Comment by moka1309** [comment]
Haa! thanks alot @JorjMcKie I written wrong loop for getting spans. My mistake. Got It and closing this thread. Thanks again! :+1: :100:
