### ISSUE TITLE
Detect background changes which are not images

### ISSUE THREAD

**Issue by maffei2443** [pymupdf/PyMuPDF#498]
**Is your feature request related to a problem? Please describe.**

The problem is to detect that the text "PODER LEGISLATIVO" is contained in a sort of "box", maybe a "backgroundbox", and get the bounding boxes of these box (along or not with its color).   

![black-back](https://user-images.githubusercontent.com/19755960/80814954-2d0d5500-8ba3-11ea-933a-c7609c94a202.png)

Since it is not even noticed by _pymupdf_ extraction methods, it becomes very hard to handle this. For example the HTML generated from **fitz.TextPage.extractHTML** w.r.t the page containing the figure above does not show the black background:

![white-white](https://user-images.githubusercontent.com/19755960/80816541-15839b80-8ba6-11ea-8a93-3000bfe00772.png)

The text however is present, since it can be selected:
![white-blue](https://user-images.githubusercontent.com/19755960/80816650-42d04980-8ba6-11ea-93ac-c7879cade4d5.png)

**Describe the solution you'd like**
A way to extract, or at least detect, the bounding boxes of those problematic PDF regions.
I suggest something like **fitz.TextPage.extractBACKGROUNDREGIONS**.
I've also thought that an alternative would be extracting them as images through
the already existent **fitz.Page.getImageList**
[novo-2020.pdf](https://github.com/pymupdf/PyMuPDF/files/4564854/novo-2020.pdf)

The full PDF whose that image was extracted from is 
[that](https://github.com/pymupdf/PyMuPDF/files/4564906/novo-2020.pdf).

**Comment by JorjMcKie** [comment]
A good question and an understandable motivation.

Howeverm, there is no realistic way to implement this. Before I give you some reasons, let me mention that you can at least assume that the white text "PODER LEGISLATIVO" most probably is placed on some dark background ... And the text color **can** be determined via text extractions.

1. For non-PDF document types there simply exists no information to determine this type of situation.
2. For PDF docs, there exist about a handful of ways to create something looking like your example. I haven't looked at your file yet, but propably a black rectangle was drawn before the text was placed over it. You would have to write a program which interprets the PDF mini-language making such paintings. Every PDF viewer (Acrobat Reader etc.) does this type of thing. This is completely different from an embedded image (the only thing detectable via getImageList and friends).
    - if the text is inside a FreeText annotation, there certainly is a way to check the annot's background color, but that's a corner case.

If you want to get impression about that PDF mini-language, see chapter "Appendix A - Operator Summary" starting page 985 of the PDF manual.

**Comment by maffei2443** [comment]
Thanks for the preply.
With respect to the **text** color yes this can be determined and I 've done this several times. 
Thanks for the recommendation about docs and for explanations why is there is no realistic way to implement the requested feature.
Could you please provide a link to the PDF documentation version?  I use to access the HTML version but having a PDF would certainly be better.

**Comment by JorjMcKie** [comment]
This chapter in PyMuPDF refers to two Adobe book for [download](https://pymupdf.readthedocs.io/en/latest/app4/#adobe-pdf-references).
