### ISSUE TITLE
convertToPDF() has memory leak

### ISSUE THREAD

**Issue by kavin-1098** [pymupdf/PyMuPDF#500]
_**Please provide all mandatory information!**_

for img in os.listdir("C:\pil"):
     imgdoc=fitz.open(os.path.join("C:\pil",img))
     imgdoc.convertToPDF()
     imgdoc.close()

I executed the above line of code my RAM bumped up to 2gb to 3 gb and did not come down at all

## Describe the bug (mandatory)
Memory leak in convertToPDF()

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

execute the following lines of code with images in any folder:

I executed with 420 images -> 1 GB ram occupied

for img in os.listdir("C:\pil"):
     imgdoc=fitz.open(os.path.join("C:\pil",img))
     imgdoc.convertToPDF()
     imgdoc.close()

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

Memory usage should come down

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

Windows 10 4 gb RAM

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
You did not provide all mandatory information: output of ``print(fitz.__doc__)`` is missing.
But never mind: found and removed the problem.
Thanks for reporting this anyway.

**Comment by kavin-1098** [comment]
what additional information you need .I can provide you right away

**Comment by kavin-1098** [comment]
mupdf: malloc of 8415000 bytes failed

I am getting the above error

**Comment by kavin-1098** [comment]
In docker gunicorn threads are getting killed because of this

**Comment by JorjMcKie** [comment]
It's ok, as I wrote: your issue content was indeed very valid and I already fixed it.
Just in the general case, I need the system configuration, which is why I configured the ``__doc__`` so that it contains the relevant info.
It was easy enough this time to detect that I forgot to free the temporary image page and document objects in the C level.

**Comment by kavin-1098** [comment]
Thanks for your quick response . When are you planning for next release of pymupdf .Does that release include this fix as well

**Comment by JorjMcKie** [comment]
How urgent is this for you?
From your example code I deduct you are on some Windows.
If you care to send me the ``fitz.__doc__`` info, I can send you a Windows wheel as a hotfix using this channel.

**Comment by JorjMcKie** [comment]
> When are you planning for next release of pymupdf .Does that release include this fix as well

 Sure. The change was a 5 minute thing.

**Comment by kavin-1098** [comment]
I am not supposed to share that document .But it is a tiff image with 420 pages in it

**Comment by JorjMcKie** [comment]
> I am not supposed to share that document .But it is a tiff image with 420 pages in it

No! I meant your output ``print(fitz.__doc__)``.

**Comment by JorjMcKie** [comment]
Just to pick the right wheel for you.

**Comment by kavin-1098** [comment]
PyMuPDF 1.16.7: Python bindings for the MuPDF 1.16.0 library.
Version date: 2019-11-07 10:22:00.
Built for Python 3.7 on win32 (32-bit).

**Comment by kavin-1098** [comment]
But the python service is hosted in Google kubernetes engine were the gunicorn worker threads are getting killed when this convertToPDF() is called .It would be good if you provide any hotfix for this also. Please let me know if anything is to changed in fitz.py to achieve this

**Comment by kavin-1098** [comment]
def convertToPDF(self, from_page=0, to_page=-1, rotate=0):
        r"""Convert document to PDF selecting page range and optional rotation. Output bytes object."""
        if self.isClosed or self.isEncrypted:
            raise ValueError("document closed or encrypted")

        return _fitz.Document_convertToPDF(self, from_page, to_page, rotate)

**Comment by JorjMcKie** [comment]
ok, thanks - that is what I needed!
If you are interested, I can prepare and send a wheel with this fix.
Otherwise you will have to wait for a few days until I am confident enough to publish the newest version 1.17.0. This will for sure take several more days - up to a week or so.

**Comment by kavin-1098** [comment]
yes please , you can share the windows wheel

**Comment by JorjMcKie** [comment]
> Please let me know if anything is to changed in fitz.py to achieve this

No this is an issue in a C component ``_fitz.Document_convertToPD``.
The issue will be gone after re-installing that new wheel.

**Comment by kavin-1098** [comment]
Got it

**Comment by JorjMcKie** [comment]
[PyMuPDF-1.16.18-cp37-cp37m-win32.zip](https://github.com/pymupdf/PyMuPDF/files/4589093/PyMuPDF-1.16.18-cp37-cp37m-win32.zip)

Rename the extension back to ".whl" (reacting to a GitHub restriction), and then install via
``python -m pip install -U PyMuPDF-1.16.18-cp37-cp37m-win32.whl``

**Comment by kavin-1098** [comment]
Renamed and installed the whl

Installing collected packages: PyMuPDF
  Attempting uninstall: PyMuPDF
    Found existing installation: PyMuPDF 1.16.7
    Uninstalling PyMuPDF-1.16.7:
      Successfully uninstalled PyMuPDF-1.16.7
Successfully installed PyMuPDF-1.16.18
WARNING: You are using pip version 20.0.2; however, version 20.1 is available.
You should consider upgrading via the 'C:\Python27\python.exe -m pip install --upgrade pip' command.

The issue doesnt seems to be resolved , again getting same error and memory leak still exists

mupdf: malloc of 8415000 bytes failed

**Comment by JorjMcKie** [comment]
can't be. 
I see python27 up there? do you need that wheel really?

**Comment by JorjMcKie** [comment]
Best you put a ``print(fitz.__doc__)`` in the failing script to confirm it is using the right PyMuPDF version.

**Comment by kavin-1098** [comment]
Apologies for the confusing folder name.It is actually python 3.7 inside that folder

output of print(fitz.__doc__)

PyMuPDF 1.16.18: Python bindings for the MuPDF 1.16.0 library.
Version date: 2020-04-22 14:00:00.
Built for Python 3.7 on win32 (32-bit).

**Comment by JorjMcKie** [comment]
Ok. And you have confirmed that the failing script indeed is using that new version?

**Comment by kavin-1098** [comment]
Yes correct

**Comment by JorjMcKie** [comment]
I am confused, because I first could reproduce your issue, and it then had disappeared with the version I sent you.

**Comment by JorjMcKie** [comment]
Well in that case I need that script and see what else may go wrong.
As the saying goes: "you can have lice **_and_** mice"!

**Comment by kavin-1098** [comment]
doc = fitz.open()
                i=0
                for img in os.listdir("C:\pil"):
                    imgdoc=fitz.open(os.path.join("C:\pil",img))
                    imgdoc.convertToPDF()
                    pdfbytes = None
                    gc.collect()
                    imgdoc.close()
                    # imgdoc = None
                    # imgpdf=fitz.open("pdf", pdfbytes)
                    # pdfbytes = None
                    print(i)
                    i = i+1
                    # doc.insertPDF(imgpdf)
                    # imgpdf.close()
                    # imgpdf = None
                gc.collect()
                doc.save("C:\pil\\allmyimages.pdf")
                doc.close()

**Comment by kavin-1098** [comment]
The folder C:\pil has 420 png images

**Comment by kavin-1098** [comment]
I have observed one thing Now the issue is not occuring for 420 individual png images

It is occuring for a single multi page tiff image which has 420 pages

**Comment by kavin-1098** [comment]
Anyways there is a improvement now I think. I will test for another day and confirm

Can you provide same patch for Linux containers also

**Comment by JorjMcKie** [comment]
> It is occuring for a single multi page tiff image which has 420 pages

Ah, I see. That may be. I am afraid, there is nothing **PyMuPDF** can do about it - only **_you_** can. Because the conversion logic always converts **_all pages_** given to it, there is a limit to what your OS configuration can muster.
You are on a 32bit system, which has a very much smaller available virtual space than 64bit systems, for example. And images are typically **_large_**, as you know.
I recommend to change the logic for a multi-page image, and only convert one page page at a time. Something in this direction:

```python
doc = fitz.open("file.tiff")
outdoc = fitz.open()
for i in range(len(doc)):
    tempbytes = doc.convertToPDF(from_page=i, to_page=i)
    temppdf = fitz.open("pdf", tempbytes)
    outdoc.insertPDF(temppdf)
    temppdf.close()
    tempbytes=None
# now save outdoc
```

**Comment by JorjMcKie** [comment]
> Can you provide same patch for Linux containers also

Sure. This works via Travis CI. So after that is finished, I will let you know, fro where to download.

**Comment by kavin-1098** [comment]
Sure Thanks . share me the patch file once done

**Comment by kavin-1098** [comment]
Hope the wheel file u provided works in all operating system

**Comment by JorjMcKie** [comment]
This will be wheels for 64bit Linux systems at Python versions 27, 35, 36, 37, 38.

**Comment by kavin-1098** [comment]
ERROR: PyMuPDF-1.16.18-cp37-cp37m-win32.whl is not a supported wheel on this platform

**Comment by kavin-1098** [comment]
This message i got while trying to install in linux system

**Comment by kavin-1098** [comment]
Can you provide a cross platform whl file

**Comment by JorjMcKie** [comment]
> Can you provide a cross platform whl file

No, this package is not pure Python. You have to wait for platform-specific wheels.

**Comment by kavin-1098** [comment]
Can I get for Linux alone today

**Comment by JorjMcKie** [comment]
Doesn't look good, there is some Travis problem and all wheel generation jobs are cancelling ☹

**Comment by kavin-1098** [comment]
Thats fine let me know once done

**Comment by javiqm12** [comment]
I am affected currently currently by this issue. It would be highly appreciated that this issue get fixed as soon as possible. Thanks in advance

**Comment by JorjMcKie** [comment]
Download your Linux version from [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux).
If you need a different Windows wheel, please let me know.

**Comment by JorjMcKie** [comment]
Concerning your large multi-page TIFF:
Have you tried the change I suggested? As I wrote: when this file causes memory issues, it is not because of a memory leak, but simply because it is such a big beast.

**Comment by javiqm12** [comment]
Thanks you very much for your quick reaction! Highly appreciated!

Yes, I tried your code that closes the temppdf.close() but the python process crashes.
My current workaround is to set max_requests in gunicorn so the workers get restarted every n requests.

I'll test your new version and let you know.
Thanks again!

**Comment by javiqm12** [comment]
I did many test and looks very good!
Thanks for your support and great work :-)

**Comment by JorjMcKie** [comment]
New v1.17.0 officially fixing this is uploaded.
