### ISSUE TITLE
Issue in getPDFnow function with timezones < 0

### ISSUE THREAD

**Issue by alSeveR** [pymupdf/PyMuPDF#502]
- Where it says `tstamp = "+" + tz` should put `tstamp += "+" + tz`.
- Still it wouldn't be enough because tz in that case is negative and in the string you would have -+.To solve this, you can make the result of the division always positive and that also serves to make `rjust` work.
- Finally, using `timezone` does not take into account daylight saving time. Therefore I think it is better to use `altzone`.
```

    import time
    tz = "%s'%s'" % (str(abs(time.altzone // 3600)).rjust(2, "0"),
                 str((abs(time.altzone // 60)%60)).rjust(2, "0"))
    tstamp = time.strftime("D:%Y%m%d%H%M%S", time.localtime())
    if time.altzone > 0:
        tstamp += "-" + tz
    elif time.altzone < 0:
        tstamp += "+" + tz
    else:
        pass
    return tstamp
```

**Comment by JorjMcKie** [comment]
Thanks for your suggestion!
I'll put that in the next version.

**Comment by JorjMcKie** [comment]
New v1.17.0 uploaded.
