### ISSUE TITLE
Graphical elements not redacted

### ISSUE THREAD

**Issue by handsomeyang** [pymupdf/PyMuPDF#504]
Thanks for this wonderful library.

When trying the redaction function, I found that graphical elements were not redacted and only texts were removed. Is it possible to fix this? Thanks.

Input file: 
[redaction.pdf](https://github.com/pymupdf/PyMuPDF/files/4613811/redaction.pdf)

Test code:
```
doc = fitz.open("redaction.pdf")
page=doc[0]
rect = fitz.Rect(100,250,450,400)
page.addRedactAnnot(rect)
page.apply_redactions()
doc.save('tmp.pdf')
```

Redaction annotation:
![Screenshot_2020-05-12_16-40-32](https://user-images.githubusercontent.com/1124230/81646895-667d7480-946f-11ea-8765-2696abce77b2.png)

Redaction result:
![Screenshot_2020-05-12_16-40-51](https://user-images.githubusercontent.com/1124230/81646928-77c68100-946f-11ea-97a9-d30f22eacb44.png)

**Comment by JorjMcKie** [comment]
In their version 1.17.0, MuPDF has improved redactions: they now also remove **_links_** and _**images**_. Even when only a part of an image is covered by a redaction, that part will be **_permanently_** erased - which really is a good job.
But **your** example will unfortunately still not work.
As an approximation to the ideal, all I can offer is specifying a fill color for the redaction, which will cover stuff underneath: ``page.addRedactAnnot(rect, fill=1)`` inserts a white rectangle.

**Comment by JorjMcKie** [comment]
I assume your question is answered and am going to close this.
If further questions arise, please do not hesitate to reopen or submit another issue.
