### ISSUE TITLE
Question / Comment: Is it possible to actual censor pdf

### ISSUE THREAD

**Issue by elben10** [pymupdf/PyMuPDF#505]
In the [censor example](https://github.com/pymupdf/PyMuPDF/wiki/How-to-Insert-new-PDF-Pages,-Images-and-Text#how-to-censor-a-pdf) it is shown how one can overlay some specific words with an image. Is it possible to actual replace the text, so the format of the pdf is kept but the text is replaced?

**Comment by JorjMcKie** [comment]
Well, you uncovered a very ancient example .. I should update or delete it 🤔

> Is it possible to actual replace the text, so the format of the pdf is kept but the text is replaced?

Yes - use a redaction annotation for this. Here is a skeleton:

```python
rlist = page.searchFor("secret text", hit_max=n, quads=False)
# choose n large enough, default is 16
# quads=False, because redactions always replace rectangles.
# The annotation accepts a quad,
# but always uses the rectangle of it
for rect in rlist: # loop through the hit rectangles
    page.addRedactAnnot(rect, text="????", fontname="helv", fontsize=11,
            align=TEXT_ALIGN_LEFT, fill=(1, 1, 1), text_color=(0, 0, 0))

# now "apply" all redactions:
page.apply_redactions()
```
Applying redactions will permanently remove text "touching" a redaction rectangle. This works on a by-character level.
In the coming v1.17.0, overlapping images will be modified with empty (white) cut-outs, overlapping links will be removed.
Replacement text will be fit into the rectangle, horizontally aligned as specified, but always vertically centered (approximately). The given fontsize will be decreased to fit as necessary. Be aware that multi-word text may result in a multiline replacement. So best make sure your new text is not longer ...
You can also give the whole thing a background color ("fill"), and you also can omit all parameters (except rect).

**Comment by elben10** [comment]
Thank you for the very thorough and quick answer.
