### ISSUE TITLE
Would not apply redactions over texts

### ISSUE THREAD

**Issue by lcy2** [pymupdf/PyMuPDF#506]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I tried to remove all texts from the whole page with Redaction Annotation but didn't work.

## To Reproduce (mandatory)
```
for block in old_page.getText('blocks'):
    old_page.addRedactAnnot(block[:4]);

#old_page.addRedactAnnot(old_page.rect)

old_page.apply_redactions();
show_image(old_page)
```
I tried both ways (with rect encompassing the whole page, or picking up individual "blocks") but the end result is always no redaction. When I do fill = 1 however, the rects are indeed filled in and blanked out, but it's not as accurate as I'd like it to be.

I can extract the texts no problem however, so PyMuPDF does see the texts as characters.

## Expected behavior (optional)
All texts are removed leaving behind the graphics that I cannot extract alone with XObjects methods.

## Your configuration (mandatory)
3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] 
 darwin 
 
PyMuPDF 1.16.18: Python bindings for the MuPDF 1.16.0 library.
Version date: 2020-04-22 14:00:00.
Built for Python 3.7 on darwin (64-bit).

**Comment by JorjMcKie** [comment]
Sounds awkward. Please provide a minimal reproducer.

**Comment by JorjMcKie** [comment]
> ...but it's not as accurate as I'd like it to be

As far as precision is concerned, v1.16 of PyMuPDF bases decisions on whether a text character should be removed on the fact whether its bottom-left bbox point is inside the redact rect. This may lead to a ragged, not always convincing appearance.
This has changed in v1.17.0: characers seem to be removed as soon as they "touch" a redact. Also images are now fully supported: they are either fully removed, or modified with overlapping parts whitened.

**Comment by lcy2** [comment]
Hi Jorj, thank you so much for your quick response. Unfortunately the PDFs (or the types of PDFs generated by the CAD software) are very sensitive documents and I cannot provide that as an example.

By the lack of accuracy, I meant, instead of simply getting rid of the texts, it slaps a white box over the area of question with "fill = 1", which gets rid of a lot more information than I'd like. That was why one of my attempts was simply placing the redaction annotation over the whole page, and hope that it would only get rid of the texts and nothing else. Unfortunately that results in nothing gets removed, even though the apply_redactions() function returns True. If I do fill = 1, as you'd expect, the whole page gets blanked out.

I did see in some other conversations you had mentioned that the redaction was by character. But for the PDF structure outputted by the CAD software, it doesn't seem as straightforward. I did some browsing around in the xrefs and saw that the decoding was by flate. Not sure whether that's helpful. Here is the meta information on the file:
{'format': 'PDF 1.7',
 'title': None,
 'author': 'NX',
 'subject': None,
 'keywords': None,
 'creator': 'cgm2pdf',
 'producer': 'PDFlib+PDI 9.2.0 (C++/Win64)',
 'creationDate': "D:20200221172651-08'00'",
 'modDate': None,
 'encryption': None}

**Comment by lcy2** [comment]
Btw, when will v1.17.0 be released?

**Comment by lcy2** [comment]
One additional bit of info: after applying the redactions, even though I can still see the texts, but when I try to do print(Page.getText('dict')), there's nothing left. Whereas before there are pages of output.

**Comment by JorjMcKie** [comment]
Unfortunate situation, indeed.
If I get you right, then ``page.getText(option)`` delivers nothing anymore after applying the redaction? No matter what value for **_option_** you use?

By definition, redaction annotations **_must remove everything_** underneath their rectangles - no matter if text or images or whatever else.
In v1.17, MuPDF fulffills this rule almost completely as described above. The exception being "paint" (draw) commands coded in the PDF mini-language as described in "Appendix A Operator Summary" starting on page 985 of the spec.
So any **"atomic"** draw commands (drawing lnes, rectangles, curves, ...) as is typical for CAD output, will **not** be removed. If one knows a bit about that mini-language, this is very understandable, because a full-blown analysis of the full page would be required - much like a PDF viewer logic.
This is the residual justification of the ``fill=color`` parameter - apart from cosmetic reasons.
So, if text doesn't go away without that fill parameter ... well then it's not _**text**_. You can create stuff looking like text by just drawing lines, curves, rectangles with that mini-lanbguage.

But you sound like, you **_only_** want to remove text and nothing else.
If so, then that's not a case for redactions.
You can just remove the text using PyMuPDF. To do that, read the page's context and remove everything wrapped by a pair of strings ``"BT ... ET"``.

**Comment by lcy2** [comment]
You are correct in that no matter what opt I supply, Page.getText(opt) returns something empty, unlike before I applied the redactions.

I'm aware that the paths are probably drawn by those atomic commands. It is just curious that even the texts can't be redacted. fill=color parameter does cover them up, but it also covers up the atomically-drawn non-text area, so I was seeking an alternative.

Could you help me with the suggestion in your last paragraph?

I currently have this:
`xrefobj = old_file.xrefStream(5).decode('utf-8')

xrefobj2 = re.sub('BT.*ET', '', xrefobj, flags= re.DOTALL).encode('utf-8')
#print(xrefobj2)
#print(type(xrefobj2))

old_file.updateObject(5, xrefobj2)
show_image(old_file.loadPage(0))`

where the object at xref = 5 is the /content of the first page, and show_image() is just a custom function to display the page.

It is complaining that 
![image](https://user-images.githubusercontent.com/15602561/82128702-de9ab180-9771-11ea-9464-f8653f7934b9.png)

How should I update the xrefobject correctly? And secondly, is there an easy to pull info out of Page.xref, maybe in a JSON format? This is so I can check which xref number is associated with "/content"

**Comment by lcy2** [comment]
Using updateStream instead of updateObject it worked. However, having removed anything between BT ... ET, it only results in a couple of circles removed. Still not the text...

**Comment by JorjMcKie** [comment]
Ok, you were faster and found out yourself how to update a page's stream.
A few things of interest:

* A page can have zero to many of those ``/Contents`` objects. ``Page.getContents()`` delivers a list of relevant xrefs.

* A page may reference so-called XObjects, which either are images or "Form XObjects". Form XObejcts can be thought of being replicates of pages from another PDF (PyMuPDF creates them as part of the ``Page.showPDFpage`` logic). As a consequence, **_Form XObjects_** may contain text as well (which would then be extracted by by ``getText`` methods of the page). Both cases don't seem to apply here, but have a look at ``doc.xrefObject(page.xref)``. You might see something like the following:

```postscript
>>> print(doc.xrefObject(page.xref))
<<
  /Type /Page
  /Parent 18 0 R
  /Resources 46 0 R  % images, fonts and Form XObjects are found here
  /Contents [ 45 0 R 53 0 R ]
  /CropBox [ 482 198 1048 924 ]
  /MediaBox [ 0 0 1417 1122 ]
  /Rotate 0
  /Thumb 42 0 R
>>
>>> print(doc.xrefObject(46))
<<
  /ExtGState <<
    /GS1 39 0 R
    /GS2 33 0 R
  >>
  /Font <<  % referenced fonts
    /F3 23 0 R
    /F5 24 0 R
    /F8 27 0 R
    /F10 28 0 R
    /F12 30 0 R
  >>
  /XObject <<
    /Im1 32 0 R  % propably an image
    /fzFrm0 52 0 R % maybe a Form XObject
  >>
  /ProcSet [ /PDF /Text /ImageC ]
>>
>>> 
```

**Comment by lcy2** [comment]
Yeah so that was what I did before. There was only one "content" object on the page:
```
print(old_file.xrefObject(old_file.loadPage(0).xref))
print('----------------')
print(old_file.xrefObject(5))
print('----------------')
print(old_file.xrefObject(9))


<<
  /Type /Page
  /Parent 1 0 R
  /Contents 5 0 R
  /Resources 9 0 R
  /MediaBox [ 0 0 2448 1584 ]
>>
----------------
<<
  /Length 4 0 R
  /Filter /FlateDecode
>>
----------------
<<
  /Font <<
    /F0 8 0 R
  >>
  /ExtGState <<
    /GS1 6 0 R
    /GS2 7 0 R
  >>
>>
```

This was why I brought up the "Flate" decode business. I believe the case here is that all of the in the one singular Content object and that's it. I'm still curious how PyMuPDF picked up all the texts though. At least the /Resources side of things, there are no XObjects.

**Comment by JorjMcKie** [comment]
> At least the /Resources side of things, there are no XObjects.

yes, I see it. So all the secrets are buried in that one and only ``/Contents``.

> I'm still curious how PyMuPDF picked up all the texts though. 

You **_should_** be able to locate the text in the original contents. It may be, that the text was coded "hidden". Especially with scanned-in images, OCR software does something like this, to make image-based text searchable and able to be copy/pasted by adding this type of text layer.
Hidden text is encoded with a ``2 Tr`` command ("text rendering"). Like any other decent text, hidden text is also removable - but it obviously will still not visually disappear.
"PDF" is a spec with lots and lots of different options!

Well, without access to your data, I'm afraid I have reached the limits of what I can suggest.

**Comment by lcy2** [comment]
Thanks a lot. I really appreciate your prompt reply and generous help.
