### ISSUE TITLE
 ValueError("rect must be finite and not empty")

### ISSUE THREAD

**Issue by gvnramu** [pymupdf/PyMuPDF#508]
Hi I'm new to PyMuPDF
My intention is to read the image from pdf page and process it and replace the processed image back to pdf file
Getting Image coordinates like this 

`rect = get_image_bbox(page, pdf_document.getPageImageList(current_page)[i])` 

I got `Rect(0.0, -7578.0, 3969.60009765625, -1966.800048828125)`
                    
when trying to insert an image using `page.insertImage(rect, pixmap=pix, overlay=True)` method I'm getting `ValueError("rect must be finite and not empty")` but
`rect.isEmpty` is returning **False** and
`rect.isInfinite` is returning **False** 
What I'm doing wrong. Please help me

**Comment by JorjMcKie** [comment]
Hi @gvnramu, pleased to see you are using PyMuPDF.

1. Preliminary comments:
For submitting a bug, all mandatory information is missing: among them info about your installation and, most importantly, basic data for reproducing the error.

2. Your script will **_not_** "replace" the old image, but leave it in the file. The new one (provided everything else is working) will just overlay it.

3. The retrieved image coordinates are probably wrong. Image insertion will check whether there is a non-empty intersection with the page rectangle, which visibly is not the case.

**Comment by gvnramu** [comment]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Incorrect rect is returned from the `get_image_bbox(page,pdf_document.getPageImageList(current_page)[i])` method 

## To Reproduce (mandatory)

Get the rect using `rect = get_image_bbox(page, pdf_document.getPageImageList(current_page)[i])`

and insert the image in the below link using 

`page.insertImage(rect, pixmap=pix, overlay=True)`

You can download the required files from here [files.zip](https://github.com/pymupdf/PyMuPDF/files/4642338/files.zip) 

## Expected behavior (optional)
Correct rect of an image int the pdf

## Screenshots (optional)
![error](https://user-images.githubusercontent.com/22232148/82179088-20a32f00-98fb-11ea-8fbb-eadc1b411f9f.png)


## Your configuration (mandatory)
- Ubuntu 18.04 LTS  - Architecture: x86-64
- Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] 
 linux 
 
- PyMuPDF 1.16.18: Python bindings for the MuPDF 1.16.0 library.
Version date: 2020-04-22 14:00:00.
Built for Python 3.7 on linux (64-bit).

 - Installed via **pip install PyMuPDF**

**Comment by JorjMcKie** [comment]
Hi @gvnramu - thank you for that detailed description!
I'll look into it. I have already confirmed, that there is indeed a bug in calculating the image bbox, so let's see ...

**Comment by JorjMcKie** [comment]
If you want to try out a hopefully improved version, download your wheel from [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux) and install in via ``python -m pip install -U <wheelname>``.

This version also supports a way to delete unwanted images by using "Redaction" annotations:

```python
doc = fitz.open(...)
page = doc[0]
page.addRedactAnnot(page.rect)  # marks the whole page content as to-be-deleted
page.apply_redactions()  # executes the deletion
# now insert the modified images here
...
doc.save(outpdf, garbage=4, deflate=True)
```
Garbage option 4 is recommended here, to get rid of as many duplicate large binary objects as possible.

**Comment by gvnramu** [comment]
Thanks @JorjMcKie I will try it

**Comment by gvnramu** [comment]
HI @JorjMcKie  after installed **PyMuPDF-1.17.0-cp37-cp37m-manylinux2010_x86_64.whl**

I got the following error 

![screenshot-2020-05-19-11-01-06](https://user-images.githubusercontent.com/22232148/82288761-d5ebea80-99c0-11ea-8a85-5c6d9a26348e.png)

**Comment by JorjMcKie** [comment]
The private method ``Page._getTransformation()`` in previous releases has been removed and is now an official **_attribute_** ``Page.transformationMatrix``.
After replacing this, you should be fine.

**Comment by gvnramu** [comment]
Hi @JorjMcKie. Even after I got the same rect `Rect(0.0, -7578.0, 3969.60009765625, -1966.800048828125)`

**Comment by JorjMcKie** [comment]
I don't believe that! I have tried your file, and I am getting this:

```python
>>> import fitz
>>> doc=fitz.open(...)
>>> imglist = doc.getPageImageList(0, True)
>>> page = doc[0]
>>> for item in imglist:
	print(item[7], page.getImageBbox(item))

	
R8 Rect(0.0, -6.103515625e-05, 396.96002197265625, 561.1199951171875)
R9 Rect(0.0, 280.87994384765625, 396.96002197265625, 842.0)
>>> 
```
And those two rectangles are correct - I confirmed this by doing ``page.drawRect(r)``.
It worked for me for both, Windows and Linux.

**Comment by gvnramu** [comment]
Sorry @JorjMcKie. That was my mistake. It's working fine. Thank you soo much. Closing the issue

**Comment by JorjMcKie** [comment]
Never mind. I am glad it is working now.

**Comment by gvnramu** [comment]
Hi @JorjMcKie I'm getting the following error while applying redactions 

page.apply_redactions()  # executes the deletion
![screenshot-2020-05-20-15-16-58](https://user-images.githubusercontent.com/22232148/82432058-1b85e180-9aad-11ea-9d18-5521b8dac68a.png)

**Comment by JorjMcKie** [comment]
I need material to reproduce ...
Also it seems opening a new issue would be appropriate.
