### ISSUE TITLE
Missing py27 Linux wheel for 1.17.0 release

### ISSUE THREAD

**Issue by stephenfin** [pymupdf/PyMuPDF#511]
Per title, there does not appear to be a `PyMuPDF-1.17.0-cp27-cp27m-manylinux2010_x86_64.whl` wheel [published to PyPI](https://pypi.org/project/PyMuPDF/#files). This necessitates building from source. I tried to figure out where these are built, so I could determine if there was a build failure or this was intentional, but I was unable to do so :disappointed:

**Comment by JorjMcKie** [comment]
I did not intend to discriminate users of outdated Python versions 😎
But Travis CI, which does the wheel building, has issues these days.
I just built a Python2 version on my machine (Ubuntu). If you want I can supply a zip of the corresponding ``fitz`` folder via this channel.

**Comment by JorjMcKie** [comment]
Ok here is comes.
[lib.linux-x86_64-2.7.zip](https://github.com/pymupdf/PyMuPDF/files/4657427/lib.linux-x86_64-2.7.zip)

**Comment by JorjMcKie** [comment]
I will check with Travis from time to time and publish the missing wheel as soon as it is working agian.

**Comment by stephenfin** [comment]
> I did not intend to discriminate users of outdated Python versions sunglasses
> But Travis CI, which does the wheel building, has issues these days.
> I just built a Python2 version on my machine (Ubuntu). If you want I can supply a zip of the corresponding `fitz` folder via this channel.

Awesome! Would it be possible to push a manually built wheel to PyPI? I spotted this issue when trying to figure out why https://github.com/rst2pdf/rst2pdf/pull/854 failed on Python 2.7 so I'd like to resolve that.

**Comment by JorjMcKie** [comment]
> Would it be possible to push a manually built wheel to PyPI? 

Maybe ... somehow I suppose. After all I am building Windows wheels with a handmade script directly on my machine.
The issue with any such handcrafted wheel would be, that it is **_not tagged manylinux_**, so only works for Ubuntu-like systems I guess.
As a Windows freak I have to wipe a sarcastic smile from my face, when I think about the portability of Linux systems ... 😂😂😂

**Comment by stephenfin** [comment]
Oh, indeed, that's certainly not trivial. Based on [this project](https://github.com/pypa/python-manylinux-demo/), it seems you should be able to do the following from the root of the pacakge to build the package:

```
wget https://raw.githubusercontent.com/pypa/python-manylinux-demo/master/travis/build-wheels.sh
docker run --rm -e PLAT=manylinux1_x86_64 -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /io/build-wheels.sh
```

...but I notice that we're not using setuptools (and maybe can't) so I've really no idea :smile:

**Comment by stephenfin** [comment]
I guess let's just wait on Travis, as you suggest

**Comment by JorjMcKie** [comment]
Further investigation showed that the issue is (1) confined to Linux Python 2.7 (tags cp27m and cp27mu), and (2) caused by ``auditwheel repair`` - not by Travis CI nor by ``cibuildwheel`` itself.

I submitted an [issue](https://github.com/pypa/auditwheel/issues/243) to the auditwheel repo.

**Comment by JorjMcKie** [comment]
In the end it turned out it was a PIP v20.1 issue.
I modified the build script for ``cibuildwheel`` so that the newest PIP would be used.
This solved the issue, and the Linux Py2.7 wheels are upload to PyPI.

**Comment by stephenfin** [comment]
Thanks for investigations on this!
