### ISSUE TITLE
fit.Rect.contains does not work properly on line-degenerated rect

### ISSUE THREAD

**Issue by maffei2443** [pymupdf/PyMuPDF#514]
## Describe the bug (mandatory)
The bug: when a rect is degenerated to a line, **fitz.Rect.contains** seems to always return **True**. I was expecting to get a _True_ ony if the whole line was inside the rec.

## To Reproduce (mandatory)
```python
import fitz
r = fitz.Rect(0,0, 605, 810)         
# False is expected
print(r.contains((0, 0, 0, 100000)))
# False is expected
print(r.contains((10000, 0, 0, 0)))
# False is expected
print(r.contains((5, 5, 5, 10000)) )
```

## Your configuration (mandatory)
 - Xubuntu 18.04 LTS, potentially version and bitness
 - Python 3.8.1 
 - PyMuPDF version: 1.16.18, wheel

## Additional context (optional)
I checked the **fitz.py** file and identified why that happens. It is caused by line **1437**:

```python
if xr.isEmpty: return True
```

The __contain__ method which is called under the hood:
```python
    def __contains__(self, x):
        if hasattr(x, "__float__"):
            return x in tuple(self)
        l = len(x)
        r = Rect(self).normalize()
        if l == 4:
            if r.isEmpty: return False
            xr = Rect(x).normalize()
            if xr.isEmpty: return True
            if r.x0 <= xr.x0 and r.y0 <= xr.y0 and \
               r.x1 >= xr.x1 and r.y1 >= xr.y1:
               return True
            return False
        if l == 2:
            if r.x0 <= x[0] <= r.x1 and \
               r.y0 <= x[1] <= r.y1:
               return True
            return False
        return False

```

The point is: shouldn't this behavior be documented? The **fitz.Rect.contains** method is:

```python
    def contains(self, x):
        """Check if containing a point-like or rect-like x."""
        return self.__contains__(x)
```
Maybe this is a documentation bug or a corner case?

**Comment by JorjMcKie** [comment]
Here is a quote from the doc:

> contains(x) 
> Checks whether x is contained in the rectangle. It may be an IRect, Rect, Point or number.
> If x is an empty rectangle, this is always true. If the rectangle is empty this is always False for all non-empty rectangles and for all points.
> If x is a number, it will be checked against the four components. x in rect and rect.contains(x) are equivalent.

**Comment by maffei2443** [comment]
I've just typed 
```python
help(fitz.Rect.contains)
```

and read it. Sorry for does not reading the whole docs file.

**Comment by JorjMcKie** [comment]
Admittedly, some aspects in PDF, MuPDF terminology are counter-intuitive.
