### ISSUE TITLE
Missing info (neither image nor text) for some PDFs

### ISSUE THREAD

**Issue by cyga** [pymupdf/PyMuPDF#517]
## Describe the bug (mandatory)

When I try to read text of some PDFs I can't find information I can clearly see in PDF viewer programs.

I tried to check both text and images related functionality.

## To Reproduce (mandatory)

I use following code to check text / images:

```python
import fitz
from IPython.display import Image

pdf = fitz.open('../tmp/missing-info.pdf')
page = pdf[0]
d = page.getText('dict')
tl = []
for block in d['blocks']:
    if 0 == block['type']:
        for line in block['lines']:
            for span in line['spans']:
                tl.append(span['text'])
    else:
        Image(data=block['image']) 
print(tl)
```

It works well for the most of my files, but not for some. For instance following one gives nothing: 
https://www.dropbox.com/s/scqmcwhhfivi9gn/missing-info.pdf?dl=0

And following shows only one text chunk:
https://www.dropbox.com/s/b7nx0g6m37uex1b/missing-info2.pdf?dl=0

I also tried following methods:
* `Document.getPageImageList()`
* `Document.getPageXObjectList()`
* iterate over `page.widgets()`
* iterate over `page.annots()`

All return nothing.

Interestingly, `Document.getPagePixmap()` returns proper image with information.

Looks like some info hasn't been parsed.

## Expected behavior (optional)

Either text or images were returned for the document. Though, I suspect it can be some other type of data. Anyway, I'd like to have a way to check it.

## Your configuration (mandatory)

```
3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] 
 linux 
 
PyMuPDF 1.16.18: Python bindings for the MuPDF 1.16.0 library.
Version date: 2020-04-22 14:00:00.
Built for Python 3.5 on linux (64-bit).
```

Installed using wheel:
PyMuPDF-1.16.18-cp35-cp35m-manylinux2010_x86_64.whl

**Comment by JorjMcKie** [comment]
This just is an example for a nasty PDF creator 😉.
If you look closer you will see, that there also are no fonts at all referenced.
The explanation:
Every single letter or other symbol, etc. has been created by atomic paint commands in the PDF mini-language (something like postscript, consult PDF manual pages 985 pp).
E.g. the letter "D" can be constructed by a short line "|" and a semi-circle. This is what is going on here.
Heaven knows why he / she did so ... maybe just to frustrate text extractors like you and me, or, more seriously, data protection motivation.
Such a file can only be deciphered using an OCR software, which you give an image of the page e.g. created via pixmap.

**Comment by JorjMcKie** [comment]
I noticed that the file was created via LibreOffice "Draw". Hm - if that's possible with it, certainly an interesting info.

**Comment by cyga** [comment]
@JorjMcKie thanks for the very quick reply.
Can you, please, give me a direction on how can I check such objects inside a PDF? In order to fallback to OCR in case of such documents.
Also, I didn't understand what did you mean by: "consult PDF manual pages 985 pp"?

**Comment by JorjMcKie** [comment]
Most of the checks you already have done: ``page.getText("dict")`` delivering nothing is a good indicator, because by default it delivers all text and also all images in ``bytes`` format.
If you want to see the "source code" of this page, do this: ``cont = page.readContents().decode()`` (convert ``bytes`` to `str`). It looks like this: [cont.zip](https://github.com/pymupdf/PyMuPDF/files/4677857/cont.zip).
What these statements mean is explained in the Adobe PDF manual, "Appendix A Operator Summary" (page 985)  http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf.

**Comment by hiendoan95** [comment]
I have the same issue as you mentioned. In my case, just a few characters are lost when I use the getTextWords() method to read all words in my pdf file.
For example, this part return text "〝     ×            ×                  〝 when extracting 
![image](https://user-images.githubusercontent.com/43055885/103168052-7d909b80-4873-11eb-9f35-df3e0e00fc8e.png)

**Comment by JorjMcKie** [comment]
@hiendoan95 - if you get words that **_seem_** to contain spaces like the example you gave, then rest assured: these **_are_** not spaces!
There are things like "protected" spaces, which are used to prevent line breaks at their position.
This is not the same case as mentioned in the discussion with @cyga.

The word extraction method scans all characters of a page and delivers strings of non-blank characters. So a new "word" is started after each space (or start of a new line) and ended when a space is encountered (or a line break).

**Comment by hiendoan95** [comment]
@JorjMcKie Is there anyway that I could find the original character at the protected positions? 
I need to extract the image and the corresponding text as the ground truth data.

**Comment by JorjMcKie** [comment]
The original character is being returned as part of the word! Just loop through the word and compute ``ord(c)`` for each word character c in word.
Note: I am saying all this without knowing what type of file you are actually processing.

**Comment by hiendoan95** [comment]
@JorjMcKie Thank you. I'll try your solution. I'm working with editable pdf file, which contains Japanese (almost) and English.
