### ISSUE TITLE
Wheels missing for 1.17 release

### ISSUE THREAD

**Issue by wohali** [pymupdf/PyMuPDF#518]
## Describe the bug (mandatory)
There's published wheels for 1.16.18, but not for 1.17. The release has been out for 7 days without binaries.

## To Reproduce (mandatory)
`pip install pymupdf` on a system without C/C++compliation support.

## Your configuration (mandatory)
 - All OSes I tried
 - Python 3.6-3.8
 - Only 1.17, 1.16.18 has wheels

## Additional context (optional)
Occasionally I've had problems getting the wheels in the past. This is compounded by tools like GitHub dependabot, which generate PRs to bump dependencies as soon as new versions are detected.

Is it possible to gate pushing the new version to pypi until the wheels are available?

**Comment by JorjMcKie** [comment]
All the usual wheels v1.17.0 for Windows, Linux and ISX are there on PyPI, https://pypi.org/project/PyMuPDF/#files.
Linux Py2.7 took a little longer because of some upstream bug, but the rest was uploaded the same day as the source material.

**Comment by JorjMcKie** [comment]
Ah, no, wait - I just saw Windows is missing!
Wait a moment ...

**Comment by wohali** [comment]
Yeah, Windows seems to go missing more often.

I'm still tracking down why `pip install` won't pull in the wheels on Linux in my CI workflow. I'm updating pip to the latest (I know this is required for the `manylinux` wheels) but what used to work 2 months ago isn't working now. Will update if it turns out not to be my fault (or the CI tool's...)

**Comment by JorjMcKie** [comment]
I just tried to upload the Win wheels, assuming I forgot them.
But: PyPI refuses them now b/o ``Client Error: File already exists. ``, and no Win files are showing on that web site!

**Comment by JorjMcKie** [comment]
I am little out of advice.
I am going to upload the Win wheel to PyMuPDF's releases folder, so you can get them from there for the time being.
That takes a bit  - another day of internet issues in Venezuela.

**Comment by wohali** [comment]
That won't help with my CI workflow, but thanks anyway.

I'll try pinning for 1.16.18 for now, until 1.17.1 comes out. If necessary I'll re-open...any chance of having your CI system push the packages for you to save bandwidth?

**Comment by wohali** [comment]
fyi: https://github.com/wohali/hough/pull/58/checks?check_run_id=710314805 is the failed attempt to pip install 1.17.0 on Linux, and it can't find the wheels. You can see it's running pip 20.1.1.

**Comment by JorjMcKie** [comment]
> ...any chance of having your CI system push the packages for you to save bandwidth?

I used to do that once, but found the process too error-prone. If anything goes wrong (which are / were norare incidents!) I had a mess of wheels successfully uploaded to PyPI and failed others. Cleaning this up is a nightmare - at least for me.
Moreover, the Win wheels are generated locally, so the relieve would be limited anyway.

Just yesterday I was able to resolve an issue with Py2.7 on Linux. This bug would have caused me again one of those nightmares.

**Comment by JorjMcKie** [comment]
Just confirmed that I can install Linux Py3.6 fromPyPI.
I have really no idea what is going on here.

**Comment by wohali** [comment]
OK, thanks, I'll close this for now and reopen if I find something that isn't my fault or GitHub's fault ;)

**Comment by wohali** [comment]
FYI pip is correctly installing pymupdf 1.17.0 on Windows from the wheel. :+1: Thanks so much!
