### ISSUE TITLE
commercial use of pymupdf

### ISSUE THREAD

**Issue by canedha** [pymupdf/PyMuPDF#521]
pymupdf is licensed under gpl_v3, doesn't this mean if one uses your library in a commercial product this would automatically be under gpl_v3 as well (and the source code would need to be made available for customers)?
or can your library be used !unmodified! in a commercial product with a gpl-incompatible license type? 
for mupdf a commercial license would be necessary for sure.

**Comment by JorjMcKie** [comment]
I am not a lawyer, but when reading the GNU GPL v3.0 license text I conclude that you can use material licensed under this in commercial products as well - under a different license and without having to disclose source.
But as you wrote: all this under the assumption that you have obtained a commercial license of MuPDF.
