### ISSUE TITLE
Redaction selects to-be-deleted text differently in v1.17

### ISSUE THREAD

**Issue by FredIngwersen** [pymupdf/PyMuPDF#526]
## Describe the bug
When redacting a line with bold in a PDF file with docker, PyMuPDF removes the surrounding bold lines. This does not happen locally.

**NOTE**
While writing up this bug report, we found that the version 1.17 is the difference, which causes the problem.

## To Reproduce
I have made a script to replace the bold text in a given PDF file.
The file can be found at: https://sonderborgkommune.dk/sites/all/files/Forvaltninger/hoeringer/files/landzonetilladelse_til_etablering_af_soe_og_dispensation_til_oprensning_af_soe.pdf

```python
import fitz

filepath = "original.pdf"
doc = fitz.open(filepath)
page = doc[0]

rect = fitz.Rect(
    (63.86399841308594, 292.0328063964844, 403.9803466796875, 305.7477111816406)
)
page.addRedactAnnot(rect, text="test")
doc.save("temp.pdf")
page.apply_redactions()
doc.save("test.pdf")
```

When this code in run on our local machine it is processed as expected, but when the pdf is processed in our docker container (python:3.7) it removes all the bold lines. The addRedactAnnot identifies the correct rect which can be found in the temp.pdf file that is produced by the above script. 

## Screenshots (optional)
Temporary pdf with annotation without them being applied
![](https://i.ibb.co/F5RPVJz/Screenshot-2020-06-09-at-16-56-28.pnghttps://i.ibb.co/F5RPVJz/Screenshot-2020-06-09-at-16-56-28.png)
Processed pdf.
![](https://i.ibb.co/RvLLk22/Screenshot-2020-06-09-at-16-56-21.png)

## Your configuration (mandatory)
**Local Machine**
```
3.7.7 (default, Mar 10 2020, 15:43:33)
[Clang 11.0.0 (clang-1100.0.33.17)]
 darwin

PyMuPDF 1.16.18: Python bindings for the MuPDF 1.16.0 library.
Version date: 2020-04-22 14:00:00.
Built for Python 3.7 on darwin (64-bit).
```
**Docker**
```
3.7.7 (default, Apr 23 2020, 14:43:26)
[GCC 8.3.0]
 linux

PyMuPDF 1.17.0: Python bindings for the MuPDF 1.17.0 library.
Version date: 2020-05-13 20:05:13.
Built for Python 3.7 on linux (64-bit).
```

Both installed with pypi

**Comment by JorjMcKie** [comment]
There indeed is a difference in MuPDF's (**_not_** PyMuPDF's) behaviour compared to v1.16.x:

While a character in v1.16 was included in the redaction when its **_bottom-left point_** was inside the redact rect, this decision is now taken when **_any part_** of the character's bbox has a non-empty intersection.

And your redact rect is chosen thus, that the characters above and below all have such an intersection. To illustrate I have marked every word bbox (thin blue line) on the page:
![grafik](https://user-images.githubusercontent.com/8290722/84171626-087d8600-aa49-11ea-8ead-53ade1277bc6.png)

If you reduce the height of your rect, for example ``fitz.Rect((xxx, 293, xxx, 304))`` you will get the desired result again:
![grafik](https://user-images.githubusercontent.com/8290722/84173015-b2114700-aa4a-11ea-85e8-d91838ae48b2.png)

**Comment by JorjMcKie** [comment]
In a programmatic situation (e.g. you determined the redacted text via text search), admittedly it may sometimes be a challenge to avoid collateral deletions ...
On the other hand, the previous criteria (containment of the bottom-left character point) also was prone to objections.
Of some help may be this approach: take the height of your redact rect, then calculate ``h = (y1 - y0) / 2`` and re-calculate ``y0 = h - alfa``, ``y1 = h + alfa`` where ``alfa = fontsize * 0.5 * percentage``.
Percentage might be something like 80% of the rect height, etc.

**Comment by FredIngwersen** [comment]
Thank you very much for the quick and comprehensive response!

I completely understand why this happens now - I'll close the issue.

Best regards

**Comment by JorjMcKie** [comment]
You are welcome and I am glad you find this package useful.

**Comment by JorjMcKie** [comment]
Just as an addendum to my comments: here is a little picture from the documentation explaining how deletion decisions were made in version 1.16:
![img-redact-2](https://user-images.githubusercontent.com/8290722/84374407-f23c0b00-abab-11ea-82ed-dd6052df192e.jpg)
I think you will agree that this behaviour was unsatisfactory. In v1.17 both characters are removed now.
