### ISSUE TITLE
Question / Comment: Any function that could return a text in given coordinates?

### ISSUE THREAD

**Issue by farhan9545** [pymupdf/PyMuPDF#527]
If I have a block and I want to extract the text from that block, any function that returns the text, if I provide the coordinates?

**Comment by JorjMcKie** [comment]
There are example scripts like [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/textboxtract.py) one.
Its basic approach is to frist extract all words from the page (``Page.getText("words")``), sort them by ascending vertical, then by hrozontal coordinate. Then select the words that are contained in a given rectangle (or alternatively **intersect** it) and then reconstruct the remaining text word by word.

However, the more you know about your PDF, the better can you choose between the many alternatives:
If your "block" can be given by just two vertical coordinates, you only need to subselect the output from ``Page.getText("blocks")``, etc.
