### ISSUE TITLE
Annot.rect attribute in 1.17

### ISSUE THREAD

**Issue by farhan9545** [pymupdf/PyMuPDF#528]
The rect attribute of annot class is giving wrong values. The values do not match with rect values of version 1.16.18. The values of 1.16.18 seems correct as they match with the values provided by pdf viewers such as foxit. 

The implementation of annot class or atleast the method that calculates the rect should be reverted back to 1.16.18.

**Comment by JorjMcKie** [comment]
There have indeed been changes. They should however only pertain to rotated pages only.

In PyMuPDF coordinates are (should) all refer to coordinates as if a page were **_not_** rotated.
If this is your case, you can swich between rotated and unrotated coordinates via matrices `Page.rotationMatrix` and `Page.derotationMatrix`.

So, before an ``annot.rect`` is returned to your script, it ismultiplied with ``page.derotationMatrix``.
Multiply what you have been getting with ``page.rotationMatrix`` and you will see where the annot is located on the rotated page.

A bug is only acceptable if your example is something else.

**Comment by JorjMcKie** [comment]
Assuming above explanation answered your inquiry.
