### ISSUE TITLE
How would you determine a zoom factor for PDF files?

### ISSUE THREAD

**Issue by liamsuma** [pymupdf/PyMuPDF#531]
I am currently working on an OCR project for bank statements and came across your package which surprisingly very handy. However, I read the documentation and couldn't figure out how you determine zoom factor. Is this randomly assigned to or is this something could be returned with an accurate number from the package? For example, 

zoom = 2 # zoom factor
mat = fitz.Matrix(zoom, zoom) # x and y direction could be zoomed independently
pix = page.getPixmap(matrix = mat, alpha = False)
The resulting png in this case has 4 times more pixels per area

Thank you for your help

**Comment by JorjMcKie** [comment]
I am not sure I quite understand:

A PDF as such has no zoom factor. It is **_you_** who **_sets_** the zoom factor when creating a page image as in your quoted example, ... because you want better quality or see more details or want to enlarge a small font or whatever.
Because PDF is some kind of vector graphics format, you can arbitrarily magnify without seeing ragged lines or borders (of course except any embedded page content in a raster format).

This matrix facility would typically be used by GUI applications, for example [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/doc-browser.py) one.

**Comment by liamsuma** [comment]
Thanks for your quick reply. So for zoom factor, it's basically depending on the users to set the parameters as how to render a page image. Here is the issue that I am currently experiencing: I set the zoom factor at 3.62 for Bank of America statements and it works just fine with extracted information. However, for some statements, a zoom factor of 3.62 would not suffice and it needs to be increased to 3.65 for some of the content to show in final output, say csv files. Any ideas how this happened? I think it might be some bugs in my Python script after conversion from PDFs to image but would like a professional opinion on this. Thank you sir

**Comment by JorjMcKie** [comment]
Does "bank statement" refer to a scanned-in image?
And do you OCR that page image for extracting content?
Maybe you can show me an example or / and the relevant part of your script ...

If you do **not** have a PDF coming from a scanner, then why don't you just **_extract_** the text and avoid all that image resolution hassle?

**Comment by liamsuma** [comment]
No. Bank statements are submitted as clean PDF format as far as I know. 
Yes. I will OCR each page and extract relevant information
Here is part of my script:
```
input_file = 'path/to/pdfs'
print('Processing File : ', input_file) 
print('Generating CSV ...')
pdf_file = input_file
fullText = "" # Just get the entire text format of bank statements and work from there 

doc = fitz.open(pdf_file)
zoom = 3.62 #3.72014 - 3.62
#zoom = 3.65
mat = fitz.Matrix(zoom, zoom)
noOfPages = doc.pageCount

for pageNo in range(noOfPages):
    page = doc.loadPage(pageNo) #number of page
    pix = page.getPixmap(matrix = mat)
    output = 'path/to/save/image' + str(pageNo) + '.jpg'
    pix.writePNG(output)
    print('Converting PDFs to Image ... ' + output)
    text_of_each_page = str(((pytesseract.image_to_string(Image.open(output))))) # Also use Pytesseract 
    fullText += '\n'

fullText = fullText.splitlines() # extract information and do things accordingly 
```
Let me try it without introducting zoom factor and see if I can get a better result. Thanks

**Comment by liamsuma** [comment]
I ran the program without introducing zoom factor for multiple pdf files and it all generated the same output for a single bank statement

**Comment by JorjMcKie** [comment]
So what you are doing is
1. convert the page to an image, and then
2. OCR that image back to text
3. interpret / read the back-converted text

My recommendation would be:
Directly read the text of the PDF page via ``page.getText(option)`` and get rid of 2 of the previous steps!

``option`` is a string which controls the output type. You can choose among things like plain text, single words with position info, HTML or XML string output, complete page content in Python dict format and what not.

**Comment by JorjMcKie** [comment]
More specifically, you could use ``option = "blocks"``. Then you get a list of items like ``(x0, y0, x1, y1, "line1\nline2\nline3...", ...)``, whe the first 4 are floats specifying the rectangle within which those concatenated lines are positioned. So the following code snippet delivers all the text lines, sorted ascending by vertical coordinate:

```python
blocks = page.getText("blocks")
blocks.sort(key=lambda block: block[3])  # sort by 'y1' values

for block in blocks:
    print(block[4])  # print the lines of this block
```

**Comment by liamsuma** [comment]
A very powerful and interesting solution.. I will look more into this and it might be a great additional to the current project. Without going through Pytesseract, the entire process gets done in a cleaner fashion. Great as always.

**Comment by JorjMcKie** [comment]
Yes, indeed much simpler ... **_if_** the PDF text really is not contained in an embedded image.

If this is true, then this solution is also very much faster by at least one order of magnitude.
