### ISSUE TITLE
Inserting text in wrong place over rotated pages

### ISSUE THREAD

**Issue by ricardonr** [pymupdf/PyMuPDF#536]
## Describe the bug:
Text is showing in wrong place and size when inserted over rotated pages using insertText() function.

## To Reproduce
[document.pdf](https://github.com/pymupdf/PyMuPDF/files/4820063/document.pdf)

```
doc = fitz.open("document.pdf")
doc_page = doc.loadPage(0)  #rotation = 270
doc_page.insertText((100,100) ,'test_100', fontsize=50)
doc_page.insertText((200,200) ,'test_200', fontsize=50)
doc_page.insertText((300,300) ,'test_300', fontsize=50)
doc.save('document_output.pdf')
``` 

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/10520828/85417103-a3945680-b545-11ea-93ed-147a43096310.png)

## My configuration: 
Win10, python 3.8.2_64, pyMuPdf 1.17.1

3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] 
 win32

PyMuPDF 1.17.1: Python bindings for the MuPDF 1.17.0 library.
Version date: 2020-06-13 07:54:31.
Built for Python 3.8 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
There are a couple of issues:
* The page contains non-encapsuled geometry modification:
```python
>>> import fitz
>>> doc=fitz.open("document.pdf")
>>> page=doc[0]
>>> print(page.readContents().decode())
0.18000 0 0 0.18000 0 0 cm  % <= non-encapsuled minimization factor
q
3308 0 0 4677 0 0 cm
/Im1 Do
Q

>>> 
```
Heal this with ``page._wrapContents()`` before inserting stuff, and you will get this as intented:
![grafik](https://user-images.githubusercontent.com/8290722/85431268-4ac9bb80-b54f-11ea-820c-397575fcc11c.png)

**Sidenote:**
PyMuPDF **_always_** inserts stuff as if the page were not rotated. If you want something else, e.g. follow the page rotation as I would suspect you do, you must adapt your calculation using the new matrices ``page.rotationMatrix``, ``page.derotationMatrix`` respectively. So, in your example, if you do this:
```python
page = doc[0]  # rotation = 270
page._wrapContents()
p1 = fitz.Point(100, 100)
p2 = fitz.Point(200, 200)
p3 = fitz.Point(300, 300)
page.insertText(
    p1 * page.derotationMatrix, "test_100", fontsize=50, rotate=page.rotation
)
page.insertText(
    p2 * page.derotationMatrix, "test_200", fontsize=50, rotate=page.rotation
)
page.insertText(
    p3 * page.derotationMatrix, "test_300", fontsize=50, rotate=page.rotation
)
doc.save(outfile)
```
You will get this output:
![grafik](https://user-images.githubusercontent.com/8290722/85431826-1276ad00-b550-11ea-93f2-8734c1a5eee8.png)

**Comment by ricardonr** [comment]
It works! Thank you very much. I hope I can contribute to this great project in the future.

**Comment by suparnaj3** [comment]
Hi @JorjMcKie,

I came across a similar issue while doing redaction. When there is a rotation in a page, the redacted area is not coming as desired.

I tried multiplying the rect with derotationMatrix, still couldn't fix it. I couldn't find rotate option in addRedactAnnot method.

```
page.addRdactAnnot(rect*page.derotationMatrix)
```
Is there any workaround to fix this issue?

Thanks,

Suparna J

**Comment by JorjMcKie** [comment]
Looks good and working fine for me:
Here is a rotated page with some text:
![grafik](https://user-images.githubusercontent.com/8290722/135773389-4d456ae8-f23d-4bad-8a4b-88316a210382.png)
Now:
```python
import fitz
doc=fitz.open("x.pdf")
page=doc[0]
rl=page.search_for("hallo text")
from pprint import pprint
pprint(rl)  # shows *unrotated* coordinates:
[Rect(100.0, 88.17500305175781, 149.510986328125, 103.28900146484375)]
page.add_redact_annot(rl[0])
'Redact' annotation on page 0 of x.pdf
doc.ez_save("y.pdf")
```
Gives this:
![grafik](https://user-images.githubusercontent.com/8290722/135773419-b2bdd85b-4858-4b13-a384-7eb25f126c1f.png)
**_Applying_** the redaction also works:
```python
doc=fitz.open("y.pdf")
page=doc[0]
page.apply_redactions()
True
doc.ez_save("z.pdf")
```
The page is emptied as requested.

**Comment by suparnaj3** [comment]
Yeah, it is working.

I was using `page.MediaBox` to find the width and height for creating the annotRect.

Moved to `page.rect`, and redaction is working perfectly.

Thank you very much.
