### ISSUE TITLE
Python script stops while iterating over widgets  for multi-page pdf. Also update for widgets does not work. 

### ISSUE THREAD

**Issue by mgoliyad** [pymupdf/PyMuPDF#538]
I am probably doing something wrong. I have 12 page pdf with many fields which I need to fill. 

If I have this code then after processing first page with widgets script terminates.
              for pageNum, page in enumerate(doc):
                    for w in page.widgets():
                        print(w.field_type_string, w.field_type, w.field_name)
                        print(w.rect)
                        print('val: ', w.field_value)

If I try to update 👍 

                    for f in f_data.itertuples():
                        try:
                            d = data.loc[data['id'].str.contains(f.id, case=False,regex=False)].reset_index(drop=True)
                        except:
                            continue
                        if len(d) > 0:
                            print(d.loc[0,'value'])
                                annot.value = d.loc[0,'value']
                                annot.update()
                   doc.save(new_file)

No changes are being saved to new_file.

I am using PyMuPDF 17.1. on Windows with Py 3.7
Please let me know how to fix my code to be able to iterate over many widgets and save updates to new file.

**Comment by JorjMcKie** [comment]
Loop through all fields of all pages like this:
```python
for page in doc:
    for w in page.widgets():
        print("Page %i, field '%s' = '%s'" % (page.number, w.field_name, w.field_value))
```
Example output:
```
Page 0, field 'cb.0' = ''
Page 0, field 't_tt.0' = ''
Page 0, field 't_tt.1' = ''
Page 0, field 't.5' = ''
Page 0, field 'cb.5a' = ''
Page 0, field 't.6' = ''
Page 0, field 't.7' = ''
...
```
Updating should work like this. Note that I did not bother about field type, so the underlying MuPDF library took a few decisions:
```python
for page in doc:
    for w in page.widgets():
        w.field_value = "new text"
        w.update()
doc.save("changed.pdf")
```
If I repeat the above field listing for the changed pdf, I am getting:
```
Page 0, field 'cb.cb.0' = 'Off'
Page 0, field 't_tt.t_tt.0' = 'new value'
Page 0, field 't_tt.t_tt.1' = 'new value'
Page 0, field 't.t.5' = 'new value'
Page 0, field 'cb.cb.5a' = 'Off'
Page 0, field 't.6.t.6' = 'new value'
Page 0, field 't.t.7' = 'new value'
...
```
and the PDF also shows them:
![grafik](https://user-images.githubusercontent.com/8290722/85618634-0d3c5f80-b62f-11ea-8300-930bdb1de5c8.png)

> What I cannot explain at the moment are the field name changes however - need to check this.

**Comment by mgoliyad** [comment]
Cannot think what's wrong with my setup. I am using Spyder from Anaconda. can this be a problem?

Here is printout from iteration - my doc has 12 pages, page 2 - first page t have widgets:

Page 2, field 'Male' = ''
Page 2, field 'Female' = ''
Page 2, field 'Other specify' = ''

(mg) C:\Users\mgoliyad_admin\OCR>

**Comment by JorjMcKie** [comment]
> I am using Spyder from Anaconda. can this be a problem?

I really do not think so.
Can you share that PDF? or have you other PDFs that do not work in the same way?

**Comment by JorjMcKie** [comment]
There was a bug in v1.17.0 which caused seg faults when iterating over widgets. This was fixed in v1.17.1 - which you told me you have installed.
But just in case you may want to double check.

**Comment by mgoliyad** [comment]
Got it! I have uninstalled 17.0 and installed from scratch 17.2
I am able to update text fields now. Do you know if it's possible to update check box? To add check mark?

**Comment by JorjMcKie** [comment]
> Do you know if it's possible to update check box? To add check mark?

This _should_ work: ``widget.field_value = True``

**Comment by mgoliyad** [comment]
Thanks A LOT!!!
