### ISSUE TITLE
Some links and images are broken in the Wiki

### ISSUE THREAD

**Issue by gabefair** [pymupdf/PyMuPDF#539]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
On this wiki page: https://github.com/pymupdf/PyMuPDF/wiki/GUI-scripts-to-display-a-PDF-using-wxPython-or-Tkinter
The first link goes to a repo that no longer exists. Also there is a broken image link near the bottom of the page.

**Comment by JorjMcKie** [comment]
thanks - links corrected
