### ISSUE TITLE
Write Pixmap resolution to image files

### ISSUE THREAD

**Issue by allefeld** [pymupdf/PyMuPDF#542]
Please provide a way to write the resolution of a `Pixmap` object to image files created from it.

`Pixmap` has a method `setResolution`, albeit with the comment 

> This is just documentary information. In MuPDF, this will not have other implications and will not be written to images created from the pixmap.

I request to change this behavior, so that the resolution is written to image files (which support it). As far as I can tell, this mainly applies to PNG files, i.e. `writeImage(filename, output='png')`, and `writePNG`.

This should also hold for data that is not written to a file, i.e. `getImageData('png')` and `getPNGData`.

This is important because generated images may be automatically included in documents, e.g. via LaTeX or in a Jupyter notebook, and this way the display size of the image can be controlled programmatically.

**Comment by JorjMcKie** [comment]
Image file creation is not done by PyMuPDF itself, but by the underlying C library MuPDF, and I have no way to influence this.
I will add this fact to the comment you quoted.

Please direct your request to MuPDF's issue system https://bugs.ghostscript.com/enter_bug.cgi.
If you want to do that, for best success refer to their own software, resp. utilities and e.g. mention that the output file of ``mutool draw -o page1.png file.pdf 1`` does not contain the resolution values.

**Comment by JorjMcKie** [comment]
Just wanted to add, that you can use Pillow to save images instead of the built in methods ``writePNG`` / ``writeImage``. The ``PIL.Image.save()`` allows setting the dpi tuple.
To create a PIL image from a pixmap use ``img = Image.frombytes(mode, [pix.width, pix.height], pix.samples)``.

**Comment by JorjMcKie** [comment]
PyMuPDF as per today has no dependencies on other Python packages at all (except for the standard built-ins).
However, your request is not the first one of its kind.
I am considering now to integrate PIL/Pillow for writing images - something like ``pix.pillowSave(*args)`` with the full set of ``Image.save`` arguments and an automatic ``from PIL import Image`` happening when this method is used.
Your reaction?

**Comment by allefeld** [comment]
Thanks for the explanation – I had feared this is a shortcoming of MuPDF. I'll create an issue there.

Regarding integrating PIL/Pillow, it sure would be convenient, but actually I agree that PyMuPDF should remain a wrapper of MuPDF and not pull in any other dependencies.

Excellent work btw.!

**Comment by allefeld** [comment]
I hate bugzilla, why can't they host on github like everybody else?! ;)

**Comment by allefeld** [comment]
<https://bugs.ghostscript.com/show_bug.cgi?id=702522>
