### ISSUE TITLE
page.searchFor fails to find all words of sentence!

### ISSUE THREAD

**Issue by IbrahimG99** [pymupdf/PyMuPDF#543]
## Describe the bug
I'm using PyMuPdf for a while now and today while doing test cases with different pdf's I come to a cross something interesting 

## To Reproduce
The part where is search method looks like this

`text_instances = page.searchFor(arrayToSearch["sentence"])`

On searchFor I send sentences from a pile of the array which I need to search on pdf and when its found to add annotation but in some case, it fails to find the complete sentence and returns me incorrect co-ordinates 

searchFor returns

```
[Rect(73.7998046875, 408.6886291503906, 149.90048217773438, 421.5201110839844),
 Rect(59.45964813232422, 419.12872314453125, 95.0076675415039, 431.4079284667969),
 Rect(97.38618469238281, 419.12872314453125, 123.79291534423828, 431.4079284667969),
 Rect(126.17143249511719, 419.12872314453125, 150.9746856689453, 431.4079284667969),
 Rect(153.35321044921875, 419.12872314453125, 161.76364135742188, 431.4079284667969),
 Rect(164.1421661376953, 419.12872314453125, 183.37557983398438, 431.4079284667969),
 Rect(185.7541046142578, 419.12872314453125, 198.752197265625, 431.4079284667969),
 Rect(201.13072204589844, 419.12872314453125, 230.04942321777344, 431.4079284667969),
 Rect(232.42794799804688, 419.12872314453125, 281.7758483886719, 431.4079284667969),
 Rect(284.15435791015625, 419.12872314453125, 293.6408386230469, 431.24071607969),
 Rect(296.0193481445P3125, 419.12872314453125, 309.560250468075,431.4079284667969),
 Rect(311.9390563964844, 419.12872314453125, 354.1900939941406, 431.4079284667969),
 Rect(356.5087585449219, 419.12872314453125, 387.9532775878906, 431.4079284667969),
 Rect(390.331787109375, 419.12872314453125, 403.3897705078125, 431.4079284667969),
 Rect(405.828125, 419.12872314453125, 441.9183349609375, 431.4079284667969),
 Rect(59.45964813232422, 429.748291015625, 92.99181365966797, 442.0274963378906)]
```
which is 16 in total and supposed to return 24

## Screenshot
Here is a screenshot from generated pdf with annotation with co-ordinates given from **searchFor**

![image](https://user-images.githubusercontent.com/34714009/86099544-e7440e80-bab7-11ea-98a7-9c952ee2869f.png)

![image](https://user-images.githubusercontent.com/34714009/86100273-e95a9d00-bab8-11ea-9f2d-c8088fea2d8d.png)

## Expected behavior
On both screenshots, the searchFor should find a sentence till the end and return co-ordinates for annotation.

## Your configuration (mandatory)
 - **Operating system**: Windows 10 (64-bit)
 - **Python version**: Python 2.7 (32 bit)
 - **PyMuPDF version**: 1.16.18
- **installation method**: wheel.

## Additional context 
I tried adding hit_max=100 and it works but I'm not sure if it is the correct to fix.

**Comment by JorjMcKie** [comment]
> I tried adding hit_max=100 and it works but I'm not sure if it is the correct to fix.

Yes it is! Please consult the documentation.

As per the wrong coordinates, please open a separate issue after upgrading to the current version.

**Comment by JorjMcKie** [comment]
As you are obviously new to using pymupdf - welcome!
Here are some additional comments:
* the ``searchFor`` method is a wrapper for a function in the C base library MuPDF. So it reflects what this guy does ...
* use one of the many ``page.getText(option)`` variants if you want to build your own search functions. Depending on "option", you can retrieve single words, blocks of text lines or rather complex dictionaries with details on text position, font and color, images and what not, down to the level of each single character.

**Comment by IbrahimG99** [comment]
Thank you for the additional comments and I love PyMuPDF it is very useful.
#use one of the many page.getText(option) variants if you want to build your own search functions. Depending on "option",
I tried may of getText options and best suitable for my requirements was getText('text')

Also as I mentioned adding **hit_max=100** resolved my problem, as far as I know, hit_max=16 is the default value because it always stopped on number 16 and didn't return more than 16 values of rectangles.

**Comment by IbrahimG99** [comment]
Thank you for the additional comments and I love PyMuPDF it is very useful.
> * use one of the many `page.getText(option)` variants if you want to build your own search functions. Depending on "option", 
I tried may of getText options and best suitable for my requirements was getText('text')

Also as I mentioned adding hit_max=100 resolved my problem, as far as I know, hit_max=16 is the default value because it always stopped on number 16 and didn't return more than 16 values of rectangles.

**Comment by JorjMcKie** [comment]
> best suitable for my requirements was getText('text')

That's fine. Note however, that this basic variant extracts text as it is coded (in a PDF). The output may not be suitable for reading, because in PDFs it is possible to store text pieces in arbitrary sequence.

> hit_max=16 is the default value

The C function allocates an array of this size and then goes searching. Other approaches are easily imaginable of course, but this is what it is ...

**Comment by IbrahimG99** [comment]
Thank you so much for your reply, 
Now I have a more clear idea of what is going on, also for getText('text') I will consider trying other options.
