### ISSUE TITLE
Cannot set checkbox value to Yes

### ISSUE THREAD

**Issue by papafelice** [pymupdf/PyMuPDF#545]
## Description of the bug
Generating or updating a checkbox widget always sets the value field to Off

## Steps To Reproduce
Code snippet:

    import fitz         
    doc = fitz.open()  
    doc.insertPage(0)
    page = doc[0]                         
    
    rect = fitz.Rect(10,  10, 15, 15)
    
    widget = fitz.Widget()
    widget.rect = rect
    widget.field_type = fitz.PDF_WIDGET_TYPE_CHECKBOX
    widget.field_name = "Check1"
    widget.field_value = "Yes"
    widget.text_font = "ZaDb"
    widget.text_fontsize = 0
    page.addWidget(widget)
    doc.save("check.pdf")
    doc.close() 

Open the file with a PDF viewer of look at the generated PDF code, the /V tag is allways set to Off. Manually changing it to Yes, checks the box, however, the check mark is displayed as "3", i.e not with the Zapf Dingbats font.

## Expected behavior
This should create a checked checkbox with the field value set to Yes

## Configuration
 OS: Suse Tumblewheed Linux 5.7.5-1-default 64bit
 Python 3.8.3 64bit
 PyMuPDF version 1.17.2, installed with pip

**Comment by JorjMcKie** [comment]
try setting ``widget.field_value = True``.

**Comment by papafelice** [comment]
Interesting: Indeed, this will set it to checked even though it will read back as Yes and the mark is initially not visible in a viewer. But blindly unchecking and rechecking finally displays the mark.

**Comment by JorjMcKie** [comment]
I see.
What I do know about MuPDF: it handles **_all_** value setting like text. It is PyMuPDF own code, which steps in in case of buttons / checkboxes and does something different.

Maybe I should also translate the value **_read_** from the PDF and return ``True`` / ``False`` instead of strings "Yes" / "No".

**Comment by papafelice** [comment]
Makes sense to me, since the PDF spec states that the on mode doesn't have to named Yes, but just needs to be defined in the /AP, so it could be anything, 1, on, ...
This would also simplify the python code in an application that toggles the state.

**Comment by JorjMcKie** [comment]
Your recommendation is noted.
