### ISSUE TITLE
Extract all the pages as images 

### ISSUE THREAD

**Issue by RayFromUiS** [pymupdf/PyMuPDF#547]
I have run pympudf on windows10 and macos, with python 3.6  aiming to extract images embeded with files.  The pdf file is  a OCR file scanned from a hard copy. Text is clearly selectedable and editable and also can be extract as pure text data. while i try to extract the images embeded within the pdf file, all the pages are returned from the running code as images.
`doc = fitz.open(filename)
print(len(doc))  ##return pages

for i in range(len(doc)):
    for img in doc.getPageImageList(i): 
        xref = img[0]
        pix = fitz.Pixmap(doc,xref)
        if pix.n < 5:
            pix.writePNG(f'p{i}-{xref}.png')
        else:
            pix1 = fitz.Pixmap(doc,xref)
            pix1.writePNG(f'p{i}-{xref}.png')
            pix = None
        pix = None
`
totaly, there are 90 png files,basically, those are all the pages.
Maybe i doing the wrong way to extract the images, or these pages all has xref, has anyone run into same problem and figured out.
Finally, thanks for such great toolkit.

**Comment by JorjMcKie** [comment]
I didn't understand what you intend to do:

1. create PNG images from each page?
2.  extract the text of each page?
3. extract something else?

For (1.) do this:
```python
for page in doc:
    pix = page.getPixmap()
    pix.writeImage("page-%i.png" % page.number)
```

For (2.) do this:
```python
for page in doc:
    print(page.getText())
    print(chr(12))  # page break
```

Because your PDF is a scan, each page has only 1 image! So you need not do anything else but making the page pixmap.
If you however - for some reason - want to extract the original page scan image (which usually is a JPEG), do this:

```python
for page in doc:
    xref = doc.getPageImageList(page.number)[0]  # there is only 1 image per page!
    pix = fitz.Pixmap(doc, xref)  # should deliver the original image dimension of the scan
    pix.writeImage(...)  # etc.
    # or, alternatively extract the image like this. Does not always work, depends on the scanner:
    img = doc.extractImage(xref)  # this is a dictionary with image meta info and the binary image
    # you can use img["ext"] and img["image"] to then save the image in its original format
```

**Comment by JorjMcKie** [comment]
Question answered?

**Comment by JorjMcKie** [comment]
Closing this for lack of feedback.
Please feel free to re-open or open a new issue with more questions.
