### ISSUE TITLE
API document missing the value for kind = LINK_NAMED

### ISSUE THREAD

**Issue by mozbugbox** [pymupdf/PyMuPDF#548]
The enum for `LINK_NAMED` was missing from the `dest.kind`:

https://pymupdf.readthedocs.io/en/latest/vars/#linkdest-kinds

It seems that EPUB documents use `LINK_NAMED` in their ToC.

**Comment by JorjMcKie** [comment]
Thanks for spotting this. Will be added with the next docu update.

**Comment by JorjMcKie** [comment]
documentation improved with version just uploaded
