### ISSUE TITLE
TextWriter.fillTextBox: continuing with different font

### ISSUE THREAD

**Issue by jotaf98** [pymupdf/PyMuPDF#549]
**Is your feature request related to a problem? Please describe.**
I'd like to use `TextWriter.fillTextBox` for its word-wrapping and aligning capabilities, but with different fonts (e.g. a bold word in the middle of the text).

**Describe the solution you'd like**
Probably the simplest would be to supply a start position to `TextWriter.fillTextBox` to allow chaining calls with different fonts, just like `TextWriter.append` supports a `pos` argument for the same reason.

**Describe alternatives you've considered**
Supplying multiple fonts to this function might work too, but it's not as flexible (e.g. for mixing graphics with text).

**Comment by JorjMcKie** [comment]
When developing this, I once had an indent for the first line start with the rectangle.
Can't recall why I dropped it again.
Let me see ...

**Comment by jotaf98** [comment]
Thanks! That would be it. It seems like an easy way in could be by adding another line after 3516 of `utils.py`:

```
if pos == 0: start.x += initial_indent
```

**Comment by JorjMcKie** [comment]
Yeah, I think I have it. If you look at [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/textwriter/textwriter-textbox.py) demo script, I can now do this:
```python

writer.fillTextbox(  # fill in above text
    fill_rect,  # keep text inside this
    text,  # the text
    align=fitz.TEXT_ALIGN_JUSTIFY,  # alignment
    warn=True,  # keep going if too much text
    fontsize=fsize,
    font=font,
)
lp = writer.lastPoint  # end point of last text box
font = fitz.Font("tibi")  # use some other font
writer.fillTextbox(  # fill in same text once more
    fill_rect,  # rectangle heigh enough to hold 2 copies of text
    text,  # the text
    pos=lp + (5, 0),  # new parameter: lastPoint and a little room
    align=fitz.TEXT_ALIGN_LEFT,  # different alignment
    warn=True,  # keep going if too much text
    fontsize=fsize,
    font=font,
)
```
Gives me this:
![grafik](https://user-images.githubusercontent.com/8290722/86544217-021ce580-bef3-11ea-9381-ff76851556c9.png)

I could also have chosen a different TextWriter (with a different color) but re-using the same fill_rect.
So it would now e.g. be possible to fill a full page rectangle with text of arbitrary colors and fonts ...

Thanks for this suggestion!

**Comment by jotaf98** [comment]
That's awesome, thanks!

I really like that this also lets us intersperse graphics with text, e.g. having a custom colored symbol within a paragraph. Lots of possibilities here!

**Comment by jotaf98** [comment]
BTW what repo/branch should I use if I want to use this feature before a release?

**Comment by JorjMcKie** [comment]
If you have a Windows system, I can send you a wheel right away. Likewise for Ubuntu 2.7, 3.6, 3.8. I can create those wheels locally.
Otherweise I'll let you know once Travis wheel generation is done.

**Comment by JorjMcKie** [comment]
You can now download a Linux version from here: https://github.com/pymupdf/PyMuPDF-wheels/tree/linux.
This repo also has OSX versions in another branch.

**Comment by jotaf98** [comment]
Thanks! I'm on Windows right now, so that would work -- although if it's more convenient to wait for Travis, that would also be OK, as it's not urgent (I can do with more basic rendering for a bit more :) )

**Comment by JorjMcKie** [comment]
That branch was filled by Travis.
Please tell e yout Py version on Windows plus bitness and you'll have your wheel rightaway.

**Comment by jotaf98** [comment]
It's Python 3.7.3, 64 bits. Thanks!

**Comment by JorjMcKie** [comment]
In the meantime, v1.17.3 is published and can be downloaded from PyPI 😎

**Comment by jotaf98** [comment]
That's even better! 😀
