### ISSUE TITLE
Conversion of .docx and .pptx to PyMuPDF object

### ISSUE THREAD

**Issue by imayachita** [pymupdf/PyMuPDF#551]
Hi all,
This might not be directly related to PyMuPDF itself, but I wonder if there is any other library or any way to convert .docx and .pptx files into PyMuPDF object (instead of saving them out to .pdf files) on Linux?

Thanks!

**Comment by JorjMcKie** [comment]
You can convert these files to PDF via MS Office or LibreOffice just as well on Windows using the respective "export" functions. There is no need to use additional converter packages for this.

If you were asking, whether office files can be opened as **_(Py-) MuPDF documents_**, then the answer is No. While MuPDF would allow to develop and add your own document types, I currently have no plans in that direction.

**Comment by imayachita** [comment]
Thanks @JorjMcKie!
