### ISSUE TITLE
What is the proper way to update the widget list in a page of the current document?

### ISSUE THREAD

**Issue by papafelice** [pymupdf/PyMuPDF#553]
When adding a new widget, it is not shown when iterating through all widgets. 

    import fitz         
    doc = fitz.open()  
    doc.insertPage(0)
    page = doc[0]                         
    rect = fitz.Rect(10, 10, 45, 20)

    widget = fitz.Widget()
    widget.rect = rect
    widget.field_type = fitz.PDF_WIDGET_TYPE_TEXT
    widget.field_name = "Text1"
    widget.field_value = "My Text"
    page.addWidget(widget)
    print("Current Page Widgets:")
    for field in page.widgets():
        print( field.xref)
    doc.save("text.pdf")
    doc.close()
    
    doc = fitz.open("text.pdf")  
    page = doc[0]                         
    print("Reloaded Page Widgets:")
    for field in page.widgets():
        print( field.xref)
    doc.close()

**Comment by JorjMcKie** [comment]
In your code snippet, `field` is a `Widget` object.
Just set its properties and then do `field.update()`.

**Comment by JorjMcKie** [comment]
Sorry, only belatedly saw your real problem:

There is a minor hickup if you want to access annotation or widgets just created on a page: You must **_reload_** the page to ensure all update activity has been saved to the page's definition. Do this after adding / updating annotations and fields before you again access them without having been on a different page: `page = doc.reload_page(page)`.

There is no such problem if you save and then re-open the document or leave the page and later re-access it.

**Comment by papafelice** [comment]
Ahh, that is the magic word: reload_page. I was looking for something like sync or update in the docs (bwt: very good documentation).

**Comment by JorjMcKie** [comment]
> bwt: very good documentation

😎Thanks for the compliments, but it obviously wasn't good enough to prevent your effort finding the answer ...
Any suggestion for locations where this hint would be beneficial?

**Comment by papafelice** [comment]
I would put a hint on page 140, 6.12.1 Modifying pages and maybe on page 147 at addWidget(widget) 

Also, on page 210, choice values:
"When updating the widget, this sequence will always the complete new list of values must be specified"
This sentence is somehow scrambled, if you about to update the docs

**Comment by JorjMcKie** [comment]
Thanks! Input much appreciated, I will take it to the next docu version.
