### ISSUE TITLE
save() API of "Document" is not giving error and file is also not saved

### ISSUE THREAD

**Issue by RajeshSeervi** [pymupdf/PyMuPDF#554]
Hi,

I was checking example program to create a PDF.
But, program is not creating file and no error is returned.
Seems like something is missing in my system or file is created on some other path (I searched and not found on my system).

Please help.

System : Windows 10

program : 

```python
import fitz
import calendar
import sys
assert len(sys.argv) == 2, "need start year as the one and only parameter"

startyear = sys.argv[1]
assert startyear.isdigit(), "year must be positive numeric"
startyear = int(startyear)
assert startyear > 0, "year must be positive numeric"

doc = fitz.open()
cal = calendar.LocaleTextCalendar(locale = "en")   # choose your locale
w, h = fitz.PaperSize("a4-l")                      # get sizes for A4 landscape paper

txt = cal.formatyear(startyear, m = 4)
doc.insertPage(-1, txt, fontsize = 12, fontname = "Courier", width = w, height = h)

txt = cal.formatyear(startyear + 1, m = 4)
doc.insertPage(-1, txt, fontsize = 12, fontname = "Courier", width = w, height = h)

txt = cal.formatyear(startyear + 2, m = 4)
doc.insertPage(-1, txt, fontsize = 12, fontname = "Courier", width = w, height = h)

doc.save("ZCalender.pdf",garbage = 4, deflate = True)
```

**Comment by JorjMcKie** [comment]
Cannot reproduce: script runs without issue and produces the PDF.
You may have saved the file in some unexpected folder - try adding the script folder to the output filename to be sure.

**Comment by RajeshSeervi** [comment]
Hi,
I tried by putting complete path also, but no luck.
To my surprise, there is no error also.

**Comment by JorjMcKie** [comment]
>  To my surprise, there is no error also.

I cannot believe this: writing the file is after all done by the base library MuPDF, and they wouldn't silently swallow an error.
How do you invoke the script? Inside your editor - like VS Code?
Or in a command window?
If you use VS Code go searching the file in your home directory.
Use outfile = os.path.abspath(outfile) und print that guy to see where it lands.
Otherwise I need your configuration: please do a ``print(fitz.__doc__)``.

**Comment by RajeshSeervi** [comment]
Hi,

I am invoking script from command prompt.
I checked `outfile = os.path.abspath("")` also and path is same where I am running script.

please find below output of `print(fitz.__doc__)` 

>PyMuPDF 1.17.2: Python bindings for the MuPDF 1.17.0 library.
>Version date: 2020-06-20 07:00:22.
>Built for Python 3.8 on win32 (32-bit).

**Comment by JorjMcKie** [comment]
Have you tried to find the file anywhere?
Have you ever used PyMuPDF and successfully created a PDF?
Use IDLE and do this
```python
>>> import fitz
>>> doc=fitz.open()
>>> page=doc.newPage()
>>> doc.save("new.pdf")
>>> 
```
The file `new.pdf` must be found in the folder from where you executed IDLE.
If not, then the hell knows what is wrong in your system ...

**Comment by RajeshSeervi** [comment]
Hi,

Checked given script also, but same result, no file produced.
Really don't know what is wrong.
Tried using admin role also and searched for file also.

Neway, thanks for help.

**Comment by RajeshSeervi** [comment]
Hi,
Further update..
I checked by removing extension from file name and now file is created.
After file creation, I changed extention of output file, i.e. from `new` to `new.pdf` and it is required pdf file.
```python
import fitz
doc=fitz.open()
page=doc.newPage()
doc.save("new1")
```

>So, we have workaround for this problem : remove extension `pdf` if such issue comes. 
> It is working file without extension or with `csv` also.

>Seems like some issue when `pdf` file is created by on Windows 10
>Searched for similar issue on net, but no solution identified.

Thanks

**Comment by JorjMcKie** [comment]
Extremely weird! So you are saying, that saving the file does work provided you do not use extension".pdf"?!

So in your Python script, if you do
```python
doc.save("new")
os.rename("new", "new.pdf")
```
you are fine?

Can you create PDF files with other programs, like Office output from a Word document?

**Comment by JorjMcKie** [comment]
Is this a security issue?
If you download MuPDF for Windows from [here](https://mupdf.com/downloads/index.html) and then execute:
``mutool draw -o new.pdf some.jpg``
Does it create the PDF?
This utility converts supported files (here a JPEG image) to PDF (or other supported document types).

**Comment by RajeshSeervi** [comment]
>Extremely weird! So you are saying, that saving the file does work provided you do not use extension".pdf"?!

Yes, it is working fine for `csv` ext as well.

----------
```python
doc.save("new")
os.rename("new", "new.pdf")
```
Above script used to create file `new`, but not `new.pdf`, i.e. unable to rename and no error.

--------------
>Can you create PDF files with other programs, like Office output from a Word document?

Yes, able to create pdf from Word document using Microsoft Word.

---------------------
>`mutool draw -o new.pdf some.jpg`
>Does it create the PDF?

Yes, it is creating pdf.

**Comment by JorjMcKie** [comment]
weird, weird
How about ``python script1.py`` creates "new".

Then a second script2 doing the os.rename is run `Python script2.py`.
Works?

**Comment by JorjMcKie** [comment]
Please try this to see any potentiall hidden error messages:

```python
doc.save("new.pdf")
print(fitz.TOOLS.mupdf_warnings())
```

**Comment by RajeshSeervi** [comment]
>How about python script1.py creates "new".
>
>Then a second script2 doing the os.rename is run Python script2.py.
>Works?

```python
import os
os.rename("new", "new.pdf")
```
This is also not able to change file name, and no error is shown.
But it is able to change to `csv`.

---------------------------

```python
doc.save("new.pdf")
print(fitz.TOOLS.mupdf_warnings())
```
This is not showing any message.

----------------------

As `os` package is also not able to change file to `pdf`, so there can be something with python ?

**Comment by JorjMcKie** [comment]
> As os package is also not able to change file to pdf, so there can be something with python ?

Yes, it definitely shows it has nothing to do with PyMuPDF. Do you have other Python versions as well to try out?
Or maybe a completely fresh new installation.
And maybe you find a similar problem on one of the sites like StackOverflow.

Just another test came into my mind: Read some PDF as binary file (not with PyMuPDF), then save it under a new name:
```python
inbytes = open("input.pdf", "rb").read()  # content as memory
outfile = open("output.pdf", "wb")
outfile.write(inbytes)
outfile.close()
```
If this doesn't work either, you can probably submit a Python bug.

**Comment by RajeshSeervi** [comment]
```python
inbytes = open("input.pdf", "rb").read()  # content as memory
outfile = open("output.pdf", "wb")
outfile.write(inbytes)
outfile.close()
```

This is also no able to write `pdf` file.

I will try to reinstall or try with some other version of python.

Thanks.

**Comment by JorjMcKie** [comment]
Ok. We have at least achieved an understanding where the problem is, and it's not PyMuPDF.
