### ISSUE TITLE
An error occurred when a page in the middle of the same PDF file was converted to a picture

### ISSUE THREAD

**Issue by firstelfin** [pymupdf/PyMuPDF#557]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When I convert a PDF file to an image, I encounter a PDF file. The fourth page of the PDF file can't be converted. The python program ends and exits directly. Try doesn't work either!

------------------------------------------------------------------------------------------------------------------------
error：
```python
mupdf: cmsCreateTransform(ICCBased(RGB,sRGB IEC61966-2.1),p���) failed
mupdf: cannot find color converter
mupdf: recursion in colorspace definition

Process finished with exit code -1073741819 (0xC0000005)
```
-----------------------------------------------------------------------------------------------------------------------
## code
```python
    pdfDoc = fitz.open(pdfPath)
    for pg in range(pdfDoc.pageCount):
        page = pdfDoc[pg]
        rotate = int(0)
        zoom_x = 2 
        zoom_y = 2
        mat = fitz.Matrix(zoom_x, zoom_y).preRotate(rotate)
        try:
            pix = page.getPixmap(matrix=mat, alpha=False)
        except Exception as e:
            print(e)
            pix = page.getPixmap(matrix=mat, colorspace="rgb", alpha=False)
```

**Comment by JorjMcKie** [comment]
This is probably a known error: MuPDF cannot handle IXX colorspaces in some situations and doesn't properly handle the exception either.
Their is a circumvention which you should try: ``fitz.TOOLS.set_icc(False)`` before making pixmaps.
Pls also refer to #369 and #397

**Comment by JorjMcKie** [comment]
Presuming you have found a circumvention ...
