### ISSUE TITLE
How to make addRedactAnnot support fontfile?

### ISSUE THREAD

**Issue by malizheng** [pymupdf/PyMuPDF#558]
Thank you very much for your contribution.
After addRedactAnnot uses the default font, there is a problem with the layout. How to make addRedactAnnot support fontfile？

**Comment by JorjMcKie** [comment]
I think you mean to use the same font as the redacted text.
That's not possible now. Let me check if I can dig out a solution.

**Comment by malizheng** [comment]
Thank you. The following code can meet my needs.
`insertFont(fontname="song", fontfile=os.path.join('trans/static/fonts/SimSun.ttf'))`

**Comment by JorjMcKie** [comment]
Ha! Wait, I was wrong  and in more than one way:

* when you talk about a "layout problem" this **_may_** referred to issue #519 - unfortunately the page cleaning process MuPDF invokes for applying redactions sometimes produces layout disorder.
* you **_can_** re-use an existing font of the page - so e.g. the font of the replaced text, too. To do that you must
    - find out the **_reference name_** of the desired font; this is item[7] of an entry in the list ``doc.getPageFontList(page.number)``.
    - when adding the redaction, specify ``page.addRedactAnnot(rect, text="blah", fontname=refname, ...)``.

Ah, I just saw you adding a post: yes, that should work too!

**Comment by JorjMcKie** [comment]
I will update the documentation accordingly.
Thanks for submitting this!

**Comment by malizheng** [comment]
Hello, I made a mistake. insertFont seems to only work for insertTextbox.
It has no effect on apply_redactions, reporting the error below.
`page.insertFont(fontname="ceshi", fontfile="font.ttf")
page.addRedactAnnot(r,res, fontname="ceshi",fontsize=fonts, align=text_pos,fill=(1, 1, 1))
page.apply_redactions()  
`
`Traceback (most recent call last):
  File "ts.py", line 82, in <module>
    cur_page.apply_redactions()    
  File "/python3.7/site-packages/fitz/utils.py", line 3272, in apply_redactions
    align=redact["align"],
  File "/python3.7/site-packages/fitz/utils.py", line 2888, in insertTextbox
    fontname=fname, fontfile=fontfile, encoding=encoding, set_simple=set_simple
  File "/python3.7/site-packages/fitz/fitz.py", line 4355, in insertFont
    wmode, serif, encoding, CJK_number)
  File "/python3.7/site-packages/fitz/fitz.py", line 4372, in _insertFont
    return _fitz.Page__insertFont(self, fontname, bfname, fontfile, fontbuffer, set_simple, idx, wmode, serif, encoding, ordering)
RuntimeError: need one of fontfile, fontbuffer`

**Comment by JorjMcKie** [comment]
It's not **_your_** mistake 🙄!
There seems to be a bug in `insertFont `...

**Comment by JorjMcKie** [comment]
Sorry about the confusion, but **_this is the current situation:_**

* Currently, only fonts can be used which already exist for the page (i.e. occur in `doc.getPageFontList()`), or are one of the PDF builtin fonts (CJK, Base-14)
* Fonts inserted via `page.insertFont`, for which so far no text exists, will be deleted from the page during execution of `page.apply_redactions()`, but before the insertion of the replacement text happens. So method `page.insertTextBox` will again not find the previously inserted font and consequently complain about missing fontfile information as you observed. Builtin and CJK fonts are no problem, because they do not need a fontfile.

`Page.insertFont` itself **_has no bug!_** I need to find a way to prevent this font removal (which is part of MuPDF's code when applying redactions).

**Comment by JorjMcKie** [comment]
As a temporary solution, you might do this to circumvent the effect:

Before you use a new font for a redaction annotation, insert some hidden text on the page with this font - just anywhere. After this, the font exists and is used, and therefore will not be cleaned away as I explained in previous post:

```python
page.insertText(
    (20,20),  # just somewhere on the page
    " ", # just anything - it will be invisible
    fontname="ceshi",
    fontfile="some.ttf",
    render_mode=2,  # this makes text invisible!
    ...)
# now you can add and apply redactions using fontname "ceshi"
page.addRedactAnnot(..., fontname="ceshi")  # no fontfile necessary / possible
```
I tried it out - it works! The only hickup as of today: there will be no **_vertical_** alignment. Horizontal alignment will continue to work.

**Comment by S0UL4** [comment]
Hi, Thanks for the work around you provided, is there any way to add fontbuffer in the work around you provided ? 
`page.insertText(
    (20,20),  # just somewhere on the page
    " ", # just anything - it will be invisible
    fontname="ceshi",
    fontfile="some.ttf",
    render_mode=3,  # 3 makes text invisible!
    ...)
# now you can add and apply redactions using fontname "ceshi"
page.addRedactAnnot(..., fontname="ceshi")  # no fontfile necessary / possible`
