### ISSUE TITLE
Documentation update: Annot.getPixmap note

### ISSUE THREAD

**Issue by cipri-tom** [pymupdf/PyMuPDF#560]
Hi,

Thank you for this great binding. I've just started dipping my toes in using the library and I'm truly impressed by its power.

I've noticed a small suspense in the documentation of [`Annot.getPixmap`](https://pymupdf.readthedocs.io/en/latest/annot.html#Annot.getPixmap):

> **Note:** If the annotation has just been created or modified

And that's it. So, what happens if it has just been created or modified ? Are there some limitations ? I supposed we need to call `.update()` to ensure that the modifications are displayed in the pixmap.

Many thanks !

**Comment by JorjMcKie** [comment]
First of all, thanks for the compliments, @cipri-tom !
And then thanks for this docu gap, too.
The sentence should be this:
**_If the annotation has just been created or modified, first reload the page via_** ``page = doc.reload_page(page)``

**The background:** I am adding features to MuPDF's own annotation handling. Hence it may happen, that not all changes have found their way yet to what MuPDF knows about the page's appearance. This may e.g. result in incomplete pixmaps of the page or an annotation. The instruction above does the equivalent of setting the page to `None` and then re-assigning it (just faster and without invalidating currently existing page child objects like annots, widgets, links).

**Comment by cipri-tom** [comment]
Hi @JorjMcKie 

Thanks a lot for the quick answer and the background explanation. Luckily this hasn't affected me, but I'll keep in mind if I need it after the modification.

A small curiosity would be whether `annot.update()` would also do this, or `reload_page()` is still needed ?

Thanks a lot !

**Comment by JorjMcKie** [comment]
> A small curiosity would be whether annot.update() would also do this, or reload_page() is still needed?

The contrary is more true 😊: ``annot.update()`` consists of 2 parts internally - part 1 is MuPDF logic, and part 2 is PyMuPDF logic which adds certain features to MuPDF's results (for some annot types only). And the latter is, what escapes MuPDF's attention - until the page is reloaded.

**Comment by cipri-tom** [comment]
Oh, that means that the pixmap is taken directly from MuPDF. That's clear. Thanks a lot !
