### ISSUE TITLE
Textfield Widget not displaying value after updating.

### ISSUE THREAD

**Issue by boukeas** [pymupdf/PyMuPDF#563]
## Describe the bug (mandatory)
A TextField widget can be added to a pdf programmatically. However, when a user loads the pdf into a viewer and manually updates the text in the field, the new value is not displayed.

## To Reproduce (mandatory)
```
import fitz
doc = fitz.Document()
page = doc.newPage()
page.insertTextbox(fitz.Rect(10, 10, 200, 30), "Some text")

widget = fitz.Widget()
widget.rect = fitz.Rect(10, 40, 200, 60)
widget.field_type = fitz.ANNOT_WG_TEXT
widget.text_fontsize = 16
widget.fill_color = (0.8, 0.8, 0.8)
widget.field_name = "textfield-1"
widget.field_value = "form text"
annot = doc[0].addWidget(widget)

doc.save("test.pdf", clean=True)
doc.close()
```
## Screenshots (optional)
This is how the text field is displayed originally. 
![Screenshot from 2020-07-20 22-56-41](https://user-images.githubusercontent.com/11033117/87990754-8454fe80-cadc-11ea-8cd1-384eb6d7210f.png)

The user manually enters new text in the field:
![Screenshot from 2020-07-20 22-57-02](https://user-images.githubusercontent.com/11033117/87990825-afd7e900-cadc-11ea-9f6f-e4a38ca61ee0.png)

The new value is not displayed:
![Screenshot from 2020-07-20 22-57-13](https://user-images.githubusercontent.com/11033117/87990845-be260500-cadc-11ea-97fc-6cd1a697e5fd.png)

## Your configuration (mandatory)
 - Ubuntu 18.04
 - Python 3.6.9
 - PyMuPDF version 1.16.17

## Additional context (optional)
In the past, I have used `pdfrw` to fill in the forms in a pdf and I had encountered a similar problem. It was solved using the `NeedAppearances` flag: 
```
# bug fix from https://github.com/pmaupin/pdfrw/issues/84
PdfReader(input_pdf).Root.AcroForm.update(PdfDict(NeedAppearances=PdfObject('true')))
```

**Comment by JorjMcKie** [comment]
Cannot reproduce.
Tried your script and successfully changed the field using:
* Adobe Acrobat Reader
* Nitro PDF 5
* Foxit Reader
* PDF-XChange

Even using the Edge internet browser worked.
Also worked changig the field programmatically using PyMuPDF.

**Comment by boukeas** [comment]
That's interesting. I have been trying this in Ubuntu's default pdf reader (Evince) but I hadn't thought of testing in a browser; I tried it in Mozilla and it did work. I am closing this, thank you.

**Comment by JorjMcKie** [comment]
>  ... It was solved using the NeedAppearances flag ...

In PyMuPDF, appearance stream objects (`/AP`) are always generated for annotations and form fields. So this is shouldn't be relevant here.
Except the software you use for filling the form is weird enough to require it.

**Comment by JorjMcKie** [comment]
Just saw your response concerning `evince`.
I currently have not Linux machine to confirm. But to be sure let me make the general change in PyMuPDF and always set that property when the PDF has fields.

**Comment by boukeas** [comment]
I've done some additional testing that may be of use. When I save the pdf form with the updated text value and reload it in my pdf viewer, the updated value is not visible but clicking in the field reveals it has been stored correctly.
![Screenshot from 2020-07-21 12-59-35](https://user-images.githubusercontent.com/11033117/88052402-1c40ff80-cb52-11ea-8362-e378c695f079.png)
![Screenshot from 2020-07-21 12-59-43](https://user-images.githubusercontent.com/11033117/88052408-1ea35980-cb52-11ea-8f2a-528c6419c0ef.png)
Unfortunately, I am not able to do that in a browser. Loading the test pdf in the browser allows you to update the field and the updated value is visible:
![Screenshot from 2020-07-21 12-52-11](https://user-images.githubusercontent.com/11033117/88051976-71c8dc80-cb51-11ea-8714-354f93e8ca64.png)
![Screenshot from 2020-07-21 12-52-31](https://user-images.githubusercontent.com/11033117/88051984-74c3cd00-cb51-11ea-853c-f53edf58e2c0.png)
When I save the pdf form with the updated text value and reload it in my browser, the original value appears in the text field.
![Screenshot from 2020-07-21 12-52-56](https://user-images.githubusercontent.com/11033117/88051989-77262700-cb51-11ea-932d-1011fb8c0ac9.png)

**Comment by boukeas** [comment]
Thank you. This is the updated pdf:
[test.newer.pdf](https://github.com/pymupdf/PyMuPDF/files/4953532/test.newer.pdf)

**Comment by JorjMcKie** [comment]
Suspicion confirmed: it seems to be the absence of that overall property `NeedAppearances``.
The appearance stream of your changed field does not contain the new field value - only the field **object** definition (the ``/V`` property has that new string). All my viewers behave exactly like you described it.

Try to check with a form PDF **_not_** created with PyMuPDF. Edit the PDF with some text editor and look for that property. Then delete it or put in ``false`` instead of ``true``. Your changes must be done such, that the new content has exactly the same number of bytes.

I also did this:
```python
>>> import fitz
>>> doc=fitz.open("test.newer.pdf")
>>> page=doc[0]
>>> w=page.firstWidget
>>> w
'Text' widget on page 0 of test.newer.pdf
>>> w.update()  # just re-update the field w/o changes
>>> doc.save("test-newer-2.pdf")
```
The resulting file behaves as it should ...

**Comment by boukeas** [comment]
> Try to check with a form PDF not created with PyMuPDF. Edit the PDF with some text editor and look for that property. Then delete it or put in false instead of true. Your changes must be done such, that the new content has exactly the same number of bytes.

I tried with this [publicly available pdf form](http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf) (reportedly created using OpenOffice). The form worked perfectly, both in the browser and my pdf viewer. Setting the property to `false` did not change anything but removing it altogether stopped the content of the updated fields from appearing.

**Comment by JorjMcKie** [comment]
So it seems we are coming to this conclusion:
In certain situations or for certain PDF viewers, setting of the Form PDF property ``NeedAppearances`` is a required feature.

As I mentioned, the next version will include a method to set this property to true or false.
