### ISSUE TITLE
Unable to install version 1.17 on ubuntu 18.04

### ISSUE THREAD

**Issue by Vibha111094** [pymupdf/PyMuPDF#565]
I am able to install 1.16 version with just a pip3 install PyMuPDF.
However, I am not able to install 1.17 the same way.

Error is :
fitz/fitz_wrap.c no such file or directory exists.

**Comment by JorjMcKie** [comment]
Make sure you control using the right Python by issuing ``python3.x -m pip install ...``.
Your error indicates that your Python is trying a non-wheel installation - which only happens if its pip doesn't find a matching wheel.

**Comment by Vibha111094** [comment]
Thanks a lot! It worked.
