### ISSUE TITLE
Fail to read PDF

### ISSUE THREAD

**Issue by DhruvAwasthi** [pymupdf/PyMuPDF#567]
[unixbook.pdf](https://github.com/pymupdf/PyMuPDF/files/4974969/unixbook.pdf)
I've a PDF book.  What I'm trying to do is extract its content. The code I'm using is this:

`document = "unixbook.pdf"`
`doc = fitz.open(document)`
`page = doc[4]`
`print(page.getText()`

The code works on all PDFs but fails on some. For those few, it just returns an empty string. 
The PDF is not password encrypted, it's the same as others.
Please help if it can be resolved. 

PFA

**Comment by JorjMcKie** [comment]
There are a number of reasons why this can happen:
* the book may be scanned-in
* the text characters may not be encoded with some font but drawn using elementary draw commands like so: the capital letter "D" is synthezised by a vertical stroke followed by a left-open semicircle, etc.

If you list the fonts of the page ``page.getFontList()`` you will probably see an empty list. You must use OCR to get the text out of such pages, e.g. the excellent [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF).
If you want you can let me see an example (please 1 or 2 pages only not the full book), or send me an weblink.

BTW to enter a bug you missed the mandatory information. This also obviously is a **_question_**.

**Comment by JorjMcKie** [comment]
Just checked your example: it is a scan!

**Comment by DhruvAwasthi** [comment]
Thank you for labelling it correctly and clearing my question. So it's basically the fact that PDFs that are scanned can not be read through this, instead, I need to use an OCR. Can you tell me please how'd you know it is a scanned copy?

**Comment by JorjMcKie** [comment]
>  is there any encoding problem that can deviate this from normal behaviour?

No. Your PDF simply contains no text, only pictures. Someone used a scanner to take a picture of every page of the book. There is nothing weird or "unnormal" here. Happens every day.

**Comment by JorjMcKie** [comment]
As I mentioned:
There exist packages (e.g. OCRmyPDF), which can interpret images and identify text on them (OCR - optical character recognition). The recognized text is then inserted in the PDF "underneath" the image (i.e. invisible).
But you then can extract that reconstructed text.
Here is a version of your book modified like this:
[unixbook.pdf](https://github.com/pymupdf/PyMuPDF/files/4977611/unixbook.pdf)

**Comment by DhruvAwasthi** [comment]
Okay I got it now. Thank you soo much for your patience and time to reply to my questions. 
Thank you!

**Comment by PasaOpasen** [comment]
@JorjMcKie how can I get the text from this file https://dropmefiles.com/Z3QjW ?

As I know, it is hidden somehow in page layers and can be extracted by pdfminer. It is not available in Adobe but it is in the browser viewer

**Comment by JorjMcKie** [comment]
@PasaOpasen if you open that file in Adobe Acrobat and similar PDF viewers, you will see a number of OC layer names like this: 
![image](https://github.com/user-attachments/assets/774d0ff8-79d3-4f4d-98fc-674d5b7a283a)

If you click on the squares on the right side you will switch on or off the respective content - including e.g. "Text" or "Text outline".
Whatever is switched on (the exe symbol in Adobe example) will become visible and also extractable. If off, it won't be seen nor extracted.

Some packages like pdfminer may be incapable to support Optional Content and always extract stuff - even when the PDF says "ignore this for now".

PyMuPDF supports Optional Content and won't (initially) extract "Text" as it is switched off in the initial view shown above.
But you can use respective `Document` methods (please consult the documentation) to learn which layers are available and switch or toggle them to influence visibility / extraction capability.

**Comment by JorjMcKie** [comment]
@PasaOpasen - by the way: you are hijacking an old Discussions thread with a completely unrelated topic. You should have created a new Discussion post for this.
No one will find your question based on this post's title.
