### ISSUE TITLE
Typo: retturn instead of return

### ISSUE THREAD

**Issue by papafelice** [pymupdf/PyMuPDF#568]
## Describe the bug
Exception ignored in: <function Annot.__del__ at 0x7f46274be1f0>
Traceback (most recent call last):
File ".../python3.8/site-packages/fitz/fitz.py", line 6180, in __del__
NameError: name 'retturn' is not defined

## To Reproduce
create an annotation and let go out of scope

## Your configuration
 - PyMuPDF 1.17.3, 1.17.4, wheel

**Comment by JorjMcKie** [comment]
WTF - thanks for spotting this!
How urgent is a resolution?

**Comment by papafelice** [comment]
Not urgend, I edited the installed lib :-), works so far.

**Comment by JorjMcKie** [comment]
Fixed in new version just uploaded.
