### ISSUE TITLE
Proper use of page.derotationMatrix

### ISSUE THREAD

**Issue by papafelice** [pymupdf/PyMuPDF#569]
I have received test PDF file (created with the "print to pdf" function of a non-Unix system) that resists in properly adding a TextBox.
The following code should create TextBox in the upper left corner of the page, however it is vertically flipped, shifted and scaled down.
Inserting a new page creates the right output, so there must be someting in the page coordinate system of the document that is not properly handled by my code. Is there anything more to do to the rect before calling insertTextbox?

    import fitz         
    doc = fitz.open("testflip.pdf")  

    page = doc[0]                         
    rect = fitz.Rect(10, 10, 100, 50) * page.derotationMatrix
    page.insertTextbox(rect, "My Text", fontsize=24, color=(0, 0, 0))

    doc.insertPage(-1)
    page = doc[1]                         
    rect = fitz.Rect(10, 10, 100, 50) * page.derotationMatrix
    page.insertTextbox(rect, "My Text", fontsize=24, color=(0, 0, 0))

    doc.save("out.pdf")
    doc.close()
 
[testflip.pdf](https://github.com/pymupdf/PyMuPDF/files/4981149/testflip.pdf)

**Comment by JorjMcKie** [comment]
This is one of the pages with "geometry changes" that are not properly wrapped:
If you look at line one of `page.readContents()` you will see the statement `.23999999 0 0 -.23999999 0 841.91998 cm`. This is a matrix in PDF's mini-language, which in this case scales (down) **all what follows** by factor 0.24 and also flips vertically (minus sign in position 4).
Because this is not wrapped in the command pair "q" / "Q", your inserts are also subject to the effect of that matrix.
You can add this missing wrapping by adding
* `page._wrapContents()` or
* `page.cleanContents()` (does much more than this wrapping)

right after `page = doc[0]` (or before the first inserts).
And of course you can evade this also by pre-pending your insert to the page contents (`overlay=False`) - which is certainly not what you want.

**Comment by papafelice** [comment]
Is it safe to always call these functions just in case even without problems? I am asking this because my program should eventually become a FOSS digital signature tool for pdfs once pymupdf can handle this. If I understood it right, the principle is that new signatures form an "onion shell" with a new hash around the old content. Calling these functions will alter the old content and the verification of the old signatures will fail, right?

**Comment by papafelice** [comment]
Just found the good explanation of the issue in the documentation 4.7.2, should have searched more intensive...
But the question with signing remains.

**Comment by JorjMcKie** [comment]
> is it safe to always call these functions ...

Yes it is. Will not harm if the contents already are properly wrapped.
I have actually considered to automate this? However, any such solution would either (1) easily bloat the page's `/Contents`, or (2) have an adverse performance impact if I would check for the first and last PDF commands to be "q" / "Q" before every insert ...

I believe the programmer knows best the when and the what.

**Comment by JorjMcKie** [comment]
> But the question with signing remains.

🙄 I have actually started with this a bit. There are a few issues, however. Especially on Windows.
The basic thing is, that MuPDF needs to be generated with integrated OpenSSL support and this breaks on Windows ...

**Comment by papafelice** [comment]
> I believe the programmer knows best the when and the what.

I just copied the snipped from the documentation

    if not page._isWrapped:
        page._wrapContents()

Good enough for the moment

**Comment by papafelice** [comment]
> I have actually started with this a bit. There are a few issues, however. Especially on Windows.
> The basic thing is, that MuPDF needs to be generated with integrated OpenSSL support and this breaks on Windows ...

To get around the openSSL API, my plan is to use the python bindings of gpgme, because I didn't want to have another key store on my machine and Kleopatra is a nice front end for gpg both on Linux and Windows. This encapsulates all the SSL stuff and currently I can list, select and display the X.509 keys. I don't have Windows, so I couldn't test it there, but probably the python bindings are not yet part of gpg4win.

Then somehow the hash must generated, signed and handed over to pymupdf for insertion without altering the original content.

**Comment by JorjMcKie** [comment]
Hm, interesting idea. Years ago I once used gpg4win (not related to programming in any way). Maybe it is worthwhile to look a that again under this aspect.
