### ISSUE TITLE
Question / Comment: Custom text block extraction

### ISSUE THREAD

**Issue by victor-ab** [pymupdf/PyMuPDF#571]
**Is your feature request related to a problem? Please describe.**
I love pymupdf, but pdfminer have a [feature ](https://github.com/pdfminer/pdfminer.six/blob/0b44f7771462363528c109f263276eb254c4fcd0/pdfminer/layout.py#L32) I think it'd be very nice to have here.
It can extract text blocks by using a custom layout analysis.

**Describe the solution you'd like**
Add a text block extractor with custom parameters to extract paragraphs and lines with more precision.

**Describe alternatives you've considered**
Use pdfminer.

**Additional context**
This would enable better text parsing, NLP tasks should get better and easier, without having to work with just single words. It will increase the accuracy of extracting a whole paragraph and will separate better the lines.

**Comment by JorjMcKie** [comment]
Thanks for submitting this. I will certainly have a closer look going forward.

In the meantime a few comments:
1. The example script to do rectangle extracts wasn't meant to be more: just an **_example_** using basic features only.
2. The "words" and "blocks" options once were created as top speed functions - not much more.
2. You might want to look at ``getText("dict")`` and ``getText("rawdict")`` extraction variants. It reveals that MuPDF readily has incorporated logic which assigns **_characters_** to text **_spans_**, text **_spans_** to **_lines_** and **_lines_** to **_blocks_**.

**Comment by victor-ab** [comment]
Hi @JorjMcKie!

1. & 2. Yes, this is the fastest algorithm by far! Yet it does a decent job when extracting blocks. 
3. Will take a look into it. Thanks for pointing it!

**Comment by JorjMcKie** [comment]
After thinking about your suggestion for a while now here is my position:
* There already are plenty of ways to extract text: various detail levels, various output formats, ...
