### ISSUE TITLE
Annotate unsearchable pdfs

### ISSUE THREAD

**Issue by Atiqul-Islam** [pymupdf/PyMuPDF#572]
I am trying to add data and annotate stuff on an unsearchable PDF.

I used Tesseract to convert the unsearchable PDF to searchable PDFs.

The goal after is to use pymupdf to draw lines based on specific `Points`.

    `pdfDoc` = fitz.open(self.__path)
    `for` page in self.__pdfDoc:
        `self.__page` = page
    `page.drawLine(fitz.Point(coords[0],` coords[1] + 4), fitz.Point(coords[3], coords[4] + 4), overlay=False,` color=(1, 0, 0))

where coords is a list:
 

 1. coords[0] = x0
 2. coords[1] = y0
 3. coords[2] = x1
 4. coords[3] = y1

Applying the logic to a searchable pdf returns expected result. However on the converted PDF using tesseract there is nothing added to the PDF.

Any suggestions would be greatly appreciated.

**Comment by JorjMcKie** [comment]
Can you please share a Tesseract-modified PDF?

It may also be, that the page "geometry" has been modified in a non-wrapping way by Tesseract. Try to do the wrapping yourself **_before_** you do your inserts:

```paython
if not page._isWrapped:
    page._wrapContents()
```

**Comment by JorjMcKie** [comment]
Making a PDF searchable works by inserting "hidden" text. This is achieved by using the so-called render mode operand `Tr`: command is ``3 Tr``. Text under the influence of this render mode value will not be rendered - although it is present.
This leaves the image visible, but the imaged text seemingly can be selected, copied, pasted and searched. In reality it is the invisible inserted text.
Render mode remains in effect until overwritten by some other value, ``0 Tr`` - the default.
If you insert text by ``insertText`` / ``insertTextbox`` make sure you set render_mode parameter.

**Comment by JorjMcKie** [comment]
Just tried ``page.drawLine`` successfully on a PDF OCR-ed using OCRmyPDF for that purpose (which under the hood uses Tesseract).

**Comment by Atiqul-Islam** [comment]
Really appreciate the quick response. In the test you conducted after conversion with OCRmyPDF did you have to make any additional changes for the drawline to work?

I was also wondering how would I set my render parameter as you suggested in the previous comment

**Comment by JorjMcKie** [comment]
>  In the test you conducted after conversion with OCRmyPDF did you have to make any additional changes for the drawline to work?

No, I just picked some page and entered this in IDLE
```python
page.drawLine(page.rect.tl, page.rect.br)
```
OCFmyPDF was invoked via ``ocrmymdf --output-type pdf ...`` and also ``ocrmymdf --output-type pdfa ...`` without any other parameters.

**Comment by JorjMcKie** [comment]
Assuming your questions are anwered. Please do not hesitate to re-open if needed.
