### ISSUE TITLE
Error with saving pdf docuemnt 

### ISSUE THREAD

**Issue by vladcube** [pymupdf/PyMuPDF#573]
Hello, i can't save my pdf document, but can save all ducuments except one.
My code:
```python
doc = fitz.open(fname)
for page in doc:
   text_instances = page.searchFor(value)
   for inst in text_instances:
            highlight = page.addHighlightAnnot(inst)
            highlight.setColors({"stroke":(0, 0, 1), "fill":(0.75, 0.8, 0.95)})
            highlight.update()


doc.save("output.pdf")
```
But i have following:
![image](https://user-images.githubusercontent.com/13377383/88857760-88c99780-d1ff-11ea-8f6a-6bc5826f9d08.png)

And also i have wanings:
![image](https://user-images.githubusercontent.com/13377383/88857814-9d0d9480-d1ff-11ea-9cf1-630035da1cbb.png)
Help me please how to i can load my file and avoid warnings. Thanks!

**Comment by JorjMcKie** [comment]
Please provide all data mandatory for a bug.
And then - you say yourself it normally works - I obviously also need the failing PDF!

> Text marker annotations (highlight and friends) indeed have not fill color (IC = interior color).

**Comment by JorjMcKie** [comment]
I hope that document is not a big one.
It may be that it is damaged right from the start. Can you save it at all - without inserting annotations?

**Comment by vladcube** [comment]
@JorjMcKie 
PDF file [here](https://drive.google.com/file/d/1JaBQTLScBTMD9irxpdezF6SPHan4_Pug/view?usp=sharing)

**Comment by JorjMcKie** [comment]
As suspected, the PDF is damaged. It is full of invalid object references like `` /Pg 322764821 0 R ``.
The large integer should be a valid object number, which for this PDF must not greater than 201. There are many dozens of errors like this.
You must somehow clean this file. Either use the CLI tool ``mutool clean`` of MuPDF, or copy it page by page into a new pdf with PyMuPDF like this:
```python
src = fitz.open("Primary Access.pdf")
new = fitz.open()
new.insertPDF(src)
new.setMetadata(src.metadata)
new.save("repaired.pdf")
```

**Comment by JorjMcKie** [comment]
BTW if you are not interested in cleaning / repairing the PDF, you may be lucky enough that **_incremental_** saves do work. In that case the PDF will not be rewritten to a new file, but your modifications are appended to it.
In this case it works if you do ``doc.saveIncr()`` instead of `doc.save(...)`. Repairing the file can be postponed or left to someone else 😎.

**Comment by vladcube** [comment]
@JorjMcKie  Thanks a lot:)
