### ISSUE TITLE
Please fix the linking for openSUSE

### ISSUE THREAD

**Issue by jloehel** [pymupdf/PyMuPDF#574]
## Describe the bug (mandatory)
The linking does not really work for openSUSE.

## To Reproduce (mandatory)
```
╭─jloehel@workmachine /tmp/test_pymupdf   
╰─➤  python3 -m venv .venv && source .venv/bin/activate                                                                                        
╭─jloehel@workmachine /tmp/test_pymupdf  (.venv) 
╰─➤  pip install pymupdf 
Collecting pymupdf
Installing collected packages: pymupdf
Successfully installed pymupdf-1.17.4
You are using pip version 18.1, however version 20.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
╭─jloehel@workmachine /tmp/test_pymupdf  (.venv) 
╰─➤  python
Python 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test_pymupdf/.venv/lib64/python3.6/site-packages/fitz/__init__.py", line 3, in <module>
    from fitz.fitz import *
  File "/tmp/test_pymupdf/.venv/lib64/python3.6/site-packages/fitz/fitz.py", line 18, in <module>
    from . import _fitz
ImportError: /tmp/test_pymupdf/.venv/lib64/python3.6/site-packages/fitz/_fitz.cpython-36m-x86_64-linux-gnu.so: undefined symbol: jpeg_resync_to_restart
>>> exit()
```

## Expected behavior (optional)
The installation from pip works without patching. (https://github.com/jloehel/PyMuPDF/commit/22e525391be67fd98ae72db87f33b03d70535296)

## Your configuration (mandatory)
```
╭─jloehel@workmachine /tmp/test_pymupdf  (.venv) 
╰─➤  cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.1"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"
PRETTY_NAME="openSUSE Leap 15.1"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
╭─jloehel@workmachine /tmp/test_pymupdf  (.venv) 
╰─➤  uname -a
Linux workmachine 4.12.14-lp151.28.52-default #1 SMP Wed Jun 10 15:32:08 UTC 2020 (464fb5f) x86_64 x86_64 x86_64 GNU/Linux
╭─jloehel@workmachine /tmp/test_pymupdf  (.venv) 
╰─➤  python --version
Python 3.6.10
```

Let me know if you need anything else.

**Comment by JorjMcKie** [comment]
Some comments:
1. ``setup.py``  is **_intended_** to be modified if building pymupdf from sources. If you look at the file, the many commented lines are a collection of cases where one thing worked, but others didn't.
2. I have no general problem adding more cases for ``module = Extension(...`` based on the platform. But the special Linux flavor must be somehow detectable ... what worked for you in jloehel@22e5253 presumably won't work for every Linux.

Best you submit a PR.

**Comment by JorjMcKie** [comment]
@jloehel  - just confirming that the generation of wheels does work as usual and these wheels have passed the tests.
Thanks again for your contribution!

**Comment by jloehel** [comment]
> @jloehel - just confirming that the generation of wheels does work as usual and these wheels have passed the tests.
> Thanks again for your contribution!

Great! You are welcome. :-)
