### ISSUE TITLE
Questiion: Is there a way to change the character printed in check boxes?

### ISSUE THREAD

**Issue by dcd271b2** [pymupdf/PyMuPDF#576]
I am using pyMuPDF v. 1.17.1.  I am reading an existing PDF and checking/un-checking check boxes.  The check boxes have a check mark (✓) when checked.  I would like to change the character to an X or other character with pyMuPDF.  Is this possible?

**Comment by dcd271b2** [comment]
I should have said I am using the Widget class (for widget in page.widgets...)

**Comment by JorjMcKie** [comment]
Have not checked this myself yet, but that should just be a matter of the font you use for the widget. By default this is ZapfDingbats. So if you choose Helvetica it should be fine - ``widget.text_font = "helv"``.
