### ISSUE TITLE
Question / Comment: inserting images via an image field

### ISSUE THREAD

**Issue by iWHOswald** [pymupdf/PyMuPDF#578]
I am aware of using the pixmap method of adding images to PDFs. However it can be somewhat time consuming to get the images perfectly aligned. Is there a way to input images into an image field  (similar time how one can fill text fields) as an alternative way of inserting images? I have looked through the documentation but don't see any specific details on doing this.

**Comment by JorjMcKie** [comment]
No, I'm afraid there isn't.
I imagine you think of something like an annotation whose rectangle should display an image, right? Then move around that rectangle to your liking ...

The only idea I can offer at the moment is the following approach
1. Add a rectangle annotation to the page `page.addRectAnnot(rect)`
2. Optimize the annot position by fiddling with rect
3. Insert your image into that optimized rect
4. Delete the annotation

**Comment by iWHOswald** [comment]
This is what I assumed, and yes I usually do something similar to what you described. Something that would be useful: Are the values for the coordinates of the pixmap based on pixels? Reason I ask is I was thinking I could get the approximate location of the image corners in photoshop and then use those as starting values and then tweak them as needed. Only thing is knowing what the DPI of the pdf w/ the inserted image is so that one could make sure they're the same in photoshop and the pdf.

**Comment by JorjMcKie** [comment]
Thinking about your interesting question.
Here is a script which you may find useful. It works using the following approach:
1. The position (and magnification and rotation) of an image are controlled by exactly one function call formulated in PDF's mini-language.
2. PyMuPDF uses a specific pattern to build this command when executing `page.insertImage`. Images are referenced by the name `fzImg<n>` where n is a zero-based integer, so the command looks like ``q a b c d e f cm /fzImg<n> Do Q``. Letters "a" through "f" are the 6 matrix parameters. "cm" is the matrix invocation function call (= "concatenate matrix" - the mini-language uses an argument-first syntax). "Do" invokes the (prepended) image, and "q" / "Q" are commands stacking / unstacking the graphics environment.
3. Finding and modifying this command is not overly difficult. One only needs to find out the image reference name, which is contained in one of the items of `page.getImageList()`: and looks like this: `(5, 0, 439, 501, 8, 'DeviceRGB', '', 'fzImg0', 'DCTDecode')`.

So here is the script together with before / after images of the test PDF.
[reposition-image.zip](https://github.com/pymupdf/PyMuPDF/files/5012518/reposition-image.zip)

**Comment by JorjMcKie** [comment]
> are the values for the coordinates of the pixmap based on pixels?

Yes, they are. But the image will be scaled up or down to always fit the given rectangle of the page.

**Comment by JorjMcKie** [comment]
Mayby you should consider writing a little GUI script which shows the PDF page. Then draw a rectangle on it where it fits and pass its coordinates to the script I sent you.
Or use a PDF viewer which lets you enter annotations, give the annotation a unique identifying name and then use image insertion to replace the annotation as indicated earlier.

**Comment by JorjMcKie** [comment]
> the image will be scaled up or down

This logic is:
* at least one of width or height are used to coincide with the resp. images edges
* the rect and image centers always coincide
* choose wether to maintain the image aspect ratio, if turned off, **_all_** edges coincide
* image rotation by one of the angles 90, 180 or 270 are possible.

**Comment by JorjMcKie** [comment]
Agree to close?

**Comment by iWHOswald** [comment]
Yes that works.

**Comment by JorjMcKie** [comment]
Ignited by your inquirey, I have written a GUI script (wxPython) which allows visual re-positioning of images.
Currently works for existing images only. If you have wxPython or can install it and would like to try this script let me know.
I'll post it on the utilities repo in a few weeks from now.

* works for many images - but not for all. Does **_not work_** in these cases:
    - images in embedded PDF pages; only images inserted directly on the page are supported. Corresponds to the same limitation of `page.getImageBbox`.
    - image location may be too obscure to reconstruct;
    - images rotated by angles other than 90-degree multiples

* supports
    - images inserted by PyMuPDF
    - rotating / unrotating images
    - ability to freely move the image rectangle across the page and changing the image rectangle size. May happen either using mouse or fine controlling via spin controls.
    - step through all images on the page (via a button) and see its reference name, rotation and coordinates
    - save modifications to a new file, or as an incremental update

This is how the new image position is indicated.
![step1](https://user-images.githubusercontent.com/8290722/89668610-0b132500-d8ac-11ea-9f9c-08ef50f00812.jpg)
After pressing `Update img` , the image is immediately moved to the red rectangle:
![step2](https://user-images.githubusercontent.com/8290722/89668981-ae643a00-d8ac-11ea-8dd8-3c0e1974364c.jpg)

At this point, the PDF has not yet been altered. Pressing `Next img` will display details about the remaining images, which can be handled in the same way.

**Comment by iWHOswald** [comment]
Wow, fantastic work!! I will check this out for sure. Thank you for taking the initiative on this - should speed up this process significantly.

**Comment by JorjMcKie** [comment]
ok here is that script - of course still under construction!
[move-image.zip](https://github.com/pymupdf/PyMuPDF/files/5042858/move-image.zip)

**Comment by JorjMcKie** [comment]
For every new page, automatically the first image will be wrapped in a red rectangle.
The first page need a bit of scrolling first.
Image relocation obviously happens with a minimum of 1 picture pixel, so that's the precision limit currently. Can only be healed if I were using zooming ...

**Comment by JorjMcKie** [comment]
Red redtangle can be enlarged or made smaller by using the bottom right corner as a handle.

**Comment by JorjMcKie** [comment]
There is an improved version [here](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/image-maintenance.py). Includes a hopefully instructive description, too.

Now you can

* remove images
* insert new images
* make problem images modifyable

Hope you find it useful.

I think your issue has been addressed by now.

**Comment by iWHOswald** [comment]
Jorj:

Just thought I would let you know I finally got around to testing your little program. It has helped immensely. I used to have to adjust many images by hand saving a pdf, inspecting, then adjusting over and over. This literally reduces that down to one step. Thanks again for this tool. You should definitely broadcast this on your front page or at least somewhere visible so others know about it - it's incredibly helpful!

**Comment by JorjMcKie** [comment]
Thank you very much for that kind feedback!

Yes, you are right, that tool helps a lot and it probably deserves some prominent announcement.
