### ISSUE TITLE
Question / Comment: How to access stream attributes from pdf image object 

### ISSUE THREAD

**Issue by BotquinThomas** [pymupdf/PyMuPDF#581]
Hello,

I have been looking for a way to check the filter attribute of an image object stream using the fitz librarie but I can't seem to find a way,
The filter attribute can take the following values: '/DCTDecode' , '/JPXDecode', ... or a list : ['/FlateDecode','/DTCDecode']
I can't find a solution on stackoverflow and I struggle finding it in the documentation,

For the moment I use Pypdf2  in order to get those values, but it would be nice if I can work from one single library, so that I don't need to open the pdf file for each library

Also, I had another question regarding the fact that images sometimes need to be reassembled after being extracted from a pdf,
Is there a simple way to do it? Is it also available on fitz or do you recommend other libraries for this task !

Thank you for your help!

**Comment by JorjMcKie** [comment]
@BotquinThomas - oops: closed before I had a chance to look 🙄
Does that mean you found the answers?

**Comment by BotquinThomas** [comment]
Hello,

yes, I found it thank you,
it was one of the image attributes,
found it by printing everything out!

I don't know if there was something else I asked in my question,
I think it was something with the possibility to output a list of all the
possible filters of the image object like ( ['DTCDecode', 'FlateDecode'] )
I didn't find the answer yet for this one but since i found the answer for
the first one I preferred removing it (I felt like it was a dumb question
:o )

  very nice library though ! thank you for the nice work

**Comment by JorjMcKie** [comment]
Find more background on these filters in section 3.3 Filters pages 65+ in manual https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf
