### ISSUE TITLE
Question / Comment: by default pdf to image will generate images with 72 dpi resolution, how to specify a certain dpi say 150/300?  

### ISSUE THREAD

**Issue by alexucb** [pymupdf/PyMuPDF#582]
in previous question, people are suggesting to apply "fitz.Matrix" to convert 72 dpi image to 150, but would it be possible to specify a certain dpi value in the first step (fitz.open)?

```
pdf_doc = fitz.open(pdf_path)
page = pdf_doc.loadPage(0)
zoom = 150. / 72.
mat = fitz.Matrix(zoom, zoom)
pix = page.getPixmap(matrix = mat)
```

applying zoom factor won't recover all the detailed pixel information those have been destroyed in the first step.

**Comment by alexucb** [comment]
i must admit that pymupdf is way more faster than imagemagic, pdftocario and other utils in converting pdfs to images. Kudos to all the contributors.

**Comment by JorjMcKie** [comment]
>  those have been destroyed in the first step

Which "first step"?

**Comment by JorjMcKie** [comment]
closed for lack of response
