### ISSUE TITLE
pix.pillowWrite and pix.pillowData throw AttributeError

### ISSUE THREAD

**Issue by shekargoud26** [pymupdf/PyMuPDF#583]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
pix.writePNG() works but pix.pillowWrite and pix.pillowData throw attribute error

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

## Expected behavior (optional)
 pix.pillowWrite should save image in specified format and pix.pillowData should return a PIL image object

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/16861024/89265673-7661ba80-d652-11ea-9b3a-25d18d0a2718.png)

## Your configuration (mandatory)
 - Ubuntu 18.04
 - Python version: 3.7
 - PyMuPDF version: PyMuPDF-1.17.1-cp37-cp37m-linux_x86_64.whl

**Comment by JorjMcKie** [comment]
As docu says: new in **_v1.17.3_**
