### ISSUE TITLE
ico name still wrong

### ISSUE THREAD

**Issue by bgermann** [pymupdf/PyMuPDF#586]
https://github.com/pymupdf/PyMuPDF/blob/d66c6aee4d540dca33d5b6f55c235a37df70f21e/docs/conf.py#L127
still has the wrong capitalization. The file is named PyMuPDF.ico, not Pymupdf.ico

**Comment by JorjMcKie** [comment]
Thank you.
Sorry about that - keep pulling in the wrong file version.
Just corrected it and created new docu on RTD.
