### ISSUE TITLE
Question / Comment: Transparency conversion

### ISSUE THREAD

**Issue by pvyuri** [pymupdf/PyMuPDF#587]
Hello!  When converting from XPS to PDF, some vector objects and text become semi-transparent to PDF (see image below), although they are not transparent in XPS.  Is it possible to adjust the transparency (turn off) of vector objects and text when converting from XPS format to PDF and how to do it?![image](https://user-images.githubusercontent.com/29060237/89671148-24879180-d8eb-11ea-9cf6-206fe3012c69.jpeg)
 Thanks!

**Comment by JorjMcKie** [comment]
Wouldn't know how to do that to be honest.
Have you tried converting via the MuPDF cli tool: ``mutool draw ...``?

**Comment by pvyuri** [comment]
> Wouldn't know how to do that to be honest.
> 
> Have you tried converting via the MuPDF cli tool: ``mutool draw ...``?

mutool gives same result

**Comment by JorjMcKie** [comment]
Then I am afraid I'm out of good advice. Maybe you send this example to MuPDF's bug tracker https://bugs.ghostscript.com/enter_bug.cgi

**Comment by pvyuri** [comment]
> Wouldn't know how to do that to be honest.
> 
> Have you tried converting via the MuPDF cli tool: ``mutool draw ...``?

mutool **draw** convert text **solid**, but not vectors. 
Is the way to tune transparency in converted PDF with pyMuPDF?
![image](https://user-images.githubusercontent.com/29060237/89679837-88658680-d8fa-11ea-9a18-817d48a547d5.jpeg)

**Comment by JorjMcKie** [comment]
Can you give me the an XPS example please, so I can better understand the problem?

**Comment by pvyuri** [comment]
> Can you give me the an XPS example please, so I can better understand the problem?
@JorjMcKie Please find attached example. 

[TST.zip](https://github.com/pymupdf/PyMuPDF/files/5062108/TST.zip)

**Comment by JorjMcKie** [comment]
Thanks for the file. This is what I learned:
1. we are **_not_** dealing with images here - it is all text and elementary PDF draw commands
2. so the phenomenon is **_not image transparency_**, but opacity, which is to 25%
3. there is a difference between the PDFs created by PyMuPDF and mutool - much to my amazement: I am calling MuPDF functions when converting.

So I need to find the point where `mutool` and PyMuPDF do different things, maybe some parameter set differently.

If you need a quick-and-dirty solution, you can do something like this:

* look at the PDF page definition text, this is the string `doc.xrefObject(page.xref)`. In the example:

```python
>>> doc=fitz.open("tst.xps.pdf")
>>> page=doc[0]
>>> o = doc.xrefObject(page.xref)
>>> print(o)
<<
  /Type /Page
  /MediaBox [ 0 0 619.5 876.75 ]
  /Rotate 0
  /Resources <<
    /Font <<
      /F0 3 0 R
      /F1 11 0 R
      /F2 17 0 R
      /F3 23 0 R
    >>
    /ExtGState <<
      /Alp0 9 0 R
      /Alp1 10 0 R
    >>
  >>
  /Contents 29 0 R
  /Parent 2 0 R
>>
```
* the object definition text is always cleanly structured like this.
* find the xref numbers of objects named starting with `/Alp...`. In this case /Alp0 = 9 and /Alp1 = 10. You can rely on the fact, that they are on separate lines and that the xref number is the third to last item of the line, which ends with upper case "R".
* If you print the content of these objects, you get
```python
>>> print(doc.xrefObject(9))
<<
  /ca .25
>>
>>> print(doc.xrefObject(10))
<<
  /CA .25
>>
```
* The letters "ca" and "CA" mean opacity values for borders and interiors of PDF objects. Both are 0.25 = 25%. If we set these to 1, there will be no opacity any more:
```python
>>> doc.updateObject(9, "<</ca 1>>")
>>> doc.updateObject(10, "<</CA 1>>")
>>> doc.saveIncr()
```
* Before:
![grafik](https://user-images.githubusercontent.com/8290722/90010644-2eecb700-dc6e-11ea-9837-4a1b8432f952.png)
* After:
![grafik](https://user-images.githubusercontent.com/8290722/90010705-4d52b280-dc6e-11ea-9d11-c89b4a1f59b1.png)

**Comment by JorjMcKie** [comment]
The original XPS has a gray-level shading inside the box: both, mutool and pymupdf ignore this and put no color at all there.

**Comment by JorjMcKie** [comment]
I also just found, that ``mutool draw ...` and `mutool convert ...` produce different outputs!!!
"Convert" produces PyMuPDF's result, and "draw" the other one.
This is an amazing finding for me.
So please try my quick-and-dirty approach for the time being: it will take a while to uncover the background of all this.

**Comment by JorjMcKie** [comment]
Here is a simple little script that does this dirty cleaning more elegantly:
[dirty-cleaner.zip](https://github.com/pymupdf/PyMuPDF/files/5062664/dirty-cleaner.zip)
Invoke like `python dirty-cleaner.py converted.pdf`. Will produce `converted.pdf-upd.pdf`.
Hope you find it useful.

**Comment by pvyuri** [comment]
@JorjMcKie Thank you very much!!!

**Comment by JorjMcKie** [comment]
Good!
I am going to close this then. The reason being, that neither of the possible outputs of  ``convert`` or ``draw`` is satisfactory.
And then we now have a solution which can be integrated into the ``pdf-convert.py`` script (so no extra step is required ... **_==> please let me know if you need help on the how_**) and in addition can be adjusted to yet other behaviours, like e.g. being more selective / intelligent, ...
