### ISSUE TITLE
undefined symbol: jm_valid_chars

### ISSUE THREAD

**Issue by cges30901** [pymupdf/PyMuPDF#588]
## Describe the bug (mandatory)
After I built PyMuPDF 1.17.5 from source on Arch Linux and tried to import, I get error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.8/site-packages/fitz/__init__.py", line 3, in <module>
        from fitz.fitz `import` *
      File "/usr/lib/python3.8/site-packages/fitz/fitz.py", line 18, in <module>
        from . import _fitz
    ImportError: /usr/lib/python3.8/site-packages/fitz/_fitz.cpython-38-x86_64-linux-gnu.so: undefined symbol: jm_valid_chars
If I build PyMuPDF 1.17.4 from source or use wheel to install, this error does not occur.

## To Reproduce (mandatory)
    $ pip install --no-binary :all: PyMuPDF
    $ python
    >>> import fitz

## Expected behavior (optional)
No error

## Your configuration (mandatory)
 - Tried on Arch Linux and openSUSE
 - Python 3.8.5 on Arch Linux and 3.6.10 on openSUSE
 - PyMuPDF 1.17.5, generated from source.

**Comment by JorjMcKie** [comment]
You must re-build your MuPDF with the modified `_pdf-font-add.c`, to be put in `mupdf/source/pdf` as `pdf-font-add.c`.
Then generate PyMuPDF. Also see the home page of the repo.
