### ISSUE TITLE
How to create a pdf from text ?

### ISSUE THREAD

**Issue by a22349** [pymupdf/PyMuPDF#589]
Hi , 
i want to convert a text file to a proper pdf file using pymupdf , could you help to list some apis that may be useful ? 
for eg , how to determine how many characters  a page can hold (given the size and text area of the page and the font of the text )? 

or could you supply one utility function like "convertTextToPdf" api ? (convert html or word to pdf may complex but convert pure text to pdf possible ? )

thanks .

**Comment by JorjMcKie** [comment]
There are several ways to do that. Nothing as simple as simple as "convertTextToPdf" however.
There are one or two scripts that implement a subset of cases. If you are looking for a simple source code writer, have a look at [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/demo/text2pdf.py).

## `Page.insertTextbox()`
Then there is `Page.insertTextbox()`. This fills a given rectangle (which may be the full page for example) with the given text. The text may be a simple string or a list of strings. Items in a list will generate a line break, as well as `\n` contained in text. Words not fitting in a line will also start a new line. Alignment can be chosen: left, right, centered. Justified works too, but only for Base14 standard fonts.

### Pros
* Returns a float:
    - if not negative, the text was successfully put in the box, the number indicates, how much space is unused (which can be used to adjust the position of a subsequent box).
    - if negative, the box is too small for the given combination of fontsize, text amount.
* Can write rotated text (by any angle 0, 90, 180, 270 degrees) in a given box.

### Cons
* All font characteristics are **fixed** for a given box: font, font size, font color.

## `TextWriter`
This is a fairly new feature in PyMuPDF. A text writer is something like a text store. It must be filled with text - outputting to a page is a separate step.

### Pros
* Free choice of font and fontsize for every text piece.
* When inserting text, the last filled text position is returned as well as the overall rectangle of text stored so far.
* Text opacity can be specified
* Text output can be "morphed", i.e. modified by matrix to achieve things like rotation and more.
* For arbitrary fonts, you can check the space a given string will occupy before outputting it.
* Automatic font fallback: if a character is not supported in the chosen font, it will be looked up in and taken from a fallback font. This way, arbitrary mixtures of extended Latin, Greek, Cyrillic and CJK text characters can be output without added effort.

### `TextWriter.fillTextbox()`
Is similar to `insertTextbox()`: give it a rectangle, a font, fontsize and some text.

#### Pros
* mixing different fonts in the same text box
* mixing fillTextbox and simple text output to the same text writer

#### Cons
If a text box cannot hold all of the text, there currently is a warning only - no return info that can programmatically be used. I have a simple fix if you want to use this feature.

**Comment by a22349** [comment]
ok , will try use these infos you supplied . thanks .

**Comment by JorjMcKie** [comment]
Keep your spirits up!
Do not hesitate to come back when your are stuck somewhere, have questions, whatever.

**Comment by JorjMcKie** [comment]
As per the `TextWriter.fillTextbox()` you may want to look at [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/textwriter/textwriter-textbox.py) example.
