### ISSUE TITLE
Question / Comment:

### ISSUE THREAD

**Issue by sarath0993** [pymupdf/PyMuPDF#590]
When I extract data as blocks, font name gets trimmed after 32 characters. How to get full font name same as given in PDF?

**Example:**
Font name `HXWOFA+AkzidenzGroteskBE-Regular` extracted as `HXWOFA+AkzidenzGroteskBE-Regula`
Font name `RMWBPG+MonsterFonts-HouseofDeath` extracted as `RMWBPG+MonsterFonts-HouseofDeat`

**Sample code:**
`    blocks = page.getText("dict", flags=11)["blocks"]`
   `for b in blocks:  # iterate through the text blocks`
        `for l in b["lines"]:  # iterate through the text lines`
            `for s in l["spans"]:  # iterate through the text spans`

**Comment by JorjMcKie** [comment]
Can you please check, whether the full name is extracted by the MuPDF cli tool `mutool -draw -o test.html input.pdf`?
Then open `test.html` with a text editor.

Currently I cannot see any place in my code where I might be truncating this field.
If the file is not big you can also post it here, so I can check what happens where.

**Comment by sarath0993** [comment]
Hi @JorjMcKie , Thanks for your reply. BTW I have checked the html output from `mutool draw` option, It returns the font name without subset. Please see below
MonsterFonts-HouseofDeath extracted as `MonsterFonts,serif` when using `mutool draw..` option

But when using `mutool info` option, it shows exact font name as shown below
`34	(1198 0 R): Type1 'RMWBPG+MonsterFonts-HouseofDeath' WinAnsiEncoding (1196 0 R)`

Please suggest an idea to get full fontname, I have attached sample pdf below
[test_fontname.pdf](https://github.com/pymupdf/PyMuPDF/files/5083006/test_fontname.pdf)

**Comment by JorjMcKie** [comment]
Thanks for the PDF, I will try to find the spot where all that happens.
The ``info`` function of `mutool` corresponds to `doc.getPageFontList()` - this will also show the full length.

**Comment by sarath0993** [comment]
@JorjMcKie Yes sure, I can wait untill you figure out something related to this issue. Thanks

**Comment by JorjMcKie** [comment]
> BTW I have checked the html output from mutool draw option, It returns the font name without subset. Please see below
MonsterFonts-HouseofDeath extracted as MonsterFonts,serif when using mutool draw.. option

Additional output formats generated by mutool reveal, that this is something inherent in the MuPDF C library:
* as you write, html output only comprises the font **_family_** (even shorter than the font name!)
* xml outputs the same font name as does PyMuPDF, e.g. ``<font name="MonsterFonts-HouseofDeat" size="24">``

So unfortunately there is nothing that can be done about it - except that I could also fall back to just outputting the font family name (which seems to just strip off any suffix starting with "-" of the font name).

**Comment by sarath0993** [comment]
@JorjMcKie Hey, Sorry for not replying to you. I will check other options and ask you still if I need your help. Thanks for your reply
