### ISSUE TITLE
Formula for zooming

### ISSUE THREAD

**Issue by Zain-Bin-Arshad** [pymupdf/PyMuPDF#592]
First of all THANKS for this package, without this I wouldn't be able to complete my project.

I am creating a PDF Viewer in pure python. As you can search on web there are no feature rich PDF Viewers that are written in Python. I am done with various features like:

- Searching through PDF
- Taking notes
- Table of content tree etc

Now, I am implementing **Zooming feature**, I know that `fitz.Matrix()` is the function that is going to help me. But, I can't find a generic way of how zooming calculations works. For example:

- The "Fit to page" feature, that zoom the page in the given area. I found out that `Matrix(1.5, 1.5)` zooms page to exactly fit my area, but when I used same Matrix for some other PDF file it didn't work quite as well. So surely we can't hard code the value. 
- When user says zoom it to 50%, how will we calculate the Matrix ?

I am stuck here, kindly help me out. If you want to see the PDF viewer, have a look:
![G3fQZFE74s](https://user-images.githubusercontent.com/49767636/90280167-e7d80f00-de83-11ea-96bf-6db659b88dc3.gif)

**Comment by JorjMcKie** [comment]
Best have a look at [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/doc-browser.py) example script. Written using PySimpleGUI as a wrapper for a plethora of underlying GUI packages.
But that's not the point: contained therein is a calculation for deterimining the appropriate zoom factor when the available screen area is known.
It also has a (somewhat rudimentary) zooming feature, which offers a fixed zoom into a page dividing it into 3 x 3 page subareas, fitting that said available window.
The basic calculation goes like this:
1. you know the screen window's size, width / height.
2. you know the page size `page.rect`
3. determine whether you have to fit to the window's height or width, depending on the page's width:height ratio (assuming that you want to show the full document page).
4. Let's assume that the page height is the value you need to fit. The page's pixmap without zooming will generate an image with dimensions of `page.rect.irect`. Use the relation of the height of this `IRect` to the available screen height to determine the zoom factor to use for the matrix. Then the page's pixmap should have a height equal to what you can display.

**Comment by JorjMcKie** [comment]
BTW: from the features observable in your nice video, there is no need to restrict yourself to just PDFs. All the stuff shown should work for all supported documents ...

**Comment by Zain-Bin-Arshad** [comment]
I was like 101% sure that you are going to give link to that document. Let me say this **You can't believe how much relieved I was when I came across that "doc-browser.py" file. I didn't want to use Tkinter and your example should me the right path. From there I start learning PySimpleGUI and Fitz**.

Well, I am going to try to convert your comments to code, lets hope I will. About supporting all documents, for now I am going to get it done for PDFs, then I will release another version in English as you can see this is in "Urdu". In that version I will surely add all the features and documents support I can.

Plus, I have to convert my code to `.exe` file, I was worried but after you commented I just looked your profile and came across "Nutika" I think its some kind of exe maker, I want only for windows and I am using following modules:

- PySimpleGUI
- fitz
- pbkdf2
- Crypto

I hope if I give Nutika a read I can use it for creating a standalone exe file that will work in windows 10. Thanks again sir you are a life saver :)

**Comment by Zain-Bin-Arshad** [comment]
I was like 101% sure that you are going to give link to that document. Let me say this **You can't believe how much relieved I was when I came across that "doc-browser.py" file. I didn't want to use Tkinter and your example should me the right path. From there I start learning PySimpleGUI and Fitz**.

Well, I am going to try to convert your comments to code, lets hope I will. About supporting all documents, for now I am going to get it done for PDFs, then I will release another version in English as you can see this is in "Urdu". In that version I will surely add all the features and documents support I can.

Plus, I have to convert my code to `.exe` file, I was worried but after you commented I just looked your profile and came across "Nutika" I think its some kind of exe maker, I want only for windows and I am using following modules:

- PySimpleGUI
- fitz
- pbkdf2
- Crypto

I hope if I give Nutika a read I can use it for creating a standalone exe file that will work in windows 10. Thanks again sir you are a life saver :)

**Comment by JorjMcKie** [comment]
I was a contributor to Nuitka (had to give it a pause for continuous internet issues), so I am sure you can use it. Take the `--standalone` feature. I think all the modules you named will be no problems for Nuitka.

**Comment by Zain-Bin-Arshad** [comment]
Hello sir, is there away I can invert the color of a page ? I am trying to include "Night Mode" feature. It will be very naive at start, just inverting the page. As most of the PDFs have white background and white text color. Inverting the colors will do a purpose for now.

I know if we set the "alpha=true" the white background disappear but how to make text white instead of black? thanks

**Comment by JorjMcKie** [comment]
This is a pixmap method `pix.invertIRect()`.

**Comment by Zain-Bin-Arshad** [comment]
Thanks sir, not only completed the Zooming part but also the night mode. I hope you find more success 🥇
