### ISSUE TITLE
Question / Comment:Crop an area of pdf around annotated text using Fitz

### ISSUE THREAD

**Issue by JacobAtExp4531** [pymupdf/PyMuPDF#593]
**Problem Statement**

1. Reading pdf and search for a word.
2. If word found, annotate the word and get an area cropped around the annotated text from the pdf file.
3. Each cropped image should only have one annotation.

**Libraries and Versions**
- python-3.6
- fitz-0.0.1.dev2
- pymupdf-1.17.5

**Issue facing**
For the first two iterations the annotation is perfect and cropping also works perfectly as expected. But by iterating for next occurence of search word from text instances then crop around that area as well as annotation of search word gets failed. Can't Find a solution for this problem.

   ` 

    import fitz
    
    def cropPdf( pdfName,word):
        c=0
        fitz_doc=fitz.open(pdfName)
        fitz_page=fitz_doc[0]
        text_instances=fitz_page.searchFor(word)
        for text_cord in text_instances:
            c=c+1
           # x0,y0,x1,y1=text_cord[0],text_cord[1],text_cord[2],text_cord[3]
           # cropPdf(x0,y1,searchWord,c,pdfName,text_instances,page,fitz_doc)
           #setting the cordinates of the window to crop
           pdfPath = "./" + pdfName + ".pdf"
           highlight = fitz_page.addRectAnnot(text_cord)
           x0,y0,x1,y1=highlight.rect
           print("fitz page rect",fitz_page.rect)
           print("fitz page  cropbox",fitz_page.CropBox)
           fitz_page.setCropBox(fitz.Rect(x0+600,y0+600,x0-600,y0-600))
           print("fitz page after set cropBox",fitz_page.rect)
           pix=fitz_page.getPixmap()
           print(fitz_page.number)
           base_name_highlight="output"+str(c)+".png"
           # fitz_doc.save("./highlight_folder/"+base_name_highlight)
           fitz_page.deleteAnnot(highlight)
           pix.writeImage("./highlight_folder/"+base_name_highlight)`

**Expected Result**

![screen1](https://user-images.githubusercontent.com/55494490/90328521-954d3e80-dfba-11ea-9c1e-332a9e88468b.png)

**False Case while Cropping**

![screen2](https://user-images.githubusercontent.com/55494490/90328563-e2311500-dfba-11ea-9d35-c0585f28647c.png)

**Comment by JorjMcKie** [comment]
This looks like a page with changes to its geometry - see [here](https://pymupdf.readthedocs.io/en/latest/faq.html#common-issues-and-their-solutions) and read section "Misplaced Item Insertions on PDF Pages".
Try to do this before inserting an annotation:
```python
if not page._isWrapped:
    page.wrapContents()
```

**Comment by JacobAtExp4531** [comment]
I have specified the code just like you said and still there is no change.

**Comment by JorjMcKie** [comment]
Then I need that PDF to see what is happening - and maybe the script, too.

**Comment by JacobAtExp4531** [comment]
Above specified code is the only thing i have for this issue. 
[A4_4 (1).pdf](https://github.com/pymupdf/PyMuPDF/files/5080778/A4_4.1.pdf)

**Comment by JorjMcKie** [comment]
Found your error:
When change the crop box, then this impact all subsequent references to page coordinates. So before your loop through the hit rectangles, save the old crop box and reset it to that value at the end of each loop.

**Comment by JorjMcKie** [comment]
Should have noticed that before, I must admit.

**Comment by JorjMcKie** [comment]
Depending what your ultimate intention is, there may be better solutions than working with annotations and crop box manipulation:
* You can create partial pixmaps of a page by adding a `clip` parameter - which may be a hit rectangle.
* You do not need hgighlight annotations at all to identify the crop box, or do you?
* You can crate new 1-page PDFs, which only show the hit rectangle (or the clip) of each hit rectangle by using `page.showPDFpage()`.

**Comment by JacobAtExp4531** [comment]
my ultimate aim is to find the searh word and if found then crop  a specific area around the word. I am not fully sure/ clear the solution you have specified. but let me try and will let you know

**Comment by JacobAtExp4531** [comment]
Yes you are correct the solution you have suggested has worked. Also would like to workout the suggestion u have put forward.
Thanks. Closing the issue
