### ISSUE TITLE
misc

### ISSUE THREAD

**Issue by harveyspecter09** [pymupdf/PyMuPDF#595]
can we embed new fonts for an existing pdf using this package?

**Comment by JorjMcKie** [comment]
Sure.
By using one of the text insertion methods, you also reference a font one way or another. That font will then be automatically embedded in the PDF upon save.

**Comment by harveyspecter09** [comment]
@JorjMcKie thanks for your quick response to be precise below are my concerns appreciate your solution at your earliest convenience.

1. Will send realtime PDF file as my input which have embedded & unembedded fonts.
   Expected Output1 : Can we have all fonts embedded
   Expected Output2 : Suppose  if there is Arial Narrow-Bold type 1 can we change it to Arial Narrow-Bold truetype font
   Expected Output3: Change a specific paragraph from one font to another

**Comment by JorjMcKie** [comment]
1. The only unembedded fonts supported by PyMuPDF are the so-called Base-14 fonts: Courier, Helvetica, Times-Roman, each of those in weights normal, italic, bold, bold-italic (which is 12 in total) plus ZapfDingbats plus Symbol - totalling 14. All other fonts are always embedded.You can also use text insertion capabilities, which use embeddable versions of these Base-14.

**Comment by JorjMcKie** [comment]
For topic 3 there exists some sort of an "approximation" (!) when you use redaction annotations:

1. locate the rectangle of that paragraph.
2. extract the text of that paragraph using `page.getText("dict")` which delivers all properties of each text piece ("span"). Subselect txt pieces contained in that paragraph.
3. Add a redaction annotation comprising the paragraph's rectangle, and then execute `page.apply_redactions()`. This will remove the paragraph.
4. Re-insert the paragraph's text from those data saved before, this time using the desired font. This will position each text piece where it has been before ... **_but_** in general it may not have the same length.

**Comment by JorjMcKie** [comment]
The approach in previous post can of course also be used for the full page:
1. extract text using `page.getText("dict")
2. write the extracted text to the corresponding page of the output using replacement fonts to your liking. The dictionary extracted in step 1 looks like [this](https://pymupdf.readthedocs.io/en/latest/textpage.html#dictionary-structure-of-extractdict-and-extractrawdict).
Special care would be required for images of course ... and some more special cases. The whole approach practically amounts to rebuilding the PDF ...

You would probably need a table upon which you would base font replacement decisions.

**Comment by JorjMcKie** [comment]
Here is a quick draft of something that reads a PDF and write a new PDF with the following features:
* copy all text to output page
* replace fonts in input by some other font
* maintains all text positions
* maintains input text colors
* all fonts are embedded

[repl-fonts.zip](https://github.com/pymupdf/PyMuPDF/files/5091216/repl-fonts.zip)

Use it as a starting point. The following aspect are not (yet) covered:
* Images are ignored (as well as XObjects ...)
* Any drawings (like lines, rectangles ...) are ignored
* No handling of fonts, that should **_not_** be replaced

Can probably be extended to arrive at a pretty good approximation to your intentions.

**Comment by harveyspecter09** [comment]
@JorjMcKie  appreciate your feedback thanks a lot

**Comment by harveyspecter09** [comment]
hi @JorjMcKie  hope you are doing good today. i am a learner out of college

I have tried to build a piece of code with your fitz package probably you can take a look,will be grateful & appreciate your suggestions.

Input - PDF(Helvetica,Helvetica-Bold)
Expected Output - PDF(Courier-Bold Helvetica-Bold) 
Actual Output - PDF(['Font Type: Type0, Font Name: Courier-Bold, Encoding: Identity-H', 'Font Type: Type0, **Font Name: (null)**, Encoding: Identity-H']) missing some characters as well compared to input.

Is there any way that you can help me in successfully fetching all data including images,drawings?

Scenario: Given a PDF , read the current font embedding and convert its encoding from one format to other.
by using your awesome package am able to read current font embedding but unsure on how to change encodings any leads on its implementation?

Scenario : Given a PDF, raise exceptions for irregular font encoding(custom encoding)/irregular font embedding(unembedded fonts) for further processing.

[embeddscript.zip](https://github.com/pymupdf/PyMuPDF/files/5114475/embeddscript.zip)

thanks in advance.
