### ISSUE TITLE
general query for usage of PyMuPDF/fitz

### ISSUE THREAD

**Issue by harveyspecter09** [pymupdf/PyMuPDF#596]
Hi
below are my concerns appreciate your solution at your earliest convenience.

Will send realtime PDF file as my input which have embedded & unembedded fonts.
Expected Output PDF :  Can we have all fonts embedded
Expected Output PDF : PDF Suppose if there is Arial Narrow-Bold type 1 can we change it to Arial Narrow-Bold truetype font
Expected Output PDF : PDF Change a specific paragraph from one font to another

can you specify on how can we achieve using PyMuPDF/fitz

**Comment by JorjMcKie** [comment]
answered that in #595
