### ISSUE TITLE
Question / Comment: How can I silence pymupdf?

### ISSUE THREAD

**Issue by MartinThoma** [pymupdf/PyMuPDF#606]
I receive way to many logging messages from pymupdf, e.g.:

> mupdf: cannot find XObject resource 'Im4'
> mupdf: cannot find XObject resource 'Im1'

Those are not useful to me, because I don't understand what they mean and what I could / should do about them.

The problem is that they seem not to use `logging`. How can I turn them off? Is it even pymupdf or directly mupdf which creates them?

**Comment by JorjMcKie** [comment]
This is the function you are looking for
```
fitz.TOOLS.mupdf_display_errors(value=None)
```

> Show or set whether MuPDF errors should be displayed.
Parameters value (bool) – if not a bool, the current setting is returned. If true, MuPDF errors will be shown on sys.stderr, otherwise suppressed. In any case, messages continue to be stored in the warnings store. Upon import of PyMuPDF this value is True.
Returns True or False

BTW your errors mean that your PDF contains structure errors.

**Comment by MartinThoma** [comment]
Thank you!

**Comment by occludedpixel** [comment]
After upgrading from PyMuPDF 1.23.26 to 1.24.0, running the following code

```
import fitz
import re

garbage = 3
deflate = True
clean = True
no_new_id = True

doc = fitz.open("input.pdf")

ocg_xref = list(doc.get_ocgs().keys())[0]
pages = []
full_matches = []

for p in doc:
  if "Resources" in doc.xref_get_keys(p.xref) and "/XObject" in doc.xref_get_key(p.xref, "Resources")[1]:
    pattern = re.compile("/fzFrm[0,1] ([0-9]+) 0 R")
    re_res = []
    print(f"pg {p.number+1}: {doc.xref_get_key(p.xref, 'Resources/XObject')[1]}")
    for match in pattern.finditer(doc.xref_get_key(p.xref, "Resources/XObject")[1]):
      re_res.append(match.group(1))
      full_matches.append(match.group(0))
    # expect only 1 XObject per page
    if len(re_res) > 0:
      pages.append(p.xref)
 
ocp = doc.xref_get_key(doc.pdf_catalog(), "OCProperties")[1]
ocg_xref = str(ocg_xref)+" 0 R"
if ocg_xref not in ocp:
  sys.exit("OCG not in OCProperties")
new_ocp = ocp.replace(ocg_xref, "")
doc.xref_set_key(doc.pdf_catalog(), "OCProperties", new_ocp)
for i in range(len(pages)):
  #doc.xref_set_key(pages[i], "Resources/XObject", "null")
  val = doc.xref_get_key(pages[i], "Resources/XObject")[1]
  if val == "<<"+full_matches[i]+">>":
    doc.xref_set_key(pages[i], "Resources/XObject", "null")
  else:   
    doc.xref_set_key(pages[i], "Resources/XObject", val.replace(full_matches[i], ""))
  
doc.save("output.pdf", garbage=garbage, deflate=deflate, clean=clean, no_new_id=no_new_id)

doc.close()
```

with [input.pdf](https://github.com/pymupdf/PyMuPDF/files/15172245/input.pdf) gives `MuPDF error: syntax error: cannot find XObject resource 'fzFrm0'` but previously did not show any errors when run with the same file. The above code is meant to remove the OCG PDF layer that the input PDF contains.

The error persists with PyMuPDF 1.24.2. I am on macOS 14.1.1 with Python 3.11.8.

May I know whether this is a bug or is it a change in the error reporting to be more strict?
