### ISSUE TITLE
"undefined symbol: jpeg_resync_to_restart"

### ISSUE THREAD

**Issue by MartinThoma** [pymupdf/PyMuPDF#609]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

After building and installing MuPDF 1.17 and then installing PyMuPDF from source, I get this:

```
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moose/GitHub/PyMuPDF/fitz/__init__.py", line 3, in <module>
    from fitz.fitz import *
  File "/home/moose/GitHub/PyMuPDF/fitz/fitz.py", line 18, in <module>
    from . import _fitz
ImportError: /home/moose/GitHub/PyMuPDF/fitz/_fitz.cpython-38-x86_64-linux-gnu.so: undefined symbol: jpeg_resync_to_restart
```

## To Reproduce (mandatory)

1. Build MuPDF 1.17 on Ubuntu 20.04 with Python 3.8.3 (installed via pyenv) according to this guide: https://github.com/pymupdf/PyMuPDF/wiki/Ubuntu-Installation-Experience
2. `pip install -e .` for pymupf
3. Try to import fitz

## Your configuration (mandatory)
 - Operating system, potentially version and bitness:  Ubuntu 20.04, 64 bit
 - Python version, bitness: 3.8.3, 64 bit
 - PyMuPDF version, installation method (**wheel** or **generated** from source): **generated**

```
>>> import sys
>>> print(sys.version, "\n", sys.platform, "\n")
3.8.3 (default, May 28 2020, 22:05:41) 
[GCC 9.3.0] 
 linux
```

**Comment by JorjMcKie** [comment]
I am not sure if that Wiki is still up-to-date.
Obviously something is wrong with your MuPDF installation - which is a prerequisite for installing PyMuPDF.
I recommend you follow [this](https://github.com/pymupdf/PyMuPDF/blob/master/installation/ubuntu/ubuntu_pymupdf.sh) script instead. I have used it myself recently for installing in my WSL Ubuntu environment.

**Comment by JorjMcKie** [comment]
Found your hickup?

**Comment by MartinThoma** [comment]
Sorry, I'm currently rotating with other tasks and my internet is not working properly (the technician will come on Friday :see_no_evil: ). I'll give it a try tomorrow :-)

**Comment by MartinThoma** [comment]
It works! Thank you!
