### ISSUE TITLE
Question / Comment: How to find common spans/lines/blocks across a set of PDF-pages

### ISSUE THREAD

**Issue by andrei-volkau** [pymupdf/PyMuPDF#613]
I would like to find common spans/lines/blocks across a set of PDF-pages.  I suppose that the best way to do that is the following methodology. 
1. Apply `.getText("dict")` to each page. It will produce a Python dictionary for each PDF-page.
2. Compare Python dictionaries in order to find intersection across them. 

**Question:** Does it sound like a reasonable approach? OR maybe PyMuPDF already has the ability to identify common spans/lines/blocks across a set of PDF-pages? 

**Example:** Let me consider a span that persists on Page 1, Page 2, Page 3, ... It appears at the same coordinates with the same text value which is 'J. Hage'. I would like to find such spans in an automatic way. So basically, I am interested in finding repeating spans/lines/blocks across a set of PDF-pages.

```
'spans': [{'bbox': (359.6025390625,
                                            36.11228942871094,
                                            385.52032470703125,
                                            44.48733901977539),
                                   'color': 0,
                                   'flags': 4,
                                   'font': 'GJDAOL+AdvP49E930',
                                   'size': 8.468199729919434,
                                   'text': 'J. Hage'}],
                        'wmode': 0}],
```

**Comment by JorjMcKie** [comment]
> OR maybe PyMuPDF already has the ability to identify common spans/lines/blocks across a set of PDF-pages?

Certainly not. PyMuPDF (like its basis MuPDF) is a library for **_building_** solutions. Not for solutions themselves. There is a [repo](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples) with a few examples. I wrote them all, over a period of several years, and most of them out of my own interests, some others to demonstrate PyMuPDF's capabilities.

But yes, your approach does make sense. Depending on the amount of congruence, comparing even lines may be possible, too.

**Comment by andrei-volkau** [comment]
@JorjMcKie, thank you for resolving the question! Closing the issue.
