### ISSUE TITLE
Question on: page.searchFor(sentence, hit_max=100, quads=True)

### ISSUE THREAD

**Issue by zeusrb** [pymupdf/PyMuPDF#616]
There must be something I'm missing, maybe something related to searching unicode chars?
My configuration:
Win 10
Python 3.7
PyMupdf 1.17.5
I'm searching a long Italian sentence in a pdf file if sentence contains a word with accent (i.e.: 'qualit**à**' ).
Any other sentence is found correctly.

1. sentence is lower case, the page content is upper case
2. sentence contains new line same as the page txt
3. sentence contain mono or multiple spaces same as the page txt
4. all the above should be managed by page.searchFor() so sentence should be found in the page text, infact normally it works with no issue.

I would neet the rl list Quad point to iterate into it and add highlight.
                    for ix, k in enumerate(rl):
                        if not k.isEmpty and k.isConvex:
                            annot = page.addHighlightAnnot(k)
...... but:

                    rl = page.searchFor(sentence, hit_max=100, quads=True)
 **rl is empty**

if I search:
                    rl = page.searchFor(sentence[0:410], hit_max=100, quads=True) 
**rl is a list of quads**

**Please note that if I evaluate:**
rl = page.searchFor(sentence[0:411], hit_max=100, quads=True)
**again rl is empty, please note that the 412th char is the accented 'à'**

and so on, if I search a string without accented char the sentence/string is found, as soon as I include an accented letter in the sentence to search, the search return an empty rl.

Is there somethint I need to do to find words or sentences containing accented letters? Any suggestion on a different approach to build the rl Quad list?
TNX!

**sentence** =
' 
 
ergin srl    tel. 035540300    cf e p.iva 03201010547    capitale sociale 10.000,00  
sede legale: strada rocca sparviera, 48 – 15067 novi ligure (al) 
sede operativa: via sorte, 17 – 24030 barzana (bg) 
 
novi ligure, 08/04/2020 
                            
 
 
lavori di taglio e deramificazione piante 
lungo linea elettrica mt di enel distribuzione 
 
 
la sottoscritta marina paola persano, in qualità di legale rappresentante della società ergin srl con'

**Text in first page (pdf document made of one page) coming from page.getText():**
' 
 
ERGIN SRL    Tel. 035540300    CF e P.IVA 03201010547    Capitale Sociale 10.000,00  
Sede Legale: Strada Rocca Sparviera, 48 – 15067 Novi Ligure (AL) 
Sede Operativa: Via Sorte, 17 – 24030 Barzana (BG) 
 
NOVI LIGURE, 08/04/2020 
                            
 
 
LAVORI DI TAGLIO E DERAMIFICAZIONE PIANTE 
LUNGO LINEA ELETTRICA MT DI ENEL DISTRIBUZIONE 
 
 
LA SOTTOSCRITTA MARINA PAOLA PERSANO, IN QUALITÀ DI LEGALE RAPPRESENTANTE DELLA SOCIETÀ ERGIN SRL CON SEDE 
LEGALE SITA IN STRADA ROCCA SPARVIERA, 48 15067 – NOVI LIGURE (AL) IN QUALITÀ DI IMPRESA ESECUTRICE 
  
RENDE NOTO 
 
CHE L’IMPRESA SOPRA MENZIONATA HA ASSUNTO L’ESECUZIONE DEI LAVORI DI TAGLIO/POTATURA PIANTE E SFALCIO ERBA SUL 
TERRITORIO DELLA ZONA DI UDINE (CONTRATTO DI APPALTO N° 8400128637) 
 
 
RENDE NOTO ALTRESI’ 
 
 
CHE DURANTE IL PER PERIODO COMPRESO TRA 09/04/2020 AL 31/07/2020 SONO PROGRAMMATI INTERVENTI PRESSO 
LE LINEE ELETTRICE E-DISTRIBUZIONE (LCL DI RIFERIMENTO 6301831752). 
 
 
AVVISA 
 
I PROPRIETARI DEL SUOLO SOTTOSTANTE DELLA LINEA ELETTRICA IN ARGOMENTO CHE DURANTE IL PREDETTO PERIODO VERRANNO 
EFFETTUATI LAVORI DI TAGLIO PIANTE, RIPRISTINO CESSE AREE BOSCATE, DERAMIFICAZIONE DI ALBERI ECC. AL FINE DI METTERE IN 
SICUREZZA I CONDUTTORI ED EVITARE INTERRUZIONI DI ENERGIA ELETTRICA. 
 
 
INFORMA 
 
CHE IL LEGNAME RESIDUO RIMARRÀ ALL’INTERNO DELLA CESSA A DISPOSIZIONE DEI PROPRIETARI STESSI MENTRE IL FRASCAME 
VERRÀ ACCATASTATO LUNGO I MARGINI DELLA CESSA, SECONDO LE PRESCRIZIONI TECNICHE CONTRATTUALI E FORESTALI. 
I PROPRIETARI DEI TERRENI INTERESSATI DAI LAVORI POSSONO, EVENTUALMENTE, CHIEDERE CHIARIMENTI AL N° 035/540300 
DURANTE IL NORMALE ORARIO DI UFFICIO. 
 
 
                                                                                       IL LEGALE RAPPRESENTANTE 
 
 
  
'

**Comment by zeusrb** [comment]
[20200724_062804_ap_bfabdfa07bb3850cdf7a04b83d0f3862.pdf](https://github.com/pymupdf/PyMuPDF/files/5125012/20200724_062804_ap_bfabdfa07bb3850cdf7a04b83d0f3862.pdf)

**Comment by JorjMcKie** [comment]
UTF8 strings are no problem. But there may be several complications:

1. If you specify **"à"**, search will **_not find_** **"À"**, because it doesn't understand that it is the upper case of the first.
2. What you see on the page may not be the sequence as the text is stored. Every single letter can be specified separately, kilometers (😎) apart from each other and in arbitrary sequence, in which case search would never find it. If you paste the word (e.g. my user id) from the screen to somewhere else in such cases, you may get "i e Mc K rj Jo".

So, opposed to your voiced expectations, `page.searchFor()` is not a carefree thing.
Here a few tests with your file:
```python
>>> page.searchFor("società")
[]
>>> page.searchFor("societÀ")
[Rect(406.8699951171875, 178.33999633789062, 411.94256591796875, 189.37998962402344), Rect(411.9100036621094, 179.8699951171875, 439.050537109375, 188.8699951171875)]
>>> page.searchFor("qualità")
[]
>>> page.searchFor("qualitÀ")
[Rect(232.71800231933594, 179.8699951171875, 265.50152587890625, 188.8699951171875), Rect(343.6209716796875, 193.30999755859375, 376.4134826660156, 202.30999755859375)]
>>> text=page.getText()
>>> page.searchFor(text[0:413]) # delivers all the rects you expect, where
>>> text[400:413]
' IN QUALITÀ D'
>>>
```
But there are more weird things happening. E.g. the highlights do not go where they should ...
Need some time for checking those out.

**Comment by JorjMcKie** [comment]
Here is some further analysis, underpinning my previous comments. I walked through the text blocks, surrended each with a rectangle and marked it with the block number.
This block number equals the sequence in which a "naive" text extraction like getText() will extract the text:
[x.pdf](https://github.com/pymupdf/PyMuPDF/files/5125696/x.pdf)
I think it is obvious that any search for text crossing block boundaries will lead to unexpected / unwanted results when trying to highlight it somehow.
So you will probably have to use block information (`Page.getText("dict") output) to limit search accordingly.

**Comment by JorjMcKie** [comment]
But you could do this to highlight lines of text between two given start / stop point:
```python
wordlist = page.getText("words")
wordlist.sort(key=lambda w: (w[1], w[0]))  # sort vertical, then horizontal
for w in wordlist:
    if w[4] == "LAVORI":  # choose a word to start marking
        pointa = fitz.Point(w[:2])  # top left of work rectangle
        break
for w in wordlist:
    if w[4] == "AVVISA":  # some word for stopping the marking
        pointb = fitz.Point(w[2:4])  # bottom right of word rectangle
        break

page.addHighlightAnnot(start=pointa, stop=pointb)  # a less well known form of hightlight annotations
```
This will nicely give you this result:
![grafik](https://user-images.githubusercontent.com/8290722/91217897-3d16ea80-e6e6-11ea-8053-c1f7b19e47ba.png)

**Comment by zeusrb** [comment]
Thank-you Sir! I'll have a look tomorrow and try your suggestions.
Will provide you some feed-back!
😉

**Comment by zeusrb** [comment]
Ciao @JorjMcKie ,

I've made some change to my code and in terms of single words everything works as expected  as you kindly suggested.

My issue is to find the end point, because (generally speaking), if I search the page for the last word of the sentence, word by word in the wordlist, I can find other occurrences that might be part of page before or after the context of the sentence.
That's the reason why I was using the page.searchFor, trying to match exaclty the sentene ang get the Quads, inside the whole page.getText('text').

Page.addHighlightAnnot(start=pointa, stop=pointb), would make the highlight faster given the pointa = rl[0] and pointb = rl[-1] , in light of what you smartly suggested.

My understanding is that there is no way to make the searchFor() on lowered page, like str.lower() would trasform "À" in "à" and so forth, making them fully comparable.
Do I understand correctly? Any existing flag I could use? Any hope to get it in the future?

Otherwise I'm thinking to split the sentence in sub-sentences, removing words with accent, perform the searchFor, highlight everything between leftmost-upper corner and rightmost lower corner of first and last "cleaned" sub-sentences (checking the corner cases, where an accented word could be the first or the last in the first or last sub-sentence, case where they would be not highlighted .... keeping in mind your suggestion about using block information.

No rush .....

**Comment by JorjMcKie** [comment]
I still recommend using the word list in your case. You have seen me using a sorted version of it: first key vertical, second key horizontal coordinate. If you use a second copy of that sorted list, you should be where you want to be: simply take ``wordlist2 = reversed(wordlist)`` In that word list the first occurrence of "AVVISA" is the geometrically last occurrence of that word on the page.

In **_Python_** you have no problem using ``upper()`` / ``lower()``: ``"QUALITÀ".lower() = "qualità"``. But ``searchFor`` is written (MuPDF) in C where this does not work, and there is no way for me to take influence.

You can also use other Python string methods: ``"avvisa" in word``, ``word.endswith("avvisa")`` etc.

**Comment by zeusrb** [comment]
Yeap, I saw wordlist has the words in the right order and is the safer way to read the text contents.
The **reversed(wordlist)** is what I did try today, in the second loop also using w[4].lower() to compare, but this is falling in the case where if the wordlist contains the last word of sentence into another position after the end of the sentence.
i.e. take "taglio" as example being the end of another sentence (3 occurrences in the page).

The **for w in reversed(wordlist)**  will find the last occurrence, which might be out of the sentence to highlight.... 

Another option is to get the occurrence being in the wordlist within the sentence lenght .... a kind of word off-set check....

**Comment by zeusrb** [comment]
btw, the case of wrong occurence picked-up, might occur also with the first word, if present multiple time and not being the first occurrence the one to be taken because the sentence is in the middle of the page .....

**Comment by JorjMcKie** [comment]
> As you might understand, the pdf and the sentence provide are just examples taken out of ten of thousands ... :-(

Yes I do. Difficult indeed, and maybe there is no perfect solution at all. You should however be able to achieve better results if you combine several of the ``getText(opt)`` alternatives:
If you know a little more then just one word of how your highlight area starts and ends, loop through the **_text spans_** in dictionary getText("dict"). A text span contains all the text of one line as long as there is no change of font attributes (font, font size, font color, font weight). So with some luck `span["text"]` equals the full line text.
Spans have their own rectangle (bbox). This may be better than fighting with single word uniqueness issues.
So the highlight start would be a span's bbox top-left, and another span's bbox bottom-right.
Of course, the spans would have to be sorted in the same way as before.

**Comment by JorjMcKie** [comment]
continuing ...
If the start of highlighting (or its end) do not coincide with a span's bbox top-left (resp. bottom-right), look the respective word position in the word list - but restrict the lookup to words with rectangles inside that span bbox.
Hope I was clear ...

**Comment by zeusrb** [comment]
Ok then, short recap, I should
get Page.getText('dict'), 
get the blocks (type 0 only) and sort blocks
for each block get the lines and sort lines
for each line get the spans and sort spans
get the span["text"], compare somehow with sentence and get back and play with the bbox points (ur for the first and lr for last).
..... first time I play so deep in pdf .... crossing fingers ;-)

**Comment by JorjMcKie** [comment]
😊 It is a tiny little bit simpler:

```python
span_list = []
flags = fitz.TEXT_PRESERVE_LIGATURES | fitz.TEXT_PRESERVE_WHITESPACE  # omits images
blocks = page.getText("dict", flags=flags)["blocks"]
for block in blocks:
    for line in block["lines"]:
        span_list.extend(line["spans"])  # all text is in a span under span["text"]

span_list.sort(key=lambda span: (span["bbox"][3], span["bbox"][0]))  # sort the spans as discussed
```

**Comment by JorjMcKie** [comment]
It's not quite that bad - look at this:

```python
import fitz

doc = fitz.open("test.pdf")
page = doc[0]
line_list = []
flags = fitz.TEXT_PRESERVE_LIGATURES | fitz.TEXT_PRESERVE_WHITESPACE  # omits images
blocks = page.getText("dict", flags=flags)["blocks"]
for block in blocks:
    for line in block["lines"]:
        line_list.append(line)


line_list.sort(key=lambda line: (line["bbox"][3], line["bbox"][0]))
for line in line_list:
    text = ""
    for span in line["spans"]:
        text += span["text"]
    print(text)
```
Produces
```
NOVI LIGURE, 08/04/2020



LAVORI DI TAGLIO E DERAMIFICAZIONE PIANTE
LUNGO LINEA ELETTRICA MT DI ENEL DISTRIBUZIONE


LA SOTTOSCRITTA MARINA PAOLA PERSANO, IN QUALITÀ DI LEGALE RAPPRESENTANTE DELLA SOCIETÀ ERGIN SRL CON SEDE
LEGALE SITA IN STRADA ROCCA SPARVIERA, 48 15067 – NOVI LIGURE (AL) IN QUALITÀ DI IMPRESA ESECUTRICE

RENDE NOTO

CHE L’IMPRESA SOPRA MENZIONATA HA ASSUNTO L’ESECUZIONE DEI LAVORI DI TAGLIO/POTATURA PIANTE E SFALCIO ERBA SUL
TERRITORIO DELLA ZONA DI UDINE (CONTRATTO DI APPALTO N° 8400128637)


RENDE NOTO ALTRESI’


CHE DURANTE IL PER PERIODO COMPRESO TRA 09/04/2020 AL 31/07/2020 SONO PROGRAMMATI INTERVENTI PRESSO
LE LINEE ELETTRICE E-DISTRIBUZIONE (LCL DI RIFERIMENTO 6301831752).


AVVISA

I PROPRIETARI DEL SUOLO SOTTOSTANTE DELLA LINEA ELETTRICA IN ARGOMENTO CHE DURANTE IL PREDETTO PERIODO VERRANNO
EFFETTUATI LAVORI DI TAGLIO PIANTE, RIPRISTINO CESSE AREE BOSCATE, DERAMIFICAZIONE DI ALBERI ECC. AL FINE DI METTERE IN
SICUREZZA I CONDUTTORI ED EVITARE INTERRUZIONI DI ENERGIA ELETTRICA.


INFORMA

CHE IL LEGNAME RESIDUO RIMARRÀ ALL’INTERNO DELLA CESSA A DISPOSIZIONE DEI PROPRIETARI STESSI MENTRE IL FRASCAME
VERRÀ ACCATASTATO LUNGO I MARGINI DELLA CESSA, SECONDO LE PRESCRIZIONI TECNICHE CONTRATTUALI E FORESTALI.
I PROPRIETARI DEI TERRENI INTERESSATI DAI LAVORI POSSONO, EVENTUALMENTE, CHIEDERE CHIARIMENTI AL N° 035/540300
DURANTE IL NORMALE ORARIO DI UFFICIO.


                                                                                       IL LEGALE RAPPRESENTANTE




ERGIN SRL    Tel. 035540300    CF e P.IVA 03201010547    Capitale Sociale 10.000,00
Sede Legale: Strada Rocca Sparviera, 48 – 15067 Novi Ligure (AL)
Sede Operativa: Via Sorte, 17 – 24030 Barzana (BG)
```

**Comment by JorjMcKie** [comment]
As every line has also a bbox, you can now use the above indicated search algorithm **_with lines_** (instead of spans).

Should work fine as long as you have no ill-built PDFs, where lines with minimal vertical coord differences actually should be regarded as one. But your test will surely show this.

**Comment by JorjMcKie** [comment]
Or simplify a little more:
```python
import fitz

doc = fitz.open("test.pdf")
page = doc[0]
line_list = []
flags = fitz.TEXT_PRESERVE_LIGATURES | fitz.TEXT_PRESERVE_WHITESPACE  # omits images
blocks = page.getText("dict", flags=flags)["blocks"]
for block in blocks:
    for line in block["lines"]:
        text = ""
        for span in line["spans"]:
            text += span["text"]
        line_list.append((fitz.Rect(line["bbox"]), text))

line_list.sort(key=lambda line: (line[0].y1, line[0].x0))
for line in line_list:
    print(line[1])
```
Here, the line_list only contains items ``(rect, text)`` for each line ...

**Comment by zeusrb** [comment]
oooh man Thanks!  I wrote already about 100 line of code and had issues with some spans with only one letter to be combined with the other, which (of course) your snippet doesn't have ..... well what can I say, I've learned a lot meanwhile!!

And yessss.... rethinking about it, why should I sort every container..... if I can simply sort the lines.
Now I start to see the rectangles looking at a pdf file I feel like RicKMupdf ..... :-))) 

Big leap ahead, will share the result .... thank-you Sir!

**Comment by JorjMcKie** [comment]
You are very welcome. Glad to see you find PyMuPDF useful.

**Comment by JorjMcKie** [comment]
> which (of course) your snippet doesn't have 

I **_did_** have that, too - before I wondered why on earth I am fiddling with those spans at all.

**Comment by zeusrb** [comment]
I'm almost there ..... 
**Clarification needed n. 1:** (I guess this is a recursive question, sorry for that, but I couldn't find anything googling).
Any chance to get rid of the ' ' replacement with '\n' at the end of the funtion? Any secret flag like PRESERVE_NEWLINES?
I've build my own function to get the for each page the **line_list, page_raw_txt = get_pdf_page_text(doc, page4.number)**, elaborating a bit on the piece of code you have suggested, all works like a charm:

def **get_pdf_page_text(doc, p**):
    page = doc[p]
    line_list = []
    text_pg = ''
    flags = fitz.TEXT_PRESERVE_LIGATURES | fitz.TEXT_PRESERVE_WHITESPACE  # omits images
    blocks = page.getText("dict", flags=flags)["blocks"]
    for block in blocks:
        for line in block["lines"]:
            text = ""
            for span in line["spans"]:
                text += span["text"]
            line_list.append((fitz.Rect(line["bbox"]), text))

    line_list.sort(key=lambda line: (line[0].y1, line[0].x0))     # Sort the list created

    _for line in line_list:    # rebuild the new lines like print(line[1]) would do, to store the full page contents.
        if line[1] == ' ':
            text_pg += '\n'
        else:
            text_pg += line[1] + '\n'_
    return **line_list**, **text_pg**

**Clarification needed n. 2:**
doing some stuff in the main with previous results, until I'm comparing with the other piece of code:
wordlist = page.getText("words")
wordlist.sort(key=lambda w: (w[1], w[0]))

Using page.getText("words") I get , as per documentation ('_generate a list of words (strings not containing spaces)_'), so no issue on that.
I only noted that while in the **line_list** and **text_pg** I have at line_list[3][1] = "**UNITA** OPERATIVA SISTEMI INFORMATIVI  " where I am missing a single quote used as apostrophe, 
![image](https://user-images.githubusercontent.com/29802059/91662161-ce200400-eae0-11ea-80b9-3a5556c29b1d.png)

while in the wordlist I have the word "**UNITA'**" with single quote at the end.
( yessss again about accents but in a different form used by some people in Italy having English keyboards ... :-(  )
![image](https://user-images.githubusercontent.com/29802059/91662203-1f2ff800-eae1-11ea-9f77-8cdb33ae7401.png)

in other lines I have the apostrophe "‘", both **line_list** and wordlist, contains the apostrophe, in words like "**dell‘Unità**" (I guess, because there is no space,..... what if there was?)
![image](https://user-images.githubusercontent.com/29802059/91662238-66b68400-eae1-11ea-8066-c8a31149ffc7.png)

So, might imagine the reason the single quote "'" and  "‘" are treated differently.
Just wondering ... is this expected behavior .... meaning still M
For the time being I can cope with the single quote, with my own workaround....

For your convenience the pdf file ....
Ciao
[20200724_063606_ap_cfc52bfb12edcfe5b2807caf5e23936c.pdf](https://github.com/pymupdf/PyMuPDF/files/5146982/20200724_063606_ap_cfc52bfb12edcfe5b2807caf5e23936c.pdf)

**Comment by JorjMcKie** [comment]
As for clarification 1:
You could build the page text like this: ``text_pg = "\n".join([line[1] for line in line_list])``. This will not have a trailing `\n`. If I understood you well.
Also, working with "list comprehensions" like this is generally recommended as being highly performant. I should actually have used it too, when building the joint text of the spans in the line: ``text = "".join(s["text"] for s in line["spans"]])``. Instead of appending things to an initially empty list ...

As for clarification 2:
Let me check out the attached PDF. I thought I have made the produced text as equal as possible between the different extraction flavours ... 🙄.
Just as a background info: All of these functions are based on a notion that I am treating as ``class TextPage`` in PyMuPDF. **_Filling_** a text page is done by MuPDF. My functions ("blocks", "text", "words", "dict", "rawdict") just read out what is contained therein - euqally so the MuPDF functions "xml", "xhtml", "html".
What I am aiming at: the extracted text material is only as good / precise as it is present in the text page. This pertains to character encoding, space between characters, decisions on block and line separation, and more.

**Comment by JorjMcKie** [comment]
The character after "dell" in ``dell’Unità`` is **_not_** a single quote, but an apostrophe. It is unicode 8217 and not 39.
Otherwise wordlist contains correctly "``dell’Unità``" as one word, and "dict" extraction delivers me the corresponding line also correctly as "``continuità alla dott.ssa Flavia Leonarduzzi la direzione ad interim dell’Unità Operativa complessa``".

**Comment by JorjMcKie** [comment]
I should have been more precise in describing the names of unicodes:
```python
>>> font.unicode_to_glyph_name(8217)
'quoteright'
>>> font.unicode_to_glyph_name(8216)
'quoteleft'
>>> font.unicode_to_glyph_name(39)
'quotesingle'
>>> 
```
The word "apostrophe" is not the name of any unicode / glyph.

**Comment by zeusrb** [comment]
I'm really enjoining PyMuPDF!
OK, when I was saying ... "_So, might imagine the reason the single quote "'" and "‘" are treated differently_" I meant what you have explained more precisely.
I have to admit, I misread my own results, in fact what I was reporting was a missing quotesingle in the word "UNITA" in the very first occurrence on top of the 1st page, in fact my brain was expecting  "UNITA'", looking at the document, afterword, I realized there's no quotesingle.
That's why I was missing it in the text extracted .... I can assure I have changed my glasses yesterday ... LOL.

Going back to the search, since all this is part of an AI solution, I'm opting for Spacy matching combined with PyMUPDF, because of the **full sentence** matching needs, 
The sentence is going through a Spacy pipe. What I'm coding right now is input the text_pg to the same Spacy pipe and use a Spacy Matcher, keeping the words coordinates to highlight ... it should also be faster having less text.
 .... your thought?

**Comment by JorjMcKie** [comment]
Interesting stuff - I have never worked with Spacy or AI, so I am certainly interested to see how it goes.
I am also happy to see that you like PyMuPDF.
If you want - your time permitting this - you are very welcome to write something in the repo's Wiki - or even publicly. Would be great.

**Comment by zeusrb** [comment]
I will for sure! Not finding the time will not be the excuse.
I'll need to check what I can disclose and what not, maybe a mix of pseudo code and snippets ... ;-)

Thanks again for your help!
How should we proceed with this thread, shall I close it? You close it? We keep it open waiting for some visual results (these I can share, the pdf I'm working on a re public...)?

**Comment by JorjMcKie** [comment]
> How should we proceed with this thread, shall I close it? You close it? We keep it open waiting for some visual results (these I can share, the pdf I'm working on are public...)?

As you wish. Maybe a good idea to keep it open for a while, so others may come across it. I will mark it "resolved" to serve this purpose.
I have to thank you for this interesting and satisfying discussion!

**Comment by zeusrb** [comment]
Not kidding close my issues on this topic yesterday .... so where can I find instructions to write/share something about in the repo Wiki ... first time for me.....  
Cheers!

**Comment by JorjMcKie** [comment]
Oops - you don’t need the issues for this. It’s better anyway to write an article in the Wiki of the repo, that is exactly what it is there for.

**Comment by houdataali** [comment]
Hello am using this function to highlight the phrases contained in highlight text (may contain phrases from different locations at a single page) it's working. but the issue is all the occurrences got highlighted then even the stop words or some words existing somewhere in the page 
def show_pdf(pdf_file,page_number,highlight_text):
    pdf_document = fitz.open(pdf_file)
    pdf_page = pdf_document[page_number - 1]
    highlight_words=highlight_text.split(" ")
    for word in highlight_words:
        text_instances = pdf_page.search_for(word)
        if text_instances:
            for inst in text_instances:
                print(inst, type(inst))
                highlight = pdf_page.add_highlight_annot(inst)
                highlight.update() 
    output_path = "highlighted_output.pdf"
    pdf_document.save(output_path, garbage=4, deflate=True, clean=True)
    with open(output_path, "rb") as pdf_output:
        modified_pdf_content = pdf_output.read()
        base64_pdf = base64.b64encode(modified_pdf_content).decode('utf-8')
    pdf_display = f'<iframe src="data:application/pdf;base64,{base64_pdf}#page={page_number}" width="800" height="800" type="application/pdf"></iframe>'
    st.markdown(pdf_display, unsafe_allow_html=True)
any suggestions please ?

**Comment by JorjMcKie** [comment]
Sorry @houdataali - but your code is unreadable. Please resend with proper indentation: wrap your code with two lines, each containing 3 back ticks.

**Comment by houdataali** [comment]
<img width="1138" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/84786211/c362c7e7-4185-4051-a3fa-2072af390f66">

**Comment by houdataali** [comment]
here is the function that am using and the issue is since I split by whitespace it just goes to the corresponding
 page and highlight all the occurrences but this is not what I want , I tried to split by '\n' but I figure out that the engine is incapable to search for the whole sub-phrases
