### ISSUE TITLE
Question / Comment: Not Seeing Embedded Files

### ISSUE THREAD

**Issue by pemigra** [pymupdf/PyMuPDF#620]
Hi, I'm attempting to use this library to extract what I thought were embedded files in a pdf, but the embedded file methods are consistently unable to see the attachments in the pdf (of which there are many). I'm beginning to think that there are alternate methods by which a file can be "embedded" into a pdf, and perhaps these alternate techniques render PyMuPDF's embedded methods incapable of detecting them? Thanks for any clarity you can provide.

**Comment by JorjMcKie** [comment]
You sure you are talking about **_embedded_** files and not about **attached** files in annotations appearing on pages?
If yes, I need a (small!) reproducer.

**Comment by pemigra** [comment]
Thanks so much for the quick response. I believe what I have are attached files, appearing on a page with a paperclip icon. I can't share the file because it's confidential (sorry, I know that isn't helpful). I'm trying to understand the distinction, and the Adobe documentation isn't super helpful. I can open and see metadata, etc. with PyMuPDF no problem. Is there a way I can use this library to extract the attached files? Again, thank you.

**Comment by pemigra** [comment]
To clarify, I'm trying to understand the distinction between embedded files and files attached as annotations.

**Comment by pemigra** [comment]
All I want to do is programmatically extract an attached csv file from a pdf, then do other operations on that csv file.

**Comment by JorjMcKie** [comment]
OK.
you iterate over a page's annotations and then check whether it is a file attachment or use:
```python
for annot in page.annots(types=(fitz.PDF_FILE_ATTACHMENT_ANNOT,)):
    file_content=annot.fileGet()  # a bytes object
```

**Comment by JorjMcKie** [comment]
> and the Adobe documentation isn't super helpful.

PyMuPDF's documentation is much better here 😎

**Comment by pemigra** [comment]
Thanks very much. Will give this a try.
