### ISSUE TITLE
Question / Comment: pdfminer not identifying rows then columns

### ISSUE THREAD

**Issue by machine-gurning** [pymupdf/PyMuPDF#621]
Apologies if this is not the place for general assistance. 

I have fiddled with all the command line settings extensively but still can't seem to be able to correctly extract the text from the attached pdf: 

[pdf_miner_output.txt](https://github.com/pymupdf/PyMuPDF/files/5133567/pdf_miner_output.txt)
[reps-vp2.pdf](https://github.com/pymupdf/PyMuPDF/files/5133568/reps-vp2.pdf)

My command for that given output was 
` pdf2txt.py reps-vp2.pdf -o pdf_miner_output.txt --line-margin 1`

I am specifically interested in grouping all the "AYES" vote names together, and all the "NOES" votes together, consistently retrieving the titles AYES and NOES before each. 

The website https://pdftotext.com/ seems to be able to do this consistently

**Comment by JorjMcKie** [comment]
I see no relation to PyMuPDF. You probably landed in the wrong repository.
