### ISSUE TITLE
Question / Comment: setToC takes a lot of time if the TOC has several ten thousand entries

### ISSUE THREAD

**Issue by sant527** [pymupdf/PyMuPDF#623]
I found `doc.setToc()` taking lot of time if pages are more

I have document of 100000 pages. and toc of 40000 entires. I found the following loop is taking lot of time 

Code from `def setToC(doc, toc, collapse=1):` takes lot of time in `utils.py`

```
for i in range(toclen):
        o = toc[i]
        lvl = o[0]  # level
        title = getPDFstr(o[1])  # title
        pno = min(doc.pageCount - 1, max(0, o[2] - 1))  # page number
        page = doc[pno]  # load the page
        ictm = ~page.transformationMatrix  # get inverse transformation matrix
        top = Point(72, 36) * ictm  # default top location
        dest_dict = {"to": top, "kind": LINK_GOTO}  # fall back target
        if o[2] < 0:
            dest_dict["kind"] = LINK_NONE
        if len(o) > 3:  # some target is specified
            if type(o[3]) in (int, float):  # convert a number to a point
                dest_dict["to"] = Point(72, o[3]) * ictm
            else:  # if something else, make sure we have a dict
                dest_dict = o[3] if type(o[3]) is dict else dest_dict
                if "to" not in dest_dict:  # target point not in dict?
                    dest_dict["to"] = top  # put default in
                else:  # transform target to PDF coordinates
                    point = dest_dict["to"] * ictm
                    dest_dict["to"] = point
        d = {}
        d["first"] = -1
        d["count"] = 0
        d["last"] = -1
        d["prev"] = -1
        d["next"] = -1
        d["dest"] = getDestStr(page.xref, dest_dict)
        d["top"] = dest_dict["to"]
        d["title"] = title
        d["parent"] = lvltab[lvl - 1]
        d["xref"] = xref[i + 1]
        lvltab[lvl] = i + 1
        parent = olitems[lvltab[lvl - 1]]  # the parent entry

        if collapse and lvl > collapse:  # suppress expansion
            parent["count"] -= 1  # make /Count negative
        else:
            parent["count"] += 1  # positive /Count

        if parent["first"] == -1:
            parent["first"] = i + 1
            parent["last"] = i + 1
        else:
            d["prev"] = parent["last"]
            prev = olitems[parent["last"]]
            prev["next"] = i + 1
            parent["last"] = i + 1
        olitems.append(d)
```

Is it possible to speed up things.

**Comment by JorjMcKie** [comment]
What do you mean "a lot of time", hours? several minutes?

Well, and in terms of amount of data: 40 K entries in a TOC is a **_lot_** ... and presumably doesn't happen very often.
Extrapolating to this amount of TOC entries on my machine, 40.000 entries would take 47 seconds.

You will have noticed, that for each page number a TOC entry is pointing to, that page is loaded to find its size. The page dimension is required to compute the right target coordinate for the TOC entry. So inserting such a large TOC entails reading 40.000 pages ...

**Comment by sant527** [comment]
Yes, thats true. Then it should be fine.

> for each page number a TOC entry is pointing to, that page is loaded to find its size. The page dimension is required to compute the right target coordinate for the TOC entry.

This is the main reason. I was thinking what is the use of calculating page dimension, rather page number should be sufficient.

**Comment by JorjMcKie** [comment]
The page dimension (value of ``page.rect``) is only known **_after_** reading the page!

A way out might be "caching" page dimensions, so that a page is at least not read multiple times ...

**Comment by JorjMcKie** [comment]
I have been testing a little with this.
You are right, it does take time if you have a TOC with several ten thousand entries. I made a PDF with 100.000 pages and inserted a TOC with 50.000 items this was almost 7 minutes.

But I must say, this is to be expected and cannot really be accelerated given the design of this function. The design goal I had in my mind was an intuitive API, not performance.
"Intuitive" meaning here, that a Python list, looking very much like the table of contents of a normal book, should be the parameter for reading and writing the TOC.
Of course that's not the only way one could do that. Look at PyPDF2 if you want an example for TOC handling, which lets you change only single items, but requires that you deal with the complexity of how this concept is designed in PDF: a double-linked chain of entries with counters to be maintained on certain nodes etc. Try to add a TOC item using this package and you will know what I mean.

**_But:_** What you are doing here, with a giant TOC, for a giant PDF, is simply going to the limits of how this is implemented in PyMuPDF! You either have to wait, or use a different package (or pay me for developping a special solution 😉).
The function will render 40K xref entries unused ("dead flesh") and acquire 40K new xref entries for the new TOC version. If you do that several times, your PDF size will soon grow beyond reasonable limits (10 MB or so each time) - or you must garbage-collect it ... which also takes a long time.

Is has to be questioned also, how much sense such a giant TOC really makes at all - even if the PDF is that large. Every viewer will be put to its limits if you ask it to show the TOC.
And as you observed: if the PDF's catalog has the entry `/PageMode /UseOutlines`, then the viewer must read that 40K TOC **_before showing the first page_** (or do something clever asynchronously).

Anyway there does not happen anything like a "structural change" as you have suspected.
