### ISSUE TITLE
Question / Comment: Slow PDF open in viewers after changing TOC with many thousand items

### ISSUE THREAD

**Issue by sant527** [pymupdf/PyMuPDF#624]
I found that to open a pdf created using pymupdf takes lot of time to open using mupdf viewer.

Any reason.

**Comment by JorjMcKie** [comment]
Please be more specific: only when opening with mupdf, but better with other viewers?, just one specific PDF or every single one? etc.

**Comment by sant527** [comment]
I have `original.pdf`  which is `100,000` pages

Then I have modified  `TOC`  and added it to the `original.pdf`. and saved the pdf as `modified.pdf`

I can open the `original.pdf` in few `ms` where the `modified.pdf` opens after `5 minutes`

 This is the modified file properties

```
$ python -m fitz show -metadata modified.pdf
'modified.pdf', pages: 105694, objects: 1022419, 315.7 MB, PDF 1.3, encryption: None

------------------------------- PDF metadata ------------------------------
       format: PDF 1.3
        title: None
       author: None
      subject: None
     keywords: None
      creator: pdftk 2.02 - www.pdftk.com
     producer: itext-paulo-155 (itextpdf.sf.net-lowagie.com)
 creationDate: D:20200815141519+05'30'
      modDate: D:20200815141519+05'30'
   encryption: None
```

The original.pdf is

```
$ python -m fitz show -metadata original.pdf 
'original.pdf', pages: 105694, objects: 995678, 333.6 MB, PDF 1.3, encryption: None

------------------------------- PDF metadata ------------------------------
       format: PDF 1.3
        title: None
       author: None
      subject: None
     keywords: None
      creator: pdftk 2.02 - www.pdftk.com
     producer: itext-paulo-155 (itextpdf.sf.net-lowagie.com)
 creationDate: D:20200815141519+05'30'
      modDate: D:20200815141519+05'30'
   encryption: None
```

**Comment by JorjMcKie** [comment]
Ahh, this is a very different situation!
Allow me to change the issue title to something like this: after replacing 40.000 TOC entries, the PDF opens slowly ...
* I still wonder whether opening the PDF in Adobe (or another viewer) is any faster.
* how did you save the PDF after changing the TOC: save options garbage, compression, etc.

**Comment by sant527** [comment]
This is the code i am trying

```
import fitz
doc1 = fitz.open("original.pdf")  # open file 1
toc1 = doc1.getToC(False)  # its table of contents (list)
pc1 = len(doc1)  # number of its pages


new_toc = []
for line in toc1:  # read to TOC
    if (line[2] > 999456): 
        line[1]="---"+line[1] # Slightly modifying the toc by adding --- (this is just shown for example)
        new_toc.append(line)
    else:
        new_toc.append(line)

doc1.setToC(new_toc)  # set table of contents for the result
doc1.save("modified.pdf")  # save result to new file
```

> I still wonder whether opening the PDF in Adobe (or another viewer) is any faster.
The comparision is not among mupdf and adobe here. Its between the original and modified file
The `original.pdf` opens in `100ms` where as the `modified.pdf` opens in `5minutes`

**Comment by JorjMcKie** [comment]
> I believe some structural changes are happening in the modified.pdf due to which its taking lot of time to open

* how many entries did the old TOC have?
* how many new entries where created by your script?
* if you do not request garbage collection when saving (which you don't), the new TOC version is added to the PDF (as always) but the old TOC entries will not be deleted
* if the open options of the PDF say that the TOC should be shown, then of course 40.000 entries must be read before you see the first page!

**Comment by sant527** [comment]
So how to convery that to delete the old TOC and use the new one

**Comment by JorjMcKie** [comment]
> So how to convery that to delete the old TOC and use the new one

That's not the point: the new TOC is accepted. The old TOC is simply still present in the file like dead flesh.
