### ISSUE TITLE
Question / Comment: Is there any way to make EPUB annotations using PyMuPDF?

### ISSUE THREAD

**Issue by andrei-volkau** [pymupdf/PyMuPDF#628]
The documentation states that **Annot** class is supported for PDF documents only. Does it mean that PyMuPDF can not be used for annotating(highlighting) EPUB documents at all?

I am specifically interested in highlighting text using colored bounding boxes.

**Comment by JorjMcKie** [comment]
>Does it mean that PyMuPDF can not be used for annotating(highlighting) EPUB documents at all?

Unfortunately yes. MuPDF has dropped that quite some ago. Apart from this fact, **updating** non-PDF documents has never been possible with PyMuPDF. So it is a "No-No".

**Comment by andrei-volkau** [comment]
@JorjMcKie thank you for the info! I am closing the question!
