### ISSUE TITLE
Pixmap partial copy dimension

### ISSUE THREAD

**Issue by PowerSnail** [pymupdf/PyMuPDF#629]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

Pixmap partial copy (``__init__(self, source, width, height[, clip])``) seems to apply ``clip`` not to the source as the document states, but to the new pixmap. So, the original pixmap is first scaled to the specified width and height, and then clipped.

For instance, if I want the left half an image, I would expect to specify `width=source.width / 2, height=source.height, clip=(0, 0, source.width / 2, source.height`. However, this actually produces the whole image, but squeezed into ``width / 2``.

On the other hand, if I were to specify `width=source.width, height=source.height, clip=(0, 0, source.width / 2, source.height)`, I would expect that I have a pixmap of ``width`` equals to ``source.width``. However, the resulting pixmap's width is ``source.width / 2``.

I hope the little snippet below explains this issue better.

## To Reproduce (mandatory)

```
import fitz
whole = fitz.Pixmap("whole.jpeg")
whole
# OUT: Pixmap(DeviceRGB, IRect(0, 0, 1280, 720), 0)
left = fitz.Pixmap(whole, whole.w // 2, whole.h, fitz.Rect(0, 0, whole.w // 2, whole.h))
left
# OUT: Pixmap(DeviceRGB, IRect(0, 0, 640, 720), 0)
left.writeImage("left_a.png")
left = fitz.Pixmap(whole, whole.w, whole.h, fitz.Rect(0, 0, whole.w // 2, whole.h))
left
# OUT: Pixmap(DeviceRGB, IRect(0, 0, 640, 720), 0)
left.writeImage("left_b.png")
```

## Expected behavior (optional)

"left_a.png" to be the correct left half of the image;
"left_b.png" to be of width 1280, and to be a stretched out version of the left half of the image.

## Screenshots (optional)

whole.jpg

![whole](https://user-images.githubusercontent.com/7428673/91654047-6395a680-ea95-11ea-8e37-e3fd6b56e6ab.jpeg)

left_a.jpg

![left_a](https://user-images.githubusercontent.com/7428673/91654048-698b8780-ea95-11ea-86d4-59d4c13e96af.png)

left_b.jpg

![left_b](https://user-images.githubusercontent.com/7428673/91654054-7314ef80-ea95-11ea-98b8-a2374d6735dd.png)

## Your configuration (mandatory)

```python
print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)

# 3.8.5 (default, Jul 25 2020, 21:22:16)
# [GCC 10.1.1 20200625 [revision c91e43e9363bd119a695d64505f96539fa451bf2]]
# linux

# PyMuPDF 1.17.6: Python bindings for the MuPDF 1.17.0 library.
# Version date: 2020-08-26 14:54:32.
# Built for Python 3.8 on linux (64-bit).
```

**Comment by JorjMcKie** [comment]
This function directly invokes a MuPDF function - so works as designed.
But maybe is not described as designed. The following produces what you expect:
```python
>>> page=doc[0]
>>> pix=page.getPixmap()
>>> clip=+pix.irect
>>> clip.x1=clip.width/2
>>> clip
IRect(0, 0, 298.0, 842)
>>> pix2 = fitz.Pixmap(pix, pix.width, pix.height, clip)
>>> pix2
Pixmap(DeviceRGB, IRect(0, 0, 298, 842), 0)
>>> pix2.writeImage("left-halt.png")
>>> 
```

**Comment by JorjMcKie** [comment]
I will change the documentation accordingly.

**Comment by JorjMcKie** [comment]
Updated docu version published.
