### ISSUE TITLE
insertTextBox fill color not workiing

### ISSUE THREAD

**Issue by himat** [pymupdf/PyMuPDF#630]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

I expected that add a `fill` parameter to insertTextBox would fill in the background of the text box. But instead, it is only changing the color of the text itself.
![image](https://user-images.githubusercontent.com/1156974/91680781-61296000-eb1a-11ea-824b-724ab484a096.png)

Is this expected? If I want my inserted text to cover whatever was behind it, should I be adding a shape first to hide the background?

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

```
text_pos_rect = (300, 340, 450, 440)
signature_text = "john james"
fitz_page.insertTextbox(
  text_pos_rect, signature_text, color=(0.3, 0.3, 0.3), fill=(0.5, 0.5, 0.5)
)
```

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

```
3.8.5 (default, Jul 21 2020, 10:42:08)
[Clang 11.0.0 (clang-1100.0.33.17)]
 darwin

PyMuPDF 1.17.6: Python bindings for the MuPDF 1.17.0 library.
Version date: 2020-08-26 14:54:32.
Built for Python 3.8 on darwin (64-bit).
```
PyMupdf installed from PyPI binary

**Comment by JorjMcKie** [comment]
This is a misunderstanding. The fill parameter does not refer to the box fill color, but to the fill color of the text if you use a suitable **_render_mode_**:
> render_mode (int)
> New in version 1.14.9: Integer in range(8) which controls the text appearance (Shape.insertText() and Shape.insertTextbox()). See page 398 in Adobe PDF References. New in v1.14.9. These methods now also differentiate between fill and stroke colors.
> For default 0, only the text fill color is used to paint the text. For backward compatibility, using the color parameter instead also works.
>For render mode 1, only the border of each glyph (i.e. text character) is drawn with a thickness as set in argument border_width. The color chosen in the color argument is taken for this, the fill parameter is ignored.
For render mode 2, the glyphs are filled and stroked, using both color parameters and the specified border width. You can use this value to simulate bold text without using another font: choose the same value for fill and color and an appropriate value for border_width.
For render mode 3, the glyphs are neither stroked nor filled: the text becomes invisible.
The following examples use border_width=0.3, together with a fontsize of 15. Stroke color is blue and fill color is some yellow.

![img-rendermode](https://user-images.githubusercontent.com/8290722/91685214-b881fd00-eb27-11ea-9a33-1a3f03439d90.jpg)

The rectangle itself cannot be filled with this method.

**Comment by himat** [comment]
So what is the best way to fill the background?

**Comment by JorjMcKie** [comment]
take the same rectangle and perform a `Page.drawRect` (resp. `Shape.drawRect`) with desired parameters - and the same morph parameter where applicable.
