### ISSUE TITLE
Scrubbing a document fails when annotations are present with error: NameError: name 'PDF_ANNOT_FILEATTACHMENT' is not defined

### ISSUE THREAD

**Issue by ishineko** [pymupdf/PyMuPDF#631]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When scrubbing a document with document.scrub() the code fails with the following error:

File "C:\apps\Anaconda3\lib\site-packages\fitz\utils.py", line 3409, in scrub
    if annot.type[0] == PDF_ANNOT_FILEATTACHMENT and attached_files:
NameError: name 'PDF_ANNOT_FILEATTACHMENT' is not defined

## To Reproduce (mandatory)
Take a PDF with a couple of annotations (in my case, redact annotations), and then try to scrub the document to sanitize it with document.scrub(). The code fails because the utils.py module tries to check the annotation type for file attachments, and it can't find that constant value.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).
All redaction annotations should have been applied, and all metadata should have been removed.

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
Windows 10. 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] 
 - Python version, bitness
Python 3.7.4.
PyMuPDF 1.17.2: Python bindings for the MuPDF 1.17.0 library.
Version date: 2020-06-20 07:00:22.
Built for Python 3.7 on win32 (64-bit).

 - PyMuPDF version, installation method (**wheel** or **generated** from source).
pip installed.

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
Yeah, the name of that value has changed and didn't pull through this function ``PDF_ANNOT_FILE_ATTACHMENT``. For the time being, best change that directly in the source until the next version.

**Comment by ishineko** [comment]
Sounds good. I'll update the source locally for it.

Thanks for checking, @JorjMcKie ! Really love this library!

**Comment by JorjMcKie** [comment]
Thanks for the feedback and your flexibility!
