### ISSUE TITLE
Question / Comment: Does PyMyPDF support 3D PDF？

### ISSUE THREAD

**Issue by menhuan** [pymupdf/PyMuPDF#634]
i want to write 3D PDF.but i have not find anyway in the documents.

**Comment by JorjMcKie** [comment]
I am not sure what you mean.
If it is just 3D annotations: they are not yet supported and no plans pertaining to their implementation exist so far.

**Comment by menhuan** [comment]
so bad 。

**Comment by JorjMcKie** [comment]
Please provide an enhancement request describing what featrues you exactly would like to see.
That way I have something to include in my plans.

**Comment by menhuan** [comment]
i hope 3d model export one pdf file And the pdf can be rotated,transform size etc。。
