### ISSUE TITLE
Question / Comment: Combine multiple pdfs

### ISSUE THREAD

**Issue by sant527** [pymupdf/PyMuPDF#635]
I want to combine multiple pdfs

input:
file1.pdf
file2.pdf
file3.pdf
file4.pdf

output
total.pdf

I want it to be command line if possible passing params to python script using mupdf

Or even python script also ok

Also i found that i can join using
```
python -m fitz join -o Output.pdf file1.pdf,, file2.pdf,,
```
Can the output be more verbose showing whats happening.

**Comment by JorjMcKie** [comment]
https://pymupdf.readthedocs.io/en/latest/module.html#joining-pdf-documents

**Comment by sant527** [comment]
Can you tell me which function in which file is executed when we run `python -m fitz join`.

**Comment by JorjMcKie** [comment]
As for all packages that are callable via the module ``-m`` parameter: this is ``__main__.py`` in the ``fitz`` folder.
