### ISSUE TITLE
Question / Comment: How to identify whether a span is in bold/italics or not?

### ISSUE THREAD

**Issue by andrei-volkau** [pymupdf/PyMuPDF#636]
Let me consider a few examples regarding `span` properties.  

Example 1. `Span` for a word  **`Rules`**. Please note that the word is in bold.
`{'size': 9.962599754333496, 'flags': 4, 'font': 'GJDBJN+AdvP6960', 'color': 0, 'text': 'Rules', 'bbox': (53.85820007324219, 419.87957763671875, 77.59908294677734, 429.8421936035156)}`

Example 2. `Span` for a statement  `clear what law is`. Please note that the statement is written using a regular text.

`{'size': 9.962599754333496, 'flags': 4, 'font': 'GJDBEM+AdvP6975', 'color': 0, 'text': 'clear what law is.', 'bbox': (53.85820007324219, 276.99560546875, 124.77896118164062, 286.33056640625)}`

Example 3. `Span` for a word `enforcement`. Please note that the original word is in italics.

`{'size': 9.962599754333496, 'flags': 4, 'font': 'GJDBEL+AdvP696A', 'color': 0, 'text': ' enforcement', 'bbox': (196.824462890625, 236.87384033203125, 249.12908935546875, 246.83644104003906)}`

**Question**: How can programmatically identify which span is in bold/italics? 

**My thoughts:** All 3 examples have the same value for the 'flags' key. It looks like I need to look into a value for the 'font' key. Those namings seem to be not human friendly. I mean that I am not able to understand the meaning. It might be possible that those namings are machine friendly. It might be possible that information like bold/italics is already encoded into those namings already. Am I right? Thank you in advance for any info!

**Comment by JorjMcKie** [comment]
This should be found encoded in the ``flags`` parameter, see [here](https://pymupdf.readthedocs.io/en/latest/textpage.html#dictionary-structure-of-extractdict-and-extractrawdict):

```python
>>> if flags & 2**1: print("italic")
>>> # etc.
```

It seems your example always shows flags=4. I have no explanation for this. Always worked in cases I looked at.

**Comment by JorjMcKie** [comment]
BTW you know that there are ways to **_simulate_** bold without actually being it?
In this case no bold property is reflected on extraction.
If the font does not return those properties using the usual functions, then MuPDF neither has the chance to determine it.
To check, create a font ``font=fitz.Font(fontbuffer=...)`` with the binary of the font und look at ``font.flags``.

This is how this works:
```python
>>> for f in doc.getPageFontList(0): print(f)

(12, 'ttf', 'TrueType', 'FNUUTH+Calibri-Bold', 'R8', '')
(13, 'ttf', 'TrueType', 'DOKBTG+Calibri', 'R10', '')
(14, 'ttf', 'TrueType', 'NOHSJV+Calibri-Light', 'R12', '')
(15, 'ttf', 'TrueType', 'NZNDCL+CourierNewPSMT', 'R14', '')
(16, 'ttf', 'Type0', 'MNCSJY+SymbolMT', 'R17', 'Identity-H')
(17, 'cff', 'Type1', 'UAEUYH+Helvetica', 'R20', 'WinAnsiEncoding')
(18, 'ttf', 'Type0', 'ECPLRU+Calibri', 'R23', 'Identity-H')
(19, 'ttf', 'Type0', 'TONAYT+CourierNewPSMT', 'R27', 'Identity-H')
>>> f = doc.extractFont(12)
>>> font=fitz.Font(fontbuffer=f[-1])
>>> font.flags
{'mono': 0, 'serif': 1, 'bold': 1, 'italic': 0, 'substitute': 0, 'stretch': 0, 'fake-bold': 0, 'fake-italic': 0, 'opentype': 1, 'invalid-bbox': 0}
>>> 
```
This is also an example, that these values need not be correct: that font is definitely **_not_** serifed!

**Comment by andrei-volkau** [comment]
Hi Jorj! @JorjMcKie Thank you for the prompt reply!

I agree that this should be found encoded in the flags parameter. But actually I have just `flags=4` for bold, italics, regular, etc.

Sorry, I do not completely understand your second message. Do you mean that a PDF document might be generated in such a way that MuPDF will not be able to distinguish between such font properties like bold, italics, serifed, regular, etc?

If the answer is `yes`, then It looks like I am working with such a bad PDF document.

**Comment by JorjMcKie** [comment]
I am currently without proper internet so have to use smart phone. 
Yes my point was that MuPDF too is dependent on what the font itself  announces about its properties. It doesn’t itself measure character thickness or inclination or whatever.
So I suggested to do a font query like indicated yourself to see what the font has to say about itself.
I am fairly sure you will find confirmed why MuPDF returns flags=4.

Von meinem iPhone gesendet

**Comment by andrei-volkau** [comment]
> Example 1. `Span` for a word **`Rules`**. Please note that the word is in bold.
> `{'size': 9.962599754333496, 'flags': 4, 'font': 'GJDBJN+AdvP6960', 'color': 0, 'text': 'Rules', 'bbox': (53.85820007324219, 419.87957763671875, 77.59908294677734, 429.8421936035156)}`
> 
> Example 2. `Span` for a statement `clear what law is`. Please note that the statement is written using a regular text.
> 
> `{'size': 9.962599754333496, 'flags': 4, 'font': 'GJDBEM+AdvP6975', 'color': 0, 'text': 'clear what law is.', 'bbox': (53.85820007324219, 276.99560546875, 124.77896118164062, 286.33056640625)}`
> 
> Example 3. `Span` for a word `enforcement`. Please note that the original word is in italics.
> 
> `{'size': 9.962599754333496, 'flags': 4, 'font': 'GJDBEL+AdvP696A', 'color': 0, 'text': ' enforcement', 'bbox': (196.824462890625, 236.87384033203125, 249.12908935546875, 246.83644104003906)}`

I checked the above fonts. 

So I have the same output for each font.

`{'mono': 0, 'serif': 1, 'bold': 0, 'italic': 0, 'substitute': 0, 'stretch': 0, 'fake-bold': 0, 'fake-italic': 0, 'opentype': 0, 'invalid-bbox': 0}`

**Conclusion:** I confirmed why MuPDF returns flags=4. Each font tells about itself the same stuff misregarding actual character thickness or inclination or whatever. 

Thank you for the help, Jorj! @JorjMcKie

**Comment by JorjMcKie** [comment]
You are very welcome. Good to know that now. 
You might  also have a look at font.name ... sometimes it tells something more, who knows. I think it’s worthwhile for me to check whether there are more font internals / metrics data i could provide in the pymupdf api...
