### ISSUE TITLE
page.addRedactAnnot(text) is not searchable

### ISSUE THREAD

**Issue by ishineko** [pymupdf/PyMuPDF#639]
I've noticed that redact annot's text is not searchable by our users by doing Ctrl+F and searching the string used for the redaction, so instead I've resorted to applying redact annots with no text, and then immediately doing a page.insertText, which is indeed searchable.

Is this the recommended workflow when redacting some original text for the replacement to searchable? Or am I missing something obvious when using redact annots?

Thanks for all your help!

**Comment by JorjMcKie** [comment]
I am currently without proper internet so this is via phone.
After applying redactions the overlay text becomes part of the other text of the page, so should be searchable. I am using “insertTextbox” myself to store this text. But - as mentioned - only in when applying redactions.

Von meinem iPhone gesendet

**Comment by JorjMcKie** [comment]
I should have mentioned: insertTextbox may be unsuccessful of course (see there), in which case no text is entering the page. This may happen when the replacement won’t fit the rectangle. There is a built in resort to stepwise decreasing the font size down to no less than 4.

**Comment by ishineko** [comment]
Thanks for your answers, @JorjMcKie!

Not sure myself why the text is not searchable, specially since I can see it on the page. Maybe the actual text distribution(as opposed to text display) is different when inserted through insertTextbox vs insertText? That could explain why we can't find it by searching, if the letters are not necessarily with the same spacing physically as displayed.

Regardless, is not that much effort to redact-and-insert-text, instead of just redact, so I call it a win in my book 👍 

Have a great day, and thanks for all the work you do maintaining this library. It must be a TON of work to maintain the code AND keep up with all our questions!

**Comment by JorjMcKie** [comment]
> Maybe the actual text distribution(as opposed to text display) is different when inserted through insertTextbox vs insertText? That could explain why we can't find it by searching, if the letters are not necessarily with the same spacing physically as displayed.

No this is code sharing a lot with each other.
I just tested the function again - it **_does_** work in examples I use, so does searching for the overlay text.
