### ISSUE TITLE
Question / Comment: How to view insertPDF progress

### ISSUE THREAD

**Issue by sant527** [pymupdf/PyMuPDF#640]
I saw the code inside `insertPDF` in `fitz.py` it uses

`_fitz.Document_insertPDF(self, docsrc, from_page, to_page, start_at, rotate, links, annots)`

I have very large documents of 100,000 pages. I want to see somprogress if possible after inserting every `1000/5000 pages` 

How can i send some logging messages to the python code from `_fitz.Document_insertPDF` function after every `1000/5000` pages of insertion.

Anything i can change in the source code and then recompile it.

Else the option is keep inserting 5000 pages at a time by mentioning the start and and page

**Comment by JorjMcKie** [comment]
This a C function, so that one would have to be modified.
Alternatively segment your input in appropriate pieces as you indicate.

**Comment by sant527** [comment]
where can i find the c function file.

**Comment by JorjMcKie** [comment]
You have to modify ``fitz_wrap.c``. Look for function ``JM_merge_range``.
Good luck!

**Comment by JorjMcKie** [comment]
What is your system config?
I am considering to make that mod and send you a pre-version hotfix 😊.

**Comment by sant527** [comment]
I am using archlinux. 

I tried to change the `JM_merge_range` in `fitz_wrap.c` but when i run the `python setup.py build and python setup.py install` it gets regenerated.

```c
void JM_merge_range(fz_context *ctx, pdf_document *doc_des, pdf_document *doc_src, int spage, int epage, int apage, int rotate, int links, int annots)
{
    int page, afterpage;
    pdf_graft_map *graft_map;
    afterpage = apage;
    graft_map = pdf_new_graft_map(ctx, doc_des);

    fz_try(ctx) {
        if (spage < epage) {
            for (page = spage; page <= epage; page++, afterpage++)
                page_merge(ctx, doc_des, doc_src, page, afterpage, rotate, links, annots, graft_map);
                // CODE ADDED
                if( page % 1000 == 0){
                  printf("CURRENT PAGES %d / %d",page,epage)
                }
        } else {
            for (page = spage; page >= epage; page--, afterpage++)
                page_merge(ctx, doc_des, doc_src, page, afterpage, rotate, links, annots, graft_map);
                // CODE ADDED
                if( page % 1000 == 0){
                  printf("CURRENT PAGES %d / %d",page,epage)
                }
        }
    }
```

This is from the PyMupdf-1.17.5 (https://files.pythonhosted.org/packages/source/P/PyMuPDF/PyMuPDF-1.17.5.tar.gz)

**Comment by sant527** [comment]
Thank you. Also can i show the src filename and also destination filename

eg:
```
doc0.insertPDF(doc1,links=False,annots =False)
```

With the c code changes no it looks like this
```
Inserted 1348 of 8138 pages.
```

Can we show file name here  like

```
FROM: doc1.name
DES: doc0.name
Inserted 1348 of 8138 pages.

**Comment by JorjMcKie** [comment]
The next version will also show file information.
For now you can do a similar hack in ``fitz.py``, which is generated in parallel to ``fitz_wrap.c``.
* look for ``def insertPDF(self, ...)``

![grafik](https://user-images.githubusercontent.com/8290722/92283799-ae1c8600-eece-11ea-94f9-a7a0370a97e3.png)

* at the line marked with a red dot insert a print statement to your liking. The two file names are in ``docsrc.name`` (source file) and ``self.name`` (target file).
* both file names may be empty strings, in which case they exist in memory.

**Comment by sant527** [comment]
But this will print only once.  and will be lost in the print statements.

in `fitz_wrap.c` 

```void JM_merge_range(fz_context *ctx, pdf_document *doc_des, pdf_document *doc_src, int spage, int epage, int apage, int rotate, int links, int annots, int show_progress)```

how to show in this function.

**Comment by JorjMcKie** [comment]
> how to show in this function.

There is no way to do that currently.

**Comment by JorjMcKie** [comment]
New version 1.17.7 is currently being uploaded.
