### ISSUE TITLE
Question / Comment: Do we have proper block types in MuPDf for things like a sum sign, a line between numerator and denominator, etc?  [see an image attached]

### ISSUE THREAD

**Issue by andrei-volkau** [pymupdf/PyMuPDF#641]
Please take a look at the following screenshot. I highlighted the text blocks in yellow. I highlighted image blocks in green (there are no image blocks).

Let me consider the formulas. Do we have proper block types in MuPDf for things like the sum sign, a line between numerator and denominator? Those things are obviously not text blocks or image blocks. I would name such things as line art (aka vector). Table lines seem to be the same kind of thing.

<img width="1440" alt="Screen Shot" src="https://user-images.githubusercontent.com/12778567/92160501-c8575500-ee37-11ea-8804-5c12e068abed.png">

**Comment by JorjMcKie** [comment]
These things are generated by draw commands in PDF's mini-language used in `/Content`` streams. Look at page 985, section "A Operator Summary" in https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf for an overview. 

> BTW every single glyph is painted by a series of such commands in a font file: "D" consist of a vertical line followed by a left-open semi-circle for example.

There is no elegant way to extract them. But you can of course read a page's `/Content` objects and dig your way through them.
If you really want to experiment here a little, consider the following hints:

* the coordinates in there are **_PDF coordinates_** i.e. based on the assumption that the origin of the coordinate system is the page's bottom-left point (MuPDF takes the top-left one).

* a page can have multiple such streams, best join them via ``page.cleanContents()`` - this also standardizes the syntax:
    - every command is on its own separate line
    - number string are shortened as much as possible: ``0.0 -> 0``, ``0.123 -> .123``, etc.

* read the contents via ´``page,readContents()``, this a bytes object.

**Comment by andrei-volkau** [comment]
Thank you for the detailed info, Jorj! @JorjMcKie 

 Yeah, obviously, there is no elegant way to extract them. Closing the issue. Thank you.
