### ISSUE TITLE
How to use setColor function to set text color?

### ISSUE THREAD

**Issue by tisttsf** [pymupdf/PyMuPDF#643]
I can only change text background color.And only to red yellow  some kind of simple color.How to change text font size to be a title,or change background or font itself color when iterate the text in page using searchFor method?
[pdf_issue_howtochange_color_fontsize_backgroundcolor.zip](https://github.com/pymupdf/PyMuPDF/files/5177906/pdf_issue_howtochange_color_fontsize_backgroundcolor.zip)

`

**Comment by JorjMcKie** [comment]
You only can set the text color in FreeText annotations via the resp. parameter.
Otherwise text color ican never be changed.
Note: your post is hardly legible, so I can only guess what your are really trying to do.

**Comment by tisttsf** [comment]
> Otherwise text color ican never be changed.
> Note: your post is hardly legible, so I can only guess what your are really trying to do.

I upload a file that can be more clear to tell my post.
By ttset the text color in FreeText annotations
> You only can set the text color in FreeText annotations via the resp. parameter.

How to set text color(text_size,text_background_color) before insert to page object(I use insertPage(pno=-1) method)?Or other way can do that?

**Comment by JorjMcKie** [comment]
Please describe clearly what you want to do
1. change text color of an existing FreeText annotation?
2. change the text color of general text of an existing page?

Option 1. works,  option 2. does not - under no circumstances.

**Comment by tisttsf** [comment]
Option1:I want to change FreeText annotation and insert to a new page and save it.

**Comment by tisttsf** [comment]
> Please describe clearly what you want to do
> 
> 1. change text color of an existing FreeText annotation?
> 2. change the text color of general text of an existing page?
> 
> Option 1. works, option 2. does not - under no circumstances.

I look up the document.There are three parameter in setColors dict:{"stroke":(),"colors":(),"fill":()}.Only stroke only works,when changing text background color to 8 different color.

**Comment by JorjMcKie** [comment]
Ah, ok.
Except FreeText, annotations have two colors that can be set: **_stroke_** and **_fill_**. Stroke is (mainly) used for borders, fill is used for interior color.

Both can be set directly as parameter in ``setColor``. **_Alternatively_** you can make a dictionary with these two parameters as keys and then provide that dict as (the only) parameter. In this case, the two direct parameters are ignored.

**Comment by tisttsf** [comment]
> Ah, ok.
> Except FreeText, annotations have two colors that can be set: **_stroke_** and **_fill_**. Stroke is (mainly) used for borders, fill is used for interior color.
> 
> Both can be set directly as parameter in `setColor`. **_Alternatively_** you can make a dictionary with these two parameters as keys and then provide that dict as (the only) parameter. In this case, the two direct parameters are ignored.
Ok...How to change interior color?I set the parameter to (1,1,0) something like that but it seems nothing change.

**Comment by JorjMcKie** [comment]
Via **_fill_** parameter as I wrote.

> but it seems nothing change

What type of annotation?

**Comment by tisttsf** [comment]
> Ah, ok.
> Except FreeText, annotations have two colors that can be set: **_stroke_** and **_fill_**. Stroke is (mainly) used for borders, fill is used for interior color.
> 
> Both can be set directly as parameter in `setColor`. **_Alternatively_** you can make a dictionary with these two parameters as keys and then provide that dict as (the only) parameter. In this case, the two direct parameters are ignored.

I see,I can change text font size using `Page.insertText()` mehod if I want have different font size in one page.But I can't change font size if I only use `insertPage` method.Is that right?

**Comment by tisttsf** [comment]
> Via **_fill_** parameter as I wrote.
> 
> > but it seems nothing change
> 
> What type of annotation?

Seems not thing change.Is it suppose to change the font itself color?

**Comment by tisttsf** [comment]
> Via **_fill_** parameter as I wrote.
> 
> > but it seems nothing change
> 
> What type of annotation?

I add a attach file that can run directly.It seems not thing change when I set fill parameter to (1,0,1) or other tuples.
![fill_para](https://user-images.githubusercontent.com/4705133/92303686-f197f280-efa9-11ea-974c-2762a60e2f04.PNG)
![fill_reuslt](https://user-images.githubusercontent.com/4705133/92303687-f2c91f80-efa9-11ea-9e96-93fb69b1fdb7.PNG)

**Comment by JorjMcKie** [comment]
The color of text you inserted via ``page.insertText`` or ``doc.insertPage`` **_cannot be changed_** in any way. You choose a color when you insert, and that's it - forever.

**Comment by JorjMcKie** [comment]
Otherwise, please read the documentation. In your code a see lots of errors: a **_highlight_** annotation is not an **_Ink_** annotation, it has no border, etc.

**Comment by tisttsf** [comment]
> Otherwise, please read the documentation. In your code a see lots of errors: a **_highlight_** annotation is not an **_Ink_** annotation, it has no border, etc.

Emm...I use addInkAnnot, it can't work,I think I passed the wrong parameters.
docs example:`annot = page.addInkAnnot((sin_points, cos_points))` .But sin_points and cos_point are different from `serachFor `method return.`serachFor ` returns a list of rects(x1,y1,x2,y2) points.
How to use it in addInkAnnot.
> The color of text you inserted via `page.insertText` or `doc.insertPage` **_cannot be changed_** in any way. You choose a color when you insert, and that's it - forever.

ok,but I did change the text background color when using setColors after `doc.insertPage(pno=-1,text=text_page,width=600,height=1000,fontname="f0",fontfile=ffile,fontsize=fsize)
`

**Comment by JorjMcKie** [comment]
An Ink annot can simulate a hand written drawing. For this, you must pass a lot of points to it. Those will then be connected via lines. That' what I did: pass points on sine and cosine lines to it.
It has no business at all in the context of text.

Highlight, underline, strikethrough, squiggle are the 4 ways to mark text: "text marker annotations". Each of them only support **_stroke_** colors - no **_fill_** color. The highlight color **_is no fill / background color_** in that sense!

**Comment by tisttsf** [comment]
> An Ink annot can simulate a hand written drawing. For this, you must pass a lot of points to it. Those will then be connected via lines. That' what I did: pass points on sine and cosine lines to it.

I think this method only suit for drawing pictures.
> It has no business at all in the context of text.
> 
> Highlight, underline, strikethrough, squiggle are the 4 ways to mark text: "text marker annotations". Each of them only support **_stroke_** colors - no **_fill_** color. The highlight color **_is no fill / background color_** in that sense!

So how can I set text color before insert them to page object?I use `addFreetextAnnot` but get
`addFreetextAnnot() got an unexpected keyword argument 'colors'`

**Comment by JorjMcKie** [comment]
A FreeText annotation is an **_annotation_**! It does not insert text to the PDF itself. But you can control the color of the text - see documentation.

Otherwise  - again - read the documentation of ``Page.insertText``, ``Page.insertTextbox``, ``TextWriter.append()`` and ````Document.insertPage()``. All have a color argument.

**Comment by tisttsf** [comment]
> A FreeText annotation is an **_annotation_**! It does not insert text to the PDF itself. But you can control the color of the text - see documentation.
> 
> Otherwise - again - read the documentation of `Page.insertText`, `Page.insertTextbox`, `TextWriter.append()` and `Document.insertPage()`. All have a color argument.

I look the other issue, and use the insertText mehod. It works fine currently!Thanks!

**Comment by lokman2k5** [comment]
Can I change the color of text that's already in a PDF document?
