### ISSUE TITLE
fetch unicodes info for all fonts from a pdf

### ISSUE THREAD

**Issue by harveyspecter09** [pymupdf/PyMuPDF#644]
@josch 

Hi JorjMcKie
Hope you are doing good today from past few days i have been using this awesome library for font manipulations.

As of now i am trying to automate few things by  providing PDF as input to below code to fetch  unicode information in a one go but couldn't achieve it since i have to provide font name as well , 

**Query**: instead of providing fontname along with input PDF, can we get needed info just by providing only pdf file and fetch all fonts unicode details in one go? 

**Expecting**  whole set of unicode details for all fonts in font specific order. By using the csv file generated in font-replacement script and iterate throughout it can we achieve it? I am unable to connect the dots. Is there any way that you can guide me in getting that info in making enhancements.

please find below code i am trying to create for unicode

"""
import fitz
def get_cmapinfo(indoc,font):
    for page in indoc:
        for f in page.getFontList():
            print(f)
            fontname = f[3]
            idx = fontname.find("+") + 1
            fontname = fontname[idx:]
            if font==fontname:
                print(indoc.xrefObject(f[0]))
                for line in indoc.xrefObject(f[0]).splitlines():
                    line = line.strip()
                    if line.startswith("/ToUnicode"):
                        stream_id = int(line.split()[1])
                        cmap_info = indoc.xrefStream(stream_id).decode()
                        start = cmap_info.find("/CMapName")
                        end = cmap_info.find("endcmap", start) if start >= 0 else -1
                        if 0 <= start < end:
                            Unicinfo = cmap_info[start:end]
                            print(Unicinfo)

[input.pdf](https://github.com/pymupdf/PyMuPDF/files/5178176/input.pdf)                       
indoc = fitz.open("input.pdf")
get_cmapinfo(indoc,'ArialNarrow')
indoc.close()

"""

and btw 
for the above pdf i could see the below font reference naming conventions(C2, T1) any significance for the same
https://pymupdf.readthedocs.io/en/latest/vars.html#font-file-extensions knew about ttf,cid,cff extensions just want to know because for most of the ttf file extensions i came across i could see font reference as F1,F2 .... 
 
Output for the above code

(29, 'ttf', 'Type0', 'VQYTJD+Cambria-Bold', 'C2_0', 'Identity-H')
(15, 'ttf', 'Type0', 'ANNXBT+ArialNarrow', 'C2_1', 'Identity-H')
<<
  /BaseFont /ANNXBT+ArialNarrow
  /DescendantFonts 107 0 R
  /Encoding /Identity-H
  /Subtype /Type0
  /ToUnicode 108 0 R
  /Type /Font
>>
/CMapName /Adobe-Identity-UCS def
/CMapType 2 def
1 begincodespacerange
<0000> <FFFF>
endcodespacerange
69 beginbfchar
<0003> <0020>
<0007> <0024>
<0008> <0025>
<000D> <002A>
<000F> <002C>
<0010> <002D>
<0011> <002E>
<0012> <002F>
<0013> <0030>
<0014> <0031>
<0015> <0032>
<0016> <0033>
<0017> <0034>
<0018> <0035>
<0019> <0036>
<001A> <0037>
<001B> <0038>
<001C> <0039>
<001D> <003A>
<0024> <0041>
<0025> <0042>
<0026> <0043>
<0027> <0044>
<0028> <0045>
<0029> <0046>
<002A> <0047>
<002C> <0049>
<002D> <004A>
<002F> <004C>
<0031> <004E>
<0032> <004F>
<0033> <0050>
<0035> <0052>
<0036> <0053>
<0037> <0054>
<003B> <0058>
<003C> <0059>
<003D> <005A>
<0044> <0061>
<0045> <0062>
<0046> <0063>
<0047> <0064>
<0048> <0065>
<0049> <0066>
<004A> <0067>
<004B> <0068>
<004C> <0069>
<004D> <006A>
<004E> <006B>
<004F> <006C>
<0050> <006D>
<0051> <006E>
<0052> <006F>
<0053> <0070>
<0054> <0071>
<0055> <0072>
<0056> <0073>
<0057> <0074>
<0058> <0075>
<0059> <0076>
<005A> <0077>
<005B> <0078>
<005C> <0079>
<008B> <00A9>
<00B1> <2013>
<00B3> <201C>
<00B4> <201D>
<00BF> <FB01>
<00C0> <FB02>
endbfchar

(80, 'cid', 'Type0', 'Cambria,Bold-Identity-H', 'C0_0', 'Identity-H')
(81, 'cid', 'Type0', 'Cambria-Identity-H', 'C0_1', 'Identity-H')
(82, 'cff', 'Type1', 'ACPPDM+ArialMT', 'T1_0', '')
(84, 'cff', 'Type1', 'ACPPDP+Calibri', 'T1_1', '')
(83, 'cff', 'Type1', 'ACPPDN+Arial-BoldMT', 'T1_2', '')
(42, 'cff', 'Type1', 'ACPPGB+CambriaBold', 'T1_3', '')

Appreciate your timely response JorjMcKie

**Comment by harveyspecter09** [comment]
+
[fetchunicodes.zip](https://github.com/pymupdf/PyMuPDF/files/5178190/fetchunicodes.zip)

**Comment by JorjMcKie** [comment]
I understand you want a list of all unicode points supported by all fonts in a PDF, per font?

I suggest an approach like this:

1. loop through all page numbers to get the list ``doc.getPageFontList(pno)``. Of that list, add the xref (first item) of each entry in a ``set()``.

2. Loop through the previous set and do this for each xref:
    - ``font_prop = doc.extractFont(xref)``
    - ``font = fitz.Font(fontbuffer=font_prop[-1])  # load font buffer to make a fitz.Font``
    - ``vuc = font.valid_codepoints()  # is a list (actually an array.array) of all unicodes supported by the font``
    - ``font.name`` is the full name of the font

The array ``vuc`` is roughly equal to the "right hand side" of the CMAP. For example if "A" is supported by the font, then ``ord("A")`` will be in the array. Or if the font contains the mathematical sum symbol "capital letter sigma"  Σ, then ``font.glyph_name_to_unicode("Sigma")`` will be in that list, etc.

This approach takes care of loading each font only once.
**_Except_** if the same font with different subsets is present in this PDF. But then you will also see different ``vuc`` lists.

Hope this is what you want.

**Comment by harveyspecter09** [comment]
@JorjMcKie  thanks for timely response 
I understand you want a list of all unicode points supported by all fonts in a PDF, per font? - Correct

`import fitz
def get_cmapinfo(infile):
    indoc = fitz.open(infile)
    xref=set()
    for i in range(len(indoc)):
        for f in indoc.getPageFontList(i):
            xref.add(f[0])
            for val in xref:
                font_prop = indoc.extractFont(val)
                font = fitz.Font(fontbuffer=font_prop[-1])
                fin=font.name
                idx = fin.find("+") + 1
                fontname = fin[idx:]
                for line in indoc.xrefObject(val).splitlines():
                    line = line.strip()
                    if line.startswith("/ToUnicode"):
                        stream_id = int(line.split()[1])
                        cmap_info = indoc.xrefStream(stream_id).decode()
                        start = cmap_info.find("/CMapName")
                        end = cmap_info.find("endcmap", start) if start >= 0 else -1
                        if 0 <= start < end:
                            Unicinfo = cmap_info[start:end]
            print("Object Stream data for the font => ", fontname)
            print(indoc.xrefObject(val))            
            print(Unicinfo)
    indoc.close()

if __name__ == "__main__":
    try:
        get_cmapinfo("input.pdf")
    except RuntimeError:
        print("!! <message> !!")`

1. The above was the modified one, at this point of time unable to connect dots on how to get final dictionary/list/set with font unicode details along with object stream details with fontname as key in such a way it would be user understandable format without duplicates.

2. In the exception would like to list out fontnames which doesn't have unicode information.

Appreciate your enhancements

**Comment by JorjMcKie** [comment]
I think we misunderstood each other:
What I meant was, that the array ``font.valid_codepoints()`` **_already is_** your unicode list! It is filled with all unicode values, that also oaccur on the right hand side of the CMAP. If a CMAP exists, this array is also filled with values. So if a CMAP line reads ``<0053> <0070>``, then ``chr(0X0070)`` can be printed by the font.

```python
import sys
import fitz
from pprint import pprint

font_xrefs = set()
doc = fitz.open(sys.argv[1])
for pno in range(doc.pageCount):
    for f in doc.getPageFontList(pno):
        font_xrefs.add(f[0])

for xref in font_xrefs:
    print()
    f = doc.extractFont(xref)
    fontbuffer = f[-1]
    if f[1] == "n/a":
        print("Font '%s' is not embedded!" % f[0])
        continue
    font = fitz.Font(fontbuffer=fontbuffer)
    vuc = font.valid_codepoints()
    if len(vuc) < 2:
        print("Font '%s' has no character map!" % f[0])
        continue
    print("Font '%s' supports the following unicode points:" % f[0])
    pprint(list(vuc[1:]))

```

**Comment by harveyspecter09** [comment]
@JorjMcKie made some enhancements to include object stream information as well ,thanks for giving a trigger
Appreciate your specifics grateful for your suggestions
thanks a ton
