### ISSUE TITLE
Question / Comment: what is the github for mupdf lbrary for android

### ISSUE THREAD

**Issue by sant527** [pymupdf/PyMuPDF#646]
This not a relavent question for this repo, but i am also using mupdf-mini source code. to customize as per my needs for a personal pdf viwere in android. Infact its the best pdf viewer which can open 180,000 page and with 65,000 outlines in few sec.

No other pdf viewer in android is capable

I have to ask some questions regarding the android library, which github repo is the place i can ask.

I want to add a button for inverting the colors.

**Comment by JorjMcKie** [comment]
should be this one: https://github.com/ArtifexSoftware/mupdf-android-fitz
