### ISSUE TITLE
Improving Documentation

### ISSUE THREAD

**Issue by Harshil783** [pymupdf/PyMuPDF#647]
Well Having A Basic Usage Of Using This Package Will Be Good As This Help The User To Understand How to use?

**Comment by JorjMcKie** [comment]
What's wrong with the **_"Tutorial"_** and the **_"Collection of Recipes"_** chapters? Not basic enough?

**Comment by Harshil783** [comment]
Problem In Github This Project Name Is PyMuPDF But In Real When Importing It is fitz can't understand the name?

**Comment by JorjMcKie** [comment]
> It is fitz can't understand the name?

You have not read the documentation! There is a comment on this - right at the beginning, so do not fear you will be wasting much of your time 😉.
And - btw - you could asked this question instead.

**Comment by Harshil783** [comment]
Ok Thanks For Telling!
