### ISSUE TITLE
Cannot see links in pdf after using insertLink method.

### ISSUE THREAD

**Issue by tisttsf** [pymupdf/PyMuPDF#648]
Is there something wrong with my code?I want to see the linktext in pdf that I can click and go directly to the link.But after running this code only `InsertText `succeed in showing text.`insertLink` seems not working.
[mupdf_one_link.zip](https://github.com/pymupdf/PyMuPDF/files/5179671/mupdf_one_link.zip)

**Comment by JorjMcKie** [comment]
No, everything just works fine with your script! The links are inserted, see here:
![grafik](https://user-images.githubusercontent.com/8290722/92326886-7d9a3080-f023-11ea-8271-2d7a5e3a8dbb.png)
Maybe not there, where you thought they would be ... 😂.
BTW I have drawn rectangles around the "from" key of the links.

**Comment by tisttsf** [comment]
> No, everything just works fine with your script! The links are inserted, see here:
> ![grafik](https://user-images.githubusercontent.com/8290722/92326886-7d9a3080-f023-11ea-8271-2d7a5e3a8dbb.png)
> Maybe not there, where you thought they would be ... 😂.
> BTW I have drawn rectangles around the "from" key of the links.

But I didn't see the link url text..also on my machine i cannot see any button to click.How can I do just like other normal pdf do,with a link higtlight color and can click to directly go to the link url)?

**Comment by JorjMcKie** [comment]
Well, you have to insert text (or anything that is visible - could also be a picture, or the url address, ...) within the link rectangle as well.
The link and what is inside its rectagnel are completely independent from each other!

**Comment by tisttsf** [comment]
> Well, you have to insert text (or anything that is visible - could also be a picture, or the url address, ...) within the link rectangle as well.
> The link and what is inside its rectagnel are completely independent from each other!

So I should insert a text exactly on the link. I think this two line code can work fine.Thank you very much for reply!
`page_one.insertLink(link)`
`page_one.insertText((link["from"][0],link["from"][1]),link["uri"],fontfile=ffile,fontsize=24)`

**Comment by JorjMcKie** [comment]
> So I should insert a text exactly on the link.

Yes, for example. You could also use ``page.insertTextbox()``. Before doing so, check the length of the text to insert and decrease fontsize, until it will fit, i.e. will not be longer than rect width.
Remeber that links can also go to some page within this document instead of the internet. Or you open another document or execute something. So url-text in the  link rect is just one of many alternatives.

**Comment by JorjMcKie** [comment]
If you insert text, choose the rectangle's bottom-left as insertion point.

**Comment by tisttsf** [comment]
> If you insert text, choose the rectangle's bottom-left as insertion point.

Ok,I will try!Thanks!

**Comment by JorjMcKie** [comment]
Here a little present for you:
```python
import fitz

urls = ("http://oreilly.com", "http://oreilly.com/catalog/")

start = fitz.Point(72, 72)  # top-left first link rectangle
fontsize = 11  # fontsize
lineheight = fontsize * 1.3  # line height = height of link rect
text_color = (0, 0, 1)
doc = fitz.open()
page = doc.newPage()
for url in urls:
    tl = fitz.getTextlength(url, fontsize=fontsize)  # length of url text
    # make the link rect
    r = fitz.Rect(start, start.x + tl, start.y + lineheight)
    # make the link
    link = {"kind": fitz.LINK_URI, "from": r, "uri": url}
    page.insertLink(link)  # insert link
    page.insertText(r.bl, url, fontsize=fontsize, color=text_color)  # insert link text
    start.y += 2 * lineheight  # for next link: go down somewhat

doc.save(__file__.replace(".py", ".pdf"))
```

**Comment by tisttsf** [comment]
> Here a little present for you:
> 
> ```python
> import fitz
> 
> urls = ("http://oreilly.com", "http://oreilly.com/catalog/")
> 
> start = fitz.Point(72, 72)  # top-left first link rectangle
> fontsize = 11  # fontsize
> lineheight = fontsize * 1.3  # line height = height of link rect
> text_color = (0, 0, 1)
> doc = fitz.open()
> page = doc.newPage()
> for url in urls:
>     tl = fitz.getTextlength(url, fontsize=fontsize)  # length of url text
>     # make the link rect
>     r = fitz.Rect(start, start.x + tl, start.y + lineheight)
>     # make the link
>     link = {"kind": fitz.LINK_URI, "from": r, "uri": url}
>     page.insertLink(link)  # insert link
>     page.insertText(r.bl, url, fontsize=fontsize, color=text_color)  # insert link text
>     start.y += 2 * lineheight  # for next link: go down somewhat
> 
> doc.save(__file__.replace(".py", ".pdf"))
> ```

**Comment by tisttsf** [comment]
> Here a little present for you:
> 
> ```python
> import fitz
> 
> urls = ("http://oreilly.com", "http://oreilly.com/catalog/")
> 
> start = fitz.Point(72, 72)  # top-left first link rectangle
> fontsize = 11  # fontsize
> lineheight = fontsize * 1.3  # line height = height of link rect
> text_color = (0, 0, 1)
> doc = fitz.open()
> page = doc.newPage()
> for url in urls:
>     tl = fitz.getTextlength(url, fontsize=fontsize)  # length of url text
>     # make the link rect
>     r = fitz.Rect(start, start.x + tl, start.y + lineheight)
>     # make the link
>     link = {"kind": fitz.LINK_URI, "from": r, "uri": url}
>     page.insertLink(link)  # insert link
>     page.insertText(r.bl, url, fontsize=fontsize, color=text_color)  # insert link text
>     start.y += 2 * lineheight  # for next link: go down somewhat
> 
> doc.save(__file__.replace(".py", ".pdf"))
> ```
And `insertText`

**Comment by tisttsf** [comment]
> > Here a little present for you:
> > ```python
> > import fitz
> > 
> > urls = ("http://oreilly.com", "http://oreilly.com/catalog/")
> > 
> > start = fitz.Point(72, 72)  # top-left first link rectangle
> > fontsize = 11  # fontsize
> > lineheight = fontsize * 1.3  # line height = height of link rect
> > text_color = (0, 0, 1)
> > doc = fitz.open()
> > page = doc.newPage()
> > for url in urls:
> >     tl = fitz.getTextlength(url, fontsize=fontsize)  # length of url text
> >     # make the link rect
> >     r = fitz.Rect(start, start.x + tl, start.y + lineheight)
> >     # make the link
> >     link = {"kind": fitz.LINK_URI, "from": r, "uri": url}
> >     page.insertLink(link)  # insert link
> >     page.insertText(r.bl, url, fontsize=fontsize, color=text_color)  # insert link text
> >     start.y += 2 * lineheight  # for next link: go down somewhat
> > 
> > doc.save(__file__.replace(".py", ".pdf"))
> > ```
> 
> Thanks,`getTextlength` and its attribute `fontsize`.That would be very useful so don't need to calculate link text length. And insert code in issue directly..
