### ISSUE TITLE
How to get the annotation font

### ISSUE THREAD

**Issue by PeterSlezak** [pymupdf/PyMuPDF#649]
I would like to write a script that standardize FreeText annotation style in the document (i.e. use only one Font, Fontsize, text color, background color, border style, border color). I'm able to set all this parameters when creating a new annotation but I'm unable to get all these values from the existing annotation that are already present in the document.

I can get the annotation type using annot.type. Border width/style using annot.border. Is there a way to get the annotation font name and font size?
Thanks in advance!

**Comment by JorjMcKie** [comment]
No, there is no standard way yet. You have to parse the annotation definition source (accessible via annnot.xref yourself.
The is a plethora of ways to specify an annot - including XML syntax in this case (not used by MuPDF). So best have a look at different examples and also consult the Adobe manual.
PyMuPDF only uses the /DA key to specify font ref name, color and font size.

**Comment by PeterSlezak** [comment]
Thank you for the quick response. I'll give it a try and If I end up with a usable script I'll post it here.

**Comment by JorjMcKie** [comment]
Couldn't hold me back to give you two examples.
Determine the annots cross reference number, xref: ``annot.xref`` and then print the object definition:
```python
>>> print(doc.xrefObject(annot.xref))  # PyMuPDF example
<<
  /Type /Annot
  /Subtype /FreeText
  /Rect [ 74 630.75 521 696 ]
  /AP <<
    /N 7 0 R
  >>
  /DA (0 0 1 rg /TiRo 16 Tf)  % <== blue, Times-Roman, fontsize=16
  /P 4 0 R
  /F 4
  /Contents (This is a text of mixed languages to generate FreeText annotations with automatic font selection - a feature new in MuPDF v1.17.)
  /Rotate 0
  /Q 1
  /C [ 1 1 0 ]
  /NM (fitzannot-0)
  /BS <<
    /W 1
    /S /S
  >>
>>
>>> 
```
Here a FreeText example using Nitro Reader:
```python
>>> print(doc.xrefObject(annot.xref))
<<
  /T (jorj.x.mckie@outlook.de)
  /Type /Annot
  /P 4 0 R
  /F 4
  /Subtype /FreeText
  /M (D:20200909042938-04'00')
  /CreationDate (D:20200909042909-04'00')
  /Contents (Entered using Nitro Reader.)
  /AP <<
    /N 101 0 R
  >>
  /BS <<
    /W 0
  >>
  /Rect [ 153.8146 669.3975 361.6519 683.6559 ]
  /IT /FreeTextTypewriter
  /RC (<?xml version="1.0" encoding="UTF-8"?><body style="font-family:Consolas;font-size:14.0pt;color:#FF0000;text-align:left;line-height:16.5pt" xfa:APIVersion="Acrobat:9.0.0" xfa:spec="2.0.2" xmlns="http://www.w3.org/1999/xhtml" xmlns:xfa="http://www.xfa.org/schema/xfa-data/1.0/"><p><span style="font-family:Consolas;font-size:14.0pt;color:#FF0000;text-align:left;line-height:16.5pt">Entered using Nitro Reader.</span></p></body>)
  /DA (0.00 0.00 0.00 rg 0.00 Tc 0.00 Tw 16.54 TL /Consolas 14.00 Tf)
  /Subj (Typewritten text)
  /DS (font: Arial,sans-serif 12.0pt; text-align:left;\ncolor:#000000)
>>
>>> 
```
As you see, they also use the ``/DA`` PDF key, but the color definition ``0.00 0.00 0.00 rg`` (black) and some other text properties are overwritten in PDF key `/RC`, which represents an XML document. The actual visible color in this case is indeed red, ``color:#FF0000``.

No doubt, you will find yet other conventions when looking at stuff entered via Adobe and what not.

**Comment by JorjMcKie** [comment]
Couldn't hold me back to give you two examples.
Determine the annots cross reference number, xref: ``annot.xref`` and then print the object definition:
```python
>>> print(doc.xrefObject(annot.xref))  # PyMuPDF example
<<
  /Type /Annot
  /Subtype /FreeText
  /Rect [ 74 630.75 521 696 ]
  /AP <<
    /N 7 0 R
  >>
  /DA (0 0 1 rg /TiRo 16 Tf)  % <== blue, Times-Roman, fontsize=16
  /P 4 0 R
  /F 4
  /Contents (This is a text of mixed languages to generate FreeText annotations with automatic font selection - a feature new in MuPDF v1.17.)
  /Rotate 0
  /Q 1
  /C [ 1 1 0 ]
  /NM (fitzannot-0)
  /BS <<
    /W 1
    /S /S
  >>
>>
>>> 
```
Here a FreeText example using Nitro Reader:
```python
>>> print(doc.xrefObject(annot.xref))
<<
  /T (jorj.x.mckie@outlook.de)
  /Type /Annot
  /P 4 0 R
  /F 4
  /Subtype /FreeText
  /M (D:20200909042938-04'00')
  /CreationDate (D:20200909042909-04'00')
  /Contents (Entered using Nitro Reader.)
  /AP <<
    /N 101 0 R
  >>
  /BS <<
    /W 0
  >>
  /Rect [ 153.8146 669.3975 361.6519 683.6559 ]
  /IT /FreeTextTypewriter
  /RC (<?xml version="1.0" encoding="UTF-8"?><body style="font-family:Consolas;font-size:14.0pt;color:#FF0000;text-align:left;line-height:16.5pt" xfa:APIVersion="Acrobat:9.0.0" xfa:spec="2.0.2" xmlns="http://www.w3.org/1999/xhtml" xmlns:xfa="http://www.xfa.org/schema/xfa-data/1.0/"><p><span style="font-family:Consolas;font-size:14.0pt;color:#FF0000;text-align:left;line-height:16.5pt">Entered using Nitro Reader.</span></p></body>)
  /DA (0.00 0.00 0.00 rg 0.00 Tc 0.00 Tw 16.54 TL /Consolas 14.00 Tf)
  /Subj (Typewritten text)
  /DS (font: Arial,sans-serif 12.0pt; text-align:left;\ncolor:#000000)
>>
>>> 
```
As you see, they also use the ``/DA`` PDF key, but the color definition ``0.00 0.00 0.00 rg`` (black) and some other text properties are overwritten in PDF key `/RC`, which represents an XML document. The actual visible color in this case is indeed red, ``color:#FF0000``.

No doubt, you will find yet other conventions when looking at stuff entered via Adobe and what not.

**Comment by JorjMcKie** [comment]
Parsing the annot object definition source, you can of course extract the XML document of the `/RC` and interpret it using lxml ...
