### ISSUE TITLE
general query

### ISSUE THREAD

**Issue by harveyspecter09** [pymupdf/PyMuPDF#650]
Hi @JorjMcKie , Hope you are doing well and having good time, 
my wholehearted thanks for your generosity in showering timely response and specifics appreciate it.

I am hoping and believe the below 3 queries will improvise for  better consumption of pymupdf in wider scale,Would love to know your feedback for the same at your earliest convenience.

1. Any leads on how to embed other fonts like ArialMT, ArailNarrow, Cambria, Verdana, Calibri, TVNordEF, TVNordCondEF... with its respective typefaces. From fontools or pymupdf_font or any other package can we achieve the above fonts embedding if so how can we achieve it? 

2. Below are the examples of sample pdfs before and after conversion using your awesome script,Output PDF is quite great but  when you take a closer look ,the position of character is changing a bit in minute scale. Is there any way that we can ensure character positions are not altered even a bit  by comparing cmap unicodes positions or any other mechanism
below are the changes made  jorj

```
Helvetica;TrueType;MacRomanEncoding;keep; 
Helvetica-Bold;TrueType;MacRomanEncoding;keep;
```

> Helvetica;TrueType;MacRomanEncoding;helvetica; 
> Helvetica-Bold;TrueType;MacRomanEncoding;helvetica-bold

[test1.pdf](https://github.com/pymupdf/PyMuPDF/files/5189610/test1.pdf)
[test1-formatted.pdf](https://github.com/pymupdf/PyMuPDF/files/5189611/test1-formatted.pdf)

3. I know its a vague query forgive me for the same but still i would like to bring to your notice, your thought process on creating basic api considering the scripts length and changes that needs to be made in csv file may be in flask which is quite basic for a learner like me :-)

thanks in advance JorjMcKie hope you have a wonderful day

**Comment by JorjMcKie** [comment]
Oops, I thought I had answered this yesterday?
Two things:
1. looking at your example, I realized that some font names may contain ";" - this is deadly! I am going to change my script to catch this.
2. the two PDFs are indeed almost identical and character positions differ only subtly. **_This is inevitable_** when replacing a font! Two fonts with coinciding properties - fontsize, weight, serifes - may still show differences in single character properties, as there are: ascendent, descendent, width, height ... After all: if there weren't, why change the font in the first place?

**Comment by JorjMcKie** [comment]
> Any leads on how to embed other fonts

The "keep" can be replaced by the following types of font specifications:
* a "reserved" built-in font code: helv, hebo, hebi, heit, tiro, tibi, tibo, tiit, cour, cobo, cobi, coit, china-s, china-t, korea, japan, symb, zadb
* a "reserved" built-in font code becoming available when you install pymupdf-fonts. For example figo, spacemo, notos, math, music and several more
* a filename of a fontfile present on your system, e.g. ``"C:/Windows/Fonts/DejaVuSans-Bold.ttf``.

**Comment by harveyspecter09** [comment]
@JorjMcKie thanks for the update as always appreciate it

> why change the font in the first place?

1. Well in my input pdf the font subtype is '**TrueType**' and encoding is '**MacRomanEncoding**' since helvetica is coming under base14 fonts list just gave a try on how its impacting its font subtype and its encoding.

(point to be noted : If i am not wrong when using fitz, pymupdf, any base14 fonts that are embedded in any input pdf the embedded font subtype is coming as '**Type1(CID)**' and its encoding as '**Identity-H**' did you notice the same? would you like to share your comments for the same?)

2. Along with basefonts i am focusing on  its font subtype and font encoding as well jorj, since  font embedding is give outstanding response for all base14 fonts just want to how it will be applicable for other fonts.

`a "reserved" built-in font code becoming available when you install pymupdf-fonts. For example figo, spacemo, notos, math, music and several more`
3. thanks for letting me about the pymudf_fonts i knew we can use it but unsure on how to implement the same in the font replacement scripts.

`a filename of a fontfile present on your system, e.g. "C:/Windows/Fonts/DejaVuSans-Bold.ttf - `
4.for this one i would appreciate if you be little more specific because at this point of time i am unable to visualize how to achieve if we have relevant font file with us in our local file system folder.


Last but not the least 
`the two PDFs are indeed almost identical and character positions differ only subtly. This is inevitable when replacing a font! Two fonts with coinciding properties - fontsize, weight, serifes - may still show differences in single character properties, as there are: ascendent, descendent, width, height ... After all: if there weren't, why change the font in the first place?`
5.for same  basefont If font sub type , font encoding changes definitely will there be change in the character positions? am unsure about this would like to hear from you.

once again :-0
I know its a vague query forgive me for the same but still i would like to bring to your notice, your thought process on creating basic api considering the scripts length and changes that needs to be made in csv file may be in flask which is quite basic for a learner like me :-)

thanks for your time and patience in reading my lengthy queries and answering it my wholehearted thanks for you
hope you have a  wonderful day.
