### ISSUE TITLE
How to use PyMuPDF to generate vertical text？

### ISSUE THREAD

**Issue by kingqiuol** [pymupdf/PyMuPDF#653]

**Comment by JorjMcKie** [comment]
The simplest way: `page.insertTextbox()`. Specify desired rectangle and angle 0, 90, 180, 270. Text will then be written either:
* top-left to bottom-right, or
* top-right to bottom-left, or
* bottom-right to top-left, or
* bottom-left to top-right

The are also lots of other ways, including writing in arbitrary angles (other than int multiples of 90 degrees).

**Comment by JorjMcKie** [comment]
Any feedback on this?

**Comment by cges30901** [comment]
I think he/she is probably referring to vertical writing in CJK languages. `rotate` is not useful here.

Here is my example script, modified from [this example](https://pymupdf.readthedocs.io/en/latest/faq.html#how-to-write-text-lines) and https://github.com/pymupdf/PyMuPDF/issues/329:

```
import fitz
doc = fitz.open()  # new or existing PDF
page = doc.newPage()  # new or existing page via doc[n]
p = fitz.Point(50, 72)  # start point of 1st line

text = "你好！hello！Hallo！ 我很喜欢德国！德国是个好地方"
# the same result is achievable by
# text = ["Some text", "spread across", "several lines."]

rc = page.insertText(p,  # bottom-left of 1st char
                     text,  # the text (honors '\n')
                     fontname = "china-ss",  # the default font
                     fontsize = 11,  # the default font size
                     rotate = 270,  # also available: 90, 180, 270
                     )
print("%i lines printed on page %i." % (rc, page.number))

doc.save("text.pdf")
```

If `rotate` is used, characters are also rotated, which is not desired.

**Comment by cges30901** [comment]
I think he/she is probably referring to vertical writing in CJK languages. `rotate` is not useful here.

Here is my example script, modified from [this example](https://pymupdf.readthedocs.io/en/latest/faq.html#how-to-write-text-lines) and https://github.com/pymupdf/PyMuPDF/issues/329

```
import fitz
doc = fitz.open()  # new or existing PDF
page = doc.newPage()  # new or existing page via doc[n]
r1 = fitz.Rect(100,100,200,200)
text = "你好！hello！Hallo！ 我很喜欢德国！德国是个好地方"
page.insertTextbox(r1, text, fontname="china-s", rotate=270)

doc.save("text.pdf")
```

If `rotate` is used, characters are also rotated, which is not desired.

**Comment by JorjMcKie** [comment]
@cges30901 - thanks for your comment! You are probably very right.
But @kingqiuol did not even honor us with more than just the title - so we are left with guessing ...

**Comment by JorjMcKie** [comment]
So if your assumption applies, the simplest, temporary solution would be to insert linebreaks after each character, wouldn't it?

**Comment by JorjMcKie** [comment]
I am about to finish the next PyMuPDF version. You can do something like this with it:
```python
import fitz

font = fitz.Font("china-s")
doc = fitz.open()
page = doc.newPage()
tw = fitz.TextWriter(page.rect)
text = "直至在專輯製作過程中方被重新發現。"
pos = fitz.Point(250, 70)
fsize = 11

tw.appendv(pos, text, font=font, fontsize=fsize)
tw.writeText(page)

doc.save("some.pdf")
```
Produces this on the PDF page:
![grafik](https://user-images.githubusercontent.com/8290722/93018958-d0369800-f5a1-11ea-99ea-eaf37db4cc0c.png)

@cges30901 - do you believe this is the required functionality?

**Comment by kingqiuol** [comment]
@JorjMcKie @cges30901 Thank you for your answer.

**Comment by kingqiuol** [comment]
@JorjMcKie ，I used your answer, but something went wrong。AttributeError: 'TextWriter' object has no attribute 'appendv'

**Comment by JorjMcKie** [comment]
The new version 1.17.7 is underway to be uploaded. Look at PyPI in about half an hour.

**Comment by asnahu** [comment]
> I am about to finish the next PyMuPDF version. You can do something like this with it:
> 
> ```python
> import fitz
> 
> font = fitz.Font("china-s")
> doc = fitz.open()
> page = doc.newPage()
> tw = fitz.TextWriter(page.rect)
> text = "直至在專輯製作過程中方被重新發現。"
> pos = fitz.Point(250, 70)
> fsize = 11
> 
> tw.appendv(pos, text, font=font, fontsize=fsize)
> tw.writeText(page)
> 
> doc.save("some.pdf")
> ```
> 
> Produces this on the PDF page: ![grafik](https://user-images.githubusercontent.com/8290722/93018958-d0369800-f5a1-11ea-99ea-eaf37db4cc0c.png)
> 
> @cges30901 - do you believe this is the required functionality?

Is this possible translate/rotate an oriented vertical text PDF to horizontal?
