### ISSUE TITLE
Question / Comment: Understanding 'hit_max' parameter while using 'searchFor' method

### ISSUE THREAD

**Issue by andrei-volkau** [pymupdf/PyMuPDF#654]
**Example 1.**
 Let me consider the following simple code.

```
import fitz

red = (1, 0, 0)
green = (0, 1, 0)


if __name__ == '__main__':
    filename = 'sample_page.pdf'
    doc = fitz.open(filename)
    for page in doc:
        for r in page.searchFor('A', hit_max=5):
            annot = page.addRectAnnot(r)
            annot.setBorder(width=1, dashes=[1, 2])
            annot.setColors(stroke=red, fill=green)
            annot.update(opacity=0.5)
    doc.save("result.pdf")
```
The following result is expected and easy to understand. I mean that one has five `a` characters highlighted. 

> <img width="461" alt="Screen Shot 2020-09-11 at 15 04 09" src="https://user-images.githubusercontent.com/12778567/92923433-212e7b00-f440-11ea-9a96-0f293089646d.png">

**Example 2.**
 Let me consider the above code again. I am using `'As a consequence, jurists had, through their advice, a great degree of inﬂuence on the development of the law.'` as a search string in this example. I am using `hit_max=1`, `hit_max=2`, `hit_max=3` also.  

`hit_max=1`:

> <img width="461" alt="Screen Shot 2020-09-11 at 15 11 21 1" src="https://user-images.githubusercontent.com/12778567/92924221-453e8c00-f441-11ea-91e3-f4aedb775cb9.png">

`hit_max=2`:

> <img width="451" alt="Screen Shot 2020-09-11 at 15 11 46" src="https://user-images.githubusercontent.com/12778567/92924216-42dc3200-f441-11ea-89b9-34bc57402492.png">

`hit_max=3`:

> <img width="455" alt="Screen Shot 2020-09-11 at 15 12 16" src="https://user-images.githubusercontent.com/12778567/92924208-3fe14180-f441-11ea-9f74-637b6d922c35.png">

**Question:** 

[The documentation states that a search string can wrap across lines.](https://pymupdf.readthedocs.io/en/latest/faq.html) The expected behavior should be having the whole search string selected while specifying  `hit_max=1`. 

It is not a criticism! I mean that it seems to be very natural to specify `hit_max=1` while I am looking for one occurrence of the whole search string.

I would appreciate comments regarding this untrivial point. It might be possible, that I am missing some concepts. Thank you in advance!

**Comment by JorjMcKie** [comment]
I understand your point. It is a matter of wording in my documentation. First some technical comments:

The method is based on an original MuPDF function. This beast is written such, that it **_pre-allocates_** a number of ``hit_max + 1`` rectangles (actualy quads), which it then fills with found occurences. The last item is left unfilled to indicate end of occurrences.

Second: if a search string wraps (the longer it is, the more probable to expect of course), then each of its portions consumes one of those pre-allocated rectangles. So you may end up with an uncomplete set of rectangles (as you did) to even represent one single occurrence of the search string.

So I am cursed with having ever published this function: you are not the first complaining about its design - with its admittedly significant weaknesses.

Depending on how important all of this is for you, you may want to have a look at the interesting discussion I had with someone from Italy with a similar intent: #616 - he uses a combination of this function, general text extraction and some AI package to do advanced searching / text marking.

**Comment by JorjMcKie** [comment]
The least I can do is clarifying the meaning of ``hit_max`` - it is not really the number of hits of the search string, but the number of allocated rectangles.

**Comment by andrei-volkau** [comment]
@JorjMcKie Thank very much you for the clear explanation! So it gives understanding the' hit_max' parameter while using the 'searchFor' method.

I am closing the issue.

**Comment by JorjMcKie** [comment]
If you really want to highlight important parts in your text, then the following may be a solution:
* search for where the interesting part starts, then take that rectangle's top-left as point A.
* search for where the part ends, then take that rectangle's bottom-right as point B.
* execute the special version ``page.addHighlightAnnot(start=A, stop=B, clip=rect)``

The result will be something like this:
![test](https://user-images.githubusercontent.com/8290722/92993336-d1db5f80-f4be-11ea-9092-14b6c5b5d3f6.jpg)

Here, I have used the the left third of the page's rect as clip. The two red dots are my points A, B.
