### ISSUE TITLE
Question / Comment: The indented line is not part of the paragraph block.

### ISSUE THREAD

**Issue by andrei-volkau** [pymupdf/PyMuPDF#656]
It is known that MuPDF (not PyMuPDF) uses some heuristics when deciding whether to create new blocks. Parameters for this include line-height and line-height changes.

In an ideal case, every paragraph should be marked as a separate block. However, we have failures in some cases. I mean that for some documents one might have the following case. I mean that indented lines have separate blocks. 

<img width="390" alt="Screen Shot 2020-09-13 at 17 42 33" src="https://user-images.githubusercontent.com/12778567/93020910-8cb34c80-f5e8-11ea-8db7-f90998a0521a.png">

An example of correct recognition is given below. Another source PDF file is used for this "healthy" example.
<img width="609" alt="Screen Shot 2020-09-13 at 17 48 19" src="https://user-images.githubusercontent.com/12778567/93021068-5fb36980-f5e9-11ea-92a5-09c9f321c6dd.png">

**Question:** Let me share my thoughts regarding this issue. I suppose that there is no way to fix it from the PyMuPDF perspective because the issue comes from MuPDF's heuristics. But do we have any other options to approach the issue? I would like to ask for thoughts on that.

**Comment by JorjMcKie** [comment]
There are apparently a number of criteria used to tell apart blocks. Obviously also evaluated is the fact whether or not line bboxes overlap, or rather line bbox distance changes: in you first example, the 1st and 3rd block consists of lines whose bboxes touch each other or even intersect. The middle block has only one line - with a visible distance to the preceeding and the following lines.

So this may be a way to emulate MuPDF's decision process more closely: a new block is started, if a line's bbox does not intersect the previous one.

Question: why are you interested in blocks so much - isn't it more important to join falsely separated lines? "Falsely" in the sense that only a minute difference in the bbox bottom value created a new line. MuPDF's definition of a TextPage line: "Text that shares a common baseline."

**Comment by andrei-volkau** [comment]
> There are apparently a number of criteria used to tell apart blocks. Obviously also evaluated is the fact whether or not line bboxes overlap, or rather line bbox distance changes: in you first example, the 1st and 3rd block consists of lines whose bboxes touch each other or even intersect. The middle block has only one line - with a visible distance to the preceeding and the following lines.

OK, got it. Thank you.

> So this may be a way to emulate MuPDF's decision process more closely: a new block is started, if a line's bbox does not intersect the previous one.

I see. Thank you.

>  isn't it more important to join falsely separated lines? "Falsely" in the sense that only a minute difference in the bbox bottom value created a new line. 

I am struggling to understand which lines are "falsely" lines in my example. Do you mean lines marked as by 1 and 2 are  "falsely" lines?

![93020910-8cb34c80-f5e8-11ea-8db7-f90333998a0521a](https://user-images.githubusercontent.com/12778567/93238304-ee5eec80-f789-11ea-91c8-eb37797310e8.png)

**Comment by JorjMcKie** [comment]
No, I do not see this problem in your example. But in my cases I typically see this type of thing happening:

![grafik](https://user-images.githubusercontent.com/8290722/93256770-db3c2480-f769-11ea-8d82-50c764a1b451.png)

The red rectangles are line bboxes, the blue ones are blocks. Obviously, the bullet points are separate lines, but I'd like to see them being part of the line following to the right. What it worse: there bottom coordinate is different from the text line following. So this requires a lot of assumptions and fuzzy logic to find the right text line for each bullet point ...

Also interesting in this example is to guess, which rules MuPDF might have applied to construct block limits ...
