### ISSUE TITLE
Question / Comment: Reproducing output of page.getText("blocks") using page.getText("dict")["blocks"]

### ISSUE THREAD

**Issue by andrei-volkau** [pymupdf/PyMuPDF#659]
Let me consider `page.getText("blocks")`. Is it possible to reproduce exactly the same text strings while merging text spans provided by `page.getText("dict")["blocks"]`? If so, could you share code for that? Thank you in advance!

**Comment by JorjMcKie** [comment]
Something like this:
```python
>>> blks=[]
>>> for b in page.getText("dict")["blocks"]:
	lines=[]
	for l in b["lines"]:
		text="".join([s["text"] for s in l["spans"]])
		lines.append(text)
	blks.append([*b["bbox"],"\n".join(lines)])

	
>>> blks[0]
[176.4199981689453, 37.529998779296875, 421.1215515136719, 47.4900016784668, 'MuPDF v1.10 Changes and their Implications for PyMuPDF ']
# ok, forgot block type and number here
# compare with this one:
>>> page.getText("blocks")[0]
(176.4199981689453, 37.529998779296875, 421.1215515136719, 47.4900016784668, 'MuPDF v1.10 Changes and their Implications for PyMuPDF ', 0, 0)
```

**Comment by baleris** [comment]
Similar to @andrei-volkau i am able to get text information from page.getText("dict"), how can i insert all these text into the pdf without missing font style, font size, font property and also alignment. I want to retain same font property and alignment as it is available in source pdf. 
```
 r=fitz.Rect(text_bbox[:4])
 p=r.tl
 page.insertText(p,text)
```
r.tl or r.br only allows for right aligned or left aligned text, however i doesn't want to miss-out original alignment.

**Comment by JorjMcKie** [comment]
Forget about the alignment. Everything else of your requirements is implemented in font replacement scripts of the utilities repo: font, color, text position, orientation,...

**Comment by baleris** [comment]
I need two clarifications here : 
1) i mean to say, is page.getText("dict") returns any information about font size, font style-bold/italic ? how can i get this information while i am extracting text from a page.. I have only return value as mentioned below:
```
{'type': 0, 'bbox': (36.0, 744.8576049804688, 66.83999633789062, 756.0204467773438), 'lines': [{'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (36.0, 744.8576049804688, 66.83999633789062, 756.0204467773438), 'spans': [{'size': 10.079999923706055, 'flags': 4, 'font': 'TimesNewRomanPSMT', 'color': 0, 'text': 'some text here ', 'origin': (36.0, 753.8400268554688), 'bbox': (36.0, 744.8576049804688, 66.83999633789062, 756.0204467773438)}]}]}
```
2) how do i pass all font related parameters(fontstyle, fontsize, fonttype) to page.insertText() method ?

**Comment by JorjMcKie** [comment]
Won’t work with insertTextbox etc. use TextWriter as in the mentioned script.

**Comment by JorjMcKie** [comment]
As per the text properties look at the documentation, specifically about TextPage dictionary. Everything there.

**Comment by baleris** [comment]
@JorjMcKie Thanks for your direction to look at utilities repo and TextPage. 
Still i have some doubts on retrial and insertion of font.
1) page.getText("dict") provides an information about 'spans', when traverse over the span; it has 'flags' value of '20' for 'font': 'TimesNewRomanPS-BoldMT' and '22' for 'font': 'TimesNewRomanPS-BoldItal'. 
From TextPage documentation i can understand that bit 1: italic and bit 4: bold, what about this value '20' / '22' represents here. How can i convert them into a respective font type in numeric.
2) in insertion writer.writeText(page) how can i provide font type to be of specific type like 'TimesNewRomanPS-BoldMT' or something else ? 
i have tried this, wont worked out:
'''font = fitz.Font(ordering=0,is_bold=True,is_italic=True)'''

**Comment by JorjMcKie** [comment]
> How can i convert them into a respective font type in numeric.

You should have read this https://pymupdf.readthedocs.io/en/latest/textpage.html#dictionary-structure-of-extractdict-and-extractrawdict](https://pymupdf.readthedocs.io/en/latest/textpage.html#dictionary-structure-of-extractdict-and-extractrawdict:

> Test these characteristics like so:
```python
>>> if flags & 2**1: print("italic")
>>> # etc.
```
---------
Font properties like bold are properties of the font of course. You must select the right font, then implicitely its properties will be taken, e.g. ``font=fitz.Font("tibi")`` is Times Romand Bold Italic.

**Comment by JorjMcKie** [comment]
The font created by ``fitz.Font(ordering=0) == fitz.Font("cjk") == fitz.Font("china-s") == fitz.Font("japan") == etc.`` is the universal "Droid Sans Fallback Regular" font. It is only available in this one font weight - no bold nor italic.

**Comment by baleris** [comment]
It helped me a lot, However is  there any difference in mismatch of font size extracted from pageText -> spans to the size of writer.fillTextbox( font = ) . When i tries to insert into a page with fillTextbox at same bbox position with same size of pageText -> spans size, it wont fit. Through a warning! "_**Warning: only fitting 0 of 3 total words**._"

Secondly why i am not able to insert text into the same source page at specific rect location ?
it gives me an error - "_**RuntimeError: not a dict (null)**_"

if i open a new page/new file, it works fine. but want to insert into the same source file.

**Comment by JorjMcKie** [comment]
Why do you use ``fillTextbox``? I understand you want to insert the same text as existed before at the same position?
If so, simply use ``writer.append()``.

>  error - "RuntimeError: not a dict (null)"

This means, the PDF is corrupt at some places. Try to heal it first: save it to a new file using ``garbage=3, deflate=True``.

**Comment by baleris** [comment]
> Why do you use `fillTextbox`? I understand you want to insert the same text as existed before at the same position?
> If so, simply use `writer.append()`.
> Here i followed your code in Utility->textwriter/textwriter-textbox.py which shows about how to insert a text using fillTextbox().
i have a pdf say abc.pdf , i want to extract all rectangles say rect-a, rect-b, rect-c. But from all those rectangles, i want to past back only rect-a, rect-c at the existing place and at the place of rect-b i will insert some manipulated text. 
It would be great if you could direct me or refer some documentation which talks about text insertion at existing position.

> > error - "RuntimeError: not a dict (null)"
> 
> This means, the PDF is corrupt at some places. Try to heal it first: save it to a new file using `garbage=3, deflate=True`.

**Comment by JorjMcKie** [comment]
> Here i followed your code in Utility->textwriter/textwriter-textbox.py which shows about how to insert a text using fillTextbox().

Yes, I thought so. But **why** did you do that in this specific situation?

> extract all rectangles

I don't understand: What does that mean - which rectangles, where do those rectangles come from?

> documentation which talks about text insertion at existing position

See e.g. [here](https://pymupdf.readthedocs.io/en/latest/faq.html#text). It explains how the old methods `Page.insertText` and `Page.insertTextbox` work.
And again: study the script ``repl-font.py`` in [this](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/font-replacement) repo folder. It uses almost all features around the new classes `Font` and `TextWriter` to replace fonts in a given document.

To be honest: I still have no clear idea, what problem you are actually trying to solve.

**Comment by baleris** [comment]
> > Here i followed your code in Utility->textwriter/textwriter-textbox.py which shows about how to insert a text using fillTextbox().
> 
> Yes, I thought so. But **why** did you do that in this specific situation?
> 
> > extract all rectangles
> 
> I don't understand: What does that mean - which rectangles, where do those rectangles come from?
> 
> > documentation which talks about text insertion at existing position
> 
> See e.g. [here](https://pymupdf.readthedocs.io/en/latest/faq.html#text). It explains how the old methods `Page.insertText` and `Page.insertTextbox` work.
> And again: study the script `repl-font.py` in [this](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/font-replacement) repo folder. It uses almost all features around the new classes `Font` and `TextWriter` to replace fonts in a given document.
> 
> To be honest: I still have no clear idea, what problem you are actually trying to solve.

sorry, due to business confidentially i would not be able to share exactly what i am trying. But i am able to get it from page.insertText(). 
i have a "TimesNewRomanPSMT" and "ArialMT" are the font types, which are not available in default 14 PDF types. How can i load these fonts in page.insertText(fontfile = , fontbuffer=) and where do i find .ttf files to load ?

**Comment by JorjMcKie** [comment]
> "TimesNewRomanPSMT" and "ArialMT" are the font types, which are not available in default 14 PDF types.

This depends on your operating system. I can only tell for Windows, that you find the fonts in "C:/Windows//Fonts/". Although the file names there may or may not have anything to do with the font name.

It is probable also, that you will be ok if you just use "tiro" (Times-Roman) instead of "TimesNewRomanPSMT" and "helv" (Helvetica) instead of "ArialMT". With some luck, you can also "reuse" those fonts - for example:
```python
>>> for f in doc.getPageFontList(0): print(f)

(23, 'n/a', 'Type1', 'TimesNewRomanPS', 'F3', 'MacRomanEncoding')
(24, 'n/a', 'Type1', 'TimesNewRomanPS-Bold', 'F5', 'MacRomanEncoding')
(27, 'n/a', 'Type1', 'HelveticaNeue-Black', 'F8', 'MacRomanEncoding')
(28, 'n/a', 'Type1', 'HelveticaNeue-Roman', 'F10', 'MacRomanEncoding')
(30, 'n/a', 'Type1', 'HelveticaNeue-Bold', 'F12', 'MacRomanEncoding')
>>> 
```
What we see here:
* all fonts are **non-embedded** ("n/a")
* e.g. TimesNewRomanPS is referenced by "F3". So you could use ``fontname="F3"`` to reuse that font in your insertText - no need to insertFont. **However,** with bad luck, the font may not define glyphs for all characters that you want to insert. In this case, find a replacement font that is similar enough in all its glyph metrics.

If all that fails, you can just search them on the internet (e.g. https://fontsgeek.com/fonts/times-new-roman-psmt) and then download the found files. Then specify the corresponding filename - you do not need to **_install_** the downloaded font on your machine.

**Comment by baleris** [comment]
> > "TimesNewRomanPSMT" and "ArialMT" are the font types, which are not available in default 14 PDF types.
> 
> This depends on your operating system. I can only tell for Windows, that you find the fonts in "C:/Windows//Fonts/". Although the file names there may or may not have anything to do with the font name.
> 
> It is probable also, that you will be ok if you just use "tiro" (Times-Roman) instead of "TimesNewRomanPSMT" and "helv" (Helvetica) instead of "ArialMT". With some luck, you can also "reuse" those fonts - for example:
> 
> ```python
> >>> for f in doc.getPageFontList(0): print(f)
> 
> (23, 'n/a', 'Type1', 'TimesNewRomanPS', 'F3', 'MacRomanEncoding')
> (24, 'n/a', 'Type1', 'TimesNewRomanPS-Bold', 'F5', 'MacRomanEncoding')
> (27, 'n/a', 'Type1', 'HelveticaNeue-Black', 'F8', 'MacRomanEncoding')
> (28, 'n/a', 'Type1', 'HelveticaNeue-Roman', 'F10', 'MacRomanEncoding')
> (30, 'n/a', 'Type1', 'HelveticaNeue-Bold', 'F12', 'MacRomanEncoding')
> >>> 
> ```
> 
> What we see here:
> 
> * all fonts are **non-embedded** ("n/a"), i.e. there is no font file present, font details are part of the font definition **in this PDF**.

WOW, thats really amazing alternative solution! I also see some values are of this type:
>>>
(4, 'ttf', 'Type0', 'ArialMT', 'F4', 'Identity-H', 0)
(31, 'ttf', 'TrueType', 'QJADKE+SymbolMT', 'TT3', 'MacRomanEncoding', 0)
>>>
what is this 2nd index 'Type0'/'TrueType' and 5th index 'Identity-H'/'MacRomanEncoding' stands for ? is its encoding technique ? 
> * e.g. TimesNewRomanPS is referenced by "F3". So you could use `fontname="F3"` to reuse that font in your insertText - no need to insertFont. **However,** with bad luck, the font may not define glyphs for all characters that you want to insert. In this case, find a replacement font that is similar enough in all its glyph metrics.
> 
> If all that fails, you can just search them on the internet (e.g. https://fontsgeek.com/fonts/times-new-roman-psmt) and then download the found files. Then specify the corresponding filename - you do not need to **_install_** the downloaded font on your machine.

**Comment by JorjMcKie** [comment]
> (4, 'ttf', 'Type0', 'ArialMT', 'F4', 'Identity-H', 0)

This is an **embedded** font - apparently the full font (no subset). So you **_should_** be able to use it with fontname="F4". When I say "should", I am referring to the fact, that the font may still be not complete (i.e. subsetted), without being marked as such.

> (31, 'ttf', 'TrueType', 'QJADKE+SymbolMT', 'TT3', 'MacRomanEncoding', 0)

An embedded **subset** font - recognizable as such by the ``QJADKE+`` prefix. You can still try fontname="TT3" and see if you are lucky enough as described earlier, and all the characters of your insertion happen to occur in that subset.

> 'Type0'/'TrueType' 

The font type - please see the PDF manual https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf for details.

> 'Identity-H'/'MacRomanEncoding' stands for ? is its encoding technique ?

Yes, exactly.
