### ISSUE TITLE
AttributeError("module 'fitz' has no attribute 'open'")

### ISSUE THREAD

**Issue by T4m** [pymupdf/PyMuPDF#660]
## Describe the bug (mandatory)
With the version 1.17.7, the basic fitz.open return the following error :
`AttributeError("module 'fitz' has no attribute 'open'")`

It is supposed to open a document as explained here: https://pymupdf.readthedocs.io/en/latest/tutorial.html

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.
* Install latest tag (1.17.7)
* Follow the tutorial documentation.

## Your configuration (mandatory)
 - Linux buster64
 - Python 3.7
 - PyMuPDF 1.17.7 from pip install

## Additional context (optional)
I could fix it by going back to version 1.16.14

**Comment by JorjMcKie** [comment]
Cannot reproduce:
```
sudo -H python3.8 -m pip install -U pymupdf
Collecting pymupdf
  Downloading PyMuPDF-1.17.7-cp38-cp38-manylinux2010_x86_64.whl (6.1 MB)
     |████████████████████████████████| 6.1 MB 156 kB/s
Installing collected packages: pymupdf
Successfully installed pymupdf-1.17.7
jorj@Dosadi:/mnt/d/Harald/Desktop$ ipython38
Python 3.8.5 (default, Jul 20 2020, 19:48:14)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import fitz

In [2]: doc=fitz.open()

In [3]: 
```

**Comment by JorjMcKie** [comment]
this error usually indicates that ``__init__.py`` wasn't executed. Which e.g. happens when you are in the installation ``fitz`` directory and start python.

**Comment by T4m** [comment]
Thank you for your answer,

It was indeed an installation issue.
I could fix it by completely rebuild my virtual environment.
:+1:

**Comment by gnash1** [comment]
Today I am battling this error with fitz (PyMuPDF) 1.23.3 in Pycharm 2022.2.3 running on Windows 10 22H2.

**Comment by julian-smith-artifex-com** [comment]
Have you installed the package `fitz` by mistake?

Unfortunately there is an unrelated package called `fitz` on pypi.org that conflicts with package `PyMuPDF`, and pip doesn't seem to protect against this, despite these packages creating some of the same files in the Python installation.

I can get the error `AttributeError: module 'fitz' has no attribute 'open'` by doing:
```
pip install fitz
pip install pymupdf
pip uninstall fitz
```

For me, things can then be made to work with:
```
pip install --force-reinstall pymupdf
```
Could you try that?

**Comment by gnash1** [comment]
I just posted my entire journey here:
https://github.com/pymupdf/PyMuPDF/issues/2681
Please test the code samples. All you have to do is load them in PyCharm
and the error will be visually and immediately obvious.

**Comment by thomasahle** [comment]
> ```
> pip install --force-reinstall pymupdf
> ```

This solved it for me. Thanks!
