### ISSUE TITLE
When we annotate redactions we're getting an unexpected console message

### ISSUE THREAD

**Issue by ishineko** [pymupdf/PyMuPDF#661]
Hi JorjMcKie!

Quick question:

We're getting the following output in the console when applying redaction annotations (and we are not printing anything ourselves to the console)

"in method 'Page__add_redact_annot', argument 3 of type 'char *' for page 450"

And this message repeats for each annotation on every page. 

Is this something that we've turned on somehow? I don't remember seeing this message before, so not sure what may have changed.

Our specs:

PyMuPDF 1.17.4: Python bindings for the MuPDF 1.17.0 library.
Version date: 2020-07-20 18:09:40.
Built for Python 3.6 on linux (64-bit).

3.6.6 (default, Apr 15 2020, 19:26:20)
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)]
linux

Thanks!

**Comment by ishineko** [comment]
Weird, not sure why the title got cut that way:

It was supposed to say: When we annotate redactions we're getting an unexpected console message

**Comment by JorjMcKie** [comment]
Did you mean "adding redaction annot" instead of "applying"?

Can you share that script or the relevant part? I haven't changed anything for v1.17.7 in that area, but I remotely recall there was something like this in an earlier version - like I needed some string - and be it "" for the overlay text.
That should have gone away in any case since then.

**Comment by ishineko** [comment]
Sorry, you are right, that's what I meant "adding redaction annot".

Here's the offending code:

text_rect = Rect(177.95054626464844, 231.99424072265626, 201.92669677734375, 241.29658447265626)
annotation = 104
font_name = 'times-roman'
fontsize = 12.98864459991455
text_color = (0.0, 0.0, 1.0)
fill = None

page.addRedactAnnot(text_rect, text=annotation, fontname=font_name, fontsize=font_size,
                                        text_color=text_color, fill=fill, cross_out=False)

And it produces the output message:
in method 'Page__add_redact_annot', argument 3 of type 'char *' for page 452

Thanks for checking!

**Comment by JorjMcKie** [comment]
Ok, seems that was the version where I had that error. Please use ``fill=""`` if you cannot upgrade.

**Comment by JorjMcKie** [comment]
**_OOps - stop, wrong!_**
You are trying to insert an integer - 104 - instead of a string!
And "fill" is of course the fll color and must be specified as such or None.

**Comment by ishineko** [comment]
AGH!!! Dude! You just solved in a minute what's taken us the last couple of hours of hair pulling!

The argument needs to be a string, of course. I guess until now the user never passed us an integer as a parameter, so we never realized the specific need for a string, but obviously makes sense! duh!

I'll make sure to wrap in str() whatever they pass us from now on :'(

Thanks, JorjMcKie! Sorry to have used your Friday evening for this... have an awesome weekend!

**Comment by JorjMcKie** [comment]
You are very welcome!
And never mind - we all see this type of thing happening. You know any German? There exists the adjective "betriebsblind", an agglutination of "Betrieb" (business, organization) and "blind", meaning the blindness for the flaws of one's own makings.

I have heard some native English speaker calling German the "Lego" language - you can build new words from other words any time you see fit, e.g. "Weltschmerz" = "Welt" (world) + "Schmerz" (agony) or rather "mundo" + " dolor" - a noun with a poetic connotation.
