### ISSUE TITLE
Block number using page.getText("dict")

### ISSUE THREAD

**Issue by apoorv-98** [pymupdf/PyMuPDF#663]
can we get block no. from page.getText("dict")
```python
>>> blks=[]
>>> for b in page.getText("dict")["blocks"]:
	lines=[]
	for l in b["lines"]:
		text="".join([s["text"] for s in l["spans"]])
		lines.append(text)
	blks.append([*b["bbox"],"\n".join(lines)])  # <== the line break may have to be replaced by ""

	
>>> blks[0]
[176.4199981689453, 37.529998779296875, 421.1215515136719, 47.4900016784668, 'MuPDF v1.10 Changes and their Implications for PyMuPDF ']
# ok, forgot block type and number here
# compare with this one:
>>> page.getText("blocks")[0]
(176.4199981689453, 37.529998779296875, 421.1215515136719, 47.4900016784668, 'MuPDF v1.10 Changes and their Implications for PyMuPDF ', 0, 0)
```

_Originally posted by @JorjMcKie in https://github.com/pymupdf/PyMuPDF/issues/659#issuecomment-692945625_

**Comment by apoorv-98** [comment]
How can we get block no. by using page.getText("blocks") as same in page.getText("blocks") if we have both image and text in a page.

**Comment by JorjMcKie** [comment]
@apoorv-98 Not 100% sure how you mean your question. In that special case I used a PDF with no images to answer a question.

But otherwise, all text extraction methods are footed on the base object ``TextPage``. And a text page likewise contains image blocks and text blocks.
I honored this in ``page.getText("blocks")`` (which indeed contains only text and no  images) by generating a surrogate block with text containing some **_image metadata_**, but still giving it a block type of 1 (image).
So block numbers and block types of "dict", "rawdict" and "blocks" extraction options are the same.

**Comment by JorjMcKie** [comment]
> How can we get block no. by using page.getText("dict") 

Currently I do not insert a separate dict key for block number. So you must do something like this:
```python
for bno, block in enumerate(page.getText("dict")["blocks"]):
    print("block number:", bno)
    ...
```

**Comment by apoorv-98** [comment]
Thank you!
After implementation: i am getting this(last one is block no.) 
(41.09765625, 630.75, 190.30810546875, 639.75, 'Community College of Allegheny County ', 58)
by using page.getText("blocks"):
(41.09765625, 630.75, 190.30810546875, 639.75, 'Community College of Allegheny County ', 47, 0)
why this is different?

**Comment by JorjMcKie** [comment]
Hm, should not happen.
Are you sure you used the same flags in ``getText(opt, flags=???)``. The default for "blocks" is to skip images 🙄. Best use flags=0 and ensure the numbers are equal.

**Comment by JorjMcKie** [comment]
But outputting the block number in the dictionary is actually a good idea. Next version.

**Comment by apoorv-98** [comment]
Thanks sir, now getting the same by skipping the image tag in page.getText("dir").
Can we encode information in  image tag ?

**Comment by JorjMcKie** [comment]
> Can we encode information in image tag ?

like what

**Comment by apoorv-98** [comment]
b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00>\x00\x00\x00\t'
          b'\x08\x02\x00\x00\x00\xe5\xdc\x08\x06\x00\x00\x00\xf5IDATx\x9c\xcd'
          b'\x94\xbdN\x031\x10\x84g\xec3\xe1GATy*\x1e#-\xc5\x01\x0f@\x8b'
          b'\x82\x10\xe29H\x05\xf7^D\x14\x97\xe4\xec]\xc6-\x12Jy\x1e\xaf%{\xab'
          b'\xcf\xa3\xf1\x12\r\xab\xdf\x0c\x85\x96\x83%\xc6X\xe0T9J\x06#'
          b'A\xce\x8d\xf7\xaf\x1e\x9e>\xed\x1c\x88\x01\x01\xf8\x83i'
          b'\xa6\x16\xfb\x97\xafy\xd0N\xaa \x8c^\xae\x85\x1d\x8a\xf6\xfexs'
          b'\xf8\xde]\xad\x10\xbc:^\xd00z\xf5\x9a\x1e \x87es\x9a\xf6\n\x8b\x91y'
          b'q\x19\xe0Z\xec_\x87\xb9\tO\xc9\xdc\x81\xb7\xc7[\x1d\xef\x9e?'
          b'\xe2\xf8\xc3\xe5J\xb9o\xda\xf5\x1aq\x92E\xe8\xaa\x0c?3?\xe4'
          b"\x14\x17\xe8\xd4i\x17=\xd3\xc64-'}U\xb8\x1d\xc1\xae>\xc5\x88NIw"
          b"M\x9ev'\xcc\xfa}{\x91S*\xd1c\xbd*3A\xc9\t\x15\x98\xa6'x"
          b'\xbb\xe8\xd2\xfdfp\x8a7C\x19A\xd1\x9f\xd5\\\xd7\xb8\xa9A\x07'
          b'~\x01z\x16jH\x01?\x87\xb0\x00\x00\x00\x00IEND\xaeB`\x82',

I am getting this information how can i decode it?

**Comment by JorjMcKie** [comment]
> I am getting this information how can i decode it?

😎 this is the binary content of an image! A PNG in this case.
Look at the documentation of an image block [here](https://pymupdf.readthedocs.io/en/latest/textpage.html#dictionary-structure-of-extractdict-and-extractrawdict).
You could use it to store away an image, key "ext" is the file extension to use:
```python
out = open("some-image.%s" % block["ext"], "wb")
out.write(block["image"])
out.close()
```
or make a pixmap of it:
```python
pix = fitz.Pixmap(block["image"])
```
or whatever.
