### ISSUE TITLE
Question : Flag tag in page.getText("dict)

### ISSUE THREAD

**Issue by apoorv-98** [pymupdf/PyMuPDF#664]
TEXT_PRESERVE_LIGATURES
1 – If set, ligatures are passed through to the application in their original form. Otherwise, ligatures are expanded into their constituent parts, e.g. the ligature ffi is expanded into three separate characters f, f, and i.

why ffi in pdf convert into f f i in text and is their any way to handle it?

**Comment by JorjMcKie** [comment]
> why ffi in pdf convert into f f i in text and is their any way to handle it?

Well, ffi and several more similar combinations have their own single glyph in many fonts and I believe also a separate unicode value. The flag gives you the option to either get delivered that combining single unicode in your text extraction, or the original separate values for f, f, i.

**Comment by apoorv-98** [comment]
Thanks sir, but how can i get that combining single unicode in text extraction?

**Comment by JorjMcKie** [comment]
Hm, never actively searched for it. And not all text in PDFs is based on fonts which really do this type of thing. So you may have a hard time ever encountering it.
But there exist web sites with the global unicode database. There you should find the unicode value for these things. Just looked up this one: https://www.amp-what.com/unicode/search/latin%20ligature.

**Comment by JorjMcKie** [comment]
```python
>>> chr(64259)
'ﬃ'
>>> 
```

**Comment by apoorv-98** [comment]
Thank you sir
