### ISSUE TITLE
mupdf: only Gray, RGB, and CMYK colorspaces supported

### ISSUE THREAD

**Issue by johnm55977** [pymupdf/PyMuPDF#666]
Hi,

When I am trying to remove all the images or texts from a pdf page, getting below error
mupdf: only Gray, RGB, and CMYK colorspaces

Could you please advice a solution

This is what I am trying now to remove all images from a pdf page

> list =doc.getImageList(page.number,full=True)

> for image in list:
      `coordinates=page.getImageBbox(image)`
      `page.applyRedactAnnot(coordinates)`

> page.apply_redactions()

**Comment by JorjMcKie** [comment]
Interesting problem!
Could you please send me the image description:

* Its entry in ``doc.pageImageList()``
* and the image metadata (only - caution not the full image binary contained in dict key "image") contained in ``doc.extractImage(xref)`` where xref is ``item[0]`` of the entry in previous list.

Haven't seen this yet. Explanation: the MuPDF routine behind ``apply_redactions()`` tries to replace the image pixels with white and obviously you encountered a colorspace which this routine cannot cope with.

I can offer you an alternative completely without redact annotations if complete image removal is all you want:

```python
search_list = [b"/%s Do" % item[7].encode() for item in doc.getPageImageList(page.number)]
page.cleanContents()  # join and clean page's /Contents objects
xref = page.getContents()[0]  # read xref of result
cont_lines = doc.xrefStream(xref).splitlines()  # read result and split by single commands
for i in range range(len(cont_lines)):  # now search and remove all image invocations 
    if cont_lines[i] in search_list:
        cont_lines[i] = b""  # remove image invocation
cont = b"\n".join(cont_lines)  # recreate rest of /Contents
doc.updateStream(xref, cont)  # and update
# do another clean to also remove image references from Page definition
page.cleanContents()
```

**Comment by johnm55977** [comment]
Okay thank you . Will try this solution .

The only requirement is to get a clear page of a pdf after removing images
and texts

**Comment by JorjMcKie** [comment]
With a similar loop you can erase all text:

```python
page.cleanContents()  # join and clean page's /Contents objects
xref = page.getContents()[0]  # read xref of result
cont = bytearray(doc.xrefStream(xref))  # read contents as a modifybale Python binary object
while i1 < len(cont):
    i1 = cont.find(b"BT")  # find start of text object
    if i1 < 0:  # no (more) found
        break
    i2 = cont.find(b"ET")  # find end of text object
    if i2 < 0:
        break
    cont[i1 : i2 + 2] = b""  # remove text object

doc.updateStream(xref, cont)  # and update
# do another clean to also remove font references from Page definition
page.cleanContents()

**Comment by JorjMcKie** [comment]
With the new v1.18.0 you can more diligently decide what should happen to images which overlap a redaction:
you can choose to 
1. ignore such conditions
2. erase an image even with a partial overlap
3. blank out overlapping parts
So for images that are not supported like your (undisclosed) example, you have at least alternatives.
