### ISSUE TITLE
Seeking to extract the z-axis of the image

### ISSUE THREAD

**Issue by mc373906408** [pymupdf/PyMuPDF#667]
I have a project that needs to identify the hierarchy of images in the PDF

**Comment by JorjMcKie** [comment]
To understand this you must be more verbose. Sequence of how images are invoked for display or what.

Von meinem iPhone gesendet

**Comment by mc373906408** [comment]
I can get the picture Bbox through page.getimagebbox(), which can be converted to X and Y, and I hope to get Z

**Comment by JorjMcKie** [comment]
I still do not understand. A picture is 2-dimensional, where should the third dimension come from?

**Comment by JorjMcKie** [comment]
And what is "hierarchy" of images?

**Comment by mc373906408** [comment]
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/5290391/test.pdf)

![image](https://user-images.githubusercontent.com/33921191/94399662-640b8500-019a-11eb-8afe-04bca40fae0c.png)

Picture 1 is on top of picture 2, and picture 2 is on top of picture 3, and I need to know the relationship

**Comment by JorjMcKie** [comment]
Ok, now I got you. You need to know, in which sequence the images are being invoked for display. You can do this:
```python
>>> page=doc[0]
>>> cont = page.readContents()  # read the page painting commands (bytes object)
>>> cont_lines=cont.splitlines()  # split into lines
>>> for line in cont_lines:
        if line.endswith(b" Do"):  # this invokes an image (or XObject) for display
            print(line.decode())

	
/Im0 Do
/Im1 Do
/Im2 Do
/Im3 Do
/Im4 Do
/Im5 Do
>>> 
```
So the 6 images are invoked in the above sequence.

**Comment by mc373906408** [comment]
think
