### ISSUE TITLE
The writing is reversed, and it's useless to rotate. It needs to be folded in half to be correct

### ISSUE THREAD

**Issue by asimovsperhub** [pymupdf/PyMuPDF#671]
def pdf_insertext(path):
    doc = fitz.open(path)
    page=doc[0]
    # page = doc.newPage(0)
    p=fitz.Point(72,800)
    text="w"
    # print(text)
    dc=page.insertText(
        p,text,fontfile="C:\Windows\Fonts\simsun.ttc",fontname="font",fontsize=30
    )
    # print(dc)
    doc.save('x.pdf')
![2](https://user-images.githubusercontent.com/41820730/94653964-f5abfb80-032e-11eb-9d5f-548796610b22.PNG)

**Comment by JorjMcKie** [comment]
You omitted all mandatory data for a bug.

But nonetheless I'll give it a try:
This seems to be an existing PDF page that probably contains unwrapped geometry changes.
Do a ``page.cleanContents()`` before your text insertions.
Also please read the documentation how to handle [this](https://pymupdf.readthedocs.io/en/latest/faq.html#common-issues-and-their-solutions) situation.
You also didn't mention whether text insertions on new pages work - they do, or don't they.

If all fails please complete required data and include a PDF to reproduce.

**Comment by JorjMcKie** [comment]
Any reaction from you?

**Comment by JorjMcKie** [comment]
Closed for lack of reaction.
