### ISSUE TITLE
Question: Is there any efficient way to convert pixmap --> data frame? 

### ISSUE THREAD

**Issue by jiezhoujenny** [pymupdf/PyMuPDF#672]
I have thousands of pdf pages which I need to get the pixmap from. I am wondering, instead of looping pixmap height and width, is there any way that can quickly do the conversion?
Many thanks for your help!

**Comment by JorjMcKie** [comment]
I haven't understood the question yet ... but I'm convinced that PyMuPDF should (one of) the most efficient way to achieve anything with PDF.
What is a "data frame"?
To create a pixmap from a page (PDF or otherwise) you need not know the page dimension / width / height.

**Comment by jiezhoujenny** [comment]
Sorry for not explain the question clearly.
I would like to save the pixmap data in one pandas dataframe, here is the code, 
for i in range(0,pix1.width,3):
            for j in range(0,pix1.height,3):
                df.iat[i,j]=pix1.pixel(i,j)
I am wondering if Pymupdf provide any more efficient method to extract the data in pixmap.

**Comment by JorjMcKie** [comment]
Ah, got you now.
The pixel interface indeed is slow. What you really should use is the ``Pixmap.samples`` object (``bytes``). This is a width * height * pixmap.n area of 8 bit (in numpy: uint8), across which you can put a numpy array mapping for example.
I'm trying to remember the exact syntax in numpy, but you can defines an array of 3 dimensions with dtype uint8 and supply your own data (i.e. the ``pix.samples`` in this case) underneath that definition.
Hope this helps, but I keep looking ...
If I remember correctly, pandas has a handy interface to numpy. Or maybe even there is a direct pandas way to use the samples.
Well, the most important information is that samples is (a copy of)  the basis for the ``pixel`` method you are currently using.

**Comment by jiezhoujenny** [comment]
Thank you so much for your help! I will try as you suggested.

**Comment by JorjMcKie** [comment]
Atleast for numpy it should work like ``arr = np.ndarray(shape, dtype=np.uint8, buffer=pix.samples)``.
The trick then is to define shape in the right way, I believe (width, height, 3) or something like that.
