### ISSUE TITLE
Question / Comment: extract transparent image with EMPTY color-space and soft-mask

### ISSUE THREAD

**Issue by dothinking** [pymupdf/PyMuPDF#677]
Hi JorjMcKie,

Me, again, good morning. I got issue when extracting one of the transparent images from [test.pdf](https://github.com/pymupdf/PyMuPDF/files/5322740/test.pdf). It looks like #657 and #670, but the main differences: **no soft mask, no colorspace**. Any suggestions would be much appreciated.

What I got:

- img-9.png is the problem -> no soft mask, no colorspace, `(9, 0, 331, 369, 1, '', '', 'Im0', 'FlateDecode')`
- img-10.png is correct -> image with soft mask as described in #657, #670, `(10, 11, 1265, 1303, 8, 'DeviceRGB', '', 'Im1', 'FlateDecode')`

![image](https://user-images.githubusercontent.com/13885442/95008528-3b2d3900-064d-11eb-8b46-66aa24316da1.png)

The attributes shown in PDF editor (may help to explore this issue):

![image](https://user-images.githubusercontent.com/13885442/95008830-c6a7c980-064f-11eb-8bf3-3cadeb06c530.png)

![image](https://user-images.githubusercontent.com/13885442/95008861-fe167600-064f-11eb-9ec9-407532ba5328.png)

The code snippet:

```python
def recoverpix(doc, item):

    x = item[0]  # xref of PDF image
    s = item[1]  # xref of its /SMask

    if s == 0:  # no smask: use direct image output
        return doc.extractImage(x)

    def getimage(pix):
        if pix.colorspace.name in (fitz.csGRAY.name, fitz.csRGB.name):
            return pix
        else:
            return fitz.Pixmap(fitz.csRGB, pix)

    # we need to reconstruct the alpha channel with the smask
    pix1 = fitz.Pixmap(doc, x)
    pix2 = fitz.Pixmap(doc, s)  # create pixmap of the /SMask entry
    pix  = fitz.Pixmap(pix1,1)  # copy of pix1, with an alpha channel added
    ba   = bytearray(pix2.samples)
    for i in range(len(ba)):
        if ba[i] > 0: ba[i] = 255
    pix.setAlpha(ba)
    pix1 = pix2 = None  # free temp pixmaps

    # we may need to adjust something for CMYK pixmaps here:
    return getimage(pix)
```

**Comment by JorjMcKie** [comment]
Without knowing the context of your question: You can of course create a partial pixmap of the page with the image bbox as the clip rectangle. Something like this will create an image looking like in the page:

>>> import fitz
>>> doc=fitz.open("test.pdf")
>>> page=doc[0]
>>> clip=page.getImageBbox("Im0")
>>> pix=page.getPixmap(clip=clip)
>>> pix.writeImage("xref9.png")

**Comment by JorjMcKie** [comment]
Uuh, that is a tough one.
The problem here is that the image at xref 9 consists of alpha values only, i.e. colorspace None as you noted.
The turquoise color you see in the PDF is not part of the image, but part of PDF background, established right before that image is invoked for display, look at the first line following. “/Im0 Do” invokes image at xref 9.

-----------------------
.251 .878 .816 rg
q
99.244507 0 0 110.650085 .5 188.0366821 cm
/Im0 Do
Q
…
------------------------

So my image extraction indeed extracts the image, but it does not / cannot look at any potentially existing PDFbackground  color.
BTW there is a new version of extract-imga.py in the utilities repo, which more reliably extracts transparent images.

**Comment by dothinking** [comment]
> … the image at xref 9 consists of alpha values only. The turquoise color you see in the PDF is not part of the image, but part of PDF background…

It answered my question. Then, is it possible to reproduce the original image like this: create a base pixmap filled with the target bg-color, then apply xref 9 as a soft mask? Just an idea. Your proposal clipping page pixmap is enough for now. 

> BTW there is a new version of extract-imga.py in the utilities repo, which more reliably extracts transparent images. 

Yes, I've read that code, but I prefer this pure `PyMuPDF` version. Work for me, and needn't to import `Pillow` for this rare case. Any known drawback of the pure `PyMuPDF` version? 

Thank you so much.

**Comment by JorjMcKie** [comment]
> Then, is it possible to reproduce the original image like this: create a base pixmap filled with the target bg-color, then apply xref 9 as a soft mask? Just an idea.

That's correct.

> Any known drawback of the pure PyMuPDF version?

I haven't yet figured out to correctly compute the alphas for transparent pixmaps in all cases - other than that, no.

**Comment by dothinking** [comment]
Many thanks for these explanations and solution. Closing the issue now.
