### ISSUE TITLE
Question / Comment: How to search exact word rather than word in between other words

### ISSUE THREAD

**Issue by marcus011** [pymupdf/PyMuPDF#678]
I am trying to find some words which I need to highlight them , so from getText() I have extracted all the text  & on that I have applied my different regex patterns , Now to find the coordinates of them I used searchFor() function but along with my word other coordinates of word also came in .

Example :
Item to be Searched:  "use"
Search Result: "disuse","use",

Item to be Searched:  "plan"
Search Result: "planned","planning","plan"

I only want that particular word need to highlight rather than other words
I have also tried using getText('words) but my search word can be long may have space ,so results were not good

So can you suggest how I can get coordinates of exact word.

**Comment by JorjMcKie** [comment]
Yeah, ``Page.searchFor``  does have its peculiarities. I almost regret I've ever introduced the method. But people seem love it ... 😆.
You could try and put a space in front and / or at the end of your search text "needle". May help, but cases do exist, where it won't work.

I'm afraid you will have to stick with ``getText("words")``. First make a list ``needle_list = needle.split()``, then sort the output of ``getText"words")`` ascending by vertical, then by horizontal coordinate. Every subsequence of words in that list which equal ``needle_list`` is a hit.

**Comment by JorjMcKie** [comment]
Snippet:

```python
>>> wordlist = page.getText("words")
>>> wordlist.sort(key=lambda w: (w[3], w[0]))
>>> for i range(len(wordlist)):
	if i > len(wordlist) - len(needle_list): break
	sub = [w[4].lower() for w in wordlist[i:i+len(needle_list)]]
	if sub == needle_list:
		print("found at", i)
```

**Comment by marcus011** [comment]
Thanks alot @JorjMcKie  for helping me out. I will try this Code snipped & let you know if any issue or further help required

**Comment by marcus011** [comment]
I tried your code snippet but it was not good , if is there any other option to find out then do let me know
Thanks

**Comment by JorjMcKie** [comment]
Hm, not at this moment.
A lot depends on your concrete data.
What went wrong actually?

**Comment by marcus011** [comment]
Currently what I have found is ,the word dictionary contain words with next character ( . , - )
Example
Word to search 'Examine'
In dictionary it was like Examine. Or Examine, 
(Punctuation or special characters were there) &
I have some numbers which were part of word
Like EA457 in EA457000004, so for all this it shows unmatch

**Comment by JorjMcKie** [comment]
I see. Well, there probably then is no real solution.
Except you could remove punctuations from the words detected by getText. Those are at the word's always.
For the "EA457000004" case ... I don't know, maybe also remove any digits.
Instead of taking ``w[4].lower()`` above invoke a function which removes all that crab and returns the remaining word string.

**Comment by marcus011** [comment]
Yes I am trying different methods on the above method, hope soon I will achieve it .
Thanks for helping me out

**Comment by JorjMcKie** [comment]
can we close the issue?

**Comment by JorjMcKie** [comment]
I made the following script in the meantime. It is able to identify the rectangles of "real" words: withut punctuation, special characters, etc.

It makes use of the new `clip` parameter of `getText`. Given an item of `getText("words")`, it builds sub-rectangles of each list item by looking at alphabetic substrings and joining the bboxes of those characters.

Should help you in all cases you mentioned above. If you need to support languages not based on the Latin character set, some changes must be made of course.
I think it is obvious how to look only for specific words, etc.
But please contact me with any questions you may have.

[strip-words.zip](https://github.com/pymupdf/PyMuPDF/files/5374638/strip-words.zip)

**Comment by marcus011** [comment]
Thanks alot @JorjMcKie for helping me out,
I will try the script that you made & let you know about it.

**Comment by piezrawski** [comment]
I know this thread is old, but perhaps someone will find it useful. I suppose you could try to search for a string + character so "stringa" "stringb" etc. to determine which matches are invalid, but as you can imagine that will multiply the run time by quite a lot.

If it's not clear, you can have a list of matches from the search_for function that looks like this:

(For search "string")
["stringawdawd","awdawstring","string"] ---what we see in this list(1)---> ["string","string","string"]

and a list of matches that will look like:

(For multiple searches, "stringa","wstring","string" etc.)
["stringa","wstring","string"] --what we see in this list(2)---> ["stringa","wstring","string"]

That way you can compare the list1 with the list2 and determine which matches are pure
