### ISSUE TITLE
Context manager

### ISSUE THREAD

**Issue by gaardhus** [pymupdf/PyMuPDF#680]
**Is your feature request related to a problem? Please describe.**
With the current
```
doc = fitz.open('file')`
...
doc.close()
```

syntax I sometimes end up with a bunch of opened PDFs which I forget to close. Having to manually remember to close each document after you've finished working with it may sometimes be difficult.

**Describe the solution you'd like**
Adding a context manager like with standard open files:
```
with open('file') as f:
    f.write('text')
```

**Describe alternatives you've considered**
I currently implement it through making my own context manager, but having it implemented somehow would be awesome!

```
class fitz_manager:
    def __init__(self, filename):
        self.filename = filename
        self.file = None
          
    def __enter__(self): 
        self.file = fitz.open(self.filename) 
        return self.file
      
    def __exit__(self, exc_type, exc_value, exc_traceback): 
        self.file.close() 
```

This makes me able to do:
```
with fitz_manager('file') as doc:
    page_one_text = doc[0]
```
And the document will automatically close after the with statement has finished.

**Additional context**
N/A

**Comment by JorjMcKie** [comment]
I think I understand ... but PyMuPDF already does support context manager for documents.
So you can do this:

```python
>>> import fitz
>>> with fitz.open("v110-changes.pdf") as doc:
	for page in doc: print("page %i" % page.number)

	
page 0
page 1
page 2
page 3
>>> doc.isClosed
True
>>> 
```

**Comment by gaardhus** [comment]
That was exactly what I was looking for! Couldn't find it in the documentation so I figured it was missing, but that is a very obvious way of doing it! Thank you for your response.

**Comment by JorjMcKie** [comment]
You are very welcome.
I will have a look in the docu - I thought I had it mentioned, but obviously not prominently enough ...
