### ISSUE TITLE
Uncaught exception on epub with bad syntax in html file

### ISSUE THREAD

**Issue by mozbugbox** [pymupdf/PyMuPDF#681]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When open an epub with bad syntax in it, getting the `doc.pageCount` cause an uncaught exception and force fitz to abort:
```
mupdf: missing quote character
mupdf: aborting process from uncaught error!
```

Open the same file with mupdf, mupdf seems caught the exception and print an different message:
```
error: missing quote character
mupdf: error: cannot open document
```

Test code:
```test.py
    fname = sys.argv[1]
    import fitz
    doc = fitz.open(fname)
    print(doc.pageCount())
```

[Sample file fitz-exception-test.zip](https://github.com/pymupdf/PyMuPDF/files/5347586/fitz-exception-test.zip)

**Comment by JorjMcKie** [comment]
Which version did you use? With the new v1.18.0 I see this:
```python
>>> import fitz
>>> doc=fitz.open("fitz-exception-test.epub")
>>> doc.pageCount
mupdf: opening and closing tag mismatch
2
>>> len(doc)
2
>>> doc[0].rect
Rect(0.0, 0.0, 450.0, 600.0)
>>> doc[1].rect
Rect(0.0, 0.0, 450.0, 600.0)
>>> doc.chapterCount
2
>>> doc[(0,0)]
page (0, 0) of fitz-exception-test.epub
>>> doc[(1,0)]
page (1, 0) of fitz-exception-test.epub
>>> 
```
At least on Windows, didn't check on Linux yet.

**Comment by JorjMcKie** [comment]
Linux same thing - decent behaviour.

**Comment by mozbugbox** [comment]
It's 1.17.4. I guess MuPDF change that error to nonfatal.

**Comment by JorjMcKie** [comment]
Yes they did announce that they changed behaviours in that corner to be more forgiving.
Close the issue?

**Comment by mozbugbox** [comment]
Is there any reason why the `chapterPageCount` was guarded by FITZEXCEPTION while `pageCount` and `chapterCount` were not?

**Comment by JorjMcKie** [comment]
No, simply forgotten.

**Comment by JorjMcKie** [comment]
Thanks again!
