### ISSUE TITLE
Question / Comment: Convert PDF from colored version to black & white.

### ISSUE THREAD

**Issue by denyskotsur** [pymupdf/PyMuPDF#687]
Hello everyone, 

Is there any option to convert PDF into black & white format? (as `filter: grayscale(100%)` in CSS3).
I haven't found any solutions in the documentation, might be missed something. 

Thanks in advance.

**Comment by JorjMcKie** [comment]
Please be more specific - what do you want to change:
* the color of all text on all pages ==> impossible (well, almost)
* the color of all images on all pages ==> impossible (well, almost)
* the color of images rendered from the single pages: no problem!

Consequently, you can convert your PDF into one that consists of grayscale images of each of the original pages.

**Comment by denyskotsur** [comment]
@JorjMcKie thanks for the reply and questions.

So, I'm having a PDF file that has images/text with different colors. 
The goal - get a black and white version of this PDF.

According to your response, the only way is:
> Consequently, you can convert your PDF into one that consists of grayscale images of each of the original pages.

Right?

**Comment by JorjMcKie** [comment]
Right!
While this may sound brute-force, the approach also has a few pro arguments:
Replacing pages with their images also destroys any sensitive information. In fact this one of the recommended ways to exactly achieve this.
The contras are also obvious - among them: text is no longer searchable (but of course you could OCR the result again, and so forth).

Why did I write "almost" in my post?
* you can  - using PyMuPDF low-level features - replace all color specs of text to some graylevel. This would (for example) replace an RGB color consisting of the three floats (r, g, b) by the grayscale (r+g+b) / 3.
* if you have masochistic tendencies, you **_could_** extract each image, convert it to grayscale (e.g. using Pillow) and re-insert it
* turn your eyes upwards and hope you will end up with something reasonable.
