### ISSUE TITLE
Pip install 1.18.0 Requires C++

### ISSUE THREAD

**Issue by cdlatimer** [pymupdf/PyMuPDF#688]
I'm trying to pip install 1.18.0 but it errors out saying I need Microsoft Visual C++ 9.0 to install it.  I know this is not a requirement for any of the previous builds so is this a new intended feature or a bug I should report?

Below is my command prompt printout:

    C:\Users\CLatimer>C:\Python27\ArcGIS10.7\python.exe -m pip install PyMuPDF==1.18.0
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
    Collecting PyMuPDF==1.18.0
      Using cached PyMuPDF-1.18.0.tar.gz (237 kB)
    Building wheels for collected packages: PyMuPDF
      Building wheel for PyMuPDF (setup.py) ... error
      ERROR: Command errored out with exit status 1:
       command: 'C:\Python27\ArcGIS10.7\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\local_clatimer\\temp\\pip-install-v9dqmd\\pymupdf\\setup.py'"'"'; __file__='"'"'c:\\users\\local_clatimer\\temp\\pip-install-v9dqmd\\pymupdf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'c:\users\local_clatimer\temp\pip-wheel-ik24ym'
           cwd: c:\users\local_clatimer\temp\pip-install-v9dqmd\pymupdf\
      Complete output (13 lines):
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-2.7
      creating build\lib.win32-2.7\fitz
      copying fitz\__init__.py -> build\lib.win32-2.7\fitz
      copying fitz\fitz.py -> build\lib.win32-2.7\fitz
      copying fitz\utils.py -> build\lib.win32-2.7\fitz
      copying fitz\__main__.py -> build\lib.win32-2.7\fitz
      running build_ext
      building 'fitz._fitz' extension
      error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
      ----------------------------------------
      ERROR: Failed building wheel for PyMuPDF
      Running setup.py clean for PyMuPDF
    Failed to build PyMuPDF
    Installing collected packages: PyMuPDF
      Attempting uninstall: PyMuPDF
        Found existing installation: PyMuPDF 1.17.7
        Uninstalling PyMuPDF-1.17.7:
          Successfully uninstalled PyMuPDF-1.17.7
        Running setup.py install for PyMuPDF ... error
        ERROR: Command errored out with exit status 1:
         command: 'C:\Python27\ArcGIS10.7\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\local_clatimer\\temp\\pip-install-v9dqmd\\pymupdf\\setup.py'"'"'; __file__='"'"'c:\\users\\local_clatimer\\temp\\pip-install-v9dqmd\\pymupdf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\local_clatimer\temp\pip-record-bntxfb\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python27\ArcGIS10.7\Include\PyMuPDF'
             cwd: c:\users\local_clatimer\temp\pip-install-v9dqmd\pymupdf\
        Complete output (13 lines):
        running install
        running build
        running build_py
        creating build
        creating build\lib.win32-2.7
        creating build\lib.win32-2.7\fitz
        copying fitz\__init__.py -> build\lib.win32-2.7\fitz
        copying fitz\fitz.py -> build\lib.win32-2.7\fitz
        copying fitz\utils.py -> build\lib.win32-2.7\fitz
        copying fitz\__main__.py -> build\lib.win32-2.7\fitz
        running build_ext
        building 'fitz._fitz' extension
        error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
        ----------------------------------------
      Rolling back uninstall of PyMuPDF
      Moving to c:\python27\arcgis10.7\lib\site-packages\fitz\
       from c:\python27\arcgis10.7\lib\site-packages\~itz
      Moving to c:\python27\arcgis10.7\lib\site-packages\pymupdf-1.17.7.dist-info\
       from c:\python27\arcgis10.7\lib\site-packages\~ymupdf-1.17.7.dist-info
    ERROR: Command errored out with exit status 1: 'C:\Python27\ArcGIS10.7\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\local_clatimer\\temp\\pip-install-v9dqmd\\pymupdf\\setup.py'"'"'; __file__='"'"'c:\\users\\local_clatimer\\temp\\pip-install-v9dqmd\\pymupdf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\local_clatimer\temp\pip-record-bntxfb\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python27\ArcGIS10.7\Include\PyMuPDF' Check the logs for full command output.

**Comment by JorjMcKie** [comment]
No, everything is fine actually.
As announced on the home page, I started deferring uploads of dead Python versions (2.7 and 3.5) until first zombie requests 😂.
Your are the first one, so wait for a few minutes and the wheel will be there again.
Please note that you must migrate to Python >3.5 by end of the year if you want to continue using wheels.

**Comment by cdlatimer** [comment]
I'm an ArcGIS user who develops for older versions of ArcPy which only uses 2.7.   I wish I could upgrade but it's not up to me. 
Going forward I'm assuming I'll need to install 1.17.7 and below in order to avoid using wheels?
Appreciate your work on all of this stuff by the way!

**Comment by JorjMcKie** [comment]
> Going forward I'm assuming I'll need to install 1.17.7 and below in order to avoid using wheels?

In order to **_profit_** from wheels - yes that's right. And I'm convinced it is not your personal inclinination for old-fashioned stuff.
To continue using Py 2.7 your company must - starting January 2021 - provide an environement for generating Python extensions from sources - C++ compiler and what not. Best would be VS 2019.
PyMuPDF is just one of lots of examples - pip (!!!) is another one of many, **many** more.

BTW as we chatted - the wheels are on PyPI now.

>  Appreciate your work on all of this stuff by the way!

Thanks a lot - this is reassuring!

**Comment by cdlatimer** [comment]
I'll be honest I have no idea how my company plans on keeping that stuff moving because older versions of ESRI/ArcGIS are stuck in 2.7 and a lot of people still use the past versions because new licenses are so expensive.  I guess we'll find out when everyone's stuff breaks and they have to fix it all.
But my stuff is back up and running so I appreciate the speedy response!
