### ISSUE TITLE
Question: How to write PDF trailer / XML metadata to a document?

### ISSUE THREAD

**Issue by MerlijnWajer** [pymupdf/PyMuPDF#691]
I am trying to load a PDF, copy its pages to another PDF, and also copy the XML metadata stream to the new PDF document. I cannot figure out how to do this currently. I see that there is a way to modify the XML metadata stream: https://pymupdf.readthedocs.io/en/latest/faq.html#how-to-access-xml-metadata

(btw: code sample needs updating, `updatefStream` should become `updateStream`)

and I see there is a function to delete the stream: `_delXmlMetadata`.

But how does one add a stream to a document? I have tried this, but it doesn't work:

```
import fitz
import sys

doc = fitz.open(sys.argv[1])
outpdf = fitz.open()
outfile = sys.argv[2]

for page in doc:
    outpdf.insertPDF(doc, from_page=page.number, to_page=page.number)

outpdf.setMetadata(doc.metadata)

print('Trailer:', doc._getTrailerString(False))
metaxref = doc._getXmlMetadataXref()

if metaxref > 0:
    print('Has XML metadata:', metaxref)
    obj = doc.xrefObject(metaxref)
    print('object:', obj)
    xmlmetadata = doc.xrefStream(metaxref)

    test = outpdf._getNewXref()
    outpdf.updateObject(test, obj)
    print('Writing:', xmlmetadata)
    outpdf.updateStream(test, xmlmetadata, new=True)

outpdf.save(outfile)
```

But that doesn't seem to work (it was a long shot anyway, to create a new xref and hope that writing the info to it would somehow work).

Is this a missing feature, or did I miss something in the documentation?

**Comment by MerlijnWajer** [comment]
I think I figured out a workaround for now. I can just modify the document structure of `doc` (the input PDF), and save it to another file. That way it will already have a XML entry.

**Comment by MerlijnWajer** [comment]
Hm... I don't think the XML metadata gets written properly using this recipe: https://pymupdf.readthedocs.io/en/latest/faq.html#how-to-access-xml-metadata

Could that be a regression?

**Comment by MerlijnWajer** [comment]
To be clear, I tried doing copy of the existing XML metadata like so:

```
metaxref = doc._getXmlMetadataXref()
if metaxref > 0:
    xmlmetadata = doc.xrefStream(metaxref)
    print(xmlmetadata)
    doc.updateStream(metaxref, xmlmetadata)
```

That seems to work (no error, XML is printed, so xref > 0), and this is saved to a PDF file. If I then run this piece of code on the saved PDF file, the result is corrupted:

```
None
mupdf: xref not a stream object
Traceback (most recent call last):
  File "recode.py", line 36, in <module>
    doc.updateStream(metaxref, xmlmetadata)
  File "/home/merlijn/archive/tesseract/venv/lib/python3.8/site-packages/fitz/fitz.py", line 4603, in updateStream
    return self._updateStream(xref, stream, new=new)
  File "/home/merlijn/archive/tesseract/venv/lib/python3.8/site-packages/fitz/fitz.py", line 4355, in _updateStream
    return _fitz.Document__updateStream(self, xref, stream, new)
RuntimeError: xref not a stream object
```

**Comment by JorjMcKie** [comment]
There currently is no (official) way to write XML metadata into a PDF that had not one before.
There certainly is an "inofficial" way, namely using the low-level features: locate the catalog object xref `doc.PDFCatalog()`, and then update that string by inserting a line like this:
```python
>>> doc.PDFCatalog()
2
>>> print(doc.xrefObject(doc.PDFCatalog()))
<<
  /Type /Catalog
  /Pages 4 0 R
  /Metadata 5 0 R  % <== insert this line
>>
>>> 
```
Before doing this, create a new object and make it a stream object:
```python
>>> xref=doc._getNewXref()
>>> xref
5
>>> stream=b"some arbitrary binary data"
>>> doc.updateObject(5, '<</Type /Metadata\n/Subtype /XML>>')
>>> doc.updateStream(5, stream, new=True)  # turns object into a stream type
>>> doc.save("x.pdf")
```
This should work, just tried it out.

**Comment by MerlijnWajer** [comment]
Thank you, I will try this out, and let you know if the recoding problem I observed is also gone.

**Comment by MerlijnWajer** [comment]
Thank you - I can now indeed properly insert the XML metadata.

Is there also a way to write to the trailer? Specifically: this section (https://pymupdf.readthedocs.io/en/latest/faq.html#how-to-access-the-pdf-file-trailer) mentions the `ID` key. How could I write to that?

I am asking because to be PDF/A compliant, the ID entry needs to be present. It looks like `doc.PDFTrailer()` is not an extra like `doc.PDFCatalog` is.

I checked the document class but didn't find any references to setting a document identifier.

**Comment by JorjMcKie** [comment]
There is currently no way to write to the trailer.
Would need to be a new document method.

**Comment by JorjMcKie** [comment]
The next PyMuPDF version will contain document methods to write XML metadata and the ID key.
Note that MuPDF will already today automatically update the second ID field if an ID already exists. The value it uses for this update is randomly generated.
I am therefore considering to **_always_** inserting an ID when a PDF is saved and has none yet. This will be two identical values in this case, as required by PDF.

As for XML metadata, the API will propably just require a bytes string. If metadata already exist, they will be updated with that string. If not, a new object wil be created.
In any case, there will be no checking if these data are correct XML syntax or make sense in whatever way.

**Comment by MerlijnWajer** [comment]
Yeah, that makes sense, no need to add XML checking to pymupdf. But nice to have the API functions!

**Comment by MerlijnWajer** [comment]
And generating the second identifier makes a lot of sense to me. Please let me know if you'd like me to test out some build. Thanks!

**Comment by JorjMcKie** [comment]
You can download a pre-version wheel from [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux).
It contains those changes:
* when creaing a new PDF, PDF IDs are automatically generated. No intervention is needed or possible. When saving any PDF, MuPDF since ever automatically updates ID part two, if the PDF has two. This conforms to the spec: part one must never be changed, part two must always be updated on saves. MuPDF generates 16-byte random strings to achieve all this
* new method `Document.setXmlMetadata(string)`. This replaces any existing metadata with the string, or creates a new /Metadata object in the PDF catalog. As announced, there is no content checking of what is being passed in the string.

**Comment by MerlijnWajer** [comment]
Thank you - I will try it this weekend.

**Comment by MerlijnWajer** [comment]
I tried the latest version, and I can confirm that `Document.setXmlMetadata(str)` works.

But it does not look like the ID was generated. What I did was open a PDF with no ID present, modify it, and then save it to a new file. Should an ID be generated in this instance as well?

**Comment by JorjMcKie** [comment]
Ah, no I forgot that case! Thanks!

**Comment by JorjMcKie** [comment]
New version ready in the wheels repo.
Should work now. Only case not covered: if the PDF only has 1 string in the `/ID`, then I leave that untouched ...

**Comment by MerlijnWajer** [comment]
Thanks - seems to work!

**Comment by JorjMcKie** [comment]
Both features contained in v1.18.2 - currently in upload to PyPI.
