### ISSUE TITLE
I need to search for multiple keywords in a pdf document and extract the specific pdf_pages, please kindly help me out in solving this.

### ISSUE THREAD

**Issue by sucanthudu** [pymupdf/PyMuPDF#693]
pdf_document = fitz.open(pdf_file_path)
 search_item = "MATHS, CALCULATIONS, GEOMETRY, ANALYTICAL, VALUES".replace(", ", "|")
 pages = [ ]
 for this_page in range(len(pdf_document)):
     page = pdf_document.loadPage(this_page)
     if page.searchFor(search_item):
         pages.append(this_page)
         print("%s found on page_no %i" % (search_item, this_page))

print(pages)

**Comment by JorjMcKie** [comment]
I think you mean to search for each word independently from the others. I also assume you want to ignore upper or lower case, and that you are not interested in (1) the position of the words on each page, or (2) how many times on each page a word occurs

If these assumptions are correct, you have several options, the easiest ones being `page.searchFor()` and `page.getText("words")`.
The best performance in your case is possible with `page.getText("words")`.

```python
import fitz

search_words = ("pixmap", "alpha", "outline", "rgb")  # words to consider, choose one of lower or upper case
results = {}
doc = fitz.open("v110-changes.pdf")
for page in doc:
    words = [w[4].lower() for w in page.getText("words")]  # all words on page (upper, lower depending on above!)
    for sword in search_words:  # loop through search list
        if sword in words:  # occurs as one of the words
            pages = results.get(sword, set())  # get set of page numbers so far
            pages.add(page.number)  # add this page number
            results[sword] = pages  # write back to results

# report the results
for word in results:
    result = list(map(str, results[word]))  # turn set of page numbers...
    page_list = ", ".join(result)  # to a comma-separated string
    print("Word '%s' occurs on pages %s." % (word, page_list))
```
Example output:
```
Word 'pixmap' occurs on pages 0.
Word 'alpha' occurs on pages 0.
Word 'outline' occurs on pages 0, 1.
Word 'rgb' occurs on pages 2.
```
This script only counts if a search word appears completely "isolated", meaning a space before and after it. If you also want to count if the search word is e.g. following by punctuation, or is combined with other words, modify the script like this:
```
import fitz

search_words = ("pixmap", "alpha", "outline", "rgb")
results = {}
doc = fitz.open("v110-changes.pdf")
for page in doc:
    words = [w[4].lower() for w in page.getText("words")]
    for sword in search_words:
        for word in words:
            if sword in word:  # search word is *part* of a word on the page
                pages = results.get(sword, set())
                pages.add(page.number)
                results[sword] = pages

for word in results:
    result = list(map(str, results[word]))
    page_list = ", ".join(result)
    print("Word '%s' occurs on pages %s." % (word, page_list))
```
and the result is
```
Word 'pixmap' occurs on pages 0.
Word 'alpha' occurs on pages 0.
Word 'outline' occurs on pages 0, 1.
Word 'rgb' occurs on pages 0, 2.
```
So "rgb" also occurs in combination with other characters.

**Comment by sucanthudu** [comment]
pdf_document = fitz.open(pdf_file_path)
search_item = "MATHS, CALCULATIONS, GEOMETRY, ANALYTICAL, VALUES".replace(", ", "|")
pages = [ ]
for this_page in range(len(pdf_document)):
page = pdf_document.loadPage(this_page)
if page.searchFor(search_item):
pages.append(this_page)
print("%s found on page_no %i" % (search_item, this_page))
print(pages)

pdf = PdfFileReader(pdf_file_path)
pdfWriter = PdfFileWriter()
for page_num in pages:
    pdfWriter.addPage(pdf.getPage(page_num))
with open(pdf_output_path, 'wb') as f:
    pdfWriter.write(f)
    f.close()
Thanks for the reply, that was great. But my objective is to search for only one particular string for example like “MATHS” or “CALCULATIONS” or “GEOMETRY” or “ANALYTICAL” or “VALUES” from many huge pdf documents having more than 300 pages and after finding that only one particular string i need to extract or get that particular pdf page alone from those documents.

For example In one pdf document a page may contain “MATHS” as a search string, using that string, pages from the pdf document should be extracted.
Same way in another pdf document, one page may contain “GEOMETRY” as a search string, that particular pdf page should be extracted using this search string. 

**I should search for either “MATHS” or “CALCULATIONS” or “GEOMETRY” or “ANALYTICAL” which can work for multiple pdf files and extract those pages containing these strings, without duplication of pages.**

**Comment by JorjMcKie** [comment]
I think I do not quite understand. Is it this:
Take MATHS and take every page from every PDF where it occurs and put that page in a new MATH pdf.
Same with all the other search words?

**Comment by JorjMcKie** [comment]
If your question is, how to copy pages between PDFs: use `doc.insertPDF(sourcePDF, from_page=n, to_page=n)` to copy a page from sourcePDF that contains a desired content.

**Comment by JorjMcKie** [comment]
For example:
```python
pdf_list = ("file1.pdf", "file2.pdf", ...)
searchword= "MATH"
mathpdf = fitz.open()  # make empty PDF for containing MATH pages
for pdf in pdf_list:
    src = fitz.open(pdf)
    for page in src:
        for word in page.getText("words"):
            if searchword in word[4]:
                doc.insertPDF(src, from_page=page.number, to_page=page.number)
                break
doc.save("math.pdf")
```

**Comment by JorjMcKie** [comment]
or
```python
pdf_list = ("file1.pdf", "file2.pdf", ...)
searchword= "MATH"
mathpdf = fitz.open()  # make empty PDF for containing MATH pages
for pdf in pdf_list:
    src = fitz.open(pdf)
    for page in src:
        if page.searchFor(searchfor) != []:
            doc.insertPDF(src, from_page=page.number, to_page=page.number)

doc.save("math.pdf")
```

**Comment by sucanthudu** [comment]
> I think I do not quite understand. Is it this:
> Take MATHS and take every page from every PDF where it occurs and put that page in a new MATH pdf.
> Same with all the other search words?

Yes correct this was my question exactly but with some changes i quoting again 
"MATHS" will be present as a unique keyword in "file1.pdf", "GEOMETRY" will be present as a unique keyword in "file2.pdf" and soon. My searchwords will be ("MATHS","GEOMETRY",......) Now I need a new "Maths.pdf" document output which contain only the pages having "MATHS" keyword related content information. In the same way i need a new "Geometry.pdf" document output which contain only the pages having "GEOMETRY" keyword related table information.

**Comment by JorjMcKie** [comment]
Well, based on my various snippets above, that is easy now, isn't it? For MATHS take file1.pdf only and copy the resp. pages to MATH.pdf, for GEOMETRY, walk thru file2.pdf and due the same thing as skecthed above, etc. for the other keywords.

The key things to know are two: (1) how to detect whether the keyword is present on a page, and (2) how to copy an eligible page to the subset PDF.

**Comment by sucanthudu** [comment]
> The key things to know are two: (1) how to detect whether the keyword is present on a page, and (2) how to copy an eligible page to the subset PDF.

yes exactly thanks for the help. One last thing i have edited the previous comment kindly give suggestions.

**Comment by tisttsf** [comment]
You can use 
\`\`\`python
def function():
    return 1
\`\`\`
```python
def a():
    return 1
```
to show your code,plain text format code just hard to read.

**Comment by tisttsf** [comment]
> pdf_document = fitz.open(pdf_file_path)
> search_item = "MATHS, CALCULATIONS, GEOMETRY, ANALYTICAL, VALUES".replace(", ", "|")
> pages = [ ]
> for this_page in range(len(pdf_document)):
> page = pdf_document.loadPage(this_page)
> if page.searchFor(search_item):
> pages.append(this_page)
> print("%s found on page_no %i" % (search_item, this_page))
> print(pages)
> 
> pdf = PdfFileReader(pdf_file_path)
> pdfWriter = PdfFileWriter()
> for page_num in pages:
> pdfWriter.addPage(pdf.getPage(page_num))
> with open(pdf_output_path, 'wb') as f:
> pdfWriter.write(f)
> f.close()
> Thanks for the reply, that was great. But my objective is to search for only one particular string for example like “MATHS” or “CALCULATIONS” or “GEOMETRY” or “ANALYTICAL” or “VALUES” from many huge pdf documents having more than 300 pages and after finding that only one particular string i need to extract or get that particular pdf page alone from those documents.
> 
> For example In one pdf document a page may contain “MATHS” as a search string, using that string, pages from the pdf document should be extracted.
> Same way in another pdf document, one page may contain “GEOMETRY” as a search string, that particular pdf page should be extracted using this search string.
> 
> **I should search for either “MATHS” or “CALCULATIONS” or “GEOMETRY” or “ANALYTICAL” which can work for multiple pdf files and extract those pages containing these strings, without duplication of pages.**

You can use 
\`\`\`python
def function():
    return 1
\`\`\`
```python
def a():
    return 1
```
to show your code,plain text format code just hard to read.

**Comment by JorjMcKie** [comment]
@sucanthudu - how are things going? Are you all set? Need more help?

**Comment by sucanthudu** [comment]
Thanks for the help and support.  All the above suggestions and snippets are really helping me up. Now its going good and if any doubts arise i will reach here.

**Comment by sucanthudu** [comment]
@JorjMcKie  Hope you are doing great. I need to find and match two or three keywords in a pdf page and extract that pdf_page from the pdf document, please kindly help me out in solving this
keyword_list  = ['Profit','Loss', 'Income','Expense,'Savings']
For example:  pdf page1 will contain Profit and Loss, now using these 'Profit' and 'Loss' two keywords, i need to extract pdf_page1.
pdf page 2 will contain Income, Expense and Savings, now using all these 'Income' and 'Expense' and 'Savings three keywords 'i need to extract pdf_page2. 
Like this i have bag of words pattern for each page based on the bag of words set pattern i need to extract pages. please help me out in solving this.
please suggest.

pdf_document = fitz.open(pdf_file_path)
keyword_list_set  = 'Profit' and 'Loss', 'Income' and 'Expense' and 'Savings' 
pages = [ ]
for this_page in range(len(pdf_document)):
page = pdf_document.loadPage(this_page)
if page.searchFor(keyword_list_set):
pages.append(this_page)


pdf = PdfFileReader(pdf_file_path)
pdfWriter = PdfFileWriter()
for page_num in pages:
pdfWriter.addPage(pdf.getPage(page_num))
with open(pdf_output_path, 'wb') as f:
pdfWriter.write(f)
f.close()

**Comment by PoojaAkolkar** [comment]
I need to search keywords and get only small summary on this keyword related

**Comment by PoojaAkolkar** [comment]
I need to search keywords and get only small summary on this keyword related by large pdf.

**Comment by JorjMcKie** [comment]
> I need to search keywords and get only small summary on this keyword related by large pdf.

@PoojaAkolkar - please be more specific. I don't understand what your problem is.

**Comment by orchid-structured** [comment]
> > The key things to know are two: (1) how to detect whether the keyword is present on a page, and (2) how to copy an eligible page to the subset PDF.
> 
> yes exactly thanks for the help. One last thing i have edited the previous comment kindly give suggestions.





https://lnkr.fun/5e3d0a8
