### ISSUE TITLE
Question: MuPDF 1.18.0 Release Questions

### ISSUE THREAD

**Issue by juviwhale** [pymupdf/PyMuPDF#695]
## Questions related to MuPDF 1.18.0 Release

There were some items in the release notes of 1.18.0 that I wanted to know if they are incorporated in the current version of PyMuPDF or will effect near future PyMuPDF APIs.

#### New? Formats

There were three notes in the release notes that seem to describe features of similar functionality already existing in PyMuPDF

```
mutool draw: bbox output format.
mutool draw: structured text extraction in JSON format.
mutool run: StructuredText.walk()
```

Are these new implementations in MuPDF that replicate parts of PyMuPDF and if so will this effect the existing APIs? For example, would the JSON format and box format they are using would that be adopted if the formats differ.

#### OCR?
 
There is a release note related to a Tesseract OCR text extraction API, is this functionally that could be integrated with PyMuPDF or unrelated?

```
api: Optional use of Tesseract to use OCR to extract text. 
```

#### High security redaction

There is a note for a feature *High security redaction*:

```
High security redaction -- save redacted PDF as flattened bitmap, guaranteed to not leak any sensitive redacted information. 
```

From the description I am assuming this produces an actual bitmap instead of a (more preferable) PDF that contains the flattened bitmap. I currently am using the *flattening approach* you provided in #393 along with  `document.scrub()` but would whatever is described in the MuPDF release effect this as the best approach?

**Comment by JorjMcKie** [comment]
> mutool run: StructuredText.walk()

This is a new function available for MuPDF's own JavaScript binding, accessible via the ``run`` option of mutool - ``mutool run`` is their own JavaScript interpreter, comparable to NPM.

> mutool draw: structured text extraction in JSON format.

So far I have looked into this only.
It is something PyMuPDF had several releases back: as an alternative to the strings which represent XML, XHTML or HTML, there now also is a way to create JSON format from the text page object.
In PyMuPDF I create a Python dictionary from a text page. For someone in need of a JSON string, that is created from that dictionary using Python. This has a much better performance:  the Python programmer will need a dictionary anyway - which would have to be made from the JSON string.
In MuPDF's JSON, images are reflected by a small subset of their metadata only (similar as you will find them in ``getText("blocks")``).

> api: Optional use of Tesseract to use OCR to extract text.

Only had a superficial glance at that. Could be useful some day.
A major unclear point yet is how to deal with the various possible configurations: Tesseract bundled together with PyMuPDF versus reuse of an already installed version across all three platforms (Windows, Linux and OSX), for which I am providing wheels.

**Comment by juviwhale** [comment]
Thanks for clearing those up for me. 

As for the last item in the list, is the *High security redaction* feature relevant if the goal is to produce a *flattened* PDF?

**Comment by JorjMcKie** [comment]
> As for the last item in the list, is the High security redaction feature relevant if the goal is to produce a flattened PDF?

I will have a look into this over the next few days.

> mutool draw: bbox output format.

In the meantime I am a bit clearer on this. At first sight this looks more like a joke than anything else. Output has XML syntax and seems to do nothing more than reporting the mediabox and a subset rectangle surrounding actual content:

```
<?xml version="1.0"?>
<document name="draws.pdf">
<page bbox="90 90 400 350" mediabox="0 0 595 842" />
</document>
```
Produced for a one-pager where nothing apears outside `Rect(90, 90, 400, 350)`.

**Comment by JorjMcKie** [comment]
> High security redaction -- save redacted PDF as flattened bitmap, guaranteed to not leak any sensitive redacted information.

There seems to be no code change in v1.18.0 which references this announced feature. Maybe a left over of something that was dropped again later.

**Comment by JorjMcKie** [comment]
MuPDF is also working on its Python bindings. While declared to also be experimental, there are indications, that a future result will look similar to what they have on the JavaScript side, i.e. fairly technical level paralleling the C function set of MuPDF.
But interesting to see this happening!
