### ISSUE TITLE
Redaction of text outside of redaction annotation

### ISSUE THREAD

**Issue by juviwhale** [pymupdf/PyMuPDF#696]
## Bug Description

Applying a redaction annotation matches/removes elements not *well* contained in the annotation region.

## To Reproduce

With the attached example doc I find the 2nd word and use it's box as the location to place a redaction annotation. 

![Screen Shot 2020-10-21 at 12 58 09 PM](https://user-images.githubusercontent.com/6657003/96775905-13540a00-139d-11eb-9b00-9072ee36779b.png)

When redactions are applied the resulting PDF has other text items removed.

![Screen Shot 2020-10-21 at 12 58 53 PM](https://user-images.githubusercontent.com/6657003/96775974-2cf55180-139d-11eb-8a2a-4d7d6a5a21ff.png)

**SCRIPT**

Example PDF:

[position_tests.pdf](https://github.com/pymupdf/PyMuPDF/files/5418433/position_tests.pdf)

```
doc = fitz.open("position_tests.pdf")
pdf_page = doc[0]
word = pdf_page.getText('words')[1]
box = (word[0], word[1], word[2], word[3])

doc[0].addRedactAnnot(
    box,
    text='Q',
    fill=(0,0,0),
    text_color=(1,1,1)
)
doc.scrub()
```

## Expected behavior

I understand that the matching behavior of what elements should be redacted for a given region is non-trivial but the current logic is unclear. Orginally it was described in #434 as 

> Text inclusion decisions are made per each single character. A charater is regarded inside if this is true for the lower left bbox corner. So the better part of a character bbox may lie outside the redaction, and it will still be removed. Or vice versa: if the bbox corner is out side, it will survive the removal.

and from what I can determine in the provided PDF this wouldn't appear to match. I believe this have changed in v1.17 as described in the docs

> Text removal is done by character: A character is removed if its bbox has a non-empty intersection with a redaction (changed in MuPDF v1.17).

Though I am not sure the original inclusion logic would have handled this specific doc + redaction case. A more desirable solution in my opinion would take into account the % of intersection of elements perhaps.

## Configuration (mandatory)
```
3.8.2 (default, Aug 25 2020, 09:23:57) 
[Clang 12.0.0 (clang-1200.0.32.2)] 
 darwin 
 
PyMuPDF 1.18.1: Python bindings for the MuPDF 1.18.0 library.
Version date: 2020-10-18 09:50:36.
Built for Python 3.8 on darwin (64-bit).
```

**Comment by JorjMcKie** [comment]
MuPDF has indeed changed the logic recently with respect to this. While earlier the bottom left point of the char bbox decided this (never found an argument for doing so), it is now the non-empty intersection of the char bbox with the redaction rectangle.
Based on this, the observable action is consistent - look at this picture with each char surrounded by its bbox drawing:
![grafik](https://user-images.githubusercontent.com/8290722/96798793-a017bb80-13cf-11eb-9fc6-e1f9162fcab4.png)

All this is beyond control of PyMuPDF.
The only solution seems to be reducing the redact rectangle height. After all it may be any epsilon > 0 😉.

**Comment by juviwhale** [comment]
How would you recommend the best/most efficient approach to gathering all of the matched characters and determining that hight? Use of the newish Page.getTextbox(rect) to get the characters and then checking the overlap of each with the rect?

**Comment by JorjMcKie** [comment]
Yes, or assume ``rect`` is the hit rectangle, then compute a new rect like this
```python
nrect = +rect
nrect.y0 += rect.height * 0.4
nrect.y1 = nrect.y0 + rect.height * 0.2
```
and go with this rectangle. It only has a height of 20% of the original and is located around the middle horizontal line of the former one.

**Comment by JorjMcKie** [comment]
this replaces all the "x0" by red "??" ... still a bit shaky  though:
```python
for rect in page.searchFor("x0"):
    old_rect = +rect
    fontsize = rect.height / 1.45
    h = (rect.y0 + rect.y1) / 2
    d = rect.height * 0.1
    rect.y0 = h - d
    rect.y1 = h + d
    page.addRedactAnnot(rect)
    page.apply_redactions()
    print(page.insertTextbox(old_rect, "??", fontsize=fontsize, color=(1, 0, 0)))
```

**Comment by caerulescens** [comment]
@JorjMcKie @juviwhale If you use `set_small_glyph_heights(True)`, then adjacent text (`y0` and `Top`) is not removed and the redaction annotation properly covers `x0`.

`set_small_glyph_heights()` was released after this issue was created.

**Comment by JorjMcKie** [comment]
@caerulescens - thanks for commenting on this.

**Comment by JorjMcKie** [comment]
Many / most modern fonts have a "natural" lineheight which one should adhere to. It is calculated as fontsize * (font.ascender - font.descender) as explained in the docu.
But for the taste of some PDF creators this yields a too large gap between lines, so they use some fontsize * factor - with factor often being 1.2.
But the wel-known Helvetica already has
```python
>>> font.ascender-font.descender
1.3740000426769257
```
