### ISSUE TITLE
Question: Does document.scrub allow setting images options

### ISSUE THREAD

**Issue by juviwhale** [pymupdf/PyMuPDF#697]
The `page.apply_redactions` has a argument for how to redact overlapping images:

> images (int) – (new in v1.18.0) how to redact overlapping images. The default (2) blanks out overlapping pixels. PDF_REDACT_IMAGE_NONE (0) ignores, and PDF_REDACT_IMAGE_REMOVE (1) completely removes all overlapping images.

This should also be an optional argument of `document.scrub` method correct? or do I have a misunderstanding of the intention? It seems it would be appropriate and relevant on that method as well.

**Comment by JorjMcKie** [comment]
good point - will look into this, for the moment I think you are right.

**Comment by JorjMcKie** [comment]
Contained in v1.18.2 which is currently being uploaded to PyPI.
