### ISSUE TITLE
How to use pymupdf to extract table information??

### ISSUE THREAD

**Issue by kingqiuol** [pymupdf/PyMuPDF#700]
I need to extract PDF information, including: text, images and table information, but there is no way to extract table information in pymupdf.

**Comment by JorjMcKie** [comment]
That is correct: interpretation of table structures and other elements of tagged PDFs is not supported.

**Comment by JorjMcKie** [comment]
What is supported since v1.18.0 is extracting drawings, meaning lines, rectangles and curves.
This may help identifying tables ...

**Comment by MartinThoma** [comment]
Is there maybe an update to this?

Can PyMuPDF extract marked content from tagged PDFs?
