### ISSUE TITLE
Question: Solve words out of order in block text extraction

### ISSUE THREAD

**Issue by caiocesarrm** [pymupdf/PyMuPDF#702]
Words out of order in blocks when using getText("blocks") (print attached, yellow marked words should be on the beggining of the block). extracting words, instead of blocks, the x position seems to be correct (print attached).

example pdf: [example.pdf](https://github.com/pymupdf/PyMuPDF/files/5423965/example.pdf)

![expected_text](https://user-images.githubusercontent.com/41218670/96898813-8f665480-1466-11eb-8ba7-3879ca6af7ef.png)
![blocks](https://user-images.githubusercontent.com/41218670/96897563-1ca8a980-1465-11eb-8f55-3a34173842e6.png)
![words](https://user-images.githubusercontent.com/41218670/96897598-26321180-1465-11eb-8e80-67053b2becb9.png)

I didn't open as a bug because, although the y coordinate is really close (564,503 vs 564,598) they're not the same and i think that it's considered from another line.
I would like to know if this is the expected behaviour and if that is anything that i can do to solve this. Because i really like to cotinue using the blocks extraction.

3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] 
 linux 
 
PyMuPDF 1.17.7: Python bindings for the MuPDF 1.17.0 library.
Version date: 2020-09-14 06:33:06.
Built for Python 3.6 on linux (64-bit).

**Comment by JorjMcKie** [comment]
> I didn't open as a bug because, although the y coordinate is really close (564,503 vs 564,598) they're not the same and i think that it's considered from another line.

Exactly right. All text extractions **_strictly_** extract characters in the sequence as encountered in the body of the page's "source code" (the `/Contents` objects). No effort is made to reorder them.
This nicely shows in your list of extracted words: the last three integers of each word tuple are block, line, word number.
So whatever was the reason, the PDF was created by **_first_** adding ", brasileiro ... Santa" and **_then_** the person's name followed by "n° 05" etc.
In addition, the word's bottom coordinates are also different - although only slightly - etc. MuPDF puts words in one line if they have the same bottom coordinate.

This is unfortunate for sure, but the PDF creator is to blame here. I have seen examples though, **_where every single_** character appeared in arbitrary permutation in the page's source. Looking at the page, nothing seemed awkward - only all text extractions (including copy / pastes from the page) delivered total chaos.

Your case can be healed using relatively simple logic like the following function. You pass the wordlist to it and it will return a text string with a re-established reading sequence.

```python
def make_text(words):
    """Return textstring output of getText("words").

    Word items are sorted for reading sequence left to right,
    top to bottom.
    """
    line_dict = {}  # key: vertical coordinate, value: list of words
    words.sort(key=lambda w: w[0])  # sort by horizontal coordinate
    for w in words:  # fill the line dictionary
        y1 = round(w[3], 0)  # bottom of a word: don't be too picky!
        word = w[4]  # the text of the word
        line = line_dict.get(y1, [])  # read current line content
        line.append(word)  # append new word
        line_dict[y1] = line  # write back to dict
    lines = list(line_dict.items())
    lines.sort()  # sort vertically
    return "\n".join([" ".join(line[1]) for line in lines])
```

**Comment by caiocesarrm** [comment]
Really appreciate your very complete response, thank you!

**Comment by renewooller** [comment]
this should be a pull request! :-) thank you!
