### ISSUE TITLE
Question / Comment:Use Pymupdf to work on blocks/areas in PDF files

### ISSUE THREAD

**Issue by jiezhoujenny** [pymupdf/PyMuPDF#703]
Hi 
I recently found that, using PDF Pro "edit Text/images" tool, it will divide PDF page in to multiple blocks/ spots, as showing in attached picture.
I am wondering if pymupdf support working on each of these blocks so that it will allow users to compare pdf block by block? For example in this case, if changed Best over all response-n(%)  result from 41(29.2) to 42(29.2), I can extract text from this small block only and annotate the difference there. 

![image](https://user-images.githubusercontent.com/17275074/96914918-9e073880-1473-11eb-8c37-fa8a4950c459.png)

**Comment by JorjMcKie** [comment]
The term "block", when talking of text on a PDF page, is not defined by PDF specifications.
So you must expect, that different applications mean different things, when talking of "blocks" on PDF pages.
MuPDF collects text lines in one block based on a number of heuristics, which include line heights, font sizes, relative vertical and horizontal distances of line bboxes, etc.
But you now (v.18.1) can easily extract text from rectangles using `page.getTextbox(rect)` and do comparisons, etc.

**Comment by jiezhoujenny** [comment]
this is great, will try to work on as you advised.
Many thanks
