### ISSUE TITLE
Question / Comment: How to change transparency using Page.showPDFpage() to add image to a PDF Page?

### ISSUE THREAD

**Issue by zsesz110** [pymupdf/PyMuPDF#704]
I found Function **Page.showPDFpage()** has a Criterion named **transparency (water marking)**. 
Does it means that we can change the _transparency_ of PDF page which need to add to a pdf page? 
If YES, then How to change the transparency?
Hope reply!

Reference Source:
https://pymupdf.readthedocs.io/en/latest/faq.html#how-to-add-images-to-a-pdf-page

**Comment by JorjMcKie** [comment]
> Does it means that we can change the transparency of PDF page which need to add to a pdf page?
Now, it means, that if the shown PDF is transparent or has transparent parts, then the page contents of the original page will be visible under it. Like this:
Original page
![grafik](https://user-images.githubusercontent.com/8290722/96956435-1dbdf300-14c6-11eb-9ab1-32f2b7fe645c.png)
PDF page insert via showPDFpage
![grafik](https://user-images.githubusercontent.com/8290722/96956485-40500c00-14c6-11eb-8c0c-bbaaf12d456d.png)
Result
![0](https://user-images.githubusercontent.com/8290722/96956624-a472d000-14c6-11eb-8cb9-30d7d0725f30.png)

**Comment by zsesz110** [comment]
Thank for reply!
Is there a parameter can control the percentage of the transparency of the PDF page which need to add to a pdf page?
For example, like 50% transparency. 
I think it is necessary for **watermark** of PDF, maybe.
Hope reply!

**Comment by JorjMcKie** [comment]
No, there is no way to know that beforehand. The shown PDF page is what it is - it cannot be changed in any way.
You can try to convert that PDF page to an image (using pixmap with transparency), then manipulate transparency of that picture with some tool and finally use insertImage to overlay the target PDF page witg it.

**Comment by zsesz110** [comment]
Okay I see, thank for your patient reply.
