### ISSUE TITLE
Hi, The encrypted pdf can be opened in Microsoft Edge without entering a password.

### ISSUE THREAD

**Issue by Purple-tulip** [pymupdf/PyMuPDF#707]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Hi, i am a chinese python programer. Fitz is a GREAT module.  print("excellent!")
But i found a problem. I don’t know if it’s caused by my mistake.
The encrypted pdf can be opened in Microsoft Edge without entering a password.

## To Reproduce (mandatory)
`
import fitz
in_path = r"C:\Users\Caoyang\Desktop\cy.pdf"
output_path = r"C:\Users\Caoyang\Desktop\cy_enc.pdf"

encrypt_meth = fitz.PDF_ENCRYPT_RC4_40
user_password = '123456'
perm = fitz.PDF_PERM_ACCESSIBILITY

output_pdf = fitz.open(in_path)
output_pdf.save(filename=output_path, encryption=encrypt_meth,
                user_pw=user_password,
                permissions=perm)
`

## Expected behavior (optional)
(1) Open the encrypted file with Adobe, you need to enter the password 123456    Success!
(2) Open the encrypted file with Google, you need to enter the password 123456   Success!
(3) Open the encrypted file with Firefox, you need to enter the password 123456   Success!
(4) Open the encrypted file with microsoft Edge, you need to enter the password 123456  Success! (Unfortunately failed···)

## Screenshots (optional)
https://github.com/Purple-tulip/Pic/blob/main/goodle_open.png
https://github.com/Purple-tulip/Pic/blob/main/adobe_open.png
https://github.com/Purple-tulip/Pic/blob/main/Edge_open.png

## Your configuration (mandatory)
win10  64bit
python3.63  32bit

PyMuPDF 1.17.7: Python bindings for the MuPDF 1.17.0 library.
Version date: 2020-09-14 06:33:06.
Built for Python 3.6 on win32 (32-bit).

Microsoft Edge 44.19041.423.0
Microsoft EdgeHTML 18.19041

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

## Additional context (optional)
Looking forward to hearing from you :)

**Comment by JorjMcKie** [comment]
Hi Horatio,
the problem goes away if you also enter an **owner** password - not only a user password.
I will do this change that for the next version: a user password is also taken as the owner password if no owner password is provided.

**Comment by Purple-tulip** [comment]
print("Thanks :)")
