### ISSUE TITLE
Can we split a pdf into pieces based on the content (like tables, drawings and text separately) ?

### ISSUE THREAD

**Issue by kvrameshreddy** [pymupdf/PyMuPDF#708]
Hi @JorjMcKie,

can we split a pdf based on content like if a pdf consists of tables, pdf drawings and text.

can we extract them separately using pymupdf or is there any alternate to this requirement.

Need some help from you

thankyou.

**Comment by JorjMcKie** [comment]
What do you mean by "split a PDF"?
Take a PDF, read every page, create new pages in 3 new PDFs, where each new page receives either text, or drawings, or ...?
* You can extract text from a page (all document types) in a plethora of formats.
* You can extract drawings (also all document types) 
* You also can extract images

If you did all that ... what next?

Apart from that, PyMuPDF is currently not able to extract tables (or other tagged content) from PDF documents ...

**Comment by kvrameshreddy** [comment]
Thanks for the reply. 
I mean dividing a  single pdf page into sections with bboxes, indicating the sections with there tags like text, image, table and Drawings.

Is there any future development for extract tables from pdf using PyMuPDF ?

**Comment by JorjMcKie** [comment]
> Is there any future development for extract tables from pdf using PyMuPDF ?

Not at the moment. I don't want to develop something from ground up, not knowing when or whether at all my base library from MuPDF wil be doing this. Certainly MuPDF has currently no plans in that respect.

>  I mean dividing a single pdf page into sections with bboxes, indicating the sections with there tags like text, image, table and Drawings.

So from one input page you would create 3 or 4 output pages (PDF format again?) in 3 or 4 new PDF documents, where page-n from PDF 1 contains contains the text of page-n of the input, etc?
Text output looking like original, but all lines, curves, images missing? BTW If you answer "yes" here, that output would also include any table content formatted like the original, because all that is also text.
Etc.

For the stuff supported (i.e. except tables), there exist usable scripts, from which you can pull together what you require:
* For extracting drawing and reconstruct them on a new page, see [this](https://pymupdf.readthedocs.io/en/latest/faq.html#extracting-drawings) section in the documentation.
* For extracting text and reconstruct it on a new page, use the [font replacement](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/font-replacement) scripts. This currently creates a new PDF with one or more fonts exchanged by new ones. Otherwise the original page doesnt change. But you can easily modify it (1) write the extracted text on a new page and (2) copy over existing fonts if you don't wnat to replace them
* For image isolation, you can look for the images listed in `page.getImageList()`, determine the rectangle each one covers on the page (`page.getImageBBox()`), then extract the binary content `doc.extractImage()`, and insert the image again on the new page using all the extracted information.

**Comment by JorjMcKie** [comment]
Part of your above wording may also suggest, that you are just looking for a layout analyzer - not the **_reproduction_** of original content categories.
If so, you could reuse and extend this script: https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/layout-analyzer.py

**Comment by kvrameshreddy** [comment]
Thank you @JorjMcKie for taking time and helping me.

**Comment by HeroadZ** [comment]
Could page.getText() ignore the text from a table?

**Comment by JorjMcKie** [comment]
> Could page.getText() ignore the text from a table?

Not `getText)` directly. Only your program logic **_using_** `getText()` and potentially `getDrawings()` -- which detects drawings (rectangles, lines, curves) on a page.
Anything inside an image however is ignored.

For example, if you know a rectangle within which the table is located, you can easily sub-select the rest of the page - by telling `getText()` to only look at certain areas.

**Comment by HeroadZ** [comment]
Thank you for the quick reply! Is there any code snippets for that? like detecting rectangles by drawing or sub-selecting the rest of the page?

**Comment by JorjMcKie** [comment]
You can sub-select the getText() output via the `clip` parameter. This is a rectangle and is simply used like that: ``page.getText(option, flags=0, clip=rect)``.
Option is one of "text", "dict", "words", "blocks", "rawdict". Depending on this, the output format varies (could be list or dict or string).
Flags=0 means: no image extraction, replace all whitespace by blanks, decompose ligatures.
If you **_know the table rectangle_**, there are up to 4 remaining rectangles on the page, you could use as the clip:
1. sub-rectangle above the table's top
2. sub-rectangle below the table's bottom
3. sub-rect to the table'left (but not intersecting top / bottom sub-rectangles
4. sub-rect to the right accordingly

It might be simpler though, to just extract the whole page and discard contents within the table rect. For example, extract text pieces ("spans") outside table_rect, returning a list of those pieces, each with its coordinates:
```python
span_list = []
for block in page.getText("dict", flags=0)["blocks"]:  # a list of text block dictionaries
    for line in block["lines"]:
        for span in line["spans"]:
            span_rect = fitz.Rect(span["bbox"])  # rect of span text
            if span_rect not in table_rect:  # ensure outside table area
                span_list.append((span_rect, span["text"]))
# the span_list can now be processed as desired.
```
-------
Example for extraction of drawings: Suppose you have a page looking like this (circle and rectangle, overlapping, some opacity):
![grafik](https://user-images.githubusercontent.com/8290722/100717713-cf3b2880-3390-11eb-8ca5-db0d4d87271d.png)
The do this:
```python
>>> import fitz
>>> doc=fitz.open("draws.pdf")
>>> page=doc[0]
>>> from pprint import pprint
>>> paths=page.getDrawings()
>>> pprint(paths)  # should be a list of 2 items:
[{'closePath': False,  # this is the rectangle
  'color': None,  # no stroke color
  'dashes': '[] 0',  # no line dashing
  'even_odd': False,  # no special PDF color switching
  'fill': [0.0, 0.0, 1.0],  # fill color blue
  'items': [('re', Rect(100.0, 100.0, 300.0, 150.0))],  # could be a list, e.g. of draw commands
  'lineCap': (0, 0, 0),  # show shape of line ends
  'lineJoin': 0,  # show shape of line connections
  'opacity': 0.3,  # 30% opacity
  'rect': Rect(100.0, 100.0, 300.0, 150.0),  # joined retangle of all "items"
  'width': 1.0},
 {'closePath': True,  # this is the circle
  'color': None,
  'dashes': '[] 0',
  'even_odd': False,
  'fill': [1.0, 0.0, 0.0],
  'items': [('c',  # consists of 4 curves: one per quarter circle
             Point(200.0, 150.0),
             Point(200.0, 205.22802734375),
             Point(244.77200317382812, 250.0),
             Point(300.0, 250.0)),
            ('c',  # "curve" command
             Point(300.0, 250.0),
             Point(355.2279968261719, 250.0),
             Point(400.0, 205.22802734375),
             Point(400.0, 150.0)),
            ('c',
             Point(400.0, 150.0),
             Point(400.0, 94.77197265625),
             Point(355.2279968261719, 50.0),
             Point(300.0, 50.0)),
            ('c',
             Point(300.0, 50.0),
             Point(244.77200317382812, 50.0),
             Point(200.0, 94.77197265625),
             Point(200.0, 150.0))],
  'lineCap': (0, 0, 0),
  'lineJoin': 0,
  'opacity': 0.3,
  'rect': Rect(200.0, 50.0, 400.0, 250.0), # the square containing the circle
  'width': 1.0}]
>>> 
```

**Comment by HeroadZ** [comment]
Thank you very much! I will try to recognize table rect based on the drawings even though it might be difficult.

**Comment by JorjMcKie** [comment]
If you know some unique keywords of text **_within_** the table, your life may be easier than looking for the right lines, or other drawings.
Maybe the header row contains something? Or the footer?
You could search the page for this: this will return "hit" rectangle(s), which you can use as the table rectangle boundaries ...
If you let me know an example PDF, I am willing to suggest some code ... 😎

**Comment by HeroadZ** [comment]
Thank you very much for your suggestions. There is no keywords that can be used for detection. But each table has a head for description. Here is a sample file. I want to ignore the the text from tables as well as the figure caption and table head if possible.

[sample.pdf](https://drive.google.com/file/d/1Pp679QHgEXYuYubN8PCCDvB4IXsmzlw_/view?usp=sharing)

**Comment by JorjMcKie** [comment]
Here is something that may help ... at least a bit. It all depends how reliable the following assumptions are. They are based on this one page only of course:

* Assumption: captions of images and tables are without line break always
* Assumption: there never is text to the right or to the left of a table
* Assumption: every table has wrapped by three lines: one at its top, two below the header, three at its bottom.

Here is a starter script, that at least works for this page:

[text-detector.zip](https://github.com/pymupdf/PyMuPDF/files/5627975/text-detector.zip)

**Comment by HeroadZ** [comment]
Thank you very much again for you great effort on it! I will try it based on your script.
