### ISSUE TITLE
Add the ability to mutool clean -d -f -i input.pdf output.pdf 

### ISSUE THREAD

**Issue by z4rd0s** [pymupdf/PyMuPDF#713]
Hi,

after open and processing a PDF I want to save the new content but only compress image and font streams.
PyMuPDF only provides the possibility to set a single value to doc.save() expand argument like

```
    doc.save(output.pdf, expand=1) 
```
But the mutool binary allows to combine multiple flags (`-d` `-f` and `-i`) to selectively compress/to not uncompress different types of stream (https://mupdf.com/docs/manual-mutool-clean.html):

```
mutool clean [options] input.pdf [output.pdf] [pages]
- d
Decompress streams. This will make the output file larger, but provides easy access for reading and editing the contents with a text editor.
-i
Toggle decompression of image streams. Use in conjunction with -d to leave images compressed.
-f
Toggle decompression of font streams. Use in conjunction with -d to leave fonts compressed.
```
As a workaround I'm first saving the modified PDF using doc.save() and call the mutool binary directly afterwords to overwrite the previously created PDF.

Would be awesome to integrate this functionality by e.g

```
doc.save(output_file_path, expand=[1,2,255])
```

Thx for considering, and keep up the awesome work! Great project!

**Comment by JorjMcKie** [comment]
Hi,
thanks for voicing this request. I think it makes sense.
My original motivation was to limit the number of ``save()`` / ``write()`` parameters. But since then a lot of time has passed and quite a number of new parameters caring about e.g. encryption have been introduced.
So this stinginess no longer makes sense.
What I will probably do is splitting up expand and deflate into sub-parameters for images, resp. fonts ... after some consideration on how to maintain backward compatibility.

**Comment by JorjMcKie** [comment]
Keep in mind however: if you do ``mutool clean -dfi infile.pdf``, then indeed every stream will first be decompressed, and then **_only_** image and font streams will be recompressed. This leaves several potentially large streams uncompressed, e.g. contents streams of pages and Form XObjects. Some CMAP streams (font character maps) may also be quite large and will stay uncompressed.

**Comment by JorjMcKie** [comment]
After a long time (which I mentioned above) looking again at the save/write parameter details, I found that the documentation no longer reflects MuPDF reality anymore:

* One cannot separately ``expand`` subcategories of streams: all streams will be expanded.
* Compress / deflate can be restricted to images and fontfiles independently.

So what will probably will happen are 2 new parameters `deflate_images`` and ``deflate_fonts``. Both should be used in conjunction with ``expand``, and the effect will be that every stream is expanded except image, resp. fontfile streams.
This will establish the same behaviour as in the CLI mutool.
This includes reactions to "foolish" combinations like "expand=True, deflate=True, deflate_images=True`` or similar.

**Comment by z4rd0s** [comment]
oh wow, thx for the very quick reply!

Yes, I'm aware of that some big streams may stay uncompressed, but the opportunity of "selective compression" is exactly what I need for my application. 

Cool, I like your suggestion with the additional parameters. Can't wait to try it ;-)

**Comment by JorjMcKie** [comment]
😎 what is your configuration?
I think I can make available a pre-release wheel today. If Windows, I'll have to post in this channel and need to know the exact config (Py version, bitness), otherwise, you can download from the wheel repo once ready.

**Comment by z4rd0s** [comment]
so cool! 
I'm using Ubuntu 64bit with Python 3.8, thx man!

**Comment by JorjMcKie** [comment]
Please find your pre-release wheel [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux).

**Comment by z4rd0s** [comment]
works like a charm! thx!

**Comment by JorjMcKie** [comment]
New version with these changes being uploaded.
