### ISSUE TITLE
text or popup annotation add setOpen() method? 

### ISSUE THREAD

**Issue by cole-dda** [pymupdf/PyMuPDF#716]
text , popup annotation add setOpen() method?

**Comment by JorjMcKie** [comment]
Don't understand - please be more verbose!

**Comment by JorjMcKie** [comment]
... and BTW popup annotations are not supported at all.

**Comment by cole-dda** [comment]
<img width="849" alt="screenshot_3874" src="https://user-images.githubusercontent.com/1077830/98840907-5ed07400-2482-11eb-8f06-ce1093dfc038.png">

**Comment by cole-dda** [comment]
by the way, why not support popup?

text,highlight annotation can have popup

**Comment by JorjMcKie** [comment]
Ok, understood you now.
I know that PDF spec contains this. The question is however, whether the C library that I am wrapping, is supporting this too.
I will check.

**Comment by JorjMcKie** [comment]
Your request was good timing:
The MuPDF C base library now does support popup annotations as well. I will extend PyMuPDF accordingly with the next version.

**Comment by JorjMcKie** [comment]
I have developped a first version. If you want to help testing it, please let me know your configuration (`print(fitz.__doc__)`) and I will point you to a pre-release wheel.

**Comment by JorjMcKie** [comment]
New version available on PyPI:
