### ISSUE TITLE
Remove form fields

### ISSUE THREAD

**Issue by papafelice** [pymupdf/PyMuPDF#718]
I have various documents that have predefined signature field that have some kind of password protection and can only be signed with a hardware token. This is really annoying.

I have a viewer where I can click on the field and display its internal data. What I would like to do now is delete the selected field. How can this be done? Also, this would help to remove other fields that had been added to a page but should be "undone".

**Comment by JorjMcKie** [comment]
Oh - there is no `deleteWidget` method yet. Should be easy to implement, but it's not there yet.
Let me check.

**Comment by JorjMcKie** [comment]
This is unfortunate: MuPDF does not support deleting widgets
So I have to create that code ...

**Comment by JorjMcKie** [comment]
Have a solution.
If you tell me your configuration, I can send you a wheel download address to test it.
It works like annot deletion: ``next_widget = page.deleteWidget(old-widget)`` - a `Page` method, which needs the field to be deleted, returning the following field (or None).

**Comment by papafelice** [comment]
Now that's what I call fast...

Linux 5.9.1-1-default #1 SMP Mon Oct 26 07:02:23 UTC 2020 (435e92d) x86_64 x86_64 x86_64 GNU/Linux
Python 3.8.5

 
 

Gesendet: Mittwoch, 11. November 2020 um 20:47 Uhr
Von: "Jorj X. McKie" <notifications@github.com>
An: "pymupdf/PyMuPDF" <PyMuPDF@noreply.github.com>
Cc: "papafelice" <felix.huber@schyf.de>, "Author" <author@noreply.github.com>
Betreff: Re: [pymupdf/PyMuPDF] Remove form fields (#718)


 

Have a solution.
If you tell me your configuration, I can send you a wheel download address to test it.
It works like annot deletion: next_widget = page.deleteWidget(old-widget) - a Page method, which needs the field to be deleted, returning the following field (or None).

**Comment by JorjMcKie** [comment]
Here is the repo branch for the Linux wheels: https://github.com/pymupdf/PyMuPDF-wheels/tree/linux.

**Comment by papafelice** [comment]
It works, the field gets deleted.
When saving the file, there are a lot of errors like this one:
mupdf: object out of range (807 0 R); xref size 192

**Comment by JorjMcKie** [comment]
Can I have the example PDF please? Obviously there are uncovered cases ...

**Comment by JorjMcKie** [comment]
Never mind - found an error, **_the_** error. New weel generation underway, I'll let you know when you can try again.

**Comment by JorjMcKie** [comment]
New wheels now ready.
Some background:
Technically, fields are special annotations. Apart from being listed in the PDF page definition int the `/Annots` array, they also are listed independently in the central `AcroForm/Fields` array of the document catalog. That's where I forgot to remove the field from ...

**Comment by papafelice** [comment]
No luck yet, I still get errors when deleting and saving under a new name.
I managed to create minimalistic demo files: Demo1.pdf is the original, Demo2.pdf has the third text field removed and then saved under this new name. The console then shows:
mupdf: object out of range (18 0 R); xref size 17
mupdf: object out of range (19 0 R); xref size 17
repeated many times.
[Demo1.pdf](https://github.com/pymupdf/PyMuPDF/files/5537356/Demo1.pdf)
[Demo2.pdf](https://github.com/pymupdf/PyMuPDF/files/5537358/Demo2.pdf)

**Comment by JorjMcKie** [comment]
thank you!
I'll let you know how this works out.

**Comment by JorjMcKie** [comment]
> mupdf: object out of range (18 0 R); xref size 17
mupdf: object out of range (19 0 R); xref size 17

This is weird and I cannot reproduce. Everything works fine on my machine.
Those two objects (Form XObjects) are btw unused - they get garbage collected when cleaning demo1.pdf via `mutool clean -ggg demo1.pdf`.
The final PDF trailer (there are several delta data because of incremental updates) says "size 17", which means xrefs 18 and 19 are illegal anyway.
A complete session with idle follows next post

**Comment by JorjMcKie** [comment]
```python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import fitz
>>> doc=fitz.open("Demo1.pdf")
>>> page = doc[0]
>>> for w in page.widgets():  # loop through fields
	print(w.xref, w)

	
4 'Text' widget on page 0 of Demo1.pdf
6 'Text' widget on page 0 of Demo1.pdf
7 'Text' widget on page 0 of Demo1.pdf
>>> doc.PDFCatalog()
15
>>> print(doc.xrefObject(15))  # print PDF catalog for demoing
<<
  /Type /Catalog
  /Pages 8 0 R
  /OpenAction [ 1 0 R /XYZ null null 0 ]
  /Lang (de-DE)
  /AcroForm <<
    /Fields [ 4 0 R 6 0 R 7 0 R ]  # the field xrefs
    /DR 11 0 R
    /NeedAppearances true
  >>
>>
>>> print(doc.xrefObject(page.xref))  # print page defintion, too
<<
  /Type /Page
  /Parent 8 0 R
  /Resources 11 0 R
  /MediaBox [ 0 0 595.30398 841.8898 ]
  /Annots [ 4 0 R 6 0 R 7 0 R ]  # the annot / link / field xrefs
  /Group <<
    /S /Transparency
    /CS /DeviceRGB
    /I true
  >>
  /Contents 2 0 R
>>
>>> page.deleteWidget(w)  # now delete last widget
>>> print(doc.xrefObject(page.xref))  # show page again
<<
  /Type /Page
  /Parent 8 0 R
  /Resources 11 0 R
  /MediaBox [ 0 0 595.30398 841.8898 ]
  /Annots [ 4 0 R 6 0 R ]  # xref 7 removed!
  /Group <<
    /S /Transparency
    /CS /DeviceRGB
    /I true
  >>
  /Contents 2 0 R
>>
>>> print(doc.xrefObject(15))  # print catalog again
<<
  /Type /Catalog
  /Pages 8 0 R
  /OpenAction [ 1 0 R /XYZ null null 0 ]
  /Lang (de-DE)
  /AcroForm <<
    /Fields [ 4 0 R 6 0 R ]  # xref 7 removed here too
    /DR 11 0 R
    /NeedAppearances true
  >>
>>
>>> doc.save("without-last-widget.pdf", garbage=3, pretty=True)  # save the file as new
>>> print(fitz.TOOLS.mupdf_warnings())  # check if mupdf had anything to complain

>>> # nope
```

**Comment by papafelice** [comment]
You're right, this is weird. When I do the same commands by hand, everything is fine. I think your code is just perfectly fine.

I could track the problem down to a single line of code: I have a viewer with a scrollable list of thumbnails of all the pages:

    class ThumbList(QListWidget):
        """
        A scrollable thumbnail preview list using a QListWidget
        """
        def __init__(self, parent=None, thumbSize=200):
            super().__init__(parent)    
            self.setThumbSize(thumbSize)
        
        def resetPreview(self, pageCount, pageNum):
            """
            fill the preview list with thumbnails of pages
            """
            self.clear()
            for i in range(pageCount):
                item = QListWidgetItem(str(i+1))
                item.setSizeHint(QSize(item.sizeHint().width(), self.thumbSize))
                self.addItem(item)
            self.setCurrentRow(pageNum)  # This line of code causes the error.

Calling the last line makes the errors appear, even if I just open the file and save it again without doing anything else.
If I comment it out, all is fine until I delete a field, then the errors also appear. That makes no sense to me yet.

**Comment by JorjMcKie** [comment]
Ok, I think the file itself has a problem - independent from widgets and all.
It probably will behave decently if cleaned up via that mutool command or PyMuPDF equivalent before all processing.
As mentioned, xref 18 / 19 exist but are not used by anything.

Maybe a little more radical approach may help: there is a `Document` method, which reloads a page and in so far forces all page updates to be finished in a consistent way. Useful after inserting annots or fields, but before taking pixmaps of that page.
Maybe it can help here too: `page = doc.reload_page(page)`. It actually internally scrolls away from the page and then reloads - re-establishing any parent / child connections to annots / widgets from before.
Maybe give it a try.

**Comment by papafelice** [comment]
The reload_page() is already in, I call it when I add or delete widgets in order to have viewer reflect the changes.
I have a split screen viewer with a list of thumbnails and the main view of the current page. I noticed that the error shows up on more files, when the thumb list gets updated while the main view is also refreshed, both of them calling getpage() for different page numbers. Can that be a problem?
So I changed the startup sequence a little bit and I can open and save the test files without error.

I have created to more test files, DemoA and DemoB. DemoA ist created with LibreOffice and exported as a pdf form. DemoB is DemoA openend with Okular, has the field content updated and then saved under the new name.

When opening DemoA with my viewer, the content of the three text forms **is not** displayed, but I can delete them and save under a new name without errors.

When openning DemoB, the content of the three text forms **is** displayed, but deleting the third one and saving under a new name gives several of these errors:
mupdf: object out of range (18 0 R); xref size 17
mupdf: object out of range (19 0 R); xref size 17

In both cases, after deleting the widget, a call to reload_page() was made. I also tried cleanContents(), no difference.
[DemoA.pdf](https://github.com/pymupdf/PyMuPDF/files/5540883/DemoA.pdf)
[DemoB.pdf](https://github.com/pymupdf/PyMuPDF/files/5540884/DemoB.pdf)

**Comment by JorjMcKie** [comment]
Replying by mail b/o sh***y internet connection.
Whatever is happening there, it has nothing to do with PyMuPDF. With my choice of PDF viewers, this is the situation (all checked on Windows 10):

  *   DemoA.pdf
     *   SumatraPDF: ok
     *   MuPDF: empty fields
     *   Adobe Acrobat: illegible (only dots, no letters)
     *   Foxit Reader: ok
     *   PDF-Xchange Viewer: ok
  *   DemoB.pdf
     *   SumatraPDF: ok
     *   MuPDF: ok
     *   Adobe Acrobat: illegible (only dots as before)
     *   Foxit Reader: ok
     *   PDF-Xchange Viewer: ok

Both files respond decently and correctly when removing form fields with the code snippet communicated in previous post. No errors, etc.
The updates (using garbage=3) did not change the legibility with any of the above viewers.

Doing doc.reload_page() of course only has an effect in on PyMuPDF functions. Other software components (from Qt and what not) will not necessarily benefit from this and may refer to information of the PDF which is not valid anymore.
Xref numbers 18 and 19 do not exist in DemoA.pdf nor in DemoB.pdf. So I guess an analysis must start at where some function is requesting those inexistent objects …

Jorj

**Comment by papafelice** [comment]
I can confirm this, some viewer show the fields, some not and your code **just works fine** if I don't use my QT based viewer. So, there is more debugging on my side needed, but since I wanted to improve my Python skills, this is it.

Interesting effect: If I decompress the file like this:
qpdf --stream-data=uncompress  DemoB.pdf DemoB1.pdf
everthing works fine.
>must start at where some function is requesting those inexistent objects …

All I do is call the save funtion, those errors are from the mupdf library, right? Can there be some kind of memory corruption?
Is there a way to "dump" the whole PDF in memory to see if it is already corrupted before saving?

**Comment by JorjMcKie** [comment]
> those errors are from the mupdf library, right?

Correct.

> Is there a way to "dump" the whole PDF in memory to see if it is already corrupted before saving?

Yes, there is `doc.write(...)` with pretty much the same parameters as `save`. This delivers a ``bytes`` binary object of the whole PDF in its current state.
After that you can check (print()) `fitz.TOOLS.mupdf_warnings()` to see whether any errors occurred so far.
This binary object can be saved as a file via

```python
output = open("some.pdf", "wb")
output.write(bytes_object)
output.close()
```
BTW the PDF is not necessarily corrupt - so far we only know, that some parts of your script try to access non-existent XREFs ...

If decompressing prevents those errors, you can do all that too within your script:

```python
doc0 = fitz.open("file.pdf")
stream = doc0.write(expand=True, garbage=4)
doc0.close()
doc = fitz.open("pdf", stream)
# work with the decompressed PDF
```

**Comment by JorjMcKie** [comment]
I am beginning to suspect, that the Qt methods in your script are allowed to do their own access to the PDF - not using PyMuPDF that is.
If so, this should be suppressed by all means! All access must happen only via one PDF access method, otherwise inconsistencies will definitely occur, if either does updates.

**Comment by papafelice** [comment]
> the Qt methods in your script are allowed to do their own access to the PDF 

They are not: I use pyQt only to display the images in the main view and in the thumblist like this:

    def _renderPage(page, scale):
        # generate final scaling matrix 
        mat = fitz.Matrix(scale, scale)
        # Render current page
        pix = page.getPixmap(matrix=mat)
        # set the correct QImage format depending on alpha
        fmt = QImage.Format_RGBA8888 if pix.alpha else QImage.Format_RGB888
        qtimg = QImage(pix.samples, pix.width, pix.height, pix.stride, fmt)
        return qtimg

All other processing is done via calls to pymupdf objects only, not via Qt.

I have to see where the break in my code occurs. On some files, if I call pdf.savepdf() directly after deleting a widget, no errors occur and I can then call the original save function (which in turn calls savepdf()) also without errors. But only on some files, others don't work out fine.

**Comment by JorjMcKie** [comment]
Hm - immer rätselhafter.
So decompression is not the **_"Allheilmittel"_**?
I am volunteering to help you debug this: If you want, you can send me the script and the most misbehaving file ...

**Comment by papafelice** [comment]
>I am volunteering to help you debug this: If you want, you can send me the script and the most misbehaving file ...

Greatly appreciated. But beware, it's more than just a script...
I was struggling with 2FA but finally I managed to push my repository with ssh. Look for Cannibal, it should run mostly also under Windows, with some loss of comfort though (no common icons, etc).
Moving the mouse over a widget and right click pops up a dialog where you can confirm the deletion. After that calling save_as shows the errors on the console. Look for "fixme" in cannibal.py, there is comment on  what I found so far.

**Comment by JorjMcKie** [comment]
New version available on PyPI:
