### ISSUE TITLE
Page.showPDFpage error

### ISSUE THREAD

**Issue by hbh112233abc** [pymupdf/PyMuPDF#722]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I use `Page.showPDFpage` copy page from another pdf,but new page display not same with old page from a special pdf document. Maybe it's page size is too large (width: 42cm height:29.7cm)

## To Reproduce (mandatory)
```
    old_pdf = fitz.open('./temp/old.pdf')
    new_pdf = fitz.open()
    for old_page in old_pdf.pages():
        new_page = new_pdf.newPage(
            old_page.number,
            old_page.rect.width,
            old_page.rect.height
        )
        new_page.showPDFpage(old_page.rect, old_pdf, old_page.number)
    new_pdf.save('new.pdf')
```
[old.pdf](https://github.com/pymupdf/PyMuPDF/files/5530632/old.pdf)
[new.pdf](https://github.com/pymupdf/PyMuPDF/files/5530634/new.pdf)

## Expected behavior (optional)
other pdf not found this problem

## Screenshots (optional)
![old_page](https://user-images.githubusercontent.com/7788164/98941930-3438f680-2528-11eb-840b-a5e81530592f.png)
![new_page](https://user-images.githubusercontent.com/7788164/98941948-3a2ed780-2528-11eb-8c03-9d741c4d4ee7.png)

## Your configuration (mandatory)
 - win10
 - python 3.7 64bit
 - PyMuPDF 1.18.3, installation method (pip install PyMuPDF).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).
```
3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
 win32

PyMuPDF 1.18.3: Python bindings for the MuPDF 1.18.0 library.
Version date: 2020-11-09 07:36:17.
Built for Python 3.7 on win32 (64-bit).
```

**Comment by JorjMcKie** [comment]
The problem here is that the input page is **_rotated_**.
So you should either rotate ``new_page`` in the same way, or specify the rotation parameter in ``showPDFpage``.

**Comment by JorjMcKie** [comment]
To be on the safe side:
1. set old page rotation to 0 first
2. create new_page and do showPDFpage
3. reset old_page rotation back to old value.

**Comment by JorjMcKie** [comment]
This script works fine:
```python
import fitz

src = fitz.open("old.pdf")
spage = src[0]
oldrot = spage.rotation
spage.setRotation(0)
doc = fitz.open()
npage = doc.newPage(width=spage.rect.width, height=spage.rect.height)
npage.showPDFpage(
    npage.rect,
    src,
    0,
)
npage.setRotation(oldrot)
doc.save("new.pdf")
```

**Comment by hbh112233abc** [comment]
Yes your script works fine. it solve my problem,thank you very much! 👍
