### ISSUE TITLE
In the extract images from a PDF, some are shown with inverted colors

### ISSUE THREAD

**Issue by albertochigua** [pymupdf/PyMuPDF#725]
# Problem
I try to extract the images from a PDF, the images are in jpx and I have simply saved them as jpg, some work (img1) and others come inverted (img2), I thought that the original image inside the pdf (img2) could be png and that I was losing the alpha channel, but when I get its extension all the images are jpx.

# Images
## img1
![image2_2](https://user-images.githubusercontent.com/20590139/99621836-76fa4300-29ee-11eb-927a-c2c6d447fd3b.jpg)
## img2
![image14_8](https://user-images.githubusercontent.com/20590139/99621875-8d080380-29ee-11eb-8814-2c38416f0385.jpg)

# Code

```
import fitz # PyMuPDF
import io
from PIL import Image
import os, sys

mydir = os.path.abspath(os.path.dirname(sys.argv[0]))


file = mydir+ "/p.pdf"
# open the file
pdf_file = fitz.open(file)

# iterate over PDF pages
for page_index in range(len(pdf_file)):
    # get the page itself
    page = pdf_file[page_index]
    image_list = page.getImageList()
    # printing number of images found in this page
    if image_list:
        print(f"[+] Found a total of {len(image_list)} images in page {page_index}")
    else:
        print("[!] No images found on page", page_index)
    for image_index, img in enumerate(page.getImageList(), start=1):
        
        # get the XREF of the image
        xref = img[0]
        # extract the image bytes
        base_image = pdf_file.extractImage(xref)
        image_bytes = base_image["image"]
        # get the image extension
        image_ext = base_image["ext"]
        # load it to PIL
        image = Image.open(io.BytesIO(image_bytes))
        # save it to local disk
        rgb_im =  image.convert("RGB") 
        rgb_im.save(open(f"{mydir}/img/image{page_index+1}_{image_index}.{image_ext}", ["wb"))]([url]([url]( @url)))
```

**Comment by albertochigua** [comment]
I just saved (img2) as jpg by right clicking and "save as" in my PDF viewer and the imgan has been saved correctly.

## img2
![img](https://user-images.githubusercontent.com/20590139/99622860-95613e00-29f0-11eb-9ebf-fbac897d4dc5.jpg)

**Comment by JorjMcKie** [comment]
I need the PDF to reproduce.
Even though a JPX, there could be an SMask (2nd item in the image list entry), which in this case you need to process too ... like in the (new version of) script extract-imga.py.

**Comment by albertochigua** [comment]
this is the pdf
[p.pdf](https://github.com/pymupdf/PyMuPDF/files/5567406/p.pdf)

**Comment by JorjMcKie** [comment]
Well, I don't yet understand the reason for this, but there is something special in these cases:
if you use the MuPDF extraction ``mutool extract p.pdf``  it will also extract images (and fonts), but create unusable extractions for a lot of the images.
Only if you force it to **_convert everything to RGB colorspace_**, things will work right and produce correct output in all cases: ``mutool extract -r p.pdf``.
The PyMuPDF equivalent is this (it works equally well as the mutool CLI):
```python
for i in range(doc.pageCount):
    for item in doc.getPageImageList(i):
        pix = fitz.Pixmap(doc, item[0])  # pixmap from the image xref
        pix0 = fitz.Pixmap(fitz.csRGB, pix)  # force into RGB
        pix0.writeImage("img%i.png" % item[0])
```
So best use this workaround for now.
I will see if I find the indicators to automatically switching to RGB PNG images when encountering images.

**Comment by albertochigua** [comment]
It works very well.

There is a lot to understand about the structure of the PDF format, it would be great to get more documentation about pyMuPDF.

Thanks a lot!

**Comment by JorjMcKie** [comment]
For your info: there is a [new version](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/extract-imga.py) of the PDF image extraction script, which automatically discovers / handles situations like in your example.

**Comment by suparnaj3** [comment]
I have gone through a similar issue. Sometimes, the image will be having a mask only.

I am using a workaround to handle this scenario:
```
pix = fitz.Pixmap(fitz.csGRAY, [0, 0, w, h], True)
pix_alpha = fitz.Pixmap(image_bytestr)
pix.set_alpha(pix_alpha.samples)
pix.save('img.png')
```

In this case, the image is not there in the getImageList() result. 

It will be present in the get_image_info(), but there's no parameter to identify that it's a mask. Currently, checking whether 'bpc' value is 1.

@JorjMcKie, It would be better to have some parameter that describes whether it's a mask or not.

Also, I am confused about whether it should be included in the getImageList() result.

**Comment by JorjMcKie** [comment]
> Also, I am confused about whether it should be included in the getImageList() result.

The `get_page_images()` list only enumerates images contained in the page's object definition. This is the `/Resourcs` dictionary of PDF pages.
But in addition to these, a page may contain more images. See the documentation (see the TextPage chaper) which these additional images may be.

Methods `page.get_image_info()` and `page.get_text(...)` in contrast deliver a complete image list. For the first method, you can request to find image xref number, where there are any.
The image information of these two methods do not and cannot contain information about any masks. Only if an xref > 0 is contained in `get_image_info` (optional request), you can find out any mask xref by inspecting the `get_images()` list.
