### ISSUE TITLE
use page.getText() method, found some random code

### ISSUE THREAD

**Issue by leyiwang** [pymupdf/PyMuPDF#729]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When i read a `pdf` format file using pymupdf, i found some chars random code, like this:
```
前  言 
����本书��2版，��版不���Elasticsearch���版本���内容，������
��1版中�����内容。���本书，����Elasticsearch�������文������
�。本书���Elasticsearch�������，�中���何�����Elasticsearch�Elasticsearch
��本��，以��何以��本�方式�������。 
本书�������Querydsl�����，���可以��复������������。
����，������何���面���faceting��������������，以��何
���������������，可以����������。�������������，
����何��Elasticsearch��������spatial capability������prospective search�。 
��，�本书�����Elasticsearch���API，������制��������。 
本书主要内容 
第1章 Elasticsearch集群入门，������文���Apache Lucene�文本����何�
����Elasticsearch。��，�����何以��本�方式�������。 
第2章 索引，���������，�何������，可以����������，�
何����，�����segment�，���merging���何���，����由�routing�。 
第3章 搜索，��Elasticsearch��文����。�����何��，�������，有
���本���复���。����，本������何������，�何����以���
�������。 
第4章 扩展索引结构，���何���复������。本����何��������
������，以��������。 
第5章   更好的搜索，��Apache Lucene�����，以���Elasticsearch��本����
�����何���� 。 
第6章 超越全文检索，�������������面以��何��Elasticsearch����
图灵社区会员 打顺顺(lvshun@live.cn) 专享 尊重版权
```
the file and code as follows:
https://drive.google.com/file/d/1ZFzIQXFMAlvRY9WKM1wA43Q7Iv4rvRxT/view?usp=sharing
```
filepath = "pages-7-7.pdf"

with fitz.open(filepath) as doc:
    for idx, page in enumerate(doc):
        for block in page.getText('rawdict')["blocks"]:
            for item in block.get("lines", []):
                print("".join(chars["c"] for span in item["spans"] for chars in span["chars"]))
```

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
Things like this happen if the characters in question are not UTF8 encoded. The question mark symbols you see are chosen when there is no way to UTF8-decode the character.
The PDF producer may have built his fontfile such that it does produce a nice looking visual character representation, but will refuse to deliver a translation back to UTF8 encoded text.
You can crosscheck these statements using the C library I am building this binding for: ``mutool draw -o your.txt your.pdf``.
Then look at the produced text file ``your.txt`` and see if anything more acceptable came out.
If not: nothing can be done about it.
Another check: try to copy text from the display of a PDF viewer and paste that in e.g. word to see, if you get readable results.

**Comment by leyiwang** [comment]
> Things like this happen if the characters in question are not UTF8 encoded. The question mark symbols you see are chosen when there is no way to UTF8-decode the character.
> The PDF producer may have built his fontfile such that it does produce a nice looking visual character representation, but will refuse to deliver a translation back to UTF8 encoded text.
> You can crosscheck these statements using the C library I am building this binding for: `mutool draw -o your.txt your.pdf`.
> Then look at the produced text file `your.txt` and see if anything more acceptable came out.
> If not: nothing can be done about it.
> Another check: try to copy text from the display of a PDF viewer and paste that in e.g. word to see, if you get readable results.

I  get it, thank you very much!
