### ISSUE TITLE
Calling update on polyline annots fills them

### ISSUE THREAD

**Issue by bjhowie** [pymupdf/PyMuPDF#732]
## Describe the bug (mandatory)
When calling annot.update() on a polyline annotation by loading a PDF with an existing annotation, the interior of the polyline is filled as if it were a polygon annotation

## To Reproduce (mandatory)
Open a PDF file, call annot.update on a polyline annotation then save the file. When reopened in a PDF Viewer the annotation is filled.

## Screenshots (optional)
Before annot.update() is called:
![image](https://user-images.githubusercontent.com/45848617/100223706-f4363280-2f6f-11eb-971a-753e8f06d32b.png)

After annot.update() is called:
![image](https://user-images.githubusercontent.com/45848617/100223759-06b06c00-2f70-11eb-81e1-8e5a1efc6d92.png)

## Your configuration (mandatory)
3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] 
 win32 
 
PyMuPDF 1.18.4: Python bindings for the MuPDF 1.18.0 library.
Version date: 2020-11-19 08:56:23.
Built for Python 3.7 on win32 (64-bit).

**Comment by JorjMcKie** [comment]
This is not the case generally. Take this example
[x.pdf](https://github.com/pymupdf/PyMuPDF/files/5596526/x.pdf)
and this snippet:
```python
>>> doc=fitz.open("x.pdf")
>>> page=doc[0]
>>> a=page.firstAnnot
>>> a
'PolyLine' annotation on page 0 of x.pdf
>>> a.set_colors(stroke=(0,0,1))
>>> a.update()
>>> doc.saveIncr()
>>> 
```
The lines have changed to blue and nothing else has happened.
So please do provide a reproducer!

**Comment by bjhowie** [comment]
When i run your code with this PDF i have the same issue.
[polyline_test.pdf](https://github.com/pymupdf/PyMuPDF/files/5599972/polyline_test.pdf)

Maybe something to do with the way Bluebeam Revu saves Polylines?

**Comment by JorjMcKie** [comment]
> Maybe something to do with the way Bluebeam Revu saves Polylines?

This is indeed the case! If I analyse the annot, I see that a fill color is defined in both, its PDF definition (from where the output ``annot.colors`` comes) and its appearance commands ``annot._getAP()``:
```python
>>> doc=fitz.open("polyline_test.pdf")
>>> page=doc[0]
>>> annot=page.firstAnnot
>>> annot.colors
{'stroke': [0.0, 0.0, 1.0], 'fill': [1.0, 0.0, 0.0]}
>>> print(annot._getAP().decode())
0 0 1 RG  % border color
1 0 0 rg  % fill color
1 w 
387.2109 650.6205 m 
319.4041 535.23 l 
244.4597 561.4011 l 
258.7348 631.587 l 
148.1026 598.2784 l 
130.2587 426.977 l 
287.285 454.3376 l 
226.6158 325.8616 l 
395.5381 319.9136 l 
438.3634 495.9734 l 
S  % stroke command only - no fill
>>> # line breaks above are mine
```
So everything is there to fill the annot with red ... but then it doesn't do it - like a **_coitus interruptus_** 😂.
As explained [here](https://pymupdf.readthedocs.io/en/latest/faq.html#common-issues-and-their-solutions), there is no software that deals with annots the same way as the annot-creating software.
The recipe is: do not ``annot.update()`` if the annot comes from somewhere else.
Or be prepared to provide all information bits to rebuild the annot appearance to your liking.

**Comment by bjhowie** [comment]
I was afraid that might be the case.
I'll have to dig out some old code to generate

**Comment by bjhowie** [comment]
So i've hacked around the issue by manually deleting the /IC entry from the annotation's dictionary before calling `annot.update()`. 
As a potentially enhancement, there should be a way to use the `annot.set_colors` method to remove the fill colour from an annotation. Something like `annot.set_colors(fill=None)`, though this currently makes no change to the annotation.

I would also argue that the current behavior of the annot.update() function is not behaving as one would expect it to in relation to polylines. Almost by definition, I can see no reason that a user would want to fill the internal area of a polyline. The `annot.update()` method should only use the fill colour to fill line ends, or otherwise ignore it.

**Comment by JorjMcKie** [comment]
> So i've hacked around the issue by manually deleting the /IC entry from the annotation's dictionary before calling annot.update().
As a potentially enhancement, there should be a way to use the annot.set_colors method to remove the fill colour from an annotation. Something like annot.set_colors(fill=None), though this currently makes no change to the annotation.

I saw this coming, and you are quite right. My local version already has that. The logic now is this:

- setting (or leaving) a color parameter to `None` means "don't change what's there"
- setting a color parameter to an empty sequence (`[]` or `()`) means "remove the entry, `/C` or `/IC`.

**Comment by JorjMcKie** [comment]
> I would also argue that the current behavior of the annot.update() function is not behaving as one would expect it to in relation to polylines. Almost by definition, I can see no reason that a user would want to fill the internal area of a polyline. The annot.update() method should only use the fill colour to fill line ends, or otherwise ignore it.

By the books (PDF spec), I do not correctly interpret the meaning of `/IC` for both, polyline **_and_** polygon:
It states in both cases that this parameter pertains to **_line ends only_**. So I should actually not offer the following polygon:
![grafik](https://user-images.githubusercontent.com/8290722/100490293-bd3b5a80-30f0-11eb-9cf4-028467537caf.png)
And your argument could be extended to line ends for polygons: why should a **_closed_** figure like a polygon have such things anyway?

**Comment by bjhowie** [comment]
Seems like a peculiarity of the PDF spec. I can't imagine any situation where a user would need line ends on a closed shape.
I think most PDF viewers interpret /IC to be the shape fill colour on polygons, and the line end fill colour on polylines. Line ends are often not offered on polygons even though the spec allows them.

**Comment by JorjMcKie** [comment]
Let me use the opportunity of this discussion and ask for your position: according to the PDF spec, I should (or *need*)
* neither offer an interior color for polylines **_nor_** for polygons
* not offer line end symbols for polygons

Currently, everything is always possible - fill color for line ends may even be different.

Remove those extras or let them live? You experienced some trouble because of them ...

**Comment by bjhowie** [comment]
An interior colour for polygons is definitely necessary, but it is not logical to think of a polyline as having an interior that can be filled. Can they not be treated differently?
/IC should define the interior colour for polygons and the line end fill colour for polylines. I think this would be the expected behaviour for the vast majority of users. 

I don't think there is any harm in offering line end symbols for polygons, even if there is barely any practical application for them. I would leave them.

**Comment by JorjMcKie** [comment]
Thanks for your position on this!
I will implement these recommendation, so the next version will behave like this:
* Both, stroke and fill color can be removed from annotations via setting them to empty sequences, e.g. ``fill=[]``.
* Fill colors for polyline annotations wil only be applied to line end symbols

Other behavior will remain unchanged.
