### ISSUE TITLE
question of installing header/lib files on MacOS

### ISSUE THREAD

**Issue by cuteufo** [pymupdf/PyMuPDF#734]
This is just a general question on Mac OS (my current OS version is Big Sur).

According the installation instructions, I will build MuPDF manually. So I did so in a local folder, like ~/Documents/src/mupdf-1.18.0-source/, by `make HAVE_X11=no HAVE_GLUT=no`, and `libmupdf.a` was generated in sub-folder named `build/release`, along with a number of other files.

Now I have two options to install the libs and header files. One is to go on with `make prefix=/usr/local install`, another is, as described in README of this repo, `brew install mupdf-tools`. I assume I should take only one route of them, not both. My best guess is I should take the first one, because it is of the same version of MuPDF source code.

Please confirm or correct me if I am wrong. Thanks.

(** I would like to make sure of this question before I try it in my real environment to minimize the chance of disrupt my development environment. **)

**Comment by JorjMcKie** [comment]
Hm, embarrassingly I do not know the Mac OSX platform, never owned one.
To be on the safe side, I would follow the few hints given on the home page.
Maybe some info could be pulled out of the run log of the OSX wheel generation. It is a common log for all Python versions, but you should be able to select the relevant part for you: https://travis-ci.org/github/JorjMcKie/py-mupdf/jobs/744891072.

**Comment by JorjMcKie** [comment]
Please do not hesitate to re-open if necessary.
