### ISSUE TITLE
Fail to open .cbz files with no directory

### ISSUE THREAD

**Issue by fgallaire** [pymupdf/PyMuPDF#735]
## Describe the bug

Fail to open .cbz files with no directory

```
mupdf: cannot recognize archive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fgallaire/.local/lib/python3.8/site-packages/fitz/fitz.py", line 3625, in __init__
    _fitz.new_Document(
RuntimeError: cannot recognize archive
```

## To Reproduce

```
>>> doc = fitz.open('file.cbz')
```

## My configurations

Ubuntu 18.04/Python 3.7.9/PyMuPDF 1.18.3
Ubuntu 20.04/Python 3.8.5/PyMuPDF 1.18.4

**Comment by JorjMcKie** [comment]
please provide mandatory info if entering a bug

**Comment by JorjMcKie** [comment]
To make sure we are on the same page:
I need a file to reproduce the problem.

**Comment by JorjMcKie** [comment]
Closed for lack of reaction.
