### ISSUE TITLE
missing or content not extracting as in pdf 

### ISSUE THREAD

**Issue by jaichandrasreeram** [pymupdf/PyMuPDF#745]
Hi,

I am trying to highlight the words which are matched exactly in the PDF with the custom list, currently, I am stuck with few issues please can you help me

1. If there are words in the custom list like **Kidney Transplant** & **Kidney Transplant failure**, we need to avoid overlap of highlighting and also highlight if exact words are matched

2. Currently, I am using ` page.getText("words")` to find words, but we are not able to search those keywords in PDF if there are multiple words (example, if there is a word like **side effect** it won't be highlighted as words will be split while extracting from pdf so side and effect will be two different)
![image](https://user-images.githubusercontent.com/74171485/101017464-25c28580-3590-11eb-8896-63009aca1dd9.png)

3. if any word is ending with special char like(comma, dot, or any special char), highlighting is happening including special chars, but need highlight only words
![image](https://user-images.githubusercontent.com/74171485/101017195-c5cbdf00-358f-11eb-8946-ff755577c38b.png)

4. Some characters are extarction its showing different chars
 ![image](https://user-images.githubusercontent.com/74171485/101017948-cca72180-3590-11eb-9f49-0d8ee30f93f7.png)

```
import fitz
pdf_file = "12300395.pdf"
blue  = (0, 0, 1)
doc = fitz.open(pdf_file)
NumPages = doc.pageCount

m = ["harm", "monitor", "glucose","Kidney Transplant","Kidney Transplant failure"]
for i in range(0, NumPages):
    page = doc[i]  
    word_customs = page.getText("words")
    for inst in word_customs:
        split_word = inst[4]
        text_instances = page.searchFor(word[4])     
        annot = page.addRectAnnot(split_word ) # 'Square'
        annot.setBorder(width=0)
        annot.setColors(stroke=blue,fill=blue)
        annot.setOpacity(0.3)
        annot.update() 

doc.save("output.pdf")
```

**Comment by JorjMcKie** [comment]
Thanks for asking this!
A complex and multipart question, so let me answer in several posts.

As per unexpected **_strange characters_** on output:
This is an effect of me setting some unfortunate defaults in the `flags` parameter of text extractions. For special character combinations like "ff", "fl", "fi", "ffi", "ffe" and more, some fonts support a seperate, own glyph (the visible appearance of a character) - for a number of good reasons. These glyphs are called "ligatures".
In `getText()` you can control, whether to dissolve ligatures into its constituents via `fitz.TEXT_PRESERVE_LIGATURES`, a bit indicator coded in the `flags` integer. I am setting that bit **_on_** by default: so you get those glyphs as separate unicode values, which look awkward on simple text output.
So for you purpose best ensure specifying `getText(option, flags=0)`. This flag value will dissolve ligatures into their constituents, will replace white space with normal space and **suppress** image extraction.

**Comment by JorjMcKie** [comment]
The typical approach for highlighting text is
1. search for it via `page.searchFor("multiple words")`
2. loop through the list of returned list of rectangles and issue `page.addHighlightAnnot(rect)` for each of them.

This approach will find strings with interpersed spaces and also detect hyphenations at line breaks, so it will find

mul-
tiple words

with the above search string and return 2 separate rectangles: one aneclosing "mul", and a second one enclosing "tiple words".
Upper or lower case are ignored, so "Multiple Words" will also be found.

**Comment by SuryaViswanath** [comment]
Hi @jaichandrasreeram, I am working on a similar kind of project. When you try to retrieve the information using `getText()` or `getTextWords()` or `getTextBlocks()` it essentially returns quads of the text i.e., the coordinates where the text is found so because of which the special characters are being highlighted as well. However, since I can't use the pdf file to kind of tell you my workaround I can suggest the following things

I used the following pdf sample
[sample.pdf](https://github.com/pymupdf/PyMuPDF/files/5636321/sample.pdf)


`
    doc = fitz.open('sample.pdf')
    page = doc[0]
    page.cleanContents()
    lit = ['Boring','Virtual Mechanics']
    toc = page.getText('words')
    for i in range(0,len(toc)):
        If toc[i][4].replace(",","") in lit:
            a,b,c,d = toc[i][:4]
            page.addHighlightAnnot([a,b,c,d])
        temp = toc[i][4] + " " + toc[i+1][4]
        temp = temp.replace(",","")
        if temp in lit:
            a,b,c,d = toc[i][:4]
            page.addHighlightAnnot([a,b,c,d])
            a,b,c,d = toc[i+1][:4]
            page.addHighlightAnnot([a,b,c,d])
        doc.save('output.pdf')
        if i==len(toc)-1: 
            break
`

well, @JorjMcKie could you tell me if I could have tried a different approach here as I am also learning I would love to have some takeaways from you about my approach too, with that being said @JorjMcKie has mentioned various things. This is just my little contribution to your work. Although the code isn't really neat
I hope this helps. Thanks

**Comment by JorjMcKie** [comment]
@jaichandrasreeram - thanks a lot!
And again I recommend evaluating the examples in the above mentioned [folder](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/word%26line-marking).
It shows how to isolate the interesting part of a word, as well as highlighting longer sentences which spread across multiple lines.

**Comment by jaichandrasreeram** [comment]
When I try` page.getText("words")` the words on the page will be split based on space and it won't be highlighted at all 
example: if there is a word **_side effect_** in the custom list it never gets highlighted as there will be no single word as **_side effect_** as we used  `page.getText("words")`
![image](https://user-images.githubusercontent.com/74171485/101158133-469edf80-3651-11eb-8569-dd29cbd69642.png)





and when I try `page.searchFor(k)` the highlight happens for in-between words also 
![image](https://user-images.githubusercontent.com/74171485/101167170-840a6980-365f-11eb-9fed-2eef6b7965f0.png)

I am trying to highlight multiple words like (side effects, ) and also avoid highlight between chars, Please suggest

**Comment by JorjMcKie** [comment]
You can still use your wordlist:
Sort it by ascending y-coordinates, then by x-coordinate. Strings following each other in the text will also be neighbors in the sorted list. When searching for a multi-word needle, just check that sequence part accordingly.

So wrapping up:
1. convert the list `page.getText("words")` into one, where every word has been freed from any punctuation and other crab. Use function `find_words` of this [script](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/word%26line-marking/mark-words.py) for it.
2. Sort that word_list. Each list item consists of a rectangle (bbox) and the text of the word with that bbox.
```python
word_list.sort(key=lambda w: (w[0].y1, w[0].x0))
# sorted the words by y-, then by x-coordinate.
```
3. Then take your needle, e.g. needle = ["side", "effect"], and loop through the word list:
```python
for i in range(len(word_list) - 1):
    if word_list[i][1] != needle[0]:  # skip if not equal to "side"
        continue
    if not word_list[i+1][1].startswith(needle[1]):  # takes care of "effect" and "effects"
        continue
    # mark the rectangles word_list[i][0] and word_list[i + 1][0]
```

**Comment by SuryaViswanath** [comment]
> When I try` page.getText("words")` the words on the page will be split based on space and it won't be highlighted at all
> example: if there is a word **_side effect_** in the custom list it never gets highlighted as there will be no single word as **_side effect_** as we used `page.getText("words")`
> ![image](https://user-images.githubusercontent.com/74171485/101158133-469edf80-3651-11eb-8569-dd29cbd69642.png)


Well if the above code is not working, could you try the code I posted and let me know if it is working. I am trying to learn to write the code properly and learning how to work with PDF files extensively, so I can learn well by helping hence.

> and when I try `page.searchFor(k)` the highlight happens for in-between words also
> ![image](https://user-images.githubusercontent.com/74171485/101167170-840a6980-365f-11eb-9fed-2eef6b7965f0.png)
> 
> I am trying to highlight multiple words like (side effects, ) and also avoid highlight between chars, Please suggest

Well with `searchfor()` as the name suggests it searches for such an instance from the pdf file and hence when it is found it returns quads of the word and `pageHiglightAnnot()` highlights with the quads given. So the workaround is using the coordinates from the `page.getText('words')` and with the help of those coordinates, you can try something as I mentioned above or as explained by @JorjMcKie. 

Thanks

**Comment by SuryaViswanath** [comment]
@JorjMcKie I think this can be closed now?

**Comment by JorjMcKie** [comment]
Please do so if you feel you got the answers you need! It is **_your_** issue ... 😉.
Let me also hint at the new "discussions" menu item, a new GitHub feature.
Maybe this allows entering in a more chatroom-like mode occasionally.
