### ISSUE TITLE
"ValueError: bad sequ. length" when adding .PNG image to PDF

### ISSUE THREAD

**Issue by lukebarone** [pymupdf/PyMuPDF#746]
## Describe the bug (mandatory)
ValueError: bad sequ. length exception happening on `page.insertImage()` function. Exact output below:

```nolang
Starting...
Traceback (most recent call last):
  File "pdf_convert.py", line 35, in <module>
    main()
  File "pdf_convert.py", line 30, in main
    overlay=True)
  File "/home/luke/.local/lib/python3.6/site-packages/fitz/utils.py", line 305, in insertImage
    r = Rect(rect)
  File "/home/luke/.local/lib/python3.6/site-packages/fitz/fitz.py", line 895, in __init__
    raise ValueError("bad sequ. length")
ValueError: bad sequ. length
```

## To Reproduce (mandatory)
I cannot include the exact files, but here is the code I'm using:

```python3
#!/bin/env python3
"""Add the principal's signature to the proper section on the PDF version of
the report cards. Please edit the variables below, and ensure the files are in
the same working directory, before continuing."""

from shutil import copyfile
import fitz

ORIGINAL_FILENAME = "Report Cards.pdf"
OUTPUT_FILENAME = "Output.pdf"
PRINCIPAL_SIGNATURE_BLOCK = "PRINCIPAL'S SIGNATURE"
SIG_BLOCK_HEIGHT = 9
SIG_BLOCK_WIDTH = 97
PRINCIPAL_SIG_FILE = "signature.png"
SIG_HEIGHT = 209
SIG_WIDTH = 439

def main():
    print(f"Starting...")
    copyfile(ORIGINAL_FILENAME, OUTPUT_FILENAME)
    doc = fitz.open(OUTPUT_FILENAME)
    for page in doc:
        rect = page.searchFor(PRINCIPAL_SIGNATURE_BLOCK)
        if not rect:
            continue
        page.insertImage(rect,
            filename=PRINCIPAL_SIG_FILE,
            keep_proportion=True,
            overlay=True)
# Error happening at this page.insertImage() command
    doc.saveIncr()


if __name__ == '__main__':
    main()

```

## Expected behavior (optional)
I want to search multiple pages for the text box containing "PRINCIPAL'S SIGNATURE", and insert a digital copy of their signature into the box.

## Screenshots (optional)
I can't, for privacy reasons.

## Your configuration (mandatory)
 - Windows 10 x64 2004
 - Python 3.6.9 x64
 - PyMuPDF version 1.18.4, installation method PIP

## Additional context (optional)
In the code above, I show the dimensions of the file (SIG_HEIGHT and WIDTH) from the file properties, as well as the SIG_BLOCK_HEIGHT and WIDTH, as returned from the `rect = page.searchFor(PRINCIPAL_SIGNATURE_BLOCK)` line. Ideally, I would like to be able to insert the picture, starting from the top left of the `rect` object, with it scaled down as appropriate.

**Comment by JorjMcKie** [comment]
The result of method `page.searchFor()` is **_always_** a list of items which are either of types Rect or Quad.
In your code you try to use that list directly as a rectangle, where you should have used rect[0] or something like that.

**Comment by lukebarone** [comment]
That's exactly what it was!

Thank you very much!
