### ISSUE TITLE
Pymupdf installation on cloud virtual instance

### ISSUE THREAD

**Issue by eve-cv** [pymupdf/PyMuPDF#747]
Hi,

My local environment is Ubuntu 18.04, where I successfully installed pymupdf by running the following command.

```
pip3 install pymupdf

```

In my local environment, this library was working well, so I intended to deploy the project on a cloud virtual instance.
When installing pymupdf on vm to deploy the project, for the first time, I faced an issue as follows.
![Screenshot from 2020-12-04 07-42-09](https://user-images.githubusercontent.com/66071898/101154653-c0f54280-3604-11eb-8f94-51956ef7a506.png)

So I tried to install mupdf by running the following command.
```
sudo apt-get install libmupdf-dev
```

Then when trying pymupdf again, I got the following issue, which I couldn't fix.

![Screenshot from 2020-12-04 07-45-29](https://user-images.githubusercontent.com/66071898/101154660-c488c980-3604-11eb-9ba9-08f36b959c87.png)

My virtual instance is Ubuntu 18.04 as my local environment.
I sincerely hope for your help.

Best regards
Artem

**Comment by JorjMcKie** [comment]
The development version of MuPDF **_cannot_** work at all - as stated on PyMuPDF's home page: as the name says, it is their current development, so almost certainly incompatible with PyMuPDF (built based on stable MuPDF).

The basic issue you are having is not a PyMuPDF issue, but instead pertains to your cloud environment itself. Apparently all these cloud solutions (IBM cloud, Amazon AWS, MS Azure, and what not) have their own specific procedures for how to support Python applications that have a binary extension as PyMuPDF has it.
I am not using any of these myself, so unfortunately cannot help you. Also, as stated, it's different anyway in each case.
So please consult your provider for how you have to proceed.
There have been a few similar support requests: #740, #430.
In the latter case I was indeed able to dig out a way to resolve that issue, so maybe you can profit from it somehow.
