### ISSUE TITLE
Duplicated annotation

### ISSUE THREAD

**Issue by IbrahimGerbiqi** [pymupdf/PyMuPDF#749]
Hi I'm using pymupdf for adding highlights to a pdf document I came across a problem that I could figure out how to fix or how to make a workaround, maybe you have a feature that can solve my problem if not take it as a request for a feature.

The problem that I came across is that inside the same page I have 2 texts that I need to highlight 1 is with quotes and it should be with green highlight and the second one is without quotes and it should have read highlight.

first one
![image](https://user-images.githubusercontent.com/34714009/101342206-8698d900-3882-11eb-999a-3326979af38c.png)

![image](https://user-images.githubusercontent.com/34714009/101342353-bba52b80-3882-11eb-89c2-b0a679d78d51.png)
on this image what happens is that when the second sentence is searched it was found 2 times and added a red highlight on both coordinates.

 I tried to remove quotes but now I got both sentences highlighted as green.

Also, I use addHighlightAnnot to add annotations to pdf document.

Could you suggest any idea or workaround about this problem?

**Comment by JorjMcKie** [comment]
Why not do the following:
1. search with quotes and, once found, mark it wth the desired color, and store the rectangle(s) you used for marking.
2. search again, this time without quotes. Loop through the returned rectangles, and only mark them if they are not contained in **_any_** of the previous ones.

**Comment by IbrahimGerbiqi** [comment]
I applied this logic but the text with quote starts with coordinates 72.xxxx also the text without quotes starts with 76.xxxx and when compared it says they are different

“IKSHPK ka konsideruar që Prizreni konsiderohet i infektuar ose drejtpërdrejt i rrezikuar nga përhapja e  infeksionit Covid-19”
Coordinates for text with quotes:    
    [
        Rect(72.0999984741211, 133.95001220703125, 533.7047119140625, 144.95001220703125), 
        Rect(72.0999984741211,148.45001220703125, 165.25302124023438, 159.45001220703125)
    ]


IKSHPK ka konsideruar që Prizreni konsiderohet i infektuar ose drejtpërdrejt i rrezikuar nga përhapja e infeksionit COVID-19
Coordinates for text without quotes when searched on page:

[
        Rect(76.697998046875, 133.95001220703125, 533.7047119140625, 144.95001220703125),
        Rect(72.0999984741211, 148.45001220703125, 160.63719177246094, 159.45001220703125), 
        Rect(386.55694580078125, 619.9500122070312, 536.9431762695312, 630.9500122070312), 
        Rect(72.0999984741211, 634.4500122070312, 468.8242492675781, 645.4500122070312)
    ]
The first 2 coordinates belong to a sentence that hase quotes

**Comment by JorjMcKie** [comment]
We may have a misunderstanding. Here is a script that works:
```python
import fitz

doc = fitz.open()
page = doc.newPage()
text = '"Pixmaps coming from other sources or generated by some functions may or may not contain an alpha, which therefore needs to be checked."'
red = (1, 0, 0)
green = (0, 1, 0)
r1 = fitz.Rect(100, 100, 400, 150)
r2 = r1 + (0, r1.height, 0, r1.height)
page.insertTextbox(r1, text)
page.insertTextbox(r2, text[1:-1])
rl1 = page.searchFor(text)
annot1 = page.addHighlightAnnot(rl1)
annot1.setColors(stroke=red)
annot1.update()

total_rl1 = rl1[0]  # join rectangle of first search result
for r in rl1[1:]:
    total_rl1 |= r

rl2 = page.searchFor(text[1:-1])  # 2nd search w/o quotes

rl3 = [r for r in rl2 if not r in total_rl1]  # sub-list avoiding 1st search

annot2 = page.addHighlightAnnot(rl3)
annot2.setColors(stroke=green)
annot2.update()

doc.save("x.pdf")
```
Result:
![grafik](https://user-images.githubusercontent.com/8290722/101352730-f5693880-3868-11eb-999c-b7ac6df1dffd.png)

**Comment by JorjMcKie** [comment]
I should have thought of this:
Instead of creating `total_rl1`, I could have directly used `annot1.rect` ... they are the same.

**Comment by IbrahimGerbiqi** [comment]
Thank you so much for your answer, it helped me a lot to solve my problem, I needed to make some changes so it can work with dynamic data and used within a for loop, I'm leaving my code here if anyone would need to use it.

```
                if arrayToSearch["citation"] == 1:
                    rl1 = text_instances
                    text_instances = rl1
                    if len(highlighted_Sentences) == 0:
                        highlighted_Sentences = rl1[0]
                        for r in rl1[1:]:
                            highlighted_Sentences |= r
                        else:
                            for r in rl1[0:]:
                                highlighted_Sentences |= r
                if len(highlighted_Sentences) > 0:
                    if arrayToSearch["citation"] == 2:
                        rl2 = text_instances
                        rl3 = [r for r in rl2 if not r in highlighted_Sentences]
                        text_instances = rl3
```
what I needed to do is to sort my array of sentences so I can highlight ones with quotes/citations first and save their coordinates so when there is a sentence without quotes/citations to check on coordinates that I stored.

**Comment by JorjMcKie** [comment]
Close the issue?
