### ISSUE TITLE
annot highlight rectangle box can be deleted 

### ISSUE THREAD

**Issue by jaichandrasreeram** [pymupdf/PyMuPDF#751]
Hi,

I am using rectangle annotation to highlight the text in pdf
```
annot = page.addRectAnnot(inst)
annot.setBorder(width=0)
annot.setColors(stroke=(0, 0, 1),fill=(0, 0, 1))
annot.setOpacity(0.5)
annot.update()
```

but when I open the pdf the highlighted rectangle annotation is draggable, 
![image](https://user-images.githubusercontent.com/74171485/101609204-acfa7800-3a2c-11eb-8b12-e38a2180bfaf.png)

is there any way I can stop draggable and highlight in custom colors, please help me

**Comment by JorjMcKie** [comment]
Try to "lock" the annotation by setting the appropriate bit in the annotation flags:
```python
flags = annot.flags
flags |= fitz.PDF_ANNOT_IS_LOCKED
# to set read only:
flags |= fitz.PDF_ANNOT_IS_READ_ONLY
# then:
annot.set_flags(flags)
```
Quote from PDF book:
> Locked (PDF 1.4) If set, do not allow the annotation to be deleted or its properties (in-
cluding position and size) to be modified by the user. However, this flag does
not restrict changes to the annotation’s contents, such as the value of a form
field. (See implementation note 84 in Appendix H.)

**Comment by JorjMcKie** [comment]
invoking ``annot.update()`` is not required.

**Comment by cipri-tom** [comment]
Nice question and solution ! 

However, it seems that the "locking" is up to the viewer that you're using. For me, Preview on MacOS doesn't respect it, I can move the annotation even if I have set the flags. Firefox and Chrome cannot move it regardless of the flags, probably because they are more "viewer" than "editor".

**Comment by JorjMcKie** [comment]
> 
> 
> Nice question and solution !
> 
> However, it seems that the "locking" is up to the viewer that you're using. For me, Preview on MacOS doesn't respect it, I can move the annotation even if I have set the flags. Firefox and Chrome cannot move it regardless of the flags, probably because they are more "viewer" than "editor".

That may be so. Also PyMuPDF - not **_being_** a viewer - ignores this obviously. 
Well, for everyone reading this then: using the `flags` bitfield is the only option to protect an annotation. If using a viewer which chooses to ignores this ... tough luck. Maybe draw some satisfaction from the fact, that this viewer is - by the books - misbehaving 😟.

**Comment by JorjMcKie** [comment]
> highlight in custom colors, please help me

Sorry, forgot to answer this part of your question @ jaichandrasreeram.
You can set the color of Highlight annotations, too. Although it seems surprising, this is **_not_** done via the fill color. All text marker annotations have no fill color.
Use the stroke color: ``annot.set_colors(stroke=...)`` followed by an ``annot.update()``.
If you want you can continue using rectangle annotations, too. I saw that you are working with opacity to keep the highlighted text underneath visible.
That's okay, but not quite satisfying, is it? Try using the annotation's **_blend mode_** additionally. This is the property, that makes highlighting look so good: ``annot.set_blendmode("Multiply")``. For reference consult the above mentioned PDF manual https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf on page 520.
