### ISSUE TITLE
PyMuPDF "Discussions" is now available - see the top menu!

### ISSUE THREAD

**Issue by JorjMcKie** [pymupdf/PyMuPDF#753]
Just activated this new feature.
Please try it out - maybe it becomes a forum for interchanging ideas and general comments!

As suggested by @cipri-tom I have removed the **_issue template_** for "Questions and Comments".

Please use top menu point **_Discussions_** instead for this. Several discussion categories are available there - pick one and open a discussion please!

**Comment by cipri-tom** [comment]
Awesome ! 
Should questions be posted there rather than in issues ? If so, maybe the issue template should remove the option for questions and direct people there ?

Also, consider pinning this issue so it appears at the top ^^.

Thanks a lot ! I'm looking forward to the community this brings

**Comment by JorjMcKie** [comment]
At a minimum, I have inserted the respective comment in that template ...
