### ISSUE TITLE
Can we extract drawings from a pdf from certain area ?

### ISSUE THREAD

**Issue by kvrameshreddy** [pymupdf/PyMuPDF#760]
I have a pdf with elementary drawings in it. I need to extract only the graph from the pdf. is there any possibility to add clip in page.getDrawings().
[3.pdf](https://github.com/pymupdf/PyMuPDF/files/5672523/3.pdf)
the bbox is [457.4316, 116.5564, 686.4030, 227.8215]

**Comment by JorjMcKie** [comment]
The effort wouldn't be worth it I think. The result of `page.getDrawings()` is a list of dictionaries, so-called paths, each of which represents a separate drawing. The path dictionary has the key `"rect"`, which wraps its drawing.
So simply select from that list by including paths satisfying the condition `path["rect"] in bbox`.

**Comment by JorjMcKie** [comment]
But including a "clip" parameter would of course neither be a big deal.
Well, thinking about it a little more, you are probably right: it would nicely match with the homologous parameter in other extraction methods.
For immediate needs there is the above option.

**Comment by kvrameshreddy** [comment]
Hi @JorjMcKie, Thanks for the immediate response. My requirement is to extract the graph and compare to another graph in different pdf to identify the differences. Here, i am having the coordinates of each and every graph, table, and text separately derived using Detectron2. If "clip" parameter is included in it. that would be a great help for me.

I didn't get your first answer. If you dont mind, please take a look at the attached pdf and the bbox values. I need that graph in a separate page. Please help me in extracting it with code.

Thank you.

**Comment by JorjMcKie** [comment]
This is what I meant:
[issue-760.zip](https://github.com/pymupdf/PyMuPDF/files/5673145/issue-760.zip)
It eproduces the drawings of your bbox on the page of a fresh PDF.
I suspect you would also want to copy the "legend" of that cone, don't you?

**Comment by JorjMcKie** [comment]
in that case, take this as a start:
[issue-760.zip](https://github.com/pymupdf/PyMuPDF/files/5673268/issue-760.zip)

**Comment by kvrameshreddy** [comment]
Hi @JorjMcKie, Thankyou very much for your help.
