### ISSUE TITLE
addStrikeoutAnnot() results in annotation of zero height

### ISSUE THREAD

**Issue by cipri-tom** [pymupdf/PyMuPDF#762]
## Describe the bug (mandatory)
`page.addStrikeoutAnnot()` creates an annotation of (almost) zero height:

![Screenshot 2020-12-10 at 16 39 16](https://user-images.githubusercontent.com/2991890/101793589-40ec4280-3b06-11eb-959a-8bfd30098cd9.png)

## To Reproduce (mandatory)
```python
d = fitz.open('dummy.pdf')
p = d[0]
r = p.searchFor('Dummy')

p.addStrikeoutAnnot(r)

d.save('/tmp/dummy_annot.pdf')
```

[dummy.pdf](https://github.com/pymupdf/PyMuPDF/files/5673870/dummy.pdf)

## Expected behavior (optional)
![Screenshot 2020-12-10 at 16 42 50](https://user-images.githubusercontent.com/2991890/101794044-c112a800-3b06-11eb-8204-10f5662e8f42.png)

obtained with `p.addRectAnnot(r[0])`. But I prefer `addStrikeoutAnnot()` because it takes a list of all findings and its name is more descriptive.

## Your configuration (mandatory)
 - Ubuntu 18.04 and MacOS Catalina
 - Python version: 3.6
 - PyMuPDF: `('1.18.4', '1.18.0', '20201119085623')`, wheel installation

--- 

Thanks for all the amazing work and sorry I ghosted the other issues, I didn't get to test those implementations 😞  !

**Comment by JorjMcKie** [comment]
Cannot reproduce:
```python
>>> import fitz
>>> doc=fitz.open("dummy.pdf")
>>> page=doc[0]
>>> r=page.searchFor("dummy")
>>> r
[Rect(56.79999923706055, 69.32511901855469, 115.85404968261719, 87.31184387207031)]
>>> a=page.addStrikeoutAnnot(r)
>>> a.rect.height
20.2349853515625
>>> page.drawRect(a.rect, width=0.3)
Point(55.67583084106445, 68.20098876953125)
>>> doc.save("y.pdf")
>>> 
```
produces this:
![grafik](https://user-images.githubusercontent.com/8290722/101804474-ffe53580-3ae7-11eb-998c-85b3e9af262e.png)

**Comment by cipri-tom** [comment]
I misunderstood the meaning of `strikeout` (see my _Expected behaviour_). I expected to make an annotation with strike colour red. Indeed, ~~this~~ is _strikeout_. Sorry for the noise 😞
