### ISSUE TITLE
Doc Mismatch with getText() output

### ISSUE THREAD

**Issue by mpalazz** [pymupdf/PyMuPDF#768]
JFYI about documentation

## Describe the bug (mandatory)
Documentation mismatch - with page.getText('blocks'):
Doc says:
(x0, y0, x1, y1, "lines in blocks", block_type, block_no)
Actual is:
(x0, y0, x1, y1, "lines in blocks", block_no, block_type)

## To Reproduce (mandatory)
mudoc = fitz.open('foo.pdf')
page =  mudoc[0] 
blocks = page.getText('blocks')
print(blocks)

## Your configuration (mandatory)
 - MacOS Catalina
 - python 3.8.5
 - pymupdf 1.18.3 installed with wheel

**Comment by JorjMcKie** [comment]
Thanks for spotting this!
Will be corrected in next version.

**Comment by JorjMcKie** [comment]
Solved by v1.18.5 being uploaded now.
