### ISSUE TITLE
getDrawings not extract all border 

### ISSUE THREAD

**Issue by bserg66** [pymupdf/PyMuPDF#769]
Hello.
I try extract all images and drawings from P48_29-30.pdf and insert its to other P48_29-30_imgall.pdf
But not all borders inserts in P48_29-30_imgall.pdf (around a spoon at first page and 3 borders at second page).
And color of book at first page and view of rectangles around pages numbers do not match the source.

[P48_29-30.pdf](https://github.com/pymupdf/PyMuPDF/files/5696393/P48_29-30.pdf)
[P48_29-30_imgall.pdf](https://github.com/pymupdf/PyMuPDF/files/5696398/P48_29-30_imgall.pdf)

My code  is:
```python
import fitz
import os

PATH = 'C:/PyWorks/PDF_Python/PDF/'

if __name__ == "__main__":
    FileRead = PATH + 'P48_29-30.pdf'
    DocRd = fitz.open(FileRead)
    DocWr = fitz.open()
    PCounts =  DocRd.pageCount
    for PageNumber in range(0,PCounts):
        PageRd = DocRd[PageNumber]
        PageWr = DocWr.newPage(width=PageRd.rect.width, height=PageRd.rect.height)

        # Insert text images 
        TextDict = PageRd.getText("dict")
        for block in TextDict['blocks']:
            if block["type"] == 1:
                PageWr.insertImage(block['bbox'], stream=block['image'])
        
        # Insert drawings 
        paths = PageRd .getDrawings() 
        shape = PageWr.newShape()  
        for path in paths:
            for item in path["items"]: 
                if item[0] == "l":  
                    shape.drawLine(item[1], item[2])
                elif item[0] == "re": 
                    shape.drawRect(item[1])
                elif item[0] == "c":  
                    shape.drawBezier(item[1], item[2], item[3], item[4])
                else:
                    raise ValueError("unhandled drawing", item)
            shape.finish(
                fill=path["fill"],  
                color=path["color"],  
                dashes=path["dashes"],  
                even_odd=path["even_odd"],
                closePath=path["closePath"],  
                lineJoin=path["lineJoin"],  
                lineCap=max(path["lineCap"]),  
                width=path["width"],  
                stroke_opacity=path["opacity"],  
                fill_opacity=path["opacity"] 
                )
        shape.commit()

        # Insert images
        xref = DocRd.getPageImageList(PageNumber, full=True)
        for i, x in enumerate(xref):
            rect = PageRd.getImageBbox(x)
            xref = x[0]
            img = DocRd.extractImage(xref)
            # image = Image.open(io.BytesIO(img['image']))
            # image.show()
            if i == 0:
                PageWr.insertImage(rect, stream=img['image'], overlay=False)
            else:    
                PageWr.insertImage(rect, stream=img['image'])         
        
    # Save to file
    FileExtDel = os.path.splitext(FileRead)[0]
    FileOut = FileExtDel + '_imgall.pdf' 
    DocWr.save(FileOut, deflate=True, garbage=3, clean=True) 
    DocRd.close()
    DocWr.close()```

**Comment by JorjMcKie** [comment]
There actually is no error!
You have a complex PDF with pages containing drawings and 2 types of images: normal ones and **_inline_** images - and you all copied these over correctly (and demonstrated great knowledge of this repo by the way - chapeau!).

Your page copy process takes these 3 types of content and regenerates each on new pages correctly. And indeed you do not get what you obviously want: the same visual appearance, but just without text.

I experimented a little and commented out each of these copy blocks separately and in addition also changed their sequence.
It then became obvious that the page appearance critically depends on the sequence of every single command contained in the source page!
What I mean is that the source page's appearance relies on things like
1. display inline image X
2. draw path Y
3. display external image Z

If you change the sequence of the above, the page will look different!
And exactly this inevitably happens if you execute all commands of category 1, then 2, and then 3 ... or 3, 2, 1 or some other permutation.

**Comment by JorjMcKie** [comment]
I do not know whether you are just experimenting or have a specific need.
For example, if you want to get rid of the text, there are other ways to achieve this ...

**Comment by bserg66** [comment]
My first question is how to get the missing boreders?

**Comment by JorjMcKie** [comment]
> My first question is how to get the missing borders?

The "border" around the spoons is **_not caused_** by any of the drawings. It may not even be a border, but the result of several images overlapping each other in such a manner that an impression like a border is generated. Hard to tell after all drawing and image-show commands are pulled out of their original contxt - see my previous comments.

The following script removes all text of the pages - including the link at the bottom of the page, which has technically been envelopped in a watermark artifact.

```python
import fitz

doc = fitz.open("P48_29-30.pdf")
for page in doc:
    page.cleanContents()  # clean and unify page command syntax
    xref = page.getContents()[0]  # get the commands - now in a single source
    cont = bytearray(doc.xrefStream(xref))  # read it as a modifyable binary object
    s = 0  # position counter
    while s >= 0:
        s = cont.find(b"BT")  # search start / end of text object
        e = cont.find(b"ET", s)
        if min(s, e) >= 0:  # found one!
            cont[s : e + 2] = b""  # remove text object
    s = 0  # reset position counter
    while s >= 0:
        s = cont.find(b"/Artifact")  # search start / end of watermark
        e = cont.find(b"EMC", s)
        if min(s, e) >= 0:
            cont[s : e + 3] = b""  # remove watermark object

    doc.updateStream(xref, cont)  # write back updated stream
    page.cleanContents()  # clean again to remove now obsolete objects from PDF

doc.save(doc.name.replace(".pdf", "-no-text.pdf"), deflate=False, garbage=3)
```

**Comment by bserg66** [comment]
Super, thanks. I only change deflate=True and size from 440KB decreased at 170KB.
My aim compress pdf size from 48MB (225pages) to minimum in grayscale 4 bits color depth (the pocketbook reproduces 16 shades of gray). I find this pdf in color after pdf-tools processing (poppler show in producer field) and it size 15MB. 
First - I wanted to figure out how to reduce in color pdf size from 48MB to 15MB. 
Second I use Ghostscript (grayscale 4 bits color depth) and pdfsizeopt (clean garbage)to reduce 15MB color in 9MB grayscale 4 bits color depth its for pocketbook good size.
Can I do it all in PyMuPdf? Fonts I change on Helvetica. There are also small questions.

**Comment by JorjMcKie** [comment]
I suggest moving your issue(s) to the new "Discussions" category - this better addresses what we are doing here.
Agree?
-----------------------------------
Independently from that:
You can do a few, but not all of the above with PyMuPDF:
* you can replace fonts, there is [this folder](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/font-replacement) with appropriate scripts. Best use a new font that is subsettable (not Helvetica)

But here is another approach:

1. extract page text for later re-insertion
2. remove text from page
3. make a grayscale image of the emptied page
4. insert image to new output page
5. re-insert saved text

This has a few advantages:
* there is no multiple images per page - just one
* the page image can be further compressed by e.g. not using PNG but JPEG with the support of Pillow - need to check this.
* freely choose appropriate font

Resulting PDF size for the 2 pages: 124 KB of which 26 KB is the Helvetica font. So we have about 50 KB per page on average. the final final file size would therefore be 225 * 50 + 26 which is about 11 MB.

**Comment by JorjMcKie** [comment]
New results using Pillow:

* file size = 70,8 KB
* average page size = (70.8 - 26) / 2 = 22.4
* expected 225 pages size: 225 * 22.4 + 26, a little over 5 MB

Here is the script:
```python
import fitz
from PIL import Image
import io

doc = fitz.open("P48_29-30.pdf")
newdoc = fitz.open()
font = fitz.Font("helv")


def remove_text(page):
    doc = page.parent
    page.cleanContents()
    xref = page.getContents()[0]
    cont = bytearray(doc.xrefStream(xref))
    s = 0
    while s >= 0:
        s = cont.find(b"BT")  # search start / end of text object
        e = cont.find(b"ET", s)
        if min(s, e) >= 0:
            cont[s : e + 2] = b""  # remove text object
    s = 0
    while s >= 0:
        s = cont.find(b"/Artifact")  # search start / end of watermark
        e = cont.find(b"EMC", s)
        if min(s, e) >= 0:
            cont[s : e + 3] = b""  # remove text object

    doc.updateStream(xref, cont)
    page.cleanContents()


for page in doc:
    blocks = page.getText("dict", flags=0)["blocks"]
    remove_text(page)
    newpage = newdoc.newPage(width=page.rect.width, height=page.rect.height)
    tw = fitz.TextWriter(newpage.rect)
    pix = page.getPixmap(colorspace=fitz.csGRAY)
    img = Image.frombytes("L", [pix.width, pix.height], pix.samples)
    bio = io.BytesIO()
    img.save(bio, format="JPEG")
    newpage.insertImage(newpage.rect, stream=bio.getvalue())
    for b in blocks:
        for l in b["lines"]:
            for s in l["spans"]:
                tw.append(s["origin"], s["text"], font=font, fontsize=s["size"])
    tw.writeText(newpage)

newdoc.save("x.pdf", garbage=4, deflate=True)
```
And the resulting PDF:
[x.pdf](https://github.com/pymupdf/PyMuPDF/files/5702015/x.pdf)

**Comment by JorjMcKie** [comment]
* Pillow also offers some more optimization option - there is an `optimize` parameter in ``save()``, which further reduces the x.pdf filesize to 67 KB.
* when creating the pages pixmap, you can also play with the resolution via using a matrix: ``pix = page.getPixmap(colorspace=fitz.csGRAY, matrix=fitz.Matrix(zoom, zoom))``. zoom < 1 will decrease image quality and size (quadratic impact!)
* depending on how exact you want to recreate the text, you can differentiate between Helvetica normal, italic, etc. Will increase final size, but with a one-time impact per font weight only. You should still remain under 5 MB.

**Comment by bserg66** [comment]
Many thanks! This is tutorial of my sun and he  will turn pages much faster at pocketbook.
I agree moving my issue(s) to the new "Discussions" category. Maybe  call him - " Pdf compress for pocketbook".
I hope this can be useful to someone else. 
I use all Helvetica - "helv", "heit", "hebo", "hebi".
I will deal with your answer and if you still have questions about working with the text, I will write to you.
