### ISSUE TITLE
How to extract textbox text?

### ISSUE THREAD

**Issue by jiezhoujenny** [pymupdf/PyMuPDF#776]
Hi, 
Is there any method that I can extract all the text in text box in a pdf file page? as attached picture shows (in red rectangle).
Thank you!
![image](https://user-images.githubusercontent.com/17275074/102658531-bc24a880-4145-11eb-9790-9d49377354a2.png)

**Comment by JorjMcKie** [comment]
The method is `page.getTextbox(rect)`.
But it seems in your example, some text pieces are not page text, but annotation or widget / field text. That text would of course **_not__** be included.
You have to extract annot / field text separately, by first checking which fields / annotations are inside the given rect, and then extracting the text from these separately.
