### ISSUE TITLE
page.getPixmap failure on 1.18.5

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#777]
One of my users see's a crash on 1.18.5 but not with 1.18.4, about calling `getPixmap` on a page...   `p` is a page.

```
  File "/home/XXXXX/.local/lib/python3.7/site-packages/plom-0.5.12.dev0-py3.7.egg/plom/scan/scansToImages.py", line 214, in processFileToBitmaps
    pix = p.getPixmap(fitz.Matrix(z, z), annots=True)
TypeError: getPixmap() takes 1 positional argument but 2 were given
```

I haven't tracked this down myself, or confirmed that `p` is still a page...  Will report back once I know more!

**Comment by cbm755** [comment]
Downstream: https://gitlab.com/plom/plom/-/issues/1321

> Quick investigation seems to indicate the getPixMap is no longer a class member function, but a standalone function.

**Comment by JorjMcKie** [comment]
Before v1.18.5, arguments have been insufficiently checked for being poditional vs keyword.
I am in the process of changing that (not finished though).
Per documentation, matrix must be given as a keyword - like all the rest, except self = page. So `page.getPixmap(matrix=fitz.Matrix(z,z))` will work.

**Comment by cbm755** [comment]
awesome, thanks for quick reply

**Comment by JorjMcKie** [comment]
> awesome, thanks for quick reply

Sorry for the confusion this may cause and thanks for your patience.
But I felt I need to clean up a few things in the repo. Unfortunately I have to support old python versions (although only 3.6+ from now on). It would be much easier to use the new `/` notation here.
Another major thing is to get rid of the CamelCase / mixedCase naming all over the place. I am in the process of introducing `page.get_pixmap(...)` type of stuff instead. This is already usable by the way in many places.

**Comment by cbm755** [comment]
We're happy to adjust to changes, no problem.

But maybe such a chance (killing off CamelCase) should be bumping the minor/major version not the patch version?  I tend to assume patch bumps are "safe" even for "core dependencies".

**Comment by cbm755** [comment]
And +1 for the new `/` notation!  That is sooo much better for libraries...  Except when they need to be backwards compatible!

**Comment by JorjMcKie** [comment]
> But maybe such a chance (killing off CamelCase) should be bumping the minor/major version not the patch version? I tend to assume patch bumps are "safe" even for "core dependencies".

So far, I am introducing new names just as synonyms - or vice versa, redefine the old names as synonyms. This of course bloats the classes. So I am considering to make a global function that can be used to delete the old names - maybe a stupid idea.
Another, maybe better option would be to introduce the new-named version (you are right: only together with a version change to 1.19.x) in conjunction with a little utility which walks through a set / folder of user scripts and replaces `.getPixmap(` occurrences by `.get_pixmap(` etc. you get the idea.
