### ISSUE TITLE
scrub() fails on removing file attachments

### ISSUE THREAD

**Issue by Naltharial** [pymupdf/PyMuPDF#785]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When trying to use fitz.utils.scrub() (called on the Document object initialized from a binary stream), PyMuPDF fails with an error on how the buffer is initialized.

```
RuntimeError: bad type: 'buffer'
  File "pdf_item.py", line xx, in preprocess
    pdf_doc.scrub(
  File "fitz/utils.py", line 3652, in scrub
    annot.fileUpd(buffer=b"")  # set file content to empty
  File "fitz/fitz.py", line 7199, in update_file
    return _fitz.Annot_update_file(self, buffer, filename, ufilename, desc)
```

The code works 99% of the time, but fails, it seems, on scrubing PDFs with attached files.

## To Reproduce (mandatory)
The relevant code is

```python
pdf_doc = fitz.Document(stream=file_data, filetype="application/pdf")
pdf_doc.scrub(
    attached_files=True,
    clean_pages=True,
    embedded_files=True,
    javascript=True,
    metadata=True,
    xml_metadata=True,
    remove_links=True,

    # TODO: OCR'd text?
    hidden_text=True,

    # Don't remove images
    redact_images=0,

    # Don't apply redaction annotations at this point
    redactions=False,

    # Don't remove form responses
    reset_fields=False,
    reset_responses=False
)
```
where `file_data` is just a binary stream of a PDF document. 

## Expected behavior (optional)
scrub() removing file attachments

## Your configuration (mandatory)
Python 3.8.6, PyMuPDF 1.18.4: Python bindings for the MuPDF 1.18.0 library.

**Comment by JorjMcKie** [comment]
Does it **_always_** fail if the PDF is provided as a stream?
Or on specific occasions only - in this case I would need a reproducer PDF.

**Comment by JorjMcKie** [comment]
Ok, forget it, found the problem:
to remove the file content, I overwrite it with an empty `bytes` object `b""`. But the replacement code asserts that `bool(buffer)` is `True`, otherwise raises an exception.
So simply using `b" "` instead solves the problem 🙄.

If you need a hotfix, simply change line 3652 in ``utils.py`` accordingly.

**Comment by JorjMcKie** [comment]
Fixed by new version currently being uploaded.
