### ISSUE TITLE
Inconsistent behavior of `getText()`

### ISSUE THREAD

**Issue by Matmaus** [pymupdf/PyMuPDF#792]
## Describe the bug
File: [pdf-example-with-bug.zip](https://github.com/pymupdf/PyMuPDF/files/5747695/pdf-example-with-bug.zip)

Method `getText()` returns different text content depending on the combination of used PyMuPDF version and value of parameter `opt`. It seems to happen since version `v1.18.2`. If it is possible to get the text as HTML, why not as plain text (and others)?

Returned text per version and `opt`:
- `v1.18.1-`
  - `text` "Hello World\n"
  - `html` "Hello World\n"
  - `json` "Hello World\n"
  - `blocks` "Hello World\n"
  - `words` "Hello World\n"
- `v1.18.2`
  - `text` "\n"
  - `html` "Hello World\n"
  - `json` "\n"
  - `blocks` ""
  - `words` ""
- `v1.18.3+`
  - `text` ""
  - `html` "Hello World\n"
  - `json` "\n"
  - `blocks` ""
  - `words` ""

## To Reproduce
```python
import fitz as pymupdf

doc = pymupdf.open('pdf-example-with-bug')  # see section above
page = doc.loadPage(0)
print(page.getText('text'))
print(page.getText('html'))
print(page.getText('json'))
print(page.getText('blocks'))
print(page.getText('words'))
```
NOTE: '\n' in `text` mode is visible only after encoding and it is not directly visible in other modes as well.

## Expected behavior
The returned text should be consistent among all `opt`s. If it can be obtained as HTML, it should be obtainable for other `opt` as well (see `v1.18.1`).

## Your configuration
 - Linux 4.19.160-1-MANJARO
 - gcc (GCC) 10.2.0
 - Python 3.8.6 (default, Sep 30 2020, 04:00:38)
 - PyMuPDF installed via `pip` (all mentioned versions), Python bindings for the MuPDF 1.18.0 library.

**Comment by JorjMcKie** [comment]
With the version you mentioned, I introduced the `clip` option to allow restriction of text extraction to a given rectangle. If not provided, then the full page rectangle is used - but it is still checked, that only characters are included that are fully contained in the rectangle (which is not the case in your example).
This restriction only applies to code that is developed by PyMuPDF, therefore (X)HTML and XML will show that text.

In the next version, I will adjust my logic a bit, so that text will be extracted if the text is at least partly on the page.

**Comment by Matmaus** [comment]
Thanks, it would be great to be able to get all text from the page.

**Comment by JorjMcKie** [comment]
The modification will be this:
* If `clip` is omitted (or `None`, the default), then no containment check is made at all. Previously, `clip = page.rect` was automatically set in that case.
* There are PDF cases, where text bboxes are (partly) outside the page rectangle (you gave an example) and this is **_unwanted_**. Then explicitely set `clip = page.rect` to exclude all characters not fully within.

If your case is urgent, drop me a note and I will make a pre-releae wheel.

**Comment by Matmaus** [comment]
It is not so urgent. I'll wait for a new release, thanks.

**Comment by JorjMcKie** [comment]
Fixed by new version currently being uploaded.
