### ISSUE TITLE
PyMuPDF fails to get metadata while opening the PDF document

### ISSUE THREAD

**Issue by Matmaus** [pymupdf/PyMuPDF#793]
## Describe the bug
File: [pdf-example-with-bug.zip](https://github.com/pymupdf/PyMuPDF/files/5747900/pdf-example-with-bug.zip)

Since version `v1.18.4`, PyMuPDF fails during the opening of this file.
```
Traceback (most recent call last):
  File "/home/user/test.py", line 12, in main
    doc = pymupdf.open(filepath)
  File "/home/user/virtualenv/lib/python3.8/site-packages/fitz/fitz.py", line 3635, in __init__
    self.initData()
  File "/home/user/virtualenv/lib/python3.8/site-packages/fitz/fitz.py", line 4657, in initData
    [
  File "/home/user/virtualenv/lib/python3.8/site-packages/fitz/fitz.py", line 4658, in <listcomp>
    (k, self._getMetadata(v))
  File "/home/user/virtualenv/lib/python3.8/site-packages/fitz/fitz.py", line 3941, in _getMetadata
    return _fitz.Document__getMetadata(self, key)
RuntimeError
```

## To Reproduce
```python
import fitz as pymupdf

doc = pymupdf.open('pdf-example-with-bug')  # see section above
```

## Expected behavior
The file should be successfully opened as in any of the previous versions (<1.18.3).

## Your configuration (mandatory)
- Linux 4.19.160-1-MANJARO
- gcc (GCC) 10.2.0
- Python 3.8.6 (default, Sep 30 2020, 04:00:38)
- PyMuPDF installed via pip (all mentioned versions), Python bindings for the MuPDF 1.18.0 library.

**Comment by JorjMcKie** [comment]
Some metadata keys contain invalid data.
The next version will catch such cases (again).

**Comment by JorjMcKie** [comment]
Fixed by new version currently being uploaded.

**Comment by Matmaus** [comment]
Thanks @JorjMcKie , I have one more question:
In the older version I got `metadata_author == '\u00c3\u00d6\u00b1\u00cd\u00c8\u00f1'`.
Now I get `metadata_author ==  '\u00c3\u0083\u00c3\u0096\u00c2\u00b1\u00c3\u008d\u00c3\u0088\u00c3\u00b1'`.
Creator has changed as well.
What is behind this change? Is it likely it will change again?

**Comment by JorjMcKie** [comment]
In the last working version, erroneous entries (i.e. invalid unicode spec) were simply ignored. Then, in an effort to heal this, I forgot to clear the Python error state before return (the reason for the exception you saw without accompanying text).
The current (and final) version has healed this and also uses the most inclusive translation mechanism:  PyUnicode_DecodeRawUnicodeEscape`, which returns an esacpe string for ilegal unicode characters, and also resets the Python error condition.

I cannot imagine this will ever change again.

**Comment by Matmaus** [comment]
OK, thank you for your answer.
