### ISSUE TITLE
Variable line-heights for insertTextbox

### ISSUE THREAD

**Issue by cmcnorgan** [pymupdf/PyMuPDF#804]
I see the line height is calculated at fixed 1.2*font size when determining the placement of subsequent lines. Is it possible to parameterize this so that line spacing could be increased/decreased, even if it meant that extenders from adjacent lines occasionally overlapped?

**Comment by JorjMcKie** [comment]
The line height is now (v1.18.5) dependent on font properties and now longer fixed.
But your request can certainly be implemented.
Note that this has to happen at two places: `Page.insertTextbox()` (resp. `Shape.insertTextbox()`) and `TextWriter.fillTextbox()`.

**Comment by JorjMcKie** [comment]
In v1.18.6 there will be an additional `lineheight` parameter in the respective methods.
This is a factor to use instead of the font property `ascender - descender`.

**Comment by JorjMcKie** [comment]
Fixed by new version currently being uploaded.
