### ISSUE TITLE
'Page' object has no attribute 'addHighlightAnnot'

### ISSUE THREAD

**Issue by wanting4** [pymupdf/PyMuPDF#808]
Hi,

I'm running PyMuPDF v.1.12.05 on Ubuntu 18.04 with Python3. When I tried to install the latest version there is an error says 'failed with error code 1 in /tmp/pip-build-_blybune/PyMuPDF/' Only v1.12.05 works.

I'm trying to highlight the text on my PDF using page.addHighlighAnnot(instance), but it keeps giving me this error:
AttributeError: 'Page' object has no attribute 'addHighlightAnnot'

My code is like this:
doc = fitz.open(current_SL)   #current_SL is the path to the PDF file
page = doc.loadPage(0)
text_instances = page.searchFor(word)
for inst in text_instances:
    highlight = page.addHighlightAnnot(inst)

The detailed log is this:
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fitz/fitz.py", line 1058, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Page, name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fitz/fitz.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Page' object has no attribute 'addHighlightAnnot'
                                
i checked the page type, it shows as fitz.fitz.Page, don't know how to fix this?

Thank you so much!

**Comment by JorjMcKie** [comment]
Open a new issue for the installation issue with the current version.
If you do this, please provide all mandatory information.
I know you use Ubuntu, but I am missing the bitness (64bit?) and the method: pip install wheel or from source, etc.

**Comment by wanting4** [comment]
OK, I will open a new issue for installing the current version. Thank you!
