### ISSUE TITLE
Cannot install current version on ubuntu 18.04

### ISSUE THREAD

**Issue by wanting4** [pymupdf/PyMuPDF#809]
Hi, 

When i try to install current version on my Ubuntu 18.04 pip3 install PyMuPDF. 
the error message is like this:
<img width="1665" alt="Screen Shot 2021-01-05 at 10 29 51 AM" src="https://user-images.githubusercontent.com/61065461/103671753-ef867600-4f40-11eb-9499-3f6e5d22388b.png">

I also tried pip3 install -U PyMuPDF, error is 
<img width="1664" alt="Screen Shot 2021-01-05 at 10 31 15 AM" src="https://user-images.githubusercontent.com/61065461/103671898-28264f80-4f41-11eb-8a73-5905194042b9.png">

Here is the information of my ubuntu cpu
<img width="500" alt="Screen Shot 2021-01-05 at 10 26 43 AM" src="https://user-images.githubusercontent.com/61065461/103671500-9d455500-4f40-11eb-9043-c3a2f6f664eb.png">

What I want to do is to use Fitz module to highlight my pdf in python. 

Thank you so much!

**Comment by JorjMcKie** [comment]
You obviously try to install PyMuPDF in a 32bit Python.
For this bitness, there exist no wheels for Linux or OSX, Therefore pip tries to generate PyMuPDF from sources. This however is bound to fail because you have not installed the prerequisite MuPDF.

Therefore you have two options:
1. use pip install for a 64bit Python 3.6 or up
2. install MuPDF first as described  in the documentation, then try installing PyMuPDF again.

**Comment by wanting4** [comment]
I'm trying to install MuPDF. I downloaded muPDF-1.18.0-source.tar.gz and unzipped it. According to the doc, after unzipping, should I copy all those files beginning with underscore '_' (_init_.py, _main_.py, _config.h) from PyMuPDF repo to the unzipped folder path: mupdf/include/mupdf/fitz/? I saw there is a config.h file in the unzipped muPDF folder, shall I just replace it? Thanks!
<img width="699" alt="Screen Shot 2021-01-05 at 11 46 15 AM" src="https://user-images.githubusercontent.com/61065461/103680475-d636f700-4f4b-11eb-8886-1e850da98461.png">

**Comment by JorjMcKie** [comment]
Just `_config.h` (**_single_** underscores only). And even that is optional: your final binary `_fitz....so` will be 30 MB large instead of about 10 MB, that's all.
And yes: this file shoudl replace `config.h`.
Do not miss to consult the `installation` folder of the repo.

**Comment by JorjMcKie** [comment]
Is there a strong reason why you must use Python 32bit?

**Comment by wanting4** [comment]
Not as I think. It's just my project keeps using 32-bit so I just kept using it. will the same code run smoothly on 64bit Python? Sorry I'm new to this. Thank you so much for the help!

**Comment by wanting4** [comment]
Do you think using 64bit python will be a better resolution than installing MuPDF?

**Comment by JorjMcKie** [comment]
> Do you think using 64bit python will be a better resolution than installing MuPDF?

Sure, it will be a no-brainer: pip will download the wheel and you are done in 10 seconds.

> will the same code run smoothly on 64bit Python?

Most probably yes. Of course you have to re-install everything in that 64bit Python. Let the pip of your Python 32bit create a requirements file, then use the pip of your 64bit Python to install everything there. This works like so:
1. In your old python do `pythonx.y -m pip freeze` will produce a listing of installed packages. Store this output in a file, say `requirements.txt`.
2. In your new python do `sudo -H pythona.b -m pip install -r requirements.txt`.

A recommendation: **_never_**  just use the command `pip3` or the like. **_Always_** use `sudo -H pythonx.y -m pip install ...` with the appropriate Python version x.y. `sudo` is of course only required when pip changes something.

**Comment by JorjMcKie** [comment]
How are you doing?
Need help?

**Comment by wanting4** [comment]
Hi Jorj,

Thank you so much. I’m trying to install Python64. I have a shell script to install required package. So I just run that shell script again on Python 64 then everything should be installed right?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wanting4** [comment]
Hi Jori, I just checked my old python3 bit version. It seems my Python is already 64 bit? Please see the screenshot below.
<img width="285" alt="Screen Shot 2021-01-11 at 10 20 50 AM" src="https://user-images.githubusercontent.com/61065461/104208997-c6f5f480-53f6-11eb-9983-a8548848b008.png">

**Comment by wanting4** [comment]
and my python3 version is 3.6.9

**Comment by wanting4** [comment]
When I run 'make' command to install MuPDF after unzip mupdf-1.18.0.source.tar.gz file, this error comes up. I check the path and there does not have the file XInput.h. Did I download wrong version?

<img width="814" alt="Screen Shot 2021-01-11 at 10 35 48 AM" src="https://user-images.githubusercontent.com/61065461/104210686-c78f8a80-53f8-11eb-8420-dd029db86697.png">

**Comment by JorjMcKie** [comment]
Hm, looks like a tohuwabohu.
If you really have a python v3 64bit, you need not install MuPDF! Just do this:
``sudo -H python3 -m pip install -U pymupdf``

**Comment by wanting4** [comment]
OK! Let me try!

**Comment by wanting4** [comment]
I got an error similar to the previous ones.
<img width="811" alt="Screen Shot 2021-01-11 at 10 45 31 AM" src="https://user-images.githubusercontent.com/61065461/104211981-53ee7d00-53fa-11eb-8a07-3094f529220a.png">

**Comment by wanting4** [comment]
Ah! I made it! I upgrade pip by using: sudo -H python3 -m pip install -U pymupdf
then do the: sudo -H python3 -m pip install -U pymupdf
It worked! Thank you so much!
Just to double check, after I installed PyMuPDF, I can run fitz and do not need to install fitz package right?

**Comment by wanting4** [comment]
Typo: sudo -H pip3 install --upgrade pip first

**Comment by JorjMcKie** [comment]
Uff - finally.

>  Just to double check, after I installed PyMuPDF, I can run fitz and do not need to install fitz package right?

Yes, you are done and can start importing fitz rightaway

**Comment by wanting4** [comment]
Got it! Thank you for the support. Really helped a lot!!
