### ISSUE TITLE
Followup to issue 313 - How to remove a *UNUSED* font

### ISSUE THREAD

**Issue by anth9217** [pymupdf/PyMuPDF#811]
Hello,

Regarding issue [313](https://github.com/pymupdf/PyMuPDF/issues/313), I'd like to implement your proposed solution:

```
xreflen = doc._getXrefLength()  # number of all xrefs
for xref in range(1, xreflen):  # do not use xref 0!
    indicator = False  # set to true if font xref is referenced
    new_obj_lines = []
    obj_lines = doc._getXrefString(xref).splitlines()  # get xref source split in lines
    for line in obj_lines:
        if " %i 0 R" % font_xref in line:
            indicator = True  # update this object!
            continue
        new_obj_lines.append(line)

    if indicator is True:  # must update this object
        new_obj = "\n".join(new_obj_lines)
        doc._updateObject(xref, new_obj)

doc.save ...
```

I have updated the function names doc._getXrefLength() to doc.xref_length() and doc._getXrefString to doc.xref_object. When I run this, I get NameError: name 'font_xref' is not defined.

Any help you could provide would be greatly appreciated.

**Comment by JorjMcKie** [comment]
> Any help you could provide would be greatly appreciated.

That name `font_xref` is just a placeholder for the xref of the font to be removed. Once you know the unwanted font, get its xref and insert it here.
Please rmember, that all this only works if the page really does not use the font. There are cases, where a font is mentioned in the page's object definition even though nothing in the page's `/Contents` objects refers to it. Only in this situation, the approach will work. To be clear: you have
1. the font occurs in the list `doc.getPageFontList(page.number)`
2. in all of the page's (one or many) `/Contents` objects no text output command refers to it.

For example, if you **_know_** that "SymbolMT" is unused, then in the following list
```python
>>> pprint(doc.getPageFontList(0))
[(12, 'ttf', 'TrueType', 'FNUUTH+Calibri-Bold', 'R8', ''),
 (13, 'ttf', 'TrueType', 'DOKBTG+Calibri', 'R10', ''),
 (14, 'ttf', 'TrueType', 'NOHSJV+Calibri-Light', 'R12', ''),
 (15, 'ttf', 'TrueType', 'NZNDCL+CourierNewPSMT', 'R14', ''),
 (16, 'ttf', 'Type0', 'MNCSJY+SymbolMT', 'R17', 'Identity-H'),
 (17, 'cff', 'Type1', 'UAEUYH+Helvetica', 'R20', 'WinAnsiEncoding'),
 (18, 'ttf', 'Type0', 'ECPLRU+Calibri', 'R23', 'Identity-H'),
 (19, 'ttf', 'Type0', 'TONAYT+CourierNewPSMT', 'R27', 'Identity-H')]
>>> 
```
this would mean that string `b"/R17"` is not contained in any `/Contents` of page 0.
**_Then_** you can set `font_xref = 16` in that code snippet.

As mentioned in #313 you can also try to simply execute `page.clean_contents()`. The internally invoked MuPDF cleaning mechanism will do the job for you.

**Comment by JorjMcKie** [comment]
Assuming your consent, I will move this issue to the "Discussions".

**Comment by JorjMcKie** [comment]
How are you doing? Need more help?
