### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by juviwhale** [pymupdf/PyMuPDF#813]
Just a heads of on a minor typo in the provided docs.

`fill_opaity` is often displayed as an argument name, using that argument causes an exception as it is defined in your code as `fill_opacity`

(REF: Docs Example](https://pymupdf.readthedocs.io/en/latest/page.html#Page.insertText)

**Comment by JorjMcKie** [comment]
Thank you for this.
Corrected the typo. New version can be downloaded in a minute.

**Comment by JorjMcKie** [comment]
Fixed.
