### ISSUE TITLE
Quick way to check if a pdf doc has annotation

### ISSUE THREAD

**Issue by jindili** [pymupdf/PyMuPDF#816]
I want to checkout if there is a quicker way to check whether a pdf doc has annotation, 
or I have to loop through pages like this:

```
for page in doc:
   for annot in page.annots():
      return True
```

**Comment by JorjMcKie** [comment]
Hm, not really, or let's say a bit maybe:

* There is no central place in a PDF where the existence of annotations is stored like there is for fields. To check field existence, there is `doc.isFormPDF`.
* You loop is a nested loop and you should make sure to break out of each as soon as you can. For a negative answer of course you are bound to wait until the last page.
* There is method `page.annot_xrefs()` which returns a list of triples `(xref, type, name)` for all **_links, fields and annotations_** that the page may have. So you could build this per page, which excludes links and widgets and makes a non-empty set if anything survives this selection:

```
set([True for i in page.annot_xrefs() if i[1] not in (fitz.PDF_ANNOT_LINK, fitz.PDF_ANNOT_WIDGET)])
# if the page has annotations, the result is
{True}
# else
set()
# so you could build a fairly short loop:
s = set()
for page in doc:
    s = s.union(set([True for i in page.annot_xrefs() if i[1] not in (fitz.PDF_ANNOT_LINK, fitz.PDF_ANNOT_WIDGET)]))
# now check whether s is {True} or set()
```

**Comment by JorjMcKie** [comment]
As I said, loading all pages is inevitable, but you can at least avoid loading any annotations.

**Comment by jindili** [comment]
Hi @JorjMcKie , Thank you for detailed explanation.

I do some test and use this code
```
def checkAnnotationInPDF(docPath):
    doc = fitz.open(docPath)
    for page in doc:
        for annot in page.annots():
            # print("Yes, There are Annotations in this file")
            return True
    return False
```

Though we have to loop through the pages, it's still fast enough to check 1000+ PDF documents.
I'll use this code till there is some way better.

**Comment by JorjMcKie** [comment]
I have just developed a minor improvement. It does what I recommended in my post, but without loading the pages.
Measurement show, that this is more than 15 times faster.
That for bringing this up anyway.

**Comment by JorjMcKie** [comment]
Just as a headsup: there will be two new `Document` methods, which check the existence of links or annotations anywhere in the document:

* `doc.has_links()`
* `doc.has_annots()` 

Both are based on that code involving Python sets. For large documents like the Adobe manual (1310 pages) or the Pandas documentation (3070 pages), which both contain no annotations (so all pages are checked), total respsonse time of `doc.has_annots()` is 12.3 ms on my machine (Win 10, 2.6 GHz processors).

**Comment by jindili** [comment]
@JorjMcKie That's Cool.
Looking forward to next release.

**Comment by jindili** [comment]
post the document here for quick reference:
Document — PyMuPDF 1.20.1 documentation
https://pymupdf.readthedocs.io/en/latest/document.html?highlight=has_annots#Document.has_annots
