### ISSUE TITLE
Help: Extracting "comment" annotations from PDF

### ISSUE THREAD

**Issue by dummifiedme** [pymupdf/PyMuPDF#819]
I have a very little knowledge of programming (just very basic stuff out of interest). I have this use case where I wanted to have a way to extract all the comments (or highlights as well) into a text or markdown. I found some tools, but they weren't of my liking in terms of formatting, they were particularly of a different use case. I can discuss my exact usecase (idea) if someone is interested, but the main element is to be able to extract a comment out of a pdf (edited using any pdf editor).

I decided to chalk out some time out of my study schedule to fix up a small code to do it for me. While searching online (github, stackoverflow), I came across PyMuPDF and several other options, and out of them PyMuPDF seems to be the most active projects. 

So, heres exactly what I needed to do to implement my idea:
- Extract each "comment" box into prefereably a new markdown file (inside a common folder)
- Link and list all those file in one file (like a index of all the comments).

I don't exactly know how to proceed. If someone can point me where to start and what all to read and understand, it would be great :)  
And, how much time would it approximately take to have such a code up and running? (including the learning part)

**Comment by JorjMcKie** [comment]
Let's start with recommending to use the "Discussions" section (top menu point). This offers better abilities to everyone wanting to join (more chat-like).

As per the time requirements, a lot depends obviously on just how early you are in programming.

Other than that, the script could be done in a day or two.

Some preliminary clarifications:
* with "comment" annotations you presumably mean the term 'FreeText' annotations in PDF?

If so, text extraction is fairly easy: the basic approach is this
* start with some list of PDF files you need to process - could be folder for example
* then, in a loop, go through those filenames and open each one as a `fitz.Document` via `doc = fitz.open(filename)`
* then in another loop one level down go through all pages of the current `doc`
* then in yet another loop level go through all annotations of the current page and select those, which are of 'FreeText' type.
* for each selected annotation "annot" read out the text via `text = annot.getText()`.
* store away the text.

Details include, how you want to mark each selected text, i.e. its meta-information. Ideas for this may be filename, page number and metadata of the annotation itself (like author, creation date, mod date, ...).

Depending on what you want to do with the outcome, a basic option would be to store all that information in a table-like structure, e.g. a CSV file, where the information mentioned above would become coluns.

Or you could create a new PDF with those data ... 😉

Here is a rough code snippet:
```python
import fitz
import os

filelist = os.listdir()  # a folder where the PDFs live
textfile = open(
    "collected-comments.txt", "w"
)  # a simple text output for the extracted comments
for filename in filelist:  # loop thru the PDFs
    if not filename.endswith(".pdf"):
        continue  # exclude files that are no PDFs
    doc = fitz.open(filename)
    textfile.write("Comments in PDF '%s'.\n" % doc.name)
    for page in doc:  # loop thru pages of current PDF
        textfile.write("Comments on page %i:\n" % page.number)
        for annot in page.annots(
            types=[fitz.PDF_ANNOT_FREE_TEXT]
        ):  # loop thru freetext annots
            text = annot.getText()  # extract the text
            textfile.write(text)
            # other annot information could be extracted
            # and written here as well
            textfile.write("-" * 10 + "\n")  # write delimiter
        textfile.write("=" * 20 + "\n")  # write end-of-page delimiter
    doc.close()
textfile.close()

```
As I wrote: just a snippet, but may be a start for you.

**Comment by dummifiedme** [comment]
@JorjMcKie Thank you for a reply and the suggestions :)

> with "comment" annotations you presumably mean the term 'FreeText' annotations in PDF?
By Comment I meant the "Text" annotations. Like a pop-up comment which could be attached to a highlight as well as free float. It is third from the top in the example I read.
![image](https://user-images.githubusercontent.com/68785729/104125030-3548a180-537a-11eb-961f-fabef3449f05.png)

The snippet works fine. Actually, it is very close to what I need. Just if I could have a way to extract the comments (the ones I mean).  I tried changing the type in your snippet to `[fitz.PDF_ANNOT_TEXT]` but it did not work. I will try to see what it is called :)

**Comment by JorjMcKie** [comment]
Yes the PDF_ANNOT_TEXT text is not stored like that. Instead that text is stored as part of the annotation's info dictionary:
```python
>>> doc=fitz.open("new-annots-0.pdf")
>>> page=doc[0]
>>> for annot in page.annots(types=[fitz.PDF_ANNOT_TEXT]):
	continue

>>> annot
'Text' annotation on page 0 of new-annots-0.pdf
>>> annot.getText()  # nothing here
''
>>> annot.info
{'content': 'têxt üsès Lätiñ charß,\nEUR: €, mu: µ, super scripts: ²³!', 'name': 'Note', 'title': '', 'creationDate': '', 'modDate': '', 'subject': '', 'id': 'jorj-A2'}
>>> text = annot.info ["content"]  # but here is what you need
>>> print(text)
têxt üsès Lätiñ charß,
EUR: €, mu: µ, super scripts: ²³!
>>> 
```
Text marker annotations on the other hand (highlight, underline, ...) do not contain text of their own at all. Their rectangle is usually used to wrap some text of the PDF page itself, so the text of "them" must be extracted from the page.
Let me know if you need that part too.

>  I will try not to bother you guys till I actually get stuck somewhere :)

Please don't stop asking, you are welcome.

**Comment by JorjMcKie** [comment]
**_Popup_** annotations are something different again.
Their support is new in PyMuPDF. Let me check how I implemented the access to them.

They will not show up in the iterator `page.annots()`. Instead, you must loop through **_all_** annotations and check for each one whether there a popup attached to it.

**Comment by dummifiedme** [comment]
> Text marker annotations on the other hand (highlight, underline, ...) do not contain text of their own at all. Their rectangle is usually used to wrap some text of the PDF page itself, so the text of "them" must be extracted from the page.

Ah, got it. I should have maybe guessed that. While trying to capture text from annotations of other types that I found in documentation, I was getting blank lines and the `------------` were still there, which meant it can see the annotation, but theres on text to capture! 

I ,now, understand how this will work. I think you have already provided all the things I needed for a start. Seeing that PyMuPdf has features or function already available for things, I think I can extend the idea I was initially having. 👍🏼 

I have a  question:
- Can I also have the color of the annotation? I did not see anything realated to color property in `annot.info`. 



> Text marker annotations on the other hand (highlight, underline, ...) do not contain text of their own at all. Their rectangle is usually used to wrap some text of the PDF page itself, so the text of "them" must be extracted from the page.
Let me know if you need that part too.

Yes, I am now thinking of capturing highlights as well. 
- How are the text under the highlights are captured?
- How can the note(comment or TEXT type here) on that particular highlight be identified?
- Can these be categorized wrt to their colours?

**Comment by dummifiedme** [comment]
> 
> 
> **_Popup_** annotations are something different again.
> Their support is new in PyMuPDF. Let me check how I implemented the access to them.
> 
> They will not show up in the iterator `page.annots()`. Instead, you must loop through **_all_** annotations and check for each one whether there is a popup attached to it.

Yeah, got it now :)

**Comment by dummifiedme** [comment]
Sidenote: Should I close this issue and continue in discussions or shall I keep barging my questions here 😅

**Comment by JorjMcKie** [comment]
> Should I close this issue and continue in discussions

Yes please, should be more adequate and approachable by others.

**Comment by JorjMcKie** [comment]
> Can I also have the color of the annotation? I did not see anything realated to color property in annot.info.

There is property `annot.colors`.
```python
>>> annot.colors
{'stroke': [1.0, 1.0, 0.0], 'fill': []}
```
Stroke means border color (mostly, not always) and fill the interior color. If omitted, an empty sequence, else the RGB color triple as PDF encodes it: 0 <= float <= 1.

You also set the colors ...

**Comment by dummifiedme** [comment]
> Yes please, should be more adequate and approachable by others.

Sure :)

> There is property annot.colors.

Is it used for assigning a color to annotation or extracting the color info? (last question here maybe :p)

**Comment by JorjMcKie** [comment]
To set an annot's color: `annot.set_colors(stroke=[...], fill=[...])`. After finished changing this annot (you may have done more things like setting the border etc.), you must invoke `annot.update()`.
To check colors see above.
Similar approach: border <=> set_boder, blendmode <=> set_blendmode, etc.
