### ISSUE TITLE
Searches on the documentation page

### ISSUE THREAD

**Issue by dummifiedme** [pymupdf/PyMuPDF#824]
The searches on the documentation page of PyMuPDF doesn't really work. It fails to find anything on the documentation. I don't know if it is a problem with Sphinx or something that just skipped somewhere :)  

I thought I should report it, no complaints anyway

This is the page I am refering to : https://pymupdf.readthedocs.io/en/latest/

**Comment by cipri-tom** [comment]
This is already discussed in #374 . Any solutions are welcome ^^

**Comment by dummifiedme** [comment]
Ah, I see. I should delete this issue or just closing it would be fine?
