### ISSUE TITLE
update_stream might still raise error with new=True

### ISSUE THREAD

**Issue by user202729** [pymupdf/PyMuPDF#837]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

```RuntimeError: not a dict (null)``` is raised if `update_stream` is called on a just-created xref.

## To Reproduce (mandatory)

```
doc=fitz.Document()
xref=doc.get_new_xref()
#doc.update_object(xref, "<< >>")  # workaround: uncomment this line
doc.update_stream(xref, b"test", new=True)
```

## Your configuration (mandatory)

(probably not necessary.)

## Additional context (optional)
The bug is trivial to workaround (if one know how), but at least this is a undocumented behavior.

**Comment by JorjMcKie** [comment]
You are right when saying "undocumented behavior".
The MuPDF reaction is correct - in so far everything works as designed.
