### ISSUE TITLE
Can you please add `linear` to write()

### ISSUE THREAD

**Issue by jloehel** [pymupdf/PyMuPDF#842]
https://github.com/pymupdf/PyMuPDF/blob/b0babae8ffb754c7b9bcc57d883800e005238a7e/fitz/fitz.i#L1685-L1688

I am not sure if this is on purpose but it would be nice to write also linearized files. :-)

**Comment by zufj** [comment]
Hey,

Apparently it is a limitation from the underlying mupdf library, see #674. So this change won't come soon.

We used temporary files to deal with it and the performance was fine on our setup.

Cheers

**Comment by JorjMcKie** [comment]
> Apparently it is a limitation from the underlying mupdf library

Linearization as implemented by MuPDF requires the output device to support the ``seek`` operation, which does not work with memory buffers.

After this had been detected by #674 I disabled the linear option for bytes output (which I will rename to `doc.tobytes` btw.).
I can't image this will change ever.

I never bothered to try alternatives like `io.BytesIO`: A considerable amount of coding would be required to present this as a file to MuPDF (out of the box, they only support filename-based files or memory as output devices), and then it is unclear whether seek operations would go through in this case ...

So it looks like temporary files are the way to go for the time being.

**Comment by JorjMcKie** [comment]
I remember I did use MuPDF's option to user-define an own output device. Requires providing function slots for all the disk operations - seek being among them.
If using a bytearray as the storage device, I image one can mimic everything that may come up ...
If that in fact works, we would be there ...

**Comment by JorjMcKie** [comment]
Let me convert this thread to a discussion ... will be more adequate.
