### ISSUE TITLE
Recompressing Objstm when saving

### ISSUE THREAD

**Issue by jayjb** [pymupdf/PyMuPDF#848]
I have noticed that when you load a pdf in using the `fitz.Document(..)`, and then view that pdfs xrefs, it automagically decompresses and organises the `/Objstm` from the pdf. 

It would be great to be able to do two things:
- tell `fitz` to not untangle that `/Objstm`, or
- have `doc.save(..)` allow you to recreate that `\ObjStm` or create a new `/ObjStm`.

Currently I can't think of alternatives for an `/ObjStm` as it is a base pdf structure. As an example, something
like
```
5 0 obj
(www.hello.com)
endobj
``` 
would work fine. But if you wanted to compress or obfuscate that url using a stream
```
5 0 obj
<</Length 30 /Filter/FlateDecode>>
stream
<some binary data>
endstream
endobj
```
That gives an error when opening the pdf. The only working alternative is to have 
```
5 0 obj
<</Filter/FlateDecode/First 25/Length 100/N 4/Type/ObjStm>>stream
<some binary data>
endstream
endobj
```
Usually these `/ObjStm` would contain a few different objects; not just one, but you get what I am saying hopefully.

Of course, this is a great project! Loving using it and would love to help contribute if you can point me in the right direction. 

Thanks so much folks!

**Comment by JorjMcKie** [comment]
I think I do understand.
And thank you for using and appreciating PyMuPDF!

Unfortunately, there is no way to do any of you suggestions - at least not in PyMuPDF. These features and behaviours are provided by our base library, MuPDF.
Obviously ObjStm objects need to be decompressed by MuPDF to access the PDF. If you changes and / or save options imply that any of the objects inside some ObjStm must be changed, then MuPDF is of course forced to leave the respective ObjStm decompressed.
MuPDF also has no option to compress objects into ObjStms during save.

Maybe you submit a feature request to them here: https://bugs.ghostscript.com/enter_bug.cgi

**Comment by jayjb** [comment]
Hi @JorjMcKie,

Thanks for getting back to me. I suspect it isnt something on the roadmap in general. Recompressing `/ObjStm` would also mean generating cross reference streams which I suspect would quite a bit of complexity for something that isn't a necessity in using PDFs. 

Ill go ahead and submit a feature request anyway and maybe it is something they are aiming at. 

I suspect most of my frustration comes from URLs having to be a sort of plaintext rather than a stream (unless im formatting it badly).

**Comment by JorjMcKie** [comment]
I understand. There have been cases, where I did miss this type of thing, too.
I am watching a little bit what they are doing on their development repo. As far as I can see, their experiments are focussing on a few other things at the moment, like integration of OCR features via Tesseract, and extending conversion output options to RTF type files.

**Comment by jayjb** [comment]
Ah ok ok, thanks so much for checking. Good luck with the project (im sure ill be bugging you soon enough 😄 )
