### ISSUE TITLE
saved pdf is huge

### ISSUE THREAD

**Issue by iamRyanChia** [pymupdf/PyMuPDF#876]
I want to remove all text block in my pdf, so i wrote following codes:
```python
doc = fitz.open('in.pdf')

for page in doc:
    blocks = page.get_text('blocks')
    for b in blocks:
        if b[-1] == 0:  # text block
            page.addRedactAnnot(b[:4])
    page.apply_redactions()

doc.save('out.pdf',
         garbage=4,
         clean=True,
         deflate=True,
         deflate_images=True,
         deflate_fonts=True)
```

Although I used `garbage` and `deflate` option, I found the saved pdf is very huge. The in.pdf is 206MB, the out.pdf is 720MB. Any other methods to reduce the file size? Thank you!

**Comment by JorjMcKie** [comment]
Not knowing your PDF, some suggestions may still help:
The default option for applying redactions is ``apply_redactions(images=fitz.PDF_REDACT_IMAGE_PIXELS)``.
This modifies each image overlapping a redact rect by whitening the overlap area. The resulting new image always is a PNG format, which may easily be larger than the original format ...
I understood you only want text removed. So best use a different option from this part of the docu:

```
Parameters: | images (int) – (new in v1.18.0) how to redact overlapping images.
              The default (2) blanks out overlapping pixels. PDF_REDACT_IMAGE_NONE (0) ignores,
              and PDF_REDACT_IMAGE_REMOVE (1) completely removes all overlapping images.
```

Also best use ``page.clean_contents()`` right in the page loop. I observed a more effective behaviour, than just using clean in the save method.

**Comment by iamRyanChia** [comment]
The pdf is scanned book, the text block is watermark. I want to remove the watermark by the codes.

I have changed the `PDF_REDACT_IMAGE_PIXELS` to `PDF_REDACT_IMAGE_REMOVE`, but the file size reduced little. I am seeking other methods. Thank you!

**Comment by JorjMcKie** [comment]
A scanned book only shows one big image per page. Not a good idea to remove that.
Also, these images are responsible for the file size - not the text.
To just remove a watermark, you may find this dicussion entry useful: https://github.com/pymupdf/PyMuPDF/discussions/874.

**Comment by iamRyanChia** [comment]
Another question: Does PyMuPDF support "inherit zoom" as Acrobat? "inherit zoom" means keeping zoom level invariant when jump to another bookmark. Thank you!

<img width="398" alt="截屏2021-02-03 下午10 24 38" src="https://user-images.githubusercontent.com/41557860/106763637-01f3ec80-6672-11eb-911c-b518c78bb1f5.png">

**Comment by iamRyanChia** [comment]
I am back to say how I solved these. PDF_REDACT_IMAGE_NONE will not increase the file size. I used PyPDF2 library to add toc, and I couldn't find how to set "inherit zoom" in PyPDF2. But toc added in PyMuPDF  is "inherit zoom" by default. Thank you for your great work!

**Comment by JorjMcKie** [comment]
>  But toc added in PyMuPDF is "inherit zoom" by default. 

Thanks for reporting this anyway. In the meantime I realized, that the base library, MuPDF, actually does not handle zoom in the right way: it always stays that way and cannot be changed ...
So I had to add code filling this gap in the next version.

Were you successful in removing the watermark?

**Comment by iamRyanChia** [comment]
> Were you successful in removing the watermark?

Yes, just change `page.apply_redactions()` to `page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)` in my codes.
