### ISSUE TITLE
Use deprecations for CamelCase functions?

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#879]
In SymPy I recall they had a `@decorator` for deprecating methods: I could look up details if needed.

Maybe this would be a nice way to do the CamelCase to snake_case porting?  People would start getting DeprecationWarnings when using CamelCase, and projects could get a head start by setting those warnings to exceptions, e.g., for CI jobs.

**Comment by JorjMcKie** [comment]
Hi,
that is a great idea! I would be really grateful for having a way to gently push people to the new naming convention.

You may have noticed that big function ``restore_aliases()`` in ``__init__.py``, which defines all those old names.
For now it is executed. My plan simply was, to no longer do this at some point, but keep it there, so people can execute it themselves when needed.
So it would be excellent, if there were one or more additional grades of stepping back from the mixedCases ...

So I imagine, instead of simply setting ``fitz.Document.pageCount = fitz.Document.page_count``, I could wrap the right side by such a decorator ...

**Comment by cbm755** [comment]
Sounds great!  A possible plan:
1.  Release a 1.19.0 (when ready) which adds these formal deprecations.
2.  Then in 1.20.0 they become errors (or even 1.21.1 if you wanted to be overly generous to your downstream).  People have the entire 1.19.x cycle to fix their code.

IIRC, in SymPy, the decorator allowed you to specify which version it would stop working in.  That's my rough memory anyway.

**Comment by abarker** [comment]
In my project pdfCropMargins I'm getting an attribute error on calling `document.isEncrypted` just after opening a document
with PyMuPDF 1.18.8.  It works when calling `is_encrypted`, and the error does not occur at all with PyMuPDF 1.17.  I assume this is related to the renaming.

I'll just push out a version with the new naming, but I don't see `isEncrypted` in the `restore_aliases` function.

**Comment by JorjMcKie** [comment]
@abarker - it indeed is related to the renaming effort.
A handful of attributes unfortunately cannot be included in the `restore_aliases` - they are created on the fly when their objects come into existence and do not already exist at the time of `import`. Attributes ``is_open`` and ``is_encrypted`` are examples for this (as opposed to ``needs_pass`` which is based on a MuPDF function, wrapped in a Python `@property`).
So I need to handle them separately. My intention is to always set their old and new name synchronously during the _interregnum_, but may have missed a spot - let me check.

**Comment by JorjMcKie** [comment]
> IIRC, in SymPy, the decorator allowed you to specify which version it would stop working in.

@cbm755 - thanks for that hint. I have looked there and found that a separate package, "deprecation" is being used. I am still investigating the best way to either integrate this (does not support attributes ..) or adopt and extend the basic idea.

**Comment by abarker** [comment]
FYI, I just got a pdfCropMargins bug issue related to the attribute `getPixmap`.  It worked up to 1.18.8 but raises an attribute error in 1.18.9.

**Comment by JorjMcKie** [comment]
@abarker - please submit an issue with more details ...

**Comment by JorjMcKie** [comment]
@cbm755 - I finally found a way to implement a feature similar to the one you mentioned.
In the next version (1.18.14 onwards) there will be deprecation warnings like:
```python
>>> import fitz
>>> doc=fitz.open()
>>> page = doc.newPage()
DeprecationWarning: deprecated (removed after v. 1.19) - use 'new_page'.
>>> page = doc.newPage()  # no message after 1st time use
>>> page = doc.newPage()
>>> page = doc.newPage()
>>> pix = page.getPixmap()
DeprecationWarning: deprecated (removed after v. 1.19) - use 'get_pixmap'.
>>> b = pix.getPNGData()
DeprecationWarning: deprecated (removed after v. 1.19) - use 'tobytes'.
>>> 
```
I found no way yet to issue a similar message if **_deprecated properties_** are used.
Maybe someone has an idea here.
But there exists a hint in the `__doc__`  of deprecated methods and attributes like so:
```python
>>> help(fitz.Document.pageCount)
Help on property:

    *** Deprecated, will be removed after v1.19. Use 'page_count'. ***
    Number of pages.

>>> help(fitz.Document.newPage)
Help on function fn in module fitz:

fn(*args, **kw)
    *** Deprecated, will be removed after v1.19. Use 'new_page'. ***
    Create and return a new page object.

>>> 
```

**Comment by cbm755** [comment]
That looks great!

Speaking as downstream: I would slightly prefer the deprecation *msg* turns on in 1.19.0 and then "will be removed in v1.20.0".  But its not a big deal!   And maybe you don't have total control of your version numbers (b/c of coordination with your MuPDF upstream...)

**Comment by JorjMcKie** [comment]
Thanks a lot for your feedback!
I was trying to express your suggestion:
1. deprecation messages from now on and including the next change in the combination of MuPDF version major.minor
2. removal of aliases in the version that follows that.

I am expecting a new MuPDF version 1.19.0 more or less every day now: it's half a year since 1.18.0 went public. So naming 1.19.0 is fine.
But I do not know what follows then: 1.20.0? 2.0.0?
So maybe a message like "will be removed in version following 1.19.0"?
Due to PyMuPDF's version naming standards, my major/minor always is obliged to equal MuPDF's ...

**Comment by JorjMcKie** [comment]
I have changed the deprecation text to ``DeprecationWarning: deprecated (removed in version following 1.19.0) - use '...'.``

Thanks again for the idea and your continuos feedback!
Going to close this for now.

**Comment by cbm755** [comment]
My point is turning on the warnings for 1.18.x forces downstream users to port for a patch bump.  But they can't do that while still supporting earlier 1.18.y.

**Comment by cbm755** [comment]
To elaborate,I think most downstream projects would prefer to do this work once and then bump deps to `>=1.19.0`.

(But I don't petsonally mind).

**Comment by JorjMcKie** [comment]
Thanks again!
You are right: I will disable the `DeprecationWarning` until we have 1.19.0, but keep the modified `__doc__`, so people may start to see that warning.
Once there is MuPDF 1.19.0, they have another 6 month period or so get moving.
On v1.20.0, I will not change much: just no longer invoke the `restore_alias()` function in the `__init__.py`. If someone still hasn't ported his stuff, he can survive by inserting `fitz.restore_aliases()` right after the import.
