### ISSUE TITLE
More pathlib.Path troubles in `Pixmap / Page.insert_image`

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#885]
In https://gitlab.com/plom/plom/-/issues/1375 with 1.18.8, I get failures from insertImage

```
File "/usr/local/lib/python3.6/dist-packages/plom/finish/examReassembler.py", line 69, in reassemble
    pg.insertImage(rec, filename=img_name)
  File "/usr/local/lib/python3.6/dist-packages/fitz/utils.py", line 355, in insertImage
    pix = Pixmap(filename)
  File "/usr/local/lib/python3.6/dist-packages/fitz/fitz.py", line 6329, in __init__
    _fitz.Pixmap_swiginit(self, _fitz.new_Pixmap(*args))
RuntimeError: unknown image file format
```
I have not yet made a MWE but I expect the issue here is that `img_name` is a `pathlib.Path` and this is similar to #878.

@JorjMcKie I'm sorry I didn't test your `str()` workround in `fitz.open()`: if I had, my CI would've probably found this before your rolled 1.18.8 :-(

I'll do that workaround here and see if that uncovers any more (but I doubt it: this is at the very end of our CI run that this crash happens).

**Comment by cbm755** [comment]
FYI: after working around this, I did *not* find any other instances of pathlib.Path causing problems in our CI pipelines.

Maybe this is less urgent than the `fitz.open` bug?

**Comment by JorjMcKie** [comment]
Ah - the change I did in this method:
The alternatives ``filename`` and ``stream`` are now temporarily opened as Pixmaps for determining a few properties needed for the insertion. This was needed to avoid the memory leak reported in the other fixed issue. Previously, I did a ``open(filename, "rb").read()`` and used the resulting ``bytes`` object further down. The ``open()`` builtin function accepts a path-like object, whereas ``fitz.Pixmap(filename)`` **_does not_**. So path support used to be there without me being even aware of that.

So I need to adapt the Pixmap creation from filenames to support path-likes ...

And yes: using ``str(filename)`` will most probably circumvent this issue.

**Comment by JorjMcKie** [comment]
Fixed in v1.18.9 currently being uploaded.

**Comment by cbm755** [comment]
PyPI: "Release date: February 28, 2021" (*check's watch*).

Just out of curiosity, why do you set the release date in the future?  Time to line up various ducks?

**Comment by JorjMcKie** [comment]
> 
> 
> PyPI: "Release date: February 28, 2021" (_check's watch_).
> 
> Just out of curiosity, why do you set the release date in the future? Time to line up various ducks?

😂 Actually, I did not expect to get ready before that - there were several last minute things. But then was surprised how quickly these were resolved.
Also, there always is _Damokles' Sword_ of failing internet above my head, so I sort of put the very latest deadline in there.
