### ISSUE TITLE
COPYING not in PyPI sdist

### ISSUE THREAD

**Issue by jayvdb** [pymupdf/PyMuPDF#888]
PyMuPDF-1.18.8.tar.gz on PyPI doesnt contain `COPYING`, or `GNU AFFERO GPL V3`

**Comment by jayvdb** [comment]
It would also be nice to include `README.md` and the release notes if there are any.

**Comment by JorjMcKie** [comment]
Ok, that stuff will be contained in the next version.
Will also include README.md. Release notes are contained in the change log, a chapter of the documentation, which is always kept synchronous with the resp. version.

**Comment by jayvdb** [comment]
Lovely. fwiw, this arose from updating the openSUSE package https://build.opensuse.org/request/show/870215 .  The relnotes are quite detailed!

**Comment by JorjMcKie** [comment]
If it helps, I can include the relevant file (``changes.rst`` or ``changes.html``) as well, no problem.

**Comment by jayvdb** [comment]
`changes.rst` would be nice

**Comment by JorjMcKie** [comment]
So the next `tar.gz` would look like this - please review the layout so we can avoid unnecessary cycles.
[PyMuPDF-1.18.9.tar.gz](https://github.com/pymupdf/PyMuPDF/files/5944865/PyMuPDF-1.18.9.tar.gz)

**Comment by jayvdb** [comment]
That tarball is missing `COPYING` and `GNU AFFERO GPL V3` which are the most important files.

**Comment by JorjMcKie** [comment]
Oops, sorry.
My intention was actually this:
![grafik](https://user-images.githubusercontent.com/8290722/107290641-49e18d80-6a3d-11eb-9cb2-5d2a19cdb0bc.png)

`COPYING` is identical to `GNU AFFERO GPL V3`. I thought this license would be sufficient, because it is the more limiting one compared to GNU GPL.
But if you think we need both, I will switch again and include them.

**Comment by jayvdb** [comment]
Hmm.  Since this library is tightly coupled with AGPLv3+, this library is also AGPLv3+.

**Comment by JorjMcKie** [comment]
So you agree with my reasoning?

**Comment by jayvdb** [comment]
No, the opposite is true.  This library should be listed as AGPL, without any mention of GPL, and include the AGPL in the sdist.  

> COPYING is identical to GNU AFFERO GPL V3

`COPYING` is currently GPL.

**Comment by JorjMcKie** [comment]
Then what - include the file `GNU AFFERO GPL V3` and **not** include `Copying`? Don't let me guess.

**Comment by jayvdb** [comment]
I would move `GNU AFFERO GPL V3` to `COPYING`, so that GitHub knows how to find the license.  Also wherever GPL is mentioned in any docs/`setup.py`, it should instead mention AGPL instead.

**Comment by JorjMcKie** [comment]
Ok, thank you very much for help.
I will do exactly that then for the coming version.

**Comment by JorjMcKie** [comment]
Update:
You may have noticed the changes in this repository. The next version, 1.18.9, which is due during this weekend, will contain this information as part of the installation material.
As part of the new partnership with Artifex Software, they also have reviewed the license- and copyright-relevant statements of the repo and suggested respective changes, which I also have already implemented, and updated the documentation accordingly for version 1.18.9

**Comment by JorjMcKie** [comment]
Fixed in v1.18.9 currently being uploaded.

**Comment by jayvdb** [comment]
Lovely!  Submitted https://build.opensuse.org/request/show/875556 for openSUSE.

Now we need to get the license change to occur in all the other [distro packages](https://repology.org/projects/?search=pymupdf), either emailing the maintainers to advise them of the change, or creating the change requests in those systems.

**Comment by JorjMcKie** [comment]
I looked into the [distro packages](https://repology.org/projects/l/?search=pymupdf), and I am willing to mail the maintainers - if you haven't already.
But where do I find them?

**Comment by jayvdb** [comment]
There are email addresses on the three pages for pymupdf:
1. https://repology.org/project/libmupdf-pymupdf/versions
2. https://repology.org/project/pymupdf/versions
3. https://repology.org/project/python:pymupdf/version
(Repology tries to cross-link them all so they are on the same page, but doesnt always catch them all)

**Comment by JorjMcKie** [comment]
ah ok got it, thank you
will send them the information
