### ISSUE TITLE
1.18.0 - Extracted text via "rawdict" returns 'c' in 'chars' only in python 3 but not in python 2

### ISSUE THREAD

**Issue by ffc01** [pymupdf/PyMuPDF#904]
While I was testing the extracted output of a pdf from PyMuPDF I came across an issue with the extractRAWDICT() function between python 2 and python 3 in the version 1.18.0. The output of this function seems to give different results depending on the python version. The 'c' key in the 'chars' key only gets extracted/shown in python 3. Is this a bug or is this intended? Is it possible to get 'c' like this in python 2?

The code I used to extract the pdf:
```
import fitz
import datetime
import sys

doc = fitz.open(r"my_infile.pdf")
outfile = open(r"my_outfile.py")

page_1 = doc.loadPage(0).getTextPage()
output = page_1.extractRAWDICT()

print sys.version, "\n", sys.platform, "\n", fitz.__doc__

outfile.write(str(output))
outfile.close()
```

### This is the output of python 2:
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]
win32
PyMuPDF 1.18.0: Python bindings for the MuPDF 1.18.0 library.
Version date: 2020-10-06 07:15:59.
Built for Python 2.7 on win32 (64-bit).
Installation method: Wheel
```
 'bbox': (265.380615234375, 318.3802185058594, 310.9012756347656, 330.37030029296875)}, {
 'wmode': 0,
 'dir': (1.0, 0.0),
 'spans': [{
			   'origin': (342.1206970214844, 328.318603515625),
			   'color': 0,
			   'chars': [{
							 'origin': (342.1206970214844, 328.318603515625),
							 'bbox': (342.1206970214844, 318.3802185058594, 351.03680419921875, 330.37030029296875)}, {
							 'origin': (351.0606689453125, 328.318603515625),
							 'bbox': (351.0606689453125, 318.3802185058594, 356.9884948730469, 330.37030029296875)}, {
							 'origin': (356.940673828125, 328.318603515625),
							 'bbox': (356.940673828125, 318.3802185058594, 363.33160400390625, 330.37030029296875)}, {
							 'origin': (363.3006896972656, 328.318603515625),
							 'bbox': (363.3006896972656, 318.3802185058594, 369.5843811035156, 330.37030029296875)}, {
							 'origin': (369.6006774902344, 328.318603515625),
							 'bbox': (369.6006774902344, 318.3802185058594, 375.52850341796875, 330.37030029296875)}],
			   'flags': 20,
			   'bbox': (342.1206970214844, 318.3802185058594, 375.52850341796875, 330.37030029296875),
			   'font': u'Tahoma,Bold',
			   'size': 9.958598136901855}],
```

### This is the output of python 3:
3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
 win32
PyMuPDF 1.18.0: Python bindings for the MuPDF 1.18.0 library.
Version date: 2020-10-06 07:15:59.
Built for Python 3.8 on win32 (64-bit).
Installation method: Wheel

```
'wmode': 0,
'dir': (1.0, 0.0),
'bbox': (265.380615234375, 318.3802185058594, 310.9012756347656, 330.37030029296875)}, {
'spans': [{
		   'size': 9.958598136901855,
		   'flags': 20,
		   'font': 'Tahoma,Bold',
		   'color': 0,
		   'chars': [{
						 'origin': (342.1206970214844, 328.318603515625),
						 'bbox': (342.1206970214844, 318.3802185058594, 351.03680419921875, 330.37030029296875),
						 'c': 'M'}, {
						 'origin': (351.0606689453125, 328.318603515625),
						 'bbox': (351.0606689453125, 318.3802185058594, 356.9884948730469, 330.37030029296875),
						 'c': 'e'}, {
						 'origin': (356.940673828125, 328.318603515625),
						 'bbox': (356.940673828125, 318.3802185058594, 363.33160400390625, 330.37030029296875),
						 'c': 'n'}, {
						 'origin': (363.3006896972656, 328.318603515625),
						 'bbox': (363.3006896972656, 318.3802185058594, 369.5843811035156, 330.37030029296875),
						 'c': 'g'}, {
						 'origin': (369.6006774902344, 328.318603515625),
						 'bbox': (369.6006774902344, 318.3802185058594, 375.52850341796875, 330.37030029296875),
						 'c': 'e'}],
		   'origin': (342.1206970214844, 328.318603515625),
		   'bbox': (342.1206970214844, 318.3802185058594, 375.52850341796875, 330.37030029296875)}],
```

### Another question I have:
Is it possible to manipulate the output of the dictionary and on how PyMuPDF extracts the pdfs when using 'dict' (not 'rawdict')? E. g. so that I can define a value/distance that determines when and where it should interpret a new textbox/span.

Thanks in advance.

**Comment by JorjMcKie** [comment]
PyMuPDF no longer supports Python version below 3.5 since these are no longer maintained by Python itself, including `pip`, sorry.

> determines when and where it should interpret a new textbox/span.

You can specify a `clip` argument in `page.get_text` which will restrict extracted text (and images where applicable) to the `clip`-rectangle.
This applies to all `page.get_text()` option variants except "html", "xhtml" and "xml".
BTW text searching `page.search_for()` accepts the same parameter, so you can restrict search hits too.
