### ISSUE TITLE
Get bounding box of an image using xref

### ISSUE THREAD

**Issue by mohammadmjn** [pymupdf/PyMuPDF#906]
Is there any approach to get image bbox using xref or any other methods which are faster than `page.get_image_bbox(image)`? I used `page.get_image_bbox(image)` but it's slow for my use case where I have a vector PDF with a lot of small raster images (with more than 500 raster images). I have to detect the image bbox to check the size of each image with the page size to decide the whole page is a raster or vector. I also checked the xref but it gives me the actual image size that in most cases the image `width` and `height` we get from xref of the object is larger than its size in PDF (its width and height obtained from bbox). Here in my current code in which I want to replace `page.get_image_bbox(image)` with a solution based on xref or other faster alternatives to `page.get_image_bbox`:
```
def find_images_bbox(file_path):
    doc = fitz.open(path)
    page = doc[0]
    image_list = doc.get_page_images(0, full=True)
    for i in range(len(image_list)):
        image_bbox = page.get_image_bbox(image_list[i])
        print('image {} Bbox: {}'.format(i, image_bbox))
    doc.close()
```

**Comment by JorjMcKie** [comment]
You don't seem to need the xref at all, do you? Or any detail on how the page appearance **_references_** the image?
If I get you right, all you need are bbox coordinates of raster images **_actually shown_** on the page.

If this is true, I recommend you use text extraction - although this seems not to be obvious:
There is a performance oriented variant, which delivers **_text blocks_** of which every image is represented by a line of text with image metadata:
```python
pprint([b for b in page.get_text("blocks") if b[-1] == 1])  # take only image blocks
[(344.25,
  88.93597412109375,
  540.0,
  175.18597412109375,
  '<image: DeviceRGB, width 261, height 115, bpc 8>',
  0,
  1)]
```
The first 4 items of each block represent the bbox of the text block. An image block is represented by a 1 as last item.
Here is a runtime compapison for a page with 218 images:
```python
In [8]: %timeit imgs=[b for b in page.get_text("blocks") if b[-1] == 1]
22.4 ms ± 245 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
In [9]: images = doc.get_page_images(1,full=True)
In [10]: %timeit  imgs=[page.get_image_bbox(i) for i in images]
2.46 s ± 10.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [11]:
```
So you have 22.4 milliseconds versus 2.46 seconds.
Is that fast enough for you?

**Comment by JorjMcKie** [comment]
The reason why we have such an apparent functional overlap here is, that the text extraction works for **_all document_** types - not just PDFs.
So, from looking at extracted text of whatever output variant, a reference back to any PDF definition specifics is not possible.

The `doc.get_page_images()` method and friends are for PDF **_only_**. Mehod `page.get_image_bbox()` also is for PDF only. I built it for cases where a reference between the page **_object definition_** and the page **_appearance definition_** is needed.
