### ISSUE TITLE
page.draw_rect influence textwriter，caused text missing

### ISSUE THREAD

**Issue by adsfgfh4654** [pymupdf/PyMuPDF#917]
i want to translate some pdf then put the translated text on the same position
in the same time , when try drawing  some specil rect such as dashes  
fond some text missing    ,try finding error on writer，but doesn't work 
finnally，cancel the dashes parameter ，it worked
this is the  code: 
writer.fillTextbox(  # fill in above text
                fitz.Rect(fill_rect[0],fill_rect[1],fill_rect[2],fill_rect[3]+20),  # keep text inside this
                resultstring,  # the text
                align=fitz.TEXT_ALIGN_JUSTIFY,  # alignment
                warn=True,  # keep going if too much text
                fontsize=8,
                font=font,
            )
            page.draw_rect(rect=writer.text_rect,color=(0,0,1),width=0.5)
            writer.writeText(page)
            this works !
but if with parameter   page.draw_rect(rect=writer.text_rect,color=(0,0,1),width=0.5,**dashes=[3]**)
this caused some text missing

**Comment by adsfgfh4654** [comment]
![1](https://user-images.githubusercontent.com/30066186/108738410-8a2d2980-756e-11eb-8f3f-84ccd900f115.jpg)
works with no dashes

**Comment by adsfgfh4654** [comment]
![2](https://user-images.githubusercontent.com/30066186/108738509-a29d4400-756e-11eb-9d07-1ffc3c9ef8bd.jpg)
when dashes parameter added，some paragraph missing，even i draw writer.text_rect,

**Comment by adsfgfh4654** [comment]
writer.fill_textbox 's parameter  text parameter， the primary string only has one "space" along words，but it caused returnline，means only one word and one "space"  in a line

**Comment by JorjMcKie** [comment]
Cannot reproduce on my side.
Please send me a simple reproducer - I don't really understand what is going on.

**Comment by JorjMcKie** [comment]
Ah, I found an error: the dashes parameter must be a string: `dashes="[3]"`!
Should be the reason.

**Comment by JorjMcKie** [comment]
Confirmation!
If you use a list `dashes=[3]` instead of a correct string `dashes="[3] 0"`, then what is happening, is up to the PDF viewer you are using. Some viewers ignore some stuff, others show a non-dashed line, and yet others behave as you expect.

If you however execute `page.clean_contents()` when you are finished with the page, then all "illegal" specifications will be corrected ...
