### ISSUE TITLE
After adding the annotation using addFreetextAnnot , if we drag and change the position of the annotation on the pdf, the font and border colors are changing

### ISSUE THREAD

**Issue by j-sripad** [pymupdf/PyMuPDF#920]
### code
import fitz
blue  = (0.75, 1, 1)
green = (0,1,0)
red   = (1,0,0)
gold  = (1,1,0)
doc = fitz.open()
page = doc.new_page()
r1 = fitz.Rect(100,100,200,150)
t = "¡Un pequeño texto para practicar!"
a1 = page.addFreetextAnnot(r1, t, text_color=red,fill_color=blue)
a1.setBorder(width=2)
a1.update(fontsize=8, border_color=(0,0,0),text_color=red,fill_color=blue)
doc.save("a-freetext.pdf")

### Before moving the annotation
![image](https://user-images.githubusercontent.com/39008190/109050221-271ecc80-76ff-11eb-9467-3715dd4f20a9.png)

### After moving the annotation
![image](https://user-images.githubusercontent.com/39008190/109050275-3736ac00-76ff-11eb-9e4d-9796062f7446.png)

**Comment by j-sripad** [comment]
Hi @JorjMcKie 

Is this issue because of the pdf viewer  I am using?

**Comment by JorjMcKie** [comment]
> Is this issue because of the pdf viewer I am using?

I was about to ask you exactly about this.
Please see [this](https://pymupdf.readthedocs.io/en/latest/faq.html#changing-annotations-unexpected-behaviour) comment in the documentation. Every viewer or other software letting you modify annotations / fields comes with its own capabilities / features ... **_and_** limitations. There are even some differences between PyMuPDF and MuPDF here.
So if you e.g. create an annot with Acrobat and later change it with PDF XChange or Foxit, similar things will happen.
What you describe will not / should not happen if you use PyMuPDF for modification.

**Comment by j-sripad** [comment]
Got it . Thank you
