### ISSUE TITLE
insertText() has memory leak

### ISSUE THREAD

**Issue by Novak89** [pymupdf/PyMuPDF#921]
Please provide all mandatory information!

I have 20000 pdf files need to insert text, when execute insertText() in for loop on the files, memory consumed keep increasing until exhaust

Describe the bug (mandatory)
Memory leak in insertText()

**Comment by JorjMcKie** [comment]
Sorry, you left out every bit of information required for submitting a bug.

**Comment by JorjMcKie** [comment]
please resubmit the issue with the required data:
your system info, PyMuPDF version, installation method, reproducer script ...
