### ISSUE TITLE
Loop in "fill_textbox()" method

### ISSUE THREAD

**Issue by adsfgfh4654** [pymupdf/PyMuPDF#927]
text='111111111'
        
writer = fitz.TextWriter(page.rect, color=blue)  # start a text writer
        writer.fillTextbox(  # fill in above text
            fitz.Rect(0,10,300,800),  # keep text inside this
            text,  # the text
            # align=fitz.TEXT_ALIGN_JUSTIFY,  # alignment
            # warn=True,  # keep going if too much text
            fontsize=8,
            font=font,
        )
overtime，i try give the bigger rectangle ，no use . try delete some words，it works，
 i roll back to 1.18.8 it works without delete words

**Comment by adsfgfh4654** [comment]
for this i try import eventlet  to limit time

**Comment by adsfgfh4654** [comment]
font=fitz.Font(ordering=0)

**Comment by adsfgfh4654** [comment]
fitz.Rect(0,10,500,800)  in 1.18.9 works
but the text is not too long，i get English text from PDF and put other language text replace it with same rectangle，if dont limit filltext's rectangle，the text would be scaled when using "writer.writeText(page)"  ,so i need limit the rectangle and cant give it 500.

**Comment by adsfgfh4654** [comment]
![Snipaste_2021-03-02_01-42-24](https://user-images.githubusercontent.com/30066186/109536429-ad208600-7af8-11eb-9f4c-356453a44b87.jpg)
![Snipaste_2021-03-02_01-43-08](https://user-images.githubusercontent.com/30066186/109536434-af82e000-7af8-11eb-8a75-c74e3c61622f.jpg)
in the pic1，we found its a space but with too long space when writer.writeText(page)，
![Snipaste_2021-03-02_01-45-10](https://user-images.githubusercontent.com/30066186/109536658-f4a71200-7af8-11eb-82e2-194dd811cbd5.jpg)
![1](https://user-images.githubusercontent.com/30066186/109537007-5b2c3000-7af9-11eb-8eaf-2fdad125d8b5.gif)

**Comment by adsfgfh4654** [comment]
after change align=fitz.TEXT_ALIGN_LEFT, it got an return line
![Snipaste_2021-03-02_01-51-59](https://user-images.githubusercontent.com/30066186/109537582-00470880-7afa-11eb-88eb-d756c5798170.jpg)
![Snipaste_2021-03-02_01-52-19](https://user-images.githubusercontent.com/30066186/109537594-0341f900-7afa-11eb-98f2-1d437cedd085.jpg)

**Comment by JorjMcKie** [comment]
yes, there is an error in the function that splits words which are longer than the rect width.
Your text is one single word, so something goes wrong and a loop is entered.
I am debugginh this.

**Comment by JorjMcKie** [comment]
Found it:
In `utils.py` the following yellow line is missing:
![grafik](https://user-images.githubusercontent.com/8290722/109556890-c2bc8e00-7aad-11eb-92cb-e96bf3312d9f.png)
You can update this file yourself or use the attached version to replace it in your installation to test if things are working then.
[utils.zip](https://github.com/pymupdf/PyMuPDF/files/6064375/utils.zip)

The error will happen if the text contains words that are longer than 2 textbox widths.
I will prepare a hotfix.

**Comment by adsfgfh4654** [comment]
thanks a lot 
i have learned much from this lib

**Comment by JorjMcKie** [comment]
I have generated a pre-version 1.18.10.
[Here](https://github.com/pymupdf/PyMuPDF-wheels/tree/osx) are Mac OSX wheel, and [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux) Linux.
If you want a Windows version, pleae drop me a note with your Python version and bitness (32 or 64).

**Comment by JorjMcKie** [comment]
fixed in just published v1.18.10
