### ISSUE TITLE
Segmentation fault for extractDICT() but not for extractText()

### ISSUE THREAD

**Issue by versae** [pymupdf/PyMuPDF#930]
## Describe the bug (mandatory)
A normal looking PDF makes PyMuPDF to error out segmentation faults from which Python cannot recover.

## To Reproduce (mandatory)
Using the attached PDF ([segfault.pdf](https://github.com/pymupdf/PyMuPDF/files/6077357/segfault.pdf)), `extractText()`, `extractTEXT()`, `extractHTML()`, `extractXHTML()`, and `extractXML()` all work fine, whereas the rest does not (`extractBLOCKS()`, `extractWORDS()`, `extractDICT()`, `extractJSON()`, `extractRAWDICT()`, `extractRAWJSON()`):
```python
import fitz
fitz.open("segfault.pdf")
page = doc[0].get_textpage()
page.extractHTML()  # it works
page.extractDICT()  # it produces a segmentation fault
```

## Expected behavior (optional)
Since it's able to produce XML, XHTML, and HTML, I see no reason why it fails for DICT or JSON. In any case, a catchable exception would be much better than a segmentation fault. But I understand the issue might be within MuPDF itself.

## Screenshots (optional)
I tried `faulthandler` but it does not give any valuable information
```bash
Fatal Python error: Segmentation fault

Thread 0x00007fbcee0fa640 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 306 in wait
  File "/usr/lib/python3.8/threading.py", line 558 in wait
  File ".../site-packages/tqdm/_monitor.py", line 69 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fbef19a1740 (most recent call first):
  File ".../site-packages/fitz/fitz.py", line 7738 in _getNewBlockList
  File ".../site-packages/fitz/fitz.py", line 7742 in _textpage_dict
  File ".../site-packages/fitz/fitz.py", line 7826 in extractDICT
  File ".../site-packages/fitz/utils.py", line 584 in getText
  File "script.py", line 302 in get_text_fitz
  File "script.py", line 399 in get_text_from_pdf
  File ".../site-packages/joblib/parallel.py", line 262 in <listcomp>
  File ".../site-packages/joblib/parallel.py", line 262 in __call__
  File ".../site-packages/joblib/_parallel_backends.py", line 572 in __init__
  File ".../site-packages/joblib/_parallel_backends.py", line 208 in apply_async
  File ".../site-packages/joblib/parallel.py", line 777 in _dispatch
  File ".../site-packages/joblib/parallel.py", line 859 in dispatch_one_batch
  File ".../site-packages/joblib/parallel.py", line 1044 in __call__
  File "script.py", line 478 in main
  File "script.py", line 572 in <module>
Segmentation fault (core dumped)
```

## Your configuration (mandatory)
 - Ubuntu 20.10 
 - Python 3.8.6
 - PyMuPDF==1.18.8 using pip

```bash
$ python -c 'import sys; import fitz; print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)'
3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0] 
 linux 
 
PyMuPDF 1.18.8: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-02-03 19:56:11.
Built for Python 3.8 on linux (64-bit).
```

## Additional context (optional)
I am processing a few million PDFs and filtering by font family and size, but found these segmentation faults were accounting for roughly 10% of the files.

**Comment by JorjMcKie** [comment]
> But I understand the issue might be within MuPDF itself.

Not in this case - dict, rawdict, words, blocks options are my own making 😒.

Seg faults bring down the interpreter - you cannot do anything against it. Usually a non-existent memory is being used.
Let me see ...

**Comment by versae** [comment]
Thanks for the quick reply. And thanks for the awesome library, BTW!

**Comment by JorjMcKie** [comment]
A few prreliminary comments:
* you can use `blocks = page.get_text("dict", flags=0)["blocks"]` to get a list of exclusively text blocks.
* it will not extract images  - which is **_very_** beneficial for the page especially: it has over 15.000 images (!!!!), but only 71 text blocks.
* it will also avoid making a TextPage yourself - happens under the hood
* I just was successfull doing `blocks=page.get_text("dict", flags=...)["blocks"]` - with or without flags setting.

**Comment by versae** [comment]
Interesting, I sometimes get the dict returned and others a segfault. Specially I get segfaults when I run the statement twice in a row.

**Comment by JorjMcKie** [comment]
So far I am unable to reproduce. Look at the following ipython log:
```python
In [10]: blocks = page.get_text("dict")["blocks"]
In [11]: blocks = page.get_text("dict")["blocks"]
In [12]: blocks = page.get_text("dict")["blocks"]
In [13]: blocks = page.get_text("dict")["blocks"]
In [14]: %timeit blocks = page.get_text("dict")["blocks"]  # including images
2.09 s ± 12.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [15]: %timeit blocks = page.get_text("dict",flags=0)["blocks"]  # no images
667 ms ± 2.18 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [16]:
```

**Comment by JorjMcKie** [comment]
the previous was under Windows, let me repeat in Linux

**Comment by JorjMcKie** [comment]
Ok, under Linux I get a segmentation fault.
That will take a while to track down ...

**Comment by versae** [comment]
The fact that sometimes I can run it without failing and then it fails with
segfault makes me think of some sort of cached structure that it's
corrupting the memory, but that's just a guess.

--
Sent using a cell-phone, so sorry for the typos and wrong auto-corrections.

**Comment by JorjMcKie** [comment]
I think I have the reason:
In the mentioned methods, I am accessing several font properties - among them are the so-called "ascender" and "descender" values. Each of them is returned by a MuPDF function. This (inside some MuPDF function) is where we are dying.
This seems to be coincidental with the fontname being the empty string.

So, whenever I encounter an empty fontname, I do not call MuPDF to for ascender / descender values. Instead, I assume some standard values.

If doing this, the segfaults no longer occur and text extraction works fine ... except for the span values for font ascender, descender.

If you want to test a pre-version - here comes a wheel.

**Comment by JorjMcKie** [comment]
[PyMuPDF-1.18.10-cp38-cp38-linux_x86_64.whl.zip](https://github.com/pymupdf/PyMuPDF/files/6083749/PyMuPDF-1.18.10-cp38-cp38-linux_x86_64.whl.zip)

**Comment by JorjMcKie** [comment]
Next I will inspect the MuPDF code. Maybe I get a clou what is really going wrong.

**Comment by versae** [comment]
Awesome! it seems to work fine. I'll do a bit more testing and report back if I found anything.

**Comment by versae** [comment]
It seems the fix is effective in some of the PDFs that were causing segfaults previously. But for many other PDFs the error persist (see for example [segfault2.pdf](https://github.com/pymupdf/PyMuPDF/files/6084772/segfault2.pdf))

**Comment by JorjMcKie** [comment]
> in some of the PDFs that were causing segfaults previously. 

Yes I have continued testing and also found that this change is not a silver bullet!
I have done series of test with MuPDF's cli `mutool`, in order to find out if really only my stuff is suffering from this. This shouldn't be expected given that a MuPDF function causes the problem.
And indeed: `mutool -D -o test.xml -F stext segfault.pdf` produces every so often an XML file with some invalid font names. Not always an empty string, but also arbitrary crab in other cases. These other cases are the ones that are still killing me!
Mutool does not segfault, because it does not access font details other than the name - which my functions **_must_** do.

If you use the above cli command several times (requires a little patience), you can reproduce this with your original example. E.g.
![grafik](https://user-images.githubusercontent.com/8290722/109993947-34c9e880-7ce3-11eb-9810-eb43814fcdee.png)
Sometimes, things also are completely fine ...

To put a long story short: the problem is generated during `TextPage` creation: every single character in MuPDF's text page structure is like an object. One of its properties is the character's font (address), which is sometimes invalid.

There are two ways of action:
1. Send a bug report to MuPDF's issue system and see what they have to say.
2. I can try to detect whether the font character property really is a font - don't even know if this is possible: they use C, not C++, so we do not have an object type checking really ...

**Comment by JorjMcKie** [comment]
Here is another version. I built in a check, whether we do have a valid font in the character at all.
Seems to work, at least I could not break it with dozens of repetitions ...
[PyMuPDF-1.18.10-cp38-cp38-linux_x86_64.whl.zip](https://github.com/pymupdf/PyMuPDF/files/6085603/PyMuPDF-1.18.10-cp38-cp38-linux_x86_64.whl.zip)

**Comment by versae** [comment]
Thank you so much for the help, @JorjMcKie. The new wheel seems to work better, but the [segfault2.pdf](https://github.com/pymupdf/PyMuPDF/files/6084772/segfault2.pdf) file still fails every time. I'll look at opening an issue in MuPDF repo and might use part of your comments since you know better than anyone what's happening.

**Comment by JorjMcKie** [comment]
>  opening an issue in MuPDF repo

Might be a good idea. If you do that, best include segfault2.pdf and argue that `mutool -D -o test.xml -F stext segfault2.pdf` produces XML files with invalid names, and different invalid names intermittently.

**Comment by JorjMcKie** [comment]
Although they of course know me, because we have a business relationship, Artifex is not in the position to debug PyMuPDF.
Therefore, a reference to it would be misleading.

**Comment by versae** [comment]
Interestingly enough, when using `mutool draw` to convert the file to PDF again, the newly produced PDF produces no errors (although it renders in a funky way when compared to the original)
```bash
$ mutool draw -o /tmp/segfault2_p.pdf /tmp/segfault2.pdf 
warning: ICC support is not available
page /tmp/segfault2.pdf 1warning: cannot create ToUnicode mapping for UMIXOK+Calibri
warning: cannot create ToUnicode mapping for UMIXOK+Helvetica
error: only Gray, RGB, and CMYK colorspaces supported
warning: Ignoring error during interpretation
```
The errors reported might also be of value.

**Comment by JorjMcKie** [comment]
The cli command is `mutool draw -D -o test.xml -F stext segfault2.pdf`.

> Interestingly enough, when using mutool draw to convert the file to PDF again, the newly produced PDF produces no errors (although it renders in a funky way when compared to the original)

Yeah - the `ch->font`  font address of some characters is invalid = points to no font. What that implies, totally depends on which font properties are being referenced. The address bytes may point to a protected area which cannot even be read or just somewhere, which simply delivers invalid but harmless data.
The name seems to always work - that's why XML output survives and just shows meaningless names.
I however do need the ascender / descender values. These are floats - they will almost certainly let me die if being calculated from crab.

**Comment by versae** [comment]
I haven't been able to reproduce the font error with `mutool draw` neither for `segfault.pdf` nor `segfault2.pdf` :(

**Comment by JorjMcKie** [comment]
>  haven't been able to reproduce the font error with mutool draw neither for segfault.pdf nor segfault2.pdf.

It sometimes does work ok - maybe 8 out of 10 times. In the segfault.pdf case, only the first 3 font names are ever invalid.

**Comment by versae** [comment]
I haven't been able to reproduce the font error with `mutool draw` neither for `segfault.pdf` nor `segfault2.pdf`.

**Comment by versae** [comment]
I'll keep trying. After 100 runs, still don't see anything corrupted.

**Comment by versae** [comment]
I do see empty font names though.

**Comment by JorjMcKie** [comment]
> I do see empty font names though.

That is sufficient!

**Comment by versae** [comment]
Would it be possible to disable the retrieval of ascender/descender values altogether from MuPDF? I know these values are useful for calculating bounding boxes of spans and such, but if I could still get the font family and font size at the character level without ascender/descender values would still be fine by me. Maybe adding an extra flag?

**Comment by versae** [comment]
Bug open: https://bugs.ghostscript.com/show_bug.cgi?id=703649

**Comment by JorjMcKie** [comment]
> Maybe adding an extra flag?

I was thinking in that direction ...

**Comment by JorjMcKie** [comment]
YAW (yet another wheel): 
[PyMuPDF-1.18.10-cp38-cp38-linux_x86_64.whl.zip](https://github.com/pymupdf/PyMuPDF/files/6089211/PyMuPDF-1.18.10-cp38-cp38-linux_x86_64.whl.zip)

If you do `fitz.TOOLS.unset_quad_corrections(True)`, there will be no extraction of font properties ascender / descender. Instead, fix values 0.8 / -0.2 will always be returned.
Other values / properties are untouched, so you should see no impact on things like font size, text, etc. The font name is just handed through and thus may or may not be correct ...
The new option can also be reverted via the `False` argument. That value is also the default. If nothing is specified, the current setting is returned.
Good luck!

**Comment by versae** [comment]
Thanks! I'll test it right away.

**Comment by versae** [comment]
I can happily confirm that after processing 1,068,807 PDF files, not a single segmentation fault was found 🥳 A few timeouts and a set of PDFs coming out empty even though they contained text, but they represent less than 0.12% of the total (1202). So we are all good.

Thanks @JorjMcKie for all your help!

**Comment by versae** [comment]
I know the issue is closed, but quick question, will this `fitz.TOOLS.unset_quad_corrections(True)` option be available in 1.18.10?

**Comment by JorjMcKie** [comment]
>  option be available in 1.18.10?

Yes, it will become an "official" feature.

**Comment by versae** [comment]
Awesome! Thanks :)

--
Sent using a cell-phone, so sorry for the typos and wrong auto-corrections.

**Comment by versae** [comment]
Just reporting that the closed the issue as if it wasn't a bug at all: https://bugs.ghostscript.com/show_bug.cgi?id=703649#c5
