### ISSUE TITLE
Can't get text from vertical text

### ISSUE THREAD

**Issue by ShinekhuuM** [pymupdf/PyMuPDF#933]
_**Please provide all mandatory information!**_

## Describe the bug
Can't get text from vertical text

## To Reproduce
```
import fitz
import sys
import json
filename = sys.argv[1]
doc = fitz.Document(filename)
jsonFilename = filename.replace('.pdf', '.json')
json = doc[0].get_text('rawjson')
jsonFile = open(jsonFilename, "w+")
jsonFile.write(json)
jsonFile.close()
```
## Screenshots
![japanase](https://user-images.githubusercontent.com/80093708/110103257-afc4f900-7de0-11eb-95fb-77936c437f14.png)
```
{
     "spans":[],
     "wmode":1,
     "dir":[
      0.0,
      1.0
     ],
     "bbox":[
      0.0,
      0.0,
      0.0,
      0.0
     ]
    },
```

## Your configuration
 - Ubuntu 20.04.1
 - Python 3.8.5
 - PyMuPDF 1.18.9

**Comment by JorjMcKie** [comment]
provide the input file please

**Comment by laeskrad** [comment]
Here is i
[modified.pdf](https://github.com/pymupdf/PyMuPDF/files/6106552/modified.pdf)
nput

**Comment by laeskrad** [comment]
Here is input
[modified.pdf](https://github.com/pymupdf/PyMuPDF/files/6106571/modified.pdf)

**Comment by laeskrad** [comment]
> provide the input file please

Here is input
modified.pdf

**Comment by laeskrad** [comment]
> provide the input file please

Here is input
[modified.pdf](https://github.com/pymupdf/PyMuPDF/files/6106584/modified.pdf)

**Comment by JorjMcKie** [comment]
Thanks for the file.
The bug is in the file, which results in wrong character heights being reported (0).
I have implemented a correction, that enforces the character height to be at least equal to fontsize. When I then draw each character's resulting boundary box (in green), the result looks like this:
![grafik](https://user-images.githubusercontent.com/8290722/110489592-de372280-80c5-11eb-9aa7-d4f251066f2d.png)
And the text itself is correctly extracted.

**Comment by JorjMcKie** [comment]
The corrective logic will be included in the next version.

**Comment by amarbayar** [comment]
@JorjMcKie  Any ETA on when the next version is planned to roll out? :)

**Comment by JorjMcKie** [comment]
I can put a pre-version wheel in this channel if you want ...

**Comment by JorjMcKie** [comment]
@amarbayar - you have Ubuntu and Py 3.8 64bit too?

**Comment by amarbayar** [comment]
> I can put a pre-version wheel in this channel if you want ...

That would be great. 

I happened to be working on something similar and came across this issue. Ubuntu, Python 3.8.

**Comment by JorjMcKie** [comment]
well then ...
[PyMuPDF-1.18.10-cp38-cp38-linux_x86_64.whl.zip](https://github.com/pymupdf/PyMuPDF/files/6121014/PyMuPDF-1.18.10-cp38-cp38-linux_x86_64.whl.zip)

**Comment by ShinekhuuM** [comment]
@JorjMcKie ty so much
