### ISSUE TITLE
Overlapping rectangles

### ISSUE THREAD

**Issue by sebastianpawlaczyk** [pymupdf/PyMuPDF#934]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When I use drawRect I expected that coordinates for Rect correspond to the coordinate system. My problem is when I want to have two rectangles stuck together. For example:
- First Rect x0 = 40, y0 = 40, x1 = 100, y1 =100
- Second Rect x0 = 100, y0 = 100, x1 = 160, y1 =160
For this data, they are overlapping.
I know that to obtain my solution I have to add +1 to x0 and y0  for the second Rect, but it is not correct and it spoils my calculation for the whole pdf page.

![wrong](https://user-images.githubusercontent.com/35168408/110123646-729d3e80-7dc1-11eb-95ac-088777e1cbe6.png)

## To Reproduce (mandatory)
```
        rect = fitz.Rect(40, 40, 100, 100)
        color = fitz.utils.getColor("green")
        self._page.drawRect(rect, color=color, fill=color, overlay=True)

        rect = fitz.Rect(100, 100, 160, 160)
        color = fitz.utils.getColor("red")
        self._page.drawRect(rect, color=color, fill=color, overlay=True)
```

## Expected behavior (optional)
![correct](https://user-images.githubusercontent.com/35168408/110123615-674a1300-7dc1-11eb-9cce-6ab2d28b73eb.png)

## Your configuration (mandatory)
 - Windows 10
 - Python 3.7
 - PyMuPDF - 1.18.9

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
> ... expected that coordinates for Rect correspond to the coordinate system.

... which they do! This is **_not a bug_**, instead it works as designed: the rectangle's border points belong to the rectangle  - by definition. What is incorrect here?

Second, if you do not want to see rectangles overlap, then why do you draw their borders?
Using `page.draw_rect(r1, color=None, fill=(1,0,0))` will give you a picture like this:
![grafik](https://user-images.githubusercontent.com/8290722/110127678-491dec00-7d9c-11eb-9a5b-f65d4434546d.png)
Please close the issue, if you have no more questions.

**Comment by sebastianpawlaczyk** [comment]
Ok now i get it. Thanks.
