### ISSUE TITLE
Unable to select radio buttons using documented instructions

### ISSUE THREAD

**Issue by jluna** [pymupdf/PyMuPDF#943]
## Describe the bug (mandatory)
- Both the [Documentation](https://pymupdf.readthedocs.io/en/latest/widget.html#supported-widget-types) and ticket #711 state that you should be able to select a radio button by setting the `field_value` to `True`.  
- However, for the PDFs I'm working with, this does not seem to work for me. 
  - Note that the radio buttons do work when editing within an application like Adobe Acrobat.

## To Reproduce (mandatory)
```python
import fitz
import pathlib


def update_widgets(doc: fitz.Document, updates: dict):
    target_widgets = (
        w for page in doc for w in page.widgets() if w.field_name in updates
    )
    for w in target_widgets:
        update = updates[w.field_name]
        w.__dict__.update(update)
        # persist the updates to the document
        w.update()


if __name__ == "__main__":
    path = pathlib.Path("../source_pdfs/526ez.pdf")
    updates = {
        "VeteranFirstName": {"field_value": "test"},
        "prev_filed_yes": {"field_value": True},
    }
    d = fitz.Document(path)
    update_widgets(d, updates)
    d.save(pathlib.Path(f"{path.stem}_test.pdf"))
```
### Notes
- Thehe VeteransFirstName field will fill just fine, but the checkbox will not.
- I've also tried all of the other checkboxes in the document with no success.
- I also tried things, like setting the value to 1, setting the value to the "Radio Button Choice", editing the annotation direction, etc.  But no luck.

### Attached PDF
[526ez.pdf](https://github.com/pymupdf/PyMuPDF/files/6124076/526ez.pdf)

## Your configuration (mandatory)
 - Mac OS, Catalina, 64-bit
 - Python: 3.8.7 (default, Jan 24 2021, 17:47:57) \n[Clang 7.1.0 (tags/RELEASE_710/final)]
 - 'PyMuPDF 1.18.8: Python bindings for the MuPDF 1.18.0 library.'
 'Version date: 2021-02-03 19:56:11.'
 'Built for Python 3.8 on darwin (64-bit).'

**Comment by JorjMcKie** [comment]
I am unable to reproduce.
Field `prev_filed_yes` is **_properly set_** (verify via `widget.field_value`) and also **_properly displayed_** as such in PDF viewers I am using for my tests:
* Windows:
    * Adobe Acrobat
    * PDF XChange
    * MuPDF
    * Nitro PDF
    * Foxit Reader
* Linux:
    * evince

I have no MAC OSX machine, so cannot check this.
Example display with Adobe:
![grafik](https://user-images.githubusercontent.com/8290722/110924533-89c7b900-82f8-11eb-9598-95a1be2195cf.png)

**Comment by JorjMcKie** [comment]
Another one: Linux evince:
![grafik](https://user-images.githubusercontent.com/8290722/110925155-39049000-82f9-11eb-8aa8-fa0ff4d06c24.png)

**Comment by jluna** [comment]
Thank you for testing @JorjMcKie 
I noticed there's a 1.18.9 release (we're on 1.18.8) so I'll try to update.

Just as a sanity check: You used my exact same script to select the radio button and it worked?

**Comment by JorjMcKie** [comment]
Yes - just changed the pathlib to use straight filenames:
```python
import fitz


def update_widgets(doc: fitz.Document, updates: dict):
    target_widgets = (
        w for page in doc for w in page.widgets() if w.field_name in updates
    )
    for w in target_widgets:
        update = updates[w.field_name]
        w.__dict__.update(update)
        # persist the updates to the document
        w.update()


if __name__ == "__main__":
    path = "526ez.pdf"
    updates = {
        "VeteranFirstName": {"field_value": "test"},
        "prev_filed_yes": {"field_value": True},
    }
    d = fitz.Document(path)
    update_widgets(d, updates)
    d.save("test.pdf", garbage=3, deflate=True, pretty=True)
```

**Comment by JorjMcKie** [comment]
What is your take on this - did you locate the problem? Anything I can do?

**Comment by jluna** [comment]
@JorjMcKie  I was able to get this to work using the latest version (1.18.9).

The buttons don't render as selected in OSX Preview or Safari but they do render in Acrobat and other web renders (like Chrome).  Thank you again for your help!

Do you have any suggestion for how I might investigate getting these to render in OSX or Safari? I know it's not necessarily related to the project, just wondering if you have any immediate suggestions come to mind.

**Comment by JorjMcKie** [comment]
> getting these to render in OSX or Safari

Normally, a browser uses a convenient PDF viewer as plugin for showing PDF content. So chances are, that Safari (on OSX) uses the default PDF viewer on that platform.
If so, then that reduces the problem to the viewer only. Unfortunately I do not have access to an OSX machine, so I cannot look my self.
As far as I have seen in your example, the button is part of a button group: one other button is part of the same group. The purpose of any such grouping is to set off other buttons automatically, when one button is put to ON.
PyMuPDF does not currently support this feature. But you could try to simulate this behaviour and set that other button explicitly 
to `False`. Then see what happens - maybe the viewer is so picky as not accepting a `True` if it doens't see a `False` everywhere else in the group.
Just a thought.
