### ISSUE TITLE
Open file using rect button

### ISSUE THREAD

**Issue by sebastianpawlaczyk** [pymupdf/PyMuPDF#945]
**Is your feature request related to a problem? Please describe.**
Is it possible to open file(e.x excel) using rect area?
I know that hyperlink is available.

**Comment by JorjMcKie** [comment]
I do not understand, I'm afraid.
Did you mean the following:

You kow there is a link on a document page, you can extract the link text and type, and now you want to open the file associated with the link text?

**Comment by JorjMcKie** [comment]
closed for lack of reaction
