### ISSUE TITLE
Please add wheel for BigSur (macOS 11.2)

### ISSUE THREAD

**Issue by serpulga** [pymupdf/PyMuPDF#950]
Installation fails due to a missing wheel file for this platform. I can help to build and provide the file but I'm unfamiliar with the process of distributing wheels with each release.

**Comment by JorjMcKie** [comment]
Hey, that would be great! is this the same as requested [here](https://github.com/pymupdf/PyMuPDF/discussions/875)?

I am using https://travis-ci.org/ to generate Linux and Mac OSX wheels. This service puts them in dedicated branches of [this](https://github.com/pymupdf/PyMuPDF-wheels) repo.
From where I feed PyPI and the releases folder of PyMuPDF's repo.
The instructions for wheel generation are controlled by a YAML file as I am sure you know. For the mentioned request #875 and Linux ARM architectures I am using this one:
[.travis.yml.zip](https://github.com/pymupdf/PyMuPDF/files/6146966/default.travis.yml.zip)
It **_seems_** (not tested so far) to work for the Linux wheel, but it doesn't for the Macs.

So if, for example, you could help massaging the YAML file would be of great help - both for PyMuPDF as well as `cibuildwheel` (I think), which is the wheel building software I run on the Travis machines.

**Comment by serpulga** [comment]
@JorjMcKie 

Thanks, I'll look into the documentation you sent me.

I think #875 is related but specific for the M1 systems, which are the new ARM-powered Apple computers. In my case, this is a good old 86-x64 laptop.

**Comment by JorjMcKie** [comment]
> In my case, this is a good old 86-x64 laptop.

Ah, ok. Then you may be interested in the YAML file I am using normally. This one creates Python wheels for 64bit desktops on Linux and OSX:
[.travis-pages.yml.zip](https://github.com/pymupdf/PyMuPDF/files/6150377/default.travis-pages.yml.zip)

**Comment by JorjMcKie** [comment]
@serpulga - To make some progress here: what is the **_platform tag_** that would a wheel make acceptable on BigSur?

**Comment by JorjMcKie** [comment]
@serpulga - have you seen [this](https://stackoverflow.com/questions/64847996/force-usage-of-10-x-wheel-in-macos-big-sur) StackOverflow question / solution?
Looks like you can circumvent the restriction by using a special formulation of the `pip` invocation command.
If I understand the contribution on StackOverflow correctly: the important message is that the generated wheel binaries as such are perfectly usable and work on BigSur already.

**Comment by serpulga** [comment]
@JorjMcKie  Thank you for following up. I gave it a try last week but I couldn't make the build work on TravisCI. I think I'm too new at this. One thing that confused me is that I expected the build yaml files to be present in the repository, but I didn't find them.

**Comment by JorjMcKie** [comment]
> yaml files to be present in the repository, but I didn't find them.

I have them in my own fork of the repo - so I can better control when a build process is actually submitted.
Anyway: The infor I relayed to you indicates, that this is a problem of PIP: it should accept those Mac OSX wheels just like they are, because the binaries in there do work on BigSur.
But PIP contains logix that looks at the wheel **_filename_** to determine whether it is compatible. It does not look at the binary itself in anyway.
So if you follow the advice given in that StackOverflow question, you are fine with the wheels that exist.

**Comment by serpulga** [comment]
@JorjMcKie In any case, I'm good with closing this one since there is a workaround.
