### ISSUE TITLE
Replacing image/extracting text layer from pdf?

### ISSUE THREAD

**Issue by wadl-cmyk** [pymupdf/PyMuPDF#951]
I have a two layered pdf - the background layer is an image and the front layer is text obtained from an OCR engine. I need to replace the image with another while keeping the text layer the same. Or, if it is easier, extract the text layer and place it with the same coordinates on the other image. Is either of these possible with PyMuPDF? I have looked at the issue #338, in order to remove the image and place a pixmap of the new image onto the pdf. You mention that it's not possible to completely remove the image, maybe a new feature has been added since then to allow for this?

**Comment by JorjMcKie** [comment]
First, please allow me to move this issue to the ``Discussions``. This seems adequate from its nature and should also find a larger community of people looking at it.
