### ISSUE TITLE
undefined symbol: jbig2_page_out

### ISSUE THREAD

**Issue by hubutui** [pymupdf/PyMuPDF#962]
## Describe the bug (mandatory)
got import error, full log:
```text
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import fitz
  File "/usr/lib/python3.9/site-packages/fitz/__init__.py", l
ine 2, in <module>
    from fitz.fitz import *
  File "/usr/lib/python3.9/site-packages/fitz/fitz.py", line 
17, in <module>
    from . import _fitz
ImportError: /usr/lib/python3.9/site-packages/fitz/_fitz.cpyt
hon-39-x86_64-linux-gnu.so: undefined symbol: jbig2_page_out
```

## To Reproduce (mandatory)
```python
import fitz
```

## Your configuration (mandatory)
 - Operating system: ArchLinux
 - Python version: 3.9.2
 - PyMuPDF version: 1.18.9, build from the source
 - mupdf: 1.18.0
 - jbig2dec: 0.19

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

## Additional context (optional)
We build pymupdf from the source:
```bash
wget https://github.com/pymupdf/PyMuPDF/archive/1.18.9.tar.gz -O PyMuPDF-1.18.9.tar.gz
tar xfv PyMuPDF-1.18.9.tar.gz
cd PyMuPDF-1.18.9
python setup.py build
```
See also the [PKGBUILD](https://github.com/archlinuxcn/repo/blob/ccac73eb39e32c8d37c465f55862ea462e517b0d/archlinuxcn/python-pymupdf/PKGBUILD) we used for create this pkg.

**Comment by JorjMcKie** [comment]
Obviously, there is an error in how you have built MuPDF:
The https://mupdf.com/downloads/archive/mupdf-1.18.0-source.tar.gz download, from which MuPDF **_must_** have been built for PyMuPDF, contains jbig2dec version 0.18, not 0.19.
In particular, PyMuPDF does not work with the MuPDF version from the Github repository.
All MuPDF thirdparty software must be used as specified in the build description.

**Comment by hubutui** [comment]
@jbarlow83 I rebuildpkg jbig2dec 0.18 with this [PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/c1a55aab18c478c8e6f8549e4e62f2ab4403ddb8/trunk/PKGBUILD), and then rebuildpkg mupdf with this [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/1ac895bed6b4daed59332276e24f5f56a63b931a/trunk/PKGBUILD). It did not use the github mupdf source:
https://github.com/archlinux/svntogit-community/blob/1ac895bed6b4daed59332276e24f5f56a63b931a/trunk/PKGBUILD#L21
but it configured to build without bundled 3rd-party libs, but system's libs.
https://github.com/archlinux/svntogit-community/blob/1ac895bed6b4daed59332276e24f5f56a63b931a/trunk/PKGBUILD#L30-L38
then I build pymupdf 1.18.9 again, but still got the same error.

**Comment by jbarlow83** [comment]
@hubutui I'm not involved with PyMuPDF in any way at the moment. I contributed a PR or two a few years ago, that's all. I'm going to unsubscribe from this issue because I have nothing to add.

**Comment by JorjMcKie** [comment]
@hubutui - Hard to tell what is going on there. If you look at the `setup.py` file, you will see a rather complex logic, which determines the required loadlibs specification per each Linuy flavour.
This logic has been contributed by several users, each representing some Linux distribution.
I am in no position to decide or investigate, whether the `regex` in function `load_libraries` (which is used for Linux detection) is correct or not. But you will see in lines 14 thru 24, what the Archlinux library list needs to be (according to some Archlinux expert). Maybe that regex is going wrong in your case, so the list of required libraries is **_not_** correctly computed.
I would try and replace line 74

```python
        libraries=load_libraries(),
```
with

```python
        libraries= ["mupdf", "mupdf-third", "jbig2dec", "openjp2", "jpeg", "freetype", "gumbo",],
```

and see if this works. As you see, this modification will explicitely pull in jbig2dec.
If that **_does_** work, then there is a bug in the system detection logic ... probably the regex ... and some expert needs to have a look -- which is not me.

**Comment by hubutui** [comment]
@JorjMcKie  Yeah, I try your fix with 1.18.10, and it does work.

**Comment by hubutui** [comment]
> @hubutui I'm not involved with PyMuPDF in any way at the moment. I contributed a PR or two a few years ago, that's all. I'm going to unsubscribe from this issue because I have nothing to add.

sorry for that typo.

**Comment by hubutui** [comment]
maybe we could use https://distro.readthedocs.io/en/latest/ for detecting Linux distribution.
```
import distro

print(distro.id())
```

**Comment by JorjMcKie** [comment]
> distro ...

Sounds like a good idea ... **_however_** this would also mean that **_every_** Linux source installation of PyMuPDF will only work if this package is installed. Is this the case for all Linux-Python installations?
Otherwise, this is unacceptable I'm afraid.
You probably should just keep your `setup.py` version for future use.

**Comment by hubutui** [comment]
`distro` is widely available on Linux distribution. You could add it to build requirement, as it's only needed when building pymupdf from the source.

**Comment by JorjMcKie** [comment]
> add it to build requirement, as it's only needed when building pymupdf from the source

Hm, let me think about it, but it sounds good. I have been reading the relevant docu part, and I definitely do like this solution!

**Comment by JorjMcKie** [comment]
The simplest way would probably be to just try/except the distro-import. If it works, go with it, otherwise use the old logic.
This won't require making a big noise around requirements.

**Comment by JorjMcKie** [comment]
I have just uploaded an updated `setup.py`. Would be great if you could confirm that it does work for you as well.
If so, we can close the issue.

**Comment by hubutui** [comment]
ok, I figure out it.
In ArchLinux, we usually [build a pkg in a clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot), and the file `/etc/os-release` is missing. So it failed to detect distribution by reading this file.
`/etc/os-release` is generated by `systemd` in ArchLinux, it's a softlink to `/usr/lib/os-release`.
`distro` also uses the output of `lsb_release -a`.

In a word, both the old and the new way detecting distribution works for ArchLinux if I add systemd to makedepends when building pymupdf from the source.

**Comment by JorjMcKie** [comment]
close issue?
