### ISSUE TITLE
Adding tags to image

### ISSUE THREAD

**Issue by Zain-Bin-Arshad** [pymupdf/PyMuPDF#966]
I have done a lot using this package and I greatly appreciate your efforts. I want to add some `alt` text to an image. This text will be a MathML string so when any screen reader encounters an image it will check whether its has some MathML data and if yes then screen reader will read the mathematical equation.

Which API end-point should I use to achieve this. Thanks.

**Comment by JorjMcKie** [comment]
As you describe it, this is not supported in neither MuPDF nor in PyMuPDF.
Please provide an example PDF to see how that would look like - maybe there is an easy way using low-level code.
