### ISSUE TITLE
README.md installed to /usr/README.md

### ISSUE THREAD

**Issue by swt2c** [pymupdf/PyMuPDF#972]
Hi,

When installing 1.18.10 on Fedora, README.md gets installed to /usr/README.md.  Also, there's this warning from setup.py:

```
running install_data
warning: install_data: setup script did not provide a directory for 'README.md' -- installing right in '/builddir/build/BUILDROOT/python-PyMuPDF-1.18.10-1.fc35.x86_64/usr'
copying README.md -> /builddir/build/BUILDROOT/python-PyMuPDF-1.18.10-1.fc35.x86_64/usr
```

This doesn't seem like the correct location to install the README.

**Comment by JorjMcKie** [comment]
I started including files `README.md` and `changes.rst` in the source distribution based on request in #888.
Would you please coordinate with the issuer of #888, @jayvdb, what I should include and where?
I have no problem making any adjustments - as long as there is no moving target ...

**Comment by jayvdb** [comment]
On openSUSE, I just delete the installed doc files as they will be handled by `%doc` in rpmbuild.  So it doesnt matter to me where, or even if, they are installed.  I only need them to be in the sdist tarball.

**Comment by JorjMcKie** [comment]
@jayvdb  - thanks for that prompt reaction ... 
@swt2c - what do you say?

**Comment by swt2c** [comment]
I agree, I think we want the `README.md` to be in the source distribution.  I would suggest not installing it by default though.  Probably removing it from `data_files` in setup.py would be sufficient?

**Comment by JorjMcKie** [comment]
> removing it from data_files in setup.py would be sufficient?

Let me check whether `setup.py sdist` will let it survive ...

**Comment by swt2c** [comment]
I believe the recommended way for controlling what goes in sdist is to use `MANIFEST.in`:
https://packaging.python.org/guides/using-manifest-in/

**Comment by JorjMcKie** [comment]
@swt2c - thank you.
Ok, I created `MANIFEST.in` with the following contents:
```
include fitz/_config.h
include changes.rst
include README.md
include PKG-INFO
include COPYING
```
Also modified `setup.py` to use `setuptools` instead of the outdated `distutils`.
Now, `setup.py` no longer contains a `data_files` argument.
The presence of `README.md` also no longer leads to an admonition when running `python setup.py sdist`.
A `PyMuPDF.egg-info` folder is created additionally.

After all this, the `.tar.gz` file has the following layout:
```text
PyMuPDF-1.18.11.tar.gz
    PyMuPDF-1.18.11.tar
        .
        PyMuPDF-1.18.11
            fitz
                fitz.py
                fitz_wrap.c
                utils.py
                _config.h
                __init__.py
                __main__.py
            PyMuPDF.egg-info
                dependency_links.txt
                PKG-INFO
                SOURCES.txt
                top_level.txt
            changes.rst
            COPYING
            MANIFEST.in
            PKG-INFO
            README.md
            setup.cfg
            setup.py
```

**Comment by JorjMcKie** [comment]
@jayvdb / @swt2c  - please confirm you are fine with this.

**Comment by swt2c** [comment]
Looks good to me.

**Comment by JorjMcKie** [comment]
Resolved by v1.18.11 just uploaded.

**Comment by swt2c** [comment]
It seems that README.md is still in data_files, though:
https://github.com/pymupdf/PyMuPDF/blob/master/setup.py#L159

**Comment by JorjMcKie** [comment]
@swt2c - thanks, will be corrected next version.

**Comment by swt2c** [comment]
`README.md` is still included in data_files...

**Comment by JorjMcKie** [comment]
@swt2c - I have completely reworked the setup:
* There no longer are separate long descriptions in files `PKG-INFO` and `README.md`. The long description is now identical to the content of `README.md`.
* File `PKG-INFO` has gone completely. The setup generates this file internally from other information.
* `setup.py` now uses `setuptools` and no longer `distutils`.
* There is a new option to ease specifying MuPDF library locations: `setup.py` checks the presence of `os.environ["PYMUPDF-DIRS"]`. If found it assumes the value to be a filename containing JSON syntax like this:
```json
{ "include_dirs": ["filename1", "filename2"], "library_dirs": ["filename3", "filename4"]}
```
The encountered lists are then appended to the predefined ones in setup.
Hopefully this obsoletes the need to manually modify `setup.py`.
