### ISSUE TITLE
Can I extract formatted text(bold, italic, underline, strikethrough)?

### ISSUE THREAD

**Issue by we29758143** [pymupdf/PyMuPDF#981]
Can I extract formatted text(bold, italic, underline, strikethrough)?

**Comment by JorjMcKie** [comment]
No, the text properties that are available for extraction are those in the span dictionary as documented.
Bold and italics are font properties anyway.
Strikethrough, underline, etc. are not. Those are represented by annotations and have nothing to do with text.
