### ISSUE TITLE
Question about linking text to the associated widgets

### ISSUE THREAD

**Issue by sparvaneh** [pymupdf/PyMuPDF#985]
Hi,

Is there any example to show how to link widget values to the associated text? For example, I have a text "gender" and there are two radio buttons associated with "Male" and "Female". I am hoping to get advice on how to link widgets and text.

**Comment by JorjMcKie** [comment]
Please either remove the "bug" label and ask this "question" in the "Discussions" tab, or provide information mandatory for bugs.

**Comment by sparvaneh** [comment]
My bad! I am closing this ticket and will ask my question in the discussion. Thanks!

**Comment by JorjMcKie** [comment]
No problem! Thanks for the understanding.
