### ISSUE TITLE
pypi markdown rendering broken

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#998]
[1.18.10 on PyPI](https://pypi.org/project/PyMuPDF/1.18.10/) renders the readme like this:

> Release date: March 22, 2021 Authors ======= * Jorj X. McKie * Ruikai Liu Introduction ============
> PyMuPDF (current version 1.18.10) is a Python binding with support for MuPDF (current version 1.18.*),
> a lightweight PDF, XPS, and E-book viewer, renderer and toolkit ...

On 1.18.9 it [looks reasonable](https://pypi.org/project/PyMuPDF/1.18.9/).

**Comment by JorjMcKie** [comment]
I feel embarrassed - yes it looks horrible!
I am about to publish 1.18.11 which gets this straightened out. Background is I erroneously edited PKG-INFO with VS Code which nullified lines consisting of only spaces ... 😒 (if you don't configure that option off for unwanted file types ...).

**Comment by cbm755** [comment]
If that is the worst mistake you've made this month you're doing better than I!

**Comment by JorjMcKie** [comment]
Let's not deep-dive on this ... at least until we sit together over a beer.

**Comment by JorjMcKie** [comment]
The issue has just been resolved by uploading v1.18.11 sources.
The wheels are still underway to PyPI.
